### ISSUE TITLE
Set language level to Java 8

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#100]
Hi, what are the thoughts about that?
I would love to get started on Java 8 :)
Do we have any reason to stick with Java 6 (I think it is not supported anymore).
Java 8 has been released almost 1 year ago (March 2014).

**Comment by matozoid** [comment]
Just one request from someone forced to use Java 1.5 at work (aaargh!!!): carefully document which version is compiled for which Java version!

**Comment by sebastiankirsch** [comment]
I would immediately fork a java6-compatible version :/

Danny van Bruggen notifications@github.com schrieb am Wed Feb 18 2015 at
3:53:48 PM:

**Comment by ftomassetti** [comment]
mmm ok, I see, probably times are not mature :)

**Comment by sebastiankirsch** [comment]
Don't get me wrong, I really like java8. But for a library, I'd say this
cripples adoption...

Federico Tomassetti notifications@github.com schrieb am Wed Feb 18 2015
at 4:06:10 PM:

**Comment by matozoid** [comment]
Suggestion: limit the src/main code to Java 6, but let the src/test code compile with 8. Besides that: investigate if there is anything that can be done with the Java 6 code that Java 8 users can take advantage of (making it easy to use functional stuff with it, for example)

Tip: use maven-enforcer-plugin and animal-sniffer-maven-plugin to enforce Java versions.
