### ISSUE TITLE
Float literals recognized as double literals

### ISSUE THREAD

**Issue by wietlol** [javaparser/javaparser#1009]
The code "0.0f" is recognized as DoubleLiteralExpr.
This would break many things as a double is not a float.

**Comment by ftomassetti** [comment]
The documentation of `DoubleLiteralExpr` states: "A float or a double constant. This value is stored exactly as found in the source.". So it means that the user has the responsibility of looking at the text and check if it ends with an "f" or not.

I would agree this could be improved.

**Comment by ftomassetti** [comment]
What we could do is:

- create FloatLiteralExpr in version 4
- add the methods `isFloat` and `isDouble` to DoubleLiteralExpr in version 3

@matozoid what do you think?

**Comment by wietlol** [comment]
I prefer consistency above anything else...
I assume IntegerLiteralExpr vs LongLiteralExpr is a similar situation

**Comment by matozoid** [comment]
Thanks! It's a duplicate though: #664. The idea is to release it in version 4, but if it is really in the way we could put this change on a branch, and you could use that version?

**Comment by matozoid** [comment]
@wietlol - I'm going to close this and keep #664 open.
