### ISSUE TITLE
Grammar for float literals

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1024]
Why is this expressed in this way?
```
  < #DECIMAL_FLOATING_POINT_LITERAL:
        (<DECIMAL_LITERAL>)+ "." (<DECIMAL_LITERAL>)* (<DECIMAL_EXPONENT>)? (["f","F","d","D"])?
      | "." (<DECIMAL_LITERAL>)+ (<DECIMAL_EXPONENT>)? (["f","F","d","D"])?
      | (<DECIMAL_LITERAL>)+ <DECIMAL_EXPONENT> (["f","F","d","D"])?
      | (<DECIMAL_LITERAL>)+ (<DECIMAL_EXPONENT>)? ["f","F","d","D"]
  >
```

I do not understand the "+" and "*" followin the DECIMAL_LITERAL, because DECIMAL_LITERAL should represent already a sequence of digits, not just one digit.

**Comment by matozoid** [comment]
Stop it with all the grammar bugs already :-D

**Comment by ftomassetti** [comment]
As soon as you stop with the comments bugs :D
Anyway I am not sure it is really a bug because it works anyway, but I thought it was the case to look into this and clarify
