### ISSUE TITLE
Support for Java 8 and 9 ....Just a question

### ISSUE THREAD

**Issue by sourabhsparkala** [javaparser/javaparser#1027]
Hello,

I have some projects built with Java8 features. Hence I was wondering if there is support for Java8 in place? Will JavaParser handle the Java8 implemented projects

Will this support Java9 as well?

Regards
Sourabh

**Comment by ftomassetti** [comment]
It has been supporting Java 8 for years (I think it is reported very clearly in the homepage of this project) and since some months supports Java 9 as well
