### ISSUE TITLE
Insert new nodes while traversing through AST using TreeVisitor

### ISSUE THREAD

**Issue by sourabhsparkala** [javaparser/javaparser#1029]
Could you please help me with TreeVisitor Abstract class. I am running a preorder tree traversal, and I am visiting each node. Say, I reach a respective node, I want to insert new nodes 'Before' and 'After' the respective node. Sometimes, the inserting node may be a 'Statement' or a 'Comment'. Is there a way to to do that? or is there some other awesome class already implemented for doing simple mutations to AST like insert new node, delete node, replace node? Any example snippet on how to achieve this or a starting point would help me a lot and it would be very much appreciated. I am new to java, hence I am not sure how this works.

To parse through a Java file

I find a statement
int i =0; 

This can be a **VariableDeclarator enclosed in a method** or **FieldDeclaration enclosed in a class** but ultimately considered as a node in AST.

I want to update the Tree by adding the new statement as a node before and after the respective node in AST

Like given below:

int j = 10;
int i = 0;
int k = 20;

public class TreeVisitorAdapter extends TreeVisitor{
	@Override
	public void process(Node node) {
		node.add(JavaParser.parse())
        }

insertStatementAtPos() is something I want to avoid, even if this is possible.

Could you please give me a hint on how to achieve this when I am traversing through the AST?

Regards
Sourabh

**Comment by matozoid** [comment]
Would you be helped with (not yet existing) methods `NodeList.insertBefore(Node)` and `NodeList.insertAfter(Node)`? Or maybe the more complex to implement `some_node.insertBeforeXxx(Xxx)` and `some_node.insertAfterXxx(Xxx)` where `Xxx` is something like `Statement` or `ImportDeclaration` ?

**Comment by sourabhsparkala** [comment]
Hello @matozoid  ,

Thank you for the reply. 

I was thinking something more like 

1. some_node.insertBefore(some_other_node), some_node.insertAdfter(some_other_node), here the node could be anything, say some_other_node is a FieldDeclaration (int i = 0) and some_node is new BlockComment()

2. I observed that, the Node.getChildNodes() returns an unmodifiableList List<Node>, if you could implement a return of modifiableList, it has the List<Node>.add(int index, Node node), which could be used to serve the same purpose above and it would be less change.

My only concern is on inserting new nodes would the parsing go into a recursive loop?
Please correct me if I am wrong.

Right now I am trying out something like this, by modifying the Node.getChildNodes() List<Node> to modifiable list

```java
//The input file
public class App 
{
	int a,b=0;
	public int main()
	{
		int i,b =0;
		System.out.println("Hello world");
		return 0;
	}
}
```

```java
//The treeVisitor abstract :
new TreeVisitor() {
			int count = 0;
			
			@Override
			public void process(Node node) {
				String startString = " " + ++count + " [ ";
				String stopString = " ] " + count + " ";
				if(!node.toString().trim().matches("\\/\\* \\d+ \\[ \\*\\/") && !node.toString().trim().matches("\\/\\* \\] \\d+ \\*\\/")){
					nodeList.add(startString);
					nodeList.add(stopString);
					node.getParentNodeForChildren().getChildNodes().add(0, new BlockComment(startString));
					node.getParentNodeForChildren().getChildNodes().add(new BlockComment(stopString));
				} else {
					count--;
				}
			}
		}.visitPreOrder(cu);
System.out.println("-Output \n"+ cu.toString());
```

```java
//The output is coming as 
public class App2 {

    int a, b = 0;

    public int main() {
        /* 15 [ */
        int i, b = 0;
        System/* ] 28 */
        .out.println("Hello world");
        return 0;
    /* ] 15 */
    }
    /* ] 2 */
}
/* ] 1 */
```

By debug, I can verify that the first BlockComment with index 0 as the childNode position is added to the childnodes. But why is it not getting displayed properly in the output of cu. Is this because of cu.toString()?

Regards
Sourabh

**Comment by matozoid** [comment]
Ooh, that list is immutable for a reason - it's pretty complex to keep it up to date correctly, and inserting something into that list is pretty much meaningless. What would it mean to insert a second `Name` into a type declaration? Does it have two names now? If I insert a node of a type that is not allowed to be a child, what do we do? If I delete a child node that is a required field, uh, please no!

`cu.toString()` uses the PrettyPrintVisitor, which uses the field getters. The fields of a node are not updated when its child node list is changed because that is, as seen above, not how the design works.

**Comment by matozoid** [comment]
Okay, what is the actual use case? I see you adding comments here and there. You're adding comments about something?

Note that comment support is iffy - we're going to rework that for 4.0: https://github.com/javaparser/javaparser/issues/638

**Comment by sourabhsparkala** [comment]
@matozoid , thank you for the insight. I understand the challenges involved.

1. I am using TreeVisitor to traverse through each node of the AST  from the parsed .java file and annotate an identifier
2. I am trying to surround the respective node with an identifier, as a blockComment
3.  
```java
int main(){
          return 0;
     }
```

4. The output will be
```java
  /*1 [*/
/*2 [*/ /*3 [ */ int main /*] 3 */ () /*] 2 */
/*4 [*/
{
       /*5 [*/ /*6 [ */return/* ] 6 */ /*7 [*/ 0 /* ] 7 */; /* ] 5 */
}
/* ] 4 */
/*]1 */
```
4. From the above Identified annotated list of nodes : I want to swap the nodes NodeId 3 wih NodeId 5
5. The output would be 
```java
 return 0 (){
          int main;
     }
```
6. In order to achieve this, I would need a way to re-position and alter the nodes. 

Your advice on how I can approach this, would be really helpful. I do't mind the compilation issue, as I am trying to implement static analysis on the altered codes.

**Comment by matozoid** [comment]
Right, I was trying to work on this, it is a good test case for the new API for modifying the token list. Little problem: the API isn't there yet :-)

Here is the idea: if you add comments to the AST like you do, you run into all the problems described in #638. There is just no way to represent every kind of comment in the AST. Therefore we should look a level lower: the token list. This would look something like `IDENTIFIER "int", WHITESPACE " ", IDENTIFIER "main", LEFT_BRACE "("` etc. This is the natural place to manipulate comments. So if we find the node you want to put comments around, we take the `TokenRange` that belongs to it, take the `begin` token, put a new comment token before it, take the `end` token and put a new comment after it.

But, the API isn't finished and we can't manipulate the list yet. I'll give it priority and hope to finish it before the weekend :-)

**Comment by matozoid** [comment]
You can follow my progress over here: https://github.com/matozoid/javaparser/blob/issue_1005_cursor_api/javaparser-core/src/main/java/tmp/Issue1029.java

**Comment by matozoid** [comment]
Okay, in version 3.3.1, this will get you the comments you want inserted:
```java
package tmp;

import com.github.javaparser.JavaParser;
import com.github.javaparser.JavaToken;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ParseStart;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.visitor.TreeVisitor;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;
import com.github.javaparser.utils.Pair;

import static com.github.javaparser.GeneratedJavaParserConstants.MULTI_LINE_COMMENT;
import static com.github.javaparser.Providers.provider;
import static com.github.javaparser.utils.Utils.EOL;

public class Issue1029 {
    public static void main(String[] args) {
        final BodyDeclaration<?> mainMethod = JavaParser.parseBodyDeclaration("int main(){" + EOL +
                "          return 0;" + EOL +
                "     }");

        new TreeVisitor() {
            int count = 0;

            @Override
            public void process(Node node) {
                node.getTokenRange().ifPresent(r -> {
                    count++;
                    JavaToken startComment = new JavaToken(MULTI_LINE_COMMENT, "/* " + count + " [ */");
                    JavaToken endComment = new JavaToken(MULTI_LINE_COMMENT, "/* ] " + count + " */");
                    // ???
                    // Go to the beginning of the node in the token list, and insert the start comment there.
                    r.getBegin().insert(startComment);
                    // Go to the end of the node in the token list, and insert the end comment after it.
                    r.getEnd().insertAfter(endComment);
                    // Update the node's token range to include these comments.
                    // (Otherwise tokenRange.toString misses the first and last comment)
                    node.setTokenRange(r.withBegin(startComment).withEnd(endComment));
                });
            }
        }.visitPreOrder(mainMethod);

        mainMethod.getTokenRange().ifPresent(System.out::println);
    }
}
```

**Comment by matozoid** [comment]
For the next step I need more info. In your comment you say "I want to swap node 3 and 5" - why did you take 3 and 5? Is it the intention to replace the method name with the return value? What would happen when the return value is a complex expression like ` return (10+5)*100;`?

**Comment by sourabhsparkala** [comment]
@matozoid Thank you so much for this implementation.

I am trying to develop a wrapper around javaparser, which would provide me with the code elements;

Also the wrapper would expose APIs for mutations of the code with operations like delete, swap, insert node elements of the AST. As mentioned **3 and 5 are identifiers of individual code node elements and the selection is random**  

1. delete element 3, would delete the node with /* int main */
2. insert "System.out.println("Test")" Above/Below node 5 element, would insert the println() statement above/below the node element 5.

Hence, I was thinking of 

1. getParent() of each node and assign new Parent for swapping.
2. Delete a node would be make the parentNode() as null.
3. Insert a node, would be to make the existing node as ParentNode(), but the position would matter, which I can use insertAtPos() w.r.t body of the method.

What do you think, is this the right way to do it?

Your insight would be appreciated.

Regards
Sourabh

**Comment by matozoid** [comment]
If you really want to be able to replace any kind of node with any kind of node, then JavaParser's nodes will not help. There are many protections against creating an invalid AST in it.

To have a clean solution will be quite a bit of (mostly boring) work, I suggest writing a visitor that will copy each node to your own custom kind of node. You can design this node to do whatever you like. Maybe you can borrow code from PrettyPrintVisitor to print these nodes.

(If you don't want to have a lot of repetitive work when creating that visitor, you could look at how JP generates its visitors in here https://github.com/javaparser/javaparser/tree/master/javaparser-core-generators/src/main/java/com/github/javaparser/generator/core/visitor )

There is an issue for this on the backlog, but it is quite some work and not high priority: #968

**Comment by matozoid** [comment]
Assuming this is answered.

**Comment by Sigurthorb** [comment]
@matozoid I am also interested in this.

I have created a list of nodes that I want to insert code before.
This code could be comments or code statements.
The current version that I have is 3.5.10.

I tried your code example on 3.3.1 but Position did not include the `insert` nor `insertAfter`

```
Position pos = node.getBegin().orElse(null);
pos.insert() // Error: Cannot resolve method 'insert()'
```

This list I have only includes statements within method for example
```
    public static String test(List<String> stringList, int length){
        int a = 0;
        if(stringList.size() == length){
            System.out.println("Hello World!");
            return "true";
        }
        else{
            System.out.println("Hello World!");
            return "false";
        }
    }
```

My list includes the following nodes:

```
int a = 0;
System.out.println("Hello World!");
return "true";
System.out.println("Hello World!");
return "false";
```

I would like to be able to loop through the statements in the list and prepend my code at every line.

Is something like this possible?

**Comment by matozoid** [comment]
@Sigurthorb - yes it is. If you look at [MethodDeclaration](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.5.10/com/github/javaparser/ast/body/MethodDeclaration.html) has a body which is a `BlockStmt`, and that contains a list of statement that you can modify as you desire.

Note that comment support is currently imperfect. The best way to have a comment is to set it on a statement (or method, or class.) Multiple comments following each other may give trouble.

**Comment by Sigurthorb** [comment]
Thank you, I was able to use this
