### ISSUE TITLE
Provide a way to configure SourceRoot to not output "Parsing <file name>"

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1039]

**Comment by jimshowalter** [comment]
There are several places in that class where a call is made to Log.info("Parsing etc.

**Comment by jimshowalter** [comment]
Finals also get in the way of testing tools like Mockito (v1, not v2).

**Comment by ftomassetti** [comment]
Note that you can use `Log.setAdapter` to specify a `Log.Adapter` that reacts to info by doing nothing. Would that solve your issue?

**Comment by matozoid** [comment]
I think this was the answer.
