### ISSUE TITLE
Typo in parameter name in SourceRoot.parse(String packag, String filename)

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1040]
Should be "package".

**Comment by ftomassetti** [comment]
It cannot be package because that is a keyword in Java. For this reason we had to change it to something else.

**Comment by jimshowalter** [comment]
Yes, that is correct. However, the current choice *looks* like a typo.

The convention for "class" when it's not a .class is clazz. Perhaps you can think of a clever scheme for "package" that's similar?

Or perhaps "aPackage", "thePackage"?

Or at least a comment?

**Comment by matozoid** [comment]
We went for the clever scheme of leaving the final "e" off :-) I've seen people use underscores, but ugh :-(

**Comment by matozoid** [comment]
Well, I was editing the file anyway, and it looked like we were mixing `packag` and `pkg` so I made all of it `pkg` now.

**Comment by jimshowalter** [comment]
Nice!

**Comment by jimshowalter** [comment]
Somebody asked Thompson (or maybe it was Ritchie) if he'd change anything in the API if he had a chance (years after he helped write Unix). He said he wished he'd called it "create" instead of "creat".
