### ISSUE TITLE
Maven coordinates are out of date in Getting Started section of javaparser.org site

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1041]
http://javaparser.org/gettingstarted.html

Ideally the site would read the latest coordinates from github. Or you could just link to the pom and not post the coordinates there (but that doesn't help with the Gradle section).

**Comment by matozoid** [comment]
https://github.com/javaparser/javaparser-website/issues/14

**Comment by matozoid** [comment]
This is fixed (for this week ;) ) Thanks for reporting!
