### ISSUE TITLE
Add info to the ebook ordering page explaining how to get the complete version after buying the incomplete version

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1043]
Or, if that won't be possible, add a note to that effect (but that will kill sales, so hopefully it's going to be possible).

https://leanpub.com/javaparservisited

**Comment by ftomassetti** [comment]
It is definitely possible: you will just have access to the new version on LeanPub. Authors can also email you to let you know about the new version, if you leave your email to LeanPub (it would not be visible to authors).

**Comment by matozoid** [comment]
@ftomassetti should we state it explicitly somewhere?

**Comment by jimshowalter** [comment]
Yes, you should state it explicitly on the ordering page. Would clear up a
lot of confusion. I suspected it was upgradeable, but didn't want to part
with $15 on spec.

On Mon, Aug 14, 2017 at 1:38 AM, Danny van Bruggen <notifications@github.com

**Comment by matozoid** [comment]
Moved it to the correct project.
