### ISSUE TITLE
Make root member variable protected instead of private in SourceRoot

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1045]
I'm subclassing SourceRoot to create a version locally that doesn't output Log.info("Parsing for every file. I can assign Path root locally, or call getRoot(), but if it was protected my subclass could access it directly.

**Comment by jimshowalter** [comment]
Also make methods protected instead of private. Subclassing and overriding public SourceRoot parse(String startPackage, JavaParser javaParser, Callback callback) throws IOException fails because the save method is private.

**Comment by ftomassetti** [comment]
This is an example of the fact that designing classes to be subclasses is not as simple as removing the final keyword :)

**Comment by matozoid** [comment]
Take a look at https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/utils/Log.java

You can use `Log.setAdapter` to an implementation that does nothing.

**Comment by jimshowalter** [comment]
Apologies--I didn't realize you'd written your own. This gives good control over logging, and means this can be closed. Thank you!
