### ISSUE TITLE
Test failures in javaparser

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1047]
Tried building javaparser and got a test failure:
Failed tests: removeAllOnRequiredProperty(com.github.javaparser.ast.NodeTest): expected:<class X {[(..)
testSimplePropertyWithGenericReplace(com.github.javaparser.ast.ReplaceNodeTest): expected:<package z;[(..)
testListProperty(com.github.javaparser.ast.ReplaceNodeTest): expected:<package x;[(..)

I'm on Windows 10. Is it possible the tests assume a Linux-style OS and file system?

**Comment by matozoid** [comment]
They shouldn't, but they do. This has been one the backlog for quite a while because none of our contributors seem to be working on Windows. See also #713

**Comment by jimshowalter** [comment]
I can try to fix them.

**Comment by matozoid** [comment]
Do try to fix them the right way, like described in #713 :-)
