### ISSUE TITLE
Maven warning in javaparser-visited

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1048]
[WARNING] Some problems were encountered while building the effective model for com.github.javaparser:javaparser-book:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21

**Comment by SmiddyPence** [comment]
https://github.com/javaparser/javaparser-visited/issues/1

Resolved.
