### ISSUE TITLE
No Maven build for javasymbolsolver

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1049]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.078 s
[INFO] Finished at: 2017-08-13T20:19:52-07:00
[INFO] Final Memory: 14M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\git\javasymbolsolver). Please verify you invoked Maven from the correct directory.

**Comment by ftomassetti** [comment]
If this is an error related to the javasymbolsolver you should [open a ticket in the javasymbolsolver project](https://github.com/javaparser/javasymbolsolver/issues/new).

That said, JSS uses gradle, not maven. It is possible to generate a pom using a gradle task but the build system is gradle.

**Comment by matozoid** [comment]
@ftomassetti I found gradle to be incredibly confusing to get started with - is there a page with build instructions?

**Comment by ftomassetti** [comment]
I think the main issue is the usage of Groovy, at least for me. I agree that it takes some time to learn how to write it, however for just using it to build a project you can run:

`./gradlew compile`

**Comment by ftomassetti** [comment]
Should we list the main tasks to be used in the README?

**Comment by jimshowalter** [comment]
Why would you have two projects, ostensibly targeting the same general outcome, using two different build systems? The more polyglot, the more confusing. Plus, Gradle is the latest ant. It's not declarative. It's scripted. Which means you can't write programs that reason about the build system, unless you parse the scripts. It seems to be the revenge of the Maven-haters.

**Comment by ftomassetti** [comment]
We have two build system because JSS was born as an external project and later moved under the JavaParser umbrella. I understand you do not like Gradle, I have a different opinion. I prefer it to Maven and I find it more powerful. From the point of view of the user it does not make a difference, the only difference is for persons who contribute to JSS. So far no contributors to JSS had an issue with Gradle.

**Comment by jimshowalter** [comment]
That's fine. Your perogative. It just means you'll never get a pull request from me.

**Comment by matozoid** [comment]
There are (distant) plans to merge everything, that will make the whole discussion moot.

**Comment by matozoid** [comment]
(Give Gradle a try someday, by the way. Pretty nice stuff once it runs)

**Comment by jimshowalter** [comment]
I'll look at it. Incremental compilation would be useful on our project. What bugs me about Gradle is that nearly every Java project has been set up to use Maven for over a decade, including all of org.apache. Tools expect Maven to be there. Developers expect Maven to be there. Along comes a new build system, which is fine--technology evolves. But unless Gradle conquers the world, we're going to wind up with some projects using Maven and others using Gradle, and we're back to oh-I-prefer-ant vs. oh-I-prefer-bash, and projects won't interoperate (again).

**Comment by matozoid** [comment]
True, and I don't see the companies I work for moving to Gradle.

Anyway, open this issue on https://github.com/javaparser/javasymbolsolver if you would like to push @ftomassetti a little more ;-)

**Comment by jimshowalter** [comment]
You merged the projects--congratulations!
