### ISSUE TITLE
Differentiate "radical" and "composite" expressions

### ISSUE THREAD

**Issue by lodart** [javaparser/javaparser#1053]
As I was working working on my internship project, I realised I had to manipulate differently "radical" expressions (ie, expressions that have no child Expression, like `NameExpr`, or `LiteralExpr`) and "composite" expressions (like `a+b` or `a.append(b)`).

Maybe there could be a way to differentiate those with an Interface ? I don't know if it would be really useful, but I thought that if I would need it, maybe others would too :)

Thank you :)

**Comment by ftomassetti** [comment]
I think 1/2 marker interface(s) could make sense. Like BasicExpression/ElementExpression and CompositeExpression

**Comment by matozoid** [comment]
If I hear marker interface I think annotations. Not sure what's the best since we use interfaces royally already, so maybe not deviate from that.

**Comment by matozoid** [comment]
For now: you could inspect the meta model for the node

**Comment by lodart** [comment]
Thank you for this :) Actually, for now, I'm doing things like 

	if (expr instanceof NameExpr){...}
	if (expr instanceof MethodCallExpr){...}
	...
but I don't know if it is a good way :/

**Comment by matozoid** [comment]
Try calling getMetaModel on the node you are looking at :)

**Comment by lodart** [comment]
Oh right, I can get its type from here :) Thank's a lot !

**Comment by matozoid** [comment]
Okay, I see now that I didn't really understand the question. Can you explain how I could figure out by looking at the properties of a node if it is complex or not?

**Comment by lodart** [comment]
Well, I know I can do it already, for instance by looking `if (expression.getChildNodesByType(Expression.class).size()  > 0)` but I thought maybe there could be a cleaner way to do it ?
I hope I'm not being obvious ^^ And if you think that is not worth it adding something to the project / confusing, that is okay too :)

**Comment by matozoid** [comment]
So the definition is "a complex node is one that has one or more children of type Expression"? What about node types that take an optional expression - is it sometimes complex, sometimes not?

**Comment by lodart** [comment]
This definition seems fine to me. But, I didn't think of optional expressions :/ (Just to be sure, for example : `VariableDeclarationExpr` has some `VariableDeclarator` that may, or may not have an initializer `Expression`, right ? ). 
I guess they are sometimes complex, and sometimes not, so in that case, I don't think there is a point modifying the library...

Well at least, I really increase my knowledge about grammar and syntax, by using Javaparser, so thank you a lot, guys ! (I wish I'd done that before my exams...)

**Comment by matozoid** [comment]
Hahaha, good luck! :-)
