### ISSUE TITLE
Missing finals in method signatures in VoidVisitorAdapter

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1055]
All of the methods appear to be generated, so fixing these in the generator will fix these.

	public void visit(SimpleName n, A arg) {
	public void visit(ArrayType n, A arg) {
	public void visit(ArrayCreationLevel n, A arg) {
	public void visit(NodeList n, A arg) {
	public void visit(ModuleDeclaration n, A arg) {
	public void visit(ModuleRequiresStmt n, A arg) {
	public void visit(ModuleExportsStmt n, A arg) {
	public void visit(ModuleProvidesStmt n, A arg) {
	public void visit(ModuleUsesStmt n, A arg) {
	public void visit(ModuleOpensStmt n, A arg) {
	public void visit(UnparsableStmt n, A arg) {

Ran into these when I started with the VoidVisitorAdapter, grep -v'd the @Generated and "n." calls, and replaced the }s with:

    super.visit(n, arg);
}

and then replaced final A arg with final Void arg. These didn't replace because they didn't match final.

**Comment by matozoid** [comment]
Will be in the next release. Thanks!
