### ISSUE TITLE
Can you use <?> to get rid of the raw type warning for this signature?

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1056]
VoidVisitorAdapter.public void visit(NodeList n, final A arg) {

**Comment by matozoid** [comment]
I tried a lot of things there, but didn't succeed. If there is a way, I don't know it.

**Comment by jimshowalter** [comment]
You can't add <?> in the base and propagate that down the inheritance?

**Comment by matozoid** [comment]
I can't remember what exactly the problems were, but I know I tried everything I could. So unless someone contributes a fix it will stay this way.

**Comment by matozoid** [comment]
Did you experiment with this? Do you hate Java yet? ;-)

**Comment by jimshowalter** [comment]
I haven't tried it yet.

**Comment by matozoid** [comment]
It would be nice if there was some kind of fix, because I wasn't too happy with this solution :-)

**Comment by ryan-beckett** [comment]
@matozoid: Were these testing problems? Changing the current code to:

`VoidVisitor.void visit(NodeList<?> n, A arg);`
`VoidVisitorAdapter.public void visit(NodeList<?> n, A arg)`

causes no compilation issues.
