### ISSUE TITLE
VisitorMap duplicates keys for same object. 

### ISSUE THREAD

**Issue by lodart** [javaparser/javaparser#1065]
Before, different objects were considered the same key, but thanks to your  VisitorMap, @matozoid, this is no longer the case. The problem is that now, even the same objects produces several keys ! 
If I take your Test example : 
```java
CompilationUnit x1 = JavaParser.parse("class X{}");
Map<CompilationUnit, Integer> normalMap = new VisitorMap<>(new HashMap<>(), new ObjectIdentityHashCodeVisitor(), new ObjectIdentityEqualsVisitor());
normalMap.put(x1, 1);
normalMap.put(x1, 2);
System.out.println(x1 == x1);
System.out.println(normalMap.size());
System.out.println(normalMap.get(x1));
```
it returns : 
```
true
2
null
```

**Comment by lodart** [comment]
In both `ObjectIdentityHashCodeVisitor` and `ObjectIdentityEqualsVisitor`, there doesn't seem to be a `visit` method for `Expression`s

**Comment by matozoid** [comment]
Okay, problem found. It will be in next weekend's release, or you can copy `VisitorMap.java` to your own project to get it now :-)

**Comment by lodart** [comment]
Thank's, but I think there is still a problem :/ `System.out.println(normalMap.get(x1));` still returns me `null` ...
I think you forgot  to change 
```java
public V get(Object key) { return (V) innerMap.get(key) }
```
to
```java
public V get(Object key){return (V) innerMap.get(new EqualsHashcodeOverridingFacade((N) key));}
```
`containsKey(Object)` is also still bugged.

**Comment by matozoid** [comment]
I'm sorry for putting this thing together so quickly, this is a little embarrassing. Would you be interested in building a PR for this so it is correct right away? :-)

**Comment by lodart** [comment]
I'm on it ! This will be my first PR ever, so be indulgent ;)

**Comment by matozoid** [comment]
You can now put "contributed to an open source project" on your resume ;-)

**Comment by matozoid** [comment]
So do you think we're done with this issue?
