### ISSUE TITLE
Annotations on types are not parsed and dumped correctly

### ISSUE THREAD

**Issue by ptitjes** [javaparser/javaparser#107]
See failing test case:
https://github.com/ptitjes/javaparser/commit/beffe836060823820eed0c4e2fcdac99545a0486

```
@Target(ElementType.TYPE_USE)
@interface Ann1 {
}

@Target(ElementType.TYPE_USE)
@interface Ann2 {
}

class B {
    class C {
    }

    class A extends @Ann1 B.@Ann2 C {
    }
}
```

is valid Java 8 code.

It parses as :

```
class A extends @Ann1 B.C {
}
```

and if you instanciate the ast manually, when dumped it produces

```
class A extends @Ann2 @Ann1 B.C {
}
```

**Comment by ptitjes** [comment]
https://github.com/ptitjes/javaparser/tree/zz-issue-107

**Comment by ptitjes** [comment]
If everyone is OK with that, I add this to 3.0 milestone.

**Comment by ftomassetti** [comment]
Hi @ptitjes . Do you have a patch for this? Do you want to still contribute one or do you prefer not to because of the license change?

**Comment by ptitjes** [comment]
Well, I don't mind helping users and give some advises from time to time when I can, but I won't contribute code because of the license change and because I prefer to use my spare time for JLaTo...

The stuff in the '3.0 type hierarchy...' contains nothing spectacular and you can easily do something similar by yourself. And BTW it has a big performance problem because of the way the lookahead is done currently for cast expressions in JavaParser.
