### ISSUE TITLE
Parse java files from a zip or jar

### ISSUE THREAD

**Issue by RedBlackTreei** [javaparser/javaparser#1079]
for example I have a jar called `commons-collections4-4.1-sources.jar`, How can I get the classes and methods, I have read the wiki, but I  didn't find anything about this.

In addition, does javaparser support fuzzy matching like eclipse or IDEA(eg. *Facade)

**Comment by matozoid** [comment]
- this parser parses source files only. Maybe you want https://github.com/javaparser/javasymbolsolver ?
- that's functionality for you to build, it's not the job of a parser, or maybe there is something in (see previous question)

**Comment by ryan-beckett** [comment]
@Matozoid: Does adding JAR support into the source root sound like something worthwhile?

**Comment by matozoid** [comment]
@ryan-beckett well, what would it do? JP's task is to parse java files, and `SourceRoot` is built for one thing: look at source files under a root directory.

**Comment by ryan-beckett** [comment]
It would extract the files then parse through them, but then does **saveAll()** write source back to its file then zip the files? It's stuff like that's kind of hassling when thinking about the API in my opinion. Whatever, I just want your thoughts. There are other things I can work on.

**Comment by matozoid** [comment]
Oh right, I completely missed that we're talking about a jar of source files! Sorry!

Here's what I wrote to do the test of the full openjdk source code (which disappeared, so it's not working right now) - https://github.com/javaparser/javaparser/blob/master/javaparser-testing/src/test/java/com/github/javaparser/manual/BulkParseTest.java

A bit disappointing maybe that I just unzip the whole thing, then go through the extracted files with `SourceRoot`. Hmmm, I guess you could mess with that unzip method to make it pass every inputstream directly to a `JavaParser` instance so we don't need a temporary file on disk... That does sound rather cool, doesn't it?

If `SourceRoot` is a root directory for source files, would `SourceJar` or `SourceZip` or `SourceArchive` be the same thing for an archive with source code? Where we only support reading with a callback? Sounds like a fun project.

**Comment by ryan-beckett** [comment]
> If SourceRoot is a root directory for source files, would SourceJar or SourceZip or SourceArchive be the same thing for an archive with source code? Where we only support reading with a callback? Sounds like a fun project.

@matozoid: Do you want to create a **Source** interface/base class? Or, does adding a new **SourceZip** class suffice for now?  Also, should this class support everything the **SourceRoot** currently does, or does supporting a non-cached parse w/ callback suffice for the moment?

Also, do you plan on taking a look at my pull request? I think it's ready to go.

**Comment by matozoid** [comment]
@ryan-beckett I did respond to your first PR, but you keep opening new ones for some reason :-) I don't expect anymore comments so I'll pull it.

Hmm, if you can see some use for a base interface, go ahead.

If we have a `SourceZip`, should we have a `SourceJar`?

Just do the callback thing for now, I haven't seen interest in more than that yet.

**Comment by ryan-beckett** [comment]
@matozoid: Awesome. Yeah, sorry about that, I'm OCDish about my code and I'm still learning Git. 

No need for a base class, unless you can think of other types of sources, and if we do in the future maybe we can add one. **SourceZip** can parse jars and zips. For now, I'll just have **SourceZip.parse(Path, Callback)** and we'll build upon that as needed.
