### ISSUE TITLE
Conditional expression should not be accepted as left-hand side of assignment

### ISSUE THREAD

**Issue by ptitjes** [javaparser/javaparser#109]
Per JLS8 §15.26:

```
AssignmentExpression:
    ConditionalExpression
    Assignment
Assignment:
    LeftHandSide AssignmentOperator Expression
LeftHandSide:
    ExpressionName
    FieldAccess
    ArrayAccess
```

Indeed, the grammar has been copied originally from the PMD one which does not build a full parse tree. Hence the comment in the grammar:

```
/*
 * This expansion has been written this way instead of:
 *   Assignment() | ConditionalExpression()
 * for performance reasons.
 * However, it is a weakening of the grammar for it allows the LHS of
 * assignments to be any conditional expression whereas it can only be
 * a primary expression.  Consider adding a semantic predicate to work
 * around this.
 */
```

**Comment by ptitjes** [comment]
A test case on that branch
https://github.com/ptitjes/javaparser/commits/zz-issue-109

Commit:
https://github.com/ptitjes/javaparser/commit/744a4a30f81e8612878e86f1cfebb7d3a35ae322

**Comment by ptitjes** [comment]
If everyone is OK with that, I add this to 3.0 milestone.

**Comment by matozoid** [comment]
@ptitjes - can we grab your fix, or would you like us to redo it?

**Comment by ptitjes** [comment]
@matozoid hmm... what fix ? :)

**Comment by matozoid** [comment]
Oh... Well, can we grab your test? ;)

**Comment by ptitjes** [comment]
Sure :)

**Comment by matozoid** [comment]
I wonder if this is best fixed by introducing a "PrimaryExpression" node that has the allowed node types as children.

**Comment by matozoid** [comment]
Thanks for reporting this!
