### ISSUE TITLE
Need exact position information of "xxx" in "class xxx { ... }"

### ISSUE THREAD

**Issue by stepinto** [javaparser/javaparser#11]
I'm developing a program like grepcode.com (https://github.com/stepinto/polaris). It uses JavaParser. I need position information about class name in a TypeDeclaration i.e. "xxx" in "class xxx {...}". Currently the position of a TypeDeclaration is the whole class body.

I think we can use NameExpr instead of String for its name. For backward compatibility, we need to add another field "NameExpr nameExpr". I can prepare a patch if you think my idea is right.

MethodDeclaration has the same problem.

**Comment by matozoid** [comment]
I accept any patch that doesn't break the build, so go ahead.
