### ISSUE TITLE
Wiki 'Users' page to present how and by which project JavaParser is used

### ISSUE THREAD

**Issue by ptitjes** [javaparser/javaparser#110]
I think that would be a good to add a such page on the wiki and a section on the homepage.

Adding the traditional note

> Please let us know if your project is using JavaParser. You can also add the "Powered by JavaParser" button below to your project page.

What do you think ?

**Comment by sebastiankirsch** [comment]
Like it. If we don't want to be our only customers and get in touch, this is a start ;)

**Comment by ptitjes** [comment]
So @SmiddyPence showed me that mvnrepository.com is cross-referencing artifact use. So I note that here because gitter log is hiding quickly.

Users of >= 2.0.0: http://mvnrepository.com/artifact/com.github.javaparser
Users of <= 1.1.11: http://mvnrepository.com/artifact/com.google.code.javaparser/javaparser

So I dug the pointer and googled a little. Here are the results:

## Users of 2.0.0
- Codeline Enforcer (https://github.com/talios/codeline-enforcer-rule) – (last-updated: 28 Jan 2015)
- Koan Annotations (https://github.com/SmiddyPence/koan-annotations) – Moved to JavaParser 2.0.0 on the 14/01/2015 for their 1.0.3 version yet to be released. (last-updated: Feb 23, 2015) – @SmiddyPence's project

## Users of 1.0.11
- JAXB2 Basics (http://static.highsource.org/jaxb2-basics/) – (last-updated: 25 Sep 2014)
- Annox (http://confluence.highsource.org/display/ANX/Home - https://java.net/projects/annox/) – (last-updated: 02 Aug 2014)
- Graddle Harmcrest Plugin (https://github.com/signed/gradle-hamcrest-plugin) – (last-updated: 6 Sep 2014)
- Write It Once (Can't find web site - http://mvnrepository.com/artifact/org.simart/write-it-once-source/0.6.5) – (last-released: Jan 13, 2015)
- Maven Sonar-Ignore Plugin (https://dev.shadowhunt.de/sonarignore-maven-plugin/) – (last-updated: Feb 8, 2015)
- deadcode4j (https://github.com/ImmobilienScout24/deadcode4j) – (last-updated: Mar 1, 2015) – @sebastiankirsch's project
- madprogger MetaModel generator (https://github.com/madprogger/metamodel) – (last-updated: 2 Dec 2014)

## Users of 1.0.10
- ScalaGen (https://github.com/mysema/scalagen) – (last-updated: 26 Jan 2014)
- SimpleFunctionalTest (https://github.com/slezier/SimpleFunctionalTest) – (last-updated: Feb 28, 2015)

## Users of 1.0.9
- Kuali Rice Development Tools (https://www.kuali.org/rice - https://svn.kuali.org/repos/) - (last-released: Jan 31, 2015)
- GraphWalker Java (http://graphwalker.org/index - https://github.com/GraphWalker/graphwalker-project) - (last-updated: Mar 4, 2015)
- Quality-Check (https://github.com/before/quality-check) – (last-updated: Jul 16, 2014) @before's project
- ut-maven-plugin (http://www.shenyanchao.cn/ut-maven-plugin/ - https://github.com/blueshen/ut-maven-plugin) – (last-updated: 2 Jan 2014)

## Users of 1.0.8
- SeSAM annotations core support (https://code.google.com/p/acris/source/browse/sesam-annotation-supports/sesam-annotation-core-support/?repo=sesam)  – Also uses ecj, javassist and cglib in the same project, so they might be interested in model support. (last-updated: Feb 5, 2015)
- Juzu Web Framework (https://github.com/juzu/juzu) – Also uses ecj. (last-updated: Feb 11, 2015)
- Helger JCodeModel (https://github.com/phax/jcodemodel) – Dependency in pom is commented "_Stick with 1.0.8 as it is the last JDK 1.5 version_". (last-updated: Feb 6, 2015)
- LibGDX jnigen (http://libgdx.badlogicgames.com/) – (last-updated: now)
- Strongly Typed JavaScript (https://st-js.github.io/) – Was using javaparser before its 3.0.0 version, moved to using javac for java8 support on the 22 Dec 2013. It uses jx.l.m, so maybe could be interested now that we support java8, if we add model support (last updated: Mar 2, 2015)
- GlassFish JAXB Reference Implementation (https://github.com/gf-metro/jaxb) – Uses JavaParser in their CodeModel module. (last-updated: Feb 13, 2015)
- gwt-test-utils (https://github.com/gwt-test-utils/gwt-test-utils) – (last-updated: 9 Mar 2014)
- Chromattic Framework (https://github.com/exoplatform/chromattic) – Uses JavaParser in their groovy and testgenerator modules (last-updated: 14 May 2014)
- Kevoree Tools Model2Code (https://github.com/dukeboard/kevoree/) – Up to version 2.0.13. Can't find any ref to JavaParser in their repo now!
- Cosmopolitan (http://rodionmoiseev.github.io/c10n/) – an internationalization library. (last-updated: 23 Sep 2014)
- Doclet (http://devtools.mikaelsvensson.info/doclet/index.html - https://github.com/mikaelsvensson/devtools) – (last-updated: 15 Oct 2014)
- Jetty :: Documentation :: XSLT Tools (https://github.com/eclipse/jetty.toolchain/tree/master/jetty-xslt-tools) – (last-updated: Mar 2, 2015)
- maven-javacodegen-plugin (https://code.google.com/p/maven-javacodegen-plugin/) – (last-updated: Feb 27, 2012)
- Gaedo Informer Generator (https://github.com/Riduidel/gaedo) – (last-updated: 4 Jul 2014)
- Mule Cloud Connector Generator (https://github.com/zauberlabs/cloudconnect) – Up to version 1.0. Now uses javac tree.
- Japid (https://github.com/branaway/Japid) – (last-updated: 17 Jul 2014)

## Users of 1.0.1
- Wikbook – https://code.google.com/p/wikbook (last-updated: 22 May 2014)
- qipki-site-maven-plugin – https://github.com/eskatos/qipki (last-updated: 25 Jan 2013)

**Comment by ftomassetti** [comment]
This is a pretty amazing list, can I copy it in the wiki?

**Comment by ptitjes** [comment]
Go on. This may need some updates by looking at: http://mvnrepository.com/artifact/com.github.javaparser.

**Comment by ftomassetti** [comment]
Thanks, the initial list is here: https://github.com/javaparser/javaparser/wiki/Projects-using-JavaParser

**Comment by SmiddyPence** [comment]
Lets close this out, I think people can add to it when then have a few moments and struck by the curiosity of usage. 

Personally I would probably just go for groupings of people using 1.x, 2.x etc.  Just to reduce the overhead of maintenance.

Objections to closing?

**Comment by ftomassetti** [comment]
+1 for closing and I agree with reducing the overhead of the list

**Comment by SmiddyPence** [comment]
Done
