### ISSUE TITLE
Kill MultiTypeParameter and BaseParameter and introduce UnionType

### ISSUE THREAD

**Issue by ptitjes** [javaparser/javaparser#111]
The idea is to make BaseParameter be Parameter again and introduce UnionType that wraps a list of Types.

The rational behind that is that it is more close to the semantic model. Also, having an object for the union type enables to consistently attribute (meaning put in the data of the AST node) a semantic type object to each syntactic type object. There is no way to associate a semantic type object to the type of a 'MultiTypeParameter' parameter as this object represents both the parameter and its type.

This can almost be done in forward-compatible way (thus deprecating the old form at first):

```
@Deprecated
class MultiTypeParameter extends Parameter {
  public MultiTypeParameter(int modifiers, List<AnnotationExpr> annotations, List<Type> types, VariableDeclaratorId id) {
    super(modifiers, annotations, new UnionType(types), id);
  }
}
class Parameter extends BaseParameter {
  public MultiTypeParameter(int modifiers, List<AnnotationExpr> annotations, Type type, VariableDeclaratorId id) {
    super(modifiers, annotations, type, id);
  }
}
@Deprecated
class BaseParameter {
  public MultiTypeParameter(int modifiers, List<AnnotationExpr> annotations, Type type, VariableDeclaratorId id) {
    // ...
  }
}

public abstract class VoidVisitorAdapter<A> implements VoidVisitor<A> {

    @Override public void visit(final MultiTypeParameter n, final A arg) {
        visit((Parameter)n, arg)
    }
}
```

**Comment by ptitjes** [comment]
If everyone is OK with that, I add this to 3.0 milestone.

**Comment by ftomassetti** [comment]
If we created the TypeBound, could we just remove the `MultiTypeParameter`?

**Comment by ptitjes** [comment]
You mean UnionType right ? (search the jls for "UnionType") If yes, then indeed you can remove MultiTypeParameter.

**Comment by matozoid** [comment]
So, considering #185 and #149, what is still to be done here?

**Comment by matozoid** [comment]
Looks like all that was left to do was a clean up of unused nodes.
