### ISSUE TITLE
How do I get a field of parameters for a method?

### ISSUE THREAD

**Issue by JoefsMaggie** [javaparser/javaparser#1117]
I need to parse my java web code as an API, for example:
`@RequestMapping(value = InnerURL.Goods.queryGoodInfoBySku, method = RequestMethod.POST)
    RestResponse<QueryGoodsBySkuToOrderDTO> queryGoodInfoBySku(@Var @Valid QueryGoodInfoBySkuDTO goodsSkuDTO){//...}`
and POJO QueryGoodInfoBySkuDTO have a field  `private String goodsSku;`,
so, what should I do?

**Comment by matozoid** [comment]
First, try the manual: https://github.com/javaparser/javaparser/wiki/Manual - it has a sample that goes through methods. Methods have a getter for parameters.

For more information, read the book https://leanpub.com/javaparservisited

**Comment by matozoid** [comment]
Assuming this is answered.
