### ISSUE TITLE
Missing method addConstructor on EnumDeclaration

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#1128]
Hey guys, i'm updating from `3.0.0-RC.4` to `3.3.5`

And I used to do :
```
EnumDeclaration enumType....;
ConstructorDeclaration ctor = enumType.addConstructor(Modifier.PRIVATE);
```
but it looks like addConstructor for EnumDeclaration has been deleted ?

That would be great to restore it :)

**Comment by matozoid** [comment]
Hmmm, odd. Let's investigate!

**Comment by DeepSnowNeeL** [comment]
I just created https://github.com/javaparser/javaparser/pull/1130 to fix it :)
