### ISSUE TITLE
Improve receiver parameter support

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1129]
Here's an idea to improve our current hacky receiver parameter support, inspired by @Bohdankm22:
- receiver parameters currently influence the method signature. They should be filtered out when creating a `CallableDeclaration.Signature`
- we could add a helper method or two that parses the receiver parameter (can we have more than one?) correctly (it is a qualified name, not a simple name like the others) and returns it.
- taking the receiver parameter out of the parameter list would mean losing the position in that list. This may lead to problems for lexical preservation. @ftomassetti ?

**Comment by ftomassetti** [comment]
What is a receiver parameter?

**Comment by matozoid** [comment]
@ftomassetti see #806 - this also needs support in JSS

**Comment by matozoid** [comment]
I didn't realize that there is only one receiver parameter, and it is always the first parameter. Those are good reasons to treat a receiver parameter as different from a normal parameter, and not put it in the parameter list, but make it a separate field.
