### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by andreamattavelli** [javaparser/javaparser#113]
I experience an increased parsing time in the latest git version of JavaParser compared with version 1.0.10.
My test is the following:

``` java
try {
  long start = System.currentTimeMillis();
  JavaParser.parse(new File("./RandoopTest0.java"));
  long end = System.currentTimeMillis();
  System.out.println((float)(end-start)/1000);
} catch (IOException | ParseException e) {
  fail();
}
```

where RandoopTest0.java is a quite huge Java file ~1.2MB and 26+k LOC.
It is a simple and not-well-written piece of code, but it is enough to expose the performance degradation that affects JavaParser (since version 1.0.11).

I have obtained the following measures:
- JavaParser 1.0.10: 0.29 s
- JavaParser 1.0.11: 111.8 s
- JavaParser latest: 1.41 s

My personal feeling is that such issue is caused by the parsing of the comments (feature introduced in 1.0.11 if I am not wrong).

**Comment by ptitjes** [comment]
Hello! Thanks for your report.

Could you try passing the option considerComments to false (the default is true) in order to confirm the problems comes from comments, please ? That would do:

```
  JavaParser.parse(new File("./RandoopTest0.java"), null, false);
```

Also would you mind sharing that huge Java file ? It would help us a lot to make measurements for the next version.

**Comment by andreamattavelli** [comment]
I did not look through the new API, so I missed the new constructor signature.
The new timings with the option considerComments to false are the following:
- JavaParser 1.0.10: 0.29 s
- JavaParser 1.0.11: 0.32 s
- JavaParser latest:  0.36 s

Now it is confirmed that parsing comments causes a performance drawback.

You can download and reuse with no limitation my huge Java file: http://www.inf.usi.ch/phd/mattavelli/javaparser/RandoopTest0.java

**Comment by ptitjes** [comment]
OK! Thanks for your quick feedback!

We will try to enhance the comment parsing in the next releases.
Can you workaround with not parsing comments for now ?

Thank you very much for the Java file.

**Comment by andreamattavelli** [comment]
Yes, now that I am aware of that option, I can proceed with no problems.
Thanks!

**Comment by ftomassetti** [comment]
Do we still have performance degradation? I remember we had some pretty awful bubble sort causing troubles but we removed them

**Comment by ptitjes** [comment]
This performance problem is due to the way the comment parsing and attribution is done.

**Comment by ftomassetti** [comment]
Sure, it was definitely that but I wonder if the comment parsing is still that slow, after some improvements we have done. If it is not we should close this.

**Comment by ptitjes** [comment]
Well, @andreamattavelli's measurements were in March and I can't remember of improvements made to the comments handling since then.

His results were with latest JavaParser at that time:
- With comments: 1.41s
- Without comments: 0.36s

I suppose that would need to be measured again before closing. Just my say...

**Comment by andreamattavelli** [comment]
Hi,
I've just checked the latest version (release 2.2.1) and the timings that I reported in March are in line with what I measured today:
- With comments: 1.446s
- Without comments: 0.343s

Answering @ftomassetti: yes, the parsing of comments it is still slow, compared to March 2015.
Nevertheless, 1.4 seconds are acceptable in my opinion, considering that I am parsing a 2 MB file. Moreover, the addition of the new option to exclude the parsing of comments works perfectly.

It's your decision to close the bug or not.

ps: the huge Java class is still available on my webpage, in case you want to write a regression test case.

**Comment by ptitjes** [comment]
>  ps: the huge Java class is still available on my webpage, in case you want to write a regression test case.

@andreamattavelli BTW, I took the liberty to include `RandoopTest0.java` in the test suite of JLaTo (https://github.com/ptitjes/jlato/tree/master/src/test/resources/org/jlato/samples). I hope you won't mind.

**Comment by andreamattavelli** [comment]
@ptitjes No problems at all, that's actually a very good idea.

**Comment by ftomassetti** [comment]
I think we can close it for now, and when we have time optimize the comments attribution. We went already from 111.8 seconds to 1.4 and comments parsing can be disabled anyway.

**Comment by stefan-reich** [comment]
The considercomments option does not exist anymore, does it?

**Comment by ftomassetti** [comment]
Please open another ticket. I think we still have the possibility of enabling or disabling comments in the JavaParserConfiguration
