### ISSUE TITLE
Get and set names of FieldDeclaration in Javaparser

### ISSUE THREAD

**Issue by AIpeter** [javaparser/javaparser#1131]
How do I get the name of a `FieldDeclaration` by using the Javaparser?  And how can I edit it?

I am able to get and change the name of a `MethodDeclaration`, but is no such function as getName() or setName() in the [FieldDeclaration Class][1].  
I tried to use [this][2], but I don't know where the `VariableDeclarationFragment` and `fragments()` came from.

  [1]: http://static.javadoc.io/com.github.javaparser/javaparser-core/3.3.4/com/github/javaparser/ast/body/FieldDeclaration.html
  [2]: https://www.programcreek.com/2012/11/get-variable-name-by-using-fielddeclaration/

**Comment by matozoid** [comment]
- a field declaration can declare multiple variables like `int a, b, c;` - you are interested in `FieldDeclaration.getVariables()`. It contains `VariableDeclarator`s which have a `setName(...)` (or use the constructor).
- the example is for the parser API that has been available from Oracle. JavaParser is a totally independent project.

**Comment by AIpeter** [comment]
Thank you very much!

It worked for class variables, but how can get and set the name for variables declared in a method?

For example like here:
`public static void test() {`
`    int a = 10;`
`}`

**Comment by matozoid** [comment]
If you want to know what node types are used for a piece of code, try this:
```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.printer.JsonPrinter;

public class Examine {
    public static void main(String[] args) {
        CompilationUnit cu = JavaParser.parse("class X{public static void test() { int a = 10; }}");
        System.out.println(new JsonPrinter(true).output(cu));
    }
}
```

In this case you'll see a `VariableDeclarationExpr`.

Of course, changing the variable name here will not change the variable name where it is used (like `int b = a + 20;`) - that is a lot bigger task, and you will need the Java Symbol Solver project for that.

**Comment by AIpeter** [comment]
The `VariableDeclarationExpr` works good for me.

When I want to use the Java Symbol Solver, I need the jar of the file, right?

**Comment by matozoid** [comment]
As far as I know it works on directories with source code, and to figure out what everything means you add jars or more source. I mean - I can't say what a certain class is or can do if I can't find it. @ftomassetti knows more.

**Comment by AIpeter** [comment]
Thank you for your help!

I found a way that the `FieldDeclaration` and `VariableDeclarationExpr` are sufficient for my purpose.
