### ISSUE TITLE
more than 1 single line comment are missing

### ISSUE THREAD

**Issue by jpgtama** [javaparser/javaparser#114]
Hi all, 

When I am using JavaParser, I found an issue as below:

Code under test:

```
...
// copy changes of all staging records in child level to their
// respective main records.
batchCopyStagingToMainWithParent(pendingDto);
...
```

After I run `CompilationUnit.toString()`, I got below code:

```
...
// respective main records.
batchCopyStagingToMainWithParent(pendingDto);
...
```

There is one line comment missing.

**Comment by ftomassetti** [comment]
At a first glance I think that was happening is that the two lines are considered as two separate comments. One of them is attributed to the call, while the other one is classified as "orphan comment", i.e., a comment floating around not associated to any particular element.
When we spit out the code we forget some orphan comments somewhere.

**Comment by jpgtama** [comment]
Yes, I checked the source code and thought the missing comments maybe went to the orphan comments. Then how to get them back? I found that comments are treated as node attributes, maybe somewhere when we are doing the “attribute" we can attribute more than one line comment.

**Comment by ftomassetti** [comment]
I have just wrote a test to verify that the comments in this class are parsed and dumped correctly:

```
class A {
  // foo
  // bar
  void aMethod(){};
}
```

It seems to work for me. Can you share your source code so that I can test it and see what is different from my small example?

**Comment by jpgtama** [comment]
Hi sorry for late. Can you move the comments into the method and try again? I am using ipad now and it's not easy to share my source code. I will share it when I got back home. :)

**Comment by jpgtama** [comment]
Hi, finally I figure out a way to share source code.

```
            // copy function logic for PendingApprovalForActivate and 
            // PendingApprovalForInactivate staging records
              String tableName = getDtoTableName(stagingDto.getClass());
              StringBuilder sqlUpdate = new StringBuilder();
              sqlUpdate.append(" update ");
              sqlUpdate.append(tableName);
              sqlUpdate.append(" set WIP_STATUS = 0, WF_STATUS_ID=:state, APPROVAL_STATUS_ID=:approvalStatusId where RECORD_ID = :record_id ");
```

Put this code in your method and try again. Thanks.

**Comment by ftomassetti** [comment]
Yes, I can now reproduce it, let's see if I can also fix it :)

**Comment by ftomassetti** [comment]
Ok, I should have a patch for this one, I am going to submit a pull request

**Comment by jpgtama** [comment]
By the way, is it worth keeping the blank lines? For example, there are two consecutive blank lines, and I want to keep them as it was after I regenerated my code.

**Comment by ptitjes** [comment]
Well we do not support whitespace preservation yet. The fact that you get blank lines at all while dumping is a side-effect of the code formatting done by DumpVisitor.

**Comment by ptitjes** [comment]
@jpgtama Evan, do not hesitate to open a ticket for the specific issue of blank lines preservation.

**Comment by jpgtama** [comment]
Hi @ptitjes , thanks, I got it. :)  I will open another ticket while I get the requirement. Currently I think this is  enough. Thanks to @ftomassetti !

**Comment by ptitjes** [comment]
@jpgtama Well thank @ftomassetti :)

**Comment by jpgtama** [comment]
yes, thank @ftomassetti .
