### ISSUE TITLE
FieldAccessExpr could implement NodeWithOptionalScope

### ISSUE THREAD

**Issue by lucamolteni** [javaparser/javaparser#1146]
It'd be useful to recursively navigate up to the root of an heterogeneous expression such as `getAddress().name.startsWith(...)`

It could be implemented as an always present Optional with `Optional.of`

**Comment by matozoid** [comment]
Okay, my thoughts:
`NodeWithOptionalScope` has `Optional<Expression> getScope()`.
`FieldAccessExpr` has `Expression getScope()`.

`Optional` is used throughout the library to warn users that a value may be missing. This as a cure for the many null-pointer issues from before 3.0.0.

We could implement `NodeWithOptionalScope` on `FieldAccessExpr`, but:
- this is misleading: it does not have optional scope
- the getter signatures do not match.

We could consider adding `NodeWithScope` and having both `NodeWith...` interfaces implement a new method for travelling into scope, that functions like what's suggested above - the method returns an `Optional`, and `NodeWithScope` never returns empty.
