### ISSUE TITLE
Plan a 3.0 release

### ISSUE THREAD

**Issue by ptitjes** [javaparser/javaparser#115]
I propose that we plan a 3.0 release after the 2.1. This ticket is to discuss what we would like in a 3.0 release.

**Comment by ptitjes** [comment]
Here is what I propose:
- Add problem reporting mechanism
  - Introduce a Location object (source path + Position, comparable)
  - Introduce a Problem object (comparable based on Location)
  - Introduce a Reporter interface and an implementation that creates and stores problems
  - Make ParserException have a list of problems
- Make JavaParser a state-full object
  - Give access to the (exception-free) reporting mechanism
  - Keep static helpers that throw ParseException
- Introduce NoopVoidVisitor and NoopGenericVisitor
- Add a Checks class (that takes a reporter)
  - Implement no-cost semantic checks
    - Modifiers coherence
    - ...
  - Extract checks currently made inside the grammar (so that people can use them to check hand-created nodes)
    - Call the checks from the grammar
  - Implement a check(Node) (that uses a noop void visitor)
  - Implement a deepCheck(Node) (that uses a scanner void visitor)
- Lexical preservation
  - Introduce Lexeme class (begin and end position, kind, image)
  - Replace the four position integers in Node with a first and last Lexeme
  - Replace the constructor of AST node accordingly
  - Adapt the grammar to use the new constructors
    (All this is similar to what I've done in grammar-work)
- AST consistency consolidation
  - Remove MultiTypeParameter in favor of UnionType – #111 
  - Introduce ArrayType – #112 
  - Change {Method&Constructor}Declaration.throws to be ClassOrInterfaceType
- Grammar enhancements
  - No conditionals as left-hand side of assignements – #109 
  - Type annotations fixes – #107

**Comment by ptitjes** [comment]
I would add:
- Support source JDK version with reporting of non-conformant constructs

**Comment by matozoid** [comment]
Do we have issues for all of this?

**Comment by ptitjes** [comment]
Not yet. I was waiting for big objections (or approvals, additions...) before opening individual tickets.

**Comment by ftomassetti** [comment]
+1 for the Location object (source path + Position, comparable)

**Comment by matozoid** [comment]
That's an incredible amount of work!

**Comment by ftomassetti** [comment]
Should we update this one and open the corresponding issues for each feature? I think there are several interesting ideas, I am just not sure we can put together all the hours needed for implementing all of this so we should probably select some ideas and establish priorities.

**Comment by SmiddyPence** [comment]
I have moved this to the wiki for posterity.  [Roadmap](https://github.com/javaparser/javaparser/wiki/Roadmap)

Some of the items will come out in the wash with existing issues, there are also a lot of additional bugs that have come to light from users since the explicit mention on the googlecode site.
