### ISSUE TITLE
Upgrade https://github.com/sakalauskas/Java-Static-Analyzer

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1180]
This project is using JP 2.5.1. Try upgrading it to the latest.

**Comment by matozoid** [comment]
https://github.com/sakalauskas/Java-Static-Analyzer/pull/1 :-D

**Comment by sakalauskas** [comment]
Ha! Nicely done! :-D

**Comment by matozoid** [comment]
Solved :-)
