### ISSUE TITLE
Add FieldDeclaration to top of ClassOrInterfaceDeclaration

### ISSUE THREAD

**Issue by ajcamilo** [javaparser/javaparser#1183]
How can I add a FieldDeclaration that's the first member of the ClassOrInterfaceDeclaration?

I can't find any easy way of doing this.

**Comment by matozoid** [comment]
I have nothing available to make an example, but the idea is to add a new `FieldDeclaration` to position 0 of the list called `members` of the `ClassOrInterfaceDeclaration`.

**Comment by ajcamilo** [comment]
That replaces with the member that already exists at position 0. 

If this is what was intended, fine by me. I'll just make a method that shifts all the `members`.

**Comment by matozoid** [comment]
I'll add a method for this because this question has been asked several times now :-)

**Comment by matozoid** [comment]
This is what you're looking for:

```java
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.VariableDeclarator;

import static com.github.javaparser.JavaParser.parse;

public class AddFieldDeclarationAtBeginning {
    public static void main(String[] args) {
        CompilationUnit cu = parse("class X{ int a; int b; int c;} ");
        cu.getClassByName("X").ifPresent(coid -> {
            FieldDeclaration fieldDeclaration = new FieldDeclaration().addVariable(new VariableDeclarator());

            coid.getMembers().add(0, fieldDeclaration);

            System.out.println(coid);
        });
    }
}
```

**Comment by ajcamilo** [comment]
That's it, thank you :)

**Comment by vidyat11** [comment]
Hi 

In this same example i am try to add new field **String arg=null;**

how can i add primitive type ...

public static void main(String[] args) {
        CompilationUnit cu = JavaParser.parse("class X{ int a; int b; int c;} ");
       
        	cu.getClassByName("X").ifPresent(coid -> {
        		
            VariableDeclarator variables = new VariableDeclarator();        
            variables.setName("arg");
            variables.setInitializer(new NameExpr("null"));
			FieldDeclaration fieldDeclaration = new FieldDeclaration().addVariable(variables);	
            coid.getMembers().add(0, fieldDeclaration);

            System.out.println(coid);
        });
    }

**Comment by matozoid** [comment]
Hi @vidyat11 - could you open a new issue instead of reusing a closed one?
