### ISSUE TITLE
Associating multiple inline comments with a single statement

### ISSUE THREAD

**Issue by huangwaylon** [javaparser/javaparser#1190]
Hi,

I am using JavaParser 2.4.0, which is quite old, but I need it to work with Java 7. I am wondering how I can attribute multiple single line comments with a single statement.

For example, in the following code block:
```
  /*
   * Multiline comment.
   * To test minimizer.
   */
  @Test
  public void test2() throws Throwable {
    java.util.List<java.lang.Integer> list = new java.util.ArrayList<java.lang.Integer>();
    list.add(1);
    list.add(2);

    org.junit.Assert.assertTrue(list.size() == 2);

    list.add(3);
    // False, should be 3.
    // Another comment line.
    org.junit.Assert.assertTrue(list.size() == 2);
  }
```

I would like to associate both the `// False, should ... ` and `// Another comment ...` with the statement `org.junit.Assert.assertTrue(list.size() ...`.

What I'm doing is I am iterating over each statement in the method body. I parse the statement and do some processing before replacing the original statement.

When I do this, I lose all orphaned comments. The comment `//False, should be 3.` disappears and only `//Another comment...` remains. 

I've noted that multiline block comments are fine, for instance, the one at the top of the code block.

Could you please advise as to how I could possibly handle these orphaned comments and make sure that single line comments that are adjacent to one another all get associated with the statement that follows immediately?

Thank you very much.

**Comment by matozoid** [comment]
@SmiddyPence - can you answer this?

My part: 2.5.1 should be the last version you can use.

**Comment by SmiddyPence** [comment]
So the relationship from Node to Comment is 1:1.

In your case the first comment gets "usurped", by the later comment.  The second comment is actually closer to the node by proximity so it gets assigned as it's comment.

Multi-line block comments although appear over one line are still a single comment, if you were to add two separate multi-line comments you would see the same behaviour; where the former gets orphaned.

Comments are always something we are looking to improve, but unfortunately the desired behaviour is subjective.  One could argue that the programmer who made those comments should have used a block comment.

**Comment by huangwaylon** [comment]
I see. Thank you very much for your response!

So a possible solution to address this issue would be to iterate through all orphaned comments in a method's body and for each orphaned comment, I would combine it with any comment that immediately follows. 

I found the comment attribution spec https://github.com/javaparser/javaparser/wiki/Comments-%28Attribution%29 and it has given me a better idea of what JavaParser does to handle comments.

**Comment by SmiddyPence** [comment]
You're most welcome.  Thank you for sharing your use case as well, it helps us drive future behaviour.
