### ISSUE TITLE
how to parse java file to get method body and annotation on method 

### ISSUE THREAD

**Issue by saxenadeepakkumar** [javaparser/javaparser#1197]
Hi,

I am new for javaparser.  I actually parse java files to get method body and annotation on the method.
How can I get?

Please help.
Thanks in advance

**Comment by matozoid** [comment]
- You can examine the structure of the AST with `YamlPrinter`. If you need more help, just ask :-)
- We have a manual at https://leanpub.com/javaparservisited - you can pay $0,00 and get it for free.

**Comment by matozoid** [comment]
Assuming this is answered
