### ISSUE TITLE
Prettier imports

### ISSUE THREAD

**Issue by leus** [javaparser/javaparser#1198]
Can we add an option to order imports during pretty print?

Also, specifying order (like IntelliJ and Eclipse) would be a plus.

**Comment by ftomassetti** [comment]
Could changing the order of imports affect the program? Like if you have asterisks imports and specific imports and one override the other.

Like:
import c.d.*;
import a.b.MyClass;

If we have both a.b.MyClass and c.d.MyClass does the order of the imports matter?

**Comment by leus** [comment]
It may. But this looks like a good candidate for a `PrettyPrinterConfiguration` option.
