### ISSUE TITLE
Tabs/spaces and indentation guidelines

### ISSUE THREAD

**Issue by ptitjes** [javaparser/javaparser#120]
Yeah I know that this is a sensitive issue...
But there are still files with tabs, others with spaces, and even some that have mixed tabs and spaces! 

It is hard to do correct every time and can lead to surprising things with diffs. I'm sure we all agree on that. Personally, I don't really have a preference as this is just a preference in the IDE...

However, I noticed that IDEA by default adds spaces (in addition to tabs) when I line-break in the middle of a method declaration's argument list in order to align with the first argument.
That's the main problem I hit when trying to be like the current code.

So do we define guidelines ?

(and maybe apply a big code reformatting once and for all for the 2.1 release...)

**Comment by ftomassetti** [comment]
+1 with the reformatting, I was thinking myself to do it. Maybe we could do one package at the time and consider the pull requests in the pipeline

**Comment by ptitjes** [comment]
Yep, that's why I proposed to do it just before 2.1 release in order to have the less pull requests to rework. If everything goes well, every null-handling, new interfaces, fixes would have gone to master for the release. Hence, there would only be the work I started for 3.0 and I don't mind reworking them.

**Comment by ptitjes** [comment]
So how do we proceed to get consensus ? Then I volunteer to make the reformatting, and there should be a second person that independently configures its IDE and do the reformatting again to check nothing has been missed.

**Comment by ptitjes** [comment]
Also I noticed that we should agree on annotations on newline or not (and maybe about method order in visitors)

For instance, see difference in 
https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/ModifierVisitorAdapter.java#L135
and in
https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericVisitorAdapter.java#L82

**Comment by matozoid** [comment]
What I know: Eclipse loves messing around with line breaks, intellij respects them. As long as these two are used simultaneously, automatic formatting will lead to nonsense diffs.

What I do: I stopped caring, I only format the pieces of code I work on, leaving line breaks alone as much as possible, introducing as few "line too long: wrap" line breaks. I tweak default formatter settings as little as possible.

No problem with a full formatting of all code, but please resubmit all your pull requests afterwards :)

**Comment by ptitjes** [comment]
There is also a setting in eclipse's formatter settings (that is turned off by default) to let line breaks as is. (Line Wrapping > Never join already wrapped lines') It works less well than idea's however.

Apart from line wrapping, we have to decide between spaces and tabs because some files use tabs and others spaces.

Ok. Let me propose some basic guidelines and let's see if we can agree on those:
- Spaces
- Type and method annotations on their own lines
- Wrapped arguments aligned to opening parenthesis

That is basically what does Idea by default. I guess Eclipse can be configured the same.
What do you think ?

**Comment by matozoid** [comment]
I guess that since I merged #131 already, this discussion is finished :-) Right?

**Comment by matozoid** [comment]
Put the guidelines here: https://github.com/javaparser/javaparser/wiki/Coding-Guidelines
