### ISSUE TITLE
Performance of toString

### ISSUE THREAD

**Issue by stefan-reich** [javaparser/javaparser#1202]
Hi, I'm using this parser as part of my [JavaX](http://javax.tinybrain.de) project, especially to post-process generated Java sources.

My question regards performance of JavaParser. I have a [20,000 lines](http://tinybrain.de:8080/tb-int/get-transpiled.php?id=1010745&raw=1) source being parsed.

I parse, visit and then call toString on the CompilationUnit. Here are the timings after warm-up (HotSpot Server VM):

    Parsing [1812 ms]
    Visiting [26 ms]
    Pretty printing [5766 ms]

Code for the pretty printing:

    PrettyPrinterConfiguration ppconf = new PrettyPrinterConfiguration();
    ppconf.setIndent("  ");
    return cu.toString(ppconf);

Why is the pretty-printing significantly slower than the parsing? I would have expected this the other way around.

Thanks,
Stefan ([BotCompany.de](http://BotCompany.de))

**Comment by matozoid** [comment]
I'll tag this as a question until someone has time to look into it :-)

**Comment by stefan-reich** [comment]
Thanks :-) Not a terrible problem anyway, maybe pretty-printing is just some effort...

**Comment by matozoid** [comment]
Well, it shouldn't be. Are you using the latest version? A few versions ago we had a performance problem that got fixed.

**Comment by matozoid** [comment]
Oh, by the way, printing comments is quite some effort, maybe you can turn that off.

**Comment by stefan-reich** [comment]
I'm using 3.4.4... yeah, and comments are off (setAttributeComments(false))

Here's the program in my fancy language (though it's easy to run): [tinybrain.de/1011245](http://tinybrain.de/1011245)

**Comment by matozoid** [comment]
Okay, I meant `printComments` in the `PrettyPrinterConfiguration`.

What the heck is that language? :-O

**Comment by stefan-reich** [comment]
It is [JavaX](http://javax.tinybrain.de) :-) - the Java I use for making the future's AI.

**Comment by matozoid** [comment]
I think the performance is much better after some recent fixes, so I'm closing this.
