### ISSUE TITLE
Option to not parse comments

### ISSUE THREAD

**Issue by stefan-reich** [javaparser/javaparser#1203]
I was told to open an issue for this :-)

**Comment by matozoid** [comment]
It's in ParserConfiguration :-)

**Comment by stefan-reich** [comment]
You mean "attributeComments", right? I set it to false and it doesn't seem to change the parsing speed...

What generally confuses me is that the Eclipse compiler compiles a source file faster than JavaParser parses it (almost twice as fast).

Please don't take this as a criticism at all though.

I have successfully used JavaParser already (I need to make all elements of a class public and it does that perfectly). I'm just wondering whether this could still be sped up.

**Comment by matozoid** [comment]
It's a good reminder that we should watch performance more! There is more stuff you can turn off in the configuration to get more out of it.

AttributeComments it is. You can't get away with not parsing comments since they are part of the source file, but we can skip attaching them to the AST.

**Comment by ftomassetti** [comment]
Should this one by closed?

**Comment by matozoid** [comment]
I think so. Open another issue if I'm wrong, @stefan-reich .

**Comment by Symbolk** [comment]
JavaParser.getStaticConfiguration().setAttributeComments(false);
