### ISSUE TITLE
How to collect invoked methods within a method

### ISSUE THREAD

**Issue by bigpotato920** [javaparser/javaparser#1207]
I am new to javaparser, I wanna collect the methods invoked by a specific method both explicitly and implicitly.For example:
```
Class A {
    @Autowired 
    C c;

    foo() {
        B b = new B();
        b.print("abc");
        c.anotherPrint("def");
    }

Class B {
    print(String arg) {
    }
}

Class C {
    @Autowired
    B b;
    anotherPrint(String arg) {
        b.print(arg);
    }
}
```
From the code above I wanna collect the information that Class A's method **foo** invoke B's print() method with the argument "abc" and "def"

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by ftomassetti** [comment]
This one is tough, because you would need to simulate the data flow. In general you cannot do that statically. You can do that for very simple cases like the one given, in which you have a simple constant value passed around.

**Comment by bigpotato920** [comment]
Is it posibble to generate a call graph like:
```
A::foo 
    -->  B::print("abc")
    -->  C::anotherPrint("def")
                --> B::print("def")
```

If this graph can be generated statically, then I can collect information I am interested in. Actually the argument in my case is indeed simple just a single string. @ftomassetti

**Comment by ftomassetti** [comment]
I am just saying that it would work for very simple cases like this one, but as soon as you have variability (for example, an if, or the value for the parameter comes from a variabile that is assigned by complex logic) the problem explodes

**Comment by matozoid** [comment]
No response, closing.
