### ISSUE TITLE
Generate hashcode/checksum of the class method

### ISSUE THREAD

**Issue by vlotarev** [javaparser/javaparser#1212]
Dear team,

I need the way to check whether some specific method in the class is changed or not. I am thinking about calculation of hashcode/checksum based on method signature and content. Could you please let me know whether is it possible to do with the JavaParser. If it is possible I would appreciate the simple code snippet that demonstrates how to do that.

Thanks in advance,
Vadim

**Comment by matozoid** [comment]
Here are some possibilities, which one would you like?
- compare the source code of two methods (call hashcode() on a MethodDeclaration)
- compare nice-but-not-perfect signatures of two methods (call hashcode() on CallableDeclaration.Signature)
- compare signatures perfectly of two methods (requires JavaSymbolSolver)
?

**Comment by vlotarev** [comment]
I think that the first solution would be the best one (hopefully white spaces and comments are ignored when java sources are parsed). Will try, thank you!

**Comment by matozoid** [comment]
Okay, let us know if you have more question! (Reading the book is also recommended: https://leanpub.com/javaparservisited )
