### ISSUE TITLE
API changes review for Javaparser Core

### ISSUE THREAD

**Issue by lvc** [javaparser/javaparser#1214]
The review of API changes for the Javaparser Core library since 2.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/javaparser-core/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/com/github/javaparser/javaparser-core/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Please let me know if you'd like to see reports for other Javaparser modules in the tracker.

Thank you.

![javaparser-core-2](https://user-images.githubusercontent.com/1517837/31983622-b3275e0e-b966-11e7-85f9-df6da19a239a.png)

![javaparser-core-1](https://user-images.githubusercontent.com/1517837/31983623-b3475e5c-b966-11e7-9458-15a7b0ec164f.png)

**Comment by matozoid** [comment]
It's not really refreshing much, is it?

**Comment by lvc** [comment]
@matozoid,

> It's not really refreshing much, is it?

The image in the message is not refreshed, but the page content at https://abi-laboratory.pro/java/tracker/timeline/javaparser-core/ is refreshed daily. Current version is `3.5.3`.

Is there snapshot jar for the library to add to the tracker?

Thank you.

![javaparser-core-3](https://user-images.githubusercontent.com/1517837/32767544-e28ac38e-c924-11e7-9736-930acbc07e43.png)
