### ISSUE TITLE
While dumping semicolons are out of place

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#122]
For example, dumping this:

```
class A {
  // foo
  // bar
  void aMethod(){};
}
```

Result in this:

```
class A {

    // foo
    // bar
    void aMethod() {
    }

    ;
}
```

**Comment by ptitjes** [comment]
Well, that semi-colon is an EmptyMemberDeclaration, right ? I guess that behavior is the expected one as we do not yet have whitespace preservation.

**Comment by ftomassetti** [comment]
well, technically it is true that it is an EmptyMemberDeclaration but our DumpVisitor should print a canonical representation of the code (so, reformatting it, I think it is unrelated from whitespace preservation) and I suppose that several codebases contains semicolons after methods. Probably users expect them to be printed after the closing bracket of the method, not on a new line.

Any thoughts? Is someone else seeing code with semicolons after methods?

**Comment by ptitjes** [comment]
@ftomassetti FYI, I just tried with IDEA (I don't however know Eclipse's behaviour), and code-formatting

```
class A {
    // foo
    // bar
    void aMethod(){};
}
```

produces

```
class A {
    // foo
    // bar
    void aMethod() {
    }

    ;
}
```

**Comment by ptitjes** [comment]
@ftomassetti Do you really think this is a bug or could we close this issue ?

**Comment by ftomassetti** [comment]
Well, it depends how we intend the dumping visitor: if we think it should produce a canonical form the current output is ok. However I think it is not what most users could want and it is not "user friendly". What about adding an option to control which of the two behaviors to use?

**Comment by ptitjes** [comment]
Well, DumpVisitor does produce a canonical representation for everything else.

And also please read the JLS page 206. ";" is admitted in the content of a class (or interface) body as itself. It is not attached to the previous method body.

If we introduce special cases for this, how do you render:

```
class Test {
    ;
}
```

or

```
class Test {
    int field;;
}
```

**Comment by ftomassetti** [comment]
Yes, I understand that the current solution adheres "to the law" but I think it could make sense to support also a "practical" approach. In practice people do not put two semicolons in a row, even if it is legal. People could instead put semicolons after brackets. I think it is typical from developers coming from C++.  In such cases I think users could prefer to keep the semicolon after the bracket instead of having it on a newline. It is definitely not something life-changing or fundamental, but I think would be nice to have.

**Comment by ptitjes** [comment]
I'm quite sure you won't find any code source with semi-colons after methods. Please point me to projects that use that awkward style. I've never seen such a thing in my Java coder's life (that is since 1995).

Also why add complexity for one particular use case when lexical preservation can handle this in a more global and clean way. (Note also that if my lexical preservation's work gets accepted, DumpVisitor gets kicked out. So maybe you might not want to give it too much new features for nothing.)

**Comment by SmiddyPence** [comment]
I think you both have valid points.  

Perhaps the conclusion is that we should offer different printing implementations?  

JLSPrinter, PragmatciPrinter, or similar id be keen to avoind the use of the word "Dump" in future.

**Comment by ptitjes** [comment]
@SmiddyPence: «Id be keen to avoid the use of the word "Dump" in future»
Oh yeah!! +1

Maybe, also making the printer implementation more customizable by overriding.

**Comment by SmiddyPence** [comment]
Sure, that would allow extension as required.   

I'll move this to 3.0 as I think in any case this class should change name, so be a breaking change.  

Even if we only provide one implementation as a version strict JLS or pragmatic printer, the name should reflect that and help avoid confusion.

**Comment by ptitjes** [comment]
@SmiddyPence Note that in my lex-preserving (#125) PR for 3.0, I introduce a Printer class, that uses a FormatterSetting object (to handle newline counts and indentation settings for now).

I did not thought how much work it would be to handle Federico's use case (not really simple I guess as the dangling semi-colon is an EmptyDeclaration on its own...)

**Comment by ftomassetti** [comment]
I think that JavaParser is pretty mature and stable now and it would make sense in the future to work on these extra features like an highly customizable Printer/PrettyPrinter/PragmaticPrinter. Definitely not something that should prevent us from release the next version

**Comment by matozoid** [comment]
Continued in #344
