### ISSUE TITLE
Format multiline Javadoc and block comments on pretty printing

### ISSUE THREAD

**Issue by leus** [javaparser/javaparser#1220]
When generating Javadoc (like this):
``` java
myMethod.setJavadocComment("line1\nline2\nline3");
```

We get the following generated code:
``` java
    /**line 1
line 2
line 3*/
    private void myMethod() {
    }
````
I would like to get something like this, perhaps modifiable via pretty printer configuration:

``` java
    /**
     * line 1 
     * line 2 
     * line 3
     */
    private void myMethod() {
    }
```

**Comment by matozoid** [comment]
Yes, we all do :-) There is currently no support for this. Now that you mention the pretty printer, we might be able to force some correct indentation in there...

Prepending " *" to every line seems more of a "reformat" option. It is completely valid *not* to have a * preceding a line in a Javadoc - but I don't think it's too much trouble to do `setJavadocComment("line1\n * line2\n * line3\n");` ?

So this issue can be: "`BlockComment` and `JavadocComment` are the only two nodes that allow embedded end-of-lines. Make sure these nodes get those lines indented correctly when pretty printing."

**Comment by matozoid** [comment]
Okay, that was really pretty easy, and I reconsidered the solution towards what you suggested:
- do a little reformatting (on empty lines, on leading stars) next to indenting. It's a pretty printer, it is reformatting all the time so my argument was silly.
- `BlockComment` is a completely different case and stays as it was. Block comments can be anywhere and in any shape for any purpose, so I can't think of formatting rules that work for every case.
