### ISSUE TITLE
Help btrplace update their dependency

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1233]
https://github.com/btrplace/scheduler is still on 2.5.1

**Comment by ftomassetti** [comment]
Do we need a new label for these issues?

**Comment by matozoid** [comment]
I'm not sure what it would be? "Promotion"?

**Comment by ftomassetti** [comment]
Maybe "Projects using JP" or "External"

**Comment by matozoid** [comment]
https://github.com/btrplace/scheduler/pull/165

**Comment by matozoid** [comment]
Done!
