### ISSUE TITLE
I think there is a bug with unicode string literals

### ISSUE THREAD

**Issue by stefan-reich** [javaparser/javaparser#1236]
Hi fellas,

I have this code:

```
static String unicode_rightPointingTriangle() {
  return "\u25B8";
}
```
and it seems the JavaParser mangles it into, ultimately, "?".

Has this been tested? I encode all my Java sources as UTF-8 - but it shouldn't matter anyways as it is ecaped as \u, as you see.

I think there really is a bug in the parser/pretty printer.

Greetings,
Stefan

**Comment by matozoid** [comment]
Take a look at #801 and #600 - it looks like there is no pretty solution for this, but we can give some priority to this again.

**Comment by stefan-reich** [comment]
Ah, thanks. The comments say "not fixable"? Hmm...

**Comment by matozoid** [comment]
What do you mean?

**Comment by stefan-reich** [comment]
Nevermind

**Comment by loren138** [comment]
I'd love to have a solution as well.  Looks like I may need to do my work at the byte code level until there is a fix.  (I'm trying to reduce test classes down to one function so I can run just one that I'm interested in, but this issue mangles the input such that the test passes on the buggy and fixed code.)

`final String input = "\ud842\udfb7" + "A";`

**Comment by matozoid** [comment]
@loren138 take a look at the PR I just started :-)
