### ISSUE TITLE
Parsing multiple files into single CompilationUnit object to generate a single AST.

### ISSUE THREAD

**Issue by mirajp1** [javaparser/javaparser#1239]
As the title says, I want to parse multiple java files into a single CompilationUnit object so I can get a single combine AST from all the files. I have looked into javadoc of CompilationUnit which says that it represents singe java file. Currently, if I try to concatenate code of all java files and pass it into the JavaParser.parse() method, it throws an exception as shown below:

```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 78,col 1) Parse error. Found "package", expected one of  ";" "@" "\u001a" "abstract" "class" "default" "enum" "final" "import" "interface" "module" "native" "open" "private" "protected" "public" "static" "strictfp" "synchronized" "transient" "transitive" "volatile" <EOF>
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10216)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10072)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:279)
  com.github.javaparser.JavaParser.parse(JavaParser.java:133)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:333)
  com.github.javaparser.JavaParser.parse(JavaParser.java:305)
  ast.ASTGenerator.storeAST(ASTGenerator.java:25)
  MainDriver.main(MainDriver.java:68)

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:337)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:305)
	at ast.ASTGenerator.storeAST(ASTGenerator.java:25)
	at MainDriver.main(MainDriver.java:68)
```

It looks like CU wasn't made for multiple files, so is there any other method/class in the library which can be used for this work?
Thank you.

**Comment by matozoid** [comment]
Hi @mirajp1, a compilation unit always has a 1:1 correspondence with a Java file. Trying to parse multiple Java files into one compilation unit will lead to questions like "which package is this in? There are so many package declarations!" or "what does `List` mean here? There are imports for java.awt.List, java.util.List...". I hope that explains why this approach won't work.

Java files are organized in packages which are in a source directory. A utility has been supplied for loading files from a directory called `SourceRoot` (although it isn't hard to write one yourself) which might do what you want. So the idea is to parse multiple files and keep their compilation units in a list or set or so.

If this isn't what you're looking for, it would be good if you could describe the problem you are trying to solve.

**Comment by mirajp1** [comment]
Hii @matozoid ,
Thank you for your prompt response.
I understand why it won't work with a single CompilationUnit. I will have a look at that SourceRoot utility and see how it works in my case.
I want a single AbstractSyntaxTree generated from JsonPrinter for whole source directory instead of multiple different AST for each file.

Thank you once again.

**Comment by matozoid** [comment]
No problem!

**Comment by jinho10** [comment]
@matozoid did you achieve this after all? I have the same goal.. but with the sourceroot, it still has list of files separately.

**Comment by matozoid** [comment]
Hello @jinho10 - what is your end goal exactly?

**Comment by jinho10** [comment]
@matozoid I am working on building an AST for the java application to find bugs from the graphs. The source root give a good enough information from each file, but I would like to construct the entire tree to see all the relations in one tree.

**Comment by matozoid** [comment]
Say that you put all the `CompilationUnits` you need in a `Map<String, CompilationUnit>` where the key is the filename, what would you still miss?

**Comment by ch710798472** [comment]
> @matozoid I am working on building an AST for the java application to find bugs from the graphs. The source root give a good enough information from each file, but I would like to construct the entire tree to see all the relations in one tree.


hi, How do you solve this problem

**Comment by jlerbsc** [comment]
If i understand correctly there is no problem. @matozoid said "a compilation unit always has a 1:1 correspondence with a Java file". You have to take into account this postulate to resolve your functionality. I think you don't need a global AST for the application but a dependency graph which models the relationships between the different classes. Isn't it?

**Comment by ch710798472** [comment]
To be honest, I just want to get global AST to implement the intelliJ idea find usages, that like a usage graph

**Comment by jlerbsc** [comment]
To my knowledge, there is no global AST or "usage" functionality in the javaparser project. What you want is a global dependency graph that covers what you want.

**Comment by ch710798472** [comment]
thanks, so can you give me some advise to solve this? I want to use CompilationUnit to analyze dependency graph

**Comment by MysterAitch** [comment]
Hi @ch710798472 ,

These two queries (working across multiple files and finding usages) comes up every once in a while. 

The second has an open issue with some discussion around this (I'll edit in the number later unless somebody else finds it first :smile: ).

@jlerbsc is 100% correct that there is no "global AST" or other form of AST that spans across multiple files. The root of an AST is the `CompilationUnit`.

Instead, if you want to work across multiple files (i.e. over multiple `CompilationUnit`s), `SourceRoot` and `PackageRoot` are available for this.

-  a `CompilationUnit` contains java code (hint: valid java code can be parsed into a syntax tree)
- a `SourceRoot` is the root directory of one or more `CompilationUnit`s (i.e. the directory to which packages are relational to -- effectively, where you would put files that are in the default package)
- a `ProjectRoot` is a directory containing one or more `SourceRoot`s (e.g. think about your IDE's project folder

Here's an example layout:

```
|- path/to/some/other/folder/ ---- some other parent directory
|-\
|--| Project folder/ ------ project root
|--\
|---|- .gitignore ----- some "other" non-java file
|---|- pom.xml ------ some "other" non-java file
|---|-\

|---|--|- src/java/main/ --- source root #1
|---|--\ 
|---|---|- SomeSourceFile.java ---- compilation unit #1

|---|--|- src/java/test/ --- source root #2
|---|--\
|---|---|- SomeTest.java ---- compilation unit #2
```

We also have a couple of `CollectionStrategy` classes which make it easier so that you don't need to manually specify `SourceRoot`s more information is at  https://javaparser.org/setting-up-for-analysing-a-whole-project/

**Comment by ch710798472** [comment]
> work across multiple files

thanks, i am prepare to use ```ProjectRoot``` to  get all project ```CompilationUnit```

**Comment by jlerbsc** [comment]
@ch710798472, if you want to build a dependency graph from all compilationUnits, you have to build it by yourself. You have to think the graph with nodes which represent the classes and the edges which represent the dependencies between the classes. When you parse java files, as things progress, you can build your graph. Once the graph is constructed you can, browse it as you want from node to node following edges. For exemple Guava graph can help you to do the staff.

**Comment by ch710798472** [comment]
> @ch710798472, if you want to build a dependency graph from all compilationUnits, you have to build it by yourself. You have to think the graph with nodes which represent the classes and the edges which represent the dependencies between the classes. When you parse java files, as things progress, you can build your graph. Once the graph is constructed you can, browse it as you want from node to node following edges. For exemple Guava graph can help you to do the staff.

thanks
