### ISSUE TITLE
Obscure issue with unicode escapes

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1242]
`'\u005cn'` is a valid character. It works by preprocessing `\u005c` to `\`, so we have `\n` left.

I'm not sure what to think of this. It's in the JDK source: https://alvinalexander.com/java/jwarehouse/openjdk-8/jaxws/src/share/jaxws_classes/com/sun/xml/internal/rngom/parse/compact/CompactSyntax.java.shtml

Note: Intellij also thinks this is illegal.

**Comment by matozoid** [comment]
@hydroper - does that thumbs up mean you really need this fixed? ;-)

**Comment by ghost** [comment]
@matozoid Personally I don't need, but it's always cool to follow standards, right? This might be an compiler extension. Though... Esprima (ECMAScript parser) had a little bug exceeding A-F and a-f.

The Java spec. shows `UnicodeInputCharacter :: UnicodeEscape` just uses 4 hexadecimal digits. So, this might be an extension.  Even ECMAScript doesn't support that, so I think it's true :smile:

**Comment by matozoid** [comment]
That's exactly the problem: since last release we do not follow the standard anymore :-D We used to convert all unicode escapes to actual characters before we even started parsing. Then the parser would simply see "\n" here and everything would be fine. So I'm wondering why I even reported this because I caused it on purpose ;-)

**Comment by ftomassetti** [comment]
Yes, I just found this case while running the tests for JSS :)

**Comment by matozoid** [comment]
Uhhh, so @ftomassetti - do you want this fixed then? :-D

**Comment by ftomassetti** [comment]
Well, I just changed the source code used in the tests :D

**Comment by matozoid** [comment]
Good, I think it's the kind of obscure stuff that no programmer will ever write :-)

**Comment by matozoid** [comment]
There is no reason to implement this after having decided not to pre-parse unicode escapes, so closing.
