### ISSUE TITLE
IfStmt.hasElseBlock() does not work correctly

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1247]
The `IfStmt.hasElseBlock()` method exhibits a somewhat surprising behavior. Consider:

```
IfStmt ifStmt = (IfStmt) JavaParser.parseStatement("if (cond) doSomething(); else doSomethingElse();");
System.out.println(ifStmt.hasElseBlock()); // prints: false
```
The above prints `false`. Granted, the else-branch is not a block, but a single statement. And indeed,
```
IfStmt ifStmt2 = (IfStmt) JavaParser.parseStatement("if (cond) doSomething(); else { doSomethingElse(); }");
System.out.println(ifStmt2.hasElseBlock()); // prints: true
```
...prints `true`. All of that would be fine. However, the following...
```
IfStmt ifStmt3 = (IfStmt) JavaParser.parseStatement("if (cond1) doSomething(); else if (cond2) doSomethingElse();");
System.out.println(ifStmt3.hasElseBlock()); // prints: true
```
...prints `true` too. But why? In the latter case, the else-branch consists of a single statement (namely, another if-statement), not a block.

I think that either *all* of the above should print `true` (in which case the method may be more aptly named `hasElseBranch()`), or *only* the second example should print `true`, while the two others should print `false` (since only the second example does have an else-*block*).

Is this a bug, or am I simply missing something?

**Comment by matozoid** [comment]
@ftomassetti - this method is your creation, so I'll leave it to you :-)

**Comment by ftomassetti** [comment]
I will try to take a look at this tomorrow

**Comment by malteskoruppa** [comment]
Wow, that was fast! :smile: Thank you very much!

As far as I'm concerned, this can be closed. Unless there is a reason to keep it open for a little while longer?

**Comment by ftomassetti** [comment]
We need first to merge the PR :)
