### ISSUE TITLE
tabulator counts as 4 characters in editors, leading to wrong column values

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javaparser#1248]
Hello there,

this is just a small problem i am having with the column values provided by the nodes. They are slightly off, when comparing to most IDEs and editors. They use 4 characters for a tabulator by default, compared to the 1 character JavaParser uses.
I tested this with Eclipse, Sublime Text, IntelliJ and Visual Studio Code, all of which count tabulator as 4 letters.
This obviously is just a tiny annoyance, however since my project/program creates output logs for students, i would like to provide information as precise as possible (to not confuse anybody). It would be cool, if this could be fixes. Maybe with a getColumn(int charactersForEachIndentation) method, which provides the amount of characters for each tabulator.

**Comment by matozoid** [comment]
Hello @un0btanium - will `tabSize` in `ParserConfiguration` do the trick for you?

**Comment by un0btanium** [comment]
Yes, it did. How was i able to miss that?!
Your tool gets greater by the minutes 👍
