### ISSUE TITLE
Parsing try-with-resources does not work correctly

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1253]
Java 9 introduced the possibility to specify already declared final or effectively final resources within a try-with-resources statement (instead of having to declare a resource).

This does not work with JavaParser. The following code:

```
JavaParser.parseStatement("try (r) {\n" +
                          "  // ...\n" +
                          "} catch (IOException|NullPointerException e) {\n" +
                          "  // ...\n" +
                          "} finally {\n" +
                          " // ...\n" +
                          "}");
```

throws an exception:

```
com.github.javaparser.ParseProblemException: (line 1,col 1) Try with resources only supports variable declarations.
```

I verified that this happens with JavaParser 3.5.4, which was released yesterday.

Yet, the very example given above is taken from JavaParser's documentation. In fact, according to the documentation, this should be supported since JavaParser 3.4.0: http://static.javadoc.io/com.github.javaparser/javaparser-core/3.4.0/com/github/javaparser/ast/stmt/TryStmt.html

Citing from that page:

> Java 9 finishes resources: you can now refer to a resource that was declared somewhere else. The following types are allowed:
> - VariableDeclarationExpr: "X x = new X()" like in Java 7-8.
> - NameExpr: "a".
> - FieldAccessExpr: "x.y.z", "super.test" etc.

This quote directly contradicts the exception's message, which states that only variable declarations are allowed.

**Comment by malteskoruppa** [comment]
Oops, my bad. :smiley: 

The following works fine:

```
JavaParser.setStaticConfiguration(new ParserConfiguration().setValidator(new Java9Validator()));
JavaParser.parseStatement("try (r) {\n" +
                          "  // ...\n" +
                          "} catch (IOException|NullPointerException e) {\n" +
                          "  // ...\n" +
                          "} finally {\n" +
                          " // ...\n" +
                          "}");
```

I was unaware that JavaParser still parses in Java 8 mode by default.

**Comment by matozoid** [comment]
Hmmm, maybe we should set it to 9, you're the second one to fall for this :-) @ftomassetti @SmiddyPence what do you think?

**Comment by ftomassetti** [comment]
It could make sense to set it to 9.
In the future it could become complicate as new releases of Java are expected to arrive every 6 months.
My expectation is that it will be a huge mess with people stuck to Java 5 and people running Java 14. So at some point it could become hard to pick a default and we may want to make the choice explicit.
Or otherwise pick as a default the last version available (as soon as we support it, of course :D)

**Comment by matozoid** [comment]
As long as the releases stay backwards compatible it should be fine to set it to the latest version - another option is to simply disable the validations, but then we would accept a lot more invalid Java.

**Comment by DeepSnowNeeL** [comment]
Why not asking for it instead of making it a default value ?

**Comment by matozoid** [comment]
Because you would have to ask for it each and every time you want to parse something. Or am I missing something?
