### ISSUE TITLE
JavaParser parse method

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1256]
Sometimes I get confused by the parse method.

The static parse method of JavaParser is exacly what users are looking for I think. It takes a string and give me back the AST: how can things be simpler and nicer than that? Perfect!

The problem is that when I instantiate JavaParser because I want to pass a configuration then I would be tempted to use this method, which however is static so it would not consider my configuration. The alternative I have is more complicated:

```
        // Parse some code using the JavaParser instance methods
        CompilationUnit cu = javaParser.parse(ParseStart.COMPILATION_UNIT,
                new StringProvider("class X { int x() { return 1 + 1.0; } }")).getResult().get();

        // Parse some code using the JavaParser static methods
        CompilationUnit cu = javaParser.parse("class X { int x() { return 1 + 1.0; } }");
```

I am not sure how to change this to make it more intuitive. Maybe we could divide the static stuff and the instance stuff in two classes. Not sure.

**Comment by matozoid** [comment]
I get the problem, I've had it a few times myself (although the IDE quickly helped me out.)

Some reasons why I merged `JavaParser` and `JavaParserInstance` for 3.0.0:
- naming something "instance" sounds like bad design to me. "instance" is not part of a type.
- `JavaParser` is a nice and simple starting point. Where should I start to use JavaParser? Well, try class `JavaParser`.

Side note: I wrote an article of course - https://matozoid.github.io/2017/10/15/javaparser-quick-full-api.html

The whole problem seems like a naming problem to me. Right now I can't think of a better solution. I'm thinking "call the instance parse method something else" but that doesn't really solve the problem. Or indeed split it in two again, but what do we call the parts? Is it worth spreading the entry point over two classes for this issue only?

**Comment by ftomassetti** [comment]
Yes, it is not trivial. Maybe we could have JavaParser to expose a static method named "defaultInstance" and do all the parsing through instance methods. It would be slightly more cumbersome for users getting started, which is a drawback.

Alternatively we could make the static methods starts with default like `defaultParsing`.

The symptom for me is that either I just use the very nice & simple `JavaParser.parse` method or as I need to configure anything I need to go through the way more complex parse method taking a ParseStart and a Provider. It would be nice there was something more gradual.

**Comment by matozoid** [comment]
It would make a lot of sense to turn all the static methods into normal methods, and to remove the static instance completely... People should be able to define their JP instance as a constant somewhere in their code, giving them the same situation as now.

**Comment by matozoid** [comment]
I was thinking a bit while driving, that we should move the static methods to non-static. Then I come here and see I already suggested this half a year ago...
