### ISSUE TITLE
Get the object associated with the scope of a MethodCallExpr

### ISSUE THREAD

**Issue by Cale-92** [javaparser/javaparser#1260]
Is there the possiblity to get the object associated with scope of a MethodCallExpr?
For example:
    
    ClassExample b = new ClassExample();
    b.get(pattern[i]);

It is possible to take the object b of ClassExample? I've tried to use 

    methodCallExpr.getScope().get();

but it returns an object of class NameExpr and not the object scope associated with method call.

**Comment by ftomassetti** [comment]
well, in that case the scope is defined as `b`, which is a NameExpr. Then you could ask JavaSymbolSolver to tell you the type of `b` and JSS should be able to tell you that `b` in that context has type `ClassExample`.

**Comment by matozoid** [comment]
Assuming this is answered.
