### ISSUE TITLE
Add possiblity to silence logs in SourceRoot

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1263]

**Comment by matozoid** [comment]
It's pretty easy to do if you investigate the Log class. I can write a little article.

**Comment by matozoid** [comment]
I missed a few questions here:
- SourceRoot is the only thing currently creating output. Do you want to silence this component, or all of JP?
- would you prefer being able to switch it off, or it being off by default and being able to switch it on?

**Comment by ftomassetti** [comment]
If SourceRoot is the only things creating output it is the only thing to silent, or am I missing something?
I would suggest that by default it should be off

**Comment by matozoid** [comment]
Oh, I mean: do you want logging filtered on component, like most logging libraries do, or do you just want to turn off everything? - but from your answer it seems you want everything ;-)
