### ISSUE TITLE
Do lambda expressions always have either an expression body or a BlockStmt body?

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1265]
Question:

Can I assume that, if `lambdaExpr.getExpressionBody().isPresent()` returns `false`, then in this case, `lambdaExpr.getBody()` will always return a `BlockStmt`?

Or can there be situations where `lambdaExpr.getExpressionBody().isPresent()` returns `false`, but `lambdaExpr.getBody()` still returns a `Statement` that is not a `BlockStmt`? If yes, could you give a simple example?

Thank you. :smiley:

**Comment by matozoid** [comment]
@ftomassetti - you've added `getExpressionBody` - can you explain?

**Comment by malteskoruppa** [comment]
Just to clarify: AFAIK, lambda expressions can be either declared using a simple expression, or using a block of code like a method.

**Scenario 1**: using a simple expression, for instance:
`Predicate<SomeType> checkSomething = someType -> someType.hasSomeProperty();`

**Scenario 2**: using a block of code like a method, for instance:
```
Predicate<SomeType> checkSomething = someType -> {
	someType.doSomething();
	return someFixedProperty == someType.getSomeProperty();
}; 
```

In scenario 1, `getExpressionBody()` would contain the `Optional[someType.hasSomeProperty()]` expression. In scenario 2, `getExpressionBody()` would return `Optional.empty`, since there is no expression body.

In scenario 1, `getBody()` would return an `ExpressionStmt` containing the `someType.hasSomeProperty();` expression statement. In scenario 2, `getBody()` would return a `BlockStmt` containing the code given in scenario 2 above.

Hence I am wondering: when `getExpressionBody().isPresent()` returns `false` (i.e., we are in scenario 2), then `getBody()` always returns a `BlockStmt`, true?

In fact, thinking about it, I think we can say that `LambdaExpr.getBody()` always returns either an `ExpressionStmt` (scenario 1), or a `BlockStmt` (scenario 2), and *never* any other kind of `Statement`. We can distinguish scenario 1 from scenario 2 by using `getExpressionBody().isPresent()`.

Do I understand correctly?

**Comment by matozoid** [comment]
Yes, the body of a lambda expression can be a block statement or an expression statement. The JLS says:
```
LambdaBody:
    Expression 
    Block
```
so that is correct.

In my opinion, `getExpressionBody()` isn't the right tool to figure out which one it is. I'm not sure why it is there at all, so that's why I'm calling @ftomassetti :-) 

If I were to handle a lambda expression body, I would probably go for one of these:

```java
        Expression expression = parseExpression("(a) -> a+1");
        Statement body = expression.asLambdaExpr().getBody();
        
        body.ifBlockStmt(block -> block.getStatements());
        body.ifExpressionStmt(expressionStmt -> expressionStmt.getExpression());

        body.accept(new VoidVisitorAdapter<Void>() {
            @Override
            public void visit(ExpressionStmt n, Void arg) {
                super.visit(n, arg);
            }

            @Override
            public void visit(BlockStmt n, Void arg) {
                super.visit(n, arg);
            }
        }, null);
```

I'm not sure if this answers the question :-D

**Comment by malteskoruppa** [comment]
Thanks! Yes it does answer my question, and not only that, it even tells me two much more elegant ways than making a case distinction on `getExpressionBody().isPresent()` to deal with the two types of lambda expressions that exist. Thank you! :smiley: 

I'll admit that the presence of `getExpressionBody()` somewhat added to my confusion in the first place. If there was only the method `getBody()` and the doc clearly stated that `getBody()` returns either an `ExpressionStmt` or a `BlockStmt`, I think things would have been much clearer. Alternatively, `getBody()` could be declared to return a `Node` and the doc could state that its return type will either be an `Expression` or a `BlockStmt` (but that would break backwards compatibility, of course).

**Comment by matozoid** [comment]
Thanks for all the feedback - I think I managed to put it all into issues :-) If you like, check out PR #1266 to see if that looks okay to you

**Comment by malteskoruppa** [comment]
Thank you again for all your support! :smile: 

I just had a look at PR #1266. Looks great. Perhaps, an additional Javadoc comment for `getBody()` would be nice, which (re-)states that the returned value is either a BlockStatement or an ExpressionStatement.

I agree with #1269 -- it would be better if `getBody()` returned a Node that is either a BlockStatement or an Expression. Once that is done, `getExpressionBody()` could be removed completely, which would make finding a new name as stated in #1270 obsolete.

**Comment by matozoid** [comment]
Thanks!
