### ISSUE TITLE
Calling getMembers() on a BodyDeclaration yields Unexpected Results

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1268]
Take the following example code: 

```
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;

public class Testclass {
        public static void main(String[] args) {
                ClassOrInterfaceDeclaration td = new ClassOrInterfaceDeclaration();
                for (BodyDeclaration bd : td.getMembers()) {

                }
        }
}
```

Now replace the line beginning with "ClassOrInterfaceDeclaration td = " with "TypeDeclaration td = new ClassOrInterfaceDeclaration();" and the code will not compile any more, spitting out following error message:
```
Testclass.java:8: error: incompatible types: Object cannot be converted to BodyDeclaration
		for (BodyDeclaration bd : td.getMembers())
```
 td.getMembers() is the same method in both cases, yet for some reason I cannot simply get the BodyDeclarations from the result, if we are dealing with a TypeDeclaration. This looks like somewhat odd behaviour and seems as though it is not supposed to happen.

**Comment by matozoid** [comment]
`TypeDeclaration` has a generic parameter. An IDE should automatically add it. You can use `TypeDeclaration<?>` most of the time. Without it, Java sends you into the pre-generics world where nobody wants to be :-)

We're trying to get rid of the generics, but that's another story.

**Comment by jjbr** [comment]
Right, my bad - thanks for the help :).

**Comment by matozoid** [comment]
No problem!
