### ISSUE TITLE
Adding tag for release 1.0.11

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#127]
Hi, I am using JavaParser version 1.0.11 in one project and I wanted to look at the code of that version but I cannot find the corresponding tag. Maybe we should create it.

**Comment by ptitjes** [comment]
+1

**Comment by matozoid** [comment]
Added tags called javaparser-(version) for each version in the repository

**Comment by ftomassetti** [comment]
That is great, thank you. How did you found out which commit to tag?

**Comment by matozoid** [comment]
Started gitk, searched for "release" and tagged every commit where them pom was changed to a non-snapshot version.
