### ISSUE TITLE
Create static synchronized initializer?

### ISSUE THREAD

**Issue by leus** [javaparser/javaparser#1273]
Using the code generation methods, how can I add a synchronized call to a method?

```java
synchronized(FooRegistry.class) {
    addController(new FooControllerImpl());
}
```

**Comment by matozoid** [comment]
A good option is to parse what you want, then inspect the AST with a debugger or something like the YamlPrinter :-)

**Comment by matozoid** [comment]
@leus - did you forget about this issue?

**Comment by leus** [comment]
@matozoid - kind of. I was trying to solve a problem with our generated code (static initializer was taking too long to finish, and other instances of the class were getting an uninitialized member) but it was solved elsewhere. I'll still like to know the answer, so I'm editing the original question.

**Comment by matozoid** [comment]
The answer above works, but the more direct answer is the SynchronizedStmt.

**Comment by matozoid** [comment]
Since you're not the only one asking these questions, I wrote an article :-)

https://matozoid.github.io/2017/12/13/inspecting-an-ast.html
