### ISSUE TITLE
Is initialization of a for loop really a list?

### ISSUE THREAD

**Issue by davidsusu** [javaparser/javaparser#1281]
For what reason does `ForStmt.getInitialization()` return with `NodeList<Expression>`? Souldn't it return with an `Optional<VariableDeclarationExpr>`? Is there any situation when the result contains more then one element?

**Update**
I just appended an additional `VariableDeclarationExpr`, and reprint the code. The result:

```java
for (int i = 0, int xxx; i < 10; i++) {
    result++;
}
```

Of course, this is a syntax error.

**Comment by ftomassetti** [comment]
...but this is not :)

![screen shot 2017-12-10 at 09 56 45](https://user-images.githubusercontent.com/439078/33803438-7eab3094-dd90-11e7-96da-3a2d8a5cf54a.png)

**Comment by ftomassetti** [comment]
So we could have different variables some of which are initialized and some of which are not

**Comment by davidsusu** [comment]
@ftomassetti Thank you for the quick response! However, at least for me, this SSCCE:

```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.expr.Expression;

public class Main {

    public static void main(String[] args) {
        NodeList<Expression> expressions = JavaParser
            .parse("class Bar {public void foo(){for(int a,b=0;;){}}}")
            .getType(0).getMethods().get(0).getBody().get()
            .getStatement(0).asForStmt().getInitialization()
        ;
        System.out.println("Size: " + expressions.size());
        for (Expression expression: expressions) {
            System.out.println("Expression: <<" + expression.toString() + ">>");
        }
    }

}
```

prints this:

    Size: 1
    Expression: <<int a, b = 0>>

<strike>I have experimented a bit, and I have a (complex) code, where `for (int i, j = array2.length - 1;` parsed to a **single** item, wich contains **only** `j = array2.length - 1` (!).</strike>

**Comment by ftomassetti** [comment]
This sounds like a bug, I guess JP is unhappy when you have an element that is initialized and one that is not. Marking this issue as a bug report.

**Comment by ftomassetti** [comment]
I tried both cases and they seem to work:

```
    @Test
    public void parsingInitializedAndUnitializedVarsInForStmt() {
        ForStmt forStmt = JavaParser.parseStatement("for(int a,b=0;;){}").asForStmt();
        assertEquals(1, forStmt.getInitialization().size());
        assertEquals(true, forStmt.getInitialization().get(0).isVariableDeclarationExpr());
        assertEquals(2, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().size());
        assertEquals("a", forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(0).getNameAsString());
        assertEquals("b", forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(1).getNameAsString());
        assertEquals(false, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(0).getInitializer().isPresent());
        assertEquals(true, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(1).getInitializer().isPresent());
    }

    @Test
    public void parsingInitializedAndUnitializedVarsInForStmtComplexCase() {
        // See issue 1281
        ForStmt forStmt = JavaParser.parseStatement("for(int i, j = array2.length - 1;;){}").asForStmt();
        assertEquals(1, forStmt.getInitialization().size());
        assertEquals(true, forStmt.getInitialization().get(0).isVariableDeclarationExpr());
        assertEquals(2, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().size());
        assertEquals("i", forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(0).getNameAsString());
        assertEquals("j", forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(1).getNameAsString());
        assertEquals(false, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(0).getInitializer().isPresent());
        assertEquals(true, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(1).getInitializer().isPresent());
    }
```

It is true that probably `getInitialization` should return a single element and not a list but beside that the information seem to be present and correct. It is just that it could be in a form slightly different from what you expect, or am I missing something?

**Comment by davidsusu** [comment]
> It is just that it could be in a form slightly different from what you expect, or am I missing something?

You are right. 

You can remove the 'Bug report' tag, because `int i` was erased by *my* code.

**Comment by matozoid** [comment]
Behold the power of C in Java!

```java
for (System.out.println("what"), System.out.println("a"), System.out.println("useful"), System.out.println("feature!"); true; System.out.println("loop"), System.out.println("yay")) {

}
```

I'll add this to my upcoming article "features in Java that nobody wants." :-D

Link to the relevant JLS section: https://docs.oracle.com/javase/specs/jls/se9/html/jls-14.html#jls-14.14

**Comment by matozoid** [comment]
Oh wait, my mistake: the previous IS useful, because `for(int i=0...` is a variable declarator, but `for(i=0...` is an expression!

**Comment by davidsusu** [comment]
@matozoid This works, and JavaParser is in sync with my IDE's syntax analyzer.

So, initializer can be a single variable declaration, **or** a list of **limited** expressions (confusing!).

I will study the specs... Nevertheless, I got the answer to the original question.

**Comment by matozoid** [comment]
Thanks for the discussion, it has led to two PR's improving JavaParser :-)
