### ISSUE TITLE
PhantomNodeLogic is not thread safe

### ISSUE THREAD

**Issue by gyfora** [javaparser/javaparser#1286]
Hi all!

I ran into the following problem:

The IdentityHashmap based logic in https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/PhantomNodeLogic.java#L38
fails if multiple threads call JavaParser.parse(code) at the same time, as the IdentityHashmap (accessed statically) is not thread-safe. Leading to weird, hard to debug errors like:

```
com.github.javaparser.ParseProblemException: Unknown error
Problem stacktrace : 
  com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:50)
  com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.storeInitialTextForOneNode(LexicalPreservingPrinter.java:254)
  com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.access$100(LexicalPreservingPrinter.java:63)
  com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$4.process(LexicalPreservingPrinter.java:242)
  com.github.javaparser.ast.visitor.TreeVisitor.visitBreadthFirst(TreeVisitor.java:94)
  com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.storeInitialText(LexicalPreservingPrinter.java:245)
  com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$setup$0(LexicalPreservingPrinter.java:104)
```

A simple fix to this problem as suggested by https://docs.oracle.com/javase/7/docs/api/java/util/IdentityHashMap.html would by using the synchronized version: `https://docs.oracle.com/javase/7/docs/api/java/util/IdentityHashMap.html`

Thanks for checking this out!

Gyula

**Comment by matozoid** [comment]
Hmmm, I'm going to ask @ftomassetti if it's possible to have this cache per AST instead of globally... @ftomassetti ?

**Comment by ftomassetti** [comment]
Well, I remember we changed that cache at a certain point, I do not remember why but it could be that we made it static on purpose

**Comment by matozoid** [comment]
@ftomassetti do you have some guidance for an approach to fix this?

**Comment by ftomassetti** [comment]
Not really. My doubt is that the cache was made static because we could want to use it from different instances. So I guess we can just do what is suggested in documentation:

```
Collections.synchronizedMap(new IdentityHashMap(...));
```

instead of

```
new IdentityHashMap(...)
```

**Comment by matozoid** [comment]
Okay, I went for the easy and hopefully correct fix. @gyfora if you feel like testing it, please do. Otherwise it goes into the next release without testing :-O

Fix is in the master branch currently.
