### ISSUE TITLE
TypeParameters on MethodDeclaration not returning

### ISSUE THREAD

**Issue by naddison** [javaparser/javaparser#1287]
Hi, this is a question that I have not been able to find an answer for, even with incessant googling. I have a method with a signature: 

`public Class<? extends String> P methodName(String arg)`

And I am unable to get the **Class<? extends String>** type argument from type field of MethodDeclaration. When printing the whole method with **toString()** (which prints through the Pretty Printer) I can see the type argument is in fact there.

When I execute `method.getType().asClassOrInterfaceType().getTypeArguments()` I simply get an empty Optional.

Is this a bug? Or am I trying to access the `Class<? extends String>` part of the return type wrong.

**Comment by matozoid** [comment]
Hmmm, I assume that "P" got in there accidentally? Anyway, here is a good way to answer these kinds of questions:

```java
Node node = parseBodyDeclaration("public Class<? extends String> methodName(String arg) {}");
System.out.println(new YamlPrinter(true).output(node));
```

**Comment by naddison** [comment]
Okay thank you for showing me how to print out the node, this helps greatly. The P is meant to be there.

I see that the Node is not picking up the TypeArguments

```yaml
 root(Type=MethodDeclaration):
    type(Type=ClassOrInterfaceType):
        name(Type=SimpleName):
            identifier: "P"
    name(Type=SimpleName):
        identifier: "click"
    comment(Type=JavadocComment):
        content: "
```

**Comment by matozoid** [comment]
Can you give the code that is producing this output so I can run it?

**Comment by naddison** [comment]
I am running the following ->

```java
Node node = parseBodyDeclaration("public <P extends PageObject> P click(WebElement webElement, @FinalDestination Class<P> klass);");
System.out.println(new YamlPrinter(true).output(node));
```

Ah, I think I see my problem, I should be looking at typeParameters. Also my example was wrong up top, it was supposed to be `<P extends PageObject>`

**Comment by matozoid** [comment]
Cool, if you're happy please close the issue :-)

**Comment by naddison** [comment]
Cheers
