### ISSUE TITLE
.replace() method sometimes doesn't properly replace AST nodes

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1290]
Take following call statement: `callSomeFun(r -> r instanceof SomeType);`.

Let's call the lambda expression argLambdaExpr and create a new MethodCallExpr to lambdaWrapper() called methodCallLambdaReplacement. When I call `argLambdaExpr.replace(methodCallLambdaReplacement)` the resulting callSomeFun-expression should be:

`callSomeFun(lambdaWrapper());` 

In fact, in the `arguments` list the lambda expression in the MethodCallExpr is replaced with our new methodCallLambdaReplacement expression. However, the `childNodes` element of the MethodCallExpr still contains the lambda expression (in addition to the new method call expression). I believe the lambda expression is supposed to be be removed from the childNodes list by the .replace() method as well.

**Comment by matozoid** [comment]
Okay, found it and created a fix - it will be in coming weekend's release!
