### ISSUE TITLE
[API] Allow retrieving parsed Javadoc elements

### ISSUE THREAD

**Issue by dhardtke** [javaparser/javaparser#1294]
Hey there,

**Use case**:
I intend to replace / merge existing Javadoc from one `MethodDeclaration` with Javadoc from another `MethodDeclaration`, e.g. when using `* {@inheritDoc}` on inherited methods.

**Problem**:
Right now, it is not possible to retrieve the `JavadocDescriptionElement`s of a `JavadocDescription` instance.
Likewise, I guess it would be nice to also be able to retrieve `JavadocBlockTag`s from `Javadoc` instances.

Is there a particular reason why there are methods like `com.github.javaparser.javadoc.description.JavadocDescription#addElement` or `com.github.javaparser.javadoc.Javadoc#addBlockTag(com.github.javaparser.javadoc.JavadocBlockTag)`, etc.?

 I would prefer to have one method like `getElements()` which would return the raw List so we can modify it based on our wishes.

I can create a PR if my idea is accepted :)

**Comment by matozoid** [comment]
Let's ask our friend @ftomassetti who created this :-)

**Comment by ftomassetti** [comment]
I do not see why not, I would say it is ok to add those methods, however I would suggest to _NOT_ modify the list, for that I would suggest using the API. Ideally I would return an immutable list.

**Comment by dhardtke** [comment]
Then I would suggest to create an immutable List using `Collections.unmodifiableList(list)` and remove methods like `addElement`, etc. - or create a new immutable List every time `addElement` is called.

**Comment by matozoid** [comment]
Hmmm, this API is so different from the rest of JavaParser... I'll make another task to refactor it someday.

**Comment by matozoid** [comment]
Hey @dhardtke - are you still interested in creating that PR? Otherwise I'll do it.

**Comment by dhardtke** [comment]
I can do it, sure. So, what's the plan? Should I add methods like "removeElement()", etc.?

**Comment by matozoid** [comment]
Sure, go wild!
