### ISSUE TITLE
The Maven Central badge is broken :-(

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1296]
Check out the badges on https://github.com/javaparser/javaparser/

**Comment by ftomassetti** [comment]
This is strange because the image loads in the browser: https://img.shields.io/maven-central/v/com.github.javaparser/javaparser-core.svg

Maybe it is taking to long to load?

**Comment by matozoid** [comment]
Other badges are becoming really slow. There's probably something down somewhere :-)

**Comment by matozoid** [comment]
It seems to have solved itself :-)
