### ISSUE TITLE
No unicode escape preprocessing?

### ISSUE THREAD

**Issue by davidsusu** [javaparser/javaparser#1299]
[Chapter 3.3 of the Java specification](https://docs.oracle.com/javase/specs/jls/se9/html/jls-3.html#jls-3.3) is about unicode escape sequences.

Unicode sequences are **part of the source code**, so JavaParser should process them.

What is the situation currently?

**1. Generally, JavaParser make no resolution.**

See this tricky code ([original source](https://stackoverflow.com/a/3866219/3948862)):

```java
class TrickyClass {
    public void trickyMethod() {
        if (false == true) { // these characters are magic: \u000a\u007d\u007b
            System.out.println("false is true!");
        }
    }
}
```
The sequence `\u000a\u007d\u007b` should be parsed as `\n}{`, which terminates the previous `if` (so the enclosed printing statement will always be executed).

Try to parse this with JavaParser:

```java
String input =
    "class TrickyClass {\n"+
    "    public void trickyMethod() {\n" +
    "        if (false == true) { // these characters are magic: \\u000a\\u007d\\u007b\n" +
    "            System.out.println(\"false is true!\");\n" +
    "        }\n" +
    "    }\n" +
    "}"
;
PrettyPrinterConfiguration prettifier = new PrettyPrinterConfiguration();
prettifier.setPrintComments(false);
for (
    Statement statement:
    JavaParser.parse(input)
        .getType(0).getMethods().get(0).getBody().get()
        .getStatements()
) {
    System.out.println("------------");
    System.out.println("# " + statement.getClass().getSimpleName());
    System.out.println(statement.toString(prettifier));
}
```

Only a single `if` statement found:

    ------------
    # IfStmt
    if (false == true) {
        System.out.println("false is true!");
    }

And code is corrupted, because I erased the "comment" (deliberatly).

My expected output is something like this:

    ------------
    # IfStmt
    if (false == true) {\u000a\u007d
    ------------
    # BlockStmt
    \u007b
        System.out.println("false is true!");
    }

**2. However, in strings, unicode sequences are processed**

```java
System.out.println(
    JavaParser.parseExpression("\"Hello World\\u0021\"")
        .asStringLiteralExpr().asString()
);
```

Output: 

    Hello World!

This snippet is syntactically invalid:

```java
System.out.println("First line\u000ASecond line");
```

Make a try:

```java
System.out.println(
    JavaParser.parseExpression("\"First line\\u000ASecond line\"")
        .asStringLiteralExpr().asString()
);
```

Result:

    First line
    Second line

**My suggested solution:**

1. Add (even optional) unicode sequence preprocessing
2. Remove unicode literal resolution from strings

**Comment by matozoid** [comment]
Thanks for the report! Please take a look at the discussion in #1240 and let us know how you feel about it.
