### ISSUE TITLE
1.0.9-SNAPSHOT is 2x slower than 1.0.8

### ISSUE THREAD

**Issue by stepinto** [javaparser/javaparser#13]
I'm switching [my project](http://github.com/stepinto/polaris) from 1.0.8 to the latest version (my project indexes Java sources with lucene). I found my indexer is 2x slower and consuming more memory.

I tried to run bisect. and found the bug was introduced in 6f070b8d84c4ef5a99ad23f167439777a29f3f2d.

Since it is a huge commit (17K lines change), it will take me more time to investigate. Let me know if you have any clue.

**Comment by stepinto** [comment]
I happened to catch this using jstack. Please see my pull request. Thanks!

**Comment by matozoid** [comment]
Everything's been pulled in - thanks :)
