### ISSUE TITLE
Make possible to get token kind name

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1304]
Currently a JavaToken has a kind, which is an ID. It is difficult to get the name of such kind. Names are available only as static fields of `GeneratedJavaParserConstants`.

**Comment by matozoid** [comment]
So shall we parse GJPC and create a reverse mapping of token kind -> name ? Or open an issue on JavaCC or ParserGeneratorCC?

**Comment by ftomassetti** [comment]
For now I am using a reflection hack...

**Comment by matozoid** [comment]
Gimme
