### ISSUE TITLE
Why doesn't AssignExpr.getTarget() return a SimpleName?

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1305]
Short question... why does `AssignExpr.getTarget()` return a general `Expression` instead of a `NameExpr` or even a `SimpleName`?

I can't think of any scenario where the target of an assignment expression is not a variable describable as  a `SimpleName`, although I am sure there are. ;) Maybe I am just tired... could you give an example? :wink:

**Comment by ftomassetti** [comment]
```
static class A {
        int a;
    }

public static void main(String[] args) {
        new A().a = 10;
}
```

**Comment by malteskoruppa** [comment]
Of course! Thank you so much. :smile: 

So... can we say that `AssignExpr.getTarget()` will always return either a `NameExpr` or a `FieldAccessExpr`?

**Comment by ftomassetti** [comment]
I would think so but I am not sure if I could miss anything

**Comment by malteskoruppa** [comment]
Thanks for all the awesome support. Btw, it might be a cool idea to add such an example to the Javadoc of `AssignExpr`. Currently two examples are given:

```
a=5 
time+=500
```
Another example such as `obj.prop *= 2` or whatever might help people who wonder the same thing in the future. :smiley:

**Comment by matozoid** [comment]
I was looking through the [JLS](https://docs.oracle.com/javase/specs/jls/se9/html/jls-15.html#jls-15.26.1) and also spotted array access and, let's not forget, braces...
(((time)))=100
peanut[a]=true

I'll go add all of these! Thanks for the feedback!
