### ISSUE TITLE
Make JavaSymbolSolver a module in the JavaParser project

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1316]
The reasons are:
1. We can have coordinated releases
2. It is easier to fix issues which requires changes in both projects
3. It could marginally make easier for user to see that JavaSymbolSolver exist in the first place

This issue is intended to
* argue in favor or against it
* discuss a strategy to do it

Things we would have to do:
* move from gradle to maven
* merge the readme

Initial strategy for merging:
1) Create a branch in JSS and just move some directories around, removing all files we do not want to bring in JP
2) Create a branch in JP
3) Merge the JSS branch in the JP branch... _This is where things could get interesting: we will see..._
4) Poke it until it compile

**Comment by matozoid** [comment]
I'm in favour. I'm also in favour of making a list of the state of all the components. I'm not too happy with the lexical preserving printer causing so many issues that it seems unusable, for example. The symbol solver already has a warning in the README, so that's cool.

**Comment by ftomassetti** [comment]
Yes, the lexical preserving printer need refinements. It seems people are using it given they produce bug reports :)
After we get this list we could devise a strategic plan and see on what to focus and how to verify we have reached the quality we want for each problematic component.
Should we do this in this issue or in a separate one?

**Comment by matozoid** [comment]
I saw that your FOSDEM presentation will be about "where next?" - so that would be good input :-)

And right, that should be another issue, or on Gitter.

**Comment by ftomassetti** [comment]
Apparently you can merge two unrelated git projects, so I started creating the `mergingjss` branch in my fork of JP

**Comment by ftomassetti** [comment]
In JSS there are 5 modules:

1. java-symbol-solver-model
2. java-symbol-solver-logic
3. java-symbol-solver-core
4. java-symbol-solver-testing
5. java-symbol-solver-examples

We could move the examples to a separate project and rename the other four.
How?

into javaparser-symbol-solver-[model/logic/core/testing]?

**Comment by matozoid** [comment]
(The simplest way would be to simply move JP and JSS one directory lower and make a new parent-parent-pom that has the old parent poms as modules. Also very lazy ;-) )

I don't mind the examples too much, although the starter projects and everything are of course also separate projects (but mostly so people can check them out and get started.)

Naming sounds fine, yes.

**Comment by ftomassetti** [comment]
I removed the examples, renamed the modules and done a few corrections.
It seems to work (at least the tests pass locally). However I do not know how to be sure all tests are run. At the end I read:

Tests run: 547, Failures: 0, Errors: 0, Skipped: 0

But I guess that refers only to the last module, not to the whole project

See #1318

**Comment by matozoid** [comment]
There's something hacky being done to get coverage right in JP, it seems to be copying the result from jp-testing to jp-core, or so. I gave up splitting off jp-jbehave from jp-testing because of this.
