### ISSUE TITLE
What about a FloatLiteralExpr?

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1320]
JavaParser seems to parse floats as doubles... just for clarification, is this intended?

`System.out.println(JavaParser.parseExpression("1f").getClass());`

The above outputs `class com.github.javaparser.ast.expr.DoubleLiteralExpr` which makes sense since there is no `FloatLiteralExpr`.

This is fine for my purposes, I can work with it. However, Java Symbol Solver correctly reports the type of the expression `1f` as `float`, so I suddenly have a `DoubleLiteralExpr` whose type is reported as `float` by Java Symbol Solver, which makes things slightly confusing. :wink:

**Comment by matozoid** [comment]
Check #664 :-)

**Comment by malteskoruppa** [comment]
Thanks! :)
