### ISSUE TITLE
Get annotation value

### ISSUE THREAD

**Issue by cunhazera** [javaparser/javaparser#1324]
Is there anyway to get the value of each annotation attribute?

**Comment by matozoid** [comment]
Yes, have you read the book? It's more or less required basic training. You can get it for free if you like: http://javaparser.org/

**Comment by cunhazera** [comment]
Oh, I haven't. I'm going to do this!
Thank you!

**Comment by matozoid** [comment]
Feel free to open another question if you can't figure it out :-)
