### ISSUE TITLE
Make AnalyseJavaParserTest optional

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1326]
It's taking a huge amount of time in each build.

**Comment by ftomassetti** [comment]
Yes, those should be sort of "acceptance tests" or somet other kind of tests, but not unit tests.

One way could be creating a separate module and run from travis/appveryor `mvn test` only on the modules of interest I guess.

**Comment by matozoid** [comment]
For JS I went the simple way: turn the test method into a main method and run it from the IDE every now and then :-)

**Comment by ftomassetti** [comment]
We could do what is specified here:
https://stackoverflow.com/questions/18164579/how-do-i-specify-a-separate-maven-goal-for-running-cucumber-acceptance-tests

We could have these more deepened tests run specifying a different goal.
We could or could not run them as part of CI. Perhaps we could just run them manually before doing a release.

**Comment by matozoid** [comment]
Looks messy with all the included/excluded paths. Can we mix having a separate module(s) and having a goal (or a profile like the generators) maybe? We can also supply a script like the current run_bla.sh that is an easy access point.
