### ISSUE TITLE
Remove duplicate classes for testing

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1334]
I keep accidentally editing test code, please remove all this duplicate code!

![image](https://user-images.githubusercontent.com/55701/34916720-e8852f3e-f93c-11e7-8125-a0b54c9bccf0.png)

**Comment by ftomassetti** [comment]
We have tests agains that source code. IntelliJ should not consider it. The way I found to convince IntelliJ to ignore those files is to mark their directories as "excluded"

**Comment by matozoid** [comment]
Something else that can be done is to download these sources on demand, so they don't clutter the resources directory: https://maven.apache.org/plugins/maven-dependency-plugin/examples/using-dependencies-sources.html
