### ISSUE TITLE
Add If statement to a method call expression

### ISSUE THREAD

**Issue by jchensc** [javaparser/javaparser#1340]
Does the current API support adding if statement to a method call?

e.g
```
// before
foo1()

//after
if() {
    foo1() 
}
```

Thanks ahead!

**Comment by matozoid** [comment]
Yes, it does! In pseudo code:
- clone `foo1()`
- create if statement.
- add cloned `foo1()` to the new if statement body.
- replace old `foo1()` by the new if statement.

**Comment by matozoid** [comment]
@jchensc - did it work?

**Comment by jchensc** [comment]
@matozoid Thanks it works!

**Comment by jchensc** [comment]
One follow up question, is it possible to customize the format of the if block?

for example, I want the above case to be 

```
if(xx) { foo1(); } 
```
so that it will not mess up the line number

**Comment by matozoid** [comment]
If you're using `toString()` or the `PrettyPrinter` (which is the same thing) to print it out, the choices you have are:
- copy the `PrettyPrintVisitor` to your own project, modify it to your wishes and use it directly (or configure `PrettyPrinter` to use it)
- open an issue for a new configuration option for the pretty printer
- open a PR with the new configuration option.

**Comment by jchensc** [comment]
Interesting. Will try it out, thanks!

**Comment by matozoid** [comment]
I assume this is answered.
