### ISSUE TITLE
[Question] - Variables defined before node (in scope at node)

### ISSUE THREAD

**Issue by Sigurthorb** [javaparser/javaparser#1349]
Hello

I am using java parser to inject code into a java class
At each injection, I need a list of variables that have been defined before the statement in question and are within scope of the statement.

For class variables, I just query the ClassOrInterfaceDeclaration for FieldVariables and from that, VariableDeclarator.

For a given statement, can I query the CompilationUnit or something else for variables defined before it?

Also knowing if the variable has been assigned or just declared would also be useful

**Comment by matozoid** [comment]
Hi, check out [VariableDeclarationExpr](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.5.10/com/github/javaparser/ast/expr/VariableDeclarationExpr.html). Also check out [this article](https://matozoid.github.io/2017/12/13/inspecting-an-ast.html) on how to see what's in an AST for any piece of code.

Let us know how far you get.

**Comment by matozoid** [comment]
Assuming this is no longer relevant.
