### ISSUE TITLE
Extract XmlPrinter, JsonPrinter, and YamlPrinter to separate modules

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1353]
... so that we can use a real library and avoid silly escaping problems.

Maybe make a deserializer too.

**Comment by matozoid** [comment]
@ftomassetti - what do you think - should they all be separate mini modules so that they all have only the dependency they need (XmlPrinter - some XML lib, JsonPrinter - some JSON lib...) or shall we put all of them in the same module?

**Comment by ftomassetti** [comment]
I would go for one single module

**Comment by Vampire** [comment]
Why not keep them internal, but add optional dependencies?
If someone want to use it at runtime he has to provide the dependency himself, if not, he doesn't need the additional dependency in his project.

**Comment by matozoid** [comment]
In theory that's a good idea. I think that would lead to a lot of issues being opened about "class not found" though. Also: it would be good to remove some bloat from core, especially when writing a full serializer will probably add more classes. Serialization isn't really essential so that's an easy target.

Do you think we have too many modules?

**Comment by Vampire** [comment]
Didn't want to imply that, just wanted to note the possibility of optional dependencies if not requireing on additional libs most users will not need would be the reason to split it off.

If you have other reasons, like clearer structure, it is fine.

About the class not found errors, this could actually be done in a user-friendly and user-unfriendly way.
And if you do all in one module, you might still need it, or a user that wants one serializer has to manually exclude the others to remove bloat and I as users always have a bad feeling if I exclude libs a project declares it needs.

In the user-unfriendly way you just use the classes and the user gets a CNFE if he tries to use it.
In the user-friendly way you have one class that does not directly depend on the 3rd party classes that is the starting point for the user to use it and therein you check in the constructor whether the 3rd party classes are there and tell him to add the library if not.

**Comment by matozoid** [comment]
That's a good point - with a decent error message and all the implementation well hidden it should be fine.

**Comment by matozoid** [comment]
I'm having a go at JSON serialization, and the Java API for JSON Processing makes the whole dependency question moot :-)

**Comment by matozoid** [comment]
There's now a JSON serializer. If people want more, we can add it.
