### ISSUE TITLE
Variable/Parameter/FieldDeclaration with optional generic types

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javaparser#1357]
Hey!

I might have missed something, but i am unable to extract information about the generic  #types of VariableDeclarationExpr, Parameter and FieldDeclaration.

In the following example, I would like to extract `Integer` (and maybe use and send it to the JavaSymbolSolver for further information):
```
private List<Integer> numbers;
```

I kind of expected a `hasGenericTypes()` or a `getGenericTypes()` with an `Optional<List<ClassOrInterfaceType>>` as return value or something similar, but it seems there is no information stored anywhere about them. (I am aware of the nested and complex nature of the generic declarations, this was just a quick example.)

I did found the class `Wildcard`, which returns only generic types with a `?`. Which is weird, since i expect this class to inherit from a more generic type ast class.

If there is no information about them at the moment, i will have to extract them manually for now, but i would wish for a more well rounded out-of-the-box solution :)

Thanks for reading.

**Comment by matozoid** [comment]
Hi! Give this page a read: https://matozoid.github.io/2017/12/13/inspecting-an-ast.html and report back if it helps :-)

**Comment by un0btanium** [comment]
That was a good hint in the right direction (would like to see this article be put into the JavaParser: Visited book). The information I require seems to be there. But it is confusing and i am not 100% sure, how I am supposed to extract it.

`private List<Integer> numbers;`
```
- member(Type=FieldDeclaration): 
    variables: 
        - variable(Type=VariableDeclarator): 
            name(Type=SimpleName): 
                identifier: "numbers"
            type(Type=ClassOrInterfaceType): 
                name(Type=SimpleName): 
                    identifier: "List"
                typeArguments: 
                    - typeArgument(Type=ClassOrInterfaceType): 
                        name(Type=SimpleName): 
                            identifier: "Integer"
```

I am able to retrieve the `VariableDeclarator`s via `FieldDeclaration.getVariables()`. Furthermore, I am able to retrieve the type (in this case `List`), but i am unable to get the `typeArguments`. Any hint how i would do that?

I imagine i could just use `.getChildNodesByType(ClassOrInterfaceType.class)` on it, but if someone thinks he is super smart and puts the import within the whole declaration, then JavaParser creates nested `ClassOrInterfaceType`s for the scope.

`private List<java.util.ArrayList<Integer>> numbers2;`
```
- member(Type=FieldDeclaration): 
    variables: 
        - variable(Type=VariableDeclarator): 
            name(Type=SimpleName): 
                identifier: "numbers2"
            type(Type=ClassOrInterfaceType): 
                name(Type=SimpleName): 
                    identifier: "List"
                typeArguments: 
                    - typeArgument(Type=ClassOrInterfaceType): 
                        name(Type=SimpleName): 
                            identifier: "ArrayList"
                        scope(Type=ClassOrInterfaceType): 
                            name(Type=SimpleName): 
                                identifier: "util"
                            scope(Type=ClassOrInterfaceType): 
                                name(Type=SimpleName): 
                                    identifier: "java"
                        typeArguments: 
                            - typeArgument(Type=ClassOrInterfaceType): 
                                name(Type=SimpleName): 
                                    identifier: "Integer"
```

I only want the `ArrayList`, not the whole package. Any idea how I would do that? I may have to create a visitor and visit the classes recursively myself, but even then i am not sure how i am supposed to be able to differentiate the package information from the class names.

**Comment by matozoid** [comment]
Here's code for the first one:
```java
package com.github.javaparser;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.type.Type;

public class Abc {
    public static void main(String[] args) {
        CompilationUnit cu = JavaParser.parse("class X{private List<Integer> numbers;}");
        Type type = cu.getClassByName("X")
                .map(coid -> coid.getMember(0).asFieldDeclaration().getVariable(0).getType())
                .orElseThrow(RuntimeException::new);
        type.asClassOrInterfaceType().getTypeArguments().ifPresent(
                tas -> tas.forEach(System.out::println)
        );
    }
}
```
The issue with `scope` being a `ClassOrInterfaceType` is one of ambiguity. The parser doesn't know if it is a qualified name or a field access. (`A.B` versus `a.B`.) If you can't make assumptions on what the user will put there, you will have to use the symbol solver to find out what it really is.

**Comment by matozoid** [comment]
Assuming this is no longer relevant.
