### ISSUE TITLE
Make clear in the readme how to add javasymbolsolver

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1358]
We should specify that if they need also JSS they could include just that (JP would be automatically included). We could create a page on the website to explain why to use just JP and why to use JSS. Then we could link that page in the Readme.

Does it make sense @matozoid ? See discussion in https://github.com/javaparser/javasymbolsolver/issues/368

**Comment by matozoid** [comment]
We could even put the JSS dependency first and say "if you only need the AST or do some code generation, you can use the core dependency."

**Comment by matozoid** [comment]
@un0btanium  and @MysterAitch - why not create a PR instead of thumbing this up? ;-)
