### ISSUE TITLE
Replacing type of a FieldDeclaration with multiple variables

### ISSUE THREAD

**Issue by httpdigest** [javaparser/javaparser#1359]
I want to use JavaParser to parse a "template Java" source file and generate multiple source files from it mostly with simply changed field types.

The following self-contained code snippet fails for me with the exception:
`Exception in thread "main" java.lang.AssertionError: The variables do not have a common type.`

Somehow, JavaParser thinks that the PrimitiveType has array levels and the assertion in [NodeWithVariables$1Helper.toArrayLevel()](https://github.com/javaparser/javaparser/blob/b64b7a425769228e24ee8784c7f535fc7b49d32e/javaparser-core/src/main/java/com/github/javaparser/ast/nodeTypes/NodeWithVariables.java#L128) fails. Also, [the abort condition](https://github.com/javaparser/javaparser/blob/b64b7a425769228e24ee8784c7f535fc7b49d32e/javaparser-core/src/main/java/com/github/javaparser/ast/nodeTypes/NodeWithVariables.java#L124) does not fire since level = 0 and the reported array level of PrimitiveType is also 0.

I am using the Maven release version 3.5.11 of JavaParser.

```Java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.type.PrimitiveType;
import com.github.javaparser.ast.type.Type;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;

public class Test {
  public static void main(String[] args) throws Exception {
    CompilationUnit template = JavaParser.parse("class A {float a, b, c, d;}");
    template.accept(new VoidVisitorAdapter<Void>() {
      Type intType = PrimitiveType.intType();

      public void visit(FieldDeclaration n, Void arg) {
        n.getVariables().forEach(vd -> {
          vd.getType().replace(intType);
        });
      }
    }, null);
  }
}
```

**Comment by matozoid** [comment]
Hm. @ftomassetti - the triggered property notifications throws an exception for this valid case. How can we fix this?

**Comment by httpdigest** [comment]
Besides that exception, I found it rather strange that in a FieldDeclaration the type is actually _not_ owned by this FieldDeclaration but instead contained and repeated in the VariableDeclarator's.
From what _seems_ logical, the type should only be on the FieldDeclaration, as it is done [in this production](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4#L336). So, one could actually not accidentally use different types on the variable declarations inside of the same FieldDeclaration, which seems inconsistent with Java's grammar and I actually do not know what should/will get produced then.
Maybe this was designed that way, because JavaParser makes no distinction between a variable declaration on a field and a local variable declaration inside of a method, so in the latter case it needs the type in each variable declaration since there is no LocalVariableDeclaration, unlike how it is done [in this production](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4#L734).

**Comment by matozoid** [comment]
@ftomassetti I'm starting to think that this:
```java
    @DerivedProperty
    default Type getMaximumCommonType() {
```
should be an `Optional<Type>` because you can set the types of the variables to incompatible types - which is a consequence of keeping the type on the variables themselves. Lexical preservation should be able to handle this by, I don't know - ignoring it or so?

**Comment by matozoid** [comment]
@httpdigest check out the paragraph on "Array support changes" in the [migration guide](https://github.com/javaparser/javaparser/wiki/Migration-Guide) for the explanation. If you like I can find the issues and PR's with the rather lenghty discussion on why exactly this way was chosen.

**Comment by httpdigest** [comment]
@matozoid Thanks for the clarification!

**Comment by matozoid** [comment]
Thank you for reporting this, even though I'm a bit peeved that you found a bug like this in the core ;-)

**Comment by httpdigest** [comment]
You're welcome. I was surprised about this, too :-) and a bit disappointed that, once I saw JavaParser as a great candidate to cover my requirements, tried the first and simplest case I needed to support, hit run, and... boom! :-(
But there is of course a workaround for me right now. Just declare the fields individually.

**Comment by ftomassetti** [comment]
> I want to use JavaParser to parse a "template Java" source file and generate multiple source files > from it mostly with simply changed field types

This seems a good idea and one of my goals would be to create a "template java language", with placeholders for the mutable parts. Not there yet.

> So, one could actually not accidentally use different types on the variable declarations inside of 
> the same FieldDeclaration, which seems inconsistent with Java's grammar and I actually do not 
> know what should/will get produced then.

I am also not a big fan of having the type for field declarations work in this way, but there were many different things we had to consider and finally we ended up with this design as a compromise. What I would say is that if you try to build illegal code you should get an exception, but a way more appropriate exception. Would it make sense?

**Comment by matozoid** [comment]
@ftomassetti - I've got a branch with placholder syntax that I'm working on. Remaining work is massaging the grammar to remove conflicts and creating a matching algorithm.

And indeed nobody loves this design. A side effect is sadly that it takes several setter calls before the type has been changed. So, it takes several set-calls to go from one valid state to the next. A setter throwing an exception for this is undoable since it is the obvious and only way to do it. There are a few more holes like this in JP, just to get out of the way of the user. We can alert the user later on though: in the PR I took the silent approach, honestly because I like seeing the `toString()` output next to a field in a debugger instead of a red exception, and because I'm not sure what the lex printer is doing.

Alternatives: redesign the API again (not recommended ;-) ), or create a sensible alternative to calling all these setters.

**Comment by ftomassetti** [comment]
@matozoid I am looking forward to see the placeholder stuff!

I guess we can redesign the API in JavaParser 4, but in the meantime we can add some methods that do the changes all at once, without moving through inconsistent states?

**Comment by matozoid** [comment]
#591 for the pattern matching :-) It's pretty nice for complex matching! Buuuuut most of the time a simple textual template engine (or String.format) will do fine.

If we seriously want to redo the API, we'll need to restart the discussion on how to deal with arrays. If this is what you want, open an issue ;-)

Opened --> #1362
