### ISSUE TITLE
Parsing java.io.FileDescriptor: Try with resources only supports variable declarations

### ISSUE THREAD

**Issue by dhardtke** [javaparser/javaparser#1361]
I was just trying to parse "java.io.FileDescriptor" from the JDK included src.zip and this is what I get:

> Exception in thread "main" com.github.javaparser.ParseProblemException: (line 217,col 13) Try with resources only supports variable declarations.

I believe it is related to `synchronized void closeAll(Closeable releaser) throws IOException {` and 
`try (releaser) {`

Apart from that all files from the JRE (java.base) are parsable 👍

**Comment by ftomassetti** [comment]
Nice, thank you for reporting this. 

I wonder if it is just a problem of language level set in ParserConfiguration. Can you try setting the validator to Java9?

@matozoid will know better about this stuff :)

**Comment by matozoid** [comment]
What @ftomassetti says, with this background:
https://matozoid.github.io/2017/04/11/enable-java-9-support.html
https://matozoid.github.io/2017/04/11/validations.html
:-)

**Comment by dhardtke** [comment]
That seems to work perfectly, awesome!

Also thanks for the quick response.
