### ISSUE TITLE
Create utility methods to change variable declaration type in one go

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1362]
Since we can have `int a, b, c;` and the type `int` is stored three times: in a, b, and c, the only way to change the type to something else is to set the new type on a, b, and c separately. That takes three method calls, and the AST state is inconsistent until they are all done.

Create a utility method that takes a type and sets it on all the variables, keeping the array brackets consistent, so `int[] a[], b;` with type changed to `float` will become `float[] a[], b;`, not `float a, b;`.

Document well that the `Type` that is being set will be cloned before inserting it into the AST, so the one that the user supplies will never end up in the AST.

**Comment by rafid009** [comment]
is a method which changes the type of multiple variable declarations exist?

**Comment by matozoid** [comment]
Not yet, this issue is still open. It would probably become... `NodeWithVariables.setCommonType(Type type)`. It would replace the element types of all the variables with the new type - this way the array depth will be retained.

**Comment by matozoid** [comment]
... It would be good if it checked if the type needs to be replaced at all, so do an equals first.

**Comment by matozoid** [comment]
I think the expected action for setCommonType would be to erase the common array brackets. Let's call it setElementType instead so that expectation is hopefully not there.

**Comment by matozoid** [comment]
The reason that there is no "setType" is because a variable declaration does not have a type. The variables declared in the declaration have a type, and thanks to array brackets, they can all have a different type.

Aw whatever, I'll just make a simple "setAllTypes" that sets a specific type to all variables.
