### ISSUE TITLE
StackoverflowError when using a custom TypeSolver reading JRE sources

### ISSUE THREAD

**Issue by dhardtke** [javaparser/javaparser#1364]
I wrote a custom TypeSolver that reads .java source files directly from the "src.zip" distributed with the JDK.
In production, that particular TypeSolver provokes a StackoverflowError inside JavaParser / JavaParserSymbolSolver:
>at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAllFields(JavaParserClassDeclaration.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.lambda$getAllFields$1(JavaParserClassDeclaration.java:105)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)

Code is probably most useful, so here is my little reproduction class:

```java
public class Reproduction {
    public static void main(String[] args) throws IOException {
        final CompilationUnit compilationUnit = JavaParser.parse(String.join(System.lineSeparator(),
                "public class Reproduction {",
                "    public void printSomething() {",
                "        System.err.println();",
                "    }",
                "}"));

        final JavaParserFacade facade = JavaParserFacade.get(new ReproductionJreSourcesTypeSolver());
        compilationUnit.accept(new MethodCallVisitor(), facade);
    }

    private static class ReproductionJreSourcesTypeSolver implements TypeSolver {
        private ZipFile zipFile;

        ReproductionJreSourcesTypeSolver() throws IOException {
            final String javaHome = System.getProperty("java.home", null);
            this.zipFile = new ZipFile(Paths.get(javaHome, "lib", "src.zip").toFile(), ZipFile.OPEN_READ);
        }

        @Override
        public TypeSolver getParent() {
            return null;
        }

        @Override
        public void setParent(final TypeSolver parent) {
        }

        @Override
        public SymbolReference<ResolvedReferenceTypeDeclaration> tryToSolveType(final String name) {
            SymbolReference<ResolvedReferenceTypeDeclaration> result = SymbolReference.unsolved(ResolvedReferenceTypeDeclaration.class);

            final String filename = name.replaceAll(Pattern.quote("."), "/") + ".java";
            System.out.printf("Trying to solve %s from filename %s%n", name, filename);

            final ZipEntry entry = zipFile.getEntry(String.format("%s/%s", "java.base", filename));

            if (entry != null) {
                try {
                    final CompilationUnit compilationUnit = JavaParser.parse(zipFile.getInputStream(entry));

                    final String[] nameElements = name.split("\\.");

                    for (int i = nameElements.length; i > 0; i--) {
                        final StringBuilder typeName = new StringBuilder();

                        for (int j = i - 1; j < nameElements.length; j++) {
                            typeName.append(nameElements[j]);
                        }

                        final Optional<TypeDeclaration<?>> astTypeDeclaration = Navigator.findType(compilationUnit, typeName.toString());

                        if (astTypeDeclaration.isPresent()) {
                            result = SymbolReference.solved(JavaParserFacade.get(this).getTypeDeclaration(astTypeDeclaration.get()));
                        }
                    }
                } catch (IOException ignored) {
                }
            }

            return result;
        }
    }

    private static class MethodCallVisitor extends VoidVisitorAdapter<JavaParserFacade> {
        @Override
        public void visit(final MethodCallExpr n, final JavaParserFacade arg) {
            System.out.println(arg.solve(n));

            super.visit(n, arg);
        }

        public void visit(final ObjectCreationExpr n, final JavaParserFacade arg) {
            System.out.println(arg.solve(n));

            super.visit(n, arg);
        }
    }
}
```
I couldn't figure out why this happens, for some reason the Visitor leads to solving of "java.lang.Object" over and over again (see the output).

PS:
When the JreTypeSolver works flawlessly, I thought of sharing it with other users (maybe I'll open a PR). Also, I wrote another TypeSolver that is capable of resolving types from JAR files / any files on the classpath.

**Comment by dhardtke** [comment]
Maybe this PR is related? I'm not sure:
https://github.com/javaparser/javasymbolsolver/pull/164

**Comment by dhardtke** [comment]
Okay, so essentially `com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration#getAllFields` does this:
`getAncestors().forEach(ancestor -> ancestor.getTypeDeclaration().getAllFields().forEach(f -> {`, i.e., it calls `getAllFields()` on each ancestor, which means: for some reason when using the custom TypeSolver, the code runs into this circular execution because in `getAllFields()` it gets all ancestors, receives each field of each ancestor, ...

I believe this is all happening because I am returning something that is getting resolved to a `JavaParserClassDeclaration` itself, instead of what the `ReflectionTypeSolver` returns.

I did manage to fix the problem quickly (but dirty as well) by overriding the `JavaParserClassDeclaration`:

```java
if (result.getCorrespondingDeclaration() instanceof JavaParserClassDeclaration) {
    // Notice: this is very (!) unsafe
    result = SymbolReference.solved(new JavaParserClassDeclaration((ClassOrInterfaceDeclaration) astTypeDeclaration.get(), this) {
        @Override
        public List<ResolvedFieldDeclaration> getAllFields() {
            if (this.getQualifiedName().equals("java.lang.Object")) {
                return Collections.emptyList();
            }

            return super.getAllFields();
        }
    });
}
```

Now, all I need is to redo this in a nice manner to open a PR in order to incorporate it into the symbolsolver-core.

**Comment by ftomassetti** [comment]
This happen because you are trying to parse the source code of java.lang.Object, right? I was not expecting people to try that

**Comment by matozoid** [comment]
Good test case though! :-D
