### ISSUE TITLE
Is it Possible to crawl all the .java files with parser as we can do with web pages?

### ISSUE THREAD

**Issue by mashalahmad** [javaparser/javaparser#1366]
I am trying to extract e.g all the methods signatures from any open source java project e.g. JHotDraw is it possible with parser? I have extracted methods signature from a single java file though

**Comment by matozoid** [comment]
The question in the title: take a look at `SourceRoot`.

Please take a moment to read the manual: https://leanpub.com/javaparservisited (it's fine if you pay $0)

**Comment by matozoid** [comment]
Assuming this is answered.
