### ISSUE TITLE
Generate Javadoc for version 2.0.0

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#137]
I think it would be useful to have Javadoc for each version available on the website. Currently we have just an old version marked as "current". I think we should always have the current one (corresponding to master) and a version for each release (maybe each minor release but not each bugfix release)

**Comment by SmiddyPence** [comment]
Now using this provider:

http://www.javadoc.io/doc/com.github.javaparser/javaparser-core

**Comment by ftomassetti** [comment]
Great stuff!
