### ISSUE TITLE
Javadoc output bug (3.5.12)

### ISSUE THREAD

**Issue by noties** [javaparser/javaparser#1371]
Given the original javadoc:

```java
    /**
     * Gets one of the buttons used in the dialog. Returns null if the specified
     * button does not exist or the dialog has not yet been fully created (for
     * example, via {@link #show()} or {@link #create()}).
     *
     * @param whichButton The identifier of the button that should be returned.
     *            For example, this can be
     *            {@link DialogInterface#BUTTON_POSITIVE}.
     * @return The button from the dialog, or null if a button does not exist.
     */
```

After processing it by adding a tag (`javadoc.addBlockTag(String,String)`):

```java
    /**
     * Gets one of the buttons used in the dialog. Returns null if the specified
     * button does not exist or the dialog has not yet been fully created (for
     * example, via {@link #show()} or {@link #create()}).
     *
     * @param whichButton The identifier of the button that should be returned.            For example, this can be            {@link DialogInterface#BUTTON_POSITIVE}.
     * @return The button from the dialog, or null if a button does not exist.
     * @mytag 3
     */
```

<em><sup>*</sup> Scroll to the right</em>

I think #907 might be a culprit here. New lines are definitely removed, but indent is kept.

 Is there an option to _keep_ original javadoc?

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by ftomassetti** [comment]
In #907 I wrote _I would say we can throw away all the EOLs that we can reconstruct later_. Maybe we have been over enthusiastic :D

**Comment by matozoid** [comment]
I'll take a look

**Comment by matozoid** [comment]
Yeah, I'm going to make it consistent again and keep the EOL's in the blocktags.

**Comment by matozoid** [comment]
@noties could you take a look at the changes in the unit tests in the PR and say if it's better this way?

**Comment by noties** [comment]
@matozoid Hey! I have just checked it out. Looks great and works as expected 👍 

BTW, I wanted to say thanks for this amazing library. So great 🙌 !

**Comment by matozoid** [comment]
Cool! It'll be in the next release, next weekend :-) Thanks for the compliments!
