### ISSUE TITLE
How to get the line number from ClassTree

### ISSUE THREAD

**Issue by vidyat11** [javaparser/javaparser#1373]
I have migrated JavaParser  2.3 into latest version 3.5.11  . In 2.3 version we can get  **int n=n.getBeginLine()**.How to get line number in latest version ..

**Comment by matozoid** [comment]
Hi! Take a look at `n.getRange()` or `n.getTokenRange()`.

**Comment by vidyat11** [comment]
Thanks for your Reply..

**Comment by matozoid** [comment]
Did it help?

**Comment by vidyat11** [comment]
Yah its helped .. i can get line number n.getBegin().get().line....i have changed int n=  n.getBegin().get().line

**Comment by matozoid** [comment]
Good!
