### ISSUE TITLE
JSON ouput has multiple keys ("type") under the same dict

### ISSUE THREAD

**Issue by wwt17** [javaparser/javaparser#1379]
I found this part of JSON when I was trying to parse a method.
```javascript
{
  "parameters": [
    {
      "type": "Parameter",
      "isVarArgs": "false",
      "name": {
        "type": "SimpleName",
        "identifier": "db"
      },
      "type": {
        "type": "ClassOrInterfaceType",
        "name": {
          "type": "SimpleName",
          "identifier": "HighlyAvailableGraphDatabase"
        }
      }
    }
  ]
}
```
You can see there are two identical keys called "type". While this is not allowed according to JSON standard. If I parse this JSON, it will get only the last one.

**Comment by ftomassetti** [comment]
Right! Thank you for reporting this

**Comment by matozoid** [comment]
Any ideas on what the output should be then?

**Comment by wwt17** [comment]
I think just change the string "type" to some other name (for example, "node") in the method output of class JSONPrinter will solve this issue.

**Comment by matozoid** [comment]
Ah, I see now, I thought it was a different problem.

**Comment by MysterAitch** [comment]
+1 

I have come up against this recently (though I don't see it present in the snippet quoted above). Solved it locally by changing "type" to "_type" to avoid the key collision on the assumption that there is unlikely to be an attribute/key of that name naturally occurring. Seems to be working well enough here so far.

**Comment by matozoid** [comment]
Note that this doesn't have a high priority, because the JSON is meant to be *looked at* to examine the AST, not to be processed.

**Comment by matozoid** [comment]
@MysterAitch - there is now a Json serialization module.

**Comment by matozoid** [comment]
... and I've renamed type to _type.
