### ISSUE TITLE
Is it possible to extract anonymous class?

### ISSUE THREAD

**Issue by t-benze** [javaparser/javaparser#138]
Hi,
I want to parse a project in which there are inner anonymous class. Currently I traverse the CompilationUnit as follow:

```
for(TypeDeclaration type : cu.getTypes()) {
    System.out.println("type: " + type.getName());
    for(BodyDeclaration body : type.getMembers()) {
        if(body instanceof TypeDeclaration) {
           TypeDeclaration subType = (TypeDeclaration)body;
           System.out.println("subtype: " + subType.getName());
        }
    }
}
```

However, it can not get the anonymous class I defined. Is this feature is supported by javaparser? If it is, how can I do that? Thanks in advance.

**Comment by ftomassetti** [comment]
Well, inner anonymous classes can be hidden anywhere in the code so you may want to recursively find all the nodes contained in a certain CompilationUnit (1) and then look for nodes representing the anonymous classes (2). 
1. To find all the nodes recursively I would use the method `getChildrenNodes` of Node (CompilationUnit and all other classes extend Node)
2. I am sure we have nodes for that (we can parse every kind of Java code), I just do not remember what types of nodes they could be, you may want to try.

Please feel free to ask other questions if this answer does not help

**Comment by sebastiankirsch** [comment]
You are looking for ObjectCreationExpr instances that have an anonymous
class body - accessible via getAnonymousClassBody().

Federico Tomassetti notifications@github.com schrieb am Mi., 13. Mai 2015
um 11:43 Uhr:

**Comment by t-benze** [comment]
Thank you very much for the direction. I think this can solve my problem. 
I also have a suggestion. Maybe you can lift up the anonymous class as a member of the type within which it's created, and name it like $1, $2 as the compiler does. So users can access it via the getMembers() API. I think this is intuitive as anonymous class can really be treated as a member of its owner, and it's easier to do it when parsing.

**Comment by ftomassetti** [comment]
Well, I think the anonymous classes are not members of the class so, we should not expose them though `getMembers`. However we could create a new method called `getAnonymousClasses` or something like that. I think that in general we should provide some helper functions to navigate the tree. For example a function to retrieve all the nodes of a certain type in a CompilationUnit. I am not sure if it would be better to do that in the nodes of the AST or in an external class, like ASTHelper
