### ISSUE TITLE
How i can add primitive type in FieldDeclaration 

### ISSUE THREAD

**Issue by vidyat11** [javaparser/javaparser#1380]
Hi

In this same example i am try to add new field String arg=null;

how can i add primitive type ...
```java
public static void main(String[] args) {
CompilationUnit cu = JavaParser.parse("class X{ int a; int b; int c;} ");

    	cu.getClassByName("X").ifPresent(coid -> {
    		
        VariableDeclarator variables = new VariableDeclarator();        
        variables.setName("arg");
        variables.setInitializer(new NameExpr("null"));
		FieldDeclaration fieldDeclaration = new FieldDeclaration().addVariable(variables);	
        coid.getMembers().add(0, fieldDeclaration);

        System.out.println(coid);
    });
}
```

**Comment by matozoid** [comment]
Hi! Thanks for opening a new issue :-)

Hints: `VariableDeclarator` has a `type` field, and there is a `PrimitiveType` node type.

Here's an interesting article: https://matozoid.github.io/2017/12/13/inspecting-an-ast.html

**Comment by vidyat11** [comment]
Great,  Solved the problem. Thanks a lot :)

**Comment by vidyat11** [comment]
Have one more doubt ..how can we add **Static variable**

**Comment by matozoid** [comment]
`static` is just a modifier, you should be able to set that on the `FieldDeclaration`.

**Comment by vidyat11** [comment]
Thanks alot:)
