### ISSUE TITLE
first example in the site is wrong?????

### ISSUE THREAD

**Issue by shikida** [javaparser/javaparser#1383]
CompilationUnit compilationUnit = JavaParser.parse("class A { }");
ClassOrInterfaceDeclaration classA = compilationUnit.getClassByName("A");

shouldn't be

CompilationUnit compilationUnit = JavaParser.parse("class A { }");
Optional<ClassOrInterfaceDeclaration> classA = compilationUnit.getClassByName("A");

?

This scares the newbie to the death

**Comment by ftomassetti** [comment]
Extra question marks scare maintainers to the death :)

Yes, the API changed so `getClassByName` is returning an Optional of ClassOrInterfaceDeclaration. We should update that. Thanks for reporting this.

**Comment by matozoid** [comment]
Thanks for your feedback! Sorry for scaring you to the death.

The samples were checked and updated.
