### ISSUE TITLE
second example from the site is wrong????

### ISSUE THREAD

**Issue by shikida** [javaparser/javaparser#1384]
compilationUnit.getNodesByType(FieldDeclaration.class);

is a deprecated method?????

no javadoc????

c'mon

**Comment by ftomassetti** [comment]
Hi Leo.
We are sorry if we did not manage to provide all necessary javadoc for the thousands of methods we wrote and share with the community in our free time. We are also users of other projects and we understand it can be disappointing. We really could use some help, so feel free to submit a pull request to help us improve the state of the project. In the meantime we consider this piece of feedback as a valuable contribution and we thank you for that.

**Comment by matozoid** [comment]
The samples were checked and updated.
