### ISSUE TITLE
while parsing its not  restore whole orphan comments in Class structure.

### ISSUE THREAD

**Issue by vidyat11** [javaparser/javaparser#1385]
Hi 

While parsing its not restore whole orphan comments 

Eg;Before 
```java
public class a {
	
	/**
	* 
	 * @param a
	* @param b
	* @return
	*/
	    public int add(int a, int b) {
	        // Noncompliant
	        a = a + b;
	        // Noncompliant
	        // Seems like the parameter is returned as is
	        return a;
	    }
	}
```

After::
```java
public class a {

    /**
     * @param a
     * @param b
     * @return
     */
    public int add(int a, int b) {
        // Noncompliant
        a = a + b;
        // Seems like the parameter is returned as is
        return a;
    }
}
```

**Comment by jlerbsc** [comment]
In version 3.16.1 this issue is corrected and the parsing result is

    public class a {

    /**
     * @param a
     * @param b
     * @return
     */
    public int add(int a, int b) {
        // Noncompliant
        a = a + b;
        // Noncompliant
        // Seems like the parameter is returned as is
        return a;
    }
}
