### ISSUE TITLE
The new expression print with one more white space

### ISSUE THREAD

**Issue by beihaifeiwu** [javaparser/javaparser#140]
When I create a new expression for source print, I expected:

```
Des des = new Des();
```

But in the result I got:

```
Des des = new  Des();
```

there are two white space between 'new' and 'Des();', Is this normal or a bug ?

**Comment by ftomassetti** [comment]
From a first look it seems a bug:

``` java
    @Override public void visit(final ObjectCreationExpr n, final Object arg) {
        printJavaComment(n.getComment(), arg);
        if (n.getScope() != null) {
            n.getScope().accept(this, arg);
            printer.print(".");
        }

        printer.print("new ");

        printTypeArgs(n.getTypeArgs(), arg);
            printer.print(" ");

        n.getType().accept(this, arg);

        printArguments(n.getArgs(), arg);

        if (n.getAnonymousClassBody() != null) {
            printer.printLn(" {");
            printer.indent();
            printMembers(n.getAnonymousClassBody(), arg);
            printer.unindent();
            printer.print("}");
        }
    }
```

You see that there is a space after new and then another space is printed after `printTypeArgs`. I guess we could remove that second space because anyway we do not want a space after the type args.

**Comment by ftomassetti** [comment]
and thank you for reporting this!

I think we should provide also some tests for this bug fix, I can do that over the week-end, but if everyone else want to jump in and do it please feel free: first coming, first merged :D

**Comment by beihaifeiwu** [comment]
Thanks for your answer, I am working on a project that user your parse to do some source merge work for Java, I think as long as this project going on, more bugs will be report, and I am glad to see your project growing!

**Comment by beihaifeiwu** [comment]
Hi ftomassetti, I have checked the new release 2.1.0, but this issue is still exist. Could you give it a shedule ?

**Comment by ftomassetti** [comment]
Hi @beihaifeiwu sorry for the delay. The patch is now being merged in the master branch but there is not a version released after the fix. I think you can specify in your project a dependency on our git repository (see here http://stackoverflow.com/questions/20161602/loading-maven-dependencies-from-github) or you should wait for us to release the new version. I asked to the other contributors what they think about releasing soon a new bugfix version of JavaParser but I cannot give you a precise schedule.
Can I help you in any way? Feel free to ask other questions, comments, etc.

**Comment by beihaifeiwu** [comment]
Thanks for your reply, I'm not very thirsty for the new release, but I'll keep my eye on the progress
