### ISSUE TITLE
Feature request: implement ClassOrInterfaceType.getFullyQualifiedName() or similar

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1406]
Consider this piece of code:

`Foo foo = new com.something.Foo();
`

Here `com.something.Foo` on the right side is a `ClassOrInterfaceType`. Its `getName()` method will return a `SimpleName` representing `Foo`, while its `getScope()` method will return another `ClassOrInterfaceType` representing `com.something`. This latter `ClassOrInterfaceType` object will return `something` when `getName()` is called, and it will return yet another `ClassOrInterfaceType` object representing `com` when its `getScope()` method is called.

What I want is to simply retrieve the fully qualified name `com.something.Foo` as a String. As far as I can see I have two options:

- I could simply use `getTokenRange()` on the outermost `ClassOrInterfaceType` object, and convert that to a String... works, but it feels kind of hacky. :/
- I could write a method that takes a `ClassOrInterfaceType` and constructs the desired String recursively by concatenating the result of the recursive call (using `getScope().get()` as argument), a dot, and the result of `getName()`. But somehow it feels like I shouldn't have to write such a method, as it somehow logically belongs to JavaParser. :wink:

Ideally, `ClassOrInterfaceType` would offer a method `getFullyQualifiedName()` that returns a `Name` (instead of a `SimpleName`). That would be nice. :smiley: 

When I look at the larger picture, I assume it would probably be cleaner if `ClassOrInterfaceType` would implement not only `NodeWithSimpleName`, but also `NodeWithName`. But then these two interfaces would have to be refactored such that the method names that they require do not clash. For instance, instead of both interfaces requiring a method `getName()`, `NodeWithSimpleName` would require `getSimpleName()` and `NodeWithName` would require `getName()`.

I would love to hear your thoughts on this. :smiley:

**Comment by malteskoruppa** [comment]
Ah, well, I guess the best option would be to simply call `asString()` on the `ClassOrInterfaceType`. :grimacing: I didn't see the wood for the trees.

I guess this would be the way to go? :smiley:

**Comment by matozoid** [comment]
I wanted to give a lecture on how we don't know whether the scope is a class or a name, but I guess it doesn't matter and yes, `asString()` will help you because it is implemented to do the thing that people would like `toString()` to do, but doesn't :-)

**Comment by malteskoruppa** [comment]
I'll admit that the difference between `toString()` and `asString()` is not very clear to me: The Javadoc of `toString()` states _"Return the String representation of this node."_ and there is unfortunately no Javadoc for `asString()`. However, I just had a look at the source code: while `asString()` seems to be an implementation of the recursive algorithm that I had mentioned in the second bullet point above, `toString()` seems to invoke a `PrettyPrinterVisitor` that prints a lot more stuff, like comments and annotations too. Is that right?

However, I also noticed that `asString()` prints type arguments if present. I don't want that, I only need that fully qualified name... I guess I will have to write my own helper function in the end, but that's fine.

I'm not sure about what you mean by "we don't know whether the scope is a class or a name"... could you please explain? :smiley:

**Comment by matozoid** [comment]
- it hasn't been documented yet, I am planning to write a blog on it. Your assumption is correct though.
- yep, what it does is more or less arbitrary.
- It's easily explained by `a.b.C` and `a.B.C`. The parser doesn't know the difference between "class C in package a.b" and "class C in class B in package a"...

**Comment by malteskoruppa** [comment]
- Oh, cool, I look forward to your blog post! :smiley: 

- Sure, but the parser doesn't have to know. I simply would like the parser to give me the fully qualified name. Basically, just give me `a.b.c` and let me worry about what `a`, `b`, and `c` are. :) Currently there is no method that just gives me `a.b.c`. `asString()` comes close, though, and I can work with it. I potentially need to cut off the type arguments, though, i.e., what I'm actually interested in is something like `-1 == asString().indexOf('<') ? asString() : asString().substring(0, asString().indexOf('<'))`. :wink: (note: untested, and I wouldn't do it like that, of course... most likely, I'd copy&paste the `asString()` implementation and remove the type arguments printing part).

**Comment by matozoid** [comment]
We don't have to know for asString(), that's why I decided not to give the lecture ;-)

**Comment by matozoid** [comment]
Post is up: https://matozoid.github.io/2018/02/19/asstring-tostring-gdas-ppv-csm.html :-)

**Comment by matozoid** [comment]
Looks like this is answered :-)
