### ISSUE TITLE
ObjectCreationExpr#resolveInvokedConstructor always throws

### ISSUE THREAD

**Issue by dhardtke** [javaparser/javaparser#1411]
Hey there,

I am slowly migrating from JavaParserFacade but I stumbled upon a problem where type solving the invoked Constructor does not work:

> com.github.javaparser.ast.expr.ObjectCreationExpr
```java
public ResolvedConstructorDeclaration resolveInvokedConstructor() {
    return getSymbolResolver().resolveDeclaration(this, ResolvedConstructorDeclaration.class);
}
```

`JavaSymbolSolver`s resolveDeclaration() method, however, does not contain an if checking for Nodes which are of type `ObjectCreationExpr` and, hence, I am stuck to the following:
```java
final List<ResolvedConstructorDeclaration> constructors =
        resolvedType.asReferenceType().getTypeDeclaration().asClass().getConstructors();

final ResolvedConstructorDeclaration constructorDeclaration = 
ConstructorResolutionLogic.findMostApplicable(constructors,
        n.getArguments().stream().map(Expression::calculateResolvedType)
        .collect(Collectors.toList()), this.typeSolver)
        .getCorrespondingDeclaration();
```

which is essentially what the JavaParserFacade is doing as well.

**Comment by ftomassetti** [comment]
Right, we should fix that. Thank you for reporting this!

**Comment by jlerbsc** [comment]
In JP 3.16.1 JavaSymbolSolver.resolveDeclaration(..) contains a an if checking for Nodes which are of type ObjectCreationExpr so i think this issue could be closed.

    if (node instanceof ObjectCreationExpr) {
            SymbolReference<ResolvedConstructorDeclaration> result = JavaParserFacade.get(typeSolver).solve((ObjectCreationExpr) node);
            if (result.isSolved()) {
                if (resultClass.isInstance(result.getCorrespondingDeclaration())) {
                    return resultClass.cast(result.getCorrespondingDeclaration());
                }
            } else {
                throw new UnsolvedSymbolException("We are unable to find the constructor declaration corresponding to " + node);
            }
        }
