### ISSUE TITLE
VariableDeclarator unable to parse multiple declaration separated with ',' (comma) like "int nra, nca;" 

### ISSUE THREAD

**Issue by deepsidhu1313** [javaparser/javaparser#1414]
I guess there is bug in the code, my visitor class is unable to parse beyond nra in given below in last line of code.

        import java.util.Random;  /* for random number */

        import java.lang.*;		/* for Math.abs funciton  */

        import in.co.s13.sips.lib.*;

        class MatMul {

            public static void main(String args[]) {
                 SIPS sim = new SIPS("MatMul");
                double a[][] = new double[50][50];
                double b[][] = new double[50][50];
                double c[][] = new double[a[0].length][b[1].length];

                int nra, nca;

If i comment out my `visit(VariableDeclarator n, Object Args)` method everything works fine. but i need this info.

**Comment by deepsidhu1313** [comment]
After further investigation, `get()` doesn't work on `n.getInitializer()` like `n.getInitializer().get()` where `n` is `VariableDeclarator` . is there a way to just return null or empty string value if initializer doesn't exist.

**Comment by deepsidhu1313** [comment]
Fixed it using `((n.getInitializer().isPresent() ) ? n.getInitializer().get() : "")`. Sorry for trouble. :) Hope this will help any other user.

**Comment by matozoid** [comment]
Here's a nice article on `Optional`: http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html - or maybe this: http://www.baeldung.com/java-optional
