### ISSUE TITLE
Problem finding file with JavaParserTypeResolver

### ISSUE THREAD

**Issue by EFregnan** [javaparser/javaparser#1417]
Good afternoon. I am sorry to bother you with this issue. 
I have the following problem. I wrote an application that uses JavaParser and Java Symbol Solver to extract information from the classes of an external project, cloned from github. 

I have the following code:
```java
public List<String> objectCreationSolve() throws IOException {
		List<String> createdObjects = new ArrayList<String>();
		CombinedTypeSolver typeSolver = new CombinedTypeSolver();
		typeSolver.add(new ReflectionTypeSolver());
		
		typeSolver.add(new JavaParserTypeSolver(new File("/User/Documents/GitHub/Auto-ordering-code-changes/lucene-solr/lucene/spatial3d/src/")));
		
		CompilationUnit cu = JavaParser.parse(commitCode);
		List<ObjectCreationExpr> objectCreationReferences = Navigator.findAllNodesOfGivenClass(cu, ObjectCreationExpr.class);
		
		for(ObjectCreationExpr oc : objectCreationReferences) {
			try {
				System.out.println("objectCreationReferences: " +oc);
				createdObjects.add(JavaParserFacade.get(typeSolver).solve(oc).getCorrespondingDeclaration().getName());
				System.out.println("solved");
			}
			catch (UnsolvedSymbolException e) {
				System.out.println("error solving class name in new object: "+e.toString() + "Message: " + e.getMessage());
				createdObjects.add(e.getMessage().split("\\:\\s+")[1]);
			}
		}
		return createdObjects;
		}
```

The problem is that the typeSolver does not solve references to other classes in the project. I think the issue is in how I set the file of JavaParserTypeSolver, but I can not find a right configuration to make it work. Can you please help me?

**Comment by ftomassetti** [comment]
You should add entries for all the JARs of all the dependencies in your typesolver

**Comment by EFregnan** [comment]
Thank you. 
Is this the only way? Apparently the JARs are not included in the project repo and I'd have prefered not to generate them. 
Is not possible to make JavaParserTypeSolver find the right class just by setting the file given as parameter in a proper manner?

**Comment by ftomassetti** [comment]
I am talking about the dependencies: the library this project is using. You need them to be able to resolve symbols, otherwise there is no way to know how the classes used by this project are

**Comment by EFregnan** [comment]
Sorry, I am still confused about this. The projects does not use external libraries: a class only references other classes defined in the project. Is the Jar still needed? I can't understand which jar should be included in this case (since there are no Jars referring to external libraries).

**Comment by ftomassetti** [comment]
Which project are using examining? Lucene-solr? Can you give me a link to the project?

**Comment by EFregnan** [comment]
Yes, this is the link to the GitHub repository: https://github.com/apache/lucene-solr

An example of the problem that I have encoured is: 
 UnsolvedSymbolException{context='unknown', name='PlanetModel', typeSolver=null}Message: Unsolved symbol : PlanetModel

When in class GeoPolygonFactory I find the following: GeoCompositePolygon rval = new GeoCompositePolygon(planetModel);
It happens for other classes as well. However, planetModel is an instance of PlanetModel which is defined in "PlanetModel.java" in the same directory.

**Comment by ftomassetti** [comment]
You are specifying just one directory ("/User/Documents/GitHub/Auto-ordering-code-changes/lucene-solr/lucene/spatial3d/src/") where that module has obviously depends at least on the other modules of the same project. I do not know Lucene and unfortunately they are using ANT instead of anything sensible for dependency management but I would be surprised if they were not using dependencies at all... anyway at the very least you need to understand which modules spatial3d depends on and add such modules in your typesolver.

**Comment by EFregnan** [comment]
I added also the directories of the other modules and it worked (I still have to check exactly which dependecies are needed). 

Thank you very much for your time.
