### ISSUE TITLE
JsonPrinter sometimes outputs malformed JSON (multi-line comments)

### ISSUE THREAD

**Issue by clintgibler** [javaparser/javaparser#1421]
Hey there,

First off, thank you all for creating `javaparser`, it's awesome! Also, I'm a big fan of @ftomassetti's detailed blog posts on parsing languages (e.g. [Java](https://tomassetti.me/parsing-in-java/) or [Python](https://tomassetti.me/parsing-in-python/)).

I'm working on a tool that uses `javaparser` that I hope to open source in a few months.

## The Issue

I've been playing with `javaparser` and it's been great, but `JsonPrinter` seems to print out malformed JSON in certain cases, specifically with multi-line comments.

## Reproduction Steps

In my `pom.xml` I have:

~~~xml
<dependency>
    <groupId>com.github.javaparser</groupId>
    <artifactId>java-symbol-solver-core</artifactId>
    <version>0.6.0</version>
</dependency>
~~~

My `javaparser` code, based on @matozoid's [blog post](https://matozoid.github.io/2017/12/13/inspecting-an-ast.html), looks like:

~~~java
// JavaParserMain.java
...
CompilationUnit cu = JavaParser.parse(new FileInputStream("JsonPrintingExample.java"));
JsonPrinter printer = new JsonPrinter(true);
// Save result of printer.output(cu) to a file
~~~

A minimal example file that demonstrates the issue is:
~~~java
/*
 * Some comment
 */
public class JsonPrintingExample {
}
~~~

After running my `javaparser` code (listed above) on the example file, the resulting JSON is:
~~~json
{"type":"CompilationUnit","types":[{"type":"ClassOrInterfaceDeclaration","isInterface":"false","name":{"type":"SimpleName","identifier":"JsonPrintingExample"},"comment":{"type":"BlockComment","content":"
 * Some comment
 "}}]}
~~~

When you try to parse the file:
~~~bash
$ cat output.json | json_pp
invalid character encountered while parsing JSON string, at character offset 203 (before "\n * Some comment\n ...") at /usr/bin/json_pp5.18 line 45.
~~~

## Troubleshooting

I observe the same error when I remove the asterix before the comment text or when I move the comment onto just 2 lines, e.g.

~~~java
/*
 Some comment
 */
~~~
or
~~~java
/* Some comment
 */
~~~
However, the following results in valid JSON:
~~~java
/* Some comment */
~~~

## Potential Solutions

Would this be an easy fix in [JsonPrinter](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/JsonPrinter.java)?

I see #1353, which looks like you've run into some errors like this before- "so that we can use a real library and avoid silly escaping problems."

I've found [Google gson](https://github.com/google/gson) fairly easy to use in prior projects, but I'm not sure if it's a good fit here.

What do you all think?

Also, thanks in advance for your time! :)

**Comment by ftomassetti** [comment]
Wow @clintgibler thank you for the report and for the compliments, you made my day!

The problem with not using libraries is that so far JavaParser core has zero dependencies. So we are really careful on breaking that rule. @matozoid was thinking of moving the printers to a separate module where we would use dependencies more freely. In that case gson would be a strong candidate to be included

**Comment by matozoid** [comment]
#1353 is indeed the central issue for this. We're swamped in work, so if someone feels like picking that up, that would be great.

**Comment by clintgibler** [comment]
Heh, I'm glad @ftomassetti :) Sorry for the response delay, I was traveling.

I think it's great that JavaParser core has no dependencies, that makes sense why you'd want to move the printers to a separate module.

I understand that there are many tasks in progress, so rather than an ideal fix that involves creating a separate module, do you think it'd be possible to do a quick fix that mostly works?

I did a little more digging, and apparently the JSON spec requires escaping `\n` in String values (see Lightness Races in Orbit's answer on [StackOverflow](https://stackoverflow.com/questions/16690101/can-a-json-value-contain-a-multiline-string)).

As a temporary hack, I tried adding a 1-liner to do this  in JsonPrinter.java but the test case I created is still outputting invalid JSON. You can see my attempt in my fork of JavaParser [here](https://github.com/clintgibler/javaparser/commit/8d1d333c1d3861c7d93fa013c00246ce586ad6d6).

Am I putting the `replace()` in the wrong location or is there a better way to do this?

**Comment by ftomassetti** [comment]
Maybe `value = value.replace("\n", "\\\n");` should be `value = value.replace("\n", "\\n");`. Also, I am not sure how this interact with the following line

**Comment by matozoid** [comment]
Okay, PR coming up.

**Comment by clintgibler** [comment]
Good call @ftomassetti, and thanks for the quick turnaround time @matozoid! Nice catch, I forgot to add the `\r` replace as well. I've tested your changes locally and it seems to work for me.

**Comment by matozoid** [comment]
@clintgibler you become an expert in EOL's when you work on a multiplatform parser :-)

**Comment by clintgibler** [comment]
@matozoid Haha fair, I could see that :) 

By the way, how hard would it be to modify JsonPrinter to output some additional contextual information, like the start and end LOC for a MethodDeclaration or the LOC and column for some symbol?

I've written some hacky snippets to extract contextual info like that from a couple of different node types, but it would be much cleaner and better if I could just extend JsonPrinter a bit.

**Comment by clintgibler** [comment]
Also, thanks again for the quick response / help, much appreciated!

**Comment by matozoid** [comment]
@clintgibler it's not really written for extension - I say copy it to your own project and fiddle with it :-) Real improvements will come when we redesign them for real serialization.

**Comment by clintgibler** [comment]
@matozoid Heh, sounds good, will do :) I know you guys have a bunch of things you're working on, but do you have a rough idea of when you'll be redesigning things for real serialization? No pressure, I'm just trying to get an approximate feel for the timeframe.

**Comment by matozoid** [comment]
The timeframe would be at least a few months away, probably longer, unless someone new walks in and starts working on it. Everyone is just really, really busy :-/

**Comment by clintgibler** [comment]
No worries, I appreciate the heads up. Good luck on everything!
