### ISSUE TITLE
Best practice: How to find the precise type of a ResolvedPrimitiveType?

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1422]
Assume I have a variable `resolvedPrimitiveType` of which I know it is an instance of `ResolvedPrimitiveType`.

Now I want to find out what primitive type it is. Is it an int? Is it a boolean? etc. For each possible primitive type I want to do something different. Ideally I would like to use a switch statement. I could do this:

```
switch(resolvedPrimitiveType.describe()) {
  case "byte: // do something
  case "short": // do something
  case "char": // do something
  case "int": // do something
  case "long": // do something
  case "boolean": // do something
  case "float": // do something
  case "double": // do something
}
```

This works, however, I have to _hardcode_ the strings "byte", "short", etc. into my application. This is not very nice. I would prefer to be able to refer to some constant or enum defined by JavaParser.

I could do this:

```
if (resolvedPrimitiveType.equals(ResolvedPrimitiveType.BYTE)) {
  // do something
} else if (resolvedPrimitiveType.equals(ResolvedPrimitiveType.SHORT)) {
  // do something
} else ...
```

You get the point. :smiley: On the one hand, this is nicer because I don't have to hardcode any strings into my application. On the other, it's uglier since I can't use a switch statement, but I have to use this heavy if-else-if-else-if-else-...-construct.

Neither approach makes me really happy. :confused: What approach would you recommend? Did I maybe miss something? Or if not, would it be possible to declare public static final Strings in ResolvedPrimitiveType that contain the words "byte", "short", etc., for me to use in my switch statement? :smile:

**Comment by daanschipper** [comment]
I had the same issue and I settled on using 
```
private Pattern resolvePrimitiveType2(ResolvedPrimitiveType type) {
    if (BOOLEAN.describe().equals(type.describe())) {
        // do something
    } else if (BYTE.describe().equals(type.describe())) {
        // do something
    } else ...
}
```

**Comment by matozoid** [comment]
@ftomassetti should be able to answer this. In the meantime: how would you expect it to work?

**Comment by ftomassetti** [comment]
We could make ResolvedPrimitiveType an enum. Sending a PR

**Comment by malteskoruppa** [comment]
PR #1426 looks like a good solution, I look forward to trying it out and of course I will report back! :smiley:

**Comment by matozoid** [comment]
Prematurely closing this, reopen if necessary ;-)
