### ISSUE TITLE
Add methods that determine if something is a poly expression.

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1434]
These are mentioned in the JLS: https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html and it seems possible to analyse this without too much complexity. I needed it when trying to implement #1432.

**Comment by ftomassetti** [comment]
We should have some (unused) code to do so in JSS...

**Comment by matozoid** [comment]
Very nice!

**Comment by ftomassetti** [comment]
Look for `ExpressionHelper.isPolyExpression(Expression)`. Note that in some cases it could throw `UnsupportedOperationException`. Basically I copied entire portions of the JLS and tried to implement it piece by piece. However in that chapter there are parts that are not very clear to me

**Comment by ftomassetti** [comment]
I rectify: expect it to throw _UnsupportedOperationException_ most of the time. It is quite complex to implement...

**Comment by jlerbsc** [comment]
There is now an isPolyExpression in class Expression that is redefined in subclasses. Several cases were treated. This issue is related to #1743. This can be improved on a case-by-case basis
