### ISSUE TITLE
Problem with solving anonymous class

### ISSUE THREAD

**Issue by Eransho** [javaparser/javaparser#1436]
Hi,
First of all - great project!
I've encountered the following issue: When trying to solve a code containing an anonymous class usage, you get the following exception:
```
java.lang.ClassCastException: com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration cannot be cast to com.github.javaparser.resolution.declarations.ResolvedClassDeclaration
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:207)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:132)
```
The relevant part of the code I tried to solved:
```
TypeA obj = ...
obj.doSomething(new TypeIfc() {
    @Override
    public void noReturn() { ... }
	
    @Override
    public TypeIfc me() { ... }
});
```
Where `TypeIfc` is a local interface in the local project I'm trying to solve. 

I wasn't sure if this is a known issue or not, didn't find it on the list.
Cheers

**Comment by matozoid** [comment]
Thanks for the report!

**Comment by matozoid** [comment]
I tried to prepare a test case, but it doesn't fail. Can you help out? https://github.com/matozoid/javaparser/blob/issue_1436_solve_anon_class/javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue1436.java

**Comment by Eransho** [comment]
Instead of calling `oce.calculateResolvedType()` I used `JavaParserFacade.get(typeSolver).solve(oce)`. 
My motivation is to get the resolved type of both return type and params of methods/ctors calls

**Comment by matozoid** [comment]
Alright, which version are you using?

**Comment by Eransho** [comment]
3.5.15
