### ISSUE TITLE
Problem using addFieldWithInitializer

### ISSUE THREAD

**Issue by BriandUlysse** [javaparser/javaparser#1440]
Hello there,
(Sorry if my english is not perfect)

I've tried to create a new Field in a class, so at first I tried with the method addField as :
`myClass.addField(String.class, nameVar)`
I also tried to use the parameter modifier using it like this :
`myClass.addField(String.class, nameVar,Modifier.PUBLIC)`
But It didn't work, I had to create a table Modifier[] with my Modifier.PUBLIC in it, not sure if it's how it's suppose to work, but it work well.

Now I try to use addFieldWithInitializer instead, but this method dosen't have as much overload than the previous one, so I have to go with the "addFieldWithInitializer(Type, String, Expression, Modifier...)".

Firstly, it didn't look like it's possible to instantiate the type Type, and this type realy confuse me, the 2 other parameter aren't a problem, but for the last one, using the table I was using previously didn't work anymore.

This is how I'm trying to use it now :
`myClass.addFieldWithInitializer(Type.class.cast(String.class), nameVar, myInitializer,myTableModifier)`

The error I have is :
> The method addFieldWithInitializer(Type, String, Expression, Modifier...) in the type NodeWithMembers<ClassOrInterfaceDeclaration> is not applicable for the arguments (Type, String, String, Modifier[])

I want to pointed out that it's kind of weird that you can't use addFieldWithInitializer just like addField but with only the Expression for the initialization to specify.

I'm not really familiar with JavaParser, so maybe I'm doing it wrong, eventually, I would like to know if there is an other alternative to create a Field initialized with a certain value.

Thank you!

**Comment by matozoid** [comment]
Hi!

Here are some samples:

```java
import com.github.javaparser.ast.CompilationUnit;
// Did you use the right import?
import com.github.javaparser.ast.Modifier;

public class Test {
    public static void main(String[] args) {
        CompilationUnit compilationUnit = new CompilationUnit();
        compilationUnit
                .addClass("X")
                .addField(String.class, "abc", Modifier.PUBLIC);
        System.out.println(compilationUnit);
    }
}
```

```java
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Modifier;

import static com.github.javaparser.JavaParser.parseExpression;
import static com.github.javaparser.JavaParser.parseType;

public class Test {
    public static void main(String[] args) {
        CompilationUnit compilationUnit = new CompilationUnit();
        compilationUnit
                .addClass("X")
                .addFieldWithInitializer(
                        // "Type" is a JavaParser class,
                        // it is the base class for all kinds of types.
                        parseType("com.abc.Abc"),
                        "abc",
                        parseExpression("5+5"),
                        Modifier.PUBLIC);
        System.out.println(compilationUnit);
    }
}
```

I agree that we can have more consistency in these convenience methods! I'll make an issue about it.

**Comment by BriandUlysse** [comment]
Thank you for your quick answer.

For the Modifier, look like my IDE was confused with 
`java.lang.reflect.Modifier`
and
`com.github.javaparser.ast.Modifier`

The only remaining problem, is with the parseExpression, I try to put a String, like this :
`parseExpression("\""+varContainingMyString+"\"")`
But my String contain some carriage return and it seem to be a problem since the new error say :

> com.github.javaparser.ParseProblemException: Lexical error at line 1, column 3.  Encountered: "\n" (10), after : "\" "

EDIT : I can skirt the problem with :
`replaceAll("\n"," ")`
But it isn't for the best then.

-------

EDIT2: Now that I'm trying to put my new Field in the right place (at the top of the class) I realise I have to use FieldDeclaration and can't do it directly with an addField.
So here is an idea (as say previously I'm not familiar with javaParser, I may be totaly wrong):

Create new Constructors for FieldDeclaration which take the same parameter than the method addField, then the method addField will only take a FieldDeclaration object in parameter, also addFieldWithInitializer will only take a FieldDeclaration object and an Expression.
In both case the user could use any FieldDeclaration constructor he want.

--------

EDIT3: I resolve all my problem, but thanks to another little inconsistency :
Firstly her is my former code :
`nodeClass.addFieldWithInitializer(parseType("String"), nameVar, parseExpression("\""+myString.replaceAll("\n", " ")+"\""), modifierTab);`
My code now :
```
FieldDeclaration field = new FieldDeclaration(modifierEnumSet,parseType("String"), nameVar);
        		field.getVariable(0).setInitializer("\""+myString+"\"");
        		nodeClass.getMembers().add(0,field);
```
Using the setInitializer allow me to use a String instead of an Expression and didn't have problem with the "\n" while the addFieldWithInitializer is less convenient.


(I'm do not criticize, I just want to pointed out as much inconsistency as possible for allow you to improve the javaParser)

Thank you.

**Comment by matozoid** [comment]
Okay, here's some additional things to try:
```java
import com.github.javaparser.ast.Modifier;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.expr.StringLiteralExpr;

import java.util.EnumSet;

import static com.github.javaparser.JavaParser.parseType;

public class Test {
    public static void main(String[] args) {
        EnumSet<Modifier> modifierEnumSet = EnumSet.noneOf(Modifier.class);
        String nameVar = "aa";
        String myString = "af\ne\naf";
        ClassOrInterfaceDeclaration nodeClass = new ClassOrInterfaceDeclaration();

        FieldDeclaration field = new FieldDeclaration(modifierEnumSet, parseType("String"), nameVar);
        // StringLiteralExpr's constructor helps you by escaping end of lines properly:
        field.getVariable(0).setInitializer(new StringLiteralExpr(myString));
        // NodeList has a bunch of utility methods like "addFirst":
        nodeClass.getMembers().addFirst(field);

        System.out.println(nodeClass);
    }
}
```

parseExpression wouldn't parse your string because you asked it to parse something like the following:
```java
        String myString = "af
                e
                af";
```

Parsing source code is full of these escaping pitfalls :-)

**Comment by BriandUlysse** [comment]
In fact my string was a sql request, so it was better to keep it on several lines.

In the end I've come up with this :
`field.getVariable(0).setInitializer("\""+sql.toString().replaceAll("\n", " \" \n + \"")+"\"");`

Then after parsing it would give me:

```
String myString = "af "
                +"e "
                + "af";
```

Thank you for your help! :)

**Comment by matozoid** [comment]
Cool! If that's everything, please close the issue :-)
