### ISSUE TITLE
LazyType::isWildcard is wrong

### ISSUE THREAD

**Issue by esplemea** [javaparser/javaparser#1442]
I noticed by going through the code that the method looked wrong
`public boolean isWildcard() {
        return getType().isArray();
    }`
should call getType().isWildcard() instead.
I am new to this project but it seemed like a small mistake of copy/pasting so I thought I should report it.

**Comment by ftomassetti** [comment]
Thank you for reporting this. In which class did you find it?

**Comment by esplemea** [comment]
LazyType, I wrote it in the title only.
The path is javaparser.symbolsolver.model.typesystem
