### ISSUE TITLE
How can I get MethodDeclaration from MethodCallExpr

### ISSUE THREAD

**Issue by dong-li-awx** [javaparser/javaparser#1443]
I get all `MethodCallExpr` in a file via following code:
```
    descendantsOfType(MethodCallExpr.class, JavaParser.parse(file)).forEach(it -> {
        // Get begin line and end line of method corresponding to the MethodCallExpr
    }

    private <T> List<T> descendantsOfType(Class<T> type, Node node) {
        LinkedList<T> descendants = new LinkedList<>();
        exploreNode(type, node, descendants);
        return descendants;
    }

    private <T> void exploreNode(Class<T> type, Node node, LinkedList<T> descendants) {
        if (type.isInstance(node)) {
            descendants.add(type.cast(node));
        }
        for (Node child : node.getChildNodes()) {
            exploreNode(type, child, descendants);
        }
    }
```
Now, I want to get the begin line and end line of the method corresponding to the `MethodCallExpr`.
I found that if I can get an instance of `MethodDeclaration`, I can get the begin line and end line via `getRange()`.
So how can I get `MethodDeclaration` from `MethodCallExpr`?

**Comment by ftomassetti** [comment]
You should call resolveInvokedMethod and then cast it to JavaParserMethodDeclaration and from there get the wrapped MethodDeclaration

**Comment by dong-li-awx** [comment]
@ftomassetti Thanks a lot!

**Comment by ftomassetti** [comment]
You are welcome. I am going to close this issue, if you have more questions feel free to open new issues

**Comment by dong-li-awx** [comment]
For some method, when casting to `JavaParserMethodDeclaration`, it raises the following exception:
```
java.lang.ClassCastException: com.github.javaparser.symbolsolver.reflectionmodel.ReflectionMethodDeclaration cannot be cast to com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration
```

**Comment by ftomassetti** [comment]
Yes, that is because they are resolved not to methods declared in source code but in JARs or through reflection, so you cannot cast them

**Comment by dong-li-awx** [comment]
I found if the call expression and declaration of a method is not in the same source file (i.e. file A calls a method declared in file B, file A and B are both source code), it will raise the `ClassCastException`.
I build `JavaParser` as follow:
```
JavaParser javaParser = new JavaParser(
                new ParserConfiguration().setSymbolResolver(
                    new JavaSymbolSolver(getTypeSolver())));

private TypeSolver getTypeSolver() throws IOException {
    CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
    combinedTypeSolver.add(new ReflectionTypeSolver(false));
    combinedTypeSolver.add(new JarTypeSolver("foo.jar"));
    combinedTypeSolver.add(new JavaParserTypeSolver(new File("source code dir")));
    return combinedTypeSolver;
}
```
Did I miss something?

**Comment by ftomassetti** [comment]
That would be really surprising...

Can you provide more details? For example, the stack trace, the examples considered, etc

**Comment by dong-li-awx** [comment]
Here is the stack trace:
```
java.lang.ClassCastException: com.github.javaparser.symbolsolver.reflectionmodel.ReflectionMethodDeclaration cannot be cast to com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration
	at qa.qe.taas.MethodCallScanner.lambda$processJavaFile$0(MethodCallScanner.java:121)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at qa.qe.taas.MethodCallScanner.processJavaFile(MethodCallScanner.java:109)
	at qa.qe.taas.MethodCallScanner.processJavaFiles(MethodCallScanner.java:61)
	at qa.qe.taas.TaaSHierarchyScanner.main(TaaSHierarchyScanner.java:77)
```
----------------------------------
Here is an example:
main/src/main/java/collaboration/todo/TodoItemTest.java
```
public class TodoItemTest {
    public void createAndDeleteTodoItem() {
        ...
        loginPage.setLanguage();
        ...
    }
}
```
main/src/main/java/collaboration/LoginPage.java
```
public class LoginPage {
    public LoginPage setLanguage() {
        ...
    }
}
```
The concerned method is `setLanguage`

-------------------------------------
Here is how I parse the source code, resolve the method call and cast it to `JavaParserMethodDeclaration`:
```
StreamProvider streamProvider = new StreamProvider(new FileInputStream(file));
descendantsOfType(MethodCallExpr.class, javaParser.parse(ParseStart.COMPILATION_UNIT, streamProvider).getResult().get()).forEach(it -> {
    ResolvedMethodDeclaration methodDecl = it.resolveInvokedMethod();
    Range range = ((JavaParserMethodDeclaration) methodDecl).getWrappedNode().getRange().get();
}        
```

**Comment by ftomassetti** [comment]
Well, you are causing the class cast exception...
When you get a `ResolvedMethodDeclaration` it *COULD* be a `JavaParserMethodDeclaration` or another subclass `ResolvedMethodDeclaration`, depending on where the method was found. If it was found in a piece of Java code it will be a `JavaParserMethodDeclaration`, if it comes from a jar it will be a `JavassistMethodDeclaration`, if it is comming from the standard library it will be a `ReflectionMethodDeclaration`. So you should check it has the right type before doing the cast.

**Comment by dong-li-awx** [comment]
Well, but why do I get a `ReflectionMethodDeclaration` when resolve above example method (`setLanguage`)?

**Comment by ErtelJessica** [comment]
Hi @letitb ,

don't know if you already have found a solution but here is mine:
I had a similar problem (https://github.com/javaparser/javaparser/issues/1488) and my solution was to add the source directory of my classes to the `CombinedTypeSolver` like `combinedTs.add(new JavaParserTypeSolver(new File(baseDir + "src/main/java")))`. 
So I think your `TypeSolver `is missing your class `LoginPage`.
Adding this missing path helped for me.
