### ISSUE TITLE
Symbol Solver is unable to solve references in an enum

### ISSUE THREAD

**Issue by ErkoKnoll** [javaparser/javaparser#1448]
Hi,

I wrote a parser that is going over JDK sources and I'm resolving method signatures for which I'm using JavaParserFacade.convertToUsage(Type, Node) to find the references for the types associated. I have set the whole JDK (1.8.0_162) source directory for symbol solver to resolve types from and for most of the types it works flawlessly but for certain enums it is failing to resolve any type other than the enum's type itself. I also tries adding ReflectionTypeSolver also but it did't make any difference. Here are the enums I found that the type solver is unable to find types for: java.time.temporal.ChronoField, java.time.Month, java.time.DayOfWeek.

In log output below you can see it is unable to solve types, but the root cause is another type the enum implements that the symbol solver is not able to resolve and therefor fails all the other types too, and it is the case for all 3 type of enums I found, though the missing type it complains about is in the JDK sources.

Log:
Failed to resolve type - Type: TemporalAccessor - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalAdjuster - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalAccessor - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalAccessor - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: String - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TextStyle - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TextStyle - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Locale - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Locale - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: ValueRange - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalQuery<R> - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalQuery<R> - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Temporal - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Temporal - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Temporal - Class: java.time.DayOfWeek - Reason: Unsolved symbol : TemporalAccessor

Failed to resolve type - Type: TemporalAccessor - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalAdjuster - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalAccessor - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalAccessor - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: String - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TextStyle - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TextStyle - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Locale - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Locale - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: ValueRange - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalField - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalQuery<R> - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: TemporalQuery<R> - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Temporal - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Temporal - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor
Failed to resolve type - Type: Temporal - Class: java.time.Month - Reason: Unsolved symbol : TemporalAccessor

Failed to resolve type - Type: String - Class: java.time.temporal.ChronoField - Reason: Unsolved symbol : TemporalField
Failed to resolve type - Type: Locale - Class: java.time.temporal.ChronoField - Reason: Unsolved symbol : TemporalField
Failed to resolve type - Type: Locale - Class: java.time.temporal.ChronoField - Reason: Unsolved symbol : TemporalField
Failed to resolve type - Type: String - Class: java.time.temporal.ChronoField - Reason: Unsolved symbol : TemporalField

**Comment by ftomassetti** [comment]
This is an interesting application!

**Comment by ftomassetti** [comment]
Do you have more details? We could add this as a long running test, maybe to be run just before releases

**Comment by ErkoKnoll** [comment]
Hi,

I don't have any more info, I just noticed those 3 enums behaving as such that are part of the JDK.

**Comment by jlerbsc** [comment]
In JP 3.16.1 this issue cannot be reproduced with this test case.

    String actual = 
                  "import java.time.DayOfWeek;\n" 
                + "import java.time.temporal.TemporalAccessor;\n"
                + "public class Foo{\n" 
                + "    public DayOfWeek from(TemporalAccessor ta ) {\n"
                + "       return DayOfWeek.from(ta);"
                + "    }\n"
                + "}";
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver(false));

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(actual);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        System.out.println(mce.calculateResolvedType());
        System.out.println(mce.resolve());
