### ISSUE TITLE
Symbol Solver is unable to resolve extended generic type

### ISSUE THREAD

**Issue by ErkoKnoll** [javaparser/javaparser#1449]
Hi,

I have the following simple class:
`public class Class5<T, S extends Class6<T>> {
}`

I'm trying to resolve Class6 that is in resolvable path. As Class6 node is a type of SimpleName then I'm using JavaParserFacade.solve(SimpleType) but when asked if it is solved by using isSolved it returns false.

**Comment by ftomassetti** [comment]
SimpleType does not exist. If you are using SimpleName the solver is probably looking for a value and not a type, therefore it cannot solve it.

You could just call `resolve` on the `ClassOrInterfaceType` (Class6 should be a ClassOrInterfaceType)

**Comment by ftomassetti** [comment]
(It does not seem a bug to me, removing the label)

**Comment by matozoid** [comment]
No response, considering answered.
