### ISSUE TITLE
How can I get the type of a statement?

### ISSUE THREAD

**Issue by pengzhendong** [javaparser/javaparser#1451]
I want to get the type of a statement in the source code, such as line 1 is an 'ArrayCreationExpr' and line 2 is an 'AssignExpr'

1 new int[5]
2 a=5

**Comment by matozoid** [comment]
Hi! Normally that would be done with `instanceof` and casting. If you need help with that, please post some code :-)

**Comment by pengzhendong** [comment]
![image](https://user-images.githubusercontent.com/10704539/36933556-04288af2-1f16-11e8-8a3a-f907d7cd0d24.png)
Such as I have a Java file called Test.java, I want to get the type of each line.
The result I expected may be:
```
line 1: xxx
...
line 3: NameExpr
line 4: ReturnStmt
...
line 8: MethodReferenceExpr, MethodCallExpr
...(until last line)
```
Each line of a multiline statement should output the same type.

Thanks very much!

**Comment by matozoid** [comment]
Okay, if you have written no code yet, I will point you to some resources to get started:
- https://leanpub.com/javaparservisited
- https://github.com/javaparser/javaparser-maven-sample
- https://matozoid.github.io/2017/12/13/inspecting-an-ast.html

Please tell me if that clears up things.

**Comment by pengzhendong** [comment]
Thanks, the sample helps a lot.

**Comment by matozoid** [comment]
Assuming this is answered.
