### ISSUE TITLE
Move articles from https://matozoid.github.io/ to javaparser.org

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1453]

**Comment by ftomassetti** [comment]
Do you need anything? You should have your user account and I can help with wordpress plugins

**Comment by matozoid** [comment]
I need time :-)

But seriously, if I can import [these files](https://github.com/matozoid/matozoid.github.io/blob/master/_posts/2017-04-14-validations.md) one on one, I'll be done in no time.

**Comment by matozoid** [comment]
@ftomassetti - you could help by doing the first one, so I can see where it has to go.

**Comment by matozoid** [comment]
This only needs links to the articles I wrote.

**Comment by ftomassetti** [comment]
Easy solution: add them manually by adding the links in the resources page

Difficult solution: find how to insert a snippet that automatically list all posts created in the wordpress installation

**Comment by matozoid** [comment]
Done manually for now.
