### ISSUE TITLE
SymbolSolver fails with StackOverflow when handling generic types

### ISSUE THREAD

**Issue by AwesomeLemon** [javaparser/javaparser#1455]
So in the file (https://github.com/treejames/SmartAndroid/blob/master/Smart_Client/app/libs/guava-master/guava/src/com/google/common/reflect/TypeToken.java) there's such code:
```
public final Class<? super T> getRawType() {
    ...
    return result;
}
...
for (TypeToken<? super T> type : this) {
        builder.add(type.getRawType());
}
```
Failure occurs when ``solveMethodAsUsage`` is called on the "type.getRawType()".
Inside at some point return type of the method is being resolved. This leads to call to ``ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType``. There at line 65 (https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/resolution/types/parametrization/ResolvedTypeParameterValueProvider.java#L65) reference to the same method is passed for solving type parameter. 

When using this method for solving type parameter ``TypeVariable {com.google.common.reflect.TypeToken.T}`` this type at line 51  is replaced with ``WildcardUsage{type=SUPER, boundedType=TypeVariable {com.google.common.reflect.TypeToken.T}}`` which leads to the call of the same function on line 60 with type parameter ``TypeVariable {com.google.common.reflect.TypeToken.T}``. Thus the endless loop is entered.

**Comment by pavlajak** [comment]
Is there a way to identify the usage of generic types? I would not mind leaving the class in question not parsed. However I cannot find a way to notice this issue before causing overflow.

**Comment by jlerbsc** [comment]
@pavlajak Can you provide us with a simple test case that allows us to reproduce the problem. thanks.

**Comment by jlerbsc** [comment]
The projet https://github.com/treejames does not exist any more. It's difficult to resolve this issue without a minimal reproducible test case.
