### ISSUE TITLE
LexicalPreservationPrinter does not prepend newline to added imports

### ISSUE THREAD

**Issue by Otanikotani** [javaparser/javaparser#1459]
This is a unit test for `LexicalPreservingPrinterTest` which currently fails:

```java
    @Test
    public void addedImportShouldBePrependedWithEOL() {
        considerCode("import a;");

        cu.addImport("b");

        assertEquals("import a;" + EOL + "import b;" + EOL, LexicalPreservingPrinter.print(cu));
    }
```

The issue is that when a new import declaration is being added it will look like `import a; import b;` - on the same line.

Locally, I fixed it by adding a new DATA key - Whitespace and specifying what kind of whitespace must be added on any `add` operations. I think it is not a good solution, but if you are interested I can show.

**Comment by ftomassetti** [comment]
The failing test is precious and I would like to take a look on your
solution

**Comment by matozoid** [comment]
I just fixed it :-D

**Comment by matozoid** [comment]
@ftomassetti respect for your code by the way, I managed to fix a few of these just by tweaking the CSM!

**Comment by ftomassetti** [comment]
Eh eh, good to hear!

**Comment by vicky1146** [comment]
This issue also occurs if a line ends with ^M character.

**Comment by matozoid** [comment]
@vicky1146 can you open a new issue? Otherwise your comment will get lost since this issue has been long closed.
