### ISSUE TITLE
Method Annotations are not coming Proper

### ISSUE THREAD

**Issue by Lokendra-Sharma** [javaparser/javaparser#1462]
If a method has multiple annotation and between annotation if there is  commented code then that commented code also concatenate with annotation mentioned after the commented code. example

@Override
// this is commented code
@CustomAnnotation
public void show() {
}

when creating compilation unit for this class and reading ClassOrInterfaceDeclaration then getting methods from cd.getMethods() and getting annotation from MethodDeclaration.getAnnotation.
this above code will return two annotation 
1. @Override
2. // this is commented code @CustomAnnotation
How it can be avoid and resolved?

Using javaparser-core 3.5.15

**Comment by matozoid** [comment]
Hi!
Can you try playing with `ParserConfiguration.setDoNotConsiderAnnotationsAsNodeStartForCodeAttribution`?

(Hmmm, it's badly named. It should be setDoNotConsiderAnnotationsAsNodeStartForCommentAttribution, or even better `ignoreAnnotationsWhenAttributingComments`.)

**Comment by matozoid** [comment]
No response, assuming answered.

**Comment by Lokendra-Sharma** [comment]
ParserConfiguration.setAttributeComments(true);
Above mentioned solution is working for me, Now all comments are ignored by this. It worked.

I have one more query.
Could you please tell me, Is there any way to get all implementation classes of an interface by using javaparser-core api, because from class we can get all implemented types but not vice-versa.

**Comment by matozoid** [comment]
@Lokendra-Sharma - that is a task for the symbol solver. If you have questions about that, please open a new issue :-) (also: https://github.com/javaparser/javasymbolsolver-maven-sample )
