### ISSUE TITLE
Parser fails when the variable name is keyword

### ISSUE THREAD

**Issue by ErkoKnoll** [javaparser/javaparser#1468]
Hi,

I stumbled upon a code in dom4j library where in one of the classes a variable is defined as "enum" and because of that parser fails for this class with the following exception:

Caused by: com.github.javaparser.ParseProblemException: (line 234,col 25) 'enum' cannot be used as an identifier as it is a keyword.
(line 242,col 27) 'enum' cannot be used as an identifier as it is a keyword.
(line 251,col 17) 'enum' cannot be used as an identifier as it is a keyword.
(line 252,col 27) 'enum' cannot be used as an identifier as it is a keyword.
	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:329)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:200)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$parse$0(JavaParserTypeSolver.java:83)
	... 55 more

Method the parser does not like:
public static Element makeElement(Branch source, String path) {
        StringTokenizer enum = new StringTokenizer( path, "/" );
        Element parent;
        if ( source instanceof Document ) {
            Document document = (Document) source;
            parent = document.getRootElement();
            // lets throw a NoSuchElementException 
            // if we are given an empty path
            String name = enum.nextToken();k
            if ( parent == null ) {
                parent = document.addElement( name );
            }
        }
        else {
            parent = (Element) source;
        }
        Element element = null;
        while ( enum.hasMoreTokens() ) {
            String name = enum.nextToken();
            if ( name.indexOf( ':' ) > 0 ) {
                element = parent.element( parent.getQName( name ) );
            }
            else {
                element = parent.element( name );
            }
            if ( element == null ) {
                element = parent.addElement( name );
            }
            parent = element;
        }
        return element;
    }

**Comment by matozoid** [comment]
Is it old source code? Try this article: http://javaparser.org/setting-java-8-9-10-etc/

**Comment by ErkoKnoll** [comment]
This library is indeed very old. But as I'm targeting other sources also and for Java 8 then I figured it is simply easier to rename that variable.
