### ISSUE TITLE
Add a clone method

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#147]
Reading this question (http://stackoverflow.com/questions/30633535/copy-nodes-in-ast) it seems that it is not obvious how to clone methods. I think we could easily add a clone method wrapping the CloneVisitor.
What do you think?

**Comment by ptitjes** [comment]
It makes sense. In addition to implement Object.clone(), Node could even implement the Cloneable interface. +1 for me.

**Comment by ftomassetti** [comment]
This has been done in #161
