### ISSUE TITLE
findAll throws StackOverflowError in recursion

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#1472]
the findAll() method throws a StackOverflowError where getChildNodesByType() works just fine

JavaParser version 3.5.18

To reproduce:

```
public class Application {

    public static void main(String[] args) {
        CompilationUnit cu = null;
        try {
            cu = JavaParser.parse(new FileInputStream("C:\\path\\To\\Test.java"));
        } catch (ParseProblemException e) {
        } catch (FileNotFoundException e) {
        }

       recursiveTest(cu.findFirst(ClassOrInterfaceDeclaration.class).get());
    }

    private static void recursiveTest(Node node) {
        for (ClassOrInterfaceDeclaration childNode : node.findAll(ClassOrInterfaceDeclaration.class)) {
            recursiveTest(childNode);
        }
    }
}
```

And the File:
```
public class Test{

}
```

**Comment by matozoid** [comment]
Hi! It's because the first node that `findAll` looks at is the startnode you supply. Since it is the type you want to find, it will match, and your code will call `recursiveTest` with the same node again.

I'm not sure why there is recursion in your algorithm: findAll finds all nodes in the complete subtree of the type you request.

**Comment by ghost** [comment]
Thanks for the fast reply
I need it to count lines of code and other metrics. Class A shouldn't have the sum LoC of all inner classes inside it, class B shouldn't have the lines of code of C etc.
I want the metrics to be 100% class specific and not accross multiple classes.

Imagine three Classes with a certain number of lines of code
```
Class A{
   Class B{
     Class C{
     }
   }
}
```
A=100LoC, B=50LoC, C=50LoC

I need to traverse the tree recursively so I can deduct the lines of code of B and C from A so it keeps its 100LoC and is not 200. To be able to do that I need to start at the bottom of the tree

Since getChildNodesByType() will be removed, is there no other way solve this?

**Comment by matozoid** [comment]
There are lots of ways to solve this. I'm thinking you could use a visitor that visits `ClassOrInterfaceDeclaration` and returns the number of lines used by it, plus the number of lines used by its nested classes. Don't forget to call `super.visit` so it will visit those nested classes.

There's more to it, but I'm at work so can't try out things :-) Give it a go and report back if you can't get it to work (and don't forget to read the book!)

**Comment by ghost** [comment]
Nevermind. A simple if(childNode!=node) {recursuion} should have the same effect as getChildNodesByType. Bit on the slow side today :)

Thanks for the help! closing

**Comment by LunNova** [comment]
`getChildNodesByType` was deprecated, saying to use `find(class)`. There's no method `find`. If you use `findAll` instead it includes the current node as well as children, which can lead to problems like the one hit here.

https://github.com/javaparser/javaparser/blob/0e77613d30ea6b2e9c53fa8c4e582b5617d1811a/javaparser-core/src/main/java/com/github/javaparser/ast/Node.java#L422

**Comment by matozoid** [comment]
Hey @nallar, that's indeed a problem. Can you open a new issue for it so it doesn't get lost?

**Comment by matozoid** [comment]
I'll correct the doc and make a note of this.

**Comment by LunNova** [comment]
Thanks @matozoid
