### ISSUE TITLE
MethodCallExpr#resolveInvokedMethod() does not work correctly for inherited methods

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1480]
As the title says, `MethodCallExpr#resolveInvokedMethod()` does not work correctly when trying to resolve calls to inherited methods.

Consider the following two classes:
Class A:
```
package org.testapp;

public class A {
  public void foo() {}
  private void bar() {}
}
```

Class B:
```
package org.testapp;

public class B extends A {

  public void test1() {
    foo(); // should be inherited from A, so there should exist an (implicit) method org.testapp.B.foo()
  }

  public void test2() {
    bar(); // should not be resolvable, since bar() is private in A and not inherited by B
  }
}
```

When I call `resolveInvokedMethod().getQualifiedName()` on the `MethodCallExpr` that represents the call `foo()`, I get: `org.testapp.A.foo()`. This is incorrect, as the called method is actually `org.testapp.B.foo()` (it is implicitly inherited in class `B`).

When I call `resolveInvokedMethod().getQualifiedName()`  on the `MethodCallExpr` that represents the call `bar()`, I get: `org.testapp.A.bar()`. This is incorrect, as there is no method `bar()` in class `B`. Instead, I should get an `UnsolvedSymbolException`.

For your convenience, I have created a repository that contains these two tests, with comments and even a README. :-)

https://github.com/malteskoruppa/javaparser-resolve-invoked-method-test

Could you fix this?

**Comment by ftomassetti** [comment]
I disagree on the first point: the method being called is defined in A, so in my opinion it should be the method org.testapp.A.foo, *unless* it was overwritten.

On the second point you are right: inherited private methods should not be visible

**Comment by malteskoruppa** [comment]
Well I had a feeling that there may be differing views on the first point. :-)

I understand that method `foo()` is _defined_ in class `A`. However, the method that is being _called_ here is the (implicitly inherited) method `foo()` in class `B`. I think that both are important pieces of information, and I think that the symbol solver should make it possible to retrieve either of them, depending on what is desired.

But let me explain my problem. I want to understand where a particular method is being _called_. Currently it is simply not possible to obtain that information (or if it is, I don't know how). When I use `resolveInvokedMethod().getQualifiedName()`, I only learn where the method is defined, but not where it is called. So, instead, I could also do this:

1. If the `methodCallExpr` does not have a scope, then the method is called in the current class (easy case).
2. If the `methodCallExpr` does have a scope, then I could use `methodCallExpr.getScope().get().calculateResolvedType()`. But then, I get problems when the scope is a type instead of an expression; see issue #1439.

Essentially I'm turning around in circles here:

- If I try to resolve the _scope_ of the method call expression, I get problems if the scope is a type, and JavaParser does not provide a way to distinguish whether the scope is a type or an expression, as discussed at length in #1439.
- If I try to resolve the method call expression itself using `resolveInvokedMethod()`, then I do not need to care if the scope is a type or an expression, but in exchange I have the problem that JavaParser only tells me in what class the method is being _defined_, but not in what class it is being _called_.

Essentially, I want to look at a method call expression, like `foo()` in the above example, and get the information: "This is calling the method `org.testapp.B.foo`". Is there any way at all to do this with the symbol solver?

**Comment by ftomassetti** [comment]
Yes, we have different points of view :)
It seems to me that you want the type on which the method is called.

I still do not understand why would you need to get `B.foo` but currently in JSS that declaration would not exist. Introducing a sort of "virtual" declaration could be complicate.

Regarding case 2, can you see if there is a value and if not assume the scope would correspond to a type? I agree JSS should offer a call to distinguish the two cases and we would really love a PR for that... just saying...

So, no, there is no call in the JSS that could give you directly the answer you want BUT I think there are the pieces to get that answer.

**Comment by malteskoruppa** [comment]
> It seems to me that you want the type on which the method is called.

Exactly! :-)

> I still do not understand why would you need to get `B.foo` but currently in JSS that declaration would not exist. Introducing a sort of "virtual" declaration could be complicate.

I don't really need to get `B.foo()`, I just need to know that `foo()` is called on the type `B`. I agree that having virtual declarations, as you say, indeed sounds rather complicated. For me it would already be enough if there was some way to determine the type that a method is called on. :-)

Would you agree that it is a valid question to ask: What's the type on which a method is called? I personally think it is a very valid question.

Maybe as a justification consider this:

```
class A {
  public String foo() {
    return getClass().getName();
  }
}

class B extends A {}
```

Calling `(new A()).foo()` will return the String `A`, and calling `(new B()).foo()` will return the String `B`. The point is: a method may behave differently depending on _what type_ it is called on, even if the method is simply inherited and not overridden. Therefore it can be interesting to know what type a method is called on.

> Regarding case 2, can you see if there is a value and if not assume the scope would correspond to a type?

That would be one way to go, but it sounds a bit hacky. It would be something like:

```
// ...assume we have a methodCallExpr with a scope here...
try {
  ResolvedType type = methodCallExpr.getScope().get().calculateResolvedType();
  // good, here we know the type that the method is called on
} catch (UnsolvedSymbolException e) {
  // ah, the scope must already have been a type;
  // let's assume that's the case, then the type is simply the scope itself
}
```

> I agree JSS should offer a call to distinguish the two cases and we would really love a PR for that... just saying...

I would love to provide a PR for that, and in fact I have already looked into it. But the thing is, understanding the whole code base of JSS is very complicated and it would require a lot of time to understand what has to be done where... it looks like it would take me days, if not weeks, to finish this, with 90% of the time only spent on understanding the code base. Unfortunately, it is time I currently do not have. :-(

Of course I understand that you have other priorities too. So don't get me wrong: I think JSS is already very awesome and it helps me a lot! Thank you so much for this tool. :-) It's just this little problem I have and I can sort it out somehow in a "hacky" way (see above), so I'm only trying to provide a little user feedback here.

> So, no, there is no call in the JSS that could give you directly the answer you want BUT I think there are the pieces to get that answer.

Agreed. :smile:

**Comment by malteskoruppa** [comment]
@ftomassetti One more note, or rather, a suggestion for a very small improvement in the JSS API. :-)

In my original post I argued that `resolveInvokedMethod().getQualifiedName()` should return `org.testapp.B.foo()` instead of `org.testapp.A.foo()`. You answered:

> I disagree on the first point: the method being called is defined in A, so in my opinion it should be the method org.testapp.A.foo, _unless_ it was overwritten.

As discussed I understand why you want to return `org.testapp.A.foo()`. However, I have a small suggestion: I think in this case it would be better to rename the method `getQualifiedName()` to `getCanonicalName()`. There are several reasons for this:

1. It would be consistent with standard Java terminology. The difference between _fully qualified names_ and _canonical names_ is explained in JLS 6.7: https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.7. In particular, see example 6.7-2:

```
package p;
class O1 { class I {} }
class O2 extends O1 {}
```
> Both `p.O1.I` and `p.O2.I` are fully qualified names that denote the member class `I`, but only `p.O1.I` is its canonical name.

In other words, the behavior of the method `getQualifiedName()` in JSS is that it actually returns _the canonical name_ instead of _a fully qualified name_.

2. Renaming `getQualifiedName()` to `getCanonicalName()` would leave the name `getQualifiedName()` free if, at some point in the future, support for returning the qualified name pertaining to the method call expression is added (i.e., in my example, `org.testapp.B.foo()`). Then, `getCanonicalName()` and `getQualifiedName()` would have well-defined and distinct behaviors consistent with Java terminology, and the user of the API would be able to decide which information they require.

3. It would be less confusing. If the method `getQualifiedName()` had been named `getCanonicalName()` from the start, I might not even have opened this issue, because then it would have been clear to me what the method really does. Other users may get confused as well. By naming the method `getCanonicalName()` noone could misunderstand -- everybody would have to agree on what the method is supposed to do, and we wouldn't have different point of views. :smiley:

**Comment by matozoid** [comment]
I'm all for staying consistent with the JLS. This stuff is confusing enough.

**Comment by ftomassetti** [comment]
If I remember correctly I did not called it canonical name because I wanted also to use this methods for local classes, which, if I remember correctly, do not have a proper canonical name.

**Comment by matozoid** [comment]
@ftomassetti any alternatives?

**Comment by ftomassetti** [comment]
It is just that "canonical name" to me it seems a definition with a precise meaning, so we must be sure that when we use it we use it as the definition forces us too. I think that we want also a second kind of name that is present even when a canonical name is not technically available

**Comment by malteskoruppa** [comment]
@ftomassetti That's true, but a local class does not have a fully qualified name either. Quoting from JLS 6.7 (https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.7):

> A local class or anonymous class does not have a fully qualified name.
> (...)
> A local class or anonymous class does not have a canonical name.

So both `getQualifiedName()` and `getCanonicalName()` are equally incorrect from that perspective (in the context of local classes). But `getCanonicalName()` at least has the advantages that I mentioned above.

Actually, speaking of *canonical names* or *fully qualified names* in the context of methods is a bit of a stretch anyway. The JLS defines these terms only in the context of primitive types, packages, classes, and interfaces, but *not* methods. If you think about it, in Javadoc comments for example, one never writes `org.testapp.A.foo` to link to a method, but rather `org.testapp.A#foo()` or `org.testapp.B#foo()` (both of these would be perfectly acceptable and correct Javadoc links in the example of my original post)... so, fully qualified name of the type first, then a dash (#), then method name & method parameter types in parentheses.

So, if we want to be fully precise and consistent with standard Java terminology, instead of having a method `getQualifiedName()` in `ResolvedMethodDeclaration` that returns `org.testapp.A.foo` (in my original example), we should better have something like this in `ResolvedMethodDeclaration`, maybe:
- `getCanonicalNameOfType()` which would return the name of the type in which the resolved method is defined (`org.testapp.A` in my original example); and
- `getFullyQualifiedNameOfType()` which would return the name of the type on which the resolved method is called (`org.testapp.B` in my original example).
...while the name/signature of the method itself (`foo()`) can be retrieved via other methods that already exist.

Of course, that still doesn't solve the problem that local classes do not have canonical names, but that is an entirely different story anyway. As mentioned at the beginning of this comment, local classes do not have fully qualified names either.

Sorry about my always really verbose comments, I really hope I'm not annoying you with them. :-)

**Comment by ftomassetti** [comment]
Your comments are appreciated. We focused on getting a decent product with the necessary features done but now that the user base is growing and the features have been implemented we can focus on getting things polished and correct some decisions. Your comments help us doing that.

Still we have the problem of lacking the manpower :)

Yes, I did not even know the JLS had a definition of "qualified name" for me "qualified name" was a generic term, so I used as it made sense to me.

Your proposition seems the more correct one. Still I think we need some sort of name that is presente _always_, so also for local classes.

**Comment by malteskoruppa** [comment]
I'm happy to hear my comments are appreciated, thank you. :smiley: 

Well I think that having a name that is present always, even in the case of a method defined in a local class, is a bit of a different problem and should probably be discussed in a different issue to avoid confusion. But anyway, here's some thoughts:

- Local classes are not the only problem here. It gets even harder with _anonymous_ classes. What kind of name should we give then? An anonymous class, by its very definition, does not even _have_ a name. Consider:

```
class B {
  void foo() {
    new Object() {
      void bar() {}
    };
  }
}
```
What should be the name of the method `bar()` here?

- Similarly, what about lambdas? In other words, what if a `ResolvedMethodDeclaration` happens to refer to an _anonymous_ method?

I think the best approach would be to do it like the JVM does it. That is, something like:
- Local class: `org.testapp.OuterClassName$InnerClassName`
- Anonymous class: `org.testapp.OuterClassName$n` (where `n` is an index)
- Lambda: `org.testapp.OuterClassName$$Lambda$n` (where `n` is an index)

But, again, this is a different issue. One step at a time. :-) For now perhaps, I would leave local classes, anonymous classes, and lambdas aside, and simply return `null` in such cases (meaning "there is no name"). That's what `java.lang.Class#getCanonicalName()` does too:

```
void foo() {
  class B {
    B() {
      System.out.println(getClass().getCanonicalName()); // prints: null
    }
  }
  new B();
}
```

I must say, for having a lack of manpower, you guys answer tremendously fast, I'm really impressed. :wink: I am helping as I can with comments and I may be able to help here and there with PRs in the future. But unfortunately, implementing a solution for the particular problem I opened this issue for (with the `getCanonicalNameOfType()` and `getFullyQualifiedNameOfType()` stuff) requires a deep understanding of the JSS codebase, and would be beyond what I can do at the moment. :/ Had it been otherwise, I would have submitted a PR instead of opening an issue. :-)
