### ISSUE TITLE
Enum Declaration Constant addition with Lexical Preservation

### ISSUE THREAD

**Issue by ozangunalp** [javaparser/javaparser#1483]
While using LexicalPreservingPrinter, adding an enum constant always adds the constant inline with the previous constant.

Considering a source enum like :
```
enum A {
   A1(1);
   A(int i) {
   }
}
```

If the change adds the enum constant `A2(2)`at the end, it should give 
```
enum A {
   A1(1),
   A2(2);
   A(int i) {
   }
}
```

Instead the LexicalPreservingPrinter writes : 

```
enum A {
   A1(1), A2(2);
   A(int i) {
   }
}
```

**Comment by matozoid** [comment]
All added code is formatted according to some built in rules. So, it doesn't inspect the enum to see how it is currently formatted. This issue can stay open to implement that functionality. Meanwhile I'll go make sure the alignment is vertical instead of inline.

**Comment by ozangunalp** [comment]
Great! If you point out where to touch I'd be glad to prepare a PR.

**Comment by matozoid** [comment]
Oh, I made this one already: #1484 :-)

**Comment by ozangunalp** [comment]
👍 that should do it too. Thanks!

**Comment by matozoid** [comment]
I'll release a new version tonight with this in it

**Comment by dblevins** [comment]
Found this via google search trying to figure out if there is a way to force a vertical alignment.  Is there a useful link/doc that shows how to force each enum element to be on its own line?

**Comment by jlerbsc** [comment]
It seems that is the default.

**Comment by jlerbsc** [comment]
LexicalPreservingPrinter adds new members with vertical alignment, but preserves existing formatting.
Perhaps can you use another printer for example

    PrettyPrinterConfiguration config = new PrettyPrinterConfiguration();
    config.setMaxEnumConstantsToAlignHorizontally(1);
    PrettyPrintVisitor v = new PrettyPrintVisitor(config);
    v.visit(<your node>, null);
    System.out.println(v.toString());

**Comment by jlerbsc** [comment]
I think this issue has been fixed but if not you can re-open it.
