### ISSUE TITLE
Fluent statements building

### ISSUE THREAD

**Issue by anatolyD** [javaparser/javaparser#1487]
Hi guys,
  I wonder if for the code manipulation we can come up with some fluent approach. For example to build expression: `new ExpressionStmt(new AssignExpr(new NameExpr(outgoingVariable), methodCallExpr, Operator.ASSIGN));`

We could have done: `ExpressionStmt.assign().name(variable).to(methodCallExpr);`
`// Operator.ASSIGN to be the default one for example`

What do you think?

**Comment by matozoid** [comment]
Hi! All setters return `this` for this purpose. The idea is to pick a constructor, then continue with a chain of setters. Can you try that?

**Comment by anatolyD** [comment]
yes, they can help. 
```
case 1: new ExpressionStmt().setExpression(new AssignExpr().setTarget(new NameExpr(outgoingVariable.getName())).setValue(methodCallExpr));

case 2: new ExpressionStmt().setExpression(new AssignExpr()).getExpression().asAssignExpr().setTarget(new NameExpr(outgoingVariable.getName())).setValue(methodCallExpr);
```

but they look a bit more verbose than 
```
ExpressionStmt.assign().name(variable).to(methodCallExpr);
```

I am not sure how many times do you do chain buildings. maybe it is not that widely required. as even i have only a couple of such cases.

**Comment by matozoid** [comment]
Maybe you want to go with https://sookocheff.com/post/java/generating-java-with-jcodemodel/ - it seems you get a little less code with that because it is focused on code generation.

(For my own purposes, I often parse strings with pieces of Java code in it, with placeholders if necessary, so I don't have to go through the new/add/set code for each and every little node)

**Comment by anatolyD** [comment]
oh no,  you can't pull me off the javaparser )) It's really cool to do the parsing and modification of the AST.
My use case to parse large code base and then change it here and there generating new methods/classes

**Comment by matozoid** [comment]
Oh, I'm sorry ;-) Do keep supplying ideas!

**Comment by matozoid** [comment]
Did you know JP partially generates its own java files using JP? --> https://github.com/javaparser/javaparser/tree/master/javaparser-core-generators/src/main/java/com/github/javaparser/generator

**Comment by matozoid** [comment]
Assuming this is answered.

**Comment by anatolyD** [comment]
yeap, I am playing with the setX that returns `this`. so far it works pretty enough
