### ISSUE TITLE
Let the symbol solver accept unparseable code

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1494]
As discussed in #1445 - make the symbol solver not fail hard on bad source.

**Comment by daanschipper** [comment]
I did make a small improvement to this already in #1493 by changing `cu = Optional.of(JavaParser.parse(srcFile));` to `cu = new JavaParser().parse(ParseStart.COMPILATION_UNIT, provider(srcFile)).getResult();`. This wraps a 'bad source' in a unsuccessful ParseResult

**Comment by matozoid** [comment]
I noticed, so this one goes to next release too :-)
