### ISSUE TITLE
Failing tests in javaparser-symbol-solver-testing

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1498]
There are 20 failing tests in module `javaparser-symbol-solver-testing`. More precisely, the failing tests are all 20 tests in the class `AnalyseJavaSymbolSolver060Test`.

This does not become apparent when running `mvn clean test`, because the class `AnalyseJavaSymbolSolver060Test` belongs to the category `SlowTest` and such tests are excluded in the pom.xml of the `javaparser-symbol-solver-testing` module.

The reason why the tests fail is simple and easily fixed: This class attempts to parse & run some tests on the source code of JSS 0.6.0. The source code of JSS 0.6.0 should be included in the directory `javaparser-symbol-solver-testing/src/test/resources/javasymbolsolver_0_6_0/`, but it is missing.

As you can see, in the JSS repository, there are two sub-directories `lib` and `src` here:
https://github.com/javaparser/javasymbolsolver/tree/master/java-symbol-solver-testing/src/test/resources/javasymbolsolver_0_6_0

In the same location of the JP repository, these two sub-directories are missing:
https://github.com/javaparser/javaparser/tree/master/javaparser-symbol-solver-testing/src/test/resources/javasymbolsolver_0_6_0

Copying these two directories to this location in the JavaParser repository fixes the failing tests.

**Comment by matozoid** [comment]
@ftomassetti - please take a look at #1425

**Comment by matozoid** [comment]
Ah, this code is actually put in place by the maven build. @ftomassetti already warned me it would be confusing, so I'll put the files back into the project.

**Comment by ftomassetti** [comment]
I sent a PR to enable slow tests on Travis, so that during development we can run only quick tests by default but at the time a PR is submitted we run all tests

**Comment by matozoid** [comment]
I have no idea why I closed this.

**Comment by matozoid** [comment]
It's been fixed a few versions ago.
