### ISSUE TITLE
Can I read source code of a class in a Jar ?

### ISSUE THREAD

**Issue by puneet-soni** [javaparser/javaparser#1499]
I want to read source code of multiple java classes like String and java.util.*. through Jar. Can i do it? I Can some one help me out here on how it can be done ? I understand that giving the source code path can give me details of each class but that is not a liberty I have.

Thank you in advance.

**Comment by ftomassetti** [comment]
Does this Jar contains the source code of those classes or just the compiled version (the class files)?

**Comment by puneet-soni** [comment]
The class files

**Comment by ftomassetti** [comment]
Then the answer is no because there is no source code to read. You are looking for a decompiler.
