### ISSUE TITLE
Unable to parse code

### ISSUE THREAD

**Issue by se-saurav** [javaparser/javaparser#1501]
Hi,

I am not able to parse the below code using javaparser. How can I get it working?

<pre>package io;

import java.util.ArrayList;
import java.util.*;

public class Example2 {  
    public void print(){
        List&lt;String&gt; list = new ArrayList<>();
        list.
    }
}</pre>

It fails at this line of code-

<pre>CompilationUnit cu = JavaParser.parse(file);</pre>

I am using latest javaparser.

**Comment by malteskoruppa** [comment]
Well, your code is not valid Java code, so I would expect it to fail to parse.

Either remove the line `list.` in the code you are parsing or complete it. :-)

**Comment by se-saurav** [comment]
Is there any way to at least get some high level data or raw AST data?

I want to show an autocomplete list whenever user enters "." character, in such case code will always be incomplete. I have all other code changes ready but while testing I found that javaparser can't parse incomplete code. Any help?

**Comment by matozoid** [comment]
There is some support for error recovery in JavaParser. There seemed to be little interest, so it wasn't developed any further (lots of work, makes a mess of the grammar.) Here is an article: http://javaparser.org/parse-error-recovery/

Since JP is unlikely to ever have sufficient error recovery for a professional IDE (unless someone starts putting a *lot* of effort into it) I'd say: try to make the best of the tokens that were parsed. See `Node.getTokenRange()`.

**Comment by ftomassetti** [comment]
To implement autocompletion is a lot of **difficult** work. Basically you have code that is unparseable all the time (the user is typing the code) and you still need to 1) build an AST that makes sense 2) perform symbol resolution on that broken AST. Doing so for a language like Java is far from being trivial. It is definitely not something you can hack for a little demo. If you really need this and you are ready to put a **ton** of effort on this we can look into this but there is definitely not a quick way to get this done.

**Comment by matozoid** [comment]
(Side note: JetBrains's [GrammarKit](https://github.com/JetBrains/Grammar-Kit), which they are suggesting to Intellij Idea plugin developers, has support for error recovery built into the generator itself, unlike JavaCC which we are using. Well, it has, but it's not as nicely integrated.)

**Comment by se-saurav** [comment]
The Java parser generated by Antlr can parse Java code even if it has some errors. Although the error gets logged in console but we can still get the parsed information. I have combined Antlr's parser with JavaParser and it gives me most of the information that I need for now.

But, I would like to mention that any parser will be considered incomplete if it can not parse the code that has errors. For example, "esprima" JavaScript parser accepts a flag to enable "Tolerant Mode".

If you think that this library is incomplete or it can not handle few cases then you should mention this in the documentation. I was completely surprised to see that JavaParser can't parse code that has errors.

**Comment by ftomassetti** [comment]
Well, @se-saurav you can build and use a parser for different reasons and depending on the kind of reasons you have an error-tolerant parser makes or makes not sense. You could be compilers, code-refactoring tools, simple code analysis scripts. In each case you want something different from your parsers. When you start producing incomplete ASTs all of a sudden you have to verify everywhere if the part you are looking at is complete and/or contains errors and in some cases it can significantly complicate things.

I am sorry you are disappointed with our current support for error tolerance/recovery and we appreciate your feedback. Out of curiosity, what are you trying to build? We would like to understand better under which use cases error recovery is useful.

We would also appreciate contributions and pull requests. This product is a community effort and tens of persons, at different skills level, have contributed for years to build it. Maybe it is not yet at the level you need it to be but perhaps you could help us bring it at that level.

**Comment by se-saurav** [comment]
I am not disappointed, it is really a great tool and very easy to understand and use. I started using it 5 years back when I remember that it was hosted on "Google Code" hosting and it was called JaPa. For 5 years I believed that it will work in every case and suddenly on this weekend I came to know that it won't handle one of the most important requirement of my product. I am just requesting you to mention this in the main documentation of this library that it won't parse incomplete code.

I am developing autocomplete feature for an IDE for Java language. To show list of fields, variables, constructors, methods etc. I need to parse the code that is being edited by the user/developer. Now the problem here is that the code will always be incomplete and it will always have errors because the user is still editing it. Error tolerance/recovery can help me in this case. Like I am using "esprima" library for the same purpose in case of JS code autocompletion.

You will be happy to see how your JavaParser is being used to provide autocompletion, see - coreide.com . You can't download it because I am still developing it.

**Comment by SmiddyPence** [comment]
Hi @se-saurav 

Can I recommend you try our book: 

https://leanpub.com/javaparservisited

It is, of course, free and considered our principal user documentation, although it is still under development the "Flying Visit Chapter" which is synonymous with a "quick start" guide for developers does actually specify:

>  The CompilationUnit is the Java representation of source code from a complete and **syntactically correct** class file you have parsed.

As mentioned error recovery is limited and under development, and if you would like to extend apon it with a PR that would be greatly appreciated!
