### ISSUE TITLE
Range to have method like getLinesCount

### ISSUE THREAD

**Issue by anatolyD** [javaparser/javaparser#1505]
Hi,
 
  do u mind if i will add the method getLinesCount into the Range class? I had found doing the following snippet quite some times... 

```
Range range = node.getRange().get();
if (range.end.line < range.begin.line) {
            return -1;
}
return range.end.line - range.begin.line + 1;
```

**Comment by matozoid** [comment]
That would fit in the concept of "adding every utility method that more than one user would find useful" :-)

You can make a PR for it if you like?

Do we have ranges with the begin line after the end line? Better not return a magic error value (-1) then, but throw an exception in the constructor when a range like that is created.

**Comment by anatolyD** [comment]
ok, i will add a PR within a couple of days. yeap. the exception it to be.

"adding every utility method that more than one user would find useful" do we have another user who finds it useful? :)

**Comment by matozoid** [comment]
Thanks!

Lots of people use JP to implement some kind of basic statistics for a code base - I suspect many of them are students making an assignment ;-)

**Comment by cdtpinto** [comment]
Apparently no one touched this issue. I'm adding `getLineCount()` to the Range class right now.

**Comment by matozoid** [comment]
Cool, if you can think of other generally useful methods, go ahead and add those too.

**Comment by cdtpinto** [comment]
Ok, if I think of any I will add it no problem.
