### ISSUE TITLE
UnsolvedSymbolException when trying to get type of FieldAccessExpression's scope with JavaParcerFacade

### ISSUE THREAD

**Issue by ErtelJessica** [javaparser/javaparser#1506]
I'm trying to get the fully qualified Name of the scope of an FieldAccessExpression.
My code works fine for the scope of a MethodCallExpression, but not for FieldAccessExpression:

```
private static String getAbsolutTypeName(Expression scope, TypeSolver typeSolver) {

		ResolvedType type = JavaParserFacade.get(typeSolver).getType(scope);
		String name = type.describe();
}
```

And the Method is called by 

```
private boolean checkScope(FieldAccessExpr expr) {
getAbsolutTypeName(expr.getScope(), combinedTs);
...
}
```

But JavaParserFacade.get(typeSolver).getType(scope) throws an Exeption:
`com.github.javaparser.symbolsolver.javaparsermodel.UnsolvedSymbolException`

I really don't know, why it's working for MethodCalls but not for FieldAccessExpressions.

**Comment by ErtelJessica** [comment]
Update:
Is it possible, that this is a bug?
I think the problem is, that it is a static call on a class e.g. ClassA.FIELD. 

I think the code is first looking for a declaration of ClassA (which would not be found because it's a static call). Afterwards the code checks for static imports. But there is no static import needed.

So I think this is a special case which is not  yet covered by the code.
Does anybody agree?

**Comment by matozoid** [comment]
@ftomassetti - wasn't this reported before?

**Comment by ftomassetti** [comment]
Maybe, not sure. I just wonder what is the scope in that situation. Because if it is a static field and we are try to resolve the scope as a value then it is normal that it fails. It is just confusing but it makes sense. In that case we should aim to communicate better the error or perhaps change the API

**Comment by ErtelJessica** [comment]
First of all: Thank you for your quick reply. :)

I'm not quiet sure if I correctly understand the way the solver works... If I solve the whole Expression `ClassA.FIELD` the Type would be `String` (if FIELD is a statci String field). But how can I get the class where the Field is defined?

So if it makes sense, that the solver failes, then how could I get the qualified name of the scope? E.g for `ClassA.FIELD` in package 'a.b.c' I need to get `a.b.c.ClassA`
What I do right now is: 

```
private static String getAbsolutTypeName(Expression scope, TypeSolver typeSolver) {
ResolvedType type = JavaParserFacade.get(typeSolver).getType(scope);
		String name = type.describe();
...
}
```
That gives me the qualified name of the scope, if the scope is not a class name.

I need it because I want to
1. add an corresponding import to the CompilationUnit
2. check whether the class `ClassA` is a subtype of another class (by using `Class.forName(...)` and `Class.isAssignableFrom(...)`

Is there any other way to get the information?

**Comment by ftomassetti** [comment]
The thing is that the field access is an expression and has a type, the scope is not an expression because `ClassA` is not a valid expression.

I guess one way to solve it would get the `SymbolSolver` and call `solveType` passing the name of the class (`ClassA` in this case)

**Comment by ErtelJessica** [comment]
That doesn't work either...
calling `ResolvedReferenceTypeDeclaration type = typeSolver.solveType(scope.toString()); `causes an error:
```
Exception in thread "main" UnsolvedSymbolException{context='unknown', name='ClassA', typeSolver=null}
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.solveType(CombinedTypeSolver.java:73)
```

And when calling ```
SymbolReference<ResolvedReferenceTypeDeclaration> type = typeSolver.tryToSolveType(argument.getScope().toString());
``` the type is `SymbolReference{Optional.empty}`.

**Comment by malteskoruppa** [comment]
Just FYI - this problem has been discussed before (in the context of static method calls instead of static field accesses, like: `ClasssA.someMethod()`, but it's essentially the same problem).

See:
* https://github.com/javaparser/javaparser/issues/1439
* https://github.com/javaparser/javaparser/issues/1480
* https://github.com/javaparser/javaparser/issues/1491

**Comment by matozoid** [comment]
@malteskoruppa - #1491 is now closed, does that mean the other two, and this one, can be closed?

**Comment by ftomassetti** [comment]
I would vote for closing this

**Comment by matozoid** [comment]
And #1439 and #1480 ?
