### ISSUE TITLE
IndexOutOfBoundsException when attempting to resolve super()

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1511]
Consider the following file `A.java` that we want to parse:

```java
class A {
    A() {
	super();
    }
}
```

This class implicitly extends `java.lang.Object`, and calling `super()` invokes the (default) empty-bodied constructor of `java.lang.Object` (see JLS 8.8.9: _"If the class being declared is the primordial class Object, then the default constructor has an empty body."_).

Now let's try to get the `ExplicitConstructorInvocationStmt` that represents the `super();` statement and then call `resolveInvokedConstructor()` on it. I would expect JSS to return a `ReflectionConstructorDeclaration` representing the parameterless constructor `java.lang.Object#Object()`.

What really happens: an `IndexOutOfBoundsException` is thrown. Stack trace:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.github.javaparser.ast.NodeList.get(NodeList.java:128)
	at com.github.javaparser.ast.nodeTypes.NodeWithExtends.getExtendedTypes(NodeWithExtends.java:39)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:152)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:136)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:147)
	at com.github.javaparser.ast.stmt.ExplicitConstructorInvocationStmt.resolveInvokedConstructor(ExplicitConstructorInvocationStmt.java:291)
```

Explanation: What happens is that while trying to resolve `super();`, JSS attempts to get the class that `A` extends. This happens in `JavaParserFacade.java` in line 152:
`ResolvedType classDecl = JavaParserFacade.get(typeSolver).convert(classNode.getExtendedTypes(0), classNode);`

However, `classNode.getExtendedTypes(0)` throws an `IndexOutOfBoundsException` since class `A` does not explicitly extend any type. Instead, it _implicitly_ extends `java.lang.Object`.

@ftomassetti My question is essentially: **Should this be considered expected behavior (JSS has no understanding that classes that do not explicitly extend anything implicitly extend `java.lang.Object`), or is this a bug/missing feature?**

Just for completeness, I used the following code to try and resolve the `super();` statement:

```java
	@Test
	public void tempTest() throws FileNotFoundException {

		// configure symbol solver
		CombinedTypeSolver typeSolver = new CombinedTypeSolver();
		typeSolver.add(new ReflectionTypeSolver());
		typeSolver.add(new JavaParserTypeSolver(new File("tmp/")));
		JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
		JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);

		// get compilation unit & extract explicit constructor invocation statement
		CompilationUnit cu = JavaParser.parse(new File("tmp/A.java"));
		ExplicitConstructorInvocationStmt ecis = cu.getPrimaryType().get()
				                                         .asClassOrInterfaceDeclaration().getMember(0)
				                                         .asConstructorDeclaration().getBody().getStatement(0)
				                                         .asExplicitConstructorInvocationStmt();

		// attempt to resolve explicit constructor invocation statement
		ResolvedConstructorDeclaration rcd = ecis.resolveInvokedConstructor(); // <-- exception occurs
	}
```

**Comment by ftomassetti** [comment]
For me it is a bug: super should be resolved to the default constructor of Object

**Comment by malteskoruppa** [comment]
Ok, thank you for the clarification! :-)

**Comment by cah-arti-deshpande** [comment]
```java
public void doSelect(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		JSONObject json = new JSONObject();		

		String lineNumberParam = request.getParameter("lineNum");
		long lineNumber = (new Long(lineNumberParam).longValue());
		
		String parentRowParam = request.getParameter("parentRow");
		long parentRow = 0;
		if (!ValueUtils.isNullOrEmpty(parentRowParam))
			parentRow = (new Long(parentRowParam).longValue());
	
		String checkedParam = request.getParameter("checked");
		if (checkedParam == null)
			return;

		boolean checked = ("1".equals(checkedParam));

		ProposalHeader hdr = (ProposalHeader) request.getSession()
				.getAttribute(SESSION_PROPOSAL_HDR);
		if (hdr == null) {
			json.put("success", false);
			json.put("message", "Unable to find the proposal in the session.  Please retrieve it again from the Saved Proposal Listing");
			response.getWriter().println(json.toString());
			response.flushBuffer();
			return;
		}
		
		final ProposalManager manager = new ProposalManager();
		boolean success = true;
		
		if (parentRow == 0) {
			if (lineNumber == -1) {
				// Select all on the page.
				ProposalResultsStateHelper stateHelper = (ProposalResultsStateHelper) request
						.getSession().getAttribute(SESSION_PROPOSAL_RESULTS_STATE);
				for (int i = stateHelper.getLowerRecordNumber() - 1; i < stateHelper
						.getUpperRecordNumber(); i++) {
					ProposalDetail dto = (ProposalDetail) hdr.getDetails().get(i);
					dto.setSelected(checked);
				}
				
			} else {
				int atIndex = manager.getDetailLineIndex(hdr.getDto(), lineNumber);
				if (atIndex >= 0) {
					ProposalDetail dtoDetail = (ProposalDetail) hdr.getDetails().get(atIndex);
					dtoDetail.setSelected(checked);
				} else {
					success = false;
					json.put("message", "Unable to find the selected line.  Please retrieve the proposal again from the Saved Proposal Listing");
				}
			}
			
		} else {
			int atIndex = manager.getDetailLineIndex(hdr.getDto(), parentRow);
			if (atIndex >= 0) {
				ProposalDetail dtoDetail = (ProposalDetail) hdr.getDetails().get(atIndex);
				
				if (lineNumber == -1) {
					//Select all sub-items
					for (Iterator iter = dtoDetail.getSubItems().iterator(); iter.hasNext();) {
						ProposalDetail dto = (ProposalDetail) iter.next();
						dto.setSelected(checked);
					}
					
				} else {
					int subIndex = manager.getDetailLineIndex(dtoDetail.getSubItems(), lineNumber);
					if (subIndex < 0) {
						return;
					}
					ProposalDetail dto = (ProposalDetail) dtoDetail.getSubItems().get(subIndex);
					dto.setSelected(checked);
				}
			} else {
				success = false;
				json.put("message", "Unable to find the selected line.  Please retrieve the proposal again from the Saved Proposal Listing");
			}
			
		}

		request.getSession().setAttribute(SESSION_PROPOSAL_HDR, hdr);

		json.put("success", success);
		response.getWriter().println(json.toString());
		response.flushBuffer();
	}

```

**Comment by cah-arti-deshpande** [comment]
public void doSelect(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		JSONObject json = new JSONObject();		

		String lineNumberParam = request.getParameter("lineNum");
		long lineNumber = (new Long(lineNumberParam).longValue());
		
		String parentRowParam = request.getParameter("parentRow");
		long parentRow = 0;
		if (!ValueUtils.isNullOrEmpty(parentRowParam))
			parentRow = (new Long(parentRowParam).longValue());
	
		String checkedParam = request.getParameter("checked");
		if (checkedParam == null)
			return;

		boolean checked = ("1".equals(checkedParam));

		ProposalHeader hdr = (ProposalHeader) request.getSession()
				.getAttribute(SESSION_PROPOSAL_HDR);
		if (hdr == null) {
			json.put("success", false);
			json.put("message", "Unable to find the proposal in the session.  Please retrieve it again from the Saved Proposal Listing");
			response.getWriter().println(json.toString());
			response.flushBuffer();
			return;
		}
		
		final ProposalManager manager = new ProposalManager();
		boolean success = true;
		
		if (parentRow == 0) {
			if (lineNumber == -1) {
				// Select all on the page.
				ProposalResultsStateHelper stateHelper = (ProposalResultsStateHelper) request
						.getSession().getAttribute(SESSION_PROPOSAL_RESULTS_STATE);
				for (int i = stateHelper.getLowerRecordNumber() - 1; i < stateHelper
						.getUpperRecordNumber(); i++) {
					ProposalDetail dto = (ProposalDetail) hdr.getDetails().get(i);
					dto.setSelected(checked);
				}
				
			} else {
				int atIndex = manager.getDetailLineIndex(hdr.getDto(), lineNumber);
				if (atIndex >= 0) {
					ProposalDetail dtoDetail = (ProposalDetail) hdr.getDetails().get(atIndex);
					dtoDetail.setSelected(checked);
				} else {
					success = false;
					json.put("message", "Unable to find the selected line.  Please retrieve the proposal again from the Saved Proposal Listing");
				}
			}
			
		} else {
			int atIndex = manager.getDetailLineIndex(hdr.getDto(), parentRow);
			if (atIndex >= 0) {
				ProposalDetail dtoDetail = (ProposalDetail) hdr.getDetails().get(atIndex);
				
				if (lineNumber == -1) {
					//Select all sub-items
					for (Iterator iter = dtoDetail.getSubItems().iterator(); iter.hasNext();) {
						ProposalDetail dto = (ProposalDetail) iter.next();
						dto.setSelected(checked);
					}
					
				} else {
					int subIndex = manager.getDetailLineIndex(dtoDetail.getSubItems(), lineNumber);
					if (subIndex < 0) {
						return;
					}
					ProposalDetail dto = (ProposalDetail) dtoDetail.getSubItems().get(subIndex);
					dto.setSelected(checked);
				}
			} else {
				success = false;
				json.put("message", "Unable to find the selected line.  Please retrieve the proposal again from the Saved Proposal Listing");
			}
			
		}

		request.getSession().setAttribute(SESSION_PROPOSAL_HDR, hdr);

		json.put("success", success);
		response.getWriter().println(json.toString());
		response.flushBuffer();
	}

**Comment by cah-arti-deshpande** [comment]
help me to find error

**Comment by MysterAitch** [comment]
@cah-arti-deshpande If you have a query, please open a new issue with a little more information about what you want to happen and what is actually happening.
