### ISSUE TITLE
Question. Is Any way to check that CompilationUnit or ClassOrInterfaceDeclaration is solved?

### ISSUE THREAD

**Issue by seoj135** [javaparser/javaparser#1515]
Hello. 
I want(am trying) to automatically analize any open source java project.

Unfortunately, some open source project repository have unnecessary/deprecated source codes. 
These code not be solvable. Because of various reasons.
- Having some ImportDeclarations not actually exist. 
- Invalid package names
- etc

Even if these code are successfully parsed to CompilationUnit. I hope to drop them.
I checked any method of CompilationUnit and JavaParserFacade. But I didn't found any ways.

**Comment by matozoid** [comment]
I think @daanschipper might know where unparseable compilation units go.

**Comment by seoj135** [comment]
Umm.. unparsable compilation units?
Maybe I'm asking for compilation units not fully solved.

**Comment by matozoid** [comment]
Oh okay. Noted.

**Comment by daanschipper** [comment]
I think you overlooked the method `ParseResult<N> parse(ParseStart<N> start, Provider provider)`, which wraps the result in a `ParseResult`. If the parsing is successful, you can access the compilation unit by calling `parseResult.ifSuccessful(compilationUnit -> // do something)`.

Since you want to parse a whole project, I'd suggest looking at the class `ProjectRoot`. You can read up on it [here](http://javaparser.org/setting-up-for-analysing-a-whole-project/).

**Comment by matozoid** [comment]
@daanschipper - it's more subtle - I think the idea is to recognize which compilation units are parseable, but not solvable (say, a file where someone deleted all the imports.)

Honestly, I think the solution is to drop a compilation unit when an attempt at solving throws an exception?

**Comment by daanschipper** [comment]
Oh, that is a subtle difference but makes it quite more complicated. I'm not sure of the specifics, but my guess is that an `UnsolvedSymbolException` is thrown.

**Comment by seoj135** [comment]
To throw UnsolvedSymbolException, need to visit all of sub nodes and try to resolve each one.
By the way, I found a solved method is already implemented. 
So, if this method can be accessible very pleasure to JSS user.

**Comment by daanschipper** [comment]
That solved method is indeed implemented, but if you don't properly insert a SymbolSolver in the compilation unit that method will throw UnsolvedSymbolExceptions all the time.

**Comment by matozoid** [comment]
... like this: https://github.com/javaparser/javasymbolsolver-maven-sample/blob/master/src/main/java/com/yourorganization/maven_sample/MyAnalysis.java

**Comment by seoj135** [comment]
@matozoid Well. It took a little longer times to try this method. Because I lost a my whole project.

```
boolean isSolvable = true;					
try {
    cu.findAll(Expression.class).forEach(expr -> {
        JavaParserFacade.get(cts).solve(expr);						
    });
} catch (UnsolvedSymbolException e) {
    isSolvable = false;
}
```

This is the best way for it on now. And I close this thread. Thanks.
