### ISSUE TITLE
How to find method by name and original line number?

### ISSUE THREAD

**Issue by ataraxie** [javaparser/javaparser#1517]
First off, thank you for your great library!
I'm trying to find a `MethodDeclaration` in some source code by name and line number. I've been trying with this code:
```
int line = 100;
String name = "someMethodName";
// findMethod is mainly applying the visitor to my CompilationUnit
MethodDeclaration method = findMethod(new MethodVisitor() {
	@Override
	public boolean methodMatches(MethodDeclaration method) {
		String methodName = method.getNameAsString();
		int methodLineNumber = method.getBegin().get().line;
		return name.equals(methodName) && line == methodLineNumber;
	}
});
```
My problem is that the `getBegin().get().line` part gives me the line number in the source of the processed AST, i.e. with comments removed etc. So the line number won't match the original line number in the file. How can I obtain the line number where this method began in the original source file?

**Comment by matozoid** [comment]
Hmmm, `getTokenRange` and `getRange` should point directly to the source code without any processing, so some assumption here is wrong. Can you show some code and what kind of line you're actually looking for?

**Comment by ataraxie** [comment]
Thanks for the fast reply! I dug a bit deeper and I think I was on the wrong track here. I think the issue is that I was expecting `getBegin().get().line` to give me the line number where the method name appears, but of course there can be other things in the lines before that belong to the method as well (in my case it was an `@override` annotation).

So now, given a `MethodDeclaration`, I need the line number where the method name appears. If you could help me with that I'd be very happy.

**Edit:** I think I already got it:
`method.getName().getBegin().get().line`

Guess you can close this issue then. Thanks again!!

**Comment by matozoid** [comment]
That would have been my suggestion too, good luck! :-)

**Comment by M-Remi** [comment]
Hello,

I did same thing : method.getName().getBegin().get().line

But it keeps returning 1

This comment refers to this  issue https://github.com/javaparser/javaparser/issues/4749
