### ISSUE TITLE
Parse Failed due to ConditionalExpr in lambda

### ISSUE THREAD

**Issue by akkinenirajesh** [javaparser/javaparser#152]
Example code (java.util.function.Pridicate)

```
static <T> Predicate<T> isEqual(Object targetRef) {
    return (null == targetRef)? Objects::isNull : object -> targetRef.equals(object);
}
```

Above code fails to parse as generateLambda method does not consider the case where ret is ConditionalExpr

**Comment by rpau** [comment]
Solved in https://github.com/javaparser/javaparser/pull/153

**Comment by ftomassetti** [comment]
A PR has been merged for this, I would close the issue. Feel free to reopen it if you still experience this problem.
