### ISSUE TITLE
ThisExpr#getClassExpr() and SuperExpr#getClassExpr() oddness

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1520]
Consider the following code:

```
package test;

class Foo {
	class InnerFoo {
		InnerFoo() {
			Foo foo = test.Foo.this;
		}
	}
}
```

Calling `getClassExpr()` on the `ThisExpr` that represents `test.foo.this` gives a `FieldAccessExpr`. I think this is incorrect. It should give a `Name` instead.

Generally speaking, I think that the "scope" of a this expression can *only* be a name and nothing else (JLS 15.8.4: https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.8.4). This name can be either fully qualified or simple.

Therefore, the most sensible thing (I think) would be to make `ThisExpr#getClassExpr()` return an `Optional<NodeWithIdentifier<?>>`, i.e., the Optional (if non-empty) would contain either a `SimpleName` or a `Name`.

Currently, it returns an `Optional<Expression>` instead:

- If the name is simple, it returns an Optional of a `NameExpr` (which in turn contains the `SimpleName`... that's ok, even though the name is not used as an expression here, so it's slightly odd);
- if the name is fully qualified, it returns an Optional of `FieldAccessExpr` which took me completely by surprise and I think this is incorrect now.

Then again, I could simply be missing something basic, in which case I would be very grateful for an explanation, because I don't get it. :-)

**Comment by malteskoruppa** [comment]
PS. The same thing happens for `SuperExpr` too.

PPS. If I am indeed right, the method may be better called `getClassName()` instead of `getClassExpr()`.

**Comment by matozoid** [comment]
Finally something I can solve :-) I'll take a look.

**Comment by malteskoruppa** [comment]
Thank you! :-)

I just had a look at the syntax as specified by the JLS (https://docs.oracle.com/javase/specs/jls/se8/html/jls-19.html) to see what it says about this expressions and super expressions, these parts may be relevant:

> **Productions from §15 (Expressions)**
> _PrimaryNoNewArray:_
>   this 
>   _TypeName_ . this 
>
> **Productions from §6 (Names)**
> _TypeName:_
>   _Identifier_ 
>   _PackageOrTypeName_ . _Identifier_
>
> _PackageOrTypeName:_
>   _Identifier_ 
>   _PackageOrTypeName_ . _Identifier_
>
> **Productions from §3 (Lexical Structure)**
> _Identifier:_
> _IdentifierChars_ but not a _Keyword_ or _BooleanLiteral_ or _NullLiteral_
>
> _IdentifierChars:_
> _JavaLetter_ {_JavaLetterOrDigit_}
>
> _JavaLetter:_
> _any Unicode character that is a "Java letter"_
>
> _JavaLetterOrDigit_:
> any Unicode character that is a "Java letter-or-digit"

In addition, there exists no production rule that allows anything else but `TypeName` to occur before `.this`.

It's similar for super expressions.

**Comment by malteskoruppa** [comment]
Note: I think it is correct that `getClassExpr()` should return either a `Name` or a `SimpleName`, but if it returns `Name`, this does not necessarily imply the type name used in the this expression is _fully_ qualified. It could also be relatively qualified, like so for instance:

```
package test;

class Foo {
    class InnerFoo {
        class InnerInnerFoo {
            class InnerInnerInnerFoo {
                InnerInnerInnerFoo() {
                    InnerInnerFoo innerInnerFoo1 = InnerInnerFoo.this;
                    InnerInnerFoo innerInnerFoo2 = InnerFoo.InnerInnerFoo.this;
                    InnerInnerFoo innerInnerFoo3 = Foo.InnerFoo.InnerInnerFoo.this;
                    InnerInnerFoo innerInnerFoo4 = test.Foo.InnerFoo.InnerInnerFoo.this;
                    System.out.println(innerInnerFoo1 == innerInnerFoo2); // true
                    System.out.println(innerInnerFoo2 == innerInnerFoo3); // true
                    System.out.println(innerInnerFoo3 == innerInnerFoo4); // true
                }
            }
        }
    }
}

```

In fact, you don't even a nested class to be able to use a qualified name. For example, in the above code, any instance method in `Foo` could refer to its current instance of `Foo` either using `this`, `Foo.this`, or `test.Foo.this` (it is logical when you recall that any class or interface is the 0'th enclosing type declaration of itself, but of course it wouldn't make a whole lot of sense to use a this expression like that.)

Anyhow, the meaning of the name is not for JavaParser to determine, of course. Hmm... I wonder if the symbol solver correctly resolves the type of all these this expressions. :-) I'll try it when I have some time.

**Comment by malteskoruppa** [comment]
I'd also suggest calling the method `getTypeName()` instead of `getClassName()` (or `getClassExpr()`), since an enclosing instance of an inner class *could* also be an interface. As stated in [JLS 8.1.3](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.1.3):

> _It is unusual, but possible, for the immediately enclosing type declaration of an inner class to be an interface. This only occurs if the class is declared in a default method body ([§9.4](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.4)). Specifically, it occurs if an anonymous or local class is declared in a default method body, or a member class is declared in the body of an anonymous class that is declared in a default method body._

So you could do this. :-)

```
interface Foo {
    default void foo() {
        class Bar {
            Bar() {
                Foo foo = Foo.this;
            }
        }
    }
}
```

**Comment by matozoid** [comment]
This is starting to sound a lot like #1428 !

**Comment by matozoid** [comment]
I've at least documented the current behaviour in #1521, hoping that I can get the weekly release done tonight.

**Comment by matozoid** [comment]
I've tried getting the parser to produce anything but fieldaccess or nameexpr, but had no luck, so I think it's possible to change that field into a name, and get the name in the AST node with some trickery. Not sure if I should, since #1428 is probably going to change the internals of the grammar to deal with all of this in a better way. That would also avoid having to solve the symbol solver twice, for which we have zero manpower right now.

**Comment by malteskoruppa** [comment]
Well from a semantic point of view, it would definitely make sense to change that field into a name instead of an expression. But you're the better judge of how much work that would be and if it's be worth the effort. :-)

It does indeed sound like `PackageOrTypeName` ([JLS 6.5.4](https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.5.4)), if implemented, would be a good fit for the type of that field. Even more precisely, one could have two classes `TypeName` ([JLS 6.5.5](https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.5.5)) and `PackageName` ([JLS 6.5.3](https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.5.3)) each inherit from `PackageOrTypeName`, and use `TypeName` as the type of the scope of a `ThisExpr`. That would be even more precise, since, in this case, the grammar itself guarantees that the scope is a `TypeName`. Of course, from a grammatical point of view, all three of these symbols are defined in the same way (see production rules in [JLS 6.5](https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.5)) and thus cannot be distinguished by themselves, but in a given context (such as in the case of a `ThisExpr`), we nevertheless know that the scope must be a `TypeName`. I don't know if it would be worth the extra effort, though. :-)

**Comment by malteskoruppa** [comment]
I've been thinking on how to work around this issue. What I need in the end is the type name of the `ThisExpr`, as a String.

When `getClassExpr()` returns a `NameExpr` this is easy enough.

But when it (incorrectly) returns a `FieldAccessExpr` (instead of a `Name`) I'd need a helper method that recursively puts the String which represents the qualified name together. It looks like the `toString()` method of `FieldAccessExpr` will do this. However, from looking at the `PrettyPrintVisitor`, it looks this method would print comments too, so it's not perfect. On the other hand, I don't think that the qualification of a this expression could ever have a comment on its own, could it? Do you think that this workaround would work fine in all scenarios (in the sense it always correctly returns the qualified type name of the this expression as a String)?

**Comment by matozoid** [comment]
Quick comment: is there an asString() method there?

**Comment by malteskoruppa** [comment]
No, unfortunately, that was my first thought too (remembering [your blog post on the subject](https://matozoid.github.io/2018/02/19/asstring-tostring-gdas-ppv-csm.html)), but `FieldAccessExpr` does not have an `asString()` method. :-)

**Comment by matozoid** [comment]
Well, it wouldn't be much more work than recursively walking the scope and appending names and dots, I think?

**Comment by malteskoruppa** [comment]
No indeed! :-)

I just thought that if there is a method that already does what I need, there's no need to reinvent the wheel. ;-) However, since the `toString()` method potentially also prints a comment, I wondered whether I might get bugs in cases where there is a comment. Then again, I thought, there is no way for Java code to only put a comment on the qualification of a `ThisExpr` but not on the `ThisExpr` itself... I think. So I'm probably safe. Hence my question, just to be sure.

**Comment by matozoid** [comment]
Do beware of annotations!

**Comment by malteskoruppa** [comment]
Thanks for the pointer!

It caused me to have another look at the [Java grammar](https://docs.oracle.com/javase/specs/jls/se8/html/jls-19.html) as well as [JLS 9.7.4: Where Annotations May Appear](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.7.4), and if I understand correctly, you can't annotate the qualification of a this expression like that. I also tried to do so in an IDE, and failed, so I think I'm safe from that vantage point too. :-)

**Comment by matozoid** [comment]
Ah good! I think adding annotations was the longest running task for JP, so I feel like they can be anywhere now ;-)

**Comment by matozoid** [comment]
Here's a quick asString for the scope:
```java
    private String asString(Expression classExpr) {
        return classExpr.toNameExpr().map(n -> n.getNameAsString()).orElseGet(() -> {
            FieldAccessExpr f;
            f = classExpr.asFieldAccessExpr();
            return asString(f.getScope()) + "." + f.getNameAsString();
        });
    }
```

I saw that not only is `b` in "a.b.this" a FieldAccessExpr, but `a` is a `NameExpr` again?! So this will be filed as a bug :-)

(edit: it was already filed as a bug...)

**Comment by malteskoruppa** [comment]
Thank you! :-)

In any kind of `FieldAccessExpr` like `a.b` whose "first" / "innermost" part is a name (instead of a method call etc.), isn't it to be expected that this first part is represented as a `NameExpr`? Given that the scope `a.b` of a `this` expression such as `a.b.this` is represented as a `FieldAccessExpr`, it doesn't surprise me that `a` is a `NameExpr` again. What surprises me is that the scope `a.b` is represented as a `FieldAccessExpr` in the first place.

**Comment by matozoid** [comment]
Yes, that :-)
