### ISSUE TITLE
Replace statement / expression with list of BlockStmt statements

### ISSUE THREAD

**Issue by FMikhaiL** [javaparser/javaparser#1525]
Hello, sorry if if was asked before, but I could not find anything

I have a question:
given a `Node foo` being `int x = 5;` and a `BlockStmt bar`, containing statements `int y = 3;` and `int z = 4`, how can I replace node `foo` with `bar` statemtns but without a pair of `{}` that just calling `foo.replace(bar)` would leave?

**Comment by matozoid** [comment]
I have no computer nearby, but here are some things to consider: a BlockStmt always has braces. I think you want to remove that int statement, then insert your statements one by one at that position. You can look at NodeList to see if there are some useful utility methods, otherwise the ones inherited from List should do.

**Comment by FMikhaiL** [comment]
Hi @matozoid, thank you for reply!
Unfortunately, I do not understand what should I do. I tried searching for methods you mentioned, but could not find anything so far.
To illustrate my whole situation further:
Imagine I want to parse following code:
```
void foo() {
    boolean condition = true;
    if (condition) {
        int x = 5;
    } else {
        int y = 3;
    }
}
```

I want to replace whole `if/else` block with `then` statement.
If I understand correctly, parsing this method will yield an `IfStmt ifStmt` object with `condition` field set to `NameExpr`, `thenStmt` field set to `BlockStmt` and `elseStmt` field set to `BlockStmt`.
Now, if I call `ifStmt.replace(ifStmt.thenStmt)`, it will result in the following code:

```
void foo() {
    boolean condition = true;
    {
        int x = 5;
    }
}
```

So, my question is: how to get rid of those extra braces?
I saw that there is a `NodeList<Statement>` field inside `BlockStmt`, but I am not sure how to use it to achieve what I want.

**Comment by matozoid** [comment]
Here you go. If you would like a version without all the functional stuff I can rewrite it.
```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.stmt.IfStmt;

public class Bla {
    public static void main(String[] args) {
        CompilationUnit cu = JavaParser.parse("class X{void foo() {\n" +
                "    boolean condition = true;\n" +
                "    if (condition) {\n" +
                "        int x = 5;\n" +
                "        int y=9;\n" +
                "    } else {\n" +
                "        int y = 3;\n" +
                "    }\n" +
                "}}");
        // Process all if's:
        cu.findAll(IfStmt.class).forEach(ifStmt -> {
            // This is the then block, cloned to avoid touching the AST (for now)
            BlockStmt thenBlock = ifStmt.getThenStmt().clone().asBlockStmt();
            // We have to manipulate the list the if is in, so let's figure it out:
            ifStmt.getParentNode()
                    // Do we have a parent? (In valid Java there should be one)
                    // Assume it's a BlockStmt (you might want to improve this to do what you want)
                    .map(parent -> ((BlockStmt) parent))
                    // Get the statements (one of these should be the if-statement)
                    .map(BlockStmt::getStatements)
                    .ifPresent(statements -> {
                        // Copy the statements in the then-block next to the if statement.
                        thenBlock.getStatements().forEach(thenStmt ->
                                // Use addBefore to get them in the right order (try addAfter to see why)
                                // Clone the statement we're copying to avoid touching the existing AST.
                                statements.addBefore(thenStmt.clone(), ifStmt));
                        // Remove the if statement. (Try removing this line.)
                        ifStmt.remove();
                    });
        });
        System.out.println(cu);
    }
}
```

**Comment by FMikhaiL** [comment]
This works fine, thank you!

However, I do not understand why we have to clone `ifStmt.getThenStmt()` and `thenStmt` in `thenBlock.getStatements().forEach(thenStmt -> ...)`?
I have just tried removing clone from both and it still works fine.

**Comment by matozoid** [comment]
You're right, it doesn't matter much in this case. I did it so I didn't risk accidentally altering the AST by altering only stand-alone cloned copies. Every node can have only one parent, if you set it somewhere in the AST, it will be removed from wherever it was.

**Comment by FMikhaiL** [comment]
I see, thank you!

**Comment by OmahaCF** [comment]
Hello,
I am getting an error whenever I try to use this line:
   cu.findAll(IfStmt.class).forEach(ifStmt -> {

The error states findAll is not  defined for the type CompilationUnit.. However I have seen it being used in other places than here. Any idea how to fix that? Also, I have all the imports.

**Comment by matozoid** [comment]
Hi @OmahaCF - please open a new issue next time so we can keep the issue tracker clean.

The answer to your question is probably: use the latest version :-)
