### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by laurenceSaes** [javaparser/javaparser#1527]
Hello,

I get a NoClassDefFoundError when I try to use the latest Maven version of the parser:

`Exception in thread "main" java.lang.NoClassDefFoundError: com/github/javaparser/utils/CollectionStrategy`

```
<dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
            <version>3.6.3</version>
</dependency>
```

When I use it like this:

`ProjectRoot projectRoot = new CollectionContext(new ParserCollectionStrategy()).collect(Paths.get(rootFolder));
`

This happens when I create an artifact with Intellij on use it on a different computer. The artifact has the following jars:

```
animal-sniffer-annotations-1.14.jar/
com.ibm.wala.core-1.4.3.jar/
com.ibm.wala.shrike-1.4.3.jar/
com.ibm.wala.util-1.4.3.jar/
error_prone_annotations-2.0.18.jar/
gson-2.8.2.jar/
guava-23.4-jre.jar/
j2objc-annotations-1.1.jar/
javaparser-core-3.6.3.jar/
javaparser-symbol-solver-core-3.6.3.jar/
javaparser-symbol-solver-logic-3.6.3.jar/
javaparser-symbol-solver-model-3.6.3.jar/
javassist-3.22.0-GA.jar/
jsr305-1.3.9.jar/
mysql-connector-java-8.0.8-dmr.jar/
```

But the class is not there:

![image](https://user-images.githubusercontent.com/518177/39625299-183bbd9a-4f9d-11e8-801d-842186126b64.png)

While it could be inside the project:

https://github.com/javaparser/javaparser/blob/dd48473c0384c198cc3ec8527a84b683ad7960d5/javaparser-core/src/main/java/com/github/javaparser/utils/CollectionStrategy.java

Why do I get a NoClassDefFoundError and how can I solve this?

**Comment by matozoid** [comment]
Okay, when?

**Comment by laurenceSaes** [comment]
Sorry, I accidentally posted the issue too soon.

**Comment by laurenceSaes** [comment]
The problem solved itself. Thanks anyway!

**Comment by matozoid** [comment]
Those are the best problems. Have fun!
