### ISSUE TITLE
Getting all extended interfaces does not work

### ISSUE THREAD

**Issue by Vampire** [javaparser/javaparser#1528]
The following Groovy script shows the problem:

```groovy
@Grab('com.github.javaparser:javaparser-symbol-solver-core:3.6.3')
import com.github.javaparser.JavaParser
import com.github.javaparser.symbolsolver.JavaSymbolSolver
import com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver

def typeSolver = new ReflectionTypeSolver()
JavaParser.staticConfiguration.symbolResolver = new JavaSymbolSolver(typeSolver)
def javaParserFacade = JavaParserFacade.get typeSolver
def compilationUnit = JavaParser.parse 'public interface Foo extends Comparable { }'
println javaParserFacade.getTypeDeclaration(compilationUnit.types[0]).allInterfacesExtended
println compilationUnit.types[0].implementedTypes
println compilationUnit.types[0].extendedTypes
```

I think the problem is that in https://github.com/javaparser/javaparser/blob/9a169f50ad23330d19d44a1553710fcdf7e4aad8/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java#L124-L125 `implementedTypes` is used instead of `extendedTypes`, as of course an interface does not implement, but extend other interfaces.

**Comment by Vampire** [comment]
Workarounds I found (I'm totally new to javaparser, if there are better ways I'd happily hear them):

Basically the logic of `getInterfacesExtended` but with `extendedTypes` instead of `implementedTypes` what I still think is the correct fix:
```groovy
compilationUnit.types[0].extendedTypes.collectMany {
    def interfaceType = new ReferenceTypeImpl(javaParserFacade.getTypeDeclaration(compilationUnit.types[0]).solveType(it.name.id, typeSolver).getCorrespondingDeclaration().asInterface(), typeSolver)
    [interfaceType, interfaceType.allInterfacesAncestors].flatten()
}.each { println it }
```

Or easier, as all ancestor types of an interface are the interfaces it extends, except for `java.lang.Object`:
```groovy
javaParserFacade.getTypeDeclaration(compilationUnit.types[0]).allAncestors.findAll { it.typeDeclaration.interface }.each { println it }
```

**Comment by Vampire** [comment]
Or this one:
```groovy
(javaParserFacade.getTypeDeclaration(compilationUnit.types[0]).allAncestors - javaParserFacade.classToResolvedType(Object) ).each { println it }
```

**Comment by matozoid** [comment]
Okay, I opened a PR so hopefully you won't have to use all these workarounds in a few days :-)

**Comment by matozoid** [comment]
Thanks for the great bug report by the way, that made it possible to solve it already :-)

**Comment by Vampire** [comment]
Thanks for being that responsive, works now. :-)

**Comment by ftomassetti** [comment]
Some interactions give enthusiasm to do more work :)
