### ISSUE TITLE
Add method values to Annotations

### ISSUE THREAD

**Issue by andye2004** [javaparser/javaparser#1529]
Firstly, apologies for having to open this question but I couldn't find / work out how to do it from the book.

I have added a new annotation to a class and had it returned as AnnotationExpr and I now want to add a property/value to it. Could someone tell me how this is done please?

Many thanks, Andy.

**Comment by andye2004** [comment]
Apologies once again! I was being a fool and trying to work directly with the AnnotationExpr. For anyone else who might bump into this the solution is below.

```java
((NormalAnnotationExpr)annotationExpr).addPair("", "");
```
Don't forget to escape the second value if it is a String value. E.g.
```java
((NormalAnnotationExpr)annotationExpr).addPair("name", "\"value\"");
```

**Comment by matozoid** [comment]
I'll close this then. Good luck :-)
