### ISSUE TITLE
Add "addSingleMemberAnnotation" util method

### ISSUE THREAD

**Issue by andye2004** [javaparser/javaparser#1535]
Hi Guys, loving using the tool, the fluent API is so nice to work with. This is really a feature request but I also want to know where the best place was to send feedback for the book?

Anyway, feature Id like to see added is a new NodeWithAnnotationsMethod as below
```java
default N addSingleMemberAnnotation(Class<? extends Annotation> clazz, Expression expression) {
    ...
}
```
Seems that this is the only combination of parameters missing.

Thanks, Andy.

**Comment by matozoid** [comment]
@SmiddyPence - can you answer the book question?

Sure, we'll add it. If you like you can open a PR yourself :-)

**Comment by matozoid** [comment]
PR is open for review!
