### ISSUE TITLE
When does symbol solver start analyzing type binding information/ symbol resolution?

### ISSUE THREAD

**Issue by parvez2014** [javaparser/javaparser#1539]
I am using symbol solver for my research. Previously I used Partial program Analyzer (PPA) but the tool is almost outdated now. Does symbol solver start analyzing source files when I add the project source code folder by calling the add method?  
 CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
 combinedTypeSolver.add(new JavaParserTypeSolver("...")));
Thanks.

**Comment by ftomassetti** [comment]
No. The JSS starts solving on request the first time you call a method that requires solving. It could then cache stuff, if needed

**Comment by parvez2014** [comment]
Thanks for the answer.
