### ISSUE TITLE
Wrong indent in code blocks within broken down method call chains

### ISSUE THREAD

**Issue by Vampire** [javaparser/javaparser#1543]
The following Groovy code

```groovy
@Grab('com.github.javaparser:javaparser-symbol-solver-core:3.6.4')
import com.github.javaparser.JavaParser
import com.github.javaparser.printer.PrettyPrinter
import com.github.javaparser.printer.PrettyPrinterConfiguration

println new PrettyPrinter(new PrettyPrinterConfiguration().setColumnAlignFirstMethodChain(true)).print(JavaParser.parse('class Foo { void bar() { foo().bar().baz(() -> { boo().baa().bee(); }).bam(); } }'))
```

produces

```java
class Foo {

    void bar() {
        foo().bar()
             .baz(() -> {
            boo().baa()
                 .bee();
        })
             .bam();
    }
}
```

but I'd expect it to produce

```java
class Foo {

    void bar() {
        foo().bar()
             .baz(() -> {
                 boo().baa()
                      .bee();
             })
             .bam();
    }
}
```

So block indent = method call chain indent + configuration.indent instead of current indent + configuration.indent.
Basically the indent of the line where the block started + the configured indent.

**Comment by matozoid** [comment]
Hmmmm, the nasty thing is that the method chain indenter is separate from the normal indenter :-/ Ugh!

**Comment by Vampire** [comment]
Yep, I know, one detail that made it harder to do when I gave it a quick shot. :-)
Maybe the method chain indenter should be incorporated into the normal indenter?
And then maybe even my other improvement ticket tackled while at the code? :-D

**Comment by matozoid** [comment]
I'm trying that now, indeed!

**Comment by matozoid** [comment]
One ugly thing is that until now, it didn't matter if you used spaces or a tab as the indent string. Now we need to have knowledge of the tab size though... I think I'm going to postpone that problem for another time.

**Comment by Vampire** [comment]
Well, that's always the problem if you align code an use tabs, that's why using tabs is bad. :-)
Maybe make a pretty printer configuration `tabWidth` that has default value of 4?
Or maybe do the additional indent always with spaces, as then the aligning always works, no matter which tab size a viewer uses (basically what is done now too I think).
Or maybe combine both, make two new configuration settings, one `tabWidth` and one that controls whether the additional indent for alignment is done with purely spaces (the default) or with tabs as far as possible with the configured tab width and the remaining with spaces, using the configured `tabWidth`.

**Comment by matozoid** [comment]
In my opinion it's better not to build a feature until someone asks for it. Saves a lot of work :-)

**Comment by Vampire** [comment]
Well, I personlly dislike tabs, but I occasionally contribute to projects that like them and if I want to generate there, it would be nice if this works, so feel asked. :-D

**Comment by matozoid** [comment]
Please open an issue :-P
