### ISSUE TITLE
question regarding parsing and java versions

### ISSUE THREAD

**Issue by esegev** [javaparser/javaparser#155]
Id like to ask if there is a dependency between the java version of the program running the java parser and the parsed file,
My Question:
Can my java parser application running over java 1.6 can parse  parsed java files that relies on java 1.8?
Thanks in advanced

**Comment by ftomassetti** [comment]
JavaParser should work on JDK 6 BUT it can parse all Java code up to Java 8.

**Comment by esegev** [comment]
Thank you
