### ISSUE TITLE
Broken Javadoc parsing with leading spaces

### ISSUE THREAD

**Issue by Vampire** [javaparser/javaparser#1551]
The Groovy snippet
```groovy
new MethodDeclaration().setJavadocComment('''
 Dispatch an event to {@link GroupChannelCreateListener}s.

 @param threadSelector The dispatch thread selector.
 @param user The {@link User}.
 @param api The discord api instance.
 @param consumer The consumer.
''').javadoc.get().blockTags
```
does not give you 4 block tags of type `PARAM`, but one block tag of type `UNKNOWN` that also is not formatted properly if you later use that parse result.
If you remove the leading spaces from the lines, the result is correct.

**Comment by matozoid** [comment]
Well, I can't find anything that says how many spaces are expected before a block tag, so I'll make that variable.

**Comment by Vampire** [comment]
Here you have it: https://docs.oracle.com/javase/1.5.0/docs/tooldocs/windows/javadoc.html#blockandinlinetags
> To be interpreted, a block tag must appear at the beginning of a line, ignoring leading asterisks, white space, and separator (/**).
