### ISSUE TITLE
Performance issue while parsing a large project.

### ISSUE THREAD

**Issue by daanschipper** [javaparser/javaparser#1554]
I'm analysing a large software project (20k .java files) and I'm running into performance issues. The time it takes to try and resolve types of certain expressions increases significantly during the duration of the program. I've narrowed it down to one method call to JavaParser, namely `expression.calculateResolvedType`. 

At the start of the execution these method calls take most of the time less than a second, with of course some exceptions.

`2018-05-09 17:34:58.897 [ForkJoinPool-1-worker-6] WARN  visitors.MessageExtractor - Resolving type java.lang.String of registerType.getRegisterTypeCode()  took 126ms`
`2018-05-09 17:34:58.926 [ForkJoinPool-1-worker-4] WARN  visitors.MessageExtractor - Resolving type java.lang.String of this.getClass().getSimpleName()  took 2059ms`
`2018-05-09 17:34:59.211 [ForkJoinPool-1-worker-0] WARN  visitors.MessageExtractor - Resolving type java.lang.Long of tx.getParentId()  took 330ms`

At the end of the execution these times significantly increase!
`2018-05-09 18:24:59.606 [ForkJoinPool-61-worker-0] WARN  visitors.MessageExtractor - Resolving type java.lang.String of obj.getClass().getSimpleName()  took 45413ms`
`2018-05-09 18:24:55.585 [ForkJoinPool-61-worker-6] WARN  visitors.MessageExtractor - Resolving type java.lang.String of e.getMessage()  took 4405ms`
`2018-05-09 18:24:51.303 [ForkJoinPool-61-worker-7] WARN  visitors.MessageExtractor - Resolving type java.lang.String of req.getPspReference()  took 15157ms`

I'll quickly explain the general procedure what I'm doing. 
- I'm first loading the project with `ProjectRoot`. 
- Then for each `SourceRoot` I'm parallel parsing all the present `CompilationUnit`s.
  - For each toString, extract the message it would print (eg `return "Hello" + " world!"` would return "Hello world!".
  - For each log statement, extract the message it would print (eg `log.info("some log message with id " + id)` would return "some log message with id /d").

To get the types of variables inside these message I'm resolving them with `expression.calculateResolvedType`. I've gathered the examples of running time with the following function:

```
private Type resolve(Expression n) {
    long startTime = System.currentTimeMillis();
    Type type = types.createIfAbsent(n.calculateResolvedType().describe());
    logger.warn("Resolving type " + type.getQualifiedName() + " of " + n.toString() + "  took " + (System.currentTimeMillis() - startTime) + "ms");
    return type;
}
```

**Comment by daanschipper** [comment]
I think the problem might be with `JavaParserTypeSolver.tryToSolveType(String name)`, where a cache of `foundTypes` is kept. Might it be the case that this cache just keeps growing as more and more as the program is parsing all the files?

**Comment by matozoid** [comment]
Hi! Here's a related issue: #1391

**Comment by matozoid** [comment]
A quick glance tells me the caches are Guava caches set to use "soft values" and that means that they behave like this: https://stackoverflow.com/questions/6592183/what-are-the-practical-consequences-of-using-soft-references

Not sure that's the problem though?

**Comment by matozoid** [comment]
Anyway, it would be very valuable to this project if you could take the source, experiment a little with the cache settings, and report your experience.

**Comment by daanschipper** [comment]
I'll continue this discussion in #1391!
