### ISSUE TITLE
Parsing a Jigsaw module statement does not work

### ISSUE THREAD

**Issue by Vampire** [javaparser/javaparser#1558]
Should `JavaParser.parseStatement("exports org.javacord.api.entity.channel.internal to org.javacord.core;");` not work?
Actually `ModuleStmt` does not implement `Statement`, so I guess no, but why?
If there is no reason, I'd suggest to add this, or how are you supposed to parse a single module statement?

**Comment by matozoid** [comment]
Hmmm, they are supposed to be called `Directive`, not `Statement`. I guess the draft I was working from was a little premature. I'll add a separate parse method for these.
