### ISSUE TITLE
Wrong indentation when removing annotations

### ISSUE THREAD

**Issue by ThLeu** [javaparser/javaparser#1567]
As promised, one of the issues that currently do not work yet with the LexicalPreservingPrinter.

The result of the test below is currently the following
```
class X {
    public void testCase() {
  }
}
```
besides correctly removing the annotation two extra spaces are added before the modifier
**The problem is identical when there is no modifier at all.**

MethodDeclarationTransformationsTest
```
    @Test
    public void removingAnnotations() {
        considerCode(
                "class X {" + EOL +
                        "  @Override" + EOL +
                        "  public void testCase() {" + EOL +
                        "  }" + EOL +
                        "}" + EOL
        );

        cu.getType(0).getMethods().get(0).getAnnotationByName("Override").get().remove();

        String result = LexicalPreservingPrinter.print(cu.findCompilationUnit().get());
        assertEqualsNoEol(
                "class X {\n" +
                        "  public void testCase() {\n" +
                        "  }\n" +
                        "}\n", result);
    }
```

**Comment by ThLeu** [comment]
Might be connected with #1568

**Comment by ThLeu** [comment]
Ok, I looked deeper into this issue and the problem has something to do with the node that is checked for the difference.

Basically, the elements that are considered for the difference application start exactly at the annotation (in this case `@Override`).
There is logic in `Difference.considerCleaningTheLine()` that would remove the two unnecessary spaces in front of the annotation after removing it, but it doesn't know about the two spaces since they are not part of the relevant node (MethodDeclaration) that is considered for the difference application.

I looked a bit at how to fix this and did not yet come up with a good solution.
1. I tried using the "previousToken" elements to see if there are any spaces that are unknown otherwise. This would probably work but the logic is not pretty and seems out of place.
2. I also shortly checked what would happen if I used the parentNode of the currently considered Node (MethodDeclaration, so the parent of that) for the difference application, but that seems to cause some trouble in other areas. 

Maybe you have some other ideas or suggestions on how to get around this problem?
If my explanation is not understandable enough, don't hesitate to ask for more information.

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by ftomassetti** [comment]
Mmm. I am not sure what is happening. One suspicion is that the LPP knows that the method should be indented, therefore it puts four spaces at the start of the line, which is not ideal in this case. However that is the first line of the method so it has no previous line from which to copy the indentation. Ideally it could remember that the annotation used to have only 2 spaces before it.
Just a suspicion however

**Comment by ThLeu** [comment]
I might have thought of a solution now, I just have to code it now :smile:
If you want you can assign this issue to me.

**Comment by ThLeu** [comment]
My idea is to consider all the "Removed" elements in a row and check if the whole line was removed ignoring the spaces that are left.
If the whole line was removed and the indentation of that line is known, the same amount of indentation will be removed on the next line (for this scenario) or on the current line (for other scenarios where the Removed element is not the first in the differenceElements list). The second part is probably already handled but could probably be replaced to get rid of any redundancy.

**Comment by ftomassetti** [comment]
> I might have thought of a solution now, I just have to code it now 😄
If you want you can assign this issue to me.

My pleasure :D

**Comment by matozoid** [comment]
@ThLeu consider yourself assigned!
