### ISSUE TITLE
Enhance parser frontend

### ISSUE THREAD

**Issue by ptitjes** [javaparser/javaparser#157]
This bug is to discuss enhancements to the parser front-end as highlighted in #115, that is:
- Make JavaParser a state-full object
  - Give access to the (exception-free) parsing mechanism
  - Keep static helpers that throw ParseException
- Add problem reporting mechanism
  - Introduce a Location object (source path + Position, comparable)
  - Introduce a Problem object (comparable based on Location)
  - Introduce a ParseResult` object that contains the parsed node and reported problems
  - For the static helpers, make a `ParseException` that contains a list of problems

I'd rather not introduce a `Reporter` interface as I previously noted in #115. Indeed, lexical preservation might enable us to later do continuous parsing à-la Papa Carlo, so I propose the creation of a `ParseResult` object which might later provide a method like `reparse(Parser, ParseHandler)` with `ParseHandler` being a reactive sink for problems and node addition/removal/replacement events. 

Here are, in a glance, the APIs that I propose for discussion:

``` java
public class Location {
  public java.nio.Path path(); // May be null if not parsed from a file
  public Position position();
}

public class Problem {
  public enum Severity { FATAL, ERROR, WARNING, INFO }
  public Severity severity();
  public Location location();
  public String message();
}

public class ParseResult<N extends Node> {
  public List<Problem> problems();
  public N node();
}

public class ParserConfiguration {
  private boolean parseComments; // + getter/setter
  // other configuration...
}

public abstract class ParseContext<N extends Node> {
  // Required package-protected boilerplate code to call ad-hoc parser production...
}

public class JavaParser {
  public JavaParser(ParserConfiguration configuration) { /* ... */ }

  public static ParseContext<CompilationUnit> COMPILATION_UNIT = ...;
  public static ParseContext<BodyDeclaration> BODY_DECLARATION = ...;
  public static ParseContext<Type> TYPE = ...;
  public static ParseContext<Statement> STATEMENT = ...;
  public static ParseContext<Expression> EXPRESSION = ...;
  // ...

  public <N extends Node> ParseResult<N> parse(ParseContext<N> context, InputStream input, Charset encoding);
  public <N extends Node> ParseResult<N> parse(ParseContext<N> context, String input, Charset encoding);

  public ParseResult<CompilationUnit> parse(Path path, InputStream input, Charset encoding);
  // And some other variations

  // + current static helpers throwing ParseException
}

public class ParseException extends Exception {
  private List<Problem> problems;
  // ...
}
```

**Comment by ooxi** [comment]
While I agree with the general idea, I have a couple of questions / additons:
- How about replacing `Location.path` with a generic `Source`? That way we could easily implement `PathSource`, `StringSource` etc. without using null as magical value
- Shouldn't we export `Problems` as `Iterable` instead of `List`? `List` implies some kind of natural order whereas problems can be ordered by various criteria like severity or location

All in all, good work :+1:

**Comment by ptitjes** [comment]
Indeed, those are good points. I do agree with both of them! :)

**Comment by matozoid** [comment]
Since @ptitjes has left the project, I would like to know if anything was done here? Should work continue?

**Comment by ptitjes** [comment]
Well, I've seen you already introduced a state-full parser object. That's a start.

**Comment by matozoid** [comment]
Alright, I took some time to study the proposal and I agree it's very nice! And it's exactly the right time to implement it. 
Note 1: it seems like path/source should be in ParseResult.
Note 2: This proposal can be split in four:
1. create separate configuration object (how would you configure the static helpers?)
2. all of the problem collection code
3. make ParseContext to reduce the amount of parse methods.
4. use JavaCC's error recovery to make better use of the problem collection code.

**Comment by matozoid** [comment]
This has been implemented with some modifications on master.
