### ISSUE TITLE
CompilationUnit#addModule does not actually set the module

### ISSUE THREAD

**Issue by Vampire** [javaparser/javaparser#1572]
The new `com.github.javaparser.ast.CompilationUnit#addModule` does create a new module and returns it, but it does not actually set it to the CU, so it never gets printed.

**Comment by matozoid** [comment]
Congratulations on opening unsolved issue 200 :-)

**Comment by ftomassetti** [comment]
Let's cry a little bit to celebrate :)

**Comment by matozoid** [comment]
:...(

**Comment by Vampire** [comment]
:'''-(

**Comment by matozoid** [comment]
Oh, you can't have more than one module per compilation unit, so `setModule` is sufficient. Removing this method completely...

No wait, making a `setModule(String)`...

**Comment by Vampire** [comment]
Yeah, `setModule(String)` is probably fine, I just searched with `add...`, as everything else is with `add...`.
But I think it is even stricter if I remember correctly.
I think you can not have anything else in the same compilation unit with the module and to be a valid module descriptor it has to be `module-info.java` without any package.
So maybe it would even make sense not being able to add / set a module to a normal CU, but instead have a module CU that can only have one module and that has a fixed file name and no packages, something like that?

**Comment by matozoid** [comment]
`add` is supposed to mean "add to a list," so if you spot a place where we have add but not a list, open an issue :-)
You are absolutely right that it is prettier to have a separate ModuleCompilationUnit or so. I don't think it's worth the additional complexity and work though.

**Comment by Vampire** [comment]
Sure, was just an idea. :-)

**Comment by matozoid** [comment]
It's appreciated :-)
