### ISSUE TITLE
JavaParser doesn't remove comments before package declaration

### ISSUE THREAD

**Issue by everplayed** [javaparser/javaparser#1574]
I posted this on Stackoverflow, and a maintainer of Javaparser told me to post an issue here.
With his help, I managed to solve my problem with another solution, but I think that this problem should be solved.
Here is my post:

I am writing a Java application that removes comments from Java files.

I wrote this code:

```
static void removeComments(Node node) {
        for (Comment child : node.getAllContainedComments()) {
            child.remove();
        }
    }
```

CompilationUnit cu = JavaParser.parse(projectDir); // projectDir is received from parameter
removeComments(cu);
It kind of works. However, if there are block comments before the package declarations, the code won't remove those comments.

For example, this code:

```
/*
 * Block comment
 */
// Line comment
package test;

/*
 * Block comment
 */
// comment
/**
 *
 * @author Me
 */
public class Test {

    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("print 1"); // comment in code line
        // comment 2
        System.out.println("print 2");
        /*
        block comment
         */
    }

}
```
Becomes this code:

```
/*
 * Block comment
 */
package test;

public class Test {

    public static void main(String[] args) {
        System.out.println("print 1");
        System.out.println("print 2");
    }
}
```
Is it a bug from JavaParser, or am I missing something?

**Edit:**

If I put a line comment at the beginning of the file, the first block comment (the one before the package declaration) will be removed, but not this line comment. I think JavaParser doesn't consider that the first line of a file may be a comment.

**Comment by matozoid** [comment]
Hi! Thanks for reporting this (I'm the one who asked.) We'll take a look.

**Comment by ftomassetti** [comment]
My suspicion: the compilation unit consider itself to starts where the "package" keyword starts, so the comment is not "contained" in the compilation unit and therefore it is not considered and deleted.

**Comment by matozoid** [comment]
What I remember is that we hardcoded the cu to start at 0,0 and end at EOL. I'm suspecting an off-by-one error.

**Comment by IlyasAzeem** [comment]
Hey, @matozoid I have the same problem. The JavaParser does not remove such block comment before the methods too. e.g. after parsing the following code the comments remain there.
```java
        /**
         * Constructs a new enumeration of resources of the given name found
         * within this class loader's classpath.
         *
         * @param name the name of the resource to search for.
         */
        ResourceEnumeration(final String name) {
            this.resourceName = name;
            this.pathElementsIndex = 0;
            findNextResource();
        }
```

**Comment by Mathiponds** [comment]
This is related to issue #2480. 
First, the problem with what you did is that you should call `getAllContainedComments` and not `getComments` to get all the comments. In fact, if there are more than one comment before the package declaration, the first one will be associated to the comment of the root node and will not be in the list of comments returned by `getAllContainedComments`.
Suppose there are n message before the package definition. 
* The first one is the comment of the root node that we can get with `getComment` called on the compilation unit
* The n-2 following will be orphan comment that we can get with `getOrphanComments` 
* The last one will be the one associated to the package declaration
As described in the JavaDoc the `getAllContainedComments` method should only return the comment *contained* in the node and then not the comment associated to it i.e. the comment you get with `getComment`. 

So we should use `getComments` to get all the comments.
However, the `getComments` in the `CompilationUnit` only return `getAllContainedComments` of the node `CompilationUnit`. In place, `getComments` should be 
```java
public List<Comment> getComments() {
        List<Comment> comments =  this.getAllContainedComments();
        this.getComment().ifPresent(comments::add);
        return comments;
    }
```
This would solve your issue and #2480

**Comment by Mathiponds** [comment]
We added tests for this. Should we make a Pull Request ?

**Comment by matozoid** [comment]
Yes, more tests is good!
