### ISSUE TITLE
How can I keep the original source code style after parse?

### ISSUE THREAD

**Issue by whxpro** [javaparser/javaparser#1578]
I have some source code like this
```
@BindView(R.id.test) 
View mView;    // comment
```
but after I call `JavaParser.parse(file)`, I print the `compilationUnit`, the code has changed, like this
```
@BindView(R.id.test)
View    // comment
mView
```
This situation also happened on `switch` statement, 
before:
```
switch (number) {
    case 0:    // comment
    ...
}
```
after:
```
switch(number) {
    case    // comment
    0:
    ...
}
```
How can I keep the original style? It seems like because of the comment, I try to use `ParserConfiguration` but it doesn't work, anyone can help me? thanks :-)

**Comment by ftomassetti** [comment]
You are looking for the LexicalPreservingPrinter

**Comment by whxpro** [comment]
@ftomassetti `LexicalPreservingPrinter` works for me, thank you
