### ISSUE TITLE
Cannot get range of resolved method's declaration

### ISSUE THREAD

**Issue by joined** [javaparser/javaparser#1580]
This issue is related to the issue I opened previously, #1552.
Thanks to pull request #1557 now I am able to obtain the path of the Java class containing the resolved method declaration. I built the project from sources and it's working as expected.
Unfortunately a regression was introduced somewhere between release 3.6.5 and the current master branch that doesn't allow me to retrieve the range of the resolved method's declaration as I was doing before.
In particular, executing the exact same script that I listed in #1552, the output now is the following:
```
Analyzing method calls of file /mcextractor/jNumerus/src/main/java/it/matjaz/jnumerus/RomanInteger.java
L98C9,L98C33 -> it.matjaz.jnumerus.RomanInteger.setValueAndNumeral(int), (L122C5,L125C5)
Path: /mcextractor/jNumerus/src/main/java/it/matjaz/jnumerus/RomanInteger.java
L110C9,L110C35 -> it.matjaz.jnumerus.RomanInteger.setNumeralAndValue(it.matjaz.jnumerus.RomanNumeral), (L136C5,L139C5)
Path: /mcextractor/jNumerus/src/main/java/it/matjaz/jnumerus/RomanInteger.java
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at nl.tud.mcextractor.RunnerSimple.main(RunnerSimple.java:44)

Process finished with exit code 1
```
Line 44 is `wrappedDeclaration.getBegin().get().line`.
I am trying to understand where this regression was introduced and if I do so, I'll contribute with a pull request to fix it. Unfortunately my Java knowledge is quite limited.

**Comment by joined** [comment]
Ok so seems like the problem lies here https://github.com/javaparser/javaparser/pull/1577/files#diff-b95e1b81b736146aae3a390cd31e21e8R90, @matozoid set the default ParserConfiguration for the JavaParserTypeSolver not to store the tokens, which is not the default behavior of ParserConfiguration which was used before in its default configuration (https://github.com/javaparser/javaparser/pull/1577/files#diff-b95e1b81b736146aae3a390cd31e21e8L92).

I can pass a ParserConfiguration that stores the tokens to the JavaParserTypeSolver and it works again, but I guess you want to keep the default behavior as it was before? I can make a PR to change that line if you want.

**Comment by ftomassetti** [comment]
A PR would be really welcome. Thank you for inspecting this one

**Comment by matozoid** [comment]
I did that on purpose to speed up parsing and lower memory usage. Well, I guess that people want to do things with the parsed files, so do create a PR :-)
