### ISSUE TITLE
Split or iterate CompilationUnit in blocks of n lines of code

### ISSUE THREAD

**Issue by dmy365** [javaparser/javaparser#1583]
What I want to accomplish is to get the content of a Java class and split it in n lines to operate in these blocks of code instead of the whole class.

I tried to split the files into ArrayLists of Strings (having each String the content of n lines of code). However, parsing the entries eventually results in a com.github.javaparser.ParseProblemException: due to the code not being consistent.

So, I would like to know if there is any easy way to split or iterate a CompilationUnit into these blocks of n lines of code.

**Comment by matozoid** [comment]
Hi! That depends on what you're trying to achieve. What kind of operation do you want to do? Why can't it be done on a complete file?

**Comment by dmy365** [comment]
Hi, thank you for the attention! Basically I want to get a list of the number of operators, keywords and tokens to apply the amount of each to a formula. The problem is that the formula only handles correctly 8 lines of code (more that that will reproduce erroneous results), so I want to apply the formula to each 8 lines of code, sum them up and calculate the average. That's why I need to "split" the compilation unit.

Do you see an easy way for me to accomplish this? I'm trying to figure a solution here, but didn't manage to get nowhere yet.

**Comment by matozoid** [comment]
Well, imagine code like this:
```java
    int []x= {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
    };
```
There's no way to split this to 8 lines. I would look for another solution to this problem.

Why does the algorithm not handle more than 8 lines?

Hmmm, something you could do, if you must do it this way: write a visitor that counts the information you want, and keep checking the line number of the node you're visiting. Every time it gets 8 (or so) higher than the last one you call your algorithm, reset all the counters, and continue visiting.

**Comment by matozoid** [comment]
No response, assuming answered.
