### ISSUE TITLE
Print methods names and respective variables names in a CompilationUnit

### ISSUE THREAD

**Issue by everplayed** [javaparser/javaparser#1587]
I want to print all the methods and respective variables declared in them.

I managed to get the methods names, but now I can't manage to get the variables of each.

This what I have so far:

```
public void printMethodsAndTheirVariables(CompilationUnit cu) {
    for (TypeDeclaration typeDec : cu.getTypes()) {
        List<BodyDeclaration> members = typeDec.getMembers();
        if (members != null) {
            for (BodyDeclaration member : members) {
                if (member.isMethodDeclaration()) {
                    MethodDeclaration field = (MethodDeclaration) member;
                    System.out.println("Method name: " + field.getNameAsString());
                    
                    /* How to get the method variables now? */
                    
                }
            }
        }
    }
}
```

Can anyone point me in the right direction in order to get the variables names? I thoght about getting the tokens and then checking which were variable declarations, but there is no "isVariable()" method for tokens.

And if someone knows a neatier/less resource consuming way to accomplish this, I would gladly appreciate it!

**Comment by matozoid** [comment]
Hi! All of this is explained in the book we wrote. You can get it for free on javaparser.org.

**Comment by everplayed** [comment]
I had a look at the book and for what I see, the only  way to get the variables is through the FieldDeclaration, right? But, as page 7 shows, MethodDeclaration doesn't have a VariableDeclarator.

So my guess is that I should get the block statement and from there try to get the variables some way. Is this a possible approach?

**Comment by everplayed** [comment]
Alright, I managed to be able to get the variable declarations inside the methods. This way I can get all the local variables in a method, since they have to be declared in order to be used.

```
BodyDeclaration method = parseBodyDeclaration(member.toString());
method.walk(VariableDeclarationExpr.class, e -> System.out.println(e.toString()));
```

However, what if there is a class variable being used in the method? Like so:

```
public class Foo {
    private static String example = "text";

    public static void method() {
        System.out.println(example);
    }
}
```

In this case, "example" is a class variable, so it wasn't declared inside the method. Is there a way for JavaParser to return class ir instance variables being used in the method? ~~Or my only option is to use Java Symbol Solver?~~ (apparently you integrated JSS in JP)

**Comment by matozoid** [comment]
For finding what's where in the AST: http://javaparser.org/inspecting-an-ast/

Without the symbol solver, JavaParser is really just a tree structure on top of a source file. So you can take the text of the variable name and compare it to the text of the fields, but it's more or less comparable to pressing "CTRL-F" in the source file and searching for that variable name. It can easily be wrong, because: names can be shadowed, and names can come from other files. But if it is sufficient for you, no need to fire up the symbol solver.

**Comment by obcardinal** [comment]
Hi, @everplayed , I implemented my search:
```java
method.getBody().get().getStatements().stream()
        .map(Node::toString)
        .filter(statement -> statement.contains("=") || statement.indexOf(" ") == statement.lastIndexOf(" "))
        .map(statement -> statement.split("=")[0])
        .map(statement -> statement.substring(0, statement.length() - 1))
        .map(statement -> statement.split(" "))
        .map(statement -> String.join(" // ", statement))
        .forEach(System.out::println);
```
Input:
```java
int a = 10;
List<String> list;
```
Output:
```java
int // a
List<String> // list
```

**Comment by matozoid** [comment]
I'm assuming this can be closed. Do reopen if not.
