### ISSUE TITLE
Can we get Source Line of Code from Javaparser

### ISSUE THREAD

**Issue by puneet-soni** [javaparser/javaparser#1596]
Hello all,
Can javaparser as a library provide us the "Source lines of code". https://en.wikipedia.org/wiki/Source_lines_of_code

If Yes how can we do it ?  If No then  what are the alternatives?

Puneet

**Comment by ghost** [comment]
As this project is a parser and not a static code analysis tool, counting LoC doesn't really belong here imo. Sonarqube is an opensource tool which already does this for you if you don't need it as a library.

However, it's not that difficult to implement
If you feel like doing it yourself as practice:

1. Get the ClassOrInterfaceDeclaration or EnumDeclaration
2.  Use BufferedReader to read the file
3. Proceed to the line where your class declaration begins and start counting LoC from that line on
4. Each line has to go through your algorithm which determines if it is a source line of code (This is doable without regex btw)
5. finish when reaching end of that class (some people put multiple top level classes in a file)

For step 4 you'll surely find some code snippets as help on the internet if you search extensively enough.

**Comment by ftomassetti** [comment]
It depends how you want to calculate LoC. You can simply open Java files and count the lines. If you need to exclude comments lines or blank lines you may want to use JavaParser. While if you want to count the number of lines for a class that should be trivial: each nodes know its starting and ending position in a source file

**Comment by matozoid** [comment]
Foot note: many people have done this before with JavaParser. With a little searching on github you can find several implementations of code quality checkers including lines of code algorithms.

**Comment by ftomassetti** [comment]
Nice, we should list them!

**Comment by matozoid** [comment]
A few are here: https://github.com/javaparser/javaparser/wiki/Projects-using-JavaParser
