### ISSUE TITLE
Question: How to get the inherited fields of a class?

### ISSUE THREAD

**Issue by TerryvanWalen** [javaparser/javaparser#1598]
It is possible to solve inherited fields that are declared in the super class and used in the child class but in my usecase I also would like to discover the inherited fields that are not used in the child class.

Is this at all possible?

**Comment by jjbr** [comment]
Is `getAllAncestors()` perhaps what you are looking for? http://static.javadoc.io/com.github.javaparser/java-symbol-solver-core/0.6.3/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeImpl.html#getAllAncestors--

**Comment by ftomassetti** [comment]
I think you are looking for this methods:

http://static.javadoc.io/com.github.javaparser/javaparser-core/3.6.6/com/github/javaparser/resolution/declarations/ResolvedReferenceTypeDeclaration.html#getAllFields--

Perhaps we should make it available also in other classes or figure out how to make it easier to find

**Comment by TerryvanWalen** [comment]
Thank you. This works.

The code to get all fields (inherited and from the current class)

```
public void visit(final ClassOrInterfaceDeclaration cid, final CandidateCollector candidates) {
    super.visit(cid, candidates);
    List<ResolvedFieldDeclaration> allFields = cid.resolve().getAllFields();
    ...
}

```

To only get the inherited fields you can do something like:
```
ResolvedReferenceTypeDeclaration resolvedClass = cid.resolve();
List<ResolvedFieldDeclaration> allInheritedFields = resolvedClass.getAllFields().stream()
        .filter(f -> !f.declaringType().equals(resolvedClass.asType()) && f.accessSpecifier() != AccessSpecifier.PRIVATE)
        .collect(Collectors.toList());
```

**Comment by ftomassetti** [comment]
Nice, looks easy enough to use
