### ISSUE TITLE
Resolving anonymous classes and methods within them doesn't work

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1599]
Currently I am struggling to resolve the type of variables that have anonymous class types and any methods called of those anonymous types. Take following code:

```
public abstract class A {
  public abstract void bar();
}

public void foo() {
  A myVar = new A() {
    public void bar() {System.out.println("bar");}
    public void bar2() {System.out.println("bar2");}
  };

  myVar.bar();
  myVar.bar2();
}
```

If I try to calculate the resolved type of `myVar.bar()` I get the `public abstract void bar();` from the original abstract class declaration. If I try to resolve `myVar.bar2()`, I get an `UnsolvedSymbolException`. Similarly, if I try to resolve the type of myVar, I only get the abstract class A.

Is this the desired behaviour? It seems as though it is not currently possible to work with anonymous classes properly. Or is there something I am missing?

**Comment by matozoid** [comment]
Does this have anything to do with #1436?

**Comment by jjbr** [comment]
I believe they are related, yes, although the approach described in #1436 seems to be slightly different. From what I can see they may, in essence, come down to the same issue, though.

**Comment by matozoid** [comment]
Then I'll declare this a bug report too.

**Comment by jjbr** [comment]
I just stumbled on a case where the core of this issue produces an arguably even less desirable result. If I implement and instantiate an interface with an anonymous implementation and try to resolve the constructor call, JavaParser throws a ClassCastException. Take the following code as example:

```
	CompilationUnit cu = JavaParser.parse(
			"public class X {" +
			"   interface Foo {" +
			"       public void foo();" +
			"   }" +
			"   public void bar() {" +
			"       Foo f = new Foo() {" +
			"           @Override" +
			"           public void foo() {System.out.println(\"Out\");}" +
			"       };" +
			"   }" +
			"}");

	ClassOrInterfaceDeclaration xClass = cu.getClassByName("X").get();
	ObjectCreationExpr creationExpr = (ObjectCreationExpr)
				((VariableDeclarationExpr)xClass.getMethods().get(0).getBody().get().getStatement(0).getChildNodes().get(0)).getVariable(0).getInitializer().get();
	creationExpr.resolve(); // throws ClassCastException
```

At the end there we get a ClassCastException because the symbol solver first resolves the type of the object to be created as the interface Foo. Consequently, when it tries to find the constructor, it tries to cast the resolved type to a ResolvedClassDeclaration, as only classes are assumed to have constructors. In this case, however, the type was resolved to be a JavaParserInterfaceDeclaration and it obviously doesn't work. 

I believe support for anonymous classes would add some valuable additional functionality to the symbol solver. What is your opinion on this topic?

**Comment by matozoid** [comment]
My opinion is that this is required functionality, and missing it is a bug. The only expert at the symbol solving code is currently rather busy and I'm kind of embarrassed that these fundamental bugs stay unfixed for so long.

**Comment by jjbr** [comment]
> The only expert at the symbol solving code is currently rather busy

The unfortunate reality in a lot of open-source projects

**Comment by matozoid** [comment]
Yep, for the symbol solver and lexical preserving printer we're running on PR's from occassional contributors.

**Comment by ftomassetti** [comment]
I agree that this is a bug, obviously. Support for anonymouse classes is really poor at the moment, and this is an example. In this case there is no really a constructor for the interface, am I right? So that should be treated as a special case in the Symbol Solver imho.

@jbrips do you feel like creating a PR with a failing test? Perhaps we can take it from there or guide you in fixing it, if you feel like it :)

**Comment by jjbr** [comment]
> @jbrips do you feel like creating a PR with a failing test? Perhaps we can take it from there or guide you in fixing it, if you feel like it :)

Yes, I will look into it. :)

**Comment by maartenc** [comment]
As far as I see it the current behaviour is correct.
The symbol solver tries to solve the type of variables like the compiler does it. It doesn't try to guess the runtime type of a variable, but the static type.

Since you declare myVar of type A, that is exactly the type you will get when resolving it. And since there is no bar2() method on type A, the exception is normal.

Maarten
