### ISSUE TITLE
Allow to keep comments in memory

### ISSUE THREAD

**Issue by jmvivo** [javaparser/javaparser#16]
In commit https://github.com/matozoid/javaparser/commit/a27c8a84c84d7e9b008b14d362555f754a981672 ASTParser has been changed to don't store comments in memory.

In some cases, as our case (Parse Compilation units, make some changes  after a process and replace the original file) this can cause to loose comments (that was one main problem in original library version).

We need some way to configure this behaviour.

Thanks in advance.

**Comment by stepinto** [comment]
Hi jmvivo,

Sorry if my commit breaks your code. 

Could you show me how do you use ASTParser? Note that "special_tokens" (which I removed) is a private member.

I agree we need some way to configure the parser. In my case, I only need the class structure and I need it to be super fast and small memory footprint.

**Comment by jmvivo** [comment]
Hi stepinto,

> Could you show me how do you use ASTParser? Note that "special_tokens" (which I removed) is a private member.

You're right, there is no problem about this change. I'm sorry. It just was a confusion.

I had found a bug than I thought It's related to this commit. I'll create a new Issue to report it.

Thank you very much.
