### ISSUE TITLE
work line by line from source code

### ISSUE THREAD

**Issue by freefire4547** [javaparser/javaparser#1602]
Is it possible to find variables, operators, function calls from a certain single line in the source code ? From each line of source code I need to find what variable is modified,and what variable is accessed and what function call is made.Sorry if this question is too basic, I am novice here.

**Comment by matozoid** [comment]
Hi! When you parse, you get `Node`s. You can ask these nodes for the begin and end position.

If you want to get a good start, grab the book: https://leanpub.com/javaparservisited

**Comment by freefire4547** [comment]
So you mean I should first parse full class and then search nodes with specific line number ?

**Comment by matozoid** [comment]
I mean that you should read the book, because you do not have the basic knowledge for using this library. You can get it for free if you like.
