### ISSUE TITLE
Parse MethodDeclaration

### ISSUE THREAD

**Issue by cdtpinto** [javaparser/javaparser#1603]
Basically, having a MethodDeclaration object, I  want to parse it.

I checked the available parsing methods and there are methods to parse expressions of variable declarations, to parse package declarations, etc... but there is no `parseMethodDeclaration()`.

What approach should I take in order to do this? Should I get the body declaration and the try to parse it? The problem with this solution is that I also need to parse the declaration itself (p.e. `public void example()`).

Can anyone give me a hand with this?

**Comment by matozoid** [comment]
Hi! `MethodDeclaration` is a `BodyDeclaration`, so that's the parse method to use. After that you can cast it to `MethodDeclaration`. Note that it has be complete, so something like `public void example { }`.

**Comment by matozoid** [comment]
I assume this is answered.
