### ISSUE TITLE
Figure out what JarTypeSolver.getJarTypeSolver is meant to do

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1615]
It will build a global `JarTypeSolver` for several jars at once, but why global? Why is it unused? Why doesn't `JarTypeSolver` have a public interface for adding jars?

**Comment by ftomassetti** [comment]
I think the reason for having one instance is that in this way we share the ClassPool. We had the problem of having classes in one JAR depends on classes in another JAR and for ASM to work correctly it needs to be aware of all the JARs

**Comment by matozoid** [comment]
Ah right. That leaves the question why it is currently unused, and if we can't make that a feature of the class instead of having a static field.

**Comment by jokster** [comment]
@ftomassetti But that makes it impossible to work with different class paths on different parsings within the same jvm run.

This wouldn't be so bad, if CombinedTypeResolver would work as expected. But this is prevented by https://github.com/javaparser/javaparser/issues/1771

**Comment by ftomassetti** [comment]
Yes, you are right @jokster . This needs some thinking, taking into account the nature of Javassist and the way the ClassPool works

**Comment by jokster** [comment]
@ftomassetti I'll try to find a solution tomorrow. If I achieve something working, 'll fork and create a pull request.
