### ISSUE TITLE
TypeParameters/TypeArguments

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#162]
For method references, the grammar currently reads some TypeParameters() instead of some TypeArguments(). This is wrong and untested and may throw a ClassCastException at some point. Note that there are two places to fix for method references in the grammar.

**Comment by matozoid** [comment]
Can you explain why this is not a bug?

**Comment by ptitjes** [comment]
I'm curious too! :p

**Comment by SmiddyPence** [comment]
not sure maybe hot keyed it somehow.

**Comment by matozoid** [comment]
I'm so confused!

**Comment by matozoid** [comment]
Fixed on master.
