### ISSUE TITLE
Get operators and operands in CompilationUnit

### ISSUE THREAD

**Issue by everplayed** [javaparser/javaparser#1622]
I am implementing Halstead metrics and am using JavaParser to parse the code from java files.

I need to get the total and uniqueoperators and operands in a file.

I don't know if this is the best idea, but I am thinking about walking the CompilationUnit and checking of the nodes have instances of operators and operands.

Can anyone tell me how can I do this? How can I check if the nodes have instances of operators and operands.

**Comment by matozoid** [comment]
Well, `UnaryExpr`, `AssignExpr`, and `BinaryExpr` all have an operator. So if you visit those (check out the book if you need more information) you can find all operators in the `CompilationUnit`. The operands are also in those nodes.

**Comment by everplayed** [comment]
Thank you very much. I will see what I can do. When I have a solution, I will post it.

**Comment by cdtpinto** [comment]
Well, I implemented the logic, but it seems that JavaParser misses the ASSIGN operator in expressions like `String str = "";` . In this case, it doesn't detect = as an operator.

I used [this code](https://pastebin.com/tEdKciBN) and JavaParser returned [these results](https://pastebin.com/fm2exJ8U).

The two ASSIGN operators that are missing are the ones in the lines `int z = a + b;` and `boolean y = !c;`.

Is this a bug or am I missing something?

I also noticed that JavaParser doesn't consider `instanceof` as an operator. Am I right?

**Comment by cdtpinto** [comment]
BTW, this is the code that I implemented:

```
m.walk(node -> {
            if (node instanceof UnaryExpr) {
                UnaryExpr ue = (UnaryExpr) node;
                System.out.println(ue.getOperator().asString());
            } else if (node instanceof AssignExpr) {
                AssignExpr ae = (AssignExpr) node;
                System.out.println(ae.getOperator().asString());
            } else if (node instanceof BinaryExpr) {
                BinaryExpr be = (BinaryExpr) node;
                System.out.println(be.getOperator().asString());
            }
        });
```
m is a `MethodDeclaration`.

**Comment by everplayed** [comment]
Well, I implemented the logic, but it seems that JavaParser misses the ASSIGN operator in expressions like `String str = "";` . In this case, it doesn't detect = as an operator.

I used [this code](https://pastebin.com/04FxBth4) and JavaParser returned [these results](https://pastebin.com/fm2exJ8U).

The two ASSIGN operators that are missing are the ones in the lines `int z = a + b;` and `boolean y = !c;`.

Is this a bug or am I missing something?

I also noticed that JavaParser doesn't consider `instanceof` as an operator. Am I right?

**Comment by everplayed** [comment]
BTW, this is the code that I implemented:

```
m.walk(node -> {
            if (node instanceof UnaryExpr) {
                UnaryExpr ue = (UnaryExpr) node;
                System.out.println(ue.getOperator().asString());
            } else if (node instanceof AssignExpr) {
                AssignExpr ae = (AssignExpr) node;
                System.out.println(ae.getOperator().asString());
            } else if (node instanceof BinaryExpr) {
                BinaryExpr be = (BinaryExpr) node;
                System.out.println(be.getOperator().asString());
            }
        });
```
m is a `MethodDeclaration`.

**Comment by everplayed** [comment]
BTW, this is the code that I implemented:

```
m.walk(node -> {
            if (node instanceof UnaryExpr) {
                UnaryExpr ue = (UnaryExpr) node;
                System.out.println(ue.getOperator().asString());
            } else if (node instanceof AssignExpr) {
                AssignExpr ae = (AssignExpr) node;
                System.out.println(ae.getOperator().asString());
            } else if (node instanceof BinaryExpr) {
                BinaryExpr be = (BinaryExpr) node;
                System.out.println(be.getOperator().asString());
            }
        });
```
m is a `MethodDeclaration`.

**Comment by matozoid** [comment]
Here's probably the most useful article on JP: http://javaparser.org/inspecting-an-ast/
That will give you the ability to find out what code construct maps to what AST :-)

Sorry for the short answer, I've got a headache :-/

**Comment by matozoid** [comment]
How is it going here?

**Comment by matozoid** [comment]
No response.

**Comment by berabulut** [comment]
> Well, I implemented the logic, but it seems that JavaParser misses the ASSIGN operator in expressions like `String str = "";` . In this case, it doesn't detect = as an operator.
> 
> I used [this code](https://pastebin.com/04FxBth4) and JavaParser returned [these results](https://pastebin.com/fm2exJ8U).
> 
> The two ASSIGN operators that are missing are the ones in the lines `int z = a + b;` and `boolean y = !c;`.
> 
> Is this a bug or am I missing something?
> 
> I also noticed that JavaParser doesn't consider `instanceof` as an operator. Am I right?

Using your code you can detect it with using `VariableDeclarationExpr`

```
...
else if (node instanceof VariableDeclarationExpr) {
...
}
```

```
String str = "";
int z = x + 1;
int y = 2 - 1;
``` 

YAML output:

```
- statement(Type=ExpressionStmt): 
    expression(Type=VariableDeclarationExpr): 
        variables: 
            - variable(Type=VariableDeclarator): 
                initializer(Type=StringLiteralExpr): 
                    value: ""
                name(Type=SimpleName): 
                    identifier: "str"
                type(Type=ClassOrInterfaceType): 
                    name(Type=SimpleName): 
                        identifier: "String"

- statement(Type=ExpressionStmt): 
    expression(Type=VariableDeclarationExpr): 
        variables: 
            - variable(Type=VariableDeclarator): 
                initializer(Type=BinaryExpr): 
                    operator: "PLUS"
                    left(Type=NameExpr): 
                        name(Type=SimpleName): 
                            identifier: "x"
                    right(Type=IntegerLiteralExpr): 
                        value: "1"
                name(Type=SimpleName): 
                    identifier: "z"
                type(Type=PrimitiveType): 
                    type: "INT"
- statement(Type=ExpressionStmt): 
    expression(Type=VariableDeclarationExpr): 
        variables: 
            - variable(Type=VariableDeclarator): 
                initializer(Type=BinaryExpr): 
                    operator: "MINUS"
                    left(Type=IntegerLiteralExpr): 
                        value: "2"
                    right(Type=IntegerLiteralExpr): 
                        value: "1"
                name(Type=SimpleName): 
                    identifier: "y"
                type(Type=PrimitiveType): 
                    type: "INT" 
```
