### ISSUE TITLE
How to get type fields.

### ISSUE THREAD

**Issue by ivanjunckes** [javaparser/javaparser#1628]
Could anyone help to answer this question? I have the same doubt.

https://stackoverflow.com/questions/22680937/how-to-get-class-level-variable-declarations-using-javaparser

**Comment by ftomassetti** [comment]
Isn't the answer present already correct?

**Comment by matozoid** [comment]
Answered it. Too bad people are posting question on StackOverflow and not here, where they will be answered quckly by the maintainers of the library.

**Comment by matozoid** [comment]
@ftomassetti it was in 2014 :-D

**Comment by matozoid** [comment]
I guess this is answered.
