### ISSUE TITLE
Missing EOL when add imports if the class not exist imports before

### ISSUE THREAD

**Issue by xinluke** [javaparser/javaparser#1634]
if the class not exist import before .if add import and use  LexicalPreservingPrinter to print, it look like that missing EOL ;

the code like that
```
@Test
    public void print() throws IOException {
        System.setProperty("line.separator", "\n");
        CompilationUnit compilationUnit = JavaParser.parse("package com.wangym.test;\nclass A{ }");
        LexicalPreservingPrinter.setup(compilationUnit);
        NodeList<ImportDeclaration> imports = compilationUnit.getImports();
        String str = "lombok.Data";
        imports.add(new ImportDeclaration(str, false, false));
        String newBody = LexicalPreservingPrinter.print(compilationUnit);
        FileCopyUtils.copy(newBody.getBytes("utf-8"), new File("c:/A.java"));
    }
```
the file we get
```
package com.wangym.test;import lombok.Data;


class A{ }
```
pom.xml info
```
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
            <version>3.6.8</version>
        </dependency>
```

**Comment by matozoid** [comment]
Thanks for reporting this!

**Comment by jlerbsc** [comment]
We can reproduce this issue with this test case

    public class Issue1634Test extends AbstractLexicalPreservingTest  {
    
    @Test
    public void testWithLexicalPreservationEnabled() {
        
        String actual = 
                "package com.wangym.test;\nclass A{ }";
        
        StaticJavaParser.setConfiguration(new ParserConfiguration());
      
        CompilationUnit cu = StaticJavaParser.parse(actual);
        LexicalPreservingPrinter.setup(cu);
        
        NodeList<ImportDeclaration> imports = cu.getImports();
        String str = "lombok.Data";
        imports.add(new ImportDeclaration(str, false, false));
        
        System.out.println(LexicalPreservingPrinter.print(cu));
    }
    }
