### ISSUE TITLE
Missing FloatLiteralExpr

### ISSUE THREAD

**Issue by jrfaller** [javaparser/javaparser#1636]
Hi all, and thanks for the awesome javaparser!

I realized that it is missing a float literal expression, therefore I have trouble to generate code where a float typed value is required.

Is there a workaround?

Cheers!

**Comment by matozoid** [comment]
Hi! `DoubleLiteralExpr` is taking the role of represeting doubles *and* floats. Can you try using that?

#664 is where we plan to put this right. Somewhere in the future...

**Comment by jrfaller** [comment]
Hi and thanks for the quick answer.

Unfortunately I cannot use DoubleLiteralExpr because I end-up with type errors in the generated code. For instance I have coded a program that aims at replacing the body of a float-typed method body by "return 0F;". However using

```
BlockStmt block = new BlockStmt();
block.addStatement(new ReturnStmt(new DoubleLiteralExpr(0)));
decl.setBody(block);
```

I end up with "return 0.0" which triggers a compile error.

Maybe I can generate the code using a lower level expression?

**Comment by ftomassetti** [comment]
Can't you use the constructor that is taking a string?
http://static.javadoc.io/com.github.javaparser/javaparser-core/3.6.8/com/github/javaparser/ast/expr/DoubleLiteralExpr.html#DoubleLiteralExpr-java.lang.String-

**Comment by matozoid** [comment]
What @ftomassetti says, because the node represents the exact text as found in the source code, so you can make it look like anything you want.

**Comment by jrfaller** [comment]
Thanks a lot @ftomassetti and @matozoid! It is working well with this method! I was afraid of using it because of the "considered private" documentation but it does the job really well.

**Comment by matozoid** [comment]
Only the one with the `TokenRange` is considered private ;-)

**Comment by jrfaller** [comment]
@matozoid ha yes you're right ;)

**Comment by MathiasBollaert** [comment]
Hi,

Although I found a workaround, I do also need FloatLiteralExpr to implement a light interpreter over the parser and the solver.

#664 is 1,5 year old, is there any clue on when it will be solved ?

Thanks a lot.

**Comment by matozoid** [comment]
Hi @MathiasBollaert, this project is maintained by some people in their spare time, so yes, sometimes issues get pretty old. This one because it is waiting for a major release, which will not be anytime soon because nobody has enough spare time to put in it right now. It's waiting for a major release because we can't do this backwards compatible, and every user will have to pay attention to this change or risk breaking their software.

**Comment by MathiasBollaert** [comment]
Thank you for answering, I didn't realize the backward compatibility issue, otherwise I would have proposed myself to give it a try ;)

**Comment by matozoid** [comment]
#664 is the main issue.
