### ISSUE TITLE
javaparser.org?

### ISSUE THREAD

**Issue by ooxi** [javaparser/javaparser#164]
Is there any interest in using a top level domain like javaparser.org? If cost is an issue I'm sure funding could be raised in no time.

**Comment by ftomassetti** [comment]
I think it could be a great idea: we could just pay the domain and host it on GitHub pages

**Comment by ooxi** [comment]
I thought so, too. Who to register the domain to?

**Comment by ftomassetti** [comment]
I am glad to pay for it (it is a few euros :D) but I would register it under the name of @matozoid

**Comment by ooxi** [comment]
That's great! What's your opinion on this @matozoid ?

**Comment by matozoid** [comment]
Seems a bit superfluous to me, but register whatever you like :)

**Comment by SmiddyPence** [comment]
I'm not against the idea.  I would just be aware that the dependency co-ordinates could get quite confusing for people.

It has already changed from code.google.com to github.com.  

If people would like to do it, I would suggest a redirect to the http://javaparser.github.io/javaparser  initially and tie in any co-ordinates to a major change version change.

**Comment by matozoid** [comment]
My neutral reaction is caused by past experiences, where projects were more interested in setting up a fancy website than actually working on the project. So I've learned to keep overhead small to focus on actual useful work.

**Comment by ftomassetti** [comment]
I agree that we would not have much time to dedicate to the website. However I am a little concerned that someone could register the name and cause confusion.

**Comment by ooxi** [comment]
Since no one is opposed to the idea of registering the javaparser.org domain (that does not necessary mean we have to change the Maven artefact coordinates) I would suggest doing so @ftomassetti

**Comment by SmiddyPence** [comment]
Sure fair point.

**Comment by matozoid** [comment]
Did anything happen since August?

**Comment by ooxi** [comment]
@ftomassetti would you register javaparser.org?

**Comment by ftomassetti** [comment]
I have done it now

**Comment by ooxi** [comment]
Thats great news :)

**Comment by matozoid** [comment]
It doesn't look very impressive yet :-) -> http://javaparser.org/

**Comment by ftomassetti** [comment]
Right, but at least they cannot take the domain.
But yes, we should do something with it :)

**Comment by ooxi** [comment]
@ftomassetti could you [create an A record](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/#configuring-an-a-record-with-your-dns-provider) to point to GitHub? Than a pull request can take care of creating a website :)

**Comment by ftomassetti** [comment]
Done, let's run `dig javaparser.org +nostats +nocomments +nocmd` in 1h or so and check

**Comment by ooxi** [comment]
Works for me

```
$ dig  javaparser.org

; <<>> DiG 9.9.5-9ubuntu0.4-Ubuntu <<>> javaparser.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49847
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;javaparser.org.            IN  A

;; ANSWER SECTION:
javaparser.org.     599 IN  A   192.30.252.153
javaparser.org.     599 IN  A   192.30.252.154

;; Query time: 54 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Fri Jan 22 09:00:13 CET 2016
;; MSG SIZE  rcvd: 75
```

**Comment by matozoid** [comment]
Looks fancy already! I guess we can follow up with issues for improving the documentation.

**Comment by ftomassetti** [comment]
Yes: I think we need tutorials and FAQ
