### ISSUE TITLE
Get information of a specific line in the code

### ISSUE THREAD

**Issue by dmy365** [javaparser/javaparser#1647]
I need to find a way to analyse a specific line of code. For example, I have this code:

```
public class Example {
	public static void m() {
		String s = "This is \n"
                + "a String \n"
                + "example";
	}
}

```

Let's say that I want to analyse line 4 `                + "a String \n"`. In this case, I want to get the information that in that line there is an operator `+` and a String literal `"a String \n"`.

I wondered around the JavaParser methods, but couldn't fint a method that returns the information of a specific `Position`, the best I got was trying to set a `Range` of just one line, but by doing that, I can only get the information of the range itself and not the content of the line.

Can anyone point me in a right direction to accomplish this?

**Comment by freefire4547** [comment]
You can first visit CompilationUnit using "ExpressionStmt" . You can make HashMap<Position,ExpressionStmt> there to store expression corresponding to each line and from there with line number you can find expression on each line. Then from ExpressionStmt take out things that you want to get.

**Comment by matozoid** [comment]
Sound like you might want the tokens. Try compilation.getTokenRange() and see if that suits your need.

**Comment by dmy365** [comment]
It seems that @matozoid tip fits better for my needs. This way, I can keep track of the `Position` of each token and check if the token if an operator, a String literal, etc...
I am gonna try and code a solution and then post it here.

**Comment by dmy365** [comment]
So, I am coding the solution and so far I got this:

```
public static void getInfoOnLineOfCode(CompilationUnit cu, int line) {
        Optional<TokenRange> tokens = cu.getTokenRange();

        tokens.get().forEach(t -> {
            if (t.getRange().get().begin.line == line) {
                doStuff();
            }
        });
    }
```

As far as I can see, if there are no comments in the file, there is no problem, because every line of code will have at least one token (correct me if I'm wrong). However, if I have, for example this code:

```
public class Example {
	/*
	 * Some comment
	 */
}
```

And I call `getInfoOnLineOfCode(cu, 3);`, `doStuff()` will never be called, because the comment token starts in line 2 and not line 3, thus it won't work properly.

Any suggestions here? Should I give up `t.getRange().get().begin`?

**Comment by matozoid** [comment]
Your algorithm has a problem with tokens that span more than one line. Try using .end as well.

**Comment by matozoid** [comment]
@dmy365 - have you gotten it to work?

**Comment by matozoid** [comment]
Assuming this is answered.
