### ISSUE TITLE
Annotation with Parameter Enum

### ISSUE THREAD

**Issue by stevekv** [javaparser/javaparser#1650]
Hello,

I was wondering how one would realize something like this with javaparser:

```
@Temporal(@TemporalType.TIMESTAMP)
private Date creationDate;
```

I would like to programmatically add the javax.persistence.Temporal Annotation to a field. But it takes an Enum as parameter (javax.persistence.TemporalType). So the NormalAnnotationExpr.addPair(key,value) can not be used?!?

Thanks for any advice.
Steve

**Comment by matozoid** [comment]
Hi!

Especially for this type of question we have this article: http://javaparser.org/inspecting-an-ast/ - please take a few minutes to read it.

Also: #1635 has made a change to that method in release 3.6.9, so be sure to upgrade to that.

**Comment by stevekv** [comment]
Hi,

that helped a lot, thanks. I can realize it via the addSingleMemberAnnotation().

You may close this question.

Thanks again,
steve

**Comment by matozoid** [comment]
Good luck!
