### ISSUE TITLE
Where do I write my code to use javaparser?

### ISSUE THREAD

**Issue by victorbergar** [javaparser/javaparser#1652]
Hello. I am a student of computer engineering, just starting in this world.

I have already downloaded javaparser and configured it in my Eclipse.

But now how can I use it? Where should I insert my code? Should I create a new package within the Javaparser-core project?

**Comment by ftomassetti** [comment]
Hi Victor,
First of all I wish you all best for your studies.
I think what you need is a tutorial on basic Java concepts. This questions has nothing to do with Javaparser. It is just that you need to understand how to create a project using external libraries and compile it properly. When I was starting out with Java I read "Thinking in Java". I am not sure if it is still a good starting point but I would try to check it out. Alternatively you can also look at the example projects we created, like this one: https://github.com/javaparser/javaparser-maven-sample

I am afraid we will not be able to guide you step by step into creating this project and the best suggestion I can give you at this time is to spend some time on tutorials. I know it is hard to starting out. I can assure you that it was the same for everybody.
