### ISSUE TITLE
Extracting method Parameters

### ISSUE THREAD

**Issue by Divya063** [javaparser/javaparser#1653]
Hi, I'm new to JavaParser, and I'm trying to extract the method parameters from the code given blelow.

```
package org.apache.tika;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class TikaDetectionTest {

    private final Tika tika = new Tika();

    /**
     * This test checks that Tika correctly detects all the file extensions
     * defined in the mime.types file (revision 819245) of the Apache HTTP
     * Server project. The tests were created with:
     * <pre>
     * cat docs/conf/mime.types | grep -v '#' | perl -lne '/\S\s+\S/ and do {
     *     my ($type, @ext) = split /\s+/;
     *     for my $ext (@ext) {
     *         print "assertEquals(\"$type\", tika.detect(\"x.$ext\"));";
     *     }
     * }'
     * </pre>
     */
    @Test
    public void testHttpServerFileExtensions() {

        assertEquals("audio/mpeg", tika.detect("x.mp3"));
        assertEquals("audio/mpeg", tika.detect("x.m2a"));
        assertEquals("audio/mpeg", tika.detect("x.m3a"));
    
       
    }

}
```
I need to extract parameters inside assertEquals and detect, as an example "audio/mpeg" and "x.m2a"
Is there any way to that? Thanks!

**Comment by matozoid** [comment]
Hi!
Yes, there is. If the use case is as simple like this, doing a `compilationUnit.findAll(StringLiteralExpr.class)` would give you all strings in the file. If not, you can find all MethodDeclarationExpr's, and find all `MethodCallExpr`'s inside it.

Do read http://javaparser.org/inspecting-an-ast/, and our main documentation is this book: https://leanpub.com/javaparservisited

**Comment by Divya063** [comment]
@matozoid Thanks for the quick reply, I would definitely try that out.

**Comment by matozoid** [comment]
Okay, let us know how it worked out.

**Comment by matozoid** [comment]
Assuming this is answered.
