### ISSUE TITLE
Make JP buildable on Java 10

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1658]
AppVeyor says we have a problem: https://ci.appveyor.com/project/ftomassetti/javaparser/build/2381

**Comment by kotari4u** [comment]
Yes i was able to replicate this when i was working on issue 1441 on java 10. I ran maven in debug mode and see that somewhere in apache utils or so (i did not remember exactly) it is validating version. Did not investigate further, instead reduced  jdk to 8 and built the project. I can check and see whats going on

**Comment by ftomassetti** [comment]
Is this error the one causing the build to file?
```
ERROR] /C:/projects/javaparser/javaparser-core/target/generated-sources/javacc/com/github/javaparser/SimpleCharStream.java:[4,29] unmappable character (0xFA) for encoding UTF-8
```

**Comment by matozoid** [comment]
I haven't looked at it - @kotari4u, consider yourself assigned :-)

**Comment by matozoid** [comment]
@kotari4u - can you also add java 10 to the Travis configuration?

**Comment by kotari4u** [comment]
Upgrading jacoco version to 0.8.1 and maven surefire plugin version to 2.21.0 resolved this issue. 
I have found test case failures in couple of classes where we have separate logic for java9. I had to write two different methods to support java 10 and anything > jdk9. Please find the [PR](https://github.com/javaparser/javaparser/pull/1666) with checked in code and let me know if you see any issues. 

References 
https://issues.apache.org/jira/browse/SUREFIRE-1439
https://blogs.apache.org/maven/entry/apache-maven-surefire-plugin-version
https://medium.com/criciumadev/java-10-migration-5d853f5b5f7e

Also, I am not aware of Travis much. I have looked at travis.yaml. If I understand correctly I just need to add oraclejdk10 ? Do not want to commit any changes with out prior knowledge, so did not work on Travis configuration

**Comment by matozoid** [comment]
Oh, yes, just add oraclejdk10 or whatever is best according to you.

**Comment by kotari4u** [comment]
Thanks added [PR](https://github.com/javaparser/javaparser/pull/1672)

**Comment by matozoid** [comment]
Thanks, @kotari4u !
