### ISSUE TITLE
Extend JsonPrinter with resolved type for a method

### ISSUE THREAD

**Issue by Arminmsg** [javaparser/javaparser#1659]
Hi,
My goal is to have a java file convert it to json file, similar like `JsonPrinter` does, but I additionally want to add the resolved method call type to the json file.

Example:
This is my sample file that I want to convert
``` java
import java.util.ArrayList;

public class ClassA {
    private static ArrayList x = new ArrayList();

    public static void main(String args[]) {
        x.add(123);
    }
}
```

Using the solver 
``` java 
List<MethodCallExpr> methodCalls = Navigator.findAllNodesOfGivenClass(cu, MethodCallExpr.class);

JavaParserFacade.get(new ReflectionTypeSolver()).solve(methodCalls.get(0)).getCorrespondingDeclaration().getQualifiedSignature();
``` 
I get `java.util.ArrayList.add(E)` and I want to extend the result of `JsonPrinter`

This is just an excerpt:
```json
...
{
          "body": {
            "statements": [
              {
                "expression": {
                  "name": {
                    "identifier": "add",
                    "resolvedType": "java.util.ArrayList.add(E)" // This is beeing added
                  },
                  "scope": {
                    "name": {
                      "identifier": "x"
                    }
                  },
                  "arguments": [
                    {
                      "value": "123"
                    }
                  ]
                }
              }
            ]
          }
...
```

My initial idea was for each `MethodCallExpr` the `parentNode` and walk up the tree, till I arrive at the root node and then use this path to find the right place in the json file to add the resolved method. But this didn't work as expected.

Is there a easy way to do this, without digging to deep into the library, or do I need to extend the "MethodCallExpr" class to save the resolved type and write a custom `JsonPrinter`?

**Comment by matozoid** [comment]
Hi! `JsonPrinter` was not built to print custom fields (or to do serious serialization!) so making a custom copy is a good idea. For custom data storage you can use `Node.data` (it's well documented,) so no need to extend anything.

**Comment by matozoid** [comment]
Assuming this is answered.
