### ISSUE TITLE
MethodResolutionLogic.findMostApplicable not return correct symbol reference when resolving overloaded method

### ISSUE THREAD

**Issue by daanschipper** [javaparser/javaparser#1660]
I have the following 6 methods:
- `info(Object)`
- `info(Object, Throwable)`
- `info(Object, JSONObject)`
- `info(Object, Object...)`
- `info(Object, Throwable, Object...)`

When I come across a `MethodCallExpr` of one of these functions and I try to resolve it to obtain the qualified signature, I'm receiving a `ResolvedMethodDeclaration` to the wrong method.

**Comment by daanschipper** [comment]
I've found the following: `MethodResolutionLogic.findMostApplicable` is called with all 6 relevant methods, but when calculating the applicable methods with 
```
List<ResolvedMethodDeclaration> applicableMethods = (List)getMethodsWithoutDuplicates(methods).stream().filter((m) -> {
    return isApplicable(m, name, argumentsTypes, typeSolver, wildcardTolerance);
}).collect(Collectors.toList());
```
only one method (`info(Object, Object...)`) 'survives' the filter.

The stacktrace:

```
findMostApplicable:394, MethodResolutionLogic (com.github.javaparser.symbolsolver.resolution)
findMostApplicable:384, MethodResolutionLogic (com.github.javaparser.symbolsolver.resolution)
solveMethod:124, JavaParserTypeDeclarationAdapter (com.github.javaparser.symbolsolver.javaparsermodel.contexts)
solveMethod:95, ClassOrInterfaceDeclarationContext (com.github.javaparser.symbolsolver.javaparsermodel.contexts)
solveMethodInType:601, MethodResolutionLogic (com.github.javaparser.symbolsolver.resolution)
solveMethod:155, MethodCallExprContext (com.github.javaparser.symbolsolver.javaparsermodel.contexts)
solve:245, JavaParserFacade (com.github.javaparser.symbolsolver.javaparsermodel)
solve:128, JavaParserFacade (com.github.javaparser.symbolsolver.javaparsermodel)
resolveDeclaration:107, JavaSymbolSolver (com.github.javaparser.symbolsolver)
resolve:311, MethodCallExpr (com.github.javaparser.ast.expr)
```

**Comment by ftomassetti** [comment]
COuld you please show which method calls are solved incorrectly?
It would ideal if you could provide a failing test for this

**Comment by daanschipper** [comment]
I know that `info(Object, Throwable)` with the throwable being a `ResolvedUnionType` fails.

I'm now investigating this MethodCallExpr `log.info("Unable to process request ", e)` where e is either a `ServiceException` or `OAuthException`. 
We then end up in `findMostApplicable(List<ResolvedMethodDeclaration> methods, String name, List<ResolvedType> argumentsTypes, TypeSolver typeSolver, boolean wildcardTolerance)` with parameters:
- methods.size = 6 (thus all overloaded methods are correctly found)
- name = info
- argumentsTypes.size = 6 (ReferenceType of String, ResolvedUnionType)
- typeSolver
- wildcardTolerance = false

After calculating the applicable methods, the list only contains the `info(Object, Object...)` ResolvedMethodDeclaration

**Comment by daanschipper** [comment]
`getMethodsWithoutDuplicates(methods)` returns all methods, so that method seems to behave correctly

**Comment by daanschipper** [comment]
The problem is related to resolving a `MethodCallExpr` with a `ResolvedUnionType` as parameter, the resolver seems to not be able to find the corresponding `ResolvedMethodDeclaration`

**Comment by ftomassetti** [comment]
I suspect the issue is in finding the common type of the ResolvedUnionType

**Comment by daanschipper** [comment]
@ftomassetti In `MethodResolutionLogic.isApplicable()` with arguments:
- method: `warn(Object, java.lang.Throwable)`
- argumentTypes: [`java.lang.String`, `ResolvedUnionType`]

I noticed that the evaluation `boolean isAssignableWithoutSubstitution = expectedType.isAssignableBy(actualType) ||
                    (method.getParam(i).isVariadic() && new ResolvedArrayType(expectedType).isAssignableBy(actualType));` results to `false` (all 3 expressions), with
- expectedType:  `ReferenceType{java.lang.Throwable, typeParametersMap=TypeParametersMap{nameToValue={}}}`
- actualType: `[ReferenceType{java.io.IOException, typeParametersMap=TypeParametersMap{nameToValue={}}},
ReferenceType{java.lang.RuntimeException, typeParametersMap=TypeParametersMap{nameToValue={}}}]`

I'm wondering about the `expectedType.isAssignableBy(actualType)` clause, that should return true right?

**Comment by ftomassetti** [comment]
I do not understand: you have one expected type and actual types?

Maybe the issues is with ResolvedUnionType

**Comment by daanschipper** [comment]
This question is more about `ReferenceTypeImpl.isAssignableBy(ResolvedUnionType)` which is a part of `MethodResolutionLogic.isApplicable()`. Should that function return `true` or `false`?

**Comment by ftomassetti** [comment]
well, if the resolved union type has as a common ancestor something that is assignable to that particular reference type then it should return true, otherwise false

**Comment by jlerbsc** [comment]
@kgeilmann Why didn't you do a PR on JP project for this issue? I have reported your solution on a repository and it resolved this issue. Thanks

**Comment by kgeilmann** [comment]
It's easy, I didn't consider it as solution but as hack.

**Comment by jlerbsc** [comment]
Why did you consider it  as hack?

**Comment by kgeilmann** [comment]
The root cause for the problem is the ResolvedUnionType, which is something not really existent in Java. So I think the real solution would be to remove the ResolvedUnionType (which is doable, because the language spec clearly defines what the type of the exception inside a multi catch should be). -> The last spec I looked into was Java 8, so this might not be valid anymore.

The hack just adds an extra handling at exactly the here discovered case, but if I remember correctly there were other parts in the type checker, where the ResolvedUnionType is not handled correctly. I can't remember the details anymore, the hack was good enough for me at the time.
