### ISSUE TITLE
Question about resolved value declaration

### ISSUE THREAD

**Issue by Shoreray** [javaparser/javaparser#1665]
Hi,

I was inspecting the classes that implements the interface ResolvedValueDeclaration in the package com.github.javaparser.symbolsolver.javaparsermodel.declarations.
For my purpose, I'm mostly interested in three classes:
-- JavaParserSymbolDeclaration
-- JavaParserFieldDeclaration
-- JavaParserParameterDeclaration

There seems to be some duplication of functionality among them. JavaParserSymbolDeclaration can also represent a field declaration or a parameter declaration. 
Which of them is actually used by the symbol solver as the output type when resolving, say, a name expression representing a field?

**Comment by matozoid** [comment]
@ftomassetti - we missed this question! :-(

**Comment by ftomassetti** [comment]
Right. This is the case, in practice now JavaParserSymbolDeclaration is used just for variables. PR coming

**Comment by Shoreray** [comment]
Great. That simplifies things a lot.
Thanks for the answer.
