### ISSUE TITLE
'UnsupportedOperationException: removed child' with LexicalPreservingPrinter

### ISSUE THREAD

**Issue by rnorth** [javaparser/javaparser#1667]
Thanks for creating this project - it looks excellent!
I'm afraid I've hit a problem that occurs when using `LexicalPreservingPrinter`. I've included a code sample below that hits the problem on v3.6.10.

It could well be that I'm doing something wrong but it's unclear, especially as the problem does not occur when not using `LexicalPreservingPrinter`. (My intention in this code sample was simply to change the type of a variable; I reduced it to this from a larger trial refactoring).

```java
public class Main {

    public static void main(String[] args) throws Exception {
        String source = "public class Foo {\n" +
                "    public void foo() {\n" +
                "        Bar bar = new Bar();\n" +
                "    }\n" +
                "}";

        doWithoutPrettyPrint(source); // prints out as expected

        doWithPrettyPrint(source); // throws exception during transform:
        // Exception in thread "main" java.lang.UnsupportedOperationException: removed child(ClassOrInterfaceType) vs "Bar"   <89>   (line 3,col 9)-(line 3,col 11)
        //	at com.github.javaparser.printer.lexicalpreservation.Difference.applyRemovedDiffElement(Difference.java:389)
    }

    private static void doWithoutPrettyPrint(String source) {
        final CompilationUnit cu = JavaParser.parse(source);

        transform(cu);

        System.out.println(cu.toString());
    }

    private static void doWithPrettyPrint(String source) {
        CompilationUnit cu = JavaParser.parse(source);
        cu = LexicalPreservingPrinter.setup(cu);

        transform(cu);

        System.out.println(LexicalPreservingPrinter.print(cu));
    }

    private static void transform(CompilationUnit cu) {
        cu.findAll(VariableDeclarator.class).stream()
                .forEach(v -> {
                    v.setType("Baz");
                });
    }
}
```

**Comment by matozoid** [comment]
Maybe @ThLeu can help? Or else @ftomassetti ?

**Comment by ThLeu** [comment]
Hey @matozoid 
Sure, I can have a look at it, it may take some time though.
Will have a look as soon as I have a little more free time.

You can assign it to me if you like.

**Comment by matozoid** [comment]
@ThLeu that would be great! Do you have anything that could help @rnorth right now?

**Comment by ThLeu** [comment]
I fear not, after looking into it for a few minutes, it seems that this case is simply not supported yet or something with token and child element gets mixed up. Would have to look deeper into it first.

**Comment by MarvinWyrich** [comment]
@matozoid @ThLeu any news on this? For our software we need the LexicalPreservingPrinter, so that a small change does not change the whole file. The javaparser otherwise makes a great impression, so we would like to use it and not have to resort to less elegant solutions because of this bug. Is there a chance to prioritize the issue a bit higher? :)

**Comment by ftomassetti** [comment]
@MarvinWyrich it has to compete with other 300+ issues: from bugs, to ideas for improvements, to corner cases to consider. It is a ton of work so it become very, very difficult to offer any reassurance regarding when this will be fixed.

If this has an impact on you perhaps you could help speeding this up by providing a PR for a failing test. Or even better a PR for the solution :) We can work with you and help you familiarize with the codebase if needed.
