### ISSUE TITLE
Dump tests don't work because of false delimiter support on Windows

### ISSUE THREAD

**Issue by maxstreichert** [javaparser/javaparser#167]
I run junit Tests on eclipse on Windows and some tests fail because of false delimiter support.
The failing tests are all with the dump scenarios and assertions seem always like this: 

Expected: is "public class A {\r\n\r\n    Object foo = new Object();\r\n}"
     but: was "public class A {\n\n    Object foo = new Object();\n}"

The reason is that jBehave provides with @Given a string with OS-specific delimiters. In case of Windows the delimiter of the newline is "\r\n". But the javaparser provides after parsing a string the Unix-specific newline-delimiter, in this case "\n".

What I tried to do: I changed the delimiters of the story-files to the Unix-like, and checked via notepad++ that there are really Unix-like delimiters, but I didn't work :(

**Comment by ftomassetti** [comment]
I suspect most contributors run test under Linux so does also our CI so we did not notice such errors so thank you for reporting them.

Can you tell us which tests exactly are failing? Can you report the error messages?

Thanks!

**Comment by SmiddyPence** [comment]
Investigating.

Ok I have reproduced on Windows.  

Thanks for reporting.

**Comment by SmiddyPence** [comment]
Will double check fix on linux later and file pull request.
