### ISSUE TITLE
How to use JarTypeSolver to get all methods

### ISSUE THREAD

**Issue by anyOne89** [javaparser/javaparser#1671]
Hi,

Im struggling to read in a jar file to get a specific class out of it and iterate trough all the methods.

Probably there is a simple way ... In the end I need a BlockStmt from that method to see if the method starts with a if condition .. `	if (method.getBody().get().getChildNodes().get(0) instanceof IfStmt) {`

So I startetd with the following code:
```
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
JarTypeSolver jarTypeSolver = new JarTypeSolver(new File("C:\\Users\\anyOne\\Downloads\\javaparser-core-2.0.0.jar"));
combinedTypeSolver.add(jarTypeSolver);
```

// Right now I would get a java.io.FileNotFoundException.
```
CompilationUnit cu= JavaParser.parse(new FileInputStream(new File("com.github.javaparser.ast.body.MethodDeclaration")));

cu.findAll(ClassOrInterfaceDeclaration.class, isExtendsClientApi).stream()//
	.map(-> {
		List<MethodDeclaration> methods = new ArrayList<>();
		myOwnMethodsVisitorAdapter.visit(arg0, methods);
		return methods;
	}).forEach(methodList -> methodList.stream().forEach(method -> {
 // do somting with the method ....
```

```
VoidVisitorAdapter<List<MethodDeclaration>> myOwnMethodsVisitorAdapter= new VoidVisitorAdapter<List<MethodDeclaration>>() {
			@Override
			public void visit(MethodDeclaration n, List<MethodDeclaration> arg) {
				arg.add(n);
				super.visit(n, arg);
			}
		};
```

**Comment by matozoid** [comment]
Hi! This sounds pretty confused, so let's start with clearing this up:
- JavaParser parses Java source code. A class file is compiled Java code, it can't read that.
- Symbol resolution is about taking source code like "A bla = new A()", and asking "what is this A?". A symbol solver could answer "it's `com.bla.bla.A`, it can be found in xyz.jar". This is what the symbol solver might use jars with classes for: to find types. It uses the javassist library to look in jars.

**Comment by anyOne89** [comment]
OK thnak you now it is a bit clearer I mixed things up.

so my plan iterate trough all methods of a class to see if the BlockStmt if starting with a if condition will only work with Java source code ?

**Comment by ftomassetti** [comment]
Hi @anyOne89 , thank you for your question. Please take the time to re-read it and improve the layout of your question as it would make easier to understand it and answer it properly. Written communication is hard, especially between all of us who are not English native speakers.

Now, do you want to examine classes in a JAR? Ok, I think you can just use Javassist. JavaParser is for analyzing classes of which you have the source code.

**Comment by anyOne89** [comment]
ok i got it now =)
@ftomassetti thanks I will try it with Javassist.

**Comment by ftomassetti** [comment]
Happy to help!
Closing the issue
