### ISSUE TITLE
Get primary type name from a JavaParser.parse(MultipartFile)

### ISSUE THREAD

**Issue by UHDante** [javaparser/javaparser#1674]
I'm new to GitHub, so don't be rough at me for not knowing where to post this :).
Following [this question](https://github.com/javaparser/javaparser/issues/1341)  (Very helpful by the way) i need to use the method "getPrimaryType" but I'm facing this issue:

Working with Angular, I receive the files in a MultipartFile type. So, is there any way to include the constructor JavaParser.parse(multipartFile) and fill the file name to work with getPrimaryType ?

Im going with -> JavaParser.parse(multipartFile.getInputStream()); 
but I need -> JavaParser.parse(multipartFile).getPrimaryTypeName();

Thanks in advance.

**Comment by daanschipper** [comment]
I don't understand the `MultipartFile` that you're talking about. I'm assuming that you have a single file populated with multiple java files, or in JavaParser terms `CompilationUnits`.

So if you want to parse this with I would think that you would need to have some way of splitting the InputStream for each `CompilationUnit`, which you can than parse with JavaParser and get the `PrimaryType`.
I don't know of any functionality that supports this out of this box.

Another option that you could try is to use `JavaParser.parse(String code)` and hope that no `ParseException` is thrown. Then you could visit the `ClassOrInterfaceDeclaration` nodes of the `CompilationUnit` to retrieve the top level declarations.

**Comment by matozoid** [comment]
Note that `getPrimaryType` only works if you read the source code from a *file*. It compares the filename to the types in the file and returns the one matching the filename. If there is no filename, there is no exact way to say what the primary type is.

**Comment by UHDante** [comment]
Hi!! thanks for your time guys. I'm really grateful.
By MultipartFile I mean that my rest api receive this type: `org.springframework.web.multipart.MultipartFile`
A representation of an uploaded file received in a multipart request. 
The file contents are either stored in memory or temporarily on disk. In either case, the user is responsible for copying file contents to a session-level or persistent store as and if desired. The temporary storage will be cleared at the end of request processing.
Since:29.09.2003 Author:Juergen Hoeller

@matozoid I noted that, I was just trying to avoid to do this:
```
for (MultipartFile multipartFile : files) {
    // If we could add new functionality like : JavaParser.parse(multipartFile).getPrimaryTypeName()
    // the next lines won't be necessary and the behavior could be the same like a file.
    String className = multipartFile.getOriginalFilename().split("\\.")[0];
    
    cu = JavaParser.parse(multipartFile.getInputStream());
    ClassOrInterfaceDeclaration classOrInterfaceDeclaration = cu.getClassByName(className).orElse(null); 
    if(classOrInterfaceDeclaration == null) 
        classOrInterfaceDeclaration = cu.getInterfaceByName(className).orElse(null);
    If(classOrInterfaceDeclaration == null)
       throw new ServiceException("No class or interface found in the file")
}
```
Because the multyfile type was originally a file readed from the file system and split into pieces to be sended and reassembled at the server.

**Comment by matozoid** [comment]
Ah, I think you want to do a `cu.setStorage` with that original filename. Then `getPrimaryType` should work.

**Comment by UHDante** [comment]
cu.setStorage is not valid in this case because I have the List<MultipartFile> files stored in memory, writing it to disk is not an option, so i can't get a path. The code I wrote before works fine and it's ok to me.
In any case, I just wanted to suggest a new functionality because MultipartFile is not included on your cu.parse() function and if any one use a normal upload component from angular you get: 

`MultipartHttpServletRequest request;`
`List<MultipartFile> files = request.getFiles("files");` 

They have to write additional code when it could be treated as a file does.
Thanks any way!!.
Your parse is awesome, hope you guys keep it like this 🥇

**Comment by matozoid** [comment]
If you want to clean it up, try setStorage and Paths.get.

MultipartFile is not part of the JDK, it seems to be part of Spring?. Since JavaParser runs without dependencies, we can't really support it. But this issue will document how to do it, I hope :-)

Thanks! Feel free to suggest more things :-)
