### ISSUE TITLE
UnsolvedSymbolException when trying to resolve FieldDeclaration that is an inner class of an extending type of an extending type

### ISSUE THREAD

**Issue by daanschipper** [javaparser/javaparser#1675]
When trying to resolve the following `FieldDeclaration` I'm getting an UnsolvedSymbolException

```
public class X extends Y {
   private Foo foo;
}

public class Y extends Z { }

public class Z {
    public static class Foo {}
}
```

`JavaParserTypeDeclarationAdapter.solveType()` only looks at the internal classes of its direct ancestor, but fails to do this iteratively. So the internal classes of `Y` are checked for a `TypeDeclaration` with name `Foo`, but of course this isn't found. However, the internal types of ancestor of `Y` aren't evaluated at all.

The stacktrace:
```
Exception in thread "main" UnsolvedSymbolException{context='unknown', name='LengthConfig'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:438)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:496)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:492)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserFieldDeclaration.getType(JavaParserFieldDeclaration.java:72)
```

**Comment by jlerbsc** [comment]
This issue seems to be resolved.

    public class Issue1675Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {
        final Path testRoot = adaptPath("src/test/resources/issue1675");
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(testRoot);
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(reflectionTypeSolver, javaParserTypeSolver);
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
        StaticJavaParser.setConfiguration(configuration);

        String src = "public class X extends Y {\n" +
                "   private Foo foo;\n" +
                "}";

        CompilationUnit cu = StaticJavaParser.parse(src);

        List<FieldDeclaration> fds = cu.findAll(FieldDeclaration.class);
        fds.forEach(fd-> {
            System.out.println(fd.resolve().getType().toString());
        });

    }
    }

result

ReferenceType{Z.Foo, typeParametersMap=TypeParametersMap{nameToValue={}}}
