### ISSUE TITLE
Wrong indentation for lambdas with BlockStmt as the body

### ISSUE THREAD

**Issue by markzyu** [javaparser/javaparser#168]
I utilize this library to generate source files according to other java files.

Here is part of my generator related to the generation of lambda expressions:

``` Java
    LambdaExpr lambda = new LambdaExpr();
    lambda.setParametersEnclosed(true);
    lambda.setParameters(Arrays.asList(singleParam));
    lambda.setBody(lambdaBody);
    ASTHelper.addArgument(netThenCall, lambda);
    ASTHelper.addStmt(body, netThenCall);
```

Here is part of the generated java file (variables' and functions' names are obfuscated):

``` Java
    public XXX connect(boolean b, YYY argsProvider) {
        if (argsProvider != null)
            Func1(b, argsProvider);
        Func2((_XXX_type args)->{
    var1.connect(args.var2);
    return null;
});
        return this;
    }
```

**Comment by ptitjes** [comment]
The problem comes from the `body.toString()` call here: http://git.io/vOG3T

You can easily fix this by replacing lines 1568 to 1573 by:

```
if (body instanceof ExpressionStmt) {
    // Print the expression directly
    ((ExpressionStmt) body).getExpression().accept(this, arg);
} else {
    body.accept(this, arg);
}
```

And voilà!

**Comment by markzyu** [comment]
Thanks! I will fix this issue locally, but it would be much appreciated if the issue can be fixed in a later release.

**Comment by ftomassetti** [comment]
@C4Phone let us know if we can help with your new PR

**Comment by ptitjes** [comment]
@ftomassetti It was #170, and @matozoid already merged it.

**Comment by matozoid** [comment]
Close this then?

**Comment by ptitjes** [comment]
Closing you can :p

**Comment by markzyu** [comment]
I am okay with closing this issue.
