### ISSUE TITLE
Removing gh-pages

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1697]
I think we do not need it anymore. Before deleting it I wanted to be sure :)

**Comment by matozoid** [comment]
I think you can check out the wiki pages from another URL, right?

Yes, https://github.com/javaparser/javaparser.wiki.git

**Comment by ftomassetti** [comment]
The link does not work for me (error 404). I think the gh-pages are different from the wiki. They could be used for the content of the website but I think we use a different hosting for that

**Comment by matozoid** [comment]
Well, I haven't used them in years, if ever, so away they go.

The link comes from the wiki - it's in the bottom right. I guess it only works for cloning?

**Comment by ftomassetti** [comment]
Removed: it was not modified in 2 years

**Comment by matozoid** [comment]
Nice, only master is left.
