### ISSUE TITLE
resolving MethodCallExpr in anonymous classes

### ISSUE THREAD

**Issue by Yonka** [javaparser/javaparser#1703]
Hi!
I have an issue while resolving type of MethodCallExpr scope variable in anonymous class.
Example:
```java
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.TransactionCallbackWithoutResult;

public class AnonymousClassExample {
    private static final Integer f = 1;
    private void sentNotificationResultEventInTransaction() {
        new TransactionCallbackWithoutResult() {
            @Override
            protected void doInTransactionWithoutResult(TransactionStatus status) {
                f.toString();
            }
        };
    }
}
```
And when I try to resolve type of `f` while calling `m.getScope().get().asNameExpr().resolve()` from `public void visit(MethodCallExpr m, Void a)`, I get: 
java.lang.UnsupportedOperationException: CorrespondingDeclaration not available for unsolved symbol.

And one more interesting thing. SymbolSolver resolved type of `f` when I placed this example code to the same package with my visitor implementation.
What am I doing wrong?

**Comment by matozoid** [comment]
@ftomassetti - we missed this question :-(

**Comment by matozoid** [comment]
@Yonka - thanks for reporting this one :-)
