### ISSUE TITLE
resolving MethodCallExpr in lambda

### ISSUE THREAD

**Issue by Yonka** [javaparser/javaparser#1704]
and one more issue.
In this example:
```
        Either<Void, Integer> t = Either.right(1);
        t.flatMap(this::getAccountDetail)
                .acceptEither(
                        null,
                        account -> new TransactionTemplate(transactionManager)
                                .execute(status -> {
                                    message.put(account);
                                    return null;
                                }));
```
 I get `java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: message.put(account), Parameter: account`.
But if I replace outer lambda with anonymous class:
```
        Either<Void, Integer> t = Either.right(1);
        t.flatMap(this::getAccountDetail)
                .acceptEither(
                        null,
                        new Consumer<String>() {
                            @Override
                            public void accept(String account) {
                                new TransactionTemplate(transactionManager)
                                        .execute(status -> {
                                            message.put(account);
                                            return null;
                                        });
                            }
                        });
```
MethodCallExpr for `message.put(account)` resolves successfully.

Is there any way to resolve this method call in first case?

**Comment by Symbolk** [comment]
Same error here, but for chained method call as arguments.

```java
java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: assertEquals("import com.github.javaparser.builders.NodeWithAnnotationsBuildersTest$hey;", cu.getImport(0).toString().trim()), Parameter: cu.getImport(0).toString().trim()
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:225)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:240)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
	at edu.pku.intellimerge.core.SemanticGraphBuilder.build(SemanticGraphBuilder.java:568)
	at edu.pku.intellimerge.core.SemanticGraphBuilder.buildGraphForOneSide(SemanticGraphBuilder.java:82)
	at edu.pku.intellimerge.client.APIClient.handleOneMergeScenario(APIClient.java:89)
	at edu.pku.intellimerge.client.APIClient.main(APIClient.java:58)
Caused by: java.lang.RuntimeException: Method 'getImport' cannot be resolved in context cu.getImport(0) (line: 58) MethodCallExprContext{wrapped=cu.getImport(0)}. Parameter types: [PrimitiveTypeUsage{name='int'}]
...
```
#1945

**Comment by matozoid** [comment]
Thanks! Can either of you make a failing test case?

**Comment by jlerbsc** [comment]
Is there a way to get a test case on this issue or should we consider that is solved?

**Comment by jlerbsc** [comment]
Not sure that this unit test can reproduce this issue ( related to @Symbolk comment)

    @Test
    void test1704() throws IOException {
        // Source code
        String sourceCode = 
                "import static java.util.Objects.requireNonNull;" +
                "class A {\n" +
                "  void m() {\n" +
                "    requireNonNull(new StringBuilder().toString().trim());"+
                "  }\n" +
                "}";
        TypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver());

        // Setup symbol solver
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(typeSolver));
        // Setup parser
        StaticJavaParser.setConfiguration(configuration);
        CompilationUnit cu = StaticJavaParser.parse(sourceCode);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        String rmce = mce.calculateResolvedType().describe();
        System.out.println(
                "MethodCallExpr " + mce.toString() + " resolved type " + rmce);

    }

but the result is correct


    MethodCallExpr requireNonNull(new StringBuilder().toString().trim()) resolved type java.lang.String

**Comment by matozoid** [comment]
I think some work has been done on this a year or two ago, so I guess it is fixed?

**Comment by jlerbsc** [comment]
Ok thank you for your comment. So I'm closing this issue and we'll open a new one if this case reappears.
