### ISSUE TITLE
Getting field declaration from field access expression 

### ISSUE THREAD

**Issue by Yonka** [javaparser/javaparser#1705]
I want to get ResolvedFieldDeclaration from FieldAccessExpr. FieldAccessExpr and  ResolvedFieldDeclaration are in different CompilationUnits.
```java
FieldAccessExpr fieldAccess = pair.getValue().asFieldAccessExpr();
JavaParserFieldDeclaration value = (JavaParserFieldDeclaration)fieldAccess.resolve().asField();
FieldDeclaration field = value.getWrappedNode();
ResolvedFieldDeclaration resolvedField = field.resolve();     //here is the problem
```
In the last line "java.lang.IllegalStateException: Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration" is thrown.

I've tried to find the problem. The exception occures in getSymbolResolver method (Node.java) because `cu.getData(SYMBOL_RESOLVER_KEY) == null`. Maybe symbolResolver should be taken from ParserConfiguration in this part of code?

**Comment by matozoid** [comment]
Hi! Here's a minimal sample of how to set everything up for symbol solving: https://github.com/javaparser/javasymbolsolver-maven-sample/blob/master/src/main/java/com/yourorganization/maven_sample/MyAnalysis.java

and it is recommended to read the book: https://leanpub.com/javaparservisited

**Comment by Yonka** [comment]
Hi!
I've configured JavaParser by setting up CombinedTypeSolver (with all source and jars path, and ReflectionTypeSolver) before asking ;) And all CompilationUnits that was parsed via `JavaParser.parse(compilationUnit)` has not null `getData(SYMBOL_RESOLVER_KEY)`.
But the CompilationUnit that we get while `ResolvedFieldDeclaration resolvedField = field.resolve();` does not have this "data".
I've added this "data" manually:
```
FieldAccessExpr fieldAccess = pair.getValue().asFieldAccessExpr();
JavaParserFieldDeclaration value = (JavaParserFieldDeclaration)fieldAccess
      .resolve().asField();
FieldDeclaration field = value.getWrappedNode();
CompilationUnit unit = field.findCompilationUnit().get();
unit.setData(Node.SYMBOL_RESOLVER_KEY, JavaParser.getStaticConfiguration()
        .getSymbolResolver().get());
ResolvedFieldDeclaration resolvedField = field.resolve();
```
and it fixed the problem. But I don't think that this is a right solution.

**Comment by matozoid** [comment]
Is the second `CompilationUnit` coming from one of the type solvers? Check the constructor of the `JavaParserTypeSolver`, it can take a `ParserConfiguration`, which is the one where you can put the solver.

It's a bit annoying to configure all of this, so @ftomassetti - is this how it is supposed to work?

Here's also a quick way to configure everything (if it fits your project structure): http://javaparser.org/setting-up-for-analysing-a-whole-project/

**Comment by Yonka** [comment]
The second `CompilationUnit` we get in the last line while field.resolve() call:
`field.resolve()` ->
```
public ResolvedFieldDeclaration resolve() {
    return getSymbolResolver().resolveDeclaration(this, ResolvedFieldDeclaration.class);
}
```
->
```
    protected SymbolResolver getSymbolResolver() {
        return findCompilationUnit().map(cu -> {   //HERE we get this CompilationUnit
            SymbolResolver symbolResolver = cu.getData(SYMBOL_RESOLVER_KEY);
            if (symbolResolver == null) { //and HERE the SymbolResolver is null
                throw new IllegalStateException("Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration");
            }
...
    }
```

> it can take a ParserConfiguration, which is the one where you can put the solver.

I've assigned all my solvers combined in CombinedTypeSolver to static configuration:
```
JavaSymbolSolver javaSymbolSolver = new JavaSymbolSolver(combinedTS);
JavaParser.getStaticConfiguration().setSymbolResolver(javaSymbolSolver);

```
Isn't it enough?

**Comment by matozoid** [comment]
Have you tried?

**Comment by Yonka** [comment]
Yes, I tried and it works!
I've added configuration (`ParserConfiguration configuration = JavaParser.getStaticConfiguration();`) to every JavaParserTypeSolver constructor.
Thank you for your help! And thanks for JavaParser, it's awesome!

**Comment by matozoid** [comment]
Cool, have fun :-)
