### ISSUE TITLE
Spaces in the file path cause a failure in the VisitorTest

### ISSUE THREAD

**Issue by maxstreichert** [javaparser/javaparser#171]
The scenarion "Scenario: A class with many different Java concepts is visited by a VoidVisitorAdaptor" in the VisitorTest throws FileNotFoundException because of the spaces in MY file path.
In SharedSteps.java the command url.getPath() provides a string with %20 instead of spaces. That leads to a failure In the JavaParser.java the FileInputStream constructer, which does not support %20

Possible solution is to change url.getPath() -> url.toURI()

**Comment by maxstreichert** [comment]
Fixed in the Pull Request #172

**Comment by ftomassetti** [comment]
The PR has been accepted, thanks!

Closing.
