### ISSUE TITLE
Check isAnnotationPresent with Full Qualified Class name

### ISSUE THREAD

**Issue by jGauravGupta** [javaparser/javaparser#1713]
`boolean isAnnotationPresent(Class<? extends Annotation> annotationClass)` checks for simple class name instead of full qualified class name , so with current solution, this api could return wrong result.

Is it possible to check annotation presence with FQN ?

Reference Class : https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/nodeTypes/NodeWithAnnotations.java#L204

**Comment by matozoid** [comment]
Yes, you need to resolve the annotation type with the symbol solver for that. Would you like some pointers?

**Comment by jGauravGupta** [comment]
Yes, please help, not getting much help from docs.

**Comment by matozoid** [comment]
Okay, the book has a chapter on using the symbol solver: https://leanpub.com/javaparservisited
Here's a sample project: https://github.com/javaparser/javasymbolsolver-maven-sample
and maybe this is of use: http://javaparser.org/setting-up-for-analysing-a-whole-project/

**Comment by jGauravGupta** [comment]
Thanks @matozoid for the above links, I followed **javasymbolsolver-maven-sample** (and javaparser-symbol-solver-core:3.6.14 dependency) but getting the following exception on calling  `ClassOrInterfaceDeclaration.getAnnotationByClass(XYZAnnot.class).get().calculateResolvedType()` :

````
java.lang.UnsupportedOperationException: com.github.javaparser.ast.expr.MarkerAnnotationExpr
	at com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:15)
	at com.github.javaparser.ast.expr.MarkerAnnotationExpr.accept(MarkerAnnotationExpr.java:69)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:416)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:313)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:295)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:229)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:561)
````

Looks similar to #1621

**Comment by matozoid** [comment]
@ftomassetti @malteskoruppa ?

**Comment by ftomassetti** [comment]
I think we need to override a method in TypeExtractor. Do for MarkerAnnotationExpr something similar to this:

```
    @Override
    public ResolvedType visit(ClassExpr node, Boolean solveLambdas) {
        // This implementation does not regard the actual type argument of the ClassExpr.
        com.github.javaparser.ast.type.Type astType = node.getType();
        ResolvedType jssType = facade.convertToUsage(astType, node.getType());
        return new ReferenceTypeImpl(new ReflectionClassDeclaration(Class.class, typeSolver), ImmutableList.of(jssType), typeSolver);
    }
```

**Comment by matozoid** [comment]
@ftomassetti has this been implemented by now?

**Comment by matozoid** [comment]
@ftomassetti has this been implemented by now? :-)

**Comment by matozoid** [comment]
Someone needs to check if this has been fixed in the meantime.
