### ISSUE TITLE
Duplicate methods: findParent(Class) and getAncestorOfType(Class)

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1727]
It seems to me that there are two methods in the JavaParser API which do exactly the same thing:

* `Node#findParent(Class)`
* `HasParentNode#getAncestorOfType(Class)`

Looking at the implementation of these two methods also reveals that they do exactly the same thing.

In the spirit of a minimal and well-defined API with no duplicate methods, would it make sense to remove either of these methods?

I think having the method in `HasParentNode` (rather than `Node`) makes sense, since then, both `Node` and `NodeList` have it. I have no strong feelings about the method's name. :-)

**Comment by matozoid** [comment]
Ah, getAncestorOfType needs a deprecation and a Javadoc saying to use findParent. The whole "find..." family is supposed to be the new, clean way of functionally accessing the AST.
