### ISSUE TITLE
Doubt about ForStmt initialization

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1738]
I am not sure if we discussed this already but I could not find any issue on that.

Consider a For Stmt with 2 variables:

```
ForStmt forStmt = parse("for (int i=0, j=1;i<10;i++) { body(); }",
                ParseStart.STATEMENT).asForStmt();
```

Now, in this case the forStmt has an initialization NodeList of one element (one VariableDeclarationExpr):

![screen shot 2018-08-12 at 09 17 25](https://user-images.githubusercontent.com/439078/43999625-9f596f90-9e10-11e8-8f87-582e03ba1938.png)

So I wonder: when the initialization list can contain more than one element? Should it be not a list?

**Comment by matozoid** [comment]
It can be a list of statements as well: https://docs.oracle.com/javase/specs/jls/se10/html/jls-14.html#jls-BasicForStatement
```java
        int a, b;
        for (a = 5, b = a * 10; a < 11; a++) {
            
        }
```

... the Javadoc is incomplete.

**Comment by matozoid** [comment]
Oh, the Javadoc is fine: "initialization is a list of expressions. These can be any kind of expression as can be seen in example 3, but the common ones are a single VariableDeclarationExpr (which declares multiple variables) in example 1, or a list of AssignExpr's in example 2."
