### ISSUE TITLE
Doubts about TryStmt

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1739]
1. Should it be called "TryWithResourcesStmt"? Is this used both for the common TryStmt and the TryWithResourcesStmt?
2. The resources are defined as Expressions but I think they can only be VariableDeclarationExpr. Should be make it more restrictive?

**Comment by matozoid** [comment]
Honestly, that's all explained in the very thorough Javadoc for that class.

**Comment by ftomassetti** [comment]
My bad, sorry about that.
