### ISSUE TITLE
visit(MethodDeclaration...) causes visit(BlockStmt...) from being called.

### ISSUE THREAD

**Issue by GeVanCo** [javaparser/javaparser#1742]
I want to remove the following stuff from my original Java sources:

- Remove package
- Remove all imports
- Remove all comments
- Remove all private stuff (fields, methods, private inner classes,...)
- Remove the complete body from all methods

Therefore, I've created a "generic" `RemoveVisitor` like so:

```
    private static class RemoveVisitor extends ModifierVisitor<Void> {
        @Override
        public Node visit(PackageDeclaration declarator, Void args) {
            System.out.println("\n***PackageDeclaration: \n" + declarator.getNameAsString());
            return null;
        }
        
        @Override
        public Node visit(ImportDeclaration declarator, Void args) {
            System.out.println("\n***ImportDeclaration: \n" + declarator.getNameAsString());
            return null;
        }
        
        @Override
        public Node visit(BlockStmt blockStmt, Void args) {
            System.out.println("\n***BlockStmt: \n" + blockStmt.toString());
            return null;
        }
          
        @Override
        public Node visit(MethodDeclaration m, Void args) {
            System.out.println("\n***MethodDeclaration: \n" + m.toString());
            System.out.println("***Modifier: " + m.getModifiers());
            if (m.isPrivate()) {
                return null;
            } else {
                return m;
            }
        }
          
        @Override
        public Node visit(FieldDeclaration m, Void args) {
            System.out.println("\n***FieldDeclaration: \n" + m.toString());
            System.out.println("***Modifier: " + m.getModifiers());
            if (m.isPrivate()) {
                return null;
            } else {
                return m;
            }
        }
    }
```
Most of the things work fine:
- I can remove the package line
- I can remove all import lines
- Comments are gone (I'm using `JavaParser.getStaticConfiguration().setAttributeComments(false);` to kick out all comments in the first place...)
- Lines with private field declarators are gone

But...  If I apply the code above as-is, then I don't get any `visitor(BlockStmt...` callback called.  As a result, I can't delete the block statements from all my methods, so I can't empty the body.  In that situation, the result is the following:

```
public class ReversePolishNotation {

    public static int ONE_BILLION = 1000000000;

    public double memoryRecall() {
        return memory;
    }

    public void memoryClear() {
        memory = 0;
    }

    public void memoryStore(double value) {
        memory = value;
    }
}
```
As you can see, no package, import, comment, private stuff anymore, but the body content is not gone...

If I comment out the `visit(MethodDeclaration...` callback method completely, then I get my block statement callback for all method bodies and I can return `null` as a node to completely remove the body.
But in that case, I'm not able anymore to see if the method has private access or not since I don't have the `visit(MethodDeclaration...` callback anymore.  So, in that case the resulting output is (I've taken the `ReversePolishNotation.java` file as input):

```
public class ReversePolishNotation {

    public static int ONE_BILLION = 1000000000;

    private Double calc(String input);

    public double memoryRecall();

    public void memoryClear();

    public void memoryStore(double value);
}
```
As you can see, the body of all methods is gone but there's still one private method present, which I don't want.

How can I solve this issue?

Next to this, I also would like to add `{}` to the end of all methods so that it looks like so:

`public void memoryClear(){};` in stead of `public void memoryClear();`

How can I add `{}` to the lines at the given position?

Best,

**Comment by matozoid** [comment]
Don't forget to call super.visit(m, args)! The parent visitor has the traversal logic.

**Comment by GeVanCo** [comment]
Arggg..... :-(

Is it good practise to do this with every `visit(...`?

**Comment by matozoid** [comment]
It's up to you: if there is some reason why you do not want to visit the children of the node you can skip it. And some visitors don't have any traversal logic, so no use calling super there.

**Comment by GeVanCo** [comment]
Ok, thanks.  I'll close this issue and open another one for the second part of my question...
