### ISSUE TITLE
ConditionalExpr resolves to wrong type

### ISSUE THREAD

**Issue by kgeilmann** [javaparser/javaparser#1743]
The type solver always resolves conditional expressions to the type of the then part, which makes e.g. ```s == null ? null  : s.toString()``` surprisingly being resolved to the null type instead of String.

**Comment by ftomassetti** [comment]
The current implementation is wrong and the rules for implementing it correctly are far from trivial. There is a pretty significant part of the JLS discussing about this: https://docs.oracle.com/javase/specs/jls/se10/html/jls-15.html#jls-15.25

**Comment by jlerbsc** [comment]
Reference conditional expression refer to #2978

**Comment by jlerbsc** [comment]
This issue is resolved but we have to manage case of conditional reference expression and poly expression.

**Comment by jlerbsc** [comment]
Poly expression is resolved with PR #2994

**Comment by jlerbsc** [comment]
TODO manage lub function (in TypeHelper.leastUpperBound) and update TypeExtractor.visit(ConditionalExpr node, Boolean solveLambdas) to manage reference conditional expression.

**Comment by jlerbsc** [comment]
Resolved in PR https://github.com/javaparser/javaparser/pull/3880
