### ISSUE TITLE
Inserting "{}"

### ISSUE THREAD

**Issue by GeVanCo** [javaparser/javaparser#1744]
I want to change this:
```
    private Double calc(String input) {
        String[] tokens = input.split(" ");
        Stack<Double> numbers = new Stack<>();
        Stream.of(tokens).forEach(t -> {
            double a;
            double b;
            switch(t) {
                case "+":
                    b = numbers.pop();
                    a = numbers.pop();
                    numbers.push(a + b);
                    break;
                case "/":
               .
               .
               .
    }
```
into this:
```
    public Double calc(String input){};
```
Or this:
```
    public int memCall(int a, int b) {
        return a ^ b;
    }
```
into this:
```
    public int memCall(int a, int b) {};`
```
In other words: kick out the **_complete_** body of a public method.

I'm using a `visit(BlockStmt...` to remove the body content like so:
```
        @Override
        public Node visit(BlockStmt m, Void args) {
            super.visit(m, args);
            System.out.println("\n***BlockStmt: \n" + m.toString());
            return null;
        }
```
That works find, but in the end, I get this:
```
    public Double calc(String input);
````
and this:
````
    public int memCall(int a, int b);
````
So, apparently JavaParser has added the `;` to the end of the string.

What I finally want is an additional `{}` added just before the `;`.  Of course, a naive implementation would be to do the following:
```
    cu.toString().replace(";", "{};");
```
but that would also add the curly braces to public fields which I also want to be part of the end result.  So, this:
```
    public static int ONE_BILLION = 1000000000;
```
would then also become this:
```
    public static int ONE_BILLION = 1000000000{}; 
```
and that's of course stupid...

Another approach could be to have the following code in the `visit(MethodDeclaration...` method:
```
.
.
    m.accept(new RemoveBlockStmt(), null); // Completely kick out the existing body by calling visit() in another private class...
    m.setBody(new BlockStmt()); // I just need the {}, so creating a new BlockStmt() object should be enough...
.
.
```
In the above approach, I've created a new private class `RemoveBlockStmt()` that has the following content:
````
    private static class RemoveBlockStmt extends ModifierVisitor<Void> {
        @Override
        public Node visit(BlockStmt m, Void args) {
            super.visit(m, args);
            System.out.println("\n***BlockStmt: \n" + m.toString());
            return null;
        }
    }
````
That one is called from another private class, also extending the `ModifierVisitor<Void>` class.
But the outcome this time is like so:
```
    public Double calc(String input) {
    }
```
So, the curly braces are added but not on the same line.  Next to this, the `;` is gone too.  Almost there, but not completely...

Therefore, my question: is there a way to do all the following in the body of the `visit(MethodDeclaration...` method:

1. Remove the complete body of the method (I think I've managed this with my latest approach...)
2. Add `{}` at the end of the line (after the possibly empty method parameter list), but before the `;`
3. Add `;` at the end of the line (after the `{}`)

This is, so far, my current implementation of that method:
```
        @Override
        public Node visit(MethodDeclaration m, Void args) {
            super.visit(m, args);
            System.out.println("\n***MethodDeclaration: \n" + m.toString());
            System.out.println("***Modifier: " + m.getModifiers());

            if (m.isPrivate()) {
                return null;
            } else {
                // Print situation before body removal
                System.out.println("m = " + m.toString());
                m.accept(new RemoveBlockStmt(), null);
                // Print situation after body removal
                System.out.println("m = " + m.toString());
                BlockStmt body = new BlockStmt();
                m.setBody(body);
                // Print situation after body modification
                System.out.println("m = " + m.toString());
                return m;
            }
        }
```
But I'm still missing the final touch to get the ultimate line exactly as I want.

Best,

**Comment by matozoid** [comment]
Does this work? (I just typed this by hand...)
```java
        @Override
        public Node visit(BlockStmt m, Void args) {
            super.visit(m, args);
            System.out.println("\n***BlockStmt: \n" + m.toString());
            return new BlockStmt();
        }
```

**Comment by GeVanCo** [comment]
There must be some kind of telepathy going on over here... :-)
About 15 minutes ago, I did that very same modification...

But in the end, the result is the same:  The `{` and `}` are put on separate lines and the `;` is gone.

I've temporarily solved it by applying a regex on the resulting complation unit output like so as a test:
```
        String endResult = cu.toString();
        Pattern pattern = Pattern.compile("\\{\\n*\\s*\\}.*");
        Matcher matcher = pattern.matcher(endResult);
        String totalResult = matcher.replaceAll("{};");
        try {
            Files.write(new File("src/main/resources/Modified1.java").toPath(), totalResult.getBytes(), StandardOpenOption.CREATE);
        } catch (IOException ex) {
            Logger.getLogger(Inspect.class.getName()).log(Level.SEVERE, null, ex);
        }
```
The result of this is (complete processed testfile output):
```
public class ReversePolishNotation {

    public static int ONE_BILLION = 1000000000;

    public Double calc(String input) {};

    public int memCall(int a, int b) {};

    public double memoryRecall() {};

    public void memoryClear() {};

    public void memoryStore(double value) {};

    public class MyPublicInnerClass {

        MyInnerClass() {};

        public String getText() {};

        public int getHowMany() {};

        public void setHowMany(int howMany) {};

        public void setText(String inText) {};
    }
}
```
So, looks OK but in the end I want to get rid of the regex and hope I can tweak it in the JavaParser part.  That would be the nicest solution.

I've already looked at `addStmt` but it's not really a statement I want to add, it's just the curly braces and a semicolon.

Hope you have more ideas on how to tackle this?

Best

**Comment by matozoid** [comment]
That semicolon is something I haven't been able to find in the Java specification: it doesn't do anything, but is allowed anyway. JavaParser throws them away while parsing because only meaningful stuff goes in the AST.

My suggestion is to not have those semicolons :-)

**Comment by GeVanCo** [comment]
Yeah, you're right: it's not mandatory.  But that's how we defined the "look'n'feel" of the "public" view for the processed Java files...

But it would make the picture complete if I could do all those things from one and the same file processing unit and avoid to have a post-processing alike thing with regex'es...

**Comment by matozoid** [comment]
It's not just not mandatory: it's a meaningless lost semicolon. Someone made a mistake while defining that view.

If you're using toString or the pretty printer, you can extend it (see PrettyPrinter and PrettyPrinterVisitor) and make it add those semicolons. You might not want to add them to each BlockStmt, so you could mark those that should have it by adding metadata with setData/getData.

**Comment by GeVanCo** [comment]
Maybe we should indeed reconsider not to have the semicolon.  It was just to visually delineate the method, including the parameters - if present - as a whole.  But you're 500% correct: they're syntactically allowed but totally useless.
Since I anyhow have to use regex'es to do some "aftercleaning" I've also taken the opportunity to kick out all the empty lines in between two methods/variables/inner public classes,...  Which is pretty neat (although I say it myself... :-)).

The final outcome looks like this now (took another Java source file as input with multiple protected inner classes):
```
public abstract class CardTabView_Common extends BaseView implements Test {
    protected MetricSystemSettings mMetricsProv;
    protected CardTabView_Common() {};
    protected CardTabView_Common(Context context) {};
    protected final void startUiUpdate() {};
    protected final void stopUiUpdate() {};
    protected abstract class UiAction implements Delayed {
        public final String name;
        protected UiAction(String name) {};
        protected abstract void setValue();
        public synchronized void scheduleUiUpdate() {};
        public synchronized long getDelay(TimeUnit unit) {};
        public synchronized int compareTo(Delayed o) {};
    }
    protected class InputFieldListener implements TextWatcher, TextView.OnEditorActionListener {
        InputFieldListener(vehiclefunctions.CardTabView_Common.UiAction uiact, InputField inputField) {};
        protected void setRefBean(CookedCCSBean bean) {};
        public void beforeTextChanged(CharSequence s, int start, int count, int after) {};
        public void onTextChanged(CharSequence s, int start, int before, int count) {};
        public void afterTextChanged(Editable s) {};
        public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {};
    }
    protected class BarChangedListener implements AbstractStepperView.OnAdjustableBarChangedListener {
        BarChangedListener(vehiclefunctions.CardTabView_Common.UiAction uiact) {};
        protected void setRefBean(CookedCCSBean bean) {};
        public void onStopTrackingTouch(AbstractStepperView bar) {};
        public void onAdjustableBarChanged(AbstractStepperView bar, double newValue, boolean fromUser) {};
        public void onAdjustableBarMaxValueReached(AbstractStepperView bar) {};
        public void onAdjustableBarMinValueReached(AbstractStepperView bar) {};
        public void onAdjustableBarDisabledTouch(AbstractStepperView bar) {};
    }
    protected class ItemSelectedListener implements PickListEditable.OnItemSelectedListener {
        ItemSelectedListener(vehiclefunctions.CardTabView_Common.UiAction uiact) {};
        protected void setRefBean(CookedCCSBean bean) {};
        public void onItemSelected(AdapterView<?> parent, View view, int position, long id, boolean fromUser) {};
        public void onNothingSelected(AdapterView<?> parent) {};
    }
    protected class CheckedChangeListener implements OnOffSwitch.OnCheckedChangeListener {
        CheckedChangeListener(cvehiclefunctions.CardTabView_Common.UiAction uiact) {};
        protected void setRefBean(CookedCCSBean bean) {};
        public void onCheckedChanged(OnOffSwitch swc, boolean checked) {};
    }
    protected class RadioCheckedChangeListener implements RadioGroup.OnCheckedChangeListener {
        RadioCheckedChangeListener(vehiclefunctions.CardTabView_Common.UiAction uiact) {};
        protected void setRefBean(CookedCCSBean bean) {};
        public void onCheckedChanged(RadioGroup grp, int checkid) {};
    }
}
```
And that's great!  Maybe I might have a look to that PrettyPrinter stuff to add empty lines between different classes and/or variable/method boundaries to let it look less "busy".

But I'm very satisfied with the achieved result so far!

**Thanks to all JP contributors/maintainers for providing the community such an elegant tool!**  

I might only know 10% of its capabilities for the moment but even that brought me quite far in what I wanted to achieve.  Especially since I started myself to write a straightforward "parser-alike" thingy for doing something similar using regex'es.  I was reading line-by-line and tried to analyse it to the best of my knowledge.
But there were always corner cases which I couldn't capture (or make lots of exceptions in the code to catch yet another special use case).  A (JP) parser jumps to the rescue in such cases.

Should there be people interested in what I did, I'm very willing to share my basic code to come to the above result.

Best.

**Comment by matozoid** [comment]
Thanks! This was a good use case for JP indeed :-) Good luck with the rest!

If you have a blog or so, why not write a bit about your experience?

I am a little curious why you would want this result, still.

Oh, and I just realized you could also have gotten this result with a modified pretty printer visitor :-) No need to remove anything from the AST, just don't print it.

**Comment by GeVanCo** [comment]
> I am a little curious why you would want this result, still.

The reason behind this is the following: we want to be able to **very quickly** see the differences between two SW releases from an API point of view, to know if and what externally accessible classes/methods/... have changed.  We're not interested in the internal "jibberjabber" (if you know _The Big Bang Theory_, you will for sure know what I mean... :-)) but only in what is accessible from the outside.

If we run two different SW releases through one and the same tool to generate the public visible items then we can very easily see if there were changes between the two releases from an API point of view.

So, here's what we do: for a certain SW release we take a Java file, run it through the parser and save the modified file (with only an overview of public accessible stuff in it) with the same name and directory structure but to another place (obviously, we don't want to overwrite the original file...).  We do this for all the Java files in that SW release.
We take another SW release and do exactly the same.  Then, we compare the two generated directories with for instance WinMerge and we see almost immediately what are the differences...

That's, in short, the story behind this.

Best.

PS: Danny, are you Dutch?  Belgian?  Your last name surely looks like it's one of the two...

**Comment by matozoid** [comment]
Nederlander hier :-) Maar het project is erg internationaal!

It's interesting that you half-implemented this project idea here: #776 - with a few days more work you could turn it into a general project!

**Comment by GeVanCo** [comment]
If I can contribute, I'm willing to help.  But then I would need some hooks to know exactly what has to be done.  If someone has a "script" and it doesn't deviate too much from what I realised so far, just let me know and I'll see what I can do in my spare time.

For the stuff I'm currently busy with, I'm running it still from the command line (with some small interaction with the user, like "specify directory of the source files" and "specify destination directory" + some checks on existence of the directories and - if needed - creation of it and the like...).

But I would like to move it to a JavaFX-based GUI-alike small app.  We've stepped into the 21st century, right?  No need for DOS3.1 anymore, I guess... ;-)

Best,

**Comment by matozoid** [comment]
I think for JavaParser it would be useful to have the API file stored in Git, and to have a unit test that collects the API and compares it to the stored file. It will fail when the API breaks, and then we can make a note in the release notes or roll it back :-)
