### ISSUE TITLE
ClassloaderTypeSolver support 

### ISSUE THREAD

**Issue by jGauravGupta** [javaparser/javaparser#1745]
JavaParser API provides the support for `ReflectionTypeSolver` but missing custom `Classloader` support.

So would be great, if `ReflectionTypeSolver` can be configured with custom classloader otherwise default to  `ReflectionTypeSolver.class.getClassLoader()`

**Comment by ftomassetti** [comment]
I just created a PR for this idea. I created the ClassLoaderTypeSolver which can take any classloader. The ReflectionTypeSolver has been refactored to be a subclass of the new ClassLoaderTypeSolver.

**Comment by ftomassetti** [comment]
Implemented in #1746
