### ISSUE TITLE
Getting the JavaToken of the other end of the parentheses

### ISSUE THREAD

**Issue by obcardinal** [javaparser/javaparser#1752]
Hi, I have `JavaToken's` from all source code, which I can to determine brackets.
But can I find the other end of the brackets with `JavaParser` having `JavaToken`?
Or only with `Stack`?

**Comment by matozoid** [comment]
If you want to stay at the token level you would need to use a stack, yes.

If you can use the AST, you can find types of nodes that have { and }, and ask for their token range. That range should include the { and } token, although they might not be exactly the first and last.

**Comment by obcardinal** [comment]
I implemented using `Stack`.

I noticed a good feature of the parser:
If at the end, after `}` there are several spaces, he does not see them. We have to check whether the matching of the caret location and the token was noticed. If not, then take the last token.

Unfortunately, it seems that the parser will not work with tokens in any way, if there is an error in the code. But okay, this problem is not so close that there was a need to look for workarounds. Maybe it will be possible to cheat somehow and to prevent an error.

Thanks, @matozoid

**Comment by matozoid** [comment]
Oh wait, a few questions about that:
- do you mean that CompilationUnit's TokenRange does not go all the way to the end of the file?
- you can make the parser less sensitive by setting its language level to "RAW", but yes, the source code will need to be reasonable or it will fail. Some attempts have been done to implement error recovery, but that's still very simple.

**Comment by obcardinal** [comment]
- Yes, after last `}`, he did not see spaces.
- Thanks, I'll try it later.

**Comment by matozoid** [comment]
Thanks! I'll open a new issue then :-)

Good luck!

**Comment by obcardinal** [comment]
@matozoid I think this is done to reduce the number of operations.

Thanks, and good luck to you :)
