### ISSUE TITLE
Update the current version in the README

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#176]
It would be great to have some sort of macro for that.

**Comment by SmiddyPence** [comment]
This is the option I can find for this:

https://img.shields.io/maven-central/v/com.github.javaparser/javaparser-core.svg

Any other offers?

Users would have to work out the dependency for their own framework, although we only show maven anyway.

**Comment by ptitjes** [comment]
Nice badge!

**Comment by SmiddyPence** [comment]
Unfortunately it doesn't appear that shields.io is entirely stable.

**Comment by SmiddyPence** [comment]
This may be better: 

https://maven-badges.herokuapp.com/maven-central/com.github.javaparser/javaparser-core/badge.svg

**Comment by ftomassetti** [comment]
Looks good to me

**Comment by ftomassetti** [comment]
This has been solved by @SmiddyPence , closing
