### ISSUE TITLE
Access modifiers are lost when printing to Json or Dot?

### ISSUE THREAD

**Issue by andrewhabib** [javaparser/javaparser#1772]

**Comment by matozoid** [comment]
Confirmed.

**Comment by andrewhabib** [comment]
Thanks for confirming. Any heads up on a quick fix?

**Comment by matozoid** [comment]
I don't know what you're using it for, but you could try the javaparser-core-serialization jar and its `JavaParserJsonSerializer`.

**Comment by andrewhabib** [comment]
Hi again, thanks for your prompt response and action. 

I have tried using the (de)serializer as per your recommendation. So far, serialization works fine, but deserialization has many issues.

Will open separate issue.
