### ISSUE TITLE
Deserialization fails with various errors.

### ISSUE THREAD

**Issue by andrewhabib** [javaparser/javaparser#1776]
Hi,

Thanks again for the great javaparser. 

I am trying to use the (de)serialization of ASTs. So far, serialziation works fine, but deserialization is buggy.

My testing case is simple:

1- parse a .java file (parsing is successful)
2- without applying any modification to the AST, serialize it (work fine)
3- deserializing the step 2 produces various errors:

Don't know how to convert: class com.github.javaparser.ast.expr.AssignExpr$Operator

Don't know how to convert: class com.github.javaparser.ast.type.PrimitiveType$Primitive

I can provide source code but I think these errors are very general and apply to simple cases like primitives, and assig expressions.

**Comment by matozoid** [comment]
Ah, let's fix that in the next release.

**Comment by matozoid** [comment]
Thanks for reporting, by the way!

**Comment by andrewhabib** [comment]
You are welcome! 

Planning new release soon? (eager for the bug fix)

Currently as a temp solution, I am writing my own json to AST :thinking:

**Comment by matozoid** [comment]
Releases are every Sunday. The fix will be in there because this is my own silly mistake.

**Comment by matozoid** [comment]
Here's a PR so you can copy/paste the corrected code already.

**Comment by andrewhabib** [comment]
Ahhh! That's great. Thanks a million!

I confirm it works :smiley:

**Comment by matozoid** [comment]
Thanks, I'll merge it then :-)

**Comment by dpnolte** [comment]
Thank this also fixes it for me.
If anyone else is using jitpack.io as maven repo, you can use the follow dependency:
`implementation 'com.github.javaparser.javaparser:javaparser-core-serialization:244d595'` with the latest fix

**Comment by matozoid** [comment]
Well, the serializer got popular really quickly! 8-o
