### ISSUE TITLE
Placing Linecomments before/after other Elements

### ISSUE THREAD

**Issue by stefanleh** [javaparser/javaparser#1780]
In my current project linecomments are used as markers in the source to apply templated sourcecode.
Unfortunately some of the existing comments are applied to elements they dont really belong to and some others are moved from the end of the source to the beginning of the main class (there are subclasses) of the source. These are two issues on their own, but my main concern is that i dont have any possibility to add linecomments before/after whichever element i want, do i?

**Comment by stefanleh** [comment]
As Comments arent BlockDeclarations they cant be added before/after other members.
I tried the following without any luck ...

	BodyDeclaration dec = new BodyDeclaration<BodyDeclaration< ? >>() {

		@Override
		public <R, A> R accept(GenericVisitor<R, A> v, A arg) {

			return null;
		}

		@Override
		public <A> void accept(VoidVisitor<A> v, A arg) {

			//

		}

	};
	dec.setLineComment("Testcomment");

	mainClassInCompilationUnitDeclaration.getMembers().add(dec);

**Comment by matozoid** [comment]
Hi! If you check this https://github.com/javaparser/javaparser/labels/Comment%20support - you can see that comment support is not perfect. It needs an overhaul before it will be dependable, but for now normal comments should work.

One thing you can consider is taking a node's TokenRange and inserting comment tokens in there. To get the result, you can print all the tokens in order. This is definitely rough terrain, though.

**Comment by stefanleh** [comment]
Hello Mr. van Bruggen, thank your answer and the suggestion. Is there a special reason why elements like comments are treated differently from other elements? From my experiences with other tree-oriented parsers it shouldnt be a problem to allow addBefore and addAfter anywhere in the tree.

**Comment by matozoid** [comment]
That's a really broad question, is there anything specific you want to know?

**Comment by stefanleh** [comment]
Ok, let me ask more specific. Would it be a problem to let Comment extend BodyDeclaration? If it would then we could move the Comments around using e.g. com.github.javaparser.ast.body.TypeDeclaration.getMembers().addBefore(..).

**Comment by matozoid** [comment]
That would scratch the immediate itch, but would imply that a comment is a body declaration, which it most definitely is not, and would limit this functionality to where you can put a BodyDeclaration.

The reason I'm a bit avoidant is because a complete answer will take long to write and won't help you :-)

I'm guessing the libraries where this is possibly have much softer typing that JavaParser, and they might be offering a simple parse tree, not an abstract one.

Here you can see a braindump: https://github.com/javaparser/javaparser/issues/638 - note that the last idea is not going to work either...

**Comment by stefanleh** [comment]
Thanks for pointing to #638. This gave me some deeper understanding.
I consider `int a(int b/*x*/)/*x*/{}` things as corner cases and would be happy if exactly placed linecomments would be possible in the future. As i stated in my initial post our current templating mechanism relies on code between markers which are linecomments (eg. // START_CUSTOM_METHODS and // END_CUSTOM_METHODS). I know thats not really smart, but i cant change it for the moment.

As a short term solution i currently use JavaParser for picking up the parts of the code i need to change and use some regexes on the original code then with the collected information.

**Comment by matozoid** [comment]
I don't think JavaParser is currently much help with less than straightforward comments. There's no manpower to improve it any time soon either. Alternatives would be to use ANTLR with the Java grammar (that would be pretty bare bones though) or maybe Spoon?

Or just regexp it yes :-)

**Comment by stefanleh** [comment]
Ok, thank you for your time @matozoid and i want to add that even without that comment handling JavaParser is very helpful for my current project.
