### ISSUE TITLE
Finding static method references with scope

### ISSUE THREAD

**Issue by stefanleh** [javaparser/javaparser#1782]
I like to find method references like Classname.methodName(...) in the tree and would do the following:

	cu.findAll(MethodCallExpr.class, c -> c.getScope().isPresent()).forEach(c -> {
		ResolvedMethodDeclaration rmd = c.resolve();
		if (rmd.isStatic() && StringUtils.equals(rmd.getClassName(), c.getScope().get().toString())) {
			// hit
		}
	});

Is there a simpler/faster way?

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by ftomassetti** [comment]
Not that I am aware of. Also, I do not understand why you need `StringUtils.equals(rmd.getClassName(), c.getScope().get().toString()`

**Comment by stefanleh** [comment]
Thats cause i need to know if the method is invoked on the class and not on an instance-reference.
Usually its not needed as static calls are done on classes but in my case there can be static calls on instance-references as i am doing a conversion of a complete static project (nearly all methods are static) to dynamic methods and spring beans. Before everything is converted there are temporary static calls on instance-references.

**Comment by matozoid** [comment]
I guess this is answered?
