### ISSUE TITLE
UnsolvedSymbolException for variadic parameter

### ISSUE THREAD

**Issue by stefanleh** [javaparser/javaparser#1783]
When trying to resolve the method call 

`rtvElief(getMnudta(MNFIRM), kopf.get(KOBLINR), kopf.get(KOBFINR), fcod, "KOBLINR", LIBLAG)` 

i get an 

`UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to rtvElief(getMnudta(MNFIRM), kopf.get(KOBLINR), kopf.get(KOBFINR), fcod, "KOBLINR", LIBLAG)', cause='null'}`.

Does the symbol solver support array parameters like in 

`rtvElief(Field p_firm, Field p_linr, Field p_finr, Fcod fcod, String errorField, FieldDescription... fields)`?

**Comment by ftomassetti** [comment]
Do you mean variadic parameters? Yes, it supports them. If you share all the relevant code we can look into that. If you woul dreduce it to a failing test that would make our life even easier and we could get a solution more quickly

**Comment by stefanleh** [comment]
Yes, its a variadic parameter, just didnt knew the english name .
Maybe its worth mentioning that the method referenced exists in several versions (overloading).
I will try to put together a testcase for you.

**Comment by ftomassetti** [comment]
I also did not know the name before I started working on JavaParser :)
I think the issue could be related to overloading as variadic parameters in general are supported but picking the right overloaded method when variadic parameters are involved could be tricky.

On I side node I would love to learn more about what you are doing with JavaParser.

**Comment by stefanleh** [comment]
**Update**: The bug is within `com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isApplicable(ResolvedMethodDeclaration, String, List<ResolvedType>, TypeSolver, boolean)` and, of course, hard to find. I would appreciate some comments on what exactly that method checks and why.Unfortunately there arent many useful comments in the code.

**Comment by stefanleh** [comment]
>On I side node I would love to learn more about what you are doing with JavaParser.

I have a project which is a 1:1 conversion from RPG language to java. It was implemented without using the OOP patterns possible with java. Therefore all classes use static methods to call each other. Now i use javaparser to find the classes to the methodcalls and generate spring (@Autowired) references in the classes and change the methodcalls to use them. This enables changing all static methods to dynamic ones. Why this cant be done manually? Its more than 40k classes.

**Comment by ftomassetti** [comment]
Well, the code is complex also because the problem is complex: take a look at the [specification for resolving method calls ](https://docs.oracle.com/javase/specs/jls/se9/html/jls-15.html#jls-15.12): the whole process is scaringly complicate!
That said the quality of that part of code could be improved and an effort to rewrite it was started. 95% of the complexity is with generics and lambdas that cause the necessity of having the resolution working in two steps (the whole "loose"/"strict" stuff explained in the JLS).

**Comment by ftomassetti** [comment]
> I have a project which is a 1:1 conversion from RPG language to java. It was implemented without using the OOP patterns possible with java. Therefore all classes use static methods to call each other. Now i use javaparser to find the classes to the methodcalls and generate spring (@Autowired) references in the classes and change the methodcalls to use them. This enables changing all static methods to dynamic ones. Why this cant be done manually? Its more than 40k classes.

Quite interesting! I would love to have an interview/article on this project for my [blog on Language Engineering](https://tomassetti.me)

**Comment by stefanleh** [comment]
> Well, the code is complex also because the problem is complex: take a look at the specification for resolving method calls : the whole process is scaringly complicate!
That said the quality of that part of code could be improved and an effort to rewrite it was started. 95% of the complexity is with generics and lambdas that cause the necessity of having the resolution working in two steps (the whole "loose"/"strict" stuff explained in the JLS).

As i consider myself not as smart enough to deal with that generics/lambdas stuff my shortcut to happyness would be to move the existing code of `isApplicable` to a `MethodApplicabilityStrategy` and make it configurable via `ParserConfiguration`. That way i could write a simple version which fits my needs and inject that. Whats your opinion about that approach?

**Comment by stefanleh** [comment]
>Quite interesting! I would love to have an interview/article on this project for my blog on Language Engineering

I will ask my boss about that as i am not 100% sure what i may share and what not.

**Comment by daanschipper** [comment]
Relevant issue #1660

**Comment by stefanleh** [comment]
More hints:

Im getting Field instead of FieldDescription as last (variadic) parameter in 
   `com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(Node, boolean)`
and those arent assignable by each other.

**Comment by stefanleh** [comment]
`com.github.javaparser.symbolsolver.core.resolution.Context.solveSymbolAsValue(String, TypeSolver)` returns the wrong type ...

**Comment by stefanleh** [comment]
[https://pasteboard.co/HBgEMGY.png](https://pasteboard.co/HBgEMGY.png)
[https://pasteboard.co/HBgF4un.png](https://pasteboard.co/HBgF4un.png)

**Comment by jlerbsc** [comment]
A simple test case illustrating the problem would be much appreciated and save time. This issue was created over 2 years ago, it is difficult to say if it has been resolved. I close this issue but you are free to create a new one if you encounter this case again.
