### ISSUE TITLE
Under certain circumstances types are resolved incorrectly (modifiers are ignored)

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1784]
Here is an interesting edge-case which the symbol solver doesn't handle quite right at the moment. 

Consider following code: 
```
public class Main {
	public class ResolveMe {
		public String s = "correct";
	}

	class Child extends ParentClass {
		void foo() {
			ResolveMe x = new ResolveMe();
		}
	}
}

class ParentClass {
	private class ResolveMe {
		public String s = "incorrect";
	}
}
```

Now try to resolve the type of `ResolveMe` in `foo()`, it will resolve this to `ParentClass.ResolveMe` where `Main.ResolveMe` would be correct. The underlying issue here is that the symbol solver (correctly) first checks ParentClass for any applicable types but then ignores the `private` modifier of `ParentClass.ResolveMe`. Also see com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter#solveType(String, TypeSolver) line 71: https://github.com/javaparser/javaparser/blob/244d595d430ca4f03096ec36cf4d5bf48ef962bf/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/JavaParserTypeDeclarationAdapter.java#L71 

Pull request with corresponding failing test: #1785

**Comment by ftomassetti** [comment]
This was fixed by #1789
