### ISSUE TITLE
Cloning problems with LexicalPreservingPrinter (using 3.6.18)

### ISSUE THREAD

**Issue by olydis** [javaparser/javaparser#1793]
When parsing
``` Java
public class Test {
  public void foo(Bar x, Bar y) {
    x.barf(); // expected to be wrapped
    x.bark(); // expected to be wrapped
    y.barf(); // expected to be wrapped
    y.bark(); // expected to be wrapped
  }
}
```
and reprinting the same instance with the `LexicalPreservingPrinter`, everything works fine. However, when printing a clone of the root node, I get
``` Java
public class Test {

public void foo(Bar x, Bar y) {
    x.barf();
x.bark();
y.barf();
y.bark();
}
}
```
which has lost its indentation and comments. The code I use looks like this, in case I do something dumb:
``` Java
    LexicalPreservingPrinter.setup(sourceASTRoot);
    System.out.println(LexicalPreservingPrinter.print(sourceASTRoot.clone()));
    // ^ good output without the `clone`
```
(FYI, I'm cloning because I don't need to perform a single "path" of mutations, but instead a tree. For example in the above case I would want both one version of the source that has all "x" replaced by "a" and another version that has "y" replaced by "b", but not both at the same time! So unless I wanna undo all my changes or reparse every time, I need to clone, right?)

I saw that the `CloneVisitor` in fact seems to copy the token ranges as well so I'm not sure what goes wrong regarding indentation; but the disappearing comments are the bigger problem, I think without the `LexicalPreservingPrinter` they were moved in front of each line, but at least weren't lost :)

Thanks a ton for this library, it's super easy to use and works great otherwise! 👍

**Comment by matozoid** [comment]
Thanks for the compliments :-) Maybe @ftomassetti can say something about this?

**Comment by olydis** [comment]
Ha, I just tried setting up the printer *on the clone* and saw that this actually does preserve everything (i.e. parse, clone, setup printer, print), but once I perform edits on one of the statements (after setting up the printer), comment and indentation are lost again, but will investigate further. Ido some cloning of subtrees as part of my edits (inserting the same node multiple times, might undergo further edits that shouldn't be reflected in other instances, so need to clone, right?), so it's probably no surprise that printing behavior in those subtrees is similar to before.

So I guess the question boils down to: Is cloning *after* setting up the printer intended to be lexically preserving? Where did my comments go? 😄

**Comment by olydis** [comment]
Just realized that the `Node` that you get via `Node::getComment` is not included in `Node::getChildNodes`. Maybe that's by design, but it was unexpected to my algorithm and who knows, maybe also related to the disappearing comments issue 🤔

**Comment by olydis** [comment]
Not sure if this is intended (please lemme know), but in fact calling `setup` **multiple times** along the way, on each cloned subtree, seems to work! 🎉

![image](https://i.imgur.com/DWrI2JY.gif?noredirect)

Overall:
``` Java
final Node n = original.clone();
LexicalPreservingPrinter.setup(n);

// later, several times
final Node subTree = <some subtree of "original" or "n">.clone();
LexicalPreservingPrinter.setup(subTree);
n.[...].replace(subTree);

// finally
LexicalPreservingPrinter.print(n);
```
Awesome! If this is intended usage, feel free to consider this question answered. Making the printer "clone-aware" would of course be a little more convenient, but I think I'm unblocked. 🎈

**Comment by matozoid** [comment]
@ftomassetti ?!?

**Comment by ftomassetti** [comment]
I am surprised. What I suspect is that the LPP is saving data associated to the identity of nodes: when we clone them the LPP is not aware where data comes from. We could change that by storing the LPP data into nodes.

This is just an hypothesis, I could be very, very wrong. And I am surprised by this

**Comment by matozoid** [comment]
@ftomassetti I remember changing the LPP so that it does indeed store the information in the nodes. Okay, so I guess this needs more investigation then.
