### ISSUE TITLE
Removal of 2 ExpressionStmt's associated to same parent fails when using LexicalPreserving CompilationUnit

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1795]
https://github.com/javaparser/javasymbolsolver/issues/358

**Comment by jlerbsc** [comment]
This issue is resolved since it was declared.

    @Test
    public void testWithLexicalPreservationEnabled() {
        
        String actual = 
                "public class Foo {\n" + 
                "  void m() {\n" + 
                "    System.out.println();\n" + 
                "    System.out.println();\n" + 
                "  }\n" +
                "}";
        
        final ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setLexicalPreservationEnabled(true);
        StaticJavaParser.setConfiguration(parserConfiguration);
      
        CompilationUnit cu = StaticJavaParser.parse(actual);
        List<ExpressionStmt> exprs = cu.findAll(ExpressionStmt.class);
        exprs.forEach(e->e.remove());
        assertTrue(cu.findAll(ExpressionStmt.class).isEmpty());
    }
