### ISSUE TITLE
Wrong endLine/endColumn for primitive ArrayCreationExpr

### ISSUE THREAD

**Issue by Legioth** [javaparser/javaparser#180]
ArrayCreationExpr created for primitive types has its endLine and endColumn set according to the primitive type token instead of the terminating ] token. There's a different projection for non-primitive arrays that seems to get the expected terminating token.

**Comment by SmiddyPence** [comment]
Thanks for reporting.

I agree the way it works for object types sounds correct.

**Comment by ftomassetti** [comment]
PR #182 prepared

**Comment by SmiddyPence** [comment]
merged
