### ISSUE TITLE
java parser old version how to migrate?

### ISSUE THREAD

**Issue by allipierre** [javaparser/javaparser#1818]

**Comment by ftomassetti** [comment]
Hi @allipierre , intereseting project! Could you share more about it with us? Is your project open-source?
I did not think there was a version 1.8 of Javaparser. Anyway it would be very, very old as Javaparser 2 and later Javaparser 3 was released several years ago. Currently we are working on Javaparser 4 :D

**Comment by allipierre** [comment]
Hi @ftomassetti,

Thanks for quick Answers. Sorry I means 1.0.8. That version http://www.java2s.com/Code/Jar/j/Downloadjavaparser108jar.htm

It is not open source.

**Comment by ftomassetti** [comment]
Out of curiosity, can you telle us more about your project?

Anyway Javaparser 1.0.8 was released on the 30th of October 2011 and it is no longer supported. We encourage you to migrate to a newer version. So many things changed in Javaparser that probably no one remember how to generate comments with that particular version.

**Comment by allipierre** [comment]
Thanks for feedback. Can you share your email please? I will share more Informations with you 

By the way can you help to migrate to the new version?

**Comment by ftomassetti** [comment]
Sure, you can write to me at federico at tomassetti.me

**Comment by matozoid** [comment]
If you manage to get to version 2.5.1, you can start using the migration guide: https://github.com/javaparser/javaparser/wiki/Migration-Guide

**Comment by matozoid** [comment]
Did half the discussion disappear? @allipierre - still need help?

**Comment by allipierre** [comment]
I already found my way. Thanks
