### ISSUE TITLE
Non-public parent constructors cannot be resolved by the ReflectionTypeSolver

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1822]
Say class B extends A and calls a non-public constructor in A (so either package-private or protected) and we try to resolve that explicit constructor call using the `ReflectionTypeSolver`. The call will not be resolved as the `ReflectionClassAdapter` uses the `java.lang.Class`'s `getConstructors()`method instead of the `getDeclaredConstructors()` method. The `getConstructors()` method only returns public constructors, however, resulting in the constructor not being found. 

I believe simply replacing the call to `getConstructors()` with a call to `getDeclaredConstructors()` will not be enough, though, as access to package-private and protected constructors depends on the scope.

**Comment by ftomassetti** [comment]
You are right, it is enough to use `getConstructors`. I prepared a PR based on your test case, which sped up things a lot for me. Thank you!
