### ISSUE TITLE
Issue resolving a constructor of a class using generics

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1827]
Try to resolve the ObjectCreationExpr in line 4 in the following code snippet, it will fail. It has something to do with the fact that the symbol solver cannot determine that the constructor of `ParametrizedClass` is actually applicable, it thinks it isn't. It seems that the symbol solver can't match the argument and parameter types properly due to the use of generics, although I am not sure of the details. 
```
public class ParametrizedParametersConstructor {
    public void foo() {
        EClass arg = new EClass();
        ParametrizedClass<String> pc = new ParametrizedClass<>(arg, arg);
    }

    class EClass implements BaseType<String> {
    }
}

class ParametrizedClass<T> {
    public ParametrizedClass(BaseType<T> arg1, BaseType<T> arg2) {
    }
}

interface BaseType<T> {
}
```

Interestingly, when I remove one of the parameters/arguments from the constructor (and corresponding call), so have `public ParametrizedClass(BaseType<T> arg1) {` and ` ParametrizedClass<String> pc = new ParametrizedClass<>(arg);`, but leave everything untouched resolution works. I'd be curious where this behaviour is coming from! :)

**Comment by JiyangZhang** [comment]
Does anyone have any resolution to this problem?

**Comment by matozoid** [comment]
@JiyangZhang I've set the test case to build: https://github.com/javaparser/javaparser/pull/1828
If it fails, the problem is still there. In that case someone will have to volunteer to analyze and fix it. Are you interested?

**Comment by jlerbsc** [comment]
This issue seems to be resolved. The unit tests implemented in class ConstructorsResolutionTest work and do not generate an error.
