### ISSUE TITLE
Update copyright notice throughout JSS classes

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1835]
As mentioned in PR #1833, throughout the JSS classes, there are still copyright notices like:

> Copyright 2016 Federico Tomassetti

They should be updated.

**Comment by matozoid** [comment]
Not a very recent idea: #655 ;-)

**Comment by malteskoruppa** [comment]
This also appears to be a direct duplicate of #1801, so let me close this one. :)

**Comment by matozoid** [comment]
The good thing about having duplicates is that a single PR can close a lot of issues at once ;-)
