### ISSUE TITLE
Improving annotation support: Implement ResolvedAnnotationDeclaration#getAllFields()

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1837]
Currently, all three classes `JavaParserAnnotationDeclaration`, `ReflectionAnnotationDeclaration`, and   `JavassistAnnotationDeclaration` implement the method `getAllFields()` by throwing an `UnsupportedOperationException`. This method should be implemented properly in all three classes.

My suggestion:

Annotations do not have fields. They can only have methods, which are then called *elements*. See https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.1:

> The body of an annotation type may contain method declarations, each of which defines an element of the annotation type.

Therefore, `getAllFields()` should always either return an empty set or throw an `UnsupportedOperationException` (as it currently does).

**Comment by jlerbsc** [comment]
According to the jls there is no notion of field in an enumeration only of methods and elements. It therefore seems coherent to throw an exception if we try to invoke the getFields method on an enumeration
