### ISSUE TITLE
Ensure JavaParser can parse all the OpenJDK sources

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#184]
One of the issues opened refer to a source file from the OpenJDK. I think it can be an interesting test gabench for veryfing JavaParser can parse all files.

It is still running but so far it has parsed over 21.5K files correctly and threw an Exception on 7 of them:
- hotspot/test/runtime/8007320/ConstMethodTest.java
- jdk/src/macosx/classes/sun/font/CFont.java
- jdk/test/java/lang/annotation/TypeAnnotationReflection.java
- jdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java
- jdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java
- jdk/test/java/lang/management/MemoryMXBean/CollectionUsageThreshold.java
- jdk/test/java/util/WeakHashMap/GCDuringIteration.java

There are 177 additional failures on files from langtools/test but many of them are supposed to fail so we should investigate them one by one to see if some of them are not expected failures.

For now I think we should correct just these 7.

I have used this: http://www.java.net/download/openjdk/jdk8/promoted/b132/openjdk-8-src-b132-03_mar_2014.zip

**Comment by ftomassetti** [comment]
jdk/src/macosx/classes/sun/font/CFont.java and jdk/test/java/lang/management/MemoryMXBean/CollectionUsageThreshold.java are addressed in #135

**Comment by ftomassetti** [comment]
jdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java seems interesting. It fails on:

``` java
    // We are inside class ConstructorReceiverTest

    @Annot(5) ConstructorReceiverTest() {}

    private class Middle {
        // fails on the parameter
        @Annot(10) public Middle(@Annot(15) ConstructorReceiverTest ConstructorReceiverTest.this) {}

        public class Inner {
            @Annot(100) Inner(@Annot(150) Middle Middle.this) {}

            class Innermost {
                @Annot(1000) private Innermost(@Annot(1500) Inner Inner.this) {}
            }
        }

        class InnerNoReceiver {
            @Annot(300) InnerNoReceiver(Middle Middle.this) {}
        }
    }
```

**Comment by ftomassetti** [comment]
To me jdk/test/java/util/WeakHashMap/GCDuringIteration.java seems broken:

``` java
        {
            int first = firstValue(map);
            final Iterator<Map.Entry<Foo,Integer>> it = map.entrySet().iterator();
            it.next();          // protects first entry
            System.out.println(map.values());
            foos[first] = null;
            tryWaitForFinalizersToRun()
            // it complains about this line, I guess because the previous one misses a semicolon
            equal(map.size(), first+1);
            System.out.println(map.values());
            checkIterator(it, first-1);
            // first entry no longer protected
            for (int i = 0; i < 10 && map.size() != first; i++)
                tryWaitForFinalizersToRun();
            equal(map.size(), first);
            equal(firstValue(map), first-1);
        }
```

**Comment by ftomassetti** [comment]
PR #185 should permit to parse hotspot/test/runtime/8007320/ConstMethodTest.java and 
jdk/test/java/lang/annotation/TypeAnnotationReflection.java

**Comment by matozoid** [comment]
So, maybe we can close this, run it again, and open specific issues? It's not clear what is still to be done here.

**Comment by matozoid** [comment]
I'll close this and open a clean, new issue.
