### ISSUE TITLE
Problems with hasAnnotation() and hasDirectlyAnnotation()

### ISSUE THREAD

**Issue by malteskoruppa** [javaparser/javaparser#1843]
Rummaging through the recent annotation issues and the JSS source code, I noticed that `ResolvedReferenceTypeDeclaration` has the following two methods:

```java
    /**
     * Has the type at least one annotation declared having the specified qualified name?
     */
    boolean hasDirectlyAnnotation(String qualifiedName);

    /**
     * Has the type at least one annotation declared or inherited having the specified qualified name?
     */
    default boolean hasAnnotation(String qualifiedName) {
        if (hasDirectlyAnnotation(qualifiedName)) {
            return true;
        }
        return getAllAncestors().stream().anyMatch(it -> it.asReferenceType().getTypeDeclaration().hasDirectlyAnnotation(qualifiedName));
    }
```

The method `hasAnnotation(String)` assumes that annotations are automatically inherited. This is not so. Annotations are only inherited under special circumstances:

* The element for which we want to find out whether it inherits some annotation is a class; and
* One of the class's superclasses is annotated with the given annotation; and
* The annotation declaration of the given annotation itself is annotated with `@Inherited`.

Also see:

* [JLS 9.6.4.3 @Inherited](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.4.3)
* [Javadoc of @Inherited](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Inherited.html)
* [This example on SO](https://stackoverflow.com/a/23973331)

Therefore, I suggest to:

1. Correct the implementation of `hasAnnotation()` to do a much more restrictive ancestor search: It should (1) check that the current `ResolvedReferenceTypeDeclaration` is a class declaration; (2) recursively search the superclasses only instead of _all_ ancestors; and (3) for each found annotation expression of a superclass, resolve the corresponding annotation declaration and check whether this annotation declaration is itself annotated with `@Inherited`.

2. Can we please rename `hasDirectlyAnnotation()` to `hasDirectAnnotation()`? :-)

**Comment by jlerbsc** [comment]
This PR (https://github.com/javaparser/javaparser/pull/3383)  introduces the verification of the inheritance capacity in an annotation.
