### ISSUE TITLE
ModifierVisitor does not visit all occurrences

### ISSUE THREAD

**Issue by UlrichKrennSSI** [javaparser/javaparser#1849]
I am using JavaParser to migrate some code in our rather large code base to a new API. Currently I am stuck with a problem and I figure I need some help to get it solved.

I wrote a ModifierVisitor that changes occurrences of some method call to some other method call. The problem is that the visit method gets only called for the most outer method call, not for nested ones. I have prepared a short example which illustrates what I mean:

```
    @test
    public void visitAllMethodCallExpressions() {
        CompilationUnit cu = JavaParser.parse( //
                        "class X {\n" + //
                        "  private int myMethod(int numbers) {\n" + //
                        "    int result = Integers.parseInt(String.format(\"%s\", 12));\n" + //
                        "    return result;\n" + //
                        "  }" + //
                        "}");

        System.out.println(cu + "\n");

        cu.accept(new ModifierVisitor<Void>() {

            @Override
            public Node visit(MethodCallExpr methodCall, Void args) {
                System.out.println("Visiting: " + methodCall.toString());
                return methodCall;
            }

        }, null);

    }
```

Running this unit test results in the output:
```
class X {

   private int myMethod(int numbers) {
     int result = Integers.parseInt(String.format("%s", 12));
       return result;
   }
}

Visiting: Integers.parseInt(String.format("%s", 12))
```

Obviously, only the outer method call is visited, not the nested one which is String.format. What am I doing wrong or how can I achieve to get every method call?
I also tried to invoke the accept method recursively on all children of the method call but that also did not have the desired effect. The visit method gets called, but changing the nested method call gets lost somewhere on the way out of the recursion.

**Comment by matozoid** [comment]
Don't forget to call super :-)

**Comment by UlrichKrennSSI** [comment]
Life can be so easy sometimes... :unamused:
Calling super perfectly fixed the issue and the code works now as expected. Thanks for the quick help. Great project by the way. :+1:

**Comment by matozoid** [comment]
Thanks! Feel free to ask more :-)
