### ISSUE TITLE
Visibility of inherited methods: private shadowing

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1852]
This relates to #1789 and #1784 - there is still a case where correct resolution of inherited but not accessible types does not work properly. Consider the following example:
````
public class Main {
	public class ResolveMe {
		public String s = "correct";
	}

	class Child extends ParentClass {
		void foo() {
			ResolveMe x = new ResolveMe();
		}
	}
}

class ParentClass extends SuperParentClass {
	private class ResolveMe {
		public String s = "incorrect";
	}
}

class SuperParentClass {
	public class ResolveMe {
		public String s = "also incorrect";
	}
}
````

The class ResolveMe in ParentClass shadows the one in SuperParentClass and as it is private makes the public one in SuperParentClass inaccessible as well. The symbol solver currently ignores the private one but instead of stopping its search through the ancestors proceeds to return the one found in SuperParentClass. As soon as a type with matching name is found we can abort the ancestor search and either return the type if it is accessible or null if not.

I've extended the test written for #1784 and included a fix as well.

**Comment by ftomassetti** [comment]
This should be fixed by #1853
