### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by wx930910** [javaparser/javaparser#1854]
Hello,

When I try to test the example from **_javaparservisited_**,  I get a NoSuchMethodError when I use:
JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);

Here is my code:
```
	private static void getReference() {

		TypeSolver typeSolver = new CombinedTypeSolver();
		JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
		JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);

		cu = JavaParser.parse(code);
		cu.findAll(AssignExpr.class).forEach(ae -> {
			ResolvedType resolvedType = ae.calculateResolvedType();
			System.out.println(ae.toString() + " is a: " + resolvedType);
		});
	}
```
Here is the error message:
```
Exception in thread "main" java.lang.NoSuchMethodError: com.github.javaparser.ParserConfiguration.setSymbolResolver(Lcom/github/javaparser/resolution/SymbolResolver;)Lcom/github/javaparser/ParserConfiguration;
	at main.java.test.testJavaParser.getReference
```

Here is the dependency I used:
```
	<dependency>
		<groupId>com.github.javaparser</groupId>
		<artifactId>javaparser-symbol-solver-core</artifactId>
		<version>3.6.3</version>
	</dependency>
```

Any help will be greatly appreciated!

**Comment by matozoid** [comment]
For these questions we have made a working project setup :-) Can you double-check your configuration with this? https://github.com/javaparser/javasymbolsolver-maven-sample

(A NoSuchMethodError is almost always a project setup problem.)

**Comment by wx930910** [comment]
Thank you @matozoid That helps a lot! I read through the sample and slove the problem!

**Comment by matozoid** [comment]
Great, good luck!
