### ISSUE TITLE
Can I use this tool for java code analysis tools like ASM?

### ISSUE THREAD

**Issue by Lingam8454** [javaparser/javaparser#1856]
Can I use this tool for java code analysis tools like ASM ? If yes how can I use this project?

**Comment by matozoid** [comment]
Hello!

What this tool does and how it is used is described here: http://javaparser.org/

Do you have a more specific question?

**Comment by Lingam8454** [comment]
We need to construct a java method hierarchy database. Is java parser tool suitable for us?

**Comment by matozoid** [comment]
If what you want is: parse file, find classes, find methods, then it is definitely suitable. A method hierarchy is a caller hierarchy? Then you can use the symbol solver module. It has its limits but seems usable for most people.
