### ISSUE TITLE
Escape strings in DotPrinter

### ISSUE THREAD

**Issue by wozuo** [javaparser/javaparser#1871]
Hey everyone,

I just noticed the DotPrinter (https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/DotPrinter.java) doesn't escape strings, so it's possible that one can end up with invalid DOT syntax. 

An example I just encountered is the comment `//Log.v(TAG, "getSSLContext()");` will be translated to `n590 [label="content='Log.v(TAG, "getSSLContext()");'"];` but should be `n590 [label="content='Log.v(TAG, \"getSSLContext()\");'"];`. 

Best regards,
Marc

**Comment by matozoid** [comment]
Thanks! The fix will be released today.

**Comment by matozoid** [comment]
Better test this for end-of-line characters too...

**Comment by matozoid** [comment]
End of line characters are fine :-)
