### ISSUE TITLE
cannot solve methodcall which contains fileld access as parameters

### ISSUE THREAD

**Issue by penelope24** [javaparser/javaparser#1875]
trying to solve a method call like this: 
```
ConditionalFormattingRule rule1 = sheetCF.createConditionalFormattingRule(
                CFRuleRecord.ComparisonOperator.BETWEEN);
```
throws exception: 
UnsolvedSymbolException{context='unknown', name='BETWEEN', typeSolver=null}

**Comment by matozoid** [comment]
Hi! Can it be that you haven't set up a type solver? In that case, take a look at the book for the whole story, or this sample project for a hint: https://github.com/javaparser/javasymbolsolver-maven-sample

**Comment by penelope24** [comment]
@matozoid thx for your kind reply! Actually I've set up a CombinedTypeSolver which contains reflections, jars and the package contain the source code. So I got little confused about how to solve this Exception.

**Comment by matozoid** [comment]
I'd say that something is missing in your setup code, since "typeSolver=null" - do you have that code for us to see?

**Comment by matozoid** [comment]
Closing because inactive.
