### ISSUE TITLE
Question about importing private member class.

### ISSUE THREAD

**Issue by teletha** [javaparser/javaparser#1880]
CompilationUnit#addImport(PrivateMemberClass.class) will generate code like the below
`import package.TopLevelClass.PrivateMemberClass;`

But java compiler reports error "The type PrivateMemberClass is not visible".
(No problem about public, protected or package-private member class)

Is this a bug that CompilationUnit#addImport can't filter private member class?
or
Filtering private member class is responsibility of Printer implementation?

**Comment by matozoid** [comment]
Hi!

The parser and AST are very happy to let you generate all types of invalid code. It only knows about the AST of a single source file, so it can't say anything about which import is correct, and which is not. It is your responsibility not to import classes that are not visible.

**Comment by teletha** [comment]
Thanks for your reply, I will filter them myself.
