### ISSUE TITLE
How can I retrieve a qualified signature from MethodDeclaration?

### ISSUE THREAD

**Issue by Chri-Ri** [javaparser/javaparser#1881]
## The Problem
How can I match the signatures from 
`MethodDeclaration.getSignature().getParameterTypes().toString()`
and
`JavaParserFacade
	.get(combinedTypeSolver)
	.solve(MethodCallExpr methodCall)
	.getCorrespondingDeclaration()
	.getSignature()`
?
## Some Details
Given this MethodDeclaration:

`public List<Zustellung> SucheZustForEmpfVonBis(String empfaenger, Date von, Date bis, Boolean ohne) { ... }' 

MethDecl returns:
as returntype:
`"List<Zustellung>"`

as signature:
`"String, Date, Date, Boolean"`

From MethodCall i get:
as returntype:
`"java.util.List<at. ... .bo.Zustellung>" (some parts skipped for privacy)`

as signature:
`"SucheZustForEmpfVonBis(java.lang.String, java.util.Date, java.util.Date, java.lang.Boolean)"`

I need a connection between both variants (qualified and 'unqualified').
It's not important from which variant I get the other one 
(But I guess its better to retrieve the unqualified types from the qualified ones).

Does a method exists which "translates" between the 'unqualified' and the qualified ?
Sure, I could implement a method, but if the wheel already exists, why reinvent it ?
(By the way, it could fail if there are some equally-named types in different classes
because it's unambiguousness which is meant)
Or does a method exist which I can use to "expand" the simple signature to a full qualified signature?

## My Background
I started programming in the mid-80ies, with object-orientation I started at the end of the 80ies.
Half a year ago I got a new job and started programming with java. in former jobs I was programming about 20 years with RDBMS progress and I developed a cross-reference-tool (starting with some project found in an usergroup). So I wanted to do this in java. The project at my office contains some 10.000 source-files, so I decided to store the results in a database. Having stored the Method-Declarations and the MethodCallExpressions, I stumbled upon the different signatures so I cannot connect the Calls with the Declarations.
For example I would like to create some "call-tree" (like a call-stack; eg. with GraphViz), but for this I need to know exactly which of the overloaded methods is called

## PS
+ Sorry for my english, I am from Austria and didnt practise enough correspondence in english.
+ Sorry for any mistake I made at my first issue
+ I hope that I explained the problem clear enough

I hope someone can help with this issue.

**Comment by ftomassetti** [comment]
Danke sehr für deine clear Erklärung.
Keine Sorge, dein Englisch ist besser als mein Deutsch :)

`JavaParserFacade .get(combinedTypeSolver) .solve(MethodCallExpr methodCall) .getCorrespondingDeclaration()` give you a [ResolvedMethodDeclaration](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.6.25/com/github/javaparser/resolution/declarations/ResolvedMethodDeclaration.html), which is an object which describe a declaration for the Symbol Solver. The declaration could come from source code, JARs or through reflection.

On the other hand you are looking at `MethodDeclaration`, which is an object that represent a method declarion _in the AST_. Now, you can go from a `MethodDeclaration` to a `ResolvedMethodDeclaration` just by calling [`resolve`](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.6.25/com/github/javaparser/ast/body/MethodDeclaration.html#resolve--). Once you do that you have two `ResolvedMethodDeclaration` on the two sides, so the signature will have the same format.

Hope it helps!

**Comment by Chri-Ri** [comment]
How could I overlook that ???
I was digging and digging and digging in the javadoc and I didn't see the wood for the trees.
Yeah, I think this will help.
But I cannot test ths now, because I'm leaving the office. I'll try sometimes in the weekend.
Thank you very much.

**Comment by matozoid** [comment]
@Chri-Ri - if you have suggestions on how to improve the documentation, that would be helpful to us.

**Comment by Chri-Ri** [comment]
Sorry for don't answering for this long time.
I was very busy in and outside the office this week. 
But last weekend I tried resolving from a methoddeclaration and I got the infos needed :) 
Thanks again.
