### ISSUE TITLE
Finding lambda return type

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1883]
I found the following code in TypeExtractor:
```java
                            actualType = returnStmts.stream()
                                    .map(returnStmt -> returnStmt.getExpression().map(e -> facade.getType(e)).orElse(ResolvedVoidType.INSTANCE))
                                    .filter(x -> x != null && !x.isVoid() && !x.isNull())
                                    .findFirst()
                                    .orElse(ResolvedVoidType.INSTANCE);
```
Does this mean that a lambda expression that contains multiple return statements will always have the type of the first return statement, and the other will be ignored? Shouldn't it return the shared parent of all the return statements types?

@ftomassetti ?

**Comment by ftomassetti** [comment]
Well, that is probably the case. I guess we did not have the logic to find the common super type at the time, while now we should have that

**Comment by jlerbsc** [comment]
This can certainly be achieved by returning the least upper bound type

**Comment by jlerbsc** [comment]
Linked to https://github.com/javaparser/javasymbolsolver/issues/200
