### ISSUE TITLE
CollectionStrategy - directory comparison

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#1888]
It appears that if the collection strategy fails when there is a mismatch between using the windows-style paths with an initial drive letter versus other style paths (e.g. `C:/var/test`) with a leading slash (e.g. `/var/test`). 

```
        final ProjectRoot projectRoot =
                new ParserCollectionStrategy()
                        .collect(Paths.get(x));
```

```
        final ProjectRoot projectRoot =
                new SymbolSolverCollectionStrategy()
                        .collect(Paths.get(x).toAbsolutePath());
```

The comparison occurs on the following lines of the following files:

https://github.com/javaparser/javaparser/blob/4f682b22ae276ed7e18a2928cfdabd4813775aa3/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/utils/SymbolSolverCollectionStrategy.java#L68 

https://github.com/javaparser/javaparser/blob/4f682b22ae276ed7e18a2928cfdabd4813775aa3/javaparser-core/src/main/java/com/github/javaparser/utils/ParserCollectionStrategy.java#L60

In my use case that has made this visible, I am storing paths normalised to unix-style path string (not a perfect solution, but forward slashes do get explicitly converted to back-slashes on Windows so hopefully safe enough!).

A test case demonstrating the different results of path comparison using this technique is shown below. Note that exactly how Windows deals with paths with a leading slash can be variable, according to a few online resources (though I don't fully understand when it differs).

```
    @Test
    public void filePathComparisonTest() {
        Path x1 = Paths.get("/var/test/");
        Path x2 = Paths.get("C:/var/test/");
        Path x3 = Paths.get("C:\\var\\test\\");

        assertTrue(x1.equals(x2)); // Fails  (Windows 7)
        assertTrue(x2.equals(x3)); // Passes (Windows 7)
        assertTrue(x1.equals(x3)); // Fails  (Windows 7)

        assertTrue(x1.toAbsolutePath().equals(x2.toAbsolutePath())); // Passes (Windows 7)
        assertTrue(x2.toAbsolutePath().equals(x3.toAbsolutePath())); // Passes (Windows 7)
        assertTrue(x1.toAbsolutePath().equals(x3.toAbsolutePath())); // Passes (Windows 7)
    }
```

**Comment by MysterAitch** [comment]
To resolve this, I suggest that the paths be converted to the absolute path (or some other normalised version). Example:

`if (dir.toAbsolutePath().equals(current_root.toAbsolutePath())) { `

Does this sound like a reasonable suggestion? Are there any other cases that this might not adequately cover (e.g. network directories such as `\\shared\dir`)?

nb: The same fix may be needed at other locations in the same file too, though I haven't gotten to testing those yet (e.g. where `.startsWith()` is used).

**Comment by matozoid** [comment]
Well, sorry for being so late. I googled a bit and would like to ask if `Files.isSameFile` also works? That seems to be the recommended way. I don't have access to a Windows machine so I can't check it myself.

**Comment by matozoid** [comment]
Hello @MysterAitch ?

**Comment by MysterAitch** [comment]
Apologies, not checked in for a while. 

I can confirm that `Files.isSameFile` appears to work, as described below:

```java
    final private Path x1 = Paths.get("/var/test/");
    final private Path x2 = Paths.get("C:/var/test/");
    final private Path x3 = Paths.get("C:\\var\\test\\");

    @Test
    public void pathComparisonTest_Files_isSameFile() throws IOException {
        // Files.isSameFile throws IOException if files do not exist
        Assume.assumeTrue(x1.toFile().exists());
        Assume.assumeTrue(x2.toFile().exists());
        Assume.assumeTrue(x3.toFile().exists());

        assertTrue(Files.isSameFile(x1, x2)); // Passes (Windows 7)
        assertTrue(Files.isSameFile(x2, x3)); // Passes (Windows 7)
        assertTrue(Files.isSameFile(x1, x3)); // Passes (Windows 7)
    }
```


Additionally, `Files.isSameFile` works with `../` and similar - to do the same otherwise would need to canonicalise the path (after `Path.toFile()`) rather than just convert to an absolute path.

Overall, it seems significantly more robust and handles many more cases than my proposed solution of using absolute/canonical paths.

**Comment by MysterAitch** [comment]
PR sent but I'm not sure if/how this should be tested, given that the drive lettering is Windows-specific and isSameFile requires the files to actually exist.

The new JUnit5 [@EnabledOnOs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-os-demo) can help with the OS differentiation. 

Not all systems will have the same drive lettering or directory/file structures available (e.g. can't necessarily assume the existence of a `C:/` drive). In which case we start encroaching on either inferring paths/directory structures, and/or creating them (fragile and/or dangerous?).

**Comment by matozoid** [comment]
Not sure what you mean with the last bit? We're only comparing files here?

We've got Travis, which is Linux, and AppVeyor, which is Windows. So platform mistakes will be noticed :-)

**Comment by MysterAitch** [comment]
Known equivalent paths (but textually different) are needed or they need to be generated (e.g. to compare windows-style `C:/` against unix-style `/`). 

The line of thought in the last bit was re: creating a directory structure e.g. `C:/test` but I see now that is unnecessary and just the roots could be compared. 

Inferring paths related to inferring/finding the drive letter that Java on Windows would find equivalent to the unix `/`.
