### ISSUE TITLE
NameExpr should not appear in unrelated node types 

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#189]
NameExpr is a kind of node representing an Expression but it is useful in different places just a synonim of a Name/QualifiedName. I think this cause confusion. For example when visiting nodes once I find a NameExpr I need to examine the parent to understand if it is a proper NameExpr or just a name in some other context.

**Comment by ptitjes** [comment]
I had a similar thoughts when I started to work on JLaTo and this made me name them "Name" and "QualifiedName". What are the 'other context's you speak about ? Are you thinking about using <IDENTIFIER> directly for the name of methods in MethodInvocationExpr for instance ?

I'm curious to see what ideas you have to resolve this as I took the reverse approach, in a fit of pique, to remove the 'Expr' suffix. I'm not quite sure this is good enough.

Some interesting reading that you might like about so-called 'name's in the java language from Eclipse's DOM:
- [org.eclipse.jdt.core.dom.QualifiedType](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FQualifiedType.html)
- [org.eclipse.jdt.core.dom.QualifiedName](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FQualifiedName.html)
- [org.eclipse.jdt.core.dom.FieldAccess](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FFieldAccess.html)

**Comment by ftomassetti** [comment]
NameExpr is used:
- to represent the names of ClassOrInterfaceDeclaration EnumDeclaration
- in ImportDeclaration
- in AnnotationTypeDeclaration
- in PackageDeclaration

and in some other places. I would also just rename NameExpr and QualifiedNameExpr to Name and QualifiedName and introduce a proper NameExpr (probably having as only child a Name) when the name is used as an expression (i.e., when referring to a field, a local variable or a parameter by name).

**Comment by SmiddyPence** [comment]
I don't know the correct answer, but it is something that was not as prevalent in the 1.5 version of the grammar, in most cases name was just a String.

From memory javalang (Walkmod) elected to keep it as a String, or perhaps forked before the change and hasn't found the need to change.  It was probably one of the most distinct divergences between the two grammars.

**Comment by ftomassetti** [comment]
I think there are benefits in having a node because it has a position. It can be useful if we want to perform space preserving changes or to identify exactly the name in the source code (useful for syntax highlighting I guess). I would just say that we should use NameExpr to indicate an Expression, not a synonim of string.

**Comment by ptitjes** [comment]
Just a note to say that in JLaTo I did remove all direct `<IDENTIFIER>` references in favor of Names. Even for labels in break and continue. I consider labels to be names.

**Comment by matozoid** [comment]
Is there anything specific we can do after this discussion?
