### ISSUE TITLE
Provide a way to add a field "at a given index", not just at the end

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser#1894]
`NodeWithMembers#addField` allows you to add a field, e.g. to a `ClassOrInterfaceDeclaration`. However it will always add the field "at the end". 

I had to insert the field "at the beginning". To do so I had to 
- get the list of field using `NodeWithMembers#getMembers`, 
- "manually" create the field
- add the field to the list using `List#add(int,N)`.

Most of this was just copy of code already implemented in `NodeWithMembers#addField`. 

To avoid this duplication `NodeWithMembers` could provide an overload of `addField` that allows specifying the index in the list the field should be inserted.

E.g.: 
`default FieldDeclaration addField(int index, Class<?> typeClass, String name, Modifier... modifiers) ...` 
_(Similar for the other overloads)_

Providing such an overload would also mirror the List interface that also provides an `#add(int, N) ` as well as an `#add(N)` method.

**Comment by matozoid** [comment]
Hi! I missed this issue, sorry!

I'm reading the following things:
- to add a field at the beginning, use `add(int,N)`. Good news here: `NodeList` has convenience methods like `addFirst` and `addBefore` for this purpose.
- the methods that are available on `NodeList` should also be available on every class for every property that is a `NodeList`. No, you're not actually writing that, but if we add convenience methods I have to consider how far we go. My gut feeling is that the indexed add is one step too far (we'll have to introduce it all over the place for every property that's a list.)
- you like the convenience add-methods. Too bad that they work directly on their node, so you can't use them with the `NodeList` methods. Now you have to create the node without all the convencience. I think we can improve something here, but I'm not sure what.

**Comment by abego** [comment]
Hi,

thanks for your detailed response. 

Now that I know I can directly modify the NodeList returned by getMembers()  without being afraid this may no longer work in future versions of JavaParser I don't think there is need for the feature I requested. You may close the issue.

Udo

P.S.: Just in case you like to know a little bit more about my initial motivation for the request...:

When I posted the issue I was very new to JavaParser. I knew I want to add a field to a Class(...)Declaration, looked for a "matching" API and found the "addField" method in the NodeWithMembers interface, implemented by ClassOrInterfaceDeclaration/TypeDeclaration.

I never thought of "addField" as a __convenience__ method, but as __the__ method to add fields to a ClassDeclaration (maybe you want to mark these methods as "convenience" methods?). Also I typically hesitate to modify a list returned by an object when the object also has methods that change the list. I then think the "expected" way to modify the list is through the API of the object and the List returned by the object is "read only". So the _convenience_ methods led me in a wrong direction.

For me a note in the JavaDoc of NodeWithMembers#getMembers may have helped, telling something like: "The returned NodeList is part of the state of this NodeWithMembers object, so changing the NodeList changes the state of the object. Working directly on the returned NodeList is expected way to work with the members".

**Comment by matozoid** [comment]
Thanks for explaining your thought pattern - next time a question like this comes up I'll know how to answer it better. I've also made an issue to improve the documentation.
