### ISSUE TITLE
Generify MethodResolutionLogic#solveMethodInType(...) to Allow for External Implementations

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#1910]
The method [`solveMethodInType(...)` in `com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic` ](https://github.com/javaparser/javaparser/blob/8209c03065e69860be9b2bd65fa0753a27bbf38e/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/MethodResolutionLogic.java#L578-L619) tries to find a method in a type. It checks which kind of `ResolvedTypeDeclaration` was provided as argument and proceeds depending on the Type identified. 

I've recently started implementing a custom type solver with custom `ResolvedTypeDeclaration`, implementations which works fine so far. I call `resolve()` on an AST node and my type solver will also be used to resolve the node. Resolving method calls fails in the `solveMethodInType(...)` function, however, as the function does not accept new/external implementations of `ResolvedTypeDeclaration` and throws an exception when encountering one.

So far, I've come up with two possible solutions. I can modify the method to consider my custom `ResolvedTypeDeclaration` implementations. Since my implementations are very specific to my project and what I am doing and bring no additional value to anyone else, I would have to put this into a private fork and maintain it alongside the official fork of JavaParser. This seems suboptimal and anyone implementing a new `ResolvedTypeDeclaration` would have to do this in order to get method resolution to work.

The second and in my eyes preferred solution is to leave the method solving logic to the implementations of 'ResolvedTypeDeclaration'. All `solveMethodInType(...)` really does, is call `solveMethod` on the different implementations of `ResolvedTypeDeclaration` or their context, right after a cast. You could put a generic abstract `solveMethod` into a new interface (or would `ResolvedReferenceTypeDeclaration` work?), which all implementations of `ResolvedTypeDeclaration` can implement if they support it. Then `solveMethodInType` could be simplified to `typeDeclaration.solveMethod(...)`, probably even removing the need for that method entirely. At the same time, support for other implementations of `ResolvedTypeDeclaration` would not be blocked.

What do you think about this proposal?

**Comment by ftomassetti** [comment]
`ResolvedTypeDeclaration` was never intended to be extended outside the library because, well, Java is Java. I could imagine that someone may want to extend it if they planned to writed a solver for _an extended version of Java_. Is this the case? If it is not, why do you want to extend `ResolvedTypeDeclaration`? To make it able to represent classes defined in other JVM languages?

I would discourage you from doing a fork because maintaining this stuff and evolve it as Java evolve is **hard**, better to put all forces together. 

If you ask me why `solveMethodInType` works in this way instead of using some common interface I honestly do not remember. However, I think that if there was an issue preventing that solution we would very soon meet it as we try to do what you propose.

Maybe it was part of the effort of reducing the number of methods which requires a `TypeSolver` as a parameter.

Also, note that this method is commented with "// TODO: Replace TypeDeclaration.solveMethod". So there was an intention to get rid of one of the two.

**Comment by ftomassetti** [comment]
In other words, I would be happy to work with you on this proposal if you can prepare an initial PR.

**Comment by matozoid** [comment]
(As the maintainer I would like to urge you all to think up a good approach to extending the solver and implement it fully, instead of fixing the direct problem and leaving other extension points for other users to solve ad-hoc.)

**Comment by jjbr** [comment]
> I could imagine that someone may want to extend it if they planned to writed a solver for _an extended version of Java_. Is this the case? If it is not, why do you want to extend `ResolvedTypeDeclaration`?

The reason for me wanting to implement the `ResolvedTypeDeclaration` (well actually more specific types such as the `AbstractClassDeclaration` but that is besides the point) is that I am trying to add another data source to the solver (for regular Java). So far the symbol solver can resolve types using a variety of different data source. The `JavaParserTypeSolver` extracts information from the source code itself but then there are more type solvers to resolve types that can be found in e.g. loaded libraries or JAR files. Some of these other type solvers require special implementations of the `ResolvedTypeDeclaration` as well (e.g. `ReflectionClassDeclaration`).

Now I have some additional type information lying around in a project-specific data format, which can be used to resolve types of which I have already discarded the source/byte code. My reasoning was that I can simply write an additional type solver that uses that external, custom-format data and provides type resolution with it. That required custom implementations of e.g. `ResolvedTypeDeclaration`, as my back-end data is of an entirely different format to what the Symbol Solver knows so far.

I figured this was a valid case to implement/extend those interfaces/classes and it seemed really rather elegant - basically I could just 'plug and play' my custom typesolver into the symbol solver and it would work (which it did for most of the type resolution already! :) ). Is there a better way to do this?

> I would discourage you from doing a fork because maintaining this stuff and evolve it as Java evolve is **hard**, better to put all forces together.

Yea, I totally agree - I really don't want to make a fork! :D I'd much rather just write a couple of classes that I can plug into the symbol solver and extend its functionality a little.


> Also, note that this method is commented with "// TODO: Replace TypeDeclaration.solveMethod". So there was an intention to get rid of one of the two.

I saw that and wondered whether something was going on here anyway - perhaps there is a chance of killing two birds with one stone here.


> In other words, I would be happy to work with you on this proposal if you can prepare an initial PR.

That sounds great! :slightly_smiling_face: I'd be happy to prepare a pull request. From what I've described, do you think the approach is reasonable?

**Comment by ftomassetti** [comment]
> (As the maintainer I would like to urge you all to think up a good approach to extending the solver and implement it fully, instead of fixing the direct problem and leaving other extension points for other users to solve ad-hoc.)

To do that I would need to understand who wants to extend this part of the solving process and for which reason. That is not clear to me yet.

**Comment by ftomassetti** [comment]
> The reason for me wanting to implement the `ResolvedTypeDeclaration` (well actually more specific types such as the `AbstractClassDeclaration` but that is besides the point) is that I am trying to add another data source to the solver (for regular Java). 

Could you expand on that? Is that another way to identify Java compilation units? Are those compilation units not on file but on DB or somewhere else (e.g., git repository)?

>So far the symbol solver can resolve types using a variety of different data source. The `JavaParserTypeSolver` extracts information from the source code itself but then there are more type solvers to resolve types that can be found in e.g. loaded libraries or JAR files. Some of these other type solvers require special implementations of the `ResolvedTypeDeclaration` as well (e.g. `ReflectionClassDeclaration`).

In general I see this: the typesolver define **where** to find stuff, and the subclasses of `ResolvedTypeDeclaration` deal with the different way of **storing** the information. For now the mapping is basically one to one, so for each type solver we have one set of subclasses of `ResolvedTypeDeclaration` but this has not to be necessarily the case.

> Now I have some additional type information lying around in a project-specific data format, which can be used to resolve types of which I have already discarded the source/byte code. My reasoning was that I can simply write an additional type solver that uses that external, custom-format data and provides type resolution with it. That required custom implementations of e.g. ResolvedTypeDeclaration, as my back-end data is of an entirely different format to what the Symbol Solver knows so far.

Ok, it makes sense to me

**Comment by jjbr** [comment]
> Could you expand on that? Is that another way to identify Java compilation units? Are those compilation units not on file but on DB or somewhere else (e.g., git repository)?

I have data stored in a database, exactly. 

> In general I see this: the typesolver define **where** to find stuff, and the subclasses of `ResolvedTypeDeclaration` deal with the different way of **storing** the information. For now the mapping is basically one to one, so for each type solver we have one set of subclasses of `ResolvedTypeDeclaration` but this has not to be necessarily the case.

That is my understanding as well. The one-to-one mapping seems logical, given the fact that the way of storing data usually varies depending on where to find it.


Now upon closer inspection I believe I know what the TODO comment above the method is about. It says to replace `TypeDeclaration.resolveMethod` and is pretty new (from August '18). Quite a few of the `resolveMethod(...)` methods are marked as deprecated (at least some of them for 2 years now), which this comment likely refers to; replace the calls to those methods with something non-deprecated.

I was wondering if you can provide a bit more insight into why those methods are deprecated and what the alternative is. Can you, by any chance, remember your train of thoughts from when you marked those methods as deprecated? Did you have a concrete plan how to replace the functionality of these methods in a different manner? As long as only the implementations of these methods is deprecated, not their interface, I will refactor in a way that simply continues using them for the time being.

**Comment by matozoid** [comment]
When you're on it, @ftomassetti, can you also look at #1395 #1396 #1397 ? These issues are blocking me from cleaning up the code.

**Comment by matozoid** [comment]
I'm assuming this issue is now fixed.
