### ISSUE TITLE
Visit fields in block statment

### ISSUE THREAD

**Issue by linh-le** [javaparser/javaparser#1912]
Hi there,

I'm trying out Java Parser and have a question. I bought and read the book yet still am unable to figure out this seem to be basic function.
I'm trying to analyze only certain methods. To do that, when I visit the method, I'm getting the block statement, and trying to visit the inner fields of that block. However, nothing happens when I run the code (the InnerFieldVisitor's visit(..) method isn't called). Could you show me the correct way to do it?

```
 public static void main(String[] args) throws Exception {
        // creates an input stream for the file to be parsed
        FileInputStream in = new FileInputStream(FILE);

        // parse it
        CompilationUnit cu = JavaParser.parse(in);

        // visit and print the methods names
        cu.accept(new AnnotationVisitor(), null);
        cu.accept(new FieldVisitor(), null);
        cu.accept(new MethodVisitor(), null);

    }

    /**
     * Simple visitor implementation for visiting MethodDeclaration nodes.
     */
    private static class MethodVisitor extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(MethodDeclaration n, Void arg) {
            /*
             * here you can access the attributes of the method. this method will be called for all methods in this CompilationUnit,
             * including inner class methods
             */
            if (n.getBody().isPresent()) {
                BlockStmt blockStmt = n.getBody().get();
                // it got here
                blockStmt.accept(new InnerFieldVisitor(), null);
            }

//            super.visit(n, arg);
        }

private static class InnerFieldVisitor extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(FieldDeclaration n, Void arg) {
            // but it didn't get here
            FieldDeclarationMetaModel metaModel = n.getMetaModel();
            EnumSet<Modifier> modifiers = n.getModifiers();
            FieldDeclaration fieldDeclaration = n.asFieldDeclaration();
            
            super.visit(n, arg);
        }
    }
}
```

**Comment by matozoid** [comment]
Hi!

A `FieldDeclaration` only exists at class level, not at method level (unless you are dealing with a rare local class.) If you want to see what you are dealing with, you can visualize the AST in several ways: http://javaparser.org/inspecting-an-ast/

**Comment by matozoid** [comment]
No response, I guess this has been answered.

**Comment by linh-le** [comment]
Yes, thanks for following up. Looking for some alternative that fits our purpose better now.

**Comment by bertbeck** [comment]
Are you the linh-le that wrote this article? 
https://niteco.com/blogs/from-expo-to-react-native/

I'm looking for an expert in Expo/React Native to help me understand how to use React Native only (without Expo) but separate Native and Javascript development similar to Expo (except that we'd be able to add/update native code). If you are this person - I think you might have some insights. If you or anyone else has such expertise, insight or interest - please respond here.

**Comment by linh-le** [comment]
No I’m not. Good luck finding the person!

**Comment by matozoid** [comment]
@bertbeck is now blocked from this repo because he's obviously abusing it.
