### ISSUE TITLE
LexicalPreservingPrinter does not (always) print renamed Types

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser#1913]
I am using JavaParser to rename some types, say `T1` to `T2`. 

I noticed this rewrite is not always reflected in the output generated by LexicalPreservingPrinter. 

Interestingly `CompilationUnit#toString()` always returns the correct result.

Here an example:

    class C {
    
        T1 f;
    
        T1 m() {
            return f;
        }
    }

When I rename the `T1` to `T2` the LexicalPreservingPrinter will print out this result:

    class C {
    
        T1 f;
    
        T2 m() {
            return f;
        }
    }
Notice the type of the field is still `T1` and not `T2`, but the return type of the method is `T2`, as expected.

On the other side using `CompilationUnit#toString()` returns the expected result:

    class C {
    
        T2 f;
    
        T2 m() {
            return f;
        }
    }

[JavaParserSimpleNameRewriteBugTest.java.txt](https://github.com/javaparser/javaparser/files/2568365/JavaParserSimpleNameRewriteBugTest.java.txt) contains a complete JUnit test showing the issue.

**Comment by matozoid** [comment]
Thanks! We're very happy with the test case, it makes things a lot easier.

**Comment by jlerbsc** [comment]
I don't know if it's an issue and how to resolve it but we can reproduce it with these unit tests.
The NodeText of the VariableDeclarationExpr, used by LexicalPreservingPrinter  to print the node's state, has not been modified with the replacement.

So to change the VariableDeclaration's type it is safer to change the type rather than to change the type's name.

    class Issue1913Test extends AbstractLexicalPreservingTest {

    @Test
    void test2() {
        String src = 
                "T1 f"; 

        considerVariableDeclaration(src);
        System.out.println(LexicalPreservingPrinter.print(expression));
        
        SimpleName name = expression.findFirst(SimpleName.class).get();
        name.getParentNode().get().replace(name, new SimpleName("T2"));
        
        assertEquals("T2 f",LexicalPreservingPrinter.print(expression));
    }
    
    @Test
    void test3() {
        String src = 
                "T1 f"; 

        considerVariableDeclaration(src);
        System.out.println(LexicalPreservingPrinter.print(expression));
        
        VariableDeclarator vd = expression.findFirst(VariableDeclarator.class).get();
        ClassOrInterfaceType nType = new ClassOrInterfaceType("T2"); 
        vd.replace(vd.getType(), nType);
        
        assertEquals("T2 f",LexicalPreservingPrinter.print(expression));
    }
    
    }

**Comment by jlerbsc** [comment]
This does not seem to correspond to a bug but maybe it would be necessary to further document the best practices to modify a source code with JP. In this case we need to document how to change the type of a variable.
