### ISSUE TITLE
MethodDeclaration should return JavadocComment even if it's followed by a line comment

### ISSUE THREAD

**Issue by marcphilipp** [javaparser/javaparser#1914]
For code like the following, the corresponding `MethodDeclaration` currently returns the text of the line comment (TODO ...) for `getComment()` and an empty `Optional` for `getJavadocComment()`.

```java
/**
 * Some Javadoc.
 */
// TODO ...
public void someMethod();
```

I haven't found a way to extract the `JavadocComment`, not even when implementing the `visit(JavadocComment, ...)` method. Would it be possible for a `MethodDeclaration` to have both a regular comment and a Javadoc comment?

**Comment by ftomassetti** [comment]
No, each node can have at most one comment associated. Therefore the other comment is considered an oprhan comment that is contained in the node physically containing this node. Comments are a bit peculiar and are not technically part of the AST, so this is why you cannot find them using visitors.

You could use [Node.getOrphanComments()](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.7.0/com/github/javaparser/ast/Node.html#getOrphanComments--)

**Comment by marcphilipp** [comment]
On which `Node` would I have to call `getOrphanComments()` in the above example? The enclosing `ClassDeclaration`?

**Comment by ftomassetti** [comment]
Yes, the enclosing `ClassDeclaration`.

We save all comments and we associate some of them to specific nodes by using heuristics (the logic is in [CommentsInserter](https://github.com/javaparser/javaparser/blob/6b9344dcd41302a1e81d8ff55baa8f8ff43dc5e6/javaparser-core/src/main/java/com/github/javaparser/CommentsInserter.java)). 
The comments not associated to nodes are considered _orphan_.

There are no strict rules we can rely upon as comments could be inserted everywhere so we think it is hard to find an approach that makes everyone happy all times, however we are happy to hear suggestions to improve those heuristics

**Comment by marcphilipp** [comment]
Alright, for now I've changed the offending code in our codebase but it's good to know that there's a workaround, should we need one. Thanks!

**Comment by ftomassetti** [comment]
You are welcome, thanks for reporting this

**Comment by matozoid** [comment]
I've been pondering this, and I think this is (another) workaround:
- get the first token in the token range for the method.
- find the body declaration preceding the method (interesting when it is the first thing in the class)
- get the last token in the token range for the preceding method.
- walk through last token -> first token.
- check the tokens to see if their type is some kind of comment. Collect the ones you want.

**Comment by JiyangZhang** [comment]
Is this bug of JavaParser.getComment() fixed for those strange Javadoc?

**Comment by matozoid** [comment]
Not yet. There is a plan to make a stand-alone object that can give information about comments, but work has not started yet.
