### ISSUE TITLE
Comparing Between Eclipse JDT and JavaParser

### ISSUE THREAD

**Issue by Symbolk** [javaparser/javaparser#1919]
As far as I know, the most powerful two state-of-the-art parsers for Java are Eclipse JDT and JavaParser. Based upon one of them, I am going to build my application. However, it is hard to choose, so I what to ask: 

> What are the differences between Eclipse JDT and JavaParser, or what are their particular advantages & disadvantages?

**Comment by ftomassetti** [comment]
I have used the Eclipse JDT before. JavaParser is way, way easier to use. You can configure it in a few lines while JDT comes with a tons of dependencies, OSGi, and an extremely complex configuration (basically you have to recreate an Eclipse project to make it work).

Also, JavaParser is _listening_ to its users, so over time we strive to make it more usable and clear.

That said JDT is probably more mature on the symbol resolving part, as they have much larger resources for the development. If you consider only the parsing part than JP is as mature as it could be.

**Comment by matozoid** [comment]
Here are some feasible alternatives: http://spoon.gforge.inria.fr/ (beware of the license), and I'm pretty sure someone wrote a wrapper for the JDT to make it easier to use.

**Comment by Symbolk** [comment]
Thanks for the reply, actually I have been playing with the 3 parsers for a while. Have to say, JavaParser is the most developer-friendly one.

I got to know them from the gumtree project:

https://github.com/GumTreeDiff/gumtree
https://github.com/SpoonLabs/gumtree-spoon-ast-diff

In which it provides 3 backends for Java, each based on one parser (though the other two are not as mature as the one based on JDTParser).

In the Issues page of Spoon, there is also a question (https://github.com/INRIA/spoon/issues/1303) discussing the differences between it and JavaParser, in which they hightlight the "navigation between usage and declaration" feature (maybe that's because it's based on JDT).

> Here are some feasible alternatives: http://spoon.gforge.inria.fr/ (beware of the license), and I'm pretty sure someone wrote a wrapper for the JDT to make it easier to use.

**Comment by ftomassetti** [comment]
Well, I thought it was appropriated to answer to the thread on spoon

**Comment by pvojtechovsky** [comment]
Spoon is using Eclipse JDT compiler. Spoon let's compile java sources by JDT compiler, which produces JDT AST. Then spoon transforms that JDT compiler specific and complex AST to java developer friendly Spoon AST.

**Comment by Symbolk** [comment]
One question: in Eclipse JDTParser we can parse code fragments by setting the kind of code, it supports 4 kinds of code:    

> ASTParser.K_COMPILATION_UNIT
ASTParser.K_CLASS_BODY_DECLARATIONS)
ASTParser.K_EXPRESSION) 
> ASTParser.K_STATEMENTS)) 

```java
      ASTParser parser = ASTParser.newParser(8);
      // set the kind of the target code string
      parser.setKind(kind);
```
In this way, not only a complete compilation unit but also incomplete code fragments can be parsed, I want to ask: does JavaParser provide such a feature?

See also: https://www.programcreek.com/2012/08/parse-a-sequence-of-java-statements-by-using-jdt-astparser/

**Comment by ftomassetti** [comment]
> One question: in Eclipse JDTParser we can parse code fragments by setting the kind of code, it supports 4 kinds of code:
> 
> > ASTParser.K_COMPILATION_UNIT
> > ASTParser.K_CLASS_BODY_DECLARATIONS)
> > ASTParser.K_EXPRESSION)
> > ASTParser.K_STATEMENTS))
> 
> ```java
>       ASTParser parser = ASTParser.newParser(8);
>       // set the kind of the target code string
>       parser.setKind(kind);
> ```
> 
> In this way, not only a complete compilation unit but also incomplete code fragments can be parsed, I want to ask: does JavaParser provide such a feature?
> 
> See also: https://www.programcreek.com/2012/08/parse-a-sequence-of-java-statements-by-using-jdt-astparser/

Yes, you can just parse at whatever granularity level you want. And do symbol resolutions on that snippets.

**Comment by Symbolk** [comment]
> > One question: in Eclipse JDTParser we can parse code fragments by setting the kind of code, it supports 4 kinds of code:
> > > ASTParser.K_COMPILATION_UNIT
> > > ASTParser.K_CLASS_BODY_DECLARATIONS)
> > > ASTParser.K_EXPRESSION)
> > > ASTParser.K_STATEMENTS))
> > 
> > 
> > ```java
> >       ASTParser parser = ASTParser.newParser(8);
> >       // set the kind of the target code string
> >       parser.setKind(kind);
> > ```
> > 
> > 
> > In this way, not only a complete compilation unit but also incomplete code fragments can be parsed, I want to ask: does JavaParser provide such a feature?
> > See also: https://www.programcreek.com/2012/08/parse-a-sequence-of-java-statements-by-using-jdt-astparser/
> 
> Yes, you can just parse at whatever granularity level you want. And do symbol resolutions on that snippets.

Can you show me some documents or examples? Thanks!

**Comment by ftomassetti** [comment]
> > > One question: in Eclipse JDTParser we can parse code fragments by setting the kind of code, it supports 4 kinds of code:
> > > > ASTParser.K_COMPILATION_UNIT
> > > > ASTParser.K_CLASS_BODY_DECLARATIONS)
> > > > ASTParser.K_EXPRESSION)
> > > > ASTParser.K_STATEMENTS))
> > > 
> > > 
> > > ```java
> > >       ASTParser parser = ASTParser.newParser(8);
> > >       // set the kind of the target code string
> > >       parser.setKind(kind);
> > > ```
> > > 
> > > 
> > > In this way, not only a complete compilation unit but also incomplete code fragments can be parsed, I want to ask: does JavaParser provide such a feature?
> > > See also: https://www.programcreek.com/2012/08/parse-a-sequence-of-java-statements-by-using-jdt-astparser/
> > 
> > 
> > Yes, you can just parse at whatever granularity level you want. And do symbol resolutions on that snippets.
> 
> Can you show me some documents or examples? Thanks!

Sure, just take a look at the Javadoc for the [`JavaParser` class](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.7.0/com/github/javaparser/JavaParser.html).

There are methods such as:

* parseExpression
* parseImport
* parseAnnotation
* parseResource

etc.

**Comment by seafitliu** [comment]
i found a weakness of javaparser compare to eclipse JDT. 

they both have CompilationUnit class:
1, the CompilationUnit of eclipseJDT has method of getLineNumber, so the ast node line can be got easily
2, the CompilationUnit of java parser doesn't have the way to get ast node line. so the feature was missed.

am i right?   finally i use JDT instead of java parser.

**Comment by jlerbsc** [comment]
> The CompilationUnit of java parser doesn't have the way to get ast node line. so the feature was missed.

This is not entirely true. Since the CompilationUnit is considered as an AST node, it benefits from the getRange() method which allows you to obtain the position of a node.

Moreover, JP has several interesting features such as lexical preservation, symbol resolver...

**Comment by seafitliu** [comment]
Thanks for reply. 

The position only have line and column , I can’t find offset of entire file. Is there any way to get the offset info. JDT can get offset by getLineNumber of CU

**Comment by jlerbsc** [comment]
What do you mean by offset?

**Comment by jlerbsc** [comment]
Can you create a new issue for your question? Thanks.

**Comment by seafitliu** [comment]
> What do you mean by offset?

the code used JDT as followed: 

`CompilationUnit _cu;

	public AstVisitor(CompilationUnit cu, String filepath) {
		_cu = cu;
	}

	@Override
	public boolean visit(SimpleName node) {
		int offset = node.getStartPosition();    // the offset in the file byte stream. i can't find any method in JP
		int length = node.getLength();
                 int line = _cu.getLineNumber(node.getStartPosition());
                 int column =  _cu.getColumnNumber(node.getStartPosition()); 
		
		return true;
	}`
