### ISSUE TITLE
Ensure all tests are running on the build

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1924]
I suspect we could be missing some tests

**Comment by ftomassetti** [comment]
This should have high priority

**Comment by matozoid** [comment]
Luckily there is no high priority label.

**Comment by ftomassetti** [comment]
I am very confused.

Looking at logs of [this build](https://travis-ci.org/javaparser/javaparser/builds/456620744) I can see that tests are run in 6 blocks with this number of tests

* 3
* 11
* 908
* 3
* 11
* 805

If I run the tests in my IDE:

* Serialization has 11 tests, all passing
* core-testing has 1460 tests, 6 ignored, 4 failing
* solver-testing has 952 tests, all passing

**Comment by ftomassetti** [comment]
Looking at the logs, the two blocks of 3 tests correspond to UnicodeEscapeProcessingProviderTest, which is a test class written in core-testing with the new JUnit Jupiter framework

**Comment by ftomassetti** [comment]
The 6 ignored files are aboute the Jave10 validator and the LexicalPreservingPrinter.

**Comment by ftomassetti** [comment]
I suspect that mixing Jupiter and old tests confuses the build.

**Comment by ftomassetti** [comment]
I have no idea why ResolvedPrimitiveTypeTest are run and FindingAllFields are not

**Comment by matozoid** [comment]
I assume this is sufficiently fixed now.
