### ISSUE TITLE
"com.github.javaparser.ParseProblemException: Lexical error at" attempting to parse Unicode character '\u005c''

### ISSUE THREAD

**Issue by tibcoktredget** [javaparser/javaparser#1927]
Using javaparser-core-3.7.1.jar attempting to parse a JavaCC generated Java file that contains the line:

`        jjtn000.setValue(t.image.substring(t.image.indexOf('\u005c'') + 1, t.image.length() - 1));`

as the Unicode escape sequence \u005c is the code for the backslash character this is equivelant to:

`        jjtn000.setValue(t.image.substring(t.image.indexOf('\'') + 1, t.image.length() - 1));`

i.e. it is looking for the index of a single quote character.

The following exception is thrown:

`com.github.javaparser.ParseProblemException: Lexical error at line 1023, column 70.  Encountered: " " (32), after : "\')"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParserTokenManager.getNextToken(GeneratedJavaParserTokenManager.java:2797)
  com.github.javaparser.GeneratedJavaParser.jj_scan_token(GeneratedJavaParser.java:10184)
  com.github.javaparser.GeneratedJavaParser.jj_3R_162(GeneratedJavaParser.java:7977)
  com.github.javaparser.GeneratedJavaParser.jj_3R_99(GeneratedJavaParser.java:8023)
  com.github.javaparser.GeneratedJavaParser.jj_3_37(GeneratedJavaParser.java:8081)
  com.github.javaparser.GeneratedJavaParser.jj_3R_98(GeneratedJavaParser.java:8112)
  com.github.javaparser.GeneratedJavaParser.jj_3_31(GeneratedJavaParser.java:8578)
  com.github.javaparser.GeneratedJavaParser.jj_2_31(GeneratedJavaParser.java:5940)
  com.github.javaparser.GeneratedJavaParser.PrimaryExpression(GeneratedJavaParser.java:2963)
  com.github.javaparser.GeneratedJavaParser.PostfixExpression(GeneratedJavaParser.java:2862)
  com.github.javaparser.GeneratedJavaParser.UnaryExpressionNotPlusMinus(GeneratedJavaParser.java:2847)
  com.github.javaparser.GeneratedJavaParser.UnaryExpression(GeneratedJavaParser.java:2751)
  com.github.javaparser.GeneratedJavaParser.MultiplicativeExpression(GeneratedJavaParser.java:2639)
  com.github.javaparser.GeneratedJavaParser.AdditiveExpression(GeneratedJavaParser.java:2601)
  com.github.javaparser.GeneratedJavaParser.ShiftExpression(GeneratedJavaParser.java:2565)
  com.github.javaparser.GeneratedJavaParser.RelationalExpression(GeneratedJavaParser.java:2515)
  com.github.javaparser.GeneratedJavaParser.InstanceOfExpression(GeneratedJavaParser.java:2497)
  com.github.javaparser.GeneratedJavaParser.EqualityExpression(GeneratedJavaParser.java:2459)
  com.github.javaparser.GeneratedJavaParser.AndExpression(GeneratedJavaParser.java:2437)
  com.github.javaparser.GeneratedJavaParser.ExclusiveOrExpression(GeneratedJavaParser.java:2416)
  com.github.javaparser.GeneratedJavaParser.InclusiveOrExpression(GeneratedJavaParser.java:2395)
  com.github.javaparser.GeneratedJavaParser.ConditionalAndExpression(GeneratedJavaParser.java:2374)
  com.github.javaparser.GeneratedJavaParser.ConditionalOrExpression(GeneratedJavaParser.java:2353)
  com.github.javaparser.GeneratedJavaParser.ConditionalExpression(GeneratedJavaParser.java:2334)
  com.github.javaparser.GeneratedJavaParser.Expression(GeneratedJavaParser.java:2169)
  com.github.javaparser.GeneratedJavaParser.ArgumentList(GeneratedJavaParser.java:3481)
  com.github.javaparser.GeneratedJavaParser.Arguments(GeneratedJavaParser.java:3468)
  com.github.javaparser.GeneratedJavaParser.PrimarySuffixWithoutSuper(GeneratedJavaParser.java:3320)
  com.github.javaparser.GeneratedJavaParser.PrimarySuffix(GeneratedJavaParser.java:3269)
  com.github.javaparser.GeneratedJavaParser.PrimaryExpression(GeneratedJavaParser.java:2968)
  com.github.javaparser.GeneratedJavaParser.PostfixExpression(GeneratedJavaParser.java:2862)
  com.github.javaparser.GeneratedJavaParser.UnaryExpressionNotPlusMinus(GeneratedJavaParser.java:2847)
  com.github.javaparser.GeneratedJavaParser.UnaryExpression(GeneratedJavaParser.java:2751)
  com.github.javaparser.GeneratedJavaParser.MultiplicativeExpression(GeneratedJavaParser.java:2639)
  com.github.javaparser.GeneratedJavaParser.AdditiveExpression(GeneratedJavaParser.java:2601)
  com.github.javaparser.GeneratedJavaParser.ShiftExpression(GeneratedJavaParser.java:2565)
  com.github.javaparser.GeneratedJavaParser.RelationalExpression(GeneratedJavaParser.java:2515)
  com.github.javaparser.GeneratedJavaParser.InstanceOfExpression(GeneratedJavaParser.java:2497)
  com.github.javaparser.GeneratedJavaParser.EqualityExpression(GeneratedJavaParser.java:2459)
  com.github.javaparser.GeneratedJavaParser.AndExpression(GeneratedJavaParser.java:2437)
  com.github.javaparser.GeneratedJavaParser.ExclusiveOrExpression(GeneratedJavaParser.java:2416)
  com.github.javaparser.GeneratedJavaParser.InclusiveOrExpression(GeneratedJavaParser.java:2395)
  com.github.javaparser.GeneratedJavaParser.ConditionalAndExpression(GeneratedJavaParser.java:2374)
  com.github.javaparser.GeneratedJavaParser.ConditionalOrExpression(GeneratedJavaParser.java:2353)
  com.github.javaparser.GeneratedJavaParser.ConditionalExpression(GeneratedJavaParser.java:2334)
  com.github.javaparser.GeneratedJavaParser.Expression(GeneratedJavaParser.java:2169)
  com.github.javaparser.GeneratedJavaParser.ArgumentList(GeneratedJavaParser.java:3481)
  com.github.javaparser.GeneratedJavaParser.Arguments(GeneratedJavaParser.java:3468)
  com.github.javaparser.GeneratedJavaParser.PrimarySuffixWithoutSuper(GeneratedJavaParser.java:3320)
  com.github.javaparser.GeneratedJavaParser.PrimarySuffix(GeneratedJavaParser.java:3269)
  com.github.javaparser.GeneratedJavaParser.PrimaryExpression(GeneratedJavaParser.java:2968)
  com.github.javaparser.GeneratedJavaParser.PostfixExpression(GeneratedJavaParser.java:2862)
  com.github.javaparser.GeneratedJavaParser.UnaryExpressionNotPlusMinus(GeneratedJavaParser.java:2847)
  com.github.javaparser.GeneratedJavaParser.UnaryExpression(GeneratedJavaParser.java:2751)
  com.github.javaparser.GeneratedJavaParser.MultiplicativeExpression(GeneratedJavaParser.java:2639)
  com.github.javaparser.GeneratedJavaParser.AdditiveExpression(GeneratedJavaParser.java:2601)
  com.github.javaparser.GeneratedJavaParser.ShiftExpression(GeneratedJavaParser.java:2565)
  com.github.javaparser.GeneratedJavaParser.RelationalExpression(GeneratedJavaParser.java:2515)
  com.github.javaparser.GeneratedJavaParser.InstanceOfExpression(GeneratedJavaParser.java:2497)
  com.github.javaparser.GeneratedJavaParser.EqualityExpression(GeneratedJavaParser.java:2459)
  com.github.javaparser.GeneratedJavaParser.AndExpression(GeneratedJavaParser.java:2437)
  com.github.javaparser.GeneratedJavaParser.ExclusiveOrExpression(GeneratedJavaParser.java:2416)
  com.github.javaparser.GeneratedJavaParser.InclusiveOrExpression(GeneratedJavaParser.java:2395)
  com.github.javaparser.GeneratedJavaParser.ConditionalAndExpression(GeneratedJavaParser.java:2374)
  com.github.javaparser.GeneratedJavaParser.ConditionalOrExpression(GeneratedJavaParser.java:2353)
  com.github.javaparser.GeneratedJavaParser.ConditionalExpression(GeneratedJavaParser.java:2334)
  com.github.javaparser.GeneratedJavaParser.Expression(GeneratedJavaParser.java:2169)
  com.github.javaparser.GeneratedJavaParser.ArgumentList(GeneratedJavaParser.java:3481)
  com.github.javaparser.GeneratedJavaParser.Arguments(GeneratedJavaParser.java:3468)
  com.github.javaparser.GeneratedJavaParser.PrimarySuffixWithoutSuper(GeneratedJavaParser.java:3320)
  com.github.javaparser.GeneratedJavaParser.PrimarySuffix(GeneratedJavaParser.java:3269)
  com.github.javaparser.GeneratedJavaParser.PrimaryExpression(GeneratedJavaParser.java:2968)
  com.github.javaparser.GeneratedJavaParser.StatementExpression(GeneratedJavaParser.java:4052)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3721)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3896)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1643)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3816)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3677)
  com.github.javaparser.GeneratedJavaParser.IfStatement(GeneratedJavaParser.java:4183)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3729)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3896)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1643)
  com.github.javaparser.GeneratedJavaParser.SwitchEntry(GeneratedJavaParser.java:4169)
  com.github.javaparser.GeneratedJavaParser.SwitchStatement(GeneratedJavaParser.java:4141)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3725)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3896)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1643)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3816)
  com.github.javaparser.GeneratedJavaParser.TryStatement(GeneratedJavaParser.java:4716)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3765)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3896)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1643)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3816)
  com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1250)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:951)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:845)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:407)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:153)
  com.github.javaparser.JavaParser.parse(JavaParser.java:130)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:329)
  com.github.javaparser.JavaParser.parse(JavaParser.java:163)
  com.github.javaparser.JavaParser.parse(JavaParser.java:176)
  ...`

See also this related issue #1299 

And this discussion #1240

**Comment by matozoid** [comment]
Thanks, this issue is all the way in the core parser, so it's high priority.

**Comment by matozoid** [comment]
As I promised to @davidsusu, I'll fix this by adding an optional unicode preprocessor.

**Comment by matozoid** [comment]
Okay @tibcoktredget, give it a go.

**Comment by tibcoktredget** [comment]
Hi Danny, thanks very much for fixing this so quickly - I am out of the
office this week, so will test it out next week. Thanks again
Keith

On 21 Nov 2018, at 18:15, Danny van Bruggen <notifications@github.com>
wrote:

Closed #1927 <https://github.com/javaparser/javaparser/issues/1927>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/javaparser/javaparser/issues/1927#event-1980792886>,
or mute
the thread

**Comment by tibcoktredget** [comment]
Thanks very much for fixing this so quickly Danny - I have tested the new
3.8.0 version and by setting the option:

JavaParser.getStaticConfiguration().setPreprocessUnicodeEscapes(true);

I can now parse:

jjtn000.setValue(t.image.substring(t.image.indexOf('\u005c'') + 1,
t.image.length() - 1));

Without setting this option it still fails to parse the code.

Regards
Keith

**Comment by matozoid** [comment]
Cool! Be sure to read the Javadoc about the disadvantages of this setting.
