### ISSUE TITLE
Find association between MethodCallExpr and variable

### ISSUE THREAD

**Issue by xgulism1** [javaparser/javaparser#1929]
Hi,
I am trying to do the following:
There is a simple class (simplified version of Composite design pattern):
```
public class Clazz {
    private List<Clazz> clazzList = new ArrayList<>();

    public void doSomething() {
        for (Clazz clazz : clazzList) {
            clazz.doSomething();
        }
    }
}
```
Using JavaSymbolSolver I am able to find out, that the `clazz.doSomething();` is calling the `public void doSomething()` method using:
```
new VoidVisitorAdapter<Void>() {
    @Override
    public void visit(MethodCallExpr n, Void arg) {
        super.visit(n, arg);
        MethodUsage methodUsage = javaParserFacade.solveMethodAsUsage(n);
        ResolvedMethodDeclaration resolvedMethodDeclaration = methodUsage.getDeclaration();
        // resolvedMethodDeclaration is the declaration we were looking for
    }
}
```

The question is:
Is it possible to verify, that the `doSomething()` is called by the `clazz` variable, which is the element of the `clazzList` list-variable?
I imagine it could be done like this:
1. from `doSomething()` method call, get the variable `clazz`,
2. from the `clazz` variable, get declaration of `Clazz clazz` in the foreach,
3. get variable `clazzList` from the foreach,
4. get declaration of the `clazzList`.

However, i was unable to solve the first step - is it possible to associate the MethodCallExpr with the variable that calls the method (using JavaParser and/or JavaSymbolSolver)?

Or maybe there is a completely different way to accomplish this, so can someone help me how it could be done please (if possible)?

Thanks!

**Comment by ftomassetti** [comment]
You want to simply find the scope of the method call. Once you have found it you have to check it has the right class (`NameExpr` I think) and then resolve it. It should be able to tell you that it is a reference to the variable `Clazz clazz` defined in the foreach.

**Comment by xgulism1** [comment]
Thanks for the help!
I managed to get the scope using `getScope()`. However, I think I am still struggling with the next part. I think I am missing something very obvious. I am sorry I am new to JavaParser and JavaSymbolSolver. I have this:
```
new VoidVisitorAdapter<Void>() {
    @Override
    public void visit(MethodCallExpr n, Void arg) {
        super.visit(n, arg);

        // This gives me "clazz" which is calling the method
        Expression expression = n.getScope().orElse(null);

        if (expression != null) {
            ResolvedValueDeclaration resolved = javaParserFacade.solve(expression).getCorrespondingDeclaration();

            // This prints: JavaParserSymbolDeclaration{name='clazz', wrappedNode=clazz}
            System.out.println(resolved);

            // I don't know how to get the part defined in the foreach from here
        }
    }
}
```
So from there, is there a way to get to the foreach to get a reference to the `clazzList` please?
I could use `resolved.getType().asReferenceType();`, but I think it only tells me it is the reference to the class `Clazz` itself (not that it is defined in the foreach).
In the end, I am trying to find the `clazzList` part of the foreach. So is there anything I could try to get to the `clazzList` from here?

Edit:
I think I got it, I can use JavaParser again like this
```
JavaParserSymbolDeclaration resolvedSymbol = (JavaParserSymbolDeclaration) resolved;
resolvedSymbol.getWrappedNode().getParentNode().orElse(null).getParentNode().orElse(null).findAll(ForEachStmt.class)
```
to get the foreach loop.

From there the rest was easy.
Thank you very much!

**Comment by matozoid** [comment]
@xgulism1 `Optional` gets better with `map` and friends. I liked this article: https://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html
