### ISSUE TITLE
Clean up unicode preprocessor

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1930]
See  #1928

Specifically:
- the code has a lot of redundant stuff in it.
- it throws a runtime exception when a bad escape is encountered (like `\uz`). It should just pass those characters through. (Which is expected behaviour starting from Java 12, but is nice to have earlier too, because the bad escapes get passed into the parser which can produce a decent error instead of a runtime exception.)

**Comment by matozoid** [comment]
While solving this we should prepare for #1930.

**Comment by haumacher** [comment]
@matozoid can you have a look at 5ef8d93 with my proposal of unicode escape processing. I did a clean room re-implementation of the stuff. Refactoring / reverse engineering the JavaCC variant was too hard for me.

**Comment by matozoid** [comment]
Looks much more readable and well tested to me. Good work! Do open a PR if you want.
