### ISSUE TITLE
CompilationUnit-getPackageDeclaration fails when package not in first line

### ISSUE THREAD

**Issue by Chri-Ri** [javaparser/javaparser#1932]
Hi.
I've got a simple file ( `package-info.java` ):
```
@TypeDefs({@TypeDef(name = "ja_nein", typeClass = JaNeinTyp.class)})
package at.(please.enter.your.own.package).bo;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;
```

for this file the method getPackageDeclaration returns the string `'@TypeDef(name'`.
My assumption is that this is NOT the desired result.  ;)

Edit: Using version 3.6.18

**Comment by matozoid** [comment]
Interesting, thanks!

**Comment by matozoid** [comment]
Oh wait, I thought it wasn't parsing correctly :-)

The package is annotated with those annotations, and `toString()` is a pretty printer, so it prints the package declaration including its annotations.

What did you want to do?

**Comment by Chri-Ri** [comment]
Sorry, the result i posted was the result of trying to extract just the package name from the declaration (splitted at ' ' and returning second entry). this simply processing fails if there are annotations in the declaration. Now I've found in the JavaDoc what I was looking for: 
`PackageDeclaration.getName()` returns just what I wanted.
Sorry for bothering you.
I just didn't dig deep enough into the docs.

**Comment by matozoid** [comment]
It's okay, feel free to ask more questions :-) Good luck!
