### ISSUE TITLE
Blacklist all external libary classes

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javaparser#1934]
Hello,

I have developed a program that tests code projects of students. Now I want to prevent the students from using external libraries. I think there would be two solutions to accomplish this: Either blacklist all external library classes or whitelist all standard java library classes.

My question: Is there an easy way to determine if a (resolved) class (or method) is part of the standard java library?

Thanks in advance :)

**Comment by matozoid** [comment]
Well, I'm not really qualified to answer this, I just maintain a parser, but here goes: I think you can build an index of all classes in a JDK by parsing its source code, and that could be your whitelist. Maybe simply looking at the package would do too: `java.*` and `javax.*`.

**Comment by un0btanium** [comment]
Alright good enough :+1:
