### ISSUE TITLE
Get FieldDeclaration from ResolvedFieldDeclaration

### ISSUE THREAD

**Issue by wozuo** [javaparser/javaparser#1935]
Hi everyone,

I just stumbled upon a small problem. I would like to get the FieldDeclaration of a ResolvedFieldDeclaration. If I understand the documentation correctly, this should be possible using `FieldDeclaration fieldDeclaration = resolvedFieldDeclaration.asField();`. But it appears not to work, I get the following error message instead: `Error:(129, 81) java: incompatible types: com.github.javaparser.resolution.declarations.ResolvedFieldDeclaration cannot be converted to com.github.javaparser.ast.body.FieldDeclaration`. 

Is there another way to achieve my goal?

Thanks a lot and best regards,
Marc

**Comment by wozuo** [comment]
Ah never mind, the `asField()` method call is unnecessary (I'm not sure what it's use is?) but it's possible to get the FieldDeclaration by casting it to JavaParserFieldDeclaration and then calling `getWrappedNode()`.

**Comment by matozoid** [comment]
I think we added something for this recently, I think "toAst" or so? @ftomassetti ?

**Comment by ftomassetti** [comment]
We need to implent AssociableToAST in ResolvedFieldDeclaration. However the result could be surprising because a field in the AST can correspond to many resolved fields. One resolvedfield would correspond to a VariableDeclarator inside the AST node for a field declaration
