### ISSUE TITLE
CompilationUnit.tostring() ignores comments

### ISSUE THREAD

**Issue by emmanueldufour** [javaparser/javaparser#194]
using javaparser-core 2.2.2
 if I parse a file like

```
package something

/**
* Blah
*/
public class Blah(){}
```

Then calling `CompilationUnit.toString()` will not output the comment (same as `CompilationUnit.toStringWithoutComments()`

**Comment by matozoid** [comment]
The following code does output the comment, so I'm assuming this is fixed. Note that the supplied sample code had to be changed to be parseable.

```java
        CompilationUnit compilationUnit = JavaParser.parse("package something;\n" +
                "\n" +
                "/**\n" +
                "* Blah\n" +
                "*/\n" +
                "public class Blah{}");

        System.out.println(
        compilationUnit.toString());
```

**Comment by LQZYC** [comment]
CompilationUnit compilationUnit = JavaParser.parse("package com.xxx.ooo.dynamicclass;\n"
            + "\n"
            + "import java.util.Arrays;\n"
            + "import java.util.HashSet;\n"
            + "import java.util.Map;\n"
            + "import java.util.Set;\n"
            + "import java.util.HashMap;\n"
            + "import java.util.Date;\n"
            + "import java.util.function.Function;\n"
            + "import java.util.function.Supplier;\n"
            + "\n"
            + "/**\n"
            + "*\n"
            + "*  xxx ooo 的测试\n"
            + "*\n"
            + "* @author xxx\n"
            + "* @author ooo\n"
            + "*\n"
            + "* @since  2018年06月14号 Thu AM 09时41分59秒\n"
            + "*/\n"
            + "\n"
            + "public class Clz_XX_OO_20180614094159 {\n"
            + "}");

        System.out.println(
            compilationUnit.toString());

i also get this problem, the above code can show this bug  repetition

**Comment by matozoid** [comment]
Hi @LQZYC, that's probably another problem. I'm guessing the empty line between the comment and the class is causing this. Can you open a new issue for this?
