### ISSUE TITLE
Implement AssociableToAST in ResolvedFieldDeclaration

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#1940]
See #1935

**Comment by 4everTheOne** [comment]
Hello @ftomassetti, i think we can say this issue was fixed here https://github.com/javaparser/javaparser/commit/b96e84c26f49380bf984c1febacf4935aa998fb4.

**Comment by jlerbsc** [comment]
Not sure if we take into account this answer but I let @ftomassetti answer your question.

> However the result could be surprising because a field in the AST can correspond to many resolved fields. One resolvedfield would correspond to a VariableDeclarator inside the AST node for a field declaration

**Comment by 4everTheOne** [comment]
I can see what you mean. Do you think PR #3063 can help on that?

**Comment by jlerbsc** [comment]
But cannot validate the impact of your PR #3063 because i'm not experienced enough on JP but I feel that there is a modification of the public API which can impact other users/projects. @MysterAitch @matozoid can you give your opinion on this subject and PR #3063 ?

**Comment by jlerbsc** [comment]
This issue appears to have been resolved if not you can reopen it.
