### ISSUE TITLE
Are there Patchnotes?

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javaparser#1944]
Hello,

quick question about the releases: Are there some patchnotes about the releases somewhere? I sometimes wish there would be. I usually just take a look at the JavaParser book (_those damn crazy nastyass honey badgers_), if there is something new worth checking out.

I know making patchnotes is a whole science in itself and takes a lot of effort to create. But maybe only the major and minor versions and only mention new features that have been added (like the new way to use the SymbolSolver) or important changes that have been made (like the recent change of `ForeachLoop` to `ForEachLoop`). I would very much appreciate it :)

**Comment by matozoid** [comment]
Here are the patch notes: https://github.com/javaparser/javaparser/blob/master/changelog.md

Please tell us how to make these more discoverable, because people aren't seeing them :-(

**Comment by un0btanium** [comment]
Oh neat. Thats exactly what I wanted :+1: 

I usually expect them on the release page. Just adding the link like this (https://github.com/javaparser/javaparser/blob/master/changelog.md#version-371) would already be enough. Then the changelog does not have to be updated in two places and each release presents its own relevant link within the changelog.

And adding the link at the end of the Readme with a "Patchnotes" title would probably also be helpful for some.
