### ISSUE TITLE
JavaParser choking on multiple generic method calls on the same line

### ISSUE THREAD

**Issue by HoldYourWaffle** [javaparser/javaparser#1945]
(Part 2 of #1942)

I'm trying to parse some code using JavaParser, but it fails to resolve a method call involving multiple generic methods on a single line.
I could write a very long description of what this code looks like and how it fails, but since that isn't fun for anybody, I have created a small sample project that replicates my code structure in a *very* simplified way while still reproducing the error. You can find it [here](https://github.com/HoldYourWaffle/JavaParserGenericsChoke).

I've abstracted my code with the use of animals.
Some animals have hair, for which there is the `HairyAnimal` interface. Not all animals have the same type of hair, sheep have wool, dogs have fur, well you get the point. This is where the `HairType` interface comes in.
Finally we need to render the hair to the users screen, which is (unsurprisingly) done by the `HairTypeRenderer` ~interface~ abstract class*.
There's also a simple sheep implementation, using `HairTypeWool` and `WoolRenderer`.
<br>
Now for the actual choking code:
```java
sheep.getHairType().getRenderer().renderHair(sheep.getHairType(), sheep);
```
That line of code fails to resolve, triggering the following exception:
```
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to sheep.getHairType().getRenderer().renderHair(sheep.getHairType(), sheep)', cause='null'}
    at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:148)
    at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
    at TestJavaParser.testChoke(TestJavaParser.java:31)
```
After some investigation I found out that if I split out the call like this everything resolves just fine:
```java
HairType<?> hairType = sheep.getHairType();
HairTypeRenderer<?> hairTypeRenderer = hairType.getRenderer();
hairTypeRenderer.renderHair(hairType, sheep);
```
I did some more variations with varying degree of 'split-out'-ness, which can all be found inside [`MainClass.java`](https://github.com/HoldYourWaffle/JavaParserGenericsChoke/blob/master/src/main/java/main/MainClass.java). The actual parsing is done inside [`TestJavaParser.java`](https://github.com/HoldYourWaffle/JavaParserGenericsChoke/blob/master/src/test/java/TestJavaParser.java).

I hope my little farming example makes enough sense, otherwise I'd be happy to explain it better (or at least try to do so).

<br><br><br><br>
**: I have to use an abstract class with a proxy method here because I want to pass an instance of the to-be-rendered-hair to the (*singleton*) renderer of the corresponding type. 
Making `HairyAnimal` a generic class itself doesn't solve the problem, since sheep can have multiple colors of wool (to be more concrete: types can change dynamically). In the proxy method I can cast the `HairType` instance to the `HairTypeRenderer`'s generic-type (which should always match) and pass that on the the implementing class.
If none of that made any sense: I'm pretty sure it's not important, and it makes a lot more sense in the actual context of the code*

**Comment by matozoid** [comment]
That's a really great bug report, thanks!

**Comment by matozoid** [comment]
@HoldYourWaffle was this solved in the PR?

**Comment by HoldYourWaffle** [comment]
Which one? #1952 just added a workaround.

**Comment by matozoid** [comment]
Okay, it's still open then.

**Comment by jlerbsc** [comment]
I think this issue is located in MethodCallExprContext.solveMethodAsUsage(..) which replaces the return type of the method in certain situations, in particular in the case of the unbounded type. I'm trying to reproduce it with a simple test case but it looks like I managed to fix this problem after long hours of debugging with the provided test case. :-(
