### ISSUE TITLE
JSS can't resolve super-default method reference

### ISSUE THREAD

**Issue by HoldYourWaffle** [javaparser/javaparser#1949]
Found another issue. ([Sample project](https://github.com/HoldYourWaffle/JavaParserDefaultMethodChoke))
This one's quite simple, JSS is unable to solve a method call like this one:
```java
MyInterface.super.defaultMethod();
```

**Comment by ftomassetti** [comment]
This should not be too hard to solve, just a missing functionality

**Comment by matozoid** [comment]
@maartenc @HoldYourWaffle - anybody wants to give this a go?

**Comment by HoldYourWaffle** [comment]
I would, but I have absolutely no idea how to.

**Comment by matozoid** [comment]
Probably copy/paste some similar code into the place where the exception is thrown (if there is an exception?)

**Comment by MysterAitch** [comment]
This threw me a little as I'd not seen this before (allowing the default methods to be called explicitly).

More info for me/others who look at this again in the future: 
https://stackoverflow.com/a/19976615/429733

```java
public class ChildClass implements A, C {
    @Override    
    public void foo() {
       //you could completely override the default implementations
       doSomethingElse();
       //or manage conflicts between the same method foo() in both A and C
       A.super.foo();
    }
    public void bah() {
       A.super.foo(); //original foo() from A accessed
       C.super.foo(); //original foo() from C accessed
    }
}
```

**Comment by HoldYourWaffle** [comment]
I hadn't seen it before either, I was quite surprised when it popped up after throwing JSS at a big codebase.
