### ISSUE TITLE
Unambigous ambiguity call with <Void> generics and lambda's

### ISSUE THREAD

**Issue by HoldYourWaffle** [javaparser/javaparser#1950]
JSS can't resolve lambda ambiguities related to `<Void>` generics when there are method overloads like this:
```java
public void method(GenericClass<T> lambda) {}
public void method(NonGenericClass lambda) {}
```
As always there's a [sample project](https://github.com/HoldYourWaffle/JavaParserGenericVoidAmbiguity). I've added comments in-code explaining why certain calls are non-ambiguous though JSS thinks they are. I don't think it's necessary to repeat it here, it's pretty self-explanatory *(famous last words...)*
Behavior is identical for both `ReflectionTypeSolver` and `JavaParserTypeSolver`.

Another interesting thing I've noticed is that `@FunctionalInterface`'s take precedence over 'normal' interfaces. Pretty sure it's intentional, but it confused me for a moment when creating the tests.

**Comment by ftomassetti** [comment]
The very best and ideal thing would be a PR containing a failing test based on the sample project you defined

**Comment by HoldYourWaffle** [comment]
I'll create one sometime this week

**Comment by jlerbsc** [comment]
This issue is reproducible with the following simplified test case based on @HoldYourWaffle one.
In this case i'm not sure this is really an issue. This unit test fails with

    com.github.javaparser.resolution.MethodAmbiguityException: Ambiguous method call: cannot find a most applicable method:
    JavaParserMethodDeclaration{wrappedNode=public static <T> void method(Callable<T> lambda) {    }, typeSolver=com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver@229c6181}, 
    JavaParserMethodDeclaration{wrappedNode=public static void method(Runnable lambda) {    }, typeSolver=com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver@229c6181}	at     com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:576)


    public class Issue1950Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {

        TypeSolver typeSolver = new ReflectionTypeSolver(false);
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(config);

        String s = 
                "import java.util.concurrent.Callable;\n" +
                "class Foo { \n" +
                "  void foo() {\n" + 
                "     method(()->{});\n" +
                "  }\n" +
                "  public void method(Runnable lambda) {\n" + 
                "  }\n" + 
                "  public <T> void method(Callable<T> lambda) {\n" + 
                "  }\n" +
                "}";
        CompilationUnit cu = StaticJavaParser.parse(s);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        ResolvedMethodDeclaration resolved = mce.resolve();
        System.out.println(resolved.getParam(0).getType().describe());

    }
    }

**Comment by vnique** [comment]
I got the same problem when I use lambda's express.
