### ISSUE TITLE
Does Javaparser assumes the scope of FieldAccessExpr and MethodCallExpr is an object?

### ISSUE THREAD

**Issue by zelinzhao** [javaparser/javaparser#1955]
I am not a pro in Javaparser, so I read the API doc a lot. 
- In `FieldAccessExpr` doc: *Access of a field of an **object**. In person.name "name" is the name and "person" is the scope.* 
- In `MethodCallExpr` doc: *A method call on an **object**. circle.circumference() In a.<String>bb(15); a is the scope...*
So, I think the scope in `FieldAccessExpr` or `MethodCallExpr` is an object.<p>
However, if there is a static class or an enum:
- `FieldAccessExpr` is `class.static_field` or `enum.field`
- `MethodCallExpr` is `class.static_method`
The scope here is a **class**, not an **object**. <p>
I override the `visit(NameExpr)` method in my visitor class and the scope of `FieldAccessExpr` and `MethodCallExpr` will be passed into my `visit(NameExpr)` method naturally.<br>
I thought the scope is a value (object) after reading the doc. Therefore in the `visit` method,  I call the `resolve` method (of `NameExpr` class) on the scope directly. The `UnsolvedSymbolException` will be thrown here.<br>
Now, I know the scope could be an **object** or a **class**. So I think the doc is missleading.
Do we need to add special classes in Javaparser for `class.static_field` type `FieldAccessExpr` and `class.static_field` type `MethodCallExpr`? I don't know whether it's nenessary.

**Comment by matozoid** [comment]
Thanks! The main issue seems to be that the Javadoc for these nodes misses a case? (Thanks for reading the Javadoc, by the way.) In that case: it's not supposed to be misleading, so we can mention "object or class" instead. Would you like to make the PR?

Did I miss anything from your issue?

**Comment by zelinzhao** [comment]
Thanks for your response. Mentioning "object or class" in the Javadoc is nice. <br>
Should we add an interface method, maybe `boolean isScopeObject()`, in `NodeWithScope` and implement this method in `FieldAccessExpr` and `MethodCallExpr`?

**Comment by matozoid** [comment]
Let's see what @ftomassetti thinks.

**Comment by ftomassetti** [comment]
Obviously the AST cannot possibly now what the scope is, if it is an object or a class because they are not syntactically distinguishable. Therefore we cannot have special AST nodes. The ambiguity have to be resolved during symbol resolution and doing so it is a complicate process which requires figuring out which symbols are visible and what is their natures (are they classes? Are they variables?)

**Comment by ftomassetti** [comment]
Of course symbol resolution is handling static fields and methods access right now. It could have bugs but it is something it does

**Comment by matozoid** [comment]
Okay, so we answer "is the scope an object or a class" on a resolved type, not on the AST node itself.

**Comment by ftomassetti** [comment]
Yes, good point

**Comment by zelinzhao** [comment]
Thank you for your response.
