### ISSUE TITLE
How to parse a specified class?

### ISSUE THREAD

**Issue by widya10969** [javaparser/javaparser#1957]
Hi.
I want to parse the list of files entered from the folder to my project.
How to parse files in the class that use the concept of inheritance, namely superclass and subclass. But it ignores ordinary classes, interfaces and abstract classes.
I am new to JavaParser.
So, what would be the best approach?
If someone has a better/prettier solution, I would gladly appreciate it.

**Comment by HoldYourWaffle** [comment]
###### Disclaimer: I'm very new to JavaParser as well, so this might not be efficient at all

In my project I use code like this to parse all classes in a directory:
```java
//Initiate the parser
TypeSolver typeSolver = new ReflectionTypeSolver(false);
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);

Files.find(Paths.get("src", "main", "java"), Integer.MAX_VALUE, //get all files in the src/main/java directory
    (path, attr)->attr.isRegularFile() && path.toString().endsWith(".java")) //filter out non-java sources
    .map(JavaParser::parse) //this won't compile, you'll need to add your own error handling
    .forEach(compilationUnit -> {
        //do something interesting
}
```
I'm not sure what exactly you want to filter, but you can use `compilationUnit.findAll(ClassOrInterfaceDeclaration.class)` to find all class/interface declarations (who'd have thought....). You can then use the `resolve` method, which will give you an `ResolvedReferenceTypeDeclaration`. Keep in mind that you'll need to add the symbol solver as a dependency to your project (see the README for more information).

This is where my current knowledge of the JavaParser API ends, but you can probably use this object to find any superclasses and do some interesting stuff with it.

**Comment by matozoid** [comment]
@widya10969 - do read the book, it was written to get you started well. https://leanpub.com/javaparservisited

**Comment by widya10969** [comment]
@HoldYourWaffle @matozoid thanks for the solution, I'll try it.

**Comment by matozoid** [comment]
Closing because inactive.
