### ISSUE TITLE
UnsolvedSymbolException when using static final field from inherited interface

### ISSUE THREAD

**Issue by maartenc** [javaparser/javaparser#1963]
Hi,

consider the following example:

```
JDialog dialog = ...;
dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
```

when trying to resolve the `JDialog.DISPOSE_ON_CLOSE` expression, an UnresolvedSymbolException is thrown. This happens because the DISPOSE_ON_CLOSE is not a direct field of the JDialog class, but is a field of the WindowConstants interface which is implemented by JDialog.

I have it fixed on a local checkout of the project, I'll try to create a PR for this.

Maarten

**Comment by matozoid** [comment]
Great!

**Comment by maartenc** [comment]
Thanks for merging the PR :-)
