### ISSUE TITLE
Add a toString(organizeImports) method

### ISSUE THREAD

**Issue by cdietrich** [javaparser/javaparser#198]
I'd like to see a toString(boolean organizeImports) method.

**Comment by ftomassetti** [comment]
Can you give more details? What this method should do? What organizeImports are?

**Comment by cdietrich** [comment]
it should basically do what organize imports in eclipse does

input

```
package abc;
@dummy.MyIf
class Test extends x.y.z.Test {
}
```

output

```
package abc;
import dummy.MyIf
@MyIf
class Test extends x.y.z.Test {
}
```

**Comment by ftomassetti** [comment]
I see, however I do not think this is something can be done in JavaParser because it would require to solve symbols I think, while JavaParser simply build an AST

**Comment by cdietrich** [comment]
so the parser still uses heuristics at some places where one can only know at bind time what is a type and what not?

**Comment by cdietrich** [comment]
i just gave it a try with a bit more complex example and saw it will not work indeed

**Comment by ftomassetti** [comment]
We could to that in [java-symbol-solver](https://github.com/ftomassetti/java-symbol-solver) which is a symbol solver built on top of JavaParser

**Comment by cdietrich** [comment]
i will have a look at that.

**Comment by cdietrich** [comment]
our current jdt based solution uses naming conventions instead of bind to distinct typenames and fieldnames etc

**Comment by ftomassetti** [comment]
I am not sure I get it, could you please add more details?

**Comment by cdietrich** [comment]
if you have a method like

```
public void doSth() {
    a.b.C.d();
}
```

we use a heuristic to find out that a.b.C is a type and not a chain of field calls with the name C breaking java naming conventions

**Comment by ftomassetti** [comment]
I missed the answer. Yes it works... until people respect naming conventions and it is definitely much easier to do :)

**Comment by SmiddyPence** [comment]
Re-closing, beyond the scope of the project.
