### ISSUE TITLE
Comparing the type parameters when there are LazyType objects

### ISSUE THREAD

**Issue by zelinzhao** [javaparser/javaparser#1983]
I use Javaparser to analyze the following code.
```
public abstract class AbstractClass<E> {
	abstract public void method(Father<E> father);
}

public class Father<E> {
	E father;
	public Father(E father){
		this.father=father;
	}
}
public class Example extends AbstractClass<Integer>{
	public static class Son extends Father<Integer>{
		public Son(Integer father) {
			super(father);
		}
		int son;
	}

	@Override
	public void method(Father<Integer> father) {
        //MethodCallExpr here
		method((Son)father);
	}
	public boolean method(Son son) {
		return true;
	}
}
```
The code is actually from Tomcat8 and I change and remove some code for simplification.

The problem is that, I use Javaparser to parse MethodCallExpr `method((Son)father);` and call `resolve()` method on this MethodCallExpr. Javaparser then tries to figure out which `method` is called in this MethodCallExpr, `void method` or `boolean method`. Javaparser compares the type parameters in `compareConsideringTypeParameters` method in `ResolvedReferenceType` class.

The `compareConsideringTypeParameters` method calls `typeParametersValues()` on `boolean method(Son son)` to get the type parameter of `Son` class, and returns a `LazyType` object, whose `concrete` is `Integer`.

In the following comparison, the type parameters of `Father<Integer>` and `Son` are different. However, the two type parameters are both `Integer` and they should be equivalent.

I think we can compare the two type parameters here via class name.
```
    if(thisParam.describe().equals(otherParam.describe()))
    	return true;
```
I tried this locally and the Javaparser works as expected.

I don't know whether this is a real bug or Javaparser is designed in this way.
I will make a PR so that you can review the code. And there may be a better way to fix this if this is a real bug.

**Comment by jlerbsc** [comment]
I think that [ABANDONNED] means not to be released. If this this is not the case you are free to reopen this PR.
