### ISSUE TITLE
Javaparser treats full class name in FieldAccessExpr as FieldAccessExpr instead of a class?

### ISSUE THREAD

**Issue by zelinzhao** [javaparser/javaparser#1985]
Hi, I have another problem when using Javaparser to parse a FieldAccessExpr. 

If I have a class:
```
package this.is.a.package
enum example{
    one, two;
}
```
If I access the enum constant via the full class name in another class, like `this.is.a.package.example.one`, (the `this.is.a.package.example` is full class name and `one` is a field), and use Javaparser to parse this field access expr, Javaparser can't solve symbol `this.is.a.package.example`.

Javaparser thinks `this.is.a.package.example` is a FieldAccessExpr and fails to solve this FieldAccessExpr.

Does anyone know how to fix this? Thanks.

**Comment by jlerbsc** [comment]
This issue seems to be resolved 

     class Issue1985Test extends AbstractResolutionTest {

    @Test()
    void test() throws IOException {
        Path rootSourceDir = adaptPath("src/test/resources/issue1985");

        String src = 
                "import foo.Example;\n" +
                "public class Bar {\n" +
                "  public void m() {\n" +
                "    Example v1 = Example.one;\n" + 
                "    Example v2 = foo.Example.one; \n" +
                "  }\n" +
                "}";

        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new JavaParserTypeSolver(rootSourceDir.toFile())));
        StaticJavaParser.setConfiguration(config);

        StaticJavaParser.setConfiguration(new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new JavaParserTypeSolver(rootSourceDir.toFile()))));
        CompilationUnit cu = StaticJavaParser.parse(src);

        List<VariableDeclarationExpr> vdes = cu.findAll(VariableDeclarationExpr.class);

        vdes.forEach(vde -> assertEquals("foo.Example",vde.calculateResolvedType().describe()));
        
    }
    }
