### ISSUE TITLE
anonymous class broken when statement is set as new method body

### ISSUE THREAD

**Issue by signed** [javaparser/javaparser#1999]
The following test fails when I run it as part of [MethodDeclarationTransformationsTest](https://github.com/javaparser/javaparser/blob/master/javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/transformations/ast/body/MethodDeclarationTransformationsTest.java) on current head.
```
    @Test
    public void replaceBodyShouldNotBreakAnonymousClasses() {
        MethodDeclaration it = consider("public void method() { }");
        it.getBody().ifPresent(body -> {
            Statement statement = JavaParser.parseStatement("Object anonymous = new Object() {\n" +
                    "};");
            NodeList<Statement> statements = new NodeList<>();
            statements.add(statement);
            body.setStatements(statements);
        });

        String expected = "public void method() {\n" +
                "    Object anonymous = new Object() {\n" +
                "    };\n" +
                "}";
        assertTransformedToString(expected, it);
    }
```

**Comment by ftomassetti** [comment]
Ok, this represents a new test that should be added, right? I will prepare a PR with this test. Thank you for submitting it.

**Comment by ftomassetti** [comment]
To me the issue seems that we do not have a way to represent an empty body for the anonymous class

**Comment by ftomassetti** [comment]
Proposing a PR in #2000

**Comment by signed** [comment]
Thank you for looking into it.

**Comment by ftomassetti** [comment]
My pleasure
