### ISSUE TITLE
Keep formatting of parsed file

### ISSUE THREAD

**Issue by l0rinc** [javaparser/javaparser#2005]
Given the following Kotlin snippet (to avoid String concats in example)
```kotlin
JavaParser.parse("""
package com.lorinc.pap.demo;

import a;

import static b;
    
public class Formatting {
  public static void main(String[] args) {
    // line 1

    // line 3
  }
}
""")
```

will result in:
```java
package com.lorinc.pap.demo;

import a;
import static b;

public class Formatting {

    public static void main(String[] args) {
    // line 1
    // line 3
    }
}
```
i.e. 
* empty lines were trimmed between imports and method lines
* new line was added after class declaration
* indentation of 2 spaces was changed to 4
* comments were unindented (adding any non-comment line to the method will re-indent the comments, too)

**Comment by ftomassetti** [comment]
Are you using the pretty printer? I think it is the default. You can keep the original formatting using the LexicalPreservingPrinter

**Comment by l0rinc** [comment]
Hey @ftomassetti, thanks for the hint.
Unfortunately that seems even worse than plain `toString`:
```Kotlin
LexicalPreservingPrinter.print(JavaParser.parse("""package com.lorinc.pap.demo;

import a;

import static b;

public class Formatting {
  public static void main(String[] args) {
    // line 1

    // line 3
  }
}

"""))
```
->
```java
package com.lorinc.pap.demo;

import a;
import static b;

public class Formatting {    

public static void main(String[] args) {
}
}
```

In addition to the previous problems this one has:
* unindented method
* removed all comments

**Comment by ftomassetti** [comment]
I suspect that the problem is that the LexicalPreservingPrinter should be setup up _before_ parsing. The fact is that while parsing we need to preserve the lexical information that are typically useless in an AST. 

You can read more about the LexicalPreservingPrinter and how it works in this [article I wrote about its implementation](https://tomassetti.me/lexical-preservation-javaparser/).

I also suggest taking a look at the [book on JavaParser](https://leanpub.com/javaparservisited), which can be downloaded for free. It should have the explanations and examples about using the lexical preserving printer.

If you are in an hurry you can take a look at the method [setup](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.9.0/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinter.html#setup(N)) of the LexicalPreservingPrinter

**Comment by l0rinc** [comment]
Thank you for your quick replies @ftomassetti :)

Unfortunately the examples in https://tomassetti.me/lexical-preservation-javaparser seem a bit outdated and don't compile anymore.

Following the doc for `LexicalPreservingPrinter#setup` however seems to solves the issue, thanks!
> Prepares the node so it can be used in the print methods. The correct order is:
>* Parse some code
>* Call this setup method on the result
>* Make changes to the AST as desired
>* Use one of the print methods on this class to print out the original source code with your changes added

i.e. 

```java
String originalCode = "package com.lorinc.pap.demo;\n" +
    "\n" +
    "import a;\n" +
    "\n" +
    "import static b;\n" +
    "\n" +
    "public class Formatting {\n" +
    "  public static void main(String[] args) {\n" +
    "    // line 1\n" +
    "\n" +
    "    // line 3\n" +
    "  }\n" +
    "}";
CompilationUnit cu = JavaParser.parse(originalCode);
CompilationUnit lpp = LexicalPreservingPrinter.setup(cu);
System.out.println(LexicalPreservingPrinter.print(lpp));
```

So the only question that remains is how do I add newlines via the API?

**Comment by matozoid** [comment]
That's a feature request, not a question :-)

Theoretically you have access to all the tokens produces when you parsed the file (in tokenRange) but the lexical preserving printer has its own copy of those.

If all you want to do is mess with new lines, you could insert them in the token ranges of the nodes where you want them, then print out the complete list of tokens.

**Comment by l0rinc** [comment]
Thank you, I'll try that.

**Comment by Symbolk** [comment]
I restore the original indentation with the begin column of Range, which is available for most nodes.

**Comment by rohitsureka** [comment]
I'm running into an issue where I'm trying to use the LexicalPreservingPrinter after altering the AST and it throws an exception
```
Exception in thread "main" java.lang.Error: Could not parse : java.lang.IllegalArgumentException: fromIndex(14) > toIndex(10)
	at java.util.SubList.<init>(AbstractList.java:624)
	at java.util.AbstractList.subList(AbstractList.java:484)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator$CalculatedSyntaxModel.sub(LexicalDifferenceCalculator.java:44)
	at com.github.javaparser.printer.lexicalpreservation.DifferenceElementCalculator.calculate(DifferenceElementCalculator.java:123)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculateListReplacementDifference(LexicalDifferenceCalculator.java:110)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListReplacement(LexicalPreservingPrinter.java:280)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listReplacement(PropagatingAstObserver.java:82)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementReplaced$3(NodeList.java:474)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.notifyElementReplaced(NodeList.java:474)
	at com.github.javaparser.ast.NodeList.set(NodeList.java:147)
	at com.github.javaparser.ast.NodeList.set(NodeList.java:47)
	at com.github.javaparser.utils.Utils.replaceElementByObjectIdentity(Utils.java:232)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1077)
```
It works fine when I try to not use the LexicalPreservingPrinter and simply do
```
compilationUnitObject.toString()
```
ofcourse in that case, it doesn't preserve my formatting. Has anyone run into an exception with a similar stack trace / use case. I can help provide a minimalistic test case for the same if thats helpful

**Comment by matozoid** [comment]
@Symbolk and @rohitsureka - please don't report new issues as comments on an old issue. They will get lost.

**Comment by rohitsureka** [comment]
@matozoid Created https://github.com/javaparser/javaparser/issues/2293
