### ISSUE TITLE
check if class is abstract

### ISSUE THREAD

**Issue by andreeasgit** [javaparser/javaparser#2020]
Hello,

How can I check if a class is abstract using javaparser/javasymbolsolver?
If this question was already asked, please redirect me to it.

Thanks!

**Comment by matozoid** [comment]
Hi! I'm trying to think of a case where a class is abstract, but does not have the `abstract` modifier... If there is no such case, just parse a file look at the `ClassOrInterfaceDeclaration`s and check `isAbstract`.

**Comment by andreeasgit** [comment]
This is exactly the answer I was expecting! Checked it and it works.

Yes, indeed. An abstract class always has the abstract modifier. I didn't knew how to find this using javaparser, but I was pretty sure it can give me this information. 

Thank you!

**Comment by matozoid** [comment]
Glad to help!
