### ISSUE TITLE
How to get Compilation Unit given `Class` object and package name?

### ISSUE THREAD

**Issue by MarioIshac** [javaparser/javaparser#2021]
I have a `Class` object and the package name of said class. However, I do not have the source itself. Is there anyway to get a `CompilationUnit` given these? I can assume that the class represented by the `Class` object is guaranteed to be the only class in the source file.

**Comment by matozoid** [comment]
Hi! Wrong tool, I'm afraid. Javaparser-core is just a parser for Java source code, no other inputs possible. Javaparser-symbol-solver can deal with class files and jars etc, but only as a way to solve symbols.

Either access the class with some byte code library to get the information you need, or reverse engineer the source code and run it into JavaParser.
