### ISSUE TITLE
How to replace every generic type use with a Visitable?

### ISSUE THREAD

**Issue by MarioIshac** [javaparser/javaparser#2026]
Let's say I have this method:
`
<T> T doSomething(T parameter) {
     T localVariable = null; 
}
`

I can visit two types of nodes: `TypeParameter` and `VariableDeclaration`. Visiting `TypeParameter` will allow me to change the type of `T parameter` but not `T localVariable`, Visiting `VariableDeclaration` will allow me to change the type of both `T Parameter` and `T localVariable` but not the return type of the method.

There is `ClassOrInterfaceType` that captures a use of a class in all contexts (parameter, class declaration, return type, etc.) Is there something similar to that for generic types? I'd prefer to visit one type of node in order to access the return type, parameters, instance variables, local variables, etc. that all have type `T`. Reason is that I want to replace `T` in all these contexts with a primitive type.

**Comment by matozoid** [comment]
Hi! There are a lot of interfaces implemented by the various nodes. Try using:
- https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/nodeTypes/NodeWithTypeParameters.java
- Node.findAll

Let me know if that helps.

**Comment by MarioIshac** [comment]
> Hi! There are a lot of interfaces implemented by the various nodes. Try using:
> 
>     * https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/nodeTypes/NodeWithTypeParameters.java
> 
>     * Node.findAll
> 
> 
> Let me know if that helps.

Visiting all nodes that extend `NodeWithTypeParameters` would not visit the types of local and instance variables that have a type `T`. It would visit the types of local and instance variables of type `A<T>`, where `A` is any class, but I need to extend this visiting to `T` as well.

**Comment by matozoid** [comment]
Ah, I think I get it now.

To the parser, the T in `T varname;` just looks like a normal type, so you will need to have some additional logic. Either you write it yourself: something like "what are the type parameters of this class/method, and do they match with this type name?" or maybe the symbol solver is of use here. @ftomassetti ?

**Comment by ftomassetti** [comment]
Yes, ideally the symbol solver should be able to figure out that it is pointing to a type variable. Without symbol solving `List` and `T` are both names used as types. There is no way the parser alone could distinguish them

**Comment by matozoid** [comment]
Ideally? There is no way to see this right now?

**Comment by ftomassetti** [comment]
Bad choice of words. I expect this to work right now, I just did not double check it with the current version
