### ISSUE TITLE
Any examples for JsonSerializer/Deserializer ?

### ISSUE THREAD

**Issue by jessrix** [javaparser/javaparser#2029]
Hi . I want to serialize and deserialize some AST Nodes to save them for later access . I currently use JsonPrinter which is deprecated and not complete and i can't get jsonserializer to work , any examples on how to use these? thanks

**Comment by matozoid** [comment]
Hi! Right now only the test cases:
https://github.com/javaparser/javaparser/blob/master/javaparser-core-serialization/src/test/java/com/github/javaparser/serialization/JavaParserJsonSerializerTest.java
https://github.com/javaparser/javaparser/blob/master/javaparser-core-serialization/src/test/java/com/github/javaparser/serialization/JavaParserJsonDeserializerTest.java

What's the problem exactly?

**Comment by jessrix** [comment]
Oh i see , thanks
