### ISSUE TITLE
FieldAccessExpr without 'this'?

### ISSUE THREAD

**Issue by LHommeDeBat** [javaparser/javaparser#2030]
Hello,

I have a question about the 'FieldAccessExpr'-Objects. My issue is the following:

I want to remove unused, private class variables. For that I need to find a way to check my class where my class variable is used. I figured out that I should use the "FieldDeclaration" and "FieldAccessExpr" for that. However, it seems that the "FieldAccessExpr" are only those expressions that contain a "this". For example:

**Test-Class:**

        private int a;
	
	public void setA(int a) {
		this.a = a;
	}
	
	public int getA() {
		return a;
	}
	
	public int getThisA() {
		return this.a;
	}

**My code:**

                CompilationUnit cu = LexicalPreservingPrinter.setup(JavaParser.parse(variablePath));

		// Get all fields
		List<FieldDeclaration> fields = cu.findAll(FieldDeclaration.class);
		List<FieldAccessExpr> exprs = cu.findAll(FieldAccessExpr.class);

		// Iterate fields
		for (FieldDeclaration field : fields) {
			// Get field variables
			System.out.println("Found field '" + field + "' at line: " + field.getBegin().get().line);
		}
		// Iterate field access expressions
		for (FieldAccessExpr expr : exprs) {
			System.out.println("Found expr '" + expr + "' at line: " + expr.getBegin().get().line);
		}

The FieldDeclaration list does return me all the class variables with the help of "field.getVariables()", however the "FieldAccessExpr" list only returns me "this.a" from the methods "setA" and "getThisA", but not the "a" from the method "getA" even though the "a" accesses my field the same way as the "this.a" from the method "getThisA". Is this some sort of bug or is the "a" from "getA" not a "FieldAccessExpr", but an entirely different object?

**Comment by matozoid** [comment]
It's a different object. Here, read http://javaparser.org/inspecting-an-ast/ so you can always figure out what AST is being produced for a piece of code.

**Comment by LHommeDeBat** [comment]
> It's a different object. Here, read http://javaparser.org/inspecting-an-ast/ so you can always figure out what AST is being produced for a piece of code.

Thank you for the fast answer! I will close the issue.
