### ISSUE TITLE
Parsing Methods of Anonymous Classes

### ISSUE THREAD

**Issue by marc-schweig** [javaparser/javaparser#2031]
I am using a JavaParserTypeSolver and a ReflectionTypeSolver iterating over all MethodDeclarations in a CompilationUnit.

What do I have to do in order to resolve methods (e.g. to get their signature) contained in anonymous classes correctly?

This seems to be releated to #1599. However I was not able to find a solution, yet. Has this been resolved?

**Comment by matozoid** [comment]
Awaiting a fix for #1599

**Comment by jlerbsc** [comment]
The issue #1599 is closed so this issue is probably resolved if not you are free to open a new issue and provide a simplified test case.
