### ISSUE TITLE
UnsupportedOperationException thrown after setting acceptIncompleteList=true

### ISSUE THREAD

**Issue by villadora** [javaparser/javaparser#2033]
https://github.com/javaparser/javaparser/blob/cb194db28ea321862242bd2472cd5d25011633a5/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java#L230

Here `UnsupportedOperationException` is thrown out even when `acceptIncompleteList=true`.
as `getCorrespondingDeclaration` called on unsolved `implementedDeclRef` later.

I think here should be another if branch to ignore unsolved `implementedDeclRef`, if acceptIncompleteList is _true_.

**Comment by matozoid** [comment]
Thanks! Do you think you can make the change yourself?

**Comment by villadora** [comment]
> Thanks! Do you think you can make the change yourself?

sure, just wonder how to add unit tests for this

**Comment by MysterAitch** [comment]
Closing this issue as it seems to no longer apply to the current code.

_( #2033 seems to have been fixed in dea27fa )_
