### ISSUE TITLE
Coveralls reports not updating

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2039]
Hi,

I was taking a cursory look at #820 and noticed that the coveralls test coverage reports haven't been run/updated since Nov 2018. 

https://coveralls.io/github/javaparser/javaparser

**Comment by matozoid** [comment]
Thanks, that might explain the constant low coverage.

**Comment by matozoid** [comment]
Aha
`[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project javaparser-parent: Execution default-cli of goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report failed: A required class was missing while executing org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report: javax/xml/bind/DatatypeConverter`

**Comment by matozoid** [comment]
Aha
https://github.com/trautonen/coveralls-maven-plugin/issues/112
A blocking issue for Java 9 with two open PR's with fixes, but still not pulled and released for two years and running :-/ @trautonen must be VERY busy.

I'll try the ugly workaround.

**Comment by matozoid** [comment]
Thanks, we're back at over 60% coverage like it used to be :-)
