### ISSUE TITLE
How Could I access separately the Body of Each If and else if and else block?

### ISSUE THREAD

**Issue by yogeshjoshi** [javaparser/javaparser#2046]
How could i access body of each "if" and "else if" and "else" block including condition also.
I have tried taking help from issue #946 but couldn't get any help.

GIVEN Code ... Which needs to be parsed
```
if (variable.toLowerCase().equals(variable1.toLowerCase().trim()) && !var.toLowerCase().equals(var1.toLowerCase().trim())) {
   int a =2;
    if (aname.toLowerCase().contains("check") || aname.toLowerCase().contains("first choice")) {
        a.setType("------");
    } else if (bname.toLowerCase().contains("hello")) {
        a.setType("++++");
    } else if (c.toLowerCase().contains("market")) {
        a.setType("*****");
    }
    break;
}
```

What I want ..
Body of each if (and else if and else) including condition also. How could i get it?

Output expected ...
-----------------------------------------------------------------------------------------------------------
```
 if (aname.toLowerCase().contains("check") || aname.toLowerCase().contains("first choice")) {
        a.setType("------");
    } 
```
-----------------------------------------------------------------------------------------------------------
```
else if (bname.toLowerCase().contains("hello")) {
        a.setType("++++");
    }
```
------------------------------------------------------------------------------------------------------------
```
 else if (c.toLowerCase().contains("market")) {
        a.setType("*****");
    }
```
-------------------------------------------------------------------------------------------------------------
and of course all input also would be part of output.

How could i achieve above output?

What I have tried?

```
   public void visit(IfStmt n, List<String> ifCondition) {
		    if(!n.getCondition().toString().contains("robot")
					   && !n.getCondition().toString().contains("option")
					   && !n.getCondition().toString().contains("python")
					   && !n.getCondition().toString().contains("Script")
					   && (n.getCondition().toString().contains("equals")
							|| n.getCondition().toString().contains("contains") 
							|| n.getCondition().toString().contains("LowerCase")
							|| n.getCondition().toString().contains("matches"))) {
//These Condition are for some other filtering .. You could ignore this	 
			 System.out.println("-----------------------------------");
			 System.out.println(n);
			 System.out.println("-----------------------------------");
			 List<IfStmt> parent = n.getChildNodesByType(IfStmt.class);
			 for(IfStmt node:parent){
				 System.out.println(node);
				 if(node.getElseStmt().isPresent()){
					 if(node.getElseStmt().get() instanceof IfStmt){
						 
					 }else{
						 System.out.println(node);
					 }
				 }
				visit(node,ifCondition);
			 }
		
	}

```

**Comment by yogeshjoshi** [comment]
The above .. 
"if" condition i'm trying to parse from the JAVA File, there might other if condition could be in file also.

Output from what i did ... Not giving me expected what i want.

the output i'm getting on execution of code ... is in format of ..
```
if (aname.toLowerCase().contains("check") || aname.toLowerCase().contains("first choice")) {
a.setType("------");
} else if (bname.toLowerCase().contains("hello")) {
a.setType("++++");
} else if (c.toLowerCase().contains("market")) {
a.setType("*****");
}
```
---------------------------------------------------------------------------------------------------------
```
 if (bname.toLowerCase().contains("hello")) {
a.setType("++++");
} else if (c.toLowerCase().contains("market")) {
a.setType("*****");
}
```
--------------------------------------------------------------------------------------------------------
```
if (c.toLowerCase().contains("market")) {
a.setType("*****");
}
```
------------------------------------------------------------------------------------------------------

But I want each block separately .. Help on this/

**Comment by MysterAitch** [comment]
Your posts are extremely difficult to read - try wrapping each codeblock in back-ticks like this. More information can be found at https://guides.github.com/features/mastering-markdown/ .

````
```java
// code goes here
``` 
````

That said, this might get you some of the way there to exploring the if statements/blocks:

```java
    Node parentNode = null;
    Node grandParentNode = null;
    
    if(ifStmt.getParentNode().isPresent()) {
        parentNode = ifStmt.getParentNode().get();
        if(parentNode.getParentNode().isPresent()) {
            grandParentNode = parentNode.getParentNode().get();
        }
    }
    
    if(ifStmt.getParentNode().isPresent() && (parentNode instanceof IfStmt || grandParentNode instanceof IfStmt)) {
        System.out.println("## ELSE IF: if(" + ifStmt.getCondition() + ") {");
    } else {
        System.out.println("## IF: if(" + ifStmt.getCondition() + ") {");
    }
    
    System.out.println("## THEN: \n" + ifStmt.getCondition() + "\n");
    
    if(ifStmt.hasElseBlock() || ifStmt.hasElseBranch() && !(ifStmt.getElseStmt().get() instanceof IfStmt)) {
        System.out.println("## ELSE \n" + ifStmt.getElseStmt());
    }
```

**Comment by yogeshjoshi** [comment]
Hi , I have updated the my comments.
The Code provided by you still not works as expected.
still not able to get each block(IF, else if, else ) statement as different block.


The Java File may contains other IF and Else IF and ELSE condition in any manner.(all permutations can be there , i.e nested or any permutations of IF and Else And Else IF condition).
I want each "IF" and "Else IF" and "Else" as a separately  block(Print separately).

**Comment by matozoid** [comment]
Hi! Quick ideas (no time for more)

- you're not going to get JavaParser to output "else ..." because that is not valid Java.
- if you want to get rid of the else-part, clone the if statement and remove the else from it before printing.

**Comment by yogeshjoshi** [comment]
It has been solved by using ModifierVisitorAdapter. But still couldn't be able to get 'else part'. Thanks for your contribution. Closing this issue.

**Comment by matozoid** [comment]
Okay!

I just noticed that this sample works with `if` and `else` a lot, by the way: https://github.com/javaparser/javaparser-maven-sample/blob/master/src/main/java/com/yourorganization/maven_sample/LogicPositivizer.java
