### ISSUE TITLE
Low level Token usage

### ISSUE THREAD

**Issue by sebkur** [javaparser/javaparser#205]
I would like to perform some rather low level operations on Java source code for which I need access to the tokens that the parser encounters when building the syntax tree.

I need this, because I am creating views of source files with highlighting and links, but need to keep the original formatting of the code intact. I know, there is the `DumpVisitor` for pretty printing, but I think it is not possible to keep the original formatting of the code using it.

Also, using a custom `VoidVisitorAdapter` extension doesn't really help here, because I would end up doing a lot of parsing work that the `ASTParser` already did before. For example, I could use a `Visitor` to modify `ReturnStmt` nodes, however that node's `begin` and `end` variables reference the whole term 'return <expression>'

I already solved this for my personal use a few years ago within a fork of Júlio Vilmar Gesser's original code here: https://github.com/sebkur/java-parser

However, as you know the original code does only support Java 1.5 code. Now I discovered you already did a good job extending his code for the latest evolutions of the language.

I created a fork of your project and made some alterations to make access to the tokens available. You can see the changes here: https://github.com/sebkur/javaparser/commit/2a70a65cac3569902919faedf86d3f5d583d4634

Basically I changed the `ASTParser`'s visibility from `package private` to `public`, enabled the `COMMON_TOKEN_ACTION` option and implemented a `CommonTokenAction(Token token)` that collects all tokens in a list.

Although this quick fix does the job for me, I would of course appreciate if such operations were possible using the main project's code. Do you think it would be possible to broaden the API somehow without negative impact for users of the library that don't care about the tokens?

I guess making the `ASTParser` public wouldn't hurt that much, but the collection of tokens in a list is an unnecessary overhead if not needed. Any way to add more optional constructor arguments for the `ASTParser` to enable this behaviour if needed? As far as I can see, the existing constructors are generated by `javacc`.

**Comment by ptitjes** [comment]
Hi sebkur,
I implemented full lex-preservation with techniques similar to what your are talking about some months ago on JavaParser. You can find it here :
https://github.com/ptitjes/javaparser/tree/lex-preserving
Note that this code is still **LGPL only**!

Tokens (I call them `Lexeme`s) are organized as a doubly-linked list with `Node`s' having pointers to `begin` and `end` tokens (by extending the `Run` class).
You can see all the `Lexeme`s and `Run` classes here: https://github.com/ptitjes/javaparser/tree/lex-preserving/javaparser-core/src/main/java/com/github/javaparser/ast/lexical

As JavaParser became dual-licensed and I did not submit to it, this won't make it to master.

Also, having the both the AST tree and the token runs be mutable, I felt it would not be easy to enforce the coherence of both the runs and AST. Thus, I implemented a new parser that you might be interested in.
It is called JLaTo (https://github.com/ptitjes/jlato) and features full end-to-end lexical preservation, customizable formatting for added nodes, a preliminary API for declaratively transform the trees and is completely based on an immutable AST with functionnal-style mutators. It seems it would perfectly fit your need.

**Comment by ftomassetti** [comment]
@sebkur I personally think it would be a nice addition to have access to the list of tokens and in my opinion it would be in scope with the mission of JavaParser. Would you consider submitting a PR? I think it would be greatly appreciated!

**Comment by sebkur** [comment]
Just created a PR: https://github.com/javaparser/javaparser/pull/207

**Comment by sebkur** [comment]
@ptitjes thanks for your information, sounds interesting

**Comment by matozoid** [comment]
As this seems to be a request to make the tokens public, I guess it's already done.
