### ISSUE TITLE
Class renaming propagation

### ISSUE THREAD

**Issue by rojoyin** [javaparser/javaparser#2051]
Hello,

This project has been really useful. This is a great tool.
I was wondering if is there any way to rename a class and propagate this change through the whole project where this class is being used, my approach would be to inspect every class and verify if the class is used to perform the change, however I would like to be sure if it is not a way using some feature of JSS.

Thank you in advance.

**Comment by matozoid** [comment]
Hi! There is no such feature. It has been suggested to add some refactorings to JP a few times, but the project is too big to maintain with the current people already. It would be nice if someone started a project with refactorings though!

**Comment by rojoyin** [comment]
Thank you for the answer. Sure it could be great to start this, I will do some changes in my code and after that contribute to this project.

**Comment by matozoid** [comment]
@rojoyin cool, but make it an external project - we don't have time for maintaining it.

**Comment by rojoyin** [comment]
Sure, @matozoid.

**Comment by ghost** [comment]
@rojoyin or @matozoid , mind posting a link to more information about where the class renaming functionality can be found?
