### ISSUE TITLE
Method descriptor

### ISSUE THREAD

**Issue by kushal256** [javaparser/javaparser#2059]
Is there a way to get the method descriptor for a method (see http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.3.3 ).  JavaSymbolSolver would be great to resolve the fully qualified objects wondering if anyone already has written something like this?

Thanks!

**Comment by Devan-Kerman** [comment]
is there any progress on this or has anyone else done this for me to look at?

**Comment by jlerbsc** [comment]
To my knowledge it is not yet implemented but it does not seem very complex to do starting from MethodDeclaration class.
