### ISSUE TITLE
Getting ConstructorDeclaration from ExplicitConstructorInvocationStmt

### ISSUE THREAD

**Issue by Meddan** [javaparser/javaparser#2061]
Hello, I was wondering if it is possible to get a ConstructorDeclaration from ExplicitConstructorInvocationStmt using the SymbolSolver? I've managed to get a MethodDeclaration from a MethodCallExpr by getting the SymbolReference (sr) and doing the following: `MethodDeclaration md = ((JavaParserMethodDeclaration) sr.getCorrespondingDeclaration()).getWrappedNode();`

However when I do this on a ExplicitConstructorInvocationStmt I get a JavaParserConstructorDeclaration instead of a JavaParserMethodDeclaration which doesn't have getWrappedNode().

Thanks

**Comment by matozoid** [comment]
This getter exists now, so it seems to have been added somewhere in the past two years.
