### ISSUE TITLE
Problem Resolving Lambdas Types of Apache Spark RDDs

### ISSUE THREAD

**Issue by RaulGracia** [javaparser/javaparser#2063]
Hi all,

As a preliminar stage of my work, I used JSS to find types of Java8 lambdas and it worked well so far. Now, I want to extend the use of JSS to lambdas executed on RDDs of the [Apache Spark](http://spark.apache.org/) framework. However, this is not working, and I would like to know if there is a possible solution to that.

Let us consider a very simple Spark program:

```
SparkConf conf = new SparkConf().setAppName("SimpleTextAnalysisSparkJava"); 
JavaSparkContext sc = new JavaSparkContext(conf);
JavaRDD<String> distFile = sc.textFile("data.txt");
distFile.map(s -> s.length());
```

As Spark is an independent framework with its own classes (e.g., JavaRDD), I assume that JSS needs the reference to the Spark/Scala libraries to do the work of type inference. For this reason, I added a couple of JarTypeSolvers in my program to handle this:

```
combinedTypeSolver.add(new JarTypeSolver(sparkJarLocation));
combinedTypeSolver.add(new JarTypeSolver(scalaJarLocation));
```
These solvers (plus the ReflectionTypeSolver and JavaParserTypeSolver) are added into a JavaParserFacade.

Then, I use a visitor to detect the lambda expressions through the code. When the program detects a lambda expression, like the `map(s->s.length())`, it tries to find the type of the lambda using: 

Type type = javaParserFacade.getType(n, true);

Unfortunately, in this case I got an error:

> UnsolvedSymbolException{context='distFile.map(s -> s.length())', name='map', typeSolver=null}

To focus the problem, I tried to change only the 3rd line of the previous program by declaring the distMap variable as a Stream of Java8 as follows:

```
SparkConf conf = new SparkConf().setAppName("SimpleTextAnalysisSparkJava");
JavaSparkContext sc = new JavaSparkContext(conf);
Stream<String> distFile = Stream.of("");  //Change the Spark JavaRDD declaration by java.util.Stream
distFile.map(s -> s.length()); 
```

In this case, this works and JSS knows that the type of the lambda is:

> Type found by JSS: java.util.function.Function<java.lang.String, java.lang.Integer>

My question is: there is any fundamental error in my approach of trying to get the types of lambda functions from external classes like JavaRDD? Or, is it more related to a bad use of JarTypeSolvers that prevents them to see the classes from Spark/Scala libraries?

Thanks in advance!

Raúl.

**Comment by jlerbsc** [comment]
This issue seems to be related to #1771 #2940 #2762

**Comment by jlerbsc** [comment]
This issue seems to be actually resolved but as there is not a test case to reproduce this error it is difficult to confirm that this case is solved.

**Comment by jlerbsc** [comment]
We can close this problem for now and possibly reopen a new one if this case occurs again.
