### ISSUE TITLE
Issue calculating the type of the scope of MethodCallExprContext

### ISSUE THREAD

**Issue by wompers** [javaparser/javaparser#2064]
Hi!

I have a code that looks like this:

```
java.math.BigDecimal Amount = new java.math.BigDecimal("12345");
String strAmount = Amount.setScale(2, java.math.RoundingMode).toString();
```

and my visit implementation looks like this:

```
@Override
public void visit(MethodCallExpr n, JavaParserFacade javaParserFacade) {
	super.visit(n, javaParserFacade);
		String method = "";
		if(n.getScope().isPresent()) {
			try {
				MethodDeclaration methodDeclaration = javaParserFacade.solve(n).getCorrespondingDeclaration();
				method= methodDeclaration.getPackageName() + "." + methodDeclaration.getClassName();
			} catch (Exception e) {
				e.printStackTrace();
			}
		} 
	}
```

However, I am encountering this error:
```
java.lang.RuntimeException: Issue calculating the type of the scope of MethodCallExprContext{wrapped=Amount.setScale(2, java.math.RoundingMode).toString()}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:151)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:261)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:145)

```

How should a code like this be parsed?
Thanks!

**Comment by jlerbsc** [comment]
In javaparser 3.15.8 this test case results in the exception MethodAmbiguityException. I'm not sure this is a bug.

     UnsolvedSymbolException{context='Amount.setScale(2, java.math.RoundingMode).toString()', name='Amount.setScale(2, java.math.RoundingMode)', cause='com.github.javaparser.resolution.MethodAmbiguityException: Ambiguous method call: cannot find a most applicable method: MethodUsage{declaration=ReflectionMethodDeclaration{method=public java.math.BigDecimal java.math.BigDecimal.setScale(int,int)}, paramTypes=[PrimitiveTypeUsage{name='int'}, PrimitiveTypeUsage{name='int'}]}, MethodUsage{declaration=ReflectionMethodDeclaration{method=public java.math.BigDecimal java.math.BigDecimal.setScale(int,java.math.RoundingMode)}, paramTypes=[PrimitiveTypeUsage{name='int'}, ReferenceType{java.math.RoundingMode, typeParametersMap=TypeParametersMap{nameToValue={}}}]}. First declared in java.math.BigDecimal'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:157)

Test

    CompilationUnit cu = StaticJavaParser
                .parse(
                        "public class A {"+
                        "  public void m() {" + 
                        "    java.math.BigDecimal Amount = new java.math.BigDecimal(\"12345\");" +
                        "    String strAmount = Amount.setScale(2, java.math.RoundingMode).toString();" +
                        "  }" +
                        "}"
                  );
        MethodCallExpr expr = cu.findFirst(MethodCallExpr.class)
                .orElseThrow(() -> new IllegalStateException("???"));
        ResolvedMethodDeclaration md = expr.resolve();
        assertTrue(!md.getPackageName().isEmpty());

**Comment by jlerbsc** [comment]
This issue is resolved now.

Package name is java.math
Class name is BigDecimal
