### ISSUE TITLE
Error on Lambda resolution

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#2066]
_Reported by Ameya Sanjay Sanjay Ketkar to me._

 have set up the environment, as in the examples. 
![dep](https://cloud.githubusercontent.com/assets/439078/26820830/8825ae30-4aa4-11e7-9c45-28745097f62d.png)
Problem I am facing: 
![visitor](https://cloud.githubusercontent.com/assets/439078/26820835/8f891fd6-4aa4-11e7-929c-811a6c0731e5.png)

When I do this in the ASTVisitor, I am unable to resolve the lambda and get its type for all the lambdas. 256/684 are resolved.

A few exceptions that i get:
1. The type of a lambda expr depends on the position and its return value
2. Error calculating the type of parameter m2.spanToString() of method call 
3. Issue calculating the type of the scope of 
4. Ambiguous method call: cannot find a most applicable method:

**Comment by jlerbsc** [comment]
It is not easy to install the test case. There are also classes that no longer exist in the current version of JP. I think this issue can be closed even if the problems still exist. I don't know of any support that would keep such a general issue open. People who have problems should take the time to implement as simple a test case as possible that reproduces the problem.

**Comment by jlerbsc** [comment]
This issue is closed because there are no new comments on whether this issue can be produced. Furthermore a simplified test case should also be provided to allow us to reproduce the error without spending too much time on it.
