### ISSUE TITLE
Error solving type of String split() method in lambda function

### ISSUE THREAD

**Issue by RaulGracia** [javaparser/javaparser#2067]
Hi,

I realized in my tests that JSS is having problems to resolve the type of the split() method of String.
This is a simple code to reproduce the problem I'm experiencing:

```
Stream<String> myStream = Files.lines(Paths.get(inputFile));
long lines = myStream.filter(s -> s.contains("Hamlet") && s.contains(" "))
		     .map(l -> l.split(" "))
		     .map(l -> l[0])
		     .count();
```

The test outputs the types found by JSS:
> Type found by JSS: java.util.function.Predicate<java.lang.String>
> Processing transformation: l -> l.split(" ")
> Type found by JSS: java.util.function.Function<java.lang.String, R>
> Processing transformation: l -> l[0]
> Type found by JSS: java.util.function.Function<R, R>

As you can see, JSS works well for the first lambda; however, after making use of the split() method, the rest of types cannot be resolved.

If we replace the return type of the second lambda from String[] to List of String as follows:
```
Stream<String> myStream = Files.lines(Paths.get(inputFile));
long lines = myStream.filter(s -> s.contains("Hamlet") && s.contains(" "))
					.map(l -> Arrays.asList(l.split(" ")))
					.map(l -> l.get(0))
					.count();
```
It works:
> Type found by JSS: java.util.function.Predicate<java.lang.String>
> Processing transformation: l -> Arrays.asList(l.split(" "))
> Type found by JSS: java.util.function.Function<java.lang.String, java.util.List<java.lang.String>>
> Processing transformation: l -> l.get(0)
> Type found by JSS: java.util.function.Function<java.util.List<java.lang.String>, java.lang.String>

Hope that this helps to reduce the spectrum of causes to solve this problem. By the way, I'm using JSS version 5.5 as provided in the Maven repository.

Thanks a lot,
Raúl.

**Comment by jlerbsc** [comment]
We cannot reproduce this issue in JP 3.17.0 with this simplified test case.

    @Test
    void test() {
        String code =
                "import java.util.stream.Stream;\n" + 
                "\n" + 
                "public class A {\n" + 
                "    public void test(){\n" + 
                "        Stream.of(\"a b c\").map(l -> l.split(\" \"));\n" + 
                "    }\n" + 
                "}";
        
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(code);
        List<MethodCallExpr> methodCallExpr = cu.findAll(MethodCallExpr.class);
        for (MethodCallExpr expr : methodCallExpr) {
            System.out.println("trying to solde " + expr.toString());
            ResolvedMethodDeclaration rd = expr.resolve();
            System.out.println(String.format("%s solved to %s", expr.toString(), rd.getQualifiedSignature()));
        }
    }

results

    trying to solde Stream.of("a b c").map(l -> l.split(" "))
    Stream.of("a b c").map(l -> l.split(" ")) solved to java.util.stream.Stream.map(java.util.function.Function<? super T, ? extends R>)
    trying to solde Stream.of("a b c")
    Stream.of("a b c") solved to java.util.stream.Stream.of(T)
    trying to solde l.split(" ")
    l.split(" ") solved to java.lang.String.split(java.lang.String)
