### ISSUE TITLE
Problem solving method call "System.out.println()"

### ISSUE THREAD

**Issue by lodart** [javaparser/javaparser#2068]
Hi ! I'm going to need to use JavaParser and JSS for a project for an Internship, and I'm a bit struggling with the TypeSolver. I tried to adapt the piece of code from the JavaParserVisited pdf to Test classes and ended with this error when `System.out.println()` was present on one of my parsed files : 

> Exception in thread "main" java.lang.NoSuchMethodError: com.github.javaparser.ast.expr.FieldAccessExpr.getScope()Ljava/util/Optional;

Here's how I built my CombindeTypeSolver : 

        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(srcDir));
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        combinedTypeSolver.add(javaParserTypeSolver);

I thought this would be covered by the ReflectionTypeSolver, as  `System.out.println()` is part of the Language (right ?) but it is not.

**Comment by matozoid** [comment]
@lodart - this is probably way too late, but if you need more help with this, please open a new issue.
