### ISSUE TITLE
solveMethodAsUsage failing help?

### ISSUE THREAD

**Issue by bennewi** [javaparser/javaparser#2070]
Hi, I'm getting a RuntimeException on line 331 of `MethodCallExprContext.java`

What I've got is a method invocation in one Java file, of a method that is defined in another Java file. This method takes two arrays as parameters, of types that are defined in an external JAR. So I'm using a `JavaResolver` and a `JARResolver`. But in my analyzer when I visit that with a `MethodCallExpr` as node type, it throws an error when I invoke `javaParserFacade.solveMethodAsUsage(n)`
  
`java.lang.RuntimeException: org.jfree.chart.ChartPanel[] org.jfree.chart.ChartPanel[]`

**Comment by jlerbsc** [comment]
It seems that this problem is not reproducible since we cannot develop a unit test that demonstrates the problem. This issue should be probably closed.

**Comment by MysterAitch** [comment]
There is mention of the class path and jar solver above.

Could this be another duplicate of #2762 and co, perhaps?

Either way, I agree that closing it seems reasonable and @bennewi or others can comment/reopen this if not :+1:
