### ISSUE TITLE
Cannot resolve variable type which is defined in another java file

### ISSUE THREAD

**Issue by rahiminasab** [javaparser/javaparser#2072]
I have two simple classes as follows defined in two separate java files in a same directory:
----------------------------------------- A.java
```
package sample1;
public class A {  }
```
-----------------------------------------B.java
```
package sample1;
public class B { A a = new A(); }
```
----------------------------------------

I instantiate my typesolver as follows:

`typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), new JavaParserTypeSolver("...path...to.../sample1"));`
----------------------------------------
When I am visiting the CompilationUnit for B, and I reach VariableDeclarator "a = newA()", I use the following line of code to get its type:
`type = JavaParserFacade.get(typeSolver).getType(var);`

But It fails to resolve, with error:
`UnsolvedSymbolException{context='unknown', name='A', typeSolver=null}`

However when both A and B are defined in same file, there is no problem. I know that JavaSymbolSolver is able to simply handle this, but I cannot figure out where am I wrong!?

**Comment by jlerbsc** [comment]
This is not an issue in javaparser 3.15.8

Test

    File f = new File("src/test/resources/issue2072/B.java");
        if (!f.exists()) {
            throw new IllegalStateException();
        }

        CombinedTypeSolver cts = new CombinedTypeSolver();
        cts.add(new ReflectionTypeSolver());
        cts.add(new JavaParserTypeSolver(f.getAbsoluteFile().getParent()));

        ParserConfiguration parserConfiguration = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(cts));
        StaticJavaParser.setConfiguration(parserConfiguration);

        CompilationUnit cu = parse(f);
        cu.accept(new VoidVisitorAdapter() {
            public void visit(VariableDeclarator n, Object arg) {
                ResolvedValueDeclaration type = n.resolve();
                assertTrue(type.getType().describe().equals("A"));
            }
        }, null);

**Comment by matozoid** [comment]
Cool!
