### ISSUE TITLE
CombinedTypeSolver does not solve user defined method declaration

### ISSUE THREAD

**Issue by Cale-92** [javaparser/javaparser#2073]
Hi! My problems are related to the CombinedTypeSolver class. Although i've specificied the correct folders where to look for user files, some method calls are not solved at all otherwise some others are.

    public static CombinedTypeSolver typeSolver() {
	CombinedTypeSolver combinedTypeSolver = null;
	try {
		combinedTypeSolver = new CombinedTypeSolver();
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123")));
		/*combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\commons\\constants")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\commons\\utils")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\activities")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\adapters")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\chart")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\fragments")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\googledrive")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\helper")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\models")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\plagiarism")));
		combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));*/
		
		combinedTypeSolver.add(new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.7\\commons-lang3-3.7.jar"));
		combinedTypeSolver.add(new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\org\\bouncycastle\\bcprov-jdk15on\\1.58\\bcprov-jdk15on-1.58.jar"));
		//combinedTypeSolver.add(new JarTypeSolver("C:\\Users\\Jt\\AppData\\Local\\Android\\sdk\\platforms\\android-25\\android.jar"));
		// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
		// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
		// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
		// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
		combinedTypeSolver.add(new ReflectionTypeSolver());

		/*new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\commons-io\\commons-io\\2.6\\commons-io-2.6.jar"),
		new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\javaparser-core\\3.3.0\\javaparser-core-3.3.0.jar"),
		new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\java-symbol-solver-core\\0.6.0\\java-symbol-solver-core-0.6.0.jar"),
		new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\java-symbol-solver-logic\\0.6.0\\java-symbol-solver-logic-0.6.0.jar"),
		new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\java-symbol-solver-model\\0.6.0\\java-symbol-solver-model-0.6.0.jar"),*/
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	return combinedTypeSolver;
}

To be more clear:

    combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123")));

This line of code is similar to "src/main/java", where i specified only the root directory of java sources.

    combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\commons\\utils")));

As opposite, this line and others similar, specify the exact structure of the project thus they point directly to java sources.

The only method calls correctly solved are method declarations write in the "commons" directory sources, instead others are not.

Is this CombinedTypeSolver instantiated right? Is there the possibility to print information of the solver at runtime?

**Comment by jlerbsc** [comment]
@matozoid I think this is not an open bug but a missuse of JavaParserTypeSolver.

**Comment by matozoid** [comment]
Thanks for helping clean up, @jlerbsc :-)
