### ISSUE TITLE
Make FieldDeclaration.declaringType returns a ReferenceTypeDeclaration

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#2074]
Remove all casts and instanceof that are unnecessary following this change.

**Comment by matozoid** [comment]
@ftomassetti has this been done already? I can't really relate this to the current codebase.

**Comment by ftomassetti** [comment]
I do not think so

**Comment by matozoid** [comment]
Okay, I find it impossible to pick up without more description. Can you add some?

**Comment by ftomassetti** [comment]
First of all that `FieldDeclaration` is now `ResolvedFieldDeclaration` and [this is the method](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.11.0/com/github/javaparser/resolution/declarations/ResolvedFieldDeclaration.html#declaringType--). However I am not sure it makes sense to return a ReferenceTypeDeclaration... this seems wrong to me and I would close it

**Comment by matozoid** [comment]
Alright, thanks!
