### ISSUE TITLE
No access to attributes?

### ISSUE THREAD

**Issue by penguinized** [javaparser/javaparser#208]
I fail to access attributes and their JavaDoc. Can you tell me what I do wrong?

```
CompilationUnit cu = JavaParser.parse(in);
System.out.println(cu.toString());
```

shows the class and the contained methods.. but no attributes or their JavaDoc!

**Comment by ftomassetti** [comment]
This seems strange. Which attributes are you looking for? Can you share the code you were parsing? Which version of JavaParser are you using?

**Comment by penguinized** [comment]
I am very sorry, I was plain stupid. I tried to access the wrong file (in my old project folder which did not use Maven.). The correct path to the file works. (Version 2.2.2)

**Comment by ftomassetti** [comment]
No problem, thank you for reporting this anyway and if you have other issues let us know: we are here to help
