### ISSUE TITLE
Can we specify an order to visit the children with VoidVisitorAdapter 

### ISSUE THREAD

**Issue by rafid009** [javaparser/javaparser#2086]
I am trying to find the type (java class type/primitive) of a single node which I am passing as an argument to my getType() function. Since I don't know which kind of entity (expression or declaration) it is, I am using VoidVisitorAdaptor. But what it's doing is that it iterates over the whole subtree the given node is root of. So I am getting the types of all entities in that node.
Like, If the given node contains:
System.out.println("Hello World!")
I want the type void that is the return type of this expression. But with using the VoidVisitorAdaptor<JavaParserFacade> I am getting both Void and String (type of String literal "Hello World!").
If I can somehow make the VoidVisitorAdaptor to iterate the nodes in a specified order (root first), then I can solve this issue. Is there a way to do it?
Or is there a better way to do what I intend here?

**Comment by rafid009** [comment]
I am trying to find the type (java class type/primitive) of a single node which I am passing as an argument to my getType() function. Since I don't know which kind of entity (expression or declaration) it is, I am using VoidVisitorAdaptor. But what it's doing is that it iterates over the whole subtree the given node is root of. So I am getting the types of all entities in that node.
Like, If the given node contains:
System.out.println("Hello World!")
I want the type void that is the return type of  this expression. But with using the VoidVisitorAdaptor I am getting both Void and String (type of String literal "Hello World!").
If I can somehow make the VoidVisitorAdaptor to iterate the nodes in a specified order (root first), then I can solve this issue. Is there a way to do it?
Or is there a better way to do what I intend here?

**Comment by rafid009** [comment]
Never mind. I got what I was looking for.

**Comment by matozoid** [comment]
If you can write one or two lines about what your solution was, then future users can benefit from it.

**Comment by rafid009** [comment]
I was actually doing something wrong. I was calling the super() method of the visit() methods. So it was not just visiting the node I was providing but also visiting its children. Now I removed the super() call and it's working as I want.

**Comment by matozoid** [comment]
Ah okay, thanks!
