### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded when looking for type in large project

### ISSUE THREAD

**Issue by Sherlock323** [javaparser/javaparser#2087]
I'm working on hadoop source code. I build a **CombinedTypeSolver** with 7000+ **JavaParserTypeSolver** and 500+**JarTypeSolver** in my code to resolve method calls. However, When the program runs to following code: `mce.resolve().getQualifiedSignature()` , throws such exception:`java.lang.OutOfMemoryError: GC overhead limit exceeded` .
My project is running on eclipse, how javaparser deal with large codebase?

**Comment by matozoid** [comment]
Here's the main memory usage issue: #1391

**Comment by matozoid** [comment]
@Sherlock323 - did you find a way to reduce the overhead?
