### ISSUE TITLE
Exporting source code as HTML with custom highlighting

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javaparser#2088]
Hello :)

I would like to export the source code with custom highlighting. I plan to export it in HTML, therefore I would like to wrap individual elements in `<span>`s with the style color tags of my choosing to highlight them. But I also would like to keep the original format of the source code.

Is there an easy way to accomplish this? I probably could do it via a Visitor, but I feel like that might mess up the original formatting. Any ideas?

**Comment by matozoid** [comment]
If the highlighting stays simple, you can take the token list and color things depending on token type. Get the token range from the compilation unit, figure out how to print it (it should give you the exact same output as the input,) then start looking at the token types.

If you want to do more complex highlighting on AST level, well, I guess you have to start hacking the lexical preserving printer?

**Comment by un0btanium** [comment]
Alright, thank you. I will see what I can do :+1:

**Comment by matozoid** [comment]
(third option is of course to take the pretty printer and create your own copy of it, but that would mean that all source code gets pretty printed)
