### ISSUE TITLE
Comment shift to new statement when adding statement

### ISSUE THREAD

**Issue by moraispgsi** [javaparser/javaparser#2099]
Hi, I'm trying to add a statement using addStatement on a BlockStmt (the method 'test' below) and the line comment seems to shift from one statement to the new (from the query.getLong(0); to the if statement), is this a bug in JavaParser? If it is, how can I work around that?

```
public class Teste {
    public void test(Uri uri, ContentProvider provider) {
        Cursor query = provider.query(uri, null, null, null, null);
        query.getLong(0); // Teste
    }
}
```

```
public class Teste {
    public void test(Uri uri, ContentProvider provider) {
            Cursor query = provider.query(uri, null, null, null, null);
            query.getLong(0); if(query != null) {
            query.close();
        }
        // Teste
    }
}
```

Thanks in advance

**Comment by matozoid** [comment]
Hi!
Comments work in a special way, it's probably best to send you here: https://github.com/javaparser/javaparser/issues/638

The (not very wonderful) suggestion is not to have comments in funny places, but in this case we should really look into fixing it.

**Comment by moraispgsi** [comment]
Removing the comment is not a possibility in this case. I only need it to stick to the same statement when it is printed back to the file. Do you have any other sugestions?

Thanks.

**Comment by matozoid** [comment]
The remaining suggestion is to fix the problem and open a PR.
