### ISSUE TITLE
Switch validation is too strict

### ISSUE THREAD

**Issue by maartenc** [javaparser/javaparser#2106]
Hi,

After upgrading to javaparser 3.13.1 (from 3.10.1), we get following exception when parsing some of our source files: `com.github.javaparser.ParseProblemException: (line 605,col 17) Only 'int's, enums, and strings in switch statements are supported.`

It seems to occur on switch statements on constants from other classes:

```java
int type = ... ;
swith (type) {
    case java.sql.Types.TINYINT:  // ParseProblemException here !!
        ...
}
```

Maarten

**Comment by matozoid** [comment]
You're correct, I'll make it less strict again for the next release. You can go back to 3.12.0 in the mean time.
