### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by socketopp** [javaparser/javaparser#2107]
I added the following jar to my Eclipse Plugin Projects  classpath. 

- javaparser-core-3.10.0.jar     

From [central maven](http://central.maven.org/maven2/com/github/javaparser/javaparser-core/3.10.0/).

I tried to run the first [basic example:](https://github.com/javaparser/javaparser/wiki/Manual)
Printing the CompilationUnit to System output. 
However I recieve:

java.lang.NoClassDefFoundError: com/github/javaparser/JavaParser
.
.
Caused by: java.lang.ClassNotFoundException: com.github.javaparser.JavaParser cannot be found by...
..
at java.lang.ClassLoader.loadClass(Unknown Source)

Any ideas to why this happends and what possible fix might be?

**Comment by matozoid** [comment]
Hi!
We have two sample project setups:
- https://github.com/javaparser/javaparser-maven-sample
- https://github.com/javaparser/javasymbolsolver-maven-sample

and this was written a while ago: https://github.com/javaparser/javaparser/wiki/Eclipse-Project-Setup-Guide.

**Comment by socketopp** [comment]
> 
> 
> Hi!
> We have two sample project setups:
> 
>     * https://github.com/javaparser/javaparser-maven-sample
> 
>     * https://github.com/javaparser/javasymbolsolver-maven-sample
> 
> 
> and this was written a while ago: https://github.com/javaparser/javaparser/wiki/Eclipse-Project-Setup-Guide.

Thanks for the reply. 
I created a Maven project and converted it to an plugin project. I have added my plugin dependencies in the project and added the javaparser dependency in my POM file.


`    
<dependencies>
        
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-core</artifactId>
            <version>3.8.0</version>
        </dependency>
    </dependencies>
`

However the project compains on: CompilationUnit cannot be resolved to a type and 
JavaParser cannot be resolved. 

I have tried to Clean the project as well as maven clean.
The issue arised when I updated the classpath settings. Not sure why that should cause this issue. 

I managed to ressolve this issue by going maven -> update project.

When I ran the project as an eclipse application and tried one of my menu buttons that trigger javaparser code the response is:
java.lang.NoClassDefFoundError: com/github/javaparser/JavaParser
.
.
Caused by: java.lang.ClassNotFoundException: com.github.javaparser.JavaParser cannot be found by

**Comment by matozoid** [comment]
Are you making a Maven plugin? Here's a sample project: https://github.com/matozoid/javaparser-maven-plugin-dependencies

We're here to help with JavaParser issues - Eclipse issues are not.

**Comment by socketopp** [comment]
Thanks for the help. I managed to find a winning solution [here](https://stackoverflow.com/questions/5744520/adding-jars-to-a-eclipse-plugin). ethnix solution did the trick. I manage to run JavaParser now.

**Comment by matozoid** [comment]
Cool! Good luck :-)
