### ISSUE TITLE
Find root in call hierarchy

### ISSUE THREAD

**Issue by v95** [javaparser/javaparser#2108]
Hello,

I am using javaparser to find methods in my project that contain a specific statement. For each such method that I find, I need to get its call hierarchy to find the root caller.

For example, let’s say the call goes like this:
`A.jsp` internally invokes `B.getData()`, which itself calls `C.doSomething()`. Let’s assume that the last method (`doSomething`) has the statement I am looking for. Is there a way to trace it back to `A.jsp` as the root of the call hierarchy?

So far, I have been (roughly) doing something this:

```
CompilationUnit cu = ...
for (MethodDeclaration md : cu.findAll(MethodDeclaration.class) {
    String body = ... // get method body
    if (conditionSatisfied(body)) {
        MethodDeclaration mdRoot = md.findAncestor(MethodDeclaration.class)
        ....
    }
}
```

However, this doesn’t return what I am looking for. Is there anyway to get the root caller (call “initiator”)?

Thank you!

**Comment by matozoid** [comment]
@ftomassetti might know better than me, but...

as far as I can see: you want to know about all the method call expressions that, when scope and parameters and everything are resolved, match with `doSomething`. For every one you find, you look up in the AST hierarchy what its method declaration is. Now you end up with a list of callers of `doSomething`. If you repeat this for the callers, you get the callers of the callers, etc.

If you can do with less accuracy, you could simplify the resolving step by not using the symbol solver and simply compare using the method name. This will of course generate false positives.

**Comment by ftomassetti** [comment]
I agree with what @matozoid suggest

Basically you first figure out that you are interested in C.doSomething, then you need to explore _the whole codebase_ to examine all method calls and check which ones are calls do `doSomething`. Then you have to iterate over this

**Comment by matozoid** [comment]
Assuming this is answered
