### ISSUE TITLE
StaticJavaParser might not be thread safe

### ISSUE THREAD

**Issue by dhardtke** [javaparser/javaparser#2113]
I think `StaticJavaParser` is not thread safe:

The "old" JavaParser class called `com.github.javaparser.JavaParser#simplifiedParse` internally which in turn created a new `JavaParser` for each parse call.

`StaticJavaParser` just re-uses the same `JavaParser` instance (which is fine I guess) but that is quite a different behavior.

It would be nice if at least this was documented somewhere so people like me don't wonder why concurrency-related tests are suddenly failing.

**Comment by matozoid** [comment]
Thankfully we have people with concurrency tests who find bugs like these! I'll go fix it.
