### ISSUE TITLE
Unable to get MethodDecleration from JavassistMethodDeclaration.toAST()

### ISSUE THREAD

**Issue by gilyerm** [javaparser/javaparser#2118]
for some reason when turning `JavassistMethodDeclaration` to it's `Optional<MethodDecleration>`, the code seems to only return "Optional.empty", which is also what is in the code:
`    public Optional<MethodDeclaration> toAst() {
        return Optional.empty();
    }
`

is this a bug / missing feature? any 'dirty' quick fixes maybe? :)

**Comment by matozoid** [comment]
Hi! `MethodDeclaration`s are created by parsing source code. Javassist works on compiled code, not source code. A `JavassistMethodDeclaration` simply does not have source code available so there is no `MethodDeclaration`. That's where it ends really :-)

If you give an idea of what you're trying to do we might be able to help.

**Comment by gilyerm** [comment]
I have both the source code and the class ("compiled") objects.
i'm trying to make connections between calls/accesses to interesting data (i.e a method invocation of another class in my project) - and mapping out the connections.
for some reason running:
`SymbolReference<ResolvedValueDeclaration> solve = JavaParserFacade.get(typeSolver).solve(n);`
gives me the javassist output, rather then the MethodDeclaration.
is it possible this happens, since i loaded all these classes into memory prior to running solve?

**Comment by matozoid** [comment]
@ftomassetti @maartenc ?

**Comment by ftomassetti** [comment]
Well, you can avoid using reflection for anything but the JDK stuff by setting a flag in the ReflectionTypeSolver

**Comment by ftomassetti** [comment]
See [ReflectionTypeSolver](https://static.javadoc.io/com.github.javaparser/javaparser-symbol-solver-core/3.13.2/com/github/javaparser/symbolsolver/resolution/typesolvers/ReflectionTypeSolver.html) and its constructors

**Comment by JonJam** [comment]
@gilyerm I was having the same issue where I had both Source and compiled added to the CombinedTypeSolver, but when calling toAst it results in Optional.empty.

The solution I came up with was when creating my CombinedTypeSolver, I add all the JavaParserTypeSolvers first and then the JarTypeSolvers. That way it will resolve things using Source first and then Compiled.

**Comment by matozoid** [comment]
Note that having the same code in source and compiled form in the solvers is not something the symbol solver expects. The results are undefined.

**Comment by matozoid** [comment]
Assuming this is answered.
