### ISSUE TITLE
TryStmt throws null pointer if setResources is not called

### ISSUE THREAD

**Issue by JLLeitschuh** [javaparser/javaparser#212]
If you create a `TryStmt` without calling `setResources(Collections.emptyList())` the to string dump visitor throws a null pointer exception.
This line:
https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/DumpVisitor.java#L1420
Should check for null as well as if empty.

**Comment by ftomassetti** [comment]
As discussed in the PR this behavior should be fixed in master, bacause we now use lazy initialized lists everywhere. I would then close this one if this is ok for everyone.

**Comment by JLLeitschuh** [comment]
It may be better if you were to start using the java util `Optional` for variables that are optional.
https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html

**Comment by ftomassetti** [comment]
Unfortunately we cannot use Optional because we have decided to be Java 6 compatible for now. However many lists are conceptually empty but just not instantiated to save memory: in an AST we tend to generate tons of objects and for performance reasons lists are instantiated only when required.

The project has a few years and some decisions could be revised but this is the historical overview :)

**Comment by JLLeitschuh** [comment]
Good to know. Thanks!

**Comment by ftomassetti** [comment]
Thank you for your help and your interest in JavaParser. It is really appreciated: we need fresh blood :)

**Comment by JLLeitschuh** [comment]
I'm using your library heavily in my Major Qualifying Project for Worcester Polytechnic Institute as a code parser and generator for OpenCV. After initially figuring out how to use the library I'm finding it quite intuitive.

I like how easy it is to use constructors within constructor calls to get the desired code.
When combined with the new Java 8 List streams the code becomes really easy to write. As an example:
https://github.com/WPIRoboticsProjects/GRIP/blob/master/buildSrc/src/main/java/edu/wpi/gripgenerator/templates/Operation.java#L193

**Comment by ftomassetti** [comment]
Yes, I love the Java 8 features (I am using them everywhere but in JavaParser). Hope it helps you. I also used a lot of code generation in my thesis but at that time I did not know JavaParser. I wish I did :)

**Comment by ftomassetti** [comment]
I think this one can be closed now. Let's reopen it if I was wrong.
