### ISSUE TITLE
how can i get the vision before the manual written?

### ISSUE THREAD

**Issue by anmilky** [javaparser/javaparser#2120]
"https://github.com/javaparser/javaparser/wiki/Manual"
i see this website still not updated, i don't know how to use this tool without the manual
how can i get the version which is released before the manual written?
i set the version to 3.3.3 in maven . but it shows not found.
is there another manual?

**Comment by anmilky** [comment]
i solved this by setting  the version to 3.6.10  : )

**Comment by matozoid** [comment]
Hi! You're right, the wiki is pretty outdated. Check out http://javaparser.org/getting-started/ for more.

You can check the issue tracker to see how many bugs you introduced by downgrading :-(

**Comment by matozoid** [comment]
https://github.com/javaparser/javaparser-visited/issues/17
