### ISSUE TITLE
Put statments inside another statement

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#2121]
Hi, I'm having a great fun with javaparser, but I'm trying to put a method statements within another higher level block (if) and I have a question. I want to turn something like this:

```
public static void MethodX()
{
  String param = function();
  int x = 0;
}
```
into:

```
public static void MethodX()
{
  if (condition == true)
  {
    String param = function();
    int x = 0;
  }
```

I was trying to use method visitor but I'm failing every time, is there a proper way of doing something like this in javaparser, or should I build a new statements list and replace it within the body node?

Need some directions on this one and thank you for this awesome piece of code.

**Comment by matozoid** [comment]
Hi! Definitely read this, which will give you a feeling for what you're working with: http://javaparser.org/inspecting-an-ast/

If the question is "how do I wrap everything in a method body in an if statement?" then I would do it like this: visit all method declarations. "new" an IfStmt, give it a BlockStmt, then add all the statements from the method declaration body to the new BlockStmt.

Can you get this to work?

**Comment by PELock** [comment]
But the problem is to replace BlockStmt with other statement type in a visitor itself, replace() method expects the same type, meh, will try everything, I just thought there might be some easier way to do it ;)

**Comment by matozoid** [comment]
Can you show me the code so I can see what you have, and what you're trying to do to it?

**Comment by PELock** [comment]
Will try the suggested approach and if fail I will come back :)

**Comment by matozoid** [comment]
Well, I guess it worked :-)
