### ISSUE TITLE
Resolving lambda fails - lambdas that use their input parameter

### ISSUE THREAD

**Issue by gilyerm** [javaparser/javaparser#2123]
trying to resolve `MethodCallExpression`s over this input block:
```
package test_p;

import java.util.Optional;
import java.util.function.Predicate;

public class Boo {
	
	public static <B> Predicate<Optional<Object>> method1(Class<B> typeB) {
        return parent -> typeB.isAssignableFrom(parent.get().getClass());
    }

    public static <B> Predicate<Optional<Object>> method2(Class<B> typeB) {
        return (Optional<Object> parent) -> typeB.isAssignableFrom(parent.get().getClass());
    }
}
```

yields this error:
`java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: typeB.isAssignableFrom(parent.get().getClass()), Parameter: parent.get().getClass() ...`

and this is true of both calls, while being an ok java syntax, being that java knows the return type is reffering to an Predicate<Optional<Object>>, thus the expression `parent.get()` must be using the symbol `parent` as an `Optional<Object>` ...

this happens regardless of using:
```
JavaParserFacade
    .get(myTypeSolver)
    .solve(methodCall, true);  // same with false
//or
methodCall.resolve()
```
and having already set the typeSolver in the configuration.

any thoughts?

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by ftomassetti** [comment]
I am not sure, what I know is that solving the type of lambdas is complicated as there is a sort of cycle in the resolution process

**Comment by matozoid** [comment]
Okay, then we need someone who wants to dive into this.

**Comment by maartenc** [comment]
I saw a similar issue in my code some time ago, I've tried to create a PR for it, but I gave up because it was too complicated for me. But maybe with this simple testcase and with some help from @ftomassetti or @matozoid it could be fixed.

**Comment by jlerbsc** [comment]
There is no more issue in current version. This test case 

    String code = 
                "import java.util.Optional;\n" + 
                "import java.util.function.Predicate;\n" + 
                "\n" + 
                "public class Boo {\n" + 
                "    \n" + 
                "    public static <B> Predicate<Optional<Object>> method1(Class<B> typeB) {\n" + 
                "        return parent -> typeB.isAssignableFrom(parent.get().getClass());\n" + 
                "    }\n" + 
                "\n" + 
                "    public static <B> Predicate<Optional<Object>> method2(Class<B> typeB) {\n" + 
                "        return (Optional<Object> parent) -> typeB.isAssignableFrom(parent.get().getClass());\n" + 
                "    }\n" + 
                "}";
        
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(code);

        List<MethodCallExpr> exprs = cu.findAll(MethodCallExpr.class);
        exprs.stream().forEach(expr -> System.out.println(expr.toString() + " resolved to " +expr.resolve().getQualifiedSignature()));

produces

    typeB.isAssignableFrom(parent.get().getClass()) resolved to java.lang.Class.isAssignableFrom(java.lang.Class<? extends java.lang.Object>)
    parent.get().getClass() resolved to java.lang.Object.getClass()
    parent.get() resolved to java.util.Optional.get()
    typeB.isAssignableFrom(parent.get().getClass()) resolved to java.lang.Class.isAssignableFrom(java.lang.Class<? extends java.lang.Object>)
    parent.get().getClass() resolved to java.lang.Object.getClass()
    parent.get() resolved to java.util.Optional.get()
