### ISSUE TITLE
How to get the full path of the method

### ISSUE THREAD

**Issue by liuqu11** [javaparser/javaparser#2126]
Hello, there is a question to ask, currently I use the jdk8 javaparser-core version using 3.6.27, I can get the full path of the method when calling public void visit(MethodDeclaration n, Void ag), such as public Static void com.javaparser.main(java.lang.String) This format, thanks

**Comment by matozoid** [comment]
Hello! The best approach to finding the full path (qualified name) of something is using the symbol solver. The book has a chapter about using it.

(If it is only about the method itself, you can get away with using getParent() to find classes, and eventually prepend the compilation unit's package declaration)

**Comment by mufid** [comment]
[According to Javadoc standard](https://docs.oracle.com/en/java/javase/11/docs/specs/doc-comment-spec.html#link), you can mention a method by using this format:

    package.class#member

If that name is the target you want to achieve, you can use following example code

    String getFullMethodName(CompilationUnit cu, MethodDeclaration method) {
        String packageClassPrefixWithDot = cu.getPackageDeclaration()
            .map(PackageDeclaration::getName)
            .map(Name::asString)
            .map(x -> x + ".")
            .orElse("");

        String className = method.getParentNode().map(x -> (ClassOrInterfaceDeclaration) x)
            .map(NodeWithSimpleName::getNameAsString)
            .orElse("");

        String fullName = new StringBuilder().append(packageClassPrefixWithDot)
            .append(".")
            .append(className)
            .append(".")
            .append(method.getNameAsString())
            .toString();

        return fullName;
    }

Try that out:

    CompilationUnit cu = StaticJavaParser.parse(file.toPath())
    List<MethodDeclaration> method = cu.findAll(MethodDeclaration.class).get(1);
    System.out.println(getFullMethodName(cu, method)) // my.exampleklass.getName
