### ISSUE TITLE
How can I change the encoding when I use sourceRoot.tryToParseParallelized()?

### ISSUE THREAD

**Issue by songyunseok** [javaparser/javaparser#2129]
SourceRoot sourceRoot = new SourceRoot(projectRoot.resolve(root));
List<ParseResult<CompilationUnit>> parseResults = sourceRoot.tryToParseParallelized();

How to change encoding?

**Comment by matozoid** [comment]
Ha, good question! You can't right now. If you want to do this anyway, make a copy of the source of the class and modify it for yourself.

**Comment by matozoid** [comment]
I think the best way to implement this is to add a character set setting to `ParserConfiguration`...

**Comment by songyunseok** [comment]
Thank you for your cooperation
