### ISSUE TITLE
Variables declared outside of a nested BlockStmt are not resolved 

### ISSUE THREAD

**Issue by jjbr** [javaparser/javaparser#2132]
`BlockStmtContext`'s `solveSymbol(String)` only calls the parent's `solveSymbol(String)` method when called. The contexts outside of a `BlockStmt` seem to handle everything from there, which works fine in most cases. However, nested block statements are an issue:
``` 
String s = "";
{
    s.length();
}
```

The `MethodCallExpression` `s.length()` cannot be resolved here, as `s` is not found, I believe because the `BlockStmtContext` does not quite enough itself. Pull request will be up in a couple of minutes too :)

**Comment by matozoid** [comment]
Thanks! @ftomassetti ?

**Comment by ftomassetti** [comment]
The block is a bit of a mess to solve because it should only look at statements _above_ the current statements. To such statements it should ask which elements do they expose. This is one of the tricky parts of the symbol resolution process

**Comment by matozoid** [comment]
@ftomassetti can you point to where things should be improved?

**Comment by ftomassetti** [comment]
probably SolveSymbol in BlockStmtContext should be overriden to consider also preceeding siblings perhaps calling `localVariablesExposedToChild`
