### ISSUE TITLE
ClassOrInterfaceDeclaration addMember using index

### ISSUE THREAD

**Issue by moraispgsi** [javaparser/javaparser#2137]
Hi, currently I am not able to place a class  inside another class in a particular index. When I try getMembers() and add the class to the collection the indentation breaks. I think the library needs a method overload e.g. addMember(int index, ...).

**Comment by matozoid** [comment]
Hi! "The indentation breaks" is not a very useful bug report, do you have some (runnable) code that demonstrates the problem?

**Comment by moraispgsi** [comment]
I agree. Basically I add the class to another class and the first line of the class that I am trying to add has no indentation. No, I don't have runnable code yet.

**Comment by matozoid** [comment]
Who is doing the indenting? The LexicalPreservingPrinter or the toString pretty printer?

**Comment by moraispgsi** [comment]
The LexicalPreservingPrinter, sorry for the delayed response.

**Comment by matozoid** [comment]
Ahhh, so we have a bug report on the lexical preserving printer. That's not totally unexpected: https://github.com/javaparser/javaparser/labels/Lexical%20Preservation

**Comment by quanturium** [comment]
I'm running into the same issue. When adding a field through classOrInterface.addField() the indentation works properly. However if I add a field through classOrInterfaceDeclartion.addMembers.add(position, field) the indentation does not work. It's even worse if the field is added between other fields (breaks indentation from the following field)

This reproduces everytime on LexicalPreservingPrinter.

Is there by any chance another way to add a field to a specific position that might preserve indentation like addField() does?

**Comment by matozoid** [comment]
As a workaround you can try adding all the members you want to a new `NodeList`, then setting that on the classOrInterface. Can you say if that works?

If you or @moraispgsi can make a PR with a testcase, that would be appreciated.

**Comment by moraispgsi** [comment]
I will happily provide the test case on the weekend @matozoid.

**Comment by quanturium** [comment]
@matozoid "then setting that on the classOrInterface" => How do I do that? setMembers(...) ?

I tried the following code:

```
NodeList<BodyDeclaration<?>> nodeList = new NodeList<>(classOrInterfaceDeclaration.getMembers());
nodeList.add(0, fieldDeclaration);
classOrInterfaceDeclaration.setMembers(nodeList);
```

The added field was not aligned properly (no indentation) unfortunately

**Comment by matozoid** [comment]
Okay, then we wait for someone to step up and fix the problem.

**Comment by jlerbsc** [comment]
Adding a test case.

    public class Issue2137extends AbstractLexicalPreservingTest  {
    @Test
    void test() {
        String EOL ="\n";
        String code = 
                "public class Foo {" + EOL +
                "  void mymethod1() {}" + EOL +
                "  void mymethod2() {}" + EOL +
                "}";
        String expected = 
                "public class Foo {" + EOL +
                "  void mymethod1() {}" + EOL +
                "  void mymethod3() {"+ EOL +
                "  }" + EOL +
                "  void mymethod2() {}" + EOL +
                "}";
        CompilationUnit cu = StaticJavaParser.parse(code);
        LexicalPreservingPrinter.setup(cu);

        ClassOrInterfaceDeclaration cid = cu.getClassByName("Foo").get();
        MethodDeclaration methodDeclaration = new MethodDeclaration();
        methodDeclaration.setName("mymethod3");
        methodDeclaration.setType(new VoidType());
        cid.getMembers().add(1, methodDeclaration);
        System.out.println(LexicalPreservingPrinter.print(cu));
        System.out.println(expected);

        TestUtils.assertEqualsStringIgnoringEol(expected, LexicalPreservingPrinter.print(cu));
    }
    }
