### ISSUE TITLE
2.2.3 Release Request

### ISSUE THREAD

**Issue by JanBessai** [javaparser/javaparser#214]
I'm currently implementing a wrapper of your AST from and to Scala (using case-classes there, so I can later work with the tree in [Kiama](https://bitbucket.org/inkytonik/kiama)). The [commit](https://github.com/javaparser/javaparser/commit/0429bcc9e404386bd6dfb6480a6ff2a7fb4882d0) to ensure that unused arguments are not `null` is extremely helpful for what I'm doing.
Could you please release a version including it? It would be great to be able to build against a published maven artifact.

**Comment by ftomassetti** [comment]
I also think that it is time for a new release: we had quite a few changes lately. I will ping the other contributors on the gitter channel.

**Comment by ftomassetti** [comment]
PR for preparing release in #215

**Comment by JanBessai** [comment]
This is great, thanks :+1:

**Comment by ftomassetti** [comment]
This has been released as JavaParser 2.3.0. Available in the best repositories since... now.
