### ISSUE TITLE
Change encoding question

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javaparser#2157]
Hello,

I am using JavaParser in one of my projects and the project gets used on a server that (needs to) starts the program with encoding "utf-32". I am currently using JavaParser version 3.8.3 (since I didnt want to deal with all the breaking changes) and it uses the default "utf-8" encoding. It basically breaks the whole thing. I saw that the newer version allows the encoding to be set via the ParserConfiguration, which would require me to upgrade the JavaParser version. Is there a way to change encoding to "utf-32" in the older version? Or do I have to/should just upgrade?

**Comment by matozoid** [comment]
The option has always been there in the various "parse" methods. It's only SourceRoot where it couldn't be changed. Then again, next to the breaking changes there are also bug fixes - if you want some help upgrading just ask on Gitter.

**Comment by un0btanium** [comment]
I am using the `SourceZip` class to read .jar files. And from what I have seen I cant set the encoding there, can I?
Its not really an issue not to upgrade. I just would have to sit down for an hour or two and make all the changes required. Just wanted to know if there is an option already, then I would have had a quick fix and wouldnt have to do that now ;)

**Comment by un0btanium** [comment]
Since I need the project in "production" next week and dont want to have something break, because of this, I just copied the methods out of `SourceZip` and `Provider` to set the encoding to UTF-8 myself. For now, this seems to does the trick. I will upgrade on a later date.

```
private List<Pair<Path, ParseResult<CompilationUnit>>> parseWithUTF8(SourceZip sourceZip, ParserConfiguration parserConfiguration) throws IOException {
	List<Pair<Path, ParseResult<CompilationUnit>>> results = new ArrayList<>();
    parseUTF8(sourceZip, parserConfiguration, (path, result) -> results.add(new Pair<>(path, result)));
    return results;
}

private void parseUTF8(SourceZip sourceZip, ParserConfiguration parserConfiguration, Callback callback) throws IOException {
	final Charset UTF8 = Charset.forName("utf-8"); 
	JavaParser javaParser = new JavaParser(parserConfiguration);
	    try (ZipFile zipFile = new ZipFile(sourceZip.getZipPath().toFile())) {
	        for (ZipEntry entry : Collections.list(zipFile.entries())) {
	            if (!entry.isDirectory() && entry.getName().endsWith(".java")) {
	            final ParseResult<CompilationUnit> result = javaParser.parse(COMPILATION_UNIT,
	                    provider(zipFile.getInputStream(entry), UTF8));
	            callback.process(Paths.get(entry.getName()), result);
	        }
	    }
	}
}
```

**Comment by un0btanium** [comment]
And I just realized I didnt had to do that because it already uses utf-8 because my bug was on an entire different portion in my code... thats just unfortunate xD

**Comment by matozoid** [comment]
Oooookay! :-D Glad to help :-)

**Comment by un0btanium** [comment]
Thanks. By the way, I appreciate your fast responses even on weekends! :+1:
