### ISSUE TITLE
NodeWithStatements without visitors?

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#2159]
Is it possible to visit all nodes of NodeWithStatements types?

Accessing only BlockStmt leaves other blocks with statements like SwitchStmt, I would like to visit all of those in one visitor.

PS. I read the book, but I wish the documentation was more complete.

**Comment by ftomassetti** [comment]
I would simply traverse the tree using getchildren and then filter them
with isInstanceOf

**Comment by matozoid** [comment]
We have the find methods for that now.
