### ISSUE TITLE
Use of Java 8 Optional

### ISSUE THREAD

**Issue by JanBessai** [javaparser/javaparser#216]
I think the API might get much cleaner, if you used Java 8 [Optionals](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) instead of `null`. The rational is explained [here](http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html). A good showcase is [MethodCallExpr](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java), which doesn't give any hints that its scope argument might be `null`.

**Comment by ftomassetti** [comment]
This is currently not possible because JavaParser is compatible with JDK6+
While it could make sense in the future move to Java 8 at the moment we decided to support those older versions of the JDK

**Comment by alechenninger** [comment]
A good compromise is to use JSR-305 annotations such as `@Nullable`

**Comment by ftomassetti** [comment]
thanks @alechenninger we will look into that

**Comment by matozoid** [comment]
We're now actually upgrading to 8, see #371 , so this is relevant again.

**Comment by matozoid** [comment]
I used one in #447 ;-)

**Comment by matozoid** [comment]
Closing in favour of #451

**Comment by matozoid** [comment]
Can be tested in alpha 5 :)
