### ISSUE TITLE
Improvment: empty node detection

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2161]
Hi,
It could be interesting to have a method to test if a body is empty on all nodes which can have body (for exemple NodeWithBody, NodeWithBlockStmt... I'm not sure it's the only ones).
isEmpty() exists for NodeWithBlockStmt but but does not exist on NodeWithBody so we have to define a method like it:

    default boolean hasEmptyBody(NodeWithBody n) {
		Statement body = ((NodeWithBody) n).getBody();
		return body.getChildNodes().size() == 0 && !EmptyStmt.class.isAssignableFrom(body.getClass());
	}

I'm not sure this statement is correct!

**Comment by matozoid** [comment]
Good idea, thanks!

**Comment by matozoid** [comment]
(`NodeWithBody, NodeWithBlockStmt` - these are not nodes, by the way. They are interfaces that are put on nodes so that they get some default behaviour. Also, if you find you need an isEmpty, there is probably a NodeList on the node that you can check for isEmpty instead.)

**Comment by jlerbsc** [comment]
You're probably right, but what about EmptyStmt. Sometimes it could be a child. Do you think the following statement is empty or not?

    if (myVar == 4)
    {
        // Do nothing because of X and Y 
    };

**Comment by matozoid** [comment]
The answer to that is in the Javadoc for EmptyStmt. Here, it is among the documentation links: https://javaparser.org/getting-started/, or use your IDE.

**Comment by matozoid** [comment]
Ah, I get your point with the if statement now.

**Comment by matozoid** [comment]
Sorry for my dumb remarks in this issue, I see I've missed several more points now :-)

**Comment by jlerbsc** [comment]
it does not matter. Thanks for your response
