### ISSUE TITLE
JavaSymbolSolver is unable to solve generic method return types

### ISSUE THREAD

**Issue by pgrepds** [javaparser/javaparser#2162]
I'm trying to solve the generic return type of a `MethodCallExpr`. 

e.g.: `getView().getTest()`, where `getView()` returns `V` with the superclass `AWT.Component`.

 I'm using `JavaParserFacade.solve(methodCallExpr).getCorrespondingDeclaration().getReturnType()`, where `methodCallExpr` is the expression above (`getView().getTest()`).

`getView()` is resolved in the type `AWT.Component`, which does not obviously has a method called `getTest`.

I get `java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call`.

**Comment by matozoid** [comment]
So this is your base class?

```java
abstract class Screen {
    abstract <V extends java.awt.Component> V getView();
}
```

**Comment by pgrepds** [comment]
Yes, exactly. And V has a method, which is not available in Component.

**Comment by matozoid** [comment]
This?
```java
import java.awt.*;

abstract class Screen {
    abstract <V extends Component> V getView();
}

class D extends Component {
    void test() {
    }
}

class B extends Screen {
    @Override
    D getView() {
        return new D();
    }
}
```

**Comment by matozoid** [comment]
Or maybe this?

```java
import java.awt.*;

abstract class Screen <V extends Component> {
    abstract V getView();
}

class D extends Component {
    void test() {
    }
}

class B extends Screen<D> {
    @Override
    D getView() {
        return new D();
    }
}
```

**Comment by pgrepds** [comment]
It's the second one.

**Comment by MysterAitch** [comment]
I've spent some time on this and my conclusion is that the issue described has presumably been solved since being posted (or I have misunderstood the problem) as I have not been able to replicate it.

Extending @matozoid 's code above, I have been using the following example code sample to run tests against (evaluating the output of the method calls in the class `Run`).

I'll submit a testcase PR shortly to show tests using this code sample passing.

```java

import java.awt.*;

abstract class Screen <V extends Component> {
    abstract V getView();
}

class D extends Component {
    void getTest() {
    }
}

class B extends Screen<D> {
    @Override
    D getView() {
        return new D();
    }
}

class Run {
    public static void main(String[] args) {
        B b1 = new B();
        b1.getView(); // b1.getView() -> B#getView(), overriding Screen#getView() -> returns object of type D.
        
        // Note that if `b2.getView` is parsed as Screen#getView (as B extends Screen), it will return type `V extends Component` thus will fail to locate the method `Component#getTest()` 
        B b2 = new B();
        b2.getView().getTest(); // b2.getView() -> returns object of type D, per above // D#getTest returns void.
        
        // This part is expected to fail as D#getView does not exist (where D is of type `V extends Component`)
        B b3 = new B();
        b3.getView().getView(); // b3.getView() -> returns object of type D, per above // D#getView doesn't exist, thus resolution will fail.
    }
}
```

**Comment by matozoid** [comment]
According to @MysterAitch this is solved. If it is not, please reopen :-)
