### ISSUE TITLE
TypeDeclaration is not a DocumentableNode

### ISSUE THREAD

**Issue by olivergondza** [javaparser/javaparser#217]
What I am trying to do is following:

``` java
for (TypeDeclaration t: compilationUnit.getTypes()) {
    t.getJavaDoc();
}
```

**Comment by ftomassetti** [comment]
TypeDeclaration is not documentable but all of its subclasses are DocumentableNode. It could make sense to make it implement DocumentableNode directly for this specific usage scenario.

Thanks for reporting this!
