### ISSUE TITLE
Special characters in annotation

### ISSUE THREAD

**Issue by sazonovm** [javaparser/javaparser#2173]
Hello! 
How can i use a special characters ('{', '}', '@' etc) in addSingleMemberAnnotation() method? 

`classDeclaration.addSingleMemberAnnotation("annotation", "{ @Test() }");`

Help, please.

**Comment by matozoid** [comment]
Hi!

Here is the answer to the general question "what does the AST for this piece of code look like": https://javaparser.org/inspecting-an-ast/

If you know this, you can construct the same thing with the constructors and setters of the nodes you need. If you feel it is too verbose, you can see if there are utility methods that can help (like `addSingleMemberAnnotation`.)

**Comment by sazonovm** [comment]
Hi, ty for answer!

I can't find StaticJavaParser, is it available in 3.12.0 version? JavaParser contains certain words for parsing and is not suitable for my case, cuz i cant use other words in annotation value.

I resolved my issue with next code:
`classDeclaration.addSingleMemberAnnotation("Test", "test");
   classDeclaration.getChildNodesByType(SingleMemberAnnotationExpr.class).get(typeClass.getChildNodesByType(SingleMemberAnnotationExpr.class).size() - 1)
.getChildNodesByType(NameExpr.class).get(0)
.getChildNodesByType(SimpleName.class).get(0)
.setIdentifier("@Test({ @test1, @test2})");`

**Comment by matozoid** [comment]
Check https://github.com/javaparser/javaparser/blob/master/changelog.md - it was added in 3.13.0.

That's a really awful solution, but I'm happy it works for you :-) Do try to read the article I linked, it will give you a much better idea of what you're doing.

**Comment by sazonovm** [comment]
i'm agree, that's awful, but it's working) 
will try to fix it.
Thanks for help
