### ISSUE TITLE
Add new semantic enhanceXxx methods for modify node more safety

### ISSUE THREAD

**Issue by johan-sun** [javaparser/javaparser#2177]
for example：

```java
Expression left = expr.getLeft();
Expression right = expr.getRight();
expr.setLeft(BoxUnboxUtil.tryUnbox(left));
```
the BoxUnboxUtil  is my util class to  wrap a method call (eg: `.intValue()`) expression for exists expression . 

when construct the MethodCallExpression using `left`, it  will first `setParentNode` to the MethodCallExpression. 

But the `expr.setLeft(...)` will  first run `this.left.setParentNode(null)` , then update the MethodCallExpression parent node to `this` . Finally, the `left` expression's parentNode is null.

If there possible to add enhanceXxx  methods to each subclass of Node , to help avoid the trouble？
```java
expr.enhanceXxx(BoxUnboxUtil::tryUnbox)
```
resetLeft looks like : 
```java 
Expression enhanceLeft(Function<Expression, Expression> mapper) {
    //do not setParentNode null, because the mapper is transformed using the left expression
    //if the expression is wrap by another expression, setParentNode(null) will cause
    //some node has no parent.
    //if (this.left != null) 
           // this.left.setParentNode(null);
    this.left = mapper.apply(this.left);
    setAsParentNodeOf(this.left);
    return this;
}
```
resetXxx mean using a exist node to construct a new node then  modify the owner， it will not set parent null for the children node.

**Comment by matozoid** [comment]
Hi! I'm not sure what's going on here. Parent node management is automatic when using the setters, so I don't know why you're using `setParentNode` all the time?

**Comment by johan-sun** [comment]
```java
@Generated("com.github.javaparser.generator.core.node.PropertyGenerator")
    public BinaryExpr setLeft(final Expression left) {
        assertNotNull(left);
        if (left == this.left) {
            return (BinaryExpr) this;
        }
        notifyPropertyChange(ObservableProperty.LEFT, this.left, left);
        if (this.left != null)
            this.left.setParentNode(null);
        this.left = left;
        setAsParentNodeOf(left);
        return this;
    }
```
`setParentNode(null);`is inside the setter， expression like `expr.setLeft(new MethocCallExpr(expr.getLeft(), methodName));` will cause the  `scope`  expression has null parent. 

Next parse, I will `calcultiResolvedType()`, it will cause `java.lang.IllegalStateException: The node is not inserted in a CompilationUnit` 

The problem is the construct of `MethocCallExpr` will automatic manage the score‘s parent node, the `setLeft` auto manage set the parentNode of `this.left` to null.  Double management cause  the node has no parentNode.

It has many way to solve it, but I think,  JavaParser can provider more convenience methods to avoid this trouble.

**Comment by matozoid** [comment]
Oh! I think I get it. In general: if you want to use a "detached" piece of the AST without affecting the original AST, `clone()` the nodes.

`expr.setLeft(new MethocCallExpr(expr.getLeft().clone(), methodName));`

In my opinion that is very straightforward.

**Comment by matozoid** [comment]
No more replies, assuming this is solved.
