### ISSUE TITLE
Cannot make a static reference to the non-static method parse(File) from the type 

### ISSUE THREAD

**Issue by askary94** [javaparser/javaparser#2181]
Hello.
I make jar file of JavaParser and I want to run example How to extract the name of all classes in a normal String from java class? in [https://tomassetti.me/getting-started-with-javaparser-analyzing-java-code-programmatically/](url)
but I conflict with error Cannot make a static reference to the non-static method parse(File) from the type? why JavaParser Class don't know Parse method `(JavaParser.parse(file))?` Please Help me...

`import java.io.File;
import java.io.IOException;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseException;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.google.common.base.Strings;

public  class ListClassesExample {
	
	public static void listClasses(File projectDir) {
        new DirExplorer((level, path, file) -> path.endsWith(".java"), (level, path, file) -> {
            System.out.println(path);
            System.out.println(Strings.repeat("=", path.length()));
            try {
                new VoidVisitorAdapter<Object>() {
                    @Override
                    public void visit(ClassOrInterfaceDeclaration n, Object arg) {
                        super.visit(n, arg);
                        System.out.println(" * " + n.getName());
                    }
                }.visit(JavaParser.parse(file), null);
                System.out.println(); // empty line
               } catch (ParseException | IOException e) {
                new RuntimeException(e);
            }
        }).explore(projectDir);
    }
	`

Thanks!

**Comment by askary94** [comment]
now I understand that problem of The method visit(ClassOrInterfaceDeclaration, Object) but why you as first argument pass JavaParser?
Please help me to change code as work correctly.

> Hello.
> I make jar file of JavaParser and I want to run example How to extract the name of all classes in a normal String from java class? in [https://tomassetti.me/getting-started-with-javaparser-analyzing-java-code-programmatically/](url)
> but I conflict with error Cannot make a static reference to the non-static method parse(File) from the type? why JavaParser Class don't know Parse method `(JavaParser.parse(file))?` Please Help me...
> 
> `import java.io.File;
> import java.io.IOException;
> 
> import com.github.javaparser.JavaParser;
> import com.github.javaparser.ParseException;
> import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
> import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
> import com.google.common.base.Strings;
> 
> public class ListClassesExample {
> 
> ```
> public static void listClasses(File projectDir) {
>     new DirExplorer((level, path, file) -> path.endsWith(".java"), (level, path, file) -> {
>         System.out.println(path);
>         System.out.println(Strings.repeat("=", path.length()));
>         try {
>             new VoidVisitorAdapter<Object>() {
>                 @Override
>                 public void visit(ClassOrInterfaceDeclaration n, Object arg) {
>                     super.visit(n, arg);
>                     System.out.println(" * " + n.getName());
>                 }
>             }.visit(JavaParser.parse(file), null);
>             System.out.println(); // empty line
>            } catch (ParseException | IOException e) {
>             new RuntimeException(e);
>         }
>     }).explore(projectDir);
> }
> `
> ```
> Thanks!

**Comment by matozoid** [comment]
Hi! The article you're looking at is three years old and very outdated. The JavaParser book has a chapter that should help you a lot better: https://leanpub.com/javaparservisited

@ftomassetti can you put some time into updating your article?

**Comment by askary94** [comment]
Thank you so much for your response.
Oh, Yes I will read the book.

**Comment by matozoid** [comment]
No problem, good luck! If there are more problems, feel free to ask more.
