### ISSUE TITLE
Removing 2 nodes with the same parent fail

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2187]
In this block, if we try to remove 2 methodCallExpr (log), the second fail (nothing is happening) because it seems that the parent node of the ExpressionStmt is setted to null after the first remove. NodeList.remove invokes notifyElementRemoved() and after this method is called all statements of the BlockStmt have the parent set to null.

    catch (final Exception e) {
        log.error("context", e);
        log.warn("another context", e);
        throw new ApplicationException(e);
    }
Below the test case
I am not sure that this code is correct but I entrust this analysis to your expert eye

    @Test
	public void test1() throws ParseException {
		String sample = "{ try {/* empty */} catch (final Exception e) {\r\n" + 
				"    log.error(\"context\", e);\r\n" + 
				"    log.warn(\"another context\", e);\r\n" + 
				"    throw new ApplicationException(e);\r\n" + 
				"}}";
		JavaParser jp = new JavaParser();
		Statement stmt = jp.parseStatement(sample).getResult().get();
		stmt = LexicalPreservingPrinter.setup(stmt);
		BlockStmt bs = stmt.getChildNodesByType(CatchClause.class).get(0).getChildNodesByType(BlockStmt.class).get(0);
		remove(bs.getStatements().get(0));
    //		System.out.println(""+stmt.toString());
		remove(bs.getStatements().get(0));
    //		System.out.println(""+stmt.toString());
	}
	// remove the node and parent's node until response is true
	boolean remove(Node node) {
		boolean result = node.remove();
		if (!result && node.getParentNode().isPresent())
			result = remove(node.getParentNode().get());
		return result;
	}

**Comment by matozoid** [comment]
Are you on the latest version? What is the setup you are using? Please give more information!

**Comment by jlerbsc** [comment]
I'm using javaparser-symbol-solver-core 3.13.6 and no custom setup except i setup LexicalPreservingPrinter with compilation unit. I will try to provide you a test case.

**Comment by matozoid** [comment]
Thanks for the test case!

**Comment by jlerbsc** [comment]
I'm not sure but it seems that in LexicalDifferenceCalculator.calculatedSyntaxModelAfterListRemoval(), JavaParser try to return a new ListNode from the current list of nodes. The add method calls own() which try to set the parent of the node (setAsParentNodeOf()) and getParentNodeForChildren() return null. So the parent of each nodes is setted to null. The method getParentNodeForChildren() returns null because the new list is not initialized at this stage so there is no parent defined.
Perhaps this could help to resolve this issue. I'm waiting for a solution ;-)

**Comment by matozoid** [comment]
If you manage to define what the correct approach would be, you can make a PR :-)

**Comment by jlerbsc** [comment]
it's only a suggestion... I don't know what is the correct approach.

**Comment by jlerbsc** [comment]
In class com.github.javaparser.printer.lexicalpreservation.changes.ListRemovalChange

previous

    @Override
    public Object getValue(ObservableProperty property, Node node) {
        if (property == observableProperty) {
            NodeList<Node> nodeList = new NodeList<>();
            Object currentRawValue = new NoChange().getValue(property, node);
            if (!(currentRawValue instanceof NodeList)){
                throw new IllegalStateException("Expected NodeList, found " + currentRawValue.getClass().getCanonicalName());
            }
            NodeList<?> currentNodeList = (NodeList<?>)currentRawValue;
            nodeList.addAll(currentNodeList);
            nodeList.remove(index);
            return nodeList;
        } else {
            return new NoChange().getValue(property, node);
        }
    }

suggestion

    @Override
    public Object getValue(ObservableProperty property, Node node) {
        if (property == observableProperty) {
            NodeList<Node> nodeList = new NodeList<>();
            Object currentRawValue = new NoChange().getValue(property, node);
            if (!(currentRawValue instanceof NodeList)){
                throw new IllegalStateException("Expected NodeList, found " + currentRawValue.getClass().getCanonicalName());
            }
            NodeList<?> currentNodeList = (NodeList<?>)currentRawValue;
            // set the parent node in the new list
            nodeList.setParentNode(node);
            nodeList.addAll(currentNodeList);
            nodeList.remove(index);
            return nodeList;
        } else {
            return new NoChange().getValue(property, node);
        }
    }

**Comment by matozoid** [comment]
Thanks! I'll give it a try tonight. Maybe you can check if it fixes your test case?

**Comment by jlerbsc** [comment]
I made a PR, the issue is resolved for the test case.

**Comment by matozoid** [comment]
Thanks so much!
