### ISSUE TITLE
Unable to resolve enum

### ISSUE THREAD

**Issue by v95** [javaparser/javaparser#2193]
I came across this when I was parsing two files (A.java and AppConstant.java):

App.java:

```
package a.b;
import a.c.AppConstant;
public class App implements AppConstant {
    public void doStuff(AppType type) {
        myFunc(type.getData());
    }
}
```
AppConstant.java:

```
package a.c;
public interface AppConstant {
    public enum AppType {
        CONFIG("CONFIG");
        public String getData() {
            ....
        }
    }
}
```

The code to resolve it is pretty straight forward:

```
CompilationUnit c = ...
for (MethodDeclaration dec : c.findAll(MethodDeclaration.class) {
    String qualifiedSig = [...].getQualifiedSignature(); // UnsolvedSymbolException on AppType
    for (MethodCallExpr e : dec.findAll(MethodCallExpr.class)) {
        e.resolve(); // UnsolvedSymbolException on type.getData()
    }
}
```

I'm getting all Method Calls in `App.doStuff` and resolving them. I'm also getting the qualified signature of `App.doStuff` (which makes it `resolve` as well). The problem is, I get an `UnsolvedSymbolException` on `AppType`/`type` when I try to resolve either one of them. The code seems to be valid (and the IDE does not have any issues resolving the types either), so is this a bug in the parser?

**Comment by matozoid** [comment]
Thanks! Yes, probably.

**Comment by qingdujun** [comment]
I have encountered the same problem.

 Is this problem solved?

**Comment by matozoid** [comment]
Hi @qingdujun, it is not. Can you help?

**Comment by jlerbsc** [comment]
It seems to be resolved 

    public class Issue2193Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {
        final Path testRoot = adaptPath("src/test/resources/issue2193");
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(testRoot);
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(reflectionTypeSolver, javaParserTypeSolver);
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
        StaticJavaParser.setConfiguration(configuration);

        String src = 
                "package a.b;\n" + 
                "import a.c.AppConstant;\n" + 
                "public class App implements AppConstant {\n" + 
                "    public void doStuff(AppType type) {\n" + 
                "        type.getData();\n" + 
                "    }\n" + 
                "}";

        CompilationUnit cu = StaticJavaParser.parse(src);

        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
        mces.forEach(mce-> {
            System.out.println(mce.calculateResolvedType().describe());
        });
        
        MethodDeclaration md = cu.findFirst(MethodDeclaration.class).get();
        System.out.println(md.resolve().getQualifiedSignature());

    }
    }

result

    java.lang.String
    a.b.App.doStuff(a.c.AppConstant.AppType)
