### ISSUE TITLE
Question about access all subclasses

### ISSUE THREAD

**Issue by WaterWan** [javaparser/javaparser#2194]
Hi! I am new to javaparser, and I am using this to help fill up the parameters in an incomplete API call.

For example:
```java
public class B {
	public void methodInB(int a, int b, B b2) {
		int mx = a > b ? a : b;
		System.out.println(mx);
	}
	public void methodInB2() {
		System.out.println("hello");
	}
}
```

```java
public class A {
	public static void main(String[] args) {
		B b = new B();
		int x = 1;
		int y = 2;
		b.methodInB2();
		b.methodInB();
	}
}
```
```java
public class BSon1 extends B {

}
public class BSon2 extends B {

}
```

In this example, it is obvious that the `b.methodInB()` in class A lacks parameters, when the parameter is not a primitive, the third parameter can be a B, or a BSon1, or a Bson2. Now, I can find out the incomplete call of methodInB(), I can also find out the required types, **but I don't know how to find all subclasses of B, I know I may use `isAssignableBy`, but I just don't know how to find out the parameter.**

What I do now is this:
```java
for(MethodCallExpr mce : methodCallExprs) {
        	try{
        		System.out.println(mce.resolve().getQualifiedSignature());
        		System.out.println(mce.resolve().declaringType().getId());
        		System.out.println(mce.resolve().getSignature());
        	} catch (Exception e) {
        		String methodName = mce.getNameAsString();
				System.err.println(methodName);
				String name = mce.getScope().get().asNameExpr().resolve().getType().describe();
				System.err.println(name);
				ResolvedReferenceTypeDeclaration resolvedReferenceTypeDeclaration = typeSolver.solveType(name);
				Set<MethodUsage> methodUsages = resolvedReferenceTypeDeclaration.getAllMethods();
				for(MethodUsage methodUsage : methodUsages) {
					if(methodUsage.getName().equals(methodName)) {
						List<ResolvedType> paramTypes = methodUsage.getParamTypes();
						for(ResolvedType paramType : paramTypes) {
							System.out.println(paramType.describe());
							System.out.println(paramType.isPrimitive());
							System.out.println(paramType.isAssignableBy());
						}
					}
				}
				
				// ===========================================================
			}
        }
```

**Comment by matozoid** [comment]
Hi! The subclasses can be found by going through all your classes and seeing if they extend your B class.

@ftomassetti correct me if I'm wrong.

**Comment by WaterWan** [comment]
I think you are right! Thank you very much!

I was thinking that: I can find out all subclasses and then find out all objects of these subclasses and use them to fill the parameters.

However, I think out a new way:
I now know that `b.methodInB()` in class A lacks parameters, now if I can get all **accessible** arguments, such as b, x and y in main method, I can compare the type of the arguments with the types that `b.methodInB()` needs. I am working on this.
