### ISSUE TITLE
how can I replace comment with code 

### ISSUE THREAD

**Issue by MatejBanas** [javaparser/javaparser#2198]
Hello, I would like to ask if there is any functionality that would allow me to replace comment with a code, for example, after finding a specific **LineComment** it gets replaced with **MethodCallExpr**. I have tried using **.replace()** but it fails and I cant figure it out. Thank you

```
compilationUnit.getComments().stream()
    .filter(c -> c.getContent().contains("PERFTRAP"))
    .forEach(c -> c.replace(JavaParser.parseStatement("PM.check(PMC.TRAP_methodName_0);")));
```

**Comment by matozoid** [comment]
Hi! Comments are not really part of the AST, so you have to ask a comment what its associated node is, then remove it, then add something near the associated node.

**Comment by MatejBanas** [comment]
Hi, thank you for the help I will try that, if I can ask another question, how could I do the exact opposite? Meaning, how can I replace a piece of code with a comment, if I add it as a comment to a node and then remove the node, the comment gets also removed, if I add it as an orphan comment, how can I ensure that it will be placed in the correct place? Thank you.

**Comment by matozoid** [comment]
In theory you could use an orphan comment and put its (line/column) position to the place where you want it. In practice there are bugs here and sometimes these comments disappear - especially in weird locations. But it's worth a try.

If it's a very specific thing you're trying to do, you can always extend or copy the PrettyPrintVisitor and add what you want to add.

**Comment by ghost** [comment]
@matozoid  @MatejBanas  Hi, I'd like to know  why when I call JavaParser. parseStatement, the Ideal always say ```non static method cannot be referenced from a static context```

**Comment by MatejBanas** [comment]
Hey, I think it is because the code example that I used is using an old version of JavaParser, if you use the newest version the syntax will be different

**Comment by matozoid** [comment]
@Kisen-Chin - where did you find the suggestion to write code like that? It might be an example we need to update.

(Please open a new issue next time, by the way :-) )

**Comment by edefazio** [comment]
As an alternative to using comments alone to signify some optional code change (i.e. to optionally add some logging, etc. at certain points in the code) You might use empty Java labeled statement blocks (i.e. label:{}) containing comments like so:
```java
class F{
    void m(int i){
        $log:{/*System.out.println("optional code running");*/}
        $log2:{
              /*System.out.println("multi-statement");*/
              /*System.out.println("optional code");*/
        }
    }            
}
```

...then you can write a scanner to find and replace the labeled statements containing comments 

```java
        TypeDeclaration td = /...code for getting/creating TypeDecl*/
        td.walk(LabeledStmt.class, ls-> {
            if( ls.getLabel().asString().startsWith("$") && ls.getStatement().isBlockStmt()){
                BlockStmt bs = (BlockStmt)ls.getStatement();
                List<Comment> comments = bs.getOrphanComments();
                List<Statement> sts = new ArrayList<>();
                comments.forEach(c -> sts.add( StaticJavaParser.parseStatement(c.getContent())) );
                if( sts.size() == 1 ){
                    ls.replace( sts.get(0) );
                } else{
                    BlockStmt bsn = new BlockStmt();
                    sts.forEach(s -> bsn.addStatement(s));
                    ls.replace( bsn );
                }
            } 
        });
        
        System.out.println(td);
```

I use a specific prefix for the labels, (something like $ or _) so it's easy to scan the code & then find where the labeled statements intended to be replaced are...
then I can replace them with code that is within the comment:

so this acts like what you want ... with a little extra verbiage, but you aren't reliant on worrying about the ordering ...you know exactly where the statement(s) may go.

just a thought.
