### ISSUE TITLE
equals and hash code required to work with collections

### ISSUE THREAD

**Issue by vporoxnenko** [javaparser/javaparser#220]
let's say we have lines of code

final ClassOrInterfaceType c = new ClassOrInterfaceType("com.blabla.MyClass");
ClassOrInterfaceDeclaration type = ....
calling "type.getExtends().contains(c)" we'll never get "true" cos equals and hashCode methods are not declared for ClassOrInterfaceType

the same problem for other entities like BodyDeclaration, EnumDeclaration, etc

**Comment by matozoid** [comment]
Will eventually be fixed by https://github.com/javaparser/javaparser/issues/353

**Comment by matozoid** [comment]
This works now, so I assume this is fixed.
```java
final ClassOrInterfaceType c = new ClassOrInterfaceType("com.blabla.MyClass");
ClassOrInterfaceDeclaration type = new ClassOrInterfaceDeclaration().addExtends("com.blabla.MyClass");
boolean contains = type.getExtendedTypes().contains(c);
```
