### ISSUE TITLE
LexicalPreservingPrinter Difference Algorithm breaks indentation after adding identical statements. 

### ISSUE THREAD

**Issue by moraispgsi** [javaparser/javaparser#2203]
When using the LexicalPreservingPrinter, adding a statement identical to the previous statement breaks the Difference Algorithm because it confuses it, it makes it believe that the first statement was the one that was added, as a consequence the indentation breaks.

**Will be submitting a PR for this with a test case.**

**Comment by jlerbsc** [comment]
I close this issue because actually all these tests pass int the current version.
