### ISSUE TITLE
find by name functionality

### ISSUE THREAD

**Issue by vporoxnenko** [javaparser/javaparser#221]
I can't check does method have annotation I want or class extends interface I want in easy way. I should scan whole collection manually. I t would be nice to have method which will do that

**Comment by ftomassetti** [comment]
I agree but please consider that you would be able just to find classes which _directly_ implements a certain interface. To find classes which indirectly implement it you would need to resolve types, which is not the goal of JavaParser (it just produces an AST).

I think some utillity class with methods to find nodes on an AST would be useful but I am not sure it should be done in JavaParser or as an extension (hence a separate library using JavaParser).

Note that many of such operations can be performed reasonably easily using a visitor.

**Comment by vporoxnenko** [comment]
sure, parser shouldn't search sub-interfaces, but currently I have manual search only. I can't even use collection.contains(nameexpressioniwant), because of #220

**Comment by JamesXNelson** [comment]
It is often preferable to take the generated "raw" ast of a parser, and use that to construct a rich API where everything is mapped nicely to do type / annotation searches.

The parser should concern itself with just one thing: Correctly translating text into objects representing the structure you are describing.  Assembling type maps of all interfaces (and subinterfaces) is beyond the scope of what a text processing tool should be doing.  

I am using javaparser to create such a rich API, complete with builders to more easily assemble generated code.  It's not ready for release yet, but the idea is that the rich, expensive, editable API is created on demand by visiting the raw, parsed API.  When you ask for things, recursively parse and load all interfaces and subinterfaces / annotations / whatever you asked for...  Not a compiler by any means, but enough that I can query and assemble the java metamodel as needed. :-)

Also, another benefit of a different business model of your AST is that if you ever want to feed it java in a different format, like bytecode, you can map a completely different structure into the same model, manipulate it as if it were source (more or less), and emit a new copy of source.

**Comment by vporoxnenko** [comment]
got yours point
but #220 is still mandatory feature ))

**Comment by ftomassetti** [comment]
@JamesXNelson I agree with your vision and I encourage to release early your project. I have built myself something similar and perhaps we can collaborate in some way. In any case I think JavaParser could benefit from your project so I think we should help you promoting it. I hope to see it soon!

**Comment by JamesXNelson** [comment]
I will pick it back up over the holiday season, and I will be sure to tag you when it goes public.

Thanks!
