### ISSUE TITLE
Resolution of Method References

### ISSUE THREAD

**Issue by MassimilianoPoggi** [javaparser/javaparser#2210]
Hi,
  I can't find a way to resolve method references (such as System.out::println) anywhere. Is this not supported by the current version of JSS?
In the process of trying to implement something of the sort myself I've also noticed that JavaParser parses the left side of the method reference as a TypeExpr: isn't this incorrect behaviour, given that instances can be the scope of a method reference (such as the example provided above)?

**Comment by matozoid** [comment]
Hi! It might be related to #2160.

**Comment by MassimilianoPoggi** [comment]
While eventual problems in the resolution might be related to the mentioned issue, the problems I'm outlining in this issue are unrelated:

1. the MethodReferenceExpr class does not implement Resolvable at all
2. JavaParser is incorrectly parsing method references by automatically assuming the left side of the expression to be a TypeExpr, while it should be possible to also parse it as a NameExpr/FieldAccessExpr for cases where the left side is an instance and not a class.

**Comment by matozoid** [comment]
Sorry, I didn't mean to close it!

**Comment by scootafew** [comment]
I'm also facing the same problem and trying to investigate, @MassimilianoPoggi did you ever get anywhere with what you were trying to implement for this?

**Comment by MassimilianoPoggi** [comment]
@scootafew Being on a deadline at the time and noticing a few other problems within the tool I ended up using what seemed like a more mature alternative in [Spoon](https://github.com/INRIA/spoon). I'm sorry I can't be of further help with your problem.

**Comment by scootafew** [comment]
@MassimilianoPoggi no worries at all, thanks for the quick reply! :)

**Comment by matozoid** [comment]
Spoon uses the compiler libraries from Eclipse behind the scenes, so their symbol resolution is definitely more mature. JavaParser has other good things (like not secretly being Eclipse ;-) )

**Comment by jlerbsc** [comment]
@MassimilianoPoggi could you give us a test case to explore this issue?

**Comment by MassimilianoPoggi** [comment]
While I don't have time to write a fully-fledged test case, here's a snippet quickly reproducing the "parsing" issue (I'm not sure whether to label it as a parsing issue exclusively as I'm fairly certain you can't differentitate between field accesses and fully qualified type references without a resolution step in-between, e.g. `java.lang.Object::toString`, so maybe just not calling it `TypeExpr` could suffice as it would be less ambiguous)

```   
public static void main(String... args) {
        ParseResult<Statement> methodReference = new JavaParser()
                .parseStatement("Arrays.asList(1, 2, 3).forEach(System.out::println);");

        ParseResult<Statement> methodCall = new JavaParser()
                .parseStatement("System.out.println(\"5\");");

        System.out.println(methodReference.getResult().get().asExpressionStmt()
                .getExpression().asMethodCallExpr().getArgument(0).asMethodReferenceExpr()
                .getScope().getClass().getName());

        System.out.println(methodCall.getResult().get().asExpressionStmt()
                .getExpression().asMethodCallExpr().getScope().get().getClass().getName());
    }
```

As far as `MethodReferenceExpr` not implementing the `Resolvable<T>` interface, that seems fairly self-explainatory to me: it probably should implement `Resolvable<ResolvedMethodDeclaration>` just like `MethodCallExpr` does.

**Comment by matozoid** [comment]
I'll give "adding a resolve" method a try.

**Comment by matozoid** [comment]
Thanks for taking the time to reply @MassimilianoPoggi , by the way!
