### ISSUE TITLE
Rename local variables

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#2212]
I have stumbled upon this problem. I have 2 loops

```
for (int item : array)
{
 if (xx == 123)
 {
   sum1 += item; //processing
 }
}

for (int item : array)
{
 //processing
 sum2 += item; //processing
}

```
I want to rename 'item' in one loop to item_1 and item_2 in the other loop and all their references, right now I was doing it like this: 

1. enumerate all methods
2. enumerate all blocks within those methods
3. enumerate all VariableDeclarator within those blocks
4. gather all declarations and variables names with each block hash
5. rename variable name at the declaration point (I store new and old names)

then I was looking for the references to those variable declarations like this

1. enumerate all methods
2. enumerate all blocks
3. enumerate all NameExpr
4. try to match old and new variable names to rename them to the new names

BUT it has a flaw, since multiple variables can have the same name (like in those loops), I thought I could use BlockStmt hash value, but those references can be declared inside other blocks so I cannot use it while comparing old and new variable name references.

So, can you give me some hints on how to rename those local variables and all their references while keeping in mind the variable names can repeat within loops?

Should I use spoon for this kind of transformations (I don't want to since I already put a lot of work in my project using JavaParser)?

**Comment by matozoid** [comment]
Spoon is a good library that you can use. They may have this kind of stuff built in.

The question seems to be... "when a variable is declared in the `for` itself, like `for(int i: array)`, how can I detect this so I can create a new scope for it?" Is that correct? Scopes would be the areas where a variable name is valid and means the same thing, so in your example we would have two scopes.
