### ISSUE TITLE
Unable to Compiler JavaParser

### ISSUE THREAD

**Issue by aditi9292** [javaparser/javaparser#2213]
While compiling Javaparser using the command
>> mvn clean install
I get the following error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project javaparser-core-testing: There are test failures.
[ERROR]
[ERROR] Please refer to G:\Aditi New\Software Setups\javaparser-master\javaparser-master\javaparser-core-testing\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :javaparser-core-testing

I have added the required dependency. Please help me to resolve this.

**Comment by MysterAitch** [comment]
How did you download the project, and what are you hoping to do with it?

It looks like master builds fine according to the badge on the front page and the CI results of the latest few commits?

Perhaps you could share the test results and/or details of which tests are failing? 

Edit: I tried cloning and building the project - the first time around I had the same issue as above, but oddly haven't since been able to replicate it a second time and didn't catch the firsts set of logs before trying again. If you try again and still have the same issue, please do share the test logs.

**Comment by edefazio** [comment]
I just cloned and `mvn clean install` ed everything and it worked the first time for  me used:
_Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00)
Maven home: C:\Program Files\Java\maven\apache-maven-3.6.1\bin\..
Java version: 11.0.3, vendor: Azul Systems, Inc., runtime: C:\Program Files\Java\zulu11.31.11-ca-jdk11.0.3-win_x64\zulu11.31.11-ca-jdk11.0.3-win_x64
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"_

Reactor Summary for javaparser-parent 3.14.2-SNAPSHOT:
[INFO]
[INFO] javaparser-parent .................................. SUCCESS [  4.623 s]
[INFO] javaparser-core .................................... SUCCESS [ 41.716 s]
[INFO] javaparser-core-testing ............................ SUCCESS [01:00 min]
[INFO] javaparser-core-testing-bdd ........................ SUCCESS [ 18.436 s]
[INFO] javaparser-core-generators ......................... SUCCESS [  1.331 s]
[INFO] javaparser-core-metamodel-generator ................ SUCCESS [  0.632 s]
[INFO] javaparser-core-serialization ...................... SUCCESS [  4.000 s]
[INFO] javaparser-symbol-solver-model ..................... SUCCESS [  1.120 s]
[INFO] javaparser-symbol-solver-logic ..................... SUCCESS [  0.707 s]
[INFO] javaparser-symbol-solver-core ...................... SUCCESS [  6.344 s]
[INFO] javaparser-symbol-solver-testing ................... SUCCESS [01:52 min]

Worked the first time, no problems.

**Comment by matozoid** [comment]
Okay, this is on hold until someone manages to supply more information.

**Comment by jlerbsc** [comment]
No news it may not be worth keeping this issue open
