### ISSUE TITLE
getting meta information on chainned calls?

### ISSUE THREAD

**Issue by kartikpatodi** [javaparser/javaparser#2219]
Hi, I want to parse through a chained expression like

someObj
 .getSomeOtherObjList()
 .get(idx)
 .setSomeProperty("string")

is there a way to get the detailed information regarding this expression (possibly with types) ?

**Comment by kartikpatodi** [comment]
@matozoid 
@ftomassetti ?

**Comment by matozoid** [comment]
Hi!

The parser will give you the structure of the chain. The symbol solver will give you types.

Go read through https://javaparser.org/ and the book if you haven't done so.

**Comment by kartikpatodi** [comment]
I tried the example from the book and wrote this vistor adapter

 private static class ExpressionPrinter extends VoidVisitorAdapter<List<String>> {
        @Override
        public void visit(ExpressionStmt expr, List<String> collector) {
            super.visit(expr, collector);
            System.out.println(expr)
        }
    }

This provides me with a list od strings so I will get the expression as a String and not as a list of tokens?
Am I missing something?

**Comment by matozoid** [comment]
Please read https://javaparser.org/inspecting-an-ast/ - it will give you the knowledge to analyse how the AST you have is constructed. You can use it on `ExpressionStmt` for example. Once you know how a method call chain is represented in an AST, you can read some of the Javadoc of the specific nodes. Here is the Javadoc for https://static.javadoc.io/com.github.javaparser/javaparser-core/3.14.0/com/github/javaparser/ast/stmt/ExpressionStmt.html for example.

Once you know how the nodes are put together in the AST, you can think of how to traverse it to get the information you want.
