### ISSUE TITLE
Unable to use com.github.javaparser.printer.lexicalpreservation from OSGi

### ISSUE THREAD

**Issue by cdelg** [javaparser/javaparser#2221]
The `com.github.javaparser.printer.lexicalpreservation` and `com.github.javaparser.printer.lexicalpreservation.changes` packages are not exported, it prevents the use of `LexicalPreservingPrinter` in an OSGi context.

Is there another way to use this class?

**Comment by matozoid** [comment]
@cdelg, please wait for today's release where I add these :-)
