### ISSUE TITLE
Make a generator for the packages in bnd.bnd

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#2227]
These are often out of date for a long time, making JP only partially usable from OSGi.

**Comment by alessiostalla** [comment]
@matozoid I would like to lend a hand on this. I've already looked at generators. Were you thinking about a generator that writes the actual bnd.bnd file? Or would printing to stdout suffice, like the GrammarLetterGenerator does?

**Comment by matozoid** [comment]
Hi! Thanks for the offer. I think it would be best to do it automatically because it gets forgotten all the time. It shouldn't be too hard to put another one in here: https://github.com/javaparser/javaparser/blob/master/javaparser-core-generators/src/main/java/com/github/javaparser/generator/core/CoreGenerator.java

GrammarLetterGenerator would have been nice to automate too, but it has to output a very specific format right in the middle of the grammar - so printing to stdout is the lazy implementation (and it is unlikely that anybody will notice if it doesn't get run for a year or two)

**Comment by alessiostalla** [comment]
@matozoid thanks for the info. I will sketch an implementation and open a PR.

**Comment by MysterAitch** [comment]
#2394 seems to fix this -- can close this issue?
