### ISSUE TITLE
Difference between code and Javadoc, FieldDeclaration

### ISSUE THREAD

**Issue by vincentzalc** [javaparser/javaparser#2228]
Hi, 
It seems the 3.14.0 `FieldDeclaration` class does not implement `NodeWithAnnotations<FieldDeclaration>` which should allow to use `addAnnotation` according to the Javadoc.

Is it just me and it means my Maven is downloading another version and not the 3.14.0?
```
<dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
            <version>3.14.0</version>
</dependency>
```

I am working on unit tests and trying to generate at least a part of them automatically. To be more precise I am trying to add the `@Spy` annotation on one of my fields right now.

Thanks to all.

**Comment by matozoid** [comment]
Hi!
- NodeWithAnnotations is there, but it's on the superclass (BodyDeclaration). addAnnotation should be there?
- Maven does not download 3.14.0 when you specify 3.14.0? How do you mean? What's happening?

**Comment by vincentzalc** [comment]
Thanks for you answer.

To be more clear:

When I am writing is

//Creating spy field for the class under test 
 FieldDeclaration mainSpy = myClass.addField(cu.getPrimaryTypeName().get(), cu.getPrimaryTypeName().get() + "Spy");

mainSpy.addAnnotation => this does not autocomplete, it seems addAnnotation does not exists even though the javadoc says it should.

**Comment by vincentzalc** [comment]
Never mind,
Maybe it is my Eclipse: the autocompletion does not function but if i write it by hand itworks fine:
mainSpy.addAnnotation(new MarkerAnnotationExpr("Spy")); => ok
mainSpy.add => does not give addAnnotation as potential autocomplete, even though it gives other possibilities.
Should I close that issue, since it seems more related to my environment than to Javaparser?

Thanks

**Comment by matozoid** [comment]
Intellij has no problem with the autocomplete, so it is indeed an IDE issue :-) Maybe there's something useful in here for you: https://github.com/javaparser/javaparser/wiki/Eclipse-Project-Setup-Guide
