### ISSUE TITLE
ASTParser and ParserException is missing

### ISSUE THREAD

**Issue by lukasonokoleg** [javaparser/javaparser#223]
Hello guys in last revisions you forgot to commit ASTParser and ParserException classes. 

Thank  you!

**Comment by ftomassetti** [comment]
hi @lukasonokoleg thanks for reporting this! Those files are generated by Javacc. If you use maven run `maven compile` and they will appear under target/generated-sources/javacc

**Comment by lukasonokoleg** [comment]
Than I do not know what is wrong. I run maven compile through eclipse, and int does not generate.

**Comment by ftomassetti** [comment]
perhaps Eclipse is not doing what is supposed to do... have you tried running mvn compile and mvn test from the command line, outside Eclipse?

**Comment by lukasonokoleg** [comment]
Nope, I thought that it should run through eclipse.

**Comment by lukasonokoleg** [comment]
Just tried to do the same outside the eclipse with mvn VIA command line ---> Compilation failed as ASTParser and other classes did not generated.

**Comment by ftomassetti** [comment]
This is very strange because Travis is compiling fine the current master version. Looking at its script it runs:
- mvn install -DskipTests=true
- mvn test

Stupid question: are you sure are you up-to-date with the repository and origin is pointing to the right place?

**Comment by lukasonokoleg** [comment]
I've downloaded the master.

**Comment by lukasonokoleg** [comment]
Well, as I see you are generating java_1_8.jj file ---> But eclipse does not read it.

**Comment by lukasonokoleg** [comment]
Well I managed to build a jar, but there is another question:

Which IDE you would suggest for developing this project? Like what are you using? 

As with eclipse, I can only write additional code, but I will still have to run compile and install via command line :) It is not comfortable :)

**Comment by ftomassetti** [comment]
I am currently using IntelliJ. If you want to just use JavaParser you can download the Jar using Maven (or just manually from Maven central). Otherwise I suggest you use IntelliJ. Note that once you have generated ASTParser and the other classes you could need to tell to your IDE to consider target/generated-sources/javacc as a directory containing source files. After that you can probably just use the IDE and compile from there. I think that manually run maven is needed only to initially generate those files and it is not needed anymore until you change the grammar file.

**Comment by lukasonokoleg** [comment]
Maybe you know how to specifie in jav1_8.jj specifik package name, where new classes should be generated?  --- no need got it.

**Comment by lukasonokoleg** [comment]
So full solution for developing in eclipse is 

---> Adding JavaCC plugin
---> Generating missing missing classes 
---> Putting them into required folders. 

Then you can flexibly develop in eclipse. 

Thx for help.

**Comment by ftomassetti** [comment]
No problem, I am glad you have it working. Let me know if you need more help. We have also a gitter channel where you can ask for help. You find the link in the README.
Cheers!
