### ISSUE TITLE
Javadoc of Range.strictlyContains doesn't match its implementation

### ISSUE THREAD

**Issue by SimonBaars** [javaparser/javaparser#2231]
The Javadoc for `Range.strictlyContains` is as follows:
```
/**
     * Do this strictly contains other? It means that this has to be larger than other and it has to start as other
     * or before and end as other or after.
     */
```
However, the implementation does not account for the `start as other` part. the implementation is currently as follows:
```
    public boolean strictlyContains(Range other) {
        return begin.isBefore(other.begin) && end.isAfter(other.end);
    }
```

However, according to the Javadoc I'd expect it to be like this:
```
public boolean strictlyContains(Range other) {
        return (begin.isBefore(other.begin) || begin.equals(other.begin))&& end.isAfter(other.end);
    }
```

Which one is correct: the Javadoc (which has my preference) or the implementation? I can change it via a PR, but first wanted to verify this problem via an issue.  The `strictlyContains` method does not seem to be used anywhere else in Javaparser, so I assume changing the implementation to the one staged above wouldn't be an issue.

**Comment by matozoid** [comment]
Thanks for the report! Can you check if the implementation has been changed in the past? It should behave like the very first implementation did :-)

(And this method obviously needs tests)

**Comment by SimonBaars** [comment]
I just checked; it has not been changed in the past. When you created the file 3 years ago, this was the implementation. The Javadoc was added later.

**Comment by SimonBaars** [comment]
Shall I modify the Javadoc accordingly?

**Comment by matozoid** [comment]
Hmmm. Yes please - I see there is already a `contains` which does contains and equal.
