### ISSUE TITLE
Lexical preservation sets incorrect indent when moving method body to lambda expression

### ISSUE THREAD

**Issue by max-prokofjev** [javaparser/javaparser#2235]
When moving method body to lambda expression as a parameter of another method, lexical preservation assumes that curly brackets belong to that method and calculates wrong indent.

Input:
![image](https://user-images.githubusercontent.com/23365083/57988002-7b5c3d80-7a91-11e9-88c3-e85920d33d75.png)

Result:
![image](https://user-images.githubusercontent.com/23365083/57988009-a21a7400-7a91-11e9-8f83-217ddce02c98.png)

Expected:
![image](https://user-images.githubusercontent.com/23365083/57988014-b3fc1700-7a91-11e9-9f08-85c78b51d514.png)

JavaParser version: **3.14.1**

Code for modifying AST:
![image](https://user-images.githubusercontent.com/23365083/57988061-40a6d500-7a92-11e9-9bcf-6fff5816d4ff.png)

[Project link](https://github.com/maxprj/JUnit-4-to-5-migration)
Maybe someone has dealt with this problem?

**Comment by matozoid** [comment]
Hi! I don't think I've seen this particular one yet.

**Comment by jlerbsc** [comment]
Hi @maximjev, could you tell us if you are having the same problem with the latest version of JP. Furthermore, it would be more useful to provide us with a textual test case versus an image.

**Comment by jlerbsc** [comment]
I'm closing this issue because there are no new elements to try to diagnose the problem. You are free to reopen it if you can provide us with usable information.
