### ISSUE TITLE
Add JavaForger to list of projects

### ISSUE THREAD

**Issue by daanvdh** [javaparser/javaparser#2239]
Hi JavaParser devs!

Thnx a lot for all the effort to create JavaParser. I started a project coupling JavaParser to a template engine to use data from parsed classes as input for templates. These templates can then be used to generate source code, tests or something else. Can you add this to the list of projects using JavaParser 3.0.0 and upwards? 

[JavaForger](https://github.com/daanvdh/JavaForger/tree/master) - Generate java source code based on existing classes using templates

Are there projects that you know of doing something similar?

Regards, 
Daan

**Comment by matozoid** [comment]
Cool! There it is: https://javaparser.org/about/ (the wiki page is gone)

https://github.com/javaparser/javaparser/tree/master/javaparser-core-generators does something similar :-) It generates a lot of code in JavaParser, based on the metamodel.

There are no projects like this that I know of that are completely generic.

**Comment by daanvdh** [comment]
Thnx! Good to know someone else did not yet do the work before me ;-)
