### ISSUE TITLE
BREAKING: Lazy loading list breaks DumpVisitor 2.3.0

### ISSUE THREAD

**Issue by JLLeitschuh** [javaparser/javaparser#225]
Many of your checks in the dump visitor check that the list isn't null but don't check that the list or element contained isn't subsequently empty.

Particular offenders:
### Bug 1

https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/DumpVisitor.java#L1233
Code:

``` java
        EnumDeclaration newEnum = new EnumDeclaration(
                ModifierSet.PUBLIC,
                null,
                getEnumerationClassName(),
                null,
                generateEnumConstantDeclarations(),
                null
        );
```

Result:

``` java
public enum BorderTypesEnum implements  {
    ...
```
### Bug 2

https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/DumpVisitor.java#L1278

Result:

``` java
    /** `iiiiii|abcdefgh|iiiiiii`  with some specified `i` */
    BORDER_CONSTANT(opencv_core.BORDER_CONSTANT) {
    }
    , /** `aaaaaa|abcdefgh|hhhhhhh` */
    BORDER_REPLICATE(opencv_core.BORDER_REPLICATE) {
    }
    , /** `fedcba|abcdefgh|hgfedcb` */
    BORDER_REFLECT(opencv_core.BORDER_REFLECT) {
    }
    , /** `cdefgh|abcdefgh|abcdefg` */
    BORDER_WRAP(opencv_core.BORDER_WRAP) {
    }
    , /** `gfedcb|abcdefgh|gfedcba` */
    BORDER_REFLECT_101(opencv_core.BORDER_REFLECT_101) {
    }
    , /** `uvwxyz|absdefgh|ijklmno` */
    BORDER_TRANSPARENT(opencv_core.BORDER_TRANSPARENT) {
    }
    , /** same as BORDER_REFLECT_101 */
    BORDER_REFLECT101(opencv_core.BORDER_REFLECT101) {
    }
    , /** same as BORDER_REFLECT_101 */
    BORDER_DEFAULT(opencv_core.BORDER_DEFAULT) {
    }
    , /** do not look outside of ROI */
    BORDER_ISOLATED(opencv_core.BORDER_ISOLATED) {
    }
    ;
```
### Bug 3

https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/DumpVisitor.java#L1599

Code:

``` java
            MethodReferenceExpr referenceExpr = new MethodReferenceExpr();
            referenceExpr.setScope(new NameExpr(type.getName()));
            referenceExpr.setIdentifier("new");
```

Result:

``` java
private final SocketHint<Mat> dstOutputHint = new SocketHint<Mat>("dst", Mat.class, Mat::<>new, SocketHint.View.NONE, null);
```

Notice the invalid `<>`

I'm pretty sure that there are others that I have missed. But for the moment this means that I'll be sticking with the older version of javaparser.

**Comment by ftomassetti** [comment]
Thank you. I would say that the code was already broken before lazy loading: empty lists should have been considered and they did not. It is true that lazy loading lists make this issue very relevant. In some parts of the code we used to do checks with the method `isNullOrEmpty`, now that lists are lazy loaded checking justs for empty lists should be enough.

I think the best course of action is first merging your patch and then carefully check DumpVisitor, perhaps also adding more tests.
