### ISSUE TITLE
How could I know which method the block statement belongs to.

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#2250]
Hi guys, I'd like to know how or which API should I call to get the method/function name of a block statement. 
For example:
```
   public static void test(String[] args) {
        int x = 0;
    }

    public static void test1(String[] args) {
        for (int o = 0; o < 10; o++) {
            int c = 5;
        }
    }

    public static void test2(String[] args) {
        if (true) {
            int a = 0;
        } else {
            int b = 4;
        }
    }
```

my expect output should be like 
```
 block int x = 0;  ===>   test
```

```
  block int c = 5; ===>   test1
```

```
  block int a = 0;  ===>   test2
```

Does anyone could help me how to get the method name of a block?

**Comment by matozoid** [comment]
Hi!

You want to find the ancestor of the node you have which is a method declaration. You can ask it for the name. Try looking through the methods on the node you have.

This is required reading: https://javaparser.org/inspecting-an-ast/
