### ISSUE TITLE
How could I figure out the kind of the blockstmt, a ifstmt? a switchstmt? a forstmt etc.

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#2251]
Hi guys, do you have any idea about how to figure out what kind of block statement ?
for example 
```
 public static void test(String[] args) {
        int x = 0;
    }

    public static void test1(String[] args) {
        for (int o = 0; o < 10; o++) {
            int c = 5;  <=== this is a forstmt
        }
    }

    public static void test2(String[] args) {
        if (true) {
            int a = 0;   <=== this is a ifstmt
        } else {
            int b = 4;
        }
    }
```

for now, I could get all the blockstmt, but when I got the blockstmt, how could I figure out what kind of stmt it is. 
Could any one help me about this? thanks a lot.

**Comment by matozoid** [comment]
Hi! Is this the same as #2250?

**Comment by ghost** [comment]
@matozoid  Hi , I'm sorry for my poor English. But I think these two questions are not the same.
I think #2250 focuses on which function calls the blockstmt. And #2251 focuses on what kind of stmt is the blockstmt.

For example:
```
public static void test1(String[] args) {
        for (int o = 0; o < 10; o++) {
            int c = 5;  <=== #2250  : test1 calls this block .    #2251: this block is a kind of forstmt.
        }
    }

    public static void test2(String[] args) {
        if (true) {
            int a = 0;    <=== #2250  : test2 calls this block .    #2251: this block is a kind of ifstmt.
        } else {
            int b = 4;
        }
    }
```

**Comment by matozoid** [comment]
Hi! This is more or less the same as your previous question, but it looks like you just want to ask for the parent, and then ask it what type it is. You can use `instanceof`.

More required reading: https://leanpub.com/javaparservisited
