### ISSUE TITLE
Solving class in rt.jar (JRE/JDK libraries)

### ISSUE THREAD

**Issue by vincentzalc** [javaparser/javaparser#2253]
Hi,
I have a problem when I am trying to solve the type of the fields in a java file (I want the **fully** qualified name hence I need symbol solving):
apparently:
```
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
TypeSolver jarTypeSolver = new JarTypeSolver("C:\\Program Files\\Java\\jdk1.8.0_201\\jre\\lib\\rt.jar");
TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(FILE_PATH_SRC));
combinedTypeSolver.add(reflectionTypeSolver);
combinedTypeSolver.add(javaParserTypeSolver);
combinedTypeSolver.add(jarTypeSolver);
```

Is not enough to avoid the following problem when I have a java.util.List field: `UnsolvedSymbolException{context='null', name='List', cause='null'}` even though some other types like String are getting solved correctly.

I have tried to get the type in two different ways:
1) 
JavaParserFacade.get(combinedTypeSolver).getType(field);

2)
StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
CompilationUnit cu = StaticJavaParser.parse(new File(FILE_PATH));
[...some code...]
field.getElementType().resolve();

I get the fields by using a visitor on my compilation unit.

Thanks a lot.

**Comment by vincentzalc** [comment]
It seems having a wrong src directory for the javaParserTypeSolver was making the solver life difficult.

**Comment by matozoid** [comment]
I love problems that solve themselves :-)
