### ISSUE TITLE
JarTypeSolver does not work

### ISSUE THREAD

**Issue by jwertherf** [javaparser/javaparser#2254]
Hello, everybody

I am having problems with the use of jarTypeSolver. Here is the code snippets:

a) To define the SymbolSolver and the ParseConfiguration:

    CombinedTypeSolver typeSolver = new CombinedTypeSolver();
    typeSolver.add(new ReflectionTypeSolver(false)); 
    typeSolver.add(new JavaParserTypeSolver(new File(SOURCE_PATH))); 
    typeSolver.add(new JarTypeSolver(new File(sourceJarPath)));
	
    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
    StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);    

b) To proccess and parse a file:

	new VoidVisitorAdapter<Object>() {
	    @Override
	    public void visit(MethodCallExpr methodCall, Object obj) {
			super.visit(methodCall, obj);
	                //
			// Identify the method called
			ResolvedMethodDeclaration resmd = null;
			// rejecting method call that can not have a ResolvedMethodDeclaration instance
			try {
				resmd = methodCall.resolve();
			} catch (UnsolvedSymbolException e) {
				if(log) toLog("WARNING: rejecting method call "+methodCall.getName()+" - UnsolvedSymbolException: "+e.getMessage());
                       }
                   ...
                   ... (etc.)
                   ...
              }  
	}.visit(StaticJavaParser.parse(new File(completeFileName)), null);

It always yields UnsolvedSymbolException whenever the captured called method belongs to a class that is in the source code jar file. The parser (and symbol solver) does not recognize the classes that are in this jar file.

What am I doing wrong?

**Comment by maartenc** [comment]
Just to be sure: the `sourceJarPath` points to a jar file containing class files, right?
The `JarTypeSolver` reads class files, not java source files...

**Comment by jwertherf** [comment]
Well, I thought JavaParser - in general - worked only with java files and not bytecodes. And I even understood this way in the examples I found on the internet. Now I changed to bytecode jar and worked fine. Thanks for make myself clear.
