### ISSUE TITLE
Type resolution issue in expression that involves object creations

### ISSUE THREAD

**Issue by Shoreray** [javaparser/javaparser#2261]
Hi,

The method calculateResolvedType() throws an exception on the code below when its' call on the expression `new TestClass3<Object>().foo().length`.
```
public class TestClass3<T> {

	public int[] foo() {
		System.out.println("Verify execution.");
		return new int[3];
	}

	public static void main(String[] args) {
		int placeholder = new TestClass3<Object>().foo().length;
	}
}
```
The stack trace is:
```
com.google.common.util.concurrent.UncheckedExecutionException: java.nio.file.InvalidPathException: Illegal char <<> at index 93: (local path on my mathine)\test-javaparser-resolve-fault\src/new TestClass3<Object>()/foo().java
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4873)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveType(JavaParserTypeSolver.java:170)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:198)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:44)
	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:448)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:310)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:292)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:250)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:564)
	...
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 93: (local path on my machine)\test-javaparser-resolve-fault\src/new TestClass3<Object>()/foo().java
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveTypeUncached(JavaParserTypeSolver.java:202)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$tryToSolveType$4(JavaParserTypeSolver.java:171)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4878)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 14 more
```
(In the exception message, I removed some parts of the local paths on my machine.)

The bug seems to have something to do with generic type parameters, as the failure disappears if I remove that part from TestClass3.

**Comment by matozoid** [comment]
Some bugs like this one were solved a few months ago. Are you on the latest version?

**Comment by Shoreray** [comment]
I was on 3.13.10 when I found the issue, and have just reproduced it on 3.14.4.

**Comment by matozoid** [comment]
Ah crap. Thanks.

**Comment by jlerbsc** [comment]
Could you give the test case please because i cannot reproduce this stacktrace with 

    String code = String.join(System.lineSeparator(),
                "public class Issue2261<T> {\n" + 
                "	public int[] foo() {\n" + 
                "		System.out.println(\"Verify execution.\");\n" + 
                "		return new int[3];\n" + 
                "	}\n" + 
                "	public static void main(String[] args) {\n" + 
                "		int placeholder = new Issue2261<Object>().foo().length;\n" + 
                "	}\n" + 
                "}"
        );

        ParseResult<CompilationUnit> parseResult = javaParser.parse(ParseStart.COMPILATION_UNIT, Providers.provider(code));
        assertTrue(parseResult.isSuccessful());
        assertTrue(parseResult.getResult().isPresent());
    
        CompilationUnit compilationUnit = parseResult.getResult().get();
        MethodDeclaration decl = compilationUnit.findFirst(MethodDeclaration.class, md ->
                md.getNameAsString().equals("main")).get();
        List<MethodCallExpr> expressions = decl.getChildNodesByType(MethodCallExpr.class);
        assertTrue(expressions.size() == 1);
        ResolvedType r = expressions.get(0).calculateResolvedType();

**Comment by Shoreray** [comment]
The error occurs when you resolve the FieldAccessExpr in the main method.
Here's the code to reproduce it:
```
// Get the compilation unit as you did in your test case
// CompilationUnit compilationUnit = ... ;
FieldAccessExpr targetExpr = compilationUnit.findFirst(FieldAccessExpr.class, 
    fieldAccess -> fieldAccess.getNameAsString().equals("length")).get();
targetExpr.calculateResolvedType();
```

**Comment by jlerbsc** [comment]
In 3.14.4 all seems to be ok.

    CompilationUnit compilationUnit = parseResult.getResult().get();
    FieldAccessExpr targetExpr = compilationUnit.findFirst(FieldAccessExpr.class, fieldAccess -> fieldAccess.getNameAsString().equals("length")).get();
    ResolvedType r = targetExpr.calculateResolvedType();
    assertEquals("int", r.describe());

**Comment by Shoreray** [comment]
Oops, I somehow didn't realize that a JavaParserTypeSolver has to be involved to trigger it, though this looks obvious in hindsight. My bad.

To reproduce it, initialize the JavaParser with:
```
ParserConfiguration config = new ParserConfiguration();
CombinedTypeSolver typeSolver = new CombinedTypeSolver();
typeSolver.add(new JavaParserTypeSolver(Paths.get("."))); // Use any valid path on your local machine.
typeSolver.add(new ReflectionTypeSolver());
config.setSymbolResolver(new JavaSymbolSolver(typeSolver));
JavaParser javaParser = new JavaParser(config);
```
Adding the code above should reproduce a stack trace similar to mine.

From the stack trace, some Windows-specific code in the JRE is also involved. The error might be different on another platform but I didn't test.

**Comment by jlerbsc** [comment]
You must add ReflectionTypeSolver to JavaSymbolSolver.

**Comment by Shoreray** [comment]
I see. Thanks for the information.

In my actual code that triggers the failure, ReflectionTypeSolver was added.
Having it or not doesn't seem to have an effect here.

I've edited the test code above.

**Comment by jlerbsc** [comment]
Ok you are right. JavaParserTypeSolver.tryToSolveType(...) doesn't filter the String name parameter and in your case the scope of the expression to resolve is "new TestClass3<Object>().foo()". So JavaParserTypeSolver throws the exception "java.nio.file.InvalidPathException: Illegal char <<> at index 75: <path to sources>\./new Issue2261<Object>()/foo().java". 
Unfortunatly TypeSolver interface doesn't define a filterName() method so i think we can filter directly the name in the JavaParserTypeSolver.tryToSolveType(...) method with a call to SourceVersion to validate the parameter.

**Comment by matozoid** [comment]
If we can pinpoint where the type parameters are accidentally added to a file name, we can fix the problem.

**Comment by jlerbsc** [comment]
TypeExtractor.visit(FieldAccessExpr, Boolean) is invoked with a node value 

    new Issue2261<Object>().foo().length

the scope of this node is a MethodCallExpr which is not a scope actually taken into account

    new Issue2261<Object>().foo()

**Comment by jlerbsc** [comment]
It seems this issue is resolved. It cannot be reproduced with this unit test.

    public class Issue2261Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {
        String code = String.join(System.lineSeparator(),
                "public class Issue2261<T> {\n" +
                        "   public int[] foo() {\n" +
                        "       System.out.println(\"Verify execution.\");\n" +
                        "       return new int[3];\n" +
                        "   }\n" +
                        "   public static void main(String[] args) {\n" +
                        "       int placeholder = new Issue2261<Object>().foo().length;\n" +
                        "   }\n" +
                        "}");

        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(reflectionTypeSolver);
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
        StaticJavaParser.setConfiguration(configuration);

        CompilationUnit cu = StaticJavaParser.parse(code);

        MethodDeclaration decl = cu.findFirst(MethodDeclaration.class, md -> md.getNameAsString().equals("main")).get();
        List<MethodCallExpr> expressions = decl.getChildNodesByType(MethodCallExpr.class);
        assertEquals("int[]",expressions.get(0).calculateResolvedType().describe());
        
        FieldAccessExpr targetExpr = cu.findFirst(FieldAccessExpr.class,
                fieldAccess -> fieldAccess.getNameAsString().equals("length")).get();
        assertEquals("int",targetExpr.calculateResolvedType().describe());

    }
    }
