### ISSUE TITLE
Parser fails on code with unicode escapes

### ISSUE THREAD

**Issue by haumacher** [javaparser/javaparser#2265]
I have a funny issue in a JavaCC-generated source file that cannot be parsed with JavaParser: 

Among other unreadable stuff there is a line containing the statement
```
return aString.replaceAll("\u005c\u005c\u005c\u005c\u005c"", "\u005c"");
```
At first glance this looks like a syntax error in the source file - but Eclipse accepts this code without any error. The problem is that `\u005c` is the unicode escape for `\` which must be processed before handing the characters to the Java lexer as the Java Specs say at https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.2.

So this must be read as
```
return aString.replaceAll("\\\\\"", "\"");
```
for the normal programmer, meaning to replace an escaped `\"` with `"`. This version is de-facto contained in the `*.jj` source file but transformed to the unreadable variant by JavaCC in its generated `*.java` output.

This seems to be related to #1242, where you unfortunately decided not to fix the problem because "no Java Programmer would ever write such code". I totally agree with that but Java code is not only created by programmers but also by tools. And it seems that there are tools out there that follow the specs producing code not parsable with JavaParser...

**Comment by matozoid** [comment]
Good news! The latest state is here: #1928

**Comment by haumacher** [comment]
Ok, sorry, I did not see this configuration option. One must say e.g.:
```
StaticJavaParser.getConfiguration().setPreprocessUnicodeEscapes(true);
```
With the drawback that the source code positions are no longer exact - which in my case is quite a pitty but I can live with it.

Don't you think, that this problem (the wrong source code positions) couldn't be fixed by simply building a mapping from unescaped source position back to original source position while unescaping the source code in the first pass? After the parser has read the AST, the position could then be mapped back to the original positions.

**Comment by matozoid** [comment]
Hmmm, that would mean... building a list of sourcerange->amount_of_chars_shifted... then going through the AST nodes, looking at both positions separately: look in which sourcerange it is, then shift the position with minus that amount of characters. That's not even that immensely difficult. It should be done in or after this one: #1930.

Do you have some time to implement it?

**Comment by haumacher** [comment]
> Do you have some time to implement it?

I think, I could make a proposal...

**Comment by matozoid** [comment]
Why can't I put a thumbs up icon here?

**Comment by haumacher** [comment]
Seems I get stuck quite at the beginning. Trying to build JavaParser in Eclipse using Run-as Maven-compile with goal "package" fails with errors like:
```
[ERROR] /C:/.../javaparser/javaparser-core/target/generated-sources/javacc/com/github/javaparser/SimpleCharStream.java:[4,29] unmappable character for encoding UTF-8
```
The file at the mentioned location contains the String `J�lio Vilmar Gesser` in a comment - which looks like wrong encoding of the JavaCC-generated file. Can you given a hint how to fix the JavaCC output encoding for the generated files?

**Comment by haumacher** [comment]
Ok on the command line, the same errors occur, but the build does not fail - Unfortunately, Eclipse does not find the generated parser files - had to add the folder target/generated-sources/javacc manually as source path...

**Comment by haumacher** [comment]
One more question: Wouldn't the proposed hack "Building a mapping from unescaped source position back to original source position while unescaping the source code and mapping back the token positions back to the original positions." result in exactly the same result as enabling unicode escapes in the JavaCC compiler? Wouldn't it be much simpler to generate two different parsers (one with unicode escaping and one without) and use the one or the other according to the options externally set to JavaParser?

**Comment by matozoid** [comment]
Sadly no, it's been a while, but I think that just generates the file that I put in `UnicodeEscapeProcessingProvider` (so I could make it optional.) That is used as the inputstream, so the parser never sees the escape codes, therefore the result is the same: the locations are wrong.

You could try opening an issue with the JavaCC people, but those are some of the most mysterious developers ever. They are making all kinds of stuff and nobody knows what or when it will be finished :-)

I'm disappointed by Eclipse not understanding the extra source directory - it's quite a common setting for a common plugin :-/
