### ISSUE TITLE
Incorrect source code positions in standards-complient unicode escaping mode

### ISSUE THREAD

**Issue by haumacher** [javaparser/javaparser#2270]
With standards-complient unicode escaping (`com.github.javaparser.ParserConfiguration.setPreprocessUnicodeEscapes(true)`), the source code positions reported in the AST are incorrect: Unicode escape sequences are processed before parsing so that the scanner consumes the decoded stream counting only positions in the decoded version of the source file. Thes positions are reported in the AST.

In the example where braces are replaced by corresponding unicode escape sequences
```
@interface AD \u007B String foo(); \u007D
```
the AST reports the range (1,17)-(1,29) for the method declaration `String foo();`, while it spans the range (1, 22)-(1, 34) in the original source.

**Comment by haumacher** [comment]
@matozoid Danny, in https://github.com/haumacher/javaparser/tree/correct-positions-with-unicode-escape-processing the `UnicodeEscapeProcessingProvider` builds a position mapping while decoding the unicode escape sequences. This mapping is then applied in a post-processing phase to the source ranges of the created AST. 

Using the same instance as pre- and post-processor looks somewhat strange in the `ParserConfiguration` constructor - maybe you have an idea for cleanup.

**Comment by matozoid** [comment]
Opening a PR gives a better view of what has been changed (you can call it [DRAFT] so it doesn't get merged.)

Here are some ideas:
- use Node.walk to go through the whole tree,
- that getResult().get() should be a getResult().ifPresent(...)
- same with node.getRange().ifPresent(...)
- you can rename the `process` methods to `preProcess` and `postProcess` - I can't find a better way either :-)
- if you like, change `setPreprocessUnicodeEscapes` to accept an enum of NO_PROCESSING, PROCESS_FAST, and PROCESS_AND_FIX_POSITIONS (or so.) That way people can tweak performance vs. functionality.

Looking good though!

**Comment by haumacher** [comment]
Implemented your suggestions in #2271. Still feeling somewhat uncomfortable when writing something like
```
result.getResult().ifPresent(
  root -> {
    PositionMapping mapping = _unicodeDecoder.getPositionMapping();
    root.walk(
      node -> node.getRange().ifPresent(
        range -> node.setRange(mapping.transform(range))));
  }
);
```
Since at least in the last line `range -> node.setRange(mapping.transform(range))` there must be an object allocation for each and every node visited, since the inner lambda accesses a local of an outer one... :-)

**Comment by haumacher** [comment]
I did not rename the processor methods or introduce an enum, since I did not want to change the API.

**Comment by matozoid** [comment]
Oh, I doubt anybody is using this particular API :-) Just make it like you want it to be.

**Comment by matozoid** [comment]
The only inconsistency left within the unicode preprocessor is that the escapes can never be retrieved in the AST. They are forever decoded. But that's for another day :-)

**Comment by haumacher** [comment]
In the AST build from the decoded source, one could retrieve the original version of e.g. a string constant from the original source code using the source code positions in the AST.

**Comment by haumacher** [comment]
If we would store the character index in the original source file with a `Position` instance, looking up the original variant of a construct would be even very efficient.

**Comment by matozoid** [comment]
Let's make that another issue. Nobody is asking for it right now, so low priority.
