### ISSUE TITLE
Question: Why an assignExpr cannot be resolved?

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2274]
We can resolve MethoCallExpr but not AssignExpr! Could you explain why it is not possible or implemented? If we try to resolve the target, is it correct to not consider "c" as a variable?

    public class A {
	  public void methodA() {
              int c;
              c = c + 1; 
	  }
    }

**Comment by matozoid** [comment]
Isn't it just a question of resolving `getTarget()`?

**Comment by jlerbsc** [comment]
It's possible but the method resolveDeclaration in JavaSymbolSolver seems to sometimes look for a context. For exemple

    if (node instanceof VariableDeclarator) {
            ResolvedValueDeclaration resolved;
            if (node.getParentNode().isPresent() && node.getParentNode().get() instanceof FieldDeclaration) {
                resolved = new JavaParserFieldDeclaration((VariableDeclarator) node, typeSolver);
            } else if (node.getParentNode().isPresent() && node.getParentNode().get() instanceof VariableDeclarationExpr) {
                resolved = new JavaParserVariableDeclaration((VariableDeclarator) node, typeSolver);
       
So it could be possible perhaps to try to resolve AssignExpr and look for the target.
