### ISSUE TITLE
Windows 10 Support (No Generated Code Ahead Please, Yet)

### ISSUE THREAD

**Issue by mearvk** [javaparser/javaparser#2276]
The file run_core_generators.sh will not run in Windows 10.  We need the GeneratedJavaParserConstants.class for the simple compile of your software.  Can we get included a Window batch file also? 

Thanks.

**Comment by edefazio** [comment]
Have you tried to run the maven build "mvn clean install" ? 

I am using Windows 10 just fine 
(I believe GeneratedJavaParserConstants.class is  "generated" by the build)

/* Generated By:JavaCC: Do not edit this line. GeneratedJavaParserConstants.java */

Are you asking for a simple batch file to generate the build (i.e. not Maven?)

**Comment by matozoid** [comment]
The `.sh` files are only necessary if you're modifying JavaParser itself.

**Comment by mearvk** [comment]
We didn't want Maven.  What else can be changed?

**Comment by matozoid** [comment]
The Maven plugin generates the source files. The whole project has been configured by Maven and I can't believe you would be stubborn enough to start by changing the build system. This is really your problem that you are getting yourself into.
