### ISSUE TITLE
new project that uses javaparser

### ISSUE THREAD

**Issue by dorkbox** [javaparser/javaparser#228]
JavaBuilder : https://github.com/dorkbox/JavaBuilder uses javaparser to find the dependencies for compiling source files.

**Comment by ftomassetti** [comment]
Thank you for reporting this! I will add it in the wiki

**Comment by ftomassetti** [comment]
And it is now listed here: https://github.com/javaparser/javaparser/wiki/Projects-using-JavaParser

Thank you again and keep up the good work!
