### ISSUE TITLE
Ability to combine PrettyPrinterConfiguration and an indentation level for JavadocComment

### ISSUE THREAD

**Issue by cowwoc** [javaparser/javaparser#2285]
Invoking `ClassOrInterfaceDeclaration.toString()` indents the Javadoc of any nested methods, but if we invoke `JavadocMethod.toString(PrettyPrinterConfiguration)` the javadoc is never indented.

I can use `MethodDeclaration.getJavadoc().get().toComment(String indentation)` to control the indentation level but then I lose the ability to control which kind of newlines get used.

Please provide a mechanism to indent the Javadoc of a single method while also using a `PrettyPrinterConfiguration` (e.g. to control which kind of newlines get used).

**Comment by edefazio** [comment]
can you put an example or snippet of what you are doing in this report and what you expect?

I wrote a little example and I cannot reproduce this behavior.

as an alternative to making a framework change to support a one-off case, you might consider
just extending the PrettyPrintVisitor implementation, then change the code here:
```java
    @Override
    public void visit(final MethodDeclaration n, final Void arg) {
        printOrphanCommentsBeforeThisChildNode(n);

        printComment(n.getComment(), arg);
        /*** rest of code*/
```

where, instead of calling printComment on methodVisit, build your own implementation
the PrettyPrinter is really just a Visitor implementation. just a thought.

**Comment by cowwoc** [comment]
@edefazio Could you please share your example? I will evolve it to reproduce the problem.

**Comment by edefazio** [comment]
````java
public void testPP(){
        com.github.javaparser.printer.PrettyPrintVisitor ppv = new PrettyPrintVisitor(new PrettyPrinterConfiguration());
        PrettyPrinterConfiguration ppc = new PrettyPrinterConfiguration();
        CompilationUnit cu = Ast.of("public class C{",
                "    /** comment */",
                "    public void m(){",
                "    }",
                "}");
        System.out.println( cu.toString() );
        System.out.println( cu.toString(ppc) );
        
        MethodDeclaration md = cu.getType(0).getMethodsByName("m").get(0);
        System.out.println( md.toString() );
        System.out.println( md.toString(ppc) );
        
        PrettyPrinterConfiguration ppc2 = ppc.setIndentSize(12).setEndOfLineCharacter("<EOL>");
        
        System.out.println( md.toString(ppc2));
        System.out.println( cu.toString(ppc2));       
    }
````

**Comment by cowwoc** [comment]
Hi @edefazio 

Thank you for the testcase. Here is the updated code:

```
public class Testcase
{
	public static void main(String[] args)
	{
		PrettyPrintVisitor ppv = new PrettyPrintVisitor(new PrettyPrinterConfiguration());
		PrettyPrinterConfiguration ppc = new PrettyPrinterConfiguration();
		CompilationUnit cu = StaticJavaParser.parse("public class C\n" +
			"{\n" +
			"    /** comment */\n" +
			"    public void m()\n" +
			"    {\n" +
			"    }\n" +
			"}");
		System.out.println("CompilationUnit.toString()");
		System.out.println("--------------------------");
		System.out.println(cu.toString());
		System.out.println(cu.toString(ppc));

		System.out.println("MethodDeclaration.toString()");
		System.out.println("---------------------------");
		MethodDeclaration md = cu.getType(0).getMethodsByName("m").get(0);
		System.out.println(md.toString());
		System.out.println();

		System.out.println("MethodDeclaration.toString(ppc)");
		System.out.println("-------------------------------");
		System.out.println(md.toString(ppc));
		System.out.println();

		System.out.println("MethodDeclaration.toString(ppc2)");
		System.out.println("--------------------------------");
		PrettyPrinterConfiguration ppc2 = ppc.setIndentSize(12).setEndOfLineCharacter("<EOL>");
		System.out.println(md.toString(ppc2));
		System.out.println();

		System.out.println("CompilationUnit.toString(ppc2)");
		System.out.println("------------------------------");
		System.out.println(cu.toString(ppc2));
		System.out.println();

		System.out.println("JavadocDeclaration.toString(ppc2)");
		System.out.println("---------------------------------");
		JavadocComment jdc = md.getJavadocComment().get();
		System.out.println(jdc.toString(ppc2));
	}
}
```

Notice that `JavadocDeclaration.toString(ppc2)` does not indent the Javadoc. Meaning, I want to extract and indent Javadoc from the AST, excluding the method declaration and body.

I believe the fix will need to go in `PrettyPrintVisitor.visit(final JavadocComment n, final Void arg)` .

**Comment by edefazio** [comment]
So your expectation is that, when you extract the Javadoc comment instance `jdc`, 
then manually print it out... 
````java
PrettyPrinterConfiguration ppc2 = ppc.setIndentSize(12);
JavadocComment jdc = md.getJavadocComment().get();
System.out.println(jdc.toString(ppc2));
````
it should be indented... like so:
````java
            /** 
             * comment
             */ 
````
assuming the indentSize is set to (12 spaces)

...I think your expectations are incorrect.  The `PrettyPrinterVisitor` doesn't work that way...

If you want to do this, I'd recommend doing it as a post-process step (i.e. use the pretty print visitors result then manually indenting it)

FWIW you wont get the same spacing because the indent level is caclulated while walking the AST, 
when you take any element out of context (in this case a comment) it doesnt "know" it's indented...

You could figure this out (by walking parents) but it seems like a lot of work just for adding prefix spaces

**Comment by edefazio** [comment]
Ohh... I forgot to mention... Comments are a little bit "tacked on" because of how attribution works in the Javaparser AST model... 

however if you want to go this route heres some code to get you started...
````java
 class C {
            class D {
                class E {
                    /**
                    * javadoc
                    */
                    public void m() {
                    }
                }
            }
        }
````

````java
JavadocComment jdc = /* ??? get the comment above some comment ??? */
Node commentedNode = jdc.getCommentedNode().get(); //this assumes comment is attributable BIG ASSUMPTION
AtomicInteger indentLevel = new AtomicInteger(0);
//System.out.println( commentedNode );
commentedNode.walk(Node.TreeTraversal.PARENTS, p -> indentLevel.incrementAndGet());
//here Im just verifying the parents... you prolly want to subtract 1 since a compilationUnit
//is a parent but is not an indentation level... so just multiply this number by the indent spaces
// and you should be good
assertEquals(4, indentLevel.get());
````

**Comment by cowwoc** [comment]
Very cool. Thank you! :)
