### ISSUE TITLE
Node equality

### ISSUE THREAD

**Issue by hugofmelo** [javaparser/javaparser#2297]
Hi JP team,

suppose my visitor is collecting CatchClause nodes into a HashSet. Two CatchClause with the same source code are considered equal, thus the second one are not being added up to the Set. That is the intended behaviour?

Example:

```
private void methodA ()
{
	try
	{
		throw new Exception();
	}
	catch (Exception e)
	{
		System.out.println("Identical catch");
	}
}

private void methodB ()
{
	try
	{
		throw new Exception();
	}
	catch (Exception e)
	{
		System.out.println("Identical catch");
	}
}
```

**Comment by matozoid** [comment]
Hi! That is the intended behaviour. To override that behaviour, we have `VisitorList`, `VisitorSet`, and `VisitorMap`.

**Comment by hugofmelo** [comment]
How can I instantiate VisitorList?

**Comment by matozoid** [comment]
With the constructor.

**Comment by hugofmelo** [comment]
And the `GenericVisitor<Integer, Void> hashcodeVisitor, GenericVisitor<Boolean, Visitable> equalsVisitor` of the constructor.. can you give a example?

**Comment by matozoid** [comment]
Put in `ObjectIdentityHashCodeVisitor` and `ObjectIdentityEqualsVisitor`.

**Comment by hugofmelo** [comment]
Ty @matozoid!

**Comment by matozoid** [comment]
Np @hugofmelo :-)
