### ISSUE TITLE
SymbolResolver is lost when iterating child method nodes

### ISSUE THREAD

**Issue by ahartvign** [javaparser/javaparser#2305]
Hi,

First of all, thank you for this great library. I am aware that this might be a stupid question. But here goes anyway. 
I am trying to generate a list of lines of all methods called 'recursively'. My test files looks like this:

```
public class MethodAccessModifiers_Class
{
    public void publicMethod()
    {
        JavaClassTwo test = new JavaClassTwo();
        test.test();
    }
}
```

```
public class JavaClassTwo
{
    public void test()
    {
        anotherTest();
    }

    public void anotherTest()
    {

    }
}
```

My code looks as such:

```
    private static void testGetMethods() throws IOException {
        String rootPath = "...\\src";
        String testClassPath = "...\\src\\testclasses\\MethodAccessModifiers_Class.java";

        TypeSolver typeSolver = new JavaParserTypeSolver(Paths.get(rootPath));
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);

        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(Paths.get(testClassPath));
        resolveMethodRecursively(cu);
    }

    private static void resolveMethodRecursively(CompilationUnit unit)
    {
        unit.findAll(MethodCallExpr.class).forEach(mc -> {
            ResolvedMethodDeclaration resolvedMethod = mc.resolve();

            MethodDeclaration wrappedNode = ((JavaParserMethodDeclaration) resolvedMethod).getWrappedNode();
            wrappedNode.findCompilationUnit().ifPresent(Main::resolveMethodRecursively);

            System.out.println("Class: " + resolvedMethod.getClassName()
                    + " - Method: " + resolvedMethod.getName()
                    + " - Range: "
                        + wrappedNode.getRange().map(range -> range.begin.line + " to " + range.end.line).orElse("?"));
        });
    }
```

This works fine for the first method (JavaClassTwo.test()). But the second time the method is called (for JavaClassTwo.anotherTest()), it seems as if the SymbolResolver is lost, and I get the following exception:

Exception in thread "main" java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
	at com.github.javaparser.ast.Node.getData(Node.java:454)
	at com.github.javaparser.ast.Node.lambda$getSymbolResolver$5(Node.java:716)
	at java.util.Optional.map(Optional.java:215)
	at com.github.javaparser.ast.Node.getSymbolResolver(Node.java:715)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Main.lambda$resolveMethodRecursively$1(Main.java:39)

Any help would be much appreciated, thanks in advance.

**Comment by matozoid** [comment]
@danilomo - do you want to take a look at this? My guess would be that something is wrong in the setup.

**Comment by danilomo** [comment]
I'm blocked the next two weeks and I didn't even start the previous ticket. When I come back into activity I can take I look at this, but if someone can investigate this before please feel free to.

**Comment by JonJam** [comment]
@ahartvign I hit this issue with 3.15.0. 

After some playing around I found that I resolved it by specifying the same ParserConfiguration I was using for the StaticJavaParser to JavaParserTypeSolver.

(As JavaParserTypeSolver creates it's own ParserConfiguration)

It would look something like this:
```java
private static void testGetMethods() throws IOException {
  String rootPath = "...\\src";
  String testClassPath = "...\\src\\testclasses\\MethodAccessModifiers_Class.java";

  final ParserConfiguration configuration = new ParserConfiguration();
  configuration.setAttributeComments(false);
  configuration.setCharacterEncoding(Charset.forName("UTF-8"));
  configuration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_11);
        
  TypeSolver typeSolver = new JavaParserTypeSolver(Paths.get(rootPath), configuration);
  JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);

  configuration.setSymbolResolver(symbolSolver);

  StaticJavaParser.setConfiguration(configuration);

  CompilationUnit cu = StaticJavaParser.parse(Paths.get(testClassPath));
  resolveMethodRecursively(cu);
}
```
