### ISSUE TITLE
Get list of all classes declared in a CompilationUnit

### ISSUE THREAD

**Issue by andrewinston** [javaparser/javaparser#2309]
I have a file (or `CompilationUnit`) that contains some classes declared. What I need is a method to obtain all `ClassOrInterfaceDelcaration` inside a certain `CompilationUnit`

Is it already possible? If there isn't a way to do it, how do I proceed to contribute?

This is probably my first issue ever, sorry for anything.

Thanks in advance.

**Comment by matozoid** [comment]
Hi! This is in the book (it's free if you want to.) https://javaparser.org/getting-started/

The advantage is that this question can be answered in several ways, and the book discusses all of them.
