### ISSUE TITLE
How is java-symbol-solver implemented? Is it based on pointer analysis?

### ISSUE THREAD

**Issue by coder-chenzhi** [javaparser/javaparser#2311]
Is java-symbol-solver based on pointer analysis? If it is, which pointer analysis methods are used? If not, how is java-symbol-solver implemented?
Thanks!

**Comment by matozoid** [comment]
@ftomassetti is the one to answer this.

**Comment by SimonBaars** [comment]
There are several methods. You can configure, in your `ParserConfiguration`, what symbol solver to use. The ones I have found most success with are:

`ReflectionTypeSolver`: As the name indicates, it uses reflection to resolve types. Classes on the classpath used to run your application will be found. No source code is available for the resolved types.
`JavaParserTypeSolver`: Defines a directory containing source code that should be used for solving symbols. The directory must correspond to the root package of the files within. Parses the source files within using JavaParser to extract its symbols.
`JarTypeSolver`: You can specify `.jar` files to seek for symbols. 

Check the `com.github.javaparser.symbolsolver.resolution.typesolvers` package for more type solvers to use! All have very good Javadoc that show exactly what they do and how they work. [Here is a link.](https://github.com/javaparser/javaparser/tree/master/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typesolvers)

Hope this solves your problem :-)

**Comment by matozoid** [comment]
No, no pointer analysis is used. It's all quite ad hoc.

**Comment by ftomassetti** [comment]
I have no idea what pointers analysis is, so I guess not

**Comment by matozoid** [comment]
It's surprisingly easy to google: https://en.wikipedia.org/wiki/Pointer_analysis - so I guess it comes down to storing a little set in each node which contains references to all the nodes that it refers to. But the only thing we store in nodes is the result of the solver.

**Comment by coder-chenzhi** [comment]
Thanks to all of you! Point analysis is the foundation for many advanced program analysis tasks. And it also can be used for type resolving. So I wonder if java-symbol-solver is implemented on point analysis.
