### ISSUE TITLE
CloneVisitor doesn't copy orphan commets

### ISSUE THREAD

**Issue by ErtelJessica** [javaparser/javaparser#2312]
Assume we have following code to parse:

	public boolean isCreatedInCurrentBusinessTransaction() {
		// comment1
		// comment2
		if (vertrag != null && vertrag.isAntrag()) {
			setCreatedInCurrentBusinessTransaction();
		}
		return false;
		// comment3
	}

Now I want to get a copy of the BlockStatement by `stmt.clone();` .But then I will loose the comments 1 and 3. My suggestion is to extend the com.github.javaparser.ast.visitor.CloneVisitor's method `copyData(Node source, Node destination)` like this:

	private void copyData(Node source, Node destination) {
		for (DataKey dataKey : source.getDataKeys()) {
			destination.setData(dataKey, source.getData(dataKey));
		}
		for (Comment comment : source.getOrphanComments()) {
			destination.addOrphanComment(comment);
		}
	}

**Comment by matozoid** [comment]
Here you go: #2304 - check the fix version :-)
