### ISSUE TITLE
Change the grammar file "java.jj"

### ISSUE THREAD

**Issue by husseinmarah** [javaparser/javaparser#2314]
I have made some changes in the grammar file "java.jj", after that I used maven to create the library, and import it in my project in Eclipse, but still, the new changes don't work.

My aim is to do changes that could make the javaparser reads some different sentences like:
```
uses interface Timer<TMilli> as Timer0;
components new TimerMilliC() as Timer0;
call Timer0.startPeriodic( 250 );
```

**Comment by matozoid** [comment]
Changing the syntax takes a lot more effort:
- java.jj needs to be changed, then regenerated (the maven build should do that)
- AST nodes need to be created and registered in the MetaModel
- run_metamodel_generator should be run so the MetaModel gets updated
- run_core_generators should be run so the new nodes get all the correct methods, visitors get updated, etc, etc
- the PrettyPrintVisitor should be updated manually
- the ConcreteSyntaxModel should be updated with the new nodes
- the symbol solver can optionally be updated to handle the new nodes

Normally it's just me who does these things, so it's not that well documented.

If you just want to do some experimenting, it might be easier to grab an ANTLR example grammar and play around with that.

If you *do* want to modify the grammar, please give a clear description of what goes wrong.

**Comment by husseinmarah** [comment]
Thank you for the answer
I have a project and need to use a parser for semi-java language, I was wondering is it possible to do that with javaparser, but it seems a little complex.

**Comment by matozoid** [comment]
Extensibility is not one of the strong points of this library, I'm afraid.
