### ISSUE TITLE
Lexical preservation for text blocks.

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#2319]
Follow-up to #2316.

The lexical preserving printer is currently not being maintained, so the code for the new text blocks feature is probably wrong.

**Comment by jlerbsc** [comment]
It seems that lexical preservation supports TextBlock. If the support is not complete, it would be necessary to be more precise in order to be able to investigate the cases which raise problems.

    @Test
	void testTextBlockSupport() {
		String code = 
				"String html = \"\"\"\n" +
                "  <html>\n" +
                "    <body>\n" +
                "      <p>Hello, world</p>\n" +
                "    </body>\n" +
                "  </html>\n" +
                "\"\"\";";
		String expected =
				"String html = \"\"\"\r\n"
				+ "  <html>\r\n"
				+ "    <body>\r\n"
				+ "      <p>Hello, world</p>\r\n"
				+ "    </body>\r\n"
				+ "  </html>\r\n"
				+ "\"\"\";";
		final JavaParser javaParser = new JavaParser(
                new ParserConfiguration()
                        .setLexicalPreservationEnabled(true)
                        .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_15)
        );
		Statement stmt = javaParser.parseStatement(code).getResult().orElseThrow(AssertionError::new);
		LexicalPreservingPrinter.setup(stmt);
		assertEqualsStringIgnoringEol(expected, LexicalPreservingPrinter.print(stmt));
	}
