### ISSUE TITLE
UnsolvedSymbolException when searching for class ancestors 

### ISSUE THREAD

**Issue by JosemariaEzeani** [javaparser/javaparser#2324]
Any help will be very much appreciated. I feel like I've done what is necessary for the code to work, especially when compared to the many examples around. 

**Configuration** 

```
private void configuration() {
    TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
    reflectionTypeSolver.setParent(reflectionTypeSolver);
    CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
    combinedTypeSolver.add(reflectionTypeSolver);

    for (String source : getsourcepaths()) {
      try {
        combinedTypeSolver.add((source.endsWith(".jar"))
                ? new JarTypeSolver(source)
                : new JavaParserTypeSolver(source));
      } catch (IOException e) {
        e.printStackTrace();
      }
    }

    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
    StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
    parserConfiguration = new ParserConfiguration().setSymbolResolver(symbolSolver);
  }
```

**Problem arises here** 

```
public class SuperClassVisitor {
  public void visit(ClassOrInterfaceDeclaration classOrInterface, List<ResolvedClassDeclaration> arg) {
    arg. addAll(classOrInterface
            .resolve()
            .getAllAncestors()
            .stream()
            .filter(t -> t.getTypeDeclaration().isClass())
            .map(t -> t.getTypeDeclaration().asClass())
            .collect(Collectors.toList()));
  }
}
```

My intention is to save all superclasses for code review. 
Also noticed that ResolvedClassDeclarations cannot be saved as ClassOrInterfaceDeclarations. 

**Same problem even when using a ParserConfiguration with a non-static parser.** 

> ```
> Unsolved symbol : ProjectDataReloader
> UnsolvedSymbolException{context='null', name='ProjectDataReloader', cause='null'}
> 	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.toReferenceType(JavaParserClassDeclaration.java:422)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getSuperClass(JavaParserClassDeclaration.java:177)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAncestors(JavaParserClassDeclaration.java:303)
> 	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.getAncestors(ResolvedReferenceTypeDeclaration.java:69)
> 	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.getAllAncestors(ResolvedReferenceTypeDeclaration.java:97)
> 	at Visitors.SuperClassVisitor.visit(SuperClassVisitor.java:17)
> 	at ParseTree.AST.visitNodes(AST.java:165)
> 	at ParseTree.AST.parse(AST.java:143)
> 	at ParseTree.AST.<init>(AST.java:106)
> 	at ParseTree.AST_TEST.setAst(AST_TEST.java:30)
> 	at ParseTree.AST_TEST.configuration(AST_TEST.java:26)
> 	at ParseTree.AST_TEST.setup(AST_TEST.java:20)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
> 	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeMethodInExtensionContext(ClassTestDescriptor.java:439)
> 	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$15(ClassTestDescriptor.java:427)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$3(TestMethodTestDescriptor.java:149)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:169)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:148)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:123)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
> 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
> 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
> 	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> ```

**ProjectDataReloader is abstract.**

**Comment by JosemariaEzeani** [comment]
@matozoid my code in principal should have worked. I am able to parse superclasses that are not abstract. *Do you know why the code does not work for abstract classes?* This seems like a bug because this suggests that abstract classes cannot be resolved.

**Comment by JosemariaEzeani** [comment]
@matozoid works when parsed class and superclass are a part of the same compilation unit.

**Comment by matozoid** [comment]
Hello! There is currently no maintainer for the symbol solver. That means the best way to get a problem solved is to fix it yourself and submit a PR.

**Comment by jlerbsc** [comment]
Which version are you using?

**Comment by JosemariaEzeani** [comment]
@jlerbsc  does the feature work for you?
```
testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter', version: '5.4.2'
    compile group: 'com.github.javaparser', name: 'javaparser-symbol-solver-core', version: '3.14.9'
    compile group: 'com.github.javaparser', name: 'javaparser-core', version: '3.14.9'
    compile group: 'com.github.javaparser', name: 'javaparser-core-serialization', version: '3.14.9'
```

**Comment by jlerbsc** [comment]
I can try to help you to resolve this issue.
Have you a simple test case?

**Comment by JosemariaEzeani** [comment]
@jlerbsc Yeah sure. 

For each class parsed I was keen to store all superclasses in a list. 
I was using the following repository for my test. 
`https://github.com/abbybader/java-study-group-refactoring/tree/master/src/main/java`
LastUpdateTimeReloader would have DataReloader as a parent. 
I also extended DataReloader with a DummySuperClass to check that the functionality works.

**Comment by jlerbsc** [comment]
Could you test with the last version because it seems that there is no problem with this version

**Comment by matozoid** [comment]
There have been fixes for cases like this in this year. Always use the latest version. (Ask for help on Gitter with upgrading if you need to)

**Comment by jlerbsc** [comment]
There have been no comments for a very long time so I think this issue can be closed
