### ISSUE TITLE
Extra whitespace in DumpVisitor for ConstructorDeclaration

### ISSUE THREAD

**Issue by trew** [javaparser/javaparser#233]
https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/DumpVisitor.java#L969

`n.getTypeParameters()` will never return null. It should be `if (!n.getTypeParameters().isEmpty())`.

**Comment by ftomassetti** [comment]
Thank you for reporting this: we recently stopped using null lists and started using lazy initialized lists, so there are a few issues of this kind to solve.
We will fix this as soon as possible.
