### ISSUE TITLE
JDK13 yield keyword is interfering with normal code.

### ISSUE THREAD

**Issue by lhou-pcx** [javaparser/javaparser#2331]
I was using StaticJavaParser to parse all the java files in a repository and make some code changes to some files. The program stopped and threw a ParseProblemException when parsing a file which contains the following line:

`        Thread.yield();`

`com.github.javaparser.ParseProblemException: (line 6,col 9) Parse error. Found ".", expected one of  "%=" "&=" "(" "*=" "++" "+=" "--" "-=" "/=" ";" "<<=" "=" ">>=" ">>>=" "^=" "|="
`

Any idea why?

Thanks very much!

**Comment by matozoid** [comment]
Yes I do unfortunately: Java 13 added the yield keyword, and that seems to be interfering with this code. That will require some work.

In the meantime you can downgrade to 3.14.9 (see https://github.com/javaparser/javaparser/blob/master/changelog.md )

Thanks for reporting!

**Comment by lhou-pcx** [comment]
@matozoid It seems 3.14.9 is working. Thanks!
