### ISSUE TITLE
DumpVisitor loses comments

### ISSUE THREAD

**Issue by cdietrich** [javaparser/javaparser#234]
```
package demo;
@Anno(stuff={
    // "Just",
    // "an",
    // "example"
})
class ABC {

}
```

gets

```
package demo;

@Anno(stuff = {})
class ABC {
}
```

**Comment by cdietrich** [comment]
i did some debugging. the comments are in orphan comments.
i used that as a workaround in a patched dumpvisitor.

**Comment by ftomassetti** [comment]
Yes, orphan comments can be in the weirdest places and we do not consider all of them. I am not sure if we should cover this case.
