### ISSUE TITLE
Handle all modifiers in lexical preserving printer

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#2340]
#2339 - check that all modifiers are handled.

**Comment by jlerbsc** [comment]
I think this test class could be related to this issue

    class PrettyPrinterIssue2340Test extends AbstractLexicalPreservingTest {
    @Test
    void printingVariableDeclarationWithAddedModifier() {
        String def2 = "List i";
        considerVariableDeclaration(def2);
        // adding a modifier to the variable declaration
        expression.asVariableDeclarationExpr().getModifiers().addFirst(Modifier.privateModifier());
        //  System.out.println(LexicalPreservingPrinter.print(expression));
        assertTrue(LexicalPreservingPrinter.getOrCreateNodeText(expression).getElements().stream()
                .anyMatch(elem -> elem.expand().equals(Keyword.PRIVATE.asString())));
    }
    }

With a new method in the AbstractLexicalPreservingTest class

    protected void considerVariableDeclaration(String code) {
        expression = LexicalPreservingPrinter.setup(parseVariableDeclarationExpr(code));
    }

**Comment by matozoid** [comment]
Is it an existing test or something new?

**Comment by jlerbsc** [comment]
It's a new one. I am working on this case because i  encountered the problem by adding a transient modifier to a field declaration. Difference class is a little complex so it can take a time to correct this issue with generic in mind.

**Comment by matozoid** [comment]
#2364 indicates that this isn't solved.

**Comment by matozoid** [comment]
Now it is :-)
