### ISSUE TITLE
Some unexpected UnsolvedSymbol errors intermittently

### ISSUE THREAD

**Issue by gilyerm** [javaparser/javaparser#2347]
Probably a wrong usage on our part, but we're having a really weird issue.
we're running over a large project with many java files and are trying to solve any AST elements that we deem "interesting".

now we're already ok with the notion of not being able to solve for things that are not directly in the project were analyzing. how ever, we seem to sometimes have some things that do resolve on some occasions and not on others.

this is out basic flow for reference:
1. running tryToParseParallelized over all our SourceRoots (we collected them)
2. taking each parsed CU and creating a new Runnable to send off to an executor service
3. each Runnable does in order:
3.1 reducing the AST to "interesting" sub-tree (our implementation), based on the Node's types
3.2 making a similar tree, and resolving any resolvable nodes along the way, using n.resolve()

seems that running this without creating the runnables (simple synchronized foreach CU) isn't reproducing the issue...

Now we already got previously that reusing the same JavaParser instance is a bad idea when working multi-threaded. this did not seem to be the case when initializing our TypeSolvers and then registering them with SymbolSolver into our ProjectRoot as a configuration.
```
JavaSymbolSolver javaSymbolSolver = new JavaSymbolSolver(...);
final ParserConfiguration parserConfiguration = new ParserConfiguration()
		.setSymbolResolver(javaSymbolSolver);
// ...
ProjectRoot ProjectRoot=new ProjectRoot(path,parserConfiguration);
```

sorry if it a little vague, and we'll try to shortly make this reproducible. but from what we're describing -- is there anythings obvious wrong or clearly avoidable that we're not doing?

**Comment by matozoid** [comment]
As far as I know the symbol solver is not thread safe. There was some discussion on the Gitter channel recently.

**Comment by matozoid** [comment]
Assuming this is answered.
