### ISSUE TITLE
Remove Nodes

### ISSUE THREAD

**Issue by vasidzius** [javaparser/javaparser#235]
Hello,

I totally cant find information how to correct delete node from Compilation Unit

visitor method:
public void visit(VariableDeclarationExpr vd, Object arg) {
}
How to remove actually visited node (vd)?

Thx for help :)

**Comment by ftomassetti** [comment]
I think you may want do that from the parent. Unfortunately it means it depends which parents contain this node and under this relation.

The first thing is to find the parent of the node (see [getParentNode](http://static.javadoc.io/com.github.javaparser/javaparser-core/2.3.0/com/github/javaparser/ast/Node.html#getParentNode--)). The parent of an expression could be for example an [ExpressionStmt](http://static.javadoc.io/com.github.javaparser/javaparser-core/2.3.0/com/github/javaparser/ast/stmt/ExpressionStmt.html). You could remove the expression setting the expression of the ExpressionStmt to null. However that would leave an invalid AST so you want probably to remove the whole ExpressionStmt. It means you will have to find the parent of the ExpressionStmt and delete it from there.

So there is not a straightforward way to delete nodes right now, it depends. Of course we would appreciate any contribution to implement that :)

**Comment by vasidzius** [comment]
I tried do as you had written but failed. 

Maybe you could suggest why?

I have a simple file.txt which I parse:

public class DeadCode {
    public void foo(int e) {
        int a = 20,
                b = (e > 0 ? e : 43) % 10,
                c = a + b,
                d = e > 0 ? c : c + a;
    }
}

And I want to make optimization  - find all Declarators like "a=20" and substitution to other code. In the end I should receive a file without "a=20" and with "c=20+b" instead of "c=a+b" and etc.

So my first step are find all Declarators, save them, for example, to HashMap and delete them from Compilation Unit. 

I wrote:

@Override
        public void visit(VariableDeclarator type, Object args)
        {
            if (type.getInit() instanceof IntegerLiteralExpr)
            {
                String valueString = ((IntegerLiteralExpr) type.getInit()).getValue();
                int valueInteger = Integer.parseInt(valueString);
                ((HashMap)args).put(type.getId().getName(), valueInteger);

```
           Node parentNode = type.getParentNode();
            List list = ((VariableDeclarationExpr) parentNode).getVars();
            list.remove(type);
```

...}  }

It perfect saves "a=20" to HashMap but "list.remove(type)" call Exception
java.util.ConcurrentModificationException at java.util.LinkedList$ListItr.checkForComodification

As I understand there are few threads with few iterators and if I remove element it brakes iterators. 

Could you suggest how safely remove this node?

Thanks!

Sorry for possible stupid mistakes - I'm coding for 2 months but I hard try because it's a test from my possible job

p.s. your parser is a best what I could find for AST modification after 2 days of search! Thank you for this project!

**Comment by vasidzius** [comment]
@ftomassetti 

I figured out. Finally I encoded the post  here https://code.google.com/p/javaparser/wiki/UsingThisParser   . As  I understand the author is creator of JavaParser

"Hi Mariusz, you could write a visitor who returns null in that method, and the other methods changes the nodes with the returned value, like this:"

It means that one have to use ModifierVisitorAdapter instead of VoidVisitorAdapter. The difference is that Modifier returns reference to actual Node. If it returns NULL then Node will be deleted from AST

Simple example:

Task is delete a=20 from here:

```
class D {

public int foo(int e) {
    int a = 20;
}
}
```

How to do:

```
class MyVisitor extends ModifierVisitorAdapter
{
@Override
public Node visit(VariableDeclarator declarator, Object args)
{
    if (declarator.getId().getName().equals("a") && declarator.getInit().toString().equals("20"))
    {
        return null;
    }
    return declarator;
}
}
```

In result you'll recieve this:

```
class D {

public int foo(int e) {
    int ;
}
}
```

To avoid empty "int ;" the actions are bit harder - you have to start visits from Parent of Declarator and of parent of parent of Declarator ... The magic comand here is 
     super.visit(declarationExpr, args); 
It means that visitor will go to inners Nodes

all code:

```
public class GitHubTest {

public static void main(String...args) throws Exception {

    /*forGitHubTest:
    class D {

public int foo(int e) {
    int a = 20,
    return  100;
}
*/
    FileInputStream file1 = new FileInputStream("forGitHubTest.java");
    CompilationUnit cu = getCompilationUnit(file1);
    String result = cu.toString();
    new MyVisitor().visit(cu, null);
    System.out.println(cu.toString());

}

public static CompilationUnit getCompilationUnit(InputStream in) {
    try {
        CompilationUnit cu;
        try {
            // parse the file
            cu = JavaParser.parse(in);
            return cu;
        } finally {
            in.close();
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}
}

class MyVisitor extends ModifierVisitorAdapter
{

@Override
public Node visit (ExpressionStmt stmt, Object args)
{
    super.visit(stmt,args);
    if (stmt.getExpression()==null)
    {
        return null;
    }
    return stmt;
}

@Override
public Node visit (VariableDeclarationExpr declarationExpr, Object args)
{
    //просматриваем все объявления
    //в каждом объявлении может быть несколько инициализаций, просматриваем все     инициализации в каждом объявлении
    super.visit(declarationExpr, args);

    //если в данном объвлении не осталось ничего кроме типа, например "int ", то ее нужно удалить
    if (declarationExpr.getVars().isEmpty()) {
        return null;
    }

    return declarationExpr;
}

@Override
public Node visit(VariableDeclarator declarator, Object args)
{
    if (declarator.getId().getName().equals("a") && declarator.getInit().toString().equals("20"))
    {
        return null;
    }
    return declarator;
}

}
```

I think it's important to add inctructions to manual because if I got this information earlier I didn't lost 2 days:)

**Comment by ftomassetti** [comment]
Right, I did not think about this solution. I agree that it should be inserted in our manual. If you had the time to insert it here https://github.com/javaparser/javaparser/wiki/Manual it would be great, otherwise we will try do that ourselves as soon as we can. Thank you!

**Comment by vasidzius** [comment]
Done.

**Comment by ftomassetti** [comment]
Thank you!
