### ISSUE TITLE
Can add an enum constant with lexical preserving printer

### ISSUE THREAD

**Issue by glllions** [javaparser/javaparser#2351]
When I run the JavaParser it removes all empty lines within a method even if I do nothing to the CompilationUnit (some of them are there for a better overview and when I just add an EnumConstant I don't want half of the lines of the file to be changed...)
Is there any possibility to just modify what was added/removed to the CompilationUnit?

btw. Thanks for this tool its really useful!

**Comment by matozoid** [comment]
Hi! I assume you're using the pretty printer? The pretty printer considers empty lines to be ugly so it does not print them. You may have more luck with the lexical preserving printer - check out the Javadoc or the book for more information.

**Comment by glllions** [comment]
Hi @matozoid  thx for your fast response!!

I tried the lexical preserving printer and it worked like you said, thank you! :)
... but it brought 2 little new problems:
When using the lexical preserving printer...

1. ...the JavaParser fails at adding EnumConstants when the enum ends with ';' (and no following code) [see Exception] - this isn't a problem without the lexical preserving printer
2. ...a switch statement is added in the same line as the existing ones. Makes sense to me since I'm not using the PrettyPrinter anymore but maybe there is a possibility to use the PrettyPrinter just for added Entries?

Hope you could help me again :) I tried to solve this one my own with javadoc but I did not get far...
.
.
.
_Caused by: java.lang.UnsupportedOperationException: Csm token token(}) NodeText TOKEN ";"   <102>   (line 166,col 40)-(line 166,col 40)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:471)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:142)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:274)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:466)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:466)
	at com.github.javaparser.ast.NodeList.add(NodeList.java:70)
	at com.github.javaparser.ast.body.EnumDeclaration.addEnumConstant(EnumDeclaration.java:146)_

**Comment by matozoid** [comment]
Well, I'm afraid I can't help you now :-/ The lexical preserving printer is looking for a new maintainer, and the enum thing is a known issue: #2296.

If you feel like it, you could make an attempt at fixing it.

**Comment by glllions** [comment]
@matozoid No problem, thx for trying
Unfortunately I don't have capacity to try to fix it so I will have to live with some restrictions...

**Comment by matozoid** [comment]
- the pretty printer is actually a reasonably simple thing, a visitor that has some print-like statements for each node. If your requirements aren't too complex, a rule like "add an empty line before each variable declaration" is easy to do by overriding or copying and changing the visitor.
- if everything else fails, maybe the Spoon project is a better fit.

**Comment by jlerbsc** [comment]
@glllions Could you give some code to illustrate this case "the JavaParser fails at adding EnumConstants when the enum ends with ';' (and no following code) [see Exception] - this isn't a problem without the lexical preserving printer" ?

**Comment by glllions** [comment]
@jlerbsc sure, here it comes:
I tried the following cases:

`public enum RandomEnum {`
`    TYPE_1,`
`    TYPE_2`
`}`
**-> this works**


`public enum RandomEnum {`
`    TYPE_1,`
`    TYPE_2;`
`}`
**-> this does not work**


`public enum RandomEnum {`
`    TYPE_1,`
`    TYPE_2;`
`    private void doSomething() {`
`    }`
`}`
**-> this works**

If you need more information just ask

**Comment by glllions** [comment]
>     * the pretty printer is actually a reasonably simple thing, a visitor that has some print-like statements for each node. If your requirements aren't too complex, a rule like "add an empty line before each variable declaration" is easy to do by overriding or copying and changing the visitor.
> 
>     * if everything else fails, maybe the Spoon project is a better fit.

that may be true but my requirements are to just add some lines into some existing classes add the occurrences of new lines are not predictable (it only would help if there was a way to keep the existing new lines but thats not how the PrettyPrinter works) ...so I think since I am am pretty happy with the JavaParser it will be the easiest way to follow the formatting rules of the PrettyPrinter for those few classes... :)

**Comment by jlerbsc** [comment]
What's is the version your are using because with javaparser 3.14.6-SNAPSHOT I get the following result. So i'm not sure to understand your issue.

    class PrettyPrinterIssue2351Test extends AbstractLexicalPreservingTest  {
    @Test
    void printingEnum2() {
        String def2 = 
                "public enum RandomEnum {\n" + 
                "TYPE_1,\n" +
                "TYPE_2;\n" + 
                "}\n";
        considerCode(def2);
        System.out.println(LexicalPreservingPrinter.print(cu));
    }
    }

Result:

    public enum RandomEnum {
    TYPE_1,
    TYPE_2;
    }

**Comment by glllions** [comment]
@jlerbsc I am using javaparser-symbol-solver-core:3.14.12
The error appears at adding an enum constant like this `enumDeclaration.addEnumConstant("SOMETHING");`

**Comment by matozoid** [comment]
@glllions - can you modify @jlerbsc's code so that it triggers the problem?

**Comment by glllions** [comment]
I made some workarounds for both problems...

For the semicolon-problem I removed the ';' before adding the EnumConstant (see workaroundForSemicolon) and for the new line story I used the lexical preserving printer and 'beatufied' the added lines (see beautifyCode):
```
private CompilationUnit workaroundForSemicolon(String code, CompilationUnit compilationUnit) {
    Matcher matcher = Pattern.compile(";(\\n|\\s|\\t)*[^\\w]}").matcher(code);
    if (matcher.find()) {
        log.warning("Using workaround for '; at end of enum'-problem");
        try {
            String result = code.replace(matcher.group(), "\n}");
            File file = File.createTempFile("temp", ".java");
            FileWriter fileWriter = new FileWriter(file);
            fileWriter.write(result);
            fileWriter.flush();
            compilationUnit = javaParser.parse(file).getResult().orElseThrow(()
                    -> new IllegalArgumentException("Something seems to be wrong with the parse result"));
            LexicalPreservingPrinter.setup(compilationUnit);
        } catch (IOException ex) {
            log.warning("Failed creating file");
            log.warning(ex.toString());
        }
    }
    return compilationUnit;
}

private String beautifyCode(String code) {
    Matcher matcherNewLine = Pattern.compile(";(.+)\\n").matcher(code);
    Matcher matcherTabCase = Pattern.compile("(\\n\\s*)(?=case )").matcher(code);
    while (matcherNewLine.find()) {
        String group = matcherNewLine.group().substring(1);
        code = code.replace(group, matcherTabCase.find() ? matcherTabCase.group() + group : "\n" + group);
    }
    return code;
}

**Comment by glllions** [comment]
@matozoid Should trigger the problem with this:
```
class PrettyPrinterIssue2351Test extends AbstractLexicalPreservingTest  {
@Test
void printingEnum2() {
    String def2 = 
            "public enum RandomEnum {\n" + 
            "TYPE_1,\n" +
            "TYPE_2;\n" + 
            "}\n";
    considerCode(def2);
    EnumDeclaration eD = cu.getEnumByName("RandomEnum").get();
    eD.addEnumConstant("TYPE_3");
    System.out.println(LexicalPreservingPrinter.print(cu));
}
}

//This is how I can reproduce it
try {
    String def2
            = "public enum RandomEnum {\n"
            + "TYPE_1,\n"
            + "TYPE_2;\n"
            + "}\n";
    File file = File.createTempFile("temp", ".java");
    FileWriter fileWriter;
    fileWriter = new FileWriter(file);
    fileWriter.write(def2);
    fileWriter.flush();
    CompilationUnit cu = javaParser.parse(file).getResult().orElseThrow(()
            -> new IllegalArgumentException("..."));
    LexicalPreservingPrinter.setup(cu);
    EnumDeclaration eD = cu.getEnumByName("RandomEnum").get();
    eD.addEnumConstant("TYPE_3");
    System.out.println(LexicalPreservingPrinter.print(cu));

} catch (IOException ignore) {
}

**Comment by matozoid** [comment]
Wait wait, this is a bug report so let's fix it before closing ;-) Thanks for the code!

**Comment by glllions** [comment]
ok sure, you're welcome :)

**Comment by jlerbsc** [comment]
I found the root of the problem, leave me the time to postpone the change in the latest version
