### ISSUE TITLE
UnsolvedSymbolException with custom class and JarTypeSolver

### ISSUE THREAD

**Issue by vin-car** [javaparser/javaparser#2352]
I'm trying to setup Symbol Solver for my project, but I get `UnsolvedSymbolException`. I've read [this sample](https://github.com/javaparser/javasymbolsolver-maven-sample) and I've tried to customize it to my needs.

My code is the following:

```java
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver());

String modules[] = { "<path to first jar>", "<path to second jar>", /*...*/ }
for(int i=0; i< modules.length; i++) {
    JarTypeSolver typeSolver = new JarTypeSolver(modules[i]);
    combinedTypeSolver.add(typeSolver);
}

JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

CompilationUnit cu = StaticJavaParser.parse("class X { int x() { "
        + " MyContext myContext = new MyContext(); "
        + " myContext.setVariable(\"name\", \"aaa\"); "
        + "return 0; } }");

cu.findAll(NameExpr.class).forEach(name -> {
    ResolvedType resolvedType = name.calculateResolvedType();
    System.out.println(name.toString() + " is a: " + resolvedType);
}
```

In the `modules` array are listed all required jars used by the class (`X` in the previous sample) I want to parse and symbol solve. So `MyContext` is a _business_ class contained in one of the jar files listed in `modules` array.

I was expecting to get:

```
myContext is a: MyContext
```

but I'm getting `UnsolvedSymbolException` on the `calculateResolvedType()`.

**Comment by jlerbsc** [comment]
I think you have to define in your test case the import statement for the class MyContext

**Comment by vin-car** [comment]
Thanks @jlerbsc , adding the import for `MyContext` class make the code work without exceptions, sorry for opening an issue for a trivial mistake.
