### ISSUE TITLE
Does not visit nested annotations

### ISSUE THREAD

**Issue by HiFromAjay** [javaparser/javaparser#2353]
I am trying to retrieve annotations from source code but I cannot retrieve nested annotations. For example, the source file at the link given below has annotations at line 42, 43, 54 and 55. I can get the annotations at lines 42 and 54, but cannot get annotations at lines 43 and 55. I am using all the three MarkerAnnotationExpr, NormalAnnotationExpr, and SingleMemberAnnotationExpr to visit annotations.
Source file link: https://github.com/hibernate/hibernate-orm/blob/master/documentation/src/main/java/org/hibernate/userguide/model/Phone.java

**Comment by matozoid** [comment]
Hi! Don't forget to call super in your visit methods.

**Comment by HiFromAjay** [comment]
got it :). thanks

**Comment by matozoid** [comment]
Cool!
