### ISSUE TITLE
Leading stars are incorrectly removed

### ISSUE THREAD

**Issue by gsmet** [javaparser/javaparser#2356]
Hi,

We are trying to use your parser in Quarkus to parse our Javadoc and generate some Asciidoc content. The fact is that for some of our Javadoc, we use Asciidoclet and thus have Asciidoc content inside our Javadoc.

This leads for instance to the following Javadoc:
```
/**
 * My Javadoc has a list:
 *
 * * First item
 * * Second item
 *
 * @asciidoclet
 */
```

The issue is that the parser totally ignores the `* ` that are in the Javadoc content and returns something like:
```
My Javadoc has a list:

First item
Second item
```
Whereas I would have expected:
```
My Javadoc has a list:

* First item
* Second item
```

It looks like the parser is a bit too aggressive in trimming the leading `* ` and doesn't only remove the first occurrence.

Would it be possible to fix this behavior? That would be very helpful.

Thanks!

**Comment by gsmet** [comment]
Ah, I just figured out from the javadoc that you were expecting the leading `* ` for all the lines except the first one and they were already removed elsewhere.

I added them back and it seems to work OK.

Closing, sorry for the noise.

**Comment by matozoid** [comment]
Uh okay :-) A personal thing: I used asciidoc in Javadoc once, but stopped very quickly when tools  continuously ruined the formatting.
