### ISSUE TITLE
CodeGenerationUtils should generate getter with `is` prefix for `boolean`s, not for `java.lang.Boolean`

### ISSUE THREAD

**Issue by vilmosnagy** [javaparser/javaparser#2357]
According to [this](https://stackoverflow.com/a/28450498/2891426) StackOverflow answer, and the JavaBeans specification referenced from that answer, the `
CodeGenerationUtils.getterName(Class<?> type, String name)` should work as the following:

 - return `name` if `name.startsWith("is") && class.equals(Boolean.TYPE)` 
 - return `"is" + capitalize(name)` if `class.equals(Boolean.TYPE)` 
 - return `"get + capitalize(name)`

Currently it generates `is` prefixed getters for any `Boolean` type, and `get` prefixed for the `boolean` ones.

**Comment by matozoid** [comment]
Makes sense.
