### ISSUE TITLE
Parameters passed into super constructor call go missing

### ISSUE THREAD

**Issue by Echogene** [javaparser/javaparser#236]
Am I correct in my expectation that `JavaParser.parseExpression("super(foo)").toString()` should be `"super(foo)"`?  It comes out as `"super"` instead.  Is there a way around this?

**Comment by ftomassetti** [comment]
Thank you for reporting this. It seems something is wrong.

**Comment by matozoid** [comment]
Actually, "super(foo)" is considered a statement, not an expression. This will work:
        `Statement s = JavaParser.parseStatement("super.a(foo);");`

**Comment by matozoid** [comment]
Parsing this as an expression will be invalid starting from #163
