### ISSUE TITLE
Symbol Solver is missing type promotion in conditional expressions

### ISSUE THREAD

**Issue by matevzk** [javaparser/javaparser#2361]
The determination of the the result of conditional expression 
```java
(cond ? if_true_exp : if_false_exp)
``` 
is defined in Sect 15.25 of Java SE 8). Symbol Solver fails to determine the resulting type correctly in case when expressions type in branches are not of the same type. 

For instance, the resulting type of:  
```java
1 < 2 ? 1f : 1d
```
is double, as ```1f``` must be promoted to double.

Java Parser Version: 3.14.13

If we try to resolveObjectCreationExpr for the following code

```java
public class Test
{
   public class InnerClass
   {
       public InnerClass(float f) {}
       public InnerClass(double d) {}
   }
    
   public Test() {
     new InnerClass(1 < 2 ? 1f : 1d); 
   }
}
```
with the following code (codeSource is String with the above code)

```java
CombinedTypeSolver combinedSolver = new CombinedTypeSolver(new ReflectionTypeSolver());	    

ParserConfiguration pc = new ParserConfiguration()
    	                         .setSymbolResolver(new JavaSymbolSolver(combinedSolver))
    	                         .setLanguageLevel(LanguageLevel.JAVA_8);			

StaticJavaParser.setConfiguration(pc);

new VoidVisitorAdapter<Object>() {
    @Override
    public void visit(ObjectCreationExpr exp, Object arg) {
        System.out.println(exp.resolve().getSignature());
    }            
}.visit(StaticJavaParser.parse(codeSource), null);
```

constructor is resolved to InnerClass(float) instead of InnerClass(double).

**Comment by MysterAitch** [comment]
Interesting spot, and thank you for the very clear description! 

For anyone else reading, here are links to the relevant sections of documentation.

- Section 15.25: https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.25
- Section 5.6.2: https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.6.2

The part I learned about just now by following up on this is that the mere presence of a double in one of the branches of the ternary operator (per tables 15.25-A/B/C) causes "binary numeric promotion" to be applied (described in section 5.6.2). 

This means that `new InnerClass(1 < 2 ? 1f : 1d);` in the test sample can be simplified to `new InnerClass(true ? 1f : 1d);` which seems to emphasise the counter-intuitive (but logical) behaviour.

**Comment by MysterAitch** [comment]
Just noticed the related issue #2360 about unary numeric promotion (where this issue describes binary numeric promotion) -- commenting here with the issue number to make GitHub create a link between the two related issues.

**Comment by jlerbsc** [comment]
This issue is related to #1743 . This is resolved since Dec 2020.
