### ISSUE TITLE
Unary bitwise complement in constructor causes JavaParserFacade exception 

### ISSUE THREAD

**Issue by matevzk** [javaparser/javaparser#2362]
Unary bitwise complement (```~```) in constructor argument causes JavaParserFacade exception.

Java Parser Version: 3.14.13

If we try to resolveObjectCreationExpr for the following code

```java
public class Test
{
   public class InnerClass
   {
       public InnerClass(int i) {}
   }
    
   public Test() {
     new InnerClass(~8); 
   }
}
```
with the following code (codeSource is String with the above code)

```java
CombinedTypeSolver combinedSolver = new CombinedTypeSolver(new ReflectionTypeSolver());	    

ParserConfiguration pc = new ParserConfiguration()
    	                         .setSymbolResolver(new JavaSymbolSolver(combinedSolver))
    	                         .setLanguageLevel(LanguageLevel.JAVA_8);			

StaticJavaParser.setConfiguration(pc);

new VoidVisitorAdapter<Object>() {
    @Override
    public void visit(ObjectCreationExpr exp, Object arg) {
        System.out.println(exp.resolve().getSignature());
    }            
}.visit(StaticJavaParser.parse(codeSource), null);
```

causes exception in line 25 of com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade class.

**Comment by SimonBaars** [comment]
It's an exception on line 225 of `com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade`. This is indeed a bug in the symbol resolver. I will check if I can resolve it :)

**Comment by matevzk** [comment]
yeah, I should work on my typing skills 25 -> 225

**Comment by SimonBaars** [comment]
This should solve the issue :)
