### ISSUE TITLE
Symbol Solver unable to resolve nested classes

### ISSUE THREAD

**Issue by matevzk** [javaparser/javaparser#2366]
Symbol Solver unable to resolve nested classes in object creation expressions.

Java Parser Version: 3.14.13

If we try to resolveObjectCreationExpr for the following code

```java
public class Test
{
   public class InnerTest
   {
       public InnerTest(int i) {}
   }
    
   public Test() {
   }

   public static void main( String[] args ) { 
       new Test().new InnerTest();
   }
}
```
with the following code (codeSource is String with the above code)

```java
CombinedTypeSolver combinedSolver = new CombinedTypeSolver(new ReflectionTypeSolver());	    

ParserConfiguration pc = new ParserConfiguration()
    	                        .setSymbolResolver(new JavaSymbolSolver(combinedSolver))
    	                        .setLanguageLevel(LanguageLevel.JAVA_8);			

StaticJavaParser.setConfiguration(pc);

new VoidVisitorAdapter<Object>() {
    @Override
    public void visit(ObjectCreationExpr exp, Object arg) {
        System.out.println(exp.resolve().getSignature());
    }            
}.visit(StaticJavaParser.parse(codeSource), null);
```

causes exception in line 156 of com.github.javaparser.ast.CompilationUnit.JavaSymbolSolver class.

Interestingly, if inner class constructor is removed Symbol Solver is able to resolve inner class object creation expression, but not outer class object creation expression.

If you try to parenthesize outer class object creation expression:  ```(new Test()).new InnerTest();```  Symbol Solver simply hangs.

**Comment by SimonBaars** [comment]
I don't think this has anything to do with the nesting of the classes here. Your code is incorrect. You call `new Test().new InnerTest();` while there is no constructor without arguments in the class. `new Test().new InnerTest(1);` should work.

**Comment by matevzk** [comment]
True, typo on my behalf. 

After correction Symbol Solver handles object expression for InnerTest class but still misses object creation expression for Test class.

**Comment by SimonBaars** [comment]
Are there even two `ObjectCreationExpressions`? When I run your test Javaparser only finds a single `ObjectCreationExpression`. This would imply a bug on Javaparsers side, not the symbol solver.

**Comment by matevzk** [comment]
Indeed, this seems to be a Javaparser bug.

**Comment by SimonBaars** [comment]
I will create a new issue for it then. Thanks for the report!

**Comment by SimonBaars** [comment]
@matozoid  solved the problem, it was not a JavaParser bug.

```
CombinedTypeSolver combinedSolver = new CombinedTypeSolver(new ReflectionTypeSolver());	    

ParserConfiguration pc = new ParserConfiguration()
    	                        .setSymbolResolver(new JavaSymbolSolver(combinedSolver))
    	                        .setLanguageLevel(LanguageLevel.JAVA_8);			

StaticJavaParser.setConfiguration(pc);

new VoidVisitorAdapter<Object>() {
    @Override
    public void visit(ObjectCreationExpr exp, Object arg) {
        super.visit(exp, arg);
        System.out.println(exp.resolve().getSignature());
    }            
}.visit(StaticJavaParser.parse(codeSource), null);
```

You forgot the `super.visit(exp, arg);` call.
