### ISSUE TITLE
Comments of added Nodes are ignored in LexicalPreservingPrinter

### ISSUE THREAD

**Issue by Implex1v** [javaparser/javaparser#2374]
Given this example code
```java
public class Bar {
    public void foo() {
        System.out.print("Hello");
    }
}
```
If I parse it with javaparser and setup the AST with the LPP and adding a new node as
```java
Statement stmt = StaticJavaParser.parseStatement("System.out.println(\"World!\");");
stmt.setLineComment("Example comment");
```
the result of `LexicalPreservingPrinter#print` will look like this:
```java
public class Bar {
    public void foo() {
System.out.print("Hello!");
System.out.println("World!");
    }
}
```
I have taken a look into the code and found out, that the CSM does not fully support comments as `CsmComment`. Is there any plan to support these comments or is it even a bug? I found a work around for it by adding the new node to the AST first and afterwards adding the comment to the added node. Thank you!

**Comment by matozoid** [comment]
Yes, that's very likely a bug.

**Comment by matozoid** [comment]
I hear the PR didn't fix the issue.

**Comment by jlerbsc** [comment]
In fact i think there is probably no issue. The code below doesn't reproduce the issue because the comment is associated to a statement which is not  printed by lexical preserving printer.

    Statement stmt = StaticJavaParser.parseStatement("System.out.println(\"World!\");");
    stmt.setLineComment("Example comment");

While this one shows the comment with lexical preserving printer

    Expression expr = StaticJavaParser.parseExpression("System.out.println(\"World!\")");
    expr.setLineComment(lineComment);
    Statement stmt = new ExpressionStmt(expr);

**Comment by matozoid** [comment]
It's not very intuitive though?

**Comment by jlerbsc** [comment]
Lexical preserving printer doesn't take into account ExpressionStmt node. May be it is related to the fact that ExpressionStmt is a wrapper on Expression and not really a node!

**Comment by matozoid** [comment]
Comments, they are always trouble... So the idea that ExpressionStmt does not have its own data is actually wrong: it can have a comment and we should consider it! ... but it looks like it does: https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/ConcreteSyntaxModel.java#L604

**Comment by Implex1v** [comment]
Here are my two cents:
As far as I understand the LPP a syntax model is created for every node, which is related to a CST (Concrete Syntax Tree). These model nodes are the Csm* classes. Actually there is one for comments (`CsmComment`) and for my example a node of this type is generated. Unfortunately these are ignored by the [LexicalDifferenceCalculator](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalDifferenceCalculator.java#L138). I would say that here the comment must be added to the `elements` list, but the [CsmComment](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/concretesyntaxmodel/CsmComment.java) node does not contain any reference to the AST or a text string except the pretty printing.
I would assume that the `CsmComment` feature is left out or it's implemented elsewhere. Maybe it's helpful.
