### ISSUE TITLE
Who can tell me what is the advantage of comparison with Eclipse-JDT

### ISSUE THREAD

**Issue by chenzhegodspeed** [javaparser/javaparser#2377]
As I known, JDT can also parse java source code or analyze it in project level(depends on Eclipse-Platform).  So I am not sure this project is more powerful than JDT or it is convenient for developers without Eclipse-platform dependency.

**Comment by matozoid** [comment]
Hi! I maintain this project because five or six years ago I wanted to parse some code and couldn't easily get started with the JDT. This looked like a much simpler project, so I patched it up (it was abandoned) and now it's a nice alternative - especially the parser and AST are quite streamlined. We have a little book/tutorial too. The nice thing is that everything is meant to be used by you, the user, not by Eclipse, the huge IDE. There's also the Spoon project which is a mix of JDT and custom code - https://tomassetti.me/analyze-generate-and-transform-java-code/

It's up to you :-)

**Comment by edefazio** [comment]
Speaking as a user, I'd say just looking at the amount of code you have to write to do (IMHO) trivial things in JDT was a turn off... I read this:
[https://www.vogella.com/tutorials/EclipseJDT/article.html#adding-a-hello-world-statement-using-the-ast](https://www.vogella.com/tutorials/EclipseJDT/article.html#adding-a-hello-world-statement-using-the-ast)

...and to do something like build some code, then add some code into the code was a downer:

```java
String source = String.join("\n",
        "public class HelloWorld {",
        "    public static void main(String[] args) {",
                  // Insert the following statement.
                  // System.out.println("Hello, World");
        "    }",
        "}");

ASTParser parser = ASTParser.newParser(AST.JLS8);
parser.setSource(source.toCharArray());
parser.setKind(ASTParser.K_COMPILATION_UNIT);

CompilationUnit unit = (CompilationUnit) parser.createAST(new NullProgressMonitor());

unit.accept(new ASTVisitor() {

    @SuppressWarnings("unchecked")
    public boolean visit(MethodDeclaration node) {
        AST ast = node.getAST();

        MethodInvocation methodInvocation = ast.newMethodInvocation();

        // System.out.println("Hello, World")
        QualifiedName qName =
                   ast.newQualifiedName(
                            ast.newSimpleName("System"),
                            ast.newSimpleName("out"));
        methodInvocation.setExpression(qName);
        methodInvocation.setName(ast.newSimpleName("println"));

        StringLiteral literal = ast.newStringLiteral();
        literal.setLiteralValue("Hello, World");
        methodInvocation.arguments().add(literal);

        // Append the statement
        node.getBody().statements().add(ast.newExpressionStatement(methodInvocation));

        return super.visit(node);
    }
});
```
...simple things should be simple, hard things doable (or so they say) and this seemed like alot of things to learn and alot of code to write to do IMHO a very trivial amount of work.

**Comment by chenzhegodspeed** [comment]
@matozoid  Well. I have same reason that I can't get started with the JDT easily,A lot extra work need to do to replace all Eclipse Platform Dependency. I hope there is a specific document but I only find a **javavisit** PDF book.

**Comment by chenzhegodspeed** [comment]
@edefazio Redundant code for me using JDT is fine. The most important is that I can't migrate my program out of Eclipse Plug-in environment easily.

**Comment by edefazio** [comment]
sounds like you've made up your mind... :)
use the right tool for the job

**Comment by chenzhegodspeed** [comment]
@edefazio Yes. I am using Javaparser now and I will estimate my cases for some time.

**Comment by matozoid** [comment]
@chenzhegodspeed - the web site has all the sources of information: https://javaparser.org/getting-started/
