### ISSUE TITLE
How to parse references to static fields

### ISSUE THREAD

**Issue by sischnei** [javaparser/javaparser#2379]
Hi guys,

I hope this is the right place to asks questions, if not please advise where a better place would be!

I have the following java source to parse:

    private final static String BASE = "base";
    private final static String EXTENSION = "some text and it's " + BASE;

    @MyAnnotation(value = EXTENSION)
    public void someMethod() { ... }

Specifically I'm interested in how to resolve the reference to EXTENSION:

    @Override
    public void visit(final MethodDeclaration methodDeclaration, final StepClass stepClass) {
        Optional<AnnotationExpr> myAnnotation = methodDeclaration.getAnnotationByName("MyAnnotation");
        //TODO how do I get the value of the extension which should be "some text and it's base"
    }

I already gave the symbol parser a try, but it seems it's only able to resolve types - or did I miss something?

**Comment by jlerbsc** [comment]
I think you have to get the variable declaration from the MemberValuePair attribute defined in the list of children of the AnnotationExpr class. It's not very intuitive!

    MemberValuePair n = (MemberValuePair) myAnnotation.get().getChildNodes().get(1);
    Expression value = n.getValue();
    Optional<VariableDeclarator> fd = cu.findFirst(VariableDeclarator.class, expr -> ((VariableDeclarator)expr).getNameAsString().equals(value.toString()));
    System.out.println(fd.get().getInitializer().toString());

**Comment by matozoid** [comment]
This is out of scope of the project because of the string concatenation: that happens either runtime by the JRE or in an optimization step of the compiler. So, maybe you can get to it by inspecting the compiled class file, or maybe you will have to run the application. JP does not compile or run source code.

**Comment by sischnei** [comment]
Ok - thanks both for your answer!

**Comment by matozoid** [comment]
No problem, good luck!
