### ISSUE TITLE
Recreate Intellij formatting settings file

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#238]
The one that is in dev-files right now is either unusable in newer intellij's, or I just don't know how to import it.

**Comment by SmiddyPence** [comment]
Think you need to move it on the file system:

```
On Linux:  ~/.IdeaIXXX/config/codestyles
On Mac: ~/Library/Preferences/IntelliJIdeaXXX/codestyles
On Windows: c:\Users\UserName.IdeaIXXX\config\codestyles
```

Something like that, then restart IntelliJ and `Settings -> Editor ->Code Style -> Java` then in the Scheme drop down.

**Comment by SmiddyPence** [comment]
@matozoid did you solve this with the above suggestion?

**Comment by matozoid** [comment]
I'll try asap.

**Comment by matozoid** [comment]
Tried it. It works. :+1:  Sorry for the delay.
For the current non-community version on Linux it's ~/.IntelliJIdea15/config/codestyles but I guess the examples are clear enough.
