### ISSUE TITLE
How to retrieve all compilation errors of all classes in the given folder

### ISSUE THREAD

**Issue by jy95** [javaparser/javaparser#2383]
Hello,

My question is the one in the title. I read these resources but couldn't find my answer : 

- [Semantic validations](https://javaparser.org/semantic-validations-in-javaparser/) 
- [Java8Validator](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.3.1/com/github/javaparser/ast/validator/Java8Validator.html) 
- [ProblemReporter](https://static.javadoc.io/com.github.javaparser/javaparser-core/3.3.2/com/github/javaparser/ast/validator/ProblemReporter.html)

For example, let's take an example of someone that merged Java and Python : 
```java
public class Test {
    private int x = 42 // missing a semi colon here
    public sayHello() { // here the fault is that this person forgets a return type
          return "";
    }
}
```

For each problem, I would to be able to show the text of the line with the problem.
Using my example : 
```
private int x = 42                       ;' expected
....
```
Thanks for your help.

**Comment by edefazio** [comment]
I'm not sure you are going to get what you you think you are going to (all errors) 
if there is more than one Syntactical error... 
(And I believe the Validators operate on syntactically valid Java code but "know" the differences
between "valid" code for Java 1.7 and Valid code for Java 1.8
(i.e. the code 
"Predicate<String> STARTSWITH = (s)->s.startsWith("a");" 
...is syntactically valid Java code for Java 1.8 and later but INVALID for 1.7 or before 
(Lambda expressions were introduced in Java 1.8)

(but @matazoid can correct me if I'm wrong here):

Here's how if you parse you can get the errors back
```java
    public void testReadAndGetAllParseErrors(){
        String c =
                "public class Test {\n" +
                "    private int x = 42 // missing a semi colon here\n" +
                "    public sayHello() { // here the fault is that this person forgets a return type\n" +
                "          return \"\";\n" +
                "    }\n" +
                "}";

        JavaParser jp = new JavaParser( new ParserConfiguration() );

        ParseResult<CompilationUnit> pr = jp.parse(c);

        List<Problem> prbs = pr.getProblems();

        prbs.forEach(p -> System.out.println( p ));

    }
```

**Comment by matozoid** [comment]
There are no compilation errors in JavaParser since it is not a compiler. There is a large amount of errors that JavaParser does not report.

That said, @edefazio's example is nice. For "in the given folder" you can use `SourceRoot`, make it parse a directory of files, the take all the resulting `ParseResult`s and use the `Problem`s that occurred as you like.

**Comment by jy95** [comment]
Oups I used the wrong word ... ( parsing instead of compilation )
A static analysis is just what I needed :)
