### ISSUE TITLE
Simple assignment can't be parsed

### ISSUE THREAD

**Issue by Caellian** [javaparser/javaparser#2385]
I keep getting same errors on multiple files generated by fernflower decompiler. Sorry for obfuscated code, I can't publish mapped code. If mappings are needed, I can provide them in a link.

I was parsing code using `StaticJavaParser.parse(...)` function.

Source context:
```java
            if (var6 < 0.2F)
               this.a = bon.dp.n();
            } else if (var6 < 0.5F) {
               this.a = bon.do.n();       // Line 159
            } else if (var6 < 0.55F) {
               this.a = bon.dt.n();
            } else {
               this.a = bon.dn.n();
            }
```
Stacktrace:
```
com.github.javaparser.ParseProblemException: (line 159,col 25) Parse error. Found ".", expected one of  "!=" "%" "%=" "&" "&&" "&=" "(" "*" "*=" "+" "+=" "-" "-=" "->" "/" "/=" "::" ";" "<" "<<=" "<=" "=" "==" ">" ">=" ">>=" ">>>=" "?" "^" "^=" "instanceof" "|" "|=" "||"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10667)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10526)
  com.github.javaparser.GeneratedJavaParser.StatementExpression(GeneratedJavaParser.java:4177)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3776)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3953)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1659)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3871)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3731)
  com.github.javaparser.GeneratedJavaParser.IfStatement(GeneratedJavaParser.java:4379)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3784)
  com.github.javaparser.GeneratedJavaParser.IfStatement(GeneratedJavaParser.java:4384)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3784)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3953)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1659)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3871)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3731)
  com.github.javaparser.GeneratedJavaParser.IfStatement(GeneratedJavaParser.java:4379)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:3784)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:3953)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1659)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3871)
  com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1264)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:959)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:851)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:408)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:919)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:851)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:408)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:154)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parse(JavaParser.java:305)
  com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
  hr.caellian.unmapper.file.transformer.Remapper.transformStream(Remapper.kt:17)
  hr.caellian.unmapper.file.FileProcessor.transform(FileProcessor.kt:21)
  hr.caellian.unmapper.Unmapper.main(Unmapper.kt:73)

	at com.github.javaparser.StaticJavaParser.handleResult(StaticJavaParser.java:260)
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
	at hr.caellian.unmapper.file.transformer.Remapper.transformStream(Remapper.kt:17)
	at hr.caellian.unmapper.file.FileProcessor.transform(FileProcessor.kt:21)
	at hr.caellian.unmapper.Unmapper.main(Unmapper.kt:73)
```

Ask for additional info.

**Comment by matozoid** [comment]
Hi! FernFlower used the keyword `do` as an identifier. That's not valid Java.

**Comment by Caellian** [comment]
You are right. Didn't notice that.

In case anyone else with the same problem comes across this:
Obfuscators don't care whether member (field/variable, method/function) names are valid as they don't matter to JVM.

Fernflower also decompiles varargs and root package class paths wrong, there might be other issues but those are the ones I came across so far.

**Comment by matozoid** [comment]
It would be good to report those to the Fernflower project, they might add some code to rename problematic identifiers etc.

**Comment by Caellian** [comment]
Fernflower allows renaming identifiers, I was working on Minecraft deobfuscation so renaming wasn't an option as mappings wouldn't work. Later figured out javaparser is probably not the right fit as the code can be deobfuscated during decompilation which would make the whole process a lot easier.

Is there a way of using javaparser with multiple sources in such a way that renaming class variable would also rename references to it from elsewhere in code? I'm guessing that would require building an index of some sort and would end up being a lot of work to implement. If you know of a project doing that, I might find that very useful soon.

Fernflower is currently maintained by JetBrains but it's part of IDEA repo which makes it very hard for people to contribute or use it separately. I might create an issue on IDEA repo asking them to separate it from the project though.

**Comment by matozoid** [comment]
> Is there a way of using javaparser with multiple sources in such a way that renaming class variable would also rename references to it from elsewhere in code? I'm guessing that would require building an index of some sort and would end up being a lot of work to implement. If you know of a project doing that, I might find that very useful soon.

Sounds like you want to take the symbol solver and look for all the names that resolve to the name of the field you're renaming. It would be smart to build an index, because the solver is not known for being very speedy.
