### ISSUE TITLE
JavaParserClassDeclaration canBeAssignedTo gives wrong result when reaches Object as super type

### ISSUE THREAD

**Issue by PeterCsubak** [javaparser/javaparser#2387]
If I configure a `ReflectionTypeSolver` and try to determine wether a parsed class extends an other class with the `JavaParserClassDeclaration.canBeAssignedTo()` method, and the parsed java class doesn't extend any other class this method will still report as a match.

I've done some debugging and found this part of the code, which I think causes the wrong results:
```
        ResolvedClassDeclaration superclass = (ResolvedClassDeclaration) getSuperClass().getTypeDeclaration();
        if (superclass != null) {
            // We want to avoid infinite recursion in case of Object having Object as ancestor
            if (Object.class.getCanonicalName().equals(superclass.getQualifiedName())) {
                return true;
            }
            if (superclass.canBeAssignedTo(other)) {
                return true;
            }
        }
```

It checks if the superclass is the `Object` but it doesn't check if the other class is also the `Object` class, which means it will return true for every class if the `java.lang.Object` can be resolved by a `TypeSolver`.

Am I guessing right, or did I miss something?

**Comment by MysterAitch** [comment]
@PeterCsubak - Do you have some sample code to hand where this causes odd behaviour, perchance? Ideally as a failing unit test :) 

Sidenote: I'm wondering if this is playing a factor in #2484 where there is odd things happening with comparing `Class<>` vs `Class<? extends Object>` vs 'Class<? extends X>` generics, but can't quite get my head around it just yet.

**Comment by PeterCsubak** [comment]
@MysterAitch Hi I've created a PR where I also added a fix for the problem. If you revert my changes in the `JavaParserClassDeclaration` you will see in the test that the `canBeAssignedTo` says the `CompilationUnit` can be assigned to `String` which I guess isn't the expected result. :) 

Sorry I don't really remember where it caused problems in my code (I've fixed it some other way, probably :) ), hence I don't have any complex tests for it, so I cannot confirm your suspicions about #2484

**Comment by MysterAitch** [comment]
Brill, cheers! 

The test case is much appreciated, though I'm not sure the fix is quite right. I'll comment on the pr in a moment.

**Comment by MysterAitch** [comment]
Here are some extra test combinations and descriptions of the rationales for the combinations -- are there any that are missing or could be expanded on?

```java
    @Test
    void testCanBeAssignedTo() {
        JavaParserClassDeclaration compilationUnit = (JavaParserClassDeclaration) typeSolver.solveType("com.github.javaparser.ast.CompilationUnit");
        ResolvedReferenceTypeDeclaration stringTypeDeclaration = typeSolver.solveType("java.lang.String");
        ResolvedReferenceTypeDeclaration objectTypeDeclaration = typeSolver.solveType("java.lang.Object");
        ResolvedReferenceTypeDeclaration cloneableTypeDeclaration = typeSolver.solveType("java.lang.Cloneable");


        // Assign "UP" (implicit) -- Assign to implicitly state ancestor (java.lang.Object) -- should be permitted
        assertTrue(compilationUnit.canBeAssignedTo(objectTypeDeclaration),"CompilationUnit should be reported as assignable to Object");

        // Assign "UP" (explicit) -- Assign to explicitly stated ancestors (extends/implements) -- should be permitted
        assertTrue(compilationUnit.canBeAssignedTo(cloneableTypeDeclaration),"CompilationUnit should be reported as assignable to Cloneable, because it extends Node which implements Cloneable");

        // Assign "SELF" -- Assign to self -- should be permitted
        assertTrue(compilationUnit.canBeAssignedTo(compilationUnit),"CompilationUnit should not be reported as assignable to CompilationUnit");
        assertTrue(stringTypeDeclaration.canBeAssignedTo(stringTypeDeclaration),"String should not be reported as assignable to String");
        assertTrue(objectTypeDeclaration.canBeAssignedTo(objectTypeDeclaration),"Object should be reported as assignable to Object");


        // Assign "DOWN" -- Assign ancestor to descendent -- should be rejected
        assertFalse(cloneableTypeDeclaration.canBeAssignedTo(compilationUnit),"CloneableTypeDeclaration should not be reported as assignable to CompilationUnit");
        assertFalse(objectTypeDeclaration.canBeAssignedTo(compilationUnit),"Object should not be reported as assignable to CompilationUnit");

        // Assign "independent" -- Assign to a class with a completely separate/independent hierarchy tree (up to Object, down to other) -- should be rejected
        assertFalse(compilationUnit.canBeAssignedTo(stringTypeDeclaration),"CompilationUnit should not be reported as assignable to String");

    }
```
