### ISSUE TITLE
LexicalPreservingPrinter and replace doesn't seem to work properly

### ISSUE THREAD

**Issue by Implex1v** [javaparser/javaparser#2393]
When using JavaParser 3.15.0 and running this example code
```java
CompilationUnit compilationUnit = StaticJavaParser.parse("public class Test { public void foo() { int i = 0;\nif(i == 5) { System.out.println(i); } } }");
LexicalPreservingPrinter.setup(compilationUnit);
IfStmt ifStmt = compilationUnit.findFirst(IfStmt.class).orElseThrow(() -> new IllegalStateException("Expected if"));
ifStmt.setCondition(StaticJavaParser.parseExpression("i > 0"));
```
the following exception is thrown
> Exception in thread "main" java.lang.UnsupportedOperationException: kept token(() vs ChildTextElement{i == 5}
> 	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:514)
> 	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:147)
> 	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatePropertyChange(LexicalDifferenceCalculator.java:120)
> 	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concretePropertyChange(LexicalPreservingPrinter.java:179)
> 	at com.github.javaparser.ast.observer.PropagatingAstObserver.propertyChange(PropagatingAstObserver.java:62)
> 	at com.github.javaparser.ast.Node.lambda$notifyPropertyChange$3(Node.java:564)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
> 	at com.github.javaparser.ast.Node.notifyPropertyChange(Node.java:564)
> 	at com.github.javaparser.ast.stmt.IfStmt.setCondition(IfStmt.java:112)
> 	at Test.main(Test.java:13)

If I remove the LPP call the exception will not occur.

**Comment by jlerbsc** [comment]
@matozoid The algorithm implemented to manage Difference in LexicalPreservingPrinter is very confuse, complexe and there is no comment or unit test to understand/validate it. I propose to implement a default strategy instead of generate UnsupportedOperationException (For exemple increment each indexes). Hopefully this default strategy will cause fewer problems.

**Comment by matozoid** [comment]
@jlerbsc that would be a decent patch. Even though it indicates a bug when this exception is thrown, it happens rather often, and the printer becomes useless when you run into it. Maybe print a warning with `Log`.

Longer term: reimplement the whole thing directly in the AST.

**Comment by jlerbsc** [comment]
A bug or a case that is not handled.
