### ISSUE TITLE
How to get the type of references

### ISSUE THREAD

**Issue by heshuguo** [javaparser/javaparser#2401]
The example from the javaparser guide,

```java 
class Bar {
	private String a;
	void aMethod() {
		while (true) {
			int a = 0;
			a = a + 1;
		}
	}
}
```

```java
 public class GetTypeOfReference {
	private static final String FILE_PATH = "src/main/java/org/javaparser/examples/chapter5/Bar.java";

	public static void main(String[] args) throws FileNotFoundException {
		TypeSolver typeSolver = new CombinedTypeSolver();

		JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
		StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

		CompilationUnit cu = StaticJavaParser.parse(new File(FILE_PATH));

		cu.findAll(AssignExpr.class).forEach(ae -> {
			ResolvedType resolvedType = ae.calculateResolvedType();
			System.out.println(ae.toString() + " is a: " + resolvedType);
		});
	}
}
```

The expected output would be: Type of `a = a + 1` is `PrimitiveTypeUsage{name='int')`
But I can not get the expected result. I got an error:

`Exception in thread "main" java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.`

What is the right way to do this?

**Comment by heshuguo** [comment]
the version is 3.15.0

**Comment by matozoid** [comment]
The error means that the symbol solver was not found inside the AST Nodes. The code sets it correctly, so have you ran *exactly* this example?

(I can't try it right now)

**Comment by heshuguo** [comment]
No, not the same. I changed it again, just a little.
```java
class Bar {
	private int a;
	void aMethod() {
		while (true) {
			String a = "0";
			a = a + "1";
		}
	}
}
```
Got the error: `Exception in thread "main" UnsolvedSymbolException{context='null', name='String', cause='null'}.`

**Comment by matozoid** [comment]
Alright, that's a completely different error.

Here's a guaranteed working sample: https://github.com/javaparser/javasymbolsolver-maven-sample

**Comment by heshuguo** [comment]
Thank you. but It still can not help to resolve the error. Would you please provide a solution to resolve the error?

**Comment by matozoid** [comment]
I did not create that part of the application, nor do I use it, and neither is anyone maintaining it, so I'm afraid that unless someone else comes in, you'll have to use the manual and the sample to figure it out.

**Comment by heshuguo** [comment]
Ok. you can close it now. I will try to figure out. Thank you.

**Comment by matozoid** [comment]
Okay, sorry for not being very useful.
