### ISSUE TITLE
Empty javadoc results in IndexOutOfBoundsException in JavadocParser

### ISSUE THREAD

**Issue by bedlaj** [javaparser/javaparser#2404]
See https://github.com/revelc/impsort-maven-plugin/issues/16

Parsing of empty javadoc, eg:

    /**
    */
    public class SomeClass {
        List something = new ArrayList();
    }

Fails with IndexOutOfBoundsException

    Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck (ArrayList.java:653)
    at java.util.ArrayList.get (ArrayList.java:429)
    at com.github.javaparser.JavadocParser.cleanLines (JavadocParser.java:124)
    at com.github.javaparser.JavadocParser.parse (JavadocParser.java:50)

**Comment by edefazio** [comment]
Looks like you are using an older version of JavaParser
(this class doesnt seem to exist in the new JavaParser core)

I googled it and I could find this class in JavaParser 3.2.12:

https://jar-download.com/artifacts/com.github.javaparser/javaparser-core/3.2.12/source-code/com/github/javaparser/JavadocParser.java

...current version is : 3.15.3
I ran the code below and it worked fine:
```java
    public void testJ(){
        CompilationUnit cu = StaticJavaParser.parse(
                "/**\n"+
                "*/\n"+
                 "public class SomeClass {\n"+
                 "    List something = new ArrayList();\n"+
                 "}");
    }
```
might want to tell the maintainers of the tool to upgrade.

**Comment by bedlaj** [comment]
This class exists in current master and the issue is still here. Check attached PR

**Comment by edefazio** [comment]
sorry I just approved your PR 
(my mistake, you are correct)
