### ISSUE TITLE
@throws used to parse as JavadocSnippet, but now doesn't

### ISSUE THREAD

**Issue by ctubbsii** [javaparser/javaparser#2408]
There seems to be some bug in the Javadoc description parsing between 3.14.5 and 3.15.4 that broken parsing `@throws` tags as instances of JavadocSnippet.

See https://github.com/revelc/impsort-maven-plugin/issues/19

**Comment by edefazio** [comment]
I'm not extremely versed in this... but in this case, wouldn't you be looking for a `JavadocBlockTag` and not a `JavaDocSnippet`?

I ran this code and was able to find the @throws tag:
```java
    public void testCheckJavadoc(){

        class t{
            /**
             * @throws IOException
             */
            public void mm(){}
        }
        CompilationUnit cu =Ast.of(t.class);
        MethodDeclaration md = cu.getType(0).getMethods().get(0);
        JavadocComment jdc = md.getJavadocComment().get();

        Javadoc jd = md.getJavadoc().get();
        List<JavadocBlockTag> jdb = jd.getBlockTags();
        System.out.println( jdb );

    }
```

returned:
[JavadocBlockTag{type=THROWS, content='JavadocDescription{elements=[]}', name=Optional[IOException]}]

FWIW, heres the javadoc of JavaDocSnippet (FWIW ive never used this class)
looks like the @ tags are JavadocBlockTags, the <code> tags define snippets
```
/**
 * A piece of text inside a Javadoc description.
 * <p>
 * For example in <code>A class totally unrelated to {@link String}, I swear!</code> we would have two snippets: one
 * before and one after the inline tag (<code>{@link String}</code>).
 */
```

**Comment by ctubbsii** [comment]
If I understand things correctly, when you call `JavadocBlockTag.getContent()`, it parses that content and returns a `JavadocDescription` object, which is where the `JavadocSnippet` comes in, as an element of the `JavadocDescription` object.

As a workaround, instead of calling `JavadocBlockTag.getContent()`, I called `JavadocDescription.parseText(javadocBlockTag.toText())`. It doesn't quite work perfectly (it includes the tag name), but it fixes the bug (see PR https://github.com/revelc/impsort-maven-plugin/pull/20)

**Comment by matozoid** [comment]
Could this one be the cause? https://github.com/javaparser/javaparser/pull/2396

**Comment by matozoid** [comment]
If I run this:
```java

    public static void main(String[] args) {
        Javadoc javadoc = JavadocParser.parse("/**\n@throws A a a a a\n*/");
        JavadocBlockTag javadocBlockTag = javadoc.getBlockTags().get(0);
        Optional<String> name = javadocBlockTag.getName();
        JavadocDescription content = javadocBlockTag.getContent();
        System.out.println(name);
        System.out.println(content.toText());
    }
```

... name is "A" and content is "a a a a\n/".

So, there is a bug with a slash somehow ending up in the content. Also,

```java
        Javadoc javadoc = JavadocParser.parse("/**@throws A a a a a*/");
```
doesn't even recognize the block tag. Another bug. That's what we get for using a custom parser instead of simply using JavaCC for the grammar.

But I don't see the problem described here?

**Comment by ctubbsii** [comment]
I created an example project to demonstrate the issue at https://github.com/ctubbsii/javaparser-example-project.

When running with version 3.14.5, the output is:
```
JavadocBlockTag{type=SEE, content='JavadocDescription{elements=[JavadocSnippet{text='Map'}]}', name=Optional.empty}
JavadocBlockTag{type=PARAM, content='JavadocDescription{elements=[JavadocSnippet{text='used for nothing'}]}', name=Optional[blah]}
JavadocBlockTag{type=SEE, content='JavadocDescription{elements=[JavadocSnippet{text='Type8#method()'}]}', name=Optional.empty}
JavadocBlockTag{type=SEE, content='JavadocDescription{elements=[JavadocSnippet{text='Type9#method(Type10)'}]}', name=Optional.empty}
JavadocBlockTag{type=THROWS, content='JavadocDescription{elements=[JavadocSnippet{text='Type11 when situation occurs'}]}', name=Optional.empty}
```

When running with version 3.15.4, the output is:

```
JavadocBlockTag{type=SEE, content='JavadocDescription{elements=[JavadocSnippet{text='Map'}]}', name=Optional.empty}
JavadocBlockTag{type=PARAM, content='JavadocDescription{elements=[JavadocSnippet{text='used for nothing'}]}', name=Optional[blah]}
JavadocBlockTag{type=SEE, content='JavadocDescription{elements=[JavadocSnippet{text='Type8#method()'}]}', name=Optional.empty}
JavadocBlockTag{type=SEE, content='JavadocDescription{elements=[JavadocSnippet{text='Type9#method(Type10)'}]}', name=Optional.empty}
JavadocBlockTag{type=THROWS, content='JavadocDescription{elements=[JavadocSnippet{text='when situation occurs'}]}', name=Optional[Type11]}
```

When I originally tested this, I did not have the "when situation occurs" text description in the `@throws`, so the elements array in `JavadocDescription` was simply empty instead of containing a `JavadocSnippet` with text "Type11", which was the behavior in 3.14.5.

I now understand the change in #2396 was the reason for the behavioral change, and that it was intended. Previously, I only had to inspect `JavadocSnippet`s in my own code. Now (at least for `@throws` and `@exception`), I also have to check for the content of the optional name field. This is okay with me... I just wasn't expecting the behavior change in a patch release and thought it was a bug (and also was confused by the fact that "name" in this case isn't actually a variable name, but an exception object type).

Feel free to close this issue, since it's not actually a bug, but merely a confusing breaking change in behavior (ultimately, for the better, though).

**Comment by matozoid** [comment]
Alright, thanks! I've learned that...
- this should have been in the changelog. Sorry for that.
- the name `name` is a misnomer here. What would be a better API for this? All I can think of now is calling it `key` which is a bit generic.

**Comment by edefazio** [comment]
Not to be a complainer, but TBH I'm not too fond of the name `JavadocBlockTag`
because that seems more like a code block (i.e. when (within a Javadoc) we add some html/code, i,.e.
```java
/**
 * here is an example: <PRE>
 * <code>this is a "block" of code</code>
 */
```

it'd be better IMHO to be `JavadocAtTag`, since what we are talking about must syntactically ALL start with @ or "at"
```java
/**
  * @param count the count of things
  * @throws SomeException when all else fails
  * @see org.blah.HeY#MyValue
  */
```

In lieu of changing the name of the class/API maybe use `atName` instead of `type` or `name` or `key` for the variable/getter?

my .02cents

**Comment by matozoid** [comment]
It's called block tag because that's what it is called :-) Check the manual for Javadoc: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html

Not that I disagree with it being a lousy name. We can still document the class as well as possible.

**Comment by edefazio** [comment]
You are correct... (sorry that naming stinks IMHO)
seems like they also use the terminology "Standalone Tag"

> Block and inline Tags
> 
> A tag is a special keyword within a documentation comment that the javadoc command processes. There are two kinds of tags: block tags, which appear as an @tag tag (**also known as standalone tags**), and inline tags, which appear within braces, as an {@tag} tag. To be interpreted, a block tag must appear at the beginning of a line, ignoring leading asterisks, white space, and the separator (/**). This means you can use the @ character elsewhere in the text and it will not be interpreted as the start of a tag. If you want to start a line with the @ character and not have it be interpreted, then use the HTML entity &#064;. Each block tag has associated text, which includes any text following the tag up to, but not including, either the next tag, or the end of the documentation comment. This associated text can span multiple lines. An inline tag is allowed and interpreted anywhere that text is allowed. The following example contains the @deprecated block tag and the {@link} inline tag. See Javadoc Tags.
> 
> 
> 

...and my favorite the **"Bock"** tag

> Tags have the following types:
> 
> **Bock** tags: Place block tags only in the tag section that follows the description. Block tags have the form: @tag.

https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html

**Comment by matozoid** [comment]
Open an issue if you'd like to see it renamed to JavadocStandaloneTag, because that sounds better to me too!

**Comment by edefazio** [comment]
I personally don't use it, so I'm fine...(Im not trying to do API breakage)... 

(I just was brainstorming about  your question):

> the name name is a misnomer here. What would be a better API for this? All I can think of now is calling it key which is a bit generic.

(so how about `tagName`... since that'd be "consistent" with how its talked about and used

> Javadoc Tags
> The javadoc command parses special tags when they are embedded within a Java documentation comment. The javadoc tags let you autogenerate a complete, well-formatted API from your source code. The tags start with an at sign (@) and are case-sensitive. They must be typed with the uppercase and lowercase letters as shown. A tag must start at the beginning of a line (after any leading spaces and an optional asterisk), or it is treated as text. **By convention, tags with the same name are grouped together**. For example, put all @see tags together. For more information, see Where Tags Can Be Used.

**Comment by ctubbsii** [comment]
Avoiding API breakage is a good idea. For that reason, I wouldn't change "name" or "JavadocBlockTag". But, I would ensure its different roles (parameter name for `@param`, and class name for `@exception` and `@throws`) is clear in the documentation.

**Comment by ctubbsii** [comment]
You could also sub-class the `JavadocBlockTag` into specific types, based on the tag type, and provide methods named appropriately for that tag type. Then, you wouldn't break `JavadocBlockTag` API, but you would provide more meaningful sub-class types with better named APIs.

**Comment by matozoid** [comment]
Definitely agree on better documentation.
A bit cautious about making users cast to subclasses because of lower discoverability.

Thanks for the feedback.

**Comment by ctubbsii** [comment]
> A bit cautious about making users cast to subclasses because of lower discoverability.

I think that ship has sailed, so to speak... this is already the normal situation when iterating over `compilationUnit.getComments()` in order to separate out `JavadocComment` instances from others, or when inspecting the results of `javadocDescription.getElements()` to separate out `JavadocInlineTag` from `JavadocSnippet`, or just when inspecting the `List<Node>` result from a call to `node.getChildNodes()` on any `Node` instance. This pattern of using subclasses to differentiate elements of the AST seems to be a dominant design pattern throughout javaparser... at least it seems so from how I've been using it :smiley_cat:.

**Comment by matozoid** [comment]
Oh, I'm not saying it isn't. It's just caused several issues and complaints up until now. So I'm trying to not over-specialize the nodes. For example:
- `AnnotationExpr` got a complaint that it doesn't really need the four subclasses. Fair.
- `SwitchEntry` on the other hand may be a little over-collapsed. That may be refactored into separate subclasses in the future.
- several issues were cause by people not being able to discover the way back from resolved type to AST nodes (which requires casting.)

**Comment by ctubbsii** [comment]
Understood. Thanks. Since the originally reported issue isn't actually a bug, but merely a misunderstood (on my part) behavior change, I'm going to go ahead and close this. While there's room for improvements, as discussed in these comments, they can be split into their own issues/PRs, as needed, by those motivated to do so. :smiley_cat:

**Comment by simonsirak** [comment]
Hi, it seems that issues #2409 #2410 are based on a misunderstanding; 

```Java
@Test
void parseSingleBlockTag() {
    Javadoc doc = JavadocParser.parse("@throws A a a a a");
    assertEquals("", doc.getDescription().toText());
    assertEquals("@throws A a a a a", doc.getBlockTags().get(0).toText());
}
```

This test will treat `@throws A a a a a` as the content of a comment. This test then shows correct behavior. The corresponding comment in the parsed source code would be `/**@throws A a a a a*/`. The parser will realise it is a javadoc comment, then consume the beginning and end of the comment (i.e `/**` and `*/`). Therefore, only the _content_ of the comment (i.e `@throws A a a a a` is pushed to the `JavadocComment` node in the abstract syntax tree, which would then delegate content parsing to the `JavadocParser`. So in reality, `/**@throws A a a a a*/` should never be passed to `JavadocParser`. 

If we suppose that `/**@throws A a a a a*/` would be treated as the content passed to `JavadocParser`(with a corresponding comment of `/** /**@throws A a a a a*/ */` which is technically not possible), then the `JavadocParser` correctly handles this according to the javadoc specification as purely a description. If the content was `/**@throws A a a a a\n*/`, then the _description_ would correctly consist of a line `/**@throws A a a a a` followed by a line `/` (since single leading asterisks are removed).

Should these issues perhaps be closed?

**Comment by matozoid** [comment]
Thanks @simonsirak !
