### ISSUE TITLE
@FunctionalInterface annotation should be used to flag Single Abstract Method interfaces

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#242]
A Single Abstract Method (SAM) interface is a Java interface containing only one method. The Java API is full of SAM interfaces, such as java.lang.Runnable, java.awt.event.ActionListener, java.util.Comparator and java.util.concurrent.Callable. SAM interfaces have a special place in Java 8 because they can be implemented using Lambda expressions or Method references.

Using @FunctionalInterface forces a compile break when an additional, non-overriding abstract method is added to a SAM, which would break the use of Lambda implementations.

**Comment by ftomassetti** [comment]
Currently JavaParser supports Java 6 so we cannot use [FunctionalInterface](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html) because it was introduced in Java 8.

We should consider that for the future, I would mark this issue with the Label "Java8" for future references.

**Comment by ptitjes** [comment]
As I explained in https://github.com/javaparser/javaparser/pull/248#issuecomment-164832149, IMHO, this should be resolved for the two mentioned interfaces by configuring Sonar to ignore the two warnings.

**Comment by ftomassetti** [comment]
I think we could close his one

**Comment by matozoid** [comment]
Won't fix until JavaParser's core is Java 8.

**Comment by matozoid** [comment]
We can check this one again.

**Comment by DeepSnowNeeL** [comment]
With my modifications for #363 and related to  #372 , those 2 interfaces have more than 1 method now

**Comment by matozoid** [comment]
Here it goes again!
