### ISSUE TITLE
ResolvedReferenceTypeDeclaration.containerType() should return Optional<> rather than throwing an IllegalArgumentException

### ISSUE THREAD

**Issue by iTakeshi** [javaparser/javaparser#2427]
I encountered the error below on running code like:
```java
void foobar(final ResolvedReferenceTypeDeclaration decl) {
  System.out.println(decl.containerType());
}
```
```
Exception in thread "main" java.lang.IllegalArgumentException: com.github.javaparser.ast.CompilationUnit
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.toTypeDeclaration(JavaParserFactory.java:144)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeAdapter.lambda$containerType$0(JavaParserTypeAdapter.java:138)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeAdapter.containerType(JavaParserTypeAdapter.java:138)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.containerType(JavaParserClassDeclaration.java:400)
```

This occurs when the `decl` is the top-level declaration in the enclosing `CompilationUnit`.
According to [the implementation in the `JavaParserFactory`](https://github.com/javaparser/javaparser/blob/master/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFactory.java#L130-L146), it just throws an error on unexpected argument type.
However, trying to call `containerType()` on a `TypeDeclaration` under investigation is a common operation.
I suggest to return `Optional<ResolvedReferenceTypeDeclaration>` from this method.

What do you think?

**Comment by MysterAitch** [comment]
Fixing `Optional<ResolvedReferenceTypeDeclaration> containerType()` to always return an optional _(and avoiding an `IllegalArgumentException` bubbling out of a method that doesn`t take any parameters!)_ sounds like a good idea to me! :)

I keep flip-flopping on whether it would be better to edit the factory method _(versus editing the code that calls it by catching the error)_ -- seeing the code changes would help form a stronger opinion one way or another. Would you be able to share a pull request showing this?

https://github.com/javaparser/javaparser/blob/master/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeAdapter.java#L134-L140

**Comment by iTakeshi** [comment]
Thanks for your quick response @MysterAitch 

> whether it would be better to edit the factory method (versus editing the code that calls it by catching the error)

Yes, this is what I also considered about, and I couldn't decide on my own --- that's why I created this issue rather than a PR.
I'll try those ways to examine what happens with those changes.

**Comment by matozoid** [comment]
This is probably part of the larger idea to stop the solver from throwing exceptions when something is not found, and return a "ResolutionResult" object or so. But feel free to use the Optional :-)

**Comment by iTakeshi** [comment]
Thanks for your comment @matozoid,

Unfortunately, I got occupied with another task since last week and couldn't implement my idea yet. I'll try it as soon as I become available.

**Comment by jlerbsc** [comment]
This will be taken into account in version 3.25.5.
This is considered a bug because we are trying to get the type declaration from a CompilationUnit.
