### ISSUE TITLE
@Override annotation should be used on any method overriding

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#243]
Using the @Override annotation is useful for two reasons : 

It elicits a warning from the compiler if the annotated method doesn't actually override anything, as in the case of a misspelling. 

It improves the readability of the source code by making it obvious that methods are overridden.

**Comment by ftomassetti** [comment]
Agreed. How can we easily find all the places where @Override should be used?

**Comment by ptitjes** [comment]
With JavaParser :p

**Comment by matozoid** [comment]
+1 for @ptitjes :D

**Comment by matozoid** [comment]
But: the last five issues were suggested through private email, and I registered them here. They'll be picked up.

**Comment by ftomassetti** [comment]
It will be very nice to do so with JavaParser, however it would mean to find ancestors of classes and that would not be trivial. I would be in awe of whoever would do that and extremely thankful :)

**Comment by SmiddyPence** [comment]
According to IntelliJ that is all of them.  Any further offers?
