### ISSUE TITLE
Using ClassOrInterFaceDecalartion.AddField without setting a Modifier (aka Package-Private))

### ISSUE THREAD

**Issue by Mosarator** [javaparser/javaparser#2438]
**Question:**
How do i add a FieldDeclaration to an instance of ClassOrInterFaceDecalartion, without setting any visibility modifier?
**Context:** I am coding an UML to code parser

I tried the following Code:
```
Modifier mod = new Modifier();
[...]
switch (visibility)
{
  case '+':
    mod.setKeyword(Modifier.Keyword.PUBLIC);
    break;
  case '#':
    // PACKAGE visibility has no modifier
    break;
  case '~':
    mod.setKeyword(Modifier.Keyword.PROTECTED);
    break;
  case '-':
    mod.setKeyword(Modifier.Keyword.PRIVATE);
    break;
  default:
    // Package visibility
    break;
}
[...]
classInfo.addField(returnType, fieldName, mod);
```
But ``Modifier mod = new Modifier();`` sets the PUBLIC modifier.

I know that there exists the ``AccessSpecifier.PACKAGE_PRIVATE``, but i didn't find a way to use it when adding a field.

Is this not possible, or am i just doing it wrong?

**Comment by jlerbsc** [comment]
have you try to create a FieldDeclaration  with no arg constructor then set variables?

**Comment by MysterAitch** [comment]
Try not passing in only two parameters

I've not tested it, but I imagine something like this would work (n.b. the third parameter is a spread operator, in theory enabling you to pass in zero or more modifiers)


```java

Modifier keyword = null; 
switch (visibility)
{
  case '+':
    keyword = Modifier.Keyword.PUBLIC;
    break;
  case '#':
    // PACKAGE visibility has no modifier
    keyword = null;
    break;
  case '~':
    keyword = Modifier.Keyword.PROTECTED;
    break;
  case '-':
    keyword = Modifier.Keyword.PRIVATE;
    break;
  default:
    // Package visibility
    keyword = null;
    break;
}

if(keyword == null) {
    classInfo.addField(returnType, fieldName);
} else {
    classInfo.addField(returnType, fieldName, keyword);
}

```

**Comment by matozoid** [comment]
(Some background: the nodes in the AST have a lot of utility methods. It is a very educational to look at the source code to find out what they actually do. Here is `addField` for example: https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/nodeTypes/NodeWithMembers.java#L108-L115 - you can see that it adds a `member` of type `FieldDeclaration` that constains one `VariableDeclarator`, then sets the modifiers on the `FieldDeclaration`. Now you have the knowledge to create all kinds of variations :-) )

**Comment by Mosarator** [comment]
Thanks @matozoid , i searched at the wrong spot.

For anyone who is interested, how i did it:

```
VariableDeclarator variable = new VariableDeclarator(StaticJavaParser.parseType(type), name);
Keyword keyword = null;
if (visibility != null && visibility.isEmpty() == false) {
	switch (visibility) {
	case "+":
	    keyword = (Modifier.Keyword.PUBLIC);
		break;
	case "#":
		// PACKAGE visibility has no modifier
		break;
	case "~":
	    keyword = (Modifier.Keyword.PROTECTED);
		break;
	case "-":
	    keyword = (Modifier.Keyword.PRIVATE);
		break;
	default:
		// Package visibility
		break;
	}
} else {
	if (matcher.group(1) == null)
		throw new RegExException("Expected '+', '#', '~' or '+'");
}
FieldDeclaration field = new FieldDeclaration();
field.getVariables().add(variable);
if(keyword != null) {
    field.setModifiers(keyword);
}
classInfo.getMembers().add(field);
```

**Comment by matozoid** [comment]
Cool, it's solved then :-)
