### ISSUE TITLE
Does symbol solver need the source code to be correctly compiled?

### ISSUE THREAD

**Issue by penelope24** [javaparser/javaparser#2439]
I made two simple toy classes that one implements another, and tried to use symvol solver to solve them.
In a compiled project, symbol solver performs perfect. But when I put the classes in a compiled-failed project, it throws an UnsolvedSymbolException.
Is this true that symbol solver need source to be compiled?

**Comment by matozoid** [comment]
Hi! The symbol solver was not designed to work with source code that is not valid Java. If it works in some cases, it is by accident :-)

Is that the answer you are looking for?

**Comment by penelope24** [comment]
> Hi! The symbol solver was not designed to work with source code that is not valid Java. If it works in some cases, it is by accident :-)
> 
> Is that the answer you are looking for?

ok, does "valid java" means "compiled correct"? what if the source code is grammaly correct but hasn't been compiled yet?
let's say we want to use symbol solver to analyze the relationship between two java files, namely A.java and B.java in an open-source project,  the java file is grammaly-correct, however the project is not compiled yet.  
I found that if I analyze A.java and B.java alone, symbol solver works very well, however if I analyze them in the project, UnsolvedSymbolException is raised.
thx a lot!

**Comment by matozoid** [comment]
How do you
- analyze before compilation
- analyze after compilation
?

With a different TypeSolver?

**Comment by penelope24** [comment]
> How do you
> 
> * analyze before compilation
> * analyze after compilation
>   ?
> 
> With a different TypeSolver?

Hi, thx for your patience :-)
firstly I put the two classes alone in a empty project:
```
/project
    /A.java
    /B.java
```
the typesolver I choose is:
```java
Typesolver = new JavaParserTypeSolver(new File("project"))
```
since A.java and B.java are grammarly-correct, the project is esay to build, and symbol solver works fine.

secondly I tried to put A.java and B.java into a open source project - spring-session, the project is not built yet (so the IDE will show errors in source due to missing dependencies). note that spring-session is a multi-moidel project, I just choose one model and put the two java files in a certain package:
```
/spring-session
    /model1
        /package A
            A.java
            B.java
        /package B
    /model2
```
the typeSolver is still JavaParserTypeSolver but the source is the root of spring-session:
```java
Typesolver = new JavaParserTypeSolver(new File("spring-session"))
```
and that's the case I found UnsolvedSymbolException is raised.

it is curious to me cause what analyze is exactly the same (A.java and B.java), but putting them in different place cuase different outcomes.

**Comment by matozoid** [comment]
Okay, I'm not the expert, but I think that in case two, the typesolver should be pointed to the root of the module, not the root of the project. Can you give that a try?

(If you think this is a lot of work, you can look into https://github.com/javaparser/javaparser/blob/master/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/utils/SymbolSolverCollectionStrategy.java )

**Comment by penelope24** [comment]
> Okay, I'm not the expert, but I think that in case two, the typesolver should be pointed to the root of the module, not the root of the project. Can you give that a try?
> 
> (If you think this is a lot of work, you can look into https://github.com/javaparser/javaparser/blob/master/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/utils/SymbolSolverCollectionStrategy.java )

Hi, I followed your advice and change the typesolver pointed to root module, and it works!
thanks a lot for you advice!
