### ISSUE TITLE
JEP 305 / JEP 375: Pattern Matching for instanceof (Preview, and 2nd Preview)

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#2445]
https://bugs.openjdk.java.net/browse/JDK-8181287

- grammar change (in addition to the current `x instance Y` we should be able to say `x instance Y y`)
- validation that the second form cannot be used before Java 14.

**Comment by MysterAitch** [comment]
I keep nibbling at the edges of the java 14 support issues, but each time don't seem to get anywhere substantial. 

Got any tips? :)

**Comment by matozoid** [comment]
Look through the grammar where we define "instanceof", check what comes after it. Find what the construct `Y y` is. That should also be allowed there. Now the node type probably can't store it, so what would be a simple, understandable way to store both kinds of instanceof. Do the types share a super type maybe? Change the node field, run the generators, it probably fails horribly. Here is where git helps :-#

And check the JLS for the grammar changes, the names of these changes, etc. Prefer to use the naming used here to avoid confusion. Introducing new names may seem to make it easier for users, but in the end there is a big clump of complexity here, which is the Java language itself, and better not make it more complex to understand by inventing a second set of terminology.

Blah blah, why not make a stand alone tiny javacc project where you can experiment a bit?

Also: install the JavaCC plugin in intellij.

**Comment by matozoid** [comment]
The validation stuff is part of the whole set of post-parse semantic validators. You can examine how the whole language level stuff works - there is one grammar that parses all Java versions, and the validators check if non-language-level compliant stuff is being used.

**Comment by MysterAitch** [comment]
#2654 adds an optional name/identifier to the `InstanceOfExpr` grammar (and the relevant metamodels and generated bits etc).

If we were to stick to the spec there should, instead, be a `Pattern` node/token. I'll add that shortly, now that I've gotten my head around things a bit better :)

**Comment by MysterAitch** [comment]
Files updated manually:

- javaparser-core/src/main/java/com/github/javaparser/printer/ConcreteSyntaxModel.java
- javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java
- javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/DefaultVisitorAdapter.java

(plus others, these are just the last few... I'll update this to be more complete later..)

**Comment by MysterAitch** [comment]
I'm starting to think that resolution of the `Pattern` variables may need to be a more substantial change than the WIP within #2654 currently has.

This has come to mind as I'm reviewing the tests in #2654 and realised that I've muddled some of them by not taking into account the negation operator (examples included below that need to be integrated into better/more complete test cases).

To my knowledge, this is the first time that the evaluation of logical expressions affects the scope of variables (as opposed to the "normal" parent/child nesting relations). Please do share any better/alternative examples if you know of any!


```java
List<Object> s = new ArrayList<>();
if (obj instanceof String s && s.length() > 5) {}
//                             ^^^^^^^^^^
// instanceof evaluates to true, thus s is String
```

```java
List<Object> s = new ArrayList<>();
if (obj instanceof String s || s.length() > 5) {}
//                             ^^^^^^^^^^
// instanceof evaluates to false, thus s is List
// (note that if it were to be false, the expression would short-circuit, 
//   skipping the right-branch of the binary expression - this is why it's never true)
```

```java
List<Object> s = new ArrayList<>();
if (!(obj instanceof String s)) {
    // the instanceof evaluates to false, 
    // therefore s resolves here to List<Object>
    s.contains("");
} else {
    // the instanceof evaluates to false, 
    // therefore s resolves here to String
    s.contains("");
}
```


```java
List<Object> s = new ArrayList<>();
if( 
  true 
  && 
  ( 
    false
    ||
    obj instanceof String s
  ) 
) {
   // I *think* s should be a String here..?
}
```


```java
List<Object> s = new ArrayList<>();
if( 
  true 
  && 
  !(   /* note the negation here */
    false
    ||
    obj instanceof String s
  ) 
) {
   // I *think* s should be a List here..?
}
```


I suspect that some of this would be easier if our grammar matched the JLS grammar with instanceof being an operator / relational expression (i.e. maybe then we can determine which variables are exposed based on the relational expressions within it), but that's more of a fuzzy idea than a concrete target.

https://docs.oracle.com/javase/specs/jls/se14/html/jls-15.html#jls-15.20

JDK8:
```
RelationalExpression:
    ShiftExpression
    RelationalExpression < ShiftExpression
    RelationalExpression > ShiftExpression
    RelationalExpression <= ShiftExpression
    RelationalExpression >= ShiftExpression
    RelationalExpression instanceof ReferenceType 
```

_and in JDK14..._
https://bugs.openjdk.java.net/browse/JDK-8181287
```
RelationalExpression:
    ShiftExpression
    RelationalExpression < ShiftExpression
    RelationalExpression > ShiftExpression
    RelationalExpression <= ShiftExpression
    RelationalExpression >= ShiftExpression
    RelationalExpression instanceof ReferenceType
    RelationalExpression instanceof Pattern  /* NEW */

Pattern:  /* NEW */
    ReferenceType Identifier  /* NEW */
```


https://github.com/javaparser/javaparser/blob/8f25c40918feaf5f66af5fae5b23d271edefbdfc/javaparser-core/src/main/javacc/java.jj#L1590-L1606

**Comment by MysterAitch** [comment]
JDK 15 has this as a second preview: 
https://openjdk.java.net/jeps/375

~~I've not yet looked to see if there are any substantive differences between the two JEPs.~~
> This JEP proposes to re-preview the feature in JDK 15, with no changes relative to the preview in JDK 14, in order to gather additional feedback.

**Comment by MysterAitch** [comment]
**JDK14 - Preview:**
https://openjdk.java.net/jeps/305

**JDK15 - Second Preview**
https://openjdk.java.net/jeps/375

> History
> 
> Pattern matching for instanceof was proposed by JEP 305 in mid 2017, and targeted to JDK 14 in late 2019 as a preview language feature. This JEP proposes to re-preview the feature in JDK 15, with no changes relative to the preview in JDK 14, in order to gather additional feedback.

**JDK16 - Targeted for release:**
https://openjdk.java.net/jeps/394

> 
> **History**
> 
> Pattern matching for instanceof was proposed by JEP 305 and delivered in JDK 14 as a preview feature. It was re-proposed by JEP 375 and delivered in JDK 15 for a second round of preview.
> 
> This JEP proposes to finalize the feature in JDK 16, with the following refinements:
> 
> - Lift the restriction that pattern variables are implicitly final, to reduce asymmetries between local variables and pattern variables.
> 
> - Make it a compile-time error for a pattern instanceof expression to compare an expression of type S against a pattern of type T, where S is a subtype of T. (This instanceof expression will always succeed and is then pointless. The opposite case, where a pattern match will always fail, is already a compile-time error.)
> 
> Other refinements may be incorporated based on further feedback.

**Comment by MysterAitch** [comment]
I have stopped faffing around and actually merged PR #2654 now :laughing: 

- That PR implements the grammar. I believe this to be complete.
- I believe that PR handles most solving situations, but is not definitely complete when comparing it against the JEP.


An example of the incomplete behaviour is "flow scoping" - an example of this can be found within [JEP394](https://openjdk.java.net/jeps/394):

```java
public void onlyForStrings(Object o) throws MyException {
    if (!(o instanceof String s))
        throw new MyException();
    // s is in scope
    System.out.println(s);
    ...
}
```

I'm not even sure that this level of solving will ever be possible in javaparser, but it's not impossible.

There are other cases too where an additional tweak/fix will be needed -- there are various combinations of true/false/brackets/negations that can be determined at compile time to definitively be true or false. 

```java
if( "x" instanceof String s != (!((!!(!((!!!!(true)))))))) {
    System.out.println("output");
}
```

There is a quick attempt at `isDefinitivelyTrue(Expression)` within `BinaryExprContext`, but it certainly needs expanding to handle additional cases (and for it to be used correctly in the rest of the class).


I'll probably need to create some more test cases for deeply nested conditions too (though I think this is fine).

**Comment by MysterAitch** [comment]
I was worried about cases where the result of a condition is not known at compile time (e.g. the snippet that follows), but I **THINK** that this might be a non-issue thus not worth considering based on my (limited) experimentation with this particular example: 

```java
if( "x" instanceof String s == (new Random().nextBoolean())) { // Not determined until runtime
    System.out.println("output: " + s);
}
```

Note this quote from the JEP which suggests that this code snippet should not compile (emphasis mine):

> Rather than using a coarse approximation for the scope of pattern variables, pattern variables instead use the concept of flow scoping. A **pattern variable is only in scope where the compiler can deduce** that the pattern has definitely matched and the variable will have been assigned a value.

**Comment by mickroll** [comment]
Hmmm. `if (x instanceof String s) {` works, but `if (x instanceof final String s) {` leads to:
```
unable to parse source file: src\main\java\com\example\Example.java, [(line 57,col 23) Parse error. Found "final", expected one of  "@" "boolean" "byte" "char" "double" "enum" "exports" "float" "int" "long" "module" "open" "opens" "provides" "record" "requires" "short" "strictfp" "to" "transitive" "uses" "with" "yield" <IDENTIFIER>
Problem stacktrace :
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:13708)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13554)
  com.github.javaparser.GeneratedJavaParser.InstanceOfExpression(GeneratedJavaParser.java:3923)
```
But javac is fine with both.

**Comment by jlerbsc** [comment]
The current implementation of the grammar is based on the second preview of this specification which does not define TypePattern.
https://docs.oracle.com/javase/specs/jls/se16/html/jls-14.html#jls-14.30.1

**Comment by jlerbsc** [comment]
The current version of JP supports pattern matching for intanceof .
