### ISSUE TITLE
JEP 359: Records (Preview)

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#2446]
Add preview for records: https://bugs.openjdk.java.net/browse/JDK-8222777

... or let's not. I have a feeling this will change a lot in Java 15 because the syntax deviates from normal classes so much.

**Comment by MysterAitch** [comment]
JDK14 - preview:
https://openjdk.java.net/jeps/359

JDK15 - second preview:
https://openjdk.java.net/jeps/384

JDK 16 - Targeted for release:
https://openjdk.java.net/jeps/395

Looks like additional changes are planned:

> **History**
>
> Records were proposed by JEP 359 and delivered in JDK 14 as a preview feature.
>
> In response to feedback, the design was refined by JEP 384 and delivered in JDK 15 as a preview feature for a second time. The refinements for the second preview were as follows:
ere as follows:
> 
> - In the first preview, canonical constructors were required to be public. In the second preview, if the canonical constructor is implicitly declared then its access modifier is the same as the record class; if the canonical constructor is explicitly declared then its access modifier must provide at least as much access as the record class.
> 
> - The meaning of the `@Override` annotation was extended to include the case where the annotated method is an explicitly declared accessor method for a record component.
> 
> - To enforce the intended use of compact constructors, it became a compile-time error to assign to any of the instance fields in the constructor body.
> 
> - The ability to declare local record classes, local enum classes, and local interfaces was introduced.
> 
> This JEP proposes to finalize the feature in JDK 16, with the following refinement:
> 
> - Relax the longstanding restriction whereby an inner class cannot declare a member that is explicitly or implicitly static. This will become legal and, in particular, will allow an inner class to declare a member that is a record class.
> 
> Additional refinements may be incorporated based on further feedback.

**Comment by jlerbsc** [comment]
I'm closing this issue because the record resolution is under development and will be delivered in the next version.
