### ISSUE TITLE
Get method invocation with Javaparser 

### ISSUE THREAD

**Issue by vignesh0710** [javaparser/javaparser#2449]
Hi,

First of all thank you for the great library. I am wondering if there is way to get the method invocations. For example:

  `public static int PxtoDp(context context, int px){
    DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics();
   return (int) (px/density);
}`

I am looking to get the 2 invocations in this method.

   `1. getResources()
     2. getDisplayMetrics()
`

**Comment by edefazio** [comment]
Heres a decent example of "inspecting" whats in an AST
```java
import java.util.ArrayList;
import java.util.List;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;

import junit.framework.TestCase;

public class GetMethodInvocations extends TestCase {
  public void testMethodCallExpression() {
    MethodDeclaration md = StaticJavaParser.parseMethodDeclaration(
      "public static int PxtoDp(context context, int px){ DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics(); return (int) (px/density); }");
		
    //heres how you can "inspect" the types that make up the AST
    md.walk(n -> System.out.println(n.getClass().getCanonicalName() + " \"" + n + "\""));
		
    //
    List<MethodCallExpr> mces = new ArrayList<>();
    //now that we know we want to peel off MethodCallExprs, we can walk and intercept only those 
    md.walk(MethodCallExpr.class, mce-> mces.add(mce) );
    System.out.println( mces );
  }
}
```
Here's the output:
>com.github.javaparser.ast.Modifier "public "
com.github.javaparser.ast.Modifier "static "
com.github.javaparser.ast.expr.SimpleName "PxtoDp"
com.github.javaparser.ast.body.Parameter "context context"
com.github.javaparser.ast.type.ClassOrInterfaceType "context"
com.github.javaparser.ast.expr.SimpleName "context"
com.github.javaparser.ast.expr.SimpleName "context"
com.github.javaparser.ast.body.Parameter "int px"
com.github.javaparser.ast.type.PrimitiveType "int"
com.github.javaparser.ast.expr.SimpleName "px"
com.github.javaparser.ast.type.PrimitiveType "int"
com.github.javaparser.ast.stmt.BlockStmt "{
    DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics();
    return (int) (px / density);
}"
com.github.javaparser.ast.stmt.ExpressionStmt "DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics();"
com.github.javaparser.ast.expr.VariableDeclarationExpr "DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics()"
com.github.javaparser.ast.body.VariableDeclarator "displayMetrics = context.getResources().getDisplayMetrics()"
com.github.javaparser.ast.type.ClassOrInterfaceType "DisplayMetrics"
com.github.javaparser.ast.expr.SimpleName "DisplayMetrics"
com.github.javaparser.ast.expr.SimpleName "displayMetrics"
com.github.javaparser.ast.expr.MethodCallExpr "context.getResources().getDisplayMetrics()"
com.github.javaparser.ast.expr.MethodCallExpr "context.getResources()"
com.github.javaparser.ast.expr.NameExpr "context"
com.github.javaparser.ast.expr.SimpleName "context"
com.github.javaparser.ast.expr.SimpleName "getResources"
com.github.javaparser.ast.expr.SimpleName "getDisplayMetrics"
com.github.javaparser.ast.stmt.ReturnStmt "return (int) (px / density);"
com.github.javaparser.ast.expr.CastExpr "(int) (px / density)"
com.github.javaparser.ast.type.PrimitiveType "int"
com.github.javaparser.ast.expr.EnclosedExpr "(px / density)"
com.github.javaparser.ast.expr.BinaryExpr "px / density"
com.github.javaparser.ast.expr.NameExpr "px"
com.github.javaparser.ast.expr.SimpleName "px"
com.github.javaparser.ast.expr.NameExpr "density"
com.github.javaparser.ast.expr.SimpleName "density"

>[context.getResources().getDisplayMetrics(), context.getResources()]

**Comment by matozoid** [comment]
Here are various ways of inspecting the AST: https://javaparser.org/inspecting-an-ast/

**Comment by vignesh0710** [comment]
The example was great and its working fine! I modified the snippet and used the book from the authors to extract - Method Names and Comments also. 


```
package com.example.helloworld;
 import com.github.javaparser.ast.CompilationUnit;
 import com.github.javaparser.ast.body.*;
import com.github.javaparser.*;


public class HelloWorld {
    public static void main(String [] args){
        // Parse the code you want to inspect:

        MethodDeclaration md = StaticJavaParser.parseMethodDeclaration(
                "/** * converts pixel to dp **/ public static int PxtoDp(context context, int px){ DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics(); return (int) (px/density); }");

        //heres how you can "inspect" the types that make up the AST
        //md.walk(n -> System.out.println(n.getClass().getCanonicalName() + " \"" + n + "\""));
       System.out.println(md.getNameAsString());
       System.out.println(md.getAllContainedComments());
    }
}

```

But if I try the same code snippet above with a following input string, it fails in 2 cases:

1. code snippets within the function
2. Comments starting with "//" within the function


```
MethodDeclaration md = StaticJavaParser.parseMethodDeclaration(
                "// Check if no view has focus: View view = this.getCurrentFocus();if (view != null) { InputMethodManager imm = (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);imm.hideSoftInputFromWindow(view.getWindowToken(), 0);}");
```


I get the following error:

```

Exception in thread "main" com.github.javaparser.ParseProblemException: Encountered unexpected token:<EOF>

Was expecting one of:

    "<"
    "boolean"
    "byte"
    "char"
    "double"
    "enum"
    "exports"
    "float"
    "int"
    "long"
    "module"
    "open"
    "opens"
    "provides"
    "requires"
    "short"
    "strictfp"
    "to"
    "transitive"
    "uses"
    "void"
    "with"
    "yield"
    <IDENTIFIER>

Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10667)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10526)
  com.github.javaparser.GeneratedJavaParser.ResultType(GeneratedJavaParser.java:2086)
  com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1217)
  com.github.javaparser.GeneratedJavaParser.MethodDeclarationParseStart(GeneratedJavaParser.java:5939)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parseMethodDeclaration(JavaParser.java:539)
  com.github.javaparser.StaticJavaParser.parseMethodDeclaration(StaticJavaParser.java:480)
  com.example.helloworld.HelloWorld.main(HelloWorld.java:18)

	at com.github.javaparser.StaticJavaParser.handleResult(StaticJavaParser.java:260)
	at com.github.javaparser.StaticJavaParser.parseMethodDeclaration(StaticJavaParser.java:480)
	at com.example.helloworld.HelloWorld.main(HelloWorld.java:18)


Process finished with exit code 1

```

Should I use a different method when I am trying to parse a snippet within a method? Thanks in advance.

**Comment by edefazio** [comment]
Yeah you are using 
`StaticJavaParser.parseMethodDeclaration(...)`
which parses **methods**  _not_ snippets

also... if you pass in a String with a leading "//" with no carriage returns
it's basically thinking you are parsing a comment (not code)...it doenst know where the comment ends and the code begins.

its easier to just "make" the snippet a Block (adding a prefix "{" and suffix "}")
then call StaticJavaParser.parseBlock(...) i.e.:
```java
String snippet = "...";
String block = "{"+snippet+"}";
BlockStmt bs = StaticJavaParser.parseBlock(block);
```

**Comment by vignesh0710** [comment]
Thank you! It worked! I just have one final question, is there any inbuilt methods like `.getName()` to extract the following inside a method or a block:

  ```
1. Enums
2. String Literals
```
or Should I write my own custom logic after parsing the code?

**Comment by edefazio** [comment]
I think all you need is on the API, you should be good with a little experience using JavaParser
:)

**Comment by vignesh0710** [comment]
Thank you!
