### ISSUE TITLE
parseBodyDeclaration  annotation use

### ISSUE THREAD

**Issue by linkai0001** [javaparser/javaparser#2454]
```
parseBodyDeclaration("@Service(age=3)").asAnnotationDeclaration()

The interpretation of the annotation does not seem to be supported, and an error is reported after execution

```
**The error message is as follows：**
Encountered unexpected token:<EOF>
    at line 1, column 15.

Was expecting one of:

    "<"
    "@"
    "boolean"
    "byte"
    "char"
    "class"
    "double"
    "enum"
    "exports"
    "float"
    "int"
    "interface"
    "long"
    "module"
    "open"
    "opens"
    "provides"
    "requires"
    "short"
    "strictfp"
    "to"
    "transitive"
    "uses"
    "void"
    "with"
    "yield"
    <IDENTIFIER>

Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10667)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10526)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:964)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclarationParseStart(GeneratedJavaParser.java:5834)
  com.github.javaparser.ParseStart$$Lambda$58/502800944.parse(Unknown Source)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parseBodyDeclaration(JavaParser.java:391)
  com.github.javaparser.StaticJavaParser.parseBodyDeclaration(StaticJavaParser.java:320)
  com.noma.test.HanlerJavaFile.opertionJavaFile(HanlerJavaFile.java:59)
  com.noma.test.HanlerJavaFile.main(HanlerJavaFile.java:109)

**Comment by matozoid** [comment]
Hi! You're mixing up annotation declarations and annotation expressions. You are supplying an annotation expression to `parseBodyDeclaration` - I bet you want to use `parseAnnotation` instead.

**Comment by linkai0001** [comment]
Thanks for the guidance, using parseAnnotation has solved my scenario problem

**Comment by matozoid** [comment]
Good luck!
