### ISSUE TITLE
how can i judge a method is a generic method using java parser

### ISSUE THREAD

**Issue by nough1** [javaparser/javaparser#2466]
how can i judge a method is a generic method using java parser

**Comment by edefazio** [comment]
check if the `MethodDeclaration` has a `TypeParameter`

i.e.
```java
MethodDeclaration md = StaticJavaParser.parseMethodDeclaration(
				"<T>void listThings( List<T> ts){ return null;}");
boolean hasTypeParameters = md.getTypeParameters().isNonEmpty();
boolean isGeneric = hasTypeParameters;
```

**Comment by nough1** [comment]
> check if the `MethodDeclaration` has a `TypeParameter`
> 
> i.e.
> 
> ```java
> MethodDeclaration md = StaticJavaParser.parseMethodDeclaration(
> 				"<T>void listThings( List<T> ts){ return null;}");
> boolean hasTypeParameters = md.getTypeParameters().isNonEmpty();
> boolean isGeneric = hasTypeParameters;
> ```

thanks , it works
