### ISSUE TITLE
How can I replace {@inheritdoc} with inherited description?

### ISSUE THREAD

**Issue by attenton** [javaparser/javaparser#2467]
I'm using `javaparser` to get the description of parameters and methods via parsing the javadoc from jdk source code. However sometimes there exists `{@inheritdoc}` in the description, and I want to replace `{@inheritdoc}` with desciption which inherits from other methods. Though method `getElement` can fetch `javadoc.description` and `{@inheritdoc}`,  I cannot fetch the inherited description. So is there any api or approach to find the inherited method and its description? Thanks a lot.

**Comment by matozoid** [comment]
Hi! That's quite some work: you have to set up the symbol solver (see book,) resolve the parent class, look for the method that is being overridden (comparing the method signature), then ask for its Javadoc. If it has none, repeat the process with the class it extends, etc.

That's the general idea. If you have more specific questions, feel free to ask.

**Comment by attenton** [comment]
Yeah, I have searched the workflow of replacing `{@inheritDoc}` in the `Java API Documentation Generator`, and implemented the workflow as you mentioned. However my implementation is not so good. 
Firstly I traverse all the files and fetch all classOrInterfaceDeclaration and store the classes they implementand extend. Then I traverse all the files and fetch all MethodDeclaration and store the classes they belong and their description. As you see, I get the methods belonging to ClassOrInterfaceDeclaration in such a complex way. In my opinion, all the methods are subNodes of the AST, so all the methods will be fetched including the methods belonging to innerClass if I use `getChildNodes`. I want to know can the method `getChildNodes` fetch all the methods which belong to the class exclueding innerClasses? Or some methods else can do this? 
Thanks.

**Comment by matozoid** [comment]
It would be good to read the book - not only will you find the answer, you will also find how to answer other questions - https://javaparser.org/getting-started/

You can do this with a visitor, and calling `super` or not, depending on whether you want to process the children. Avoid `getChildNodes` where possible.

**Comment by attenton** [comment]
okay, Thanks, and wish you a Happy New Year in advance.
