### ISSUE TITLE
tryToParse runs very slowly and consumes a lot of memory

### ISSUE THREAD

**Issue by qingdujun** [javaparser/javaparser#2469]
I want to get a comprehensive abstract syntax tree(because MethodCallExpr needs to be parsed, `methodCallExpr.resolve().getQualifiedSignature()`).

I used the following method, but it runs very slowly and consumes a lot of memory(about 32G).
```
ParseResult<CompilationUnit> pr = sourceRoot.tryToParse(startPackage, fileName);
```

Are there other ways to increase speed and consume less memory?

**Comment by qingdujun** [comment]
I just want to build an SDG for a project of about 10,000 files. 

I spent 5 hours and have analyzed 420 files.

**Comment by matozoid** [comment]
Hi! Yes, this happens more often, here is the biggest issue about it: #1391 - if you can help, that would be great.

There are also quick wins by changing the parser configuration. Turn off everything you don't need (because everything is turned on by default!)

**Comment by qingdujun** [comment]
@matozoid I set the package name and it's fine now. (Although it is still slow, the memory problem is gone)

**Comment by matozoid** [comment]
Okay, good!
