### ISSUE TITLE
A block comment containing '/*' is not parsed correctly

### ISSUE THREAD

**Issue by msayagh** [javaparser/javaparser#247]
Hi,
Parsing this file is not working. The parser duplicates some methods:
[BeanConfig.txt](https://github.com/javaparser/javaparser/files/62645/BeanConfig.txt)

**Comment by ftomassetti** [comment]
At a first look it seems fine to me. Can you give more details please? Which methods appear to be duplicated?

I tried parsing & dumping the given file and I cannot see any wrong. Perhaps I am missing something, can you help us?

**Comment by msayagh** [comment]
Yes, sure. 

The duplicate methods are : getComponent, getClassType. And there is something looking like this:

```
/**
```
- Sets the component implementation class.
  _/
  public void setClass(Class<?> cl) {
      _cl = cl;
      // env/1072
      Class<?> type = getBeanConfigClass();
      if (type != null && !type.isAssignableFrom(cl))
          throw new  ConfigException(L.l("'{0}' is not a valid instance of '{1}'", cl.getName(), type.getName()));
  }
  --->>>> missed method declaration and duplicate code
  /_
  if (_name == null)
    _name = Introspector.decapitalize(cl.getSimpleName());
    /*/
  
  Class<?> type = getBeanConfigClass();
  
  if (type != null && ! type.isAssignableFrom(cl))
    throw new ConfigException(L.l("'{0}' is not a valid instance of '{1}'",
                                  cl.getName(), type.getName()));
  }

By the way, I'm using this version:

<dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-core</artifactId>
            <version>2.1.0</version>
        </dependency>

**Comment by msayagh** [comment]
Hi,
Any updates on this issue ?

**Comment by ftomassetti** [comment]
not yet sorry

**Comment by ftomassetti** [comment]
The problem is present also stripping down the file to:

```
public class BeanConfig {

  public void setClass(Class<?> cl)
  {
    _cl = cl;

    /*
    if (_name == null)
      _name = Introspector.decapitalize(cl.getSimpleName());
      /*/
  }

  public Class<?> getClassType() { }

  public Bean<?> getComponent() { }

  /**
   * Adds a component binding.
   */
  public void addBinding(Annotation binding) { }

}
```

It seems to be a problem in the DumpVisitor and it seems related somehow to comments (deleting them it disappears.

**Comment by ftomassetti** [comment]
Changing:

```
/*
    if (_name == null)
      _name = Introspector.decapitalize(cl.getSimpleName());
      /*/
```

To:

```
/*
    if (_name == null)
      _name = Introspector.decapitalize(cl.getSimpleName());
      */
```

The problem disappears

**Comment by ftomassetti** [comment]
PR sent (#257)

The issue is that this is invalid:

```
/*/
```

But this is valid:

```
/*      /*/
```

A slash followed by an asterisk can be part of a block comment but a slash, an asterisk and a slash are not a valid block comment.
