### ISSUE TITLE
Lexical error

### ISSUE THREAD

**Issue by tronicek** [javaparser/javaparser#2478]
When parsing a Java source code, the parser reports an error as follows:

Lexical error at line 71, column 21.  Encountered: "\u017d" (381) ...

Preprocessing of Unicode escapes does not help. The file is attached.
[649201.java.txt](https://github.com/javaparser/javaparser/files/4017437/649201.java.txt)

**Comment by matozoid** [comment]
Oh, I thought I had answered this - sorry!

```java
/**
 * ƒ?ƒOƒtƒ@ƒCƒ‹‚ÌƒAƒbƒvƒ??[ƒh‚ÉŠÖ‚·‚é?ˆ—?‚ð?s‚¤
 * @author Hiroshi Yoshida
 */
```

Is this how it is supposed to look? My IDE (Intellij Idea) has several errors because of encoding problems.

**Comment by tronicek** [comment]
Thanks, but I have no idea how it is supposed to look. This file is from BigCloneBench:

https://github.com/clonebench/BigCloneBench

I use it just to evaluate my research project.

**Comment by matozoid** [comment]
This is the particular sequence that gives trouble:
```java
public class Test {
    String x = "\Ž";
}
```
`\` is the start of an escape sequence, like `\n` or `\t`. `\Ž` is not a valid one, so JavaParser correctly fails to parse it.

You have been given an invalid Java source file.

**Comment by tronicek** [comment]
I investigated this further and the file can be parsed if encoding Shift_JIS (Shift Japanese Industrial Standards) is used. The original file is attached if someone is interested (the previous one was after conversion to UTF-8). Thanks.

[649201.java.txt](https://github.com/javaparser/javaparser/files/4100079/649201.java.txt)
