### ISSUE TITLE
How can I get declaration node from ResolvedXXX?

### ISSUE THREAD

**Issue by chenzhegodspeed** [javaparser/javaparser#2479]
For example. If I get a FieldAccessExpr fae, how can I get the physical declaration node of fae? I can only get ResolvedValueDeclaration using resolve(). I need to find the declaration node of any AST node(if possible). I think it is called **Binding** in **JDT**. I am not sure wrappedNode is my answer or not.

**Comment by jlerbsc** [comment]
In this case (get the field declaration node from FieldAccessExpr ),you can access the declaration from 

    ResolvedValueDeclaration rvd = fae.resolve();
    JavaParserFieldDeclaration jfd = (JavaParserFieldDeclaration)rvd.asField();
    FieldDeclaration fd = jfd.getWrappedNode();

**Comment by chenzhegodspeed** [comment]
@jlerbsc  Well. I got it.
