### ISSUE TITLE
CompilationUnit.getComments does not return comment before package statement

### ISSUE THREAD

**Issue by jmflorezff** [javaparser/javaparser#2480]
**Steps to reproduce:**
```java
CompilationUnit u = StaticJavaParser.parse("/*Comment*/ package a; class A {}");
System.out.println(u.getComments());
```

**Expected result:**
A singleton list containing the comment that reads `/*Comment*/`

**Observed result:**
An empty list

I can get the comment with `u.getComment()`. I don't know if this is intended, but I think it's kind of ugly to have to call both `getComment` and `getComments` if I want to get ALL the comments in the compilation unit.

**Comment by matozoid** [comment]
Thanks, that's weird.

**Comment by edefazio** [comment]
I looked into this a bit, and:
(What I _thought_ was going on was that the comment was going to be attributed to the package
_... but thats not true_)

it is a comment associated directly with the `CompilationUnit` and you would think a method named
`getComments()` would include the comment on the `CompilationUnit` itself considering there is a `getContainedComments()` method (which is the union of attributable comments and "orphan comments" BELOW the `CompilationUnit`) 

...so this definately seems like a bug: (code in CompilationUnit:
```java
    public List<Comment> getComments() {
        return this.getAllContainedComments();
    }
```
should be something like:
```java
    public List<Comment> getComments() {
        List<Comment> cs = this.getAllContainedComments();
        if(this.getComment().isPresent()){
            cs.add(this.getComment().get());
        }
        return cs;
    }
```
NOTE: I tested manually creating a comment on the `PackageDeclaration` of the `CompilationUnit` and that DOES in fact show up if we call `getComments()` so (FWIW) I think the above fix should work
without any additions

**Comment by matozoid** [comment]
True, and thinking about that: `getComments` is a pretty generic name, and could be renamed to `getAllComments` or so. Besides, it is redundant because `ParseResult` has a `CommentsCollection` that will get you all the comments anyway - but JP likes redundancy so that is okay.

**Comment by matozoid** [comment]
@Mathiponds  - are you interested in deprecating `getComments` and implementing `getAllComments` as @edefazio explained?

**Comment by Mathiponds** [comment]
Yes I can do that

**Comment by Mathiponds** [comment]
I'm not sure if I should only let one line with the `@deprecated` in the JavaDoc of `getComments` or I should keep the previous 10 lines of JavaDoc and add the `@deprecated` ?

**Comment by matozoid** [comment]
@Mathiponds - what you prefer.
For deprecations:
- make sure to mention why it was deprecated, and what to use instead.
- use both @deprecated in Javadoc and the @Deprecated annotation.
