### ISSUE TITLE
SymbolSolver choosing wrong method after resolving

### ISSUE THREAD

**Issue by gpr-indevelopment** [javaparser/javaparser#2489]
Suppose I have three classes: ComponentBase, ObjectContextDecorator and ObjectContext.

```
public class ComponentBase extends ObjectContextDecorator {
}
```

```
public class ObjectContextDecorator extends ObjectContext {

    public void set(String objectTypePath, String characteristicName, Object value) {
        //...
    }
}
```

```
public class ObjectContext {
    public void set(String characteristicName, Object value, boolean forced) {
       //...
    }
}
```

Then, I have the following piece of code. The "set" method called below needs to be resolved by the SymbolSolver:

```
ComponentBase otm4e = _this.getParent().getParent();
otm4e.set(""OTM4E_EFFLEVEL"", ""IE1 / STD"", true);
```

Then, the resolve method points out that the "set" method called belongs to ObjectContextDecorator. In fact, in this situation, it does belong to ObjectContext (that is what the programmer intended to write). Is there any way to change priority to the upper levels of the hierarchy? It seems to me there is a reason why the resolver gave preference to ObjectContextDecorator, even when ObjectContext also has a method with a signature that matches the method called.

**Comment by gpr-indevelopment** [comment]
One crucial piece of information:

I have brought the discussion to a [SO](https://stackoverflow.com/questions/59862051/overload-resolution-which-method-is-called) question.

It seems that the compiler uses the following criteria to decide which code to execute: It gives preference to methods that can execute without boxing/unboxing of any parameter.

In our case, ObjectContext's set can execute without any boxing to the arguments, since `String` inherits from `Object`, and `boolean` needs to be boxed to `Boolean` in order to inherit from `Object`.

So, the conclusion is that the SymbolSolver should resolve that method as ObjectContext.set, not ObjectContextDecorator.set

**Comment by matozoid** [comment]
Alright, upgraded to a bug report :-)
