### ISSUE TITLE
JavaParserTypeSolver won't support interfaces?

### ISSUE THREAD

**Issue by voxelbustersold** [javaparser/javaparser#2496]
https://github.com/javaparser/javaparser/blob/5406b759b22bec569cf967e4d96388a394ce19e9/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typesolvers/JavaParserTypeSolver.java#L181

**Comment by matozoid** [comment]
That would probably have been noticed before. It would be good to figure out in which situation this TODO is relevant though!

**Comment by voxelbustersold** [comment]
Any other library which can handle interfaces too?

**Comment by MysterAitch** [comment]
I've not been able to produce a failing test case for this so far, and I note that the comments were added in 2015 (when the contents of the file were first created!), so my strong suspicion is that the comments are outdated from a time before it was implemented.

I'll tidy up a few things and push the test cases shortly.

Cheers for highlighting this @voxelbusters ! :)
