### ISSUE TITLE
Using javaparser for refactoring

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#25]
To do that all the comments should be preserved (see #2 ), at least. Possibly also the layout should be kept as-is.

Any thoughts about that? I would like to take a look at that and I would appreciate suggestions, help, advices, etc.

**Comment by rpau** [comment]
Hi,

walkmod (an open source project to apply code conventions - http://www.walkmod.com) uses an old version of the source code of this project. walkmod contains the issue #2 solved. You can get the source code from https://bitbucket.org/rpau/walkmod

See the differences between the methods called "addComments" of the java grammar files. It will help you a lot.

To apply a powerful refactorings in terms of code migration, you need to infer the types of any symbol (variable, parameter, methodcall, ..) to check if it is a valid element to change. To get it, you need to implement:

1) A symbol table to save and look up symbols of any scope (class, method..)
2) A type engine to infer the type of expressions like "x.y.w". To get the type of expressions you could use reflection mechanisms. However, notice that you need to load the classpath of the input source code in a separate classloader.

One year ago, I started to create a refactoring utility as a walkmod plugin to execute it as a command line tool, but if you prefer to add this feature in javaparser I can help you too :)

**Comment by ftomassetti** [comment]
I going to look into walkmod. In the last half an hour I coded an (apparently working) prototype of a solution. Basic I parse separately all the comments (in a separate, simple, manually coded parer) and I get a list of all comments present in a source file. Then I take the CompilationUnit obtained from the JavaParser and I look which comments are there and which are missing. The missing ones are the one "floating around", which can not be associated with a statement, a class or whatever node. They could be for example inside statements or at the end of methods:

int /_comment_/ a = /\* other comment */ 2;

void foo(){/_comment associated with next statement_/ foo(); /\* floating comment*/ }

I call them "orphan comments" and I put them in the smallest AST node which contain them.

Now let's look into walkmod and see what kind of apprach it has.

**Comment by ftomassetti** [comment]
@rpau about this issue, the implementation of the comments parsing is done in the javacc file, right? I am not familiar with this parser generator. Does it add all comments to the node being currently build? Does it keep the distinction between "properly positionated comments" (the ones that javaparser parses now, i.e., the ones put before complete statements or nodes of any kind) and the "floating comments" (the ones not currently parsed)?

About walkmod I will drop you a few lines. Maybe I can use it for a project.

**Comment by rpau** [comment]
walkmod adds all comments (the ones parsed by javaparser and the missing ones, which are accumulated as a linked list in the specialToken field). It is performed as follows:

 private void addComments(Token token, Token special){

```
    if(special.specialToken != null){
            addComments(token, special.specialToken);
    }
    //the rest of the code
```

}
I have been used walkmod in my company and all comments have been conserved. Also, the DumpVisitor component of Javaparser should be modified.

**Comment by ftomassetti** [comment]
Yes, all comments are parsed but are they all attributed to the CompilationUnit?
In your codebase Node has not anymore a Comment while CompilationUnit holds a List of Comment.
Am I right?

**Comment by rpau** [comment]
Yes, all comments are in the compilation unit and  the DumpVisitor decides where write (aprox) them.

**Comment by ftomassetti** [comment]
Ok, thank you. Maybe it would be nice to have both approaches: the possibility to get all the comments in a given element and its sub elements (for example all the elements in a compilationUnit, in a class and so on) and also the association between a comment and the thing commented. These association could be derived after the parsing.

**Comment by rpau** [comment]
Ok, thank you. We'll get it into account :) and we will add as an improvement.

**Comment by matozoid** [comment]
Is this solved with 1.0.11?

**Comment by ftomassetti** [comment]
I did not look anymore into that but when I committed all of my (few) tests were passing https://github.com/matozoid/javaparser/commit/ce0d8c4064cec29c65315a718465d568fa125ad9

If there is any problem with that code I am willing to help.

**Comment by matozoid** [comment]
Just doing some book keeping. I'll add this to 1.0.11 as "closed." Open another issue if this is a mistake :)
