### ISSUE TITLE
Appveyor / maven 3.2.5?

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2501]
The appveyor script installs maven v3.2.5 (released in 2014)

I'm not aware of any particular reason/need to upgrade, but 2014 seems to be extremely old!

_(I just noticed that this is the last version that has a minimum java 6, and the next [version 3.3.1 has a minimum of java version 7](https://maven.apache.org/docs/history.html) --- is this the rationale for not updating?)_

https://github.com/javaparser/javaparser/blob/d1ee0363f4f1e0e93c7d34510f48194a899405ce/appveyor.yml#L5-L15

**Comment by matozoid** [comment]
The version requirements in short:
- the JP jars must be usable for people running Java 8
- keep everything as recent as possible

So there is some maintenance to be done here. In theory all the test code could be Java 13 already, but the setup for this will take some investigation.
