### ISSUE TITLE
`EnclosedExpr` -- inner may be null?

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2503]
Within `EnclosedExpr`, `removeInner()` calls `setInner(null)`. Additionally, the javadoc for `setInner(Expression value)` indicates that the value may be null.

The first line of `setInner` is an assertion that `value` is not null. 

<s>I suspect this might be as simple as removing the assertion, but there are other wide-impacting side-effects of doing so such as allowing `getInner()` to return null (as opposed to being optional). </s>

_Edit: just spotted #1010 and #1018 which indicates that the intention is inner must not be null._

If inner **_is_** required (i.e. must not be null), then different changes are needed -- minimum edit the documentation and to do _something_ to `removeInner` (not sure what? maybe throw an error?) and perhaps the constructors?

Either way, it seems some additional tests would be helpful here too!

Thoughts? :) 

https://github.com/javaparser/javaparser/blob/d1ee0363f4f1e0e93c7d34510f48194a899405ce/javaparser-core/src/main/java/com/github/javaparser/ast/expr/EnclosedExpr.java#L83-L101

https://github.com/javaparser/javaparser/blob/d1ee0363f4f1e0e93c7d34510f48194a899405ce/javaparser-core/src/main/java/com/github/javaparser/ast/expr/EnclosedExpr.java#L111-L114

**Comment by MysterAitch** [comment]
Just spotted similar in `TryStmt`: 

https://github.com/javaparser/javaparser/blob/d1ee0363f4f1e0e93c7d34510f48194a899405ce/javaparser-core/src/main/java/com/github/javaparser/ast/stmt/TryStmt.java#L249-L254

https://github.com/javaparser/javaparser/blob/d1ee0363f4f1e0e93c7d34510f48194a899405ce/javaparser-core/src/main/java/com/github/javaparser/ast/stmt/TryStmt.java#L190-L204

**Comment by matozoid** [comment]
- looks like the lambda part is not using an empty enclosedexpr anymore. I can't find it in the code, and it would have caused major issues on the issue tracker if they were.
- it's not marked `@OptionalProperty`, so it is required. The null checks should be there.
- the remove method is probably a left over. Maybe try removing it and running the code generators again?
