### ISSUE TITLE
The question about the parsing of the method invocation chain

### ISSUE THREAD

**Issue by ilsid** [javaparser/javaparser#251]
Hi Folks,

Thank you for your parser :)

I have the question regarding the parsing of the method invocation chain. Not sure whether it is a bug or an improper usage from my side.
If I have the following statement within some method
<code>a().b().c();</code>
how I can intercept the call of methods a() and b() ?
I'm overriding 
<code>VoidVisitorAdapter.visit(MethodCallExpr, A)</code>
But in this case, I can only intercept the invocation of c() method.
The methods a() and b() are ignored.

Version: 2.2.2
Please let me know, if more details are needed.

Thanks,
Illia

**Comment by ptitjes** [comment]
Hi,

A method invocation expression has four components:
- its target
- the passed type arguments
- the called method name
- the passed arguments

So the expression `a().b().c()` is a method invocation expression with target the expression `a().b()`, method name `c`, no type arguments and no arguments.

Thus you must always recursively visit the sub-expressions (here the important one is the target expression of the method invocation) by using either `subExpr.accept(this, arg)` or `super.visit(callExpr, arg)`.

Does this fix your problem ?

**Comment by ilsid** [comment]
Yes, both super.visit() and subExpr.accept() fix the issue.
Thanks a lot!

**Comment by ptitjes** [comment]
Welcome!
