### ISSUE TITLE
Comments preceding package-decl lead to IllegalStateException when LexicalPreservationEnabled is true

### ISSUE THREAD

**Issue by zaph-b33blebrox** [javaparser/javaparser#2513]
With the code below I am running into an IllegalStateException at LexicalPreservingPrinter, line 130.
The problem is reproducible with a ParserConfiguration having *setLexicalPreservationEnabled(true)* AND there parsed code has a comment preceding the java *package* declaration.

I am looking at version 3.15.11 of JavaParser code. Maybe I missed some point, but the longer I keep investigating, the more this appears to be a bug in the *LexicalPreservingPrinter* class (LexicalPreservingPrinter.java, lines 129-131):

    129         if (!observedNode.getParentNode().isPresent()) {
    130             throw new IllegalStateException();
    131         }

In Line 129 the observedNode is the CompilationUnit, which in my understanding never has a parent node. Hence the IllegalStateException is being thrown.

The code to be parsed is quite simple:

    // Copyright (C) 2002-2020 ACME Enterprises. All rights reserved
    package javaparser.bugreport.democode;
    public interface TypeWithACommentBeforeThePackageDeclaration {
    }

Thanks a lot in advance for investigating and providing a fix or for pointing me to a work-around!

The following is a minimal self contained example:

    package javaparser.bugreport;
    
    import java.util.Optional;
    
    import com.github.javaparser.JavaParser;
    import com.github.javaparser.ParserConfiguration;
    import com.github.javaparser.ast.CompilationUnit;
    
    public class LeadingCommentsProblemDemo {
    
    	public static void main(String[] args) {
    		StringBuilder code = new StringBuilder();
    		code.append("// Copyright (C) 2002-2020 ACME Enterprises. All rights reserved.").append('\n');
    		code.append("package javaparser.bugreport.democode;").append('\n');
    		code.append("public interface TypeWithACommentBeforeThePackageDeclaration {}");
    		
    		ParserConfiguration parserConfiguration = new ParserConfiguration();
    		parserConfiguration.setLexicalPreservationEnabled(true);
    		
    		JavaParser javaParser = new JavaParser(parserConfiguration);
    
    		System.out.println("parsing code...");
    		System.out.println("-----------------------");
    		System.out.println(code);
    		System.out.println("-----------------------");
    
    		Optional<CompilationUnit> result = javaParser.parse(code.toString()).getResult();
    		if (!result.isPresent()) {
    			// reason is IllegalArgumentException at LexicalPreservingPrinter, line 130
    			System.err.println("Failed to parse code");
    		} else {
    			System.out.println("Successfully parsed code");
    		}
    	}
    }

**Comment by matozoid** [comment]
Thanks for reporting this!

**Comment by MysterAitch** [comment]
Perhaps this explains #1301 ?

**Comment by zaph-b33blebrox** [comment]
Hey guys,

doubting that this is a real and proper solution, but at least for my use case I found a fix / work-around. I have patched method LexicalPreservingPrinter#Observer#concretePropertyChange(...) starting at line 129:

current code is:

    128 if (property == ObservableProperty.COMMENT) {
    129     if (!observedNode.getParentNode().isPresent()) {
    130         throw new IllegalStateException();
    131     }
    132
    133     NodeText nodeText = getOrCreateNodeText(observedNode.getParentNode().get());
    134
    135     if (oldValue == null) {
    136         // Find the position of the comment node and put in front of it the [...]
    137         int index = nodeText.findChild(observedNode);


changed this to:

    128 if (property == ObservableProperty.COMMENT) {
    129     NodeText nodeText = null;
    130     Optional<Node> optional = observedNode.getParentNode();
    131     if (!optional.isPresent()) {
    132         // i.e. comments preceding the package declaration
    133         nodeText = getOrCreateNodeText(observedNode);
    134     } else {
    135         nodeText = getOrCreateNodeText(optional.get());
    136     }
    137
    138     if (oldValue == null) {
    139         // Find the position of the comment node and put in front of it the [...]
    140         int index = optional.isPresent() ? nodeText.findChild(observedNode) : 0;

The idea is to insert the leading comment not through the (non-existent) parent, but through the node (CompilationUnit) itself. 
Hope this helps to implement a proper solution.

**Comment by matozoid** [comment]
Thanks for the great report and help! For now I've found two problems:
- the one found here: setting a comment on `CompilationUnit` simply doesn't work. It's an odd situation, and I think your fix to put it at the top of the file is fine. (It probably triggers on partial AST's too, and assuming the top is fine there too.)
- the lexical preserving printer is set up too soon. All the comments get set on the AST after that, and all of them needlessly trigger the printer.

**Comment by matozoid** [comment]
@MysterAitch - maybe. Better retest after this fix.

**Comment by matozoid** [comment]
Alright, I'm currently flabbergasted by the comment code. There is a lot wrong there.

**Comment by matozoid** [comment]
PR is open for review.
