### ISSUE TITLE
isPhantomNodeCache is never cleaned up. Let's add a way to clean it up manually

### ISSUE THREAD

**Issue by quanturium** [javaparser/javaparser#2515]
Context: This comes from lexical preservation: [https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/PhantomNodeLogic.java](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/PhantomNodeLogic.java)

This cache seems to be used to preserve the lexical grammar. It is not used if setLexicalPreservationEnabled is set to false inside the ParserConfiguration object.

Previous conversation on Glitter chat:

@myself : Hello, isPhantomNodeCache seems to be growing indefinitely. What would be a good way to clean it up? I'm iterating over a list of files that I might or might not want to modify. They are all independent of each other. I'd like to cleanup isPhantomNodeCache instead of letting it grow linearly.
[...]
@matozoid : I guess someone will need to look into that. Can you open an issue?

I will follow up with a diff allowing manual cleanup.

**Comment by matozoid** [comment]
Let's keep this one open, we can investigate how to make the cache self-managing. It's odd that we have all these caches that grow infinitely big!

**Comment by jlerbsc** [comment]
This issue can be closed because the PhantomNodeLogic class is no longer used in JP. Phantom nodes are now an attribute of every node. Use of the PhantomNodeLogic class is deprecated.
