### ISSUE TITLE
VoidVisitorAdapter skips some NameExprs

### ISSUE THREAD

**Issue by clause** [javaparser/javaparser#252]
The VoidVisitorAdapter does not visit all children of certain nodes types.  For example, the current implementation for visiting a FieldAccessExpr does not dispatch to the field expr itself.

Current:

``` java
@Override public void visit(final FieldAccessExpr n, final A arg) {
    visitComment(n.getComment(), arg);
    n.getScope().accept(this, arg);
}
```

Proposed:

``` java
@Override public void visit(final FieldAccessExpr n, final A arg) {
    visitComment(n.getComment(), arg);
    n.getScope().accept(this, arg);
    n.getFieldExpr().accept(this, arg);
}
```

Similarly, the visit method for MethodDeclaration does not dispatch to the declaration's name.  Unfortunately, I'm not sure in how many cases nodes are skipped.

**Comment by clause** [comment]
Along this issue, is there a reason why, in some cases, names are stored as NameExprs while in others they are stored as Strings?  For example, in ClassOrInterfaceDeclaration the name is stored as a  NameExpr (from the parent class) while in ClassOrInterfaceType the name is stored as a String.

It would simplify processing if names were always part of a parse tree as NameExprs.

**Comment by ptitjes** [comment]
Indeed!

**Comment by matozoid** [comment]
I started working on this, but quickly found that
- String getName belongs to NamedNode
- NameExpr getNameExpr exists in some places

So we could...
- make everything consistent by putting both methods in NamedNode, or
- add another interface "NameExpressionNode" or so, or
- following another discussion: getting rid of NameExpr completely.

I need some input on this.

**Comment by matozoid** [comment]
(Note: the fix to VoidVisitorAdapter has already been merged.)

**Comment by matozoid** [comment]
Opened #358 to discuss node naming.
