### ISSUE TITLE
How to get the qualified name of returnValueType, Parameter, throwException in a method?

### ISSUE THREAD

**Issue by attenton** [javaparser/javaparser#2524]
Thank you for your works. It heps me a lot. And now I meet some problems. I want get the qualified name of returnValueType, Parameter, throwException in a method. For example, `public StateEngine add(State oldState, Input input, Guard guard, Action action, State newState) throws IllegalStateException`, the returnValueType, parameters and exception are all simple names(`StateEngine`, `State`, `IllegalStateException`). and the qualified name of the parameters can be fetched by the QualifiedSignature of the methodDeclaration. however I don't know hwo to get the qualified names of returnValueType and throwException? So how can I get the qualified names? Thank a lot.

**Comment by matozoid** [comment]
Hi! You need the symbol solver for this - check out our getting started page: https://javaparser.org/getting-started.html

**Comment by MysterAitch** [comment]
Hi @attenton, it looks like the question has been answered and it has been over a month since the last reply, so I'm going to close this issue to help keep the issue tracker tidy.

Please do reply/follow up if there is anything outstanding!

Stay safe and take care :)
