### ISSUE TITLE
How do I add try/catch statement by line number

### ISSUE THREAD

**Issue by lingchaochen** [javaparser/javaparser#2530]
Thanks for your great work! I am learning it to help me fix some buggy code. However, I am facing a problem and don't how to solve it. I want to add a try/catch statement by a specific line number. For example, I want to add a try/catch statement in line 9 to include the whole whilestatement in the following code.
```
public class CSV_Parser{

    public ArrayList<String[]> parse() throws IOException {

        CSVReader reader = new CSVReader(new FileReader(filepath + "/" + filename));

        ArrayList<String[]> lines = new ArrayList<>();
        String[] line;
        while ((line = reader.readNext()) != null) {
            if(line.length <= 1)
                continue;
            else
                lines.add(line);
        }
        return lines;
    }
}
```
I know how to add a blockstatement. For the try/catch statement, should I clone the statement with the specific line number and put it in the TryStatement, delete the original statement, and add the new try/catch statement? Is anyone could give me a sample to help me?

**Comment by edefazio** [comment]
You probably dont want to identfy by line number per se... 
I'd navigate and get the whileStatement heres some code that should do what you want (youll need to customize it of course)

```java
 public void testRead(){
        CompilationUnit cu = StaticJavaParser.parse("...CSV_Parser.java");

        //find the while statement
        WhileStmt ws = cu.findFirst(WhileStmt.class).get();

        //build the try statement
        TryStmt ts = new TryStmt();
        BlockStmt bs = new BlockStmt();
        bs.addStatement(ws.clone()); //clone the whilestmt here
        ts.setTryBlock(bs);

        CatchClause cc = new CatchClause();
        Parameter p = new Parameter();
        p.setName("ex");
        p.setType( Ast.typeRef(Exception.class));
        cc.setParameter(p);
        BlockStmt cb = new BlockStmt();
        cb.addStatement(StaticJavaParser.parseStatement("System.out.println(\"Exception\");"));
        cc.setBody(cb);
        NodeList<CatchClause> sts = new NodeList<>();
        sts.add(cc);
        ts.setCatchClauses(sts);

        //replace the while statement with the trycatch
        ws.replace(ts);
    }
```

**Comment by matozoid** [comment]
(If you really do want to use line numbers, you could visit or walk the whole AST, examining getRange() to see what line number that node was originally on, examining the type of the node to be what you want, and if you find the one you want, do @edefazio's code. Note that the line numbers point to the source file that was parsed, by the way, they will not be updated, and new nodes won't have line/column information... unless you call `CompilationUnit.recalculatePositions()`)

**Comment by lingchaochen** [comment]
Thanks for your help! I could try to follow @edefazio 's code to do it. I am thinking about there might be another solution is to addThrownException in the corresponding MethodDeclaration. 
```
public class test {

    public void test() {
        CompilationUnit cu = StaticJavaParser.parse("...CSV_Parser.java");
        int lineNum = 9;
        List<String> methodCalls = getMethodCallExprByLineNumber(cu, lineNum);
        HashSet<ResolvedType> exceptions = findAllExeceptionByLineNumber(cu, lineNum, methodCalls);
        modifyMethodExceptionByLineNumber(cu, lineNum, exceptions);

    }
    public static List<String> getMethodCallExprByLineNumber(CompilationUnit cu, int lineNumber) {
        List<String> result = new ArrayList();
        List<MethodCallExpr> MethodCallExprs = cu.findAll(MethodCallExpr.class);
        for (MethodCallExpr MethodCallExpr : MethodCallExprs) {

            if (MethodCallExpr.getBegin().get().line == lineNumber) {
                result.add(MethodCallExpr.getNameAsString());
            }
        }
        return result;
    }
    public static HashSet<ResolvedType> findAllExeceptionByLineNumber(CompilationUnit cu, int lineNumber, List<String> methodLists) {

        HashSet<ResolvedType> method_exceptions = new HashSet<>();
        List<NameExpr> nameExprs = cu.findAll(NameExpr.class);
        for (NameExpr nameExpr : nameExprs) {
            if (nameExpr.getBegin().get().line == lineNumber) {
                ResolvedValueDeclaration resolve = nameExpr.resolve();

                if (resolve.getType().isReferenceType()) {
                    ResolvedReferenceType resolve_reference = resolve.getType().asReferenceType();
                    List<ResolvedMethodDeclaration> resolvedMethods = resolve_reference.getAllMethods();
                    for (ResolvedMethodDeclaration resolvedMethod : resolvedMethods) {
                        for (String m : methodLists) {
                            if (resolvedMethod.getName().equals(m)) {
                                List<ResolvedType> e = resolvedMethod.getSpecifiedExceptions();
                                method_exceptions.addAll(e);
                            }

                        }
                    }
                }

            }
        }
        return method_exceptions;
    }

    public static void modifyMethodExceptionByLineNumber(CompilationUnit cu, int lineNumber, HashSet<ResolvedType> exceptions) {

        List<MethodDeclaration> methodDeclarations = cu.findAll(MethodDeclaration.class);
        for (MethodDeclaration methodDeclaration : methodDeclarations) {

            for (ResolvedType e : exceptions) {

//				methodDeclaration.addThrownException(e.asReferenceType());

            }

        }
    }
}
}
```
Because the exception was located in the third-party jar files, I only get the ResolvedType here. However, the method 'methodDeclaration.addThrownException()' needs ReferrencedType. Is there any way to transform it or this solution cannot work? Sorry for my elementary questions and thanks again.

**Comment by edefazio** [comment]
No offense... (this is only my opinion), but your approach is more work/more tedious/more error prone.

Unless you want to have JavaParser parse the source code for all your 3rd party jars, I think you are gonna have a bad time. 

I'd just update the code at the call site... if you don't know all the exception types, I'd use `Throwable/Exception/RuntimeException` or whatever is appropriate...  

Otherwise I would manually update the code rather than try to update code via JavaParser

**Comment by matozoid** [comment]
Doesn't `addThrownException` add an exception...
```java
class X{
   void x() throws ***here*** {
   }
}
```

?

**Comment by lingchaochen** [comment]
@matozoid Yes. I found `addThrownException` accepts `ReferrencedType` argument. But the specific exception from the third-party jar is a `ReferrencedType`.
