### ISSUE TITLE
Error while Private methods and private static methods defined in Java 11 interface.

### ISSUE THREAD

**Issue by eyals24** [javaparser/javaparser#2533]
From Java 9 on wards, we can write private methods in interfaces using private access modifier . 
However the parser throws com.github.javaparser.ParseProblemException: 'private' is not allowed here.

**Comment by matozoid** [comment]
Hi! Did you set the language level to 9 in the configuration?

**Comment by eyals24** [comment]
> Hi! Did you set the language level to 9 in the configuration?

I didn’t. Thanks . I thought It’s come from build.gradle sources compatibility.

**Comment by pvlasov** [comment]
Hello,

I'm using 3.25.9 and getting "(line 5,col 4) Cannot be 'abstract' and also 'private'." problem on a private interface method. My language level is 17. With level 9 it reports the same problem.

Test case:

```java
@Test
public void testPrivateInterfaceMethod() {
	ParserConfiguration parserConfiguration = new ParserConfiguration();
	parserConfiguration.setLanguageLevel(LanguageLevel.JAVA_17);
	JavaParser parser = new JavaParser(parserConfiguration);
	ParseResult<CompilationUnit> parseResult = parser.parse("""
					package org.nasdanika.graph;
					
					public interface Element {
					
						private void matchPredicate(Object obj, String expr) {
						
						}
						
					}
		""");
	System.out.println(parseResult.getProblems());
}
```
The problem comes from ModifierValidator line 131 and is caused by the fact that the method declaration isAbstract() returns true, which seems to be because the implementation doesn't take private modifier into account on line 280.
I still get the compilation unit, but the problem report is wrong.

Can you please help?

**Comment by jlerbsc** [comment]
Hi @pvlasov,  I've just tested your code and the parsing is successful.

**Comment by pvlasov** [comment]
Hi @jlerbsc,

Thank you for taking a look!

The above code doesn't fail, it just prints problems to the console. You can find two failing tests here: https://github.com/Nasdanika/javaparser-tests

Maven output in my environment (``mvn clean package``):

```
[ERROR] Failures:
[ERROR]   JavaParserTests.testPrivateInterfaceMethod:37 [(line 5,col 4) Cannot be 'abstract' and also 'private'.] ==> expected: <true> but was: <false>
[ERROR] Errors:
[ERROR]   JavaParserTests.testPrivateInterfaceMethodStatic:43 ? ParseProblem (line 5,col 4) Cannot be 'abstract' and also 'private'.                                                                                                                                                                                                                                                                                                                                    
    
[ERROR] Tests run: 2, Failures: 1, Errors: 1, Skipped: 0                                                                                    
```

Please advise! It is not a showstopper for me, but it would confuse my users and I would appreciate it addressed!

**Comment by jlerbsc** [comment]
I don't know what to tell you... I ran your 2 test cases without error.

**Comment by pvlasov** [comment]
@jlerbsc, it fails for me on two different machines and also in GitHub actions (https://github.com/Nasdanika/javaparser-tests/actions/runs/8481467915/job/23238850547):

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.nasdanika.javaparser.tests.JavaParserTests
[(line 5,col 4) Cannot be 'abstract' and also 'private'.]
false
Optional[package org.nasdanika.graph;

public interface Element {

    private void matchPredicate(Object obj, String expr) {
    }
}
]
Error:  Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.216 s <<< FAILURE! -- in org.nasdanika.javaparser.tests.JavaParserTests
Error:  org.nasdanika.javaparser.tests.JavaParserTests.testPrivateInterfaceMethodStatic -- Time elapsed: 0.167 s <<< ERROR!
```

My hypothesis is that you might have already fixed version in your local maven repository - happened to me once or twice with my products.

Can you try

```
mvn clean
mvn -Dmaven.repo.local=target/maven-repository package
```
This way it will pull all dependencies into a new repository. However, if your setup points to something other than Maven Central it may still yield a result different from mine. If it still passes, can you go to the ``target\maven-repository\com\github\javaparser\javaparser-core\3.25.9`` directory and check ``javaparser-core-3.25.9.jar.sha1``? I have ``ffd55be7e8739c267952b5d1ea3714725840fd7c`` in mine.

**Comment by jlerbsc** [comment]
I don't have the time to do this right now. Perhaps you could try with the snapshot version?

**Comment by pvlasov** [comment]
Thank you, @jlerbsc! Tests pass with 3.25.10-SNAPSHOT, I checked the sources and the issue was fixed by you 3 weeks ago - issue 4331.
I'll wait for 3.25.10 release!
