### ISSUE TITLE
Github README Outdated

### ISSUE THREAD

**Issue by dev-ns8** [javaparser/javaparser#2558]
Probably not a huge issue, but this is a high quality library so I figured I would bring this to someones attention.  The README states that the current version of symbol-solver-core is 3.15.15, however the latest in the maven repo is 3.15.12.  Maven fails to resolve the dependency if you blindly copy the <dependency> from the README

![Screenshot (3)](https://user-images.githubusercontent.com/9218296/76315759-b85b2000-62af-11ea-8559-d175467e67b4.png)

**Comment by matozoid** [comment]
True, we're having problems uploading to Maven central, so it might be a good idea to temporarily reduce the version. 3.15.14 is the latest: https://search.maven.org/search?q=g:com.github.javaparser

**Comment by matozoid** [comment]
Done! Thanks!
