### ISSUE TITLE
Same package name in different modules causes error when compile java9 module

### ISSUE THREAD

**Issue by dong-li-awx** [javaparser/javaparser#2563]
Package `com.github.javaparser.symbolsolver.model.typesystem` exists both in `javaparser-symbol-solver-model` and `javaparser-symbol-solver-core`, which causes error when requires module in `module-info.java` 
```
module my.module {
^^^^^^^^^^^^^^^^
    requires com.github.javaparser.symbolsolver.core;
    requires com.github.javaparser.symbolsolver.model;
}
```
Error message: `module my.module reads package com.github.javaparser.symbolsolver.model.typesystem from both com.github.javaparser.symbolsolver.core and com.github.javaparser.symbolsolver.model`

**Comment by matozoid** [comment]
Interesting, thanks!

**Comment by MysterAitch** [comment]
I'm not familiar with modules yet, so please forgive the potentially naive questions!

- Does this problem occur every time that a package exists within multiple modules? 

- With the caveat that the project is built under java 8, is anything else needed to be done ensure that the project is compatible with java 9 modules?

**Comment by dong-li-awx** [comment]
@matozoid 
> Does this problem occur every time that a package exists within multiple modules?

Yes, reading package with the same name from different modules is forbidden by Java 9 Module System.

> With the caveat that the project is built under java 8, is anything else needed to be done ensure that the project is compatible with java 9 modules?

I think Module System is the key change of Java 9.

**Comment by MysterAitch** [comment]
@letitb - thanks, the notes are much appreciated by me! 

Is this the only place that packages are duplicated across modules? I have only limited pc access until tomorrow so can't personally check yet.
