### ISSUE TITLE
Fetch comments before methods in java file

### ISSUE THREAD

**Issue by srimathigowri** [javaparser/javaparser#2568]
Sample Java file - sample.java

```
import java.io.File;

class SampleClass

{
public static String concat(String s1, String s2){
    return s1+"_"+s2;
}

/*
sample comment outside function
*/

public static int product(int n1, int n2){
    /* 
    sample comment inside function
     */
    return n1*n2;
   }


public static void main(String[] args) {
    System.out.println(product(3,2));
    System.out.println(concat("My","Name"));
}
}
```

Looking to fetch comments INSIDE and OUTSIDE methods.

Able to get the comments INSIDE Methods with the following pipeline:

```
Extract Methods from file using - VisitorAdapter and Visit
Comments inside the method - MethodDeclaration and getAllContainedComments()
```

op:
```
[sample comment inside function]
```

Similarly any methods/ways to get the comments before the method body?

Sample Expected OP:

```
[sample comment outside function]
[sample comments inside function]

**Comment by edefazio** [comment]
If you want to get the comments within a `CompilationUnit`, you call 
`getAllContainedComments()`

for instance assuming you have CompilationUnit cu
`cu.getAllContainedComments().forEach(c -> System.out.println("CONTAINED"+c ));`

produces:
```java
CONTAINED/*sample comment outside function*/
CONTAINED/*sample comment inside function*/
```

**Comment by MysterAitch** [comment]
@srimathigowri -- Are you looking to get **all** comments throughout the file? If so, take a look at @edefazio 's comment.

If you want comments attached to a method (I'm wondering if this is what "comments before methods" means), this should be possible via the method declaration's method `getComment()`.

**Comment by srimathigowri** [comment]
> @srimathigowri -- Are you looking to get **all** comments throughout the file? If so, take a look at @edefazio 's comment.
> 
> If you want comments attached to a method (I'm wondering if this is what "comments before methods" means), this should be possible via the method declaration's method `getComment()`.

You are right, I am looking for the latter but Method declaration's getComment() fetches the comment within the method, For example:

```

/*
this function is a sample OUTSIDE comment
*/

public static void sampleFunc(){
/*
this function is a sample INSIDE comment
*/
}

```

getComment() is getting the comments `this function is a sample INSIDE comment` and not `this function is a sample OUTSIDE comment` which I need.

**Comment by edefazio** [comment]
I am not getting the same results as you...(this test passes because calling `getComment()` on the method is NOT PRESENT, it is NOT returning the inside comment)
```java
    public void testCommentAttribution(){
        
        CompilationUnit cu = StaticJavaParser.parse(
                "public class C{\n" +
                "/*\n" +
                "this function is a sample OUTSIDE comment\n" +
                "*/\n" +
                "\n" +
                "public static void sampleFunc(){\n" +
                "/*\n" +
                "this function is a sample INSIDE comment\n" +
                "*/\n" +
                "}\n"+
                "}"
        );
        assertFalse(cu.getType(0).getMethods().get(0).getComment().isPresent());
    }
```

IMHO easiest way is to get all comments, and since comments have a reference back to the node they are referencing through `getCommentedNode()` (this is called Attribution) 
the comments that are not "Attributed" or tied to anything, (here Methods) have no attribution.

FYI I believe this is still relevant:
https://tomassetti.me/java-comments-parsing/

**Comment by edefazio** [comment]
in the above case, 
```java
/*
this function is a sample OUTSIDE comment
*/
```

is NOT attributed to the method `sampleFunc`, so you have to go to the container class, (the `TypeDeclaration`) and `getAllComments` and you will find it.

**Comment by srimathigowri** [comment]
> in the above case,
> 
> ```java
> /*
> this function is a sample OUTSIDE comment
> */
> ```
> 
> is NOT attributed to the method `sampleFunc`, so you have to go to the container class, (the `TypeDeclaration`) and `getAllComments` and you will find it.

Great. Thanks for the suggestions.
