### ISSUE TITLE
Extract enums from Java file.

### ISSUE THREAD

**Issue by srimathigowri** [javaparser/javaparser#2571]
Sample Java file:

```java
import java.io.File;

class SampleClass {

    public enum CARS {
        HONDA("stand",0),
        MERC("stand",0),
    }

    public static String concat(String s1, String s2){
        return s1+"_"+s2;
    }

/*
sample comment outside function
*/

    public static int product(int n1, int n2){
        return n1*n2;
    }


    public static void main(String[] args) {
        System.out.println(product(3,2));
        System.out.println(concat("My","Name"));
    }

}
```

I am using the following pipeline to extract all methods from the file:

```java
public static fetchMethods(String fpath){

    (VoidVisitorAdapter) visit(n,arg) -> {
        super.visit(n,arg);
        System.out.println(n.getDeclarationAsString());
    }.visit(StaticJavaParser.parse(new File(path),null);
}
```

Similarly any suggestions on inbuilt functions for extracting `ENUMS` in the file.

Expected OP in this case - A `List<String>` with length 1:

```
["public enum CARS {  HONDA("stand",0), MERC("stand",0) }"]
```

**Comment by edefazio** [comment]
Is the above even valid Java code (i.e. does it compile in your editor)?

You are going top have to learn how the tool works by reading up and using it a bit
https://javaparser.org/inspecting-an-ast/

and maybe getting the book...
https://leanpub.com/javaparservisited

Good luck

**Comment by MysterAitch** [comment]
I've taken the liberty of reformatting the code snippets to be more readable. As it is whitespace-only changes then it shouldn't change the output, but if it does let us know!

As @edefazio says, take a look at the documentation and do feel free to follow up if there's anything else unclear!

**Comment by MysterAitch** [comment]
Hi @srimathigowri, it looks like the question has been answered and it has been over a month since the last reply, so I'm going to close this issue to help keep the issue tracker tidy.

Please do reply/follow up if there is anything outstanding!

Stay safe and take care :)
