### ISSUE TITLE
UnsolvedSymbolException when trying to resolve a methodCallExpr enum argument

### ISSUE THREAD

**Issue by ariel-levy** [javaparser/javaparser#2577]
when trying to resolve a method call that gets an enum argument as a value `JavaParderFacade::solve` gets an `UnsolvedSymbolException` for that argument.
 This seems to happens only when the enum is not the declared in the same CU.
can be reproduced with `https://github.com/029ye/Java-.git` on calls to `getDtoItems`, methodCallExpr node solving succeed for calls from `main/java/cz/jiripinkas/jba/service/ItemService.java` and fails for every other call.

It rose with a simple visitor and a standard `combinedTypeSolver` containing `javaParserTypeSolvers`  (other methodCallExpressions in the project resolves great without any issues)

**Comment by MysterAitch** [comment]
I've tried to reproduce, but struggled as I'm not 100% sure what circumstances are needed to make it happen again.

Which method fails to resolve?

Any chance you could put together a test case e.g. an enum file and a single class that shows this bug please?

**Comment by vnique** [comment]
I got the same problem when trying to resolve a method call that gets an enum argument as a value
I have 4 files:

package test;
import test.B.*;
public class A {
    public static EB eb = null;
}

package test;

public class B {
  public enum EB {
    VA("va"),
    VB("vb");

    String name;

    EB(String name) {
      this.name = name;
    }
  }
}

package test;
import test.B.*;
public class C {
  public int test(EB b) {
    return 0;
  }
}

package test;

import static test.A.*;

public class Main {
  public static void main(String[] args) {
    int x = new C().test(eb);
  }
}

when I solve the type of 'eb' in Main  method in Main class,got UnsolvedSymbolException

**Comment by jlerbsc** [comment]
This issue cannot be reproduce with this test case. Of course you can comment on this ticket if the test case is not completely correct.

    public class Issue2577Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {
        final Path testRoot = adaptPath("src/test/resources/issue2577");
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(testRoot);
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(reflectionTypeSolver, javaParserTypeSolver);
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
        StaticJavaParser.setConfiguration(configuration);

        String src = 
                "import a.Status;\n"+
                "public class B {\n" +
                "  public void m(Status s) {\n" +
                "  }\n" +
                "\n" +
                "}";

        CompilationUnit cu = StaticJavaParser.parse(src);

        List<MethodDeclaration> mds = cu.findAll(MethodDeclaration.class);
        System.out.println(mds.get(0).resolve().getQualifiedSignature());
    }
    }

and enum

    package a;
    public enum Status {
      CLOSED;
    }

result

    B.m(a.Status)
