### ISSUE TITLE
Travis being "flakey"?

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2582]
Not sure if I'm just noticing it more, but I keep seeing the build checks hang due to the Travis check.

Most of the time either there has been a network error and the dependency hasn't downloaded, or it has passed fine but for some reason it hasn't registered with GitHub.

Just posting this in case anyone knows a bit more about it and can comment!

**Comment by matozoid** [comment]
I've seen this too. There was a wave of enthusiasm over building inside github lately. Not sure how that works but might be interesting.

**Comment by MysterAitch** [comment]
I'm gonna close this as things seem to have stabilised a fair bit recently and there's presumably not a lot we can do about Travis directly!

Can always re-open if it crops up again.

**Comment by MysterAitch** [comment]
Hmm... spoke too soon!!! 

![image](https://user-images.githubusercontent.com/1537214/80012941-02960a80-84c6-11ea-8c4b-e264a98c8f4e.png)
