### ISSUE TITLE
printStackTrace is called directly from GeneratedJavaParserTokenManager

### ISSUE THREAD

**Issue by ReallyLiri** [javaparser/javaparser#2584]
I'm seeing stack traces printed to console without usage of log adapter.

I tracked it back to GeneratedJavaParserTokenManager code:

```
    private void CommonTokenAction(Token token) {
        // Use an intermediary stack to avoid recursion, see issue 1003
        do {
            tokenWorkStack.push(token);
            token = token.specialToken;
        } while (token != null);

        // The stack is now filled with tokens in left-to-right order. Process them.
        while(!tokenWorkStack.empty()) {
            token = tokenWorkStack.pop();
            token.javaToken = new JavaToken(token, tokens);

            if(storeTokens) {
                tokens.add(token.javaToken);
            }

            if (homeToken == null) {
                homeToken = token.javaToken;
            }

            if(token.kind == JAVADOC_COMMENT){
              JavadocComment comment = (JavadocComment) createCommentFromToken(token);

              try {
                InputStream stream = new ByteArrayInputStream(token.image.getBytes("UTF-8"));
                GeneratedJavaDocParser jdp = new GeneratedJavaDocParser(stream, "UTF-8");
                try {
                  comment.setContentNode(jdp.parse());
                } catch(com.github.javadocparser.ParseException e) {
                  Log.error(e);
                  e.printStackTrace();
                }
              } catch(java.io.UnsupportedEncodingException e) {
                e.printStackTrace();
                System.exit(1);
              }

              commentsCollection.addComment(comment);
            } else if(TokenTypes.isComment(token.kind)) {
                Comment comment = createCommentFromToken(token);
                commentsCollection.addComment(comment);
            }
        }
    }
```

I would expect it to use `Log.error()`.

I couldn't track back where this file is generated from. `com.github.javadocparser.ParseException` seems to be generated too.

**Comment by edefazio** [comment]
I'm in the middle of a big refactor, I can double check when things are back normalized,

I think I've noticed the same thing (logs being printed when I run tests when I upgraded to the 3.15.17 version) (Logs being printed out)

but until then ... are you sure that some of the other code you are calling doesn't 
setUp the Log? (I'm not accusing, I've done this many times myself)...

(alternatively, can you roll back to a previous version and see if the error persists?)

thanks

**Comment by edefazio** [comment]
From Gitter chat:

Danny van Bruggen @matozoid 09:02
@edefazio - issue #2584 is caused by that Javadoc merge. It was rolled back and put on a branch.

**Comment by edefazio** [comment]
Imma close this unless you have any objection...

**Comment by ReallyLiri** [comment]
no objection, waiting for roll back release

**Comment by matozoid** [comment]
That was released quite a while ago: https://github.com/javaparser/javaparser/blob/master/changelog.md
