### ISSUE TITLE
Parser errors

### ISSUE THREAD

**Issue by koor-fr** [javaparser/javaparser#2587]
Hi,

For informations, i had test JavaParser on Java SE 14 (Open JDK) source code (ZIP located in $JDK_HOME/lib/src.zip). Some files cannot be parsed. For example, you can test these files :

>>> Cannot parse src-jdk/java.desktop/java/awt/Cursor.java
[(line 339,col 13) Try with resources only supports variable declarations.]

>>> Cannot parse src-jdk/java.base/java/io/FileDescriptor.java
[(line 341,col 13) Try with resources only supports variable declarations.]

It can be boring.
Thank you

**Comment by edefazio** [comment]
Hi, thanks for the report... can you provide the code you are using for the parse?

also which version of the JavaParser are you using ? (3.15.17)?

(Just want to make sure you are using the `ParserConfiguration.LanguageLevel.JAVA_14` features)

thanks

**Comment by koor-fr** [comment]
Ok, it's my fault, I didn't configure this point. 
There are no more problems. 
Sorry and thank you very much.
