### ISSUE TITLE
About the class inheritance relation

### ISSUE THREAD

**Issue by ZSShen** [javaparser/javaparser#259]
Hi there, I am new to this amazing project!

Well, my question is, is it possible to blueprint the `class inheritance relation` via some 
javaparser APIs?

For example, 

``` java
List<TypeDeclaration> list_type = cu.getTypes();
for (TypeDeclaration type : list_type) {
    List<BodyDeclaration> list_member = type.getMembers();
    // type.getBaseType(); Some APIs to trace the inherited ancestors.
}
```

It seems that TypeDeclaration does not offer the similar functionality.

**Comment by ftomassetti** [comment]
No, it is not possible to print the inherited ancestors. JavaParser is a parser and built the AST: it basically organizes in a tree the information which is present in the source file. However to find the inherited ancestor you should be able to find the declarations corresponding to the names. For example:

```
import a.Foo;

class A extends Foo {
}
```

In this case the AST tells me that A extends "Foo" but it does not have the logic to understand that "Foo" is actually "a.Foo" and it does not know how to locale a.Foo, extract information from it and finding the ancestors. Note that a.Foo could be a class in a Jar, in the JDK or another source file.

**Comment by ZSShen** [comment]
Got it! Thanks for the tip. :)
