### ISSUE TITLE
Finding all the control variables from a method

### ISSUE THREAD

**Issue by shaifulcse** [javaparser/javaparser#2596]
From this expression:
`actualCounter.value(Scope.PACKAGE) > mMax`

I am trying to extract `Scope.PACKAGE`, and `mMax`.

If I use, `expr.findAll(NameExpr.class)`
I get `[actual, Scope, and mMax]`. 
I don't want `actual` because it's not a control variable. Also, I want  `Scope.PACKAGE`, not just `Scope`, because it creates problem later. Any idea please.

**Comment by MysterAitch** [comment]
Off the top of my head, if you're having arbitrary input then "not easily".

As a general hint, I very strongly recommend defining your task more precisely. When you say "control variables", what exactly does this mean? Parameters passed into a method? Variables used within a comparison?

By breaking down the definition of "control variables" in this way, it will help you to improve the accuracy/precision of your query (i.e. reducing false positives/negatives).

Hope this helps!

**Comment by shaifulcse** [comment]
Control variables are the variables that are part of a conditional expression, because they decide which path the flow will follow. 

` actualCounter.value(Scope.PACKAGE) > mMax`

In the above example, we have two control variables (including fields I guess): 
`Scope.PACKAGE `and  `mMax`

How can I retrieve all such names  from an expression. NameExpr type returns all the names including `actualCounter` (which I don't want). It also can not catch subnames after dot. It does not return  `Scope.PACKAGE `, it returns only `Scope`.

**Comment by edefazio** [comment]
So until you get familiar with the way the AST nodes are composed, what you are asking gets difficult to communicate (there isnt a concept of 'control variables' in the JLS or JP as you describe).  So, in this case you are going from a Generic Structure (Expression) and you want to extract "specific" things from it... I'd probably FIRST need to look at the tree based on the expression:

```java
    public void testPrintExpressionTree(){
        //How to "break down" an expression into it's parts
        Expression e = StaticJavaParser.parseExpression("actualCounter.value(Scope.PACKAGE) > mMax");
        e.stream().forEach(n-> System.out.println( n.getClass().getSimpleName()+System.lineSeparator()+"    "+n) );
   }
```
it'll print this:
```java
BinaryExpr
    actualCounter.value(Scope.PACKAGE) > mMax
MethodCallExpr
    actualCounter.value(Scope.PACKAGE)
NameExpr
    actualCounter
SimpleName
    actualCounter
SimpleName
    value
FieldAccessExpr
    Scope.PACKAGE
NameExpr
    Scope
SimpleName
    Scope
SimpleName
    PACKAGE
NameExpr
    mMax
SimpleName
    mMax
```

 In your case, when you understand which specific nodes you have, you can manually look at them:

```java
    public void testBinaryE(){
        //In your case, what we really have is a BinaryExpr
        //you need to look at the underlying internal node types in order to extract
        // "control variables"
        BinaryExpr be = (BinaryExpr)StaticJavaParser.parseExpression(
                "actualCounter.value(Scope.PACKAGE) > mMax");
        System.out.println( be );
        MethodCallExpr mce = (MethodCallExpr)be.getLeft();
        NameExpr ne = (NameExpr)be.getRight();
        System.out.println( "ARG: " + mce.getArguments().get(0) );
        System.out.println( "NAME: " +ne );
    }
```

NOTE: this could also be done via listeners, but you probably want to get more familiar with the way the JavaParser AST puts things together, reading the book or looking at some examples might help you on your way.

thanks

**Comment by shaifulcse** [comment]
Amazing. Thanks so much.
