### ISSUE TITLE
MethodDeclaration.getComment() returns the JavaDoc, but only if there are no comments present as well

### ISSUE THREAD

**Issue by Alexeggers** [javaparser/javaparser#260]
Disclaimer: I am only a lowly trainee, so please forgive me if I made elementary mistakes :(

I am writing an automatic API generator, and the classes need JavaDoc as well as comments because some of the values the API contains shouldn't be written down in the JavaDoc (exampleResponse for example).

However, it seems that the comments above the individual Methods replace the Javadoc, so when I want to get the description from the JavaDoc (which i want to do so I don't have to write it again in the comments), I have a problem.

Is there any way to work around this?

EDIT: Using getJavadoc() always returns null. I also attempted to use getOrphanComments(), but it returned null. Did I misunderstand the documentation? I assumed if I wrote two comments above a method, the top one would move to orphanComments for that method.

**Comment by SmiddyPence** [comment]
Hi.  Sorry it took so long to respond.

Can you provide the source that produces your problem?  t makes much easier to investigate.

Thanks

**Comment by matozoid** [comment]
There's a PR waiting here that will fix how JavaDoc functions: https://github.com/javaparser/javaparser/pull/336

Since there was no reply to the question, I'm closing this.
