### ISSUE TITLE
Update versions in the readme when the version changes

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2613]
My presumption is that there should be a way to do this automatically as part of the release process.

I'm not 100% how best to achieve this, so before running with it I'd like to open it out for discussion.

To start things off, [this SO question](https://stackoverflow.com/questions/34629326/update-versions-contained-in-readme-on-maven-release) has a few answers/suggestions. 

One suggestion there is to have a template in the resources directory with placeholders for version numbers, where these placeholders can be replaced during the build (and/or release) process.

**Comment by MysterAitch** [comment]
Also, probably a separate issue, but maybe also have PRs automatically get created for the sample projects when a new release is pushed (might be possible via GitHub actions)?

https://github.com/javaparser/javaparser-maven-sample
https://github.com/javaparser/javasymbolsolver-maven-sample

**Comment by MysterAitch** [comment]
> 
> 
> Also, probably a separate issue, but maybe also have PRs automatically get created for the sample projects when a new release is pushed (might be possible via GitHub actions)?
> 
> [javaparser/javaparser-maven-sample](https://github.com/javaparser/javaparser-maven-sample)
> [javaparser/javasymbolsolver-maven-sample](https://github.com/javaparser/javasymbolsolver-maven-sample)

Just added dependabot to the projects, so when releases get pushed to maven central then a PR will be created to update their dependencies to the latest version :smile:

**Comment by matozoid** [comment]
(Confirmed: this is currently all manual work.)

**Comment by MysterAitch** [comment]
http://maven.apache.org/maven-release/maven-release-plugin/examples/run-goals-before-commit.html

This seems to be the "correct" way to do it using the release plugin which has an option to run goals as part of the release prepare, but before the commit occurs.

Just gotta figure out a goal to run that can do it (maybe something that copies a template over from either the dev folder or a resources folder and replaces version number placeholders).

Probably easy for someone that knows what they're doing 😅

**Comment by matozoid** [comment]
Neat!
