### ISSUE TITLE
Is there a plan to support ResolvedAnnotationExpression?

### ISSUE THREAD

**Issue by marciodel** [javaparser/javaparser#2614]
Hi, I've noticed that, using SymbolSolver,  it is not possible to get the annotations of a resolved declaration or type. 

Is there a plan to support it?

Thanks

**Comment by MysterAitch** [comment]
I can't find a class named that -- are you asking about its introduction?

And is this related to #2055 ?

Please do share some thoughts and/or a PR to review :)

**Comment by marciodel** [comment]
Yes, this is related to #2055. 
 
I'll close this and continue the discussion there.

Thanks
