### ISSUE TITLE
TokenRange not updated?

### ISSUE THREAD

**Issue by hsellik** [javaparser/javaparser#2617]
Hi,

It seems that `tokenRange` does not update when a file/method is parsed without comments. Is this normal behaviour? 

`code` is:
```
    /**
     *
     * @param param1
     */
    public static String foo(long something) {
    	/* 
    	 * comment
    	 */
         // another comment
         int a = 0;
    	// comment
    	return "";
    }
```

I parse this method in the following way:
```
javaParser = new JavaParser();
javaParser.getParserConfiguration().setAttributeComments(false);
javaParser.parseMethodDeclaration(code).getResult();
```
![Screen Shot 2020-04-20 at 16 57 07](https://user-images.githubusercontent.com/16798824/79760027-202d6d80-8328-11ea-814d-d191d8e760dd.png)

**Comment by edefazio** [comment]
Is this referring to @MysterAitch 's IntelliJ Plugin or JavaParser proper?

(I can't reproduce with JavaParser and printing out tree ranges appear to be there):
```java
    public void testFFF(){
        class F {
            /**
             * @param param1
             */
            public String foo(long something) {
                /*
                 * comment
                 */
                // another comment
                int a = 0;
                // comment
                return "";
            }
        }
        JavaParser javaParser = new JavaParser();
        javaParser.getParserConfiguration().setAttributeComments(false);
        CompilationUnit cu = Ast.of(javaParser, F.class);
        Print.tree(cu);
    }
```

returned :
```java
"public class F {...}" CompilationUnit : (1,1)-(7,1)
└─"public class F {...}" ClassOrInterfaceDeclaration : (1,1)-(7,1)
  ├─"public" Modifier : (1,1)-(1,6)
  ├─"F" SimpleName : (1,14)-(1,14)
  └─"public String foo(long something) {...}" MethodDeclaration : (3,5)-(6,5)
    ├─"public" Modifier : (3,5)-(3,10)
    ├─"foo" SimpleName : (3,19)-(3,21)
    ├─"long something" Parameter : (3,23)-(3,36)
    │ ├─"long" PrimitiveType : (3,23)-(3,26)
    │ └─"something" SimpleName : (3,28)-(3,36)
    ├─"String" ClassOrInterfaceType : (3,12)-(3,17)
    │ └─"String" SimpleName : (3,12)-(3,17)
    └─"{...}" BlockStmt : (3,39)-(6,5)
      ├─"int a = 0;" ExpressionStmt : (4,9)-(4,18)
      │ └─"int a = 0" VariableDeclarationExpr : (4,9)-(4,17)
      │   └─"a = 0" VariableDeclarator : (4,13)-(4,17)
      │     ├─"int" PrimitiveType : (4,9)-(4,11)
      │     ├─"a" SimpleName : (4,13)-(4,13)
      │     └─"0" IntegerLiteralExpr : (4,17)-(4,17)
      └─"return "";" ReturnStmt : (5,9)-(5,18)
        └─"""" StringLiteralExpr : (5,16)-(5,17)
```

**Comment by MysterAitch** [comment]
I was a little confused at first but, on the face of it, this seems normal behaviour.

Note that what is displayed in the debugger next to the variable is the output of `toString()` (which uses the pretty printer by default).

With respect to the token ranges, the tokens are still there in the source/tree but they are not necessarily attributed to anything (thus they'll either not be output in `toString()`, or they'll appear at the end as orphaned comments -- judging by the screenshot, they're omitted).

Does this help to clarify things?

**Comment by matozoid** [comment]
The toString of a TokenRange prints the tokens in its range. That's the exact pieces of text found in the parsed source code. The toString of a `Node` uses the pretty printer as @MysterAitch says. The pretty printer is free to do whatever it likes to make things pretty, and tends to accidentally throw comments out.

**Comment by MysterAitch** [comment]
I've just reread this in light of @matozoid 's last comment (in particular the bit about throwing comments out) and now I'm leaning towards the issue described being a bug in the pretty printer rather than the token list.

The option about comment attribution is whether the comments are attributed to a node, not whether they should be included in the output.

If the desired behaviour is to not have comments in the tokens, that's a separate thing and will need different configurations.

**Comment by hsellik** [comment]
It might be a separate issue but I do have a similar problem with mutating/changing Java methods. The specific nodes of methods I change do get changed and are reflected in the value variable of the parsed methodDeclaration (green line in the image of first post), but the changes are not updated in tokenRange (red line in the image of first post).

Right now, my workaround for all my tokenRange problems is to get the code from methodDeclaration as a String and reparse the entire method. This will end up with a correct tokenRange.

At that point I was wondering if tokenRange should be something static or change when a method is parsed with options such as discarding comments and also update to reflect manual changes to nodes in the methodDeclaration. 

Is there any way to call a refresh for tokenRange specifically? That would help in my case.

**Comment by MysterAitch** [comment]
I seem to recall that edits not propagating out through the whole model has come up a few times and is probably something that needs to be edited, but I'm not sure what direction this should head in (there's probably an issue or gitter chat about it that I'd need to re-read to catch up). 

@edefazio and @matozoid can probably comment better than I (my use of JavaParser doesn't involve any editing of the AST, so it's not really anything I come across/use much).

**Comment by edefazio** [comment]
`Range` / `TokenRange`s are NOT updated (with `Position` information) when you update an Ast. 

This is just a wrinkle with how things are done with JavaParser... writing it out and reading it back in is the most reliable way to make sure the position / Range information is correct. 
(We all agree this isn't "efficient", but its the state of things right now)

**Comment by hsellik** [comment]
Okay, the final resolution for me is that if I do not want comments to be present in tokenRange, I will double parse the source code.

Feel free to close the issue if you guys think there are no bugs here.
