### ISSUE TITLE
LexicalPreservingPrinter print issue when adding a new element

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2620]
In the latest version, when we add  an element in first position in the ClassOrInterfacedeclaration members list, we are facing to a issue linked to LexicalPreservingPrinter.

    CompilationUnit cu = StaticJavaParser.parse(
                "  public class Foo { //comment\n" +
                "    String a;\n" +
                "  }\n"
                );
        LexicalPreservingPrinter.setup(cu);
        // create a new field declaration
        VariableDeclarator variable = new VariableDeclarator(new ClassOrInterfaceType("String"), "b");
        FieldDeclaration fd = new FieldDeclaration(new NodeList(Modifier.privateModifier(), Modifier.staticModifier()), variable);
        Optional<ClassOrInterfaceDeclaration> cd = cu.findFirst(ClassOrInterfaceDeclaration.class);
        // add the new variable
        cd.get().getMembers().addFirst(fd);
        // should be printed like this
        System.out.println(cu.toString());
       // but the result is
        System.out.println(LexicalPreservingPrinter.print(cu));

should be printed like this

    public class Foo {
       private static String b;
       String a;
    }

but the result is

     public class Foo { //commentprivate static String b;
        String a;
     }

**Comment by MysterAitch** [comment]
Cheers for the report! 

I noticed the phrase "in the latest version" - to clarify, is this something that worked in an older version?

**Comment by edefazio** [comment]
I tried 3.15.10 & 3.15.1 both produced the same failing results, 

I think we might dub this issue:
"LPP/PrettyPrinter/OrphanedComments Modification known unknowns Issue" 

& I'm pretty sure I know how to fix it... 
(its just not gonna be easy as we have to suddenly introduce node order within the Ast, and right now we just willy nilly add nodes (to the end of a nodeList) and remove nodes (from anywhere in the nodeList) to a NodeList when we update the AST). If we could trust the order of the nodes in the nodelist, it would make our lives easier, but thats not how modifications work right now.

Heres when I think I first kinda saw the issue manifest itself:
https://github.com/javaparser/javaparser/issues/2578

**Comment by jlerbsc** [comment]
I think the problem come from Difference.apply(..) and more precisely in applyAddedDiffElement method. But i don't know how to solve it. This code is not documented and the code is relatively complex.

**Comment by MysterAitch** [comment]
Looks like @jlerbsc 's PR in #2646 fixes the issue described (thank you!), but it brings to the fore some other JavaParser behaviours that I am not sure are correct.

It seems that generated code is injected using the host's line endings. This is normally fine, but if the input text has a different line encoding then this leads to a source with mixed line endings. See the quoted post below, and the linked PR, for details.


https://github.com/javaparser/javaparser/pull/2646#issuecomment-623701912

> 
> 
> Digging deeper, @jlerbsc 's fix as given seems to work fine for fixing the problem presented in #2620 , but the tests fail due to the injected line endings not matching the parsed text.
> 
> For example if the parsed text has `\r\n` line endings, then on Ubuntu the host`s line endings (`\n`) are injected -- ONLY on the injected lines.
> 
> I am unsure if this is a separate bug / issue that should be handled separately, or if it should be handled as part of this.
> ### Ubuntu test failures
> 
> https://github.com/javaparser/javaparser/pull/2646/checks?check_run_id=644201141#step:6:1505
> _(line breaks / spacing added for clarity)_
> 
> ```
>  [ERROR] Failures: 
> [ERROR]   Issue2620Test.testWithCr:49->doTest:110 
> expected: <    public class Foo { //comment\r    private String newField;\r    \r    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
>  but was: <    public class Foo { //comment\r    private String newField;\n    \n    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
> 
> [ERROR]   Issue2620Test.testWithCrLf:59->doTest:110
>  expected: <    public class Foo { //comment\r\n    private String newField;\r\n    \r\n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
>  but was: <    public class Foo { //comment\r\n    private String newField;\n    \n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
> ```
> 
> ### Mac test failures
> 
> https://github.com/javaparser/javaparser/pull/2646/checks?check_run_id=644201231#step:6:1499
> _(line breaks / spacing added for clarity)_
> 
> ```
> [ERROR] Failures: 
> [ERROR]   Issue2620Test.testWithCr:49->doTest:110 
> 
> expected: <    public class Foo { //comment\r    private String newField;\r    \r    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
>  but was: <    public class Foo { //comment\r    private String newField;\n    \n    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
> 
> [ERROR]   Issue2620Test.testWithCrLf:59->doTest:110 
> expected: <    public class Foo { //comment\r\n    private String newField;\r\n    \r\n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
>  but was: <    public class Foo { //comment\r\n    private String newField;\n    \n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
> ```
> 
> ### Windows test failures
> 
> https://github.com/javaparser/javaparser/pull/2646/checks?check_run_id=644201340#step:6:1505
> _(line breaks / spacing added for clarity)_
> 
> ```
> [ERROR] Failures: 
> [ERROR]   Issue2620Test.testWithCr:49->doTest:110
> expected: <    public class Foo { //comment\r    private String newField;\r    \r    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
>  but was: <    public class Foo { //comment\r    private String newField;\r\n    \r\n    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
> 
> [ERROR]   Issue2620Test.testWithLf:54->doTest:110 
> expected: <    public class Foo { //comment\n    private String newField;\n    \n    private String a;\n        private String b;\n        private String c;\n        private String d;\n    }>
>  but was: <    public class Foo { //comment\n    private String newField;\r\n    \r\n    private String a;\n        private String b;\n        private String c;\n        private String d;\n    }>
> ```
