### ISSUE TITLE
Add messages to thrown exceptions

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2625]
We have quite a few calls to `new UnsupportedOperationException()` (and similar) without a message to describe why it is unsupported. 

In most cases this will be because an inherited method is not appropriate for that particular sub-class based on the rules/logic of Java / the AST.

In other cases this will be because it's not yet implemented or similar.

Adding in messages to these calls will make the distinction more visible / apparent to any users that come across this, and future developers who are looking at those bits of code.

**Comment by MysterAitch** [comment]
I've just assigned myself to help remind me that I'm working on it, but if anyone else wants to work on it then please do! :)

**Comment by sharath2106** [comment]
@MysterAitch Are you working on this? If not, I'm willing to take this up.

**Comment by MysterAitch** [comment]
> 
> 
> @MysterAitch Are you working on this? If not, I'm willing to take this up.

Please do! :+1: 

I think I did some bits, but then got distracted -- oops!

Incremental improvements are very welcome -- doing every class would be awesome, but if you get bored halfway through then contributing just that would be gratefully received :)

**Comment by MysterAitch** [comment]
One of the things I had in mind for the "longer term" is to create a `NotYetImplementedException` or similar to indicate cases where there is a work in progress or a todo or similar and it _might/should_ be supported in the future. 

There could also be another exception to indicate places where it _shouldn't ever_ be supported and is never likely to be implemented in the future (I can't think of an actual example right now, but these might be thrown as `IllegalStateException`s). 

If that's something you want to give a go too then great, but no worries if not! :smile:

**Comment by nelson-ng-96** [comment]
Hi, I would like to work on this issue for my university project. Is it possible for this issue to be assigned to me? @sharath2106 are you working on this issue?

**Comment by oannhpham** [comment]
Hi! I am currently a student studying at the Australian National University and would like to work on this issue for my university assignment.

@sharath2106 Are you working on this issue and is it possible to assign this issue to me?

**Comment by jlerbsc** [comment]
Of course you can work on this issue but the previous attempt was unsuccessful because the messages were too technical and not sufficiently understandable for a user.

**Comment by oannhpham** [comment]
> Of course you can work on this issue but the previous attempt was unsuccessful because the messages were too technical and not sufficiently understandable for a user.

Thank you! I'll take a look at the previous attempt!
