### ISSUE TITLE
Wrong node range on very long java file

### ISSUE THREAD

**Issue by truongthanh96** [javaparser/javaparser#2627]
Hi I encouter a wrong node range (startLine, endLine are shifted up above) in this file for placeholder methodDeclaration node.

https://github.com/tensorflow/java/blob/49b7bac612adce3773bdc1dff27f36542a91e21d/tensorflow-core/tensorflow-core-api/src/gen/annotations/org/tensorflow/op/Ops.java#L3682-L3685

Parsing only a valid subset of this file (about ~2000 lines) still yield the correct result.
Version:
`    implementation 'com.github.javaparser:javaparser-core:3.15.18'`

OS:
Ubuntu 18.04

**Comment by edefazio** [comment]
I cannot reproduce this behavior... I was able to parse this file and look at the AST for the "placeholder" method, and I got the correct Range:
```java
CompilationUnit cu = StaticJavaParser.parse(Paths.get("C:\\jdraft\\project\\jdraft\\src\\test", "OPS.txt"));
Optional<Node> omd =
                cu.stream().filter(n -> n instanceof MethodDeclaration && ((MethodDeclaration) n).asMethodDeclaration().getNameAsString().equals("placeholder")).findFirst();
System.out.println(  omd.get().getRange().get() );
```
(line 3686,col 3)-(line 3689,col 3)

Note: worked on 3.15.18 and 3.15.21

**Comment by truongthanh96** [comment]
Hi @edefazio thank you for your concern. I have checked again and found that this happen on Ubuntu 18.04 and not happen on Windows 10.  
The above snippet show this line when ran under Ubuntu. 
(line 3682,col 3)-(line 3685,col 3)

On windows it ran perfectly.
(line 3686,col 3)-(line 3689,col 3)

I think this might related to CRLF and LF.

**Comment by edefazio** [comment]
thanks for checking this out... yes, I'm running Windows 10, so its working for me

I'm looking into seeing if there is just a way to "normalize" all the CR LF data (manually) 
and run it through, but Im going to have to check with @MysterAitch or @matozoid who have other OSes if it'll work...

Bummer thing is that most examples out there require the file to be modified, and I dont think we want to do that (i.e. change the single character \r to two characters \n\r which will change the `Position`s/ `Range`s.

Open to possible alternatives (I'd like to use some kinda FilterInputStream to "normalize" this, 
https://www.cct.lsu.edu/~rguidry/ecl31docs/api/org/eclipse/team/internal/core/streams/LFtoCRLFInputStream.html
but perhaps we have to handle this internally)

**Comment by MysterAitch** [comment]
I'm able to reproduce on Windows. tldr: It doesn't immediately seem to be line-separator related.

Looks like the very first method that is offset is at line 907/911 (notepad++ and intellij editors show it to be at line 911, but javaparser reports it to be on line 907).

https://github.com/tensorflow/java/blob/49b7bac612adce3773bdc1dff27f36542a91e21d/tensorflow-core/tensorflow-core-api/src/gen/annotations/org/tensorflow/op/Ops.java#L910-L915


<details>
  <summary>Screenshots are below just in case you can see anything that I'm missing?</summary>


![image](https://user-images.githubusercontent.com/1537214/80283202-ca810880-870d-11ea-91a3-45f593cd72c6.png)


![image](https://user-images.githubusercontent.com/1537214/80283133-7413ca00-870d-11ea-82a9-30760184db18.png)


![image](https://user-images.githubusercontent.com/1537214/80283143-7bd36e80-870d-11ea-8499-2ca1e9de3076.png)


![image](https://user-images.githubusercontent.com/1537214/80283148-83931300-870d-11ea-8c41-bfd5c880029a.png)

</details>

**Comment by truongthanh96** [comment]
I found why.

Parsing with LF cause this problem on windows 10.

(line 3682,col 3)-(line 3685,col 3)

![image](https://user-images.githubusercontent.com/15905652/80296135-a02d5a80-87a2-11ea-95a4-331ad5a4f73d.png)

**Comment by MysterAitch** [comment]
I'm still not sure what is causing this, but I have managed to shrink the testcase to only  165 lines and exaggerate the difference (Expected :161 / Actual :139).

I don't see why this would be an issue or if it is even relevant, but just in case something similar is seen by others -- One of the common bits that seemed to keep cropping up is the use of `[` and `]` in the javadoc (e.g. I could delete one line without [] on it and it'd do the expected thing of shift the line number by one even if it is wrong, but deleting a line with [ or ] on it would cause a parse error).

Smaller example: 
https://github.com/MysterAitch/javaparser/blob/issue_2627/javaparser-core-testing/src/test/resources/com/github/javaparser/issue_samples/issue_2627/Ops_minimal.java

Test results on this example: 
https://github.com/MysterAitch/javaparser/runs/619948157?check_suite_focus=true
