### ISSUE TITLE
variable extraction

### ISSUE THREAD

**Issue by sangram82** [javaparser/javaparser#2628]
when using VariableDeclarationExpr  to get variable of a class , For ex:

Class A{

public void test(){

String s = "a";
if(x==y)
  s = "test"
}
I am getting only one instance i.e s = "a" , is it an issue , or it was the expected behaviour.

**Comment by jlerbsc** [comment]
In your sample, it's the only variable declaration.

**Comment by edefazio** [comment]
yes, the second one 
`s=test`
is an `AssignmentExpr`

**Comment by sangram82** [comment]
I am able to get using AssignmentExpr. Thank you.
