### ISSUE TITLE
DumpVisitor loses comments II

### ISSUE THREAD

**Issue by cdietrich** [javaparser/javaparser#263]
```
package a;

public class Test {

            // one line of comment
            // another line of comment

            static {
                System.out.println("Hello");   
            }   

}
```

the comments get lost wenn dumping the parsed file

**Comment by matozoid** [comment]
Made a potential fix here: https://github.com/javaparser/javaparser/pull/338

**Comment by jlerbsc** [comment]
I'm not sure to understand what you want to say by "dumping the parsed file". When we try to print the compilation unit there is no issue in JP 3.16.1... comments are printed too. Could you give us a test case please? Perhaps this issue is too old. I'm trying to test/close very old issues.

**Comment by jlerbsc** [comment]
This issue is already resolved.

**Comment by matozoid** [comment]
(side note: DumpVisitor is the old name of the PrettyPrintVisitor. Maybe it should have remained DumpVisitor because it is more of a quick dump than a well-configurable prettyprinter.)

**Comment by jlerbsc** [comment]
The problem is not reproducible in the current version with the test case used (see above). Maybe you can modify this unit test to reproduce the problem you are having.
