### ISSUE TITLE
NodeList - todo re: iterators

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2635]
There is a todo on the [NodeList#iterator](https://github.com/javaparser/javaparser/blob/8f25c40918feaf5f66af5fae5b23d271edefbdfc/javaparser-core/src/main/java/com/github/javaparser/ast/NodeList.java#L134-L138) method saying about handling `iterator.remove()`.

Reading into it `NodeList#add()` (and remove/set) is carefully used throughout the rest of the class to ensure that any modifications trigger the relevant observers, but doing modifications via the iterator (or listIterator) bypasses this - potentially leading to an inconsistent state.

https://github.com/javaparser/javaparser/blob/8f25c40918feaf5f66af5fae5b23d271edefbdfc/javaparser-core/src/main/java/com/github/javaparser/ast/NodeList.java#L134-L138

**Comment by 4everTheOne** [comment]
I think this issue might been already fixed with issue #2936.
https://github.com/javaparser/javaparser/blob/c579b8d1a9cb60db3babbe9384f514690fec13b8/javaparser-core/src/main/java/com/github/javaparser/ast/NodeList.java#L134-L138

Can you confirm if it's fixed @MysterAitch please? :)

**Comment by jlerbsc** [comment]
I am closing this issue as it appears to be identical to an issue that has been fixed.
