### ISSUE TITLE
Lexical Preservaton -- Injected code uses host's EOL not the source's

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2647]
Looks like @jlerbsc 's PR in #2646 fixes the issue described (thank you!), but it brings to the fore some other JavaParser behaviours that I am not sure are correct.

It seems that generated code is injected using the host's line endings. This is normally fine, but if the input text has a different line encoding then this leads to a source with mixed line endings. See the quoted post below, and the linked PR, for details.

https://github.com/javaparser/javaparser/pull/2646#issuecomment-623701912

> 
> 
> Digging deeper, @jlerbsc 's fix as given seems to work fine for fixing the problem presented in #2620 , but the tests fail due to the injected line endings not matching the parsed text.
> 
> For example if the parsed text has `\r\n` line endings, then on Ubuntu the host`s line endings (`\n`) are injected -- ONLY on the injected lines.
> 
> I am unsure if this is a separate bug / issue that should be handled separately, or if it should be handled as part of this.
> ### Ubuntu test failures
> 
> https://github.com/javaparser/javaparser/pull/2646/checks?check_run_id=644201141#step:6:1505
> _(line breaks / spacing added for clarity)_
> 
> ```
>  [ERROR] Failures: 
> [ERROR]   Issue2620Test.testWithCr:49->doTest:110 
> expected: <    public class Foo { //comment\r    private String newField;\r    \r    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
>  but was: <    public class Foo { //comment\r    private String newField;\n    \n    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
> 
> [ERROR]   Issue2620Test.testWithCrLf:59->doTest:110
>  expected: <    public class Foo { //comment\r\n    private String newField;\r\n    \r\n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
>  but was: <    public class Foo { //comment\r\n    private String newField;\n    \n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
> ```
> 
> ### Mac test failures
> 
> https://github.com/javaparser/javaparser/pull/2646/checks?check_run_id=644201231#step:6:1499
> _(line breaks / spacing added for clarity)_
> 
> ```
> [ERROR] Failures: 
> [ERROR]   Issue2620Test.testWithCr:49->doTest:110 
> 
> expected: <    public class Foo { //comment\r    private String newField;\r    \r    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
>  but was: <    public class Foo { //comment\r    private String newField;\n    \n    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
> 
> [ERROR]   Issue2620Test.testWithCrLf:59->doTest:110 
> expected: <    public class Foo { //comment\r\n    private String newField;\r\n    \r\n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
>  but was: <    public class Foo { //comment\r\n    private String newField;\n    \n    private String a;\r\n        private String b;\r\n        private String c;\r\n        private String d;\r\n    }>
> ```
> 
> ### Windows test failures
> 
> https://github.com/javaparser/javaparser/pull/2646/checks?check_run_id=644201340#step:6:1505
> _(line breaks / spacing added for clarity)_
> 
> ```
> [ERROR] Failures: 
> [ERROR]   Issue2620Test.testWithCr:49->doTest:110
> expected: <    public class Foo { //comment\r    private String newField;\r    \r    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
>  but was: <    public class Foo { //comment\r    private String newField;\r\n    \r\n    private String a;\r        private String b;\r        private String c;\r        private String d;\r    }>
> 
> [ERROR]   Issue2620Test.testWithLf:54->doTest:110 
> expected: <    public class Foo { //comment\n    private String newField;\n    \n    private String a;\n        private String b;\n        private String c;\n        private String d;\n    }>
>  but was: <    public class Foo { //comment\n    private String newField;\r\n    \r\n    private String a;\n        private String b;\n        private String c;\n        private String d;\n    }>
> ```

_Originally posted by @MysterAitch in https://github.com/javaparser/javaparser/issues/2620#issuecomment-623703521_

**Comment by MysterAitch** [comment]
The offending lines in the lexical preservation side of things appear to be in two locations:

https://github.com/javaparser/javaparser/blob/8f25c40918feaf5f66af5fae5b23d271edefbdfc/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinter.java#L144-L148

https://github.com/javaparser/javaparser/blob/8f25c40918feaf5f66af5fae5b23d271edefbdfc/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalDifferenceCalculator.java#L182-L185

**Comment by MysterAitch** [comment]
Perhaps this needs to be opened out more widely -- in what circumstances should we use the system's EOL versus maybe a detected EOL based on whatever was found inside it?

Maybe it could be as simple as logging a warning about mixed line endings being detected when doing parsing?

Not sure re: injection though.

**Comment by matozoid** [comment]
My idea: the lexical preserving printer should not be inserting EOL's at all and should be redesigned :-) For now it could be some configuration option that defaults to the system EOL, but that's not very satisfying... Also note that this printer currently has no configurable settings (I think.)

Using the EOL's in the input is indeed difficult if they are mixed. How are you going to determine which one is the correct one? Heuristics. Not very satisfying either...

**Comment by MysterAitch** [comment]
Merged in #2685 

> Using the EOL's in the input is indeed difficult if they are mixed. How are you going to determine which one is the correct one? Heuristics. Not very satisfying either...

If the input is unambiguously CR/LF/CRLF, then use that... otherwise default to the system's line separator for "new" code being injected.

As you say, this is less than ideal and there should probably be a warning or similar in this case. That can be added via another issue/PR though :+1: 

I'll add a couple more issues in a moment.
