### ISSUE TITLE
Infinite recursin on "java.lang.Object"

### ISSUE THREAD

**Issue by corradomio** [javaparser/javaparser#2669]
When the JDK is used with ""JarTypeSolver""  and not with a "ClassLoaderTypeSolver", there is a problem in the class **JavassistClassDeclaration**:

1) the method **getSuperClass()** generates a "StackOverflow" when it try to retrieve the superclass of `java.lang.Object`, because the superclass of `java.lang.Object` is itself.
It is possible to resolve adding and extra check:

```java
@Override
    public ResolvedReferenceType getSuperClass() {
        try {
            if ("java.lang.Object".equals(ctClass.getName())) {
                return null;
            }
            if (ctClass.getClassFile().getSuperclass() == null) ...
    }
```

It is necessary to modify also the method **solveMethod()** to consider that **getSuperClass()** can return null:

```java
@Override
    @Deprecated
    public SymbolReference<ResolvedMethodDeclaration> solveMethod(String name, List<ResolvedType> argumentsTypes, boolean staticOnly) {
        ...
        ResolvedReferenceType rrt = getSuperClass();
        if (rrt == null) {
            return SymbolReference.unsolved(ResolvedMethodDeclaration.class);
        }
        SymbolReference<ResolvedMethodDeclaration> superClassMethodRef =  ...
    }
```

**Comment by MysterAitch** [comment]
Really appreciate this report, thanks! 

I know that something similar was corrected recently - seems we missed the Javassist side of things.

Looks like this should be fairly straightforward to sort out given that you've been really helpful in pinning it down and providing a fix. 

The only comment I have at the moment is that returning null is something we aim to avoid, instead favouring returning optional (even where it leads to signature changes).

**Comment by corradomio** [comment]
Another method to correct (in the same class as before) is **getAncestors()**

```java
@Override
    public List<ResolvedReferenceType> getAncestors(boolean acceptIncompleteList) {
        List<ResolvedReferenceType> ancestors = new ArrayList<>();
        if (ctClass.getName().equals("java.lang.Object"))
            return ancestors;
```

**Comment by MysterAitch** [comment]
PR submitted..

I have just added many thoughts/comments, including a few thoughts/fixmes/todos that I didn't catch at the time of writing and need to go back to do...

@migliorabile -- if you have a moment, please do take a look through, but it should be included within the next release 

_(the next release should be before the end of the weekend, but I want to also convert `getTypeDeclaration()` to optional also so that users of JavaParser have only one release of API changes to deal with rather than several in a row)_

**Comment by corradomio** [comment]
Thanks a lot!
