### ISSUE TITLE
Parsing error: Encountered: "\ufeff" (65279), after : ""

### ISSUE THREAD

**Issue by JinyongPark** [javaparser/javaparser#267]
This is error logs)

XdbHelperForLotte.java

Exception in thread "main" com.github.javaparser.TokenMgrError: Lexical error at line 1, column 1.  Encountered: "\ufeff" (65279), after : ""
    at com.github.javaparser.ASTParserTokenManager.getNextToken(ASTParserTokenManager.java:2483)
    at com.github.javaparser.ASTParser.jj_scan_token(ASTParser.java:8931)
    at com.github.javaparser.ASTParser.jj_3R_213(ASTParser.java:8465)
    at com.github.javaparser.ASTParser.jj_3R_178(ASTParser.java:8521)
    at com.github.javaparser.ASTParser.jj_3R_123(ASTParser.java:8576)
    at com.github.javaparser.ASTParser.jj_3R_122(ASTParser.java:7040)
    at com.github.javaparser.ASTParser.jj_3R_72(ASTParser.java:7048)
    at com.github.javaparser.ASTParser.jj_3_1(ASTParser.java:7057)
    at com.github.javaparser.ASTParser.jj_2_1(ASTParser.java:5021)
    at com.github.javaparser.ASTParser.CompilationUnit(ASTParser.java:141)
    at com.github.javaparser.JavaParser.parse(JavaParser.java:112)
    at com.github.javaparser.JavaParser.parse(JavaParser.java:134)
    at com.util.JavaParsingUtil.dataConvertForExcel(JavaParsingUtil.java:24)
    at com.business.VisitProcess.visitFile(VisitProcess.java:48)
    at com.main.ProjectInfoPrint.main(ProjectInfoPrint.java:40)

This is the file I wanted to parse)

XdbHelperForLotte.java

package ec.site.shopping.common.etc;

import com.softforum.xdbe.*;

public class XdbHelperForLotte {
    public static XdbHelper xdb_jumin       = new XdbHelper();      //주민번호 정책
    public static XdbHelper xdb_card        = new XdbHelper();      //신용카드 정책
    public static XdbHelper xdb_account     = new XdbHelper();      //계좌번호 정책
    public static XdbHelper xdb_passport    = new XdbHelper();      //여권번호 정책
    public static XdbHelper xdb_temp_01     = new XdbHelper();      //여분의 정책01
    public static XdbHelper xdb_temp_02     = new XdbHelper();      //여분의 정책02

```
public static final int XDBHELPER_JUMIN_KEY     = 101;
public static final int XDBHELPER_CARD_KEY      = 102;
public static final int XDBHELPER_ACCOUNT_KEY   = 103;
public static final int XDBHELPER_PASSPORT_KEY  = 104;
public static final int XDBHELPER_XDB_TEMP_01   = 201;
public static final int XDBHELPER_XDB_TEMP_02   = 202;

/**
 * 일반 생성자
 */
public XdbHelperForLotte(){
    /*
        설정 암호화 모듈 구현 위치
    */
    try{
        if(!xdb_jumin.IsConnected()){
            xdb_jumin.Connect("pool1","DataEncrypt","lc_user","lc_object","pattern7_pn");
            xdb_card.Connect("pool1","DataEncrypt","lc_user","lc_object","pattern6_cc");
            xdb_account.Connect("pool1","DataEncrypt","lc_user","lc_object","alldata_acc");
            xdb_passport.Connect("pool1","DataEncrypt","lc_user","lc_object","alldata_pp");
        }
    }catch(Exception e){
        //로그 설정
    }
}

/**
 * 여분의 생성자 사용 모듈
 * @param arr 정책 서버 설정 파일
 * @param value 추가 정책 수
 */
public XdbHelperForLotte(String[][] arr, int value){
    /*
        설정 암호화 모듈 구현 위치
    */
    try{
        if(!xdb_jumin.IsConnected()){
            xdb_jumin.Connect("pool1","DataEncrypt","lc_user","lc_object","pattern7_pn");
            xdb_card.Connect("pool1","DataEncrypt","lc_user","lc_object","pattern6_cc");
            xdb_account.Connect("pool1","DataEncrypt","lc_user","lc_object","alldata_acc");
            xdb_passport.Connect("pool1","DataEncrypt","lc_user","lc_object","alldata_pp");
            if(value == 1){
                xdb_temp_01.Connect(arr[0][0], arr[0][1], arr[0][2], arr[0][3], arr[0][4]); //arr[0]부분은 설정 암호화 모듈 구현에 따라 바뀐다.
            }else if(value == 2){
                xdb_temp_01.Connect(arr[0][0], arr[0][1], arr[0][2], arr[0][3], arr[0][4]);
                xdb_temp_02.Connect(arr[1][0], arr[1][1], arr[1][2], arr[1][3], arr[1][4]);
            }
        }
    }catch(Exception e){
        //로그 설정
    }
}

/**
 * 복호화 method
 * @param encoding_text
 * @param key
 * @return 복호화된 문자열
 */
public static String decoding(String encoding_text, int key){
    String ret = "";

    switch (key) {
        case XDBHELPER_JUMIN_KEY:
            ret = xdb_jumin.Decrypt(encoding_text);
            break;
        case XDBHELPER_CARD_KEY:
            ret = xdb_card.Decrypt(encoding_text);
            break;
        case XDBHELPER_ACCOUNT_KEY:
            ret = xdb_account.Decrypt(encoding_text);
            break;
        case XDBHELPER_PASSPORT_KEY:
            ret = xdb_passport.Decrypt(encoding_text);
            break;
        case XDBHELPER_XDB_TEMP_01:
            ret = xdb_temp_01.Decrypt(encoding_text);
            break;
        case XDBHELPER_XDB_TEMP_02:
            ret = xdb_temp_02.Decrypt(encoding_text);
            break;  
        default:
            ret = encoding_text;
            break;
    }
    return ret;
}

/**
 * 암호화 method
 * @param decoding_text
 * @param key
 * @return 암호화된 문자열
 */
public static String encoding(String decoding_text, int key){
    String ret = "";

    switch (key) {
        case XDBHELPER_JUMIN_KEY:
            ret = xdb_jumin.Encrypt(decoding_text);
            break;
        case XDBHELPER_CARD_KEY:
            ret = xdb_card.Encrypt(decoding_text);
            break;
        case XDBHELPER_ACCOUNT_KEY:
            ret = xdb_account.Encrypt(decoding_text);
            break;
        case XDBHELPER_PASSPORT_KEY:
            ret = xdb_passport.Encrypt(decoding_text);
            break;
        case XDBHELPER_XDB_TEMP_01:
            ret = xdb_temp_01.Encrypt(decoding_text);
            break;
        case XDBHELPER_XDB_TEMP_02:
            ret = xdb_temp_02.Encrypt(decoding_text);
            break;
        default:
            ret = decoding_text;
            break;
    }
    return ret;
}
```

}

... what's problem... ?
sorry. I use English little a bit.. 
thank you

**Comment by asheiduk** [comment]
The message about `\ufeff` indicates, that your file has a byte order mark.

**Comment by matozoid** [comment]
Did you use a parse method without an "encoding" parameter, and are you running on Windows?

If that is true, use a parse method with encoding set to UTF-8.

**Comment by matozoid** [comment]
No response, closing. Please reopen if required.
