### ISSUE TITLE
Update LanguageLevel

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#2686]
LanguageLevel.CURRENT should be 14, and maybe Java 8 is not the most popular one anymore (but it probably still is.) Bleeding edge should be Java 15 then.

**Comment by MysterAitch** [comment]
Not sure how to label this. But yes. 

I can see that this will not necessarily affect the JavaParserConfiguration default as that is currently set to a specific version. Changing the config default perhaps warrants its own issue.

```java
    private LanguageLevel languageLevel = JAVA_8;
```

**Comment by matozoid** [comment]
Oh is it? I would have thought that would be set to the most popular.
