### ISSUE TITLE
TypeParameter misses out on setting itself as parent of its annotations

### ISSUE THREAD

**Issue by sebastiankirsch** [javaparser/javaparser#269]
As noticed by @ptitjes, TypeParameter has some minor issues due to not setting itself as parent at these spots:

Missing setAnnotations() call here: https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/TypeParameter.java#L73

Missing setAsParentNodeOf() call here: https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/TypeParameter.java#L132

**Comment by ptitjes** [comment]
thumbs-up
