### ISSUE TITLE
Lexical preservation not yet enabled on the generators

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2700]
Lexical preservation is currently disabled on the generators:

https://github.com/javaparser/javaparser/blob/dbea9d069ba0d6335f7285c3884ce84a07ff9db8/javaparser-core-generators/src/main/java/com/github/javaparser/generator/core/CoreGenerator.java#L43-L50

As it is, any generators that touch but do not modify a file leads to many unrelated changes.

There probably needs to be a better description than this :smile:

**Comment by matozoid** [comment]
It's not enabled because of bugs in the printer. Those may be gone now. (I think there is an older issue for this too)

**Comment by MysterAitch** [comment]
I did do a quick/lazy search for existing issues but didn't spot anything #oops

Do feel free to close this as a duplicate with a link if you have a link to hand! :) 

But yes, I'm currently trying to work through issues in the lexpres printer and wanted a separate issue to refer to. Might not come to anything if it ends up being too hard! :stuck_out_tongue_winking_eye:

**Comment by MysterAitch** [comment]
Ah yes, I now see #1301 -- closing this as a duplicate.
