### ISSUE TITLE
Improve naming of methods and classes

### ISSUE THREAD

**Issue by sharath2106** [javaparser/javaparser#2709]
Hi

While working on the issue - https://github.com/javaparser/javaparser/issues/2625

I've come across methods and classes which could've been named better. Screenshots attached.

Please let me know if I can also work on this. So that I can create a PR against this issue.

<img width="909" alt="Screenshot 2020-06-01 at 10 17 40 PM" src="https://user-images.githubusercontent.com/25933070/83431916-bab7bb00-a455-11ea-83e5-83662d41183c.png">
<img width="530" alt="Screenshot 2020-06-01 at 10 17 27 PM" src="https://user-images.githubusercontent.com/25933070/83431926-be4b4200-a455-11ea-84e2-85889d309352.png">

**Comment by MysterAitch** [comment]
Before making this change, which names are you looking to change and what would you suggest is an alternative?

As far as I can tell, `breakTarget` is used only once and that is within the same class it is defined (and that method `exitTheStatement` is never called at all?).

**Comment by sharath2106** [comment]
First, apologies for the delayed response as I was caught up with other items here. The change with respect to naming the class and methods is to improve the readability (which can be achieved just by spelling it better)

For example - 

BreakStmt can be renamed to BreakStatement
EnclosedExpr can be renamed to EnclosedExpression

<img width="346" alt="Screenshot 2020-06-04 at 8 37 36 AM" src="https://user-images.githubusercontent.com/25933070/83710602-ca462800-a63e-11ea-9fed-49ae5bc4abc7.png">
<img width="534" alt="Screenshot 2020-06-04 at 8 34 41 AM" src="https://user-images.githubusercontent.com/25933070/83710613-ce724580-a63e-11ea-9de8-4b357cb6d19c.png">
<img width="377" alt="Screenshot 2020-06-04 at 8 32 36 AM" src="https://user-images.githubusercontent.com/25933070/83710618-cf0adc00-a63e-11ea-800e-cb473d13cb22.png">

**Comment by MysterAitch** [comment]
> First, apologies for the delayed response as I was caught up with other items here.

All good! 

One of the things we strongly encourage is that contributing to open source should be fun (or, at least, not a chore or annoyance!).

That, and your "real life" comes first -- i.e. family and school and work that pays the bills!


> The change with respect to naming the class and methods is to improve the readability (which can be achieved just by spelling it better)
> 
> For example - 
> 
> BreakStmt can be renamed to BreakStatement
> EnclosedExpr can be renamed to EnclosedExpression
> 
> <img width="346" alt="Screenshot 2020-06-04 at 8 37 36 AM" src="https://user-images.githubusercontent.com/25933070/83710602-ca462800-a63e-11ea-9fed-49ae5bc4abc7.png">
> <img width="534" alt="Screenshot 2020-06-04 at 8 34 41 AM" src="https://user-images.githubusercontent.com/25933070/83710613-ce724580-a63e-11ea-9de8-4b357cb6d19c.png">
> <img width="377" alt="Screenshot 2020-06-04 at 8 32 36 AM" src="https://user-images.githubusercontent.com/25933070/83710618-cf0adc00-a63e-11ea-800e-cb473d13cb22.png">
> 
> 


These changes affect the public API of the program -- this means that this would be a breaking change for users of JavaParser! 

Breaking the public API means that existing documentation and articles and demo code and, perhaps most importantly, code written by users of the library, will no longer function correctly.

This isn't something that should be done lightly.

---

The other aspect to consider is that `Expr` and `Stmt` are common suffixes in the world of parsing. 

While I do suspect that it might make things more intuitive for new users and users whose first language doesn't uses these common abbreviations, and I do wholeheartedly agree that using full words is generally better, a PR to change only class/interface names stmt-statement and expr-expression isn't something that will be accepted soon (maybe as a larger overhaul of the library or among other substantial breaking changes).

---

Note: If these were non-public details/components, then we can be a bit more liberal with name changes (e.g. local variables/parameters, or private (and maybe protected) methods/classes/enums).

For example -- `diffElements` in your screenshot could be renamed to `differenceElements`.

**Comment by sharath2106** [comment]
> These changes affect the public API of the program -- this means that this would be a breaking change for users of JavaParser!
> Breaking the public API means that existing documentation and articles and demo code and, perhaps most importantly, code written by users of the library, will no longer function correctly.
> This isn't something that should be done lightly.
> The other aspect to consider is that Expr and Stmt are common suffixes in the world of parsing.
> While I do suspect that it might make things more intuitive for new users and users whose first language doesn't uses these common abbreviations, and I do wholeheartedly agree that using full words is generally better, a PR to change only class/interface names stmt-statement and expr-expression isn't something that will be accepted soon (maybe as a larger overhaul of the library or among other substantial breaking changes).

I agree with your point here. And yes, it is not an easy task to make this change. Reason for me raising the issue is because of the readability. Maybe we can make this change at a later point of time. 

> Note: If these were non-public details/components, then we can be a bit more liberal with name changes (e.g. local variables/parameters, or private (and maybe protected) methods/classes/enums).
> For example -- diffElements in your screenshot could be renamed to differenceElements.

So, should I go ahead and rename this?

**Comment by MysterAitch** [comment]
> 
> > Note: If these were non-public details/components, then we can be a bit more liberal with name changes (e.g. local variables/parameters, or private (and maybe protected) methods/classes/enums).
> > For example -- diffElements in your screenshot could be renamed to differenceElements.
> 
> So, should I go ahead and rename this? 

Completely up to you!

Personally I have no strong feelings either way given that "diff" is an extremely common shortened version of "difference", but would welcome it it as a first time PR to get the ball rolling as a contributor 😊

**Comment by jlerbsc** [comment]
I'm closing this issue because not only could these changes affect the entire community using JP, but also because these changes add little value to JP.
