### ISSUE TITLE
TypedNode Interface with getType/setType

### ISSUE THREAD

**Issue by LunNova** [javaparser/javaparser#271]
Could we get a TypedNode interface?

It would be implemented by all nodes which have getType/setType methods.

```
void setType(Type t);
Type getType();
```

I'm trying to remap types in some code, currently this requires either a large number of instanceof checks, casts and code duplication or costly/slow reflection as there is no interface implemented by everything which has a Type.

If this feature request makes sense/is approved I can make a PR for it.

**Comment by ftomassetti** [comment]
I am in favor of this kind of interfaces: we introduced a few liked the NamedNode and we had a shot at the NodeWithModifiers interface. I agree they helped a lot in processing code.

**Comment by matozoid** [comment]
Sounds like something that should have been there already :) If more methods-that-should-have-been-part-of-a-type are known, please open issues for those too.

Go ahead and submit a PR.

**Comment by LunNova** [comment]
Changed the name to TypedNode as that seemed more consistent with NamedNode which @ftomassetti mentioned.

**Comment by thejohnfreeman** [comment]
Can this be closed?

**Comment by ftomassetti** [comment]
Yes, it makes sense to close this one. Thanks @thejohnfreeman
