### ISSUE TITLE
should I compile a java project before analyse it.

### ISSUE THREAD

**Issue by for-just-we** [javaparser/javaparser#2725]
create a test maven project. define 3 classes foo, foo1, foo2  without compile.  
the code of foo is

```java
   public class foo {
        public foo1 getFoo1(){
            return new foo1();
        }

    public foo2 getFoo2(){
        return new foo2();
    }

    public static void main(String[] args){
        foo f = new foo();
        foo1 f1 = f.getFoo1();
        foo2 f2 = f.getFoo2();
    }
}
```

And I analyse it with code

```java

CombinedTypeSolver typeSolver = new CombinedTypeSolver(
                new JavaParserTypeSolver(new File("/home/prophe/projects/java/staticAnalysis/test/simpleTest")));


        CopilationUnit agendaCu = StaticJavaParser
               .parse(new FileInputStream(
                       new File("/home/prophe/projects/java/staticAnalysis/test/simpleTest/src/main/java/com/example/foo.java")));
        agendaCu.accept(new TimeJavaApi(), JavaParserFacade.get(typeSolver));
```

**`/home/prophe/projects/java/staticAnalysis/test/simpleTest`** is the path of the maven project.

There is always **`UnsolvedSymbolException{context='null', name='foo1', cause='null'}`**

And I don't know what the problem is

**Comment by jlerbsc** [comment]
Hi for-just-we, below is a late answer to your question which may possibly help other people.
First you cannot parse a project with compilation errors.
Second JavaParserTypeSolver must be initialized with java source folder (in your case  /home/prophe/projects/java).

**Comment by MysterAitch** [comment]
Hi @for-just-we -- if you still have questions, please do post a reply either here or in a new issue :) :+1:
