### ISSUE TITLE
RuntimeException is thrown when resolving variable used inside case statement, because not existing method is called after switch 

### ISSUE THREAD

**Issue by poxu** [javaparser/javaparser#2734]
I have this small code snippet 
```java
public class MyService {
    public int getResult(MyDto dto) {
        ResultDto result = new ResultDto();
        switch (dto.getNumber()) {
            case 1:
                result.getNumber();
                return 2;
        }
        return 2;
    }
}

```

I am looking for all method calls and then try to resolve first child node of method call, which is the object containing the method.
It works for dto.getNumber() , but for the second method call **result.getNumber()** result variable can not be resoved.

What is also weird is that RuntimeException is generated instead of UnsolvedSymbolException. And error message says that dto.getNumber() method could not be resolved, not **result** variable.
MyDto.getNumber() method does not exist, so JavaParser wouldn't be able to resolve it, but as far as I understand my code shouldn't try to resolve methods, only variables.

I have loaded my snippet to github repository https://github.com/poxu/java-parser-bug-demo . Just look at com.evilcorp.Main . The code to reproduce the issue is there . Lombok is used to demonstrate how such an issue could occur in a real project.

**Comment by jlerbsc** [comment]
This issue seems to have been corrected in the current version of JP.
