### ISSUE TITLE
Generation. Print. Avoid fully qualitfied names.

### ISSUE THREAD

**Issue by DmitriZamysloff** [javaparser/javaparser#2736]
Hi,
Javaparser is very interesting.  Thank you for your engagement. 

Im my generator I am defining Names of classes with qualifiers. These I use in compilation unit to define import statements. And the same Names I want to be able to use in Field declarations, Generic types, etc. Everything is fine, but by printing the compilation unit out I am getting over all full qualified names. How can I control this? Is it possible to avoid full qualified names after output of imports?

thank you.

**Comment by jlerbsc** [comment]
Hi DmitriZamysloff, I think you have to modify the variable or parameter type by yourself. Below an exemple

    @Test
    void test() {
        // original code
        String code = 
                "class A {" +
                "  void m1(b.Z z) {" +
                "    System.out.println(b.Z.z);" +
                "  }" +
                "}";
      
        CompilationUnit cu = StaticJavaParser.parse(code);
        LexicalPreservingPrinter.setup(cu);
        System.out.println(LexicalPreservingPrinter.print(cu));
        // creates an import declaration
        String importDecl = "b.Z";
        ImportDeclaration id = new ImportDeclaration(importDecl, false, false);
        cu.getImports().add(id);
        // modifies the parameter type 
        MethodDeclaration md = cu.findFirst(MethodDeclaration.class).get();
        md.getParameters().forEach(p -> {
            if (importDecl.equals(p.getTypeAsString())) {
                String type = importDecl.substring(importDecl.lastIndexOf(".")+1);
                p.setType(type);
            }
        });
        // prints the new compilation unit
        System.out.println(LexicalPreservingPrinter.print(cu));
    }

returns

    class A {  void m1(b.Z z) {    System.out.println(b.Z.z);  }}
    import b.Z;

    class A {  void m1(Z z) {    System.out.println(b.Z.z);  }}

**Comment by jlerbsc** [comment]
This issue hasn't been active for several months, so I assume that the answer solved the problem.
