### ISSUE TITLE
UnsolvedSymbolException while trying to ResolvedMethodDeclaration from MethodCallExpr

### ISSUE THREAD

**Issue by SunilDC** [javaparser/javaparser#2738]
Hello,

I am trying to fetch method callers. In that i have a case with method overloaded.
I need to check the arguments type to identify the respective methods. So i am calling `resolve()` method from `MethodCallExpr`.
I am facing `UnsolvedSymbolException` while executing `resolve()` method. Please find the below code snap.
Please help me to solve the issue.

JavaParser Configuration:
------------------------------------------
```java
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver());
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
CompilationUnit parsingResult = StaticJavaParser.parse(filePath);
```

Exception @ below line:
-----------------------------------------
```java
ResolvedMethodDeclaration resolve = mCallExp.resolve();**
```

Thank you.

**Comment by jlerbsc** [comment]
Hi SunilDC could you give us a full test case please because extract cannot help us to find any issue?

**Comment by SunilDC** [comment]
Hello @jlerbsc , 

Thanks for your replay.
I have use case to fetch call hierarchy of selected method from a class. Here I have use case that class having overloaded methods with different types(sub type). I need to retrieve exact method getting called. Please find the below test case:

Class A{
//Method1
B(Type1 arg1)
{
}

//Method2 overloaded and Type2 is sub type of Type1
B(Type2 arg2)
{
}
}

TestClass
{
//calling above method
B(arg)
}

Now I wanted to check arg is of which type (Type1 or Type2)

I have MethodCallExpr object where I can see typeargument is null. So I am trying to use ResolvedMethodDeclaration to resolve the type symbols using resolve() method. This methods throws UnsolvedSymbolException. 
Here i wanted to check the types of the argument so that i can identify the methods which is getting called.
Please help me to figure out the issue. Do i need to configure any other typesolver? Please let me know.

Regards,
Sunil D C

**Comment by jlerbsc** [comment]
Could you provide a runnable test case please because the test case below don't reproduce this issue.

    @BeforeEach
    void setUp() {
        TypeSolver typeSolver = new ReflectionTypeSolver();
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(config);
    }
    
    @Test
    void test() {
        String code = 
                "class A {" +
                "  void a(Object o) {" +
                "  }" +
                "  void a(String s) {" +
                "  }" +
                "  void c() {" +
                "    a(\"\");" +
                "  }" +
                "}";
      
        CompilationUnit cu = StaticJavaParser.parse(code);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        ResolvedMethodDeclaration resolve = mce.resolve();

        System.out.println(resolve.getQualifiedSignature());
    }

In this case the qualified signature is 

    A.a(java.lang.String)

**Comment by jlerbsc** [comment]
Hi @SunilDC do classes A and B (in your exemple) belong to different libraries? have you resolved this issue?

**Comment by audreyseo** [comment]
Hello, I think I have the exact same problem as @SunilDC. Here are two test classes, which I minimized a lot (originally the type parameter `C` in class `B` also extended `Comparable<C>`. It is actually necessary though for the type parameter `K` to extend `Comparable<C>` to reproduce the bug, at least on my end.)


```
// file name: exposeBug/org/A.java
package org;

public class A<K extends Comparable<K>> {
    private void doNothing() {
        System.out.println("Doing nothing.");
    }

    public int getIndex(K key) {
        return 0;
    }
}
```

```
// file name: exposeBug/org/B.java
package org;

public class B<C> {
    private A<C> aC;
    private C myC;

    public void getValue(int row, int column) {
        aC.doNothing();
        aC.getIndex(myC);
    }

}
```

Here is the code that I was running that exposes the bug (imports omitted, though I can provide them if that would be helpful):

```
public class ExposeBug {
    public static void main(String[] args) throws FileNotFoundException {
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("exposeBug"));
        ArrayList<String> fileNames = new ArrayList<>();
        fileNames.add("exposeBug/org/A.java");
        fileNames.add("exposeBug/org/B.java");

        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();
        combinedSolver.add(reflectionTypeSolver);
        combinedSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);

        StaticJavaParser.getConfiguration()
                        .setSymbolResolver(symbolSolver);
        for (String fileName : fileNames) {
            CompilationUnit cu = StaticJavaParser.parse(new File(fileName));
            cu.findAll(MethodCallExpr.class)
              .forEach(
                      mce -> {
                          try {
                              System.out.println(mce.resolve().getQualifiedSignature());
                          } catch (UnsolvedSymbolException e) {
                              System.out.println(e.getMessage());
                              e.printStackTrace();
                          }
                      }
              );
        }
    }
}
```

Here is the output:

```
java.io.PrintStream.println(java.lang.String)
org.A.doNothing()
Unsolved symbol : We are unable to find the method declaration corresponding to aC.getIndex(myC)
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to aC.getIndex(myC)', cause='null'}
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:167)
        at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:316)
        at org.codemap.parser.Explore.lambda$main$0(Explore.java:40)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.codemap.parser.Explore.main(Explore.java:37)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

The expected output however is

```
java.io.PrintStream.println(java.lang.String)
org.A.doNothing()
org.A.getIndex(K)
```

Oddly enough, it can resolve `getIndex` if `K` does not extend `Comparable`, and it is obvious that it is finding the class `org.A` since it is able to resolve `org.A.doNothing()`.

**Comment by audreyseo** [comment]
(Pinging @jlerbsc just in case, since I know this is a bit of an old issue.)

**Comment by audreyseo** [comment]
Hmm, on re-reading @SunilDC's original posts, perhaps my issue is a bit different since it has nothing to do with subclassing and overriding methods, and instead seems a little bit more related to type parameters that need to be superclasses of some other type. If need be, I can submit another issue.

**Comment by jlerbsc** [comment]
@audreyseo we do not have enough information to know if the 2 cases are identical or not. In the absence of a real test from @SunilDC case we will assume that these are the same problems. However your example does not compile but perhaps you would write that (see type parameter in class B).

    public class A<K extends Comparable<K>> {
        public void doNothing() {
            System.out.println("Doing nothing.");
        }
        public int getIndex(K key) {
            return 0;
        }
    }
    
    public class B<**C extends Comparable<C>**> {
        private A<C> aC;
        private C myC;

        public void getValue(int row, int column) {
            aC.doNothing();
            aC.getIndex(myC);
        }
    }


Bellow an custom test case 

    @Test
    void test() throws IOException {
        ParserConfiguration config = new ParserConfiguration();
        Path pathToSourceFile = adaptPath("src/test/resources/issue2738");
        Path root = classLoaderRoot(this.getClass()).resolve("../..").resolve(pathToSourceFile).normalize();
        TypeSolver cts = new CombinedTypeSolver(
                new ReflectionTypeSolver(),
                new JavaParserTypeSolver(pathToSourceFile));
        config.setSymbolResolver(new JavaSymbolSolver(cts));
        SymbolSolverCollectionStrategy symbolSolverCollectionStrategy = new SymbolSolverCollectionStrategy(config);
        ProjectRoot projectRoot = symbolSolverCollectionStrategy.collect(root);
        List<SourceRoot> sourceRoots = projectRoot.getSourceRoots();
        for (SourceRoot sourceRoot : sourceRoots) {
            sourceRoot.tryToParse("");
            List<CompilationUnit> compilationUnits = sourceRoot.getCompilationUnits();
            for (CompilationUnit cu : compilationUnits) {
                cu.findAll(MethodCallExpr.class)
                        .forEach(
                                mce -> {
                                    try {
                                        System.out.println(mce.resolve().getQualifiedSignature());
                                    } catch (UnsolvedSymbolException e) {
                                        System.out.println(e.getMessage());
                                        e.printStackTrace();
                                    }
                                });
            }
        }
    }

**Comment by jlerbsc** [comment]
@maartenc @MysterAitch i think this issue is caused by the fact that when determining whether one ResolvedTypeVariable is assignable by another, JP compares the name of the variable types. In the example it compares K and C instead of comparing, in the case of an upper bounded type, the types of the variables (here Comparable). But I am not sure of my analysis.

**Comment by singhstronaut** [comment]
Here's the working code to resolve `UnsolvedSymbolException` with javaparser v3.27.1 :

```
// false in constructor will solve UnsolvedSymbolException exception for jdk classes.
// because by default true only includes jre classes and not all classes.
TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);

CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(reflectionTypeSolver);

// jarsPath will have all jars 'fully qualified names' to resolve UnsolvedSymbolException for the classes reported.
for (String jarPath : jarsPath) {
	combinedTypeSolver.add(new JarTypeSolver(jarPath));
}

JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
```

**Comment by jlerbsc** [comment]
@singhstronaut  Why are you commenting on an issue that is closed and resolved?
