### ISSUE TITLE
Rename FieldAccessExpr (was: Incorrect type)

### ISSUE THREAD

**Issue by samczsun** [javaparser/javaparser#274]
The following code:

`this.value = java.util.Arrays.copyOfRange(a, i, i + i0);`

Will give AST which states that

`java.util.Arrays`

is a FieldAccessExpr

**Comment by ftomassetti** [comment]
Well, at the parser level there is no way to know that Arrays is a class and java.util is a package. So I guess this is the best you can do while parsing.

**Comment by samczsun** [comment]
Fair enough. Do you think there's a good way of letting users know that FieldAccessExpr might also be used for FQN? It threw me off for a bit because I was wondering why some of the parsed code wasn't being handled

**Comment by ftomassetti** [comment]
Perhaps we should come up with a better name. Do you have suggestions on this?

**Comment by samczsun** [comment]
Unfortunately, I can't think of any good names to call it. I'll keep thinking about it though.

**Comment by matozoid** [comment]
What are our thoughts now?

**Comment by matozoid** [comment]
No response, this stays as it is.
