### ISSUE TITLE
bug MethodCallExpr exception

### ISSUE THREAD

**Issue by MornSunShine** [javaparser/javaparser#2740]
```java
private void getBackupsFromDrive(DriveFolder folder) {
        Query query = new Query.Builder().build();
        folder.queryChildren(mGoogleApiClient, query)
                .setResultCallback(new ResultCallback<DriveApi.MetadataBufferResult>() {
                    private ArrayList<Integer> t = new ArrayList<>();

                    @Override
                    public void onResult(@NonNull DriveApi.MetadataBufferResult result) {
                        t.add(10);
                    }
                });
    }
```

above on, when solve code `t.add(10)`, with `JavaParserFacade.get(typeSolver).solve(callExpr9);` exception will be thrown, like

```
UnsolvedSymbolException{context='t', name='Solving t', cause='null'}.
```
If I make some adjustment, it will be successful. like the following,

```java
public void onResult(@NonNull DriveApi.MetadataBufferResult result) {
  ArrayList<Integer> t = new ArrayList<>();
  t.add(10);
}
```

I think it is bug

**Comment by MornSunShine** [comment]
Maybe, new fields declared in the anonymous class are rare, and anonymous class is corresponded to ObjectCreationExpr, However, the search of declaration is ignored.

**Comment by MornSunShine** [comment]
I fix the bug in the source code. 
For the following test code,
```
        folder.queryChildren(mGoogleApiClient, query)
                .setResultCallback(new ResultCallback<DriveApi.MetadataBufferResult>() {
                    private ArrayList<Integer> t = new ArrayList<>();

                    @Override
                    public void onResult(@NonNull DriveApi.MetadataBufferResult result) {
//                        ArrayList<Integer> t = new ArrayList<>();
                        t.add(10);
                    }

                });
```
The access identifier of variable 't' is private. However, in the method, com.github.javaparser.symbolsolver.javaparsermodel.contexts.AnonymousClassDeclarationContext.solveSymbol(String name), 
```
    if (myDeclaration.hasVisibleField(name)) {
      return SymbolReference.solved(myDeclaration.getVisibleField(name));
    }
```
I correct it as
```
    if (myDeclaration.hasField(name)) {
      return SymbolReference.solved(myDeclaration.getField(name));
    }
```

**Comment by jlerbsc** [comment]
Hi @MornSunShine This issue  is reproducible with the following test case and the proposed modification solve it. But the PR does a lot of things whose seem to not be directly related to this issue. Perhaps you can open a new issue for others problems and give us a simple test case. 

    @Test()
    void test() {
        String code =
                "import java.util.function.Consumer;\n" + 
                "import java.util.ArrayList;\n" + 
                "\n" + 
                "public class A {\n" + 
                "    \n" + 
                "    void m() {\n" + 
                "        new Consumer<String>() {\n" + 
                "            private ArrayList<Integer> t = new ArrayList<>();\n" + 
                "            @Override\n" + 
                "            public void accept(String s) {\n" + 
                "                t.add(s);\n" + 
                "            }\n" + 
                "            \n" + 
                "        };" + 
                "    }\n" + 
                "\n" + 
                "}";

        
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(code);
        List<MethodCallExpr> methodCallExpr = cu.findAll(MethodCallExpr.class);
        for (MethodCallExpr expr : methodCallExpr) {
            System.out.println("trying to solde " + expr.toString());
            ResolvedMethodDeclaration rd = expr.resolve();
            System.out.println(String.format("%s solved to %s", expr.toString(), rd.getQualifiedSignature()));
        }
    }
