### ISSUE TITLE
How can I use the DifferenceElementCalculator class which is not visible in JavaParser?

### ISSUE THREAD

**Issue by DehengYang** [javaparser/javaparser#2741]
Dear authors,

Sorry for interrupting you with this issue. I am trying to parse the Java file and obtain the differences between two Nodes using JavaParser. However, when obtaining the differences between Nodes, the DifferenceElementCalculator class, which is seemingly able to deal with this case, is not visible. Therefore, I would like to ask that if there is any solution for using the **DifferenceElementCalculator** class and to obtain such aforementioned differences.

Thank you in advance for your time and help.

**Comment by MornSunShine** [comment]
Reflection may help you. The technology makes methods or classes which are private be accessed as the public.

**Comment by jlerbsc** [comment]
DifferenceElementCalculator has a default visibility you cannot use it directly. To obtain difference between 2 nodes you can, for exemple, compare string representation of the 2 nodes with the org.apache.commons.text.diff.StringsComparator library. I'm not sure javaparser provides this functionality.

**Comment by DehengYang** [comment]
@jlerbsc Thank you so much for the suggestion. I may first use org.apache.commons.text.diff.StringsComparator to get the textDiff between 2 nodes, and then transfrom it into the corresponding astNodeDiff that I actually need. 

@MornSunShine Thank you very much for the help. Next, I plan to 1) figure out the usage of DifferenceElementCalculator  via debugging the javaparser in IDE; 2) if the DifferenceElementCalculator cannot calculate the astNodeDiff between nodes, maybe I will fork the JavaParser and try to implement such feature. But this feature will require many modifications involving  mulitple classes of JavaParser, I suppose.

**Comment by jlerbsc** [comment]
@DehengYang Did this answer answer your question? if yes maybe you can close the issue?

**Comment by DehengYang** [comment]
Thank you for your help. I did not find the function I want in JavaParser and I started to revise JavaParser to obtain the diff between two nodes, and I am still working on this. Thank you!
