### ISSUE TITLE
How can I judge which class a method belongs to when I use [methodcallexpr]

### ISSUE THREAD

**Issue by 2625180201** [javaparser/javaparser#2742]
How can I judge which class a method belongs to when I use [methodcallexpr] to call methods of other classes in the current class. Eg:

class X { public static int x() { return 1 + 1.0 - 5; } }

class Y { int y() { return x(); } }

How do I know that x () is a method of X when parsing y class.

**Comment by jlerbsc** [comment]
This test case doesn't compile.

    class X { public static int x() { return 1 + 1 - 5; } }

    class Y { int y() { return X.x(); } }

X is the scope of your method call expression. You can resolve the scope.

    ResolvedType rt = mce.getScope().get().calculateResolvedType();
    System.out.println(rt.asReferenceType().getQualifiedName());

**Comment by jlerbsc** [comment]
Hi @2625180201 Did this answer help you? If yes could you close this issue please?
