### ISSUE TITLE
A problem of code encapsulation

### ISSUE THREAD

**Issue by 2625180201** [javaparser/javaparser#2748]
before:
 public static String getV4IP() {
        String ip = "";
        ip="xxx";
        ip="aaa";
       return ip;
    }
after:
 public static String getV4IP() {
        String ip = "";
       doSome(ip);
       return ip;
    }
public static void doSome(String ip){
        ip="xxx";
        ip="aaa";
        return ip;
}
When I split code, how do I know which blocks of code I split need to be passed into the new method?

**Comment by jlerbsc** [comment]
This is not an issue related to javaparser or symbol solver!

**Comment by jlerbsc** [comment]
Hi @2625180201, your sample doesn't work as excpected because String are immutable. 
Your question does not highlight a problem with the javaparser project, perhaps it would be more efficient to post your question on another site stackoverflow?
