### ISSUE TITLE
Generated XML contains duplicated "type" attribute

### ISSUE THREAD

**Issue by michaelhkay** [javaparser/javaparser#2750]
The source code fragment

`protected int xsdVersion = XSD11;`

results in the XML output

`<variable type='VariableDeclarator'><initializer type='NameExpr'><name type='SimpleName' identifier='XSD11'></name></initializer><name type='SimpleName' identifier='xsdVersion'></name><type type='PrimitiveType' type='INT'></type></variable>`

which is invalid because the `type` element has two `type` attributes.

**Comment by michaelhkay** [comment]
Obvious fix is to use a different attribute name for the node type, one that isn't going to be used elsewhere, e.g.

```
        if (outputNodeType) {
            builder.append(attribute("nodeType", metaModel.getTypeName()));
        }
```

But I don't know enough about the project to know how you manage the backwards compatibility issues. The bug is so basic that it's hard to believe anyone is actually using this code.

**Comment by jlerbsc** [comment]
This issue seems to have been corrected in the current version, as the result is now

<type type="INT"></type>
