### ISSUE TITLE
How to resolve method calls from a standard library (jre)

### ISSUE THREAD

**Issue by Aupateli** [javaparser/javaparser#2753]
Hi all,  this is really a powerful parser.

I want to resolve method calls from a standard library like **java.lang.Object**. But I don't have the source code of java standard library, I cannot resolve method calls like what you do in the JAVAPARSER:VISITED book:

`CompilationUnit cu = StaticJavaParser.parse(new File(FILE_PATH));`
`cu.findAll(MethodCallExpr.class).forEach(mce -> ...(mce.resolveInvokedMethod().getQualifiedSignature()));`

Is there anyway to resolve method calls from a standard library?

**Comment by jlerbsc** [comment]
Hi @Aupateli, you have to setup the solver (see chapters How to setup the JavaSymbolSolver? ou Resolving a type using an absolute name)

**Comment by jlerbsc** [comment]
Hi @Aupateli, you don't need to have the source code of the java standard library . All you have to do is to setup the JavaSymbolSolver . This is an example of how you can do it.

     public void test() {
        String actual = 
                "public class Foo{\n" + 
                "    public void m(Object o){\n" + 
                "        o.toString();\n" + 
                "    }\n" + 
                "}";
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver());

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(actual);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        System.out.println(mce.resolve().toString());
    }
