### ISSUE TITLE
Not Getting a (Javadoc) Comment for a particular Class, Interface or Method ?

### ISSUE THREAD

**Issue by waqas19921** [javaparser/javaparser#276]
Please help can not get javaDoc comment through getJavaDoc() method for class or interface declaration and method declaration.

**Comment by SmiddyPence** [comment]
Hi @waqas19921, can you include some sample code so we can try and reproduce the issue.

**Comment by waqas19921** [comment]
```
CompilationUnit cu = JavaParser.parse(in);
    private static class ClassVisitor extends VoidVisitorAdapter<Object> {

        @Override
        public void visit(CompilationUnit n, Object arg) {
            for (TypeDeclaration type : n.getTypes()) {
                if (type instanceof ClassOrInterfaceDeclaration) {
                    this.visit((ClassOrInterfaceDeclaration) type, arg);
                }
            }
        }

        @Override
        public void visit(ClassOrInterfaceDeclaration n, Object arg) {
            System.out.println("Class : "+ n.getName() + "Java Doc Comment: ");
            System.out.println(n.getJavaDoc());
            System.out.println("------------------------");

            if (n.getMembers() != null) {
                for (final BodyDeclaration member : n.getMembers()) {
                    member.accept(this, null);
                }
            }
        }

        @Override
        public void visit(MethodDeclaration n, Object arg) {
            System.out.println("Function "+ n.getName() +"Java Doc Comment: ");
            System.out.println(n.getJavaDoc());
            System.out.println("------------------------");

        }
}
```

**Comment by waqas19921** [comment]
if i run this than null pointer exceptions occur on function getJavaDoc()

**Comment by ftomassetti** [comment]
Does it occur on the invocation or inside the invocation? In other words, does it happen because _n_ is null or does it occur inside _getJavaDoc_? Could you please report the stacktrace?

In the meantime I mark this one as a bug for precaution, so we will keep an eye on it.

**Comment by jhrldev** [comment]
Probably inside of getJavaDoc.
Obs: He calls n.getName, but NPE occurs only when he calls getJavaDoc

**Comment by waqas19921** [comment]
Obs : n is null that means no javadoc is stored when parsing occurs

**Comment by ndimitry** [comment]
I was also not able to get javadoc to method. Comment to method like /*\* text */ is parsed as a comment, not a javadoc.
Also if method is annotated comments are not parsed at all (I will add more info further)

**Comment by ndimitry** [comment]
Found issue, creating a new one (because it is a separate thing)

**Comment by ftomassetti** [comment]
You gave us the code you used to parse but I think that also an example of the code being parsed would be useful

**Comment by matozoid** [comment]
This is fixed on master.
