### ISSUE TITLE
How do I get line information of class and methods?

### ISSUE THREAD

**Issue by vjjangid** [javaparser/javaparser#2760]
I am writing code for getting line details of all the classes and functions in given java code file.
Line number here means from which line number class is declared and  on which line number its definition is completed in text editor.
Can it be done using javaparser?

**Comment by vinaysshenoy** [comment]
@vjjangid I am attempting to do something similar. Where you able to figure out how to do this using javaparser?

**Comment by jlerbsc** [comment]
You can call getRange() on each Node. A range is defined with begin position and end position attributes. Each position defines line and column attributes.

**Comment by vinaysshenoy** [comment]
> You can call getRange() on each Node. A range is defined with begin position and and position attributes. Each position defines line and column attributes.

Thank you for the reply! I was able to solve by problem by searching Github issues and found what I needed in https://github.com/javaparser/javaparser/issues/1373.
