### ISSUE TITLE
UnsupportedOperationException when resolving symbol inside for statement initialization

### ISSUE THREAD

**Issue by jmflorezff** [javaparser/javaparser#2764]
I am getting an exception when resolving a `NameExpr` inside of a `UnaryExpr` inside of a for statement initialization. See the following example (resolving name expression `e`):

```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.UnaryExpr;
import com.github.javaparser.resolution.declarations.ResolvedValueDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class UnaryExpForStmt {
    public static void main(String[] args) {
        JavaParser parser = new JavaParser(
                 new ParserConfiguration().setSymbolResolver(
                      new JavaSymbolSolver(new ReflectionTypeSolver(true))));

        CompilationUnit res = parser.parse("class A {" +
                "void a() {" +
                "int e; for(e++;;){}" +
                "} }")
                .getResult()
                .get();

        NameExpr name = (NameExpr) res.findFirst(UnaryExpr.class)
                .get()
                .getExpression();
        ResolvedValueDeclaration resolve = name.resolve();

        System.out.println(resolve);
    }
}
```

The error is explicitly caused by [this line](https://github.com/javaparser/javaparser/blob/6b9344dcd41302a1e81d8ff55baa8f8ff43dc5e6/javaparser-symbol-solver-testing/src/test/test_sourcecode/javasymbolsolver_0_6_0/src/java-symbol-solver-core/com/github/javaparser/symbolsolver/javaparsermodel/contexts/ForStatementContext.java#L53) in `ForStatementContext`.

I think it is reasonable to expect this to be resolved, and it could be easily done by delegating to the parent context. Is this an oversight or am I missing something?

**Comment by jlerbsc** [comment]
This issue is fixed. Thank you for taking the time to report this case.

**Comment by MysterAitch** [comment]
Just a heads up that my IDE complained about `e` not being initialised, but that is unrelated to parsing/solving here. 

Thank you @jlerbsc for the fix!
