### ISSUE TITLE
RuntimeException when resolving MethodCallExpr 

### ISSUE THREAD

**Issue by zhizhixiongxuwei** [javaparser/javaparser#2767]
When I write this code 
`MethodCallExpr mce = (MethodCallExpr)node; // invokeWrapExceptions`
`ResolvedMethodDeclaration rmd = mce.resolve();`

it throws a RuntimeException Unable to calculate the type of a parameter of a method call. Method call: `invokeWrapExceptions(innerSetter, bean, value)`, Parameter: bean

**Comment by zhizhixiongxuwei** [comment]
Test file is here
[BeanPropertySet.txt](https://github.com/javaparser/javaparser/files/4987261/BeanPropertySet.txt)

**Comment by jlerbsc** [comment]
@zhizhixiongxuwei What javaparser version are you using? How have you initialized SymbolSolver? If you use external libraries you have to use CombinedTypeSolver and add a JavaParserTypeSolver for each library.

**Comment by zhizhixiongxuwei** [comment]
Thanks for your reply. I will check the testing code at that time(I can’t find it on hand). But I think it is about a part or lambda expression and no external libraries. By the way, is the project stopped?
________________________________

**Comment by jlerbsc** [comment]
There is no comment for a long time so i think this issue is resolved.
