### ISSUE TITLE
Fail to handle method that has this as a parameter

### ISSUE THREAD

**Issue by duanasour** [javaparser/javaparser#2768]
Hi JP developers,

Thanks for creating this great tool!

Not sure if this is valid but I see people write methods like

void someMethod(SomeClass this)

and JP rewrites it to 

void someMethod(SomeClass this, )

Is it something we should fix on JP side?

Thanks!
Tao

**Comment by jlerbsc** [comment]
Hi, could you provide a test case because it seems to work fine with JP 3.15.22

     @Test
    public void test() {
        String expected = 
                "public class Foo {" + EOL +
                "  public void someMethod(Foo this) {" + EOL +
                "  }" + EOL +
                "}";
      
        CompilationUnit cu = StaticJavaParser.parse(expected);
        LexicalPreservingPrinter.setup(cu);
        assertTrue(LexicalPreservingPrinter.print(cu).equals(expected));
    }

**Comment by duanasour** [comment]
I didn't use LexicalPreservingPrinter. Here is the code I tried.
```
public class Test {
  public static void main(String[] args) throws IOException {
    SourceRoot sourceRoot = new SourceRoot(Paths.get(args[0]));
    List<ParseResult<CompilationUnit>> parseResults = sourceRoot.tryToParse();
    sourceRoot.saveAll();
  }
}
```
And the class to parse:
```
public class TestData {
    public void someMethod(TestData this) {
    }
}
```

**Comment by jlerbsc** [comment]
Hi xiaotaoduan,
Which version are you using?
Did you try to reproduce it with a junit test case ?

I connot reproduce it with this test case

    String expected = 
                "public class Foo {" + EOL +
                EOL +
                "    public void someMethod(Foo this) {" + EOL +
                "    }" + EOL +
                "}";
      
        CompilationUnit cu = StaticJavaParser.parse(expected);
        System.out.println("original:\n"+cu.toString());
        System.out.println("expected:\n"+expected);
        assertTrue(cu.toString().equals(expected));

**Comment by duanasour** [comment]
Hi Jean,

I am using 3.5.11 downloaded Maven.

Could it be caused by sourceRoot.saveAll()? Since I noticed this error in the output file.

**Comment by jlerbsc** [comment]
Internally SourceRoot use PrettyPrinter class (default) to print a node (here a CompilationUnit). I have modified the test case to use this printer but i cannot reproduce this problem. Please, with this code base could you try to reproduce your error.

    @Test
    public void test() {
        String expected = 
                "public class Foo {" + EOL +
                EOL +
                "    public void someMethod(Foo this) {" + EOL +
                "    }" + EOL +
                "}";
      
        PrettyPrinter printer = new PrettyPrinter();
        CompilationUnit cu = StaticJavaParser.parse(expected);
        System.out.println("original:\n"+cu.toString());
        System.out.println("expected:\n"+expected);
        System.out.println("printed:\n"+printer.print(cu));
        assertTrue(printer.print(cu).equals(expected));
    }

**Comment by duanasour** [comment]
Hi Jean,

I switched to the latest version 3.16.1 and tested. The problem was gone. It seems this was just an issue in the old (3.5.11) releases.

Sorry for the false alarm and thanks for looking into this!

best,
Tao

**Comment by MysterAitch** [comment]
Hi @xiaotaoduan , thank you for the report and the update! :)
