### ISSUE TITLE
Fatal error compiling: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by IT-Jiang** [javaparser/javaparser#2773]
HI,I use the StaticJavaParser in AbstractProcessor

@SupportedAnnotationTypes( "XXX" )
@SupportedSourceVersion( SourceVersion.RELEASE_8 )
public class XXXProcessor extends AbstractProcessor {
	@Override
	public boolean process(final Set< ? extends TypeElement > annotations, 
	        final RoundEnvironment roundEnv) {

               **CompilationUnit unit = StaticJavaParser.parse(file);**
     }
}

However I recieve message when i maven compiler the project

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project XXXX: Fatal error compiling: java.lang.NoClassDefFoundError: com/github/javaparser/StaticJavaParser: com.github.javaparser.StaticJavaParser -> [Help 1]

Any ideas to why this happends and what possible fix might be?

**Comment by IT-Jiang** [comment]
maybe I added the following dependency into pom

               <dependency>
			<groupId>com.sun</groupId>
			<artifactId>tools</artifactId>
			<version>1.8</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/tools.jar</systemPath>
		</dependency>

**Comment by jlerbsc** [comment]
Have you added the javaparser library to your dependencies?
