### ISSUE TITLE
JavaParser 3.16.1 using LexicalPreservingPrinter.setup leaks memory

### ISSUE THREAD

**Issue by Maths-Maths** [javaparser/javaparser#2784]
I am using JavaParser 3.16.1,

Whenever I use LexicalPreservingPrinter.setup(CompilationUnit node) the memory usage keeps going up.

I keep going through a folder full of java files and using javaparser.parse I parse each files , I get a return value of type CompilationUnit after this I call LexicalPreservingPrinter.setup(CompilationUnit node). This is in a plugin. I see the memory usage keeps going up. If I comment LexicalPreservingPrinter.setup(CompilationUnit node) the memory usage is constant. I tried removing LexicalPreservingPrinter.setup(CompilationUnit node) and calling ParserConfiguration.setLexicalPreservationEnabled(true) the memory usage kept growing. Can you suggest something to reign in the memory usage.

**Comment by jlerbsc** [comment]
LexicalPreservingPrinter store NodeText for each node so it is normal that the memory consumption is higher.

**Comment by Maths-Maths** [comment]
How do I release it, as I told you this is in a plugin, the memory consumption has to be brought down. Each java file is read one after another and the memory keeps going up, there must be a way to let the garbage collector pick up these.

**Comment by Maths-Maths** [comment]
Each java file is read one after another and the memory keeps going up, there must be a way to let the garbage collector pick up these. I would be grateful if you could suggest a solution. I have about 2 months of work behind this.

**Comment by jlerbsc** [comment]
Oddly, I have a project that parses several thousand java source files and I have not identified this problem. Could you profile your project to identify java heap hot spot?

**Comment by Maths-Maths** [comment]
> Oddly, I have a project that parses several thousand java source files and I have not identified this problem. Could you profile your project to identify java heap hot spot?

The reason for that is you don’t have the project running all the time like a daemon or a plug-in in an integrated development environment. You will the see that the garbage collector never is able to reclaim the memory if LexicalPreservingPrinter.setup(CompilationUnit node) is called on the Compilation Unit returned by JavaParser.parse file.

**Comment by Maths-Maths** [comment]
I think the problem is in this code.

public class LexicalPreservingPrinter {
private static AstObserver observer;

If you could change the static or remove the reference at the end the memory issue would go away. Hope you would be kind enough to do it. Please look at the setup code and node.registerForSubtree observer. You will see what I am talking about.

Can you also take a look at the static NODE_TEXT_DATA you are doing node.setData(NODE_TEXT_DATA, new

**Comment by jlerbsc** [comment]
You mean that after having profiled your plugin the memory is retained by the ASTObserver and LexicalPreservingPrinter classes.

**Comment by Maths-Maths** [comment]
I went through the code, if you look at what I pointed you will understand why memory is accumulating please keep in mind the node_text_data and node.setdata node_text_data also

**Comment by jlerbsc** [comment]
Data is setted in node to provide lexical preservation, "i.e., the ability of parsing a Java source file, modifying the AST and get back the modified Java source code keeping the original layout". The lexical preservation has a counter part. This article explain a little more the concept.
https://tomassetti.me/lexical-preservation-javaparser/#:~:text=Many%20users%20of%20JavaParser%20are,code%20keeping%20the%20original%20layout.

**Comment by Maths-Maths** [comment]
Just try removing static from both node_text_data and observer. LexicalPreservingPrinter should be used as a normal object. Garbage Collector would have reclaimed the memory

**Comment by jlerbsc** [comment]
@Maths-Maths I cannot reproduce your issue so i cannot fix it. If you have a good understanding of what to do, you can provide a PR to javaparser project leaders.  In fact LexicalPreservingPrinter has a static API so i think that accessing instance field from static methods is not a best practice and modifying static methods has many impacts to the javaparser community. Perhaps you can use another printer (like PrettyPrinter) or implement your own printer class.

**Comment by jlerbsc** [comment]
Hi @Maths-Maths I'm sorry for this late reply, you are right when you setup the lexical preservation there is memory retention. The principal suspect is PhantomNodeLogic which has a static cache that you can clear with the static method PhantomNodeLogic.cleanUpCache(). I think this should be enough to reduce JP memory consumption. @ftomassetti @matozoid Could you explain us what is this concept of "Phantom" nodes.

**Comment by jlerbsc** [comment]
For total transparency, to analyze this issue i use the jps command to identify the test process id, generate a heap dump with the command jcmd <pid> GC.heap_dump dump.hprof and analyze it's content with Memory analyzer.

a test case 

    @Test
    void test() throws IOException, InterruptedException {
        ParserConfiguration config = new ParserConfiguration();
        config.setLexicalPreservationEnabled(true);
        JavaParser parser = new JavaParser(config);
        memory();
        CompilationUnit cu = parser.parse(new File("D:/dev/projects/javaparser-3.16.1/javaparser/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinter.java")).getResult().get();
        LexicalPreservingPrinter.setup(cu);
        memory();
       //        Thread.sleep(120000);
        PhantomNodeLogic.cleanUpCache();
        memory();
    }
    
    private void memory() {
        System.gc();
        Runtime rt = Runtime.getRuntime();
        long usedMB = (rt.totalMemory() - rt.freeMemory()) / 1024 / 1024;
        System.out.println("memory usage " + usedMB);
    }

**Comment by jlerbsc** [comment]
Hi @Maths-Maths perhaps you can close this issue and open a new one with the subject "what is this concept of "Phantom" nodes"

**Comment by matozoid** [comment]
@ftomassetti made these phantom nodes. I think it is when the lexical preserving printer works on a node that is not explicitly modelled or so. I think you can figure it out if you check where they are used.

**Comment by MysterAitch** [comment]
> 
> 
> [..] close this issue and open a new one with the subject "what is this concept of "Phantom" nodes"

#2935
