### ISSUE TITLE
Changing all private methods to protected in com.github.javaparser.printer.PrettyPrintVisitor so extending class can call them

### ISSUE THREAD

**Issue by uslswk** [javaparser/javaparser#2790]
I am extending `PrettyPrintVisitor` class to add some custom formatting. I wanted to override `printMembers(final NodeList<BodyDeclaration<?>> members, final Void arg)` method, but it is not possible now because it has modifier 'private' . I have overriden `visit(final ClassOrInterfaceDeclaration n, final Void arg)` method that calls `printMembers(final NodeList<BodyDeclaration<?>> members, final Void arg)` but this method is also calling other private methods of `PrettyPrintVisitor` class. To achieve my goal i had to copy all private methods of `PrettyPrintVisitor` class that are called from `visit(final ClassOrInterfaceDeclaration n, final Void arg)` to my extending class although i didnt want to modify them.  
Changing all 'private' methods to 'protected' would solve this problem.

**Comment by jlerbsc** [comment]
Can you specify what you want to achieve. Internally the PrettyPrintVisitor class uses the SourcePrinter class. Perhaps what you want instead is to be able to provide your own implementation of the SourcePrinter class?

**Comment by jlerbsc** [comment]
Hi @uslswk have you try to implement SourcePrinter to resolve your issue?

**Comment by uslswk** [comment]
Hi, no i don't need my own implementation of SourcePrinter. I wanted to change how  `printMembers(final NodeList<BodyDeclaration<?>> members, final Void arg)` prints members so it prints them separated only by one newline character.  Now it prints them like this:

```
    private Long id;

    private String name;

    public Long getId() {
        return id;
    }
	
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }
	
    public void setName(String name) {
        this.name= name
    }
```
And i wanted something like this:
```
    private Long id;
    private String name;

    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name= name
    }
```
So i had to change implementation of method `printMembers(final NodeList<BodyDeclaration<?>> members, final Void arg)` 
from: 
```
    private void printMembers(final NodeList<BodyDeclaration<?>> members, final Void arg) {
        for (final BodyDeclaration<?> member : members) {
            printer.println();
            member.accept(this, arg);
            printer.println();
        }
    }
```
to:
```
	private void printMembers(final NodeList<BodyDeclaration<?>> members, final Void arg) {
		boolean isMethod = false;
		printer.println();
		for (final BodyDeclaration<?> member : members) {

			if (!isMethod && member.getClass() == MethodDeclaration.class) {
				isMethod = true;
				printer.println();
			}

			member.accept(this, arg);
			printer.println();
		}

	}
```
