### ISSUE TITLE
Is the project stopped?

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2802]
Historical contributors no longer appear on this project. So we can ask ourselves the question of the life cycle of this project.

**Comment by hunan889** [comment]
with plenty of bugs left...

**Comment by matozoid** [comment]
Officially, the maintainer is @MysterAitch.

@ftomassetti may be available for hire.

I have stopped since May or so, but am willing to transfer knowledge to anyone willing to maintain JavaParser. I believe this is a great opportunity to take the wheel of a medium-sized, successful open source project!

**Comment by maartenc** [comment]
I'm willing to help @matozoid , but my knowledge of the project is limited to the symbol solving part for now...

**Comment by matozoid** [comment]
@maartenc - that would be great! In my opinion the minimal job is to make releases, and respond to issues (even if it is "I don't know"). @MysterAitch - can you please pop up so we can get this going? You're the one who knows how to get everything set up for releasing :-)

**Comment by ftomassetti** [comment]
I guess I can be considered an "historical contributor" :D 

Over time my consulting business took over more and more time and I was no longer available to contribute to the project.
That said, I would be happy to help with knowledge transfer and promotion of the project as much as I can.

@maartenc I think that the symbol solving part is the most complex one, so it is very good to have someone able to dig into that part

**Comment by jlerbsc** [comment]
I'm willing to help too.

**Comment by matozoid** [comment]
@ftomassetti - can you add @maartenc and @jlerbsc to the core team with all rights? Aw, add me back too if you like.

**Comment by ftomassetti** [comment]
I have added you and invited them

**Comment by jlerbsc** [comment]
Thank you i will try to be up to the task ;-).

**Comment by matozoid** [comment]
@jlerbsc @maartenc - can you join the "javaparser" room on JP's Gitter? I'll see if I can get you to make a release :-)

**Comment by matozoid** [comment]
In the meantime: feel free to respond to issues, organize them, and pull them.

**Comment by matozoid** [comment]
@jlerbsc can you check gitter and take action?
