### ISSUE TITLE
EOL separator problems on windows

### ISSUE THREAD

**Issue by signed** [javaparser/javaparser#2806]
Hi, I'm running into a problem on windows when adding and import to an existing source file that uses `\n` line endings.
This happens when using `setLexicalPreservationEnabled(true)` and printing with `LexicalPreservingPrinter`.
I'm currently updating to `javaparser 3.16.1`.

I have a [minimal example](https://github.com/signed/convert-junit4-to-junit5/blob/e5e91942510d8499ca86bc273e0de2b162565fda/src/test/java/jb/convert/ast/LineSeparatorOnWindowsTest.java) that reproduces the problem.

To me it looks like the parser uses [Utils.EOL](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/utils/Utils.java#L47) that defaults to `\r\n` on windows and during the code modification some assumptions break. I did not find an equivalent to `PrettyPrinterConfiguration` for the `LexicalPreservingPrinter`.

Is there an API that I'm missing?
Am I using the api correctly?

```Java
package testcase;
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.ImportDeclaration;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;

class LineSeparatorOnWindowsTest {

    @BeforeEach
    void fakeWindows() {
       System.getProperties().setProperty("line.separator", "\r\n");
    }

    @Test
    void importIsAddedOnTheSameLine() {
        String junit4 = "import java.lang.IllegalArgumentException;\n" +
                "\n" +
                "public class A {\n" +
                "}";
        String junit5 = "import java.lang.IllegalArgumentException;\n" +
                "import java.nio.file.Paths;\n" +
                "\n" +
                "public class A {\n" +
                "}";
        JavaParser parser = new JavaParser(new ParserConfiguration().setLexicalPreservationEnabled(true));
        CompilationUnit cu = parser.parse(junit4).getResult().get();
        ImportDeclaration importDeclaration = new ImportDeclaration("java.nio.file.Paths", false, false);
        CompilationUnit compilationUnit = cu.addImport(importDeclaration);
        String out = LexicalPreservingPrinter.print(compilationUnit);
        assertThat(out, equalTo(junit5));
    }
}

```

**Comment by jlerbsc** [comment]
@signed You are right. Thanks for reporting this issue which is related to the Difference processing since the end of line has been refactored.

**Comment by signed** [comment]
@jlerbsc thank you for taking the time to look into the report and providing a fix.
Are there snapshot releases of javaparser that I can use until the next release is published?

**Comment by jlerbsc** [comment]
@signed For the moment tests fail but i don't know why! So be patient ;-)

**Comment by signed** [comment]
@jlerbsc is there already and ETA for the next release?

**Comment by jlerbsc** [comment]
What is an ETA?

**Comment by signed** [comment]
Estimated time of arrival (ETA). Sorry, should have just asked if there is already a date for the next release.

**Comment by jlerbsc** [comment]
Hi @maartenc Have you planned a new release these days?

**Comment by maartenc** [comment]
I'm working on it, I hope to create a new release within the next couple of days.

**Comment by jlerbsc** [comment]
Fantastic. Thanks

**Comment by maartenc** [comment]
@signed : we've released a new version today.
Could you give it a try?

**Comment by signed** [comment]
@maartenc `3.16.2` looks good, thank you
