### ISSUE TITLE
Character encoding in Comments Parser is broken 

### ISSUE THREAD

**Issue by danielbobbert** [javaparser/javaparser#281]
Fix #41 sought to handle the case where source files are not encoded in UTF-8. Unfortunately the author of the fix chose to use the default Charset for encoding/decoding. Now, if you run the parser on UTF-8 encoded source code that contains special characters, and the platform you are running the parser on happens to have a default characterset that cannot display those special characters, then the comment parser will fail to parse the comment or simply replace the special characters by question marks.

The comments parser should simply use UTF-8 for both encoding and (re-)decoding the source code. This way, the intent of the original fix for #41 is maintained while still making sure that all special characters can be represented and parsed.

```
public CommentsCollection parse(final String source) throws IOException, UnsupportedEncodingException {
    // use UTF-8 to ensure that we can represent all characters
    String encoding = "UTF-8";
    InputStream in = new ByteArrayInputStream(source.getBytes(Charset.forName(encoding)));
    return parse(in, encoding);
}
```

**Comment by ftomassetti** [comment]
I think you can use the method of CommentsParser which let you specify the encoding. Would that help in your case?

**Comment by danielbobbert** [comment]
I tried to. That helps for parsing, but then there is no easy way of inserting the parsed comments into the CompilationUnit because JavaParser.insertCommentsInCu() is private.

**Comment by danielbobbert** [comment]
BTW: I was wondering why you keep encoding strings to streams back and forth anyways. CommentsParser.parse(String) builds an InputStream (with an arbitrary encoding) just for CommentsParser.parse(InputStream, String) to turn that into a Reader again (using the same encoding).

An easier (and more efficient) way would be to offer a method that takes a Reader right way:

```
public CommentsCollection parse(final String source) throws IOException, UnsupportedEncodingException {
    // simply use the Reader-variant to omit all re-encoding
    return parse(new StringReader(source));
}

// existing method, now forwards to the Reader-variant
public CommentsCollection parse(final InputStream in, final String charsetName) throws IOException, UnsupportedEncodingException {
    return parse(new InputStreamReader(in, charsetName));
}

// new method that takes a Reader instead of an InputStream
public CommentsCollection parse(final Reader in) throws IOException {
    boolean lastWasASlashR = false;
    BufferedReader br = new BufferedReader(in);
    ...
```

**Comment by matozoid** [comment]
Hmm, in the JDK the usual behaviour when not specifying an encoding is to take the platform specific one, so I would say that this is not the problem here. I'm thinking we could have a parser-wide override for this?

**Comment by matozoid** [comment]
This was implemented in one of the alphas.
