### ISSUE TITLE
How to capture the fields which are accessed without calling with the class name?

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#2810]
For example, the `address` is directly accessed, and I cannot get the field it using the FieldAccessExpr. The code is shown below.
```java
public void visit(FieldAccessExpr field, Void arg) {
    ResolvedValueDeclaration node =  field.resolve();
    System.out.println("Field: " + node.getName() + ", Type: " + node.getType());
    super.visit(field, arg);
}
```

```java
// test
public class C1{
    public String name = "u";
    public String address = "y";
    public void m1(){
        C2.phone; //success
        address = "9"; //fails
    }
}
```

Any help is appreciated.

**Comment by zhizhixiongxuwei** [comment]
address="9" should be assignExpr（address is nameExpr）. And if you can use this.address you will get what u want.

**Comment by zhizhixiongxuwei** [comment]
I am not sure if you have some experience about parsing tool like Eclipse-JDT.  But xx.address is different with address.

**Comment by ghost** [comment]
@zhizhixiongxuwei Thank you for your fast reply. I thought that a statement containing a field meant access to the field.
You clarify it. Accessing a field should mean using its value.

But, in the following case, the fields (i.e., alias_ratio, literals_file, and literals_level) are directly used, and they are not identified. However, `ClassLiteralsMode.NONE` can be identified.

```java
public abstract class GenInputsAbstract extends CommandHandler {
    public static double alias_ratio = 0;
    public static List < String > literals_file = new ArrayList < > ();
    public static ClassLiteralsMode literals_level = ClassLiteralsMode.CLASS;

    public void checkOptionsValid() {

        if (alias_ratio < 0 || alias_ratio > 1) {
            throw new RandoopUsageError("xxx.");
        }
        if (!literals_file.isEmpty() && literals_level == ClassLiteralsMode.NONE) {
            throw new RandoopUsageError("xcxx");
        }
        ...
    }
}

// NONE can be identified, but alias_ratio, literals_file, and literals_level fail.
```

**Comment by zhizhixiongxuwei** [comment]
identified, but alias_ratio, literals_file, and literals_level  shoule be nameExpr. ClassLiteralsMode.NONE can be identified as FieldAccess?  I  can't reproduce this problem(your code is not complete).

**Comment by zhizhixiongxuwei** [comment]
I simplify your code as below
```
public double alias_ratio = 0;
    public List < String > literals_file = new ArrayList < > ();
    public String literals_level = "";

    public void checkOptionsValid() {

        if (this.alias_ratio < 0 || alias_ratio > 1) {
            System.out.println();
        }
        if (!literals_file.isEmpty() && literals_level == "") {
            System.out.println();
        }
        
    }
```
if you use this.alias_ratio(FieldAccessExpr)  use alias_ratio directly will nameExpr. Because FieldAccessExpr is defined  like this:  scope + name. scope can be thisExpr or other object.

**Comment by ghost** [comment]
@zhizhixiongxuwei 
Thank you~

- The code is from Randoop; you can find it attached (please modify its extension name). [GenInputsAbstract.txt](https://github.com/javaparser/javaparser/files/5302909/GenInputsAbstract.txt)

- I just tested the `this`.  A field does have to be accessed with `this` to be identified as a `FieldAccessExpr`.
But for the static fields, they cannot be accessed using `this`......

So if I want to identify all fields used in a method, I should use the `nameExpr` for fields in the current class and `FieldAccessExpr` for fields in other classes?

By the way, I find `this.field = "xxx"` can also be identified a `FieldAccessExpr`. So the access means using the address of the field.

**Comment by zhizhixiongxuwei** [comment]
I don't know why u focus on collect these information. As I known, you can visit nameExpr and call nameExpr.resolveVariableDeclaration to check whether it is field or not. And visit(FieldAccessExpr) to cover another situation.

**Comment by ghost** [comment]
@zhizhixiongxuwei Thanks a lot.

**Comment by ghost** [comment]
@zhizhixiongxuwei Hi, I study the field access without the qualifier (i.e., class name or `this`) again. And the method `resolveVariableDeclaration` cannot be associated with a nameExpr. But I solve it using the following code.

```java
public void visit(NameExpr n, Void arg) {
    if (n.resolve().isField()) {
        System.out.println("Field Name: " + n.resolve().getName() + 
        ", Declaring Type: " + n.resolve().asField().declaringType().getQualifiedName());
    }
    super.visit(n, arg);
}
```

By the way, the AST is very useful to study the API usage of JavaParser.
