### ISSUE TITLE
How to visit the static block?

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#2811]
Some classes may have `static` block, but I don't find the `visit` method for it.

```java
public class C1{

    static{
       ...... // how to visit elements (method invocation and field access expression) ?
    }

}

**Comment by jlerbsc** [comment]
This is an InitializerDeclaration. I think to better understand or use AST you should use a debugger to understand its structure. Personally that's what I do regularly ;-)

**Comment by ghost** [comment]
@jlerbsc Thank you.
