### ISSUE TITLE
How to get the name of the class which the given FieldAccessExpr and ObjectCreationExpr are located in?

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#2814]
I'm computing the dependency between classes.

So I  visit the `MethodCallExpr`, `FieldAccessExpr`, and `ObjectCreationExpr` to get their types and which classes they are located in.

**I want to distinguish between outer classes and inner classes.**

For example, in the following code, when analyzing the `MethodCallExpr` of class `Main`, I want to only focus on the method `m1()` and ignore `m2()` because  `m2()` is in the inner class `Inner1`.
```java
public class Main {
    public static String address = "2";

    public static void m1() {
        if (C1.name){
             C1.m3();
        }        
    }

    public static class Inner1 {
        public void m2() {
             if (C2.name){
             C1.m4();
        } 
        }
    }
}
```
I code as follows, but it introduces inner classes into the analysis of the outer classes.

1. Firstly, I visit `ClassOrInterfaceDeclaration`, and get the class name or interface name. 
2. Then for each `ClassOrInterfaceDeclaration`, I visit `MethodCallExpr`, `FieldAccessExpr`, and `ObjectCreationExpr` to get their types. 

I find that this involves the `C1.m4()` and `C2.name` when analyzing class `Main`.

I can solve the `C1.m4()`  by visiting `MethodDeclaration`. But how can I get which classes the `FieldAccessExpr`, and `ObjectCreationExpr`  are in?

**Comment by jlerbsc** [comment]
@liuyuanOUC what you are trying to do is not very clear. Have you try to resolve the FieldAccessExpr or the ObjectCreationExpr? Have you try to use debugger to understand the AST produced by your test code? Have you setup the SymbolSolver?

**Comment by ghost** [comment]
@jlerbsc Thank you for your attention.

I have set up the SymbolSolver by `SymbolSolverCollectionStrategy`.

Sorry for my confused description . You can see the following code. 
```java
// demo
public static class ExternalClass{
        public static class InternalClass{
                C1 c1 = new C1(); // the object c1 is created. And this creation statement is located in a inner class.
        }
}
```
Take `ObjectCreationExpr` as an example, I can get the declaring type of `c1` using the following code:
```java
public void visit(ObjectCreationExpr n, Void arg) {
        String declaringTypeName = n.resolve().declaringType().getQualifiedName(); //return C1's full name
        super.visit(n, arg);
}
```

But how can I get the type that contains the _object creation expression_ (i.e., `new C1()`)? In the example above, `new C1()` is located in the class **`InternalClass`**.

**Comment by jlerbsc** [comment]
@liuyuanOUC I understand that you want to access to the ClassOrInterfaceDeclaration which contains the ObjectCreationExpr.
Use of findAncestor method give you a mean to do that.

     ObjectCreationExpr oce = cu.findFirst(ObjectCreationExpr.class).get();
     oce.findAncestor(ClassOrInterfaceDeclaration.class).ifPresent(d-> System.out.println(d.getFullyQualifiedName().get()));

produces

    ExternalClass.InternalClass

with code

    public class ExternalClass{
        public static class InternalClass{
                C1 c1 = new C1(); // the object c1 is created. And this creation statement is located in a inner class.
        }
}

**Comment by ghost** [comment]
@jlerbsc Thank you. It works fine.
