### ISSUE TITLE
Question: Getting all callers to external library

### ISSUE THREAD

**Issue by bojanv55** [javaparser/javaparser#2821]
My project is using Spring and RabbitAMQP library.

Is it possible to do the following: parse my whole project, and find all possible code invocations of some method in external maven dependency lib (in this case rabbitmq lib), like this one `void createQueue(String name)`?

e.g. My code could be:

```
class A{
public static void main(){
  B.doIt("someQueueName");
  B.doIt("someQueueName2");
}
}

class B{
void doIt(String name){
   externalRabbitLib.createQueue(name);
}
}
```

and the output I would just need is:
1 -> called as `createQueue(String "someQueueName")` and 2-> called as `createQueue(String "someQueueName2")`

**Comment by jlerbsc** [comment]
Hi @bojanv55 First of all, can you define "all possible code invocations". Do you only want method calls? I think it's possible. You have to setup SymbolSolver, use a visitor to resolve each expression (for exemple MethodCallExpr) and filter on the qualified signature .

    CombinedTypeSolver typeSolver = // create and initialize the CombinedTypeSolver
    ParserConfiguration config = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
    StaticJavaParser.setConfiguration(config);
    CompilationUnit cu = StaticJavaParser.parse(<your class>);
    Set<MethodCallExpr> methodCallExpr = new HashSet<>(cu.findAll(MethodCallExpr.class));
    for (MethodCallExpr expr : methodCallExpr) {
	try {
		ResolvedMethodDeclaration rd = expr.resolve();
		System.out.println("\t Solved : " + rd.getQualifiedSignature()); // for example Solved : javaparser.JSONObject.put(java.lang.String, java.lang.String)
	} catch (UnsolvedSymbolException e) {
		System.out.println("\t UNSOLVED: " + expr.toString());
	}
}

**Comment by bojanv55** [comment]
Thanks. I just tried this, but the problem is that it is loading only first class in the project (class that I specified in `StaticJavaParser.parse(<your class>)`). Is it possible to give `src/main/java` to analyzer? I found `ProjectRoot projectRoot = new SymbolSolverCollectionStrategy()...` and this one goes over all files, but it creates separate `CompilationUnit` and I guess I would need this thing to be analyzed as one big file?

Also, can javaparser resolve method calls when using Spring beans? e.g.

```
@Import({Config2.class})
class Config{
  void Some(SmCl a){. //here we autowire object returned from a() method in Config2 class
    ..
  }
}

class Config2{
  @Bean
  void SmCl a(){
  }
}
```

**Comment by bojanv55** [comment]
btw got this Runtime Exception when parsing project:

```
java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: responseParser.getAsType(new TypeReference<ArrayList<MyClass>>() {
}), Parameter: new TypeReference<ArrayList<MyClass>>() {
}

...

CorrespondingDeclaration not available for unsolved symbol.

```

where TypeReference is from jackson core:

```
package com.fasterxml.jackson.core.type;

public abstract class TypeReference<T> implements Comparable<TypeReference<T>> {
```

**Comment by jlerbsc** [comment]
@bojanv55 I only provide you an example not a solution to your problem. If it's the first time you work with JP i recommand you to read JP userguide. I am not familiar with @Import annotation so i don't know if your use case is supported by JP.

The other issue "Unable to calculate the type of a parameter of a method call" you are facing with is probably related to the issue #2762. There is currently a discussion on this subject to find the best solution.

**Comment by jlerbsc** [comment]
Hi @bojanv55 if you have no more questions can you close this issue please.
