### ISSUE TITLE
Type resolving inside block code

### ISSUE THREAD

**Issue by himamis** [javaparser/javaparser#2830]
I am trying to parse and resolve symbols for this java file
```
class ThisReference {

    void method() {
        ThisReference a = this;
        {
            a.method();
        }
    }
}
```
But when I visit the node `a.method()` with the following code
```
	@Override
	public Visitable visit(MethodCallExpr n, Void arg) {
		ResolvedMethodDeclaration d = n.resolve();
		return super.visit(n, arg);
	}
```
I get a `UnsolvedSymbolException{context='a.method()', name='a', cause='UnsolvedSymbolException{context='a', name='Solving a', cause='null'}'}` at the resolve call.

This does not happen, if I remove the wrapping `{}` brackets around the `a.method()` call. Any ideas how to solve this issue?

**Comment by himamis** [comment]
Maybe a duplicate of https://github.com/javaparser/javaparser/issues/2477? This looks like a big issue.

**Comment by jlerbsc** [comment]
Thanks for reporting this issue.
