### ISSUE TITLE
Get the FieldDeclaration for a field inherited from a parent class.

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#2835]
The field `name2` is declared in the child class `C2`. Its initialization contains a field `name` which is inherited from `C2`'s parent class `C1`.
```java
public class C1{
    public String name = "foo";
}

public class C2 extends C1{
    public String name2 = name + "xxx";
}
```
Given the FieldDeclaration of  name2 (i.e., `public String name2 = name + "xxx"`), I try to get the FieldDeclaration of `name` using the following code.

```java
...
else if (bExprLeft.isNameExpr() && bExprRight.isStringLiteralExpr()) {
    try {
        if (bExprLeft.asNameExpr().resolve().isField()) {
            JavaParserFieldDeclaration leftValue = (JavaParserFieldDeclaration) bExprLeft.asNameExpr().resolve().asField();
            FieldDeclaration bLeft = leftValue.getWrappedNode();
            bRight = bExprRight.asStringLiteralExpr().getValue();
        }
    } catch (UnsolvedSymbolException e) {
        System.out.println(bExprLeft.asNameExpr().getName().asString() + " cannot be resolved.");
    }
}
...
```
`name` corresponds to `bExprLeft`, and "xxxx" corresponds to `bExprRight`. Then `bExprLeft.asNameExpr().resolve().isField()` can return true. But the statement `JavaParserFieldDeclaration leftValue = (JavaParserFieldDeclaration) bExprLeft.asNameExpr().resolve().asField();` throws an exception:
```
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration$1 cannot be cast to com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserFieldDeclaration
...
```
I think `bExprLeft.asNameExpr().resolve().asField()` should be a JavaParserFieldDeclaration, but why it is a `JavaParserClassDeclaration`?
Or it is a bug?

**Comment by ghost** [comment]
The AST tree of `public String name2 = name + "xxx";` is shown in following figure.
![image](https://user-images.githubusercontent.com/27879832/96182879-b5867480-0efb-11eb-9840-8223fed15da4.png)

**Comment by jlerbsc** [comment]
Hi @liuyuanOUC Your issue seems to be related to the issue #1479 which was solved yesterday. The fix will be available in the next version of JP which should arrive shortly. In the next version you could do this like it

     ResolvedFieldDeclaration leftValue = bExprLeft.asNameExpr().resolve().asField();;
     Optional<FieldDeclaration> bLeft = = leftValue.toAst();

**Comment by ghost** [comment]
Hi @jlerbsc. Nice! Thank you very much for your consistent help.
