### ISSUE TITLE
findAll(ThrowStmt.class) not list Optional.orElseThrow exception

### ISSUE THREAD

**Issue by minhnguyenvan95** [javaparser/javaparser#2859]
findAll(ThrowStmt.class) not list Optional.orElseThrow exception

TransferPaymentTransactionNotFoundException is not listed when trying to call findAll(ThrowStmt.class)

orElseThrow(TransferPaymentTransactionNotFoundException::new) is known as MethodReferenceExpr 

```
        TransferPaymentEntity transferPaymentEntity = transferPaymentRepository
                .getByDebitAccountIsAndOnlineTransactionIdIs(debitAccount, onlineTransactionNumber)
                .orElseThrow(TransferPaymentTransactionNotFoundException::new);
```

**Comment by jlerbsc** [comment]
Hi @minhnguyenvan95, using a debbuger it seems that arguments of the below expression is resolved to MethodReferenceExpr with a TypeExpr.

    Optional.ofNullable(new Object()).orElseThrow(UnsupportedOperationException::new);

**Comment by jlerbsc** [comment]
@minhnguyenvan95 Does this answer to your question suit you?

**Comment by minhnguyenvan95** [comment]
But I think UnsupportedOperationException::new should recognize as ThrowStmt too

**Comment by jlerbsc** [comment]
In AST UnsupportedOperationException::new is a MethodReferenceExpr argument of a MethodCallExpr. You can verify this yourself with a debugger as I did.
