### ISSUE TITLE
Wrong result for EnumDeclaration.toString()

### ISSUE THREAD

**Issue by LajosCseppento** [javaparser/javaparser#286]
JavaParser 2.3.0 outputs a non-compilable string for enums. 

Original code:

``` java
public enum State {
    STARTED,
    PAUSED,
    STOPPED,
    IDLE
}
```

JavaParser 2.3.0 output:

``` java
public enum State implements  {

    STARTED() {
    }
    , PAUSED() {
    }
    , STOPPED() {
    }
    , IDLE() {
    }
    ;
}
```

It was working with 2.2.2 and it is due to the new _ensureNotNull()_ calls. Reference: DumpVisitor.java:1233:

``` java
        if (n.getImplements() != null) { **this is never null from 2.3.0**
            printer.print(" implements ");
            for (final Iterator<ClassOrInterfaceType> i = n.getImplements().iterator(); i.hasNext();) {
                final ClassOrInterfaceType c = i.next();
                c.accept(this, arg);
                if (i.hasNext()) {
                    printer.print(", ");
                }
            }
        }
```

Althought _ensureNotNull()_ was introduced, in DumpVisitor there are still a lot of null checks.

**Comment by LajosCseppento** [comment]
Sorry for reporting it, it is a duplicate: https://github.com/javaparser/javaparser/issues/231
When will be the fix released to mavencentral?

**Comment by ftomassetti** [comment]
Do you see the issue with 2.3.0? If so we should re-open this ticket

**Comment by LajosCseppento** [comment]
The issue is present in 2.3.0, but it seems that it is already fixed in the committed code.

**Comment by ftomassetti** [comment]
Should we close this one then?

**Comment by LajosCseppento** [comment]
Unfortunately I could not fetch 2.4.0 neither from mavencentral nor from jcenter, so I built your tagged 2.4.0 release and I verified that it is working now for my enums.

**Comment by ftomassetti** [comment]
Hi @cseppento thanks for verifying this! We are releasing 2.4.0 on Maven central in these days, for now it is on bintray https://bintray.com/javaparser/JavaParser/javaparser/view
