### ISSUE TITLE
When adding a new SourceRoot to ProjectRoot, this root is not added to the CombinedTypeSolver

### ISSUE THREAD

**Issue by Z13NDELS** [javaparser/javaparser#2863]
TItle says quite all : If I try to create a ProjectRoot with a `CombinedTypeSolver`, the combined type solver is in fact replaced in `SymbolSolverCollectionStrategy` in these lines

```
    public SymbolSolverCollectionStrategy(ParserConfiguration parserConfiguration) {
        // TODO/FiXME: Allow the symbol resolver to be set via the given parser configuration, and throw if invalid?
        this.parserConfiguration = parserConfiguration.setSymbolResolver(new JavaSymbolSolver(typeSolver));
    }
```

This is a blocker for me, as I want to read source code from multiple maven modules and be able to chain method discovery.
To overcome that, I'll have to replace the `ParserConfiguration` with an anonymous subclass where the getter/setter for symbol solver is deactivated ... Not optimal, to say the least.

**Comment by jlerbsc** [comment]
Thanks for reporting this issue. It will be corrected in the next version.

**Comment by Z13NDELS** [comment]
I'm using JavaParser 3.16.1.
When is the next version expected ? Do you think I can try locally ? Maybe cloning/building/using the snapshot will do the job ?

**Comment by jlerbsc** [comment]
JP 3.16.2 has been released last week so you can clone and build the current snapshot.
