### ISSUE TITLE
SymbolSolver does not resolve some of the methods' signaturer

### ISSUE THREAD

**Issue by shaifulcse** [javaparser/javaparser#2865]
I am applying the symbol solver on the checkstyle project (https://github.com/checkstyle/checkstyle, checked out at e454ccdc73d393bed3fbd3713249b5f8d8219a3b).

I have parsed total 3180 methods but failed to resolve the fully qualified signature for 129 of them. Although some are having issues with syntax (that's fine), some of the cases do not make enough sense. Are these happening because of SymbolSolver's bugs? I am not sure. For example, it fails to resolve the following method, 

```
   @Override
    public void fatalError(SAXParseException exception) throws SAXException {
        throw exception;
    }

```
Looking at the import statements, I found,
 
```
import org.xml.sax.SAXException 
import org.xml.sax.SAXParseException;

```
The file path: 
`src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java
`

My POM file contains, 

```
<dependency>
     <groupId>com.github.javaparser</groupId>
     <artifactId>javaparser-symbol-solver-core</artifactId>
      <version>LATEST</version>
</dependency>

```

I can continue like this, but wondering if this is a bug, or I am doing something wrong.

**Comment by jlerbsc** [comment]
Hi @shaifulcse could you tell us how you initialize JP and in particular JSS and RefectionTypeSolver? By default RefectionTypeSolver will only resolve types from the java or javax packages.

**Comment by shaifulcse** [comment]
To download all the jar files, I first used the command: `mvn dependency:copy-dependencies`

Here is my code:

 ```
public  static void processFiles(List<String> sourceDirectories) throws FileNotFoundException {
        ParserConfiguration parserConfiguration = new ParserConfiguration()
                .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_11);

        CombinedTypeSolver combinedTypeSolver = getCombinedTypeSolver(sourceDirectories);
        StaticJavaParser.setConfiguration(parserConfiguration);
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));

..............................
..............................
```


```

 private static CombinedTypeSolver getCombinedTypeSolver(List<String> sourceDirectories) {
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        // add source directories
        for(String dir: sourceDirectories){
            System.out.println(dir);
            combinedTypeSolver.add(new JavaParserTypeSolver(new File(dir)));
        }

        // add jar files..
        // need to run mvn dependency:copy-dependencies for generating all jars in target folder
        File target = new File(Settings.BASE_PATH+Settings.PROJECT+"/"+"target/dependency/");
        String[] jars =    target.list();
        for (String jar: jars){
            try {
                combinedTypeSolver.add(new JarTypeSolver(Settings.BASE_PATH+Settings.PROJECT+"/"+"target/dependency/"+jar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return combinedTypeSolver;
    }
```

**Comment by jlerbsc** [comment]
Could you try to initialize CombinedTypeSolver with 

    combinedTypeSolver.add(new ReflectionTypeSolver(false));

Because by default RefectionTypeSolver will only resolve types from the java or javax packages.

**Comment by shaifulcse** [comment]
Thanks so much. It solved most of the problems. Grateful to this community.
