### ISSUE TITLE
I use java-symbol-solver to resolve this file , then it raises a error: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by mf1832146** [javaparser/javaparser#2869]
The analyzed file:

[BatteryStatsImpl.txt](https://github.com/javaparser/javaparser/files/5434105/BatteryStatsImpl.txt)

The code I used as below:
```java
    public void visit(MethodCallExpr mc, List<String> api_seq){
        // 处理参数调用
        try{
            super.visit(mc, api_seq);
            ResolvedMethodDeclaration re = mc.resolve();
            if(!re.getPackageName().startsWith("java"))
                return;
            addToSeq(re.getQualifiedSignature() + ":" + re.getReturnType().describe(), api_seq);
        }catch (Exception e){
            logger.debug("unresolved method call: " + e.toString());
        }
    }

    // Method create
    @Override
    public void visit(ObjectCreationExpr oc, List<String> api_seq){
        try{
            super.visit(oc, api_seq);
            ResolvedConstructorDeclaration rc = oc.resolve();
            if(!rc.getPackageName().startsWith("java"))
                return;
            addToSeq(rc.getQualifiedSignature() + ":" + rc.getPackageName() + "." + rc.getClassName(), api_seq);
        }catch (Exception e){
            logger.debug("unresolved method call: " + e.toString());
        }
    }
```

That is a bug or I wrote the wrong code ?

**Comment by jlerbsc** [comment]
Hi @mf1832146 we lack a lot of information to be able to help you including a unit test case. In fact we can't use your test class because it uses dependencies that we don't have.
You can use this one to verify what is wrong in your context.

    public class Issue2869Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() throws IOException {
        
        Path testResources= adaptPath("src/test/resources/issue2869");
        Path pathToSourceFile = adaptPath(testResources.toString() + "/BatteryStatsImpl.java");
        
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver());
        typeSolver.add(new JavaParserTypeSolver(testResources));

        StaticJavaParser.setConfiguration(new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver)));

        CompilationUnit cu = StaticJavaParser.parse(pathToSourceFile);
        
        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
        
        mces.forEach(mce -> {
            try {
            System.out.println("trying to resolve method expr : " + mce.toString());
            System.out.println(String.format("%s resolved to %s", mce, mce.resolve().getQualifiedName()));
            } catch (Exception e) {
                System.out.println(""+e.getMessage());
            }
        });
        
    }

}

result

    trying to resolve method expr : cb.batteryNeedsCpuUpdate()
    Unsolved symbol in cb.batteryNeedsCpuUpdate() : cb
    trying to resolve method expr : cb.batteryPowerChanged(msg.arg1 != 0)
    Unsolved symbol in cb.batteryPowerChanged(msg.arg1 != 0) : cb
    trying to resolve method expr : in.readInt()
    Unsolved symbol in in.readInt() : in

**Comment by mf1832146** [comment]
Thank you for your prompt reply. I found that my issue is the same as [2781](https://github.com/javaparser/javaparser/issues/2781).  I solved it by putting the resolving process into a thread, and then just skip it when the process goes wrong. Hoping the issue could be solved soon. 


> Hi @mf1832146 we lack a lot of information to be able to help you including a unit test case. In fact we can't use your test class because it uses dependencies that we don't have.
> You can use this one to verify what is wrong in your context.
> 
> ```
> public class Issue2869Test extends AbstractSymbolResolutionTest {
> 
> @Test
> public void test() throws IOException {
>     
>     Path testResources= adaptPath("src/test/resources/issue2869");
>     Path pathToSourceFile = adaptPath(testResources.toString() + "/BatteryStatsImpl.java");
>     
>     CombinedTypeSolver typeSolver = new CombinedTypeSolver();
>     typeSolver.add(new ReflectionTypeSolver());
>     typeSolver.add(new JavaParserTypeSolver(testResources));
> 
>     StaticJavaParser.setConfiguration(new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver)));
> 
>     CompilationUnit cu = StaticJavaParser.parse(pathToSourceFile);
>     
>     List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
>     
>     mces.forEach(mce -> {
>         try {
>         System.out.println("trying to resolve method expr : " + mce.toString());
>         System.out.println(String.format("%s resolved to %s", mce, mce.resolve().getQualifiedName()));
>         } catch (Exception e) {
>             System.out.println(""+e.getMessage());
>         }
>     });
>     
> }
> ```
> 
> }
> 
> result
> 
> ```
> trying to resolve method expr : cb.batteryNeedsCpuUpdate()
> Unsolved symbol in cb.batteryNeedsCpuUpdate() : cb
> trying to resolve method expr : cb.batteryPowerChanged(msg.arg1 != 0)
> Unsolved symbol in cb.batteryPowerChanged(msg.arg1 != 0) : cb
> trying to resolve method expr : in.readInt()
> Unsolved symbol in in.readInt() : in
> ```

**Comment by jlerbsc** [comment]
How did you initialize symbol solver? BatteryStatsImpl class extends android.os.BatteryStats class which is probably defined in a library?

**Comment by mf1832146** [comment]
I am trying to extract the JDK API call sequences from a java code corpus, so I just use the JavaSymbolSolver to initialize. The method calls in android.jar are then ignored. The code I used is copied from the user guide as belows:
`
        ParserConfiguration parserConfiguration = new ParserConfiguration().setAttributeComments(false);
        StaticJavaParser.setConfiguration(parserConfiguration);

        TypeSolver typeSolver = new ReflectionTypeSolver();
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);`

**Comment by jlerbsc** [comment]
I think to avoid your problem you have to correctly initialize the symbol solver by integrating the android jar in a CombinedTypeSolver.

    CombinedTypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(false),
                new JarTypeSolver(<path_to_library>), new JavaParserTypeSolver(<path_to_sources>));
    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
    StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

**Comment by jlerbsc** [comment]
> The method calls in android.jar are then ignored.

If you do not include libraries in the symbol solver, you risk causing inappropriate symbol resolution strategies. This is what happens when classes have the same name in different packages.

For exemple to resolve proc.addSpeedStepTimes, symbol solver first search for methods declared in BatteryStatsImpl.Uid.Proc and all this ancestors. BatteryStatsImpl.Uid.Proc extends BatteryStats.Uid.Proc (which is located in an android library). The  BatteryStats.Uid.Proc resolution failed so it try to resolve Uid.Proc which is declared in BatteryStatsImpl. Then it tries to solve again BatteryStatsImpl.Uid.Proc... I think a quick workaround is to declare your library into the symbol solver.

    Uid.Proc proc = uid.getProcessStatsLocked("*wakelock*");
    proc.addSpeedStepTimes(cpuSpeedTimes);

**Comment by jlerbsc** [comment]
Hi @mf1832146 Did these tips help you?

**Comment by jlerbsc** [comment]
Hi @mf1832146 could you tell us if this issue is resolved?

**Comment by jlerbsc** [comment]
No comment so i think this issue is resolved.
