### ISSUE TITLE
Hi, in witch file i have to add the dependencies ??

### ISSUE THREAD

**Issue by frankpunx** [javaparser/javaparser#287]

**Comment by ftomassetti** [comment]
Can you give us more details?
JavaParser itself uses Maven, so if you would add dependency to JavaParser you should modify the pom.xml. However you probably not want to do that.
I suppose you want to _use_ JavaParser and it as a dependency to your project. How to do that depends on the build system you are using: Gradle, Maven, etc.
There are many tutorials to explain how to use those build systems.

Does it help?

**Comment by frankpunx** [comment]
Hi,
The reason im going to use javaparser is for a compiler project. Im not
sure how to view the project in a IDE.
On the Dependency Management it says to add the following to my maven
configuration.
I currently have maven installed but i don't know where to exactly put it.

It would be grate if you could help.
Thanks
Francisco

**Comment by ftomassetti** [comment]
I suggest to take a look to a Maven tutorial:
https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

Basically you have to add JavaParser among the dependency of your project,
in the pom.xml file.

Something like this should work:

```
<dependency>
  <groupId>com.github.javaparser</groupId>
  <artifactId>javaparser-core</artifactId>
  <version>2.3.0</version>
</dependency>
```

However you should familiarize with Maven first.

Cheers,
Federico

On 14 March 2016 at 09:39, frankpunx notifications@github.com wrote:

> Hi,
> The reason im going to use javaparser is for a compiler project. Im not
> sure how to view the project in a IDE.
> On the Dependency Management it says to add the following to my maven
> configuration.
> I currently have maven installed but i don't know where to exactly put it.
> 
> It would be grate if you could help.
> Thanks
> Francisco
> 
> On Fri, Mar 11, 2016 at 12:47 PM, Federico Tomassetti <
> notifications@github.com> wrote:
> 
> > Can you give us more details?
> > JavaParser itself uses Maven, so if you would add dependency to
> > JavaParser
> > you should modify the pom.xml. However you probably not want to do that.
> > I suppose you want to _use_ JavaParser and it as a dependency to your
> > project. How to do that depends on the build system you are using:
> > Gradle,
> > Maven, etc.
> > There are many tutorials to explain how to use those build systems.
> > 
> > Does it help?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/javaparser/javaparser/issues/287#issuecomment-195351684
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/javaparser/javaparser/issues/287#issuecomment-196204480
> .

## 

Website at http://tomassetti.me http://www.federico-tomassetti.it
GitHub https://github.com/ftomassetti

**Comment by ftomassetti** [comment]
I think we can close this one. Please contact us on gitter or open a new issue if you have further questions
