### ISSUE TITLE
Crash on annotated varargs parameter

### ISSUE THREAD

**Issue by jwaataja** [javaparser/javaparser#2879]
JavaParser has helped significantly in a project I'm working on, but I get a crash in one specific edge case. It occurs when a method takes a varargs parameter of primitive type with an annotation. I'm running this code.
```java
package test;

import com.github.javaparser.StaticJavaParser;

public class AnnotatedVarArgs  {
    public static void main(String[] args) {
        StaticJavaParser.parse(
                "import java.lang.annotation.*;" +
                "public class Test {" +
                "    public void method(int @MyAnno ... param) {}" +
                "}" +
                "@Target(ElementType.TYPE_USE) @interface MyAnno {}"
                );
    }
}
```

Here's the crash:
```
com.github.javaparser.ParseProblemException: (line 1,col 78) Parse error. Found "...", expected one of  "["
Problem stacktrace :
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10906)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10752)
  com.github.javaparser.GeneratedJavaParser.ArrayBracketPair(GeneratedJavaParser.java:1786)
  com.github.javaparser.GeneratedJavaParser.ReferenceType(GeneratedJavaParser.java:1739)
  com.github.javaparser.GeneratedJavaParser.Type(GeneratedJavaParser.java:1700)
  com.github.javaparser.GeneratedJavaParser.Parameter(GeneratedJavaParser.java:1462)
  com.github.javaparser.GeneratedJavaParser.Parameters(GeneratedJavaParser.java:1377)
  com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1225)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:961)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:852)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:409)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:152)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parse(JavaParser.java:306)
  com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
  test.AnnotatedVarArgs.main(AnnotatedVarArgs.java:7)
  org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
  java.base/java.lang.Thread.run(Thread.java:834)

    at com.github.javaparser.StaticJavaParser.handleResult (StaticJavaParser.java:260)
    at com.github.javaparser.StaticJavaParser.parse (StaticJavaParser.java:229)
    at test.AnnotatedVarArgs.main (AnnotatedVarArgs.java:7)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:834)
```

The parsed code compiles with javac, so I assume it's valid. The crash doesn't occur if I change `int` to `String` or `Object` so the problem seems to be unique to primitives.

JavaParser version 3.16.2
OpenJDK version 11.0.9

**Comment by jlerbsc** [comment]
This syntaxe doesn't generate ParseProblemException.

    public void method( int @MyAnnos[] ... param) {}


@maartenc, @MysterAitch,  i think (but I'm not sure) this PrimitiveType declaration generates this parsing exception.

	ReferenceType ReferenceType(NodeList<AnnotationExpr> annotations):
	{
		Type type;
		ArrayBracketPair arrayBracketPair;
		List<ArrayBracketPair> arrayBracketPairs = new ArrayList(0);
	}
	{
	  (
	   **type = PrimitiveType(annotations) ( LOOKAHEAD(Annotations() "[") arrayBracketPair = ArrayBracketPair(Origin.TYPE) { arrayBracketPairs=add(arrayBracketPairs, arrayBracketPair); } )+**
	  |
	   type = ClassOrInterfaceType(annotations)  ( LOOKAHEAD(Annotations() "[") arrayBracketPair = ArrayBracketPair(Origin.TYPE) { arrayBracketPairs=add(arrayBracketPairs, arrayBracketPair); } )*
	  )
	  { return (ReferenceType)wrapInArrayTypes(type, arrayBracketPairs); }
	}

**Comment by MysterAitch** [comment]
@jlerbsc I think you're not far off, but I don't believe it would be that part of the grammar.

See also this section which defines a "parameter": 
https://github.com/javaparser/javaparser/blob/f20d6fdc306bb8ae135e9a9639ca1b04acecd976/javaparser-core/src/main/javacc/java.jj#L1120-L1137

It definitely is not the most readable thing in the world, but it indicates that a parameter is defined as:

- a modifier (e.g. `final`), 
- followed by a type (defined elsewhere as primitive type or reference type), 
- optionally followed by `...`, and then 
- followed by the variable declarator id.

The values for these parts are then passed into the constructor for `new Parameter()`.


**This slightly reformatted version with additional linebreaks (one bullet point per line) may make things a little clearer.** 

```
Parameter Parameter():
{
	ModifierHolder modifier;
	Type partialType;
	boolean isVarArg = false;
	Pair<SimpleName, List<ArrayBracketPair>> id;
	NodeList<AnnotationExpr> varArgAnnotations = emptyList();
}
{
    modifier = Modifiers()
    partialType = Type(emptyList())
    [ varArgAnnotations = Annotations() "..." { isVarArg = true;} ]
    id = VariableDeclaratorId()
    {
        JavaToken begin = orIfInvalid(modifier.begin, partialType);
        return new Parameter(range(begin, token()), modifier.modifiers, modifier.annotations, juggleArrayType(partialType, id.b), isVarArg, varArgAnnotations, id.a);
    }
}
```


---

I'm a little rusty and had to google this to refresh, but note that the `[]` denotes that what it contains is optional, and the `{}` denotes java code that is executed. 
[more detail is available here](https://javacc.github.io/javacc/tutorials/examples.html)

![image](https://user-images.githubusercontent.com/1537214/98456249-540c9b00-2173-11eb-8066-133cc10d11b4.png)

**Comment by MysterAitch** [comment]
... or this commented version might make it more readable too: 

```java
    // EXAMPLES: 
    // methodCall(final int x)
    // methodCall(final int ... x)
    // methodCall(final Integer ... x)
    // methodCall(final Integer[] @P ... x)

    modifier = Modifiers() // e.g. `final`
    partialType = Type(emptyList()) // e.g. `int`, `Integer`, `Integer[]`
    [ varArgAnnotations = Annotations() "..." { isVarArg = true;} ] // e.g. `@P ...` OPTIONALLY (because of the [])
    id = VariableDeclaratorId() // e.g. `x`
```

**Comment by MysterAitch** [comment]
Here's the grammar defining parameters to a method declaration. 

It shows that the `...` may be preceeded by an annotation, but the identifier itself must not.

https://docs.oracle.com/javase/specs/jls/se15/html/jls-8.html#jls-8.4.1

```
FormalParameterList:
    FormalParameter {, FormalParameter}

FormalParameter:
    {VariableModifier} UnannType VariableDeclaratorId
    VariableArityParameter

VariableArityParameter:
    {VariableModifier} UnannType {Annotation} ... Identifier

VariableModifier:
    Annotation
    final
```

... And here is some experimentation re: confirming where parameters may be located:

![image](https://user-images.githubusercontent.com/1537214/98456636-0e060600-2178-11eb-8c55-9c2b7a6b82fe.png)

**Comment by MysterAitch** [comment]
Going up a level, here is the grammar for a method declaration:

```
MethodDeclaration:
    {MethodModifier} MethodHeader MethodBody

MethodHeader:
    Result MethodDeclarator [Throws]
    TypeParameters {Annotation} Result MethodDeclarator [Throws]

MethodDeclarator:
    Identifier ( [ReceiverParameter ,] [FormalParameterList] ) [Dims]

ReceiverParameter:
    {Annotation} UnannType [Identifier .] this


// The following production from §4.3 is shown here for convenience: 
Dims:
    {Annotation} [ ] {{Annotation} [ ]}
```


In terms of the JavaParser grammar here, there is some oddity going on with arraybracketpairs that I can't explain -- it's probably all fine, but `arrayBracketPair` and `arrayBracketPairs` are used later as parameters to `juggleArrayType()` which I haven't yet dug into.


```java
MethodDeclaration MethodDeclaration(ModifierHolder modifier):
{
	RangedList<TypeParameter> typeParameters = new RangedList<TypeParameter>(emptyList());
	Type type;
	SimpleName name;
	Pair<NodeList<Parameter>, ReceiverParameter> parameters = new Pair<NodeList<Parameter>, ReceiverParameter>(emptyList(), null);
	ArrayBracketPair arrayBracketPair;
	List<ArrayBracketPair> arrayBracketPairs = new ArrayList(0);
	NodeList<ReferenceType> throws_ = emptyList();
	BlockStmt body = null;
	NodeList<AnnotationExpr> annotations;
	JavaToken begin = modifier.begin;
	ReferenceType throwType;
}
{
    // Modifiers already matched in the caller!

    // https://docs.oracle.com/javase/specs/jls/se15/html/jls-8.html#jls-8.4

    // MethodHeader begins (option a) -- Result MethodDeclarator [Throws]
    // MethodHeader begins (option b) -- TypeParameters {Annotation} Result MethodDeclarator [Throws]
    [ typeParameters = TypeParameters() { begin = orIfInvalid(begin, typeParameters.range.getBegin()); } ]
    annotations = Annotations() { modifier.annotations.addAll(annotations); begin = orIfInvalid(begin, nodeListBegin(annotations)); }
    type = ResultType(emptyList()) { begin = orIfInvalid(begin, type); } // note that 'Result' is defined as a type OR void

    // MethodDeclarator begins -- Identifier ( [ReceiverParameter ,] [FormalParameterList] ) [Dims]
    name = SimpleName()
    parameters = Parameters()
    ( arrayBracketPair = ArrayBracketPair(Origin.NAME) { arrayBracketPairs=add(arrayBracketPairs, arrayBracketPair); } )* // TODO: What are these? How do they relate to the JLS grammar?
    // MethodDeclarator ends...

    // MethodHeader continues...
    [
        "throws" throwType = AnnotatedReferenceType() { throws_ = add(throws_, throwType); }
         ("," throwType = AnnotatedReferenceType() { throws_ = add(throws_, throwType); } )*
    ]
    ( body = Block() | ";" )
    {
        type = juggleArrayType(type, arrayBracketPairs);
        return new MethodDeclaration(range(begin, token()), modifier.modifiers, modifier.annotations, typeParameters.list, type, name, parameters.a, throws_, body, parameters.b);
    }
}
```

**Comment by MysterAitch** [comment]
> 
> 
> This syntaxe doesn't generate ParseProblemException.
> 
> ```
> public void method( int @MyAnnos[] ... param) {}
> ```
> 
> @maartenc, @MysterAitch, i think (but I'm not sure) this PrimitiveType declaration generates this parsing exception.
> 
> ```
> ReferenceType ReferenceType(NodeList<AnnotationExpr> annotations):
> {
> 	Type type;
> 	ArrayBracketPair arrayBracketPair;
> 	List<ArrayBracketPair> arrayBracketPairs = new ArrayList(0);
> }
> {
>   (
>    **type = PrimitiveType(annotations) ( LOOKAHEAD(Annotations() "[") arrayBracketPair = ArrayBracketPair(Origin.TYPE) { arrayBracketPairs=add(arrayBracketPairs, arrayBracketPair); } )+**
>   |
>    type = ClassOrInterfaceType(annotations)  ( LOOKAHEAD(Annotations() "[") arrayBracketPair = ArrayBracketPair(Origin.TYPE) { arrayBracketPairs=add(arrayBracketPairs, arrayBracketPair); } )*
>   )
>   { return (ReferenceType)wrapInArrayTypes(type, arrayBracketPairs); }
> }
> ```

... and in spite of everything I posted above, I suspect that I have just come full circle into (potentially) agreeing with you here! :D 

I see that the line you've added asterisks to for emphasis ends in `+` to indicate "one or more" array bracket pairs for primitive types, whereas the asterisk `*` is used for `ClassOrInterfaceType` to indicate "zero or more" array bracket pairs.

Maybe there is a deliberate distinction where an array of primitives is considered to be a reference type (noting that this is the `ReferenceType` section of the grammar)? 


I'm really not sure, but I suspect it's time for me to step away from the keyboard and rest! Maybe these notes will lead to an epiphany when they're read, maybe they'll not... Hopefully they'll be useful, but no worries if not!


Tomorrow I'll have a look at stepping through to see exactly what tokens are consumed at the point that the error is thrown to see if that gives any clues.
