### ISSUE TITLE
Using JavaParser in .Net 

### ISSUE THREAD

**Issue by Balawalbutt** [javaparser/javaparser#288]
Can we use   javaparser-core-2.3.0.jar through IKVM  In .net ? 
I Have converted the jar file successfully in .dll and  have added references correctly , but 
When i do this 

```
MyMethodVistor mv = new MyMethodVistor();
mv.visit(cu, null);
```

Call to *_visit() *_Just don't happen (because it do not print anything through messegeBox ), Any idea why  ?
or its not possible to use it in .net    ?

**Comment by ftomassetti** [comment]
I am really not familiar with IKVM. We could try to help if you show us the code of MyMethodVisitor

**Comment by Balawalbutt** [comment]
@ftomassetti  Thanku so much... i have resolved the issue , its working perfectly now, problem was in overriding ,

**Comment by ftomassetti** [comment]
Happy to hear that!
I think we can close this issue now.
