### ISSUE TITLE
Resolve a type from contex

### ISSUE THREAD

**Issue by alitarfa** [javaparser/javaparser#2881]
Hello friends, 
I have a Spring boot project and I want to parse it and file the dependencies  between classes I am using the JavaSymbolSolver to find out the Class Name 

```java
 public static void main(String[] args) throws Exception {

        Set<Map<String, Set<String>>> entries = new HashSet<>();
        String jdkPath = "/usr/lib/jvm/java-11-openjdk-amd64/";
        List<File> projectFiles = FileHandler.readJavaFiles(new File("/home/tarfa/MySpace/Tekit/soon-back/src/main"));
        CombinedTypeSolver combinedSolver = new CombinedTypeSolver
                (
                        new JavaParserTypeSolver(new File("/home/tarfa/MySpace/Tekit/soon-back/src/main/java/")),
                        new JavaParserTypeSolver(new File(jdkPath)),
                        new ReflectionTypeSolver()
                );

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
        CompilationUnit cu = null;

        try {
            cu = StaticJavaParser.parse(projectFiles.get(7));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        List<ClassOrInterfaceDeclaration> classes = new ArrayList<>();
        TypeDeclarationImp typeDeclarationImp = new TypeDeclarationImp();
        typeDeclarationImp.visit(cu, classes);
        Set<String> collect = classes.stream()
                .map(classOrInterfaceDeclaration -> {
                    List<MethodCallExpr> collection = new ArrayList<>();
                    MethodInvocationImp methodInvocationImp = new MethodInvocationImp();
                    classOrInterfaceDeclaration.accept(methodInvocationImp, collection);
                    return collection;
                })
                .flatMap(Collection::stream)
                .map(methodCallExpr -> {
                    return methodCallExpr
                            .getScope()
                            .stream()
                            .filter(Expression::isNameExpr)
                            .map(Expression::calculateResolvedType)
                            .map(ResolvedType::asReferenceType)
                            .map(ResolvedReferenceType::getQualifiedName)
                            .map(s -> s.split("\\."))
                            .map(strings -> strings[strings.length - 1])
                            .collect(Collectors.toSet());
                })
                .filter(expressions -> expressions.size() != 0)
                .flatMap(Collection::stream)
                .collect(Collectors.toSet());
        collect.forEach(System.out::println);
    }

```

I am facing this issue 

```
Exception in thread "main" UnsolvedSymbolException{context='SecurityContextHolder', name='Solving SecurityContextHolder', cause='null'}
```
- could you tell me if it is necessary to indicate all the libraries used by the project to parse it or there is another way for that

**Comment by jlerbsc** [comment]
Could you provide us a simple test case that isolates the problem please. What can we find in this place /usr/lib/jvm/java-11-openjdk-amd64/? libraries or source files?

**Comment by alitarfa** [comment]
-  /usr/lib/jvm/java-11-openjdk-amd64/? libraries or source files?
You can find the java JDK
- /home/tarfa/MySpace/Tekit/soon-back/src/main/java/ 
In this directory you find the source code

**Comment by jlerbsc** [comment]
Hi @alitarfa where the SecurityContextHolder class is declared? Is it a spring class?
I think that CombinedTypeSolver is badly initialized. For jar libraries you have to use JarTypeSolver and for java classes ReflectionTypeSolver generally does the job.

**Comment by alitarfa** [comment]
Hi @jlerbsc 
Yes, SecurityContextHolder is a spring class.
do you mean by using CombinedTypeSolver, I need to use JarTypeSolver like this 
```java
 CombinedTypeSolver combinedSolver = new CombinedTypeSolver
                (
                        new JavaParserTypeSolver(new File(projectPath))
                        new JarTypeSolver("the path to spring Jars"),
                        new ReflectionTypeSolver()
                );
```

-It's mandatory to specify all **Jars** used by the project? it there any way to avoid this?

**Comment by jlerbsc** [comment]
yes you are right. JarTypeSolver is used to solve classes in library (bytecode) and JavaParsertypeSolver is used to solve java source files. You can discover libraries automatically depending on whether you parse a maven project or other type org.jboss.shrinkwrap.resolve can help you.

**Comment by alitarfa** [comment]
@jlerbsc 
- My question now is it's mandatory to specify all **Jars** one by one like this ? or no.
- **Is there another way to resolve the dependencies from the pom.xml file of the maven project automatically**

```java
 CombinedTypeSolver combinedSolver = new CombinedTypeSolver
                (
                        new JavaParserTypeSolver(new File(projectPath))
                        new JarTypeSolver("path to jar_1"),
                        new JarTypeSolver("path to jar_1"),
                        new JarTypeSolver("path to jar_2"),
                        ..... etc 
                        new ReflectionTypeSolver()
                );
```

Because the project is so huge and uses a lot of Libraries it's so hard to specify all the jars files

**Comment by jlerbsc** [comment]
If you need to solve symbol you have to provide all entries to JavaSymbolSolver otherwise you may get errors UnsolvedSymbolException. Since it is a maven project i advise you to use org.jboss.shrinkwrap.resolve to find all dependencies from pom.xml files. 
Finally you can add JarTypeSolver from CombinedTypeSolver "public void add(TypeSolver typeSolver)" method.

**Comment by alitarfa** [comment]
@jlerbsc Thank you so much for your response I will try out the solution and I will come back

**Comment by alitarfa** [comment]
@jlerbsc 
- Is possible to parse a project if it has a compilation problem ? or there is no relation between the compilation and compilation

**Comment by jlerbsc** [comment]
To my knowledge this is not possible to parse a project if it has a compilation problem.

**Comment by alitarfa** [comment]
@jlerbsc Thanks

**Comment by jlerbsc** [comment]
Hi @alitarfa I'm closing this issue because it was not related to a real problem but you are free to open a new issue if you have another question.
