### ISSUE TITLE
findAll does not work correctly for Comment.class.

### ISSUE THREAD

**Issue by boyang9602** [javaparser/javaparser#2882]
[Testfile.txt](https://github.com/javaparser/javaparser/files/5498000/Testfile.txt)
Parse the attached file and call `List<Comment> comments = compilationUnit.findAll(Comment.class);`. It cannot get all the comments in the file.

**Comment by boyang9602** [comment]
Seems also for BodyDeclaration.class

**Comment by jlerbsc** [comment]
Hi @boyang9602 Did you try compilationUnit.getAllContainedComments()?

**Comment by boyang9602** [comment]
Yes. `getAllContainedComments()` works. I am wondering why `compilationUnit.findAll(Comment.class)` does not work.

**Comment by jlerbsc** [comment]
Certainly because some comments are tied to nodes while others are orphan comments

**Comment by boyang9602** [comment]
Oh ok, is that the expected behavior? Because from the API docs, I cannot get this information.

**Comment by jlerbsc** [comment]
It's clear for me. Could you close this issue if there is no more question please? 

    /**
     * This is the list of Comment which are contained in the Node either because
     * they are properly associated to one of its children or because they are floating
     * around inside the Node
     *
     * @return all Comments within the node as a list
     */

**Comment by boyang9602** [comment]
I mean the `findAll()`'s doc. It says 
```
public <T extends Node> List<T> findAll(Class<T> nodeType)
Walks the AST with pre-order traversal, returning all nodes of type "nodeType".
```

**Comment by jlerbsc** [comment]
You are right but there is another method which is more explicit on the management of comments.
