### ISSUE TITLE
JDK15 / JEP 371: Hidden Classes

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2886]
I'm not yet entirely clear on what exactly "hidden classes" are, but it looks like there's a chance JEP371 might introduce changes if they're available via reflection (the symbol solver), so this issues is a reminder to dig a bit deeper (and an invitation for others to comment if you know more than I do about them! :+1: ).

https://openjdk.java.net/jeps/371

> **Summary**
> Introduce hidden classes, which are classes that cannot be used directly by the bytecode of other classes. Hidden classes are intended for use by frameworks that generate classes at run time and use them indirectly, via reflection. A hidden class may be defined as a member of an access control nest, and may be unloaded independently of other classes.

**Comment by matozoid** [comment]
This look like a runtime feature to me, and can be happily ignored.

**Comment by MysterAitch** [comment]
From gitter: 

> Looks like some way to support people who want to write code that generates classes at runtime, so it is user code, running on the JVM, that is generating byte code to run on the same JVM, which can then be used only with reflection. Symbol solving is all about static, compile-time analysis, so this JEP would only be of interest if JP also had a JVM implementation :-)

**Comment by MysterAitch** [comment]
Seems like I'm overthinking it... :)

What I had in mind is something like:

```java
public static void main(String[] args) {

    // Do something to create a new class that is available via reflection

    // Use the dynamically created class...
    X x = new X();
    
}
```

It looks like my thoughts/worries were likely unfounded though, given this quote - emphasis mine: 

> It is important to realize that the only way for other classes to use a hidden class is indirectly, via its Class object. The hidden class cannot be used directly by bytecode instructions in other classes because it cannot be referenced nominally, that is, by name.
> [...]
> **Without the ability of the constant pool to refer nominally to a hidden class, there is no way to use a hidden class as a superclass, field type, return type, or parameter type.**
