### ISSUE TITLE
JEP 360: Sealed Classes (Preview)

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser#2888]
Multiple examples available at: https://openjdk.java.net/jeps/360

> **Summary**
> Enhance the Java programming language with sealed classes and interfaces. Sealed classes and interfaces restrict which other classes or interfaces may extend or implement them.

> **Description**
> A sealed class or interface can be extended or implemented only by those classes and interfaces permitted to do so.
> 
> A class is sealed by applying the sealed modifier to its declaration. Then, after any extends and implements clauses, the permits clause specifies the classes that are permitted to extend the sealed class. For example, the following declaration of Shape specifies three permitted subclasses:
> 
> ```
> package com.example.geometry;
> 
> public abstract sealed class Shape
>     permits Circle, Rectangle, Square {...}
> ```

> **Java Grammar**
> 
> ```
> NormalClassDeclaration:
>   {ClassModifier} class TypeIdentifier [TypeParameters]
>   [Superclass] [Superinterfaces] [PermittedSubclasses] ClassBody
> 
> ClassModifier:
>   (one of)
>   Annotation public protected private
>   abstract static sealed final non-sealed strictfp
> 
> PermittedSubclasses:
>   permits ClassTypeList
> 
> ClassTypeList:
>   ClassType {, ClassType}
> ```

**Comment by FeldrinH** [comment]
With https://github.com/javaparser/javaparser/pull/3997 merged and released, is there more to do or are sealed classes now fully supported in JavaParser?

**Comment by jlerbsc** [comment]
To my knowledge, sealed classes are supported. Did you find any errors?

**Comment by FeldrinH** [comment]
No, but the codebases that I analyse don't have many sealed classes. I was just wondering if this issue could be closed.

**Comment by jlerbsc** [comment]
"sealed is just a modifier. This issue can be closed.
