### ISSUE TITLE
EnumConstantDeclaration always prints the body {}

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#289]
Hello guys, I would love that the enums constants doesn't have a body {} if nothing is in the ClassBody list. 

Using setClassBody(null); doesn't work because of the ensureNotNull in the getter.

Therefore in DumpVisitor line 1278 `if (n.getClassBody() != null)` never works... I would love to see a `&& n.getClassBody().size != 0` in that condition.

**Comment by ftomassetti** [comment]
~~We have already solved a few of such issues but this is yet open.~~
This has been corrected already:

```
        if (!n.getClassBody().isEmpty()) {
            printer.printLn(" {");
            printer.indent();
            printMembers(n.getClassBody(), arg);
            printer.unindent();
            printer.printLn("}");
        }
```

It will be in the new release (@matozoid is working on it)
