### ISSUE TITLE
Differentiate between the two child classes which extends the same super class 

### ISSUE THREAD

**Issue by f71uday** [javaparser/javaparser#2890]
Here is a sample class for which I am building an AST using JavaParser , then trying to resolve the function calls using JavaSymbolSolver
```
import java.util.Random;
import java.security.SecureRandom;
class MyClass {   
    public int returnSomeValue(int maximumValue) {=

        Random r = new Random();  
        SecureRandom s = new SecureRandom();
        int b = s.nextInt(); // securerandom number
        int a = r.nextInt(); // random number
        return a+b;

    }
}
```

If I am trying to resolve method calls `nextInt()`  in above code snippet using using below  code 

```
 List<MethodCallExpr> methodCallExprs = compilationUnit.findAll(MethodCallExpr.class); 
 methodCallExprs.forEach(methodCallExpr -> resolveMethodCall(methodCallExpr));



 private static void resolveMethodCall(MethodCallExpr methodCallExpr) {
      String s =   methodCallExpr.resolve().getQualifiedSignature();
      LOG.info(s);
    }
```

but both method calls get resolved as `java.util.Random.nextInt()` , I think this is because `SecureRandom` Class in Java extends `Random` Class, but then how do I differentiate between these two method calls.

**Comment by MysterAitch** [comment]
`MethodUsage` has a method `getDeclaration()`. From there, you can determine which class / compilation unit the declaration exists within. 

Hope this helps! If not, or if I've misunderstood your question, let us know and we'll get you a fuller reply :)

**Comment by f71uday** [comment]
Thnaks @MysterAitch , it worked!.
