### ISSUE TITLE
Unexpected result when solving an outer class reference

### ISSUE THREAD

**Issue by deadlocklogic** [javaparser/javaparser#2909]
Consider this example:
```java
package test;

public class Program {

    public class OuterClass {
        int field = 0;

        public class InnerClass {
            InnerClass() {
                OuterClass outer = OuterClass.this;
                OuterClass.this.field = 1;
            }
        }
    }
}
```
Using a visitor on the compilation unit, when reaching the `ThisExpr` node and resolving the node with `calculateResolvedType()` the `ResolvedType` corresponds unexpectedly to the `OuterClass.InnerClass`.
Of course, the expected type should've been `OuterClass` as `OuterClass.this` references the outer class.
Looks like the SymbolSolver is erroneously dismissing `ThisExpr`'s typename.

Any thoughts on this? Is it a bug or I am missing something?

**Comment by deadlocklogic** [comment]
**Edit:**
Actually using fully qualified class name yields correct result when `ThisExpr `is solved.
```java
package test;

public class Program {

    public class OuterClass {
        int field = 0;

        public class InnerClass {
            InnerClass() {
               OuterClass outer = test.Program.OuterClass.this;
               test.Program.OuterClass.this.field = 1;
            }
        }
    }
}
```
So it is actually a bug, 

I am trying to dig the code responsible for it.
I found this method to branch differently between these 2 cases and I think it is where the issue lies:
https://github.com/javaparser/javaparser/blob/e3240fc48b1ed205fa90009f698a60adf58d66f1/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java#L361-L383

I will try to investigate further hoping I can fix the underlying problem.

**Comment by jlerbsc** [comment]
Thanks for reporting this issue.

**Comment by deadlocklogic** [comment]
With pleasure, by the way javaparser-core is really mature and robust!
My issue is within symbol-solver, many other problems I am facing with it so far (some are duplicates).

Actually, going a lit bit deeper in `JavaParserTypeSolver` I found this method to be surprisingly worrisome :
```java
private SymbolReference<ResolvedReferenceTypeDeclaration> tryToSolveTypeUncached(String name)
```
It tries to resolve the class type from name by fetching in the source directory for a direct match, which is clever when used as a last ditch attempt but not early on as it is in its current state.
So In my case defining another class in the default package as:
```java
//Notice: default package
public class OuterClass {
    int field = 0;
}
```
Now `OuterClass.this` of the preview example refers to the class in the default package, which is even wrong.
Maybe class testing should bubble up from an inner class to its parent (and so on) and dive through if the name split matches until a complete match.
If no match is found then switch to a different strategy like querying and parsing from source directory. 

And in worst cases if no strategy works, I think throwing an exception is rather appropriate than returning a faulty reference of the declaring class of `ThisExpr`.

**Comment by jlerbsc** [comment]
I can suggest a patch that fixes this bug but I'm not sure it fixes all similar cases

**Comment by deadlocklogic** [comment]
Hey guys, I tried this patch and it worked to this specific test but still didn't solve the initial problem when full qualified `OuterClass` name isn't provided.
The test works of course as in: https://github.com/javaparser/javaparser/blob/efb242d42b3e165115f31f18c44cd4a6abbc228d/javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue2909Test.java#L25-L37
Now try to change it to:
```
    "public class Program {\n" +
    "\n" +
    "    public class OuterClass {\n" +
    "        int field = 0;\n" +
    "\n" +
    "        public class InnerClass {\n" +
    "            InnerClass() {\n" +
    "               OuterClass outer = OuterClass.this;\n" +
    "               OuterClass.this.field = 1;\n" +
    "            }\n" +
    "        }\n" +
    "    }\n" +
    "}"
```
Which is perfectly legal java-wise, now the test fails with this exception:
```
java.lang.IllegalStateException: Parent not found, the node does not appear to be inserted in a correct AST

	at com.github.javaparser.symbolsolver.javaparser.Navigator.lambda$demandParentNode$3(Navigator.java:147)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at com.github.javaparser.symbolsolver.javaparser.Navigator.demandParentNode(Navigator.java:147)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:644)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.findContainingTypeDeclOrObjectCreationExpr(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:380)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:97)
	at com.github.javaparser.ast.expr.ThisExpr.accept(ThisExpr.java:77)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:566)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:398)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:380)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:281)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:564)
        ...
```
Still there are few corner cases to the problem which need appropriate tests. I will try to scratch my head around and see if I can submit a PR.

**Comment by jlerbsc** [comment]
This implementation can be refactored in CompilationUnit to provide a new method that can get a local ClassOrInterfaceDeclaration from a class name. Actually the method getClassByName(..) tries to get a top level class declaration by its name.

**Comment by deadlocklogic** [comment]
Sorry to bump this issue again but still the patch works for this specific test. I will try giving a general test including different corner cases and what needs to be changed. Actually I patched this issue on my other machine but can't submit a PR right now.
### Defects with the current implementation:

**1.** Any class in the default package sharing same `typeName` of `ThisExpr` to be resolved is automatically considered as match which is wrong.
**Example:**
```java
//default package
public class OuterClass {
}
```
and
```java
package test;

public class Program {

    public class OuterClass {
        int field = 0;

        public class InnerClass {
            InnerClass() {
                // Different cases to refer to enclosing type
                OuterClass outer1 = OuterClass.this; // case1
                OuterClass.this.field = 1; // case1
                OuterClass outer2 = Program.OuterClass.this; // case2
                Program.OuterClass.this.field = 1; // case2
                OuterClass outer3 = test.Program.OuterClass.this; // case3
                test.Program.OuterClass.this.field = 1; // case3
            }
        }
    }
}
```
Now resolving **case1** will automatically return `OuterClass` of the default package which is **wrong**. (Keep in mind that we are using a `CombinedTypeSolver` here consisting of `ReflectionTypeSolver` and `JavaParserTypeSolver`)
This is because in the `TypeExtractor.java` we are first trying to resolve using a typeSolver which should be done as a second step not first.

**2.** Lets go one level deeper in nesting these inner classes and introduce a top class `FarOuterClass` (we can dismiss the `OuterClass` in the default package)
```java
package test;

public class Program {

    public class FarOuterClass {

        public class OuterClass {
            int field = 0;

            public class InnerClass {
                InnerClass() {
                    // Different cases to refer to enclosing type
                    OuterClass outer1 = OuterClass.this; // case1
                    OuterClass.this.field = 1; // case1
                    OuterClass outer2 = FarOuterClass.OuterClass.this; // case2
                    FarOuterClass.OuterClass.this.field = 1; // case2
                    OuterClass outer3 = Program.FarOuterClass.OuterClass.this; // case3
                    Program.FarOuterClass.OuterClass.this.field = 1; // case3
                    OuterClass outer4 = test.Program.FarOuterClass.OuterClass.this; // case4
                    test.Program.FarOuterClass.OuterClass.this.field = 1; // case4
                }
            }
        }
    }
}
```
This test fails too, all `ThisExpr` should refer to `test.Program.FarOuterClass.OuterClass` which is not always true

**3.** Lets add an `OuterClass` in the top level hierarchy
```java
package test;

public class Program {

    public class OuterClass {
    }

    public class FarOuterClass {

        public class OuterClass {
            int field = 0;

            public class InnerClass {
                InnerClass() {
                    // Different cases to refer to enclosing type
                    OuterClass outer1 = OuterClass.this; // case1
                    OuterClass.this.field = 1; // case1
                    OuterClass outer2 = FarOuterClass.OuterClass.this; // case2
                    FarOuterClass.OuterClass.this.field = 1; // case2
                    OuterClass outer3 = Program.FarOuterClass.OuterClass.this; // case3
                    Program.FarOuterClass.OuterClass.this.field = 1; // case3
                    OuterClass outer4 = test.Program.FarOuterClass.OuterClass.this; // case4
                    test.Program.FarOuterClass.OuterClass.this.field = 1; // case4
                }
            }
        }
    }
}
```
This test fails also, it will resolve in some cases as: `test.Program.OuterClass`

### Patch
### Test
First I created a simple class name `OuterClass.java` in **resources/issue2909**
```java
public class OuterClass {
}
```
In `Issue2909Test.java`, I added a generic test
```java
@Test
void genericTest() {
    Path rootSourceDir = adaptPath("src/test/resources/issue2909");

    ParserConfiguration config = new ParserConfiguration();
    CombinedTypeSolver cts = new CombinedTypeSolver(new ReflectionTypeSolver(false), new JavaParserTypeSolver(rootSourceDir.toFile()));
    config.setSymbolResolver(new JavaSymbolSolver(cts));
    StaticJavaParser.setConfiguration(config);

    String s =
            "package test;\n" +
                    "\n" +
                    "public class Program {\n" +
                    "\n" +
                    "    public class OuterClass {\n" +
                    "    }\n" +
                    "\n" +
                    "    public class FarOuterClass {\n" +
                    "\n" +
                    "        public class OuterClass {\n" +
                    "            int field = 0;\n" +
                    "\n" +
                    "            public class InnerClass {\n" +
                    "                InnerClass() {\n" +
                    "                    // Different cases to refer to enclosing type\n" +
                    "                    OuterClass outer1 = OuterClass.this; // case1\n" +
                    "                    OuterClass.this.field = 1; // case1\n" +
                    "                    OuterClass outer2 = FarOuterClass.OuterClass.this; // case2\n" +
                    "                    FarOuterClass.OuterClass.this.field = 1; // case2\n" +
                    "                    OuterClass outer3 = Program.FarOuterClass.OuterClass.this; // case3\n" +
                    "                    Program.FarOuterClass.OuterClass.this.field = 1; // case3\n" +
                    "                    OuterClass outer4 = test.Program.FarOuterClass.OuterClass.this; // case4\n" +
                    "                    test.Program.FarOuterClass.OuterClass.this.field = 1; // case4\n" +
                    "                }\n" +
                    "            }\n" +
                    "        }\n" +
                    "    }\n" +
                    "}";

    CompilationUnit cu = StaticJavaParser.parse(s);
    List<ThisExpr> exprs = cu.findAll(ThisExpr.class);
    exprs.forEach(expr -> {
        assertEquals("test.Program.FarOuterClass.OuterClass", expr.calculateResolvedType().describe());
    });
}
```
### Changes:
In Java `JavaParserFacade`, I created 2 methods:
```java
protected TypeDeclaration<?> findContainingTypeDecl(Node node, String className) {
    return findContainingTypeDecl(node, className, node.findCompilationUnit().map(cu -> cu.getPackageDeclaration().map(pd -> pd.getNameAsString()).orElse("")), "", null);
}

protected TypeDeclaration<?> findContainingTypeDecl(Node node, String className, Optional<String> packageName, String pseudoName, TypeDeclaration<?> result) {
    if (node instanceof TypeDeclaration) {
        boolean flagMatches = false;
        TypeDeclaration<?> typeDecl = (TypeDeclaration<?>) node;
        if (typeDecl.getFullyQualifiedName().isPresent()) {
            if (typeDecl.getFullyQualifiedName().get().equals(className)) {
                return typeDecl;
            } else {
                if (packageName.isPresent() && typeDecl.getFullyQualifiedName().get().equals(packageName.get() + "." + className)) {
                    return typeDecl;
                } else {
                    if (pseudoName.isEmpty()) {
                        result = typeDecl;
                        pseudoName = typeDecl.getNameAsString();
                    } else {
                        pseudoName = typeDecl.getNameAsString() + "." + pseudoName;
                    }
                    if (className.endsWith(pseudoName)) {
                        if (className.equals(pseudoName)) {
                            return result;
                        }
                        flagMatches = true;
                    }
                }
            }
        }
        if (!flagMatches) {
            pseudoName = "";
        }
    } else if (node instanceof LocalClassDeclarationStmt) {
        pseudoName = "";
    } else if (node instanceof ObjectCreationExpr) {
        pseudoName = "";
    }
    return findContainingTypeDecl(demandParentNode(node), className, packageName, pseudoName, result);
}
```
In `TypeExtractor.java` the following method is changed:
```java
@Override
public ResolvedType visit(ThisExpr node, Boolean solveLambdas) {
    // If 'this' is prefixed by a class eg. MyClass.this
    if (node.getTypeName().isPresent()) {
        // Get the class name
        String className = node.getTypeName().get().asString();

        // Attempt to resolve locally in Compilation unit
        try {
            return new ReferenceTypeImpl(facade.getTypeDeclaration(facade.findContainingTypeDecl(node, className)), typeSolver);
        } catch (Exception e) {
        }

        // Attempt to resolve using a typeSolver
        SymbolReference<ResolvedReferenceTypeDeclaration> clazz = typeSolver.tryToSolveType(className);
        if (clazz.isSolved()) {
            return new ReferenceTypeImpl(clazz.getCorrespondingDeclaration(), typeSolver);
        }
        throw new IllegalStateException("Couldn't resolve typeName of ThisExpr: " + className);
    }
    return new ReferenceTypeImpl(facade.getTypeDeclaration(facade.findContainingTypeDeclOrObjectCreationExpr(node)), typeSolver);
}
```

Plus I removed the unused methods of patches: #2911 #2914 #2920
So as I commented before, the implementation should bubble up from `ThisExpr`'s node and not find classes directly from higher hierarchy.
Sorry again, that I couldn't submit a PR because I am setting up my new machine.
By the way, I am using _javaparser_ to build a java tool and a transpiler, so I can give you a lot of feedback especially concerning _symbolSolver_.

**Comment by jlerbsc** [comment]
Do you agree with these results?

    OuterClass.this is resolved to test.Program.OuterClass
    OuterClass.this is resolved to test.Program.OuterClass
    FarOuterClass.OuterClass.this is resolved to test.Program.FarOuterClass.OuterClass.InnerClass
    FarOuterClass.OuterClass.this is resolved to test.Program.FarOuterClass.OuterClass.InnerClass
    Program.FarOuterClass.OuterClass.this is resolved to test.Program.FarOuterClass.OuterClass.InnerClass
    Program.FarOuterClass.OuterClass.this is resolved to test.Program.FarOuterClass.OuterClass.InnerClass
    test.Program.FarOuterClass.OuterClass.this is resolved to test.Program.FarOuterClass.OuterClass.InnerClass
    test.Program.FarOuterClass.OuterClass.this is resolved to test.Program.FarOuterClass.OuterClass.InnerClass

**Comment by deadlocklogic** [comment]
All the results should return `test.Program.FarOuterClass.OuterClass`

**Comment by deadlocklogic** [comment]
I believe my workaround is the correct solution not because just all the tests passes, but because this is how inner classes should be resolved, keeping in mind that `this` can only point to instance class, or instance enclosing class.
So we should first check if **_typename_**.`this` refers to a local class (be it member or enclosing) by bubbling through the hierarchy and last we should use the symbol-solver available (in case of **_typename_**.`this` in an ObjectCreationExpr). If both fail, we should throw an exception because we couldn't resolve it.

**Comment by jlerbsc** [comment]
Thank you for providing us with such a rich test case.

**Comment by deadlocklogic** [comment]
No problem.
But the test should be:
```java
Path rootSourceDir = adaptPath("src/test/resources/issue2909");

ParserConfiguration config = new ParserConfiguration();
CombinedTypeSolver cts = new CombinedTypeSolver(new ReflectionTypeSolver(false), new JavaParserTypeSolver(rootSourceDir.toFile()));
config.setSymbolResolver(new JavaSymbolSolver(cts));
StaticJavaParser.setConfiguration(config);
```
instead of (other than that the OuterClass.java in the default package makes no sense):
https://github.com/javaparser/javaparser/blob/818946fa5d9a5a6cb1aa19058b8b44be38ae2cfb/javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue2909Test.java#L76-L78

**Comment by deadlocklogic** [comment]
Ok so now I set up my machine, I am back on my horse. Here is PR #2928 where I give an example which breaks your implementation. Please no offense, but I am easily figuring out counter-arguments because I worked out the correct solution myself. Of course I saw your attempt to search this time with using `endsWith`, and from bottom of the hierarchy, I repeat once again this simple approach won't work because simply I can switch the place of the top-most `OuterClass` and break the implementation. Remember we need to make a foolproof implementation which doesn't break too easily and isn't bound by code-style etc...

**Comment by jlerbsc** [comment]
Hi @deadlocklogic Thanks for this work. Did you try to run all the unit tests of the project before doing your PR?

**Comment by deadlocklogic** [comment]
Yes, they passed for the current test, but the method `test` was incomplete as I stated before, you forgot to include a `JavaParserTypeSolver` as it should be
```java
Path rootSourceDir = adaptPath("src/test/resources/issue2909");

ParserConfiguration config = new ParserConfiguration();
CombinedTypeSolver cts = new CombinedTypeSolver(new ReflectionTypeSolver(false), new JavaParserTypeSolver(rootSourceDir.toFile()));
config.setSymbolResolver(new JavaSymbolSolver(cts));
StaticJavaParser.setConfiguration(config);
```
What the point of creating `OuterClass.java` in the default package in `resources/issue2909` if not using it in the solver then?
Yes I even added a new test that it will fail will the default implementation.

**Comment by deadlocklogic** [comment]
You can check my PR #2928, I dissected every step possible, it is not that huge PR thought, 10 min at best you will figure out all the changes and what is wrong with this current implementation.

**Comment by jlerbsc** [comment]
From my point of view this issue can be closed. A simple solution was found to the problem posed. Of course you are free to open a new issue if you encounter a problem again.

**Comment by deadlocklogic** [comment]
You know what? The word **simple solution** struck me like a thunder😛 So I had to restore my dignity as a tester.
This test fails:
```java
@Test
void testInDepth() {
    Path rootSourceDir = adaptPath("src/test/resources/issue2909");

    ParserConfiguration config = new ParserConfiguration();
    CombinedTypeSolver cts = new CombinedTypeSolver(new ReflectionTypeSolver(false), new JavaParserTypeSolver(rootSourceDir.toFile()));
    config.setSymbolResolver(new JavaSymbolSolver(cts));
    StaticJavaParser.setConfiguration(config);

    String s = "package test;\n" +
            "public class Program {\n" +
            "\n" +
            "    public class OuterClass {\n" +
            "        int field = 0;\n" +
            "\n" +
            "        public class IntermediateClass {\n" +
            "            \n" +
            "            public class InnerClass {\n" +
            "                InnerClass() {\n" +
            "                    // Different cases to refer to enclosing type\n" +
            "                    OuterClass outer1 = OuterClass.this; // case1\n" +
            "                    OuterClass.this.field = 1; // case1\n" +
            "                    OuterClass outer2 = Program.OuterClass.this; // case2\n" +
            "                    Program.OuterClass.this.field = 1; // case2\n" +
            "                    OuterClass outer3 = test.Program.OuterClass.this; // case3\n" +
            "                    test.Program.OuterClass.this.field = 1; // case3\n" +
            "                }\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

    CompilationUnit cu = StaticJavaParser.parse(s);
    List<ThisExpr> exprs = cu.findAll(ThisExpr.class);
    exprs.forEach(expr -> {
        System.out.println(String.format("%s is resolved to %s", expr.toString(), expr.calculateResolvedType().describe()));
        assertEquals("test.Program.OuterClass", expr.calculateResolvedType().describe());
    });
}
```

**Comment by jlerbsc** [comment]
Where is the error?

    OuterClass.this is resolved to test.Program.OuterClass
    OuterClass.this is resolved to test.Program.OuterClass
    Program.OuterClass.this is resolved to test.Program.OuterClass
    Program.OuterClass.this is resolved to test.Program.OuterClass
    test.Program.OuterClass.this is resolved to test.Program.OuterClass
    test.Program.OuterClass.this is resolved to test.Program.OuterClass

**Comment by deadlocklogic** [comment]
Oh snap! I thought I pulled yesterday after you merged. My mistake!!! Yes indeed all tests pass, including this one. So I think this issue should be solved.
