### ISSUE TITLE
I dont know if i'm doing it right or not but ConditionalExpr is not giving correct output.

### ISSUE THREAD

**Issue by flouthoc** [javaparser/javaparser#292]
When i do this

``` java
public void visit(IfStmt n, Object arg){
                        System.out.println(n.getThenStmt().toString());
                        super.visit(n, arg);
                }
```

it works but when i try to do the same thing via **ConditionalExpr it does not prints anything**

``` java
public void visit(ConditionalExpr n, Object arg){
                        System.out.println(n.getThenExpr().toString());
                        super.visit(n, arg);
                }
```

**Comment by ftomassetti** [comment]
Can you give us more details? We need to first verify if the method is invoked. If it is, why it prints an empty string.

**Comment by flouthoc** [comment]
I dont know what should conditional expression parse , if i'm interpreting (understanding) it correctly then in this following java code

``` java
public class{
         public static void main(String args[]){
             int foo = 3;
             if(foo)
                  System.out.println("Hello");
         }
}
```

``` java
public void visit(ConditionalExpr n, Object arg){
                        System.out.println(n.getThenExpr().toString());
                        super.visit(n, arg);
                }
```

It should print  `System.out.println("hello");` but it prints nothing however
IfStmt works correctly

``` java
public void visit(IfStmt n, Object arg){
                        System.out.println(n.getThenStmt().toString());
                        super.visit(n, arg);
                }
```

also i guess if **Conditional Expression** here means  **Ternary Expression**  then this issue must be closed cause i think i'm misinterpreting conditional expression with If-else like statements.

Thanks

**Comment by ftomassetti** [comment]
Hi @flouthoc I think you are right, ConditionalExpr is `a ? b : c`

Sorry for the late answer!

Closing.
