### ISSUE TITLE
The method "getArgs" in "ObjectCreationExpr" class doesn't ensure null list

### ISSUE THREAD

**Issue by JaviRpo** [javaparser/javaparser#293]
The method "getArgs" in "ObjectCreationExpr" class doesn't ensure null list

**Comment by mmuesly** [comment]
I had the same problem. It could be solved by adding a line, but I don't know what the desired behavior is. Please have a look at #295 or add a comment to the source code, if the null value is desired.

**Comment by ftomassetti** [comment]
There are just a few cases in which null is a valid value (it tells us something). Probably this is not one of those cases (in which we should use our own Optional anyway: we cannot use the standard Optional because it was introduced after Java 6 and for now we are Java 6 compatible).

**Comment by matozoid** [comment]
It seems we merged this already with #295
