### ISSUE TITLE
How do I resolve MethodCallExpr in a. Java file when I don't have the original Java project file

### ISSUE THREAD

**Issue by Elfe-w** [javaparser/javaparser#2932]
hello,I want to get the function signature information of the called function in. Java file (such as the name of the function, parameter type, etc.), but when using JavaParserTypeSolver,MethodCallExprs that are in the same package but different Java files can be parsed correctly if the input path is one level above the package path. If there is packages only Java file, how should I deal with it?

Test file is:animal.java
```
package sampleMyself;
import java.util.*;
public class animal {
	private String type="";
	public animal(){
	type="tiger";
	}
	public animal(String type)
	{
	this.type = type;
	}
	public String toString(){
	return type;
	}
	public void sound(int a){
	}
	public static  String testString(int a){
		return "hhhh ";
		}
	public static  String maybe(java.lang.Object a){
		return "hhhh ";
		}
	public static test test1(){
		
		String ss="oo,pp,uu,yy";
		String aa[]=ss.split(",");
		System.out.print(aa[aa.length-1]);
		test a=new test();
		return a;
	}
	public static void main(String[] args) {
	test1();
	animal a1 = new animal();
	System.out.println(a1);
	a1.sound(3);
	animal a2 = new animal("panda");
	System.out.println(a2);
	a2.sound(4);
	String x=testString(3);
	}
}
class test{
	int a;
	 test(){
		
	}
	 test(int a){
			this.a=a;
		}
	 public void testSetage(int a){
		 
	 }
}
```
person.java:
```

package sampleMyself;

public class person {
	 private String name;
	 
	    private String sex;
	 
	    private int age;
	 
	    
	 
	    public person()
	 
	    {
	 
	        name = null;
	 
	        sex = null;
	 
	        age = 0;
	 
	    }
	 
	    public void setName(String n)
	 
	    {
	 
	        name = n;
	  
	    }
	 
	    public void setSex(String s)
	 
	    {
	 
	        sex = s;
	        setAge(4);
	 
	    }
	 
	    public void setAge(int a)
	 
	    {
	 
	        age = a;
	        test();
	 
	    }
	 
	    public void print()
	 
	    {
	 
	        System.out.println("name:"+name+"; sex:"+sex+"; age:"+age);
	 
	    }
	    public int test(){
	    	int a=9;	    
	    	String s="00000000000";
	    	//twoP(a,s);
	    	return a;
	    }
	    public animal twoP2(int a,String s){
	    	setAge(4);
	    	animal xx=new animal();
	    	return xx;
	    }
	    public animal twoP(int a,String s){
	    	setAge(4);
	    	animal xx=new animal();
	    	test(xx,3);
	    	return xx;
	    }
	    public void test(animal a,int x){
	    	System.out.println("hhhhhh");
	    	test();
	    }
}
```

Modify the SourceFileInfoExtractor.toString to output function call information that cannot be resolved properly:

```
 private String toString(MethodCallExpr node) {
        try {
            return toString(JavaParserFacade.get(typeSolver).solve(node));
        } catch (Exception e) {
        	System.out.println("I am failed: "+String.valueOf(node));
            if (verbose) {
                System.err.println("Error resolving call at L" + lineNr(node) + ": " + node);
                e.printStackTrace();
            }
            return "ERROR";
        }
    }
```

The code used for parsing is:
```
`Path src=Paths.get("E:/test/");
    	CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
    	
    	combinedTypeSolver.add(new ReflectionTypeSolver());
    	combinedTypeSolver.add(new JavaParserTypeSolver(src));
    	
    	SourceFileInfoExtractor sourceFileInfoExtractor = new SourceFileInfoExtractor(combinedTypeSolver);
    	 try {
         	methodInfo=sourceFileInfoExtractor.solveMethodCalls(src);  
         	//sourceFileInfoExtractor.solve(src1);
 		} catch (IOException e) {
 			// TODO Auto-generated catch block
 			e.printStackTrace();
 		}`
```
when `Path src=Paths.get("E:/test/");`I'll get this

```
`- parsing E:\test\src\sampleMyself\animal.java
- parsing E:\test\src\sampleMyself\person.java
I am failed: test()
I am failed: test(xx, 3)
I am failed: test()`

```
when `Path src=Paths.get("E:/test/src");`I'll get this:

```
`- parsing E:\test\src\sampleMyself\animal.java
- parsing E:\test\src\sampleMyself\person.java`

```
when `Path src=Paths.get("E:/test/src/sample");`I'll get this:
```
`- parsing E:\test\src\sampleMyself\animal.java
- parsing E:\test\src\sampleMyself\person.java
I am failed: test()
I am failed: test(xx, 3)
I am failed: test()`
```

That means that only functions that are in the same package but different Java files can be parsed correctly if the path is one level above the package path, right?Can you solve this problem if only Java files don't know the package path?

**Comment by jlerbsc** [comment]
Hi @Elfe-w you have to setup JavaParserTypeSolver with the root path to the source directory. In your case it's e:/test/src

**Comment by Elfe-w** [comment]
Thank you for your prompt reply, but are there any other solutions?

**Comment by jlerbsc** [comment]
Have you try a test with the correct setup of the JavaParserTypeSolver ?

**Comment by Elfe-w** [comment]
Do you mean set it like this:Path src=Paths.get("E:/test/src")?Yes, I tested it this way and got the right results, but there was no way I could create a root path for each file with a large number of Java files.

**Comment by jlerbsc** [comment]
You need to initialize a JavaParserTypeSolver (with the root path of java files) for each source root. For example for a classic maven project if you want to parse (and resolve) main and test source files you have to setup a JavaParserTypeSolver for each directory. that's all.

    new JavaParserTypeSolver("src/main/java");
    new JavaParserTypeSolver("src/test/java");

**Comment by Elfe-w** [comment]
Ok, thank you for your answer.

**Comment by jlerbsc** [comment]
When I reread your question in fact I realize that I do not understand what you want?

     If there is packages only Java file, how should I deal with it?

**Comment by Elfe-w** [comment]
Oh sorry, I made a mistake, it should be: no package paths just Java files.
For example, I have  two Java files, and if I want to initialize a JavaParserTypeSolver  for each source root, I have to open it and look at its Packagename to create its root path.like this:
```
package a.b.c.d;
public class test1{
    public void  f1(int x){
         x=9;
  }
}
```
```
package a.b.c.d;
public class test2{
    public void   f2(){
         int x=7;
         f1(x);
  }
```
}
But with a large number of Java files, it is very difficult to initialize a JavaParserTypeSolver for each source path

**Comment by jlerbsc** [comment]
Not "each source path" but each root source path in your case there seems to be only one root source path "E:/test/src"

**Comment by Elfe-w** [comment]
OK，I got that.

**Comment by jlerbsc** [comment]
if you have no more questions maybe you can close this issue

**Comment by MysterAitch** [comment]
> But with a large number of Java files, it is very difficult to initialize a JavaParserTypeSolver for each source path

If you have multiple source roots, this article is helpful:

https://javaparser.org/setting-up-for-analysing-a-whole-project/

It sounds like this isn't quite what you're asking about though -- is it correct that you have all source files within the same folder?

JavaParser does assume that all files are to be found in the correct directory structure (one that matches the packages).

This would be an interesting feature to have though.


-----

Pre-edit: One (incomplete but immediate) solution is to pre-process the source files, removing (or changing) the package so that they're all the same. That would mean all source files, and the directory, are the same - enabling resolution to occur. Depending on your goal, this might be enough.

**Comment by Elfe-w** [comment]
Ah, thank you for your solution. The problem you are talking about is exactly what I have encountered.I apologize for my inaccurate question and thank you for your help.
