### ISSUE TITLE
Extracting all Java Methods in a Java File (i.e. myFile.Java)

### ISSUE THREAD

**Issue by cyberjj999** [javaparser/javaparser#2934]
Hi everyone, I would love like to extract all Java Methods in a Java File as mentioned in the title of this question.
To give an example of what I mean

```
public static List<String> getLinks(String url) throws IOException {
    List<String> result = new ArrayList<String>();
    Document doc = Jsoup.connect(url).get();
    Elements links = doc.select("a");
    for (Element link : links) {
      result.add(link.absUrl("href"));
    }
    return result;
  }

  public static List<String> getLinksV2(String url) throws BadRequest {
    try {
      URL aUrl= new URL(url);
      String host = aUrl.getHost();
      System.out.println(host);
      if (host.startsWith("172.") || host.startsWith("192.168") || host.startsWith("10.")){
        throw new BadRequest("Use of Private IP");
      } else {
        return getLinks(url);
      }
    } catch(Exception e) {
      throw new BadRequest(e.getMessage());
    }
  }
```
Given the following code, I should be able to get back the 2 method entirely (including the method header, body and return statement etc)

P.S. I am not sure if Javaparser is the best tool for this, but I am certainly open to other tools. I have tried using REGEX and python script but it is not very accurate. I am open to any other command-line tools as well.
The primary goal I have is to be able to have the list of methods that is within a java file.
P.S. Please suggest any tools to me for this purpose! I would really appreciate it!

Thanks in advanced!

**Comment by jlerbsc** [comment]
hi @cyberjj999 what informations would you want to get? the name? the qualifed signature?...

**Comment by cyberjj999** [comment]
Hello @jlerbsc I would need the entire method, it would be very ideal if it is possible to identify the name, qualified signature etc. But if anything, the most important thing is getting the entire method as a String.

In this example, i would want to get the whole string of both methods, i.e.
```
public static List<String> getLinks(String url) throws IOException {
    List<String> result = new ArrayList<String>();
    Document doc = Jsoup.connect(url).get();
    Elements links = doc.select("a");
    for (Element link : links) {
      result.add(link.absUrl("href"));
    }
    return result;
  }
```

And to be clear, if I can separate the strings and not get it in a chunk it would be ideal, i.e. if I can get the string for the 4th method that exists in a java file, instead of having to do some splitting functionality to split each method.

**Comment by jlerbsc** [comment]
Below an example to extract the method signatures

    @Test
    public void test() {
        String code = 
                "public class A {\n" +
                "  public static List<String> getLinks(String url) throws IOException {\r\n" + 
                "    List<String> result = new ArrayList<String>();\r\n" + 
                "    Document doc = Jsoup.connect(url).get();\r\n" + 
                "    Elements links = doc.select(\"a\");\r\n" + 
                "    for (Element link : links) {\r\n" + 
                "      result.add(link.absUrl(\"href\"));\r\n" + 
                "    }\r\n" + 
                "    return result;\r\n" + 
                "  }\r\n" + 
                "\r\n" + 
                "  public static List<String> getLinksV2(String url) throws BadRequest {\r\n" + 
                "    try {\r\n" + 
                "      URL aUrl= new URL(url);\r\n" + 
                "      String host = aUrl.getHost();\r\n" + 
                "      System.out.println(host);\r\n" + 
                "      if (host.startsWith(\"172.\") || host.startsWith(\"192.168\") || host.startsWith(\"10.\")){\r\n" + 
                "        throw new BadRequest(\"Use of Private IP\");\r\n" + 
                "      } else {\r\n" + 
                "        return getLinks(url);\r\n" + 
                "      }\r\n" + 
                "    } catch(Exception e) {\r\n" + 
                "      throw new BadRequest(e.getMessage());\r\n" + 
                "    }\r\n" + 
                "  }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        List<MethodDeclaration> mds = cu.findAll(MethodDeclaration.class);
        mds.forEach(md-> System.out.println(md.getDeclarationAsString()));
    }

returns 

    public static List<String> getLinks(String url) throws IOException
    public static List<String> getLinksV2(String url) throws BadRequest

for the whole content of each method use

    mds.forEach(md-> System.out.println(md.toString()));

then you can write it in a file

**Comment by cyberjj999** [comment]
Hi @jlerbsc . My apologises for the late response as I was having dinner just now.
I'm not looking to only retrieve the method header in a test.java file - I actually am looking to get the whole method (including header, body and return msg etc.) as a string, like the example I gave above.
May I know if its possible to do it with Java Parser?

Edit: I would like to also eventually pass the output into my python script to run the extracted method over some algorithm, may I ask if theres a way to convert this into i.e. a Java JAR file and print the output to the console?
Example Usage may be like: java -jar myExtractor.jar -extract test.java
(Then all the methods get output into the terminal or something)
I am definitely open to better options, but if Javaparser only works with Java Code, even if it is compiled as a JAR Program, I can 
use python libraries to capture the output of the JAR Program and run algorithm using python code.
I hope this is clear

**Comment by MysterAitch** [comment]
@cyberjj999 This may be of interest to you:

https://javaparser.org/inspecting-an-ast/

https://plugins.jetbrains.com/plugin/14245-javaparser-ast-inspector


You can search for all method declarations within a compilation unit and, once you have that, you can extract anything you want. For example, you can print the whole thing and you can extract specific parts.

In @jlerbsc 's example above, a list of the method declarations is gotten and the declaration signature is printed -- if you want to just print the fourth one, you can get the fourth one from the list instead of iterating over all of them.
