### ISSUE TITLE
Methods accessible by a PackageDeclaration instance

### ISSUE THREAD

**Issue by divad1998** [javaparser/javaparser#2937]
Hello JP, *smiles*
So I'm working on this really interesting library which requires that this method: 'setJavadoc(Javadoc javadoc)' becomes accessible by a PackageDeclaration instance. My project is currently on hold due to the absence of this feature, so I'm actually suggesting an inclusion of this feature in your library. 
Patiently hoping this suggestion is considered and the library updated. 
Thanks JP.

**Comment by MysterAitch** [comment]
Hi @divad1998 :) 

Are you actually trying to add javadoc comment to the package declaration? I ask as there is subtle nuance around what a comment gets attributed/attached to versus where it is positioned in the file.

Alternatively, do you just want it at the top of the file? (e.g. for a copyright notice)


Also: I don't have it available but, if you do, can you confirm if the javadoc tool allows it to be added to the package please?

**Comment by jlerbsc** [comment]
The JLS says that "It is recommended that package-info.java, if it is present, take the place of package.html for javadoc and other similar documentation generation systems. If this file is present, the documentation generation tool should look for the package documentation comment immediately preceding the (possibly annotated) package declaration in package-info.java. In this way, package-info.java becomes the sole repository for package-level annotations and documentation". I'm not sure how package declaration javadoc must be taken into account by by JP.
https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html

**Comment by jlerbsc** [comment]
There is also a sonar rule that identify a minor violation "Packages should have a javadoc file 'package-info.java'"
"Each package in a Java project should include a package-info.java file. The purpose of this file is to document the Java package using javadoc and declare package annotations."
https://rules.sonarsource.com/java/tag/convention/RSPEC-1228

**Comment by divad1998** [comment]
> osit

I intend adding a javadoc comment before the package declaration line

**Comment by divad1998** [comment]
> The JLS says that "It is recommended that package-info.java, if it is present, take the place of package.html for javadoc and other similar documentation generation systems. If this file is present, the documentation generation tool should look for the package documentation comment immediately preceding the (possibly annotated) package declaration in package-info.java. In this way, package-info.java becomes the sole repository for package-level annotations and documentation". I'm not sure how package declaration javadoc must be taken into account by by JP.
> https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html

I intend adding a javadoc comment before the package declaration line.

**Comment by jlerbsc** [comment]
I understand what you want to do but my point is just to remember that it is not JLS compliant and that tools like SonarQube detect issues like this. I am not sure that we want to integrate features into JP that are not recommended by the JLS.  @MysterAitch what is your opinion?

**Comment by MysterAitch** [comment]
I agree -- if there's anything to show that this is supported anywhere else, I would be open to it.

If you could share some more details about what it is you're trying to achieve (e.g. is it just to insert the comment, or do you want to replace an existing comment, or to add a copyright header, or something else), we might be able to give figure out how to make it happen! :) 

---

Thinking out loud...

iirc the compilation unit can have a comment added to it and it'll be inserted at the top prior to the package line -- JavaParser won't necessarily associate it with the package line, but if your goal is just to get the comment added to the top of the file then that might get you to what you are trying to do :+1:

Alternatively, you could use JavaParser to add a line/block comment above the package, and then do a string replacement to convert it into /**?

If neither of those are fine, you could look at running a custom printer -- but more information is needed :) 

Sidenote: A decorated package declaration might be an option too (i.e. `public class CustomPackageDeclaration extends PackageDeclaration implements DocumentableNode` or something to that effect). I presume that calling `.replace()` to insert it would work, but I'd have to have a play to be sure if it is possible/workable as an option.

**Comment by divad1998** [comment]
> I understand what you want to do but my point is just to remember that it is not JLS compliant and that tools like SonarQube detect issues like this. I am not sure that we want to integrate features into JP that are not recommended by the JLS. @MysterAitch what is your opinion?

I'm not going against JLS actually. What I want to do is: read the package-info.java file, get and edit the javadoc comment on top of the package declaration line, and replace/set it.

**Comment by divad1998** [comment]
> I agree -- if there's anything to show that this is supported anywhere else, I would be open to it.
> 
> If you could share some more details about what it is you're trying to achieve (e.g. is it just to insert the comment, or do you want to replace an existing comment, or to add a copyright header, or something else), we might be able to give figure out how to make it happen! :)
> 
> Thinking out loud...
> 
> iirc the compilation unit can have a comment added to it and it'll be inserted at the top prior to the package line -- JavaParser won't necessarily associate it with the package line, but if your goal is just to get the comment added to the top of the file then that might get you to what you are trying to do 
> 
> Alternatively, you could use JavaParser to add a line/block comment above the package, and then do a string replacement to convert it into /**?
> 
> If neither of those are fine, you could look at running a custom printer -- but more information is needed :)

I intend editting and replacing an existing comment

**Comment by jlerbsc** [comment]
Sorry I did not understand your request. I let @MysterAitch help you.

**Comment by MysterAitch** [comment]
> 
> I intend editting and replacing an existing comment

Could you elaborate further please? Is this one file vs a few vs thousands etc? Will it be run once or do you intend to repeat it? Will the package line (and it's comment) be the first lines of the file?


In the immediate term, to get you going ASAP with a solution, perhaps this article will help:

https://javaparser.org/inspecting-an-ast/


If you can identify where the existing comment is added/attributed, then that should make it easy to replace it.

I'm on mobile so can't personally verify at the moment, but I'm pretty sure the existing comment will be attributed to the compilation unit. 

If it's not the compilation unit, then I expect that it'll be an orphan comment.

**Comment by divad1998** [comment]
`@PackageDoc(description = "...", version = "1.0", since = "2020-11-21")
package org.unidoc;
`
So, my project introduces commenting java codes with annotations. I also intend building a commandline tool which internally converts these comments to javadoc commenting style for effective javadoc documentation. So far I've completed the necessary codes for converting ClassDeclaration comments and other declarations (except PackageDeclaration). Why? A PackageDeclaration instance can't access the required 'setJavadoc' method.

**Comment by divad1998** [comment]
> > I intend editting and replacing an existing comment
> 
> Could you elaborate further please? Is this one file vs a few vs thousands etc? Will it be run once or do you intend to repeat it? Will the package line (and it's comment) be the first lines of the file?
> 
> In the immediate term, to get you going ASAP with a solution, perhaps this article will help:
> 
> https://javaparser.org/inspecting-an-ast/
> 
> If you can identify where the existing comment is added/attributed, then that should make it easy to replace it.
> 
> I'm on mobile so can't personally verify at the moment, but I'm pretty sure the existing comment will be attributed to the compilation unit.
> 
> If it's not the compilation unit, then I expect that it'll be an orphan comment.

It would be all package-info.java files and It would be run whenever the programmer tries generating a javadoc documentation file. And yes, it would be the first lines in the files.

**Comment by divad1998** [comment]
The above solutions you suggested aren't apt

**Comment by MysterAitch** [comment]
It sounds like a really interesting project! 😊😊


Personally I lean towards being permissive in allowing cases where things are "allowed, but discouraged". 

For example, if we're "supposed" to put package documentation in `package-info.java` but it's fine to add it at the top of each Java file then this is developer choice and a case of best practices -- and it would not necessarily JavaParser's role to arbitrate in that case so should add it in!

Unfortunately, most literature I've been able to find indicates that it's a thing that people do but isn't actually supported -- in the same way that javadoc can be added ANYWHERE inside of a java file, but it won't actually be attached to anything or processed by javadoc unless it is in a prescribed location.

Here's the most compelling and explicit example which enumerates the very limited set of cases where javadoc can be added:

> **Placement of comments** - Documentation comments are recognized only when placed immediately before class, interface, constructor, method, or field declarations -- see the class example, method example, and field example.

https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html

This explicitly and unequivocally states that package declarations are not a node that can have javadoc attached to it. Given this, I can't reasonably argue for adding it.


I do note the url refers to Java 7 so maybe more recent notes are available, but I've not been able to find them. 

I don't ever use/run the javadoc tool locally -- if you can provide anything online that is more recent or can show that it is used, I am more than happy to change my view! :)

**Comment by divad1998** [comment]
> unequivocally

After studying the page associated with the link, I observed that the section which contains the subsection: 'Placement of comments' only specifies the placement of doc comments in source code files.

**Comment by MysterAitch** [comment]
> 
> 
> > unequivocally
> 
> After studying the page associated with the link, I observed that the section which contains the subsection: 'Placement of comments' only specifies the placement of doc comments in source code files.

To confirm: this means that we are in agreement about the quoted section applying to documentation comments (i.e. javadoc), yes? 

If so: package declarations cannot have documentation comments (javadoc), thus it is inappropriate to add `PackageDeclaration#setJavadoc(Javadoc javadoc)`.

Do you have another interpretation?

**Comment by divad1998** [comment]
> > > unequivocally
> > 
> > 
> > After studying the page associated with the link, I observed that the section which contains the subsection: 'Placement of comments' only specifies the placement of doc comments in source code files.
> 
> To confirm: this means that we are in agreement about the quoted section applying to documentation comments (i.e. javadoc), yes?
> 
> If so: package declarations cannot have documentation comments (javadoc), thus it is inappropriate to add `PackageDeclaration#setJavadoc(Javadoc javadoc)`.
> 
> Do you have another interpretation?

Actually, we didn't reach an agreement. Why? package-info.java isn't a source code file. Remember I intend reading a package-info.java file.

**Comment by divad1998** [comment]
In other words, the quoted section doesn't apply to package-info.java files(which are not source code files).

**Comment by MysterAitch** [comment]
I think I finally understand. 

You are not wanting to add the comment into the `package-info.java` file. My (mis-)understanding earlier is that you wanted to read from `package-info.java` and then insert it into e.g. `MyClass.java`.

This means you are correct that the `PackageDeclaration` CAN have javadoc attached, but only when it is within a file name `package-info.java`. Thank you! :+1:

**Comment by MysterAitch** [comment]
I see that the `setComment()` method allows you to specify any kind of comment (including javadoc comments). This means you can add javadoc comments, just not via `setJavaDoc()`. The only catch is that the next time you parse it, it will be attached to the compilation unit.

The good news here is that you can get going ASAP before any fixes are applied!  :smiley: 

Hope this helps! :) 


See below for an example:

```java
    @Test
    void test() throws IOException {
        CompilationUnit compilationUnit = StaticJavaParser.parse(Paths.get("samples\\package-info.java"));

        List<PackageDeclaration> packageDeclarations = compilationUnit.findAll(PackageDeclaration.class);
        assertEquals(1, packageDeclarations.size());

        PackageDeclaration packageDeclaration = packageDeclarations.get(0);

        // Existing comment is associated with the compilation unit:
        assertTrue(compilationUnit.getComment().isPresent());
        assertFalse(packageDeclaration.getComment().isPresent());

        // Remove the comment from the compilation unit, and add a replacement to the package declaration.
        compilationUnit.removeComment();
        packageDeclaration.setComment(new JavadocComment("abc"));

        // Verify that the correct nodes have the appropriate comment.
        assertFalse(compilationUnit.getComment().isPresent());
        assertTrue(packageDeclaration.getComment().isPresent());

        // Verify that the comment attached to the package declaration is a javadoc comment.
        assertEquals(JavadocComment.class, packageDeclaration.getComment().get().getClass());

        // Print out the file
        System.out.println(compilationUnit);

    }
```

**Comment by divad1998** [comment]
> I see that the `setComment()` method allows you to specify any kind of comment (including javadoc comments). This means you can add javadoc comments, just not via `setJavaDoc()`. The only catch is that the next time you parse it, it will be attached to the compilation unit.
> 
> The good news here is that you can get going ASAP before any fixes are applied! 
> 
> Hope this helps! :)
> 
> See below for an example:
> 
> ```java
>     @Test
>     void test() throws IOException {
>         CompilationUnit compilationUnit = StaticJavaParser.parse(Paths.get("samples\\package-info.java"));
> 
>         List<PackageDeclaration> packageDeclarations = compilationUnit.findAll(PackageDeclaration.class);
>         assertEquals(1, packageDeclarations.size());
> 
>         PackageDeclaration packageDeclaration = packageDeclarations.get(0);
> 
>         // Existing comment is associated with the compilation unit:
>         assertTrue(compilationUnit.getComment().isPresent());
>         assertFalse(packageDeclaration.getComment().isPresent());
> 
>         // Remove the comment from the compilation unit, and add a replacement to the package declaration.
>         compilationUnit.removeComment();
>         packageDeclaration.setComment(new JavadocComment("abc"));
> 
>         // Verify that the correct nodes have the appropriate comment.
>         assertFalse(compilationUnit.getComment().isPresent());
>         assertTrue(packageDeclaration.getComment().isPresent());
> 
>         // Verify that the comment attached to the package declaration is a javadoc comment.
>         assertEquals(JavadocComment.class, packageDeclaration.getComment().get().getClass());
> 
>         // Print out the file
>         System.out.println(compilationUnit);
> 
>     }
> ```

I would come to you with the result of trying this approach. *thumbs-up*

**Comment by divad1998** [comment]
> I see that the `setComment()` method allows you to specify any kind of comment (including javadoc comments). This means you can add javadoc comments, just not via `setJavaDoc()`. The only catch is that the next time you parse it, it will be attached to the compilation unit.
> 
> The good news here is that you can get going ASAP before any fixes are applied! 
> 
> Hope this helps! :)
> 
> See below for an example:
> 
> ```java
>     @Test
>     void test() throws IOException {
>         CompilationUnit compilationUnit = StaticJavaParser.parse(Paths.get("samples\\package-info.java"));
> 
>         List<PackageDeclaration> packageDeclarations = compilationUnit.findAll(PackageDeclaration.class);
>         assertEquals(1, packageDeclarations.size());
> 
>         PackageDeclaration packageDeclaration = packageDeclarations.get(0);
> 
>         // Existing comment is associated with the compilation unit:
>         assertTrue(compilationUnit.getComment().isPresent());
>         assertFalse(packageDeclaration.getComment().isPresent());
> 
>         // Remove the comment from the compilation unit, and add a replacement to the package declaration.
>         compilationUnit.removeComment();
>         packageDeclaration.setComment(new JavadocComment("abc"));
> 
>         // Verify that the correct nodes have the appropriate comment.
>         assertFalse(compilationUnit.getComment().isPresent());
>         assertTrue(packageDeclaration.getComment().isPresent());
> 
>         // Verify that the comment attached to the package declaration is a javadoc comment.
>         assertEquals(JavadocComment.class, packageDeclaration.getComment().get().getClass());
> 
>         // Print out the file
>         System.out.println(compilationUnit);
> 
>     }
> ```

So, after editting the doc comments in the package-info.java file, I wrote the result to another file and got this output:
```
[, /**
 * package description...
 *
 * @author jhbckjc
 */
package org.unidocTest.api;

import org.unidoc.annotations.PackageDoc;

, , , , ]
```

Apparently the setComment(JavadocComment) method wraps the entire contents of the file in an array. Very surprising.

When I tried to replace the square brackets, commas and superfluous spaces so it becomes a proper java doc comment:

```
Optional<Comment> comment = cu.getComment();
comment.toString().replace("[, ", "");
comment.toString().replace(" *", "*");
```
It didn't work.

**Comment by divad1998** [comment]
please, pardon the format of the code.

**Comment by MysterAitch** [comment]
> So, after editting the PackageDeclaration doc comments (in the package-info.java file). I wrote the result to another file and got this output:

Please share the actual code you have used to do this. 
There is no reason I am aware of that it would return as an array. 


>         // Print out the file
>         System.out.println(compilationUnit);

Possibly worth highlighting that `compilationUnit.toString()` will return a pretty-printed string showing the contents of the compilation unit. If you're getting an array in there, something very strange is going on.

_(Note that you can use this as `String fileContents = compilationUnit.toString();`.)_

**Comment by divad1998** [comment]
> > So, after editting the PackageDeclaration doc comments (in the package-info.java file). I wrote the result to another file and got this output:
> 
> Please share the actual code you have used to do this.
> There is no reason I am aware of that it would return as an array.
> 
> > ```
> >     // Print out the file
> >     System.out.println(compilationUnit);
> > ```
> 
> Possibly worth highlighting that `compilationUnit.toString()` will return a pretty-printed string showing the contents of the compilation unit. If you're getting an array in there, something very strange is going on.
> 
> _(Note that you can use this as `String fileContents = compilationUnit.toString();`.)_

```
@Override
    public void visit(CompilationUnit cu, Void arg) {
        super.visit(cu, arg);
        List<PackageDeclaration> packageDeclarations = cu.findAll(PackageDeclaration.class);

        for (PackageDeclaration pd : packageDeclarations) {

            PackageDocumentation packageDocumentation = new PackageDocumentation(pd);
            pd.getAnnotationByClass(PackageDoc.class).ifPresent(packageAnnotationExpr -> packageAnnotationExpr.remove());
            pd.setComment(packageDocumentation.getJavadoc());

        }
```

**Comment by divad1998** [comment]
oops! I see a List.

**Comment by divad1998** [comment]
I've observed the bug.

**Comment by divad1998** [comment]
Thanks for the assistance! boom! *grinning*

**Comment by divad1998** [comment]
Really grateful.
