### ISSUE TITLE
compareConsideringTypeParameters issue

### ISSUE THREAD

**Issue by zcbbpo** [javaparser/javaparser#2940]
Hi , 
I have some code use 
```javaParserFacade.getType(expression);```
This was return 
```
Method  name cannot be resolved in context .......
```
I have see the source code ```com.github.javaparser.resolution.types.ResolvedReferenceType#compareConsideringTypeParameters```
```
if (thisParam instanceof ResolvedTypeVariable && otherParam instanceof ResolvedTypeVariable) {
    List<ResolvedType> thisBounds = thisParam.asTypeVariable().asTypeParameter().getBounds()
         .stream().map(ResolvedTypeParameterDeclaration.Bound::getType)
         .collect(Collectors.toList());
    List<ResolvedType> otherBounds = otherParam.asTypeVariable().asTypeParameter().getBounds()
        .stream().map(ResolvedTypeParameterDeclaration.Bound::getType)
        .collect(Collectors.toList());
    return thisBounds.size() == otherBounds.size() && otherBounds.containsAll(thisBounds);
} else if (!(thisParam instanceof ResolvedTypeVariable) && otherParam instanceof ResolvedTypeVariable) {
    return compareConsideringVariableTypeParameters(thisParam, (ResolvedTypeVariable)otherParam);
} else if (thisParam instanceof ResolvedTypeVariable && !(otherParam instanceof ResolvedTypeVariable)) {
    return compareConsideringVariableTypeParameters(otherParam, (ResolvedTypeVariable) thisParam);
} 
 return false;
```
I want to confrim it possible miss else if ReferenceTypeImpl?
can i add ```else if (thisParam instanceof ResolvedReferenceType && otherParam instanceof ResolvedReferenceType) ```

Thanks

**Comment by jlerbsc** [comment]
Hi @zcbbpo Can you give us more information on what you are trying to do and a simple test case that reproduces the issue you are facing?

**Comment by zcbbpo** [comment]
Hi jlerbsc,
I see ```com.github.javaparser.resolution.types.ResolvedReferenceType#compareConsideringTypeParameters```
```
if (other.equals(this)) {
    return true;
}
```
It's will call ```javassist.CtClassType.equals```
and ```javassist.CtClassType.equals``` was call java.lang.Object.equals
They was compare object pointer.
I see the two CtClassType has the same attributes, field but they has different memory address, this method 
```
if (other.equals(this)) {
    return true;
}
```
will not pass.
Thanks.

**Comment by jlerbsc** [comment]
Please can you give us a simple test case that reproduces the issue you are facing.

**Comment by zcbbpo** [comment]
Hi @jlerbsc 
When I use ```javaParserFacade.getType(expression);``` I have few issue.
The blew is my two jar
The download link:
[javaparse-test-1.0-SNAPSHOT.jar](https://www.dropbox.com/s/n64c8mhbofmp8s2/javaparse-test-1.0-SNAPSHOT.jar?dl=0)
[javaparse-test-common-1.0-SNAPSHOT.jar](https://www.dropbox.com/s/ksxqddb7md3k8xq/javaparse-test-common-1.0-SNAPSHOT.jar?dl=0)

The one jar(javaparse-test-common-1.0-SNAPSHOT.jar):
```
public class QueryDto<T> {
    private T data;
}
```
```
public class ResponseVO<T> {
    private T data;
}
```
The next jar(javaparse-test-1.0-SNAPSHOT.jar):
```
public class AppDto {
}
```
```
public interface FooService {
    ResponseVO<String> query(QueryDto<AppDto> queryDto);
    ResponseVO<Integer> simpleQuery(int i);
    ResponseVO<Integer> simpleStringQuery(String s);
}
```
And javaparse-test-1.0-SNAPSHOT.jar dependency of javaparse-test-common-1.0-SNAPSHOT.jar

This is my test source for parse:
```
public class MessageController {

    private FooService fooService;

    public Object willSuccess() {
        // pass
        QueryDto queryDto2 = new QueryDto();
        return fooService.query(queryDto2);
    }

    public Object willFail() {
        // not pass
        QueryDto<AppDto> queryDto = new QueryDto<AppDto>();
        return fooService.query(queryDto);
    }

}
```
This is my test case code:
```
public class ParseTest {
    private JavaParserFacade javaParserFacade;

    @Before
    public void beforeTest() throws Exception{
        // /Users/jimcao/.m2/repository/org/example/javaparse-test/1.0-SNAPSHOT/javaparse-test-1.0-SNAPSHOT.jar
        // /Users/jimcao/.m2/repository/org/example/javaparse-test-common/1.0-SNAPSHOT/javaparse-test-common-1.0-SNAPSHOT.jar
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        combinedTypeSolver.add(new JarTypeSolver(Paths.get("/Users/jimcao/.m2/repository/org/example/javaparse-test-common/1.0-SNAPSHOT/javaparse-test-common-1.0-SNAPSHOT.jar")));
        JarTypeSolver jarTypeSolver = new JarTypeSolver(Paths.get("/Users/jimcao/.m2/repository/org/example/javaparse-test/1.0-SNAPSHOT/javaparse-test-1.0-SNAPSHOT.jar"));


        combinedTypeSolver.add(jarTypeSolver);
        javaParserFacade = JavaParserFacade.get(combinedTypeSolver);
    }

    @SuppressWarnings("UnstableApiUsage")
    @Test
    public void test() throws Exception {
        String s = Resources.toString(Resources.getResource("MessageController.java"), Charsets.UTF_8);
        CompilationUnit compilationUnit = StaticJavaParser.parse(s);
        List<MethodDeclaration> allMethod = compilationUnit.findAll(MethodDeclaration.class);

        ResolvedType passResolvedType = getReturnType(allMethod, "willSuccess");
        System.out.println(passResolvedType);
        ResolvedType notPassResolvedType = getReturnType(allMethod, "willFail");
        System.out.println(notPassResolvedType);
    }

    private ResolvedType getReturnType(List<MethodDeclaration> allMethod, String methodName) {
        return allMethod.stream()
                .filter(methodDeclaration -> StringUtils.contains(methodDeclaration.getNameAsString(), methodName))
                .map(methodDeclaration -> methodDeclaration.findAll(ReturnStmt.class))
                .flatMap(Collection::stream)
                .findFirst()
                .flatMap(ReturnStmt::getExpression)
                .map(expression -> javaParserFacade.getType(expression))
                .orElse(null);

    }
}
```
I will run test, It's tell me "java.lang.RuntimeException: javassist.NotFoundException: QueryDto".
I have modified my test case code to:
```
public class ParseTest {
    private JavaParserFacade javaParserFacade;

    @Before
    public void beforeTest() throws Exception{
        // /Users/jimcao/.m2/repository/org/example/javaparse-test/1.0-SNAPSHOT/javaparse-test-1.0-SNAPSHOT.jar
        // /Users/jimcao/.m2/repository/org/example/javaparse-test-common/1.0-SNAPSHOT/javaparse-test-common-1.0-SNAPSHOT.jar
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        combinedTypeSolver.add(new JarTypeSolver(Paths.get("/Users/jimcao/.m2/repository/org/example/javaparse-test-common/1.0-SNAPSHOT/javaparse-test-common-1.0-SNAPSHOT.jar")));
        JarTypeSolver jarTypeSolver = new JarTypeSolver(Paths.get("/Users/jimcao/.m2/repository/org/example/javaparse-test/1.0-SNAPSHOT/javaparse-test-1.0-SNAPSHOT.jar"));

        URL[] urls = new URL[]{
                Paths.get("/Users/jimcao/.m2/repository/org/example/javaparse-test-common/1.0-SNAPSHOT/javaparse-test-common-1.0-SNAPSHOT.jar").toUri().toURL(),
        };
        URLClassLoader urlClassLoader = new URLClassLoader(urls);
        Field field = JarTypeSolver.class.getDeclaredField("classPool");
        field.setAccessible(true);
        ClassPool classPool = (ClassPool) field.get(jarTypeSolver);
        classPool.appendClassPath(new LoaderClassPath(urlClassLoader));

        combinedTypeSolver.add(jarTypeSolver);
        javaParserFacade = JavaParserFacade.get(combinedTypeSolver);
    }

    @SuppressWarnings("UnstableApiUsage")
    @Test
    public void test() throws Exception {
        String s = Resources.toString(Resources.getResource("MessageController.java"), Charsets.UTF_8);
        CompilationUnit compilationUnit = StaticJavaParser.parse(s);
        List<MethodDeclaration> allMethod = compilationUnit.findAll(MethodDeclaration.class);

        ResolvedType passResolvedType = getReturnType(allMethod, "willSuccess");
        System.out.println(passResolvedType);
        ResolvedType notPassResolvedType = getReturnType(allMethod, "willFail");
        System.out.println(notPassResolvedType);
    }

    private ResolvedType getReturnType(List<MethodDeclaration> allMethod, String methodName) {
        return allMethod.stream()
                .filter(methodDeclaration -> StringUtils.contains(methodDeclaration.getNameAsString(), methodName))
                .map(methodDeclaration -> methodDeclaration.findAll(ReturnStmt.class))
                .flatMap(Collection::stream)
                .findFirst()
                .flatMap(ReturnStmt::getExpression)
                .map(expression -> javaParserFacade.getType(expression))
                .orElse(null);

    }
}
```
Then i rerun my test case.
For "willSuccess" method, it's will work fine.
For "willFail" method, it's was throw 

> java.lang.RuntimeException: Method 'query' cannot be resolved in context fooService.query(queryDto) (line: 14) MethodCallExprContext{wrapped=fooService.query(queryDto)}. Parameter types: [ReferenceType{QueryDto, typeParametersMap=TypeParametersMap{nameToValue={QueryDto.T=ReferenceType{AppDto, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}]

I guess it cause by:
```com.github.javaparser.resolution.types.ResolvedReferenceType#compareConsideringTypeParameters```
```
if (other.equals(this)) {
    return true;
}
```
It's may use ```return ctClass.subtypeOf(that.ctClass);```?

Thanks

**Comment by MysterAitch** [comment]
This sounds similar to #1771 and #2762

**Comment by zcbbpo** [comment]
Hi @MysterAitch ,
Thanks your reply.
I feel it's two issue.
The one issue is many JarTypeSolver dependency .
I was use 
```
JarTypeSolver jarTypeSolver = new JarTypeSolver(Paths.get("/Users/jimcao/.m2/repository/org/example/javaparse-test/1.0-SNAPSHOT/javaparse-test-1.0-SNAPSHOT.jar"));

URL[] urls = new URL[]{
                Paths.get("/Users/jimcao/.m2/repository/org/example/javaparse-test-common/1.0-SNAPSHOT/javaparse-test-common-1.0-SNAPSHOT.jar").toUri().toURL(),
        };
URLClassLoader urlClassLoader = new URLClassLoader(urls);
Field field = JarTypeSolver.class.getDeclaredField("classPool");
field.setAccessible(true);
ClassPool classPool = (ClassPool) field.get(jarTypeSolver);
classPool.appendClassPath(new LoaderClassPath(urlClassLoader));
combinedTypeSolver.add(jarTypeSolver);
```
to ignore it.
The next issue is:
```
// pass - work fine.
return fooService.query(new QueryDto()); 
// fail - throw Method 'query' cannot be resolved in context fooService.query(queryDto) (line: 14)....
return fooService.query(new QueryDto<AppDto>());
```
It's look like generic parameter issue....

**Comment by jlerbsc** [comment]
Hi @MysterAitch  I agree with you. A quick win in my opinion would be to have a single classpool instance shared between the different jartypesolver. But this solution did not seem to have the consensus. This would initially unblock the issues and possibly allow time to think about another solution.

**Comment by zcbbpo** [comment]
Hi @jlerbsc 
```
// pass - work fine.
return fooService.query(new QueryDto()); 
// fail - throw Method 'query' cannot be resolved in context fooService.query(queryDto) (line: 14)....
return fooService.query(new QueryDto<AppDto>());
```
Your means ```return fooService.query(new QueryDto<AppDto>());``` was cause by different jartypesolver classpool?

**Comment by jlerbsc** [comment]
Hi @zcbbpo yes each JarTypeSolver references it's own classpool.

**Comment by zcbbpo** [comment]
@jlerbsc Thanks~

**Comment by zcbbpo** [comment]
Hi @jlerbsc
Could you please help me check the other issue of [NullType must not fail matchTypeParameters](https://github.com/javaparser/javaparser/pull/2939)

**Comment by zcbbpo** [comment]
Do we have any hard codes to quick fixed it at user side

**Comment by jlerbsc** [comment]
I would try to look at this tonight.

**Comment by MysterAitch** [comment]
> Hi @jlerbsc
> Could you please help me check the other issue of [NullType must not fail matchTypeParameters](https://github.com/javaparser/javaparser/pull/2939) 

@zcbbpo I appreciate it's likely just a text-communication thing (maybe I'm being oversensitive/misinterpreting), but:

- Sometimes replies/fixes will be fast (@jlerbsc has been amazing with this recently!!) but we should not _expect_ or _demand_ this to always be the case
- Sometimes work/family/etc will interrupt (reasonably) causing replies to be slower - or in some cases it might just be a really hard bug to fix that takes a while :+1:

please do take care and remember that none of us are paid to develop JavaParser :+1: :)

**Comment by zcbbpo** [comment]
If my reply caused your misunderstanding, I am very sorry.
I just comfrim this issue.
Very thanks for @jlerbsc.
Have a nice day~

**Comment by jlerbsc** [comment]
With the current version this issue seems to be resolved. The test case prints respectively

    ReferenceType{ResponseVO, typeParametersMap=TypeParametersMap{nameToValue={ResponseVO.T=ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}
    ReferenceType{ResponseVO, typeParametersMap=TypeParametersMap{nameToValue={ResponseVO.T=ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}
