### ISSUE TITLE
GetType of a Node. 

### ISSUE THREAD

**Issue by bernardnongpoh** [javaparser/javaparser#298]
Given a Node 
public Node visit(AssignExpr n, Object arg) {
//do something
}

how to find type of n?

**Comment by ftomassetti** [comment]
Do you mean the Java type? Like string, int, List<Boolean> ?
In that case you need a symbol solver, this is not something present in the AST. Depending on the situation it could be very easy or very complicate to find the corresponding declaration and then look at the type of that declaration.

**Comment by bernardnongpoh** [comment]
Hello Federico,
Thanks for the reply, Yes I came across the same post at stackoverflow .
Yes maybe I need to look into symbol solver.
Thanks alot
