### ISSUE TITLE
Empty type parameters list on ObjectCreationExpr

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2985]
In this ObjectCreationExpr, getTypeArguments() returns null but it should return String! Is this bug or misunderstanding?

    new ArrayList<String>();

actually

    String code = "class A { List<String> l = new ArrayList<String>();}";
    ObjectCreationExpr expr = StaticJavaParser.parse(code).findFirst(ObjectCreationExpr.class).get();
    expr.getType().getTypeArguments().get().get(0).asString()

return

    String

**Comment by jlerbsc** [comment]
My bad

**Comment by 4everTheOne** [comment]
Hello @jlerbsc,

I tried to reproduce this issue in versions 3.18.0 and 1.18.1-SNAPSHOT and the test succeeded in both versions.

Can you confirm if it's fixed for you too?

```java
@Test
public void testIssue2985() {
    String code = "class A { List<String> l = new ArrayList<String>();}";
    ObjectCreationExpr expr = StaticJavaParser.parse(code).findFirst(ObjectCreationExpr.class).get();
    assertEquals("String", expr.getType().getTypeArguments().get().get(0).asString());
}
```

**Comment by jlerbsc** [comment]
I won't be able to check in the next few days. I will do it as soon as possible.

**Comment by jlerbsc** [comment]
Hi @4everTheOne I forgot it :-(
It is this expression that returns an empty optional
> expr.getTypeArguments()

**Comment by jlerbsc** [comment]
This is a misunderstanding of JavaParser.
