### ISSUE TITLE
JavaParser.parseBodyDeclaration does not parse void-method

### ISSUE THREAD

**Issue by florianlieb** [javaparser/javaparser#299]
`JavaParser.parseBodyDeclaration("public void test() { }");` 
fails with a
   `com.github.javaparser.ParseException: Encountered " "void" "void "" at line 1, column 8.`

**Comment by ftomassetti** [comment]
Thanks for reporting this

**Comment by matozoid** [comment]
This was accidentally fixed in one of the alpha releases.
