### ISSUE TITLE
Static imported field from other class is not treated as FieldAccessExpr

### ISSUE THREAD

**Issue by arkaanni** [javaparser/javaparser#2993]
hi, I have a question about static imported field. Let say we have a class with a static field called "a":
```java
package example2;

public class StaticField {
    public static String a = "a";
}
```

and another class that access the static field "a":

```java
package example2;

import static example2.StaticField.a;

public class Test {
    public static void main(String[] args) {
        System.out.println(a);
    }
}
```
When I try to find nodes with ```findAll(FieldAccessExpr.class)``` the "a" field is not showing.

In my opinion the "a" field that accessed in Test class  should be a ```FieldAccessExpr``` (because it's a field from StaticField class) but instead it's a ```NameExpr``` (which is true because it's an identifier), is this an intended behavior or did I miss something?

Thank you.

**Comment by jlerbsc** [comment]
Hi @arkaanni In your example "a" is not a field access expression as defined in the JLS https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.11

    FieldAccess:
    Primary . Identifier
    super . Identifier
    TypeName . super . Identifier

**Comment by arkaanni** [comment]
So if we do a static import of a field from other class and use it directly it will not treated as a field access expression?
Because if we do instead of static importing a field but using it's reference (```StaticField.a``` in this case) the JP will treat it as field access expression. Sorry I'm so confused with this xd

**Comment by jlerbsc** [comment]
Is the JLS not sufficiently clear on this subject? What i understand is : it's not related to a JP specific implementation! The JLS defines what is a field access expression.

**Comment by arkaanni** [comment]
Yes but it's clear to me now, thank you!
