### ISSUE TITLE
LexicalPreservationEnabled causes memory leak

### ISSUE THREAD

**Issue by frevib** [javaparser/javaparser#2996]
Hi,

In parsing a couple of thousand Java source files, the following happens when `LexicalPreservationEnabled` is enabled, which results in an out of memory error after a while:

![Screenshot 2020-12-28 at 15 39 11](https://user-images.githubusercontent.com/5623111/103221782-b9833980-4923-11eb-813f-2d49897780a2.png)

![Screenshot 2020-12-28 at 15 43 25](https://user-images.githubusercontent.com/5623111/103221803-c7d15580-4923-11eb-84ee-1e4380ada7e5.png)

<br/><br/>

When I run the same code __without__ `LexicalPreservationEnabled` everything runs fine:

![Screenshot 2020-12-28 at 15 36 06](https://user-images.githubusercontent.com/5623111/103221836-e0417000-4923-11eb-9b57-00b450ebe253.png)

![Screenshot 2020-12-28 at 15 36 27](https://user-images.githubusercontent.com/5623111/103221864-efc0b900-4923-11eb-9ab5-3400f8f750ac.png)

I've tried `JavaParserFacade.clearInstances()` but it doesn't help.

It looks like the GC has issues cleaning up some of the references, but since the GC has no problems when `LexicalPreservationEnabled` is disabled it doesn't seem these objects are still referenced.

Here is the Kotlin code:

```kotlin
File(pathJuliet)
        .listFiles()
        .filterNotNull()
        .filter { it.isDirectory }
        .forEach { directory ->
            val puid = UUID.randomUUID()
            directory
                .walk()
                .filter {
                    it.isFile && it.extension == "java"
                }
                .flatMap { javaFile ->
                    processFile(javaParser, javaFile, puid)
                }
                .let {
                    Json.encodeToString(it)
                }
                .also {
                    File("$pathOutput/${directory.name}.json").writeText(it)
                }
```

Any idea what could be wrong?

**Comment by jlerbsc** [comment]
PhantomNodeLogic.cleanUpCache() should resolve your issue.

**Comment by frevib** [comment]
Thanks you so much, that solved it!

![Screenshot 2020-12-28 at 16 09 42](https://user-images.githubusercontent.com/5623111/103223878-467bc200-4927-11eb-8f71-86ff5ca1341c.png)

Fixed code:

```Kotlin
File(pathJuliet)
        .listFiles()
        .filterNotNull()
        .filter { it.isDirectory }
        .forEach { directory ->
            val puid = UUID.randomUUID()
            directory
                .walk()
                .filter {
                    it.isFile && it.extension == "java"
                }
                .flatMap { javaFile ->
                    processFile(javaParser, javaFile, puid)
                }
                .let {
                    Json.encodeToString(it)
                }
                .also {
                    File("$pathOutput/${directory.name}.json").writeText(it)
                    // Fix 
                    PhantomNodeLogic.cleanUpCache()
                }
        }
```

**Comment by jlerbsc** [comment]
Don't close this issue please. I have to push a definitve solution to this problem.

**Comment by jlerbsc** [comment]
Hmm! it's a little more complicated than I thought because the cache is global to the whole JVM and the multithreaded tests fail.

**Comment by frevib** [comment]
Maybe you could at least update JavaDoc or add a note here https://github.com/javaparser/javaparser/blob/54496f6448666296769b275dfa3dbc04e87447b4/javaparser-core/src/main/java/com/github/javaparser/ParserConfiguration.java#L339 for now? I had to find the leak by trail and error as there is no hint to be found on Google or the docs.

**Comment by jlerbsc** [comment]
I didn't say that I was going to leave this subject aside ;-) I'm looking for a solution. for the moment i think about a cache 
 by compilation unit which would be stripped when the finalize method is invoked on the object CompilationUnit

**Comment by jlerbsc** [comment]
Hi @frevib could you test with this fork (https://github.com/jlerbsc/javaparser) before i merge the PR. If it works there is no need to use PhantomNodeLogic.cleanUpCache(). Thanks

**Comment by jlerbsc** [comment]
I  think the best solution is to remove the cache and keep the attribute 'isPhantomNode" in node's data. So there is no need to manage the cache and JP will manage his memory better.

**Comment by frevib** [comment]
So this means there is no call to `PhantomNodeLogic.cleanUpCache()` needed any more?

**Comment by jlerbsc** [comment]
Yes

**Comment by frevib** [comment]
Heap memory usage is much more stable compared to using `PhantomNodeLogic.cleanUpCache()`

<img width="527" alt="Screenshot 2020-12-30 at 20 55 53" src="https://user-images.githubusercontent.com/5623111/103378095-7a024c00-4ae1-11eb-945f-937912f4e29e.png">

Very nice solution 👍

**Comment by jlerbsc** [comment]
Thank you for your answer because I could not really test this solution under the same conditions as you
