### ISSUE TITLE
Comments should be initialized to null

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#3]
This patch: http://code.google.com/p/javaparser/issues/detail?id=9#c19 left the unit tests broken. They were fixed by always creating an empty list for comments. The rest of the API seems to initialize lists to nulls. This needs to be made consistent again.

**Comment by arouel** [comment]
I think we should avoid `null` when ever possible. It's so unnecessary to check all list return values for `null`. I prefer to call `isEmpty()` instead. What do you think?

**Comment by stepinto** [comment]
+1 for using empty lists whenever possible

**Comment by matozoid** [comment]
I'm for that solution too, but it would mean more memory usage. If anybody wants to patch this one way or another, send it in.

**Comment by ftomassetti** [comment]
What about using lazy evaluation: lists stay null until someone try to access them, at that moment the list is instantiated if it is still null.

**Comment by matozoid** [comment]
Sounds memory efficient and safe. Go ahead!

**Comment by ftomassetti** [comment]
Is this one solved?

**Comment by ftomassetti** [comment]
I think this one was solved long ago, closing. Feel free to reopen if you are affected by a similar problem.
