### ISSUE TITLE
getThrows() method returns List<NameExpr> for ConstructorDeclaration, but List<ReferenceType> for MethodDeclaration

### ISSUE THREAD

**Issue by sebasj14** [javaparser/javaparser#302]
I updated recently to 2.4.0, and noticed that getThrows() for MethodDeclaration was changed to return List of ReferenceType, but for ConstructorDeclaration the return type is still List of NameExpr.

**Comment by matozoid** [comment]
Alright, this seems to be associated with this PR: https://github.com/javaparser/javaparser/pull/187
@ftomassetti - please advise on how to continue.

**Comment by ftomassetti** [comment]
I think that NameExpr represents expressions, while ReferenceType is what we need in this context. We should probably update MethodDeclaration too.

**Comment by matozoid** [comment]
Fixed on master.
