### ISSUE TITLE
UnsolvedSymbolException when trying to solve set/get methods generated with lombok library 

### ISSUE THREAD

**Issue by daiwenlong** [javaparser/javaparser#3023]
code like this...

> 

    @ApiOperation(value = "注册账户信息", tags = "账户")
    public JsonResponseEntity<String> register(@RequestBody @Valid BankAccountDTO dto) {
        UserBasic user = UserUtil.getUserInfo();
        MobileInfo mobileInfo = new MobileInfo(dto.getContactPhone(), dto.getVerificationCode());
        String status = accountServiceApplication.register(null, user.getUid(), user.getUsername());
        return JsonResponseEntity.ok(status);
    }

`

> 
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("D:\\ideawork\\src\\main\\java"));
        combinedTypeSolver.add(reflectionTypeSolver);
        combinedTypeSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
`

Exception:UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to dto.getContactPhone()', cause='null'}

How to deal with it?

**Comment by MysterAitch** [comment]
Hi @daiwenlong, where is `BankAccountDTO` defined?

**Comment by daiwenlong** [comment]
@MysterAitch 
![image](https://user-images.githubusercontent.com/30766058/103884326-5eb6c280-5119-11eb-8491-ab9cd6fa244b.png)

**Comment by daiwenlong** [comment]
@MysterAitch 
`import com.maniujk.merchant.account.controller.dto.request.*;`

Can a definition be found in this way？

**Comment by MysterAitch** [comment]
Nothing obvious is jumping out to me - it seems that it is setup correctly, but I would need to try it at a computer to test this.

Are you able to reduce it to a simple, reproducible, test case please? 

E.g., does the same error happen when you remove the annotations? Or when you remove the other methods?

**Comment by daiwenlong** [comment]
package com.maniujk.merchant.account.controller;

import com.maniujk.merchant.account.application.AccountServiceApplication;
import com.maniujk.merchant.account.controller.dto.request.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.Valid;


@RestController
@RequestMapping("/account/consumer")
public class AccountController {

    @Autowired
    private AccountServiceApplication accountServiceApplication;


    @PostMapping("/registerAccount")
    public String register(@RequestBody @Valid BankAccountDTO dto) {
        return accountServiceApplication.register(dto.getBankcardNo());
    }

}


package com.maniujk.merchant.account.application;


import org.springframework.stereotype.Component;


@Component
public class AccountServiceApplication {


    public String register(String uid) {
        return null;
    }


}


package com.maniujk.merchant.account.controller.dto.request;


import lombok.Data;



@Data
public class BankAccountDTO {

    private String bankcardNo;

}



public class CodeParser {
    
    public static void main(String[] args) throws FileNotFoundException {

        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("D:\\ideawork\\src\\main\\java"));
        combinedTypeSolver.add(reflectionTypeSolver);
        combinedTypeSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(new File("D:\\ideawork\\src\\main\\java\\com\\maniujk\\merchant\\account\\controller\\AccountController.java"));

        VoidVisitor<?> methodNameVisitor = new MethodNamePrinter();
        methodNameVisitor.visit(cu, null);

    }

    private static class MethodNamePrinter extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(MethodDeclaration md, Void arg) {
            System.out.println(md.resolve().getQualifiedSignature());
            md.findAll(MethodCallExpr.class).forEach(mce -> {
                try {
                    System.out.println(mce.resolve().getQualifiedSignature());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
            super.visit(md, arg);
        }
    }

}

**Comment by jlerbsc** [comment]
Hi @daiwenlong Are the getter / setter methods generated by lombok?

**Comment by daiwenlong** [comment]
@jlerbsc yes, getter / setter methods generated by lombok.

**Comment by jlerbsc** [comment]
So it's not an issue because in your example SymbolSover analyses the source code that does not contain get/set methods generated by lombok. I think that if you want to solve set/get methods you have to setup SymbolSolver with your project jar file.

**Comment by MysterAitch** [comment]
See also #3095 for Lombok related comments/information/links.
