### ISSUE TITLE
IndexOutOFBoundsException when resolving with multiple varargs methods available. 

### ISSUE THREAD

**Issue by greggers123** [javaparser/javaparser#3028]
I found this issue when resolving code containing calls to log4j but have now recreated the issue with some much simpler code that has no dependencies on other libraries:

```
import java.util.function.Supplier;

public class AParserTest {

	public void testMethod() {
		doSomething("abc");
	}
	
	private void doSomething(String string, Supplier<?>... supplier) {
		
	}

	private void doSomething(String string, Object... object) {
		
	}
}
```
The parsing code I used was very simple, here is the main class:
```
public class Parser {
	
	private static final String PATH_TO_SOURCE = "...";

	private static final Logger LOGGER = LogManager.getLogger();
	public static void main(String[] args) {
		
		try {
			TypeSolver typeSolver = new CombinedTypeSolver(
					new ReflectionTypeSolver());
			JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
			
			StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

			CompilationUnit cu = StaticJavaParser.parse(New File(PATH_TO_SOURCE));
				
			List<String> messages = new ArrayList<>();
			VoidVisitor<List<String>> collector = new Collector();
			collector.visit(cu, messages);
		} catch (Exception ex) {
			String message = "Exception thrown";
			LOGGER.error(message, ex);
			throw new RuntimeException(message, ex);
		}
	}
}
```
And the Collector:
```
public class Collector extends VoidVisitorAdapter<List<String>> {

	private static final Logger LOGGER = LogManager.getLogger();
	
	@Override
	public void visit(MethodCallExpr mce, List<String> collector) {
		
		super.visit(mce, collector);

		try {
			String methodQualifiedMethodName = mce.resolve().getQualifiedName();
			LOGGER.info("Method: {}", methodQualifiedMethodName);
			
		} catch (UnsolvedSymbolException ex) {
			LOGGER.warn("Skipping method {}, not found in core or referenced JAR(s)", mce.getName());
		}
		
	}
}
```
The execution of the above yields an IndexOutOfBoundsException:
```
[ERROR] 2021-01-08 08:43:55.900 [main] Parser - Exception thrown
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_151]
	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_151]
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isExactMatch(MethodResolutionLogic.java:597) ~[javaparser-symbol-solver-core-3.18.0.jar:?]
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:583) ~[javaparser-symbol-solver-core-3.18.0.jar:?]
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:501) ~[javaparser-symbol-solver-core-3.18.0.jar:?]
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveMethod(JavaParserTypeDeclarationAdapter.java:206) ~[javaparser-symbol-solver-core-3.18.0.jar:?]
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:126) ~[javaparser-symbol-solver-core-3.18.0.jar:?]
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.solveMethod(JavaParserClassDeclaration.java:326) ~[javaparser-symbol-solver-core-3.18.0.jar:?]
```

The javaparser is expecting to find multiple arguments in the call to the doSomething method - But throws the exception when it tries to get the second argument, because there isn't one. 

The issue only occurs when both doSomething methods are present in the AParserTest class (the Object and Supplier) - If one or the other is removed, the code parses without issue. 

I'm using Java 1.8.0_151 (yes, I know it's old), and this Maven dependency for everything javaparser related:
```
<dependency>
   <groupId>com.github.javaparser</groupId>
   <artifactId>javaparser-symbol-solver-core</artifactId>
   <version>3.18.0</version>
</dependency>
```

**Comment by greggers123** [comment]
I had a quick look at the Java specification and it states that the method that is more specific is called. In the case above the generic Supplier is called. If instead the methods had String... and Object... the String method would be called as it is more specific than object and is inherited from Object. 

In the MethodResolutionLogic class isMoreSpecific method because the number of arguments in the calling method is 1 but there are 2 arguments in the candidates it returns before considering the varargs. We know varargs will be the last argument in the method signature so a check could be added to see if there is one more parameter than the number of arguments (we already know if there are varargs). Once this is known the specificity of the varargs could be checked... I can see there is an isAssignableBy method on the ResolvedType which would can be used to see which is more specific. 

If the isMoreSpecific code is changed, it possibleAmbiguity won't be true and the code that currently throws the exception shouldn't be called.

**Comment by jlerbsc** [comment]
Thank you for this detailed analysis.

**Comment by greggers123** [comment]
> Thank you for this detailed analysis.

No problem - If you are good with my analysis, I was going to try to fix it.

**Comment by jlerbsc** [comment]
Choosing the most specific method is not trivial part of the jls (https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.2.5) but of course you can submit a PR

**Comment by greggers123** [comment]
I don't think the logic for finding the most specific method needs to change, the code just needs a tweak to deal with the lack of the call specifying a vararg. 

I've made the change in a fork as per your process - just running the tests now.
