### ISSUE TITLE
Cannot parse Stream::<IVariable<?>>empty

### ISSUE THREAD

**Issue by flashpixx** [javaparser/javaparser#303]
On a Java 1.8 file I'm using streams and I use the following struct:

``` java
.orElseGet( Stream::<IVariable<?>>empty )
```

On the <IVariable<?>> the parser breaks with: Encountered " "<" "< ""
I'm using the version 2.4.0

Thx

**Comment by matozoid** [comment]
This seems connected to #162

**Comment by matozoid** [comment]
Fixed on master.
