### ISSUE TITLE
Update to JavaParser 3.18.0 from 3.17.0 causes MethodCallExpr::resolve to hang

### ISSUE THREAD

**Issue by oxisto** [javaparser/javaparser#3038]
When analysing the file https://github.com/Fraunhofer-AISEC/codyze/blob/59da2a92a5d6623d0066efb4bbae8d860a8485aa/src/test/resources/java/jca/AESCTR.java we encounter an endless loop in our analysis program. 

The root cause of this seems to be the call to `resolve`  of the expression `System.out.printf("update  %2d: %32s [%s]\n", i, Utils.bytesToHex(ciphertextblock), Utils.bytesToHex(mac));`. Once we call resolve, the program seems to be stuck in an endless-loop, however, it does seem to complete the call to resolve after > 10 mins. 

Running the program with JavaParser 3.17.0 works fine and returns in < 1s. Only analysing the expression on its own also seems to work, but analysing the function as described in the file seems to cause the loop.

To construct JavaParser we use a `CombinedTypeSolver` using a `ReflectionTypeSolver` as well as `JavaParserTypeSolver` based on the root of the file.

**Comment by jlerbsc** [comment]
Hi @oxisto Could you provide a simple test case that reproduces this issue?

**Comment by Col-E** [comment]
Can confirm this occurs, issue seems to be based on some nearly infinite looping [`StementContext.java` around lines 242-255](https://github.com/javaparser/javaparser/blob/2903fc918dd87be53192aa1065047392f7adf4d1/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/StatementContext.java#L242) due to changes introduced in #2654

The code I'm looking at is structured like the following: 
```java
void main() {
    // lots of variable assignments
    // Just do:
    // String s1 = ...
    // String s2 = ...
    // ...
    // String s100 = ...
    Thread t = new Thread(() -> {
       Foo f = Foo.getInstance(); // Resolve the "Foo" as a NameExpression and it will hang
    }.start();
}
```
Attempting to resolve the `NameExpr` (`Foo`) in `Foo.getInstance()` causes the hang. It will attempt to look for instances of `Foo` being declared in a parent context to resolve, then its parent's parent, etc. But this content does not exist, so it does not get resolved. This cycle happens once every iteration in the `while` loop segment linked above. 

The key is that there are lots of assignments in the parent context.

I'll attach the demo source here too: [Example.java](https://github.com/javaparser/javaparser/files/5941897/Example.java.txt)

**Comment by jlerbsc** [comment]
It may be the same problem as #2990

**Comment by jlerbsc** [comment]
In the current JP version there is no issue using this test case. Can you provide more details please and a unit test that reproduces this issue?

    @Test
    void e() {
        String code = "public class Foo{\n" +
                "    public static void main(String[] args) {\n" +
                "        String s0   = \"hello\";\n" +
                "        String s1   = \"hello\";\n" +
                "        String s2   = \"hello\";\n" +
                "        String s3   = \"hello\";\n" +
                "        String s4   = \"hello\";\n" +
                "        String s5   = \"hello\";\n" +
                "        String s6   = \"hello\";\n" +
                "        String s7   = \"hello\";\n" +
                "        String s8   = \"hello\";\n" +
                "        String s9   = \"hello\";\n" +
                "        String s10  = \"hello\";\n" +
                "        String s11  = \"hello\";\n" +
                "        String s12  = \"hello\";\n" +
                "        String s13  = \"hello\";\n" +
                "        String s14  = \"hello\";\n" +
                "        String s15  = \"hello\";\n" +
                "        String s16  = \"hello\";\n" +
                "        String s17  = \"hello\";\n" +
                "        String s18  = \"hello\";\n" +
                "        String s19  = \"hello\";\n" +
                "        String s20  = \"hello\";\n" +
                "        String s21  = \"hello\";\n" +
                "        String s22  = \"hello\";\n" +
                "        String s23  = \"hello\";\n" +
                "        String s24  = \"hello\";\n" +
                "        String s25  = \"hello\";\n" +
                "        String s26  = \"hello\";\n" +
                "        String s27  = \"hello\";\n" +
                "        String s28  = \"hello\";\n" +
                "        String s29  = \"hello\";\n" +
                "        String s30  = \"hello\";\n" +
                "        String s31  = \"hello\";\n" +
                "        String s32  = \"hello\";\n" +
                "        String s33  = \"hello\";\n" +
                "        String s34  = \"hello\";\n" +
                "        String s35  = \"hello\";\n" +
                "        String s36  = \"hello\";\n" +
                "        String s37  = \"hello\";\n" +
                "        String s38  = \"hello\";\n" +
                "        String s39  = \"hello\";\n" +
                "        String s40  = \"hello\";\n" +
                "        String s41  = \"hello\";\n" +
                "        String s42  = \"hello\";\n" +
                "        String s43  = \"hello\";\n" +
                "        String s44  = \"hello\";\n" +
                "        String s45  = \"hello\";\n" +
                "        String s46  = \"hello\";\n" +
                "        String s47  = \"hello\";\n" +
                "        String s48  = \"hello\";\n" +
                "        String s49  = \"hello\";\n" +
                "        String s50  = \"hello\";\n" +
                "        String s51  = \"hello\";\n" +
                "        String s52  = \"hello\";\n" +
                "        String s53  = \"hello\";\n" +
                "        String s54  = \"hello\";\n" +
                "        String s55  = \"hello\";\n" +
                "        String s56  = \"hello\";\n" +
                "        String s57  = \"hello\";\n" +
                "        String s58  = \"hello\";\n" +
                "        String s59  = \"hello\";\n" +
                "        String s60  = \"hello\";\n" +
                "        String s61  = \"hello\";\n" +
                "        String s62  = \"hello\";\n" +
                "        String s63  = \"hello\";\n" +
                "        String s64  = \"hello\";\n" +
                "        String s65  = \"hello\";\n" +
                "        String s66  = \"hello\";\n" +
                "        String s67  = \"hello\";\n" +
                "        String s68  = \"hello\";\n" +
                "        String s69  = \"hello\";\n" +
                "        String s70  = \"hello\";\n" +
                "        String s71  = \"hello\";\n" +
                "        String s72  = \"hello\";\n" +
                "        String s73  = \"hello\";\n" +
                "        String s74  = \"hello\";\n" +
                "        String s75  = \"hello\";\n" +
                "        String s76  = \"hello\";\n" +
                "        String s77  = \"hello\";\n" +
                "        String s78  = \"hello\";\n" +
                "        String s79  = \"hello\";\n" +
                "        String s80  = \"hello\";\n" +
                "        String s81  = \"hello\";\n" +
                "        String s82  = \"hello\";\n" +
                "        String s83  = \"hello\";\n" +
                "        String s84  = \"hello\";\n" +
                "        String s85  = \"hello\";\n" +
                "        String s86  = \"hello\";\n" +
                "        String s87  = \"hello\";\n" +
                "        String s88  = \"hello\";\n" +
                "        String s89  = \"hello\";\n" +
                "        String s90  = \"hello\";\n" +
                "        String s91  = \"hello\";\n" +
                "        String s92  = \"hello\";\n" +
                "        String s93  = \"hello\";\n" +
                "        String s94  = \"hello\";\n" +
                "        String s95  = \"hello\";\n" +
                "        String s96  = \"hello\";\n" +
                "        String s97  = \"hello\";\n" +
                "        String s98  = \"hello\";\n" +
                "        String s99  = \"hello\";\n" +
                "        String s100 = \"hello\";\n" +
                "        new Thread(){\n" +
                "            @Override\n" +
                "            public void run() {\n" +
                "                Foo foo = Foo.getInstance(); // Resolve \"Foo\" as a NameExpr and go read a book or something\n"
                +
                "            }\n" +
                "        }.run();\n" +
                "    }\n" +
                "    static Foo getInstance() {\n" +
                "        return new Foo();\n" +
                "    }\n" +
                "}";
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(code);

        List<MethodCallExpr> exprs = cu.findAll(MethodCallExpr.class);
        exprs.forEach(expr -> {
            System.out.println(expr.toString() + " resolved to " + expr.resolve().getQualifiedName());
        });
    }

**Comment by Col-E** [comment]
~~I've updated my prior comment with the test.~~ It explicitly is something with `NameExpr` but in the test case you whipped up I see you're using `MethodCallExpr`. Swap it out and that should cause the issue. In my case trying to resolve `Foo` as a `NameExpr` does it.

Edit: Oh wait I uploaded the wrong file that was supposed to be the unit test, but yeah just swap the class type in `findAll` in your example.

**Comment by Col-E** [comment]
```java
package com.github.javaparser.symbolsolver;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.symbolsolver.resolution.AbstractResolutionTest;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import org.junit.jupiter.api.Test;

import java.util.List;

public class Issue3038Test extends AbstractResolutionTest  {
	@Test
	public void test3038() {
		String code = "public class Foo{\n" +
				"    public static void main(String[] args) {\n" +
				"        String s0   = \"hello\";\n" +
				"        String s1   = \"hello\";\n" +
				"        String s2   = \"hello\";\n" +
				"        String s3   = \"hello\";\n" +
				"        String s4   = \"hello\";\n" +
				"        String s5   = \"hello\";\n" +
				"        String s6   = \"hello\";\n" +
				"        String s7   = \"hello\";\n" +
				"        String s8   = \"hello\";\n" +
				"        String s9   = \"hello\";\n" +
				"        String s10  = \"hello\";\n" +
				"        String s11  = \"hello\";\n" +
				"        String s12  = \"hello\";\n" +
				"        String s13  = \"hello\";\n" +
				"        String s14  = \"hello\";\n" +
				"        String s15  = \"hello\";\n" +
				"        String s16  = \"hello\";\n" +
				"        String s17  = \"hello\";\n" +
				"        String s18  = \"hello\";\n" +
				"        String s19  = \"hello\";\n" +
				"        String s20  = \"hello\";\n" +
				"        String s21  = \"hello\";\n" +
				"        String s22  = \"hello\";\n" +
				"        String s23  = \"hello\";\n" +
				"        String s24  = \"hello\";\n" +
				"        String s25  = \"hello\";\n" +
				"        String s26  = \"hello\";\n" +
				"        String s27  = \"hello\";\n" +
				"        String s28  = \"hello\";\n" +
				"        String s29  = \"hello\";\n" +
				"        String s30  = \"hello\";\n" +
				"        String s31  = \"hello\";\n" +
				"        String s32  = \"hello\";\n" +
				"        String s33  = \"hello\";\n" +
				"        String s34  = \"hello\";\n" +
				"        String s35  = \"hello\";\n" +
				"        String s36  = \"hello\";\n" +
				"        String s37  = \"hello\";\n" +
				"        String s38  = \"hello\";\n" +
				"        String s39  = \"hello\";\n" +
				"        String s40  = \"hello\";\n" +
				"        String s41  = \"hello\";\n" +
				"        String s42  = \"hello\";\n" +
				"        String s43  = \"hello\";\n" +
				"        String s44  = \"hello\";\n" +
				"        String s45  = \"hello\";\n" +
				"        String s46  = \"hello\";\n" +
				"        String s47  = \"hello\";\n" +
				"        String s48  = \"hello\";\n" +
				"        String s49  = \"hello\";\n" +
				"        String s50  = \"hello\";\n" +
				"        String s51  = \"hello\";\n" +
				"        String s52  = \"hello\";\n" +
				"        String s53  = \"hello\";\n" +
				"        String s54  = \"hello\";\n" +
				"        String s55  = \"hello\";\n" +
				"        String s56  = \"hello\";\n" +
				"        String s57  = \"hello\";\n" +
				"        String s58  = \"hello\";\n" +
				"        String s59  = \"hello\";\n" +
				"        String s60  = \"hello\";\n" +
				"        String s61  = \"hello\";\n" +
				"        String s62  = \"hello\";\n" +
				"        String s63  = \"hello\";\n" +
				"        String s64  = \"hello\";\n" +
				"        String s65  = \"hello\";\n" +
				"        String s66  = \"hello\";\n" +
				"        String s67  = \"hello\";\n" +
				"        String s68  = \"hello\";\n" +
				"        String s69  = \"hello\";\n" +
				"        String s70  = \"hello\";\n" +
				"        String s71  = \"hello\";\n" +
				"        String s72  = \"hello\";\n" +
				"        String s73  = \"hello\";\n" +
				"        String s74  = \"hello\";\n" +
				"        String s75  = \"hello\";\n" +
				"        String s76  = \"hello\";\n" +
				"        String s77  = \"hello\";\n" +
				"        String s78  = \"hello\";\n" +
				"        String s79  = \"hello\";\n" +
				"        String s80  = \"hello\";\n" +
				"        String s81  = \"hello\";\n" +
				"        String s82  = \"hello\";\n" +
				"        String s83  = \"hello\";\n" +
				"        String s84  = \"hello\";\n" +
				"        String s85  = \"hello\";\n" +
				"        String s86  = \"hello\";\n" +
				"        String s87  = \"hello\";\n" +
				"        String s88  = \"hello\";\n" +
				"        String s89  = \"hello\";\n" +
				"        String s90  = \"hello\";\n" +
				"        String s91  = \"hello\";\n" +
				"        String s92  = \"hello\";\n" +
				"        String s93  = \"hello\";\n" +
				"        String s94  = \"hello\";\n" +
				"        String s95  = \"hello\";\n" +
				"        String s96  = \"hello\";\n" +
				"        String s97  = \"hello\";\n" +
				"        String s98  = \"hello\";\n" +
				"        String s99  = \"hello\";\n" +
				"        String s100 = \"hello\";\n" +
				"        new Thread(){\n" +
				"            @Override\n" +
				"            public void run() {\n" +
				"                Foo foo = Foo.getInstance(); // Resolve \"Foo\" as a NameExpr and go read a book or something\n"
				+
				"            }\n" +
				"        }.run();\n" +
				"    }\n" +
				"    static Foo getInstance() {\n" +
				"        return new Foo();\n" +
				"    }\n" +
				"}";
		ParserConfiguration config = new ParserConfiguration();
		config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
		StaticJavaParser.setConfiguration(config);

		CompilationUnit cu = StaticJavaParser.parse(code);

		List<NameExpr> exprs = cu.findAll(NameExpr.class);
		exprs.forEach(expr -> {
			System.out.println(expr.toString() + " resolved to " + expr.resolve().getType().describe());
		});
	}
}
````
Letting it run, I'll let you know when it finishes.

 - 200s passed so far
 - 700s
 - 1200s
 - 2500s
 - 4000s
 - 4500s, shutting down manually

**Comment by Col-E** [comment]
I'm going to open a new issue that explicitly declares the `NameExpr` resolve issue. I'll also open a PR to address it. If it also resolves this issue that'd be cool, but I don't have a case of `MethodExpr` taking forever yet.
