### ISSUE TITLE
Not consider implicit type conversion when resolve ConditionalExpr

### ISSUE THREAD

**Issue by twelveand0** [javaparser/javaparser#3041]
I found a bug (maybe) when using SymbolSolver to resolve type of ConditionalExpr. 

## lib version: 
javaparser-symbol-solver-core: 3.18.0

### 1.
ConditionalExpr: 
```java
ClassA a = new ClassA();
obj = flag  ? null : a;
```
When trying to resolve type of expr "**flag ? null : a**", javaparser-symbol-solver 
Output: null
Expected: ClassA 

However, when I tried to resolve type of expression "**flag ? a : null**", javaparser-symbol-solver output "ClassA". So I infer the solver just takes the type of then-expr as the type of the whole conditional expr.
### 2.
ConditionalExpr:
```java
b = flag ? Long.valueOf(100) : 0;
c = flag ? 0 : Long.valueOf(100);
```
When trying to resolve type of expr "**flag ? Long.valueOf(100) : 0**", javaparser-symbol-solver
Output: java.lang.Long
Expected: java.lang.Long

however, when trying to resolve type of expr "**flag ? 0 : Long.valueOf(100)**",  javaparser-symbol-solver
Output: int
Expected: java.lang.Long

So, I infer the current solver just takes  type of the ThenExpr  as type of full ConditionalExpr, and does not consider implicit type conversion. I think this may be a bug, but I'm not sure.

**Comment by jlerbsc** [comment]
There is no problem with the current version. Unit test below 

    @Test
    public void test() {
        String code = 
                "public class A {\n" +
                "    public void foo() {\n" +
                "        Object obj = flag  ? null : new Object();\n" +
                "    }\n" +
                "}";
        StaticJavaParser.getConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        List<ConditionalExpr> exprs = StaticJavaParser.parse(code).findAll(ConditionalExpr.class);
        for (ConditionalExpr expr : exprs) {
            System.out.println(expr.calculateResolvedType().describe());
        }
    }

returns 


    java.lang.Object

**Comment by twelveand0** [comment]
Thanks for your reply.

```
<dependency>
        <groupId>com.github.javaparser</groupId>
        <artifactId>javaparser-symbol-solver-core</artifactId>
        <version>3.18.0</version>
</dependency>
```

When using 3.18.0 release version, the above Unit test returns "null". I don't test the latest code in master branch. According to your test, I think this problem has not existed in current code.

**Comment by jlerbsc** [comment]
Hi @twelveand0 if you have validated your case with the current JP version perhaps can you close this issue?
