### ISSUE TITLE
JavaParserSymbolDeclaration#localVar returning old declaration

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3048]
The static method JavaParserSymbolDeclaration#localVar(VariableDeclarator, TypeSolver) is used in different contexts to create a reference to a variable. During testing, noticed that the declaration was using an old class _JavaParserSymbolDeclaration_ that was later replaced by _JavaParserVariableDeclaration_.

## Test

```java
@Test
void createdLocalVariableShouldBeMarkedAsVariable() {
    VariableDeclarator variableDeclarator = parseVariableDeclarationExpr("int x = 0").getVariable(0);
    ResolvedValueDeclaration localVar = JavaParserSymbolDeclaration.localVar(variableDeclarator, typeSolver);

    assertTrue(localVar.isVariable());
}
```
## Observed behavior
When we call isVariable() of the returned _ResolvedValueDeclaration_ we receive a **false**.

## Expected behavior
When a call to isVariable() of the returned _ResolvedValueDeclaration_ we would expect a **true**.

## Possible solution
A fix for this issue could be replacing the return type of the method JavaParserSymbolDeclaration#localVar(VariableDeclarator, TypeSolver) to be _JavaParserVariableDeclaration_ instead of  _JavaParserSymbolDeclaration_.

**Comment by jlerbsc** [comment]
Hi @ftomassetti could you validate this proposal?

**Comment by jlerbsc** [comment]
Hi @4everTheOne I do not know precisely what is the use of the class JavaParserSymbolDeclaration (perhaps @ftomassetti or @matozoid or @MysterAitch can give you clarification on this topic) but if you use 

     ResolvedValueDeclaration localVar = new JavaParserVariableDeclaration(variableDeclarator, new ReflectionTypeSolver(false));
     assertTrue(localVar.isVariable());

The result is correct.

**Comment by 4everTheOne** [comment]
Hello @jlerbsc. Thanks for the feedback! I totally agree with you, I think it could be fixed by replacing the use of JavaParserSymbolDeclaration with the JavaParserVariableDeclaration.
When I was debug the issue, noticed that the parser by default uses this static method:
https://github.com/javaparser/javaparser/blob/2903fc918dd87be53192aa1065047392f7adf4d1/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserSymbolDeclaration.java#L71-L73
And this uses the JavaParserSymbolDeclaration  instead of the JavaParserVariableDeclaration. I tried to fix this in PR #3049 by doing the substitution and removed the old code to avoid confusions.

What is the opinion of the team?

**Comment by jlerbsc** [comment]
I think your PR goes beyond the problem encountered but in my opinion the localVar method should return an object of type JavaParserVariableDeclaration. I will do some tests this evening to check my understanding of this problem.

**Comment by 4everTheOne** [comment]
Sorry but i'm not seeing why you say it goes beyond the problem, could you give me more detail so i can improve it accordingly.
Also, thanks for you time.

**Comment by jlerbsc** [comment]
I didn't really understand what you want to do! Sorry. But I don't know enough about JP to know what the JavaParserSymbolDeclaration class really represents. Personally I cannot validate this PR. Maybe another team member will.

**Comment by 4everTheOne** [comment]
Oh ok, thanks!. I'll try to explain it better to make the issue clear for the other members.

According to the documentation this class should not be used anymore since there's a new replacement for it (See [JavaParserVariableDeclaration](https://github.com/javaparser/javaparser/blob/1ce7d85c2b1653a192169ea245c14c537a99132b/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserVariableDeclaration.java)).
https://github.com/javaparser/javaparser/blob/e9af3e337100645141534e3a73004f2b45c2f572/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserSymbolDeclaration.java#L42-L49

But at the moment is being used to declare a variable at method localVar.
https://github.com/javaparser/javaparser/blob/e9af3e337100645141534e3a73004f2b45c2f572/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserSymbolDeclaration.java#L69-L71

The problem with the use of JavaParserSymbolDeclaration is that is not representing the expected behavior of a variable. Given the example from the issue, if we have a variable `int x = 0` we would expect the declaration to say it's a variable but the  JavaParserSymbolDeclaration says its not.

**Comment by jlerbsc** [comment]
So JavaParserSymbolDeclaration become a factory for field/parameter/variable declaration and is no longer a ResolvedValueDeclaration

**Comment by 4everTheOne** [comment]
Exactly that

**Comment by MysterAitch** [comment]
I've just added a couple of comments on the PR ~about the process (deprecated first vs remove immediately - I have no strong views)~, but the content seems good :+1:
