### ISSUE TITLE
Catch with multiple exceptions is displayed incorrectly

### ISSUE THREAD

**Issue by ArrayListList** [javaparser/javaparser#305]
I parse a file with something like this:
`
        try{
            // dostuff
        }
        catch (IndexOutOfBoundException|IOException e){
            // handle 
        }
`
then CompilationUnit.toString looks like this:
`try {
            // dostuff
        } catch (IndexOutOfBoundExceptionIOException |  e) {
            // handle 
        }`

Can you fix this?

**Comment by ftomassetti** [comment]
Thank you for reporting this
