### ISSUE TITLE
StaticJavaParser might not be thread safe

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3050]
It seems StaticJavaParser is not thread-safe as com.github.javaparser.Providers.PreProcessor seems not thread-safe.

The following code burns CPU until the issue happens:

```
package eu.solven.cleanthat.java.mutators;

import java.util.stream.IntStream;

import com.github.javaparser.StaticJavaParser;

public class StaticJavaParserThreadSafetyIssue {
	public static void main(String[] args) {
		IntStream.range(0, 16).parallel().forEach(i -> {
			while (true) {
				StaticJavaParser.parse("package eu.solven.cleanthat.java.mutators;\n" + "\n"
						+ "import java.util.stream.IntStream;\n"
						+ "\n"
						+ "import com.github.javaparser.StaticJavaParser;\n"
						+ "\n"
						+ "public class StaticJavaParserThreadSafetyIssue {\n"
						+ "	public static void main(String[] args) {\n"
						+ "		IntStream.range(0, 16).parallel().forEach(i -> {\n"
						+ "			StaticJavaParser.parse(\"\");\n"
						+ "		});\n"
						+ "	}\n"
						+ "}\n"
						+ "");
			}
		});
	}
}

```

Which gives at some point (in a few seconds max):
```
Exception in thread "main" com.github.javaparser.ParseProblemException: Parse error. Found  "acg" <IDENTIFIER>, expected one of  ";" "@" "\u001a" "abstract" "class" "default" "enum" "final" "import" "interface" "module" "native" "open" "private" "protected" "public" "static" "strictfp" "synchronized" "transient" "transitive" "volatile" <EOF>
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:12827)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:12673)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:192)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parse(JavaParser.java:306)
  com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
  eu.solven.cleanthat.java.mutators.StaticJavaParserThreadSafetyIssue.lambda$0(StaticJavaParserThreadSafetyIssue.java:11)
  java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
  java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
  java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
  java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
  java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
  java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Problem stacktrace : 
  com.github.javaparser.StaticJavaParser.handleResult(StaticJavaParser.java:260)
  com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
  eu.solven.cleanthat.java.mutators.StaticJavaParserThreadSafetyIssue.lambda$0(StaticJavaParserThreadSafetyIssue.java:11)
  java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
  java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
  java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
  java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
  java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
  java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:439)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:596)
	at eu.solven.cleanthat.java.mutators.StaticJavaParserThreadSafetyIssue.main(StaticJavaParserThreadSafetyIssue.java:9)

```

I pretend the issue is in (com.github.javaparser.LineEndingProcessor):

```
            @Override
            public Provider process(Provider innerProvider) {
                if (isDetectOriginalLineSeparator()) {
                    _lineEndingProcessingProvider = new LineEndingProcessingProvider(innerProvider);
                    return _lineEndingProcessingProvider;
                }
                return innerProvider;
            }
```

Concurrent calls led to multiple StaticjavaParser instances sharing the same '_lineEndingProcessingProvider': KO

**Comment by jlerbsc** [comment]
Hi @blacelle thanks for reporting this issue but as you can read in https://javaparser.org/the-quick-and-the-full-api-of-javaparser/  a JavaParser instance is not thread safe. JavaParser is not designed to be used/shared in a multithreaded application. From my point of view StaticjavaParser class is a utility class mainly used to develop tests.

**Comment by jlerbsc** [comment]
Related to issue #2113 and #2183

**Comment by blacelle** [comment]
@jlerbsc In fact, it is https://github.com/javaparser/javaparser/issues/2113 comment thread which make me think StaticJavaParser would definitely be ThreadSafe.

Typically, some other methods explicitelystates they are not thread-safe:

    com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.get(TypeSolver)

> Note that the addition of the modifier {@code synchronized} is specific and directly in response to issue #2668.
> <br>This <strong>MUST NOT</strong> be misinterpreted as a signal that JavaParser is safe to use within a multi-threaded environment.

...

Reading again this comment make me understand the signal is not only JavaParserFacade.get thread-safe, but the whole library might not be thread-safe.

> From my point of view StaticjavaParser class is a utility class mainly used to develop tests.

As a beginner with JavaParser, StaticjavaParser is useful to get quickly on track.

**Comment by blacelle** [comment]
After having gone through https://javaparser.org/the-quick-and-the-full-api-of-javaparser/, I get mainly that:

> A JavaParser instance is not thread safe!

But here, the issue occurs due to ParserConfiguration (or more exactly com.github.javaparser.LineEndingProcessor) not being thread-safe. `StaticJavaParser.parse` make a new JavaParser instance on each call.

**Comment by jlerbsc** [comment]
This issue can be reproduced by this simple unit test that does not use symbol solver. So I review my analysis there is certainly a bug in the java parser library

    @Test
    public void test() {
        String code = 
                "public class Test {\n"
                + "}";
        
        IntStream.range(0, 16).parallel().forEach(i -> {
            while (true) {
                StaticJavaParser.parse(code);
            }
        });
    }

with the stacktrace


    com.github.javaparser.ParseProblemException: Parse error. Found  "ubi" <IDENTIFIER>, expected one of  ";" "@" "\u001a" "abstract" "class" "default" "enum" "final" "import" "interface" "module" "native" "open" "private" "protected" "public" "static" "strictfp" "synchronized" "transient" "transitive" "volatile" <EOF>
    Problem stacktrace : 
          com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:12827)
          com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:12673)
          com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:192)
          com.github.javaparser.JavaParser.parse(JavaParser.java:123)
          com.github.javaparser.JavaParser.parse(JavaParser.java:306)

    Problem stacktrace : 
          com.github.javaparser.StaticJavaParser.handleResult(StaticJavaParser.java:260)
          com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
          com.github.javaparser.symbolsolver.AATest.lambda$4(AATest.java:199)

oddly enough this test is executed correctly

    @Test
    public void test() {
        String code = 
                "public class Test {\n"
                + "}";
        
        IntStream.range(0, 16).parallel().forEach(i -> {
            while (true) {
                new JavaParser().parse(code);
            }
        });

    }

**Comment by blacelle** [comment]
@jlerbsc This is because `StaticJavaParser `relies on `StaticJavaParser.configuration`, and the thread-safety issue is in `ParserConfiguration `shared instance of `LineEndingProcessor`

**Comment by jlerbsc** [comment]
I will take a closer look at this point. Thanks for the tip.

**Comment by jlerbsc** [comment]
As a quick turnaround i tried to replace static ParserConfiguration with a threadlocal one and it seem to resolve this problem.
I don't know how to resolve it without an impact on JP users without using this technical solution. In my mind StaticJavaParser is a utility class that should only be used to facilitate the development of unit tests.
