### ISSUE TITLE
Discussion : Does javaparser provides any support for these features ?

### ISSUE THREAD

**Issue by udit-dasari** [javaparser/javaparser#3053]
Hi, i and my team want to know more about the various features that javaparser may support, so we came up with some requirements for our project :

1. Control flow analysis
2. support for binaries
3. will it be maintained in future
4. lexeme related data
5. Data Dependancy graph
6. Incremental support
7. Data flow analysis
8. any other features ?
9. GotoDef edges
10. Reference edges
11. filtering nodes based on elementType

Can you please confirm the support for above features ?

**Comment by jlerbsc** [comment]
Hi @udit-dasari, after a brief consultation in the team here is my vision.

Control flow analysis: not implemented in JP project
support for binaries: Can you clarify your thought
will it be maintained in future: yes how it has been for years
lexeme related data: Can you clarify your thought
Data Dependancy graph: not implemented in JP project
Incremental support: Can you clarify your thought
Data flow analysis: not implemented in JP project
any other features ? Can you clarify your thought
GotoDef edges: Can you clarify your thought
Reference edges: Can you clarify your thought
filtering nodes based on elementType: If I understand this correctly, it is already operational else Can you clarify your thought

This questioning seems to result from a copy / paste, you might need to be more precise in your questions. Thanks.

**Comment by zhangziqiang1** [comment]
Thanks for your quick response, and I'm trying to verify if there's a similar situation.
