### ISSUE TITLE
Optional<MethodDeclaration> of method call expression returns "No Value Present".

### ISSUE THREAD

**Issue by Tejas8079** [javaparser/javaparser#3056]
I want the Optional<MethodDeclaration> of method call expression written in constructor.
Suppose I have method methodA() from class A which is called inside B class constructor.
Class B{
B(){
methodA();
}
}

Excepted Output : "Optional<MethodDeclaration> callerMethodOpt = mCallExp.findAncestor(MethodDeclaration.class);"
this statement should return B() constructor. It is working fine except constructor.
 
Actual output : the above statement returns "no value present" as method called inside constructor.

Am I missing some configuration while parsing java file?

Thanks in advance.

**Comment by jlerbsc** [comment]
MethodDeclaration is different from ConstructorDeclaration.
So you have to use 

    mCallExp.findAncestor(ConstructorDeclaration.class)

to get the expected result.

**Comment by Tejas8079** [comment]
Thanks @jlerbsc
