### ISSUE TITLE
isField and isParameter throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3057]
When i try to check if a JavaParserTypeVariableDeclaration is a field or a parameter, it throws an unsupported exception.

https://github.com/javaparser/javaparser/blob/e9af3e337100645141534e3a73004f2b45c2f572/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeVariableDeclaration.java#L137-L145

Looking into ResolvedDeclaration by default it returns False. Should JavaParserTypeVariableDeclaration also return false instead of throwing the exception?

https://github.com/javaparser/javaparser/blob/2903fc918dd87be53192aa1065047392f7adf4d1/javaparser-core/src/main/java/com/github/javaparser/resolution/declarations/ResolvedDeclaration.java#L43-L48

https://github.com/javaparser/javaparser/blob/2903fc918dd87be53192aa1065047392f7adf4d1/javaparser-core/src/main/java/com/github/javaparser/resolution/declarations/ResolvedDeclaration.java#L71-L76

**Comment by jlerbsc** [comment]
You are right usually this means that the feature is not yet implemented.

**Comment by 4everTheOne** [comment]
I think it can be easily fixed by simply removing the definition of both methods in JavaParserTypeVariableDeclaration and inherit from the super class. I will give it a try
