### ISSUE TITLE
JavaConcepts.java

### ISSUE THREAD

**Issue by msayagh** [javaparser/javaparser#306]
Hi,

I used your parser to parse the code of your parser :-) 

There is a bug in the parsing of the file "JavaConcepts.java"

Best regards

**Comment by matozoid** [comment]
Hi! What is the bug exactly?

**Comment by ftomassetti** [comment]
We have a file name `javaparser-testing/src/test/resources/com/github/javaparser/bdd/samples/JavaConcepts.java` but I have no idea how it could be related to this bug report

**Comment by matozoid** [comment]
Closing because there is no response. Please re-open if there is news.
