### ISSUE TITLE
if condition contains leading comments 

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#307]
Use DumpVisitor against  DumpVisitor.java itself

Comment will appear inside If condition in public void visit(final IfStmt n, final Object arg)

Method in error is DumpVisitor public void visit(final IfStmt n, final Object arg) or IfStmt.java itself

**Comment by ftomassetti** [comment]
Thanks for reporting this one

**Comment by kay** [comment]
I'm trying to find the right place to raise an issue without duplicating things. Is this issue related to this example/behaviour I'm seeing

Given
```
public class CommentTestCase {
    public static void main(String[] args) throws Exception {
        int a = 4, b = 8;
        if (a < b) { // what a weird bug?
            // Another comment
            if (b == a) {
            }
        }
        if (b > a) { // for real?
        }
        CompilationUnit cu = JavaParser.parse(new File("src/main/java/testcase/CommentTestCase.java"));
        System.out.println(cu.toString());
    }
}
```

I receive this output:

```
public class CommentTestCase {

    public static void main(String[] args) throws Exception {
        int a = 4, b = 8;
        if (a < b) {
            // Another comment
            if (b == a) {
            }
        }
        if (b > a) {
        // for real?
        }
        CompilationUnit cu = JavaParser.parse(new File("src/main/java/testcase/CommentTestCase.java"));
        System.out.println(cu.toString());
    }
}
```

Note that the comment on the `if (a < b) {` line has been removed. Seems to only happen if a comment attached to an IfStmt is followed by a comment attached to another  IfStmt.

**Comment by ftomassetti** [comment]
Yeah, probably related. The reason is that we assign some comments to node so "Another comment" is assigned to the if. "What a weird bug" is an orphan comment and the code printing Java does not remember to print orphan comments in all places

**Comment by matozoid** [comment]
Hey @ftomassetti, I'm looking at that last one, and I'm wondering what should be the output. This?

```java
if (a < b) {
    // what a weird bug?
    // Another comment
    if (b == a) {
    }
}
```

**Comment by ftomassetti** [comment]
Yes, I guess

**Comment by matozoid** [comment]
Where would "what a weird bug" be stored?

**Comment by matozoid** [comment]
I get it now, after digging through the visitor.

**Comment by matozoid** [comment]
This is identical to #263.

**Comment by jlerbsc** [comment]
It seems that this issue could be closed. No comment has been lost.

    @Test
    void test() {
        String actual = 
                "public class CommentTestCase {\n" + 
                "    public static void main(String[] args) throws Exception {\n" + 
                "        if (true) { // what a weird bug?\n" + 
                "            // Another comment\n" + 
                "            if (b == a) {\n" + 
                "            }\n" +
                "        }\n" + 
                "    }\n" + 
                "}";
        String expected = 
                "public class CommentTestCase {\n" + 
                "\n" +
                "    public static void main(String[] args) throws Exception {\n" + 
                "        if (true) {\n" + 
                "            // what a weird bug?\n" +
                "            // Another comment\n" + 
                "            if (b == a) {\n" + 
                "            }\n" + 
                "        }\n" + 
                "    }\n" + 
                "}\n";
        CompilationUnit cu = StaticJavaParser.parse(actual);
        TestUtils.assertEqualsStringIgnoringEol(expected, cu.toString());
    }
