### ISSUE TITLE
Unable to delete .jar files after parsing and using symbol solver.

### ISSUE THREAD

**Issue by kawaiifoxx** [javaparser/javaparser#3074]
I am having difficulties deleting .jar files after I parse them, I am using ProjectRoot for reading root directory.

After I parse the files and  use symbol solver to get resolved declarations and  then  I try to delete root directory after I am done with my work, I try to delete files and I can delete every file except .jar files.

I tried deleting root directory of files which I am trying to parse, without actually parsing it and it works fine, all the files get deleted.

``` java
public static SourceComponent parse(Path PATH) {
        ProjectRoot projectRoot = new SymbolSolverCollectionStrategy().collect(PATH);

        var sourceRoots = projectRoot.getSourceRoots();

        if (sourceRoots.isEmpty()) {
            throw new RuntimeException("[Parser] Source directory is empty i.e it does not contain any .java or .jar files.");
        }

        List<ResolvedDeclaration> resolvedDeclarations = getResolvedDeclarations(sourceRoots);

        return new SourceComponent(resolvedDeclarations);
    }
```

I am deleting files using  `FileDeleteStrategy.FORCE.delete(rootDir)`

Thanks for helping.  : )

**Comment by jlerbsc** [comment]
This may be related to the fact that when parsing jar files the JarFile.close () method is not invoked to free the resources.

**Comment by kawaiifoxx** [comment]
So, is there some way to fix this. so, that I can delete whole root directory some how.

**Comment by jlerbsc** [comment]
Could you test this version https://github.com/jlerbsc/javaparser before i push a PR i think it should solve your problem

**Comment by kawaiifoxx** [comment]
I tested this version and unfortunately, I still can't delete .jar files.

**Comment by jlerbsc** [comment]
It's curious because this version close all JarFile in a ShutDownHook. So resources used by these files are freed.

**Comment by kawaiifoxx** [comment]
Hey, jlerbsc Thanks for your quick reply.
I see the problem here, the problem for me is that I want  JarTypeSolver to release all resources after I am done parsing and symbol solving but it does that only when vm terminates.

So, I added this piece of code in ShutDownHookRegistry:
```java
public void closeAllFiles() {
            jarfiles.forEach(jarFile -> {
                try {
                    jarFile.close();
                } catch (IOException exception) {
                    Log.error("Cannot close jar file %s", jarFile::getName);
                }
            });

            jarfiles.clear();
        }
```

And to delete files in my project I did this:
```java
JarTypeSolver.ShutDownHookRegistry.getRegistry().closeAllFiles();
FileDeleteStrategy.FORCE.delete(rootDir);
```

And all files get deleted successfully.

**Comment by jlerbsc** [comment]
Yes you are right ShutDownHook is executed when VM stops. I had misunderstood the execution context. I thought you were unable to delete files when software was finished.

**Comment by jlerbsc** [comment]
You can use JarTypeSolver.ResourceRegistry.getRegistry().cleanUp() to explicitly freeing resources.

**Comment by kawaiifoxx** [comment]
@jlerbsc  Thanks for fixing the issue.
