### ISSUE TITLE
Multiple visitors: Order of Vistors

### ISSUE THREAD

**Issue by Balawalbutt** [javaparser/javaparser#308]
Hi , I have Three Visitor Methods Defined in my Class Which inherits Void Visitor 

```
public override void visit(MethodCallExpr n, object arg) -- > this method don't call to Super.visit
public override void visit(ConstructorDeclaration n, object arg) -> call to super.Visit at end
public override void visit(MethodDeclaration n, object arg) -> call to super .visit at end.
```

Calling this.visit(cu, null); from another member of the same class will automatically start  recursive calls to all these three visitors , now  , to the best of my understanding , MethodDeclaration visitor should be called first on a compilation unit before  Method methodCallExpr Visitor  is called. but this is not happening in my case. 
some times (When a source file changes)  MethodCallExpr Happen first and then rest of the visitors. 
this is creating a totally mess in my project. i want to know if there is a way to specify explicit call order or not ?
I would also want to know why this is happening ?

**Comment by matozoid** [comment]
Could you please create a minimal project that shows the issue? Something like https://github.com/matozoid/javaparser-issue-323 ? That would clear things up immensely.

**Comment by matozoid** [comment]
No follow up, closing.
