### ISSUE TITLE
TypeSolver does not resolve org.xml.sax.* names

### ISSUE THREAD

**Issue by michaelhkay** [javaparser/javaparser#3080]
Attempting to resolve a name such as Locator (which is actually org.xml.sax.Locator) fails.

I think the problem is probably at ReflectionTypeSolver line 21 which reads

```
protected boolean filterName(String name) {
        return !this.jreOnly || name.startsWith("java.") || name.startsWith("javax.");
    }
```

but I haven't succeeded in rebuilding from source to check whether the obvious change fixes it.

**Comment by michaelhkay** [comment]
I can work around the problem by doing

```
    combinedTypeSolver.add(new ReflectionTypeSolver() {
            protected boolean filterName(String name) {
                return super.filterName(name) || name.startsWith("org.");
            }
        });
```

so this definitely appears to be the cause.

**Comment by jlerbsc** [comment]
Can you try to instanciate ReflectionTypeSolver like this

    new ReflectionTypeSolver(false)

**Comment by michaelhkay** [comment]
Yes, on my travels with the debugger I realised that would be an alternative workaround (though it's possible it could have unwanted side-effects, I don't know). But I would expect the org.xml and org.w3c classes in the JDK to be treated in exactly the same way as all other classes in the JDK - certainly I didn't see any documentation that suggested otherwise.

**Comment by jlerbsc** [comment]
The javadoc says "This is an easy way to say" I need a JRE to solve classes, and the one that is currently running is fine. If false, will resolve any kind of type. ". This is not a workaround, it's just the way to go in your case.
