### ISSUE TITLE
More NamedNodes

### ISSUE THREAD

**Issue by thejohnfreeman** [javaparser/javaparser#309]
Should `Parameter` or `BaseParameter` be a `NamedNode`? I would find it helpful for a symbol table of `NamedNode`.

`BaseParameter` would need to add a `getName` method that defers to its `VariableDeclaratorId` child, but there is precedent for that pattern in `MethodCallExpr` which defers to its `NameExpr` child (though I'm ambivalent whether `MethodCallExpr` should be made a `NamedNode`).

**Comment by matozoid** [comment]
Wouldn't this visit the name of every BaseParameter Node twice, since its id is also a NamedNode?

**Comment by thejohnfreeman** [comment]
Would what visit? AFAIK, `NamedNode` is just an interface with `getName()`.

**Comment by matozoid** [comment]
You're right, let's get this merged.
