### ISSUE TITLE
Race condition in JavaParserTypeSolver

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3090]
`JavaParserTypeSolver` has an `JavaParser` instance that is used to parse the files. At the moment it is not thread safe which makes it throw weird exceptions when parsing from different threads. The limitation here is `JavaParser` because it can only parse one instance at a given time. 

I think a simple fix for this issue, could be make the parser synchronized to avoid the concurrency.

## Stack trace
```
Caused by: java.lang.AssertionError: Invalid token kind 2147483647
	at com.github.javaparser.TokenTypes.getCategory(TokenTypes.java:257)
	at com.github.javaparser.TokenTypes.isComment(TokenTypes.java:63)
	at com.github.javaparser.GeneratedJavaParserTokenManager.CommonTokenAction(GeneratedJavaParserTokenManager.java:106)
	at com.github.javaparser.GeneratedJavaParserTokenManager.getNextToken(GeneratedJavaParserTokenManager.java:2951)
	at com.github.javaparser.GeneratedJavaParser.jj_scan_token(GeneratedJavaParser.java:12682)
	at com.github.javaparser.GeneratedJavaParser.jj_3_1(GeneratedJavaParser.java:8747)
	at com.github.javaparser.GeneratedJavaParser.jj_2_1(GeneratedJavaParser.java:7873)
	at com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:74)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:123)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$parse$1(JavaParserTypeSolver.java:153)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 32 more
```

## Unit test
```java
@RepeatedTest(25)
void testTryToSolveTypeWithMultipleThreads() {
    class StressRunnable implements Runnable {

        private final String typeToSolve;
        private final JavaParserTypeSolver javaParserTypeSolver;

        StressRunnable(String typeToSolve, JavaParserTypeSolver javaParserTypeSolver) {
            this.typeToSolve = typeToSolve;
            this.javaParserTypeSolver = javaParserTypeSolver;
        }

        @Override
        public void run() {
            javaParserTypeSolver.tryToSolveType(typeToSolve);
        }
    }

    JavaParserTypeSolver javaParserTypeSolver = JAVA_PARSER_PROVIDER.get();

    CompletableFuture<Void> tasks = CompletableFuture.allOf(
            CompletableFuture.runAsync(new StressRunnable("com.github.javaparser.ast.body.Object",
                    javaParserTypeSolver)),
            CompletableFuture.runAsync(new StressRunnable("com.github.javaparser.ast.comments.Object",
                    javaParserTypeSolver)),
            CompletableFuture.runAsync(new StressRunnable("com.github.javaparser.ast.expr.Object",
                    javaParserTypeSolver)),
            CompletableFuture.runAsync(new StressRunnable("com.github.javaparser.ast.stmt.Object",
                    javaParserTypeSolver))
    );
    assertDoesNotThrow(tasks::join,
            "JavaParserTypeSolve should work properly when called from multiple threads.");
}
```

**Comment by jlerbsc** [comment]
Maybe you can just create new instances of JavaParserTypeSolver, one for each thread.

**Comment by 4everTheOne** [comment]
That for sure could be a workaround for the issue, but there are a some situation that we can take advantages of using the same configuration for all of them. Imagine that we have a project with multiple modules:

Module A - Base code
Module B - Uses code from module A
Module C - Uses code from module A

Since we are talking about some modules of the current project they share a lot of dependencies among them. In this type of scenarios we would like to also share the same configuration to take advantage of the cached types.

**Comment by 4everTheOne** [comment]
Also, I forgot to mention that each module is processed in a different thread to speed up the process.

**Comment by MysterAitch** [comment]
Thread safety is something that JP explicitly doesn't make any guarantees about or support, but in the past has included some tweaks that have blocked people from implementing their own workarounds (e.g., #2668 / #2694).

Personally I don't have any objections to improving thread safety, but any PR that does get merged will need sufficient documentation/comments to highlight that there are no guarantees.

**Comment by 4everTheOne** [comment]
I understand your point. 

I think this a tiny tweak in JP could make it easier to work it in threads, but off course without guarantees of being thread safe. In PR #3091 i suggest a tweak that solves this issue. 

Should I add comments to the PR highlighting that there are no guarantee despiste the tweak?

**Comment by corradomio** [comment]
JavaParser, during the analysis, creates the AST of the current file using a LOCAL FIELD as storage (```JavaParser.astParser```).
It is absolutely MANDATORY to have a DIFFERENT instance of JavaParser FOR EACH THREAD/FILE processed.

You can REUSE the same instance ONLY after completing the previous analysis.

The best solution to use JavaParser in parallel is being able to use multiple instances in parallel, that is, to remove STATIC objects as, for example ""JavaParserFacade.get(TypeSolver)"" and its STATIC WeakHashMap ""instances"".

An alternative solution for ""JavaParserFacade.instances"" is to make it  ""ThreadLocal"", this resolve the problem of the "synchronize" and the problem of TypeSolves that are not removed when an analysis is terminated.

But other solutions are possible.
