### ISSUE TITLE
1.0.11 Release

### ISSUE THREAD

**Issue by SmiddyPence** [javaparser/javaparser#31]
It would be good to get the additional comment support into a release version on maven central.

A chap called before seems to have done this previously.  Anyone else offer advice on how to do this?

**Comment by arouel** [comment]
I can do it again if everything is ready.

**Comment by SmiddyPence** [comment]
matozoid's call I would say, if he wants to put anything else in first.

**Comment by matozoid** [comment]
I'd say release as often as possible. Can whoever releases this time also document the process on the wiki, so others can give it a go?

**Comment by SmiddyPence** [comment]
Sounds like we're set!

**Comment by arouel** [comment]
@SmiddyPence I will do it in the next days.

**Comment by arouel** [comment]
Next release will be available soon on Central Repository.

**Comment by arouel** [comment]
How to do a release is documented under: https://github.com/matozoid/javaparser/wiki/How-to-create-a-release-on-Central-Repository

**Comment by SmiddyPence** [comment]
Nice one, thanks!

**Comment by matozoid** [comment]
Awesome!

**Comment by SmiddyPence** [comment]
Don't these usually go in over the weekend? Can't see it yet

**Comment by arouel** [comment]
It's available since February the 2nd: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.code.javaparser%22%20AND%20a%3A%22javaparser%22

**Comment by SmiddyPence** [comment]
Sorry wasn't clear I mean the search/indexing on mvnrepository.com is meant to be updated at weekends.

**Comment by talios** [comment]
Use http://search.maven.org if you want the official up-to-date index search results for maven-central.
