### ISSUE TITLE
JavaParser parses local variables in a method reference as a ClassOrInterfaceType

### ISSUE THREAD

**Issue by corradomio** [javaparser/javaparser#3102]
Given the class

```
public class TestBasic {

    public static void main(String[] args) {
        HashMap<String, String> statsStorageForSession = new HashMap<>();
        Function<String, String> statsStorageProvider = statsStorageForSession::get;
    }
}
```

```statsStorageForSession``` in ```statsStorageForSession::get``` is parsed as ```ClassOrInterfaceType```

**Comment by jlerbsc** [comment]
This is probably a lack in the JavaParser grammar. @MysterAitch what do you think about that?
TypeExpr is defined as a scopes for MethodReferenceExpr nodes to encapsulate Types. By default the internal type is a ClassOrInterfaceType. I'm not sure the JSL (https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.13) provides more information in this case.

**Comment by MysterAitch** [comment]
I'll need to double check once I'm at a computer but the current behaviour does seem reasonable (unless I'm missing something).

Could you share some more details about the `ClassOrInterfaceType` that gets returned -- specifically, is it referring to `Function` with type parameters?

Note that at compile time, it's not possible to determine whether the declared type is a class vs interface (vs record).

The only way to distinguish is to examine the declaration of the class or interface (or record) -- and this happens during symbol resolution.

**Comment by jlerbsc** [comment]
In the AST ClassOrInterfaceType has a SimpleName child. I'm not sure I answer the question ;-)

**Comment by 4everTheOne** [comment]
I think issue #3077 is also related with this :)

**Comment by jlerbsc** [comment]
I'm closing this issue because the answer was given by this comment "Note that at compile time, it's not possible to determine whether the declared type is a class vs interface (vs record)." and there's no real problem.
