### ISSUE TITLE
Simplify the use of JavaParser

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3108]
Currently working with JavaParser requires some unnecessary boilerplate (See conversation at https://github.com/javaparser/javaparser/pull/3081).

The intention of the issue is to allow a conversation with possible solutions for this problem.

**Comment by 4everTheOne** [comment]
A suggestion to simplify usage of `JavaParser` without breaking the current API could be using a method like the following:
```java
public CompilationUnit parseAndUnpack(final File file) throws FileNotFoundException {
    return handleResult(parse(file));
}
```
This method unpacks the result (basically the boilerplate code that is always required) and if the compilation fails a `ParseProblemException` is thrown (similar to how `StaticJavaParser` handles it). This allows us to keep the old JavaParser API and also implement a simpler way of working with `JavaParser`.

The method handle result would look something like:
```java
private <T extends Node> T handleResult(ParseResult<T> result) {
  if (result.isSuccessful()) {
  
    Optional<T> results = result.getResult();
    if (results.isPresent())
      return results.get();
    else
      throw new IllegalStateException("Parsed results is marked as successful but has no result present.");

  } else {
    throw new ParseProblemException(result.getProblems());
  }
}
```

Let me know your opinions! :)

**Comment by MysterAitch** [comment]
I hesitate to agree that it is _"unnecessary"_ boilerplate :wink: 

Personally, as mentioned in #3081, I'm open to adding methods like this into the main `JavaParser` class :+1: 

I say this with the caveat that @jlerbsc and others are more than welcome to chip in with reasons this is a bad idea -- I shan't be offended!


Here's an example for the other parse methods to explicitly highlight that these would be a wrapper around the "normal" existing methods:

```java
    public ParseResult<Statement> parseStatement(final String statement) {
        return parse(STATEMENT, provider(statement));
    }

    // Matching "and unpack" method:
    public ParseResult<Statement> parseStatementAndUnpack(final String statement) {
        // delegates to the matching `parseStatement`
        return handleResult(parseStatement(statement));
    }
    // Alternative naming:
    public ParseResult<Statement> parseAndUnpackStatement(final String statement) {
        // delegates to the matching `parseStatement`
        return handleResult(parseStatement(statement));
    }
```

**Comment by MysterAitch** [comment]
I would also lean towards the method being named to match the naming of the wrapper methods and what they do.

Perhaps something like:
- `unpackResult` (to match the above) or
- `unwrapResult` (to indicate we're returning a child object) 
- `parseAndGetStatement` (to match optional's `get` method)

**Comment by jlerbsc** [comment]
Personally I think this API was introduced previously by the project leaders to deal with parsing issues. If a user wants to manage a different strategy it is very easy to adapt the current behavior with an "adapter" pattern. I'm not convinced this is a boilerplate code, especially since it's only used in one place. Maybe a better documentation would suffice to describe how to start or parse with JP. There are still a lot of bugs to fix or TODO to implement. In fact it does not seem to me a priority but if you think that it is essential go there :-)

**Comment by matozoid** [comment]
Here is the article that describes the thinking behind how it works right now: https://javaparser.org/the-quick-and-the-full-api-of-javaparser/
