### ISSUE TITLE
Arrow missing in Switch Expression + jumbled up in LexicalPreservingPrinter

### ISSUE THREAD

**Issue by kernkat97** [javaparser/javaparser#3113]
Hi,
I stumbled across a problem that is probably related to issue #2636 - I have the same problem with parsing Java 12 switch expressions, the arrows are replaced with colons. When the resulting CompilationUnit is later passed to the LexicalPreservingPrinter, the arrows are there, but the expression after "case" is appended to the end of the line.
Here's a minimal code example:
```kotlin
StaticJavaParser.getConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_12)

val originalSourceCode = "public class HelloWorld {\n" +
        "  public static void main(String[] args) {\n" +
        "      final int value = 2;\n" +
        "      String numericString;\n" +
        "    \n" +
        "      switch (value)\n" +
        "      {\n" +
        "        case 1 -> numericString = \"one\";\n" +
        "        case 2 -> numericString = \"two\";\n" +
        "        case 3 -> numericString = \"three\";\n" +
        "        default -> numericString = \"N/A\";\n" +
        "      }\n" +
        "    \n" +
        "      System.out.println(\"value:\" + value + \" as string: \" + numericString);\n" +
        "  }\n" +
        "}\n"

val originalCompilationUnit = StaticJavaParser.parse(originalSourceCode)
LexicalPreservingPrinter.setup(originalCompilationUnit)

// ...

val modifiedSourceCode = LexicalPreservingPrinter.print(originalCompilationUnit)
```

After executing, originalCompilationUnit looks like this...
```java
public class HelloWorld {

    public static void main(String[] args) {
        final int value = 2;
        String numericString;
        switch(value) {
            case 1:
                numericString = "one";
            case 2:
                numericString = "two";
            case 3:
                numericString = "three";
            default:
                numericString = "N/A";
        }
        System.out.println("value:" + value + " as string: " + numericString);
    }
}

```

... and modifiedSourceCode like this:
```java
public class HelloWorld {
  public static void main(String[] args) {
      final int value = 2;
      String numericString;
    
      switch (value) { 
        case  -> numericString = "one";1
        case  -> numericString = "two";2
        case  -> numericString = "three";3
        default -> numericString = "N/A";
      }
    
      System.out.println("value:" + value + " as string: " + numericString);
  }
}
```

I'm not sure if this is caused by the issue mentioned above or a problem on its own (I'm new to JavaParser). I'd be really grateful if someone could take a look at it and/or give some hints on a workaround :)

**Comment by jlerbsc** [comment]
Not sure but may be it's a parsing error.

**Comment by WanliZhong** [comment]
Our group try to solve this problem and would like to get some advice. Thank you! @jlerbsc

SE_SUSTech

**Comment by jlerbsc** [comment]
Maybe there is a parsing issue or LexicalPreservingPrinter issue. We can reproduce this with this unit test.

    @Test
    public void issue3113() {
        StaticJavaParser.getConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_12);

        String originalSourceCode = "public class HelloWorld {\n" +
                "  public static void main(String[] args) {\n" +
                "      final int value = 2;\n" +
                "      String numericString;\n" +
                "      switch (value)\n" +
                "      {\n" +
                "       case 1 -> numericString = \"one\";\n" +
                "       default -> numericString = \"N/A\";\n" +
                "      }\n" +
                "      System.out.println(\"value:\" + value + \" as string: \" + numericString);\n" +
                "  }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(originalSourceCode);
        LexicalPreservingPrinter.setup(cu);
        SwitchStmt expr = cu.findFirst(SwitchStmt.class).get();
        String modifiedSourceCode = LexicalPreservingPrinter.print(expr);
        System.out.println(modifiedSourceCode);
    }

result

    switch (value)
      {
       case  -> numericString = "one";1
       default -> numericString = "N/A";
      }

**Comment by deadlocklogic** [comment]
It is a parsing issue.
After a little digging I found the offending part but I will leave it to the maintainers to fix the issue/create a PR.
Of course I can dig further, but maybe someone is already familiar with the parser/knows other corner cases.
Offending lines:
https://github.com/javaparser/javaparser/blob/890979ad9844e3e71df454e72ee102f9647846ee/javaparser-core/src/main/javacc/java.jj#L4355-L4359
Fix:
```
 { 
     TokenRange r=range(begin, token()); 
     stmts.add(new ExpressionStmt(expression.getTokenRange().get(), expression));
     ret = new SwitchEntry(r, labels, EXPRESSION, stmts); 
 } 
```

**Comment by WanliZhong** [comment]
> It is a parsing issue.
> After a little digging I found the offending part but I will leave it to the maintainers to fix the issue/create a PR.
> Of course I can dig further, but maybe someone is already familiar with the parser/knows other corner cases.
> Offending lines:
> https://github.com/javaparser/javaparser/blob/890979ad9844e3e71df454e72ee102f9647846ee/javaparser-core/src/main/javacc/java.jj#L4355-L4359
> 
> 
> Fix:
> ```
>  { 
>      TokenRange r=range(begin, token()); 
>      stmts.add(new ExpressionStmt(expression.getTokenRange().get(), expression));
>      ret = new SwitchEntry(r, labels, EXPRESSION, stmts); 
>  } 
> ```

I've tried your modification and it can really solve the problem. I've created a [PR](https://github.com/javaparser/javaparser/pull/3235)
