### ISSUE TITLE
Coveralls report not updating

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3115]
Hello, I was looking at the [Coveralls report](https://coveralls.io/github/javaparser/javaparser) and looks like it was not updated since November 2020.

Was it intentional?

**Comment by MysterAitch** [comment]
Mostly yes -- with the need to move away from Jenkins, the integration with coveralls wasn't there any more.

I forget the rest of the rationale but this led to switching the codecov instead.

Perhaps we could do both? :)

**Comment by 4everTheOne** [comment]
Oh ok, thanks for the explanation :)

Also just for curiosity, why is JP SS Core not included in Codecov analysis?

**Comment by MysterAitch** [comment]
> Oh ok, thanks for the explanation :)
> 
> Also just for curiosity, why is JP SS Core not included in Codecov analysis?

Likely a mistake :+1:

**Comment by MysterAitch** [comment]
Thinking about it, this would explain #3190 if the symbol solver code always reports 0% coverage.

**Comment by hazendaz** [comment]
Not sure the direction here still, but saw coveralls plugin in the build.  If needed there is a simple GHA action for that which can be found here https://github.com/mybatis/mybatis-3/blob/master/.github/workflows/coveralls.yaml.  If the other is being used, maybe remove coveralls plugin all together.
