### ISSUE TITLE
Partial SymbolSolver for Map/HashMap

### ISSUE THREAD

**Issue by thiagodnf** [javaparser/javaparser#3119]
Hello everyone,

I am trying to use the SymbolSolver to resolve `Map<String, CloneFailedException>`. The problem is because `CloneFailedException` comes from a library that I didn't include (in fact, I don't want to include it), so JavaParser is throwing an exception about the missing of this class.

I would like to know if it is possible to resolve just "Map" and "String"? In other words, is it possible to get the following as output?

```
java.util.Map<java.util.String, CloneFailedException>
```

Thanks in advance.

**Comment by MysterAitch** [comment]
Not to my knowledge.

There might be workarounds like providing a stub for the other library's classes (variable feasibility -- e.g. just a couple of classes vs a whole library), but this isn't something I've personally tried so your feedback here would be appreciated!

**Comment by jlerbsc** [comment]
Hi @thiagodnf if @MysterAitch answered your question can you close this issue please?

**Comment by Col-E** [comment]
If you do end up going with the stubbed classes approach, I'd recommend checking out [JPhantom](https://github.com/gbalats/jphantom). It can automate the process pretty easily for you. I have a fork open with some improvements and the artifact is tossed up on Jitpack if anything in the latest PR interests you.

**Comment by jlerbsc** [comment]
It seems to me that the approach of the JP project leaders has been to avoid as much as possible including external libraries but it is interesting to have this in mind.

**Comment by thiagodnf** [comment]
Thanks everyone for the comments and also @4everTheOne for trying to submit a pull request that tries to address my issue (in fact, you went beyond of my issue)

I think what you did @4everTheOne could be useful to me but, of course, I don't want to break the entire code. Regarding the stubbed classes, it looks also interesting but the problem is I don't know how to create stubs "dynamically" (it means that I want to create those ones just when I have a non-resolved class)

Again, thanks for this discussion
