### ISSUE TITLE
Instrumenting Java code

### ISSUE THREAD

**Issue by IjazAhmed** [javaparser/javaparser#3120]
// code before instrumentation test.java
public class test{
public void m (int a, b){
a=a+b;
b=a*b;
}
}

**Question:**
I traversed the file test.java (given above) with the help of ASTVisitor, and generated some assert statements as a String. Now, I want to instrument test.java code with the generated assert statements as shown below. Very specifically,  I am supposed to add assert statements at the start and end of a method body. It would be kind of you, if you may please guide me, how to add asserts statements with the aid of an example-code? 

// code after instrumentation test.java
public class test{
public int m (int a, b){
assert(a >0 && b>0);
a=a+b;
b=a*b;
assert(a>0 && b>0);
}
}

**Comment by jlerbsc** [comment]
Hi @IjazAhmed, Did you take some time to read this book https://github.com/javaparser/javaparser-visited ?

**Comment by jlerbsc** [comment]
This is an exemple of what you can do.

    @Test
    public void c() {
        String code = "public class Test {\n" +
                " public void m(int a, int b) {\n" +
                "  a=a+b;\n" +
                "  b=a*b;\n" +
                " }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        MethodDeclaration md = cu.findFirst(MethodDeclaration.class).get();
        Expression assertExpr = new BinaryExpr(new NameExpr("a"), new IntegerLiteralExpr(), Operator.GREATER);
        md.getBody().get().getStatements().addFirst(new AssertStmt(new EnclosedExpr(assertExpr)));
        md.getBody().get().getStatements().addLast(new AssertStmt(new EnclosedExpr(assertExpr)));
        System.out.println(cu.toString());
    }

results

    public class Test {
     public void m(int a, int b) {
        assert (a > 0);
        a = a + b;
        b = a * b;
        assert (a > 0);
     }
    }

**Comment by IjazAhmed** [comment]
Thank you for your detailed help. The guided example modifies the AST only, and changes are not reflected in the source code. So, if I want to persist the changes in source code, what should I do. Once again, thank you for your help.

**Comment by jlerbsc** [comment]
You are right this example show you how to insert assert statement in your compilation unit. You have to write this result in the java source file probably using the LexicalPreservingPrinter.

**Comment by MysterAitch** [comment]
> Thank you for your detailed help. The guided example modifies the AST only, and changes are not reflected in the source code. So, if I want to persist the changes in source code, what should I do. Once again, thank you for your help. 

You are correct that it is an in-memory change, not affecting the file on disk.

The `SourceRoot` object has a method `save` that allows you to save the compilation unit to disk. Whether you have direct access to it will depend on how you've setup your parsing.

Alternatively, you can use one of the `printer` classes to convert the source code to a string and then manually write the string to a file.

Hope this helps @IjazAhmed but do feel free to comment again if needing another nudge in the right direction :)
