### ISSUE TITLE
How to add new method call in existing method call chain in return statement

### ISSUE THREAD

**Issue by nareshgnT** [javaparser/javaparser#3122]
Thank you all for your efforts and this library is very useful.
```java
        ParseResult<CompilationUnit> cup = new JavaParser().parse("public class SwaggerConfig {\n" +
                "    @Bean\n" +
                "    public Docket api() {\n" +
                "        return new Docket(DocumentationType.SWAGGER_2)\n" +
                "                .select()\n" +
                "                .apis(RequestHandlerSelectors.basePackage(\"com.test\"))\n" +
                "                .paths(PathSelectors.any())\n" +
                "                .build()\n" +
                "                .ignoredParameterTypes(AuthenticationPrincipal.class)\n" +
                "                .directModelSubstitute(ResponseEntity.class,Void.class)\n" +
                "                .globalOperationParameters(getParameters());\n" +
                "    } }");
```
`javaparser-core:3.18.0`
In the above code, I want to add another method `myNewMethod(Myclass.class)` after `.globalOperationParameters(getParameters())`. expected output as follows

```java
public class SwaggerConfig {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.test"))
                .paths(PathSelectors.any())
                .build()
                .ignoredParameterTypes(AuthenticationPrincipal.class)
                .directModelSubstitute(ResponseEntity.class,Void.class)
                .globalOperationParameters(getParameters())
                .myNewMethod(Myclass.class); // added method
    }
}
```

I tried multiple options but nothing worked. The only way could be to get `ReturnStmt.getExpression.getChildNodes.add` but `getChildNodes` return immutable list. Any help appreciated

**Comment by jlerbsc** [comment]
This operation is not as easy as it seems, may be this example can help you.

    @Test
    public void addingMethodCallExpr() {
        String code = "public class SwaggerConfig {\n" +
            "    @Bean\n" +
            "    public Docket api() {\n" +
            "        return new Docket(DocumentationType.SWAGGER_2)\n" +
            "                .select()\n" +
            "                .apis(RequestHandlerSelectors.basePackage(\"com.test\"))\n" +
            "                .paths(PathSelectors.any())\n" +
            "                .build()\n" +
            "                .ignoredParameterTypes(AuthenticationPrincipal.class)\n" +
            "                .directModelSubstitute(ResponseEntity.class,Void.class)\n" +
            "                .globalOperationParameters(getParameters());\n" +
            "    } }";
        CompilationUnit cu = StaticJavaParser.parse(code);
        List<MethodCallExpr> exprs = cu.findAll(MethodCallExpr.class);
        MethodCallExpr first = exprs.get(0); // this is the scope of the new methodCallExpr
        Node parent = first.getParentNode().get();
        MethodCallExpr replacementNode = new MethodCallExpr(first, "myNewMethod"); // create the new MethodCallExpr (without parameter) with the last mce in scope
        parent.replace(first, replacementNode); // replace the previous last MethodCallExpr by the new one
        System.out.println(cu.toString());
    }

This example returns 

    public class SwaggerConfig {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.basePackage("com.test")).paths(PathSelectors.any()).build().ignoredParameterTypes(AuthenticationPrincipal.class).directModelSubstitute(ResponseEntity.class, Void.class).globalOperationParameters(getParameters()).myNewMethod();
    }
}

**Comment by nareshgnT** [comment]
Thank you @jlerbsc very much for your quick response, it worked like a charm!! Please close this issue.
