### ISSUE TITLE
why this method without return type compiled?

### ISSUE THREAD

**Issue by esoftGithub** [javaparser/javaparser#3135]
hello
int getMax() {}  // correct syntax is -> int getMax(){ return 3;}
this issue is also for int getMax();

thanks

**Comment by jlerbsc** [comment]
Can you clarify your problem please?

**Comment by esoftGithub** [comment]
I want to read the classes and also check their syntax problems, but for example, in the User class, the getMax method does not have the correct syntax as mentioned above , but the following code works correctly:
**CompilationUnit cu = StaticJavaParser.parse(new File( "User.java"));**
**ClassOrInterfaceDeclaration myClass = cu.getClassByName("User").isPresent() ? cu.getClassByName("User").get() : null;**

**User.java**
````
public class User {
    private String name = "aa";
    private int max = 5;
    public User(String name) {this.name = name;}
    int getMax();
}
````

**Comment by MysterAitch** [comment]
JavaParser is primarily a parser / resolver, not a compiler. Given this, JavaParser is more permissive than e.g. javac would be. 

See the grammar and the validators for details about what JavaParser specifically checks for.


The other substantial factor to bear in mind is that JavaParser also deals with partial / modification-in-progress syntax trees.

What I mean by this is that we might create a new method declaration object, then set the return type, and THEN add in the return statement. The intermediate state is invalid java, but JavaParser (generally) needs to allow it.


There are potentially ways to do this (e.g. builders and other bits and probably other things that the cleverer people on the team can figure) but I don't _think_ this is a direction JavaParser is likely to head in.


I'm not at a computer at the moment, but it should be fairly easy to add your own validators if that is of interest -- a relatively naive implementation just checking for the presence of a return statement should be easy enough, but a more complete one which does data flow analysis and logic checks will be trickier (e.g. to check all branches / conditionals). Let me know if the simpler/more naive version is of interest and if you need a hand with that.
