### ISSUE TITLE
When resolve a MethodCallExpr, throws 'java.lang.UnsupportedOperationException'

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#3140]
Test case:
```java
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class TestIssue3140 {
    public static void main(String[] args) throws IOException {
        Path pathToJar = Paths.get("/Users/liuyuan/Downloads/dataset/traccar-4.6/libs/jakarta.annotation-api-1.3.4.jar");
        ParserConfiguration config = new ParserConfiguration();
        CombinedTypeSolver cts = new CombinedTypeSolver();
        cts.add(new ReflectionTypeSolver(false));
        cts.add(new JarTypeSolver(pathToJar));
        config.setSymbolResolver(new JavaSymbolSolver(cts));
        StaticJavaParser.setConfiguration(config);

        String str = "import java.lang.reflect.Method;\n"
                   + "import javax.annotation.security.PermitAll;\n"
                   + "public class Foo {\n"
                       + "void a() {\n" 
                       + "    Method method = new Method();\n"
                       + "    method.isAnnotationPresent(PermitAll.class);\n"
                       + "}\n" + "}\n";

        CompilationUnit cu = StaticJavaParser.parse(str);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        
        if (mce.getScope().isPresent()){
            System.out.println(mce.resolve().getQualifiedSignature());
        }
    }
}
```
The code `str` comes from traccar-4.6's `SecurityRequestFilter.java` file, line 108.

The jar is attached here.
[jakarta.annotation-api-1.3.4.zip](https://github.com/javaparser/javaparser/files/6091521/jakarta.annotation-api-1.3.4.zip)

**Comment by jlerbsc** [comment]
It's because there are functions which are not implemented when resolving an annotation from a library. Here JP tries to find the ancestors of the annotation and there is no implementation for the moment. I will try to add the implementation this weekend

**Comment by 4everTheOne** [comment]
I can confirm the issue. I reproduced the issue and implementing the method for `JavassistAnnotationDeclaration` fixed it. @jlerbsc do you mind if i submit the PR?

**Comment by jlerbsc** [comment]
I don't understand if I take the time to analyze the problem why are you doing the same?

**Comment by 4everTheOne** [comment]
I just asked if you didn't mind, because I started to take a look at it before doing any comment on the issue because I was not sure if i was able to solve it. But during the process I manage to understand it and implement a fix for it. After that I saw your message and I asked if you didn't mind, because i don't want to waste your time on it.

I'm sorry about this, I should have written a message.

**Comment by ghost** [comment]
@jlerbsc @4everTheOne Thanks for your attention and help.

**Comment by maartenc** [comment]
PR #3167 also contains a fix for this

**Comment by ghost** [comment]
@jlerbsc well done, thank you. And I'll close this issue.

**Comment by jlerbsc** [comment]
Thank you @maartenc ;-)

**Comment by ghost** [comment]
@maartenc thank you.
