### ISSUE TITLE
JavaParser Position API should provide a method to return first position and last position from a list of positions 

### ISSUE THREAD

**Issue by f71uday** [javaparser/javaparser#3143]
Java Parser Position API should provide a method to compare a list of position and tell which position appears first and which position appears last 

 public Position firstPosition(List<Position> positions);

public Position lastPosition(List<Position> positions);

**this help in finding the uses of NameExpr and SimpleName**

**Comment by MysterAitch** [comment]
You might find `PositionUtils` of interest - that has some helper methods which could help you.

I also see that `Position` implements `Comparable` - you can use a sorted collection of positions to figure out first / last.

Hope this helps, but feel free to post again if you need a bit more.

**Comment by f71uday** [comment]
HI @MysterAitch  `PositionUtils` fits right 

Thank you so much for helping Out !!!

**Comment by MysterAitch** [comment]
Wonderful! 🤗🤗
