### ISSUE TITLE
JavaParserSymbolDeclaration is used to represent variables, but #isVariable() always returns false

### ISSUE THREAD

**Issue by cargaji** [javaparser/javaparser#3159]
A simple example could be:

```
class Test {
  void f() {
    int a = 0;
    while (a < 10) {}
  }
}
```

When applying `#resolve()` on the `NameExpr` that represents `a` in the condition for the `WhileStmt`, it returns a `JavaParserSymbolDeclaration`. This class reads in its javadoc that it should be merged with `JavaParserVariableDeclaration`. In the meantime, symbol declaration's `#isVariable()` returns `false` in all cases, but in this case (and possibly others) it should return `true`.

**Comment by jlerbsc** [comment]
Hi @cargaji You are right. Thanks you for reporting this bug.
