### ISSUE TITLE
Contruct the CFG for a give method

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#3164]
Hi, I’m trying to get the customized types (i.e., classes, interfaces, and enums) in a statement.
For example, line 3 is expected to return types that are referenced or used: C1 and C2.  

```java
1. C1 c1 = new C1();
2. C2 c2 = new C2();
3. int i = c1.m(c2); 
```

Because I concern the appearance order of types. So I first construct the CFG (flow-sensitive and path-sensitive) for a given method; then I extract the declaring types of variables and methods for each node.

One way to build a CFG is walking the AST tree, which is difficult to deal with loops and conditional branches, as well as other keywords with jumping functions, such as `break`. 

So is there an easier way in JavaParser to implement a CFG? Or a better way to get the sequences of types? thank you~

**Comment by zhizhixiongxuwei** [comment]
据我所知应该没有，如果想要CFG等信息可能用wala会好点？

**Comment by jlerbsc** [comment]
Building a cfg (control flow graph) is not a trivial task but it can be done from the AST.

**Comment by jlerbsc** [comment]
> 据我所知应该没有，如果想要CFG等信息可能用wala会好点？

@zhizhixiongxuwei can you use english to answer this would allow everyone to understand your answer.

**Comment by ghost** [comment]
@jlerbsc thank you. I think so, I'll close this issue. 
@zhizhixiongxuwei thank you. I'll try Wala. (我抽空瞧瞧，谢谢老哥)
