### ISSUE TITLE
How to get a full qualified reference of method?

### ISSUE THREAD

**Issue by sergiofigueras** [javaparser/javaparser#317]
Hello guys,

I need to parse each statement and see if that statement calls another class, for example:

```
public void testGetAddressFail() throws UnknownHostException {
    mockStatic(InetAddress.class);
    when(InetAddress.getLocalHost())
        .then(new ThrowsExceptionClass(UnknownHostException.class));

    ApplicationHelper applicationHelper = new ApplicationHelper();
    applicationHelper.getHostAddress();
  }
```

I should run this block and see if it references a **when** method present in PowerMockito (org.powermock.api.mockito.PowerMockito.when).

The problem is that each MethodCallExpr doesn't references a class that's being called. I mean that the value that's inside this MethodCallExpr is "when(InetAddress.getLocalHost()).then(new ThrowsExceptionClass(UnknownHostException.class))" and it doesn't contains any references to **org.powermock.api.mockito.PowerMockito.when**

So, I would need to get this reference of which class is this method refering (ex content of MethodCallExpr be org.powermock.api.mockito.PowerMockito#when).

How can I achieve this with Javaparser?

**Comment by ftomassetti** [comment]
It depends how much reliable you need it to be.

JavaParser is... a parser: it analyzes the source code and build an Abstract Syntax Tree so we know that `when(InetAddress.getLocalHost()).then(new ThrowsExceptionClass(UnknownHostException.class))` is method call to a method named when. What we do not know is which method is actually called:
- is it a method declared in the current class?
- is it a method declared in an enclosing class?
- is it an inherited method?
- is it a method imported statically?

To understand that precisely you would need to consider all these options and possibly pick the right "when" method considering the type of parameters. This is complex and for this case I would suggest to use [JavaSymbolSolver](https://github.com/ftomassetti/java-symbol-solver) which is built on top of JavaParser. However it is significantly less mature than JavaParser (disclaimer: I wrote JavaSymbolSolver, so I have strong bias).

Now, alternatively you can just look at the imports and see if `org.powermock.api.mockito.PowerMockito.when` has been imported statically and in that case assume that your call to "when" refers to that particular "when". If you do not need something absolutely always correct you can go away with this.

Also, you can load the class using javassist and examine the bytecode.
