### ISSUE TITLE
Using resolve() method in multithreading context

### ISSUE THREAD

**Issue by dimizisis** [javaparser/javaparser#3171]
I would like to be able to resolve symbols (ClassOrInterfaceDeclaration or MethodDeclaration etc.) in a multithreading context. As I've seen in some issues posted, there is a possibility of declaring a SymbolSolver for each thread. Is there any example code to be guided with? I tried declaring a symbol solver for every thread (inside my Visitor class) and tried using resolveDeclaration() method, but with no luck.

For example, I want the following code to be executed concurrently:
```java
private List<String> getSuperClassNames(ClassOrInterfaceDeclaration javaClass) {
    try {
         return javaClass
                   .getExtendedTypes()
                   .stream()
                   .map(extendedType -> extendedType.resolve().getQualifiedName())
                   .collect(Collectors.toList());
    } catch (Exception e) { return null; }
}
```

My configuration for StaticJavaParser (Main):

```java
TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(getCurrentProject()));
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(javaParserTypeSolver);
ParserConfiguration parserConfiguration = new ParserConfiguration();
parserConfiguration.setStoreTokens(false)
            .setAttributeComments(false)
            .setDoNotAssignCommentsPrecedingEmptyLines(true)
            .setIgnoreAnnotationsWhenAttributingComments(true)
            .setLexicalPreservationEnabled(true)
            .setPreprocessUnicodeEscapes(false)
            .setSymbolResolver(symbolSolver);
StaticJavaParser
            .setConfiguration(parserConfiguration);
```

Thanks in advance!

**Comment by MysterAitch** [comment]
I do see talk of people doing it, though the official position is that support for using JavaParser across multiple threads is explicitly not supported/encouraged.

_(i.e., if it works then that is great, but there are no promises/warranty/guarantees etc!)_

That said, we are open to making changes to improve on this and having discussions / recommendations.

**Comment by maartenc** [comment]
Since some recent changes, StaticJavaParser isn't suitable to use in a multithreaded environment this way.
You have to create your own JavaParser instance and reuse it accross your threads.

```
ParserConfiguration configuration = new ParserConfiguration();
...
JavaParser parser = new JavaParser(configuration); 
```
