### ISSUE TITLE
Code formatting changes after I add an annotation

### ISSUE THREAD

**Issue by theokyr** [javaparser/javaparser#318]
After adding a few annotations to a method and re-saving the file, the formatting (braces, newlines, comments) changes.

Here's an example.

before adding the annotation:

```
public void methodTest()
{
    System.out.println("Hello there!" + this.field1 + this.field2);
} //This is a comment
```

after adding the annotation and saving the file

```
@TestAnnotation
    public void methodTest() {
        System.out.println("Hello there!" + this.field1 + this.field2);
    }

    //This is a comment
```

**Comment by ftomassetti** [comment]
Well, this is intended. The AST does not preserve space and formatting.

**Comment by theokyr** [comment]
Is there any way to preserve it?

If not, is there a planned feature in the future to make formatting preservation happen?

**Comment by ftomassetti** [comment]
we add several discussions on this. Preserve spaces when printing back the very same AST is easy but it is not trivial to understand what happens when you refactor the AST. This is probably something that is not going to be changed soon _UNLESS_ someone is willing to contributes patches :)

**Comment by theokyr** [comment]
I see, thanks
