### ISSUE TITLE
In some scenarios, version 3.20.0 of type resolution differs greatly from version 3.15.13.

### ISSUE THREAD

**Issue by zhangziqiang1** [javaparser/javaparser#3181]
[JavaParserSample3.zip](https://github.com/javaparser/javaparser/files/6181800/JavaParserSample3.zip)

I provided HTML Schema test cases in Java Parser Sample 3. I tested them using 3.20.0 and 3.15.13, and the performance difference was dozens of times.

use 3.20.0 version 
```
208:setPrefix("html")
2785:elementType("<pcdata>", M_EMPTY, M_PCDATA, 0)
2586:elementType("<root>", M_ROOT, M_EMPTY, 0)
3823:elementType("a", M_PCDATA | M_NOLINK, M_INLINE, 0)
6159:elementType("abbr", M_PCDATA | M_INLINE, M_INLINE | M_NOLINK, F_RESTART)
81027:elementType("acronym", M_PCDATA | M_INLINE | M_INLINE | M_INLINE | 
```

use  3.15.13
```
188:setPrefix("html")
21:elementType("<pcdata>", M_EMPTY, M_PCDATA, 0)
9:elementType("<root>", M_ROOT, M_EMPTY, 0)
7:elementType("a", M_PCDATA | M_NOLINK, M_INLINE, 0)
11:elementType("abbr", M_PCDATA | M_INLINE, M_INLINE | M_NOLINK, F_RESTART)
8:elementType("acronym", M_PCDATA | M_INLINE | M_INLINE | M_INLINE | M_INLINE

```

**Comment by zhangziqiang1** [comment]
@Col-E Seems a little like [https://github.com/javaparser/javaparser/pull/3072](https://github.com/javaparser/javaparser/pull/3072)

**Comment by MysterAitch** [comment]
@zhangziqiang1 -- could you comment on whether you consider the behaviour before or after to be more correct? i.e., are you reporting a bug?

**Comment by Col-E** [comment]
> @Col-E Seems a little like https://github.com/javaparser/javaparser/pull/3072

It could be the case that a similar design pattern is being used elsewhere, I only noticed it in the place I did because I had a use case where it was very obvious to me. 

Edit: Oh I peeked at the sample source, I see what this issue is showing now. And yeah, I am almost 100% sure its an issue in the same vein as #3071 

I can investigate a fix later today. I'm hoping that the [secondary item](https://user-images.githubusercontent.com/21371686/108801001-957a5800-7562-11eb-9fc9-2e50dd93acee.png) I mentioned in the PR that I didn't get around to adding in can improve on this.

**Comment by zhangziqiang1** [comment]
This is not a mistake, this is a performance issue. @MysterAitch

**Comment by Col-E** [comment]
Just confirmed the secondary item does significantly cut down on the time to resolve nodes in the provided demo.

Before: ![image](https://user-images.githubusercontent.com/21371686/112087067-b20aaf80-8b63-11eb-9ad5-d1953f16605e.png)

After: ![image](https://user-images.githubusercontent.com/21371686/112087142-cf3f7e00-8b63-11eb-931c-f7014e1ef821.png)


I'll run a full test of the resolve core to ensure there are no backwards compatible changes.

Edit: Ran the test suite

![image](https://user-images.githubusercontent.com/21371686/112085943-c483e980-8b61-11eb-9353-7f560bf5f2d9.png)

No regressions in the test cases, opening a PR

**Comment by Col-E** [comment]
Opened a PR to address this #3185 

Edit: I apparently misjudged the layout o this code and its similarity to the #3072 case, but its still a relevant PR. Further below is a proper fix for this issue.

**Comment by zhangziqiang1** [comment]
[JavaParserSample4.zip](https://github.com/javaparser/javaparser/files/6187279/JavaParserSample4.zip)
@Col-E The performance of this case is limited by the number of lines of code in the same block, which does not seem reasonable.

**Comment by zhangziqiang1** [comment]
This should be a similar case.

**Comment by zhangziqiang1** [comment]
@Col-E For JavaParserSample3.zip, local validation shows no significant performance improvement.

**Comment by Col-E** [comment]
@zhangziqiang1 I'll take a look at these too

**Comment by zhangziqiang1** [comment]
I find that most of the time is spent on this, and I'm still working on the details. @Col-E [https://github.com/javaparser/javaparser/commit/0dc492a8653c197b8fc5b32c378993763c99e3a7](https://github.com/javaparser/javaparser/commit/0dc492a8653c197b8fc5b32c378993763c99e3a7)

**Comment by Col-E** [comment]
Ok so if we copy the resolve logic from `StatementContext` into `BlockStmtContext` it resolves the items from 0dc492a8653c197b8fc5b32c378993763c99e3a7 in a fraction of the time, again it scales with the type of input. A long flat scope like the attached case will trigger it moreso than some average code.

Before: 
![image](https://user-images.githubusercontent.com/21371686/112189989-f4230800-8bda-11eb-8f4d-f60bb997dfdb.png)

After: 
![image](https://user-images.githubusercontent.com/21371686/112190016-fbe2ac80-8bda-11eb-8cd8-2b1640ad7ed7.png)

**Comment by Col-E** [comment]
I was going to put up a PR but it looks like @jlerbsc beat me to it with #3189 
His PR achieves similar performance.

#3185 still has improvements for similar situations but not this explicit one _(Edit, meant 3185, not 3182. I've not looked at 3182 but a quick look over it looks like it's 👍 too)_

**Comment by jlerbsc** [comment]
Sorry for this intrusion but @zhangziqiang1 pinged me on this topic and I didn't know you had it in charge.

**Comment by jlerbsc** [comment]
@zhangziqiang1 to avoid this type of situation it is preferable that there is only one person who works on a topic. I understand that you are in a hurry but it is frustrating for a person to work on a subject and not be able to complete it.

**Comment by Col-E** [comment]
> Sorry for this intrusion but @zhangziqiang1 pinged me on this topic and I didn't know you had it in charge.

All good 👍 

The only thing I'd add to the test cases here is some generation of arbitrary variable declarations to show the `O(n * n)` has been resolved. I included some of that in an updated 2477 test case and got the performance metrics I posted above. Your PR matches mine in terms of runtime speed on my modified test.

**Comment by zhangziqiang1** [comment]
Thank you both. I'm probably in a hurry. @jlerbsc @Col-E All good
