### ISSUE TITLE
Resolved methods in outer classes not inferred correcly

### ISSUE THREAD

**Issue by deadlocklogic** [javaparser/javaparser#3195]
Test case:
```java
@Test
void test() {
    ParserConfiguration config = new ParserConfiguration();
    config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
    StaticJavaParser.setConfiguration(config);
    String s =
            "import java.util.Arrays;\n" +
                    "class MyClass {\n" +
                    "    public void writeFile() {\n" +
                    "        Arrays.asList(\"\", \"\");\n" +
                    "    }\n" +
                    "}\n";
    CompilationUnit cu = StaticJavaParser.parse(s);
    MethodCallExpr metCallExpr = cu.findFirst(MethodCallExpr.class).get();
    ResolvedType resolvedType = metCallExpr.calculateResolvedType();
    assertEquals("java.util.List<java.lang.String>", resolvedType.describe());
}
```
Test fails:
```
Expected :java.util.List<java.lang.String>
Actual   :java.util.List<T>
```
This issue might be the reason for many other active issues.

**Comment by maartenc** [comment]
@deadlocklogic I think this is fixed by PR #3194 as well, could you try?

**Comment by deadlocklogic** [comment]
But this PR fails all tests, I don't think someone will touch it if at least it passes al the tests other than codecov maybe.

**Comment by maartenc** [comment]
Yes I know it fails, but it would be good to get an indication if we are looking at to right place in the code.
But never mind, I've tried it myself and your example works with the change in #3194 :-)
Now let's look why some other tests fail

**Comment by deadlocklogic** [comment]
As remember correctly, this snippet was offending in my case:
https://github.com/javaparser/javaparser/blob/491dcb9fadda45d3caa1633fa16fa6af70532a46/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java#L100-L115
The inference wasn't working correctly on the `MethodUsage`.
Not sure other parts have any effect on this matter.
Again if anyone could volunteer with a good documentation on the solver part, especially the javaparsermodel module, it would boost the issues/fixes drastically.

**Comment by maartenc** [comment]
Yes, it is in the method `resolveMethodTypeParameters` which doesn't handle varargs correctly I believe
