### ISSUE TITLE
Use it without Maven

### ISSUE THREAD

**Issue by mohanr** [javaparser/javaparser#320]
Can I just pull the code and use it directly ? Are there too many dependencies ?

**Comment by matozoid** [comment]
javaparser-core has zero dependencies. Just run Maven once to hava javacc generate some required code.

Why do you want to do this, by the way?

**Comment by mohanr** [comment]
I generate some code to transform Struts to Spring. So I wanted to make my
tool extensible. Didn't think Maven was needed to a standalone code
generator.

**Comment by matozoid** [comment]
Alright, good luck!
