### ISSUE TITLE
When visit ArrayCreationExpression initializer is missed in some cases.

### ISSUE THREAD

**Issue by svlassiev** [javaparser/javaparser#321]
In ModifierVisitorAdapter, GenericVisitorAdapter, VoidVisitorAdapter and DumpVisitor in case of non-null dimensions of ArrayCreationExpression node an initializer of the node is not visited.
This means in this valid code
String[] array = new String[]{"one", "two" , "three"};
visitors miss to visit nodes that represent literals "one", "two" and "three".

**Comment by matozoid** [comment]
Can you open a pull request?

**Comment by svlassiev** [comment]
Actually, bug is still open due to lack of new tests.
And I don't understand how I can reopen pull request if it's already merged.

**Comment by matozoid** [comment]
Oh, I get it now, this is the one I accidentally merged. Let's just close it then.
