### ISSUE TITLE
GetSourceRoots() does not return all source roots

### ISSUE THREAD

**Issue by dimizisis** [javaparser/javaparser#3218]
This happened only with apache's log4j (https://github.com/apache/log4j), I have never experienced this problem before. Here's the code I'm executing:

```java
ProjectRoot projectRoot = new SymbolSolverCollectionStrategy().collect(Paths.get(projectRootStr));
List<SourceRoot> sourceRoots = projectRoot.getSourceRoots();
```
Where projectRootStr is the absoulute path to log4j's directory (Example: C:/Users/user/Desktop/log4j-trunk). 

The size of list (sourceRoots) returned is 5, whereas the original size is much bigger. Am I missing something? 

Thank you for your time and help!

**Comment by MysterAitch** [comment]
Thanks for the report - we'll have a look!

Out of curiosity, what source roots are you expecting and what is actually returned? Or, which ones are missing?

Cheers

**Comment by dimizisis** [comment]
I'm getting:

1. SourceRoot at log4j-trunk
2. SourceRoot at log4j-trunk/contribs/Jamie Tsao
3. SourceRoot at log4j-trunk/contribs/CekiGulcu
4. SourceRoot at log4j-trunk/contribs/JimMoore
5. SourceRoot at log4j-trunk/contribs/ThomasFenner

I was expecting:

1. SourceRoot at log4j-trunk/src/main/javadoc
2. SourceRoot at log4j-trunk/src/performance/java
3. SourceRoot at log4j-trunk/src/main/java
4. SourceRoot at log4j-trunk/tests/src/java

From the source roots I'm currently getting (the 5 directories above), it only finds 17 classes, which are not so important for my task (or even for the project itself).

Thanks again!

**Comment by ThanoshanMV** [comment]
Hi @dimizisis, and @MysterAitch How did you resolve this issue?

**Comment by dimizisis** [comment]
Hi @ThanoshanMV,

Personally I didn't manage to resolve it, I believe it is still an open issue. I recently had the exact same problem with the [Apache Maven project](https://github.com/apache/maven), too.

**Comment by ThanoshanMV** [comment]
Thank you @dimizisis for the quick reply!

**Comment by jlerbsc** [comment]
There is a bug in the SymbolSolverCollectionStrategy class. Thank you for reporting this issue.
