### ISSUE TITLE
Can javaparser be encapsulated in IDEA as a plugin

### ISSUE THREAD

**Issue by xiexiangwei0928** [javaparser/javaparser#3228]
If I need a plugin that works like javaparser, do you have any suggestions?

**Comment by MysterAitch** [comment]
Which functionality do you want to use as part of a plugin?

**Comment by xiexiangwei0928** [comment]
> 您想将哪些功能用作插件的一部分？

For example, generating code, incrematically updating code, including changing references to code, javaparser we were going to use on the server side, and now we are going to do it through the IDEA plugin, which we think will have the same capabilities as javaparser

**Comment by MysterAitch** [comment]
The short answer is that it _can_ be done.

It's likely not sophisticated enough to meet your needs of transformation of code, but for browsing/inspecting/exporting the AST there is a plugin available which does the basics -- I added detection of the project's jdk, java level, and source roots recently, and I'll be adding symbol solving soon :+1:

https://plugins.jetbrains.com/plugin/14245-javaparser-ast-inspector

**Comment by xiexiangwei0928** [comment]
> 简短的答案是_可以_做到的。
> 
> 它可能不够完善，无法满足您对代码转换的需求，但是对于浏览/检查/导出AST，有一个可用的插件可以执行基本操作-我最近添加了对项目的jdk，java级别和源根的检测，我将很快添加符号求解 👍
> 
> https://plugins.jetbrains.com/plugin/14245-javaparser-ast-inspector

If what I want to do now is to find a plugin, the function of this plugin is the same as the refactor code in the idea editor. When I rename a method, the referenced place of this method will also be modified. Generally speaking, it can be found Do you have any good suggestions for a plugin for the reference relationship between codes?
