### ISSUE TITLE
final variable declarations not being visited in VariableDeclarationExpression visitor

### ISSUE THREAD

**Issue by rmd6502** [javaparser/javaparser#323]
```
public void foo() {
   Bar bar;
   final Baz baz;
}

```

The visitor gets invoked for bar but not baz

**Comment by matozoid** [comment]
I've set up a test here: https://github.com/matozoid/javaparser-issue-323 It prints both declarations, so that seems fine.

Please submit a PR for https://github.com/matozoid/javaparser-issue-323 that does reproduce the problem.

**Comment by matozoid** [comment]
Sadly no PR :(
