### ISSUE TITLE
JavaSymbolSolver can resolve MethodDeclaration find method param type is use generic?there is a exception

### ISSUE THREAD

**Issue by hfutyezi** [javaparser/javaparser#3232]
method :

```java
private GoodsFilterComponentRequest getGoodsFilterComponentRequest(DpInputContext<FapiParam> context)
```

my JavaSymbolSolver
```java
       TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(SRC_PATH));
        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();
        combinedSolver.add(reflectionTypeSolver);
        combinedSolver.add(javaParserTypeSolver);
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
```

exception:
```
Exception in thread "main" UnsolvedSymbolException{context='null', name='FapiParam', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:682)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.lambda$convertToUsage$8(JavaParserFacade.java:687)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
```

**Comment by hfutyezi** [comment]
i found 
`protected ApiRequestInfo<List<DpGoodsResultBo>> handle(GetOutletGoodsInfoComponentV2Event event, List<Object> requestParams) `

is this MethodDeclaration , `List<Object>` works ok,it will translate to List

but

`private GoodsFilterComponentRequest getGoodsFilterComponentRequest(DpInputContext<FapiParam> context)`

`DpInputContext<FapiParam>` throw an exception

**Comment by jlerbsc** [comment]
Hi @hfutyezi where is the type FapiParam defined? Is it in a library or in your source directory?

**Comment by hfutyezi** [comment]
> Hi @hfutyezi where is the type FapiParam defined? Is it in a library or in your source directory?

in my  source directory,like this 
`import com.aa.bb.FapiParam;`

**Comment by jlerbsc** [comment]
I'm not sure to understand your answer. This class or interface com.aa.bb.FapiParam is defined in your source code directory. Is it right? I'm not speaking about import declaration! Could you provide us a simple test case to reproduce this result?

**Comment by hfutyezi** [comment]
> I'm not sure to understand your answer. This class or interface com.aa.bb.FapiParam is defined in your source code directory. Is it right? I'm not speaking about import decladaration! Could you provide us a simple test case to reproduce this result?

[Uploading GetOutletGoodsInfoComponentV2EventHandler.txt…]()

**Comment by hfutyezi** [comment]
> I'm not sure to understand your answer. This class or interface com.aa.bb.FapiParam is defined in your source code directory. Is it right? I'm not speaking about import decladaration! Could you provide us a simple test case to reproduce this result?

hello,i has updated an java file,.FapiParam is defined in my project ,i just import it in my class

**Comment by hfutyezi** [comment]
[GetOutletGoodsInfoComponentV2EventHandler.txt](https://github.com/javaparser/javaparser/files/6323499/GetOutletGoodsInfoComponentV2EventHandler.txt)

**Comment by jlerbsc** [comment]
May be  a bug!  Can you provide us a simple test case to reproduce this result? Thank you

**Comment by hfutyezi** [comment]
[java_callgraph.zip](https://github.com/javaparser/javaparser/files/6324073/java_callgraph.zip)
this is a simple maven project ,test entrance is TestBug，and you will be reproduce

**Comment by hfutyezi** [comment]
> [java_callgraph.zip](https://github.com/javaparser/javaparser/files/6324073/java_callgraph.zip)
> this is a simple maven project ,test entrance is TestBug，and you will be reproduce

**Comment by hfutyezi** [comment]
> [java_callgraph.zip](https://github.com/javaparser/javaparser/files/6324073/java_callgraph.zip)
> this is a simple maven project ,test entrance is TestBug，and you will be reproduce

maybe you need to modify FILE_PATH and SRC_PATH

**Comment by jlerbsc** [comment]
Can you try to setup SRC_PATH to your <project dir>/src/java/main directory please?

**Comment by hfutyezi** [comment]
> Can you try to setup SRC_PATH to your /src/java/main directory please?

[java_callgraph.zip](https://github.com/javaparser/javaparser/files/6324201/java_callgraph.zip)

**Comment by hfutyezi** [comment]
> Can you try to setup SRC_PATH to your /src/java/main directory please?

[java_callgraph.zip](https://github.com/javaparser/javaparser/files/6324359/java_callgraph.zip)
now you can run TestBug directly

**Comment by jlerbsc** [comment]
You don't understand what i say :-). You have to setup JavaParserTypeSolver with the root source path.

    String SRC_PATH = new File("").getCanonicalPath()+"\\src\\main\\java"

**Comment by hfutyezi** [comment]
> You don't understand what i say :-). You have to setup JavaParserTypeSolver with the root source path.
> 
> ```
> String SRC_PATH = new File("").getCanonicalPath()+"\\src\\main\\java"
> ```

you are right,but if my project has multi src folder , how to set it ?

**Comment by jlerbsc** [comment]
You can have multiple JavaParserTypeSolver defined one for each root source path or probably you can use SourceRoot class to help you.

**Comment by MysterAitch** [comment]
> you are right,but if my project has multi src folder , how to set it ?

This post may help:

https://javaparser.org/setting-up-for-analysing-a-whole-project/

**Comment by jlerbsc** [comment]
Hi @hfutyezi what is the status of this issue? Can we close it?
