### ISSUE TITLE
Finding body of a method called

### ISSUE THREAD

**Issue by abolfazl-sh** [javaparser/javaparser#3234]
Hi. I want to find the body of the method was called.

```
public class backup {

	private void f(){
		g(20);
	}
	
	private int g(double x){
		
		int y = x + 20;
		
		if(x > 10){
			
			return y / 10;
			
		}else if(x < 10){
				return y * 10;
			
		}
		
	}
	
		private int g(int x){
		
		int y = x + 20;
		
		if(x > 10){
			
			return y / 10;
			
		}else if(x < 10){
				return y * 10;
			
		}
		
	}
}
```

for example in above code, I want the get the third method. I try to match the name, number of parameters and type of parameters. but the problem is about `getTypeArguments()`, because it always return Optional.Empty.

and the method to check them match is as below : 

```
   public static boolean areSame(MethodDeclaration md, MethodCallExpr mce) {
    
        if (!md.getName().equals(mce.getName())) {
            return false;
        }

        if (md.getParameters().size() != (mce.getArguments().size())) {
            return false;
        }

        for (int i = 0; i < md.getParameters().size(); i++) {
            if(!(md.getParameter(i).getType().equals(mce.getTypeArguments().get().get(i)))){
                return false;
            }
        }

        return true;
    }
```
(as I said `mce.getTypeArguments()` returns Optional.Empty so `mce.getTypeArguments().get()` caused throw "Exception in thread "main" java.util.NoSuchElementException: No value present").

**Comment by jlerbsc** [comment]
Why don't you use getArguments?

    md.getParameter(i).getType().equals(mce.getArguments().get(i).getType())

**Comment by jlerbsc** [comment]
Why don't you use getArguments?

    md.getParameter(i).getType().equals(mce.getArguments().get(i).getType())

But you can also simply your method

    public static boolean areSame(MethodDeclaration md, MethodCallExpr mce) {
      ResolvedMethodDeclaration rmd = mce.resolve();
      return md.equals(rmd.toAst().get());
    }

**Comment by abolfazl-sh** [comment]
about the first part :
the `mce.getArguments().get(i)` return an Expression and there isn't any getType() method for it.
about the second part:
I use your code  and " Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration" was throw. I have no idea how can I configure it.
` CompilationUnit  cu = StaticJavaParser.parse(new File(FILE_PATH));` 
(I think about line should change does it right?)

**Comment by jlerbsc** [comment]
Yes you are right. You have to resolve the type of each argument.

Below an exemple to setup the symbol solver

        TypeSolver typeSolver = new ReflectionTypeSolver();
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(config);

You have many examples in the project javaparser-symbol-solver-testing or in the doc https://www.livingtech.com.cn/media/javaparservisited.pdf

**Comment by abolfazl-sh** [comment]
thanks. it works like a charm.
and sorry didn't check the doc.
