### ISSUE TITLE
OrphanComment in BlockStmt not appearing

### ISSUE THREAD

**Issue by yoshivda** [javaparser/javaparser#3244]
In an earlier version (3.6) the following code: 

```java
BlockStmt block = new BlockStmt();
block.addOrphanComment(new LineComment("TODO"));
System.out.println(block);
```

produced
```
{
// TODO
}
```

In the most recent version however, the comment does not appear at all, the result is an empty block. Did something change in the implementation and should this be done in another way, or is this a regression?

**Comment by jlerbsc** [comment]
It's seems that it's because there is no parent to your BlockStmt. I think it worked the same way in 2018 (on version 3.6). Add a parent node and the orphan comment will be printed.

**Comment by yoshivda** [comment]
@jlerbsc The code I have didn't change. You can find the full code [here](https://gitlab.ewi.tudelft.nl/weblab/generator-java/-/blob/master/src/main/java/nl/tudelft/weblab_generator/Generator.java#L265), it replaces the body of a method with `// TODO` if the method is annotated with `@Empty`. The exact same code produces an empty block after upgrading to the latest version

**Comment by jlerbsc** [comment]
Hi @yoshivda thank you for reporting this regression.

**Comment by matozoid** [comment]
The following shows that the problem is with comments without a range. Only the second case shows no TODO. The third is a workaround, just set a range of whatever.

````java
    public static void main(String[] args) {
        Statement parse = StaticJavaParser.parseStatement("{//TODO\n}");
        System.out.println(parse);

        BlockStmt blockStmt = new BlockStmt();
        blockStmt.addOrphanComment(new LineComment("TODO"));
        System.out.println(blockStmt);

        BlockStmt blockStmt2 = new BlockStmt();
        LineComment todo = new LineComment("TODO");
        todo.setRange(Range.range(Position.pos(100,100), Position.pos(100,100)));
        blockStmt2.addOrphanComment(todo);
        System.out.println(blockStmt2);
    }
```

**Comment by yoshivda** [comment]
@matozoid Adding a range indeed works around this issue, I will use this for now, thanks!
