### ISSUE TITLE
Can it parse JavaDoc? 

### ISSUE THREAD

**Issue by ipolevoy** [javaparser/javaparser#325]
I wonder if it is possible to get a representation of JavaDoc from classes and methods, i.e.:

``` java

/**
* Foo does foo. 
*
*  <p> hello world</p>
*
*/
public  class Foo extends Bar{

   /**
   *  This method blah, blah
   *  @param foo - this is a foo
   *  @return initialized Bar
   */
   public Bar getBar(Foo foo) { ... }
}

```

Specifically, is there a way to parse the Java sources and get JavaDoc in object form, including method names, parameters and return values. 

The goal of this is to write a generator of documentation for web services.

**Comment by ftomassetti** [comment]
Currently JavaParser:
- recognize comments
- associate comments to elements
- distinguish between normal comments and JavaDoc comments

However it does not parse the content of JavaDoc comments. You could use JavaParser to get the AST + the JavaDoc comments associated to the different elements and then parse yourself the content.
If you would also send a PR with that contribution it would be absolutely great.

**Comment by rpau** [comment]
Hi Igor,

This is a feature I implemented in a very old fork of javaparser (https://github.com/rpau/javalang) for the walkmod project. It is a project with LGPL license, and probably your transformation can be shared as a walkmod plugin. However, our version you do not know the comments (excluding Javadoc) associated to an specific element. 

If you are interested in collaborate with Javaparser to include this particular feature, we can talk about :)

**Comment by ipolevoy** [comment]
thanks, guys. I will explore.

**Comment by ipolevoy** [comment]
Just to give you more context. I was thinking of adding web services support for self-documenting, where JavaDoc can be dynamically converted to a simple webapp for developers to see service end points documentation, and potentially directly invoke methods. I'm a main contributor to http://javalite.io. If you have better ideas for implementation than parsing JavaDoc, that would also be great. 
Example  of an API app: https://github.com/javalite/activeweb-rest

**Comment by ftomassetti** [comment]
I think this is a very interesting topic and I would be very interested in hearing more about this project.

For self-documentation I guess there are different strategies possible, but the simplest one is extracting JavaDoc. It should be reasonably easy to do.

**Comment by ftomassetti** [comment]
And of course if @rpau can contribute her code adapting the license it would be great!

**Comment by ipolevoy** [comment]
@ftomassetti do you think you can provide a Hello World to pull the JavaDoc? This would save me some time:)

**Comment by ftomassetti** [comment]
That would not save time to me :)
Extracting the JavaDoc text is as easy as traversing the tree, calling getComment() and verifying the comment is a JavaDoc comment and not a common comment.
Then you can parse the content either using a grammar or regular expressions, given JavaDoc is so limited

**Comment by matozoid** [comment]
It would make a neat example for our documentation...

**Comment by ftomassetti** [comment]
Good point! Let me see if I can write something in the form of an example for a post and our documentation

**Comment by ftomassetti** [comment]
@ipolevoy you may want to take a look at https://github.com/ftomassetti/javadoc-extractor

``` java
public class JavadocExtractor {

    public static void main(String[] args) {
        File projectDir = new File("source_to_parse/");
        new DirExplorer((level, path, file) -> path.endsWith(".java"), (level, path, file) -> {
            try {
                new VoidVisitorAdapter<Object>() {
                    @Override
                    public void visit(ClassOrInterfaceDeclaration n, Object arg) {
                        super.visit(n, arg);
                        if (n.getComment() != null && n.getComment() instanceof JavadocComment) {
                            String title = String.format("%s (%s)", n.getName(), path);
                            System.out.println(title);
                            System.out.println(Strings.repeat("=", title.length()));
                            System.out.println(n.getComment());
                        }
                    }
                }.visit(JavaParser.parse(file), null);
            } catch (ParseException | IOException e) {
                new RuntimeException(e);
            }
        }).explore(projectDir);
    }
```

Given a directory this produce something like:

```
ASTParserConstants (/javaparser/javaparser-core/target/generated-sources/javacc/com/github/javaparser/ASTParserConstants.java)
==============================================================================================================================
/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */

ParseException (/javaparser/javaparser-core/target/generated-sources/javacc/com/github/javaparser/ParseException.java)
======================================================================================================================
/**
 * This exception is thrown when parse errors are encountered.
 * You can explicitly create objects of this exception type by
 * calling the method generateParseException in the generated
 * parser.
 *
 * You can modify this class to customize your error reporting
 * mechanisms so long as you retain the public fields.
 */

ASTParser (/javaparser/javaparser-core/target/generated-sources/javacc/com/github/javaparser/ASTParser.java)
============================================================================================================
/**
 * <p>This class was generated automatically by javacc, do not edit.</p>
 */

ASTParserTokenManager (/javaparser/javaparser-core/target/generated-sources/javacc/com/github/javaparser/ASTParserTokenManager.java)
====================================================================================================================================
/** Token Manager. */
```

I am just printing the Javadoc comments associated to classes, I am not parsing the Javadoc comments yet

**Comment by ipolevoy** [comment]
@ftomassetti this is interesting, thanks for the tip - I will explore further!

**Comment by matozoid** [comment]
Javadoc parsing support will be in the next release, thanks to @ftomassetti .

**Comment by Trasd** [comment]
Has there been progress with this addition?  Has Javadoc parsing been fully integrated?

I'm not currently working on a project that needs this capability (so I haven't dug too deep), but kicking around an idea for the future.

Thanks.

**Comment by matozoid** [comment]
@Trasd the issue is closed and marked solved in 3.0.1. The pull request for it that I just linked (#699) has some info.

**Comment by Trasd** [comment]
@matozoid Yes, thank you.  Sorry to clutter it up.  I noticed it was closed **after** I posted.

As I said, I'm not ready yet, but I got interested and have uncovered a lot since my post.

Nice work guys!

**Comment by matozoid** [comment]
Thanks! Feel free to clutter stuff up a bit :-)

**Comment by IrfanKhanKakar** [comment]
Hi, i have a File which contain Java projects,
know i want parser this file and generate UML Class diagram.

but when i write : CompilationUnit compilationUnit = JavaParser.parse(file);

its give me an Error, due to CompilationUnit not import in java package,

i try a lot to load http://javaparser.org library in my eclipse, but its not working.

kindly anyone help me........................
