### ISSUE TITLE
Failed to generate the AST.

### ISSUE THREAD

**Issue by zhangziqiang1** [javaparser/javaparser#3255]
When I was using version 3.22.0, I found that this case failed to generate AST.

```java
        CompilationUnit compilationUnit = StaticJavaParser.parse("class Test {\n" +
                "    private void bad() {\n" +
                "        String record = \"\";\n" +
                "        record.getBytes();\n" +
                "    }\n" +
                "}");

        System.out.println(compilationUnit);
```

The local variable of record exists in my code. In this case, the AST generation fails. I want to generate the AST successfully. What do I need to do in the new version?

**Comment by MysterAitch** [comment]
This seems to be related to the use of `record` as an identifier, following #3022 (support for parsing Java Records). 

The default Java level is Java 8 so should not be happening - I will need to investigate further.

As an immediate fix, changing the identifier name to something else (e.g. `record2` or `recordString`) will allow you to produce the AST.

**Comment by MysterAitch** [comment]
Should be fixed in the next release :+1:

**Comment by zhangziqiang1** [comment]
Thanks for your quick response, and I'm trying to verify if there's a similar situation.

**Comment by ctubbsii** [comment]
> Should be fixed in the next release

Which release version will that be? And, when can it be expected to be released?

**Comment by MysterAitch** [comment]
> > Should be fixed in the next release
> 
> Which release version will that be? And, when can it be expected to be released?

Just pushed out the release (v3.22.1), which should be available to download in the next few hours or whenever the relevant caches etc get flushed at sonatype/maven central :+1:
