### ISSUE TITLE
EOL problem on Windows

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#326]
Scenario "Dumping orphan comments in empty method" fails when compiling on Windows because of a \n \r\n mismatch.

**Comment by ftomassetti** [comment]
In the long run we want to configure AppVeyor to prevent Windows specific errors in the future

**Comment by matozoid** [comment]
Want to open an issue for that?

I've found the bug and will commit the patch tonight.

**Comment by ftomassetti** [comment]
Issue opened as #329
