### ISSUE TITLE
Parser fails on nested record within annotation interface and record class

### ISSUE THREAD

**Issue by handmadecode** [javaparser/javaparser#3260]
Using javaparser-core 3.22.0 and  `ParserConfiguration.LanguageLevel.JAVA_16`, the following code fails to parse:

```
@interface X {
    record Y(int z) {
    }
}
```
with the error _com.github.javaparser.ParseProblemException: (line 2,col 13) Parse error. Found "int", expected ")"_

Similarly, the following code fails to parse:

```
record X(int n) {
    record Y(int z) {
    }
}
```
with the error _com.github.javaparser.ParseProblemException: (line 2,col 5) 'record' cannot be used as an identifier as it is a keyword_

Both snippets work in JDK 16's jshell, and according to JLS 9.6.1 and 8.10.2 nested records should be allowed within annotation interfaces and record classes.

Parsing a nested record within a normal class, a normal interface, or an enum class succeeds.

**Comment by handmadecode** [comment]
The following two test cases can be added to `com.github.javaparser.ast.body.RecordDeclarationTest` to show the failures:

```
    @Test
    void record_allowNestedWithinAnnotation() {
        String s = "\n" +
            "@interface X {\n" +
            "    record Point(int x, int y) {\n" +
            "    }\n" +
            "}\n";

        CompilationUnit cu = TestParser.parseCompilationUnit(s);
        assertOneRecordDeclaration(cu);
    }
```

and

```
    @Test
    void record_allowNestedWithinRecord() {
        String s = "\n" +
            "record X(int z) {\n" +
            "    record Point(int x, int y) {\n" +
            "    }\n" +
            "}\n";

        CompilationUnit cu = TestParser.parseCompilationUnit(s);
        List<RecordDeclaration> recordDeclarations = cu.findAll(RecordDeclaration.class);
        assertEquals(2, recordDeclarations.size());
    }
```

**Comment by handmadecode** [comment]
I had a look at the grammar file` java.jj`, and the following two modifications seem to fix the issue:

line 1753ff:
```

BodyDeclaration<?> RecordBodyDeclaration():
{
    ModifierHolder modifiers;
    BodyDeclaration<?> ret;
}
{
    (
        LOOKAHEAD(2)
        ret = InitializerDeclaration()
     |
        // Just get all the modifiers out of the way. If you want to do
        // more checks, pass the modifiers down to the member
        modifiers = Modifiers()
        (
            ret = ClassOrInterfaceDeclaration(modifiers)
         |
            LOOKAHEAD("enum")
            ret = EnumDeclaration(modifiers)
         |
            LOOKAHEAD("@" "interface")
            ret = AnnotationTypeDeclaration(modifiers)
/** Begin added code **/
         |
            LOOKAHEAD("record")
            ret = RecordDeclaration(modifiers)
/** End added code **/
         |
...
```
and line 5454ff
```
BodyDeclaration<?> AnnotationBodyDeclaration():
{
    ModifierHolder modifier;
    BodyDeclaration ret;
}
{
    modifier = Modifiers()
    (
/** Begin added code **/
        LOOKAHEAD("record")
        ret = RecordDeclaration(modifier)
     |
/** End added code **/
        LOOKAHEAD(Type() Identifier() "(")
        ret = AnnotationTypeMemberDeclaration(modifier)
     |

```

The first fix seems straight-forward, but I have some doubts about the second fix; the matching clause for record declaration must come before the one for annotation type member. I assume this is because the `record` restricted identifier is matched as an identifier in that clause. Maybe there is a better fix for records nested within annotation interfaces?

Should you think the test cases and code changes are appropriate, I'd be happy to put together a pull request.

**Comment by jlerbsc** [comment]
Hi @MysterAitch, what do you think of this proposal?

**Comment by jlerbsc** [comment]
This is no longer an issue in the current version of JP.

**Comment by handmadecode** [comment]
I can confirm that my tests now pass. Thanks for fixing this
