### ISSUE TITLE
Test resources containing included interfaces do not compile

### ISSUE THREAD

**Issue by si-e** [javaparser/javaparser#3269]
In `javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/ImplementedOrExtendedTypeResolutionTest.java`, there is a native test case that tests the case for nested interfaces, as follows

```java
assertEquals(clazz.getFieldByName("field_i2").get().resolve().getType().describe(), "I2.I2_1");
assertEquals(clazz.getFieldByName("field_i3").get().resolve().getType().describe(), "I3.I3_1.I3_1_1");
```

The sample code it tests is as follows

```java
interface I1 {
}

interface I2 {
    interface I2_1 {
    }
}

interface I3 {
    interface I3_1 {
        interface I3_1_1 {
        }
    }
}

...

class InterfaceTest implements I2.I2_1, I3.I3_1.I3_1_1 {
    I1 field_i1;
    I2_1 field_i2;
    I3_1_1 field_i3;
}

...
```

But I think there's a problem with this sample code, because I can't even compile this code successfully

```
>javac ImplementedOrExtendedTypeResolution.java
ImplementedOrExtendedTypeResolution.java:33: 错误: 找不到符号
    I2_1 field_i2;
    ^
  符号:   类 I2_1
  位置: 类 InterfaceTest
ImplementedOrExtendedTypeResolution.java:34: 错误: 找不到符号
    I3_1_1 field_i3;
    ^
  符号:   类 I3_1_1
  位置: 类 InterfaceTest

...
```

So I think the assert in the test cases is also incorrect.

This problem was found when I was fixing #3214. If the above problem is not solved, this Issue cannot be fixed.

Here is my Java version, I don't know if this is relevant.

```
>java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```

**Comment by jlerbsc** [comment]
This is correct. Example code doesn't compile. Properties must be prefixed with the name of the class / interface. Personally I dont really understand the goal of this test.
