### ISSUE TITLE
Trailing comments moved to beginning of method when modifying a method body

### ISSUE THREAD

**Issue by bishboria** [javaparser/javaparser#3271]
When testing out a toy example to add a print statement as the first line in any methods found, I noticed that if a method has trailing comments then they are moved to the top of the method after processing the original file AND THEN the print statement is added. The code below reads and modifies itself, but the same thing happens when not self modifying.

I'm using JavaParser Core 3.22.1.

```java
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.StringLiteralExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class SimpleJPmodTest {

    public static void main(String[] args) throws Exception {
        FileInputStream in = new FileInputStream("src/SimpleJPmodTest.java");
        CompilationUnit cu;
        try {
            cu = StaticJavaParser.parse(in);
        } finally {
            in.close();
        }
        new MethodModVisitor().visit(cu, null);
        byte[] modfile = cu.toString().getBytes();
        Path file = Paths.get("src/SimpleJPmodTest.java");
        Files.write(file, modfile);
    }

    private static class MethodModVisitor extends VoidVisitorAdapter {

        @Override
        public void visit(MethodDeclaration n, Object arg) {
            MethodCallExpr call = new MethodCallExpr(new NameExpr("System.out"), "println");
            call.addArgument(new StringLiteralExpr(n.getNameAsString()));
            n.getBody().get().addStatement(0, call);
            // trailing comment
        }
    }
}
```

becomes

```java
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.StringLiteralExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class SimpleJPmodTest {

    public static void main(String[] args) throws Exception {
        System.out.println("main");
        FileInputStream in = new FileInputStream("src/SimpleJPmodTest.java");
        CompilationUnit cu;
        try {
            cu = StaticJavaParser.parse(in);
        } finally {
            in.close();
        }
        new MethodModVisitor().visit(cu, null);
        byte[] modfile = cu.toString().getBytes();
        Path file = Paths.get("src/SimpleJPmodTest.java");
        Files.write(file, modfile);
    }

    private static class MethodModVisitor extends VoidVisitorAdapter {

        @Override
        public void visit(MethodDeclaration n, Object arg) {
            // trailing comment
            System.out.println("visit");
            MethodCallExpr call = new MethodCallExpr(new NameExpr("System.out"), "println");
            call.addArgument(new StringLiteralExpr(n.getNameAsString()));
            n.getBody().get().addStatement(0, call);
        }
    }
}
```

You can see that the print statement in the main method is in the correct place, but in the visit method what was the trailing comment has now become the first line and the print statement is second. If you then run the program again on itself, now it has no trailing comments, the print statement is correctly at the top of each method.

If the method has multiple trailing comments they are all moved to the top of the method.

**Comment by jlerbsc** [comment]
Hi @bishboria JP 3.15.11 is over a year old can you check with the latest version please.

**Comment by bishboria** [comment]
Hi @jlerbsc, I can confirm that it happens in the latest version as well. I've updated my original issue to say the new version rather than the old version. Thanks.

**Comment by jlerbsc** [comment]
I think it's the strategy to print orphan comment in JP but i will check this.

**Comment by bishboria** [comment]
@jlerbsc Any further forward on this bug?

**Comment by jlerbsc** [comment]
Hi @bishboria this is not a bug, this is how orphan comments are handled.

**Comment by bishboria** [comment]
I'm confused, why it would move comments around? Is there a document/changelog/place where this is described?

**Comment by MysterAitch** [comment]
Hi @bishboria 

This blog post describes how comments get parsed: https://tomassetti.me/java-comments-parsing/

It contains this quote: 
> Not all the comments can be associated to one element: the remaining comments are considered orphan comments. 
> They will be inserted in the list of orphan comments of the first node which contains them.

Hope this helps to clarify how/why this happens.

**Comment by jlerbsc** [comment]
Using LexicalPreservingPrinter displays the code without changing the format.
