### ISSUE TITLE
I want to extract every method from a Java File

### ISSUE THREAD

**Issue by mosh98** [javaparser/javaparser#3281]
Hi,
I was trying to extract every single java method separately from any java file and store each method in a text file for example.

However it seems that the API doesn't really allow me to do that except for querying the import, comments and other. 

Could you help me out by suggesting a solution or any other parser that could help me achieve that.

Any tips would be much appreciated!

**Comment by jlerbsc** [comment]
Hi @mosh98 i don't really understand what you are trying to do but it seems to be simple to do with JavaParser. Have you try to read more informations from https://javaparser.org/getting-started.html ?

**Comment by mosh98** [comment]
Hi,
I am sorry i couldn't explain myself. 

Here is the example i am working with, I have a java file containing 5 methods including constructors and other methods. Hence i want to make 5 text file where each method from that specific java file has. So, 1 java file generates 5 textfiles. 

The task that i want to achieve is to extract every method from that java file.

So my question is: Is there any API in javaparser that allows me to do it?

I have read the docs but i may have missed something. 

Again thanks being in contact :D

**Comment by jlerbsc** [comment]
You can do it simply using a visitor. Have you read the book https://leanpub.com/javaparservisited  that gives a lot of informations to begin with JP? From page 12 you have some examples to do what you want.

**Comment by mosh98** [comment]
Yes that might actually work. 
Huge Thanks!

**Comment by mosh98** [comment]
I tried the solution, just want to let you know that it worked! 
Many Thanks and have a wonderful summer :D 

<img width="640" alt="Skärmavbild 2021-05-29 kl  13 10 01" src="https://user-images.githubusercontent.com/48658042/120068087-33f4e880-c07f-11eb-829b-ab8bbed7c1e6.png">

**Comment by jlerbsc** [comment]
Thanks for your feedback and use JP as much as possible
