### ISSUE TITLE
Changing the name of a ClassOrInterfaceType doesn't work with LexicalPreservation activated

### ISSUE THREAD

**Issue by benoitdupont** [javaparser/javaparser#3284]
Hello, I'm trying to automate the migration of classes by replacing their occurrence with the new name, here for instance `org.springframework.hateoas.ResourceSupport` should become `... .RepresentationModel` in the following class to update:

```
public ResponseEntity<ResourceSupport> getIndex() {
	ResourceSupport indexResource = null;
	return ok().body(indexResource);
}
```

Here's the test case to reproduce:

```		
ParserConfiguration parserConfiguration = new ParserConfiguration();
parserConfiguration.setLexicalPreservationEnabled(true);

SourceRoot sourceRoot = new SourceRoot(CodeGenerationUtils.mavenModuleRoot(getClass()).resolve("src/test/resources"), parserConfiguration);

CompilationUnit cu = sourceRoot.parse("", "IndexController.java");

// The following line doesn't seems to change anything
//		LexicalPreservingPrinter.setup(cu);

cu.accept(new ModifierVisitor<Void>() {
	@Override
	public Visitable visit(ClassOrInterfaceType classOrInterfaceType, Void arg) {
		if ("ResourceSupport".equals(classOrInterfaceType.getNameAsString())) {
			classOrInterfaceType.setName("RepresentationModel");
			Log.info("I substituted something !");
		}

		return super.visit(classOrInterfaceType, arg);
	}
}, null);

// Try with the regular printer, will succeed
assertStringHasBeenAdapted(sourceRoot.getPrinter().apply(cu));

// Try with the lexical one, will fails
sourceRoot.setPrinter(LexicalPreservingPrinter::print);
assertStringHasBeenAdapted(sourceRoot.getPrinter().apply(cu));

...

static void assertStringHasBeenAdapted(String outputFile) {
     if (outputFile.contains("ResponseEntity<ResourceSupport>") || outputFile.contains("ResourceSupport indexResource")) {
	throw new IllegalStateException("ResourceSupport was not replaced by RepresentationModel !!: ");
    }
}
```

The sourceRoot seems properly adapted by the `classOrInterfaceType.setName` with the default printer, but when I change it to LexicalPreservingPrinter, it's still the old value `ResourceSupport` which is printed.

This also may not be a bug and I'm adapting the value incorrectly with `classOrInterfaceType.setName`.

I added the [testcase here on github](https://github.com/benoitdupont/javaparser-lexicalissue) to ease the reproduction, dunno if it's a good idea.

Also I'm not sure about the utility of the following line (saw that in one of the issue)  `LexicalPreservingPrinter.setup(cu);`

Can someone help me ? Thanks a lot !

**Comment by jlerbsc** [comment]
Hi @benoitdupont ,
Thank you for that very clear explanation and test cases that we can save some time.
If you want to use LexicalPreservingPrinter you have to setup it with CompilationUnit.

    LexicalPreservingPrinter.setup(cu);

I have modified your unit test

    @Test
    public void shouldReplace_ResourceSupport_with_RepresentationModel() {
        
        String input =
            "import static org.springframework.http.ResponseEntity.ok;\n" + 
            "import org.springframework.http.ResponseEntity;\n" + 
            "import org.springframework.hateoas.ResourceSupport;\n" + 
            "public class IndexController {\n" + 
            "    public ResponseEntity<ResourceSupport> getIndex() {\n" + 
            "        ResourceSupport indexResource = null;\n" + 
            "        return ok().body(indexResource);\n" + 
            "    }\n" + 
            "}";
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setLexicalPreservationEnabled(true);
        CompilationUnit cu = StaticJavaParser.parse(input);
        LexicalPreservingPrinter.setup(cu);
        cu.accept(new ModifierVisitor<Void>() {
            @Override
            public Visitable visit(ClassOrInterfaceType classOrInterfaceType, Void arg) {
                if ("ResourceSupport".equals(classOrInterfaceType.getNameAsString())) {
                    classOrInterfaceType.setName("RepresentationModel");
                }

                return super.visit(classOrInterfaceType, arg);
            }
        }, null);
        
        System.out.println(LexicalPreservingPrinter.print(cu));

    }

this test displays


    import static org.springframework.http.ResponseEntity.ok;
    import org.springframework.http.ResponseEntity;
    import org.springframework.hateoas.ResourceSupport;
    public class IndexController {
      public ResponseEntity<RepresentationModel> getIndex() {
          ResourceSupport indexResource = null;
          return ok().body(indexResource);
      }
    }

I think this is what you want to get.

**Comment by benoitdupont** [comment]
Hello Jean-Pierre, thank you for the reply.

I still see `ResourceSupport indexResource = null` in your test display, my example is confusing because there are two substitutions to make (one succeed, the other not). Let's simplify it to keep only the failing substitution (and include the `LexicalPreservingPrinter.setup(cu))`, in the [following test, also on Github](https://github.com/benoitdupont/javaparser-lexicalissue/blob/5bbdd8a30852672a0451084c60453659b4ae9794/src/test/java/ReplaceWithLexicalPreservation_The_Second_Test.java), which fails:

```
@Test
public void shouldReplace_ResourceSupport_with_RepresentationModel() {
	String input = "import org.springframework.hateoas.ResourceSupport;\n" +
					"public class IndexController {\n" +
					"             public void getIndex() {\n" +
					"        ResourceSupport indexResource = null;\n" +
					"    }\n" +
					"}";

	ParserConfiguration parserConfiguration = new ParserConfiguration();
	parserConfiguration.setLexicalPreservationEnabled(true);

	SourceRoot sourceRoot = new SourceRoot(CodeGenerationUtils.mavenModuleRoot(getClass()).resolve("src/test/resources"), parserConfiguration);

	CompilationUnit cu = StaticJavaParser.parse(input);
	LexicalPreservingPrinter.setup(cu);

	cu.accept(new ModifierVisitor<Void>() {
		@Override
		public Visitable visit(ClassOrInterfaceType classOrInterfaceType, Void arg) {
			if ("ResourceSupport".equals(classOrInterfaceType.getNameAsString())) {
				classOrInterfaceType.setName("RepresentationModel");
			}

			return super.visit(classOrInterfaceType, arg);
		}
	}, null);


	// Try with the lexical one, will fails
	sourceRoot.setPrinter(LexicalPreservingPrinter::print);

	String output = sourceRoot.getPrinter().apply(cu);
	System.out.println(output);
	if (output.contains("ResourceSupport")) {
		Assertions.fail("ResourceSupport was not replaced by RepresentationModel !!: ");
	}
}
```

**Comment by jlerbsc** [comment]
This is right in your case a workaround is to declare 

    @Override
            public Visitable visit(VariableDeclarator vd, Void arg) {
                if ("ResourceSupport".equals(vd.getType().asString())) {
                    vd.setType("RepresentationModel");
                }
                return super.visit(vd, arg);
            }

**Comment by benoitdupont** [comment]
Thanks a lot for the workaround and the fast responses !

**Comment by jlerbsc** [comment]
@benoitdupont Can you close this issue if you have no more questions?

**Comment by benoitdupont** [comment]
No more questions, it's closed now thanks
