### ISSUE TITLE
Adding "System.exit(1)" in try-catch block

### ISSUE THREAD

**Issue by IjazAhmed** [javaparser/javaparser#3286]
Hi, 
 
 I want to add "System.exit(1)" at the _start_ of catch block. I have a reference to the **CatchClause**, say in the variable **catchRef**.
 
 I tried the following code 
 catchRef.getBody().addStatement("System.exit(1)");
 
 but by somehow, it does not work for me.
 
 Kindly guide. Thank you.

**Comment by jlerbsc** [comment]
Hi @IjazAhmed i don't know what you mean by "it doesn't work for me" but maybe just try this

    catchRef.getBody().addStatement("System.exit(1);");

**Comment by IjazAhmed** [comment]
thank you for prompt reply. The semicolon ; solved the problem. Just one side question, this code add "System.exit(1);" at the end of catch block. I want to add it at the start of catch-body. Any advise in this regard.

**Comment by jlerbsc** [comment]
This is probably what you want to do.

    catchRef.getBody().getStatements().addFirst(parseStatement("System.exit(1);"));
