### ISSUE TITLE
Configure AppVeyor

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#329]
So that we can prevent Windows-only bugs to go unnoticed

**Comment by matozoid** [comment]
Clicky linky: https://www.appveyor.com/

**Comment by matozoid** [comment]
I see AppVeyor is already running. However, it is extremely slow. There seems to be a big queue for build jobs :(

**Comment by ftomassetti** [comment]
Unfortunately AppVeyor is very slow. Sometimes things just go stuck and you have to restart it.
It is not ideal. I would suggest normally look just to Travis and wait for AppVeyor when there is the suspicion that some change could be OS specific

**Comment by matozoid** [comment]
Let's leave it at that for now, then.
