### ISSUE TITLE
LexicalPreservation bug for array brackets

### ISSUE THREAD

**Issue by nimakarimipour** [javaparser/javaparser#3296]
Hello all, thank you for developing such a great tool. However, I found a bug when using `LexicalPreservation` tool when I try to add an annotation to a class field which has the type `array` and the brackets `[]` are behind the parameter's name as shown in the example below.

```java
class Test{
   String[] allTest;
}
```
Please note that the example below works fine and the exception happens only when the brackets are behind field name. 

```java
class Test{
   String allTest[];
}
```

I also provided the code below that will generate the same exception mentioned above when executed:
```java
String code = "public class Test { String[] allTest; }";
CompilationUnit cu = LexicalPreservingPrinter.setup(StaticJavaParser.parse(code));
Optional<ClassOrInterfaceDeclaration> clazzOptional = cu.getClassByName("Test");
assertTrue(clazzOptional.isPresent());
ClassOrInterfaceDeclaration clazz = clazzOptional.get();
clazz.getMembers().forEach(
        bodyDeclaration ->
                bodyDeclaration.ifFieldDeclaration(
                        fieldDeclaration -> {
                            NodeList<VariableDeclarator> vars =
                                    fieldDeclaration.asFieldDeclaration().getVariables();
                            for (VariableDeclarator v : vars) {
                                if (v.getName().toString().equals("allTest")) {
                                    fieldDeclaration.addMarkerAnnotation("Nullable");
                                    break;
                                }
                            }
                        }));
String changed = LexicalPreservingPrinter.print(cu);
```

Here is the error I get when executing the code above:

```java
java.lang.UnsupportedOperationException: kept child(VariableDeclarator) vs "["   <101>   (line 1,col 27)-(line 1,col 27)

	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:513)
```

With best regards, 

Nima Karimipour

**Comment by nimakarimipour** [comment]
Just a quick note, I am not sure if it's the right way to resolve it but I was able to fix the issue with the fix below at `Difference.java` class:
```java
if (kept.isPrimitiveType()) {                    
   originalIndex++;                    
   diffIndex++;                
}else{                    
   originalIndex++;               
}
```
And here is the link to the [change](https://github.com/nimakarimipour/javaparser/blob/395d0ca398eccd5251288db7ec22ab3789956f63/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Difference.java#L512) I applied. All regression tests will still pass with this fix applied.

**Comment by jlerbsc** [comment]
Hi @nimakarimipour Thank you for reporting this bug. May be you can push a PR?

**Comment by nimakarimipour** [comment]
@jlerbsc Sure, Just did. I am waiting for the result of CI, once it is finished with no issue, I will notify you. Thank you.
