### ISSUE TITLE
JavaParserTypeSolver does not resolve all types correctly

### ISSUE THREAD

**Issue by Hannah421** [javaparser/javaparser#3298]
Hello,
I am working on a project where it is necessary to parse multiple .java files. The parsing seems fine, but if I try to resolve types from other java files the SymbolSolver can not figure out the types correctly. I broke that issue down to the following example:

We got ClassA 
![image](https://user-images.githubusercontent.com/63290959/122242849-ee7c4c00-cec3-11eb-903b-129a0a6ae5f4.png)

and ClassB
![image](https://user-images.githubusercontent.com/63290959/122242956-05bb3980-cec4-11eb-84e1-e4d50a098c19.png)

In the Main I build a CombinedTypeSolver and inject the JavaParserTypeSolver and ReflectionTypeSolver. The JavaParserTypeSolver gets the path to the directory that contains ClassA.java and ClassB.java.
Then I build a ParserConfiguration with the CombinedTypeSolver and set it in the StaticJavaParser.
Then I am parsing the ClassA.java file. If i try to resolve all MethodCallExpr, especially classB.bar() can not be resolved. But the ReflectionTypeSolver works fine.
![image](https://user-images.githubusercontent.com/63290959/122243191-37340500-cec4-11eb-9dde-c543755d7f37.png)

You can see this in the following output:
![image](https://user-images.githubusercontent.com/63290959/122243354-5468d380-cec4-11eb-92f7-f9f02b6d0552.png)

Did I screwed something up or is this intended?
And when it is my fault, how can i fix it? :D

**Comment by jlerbsc** [comment]
Hi @Hannah421 the 'root' variable must point to src/main/java directory.

**Comment by Hannah421** [comment]
Thank you for your fast response @jlerbsc 
That was quite simple :D

Can may you explain shortly why exactly this path is needed and neither the subfolder nor the src/main or src/ directory are working?

**Comment by jlerbsc** [comment]
This is just because JavaParserTypeSolver needs to work on the root source directory.
