### ISSUE TITLE
Make CuPrinter implement java.io.Closeable 

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#33]
This allows Java 7 to auto close the resource. This would mean moving to java 7.

(imported from google code comments)

**Comment by SmiddyPence** [comment]
Probably looking at putting that in a major release version.

i.e. v 2.0.0
With minimum Java 7 and support for Java 8 syntax.

P.S. Good work on the tidy up, was this the only relevant issue from google code? Pretty nice if that's all you're left with.

**Comment by matozoid** [comment]
A new milestone was added :)

As far as I can see, there were about three issues that were solved (double check if you like,) the rest were complaints about lacking documentation and many samples that, in my opinion, didn't add much.

**Comment by sebastiankirsch** [comment]
Hm, `java.io.Closeable` is around since 5, so we could implement it right away.

I'd assume that this enables auto-closing as well (even if javaparser is compiled with JDK < 7), but I don't know for sure. Any "Oracle Certified Associate, Java SE 7 Programmer" around to confirm this?

**Comment by SmiddyPence** [comment]
That sounds correct, having swatted up. Only SCJP for 1.4 here :wink: 

Personally I was getting Closable and AutoClosable confused, had assumed there was only 1 for using the try-with-resource; which was only available >= 7.

Incidentally this CuPrinter has been removed anyway, (likely me)! Looks like it was just a cheeky little main method to dump a class out as a String.
