### ISSUE TITLE
Wrong line numbers when parsed file starts with empty lines

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javaparser#330]
I'm running the Javaparser on Windows. When visiting a `PackageDeclaration` with the following code it seems like empty lines at the top of the parsed file are ignored.

```
public class JavaAstVisitor extends VoidVisitorAdapter<Void> {
    public void visit(final PackageDeclaration n, final Void v) {
        NameExpr nameExpr = n.getName();
        int nameBeginLine = nameExpr.getBeginLine();
        ...
        super.visit(n, v);
    }
    ...
}
```

**Comment by matozoid** [comment]
I tried to reproduce it here: https://github.com/matozoid/javaparser-issue-330

When I put empty lines on top of "Bla.java", nameBeginLine gets incremented, so either I can't reproduce it, or I don't understand the problem.

**Comment by mlangkabel** [comment]
Thank you for looking into this. I just checked out the repo and tested your code on my machine. It seems to be working as expected. I'm sorry for having bothered you with that.

**Comment by matozoid** [comment]
No problem, thanks for reporting!
