### ISSUE TITLE
A more intelligent `ModifierVisitorAdapter`?

### ISSUE THREAD

**Issue by thejohnfreeman** [javaparser/javaparser#331]
The manual includes [a lengthy example on how to remove "dead" context nodes surrounding a removed node](https://github.com/javaparser/javaparser/wiki/Manual#remove--delete-node-from-ast). This isn't an isolated case. There are many nodes that have required children: if the child is removed, the parent should be removed as well. Should we have that behavior by default?
- [ ] `ExpressionStmt`: should be removed if the expression is removed
- [ ] `VariableDeclarationExpr`: should be removed if all children are removed
- [ ] `VariableDeclarator`: should be removed if the id is removed

Going out on a limb, I can think of others:
- [ ] `IfStmt`: should be removed if the "then" clause is removed
- [ ] `DoStmt`: should collapse to a `WhileStmt` if the body is removed
- [ ] `AssignExpr`: should be removed if either side is removed
- [ ] `BinaryExpr`: should collapse to the other side if either side is removed, or be removed if both sides are removed
- [ ] `FieldAccessExpr`: should be removed if the scope is removed
- [ ] `CastExpr`: should collapse to the expression if the type is removed

What do we think? I'll work on a PR unless I hear some objections.

**Comment by matozoid** [comment]
Interesting! At what moment would you do the removing?

**Comment by thejohnfreeman** [comment]
For example, [here](https://github.com/javaparser/javaparser/blob/713bd688de2456219a20ccb0ce649f11c387080b/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/ModifierVisitorAdapter.java#L509), where `ExpressionStmt` sets its child expression. Change it to this:

``` java
 @Override public Node visit(final ExpressionStmt n, final A arg) {
    final Expression child = (Expression) n.getExpression().accept(this, arg);
    if (child == null) {
      return null;
    }
    n.setExpression(child);
    return n;
}
```

Similar for all the others. I'll try to work on a patch this evening or tomorrow.
