### ISSUE TITLE
Comment in the middle of a multi-line single statement

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3317]
JavaParser 3.22.1

I consider the following piece of code:

	protected Map<?, ?> someMethod() {
		// Before
		return ImmutableMap.builder()
				// Middle Comment
				.build();
		// After
	}

Simply loading and printing the AST leads to:

	protected Map<?, ?> someMethod() {
		// Before
		return ImmutableMap.builder().build();
		// After
	}

I read https://github.com/javaparser/javaparser/issues/3271, hence https://tomassetti.me/java-comments-parsing/ (which itself targets https://github.com/javaparser/javaparser/wiki/Comments-%28Attribution%29 **but this links looks KO**)

I guess '// Middle Comment' is an orphan comment: OK for me. However, I would have expected this comment to be moved elsewhere, not to be totally dropped.

Is this a bug, or an expected behavior?

> They will be inserted in the list of orphan comments of the first node which contains them.

Makes me feel this comment should not be lost.

**Comment by blacelle** [comment]
I considered trying

> JavaParser.setDoNotAssignCommentsPreceedingEmptyLines(false);

but the method seems to have moved elsewhere

**Comment by jlerbsc** [comment]
HI @blacelle The method JavaParser.setDoNotAssignCommentsPreceedingEmptyLines has not been moved.

**Comment by jlerbsc** [comment]
@blacelle you are right the middle comment is dropped by the prettry printer but the LexicalPreservingPrinter keeps it.

**Comment by jlerbsc** [comment]
@blacelle It seems that the comment is attached to the build method which is represented by a SimpleName node, but the pretty printer does not display comments on this type of node. I will try to correct this issue during the day.

**Comment by blacelle** [comment]
> The method JavaParser.setDoNotAssignCommentsPreceedingEmptyLines has not been moved.

Has it been removed then? (Can not be found in https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/JavaParser.java)

> I will try to correct this issue during the day.

Excellent.

**Comment by jlerbsc** [comment]
You are right setDoNotAssignCommentsPrecedingEmptyLines is implemented in ParserConfiguration.
