### ISSUE TITLE
Clone a MethodDeclaration leads to an unexpected UnsolvedSymbolException

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3322]
I consider a MethodDeclaration. 

```
	public static class CheckStartsWith {
		public Object post(String o) {
			return o.startsWith("Youpi");
		}
	}
```

After cloning it (as we want to unit-test the diff between the original method, and the mutated one), our code encounter issues resolving symbols (here we want to check the type of 'o', which is expected to be spot as a java.lang.String even after cloning):

```
UnsolvedSymbolException{context='null', name='String', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:682)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:740)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:736)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:69)
	at com.github.javaparser.symbolsolver.model.resolution.Value.from(Value.java:45)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveSymbolAsValueInParentContext(Context.java:148)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:161)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:78)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:83)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:533)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
...

```

I consider the following test-case:

```
public class ITGetType {
	private static final Logger LOGGER = LoggerFactory.getLogger(ITGetType.class);

	@UnchangedMethod
	public static class CheckStartsWith {
		public Object post(String o) {
			return o.startsWith("Youpi");
		}
	}

	@Test
	public void testResolveType() throws IOException {
		File file = new File("src/test/java/" + ITGetType.class.getName().replace(".", "/") + ".java");

		if (!file.isFile()) {
			throw new IllegalArgumentException("Can not read: " + file.getAbsolutePath());
		}

		String pathAsString = Files.readString(file.toPath());

		CompilationUnit tree = StaticJavaParser.parse(pathAsString);

		CombinedTypeSolver ts = new CombinedTypeSolver();
		ts.add(new ReflectionTypeSolver());
		JavaParserFacade parser = JavaParserFacade.get(ts);

		tree.findAll(ClassOrInterfaceDeclaration.class).forEach(clazz -> {

			List<MethodDeclaration> preMethods = clazz.getMethodsByName("post");
			if (preMethods.size() != 1) {
				return;
			}
			MethodDeclaration pre = preMethods.get(0);

			pre = pre.clone(); // <-- This is leading to Symbol resolution ssues

			pre.walk(node -> {
				if (!(node instanceof MethodCallExpr)) {
					return;
				}
				MethodCallExpr methodCall = (MethodCallExpr) node;
				if (!methodCall.toString().equals("o.startsWith(\"Youpi\")")) {
					return;
				}

				Optional<Expression> optScope = methodCall.getScope();

				Expression scope = optScope.get();

				ResolvedType type = parser.getType(scope);

				LOGGER.info("Type: {}", type);
			});
		});
	}
}
```

**Comment by jlerbsc** [comment]
Hi @blacelle I modified your example slightly. There are 2 modifications:
1/ method declaration substitution
2/ type resolution

    @Test
    void test() {
        // Source code
        String sourceCode = "public class A {\n" + 
                "        public static class B {\n" + 
                "            public Object post(String o) {\n" + 
                "                return o.startsWith(\"Youpi\");\n" + 
                "            }\n" + 
                "        }\n" + 
                "    }";
        // Setup symbol solver
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        // Setup parser
        JavaParser parser = new JavaParser(configuration);
        CompilationUnit cu = parser.parse(sourceCode).getResult().get();
        // Test
        cu.findAll(ClassOrInterfaceDeclaration.class).forEach(clazz -> {

            List<MethodDeclaration> preMethods = clazz.getMethodsByName("post");
            if (preMethods.size() != 1) {
                return;
            }
            MethodDeclaration md = preMethods.get(0);

            MethodDeclaration cloned = md.clone(); 

            clazz.replace(md, cloned); // 1 - this is how to replace the method declaration in the ClassOrInterfaceDeclaration

            cloned.walk(node -> {
                if (!(node instanceof MethodCallExpr)) {
                    return;
                }
                MethodCallExpr methodCall = (MethodCallExpr) node;
                if (!methodCall.toString().equals("o.startsWith(\"Youpi\")")) {
                    return;
                }

                Optional<Expression> optScope = methodCall.getScope();

                Expression scope = optScope.get();

                ResolvedType type = scope.calculateResolvedType(); // 2 - this is how to solve the type

                System.out.println(type.describe());
            });
        });
    }

**Comment by blacelle** [comment]
Thanks @jlerbsc . You read between lines, and your feedback is very helpful. About the kind of code modification I apply (i.e.  the original snippet comes from a unit-test over a code-mutator), I rather do things like https://github.com/solven-eu/cleanthat/blob/master/java/src/main/java/eu/solven/cleanthat/rules/OptionalNotEmpty.java . Your suggested way of solving types looks much leaner than my current way of proceeding.

---

About the initial ticket, should we consider it an issue due to an ill-usage of the library, or an actual issue/limitation/expected behavior?

**Comment by jlerbsc** [comment]
If you are talking about replacing one node with another, your expression modify only the reference of the method declaration field. The AST is not modified and the symbol solver cannot solve any cloned expression. It seems to me that the exemple show you the best way to do it. 

    pre = pre.clone();

**Comment by blacelle** [comment]
> The AST is not modified and the symbol solver cannot solve any cloned expression. 

This was key to my understanding. Thanks
