### ISSUE TITLE
Is it possible to remove guava, it introduces too many dependencies. 

### ISSUE THREAD

**Issue by xiejx618** [javaparser/javaparser#3327]
Is it possible to remove guava, it introduces too many dependencies. 
![image](https://user-images.githubusercontent.com/2609827/126858151-3fd56288-2160-4f64-8a4b-692940b0a155.png)

**Comment by jlerbsc** [comment]
Hi @xiejx618 Guava library is used mainly to use ImmutableList, Cache, Preconditions. What is your problem with this library? Do you have any conflicts?

**Comment by xiejx618** [comment]
There is no conflict, just import too many dependencies, which caused my plug-in become big
