### ISSUE TITLE
Know if a field access is over an Object or a Class?

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3330]
I consider code like:

```
public class ITGetType {
	private static final String SOME_CONSTANT = "magic";

	public static class CheckEqualsConstant {

		public Object post(String lang) {
			String constant = ITGetType.SOME_CONSTANT;
			return lang.equals(constant);
		}
	}
}
```

I have difficulties inferring an equals methodCall refers to a static final field. I succeed getting the variable constant is Initialized by `ITGetType.SOME_CONSTANT` (even though my methodology might not be the leanest).

- How can I get `ITGetType` is a Class and not a (not Class<?>) object? (it seems related to https://github.com/javaparser/javaparser/issues/1439 and https://github.com/javaparser/javaparser/issues/1506)
- How can I get `SOME_CONSTANT` is a static final field? (i.e. I suppose JavaParser would enable answering this, but I'm find if Java reflection is the way to go)

---

I consider the following test:

```
public class ITGetType {
	private static final String SOME_CONSTANT = "magic";

	public static class CheckStartsWith {

		public Object post(String lang) {
			String constant = ITGetType.SOME_CONSTANT;
			return lang.equals(constant);
		}
	}

	// Setup symbol solver
	final ParserConfiguration configuration = new ParserConfiguration()
			.setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
	// Setup parser
	final JavaParser parser = new JavaParser(configuration);

	// https://github.com/javaparser/javaparser/issues/1439
	// https://github.com/javaparser/javaparser/issues/1506
	@Test
	public void testResolveType() throws IOException {
		File file = new File("src/test/java/" + ITGetType.class.getName().replace(".", "/") + ".java");
		if (!file.isFile()) {
			throw new IllegalArgumentException("Can not read: " + file.getAbsolutePath());
		}
		String pathAsString = Files.readString(file.toPath());
		CompilationUnit tree = parser.parse(pathAsString).getResult().get();

		tree.findAll(ClassOrInterfaceDeclaration.class).forEach(clazz -> {
			List<MethodDeclaration> preMethods = clazz.getMethodsByName("post");
			if (preMethods.size() != 1) {
				return;
			}
			MethodDeclaration pre = preMethods.get(0);
			pre.walk(node -> {
				if (!(node instanceof MethodCallExpr)) {
					return;
				}
				MethodCallExpr methodCall = (MethodCallExpr) node;
				if (!methodCall.toString().contains("equals")) {
					return;
				}

				Expression arg0 = methodCall.getArgument(0);
				if (arg0.isNameExpr()) {
					NameExpr nameExpr = arg0.asNameExpr();
					ResolvedValueDeclaration resolved = nameExpr.resolve();
					System.out.println(resolved);

					if (resolved instanceof JavaParserVariableDeclaration) {
						VariableDeclarator declarator =
								((JavaParserVariableDeclaration) resolved).getVariableDeclarator();
						
						// 'constant = ITGetType.SOME_CONSTANT'
						System.out.println(declarator);
						declarator.getInitializer().ifPresent(expr -> {
							// 'ITGetType.SOME_CONSTANT'
							System.out.println(expr);

							// How can one infer ITGetType is a Class<?> reference?
						});
					}
				}
			});
		});
	}
}
```

Thanks

**Comment by jlerbsc** [comment]
Hi @blacelle, i can answer to this question

> How can I get SOME_CONSTANT is a static final field?
 
In this expression 

    String constant = ITGetType.SOME_CONSTANT;

"ITGetType.SOME_CONSTANT" is a FieldAccessExpr. So you can resolve it to obtain a declaration and the ask it if it's a static declaration.

    ResolvedValueDeclaration rvd = fae.resolve();
    System.out.println(rvd.asField().isStatic());

**Comment by jlerbsc** [comment]
@blacelle it's not clear why you answer that?

> How can I get ITGetType is a Class and not a object? 

ITGetType is a nameExpr so you can resolve the type of the scope. 

    fae.getScope().calculateResolvedType() // fae is a FieldAccessExpression representing ITGetType.SOME_CONSTANT

Can you clarify your question?

**Comment by blacelle** [comment]
Thanks @jlerbsc.

> it's not clear why you answer that?

I thumbed-up your answer ; I'm very happy with your help :).

---

> > How can I get SOME_CONSTANT is a static final field?

I tested your code with the following cases:

```
public class ITGetType {
	private static final String SOME_STATIC_CONSTANT = "magic";
	private final String someConstant = "magic";

	public static class ReferStaticFieldAsStatic {

		public Object post(String lang) {
			String constant = ITGetType.SOME_STATIC_CONSTANT;
			return lang.equals(constant);
		}
	}

	public static class ReferStaticFieldAsField {

		public Object post(String lang) {
			String constant = new ITGetType().SOME_STATIC_CONSTANT;
			return lang.equals(constant);
		}
	}

	public static class ReferFieldAsField {

		public Object post(String lang) {
			String constant = new ITGetType().someConstant;
			return lang.equals(constant);
		}
	}
```

and it correctly/as expected inferred the static nature of the considered field. Thanks a lot.

---

> > How can I get ITGetType is a Class and not a object?

> ITGetType is a nameExpr so you can resolve the type of the scope.

I fear I'm not comfortable with the implication of being a nameExpr. However, I feel your previous answer super-seeded this part of my initial questions: I'm more interested in known the field is a static field, than it being referring through a Class or an object (as a static field can be referred through an object of given class).

My question remains: how can I know (with JavaParser) that ITGetType is a Class<?> name or a (poorly named) variable in the following code:

```
		public Object post(String lang) {
			String constant = ITGetType.SOME_STATIC_CONSTANT;
			return lang.equals(constant);
		}
```
?

Am I wrongly calling _ITGetType_ a _Class name_, while the correct wording would be a _Name Expression_?

**Comment by jlerbsc** [comment]
> how can I know (with JavaParser) that ITGetType is a Class<?> name or a (poorly named) variable

The short answer is 

    fae.getScope().calculateResolvedType().asReferenceType().getTypeDeclaration().get().isClass() or isVariable or isField...

In fact the answer is carried by the declaration. Of course you have to test the different cases in which you find yourself.

**Comment by blacelle** [comment]
Thanks
