### ISSUE TITLE
Turning `AnnotationExpr` into `AnnotationDeclaration`

### ISSUE THREAD

**Issue by oneturkmen** [javaparser/javaparser#3331]
My goal is to get retrieve annotations on annotation declaration. For example, I want to retrieve `@A` and `@B` from the following example where `@Foo` itself is custom annotation:

```java
@A
@B
public @interface Foo { ... }
```

I am given `AnnotationExpr`. Any way to turn it into `AnnotationDeclaration` to be able to call `getAnnotations`?

Thank you!

**Comment by jlerbsc** [comment]
Hi @oneturkmen  from AnnotationDeclaration you can access annotations from getAnnotations() method, from an AnnotationExpr you can get the resolved declaration with the resolve() method then get the annotation declaration from the toAst() method.

    annotationDeclaration.getAnnotations();

or

    ResolvedAnnotationDeclaration rad = annotationDeclaration.resolve();
    rad.toAst().get().getAnnotations();

**Comment by jlerbsc** [comment]
Does this reply answer your question?

**Comment by oneturkmen** [comment]
@jlerbsc Yes, it did! Sorry for the late response.
