### ISSUE TITLE
How to add enum type or annotation type value in addPair

### ISSUE THREAD

**Issue by ramkishor05** [javaparser/javaparser#3332]
((NormalAnnotationExpr)annotationExpr).addPair("name", "\"value\"");

**Comment by jlerbsc** [comment]
Hi @ramkishor05 could you explain to us what you want to do or give us an example of what you are trying to implement?

**Comment by jlerbsc** [comment]
Did you find an answer to your question?

**Comment by MysterAitch** [comment]
@ramkishor05 -- please give an example of what you are trying to achieve (a before/after) and reopen this when you do :+1:
