### ISSUE TITLE
Replace MethodCallExpr with body of called method

### ISSUE THREAD

**Issue by florianwendland** [javaparser/javaparser#3352]
Dear all,

I have to replace a MethodCallExpr with the body of the called method, but failed for several hours to succeed.

Consider the following:

```
someExpression
this.k()
someExpression
```
with

```
public void k()
{
some_K_expression1;
some_K_expression2;
}
```

resulting after transfomation in
```
someExpression
{
some_K_expression1
some_K_expression2
}
someExpression
```
My first attempt was to leverage the ModifierVisitor<Void> and return the BlockStmt of the called expression.
```
public Visitable visit(MethodCallExpr n, Void arg) {
...
final MethodDeclaration methodDecl = ((JavaParserMethodDeclaration)mce).getWrappedNode();
final BlockStmt bodyStmt = methodDecl.getBody().get();
...
return bodyStmt;
```

Seemed promising, but failed with the following ClassCastException:

```
Exception in thread "main" java.lang.ClassCastException: class com.github.javaparser.ast.stmt.BlockStmt cannot be cast to class com.github.javaparser.ast.expr.Expression (com.github.javaparser.ast.stmt.BlockStmt and com.github.javaparser.ast.expr.Expression are in unnamed module of loader 'app')
...
```

I gave several other approaches an attempt, but with no success. I am pretty sure there is a fairly straight forward solution to this problem, but I am just to blind to see it.

Grateful for any hint to solve this problem.

Best regards,
Marc-Florian

**Comment by jlerbsc** [comment]
Hi @florianwendland It seems to me that, in your case, ModifierVisitor would be useful to modify a MethdoCallExpr (arguments, scope, comments ...) but this visitor must return a MethodCallExpr. In your case, you need to resolve the MethodCallExpr to get the declaration, then get the body of that method and replace the initial MethodCallExpr with the BlockStmt.

**Comment by florianwendland** [comment]
You wrote: "...then get the body of that method and replace the initial MethodCallExpr with the BlockStmt."

And how can this be done? Whatever I tried so far resulted in a ClassCastException. Last try:

`methodCallExpression.replace(blockStmt.clone());`

with _blockStmt_ being the resolved body of the corresponding MethodDeclaration.

**Comment by jlerbsc** [comment]
I think in your case you have to replace methodCallExpression with blockStmt in the parent node list of the methodCallExpression.
If you need more help can you give us a simple test case that reproduces your issue.

**Comment by MysterAitch** [comment]
The problem seems to be trying to replace the method call **expression** with a **statement**:

```java
methodCallExpression.replace(blockStmt.clone());
```

The parent of your `MethodCallExpr` (doesn't include the semicolon) is likely to be an `ExpressionStmt` (DOES include the semicolon). 

As a potential solution, try getting the parent node (should be an expression) and try replacing THAT:

![Screenshot from 2021-10-05 18-32-06](https://user-images.githubusercontent.com/1537214/136073630-14ba4e86-f5d6-40bd-b82c-52e5efe8750d.png)

**Comment by jlerbsc** [comment]
Is this issue still open?
