### ISSUE TITLE
[Suggestion] Builder to construct type solvers

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3355]
In the comment https://github.com/javaparser/javaparser/pull/3343#issuecomment-902648574, was suggested to created builder to make it easier to setup the type solvers.

A simple example could be something like:
```java
TypeSolver typeSolver= new TypeSolverBuilder()
    .useJavaRuntime()
    .addJar("path/to/file.jar")
    .addSourceCode("path/to/project")
    .build()
```

Let's try to group suggestion of what would be nice to have in it in this thread.

**Comment by 4everTheOne** [comment]
I think it could be also interesting to add android archives (aar) and manual symbols (memory type solver) with something like:
```java
TypeSolver typeSolver= new TypeSolverBuilder()
    .addAndroidArchive("path/to/file.aar")
    .addManualType("com.example.Foo", fooTypeSymbol)
    .build()
```

**Comment by jlerbsc** [comment]
I am closing this issue since a pr was merged.
