### ISSUE TITLE
Regarding data flow and taint tracking in java code

### ISSUE THREAD

**Issue by navyasri1** [javaparser/javaparser#3356]
Hi,

Can we get the arguments of specific methods and check the data flow of it using java parser in a java project.

For example if method called with an argument and the argument value tracks down to a string at the end in some other file.

**Comment by jlerbsc** [comment]
Hi @navyasri1 At the moment there is no data flow in the javaparser project.

**Comment by jlerbsc** [comment]
There are currently no plans to develop this type of functionality. For the moment we close this issue.

**Comment by matozoid** [comment]
(Maybe @daanvdh can add something here)

**Comment by daanvdh** [comment]
As long as the dataflow you are looking for is in the same file, the functionality you are looking for already exists in https://github.com/daanvdh/JavaDataFlow. It's on the roadmap to support dataflow over multiple files, some help would be much appreciated ;-).
