### ISSUE TITLE
Replace variable usage with one wrapped with Math.abs()

### ISSUE THREAD

**Issue by sjoon2455** [javaparser/javaparser#3360]
Hi, I'm a newbie to javaparser.

I want to replace a variable usage AST node with a one wrapped with Math.abs(), just like as follows;

```a = b+1;``` -> ```a = Math.abs(b)+1;```

I tried to do it as follows;

(...while iterating an AST node...)
```
Optional<Range> nodeRange = node.getRange();
nodeRange.ifPresent(nr-> 
    {if(line == nr.begin.line){
        String snippet = "Math.abs("+nodeName+")";
        Node newNode = StaticJavaParser.parseExpression(snippet);

        // node.replace(newNode);
...
```

The above code yields the following error:

```
Error: class com.github.javaparser.ast.expr.MethodCallExpr cannot be cast to class com.github.javaparser.ast.expr.SimpleName (com.github.javaparser.ast.expr.MethodCallExpr and com.github.javaparser.ast.expr.SimpleName are in unnamed module of loader 'app')
```

I wonder, is it impossible to replace node with another type(SimpleName to MethodCallExpr)?
Or am I implementing in some wrong way?

Thanks in advance!

**Comment by jlerbsc** [comment]
Hi @sjoon2455 as the message says you cannot replace a methodCallExpr by a SimpleName . In this way you can only replace the name of the method, or a parameter or a type... If you want to replace the methodCallExpr by another expression you have to get the parent of the node and call the method like that 

    parentNode.replace(node, replacementNode)

**Comment by sjoon2455** [comment]
@jlerbsc Hi, thank you for your reply. It actually helped!
