### ISSUE TITLE
"yield List.of(1);" should be valid in Java 16

### ISSUE THREAD

**Issue by koppor** [javaparser/javaparser#3364]
Following is a valid Java 16 code:

```java
        List<Integer> result = switch (s) {
            case "Foo":
                yield List.of(1);
            case "Bar":
                yield List.of(2);
            default:
                System.out.println("Neither Foo nor Bar, hmmm...");
                yield Collections.emptyList();
        };
```

However, following error is risen:

    org.opentest4j.AssertionFailedError: [(line 3,col 15) Parse error. Found ".", expected one of  "," ";" "=" "@" "["

I created a PR to a) add a test for that and b) an initial fix (https://github.com/javaparser/javaparser/pull/3361). However, the fix does not work on the CI.

(This issue is created to follow the typical GitHub usage.)

**Comment by jlerbsc** [comment]
This issue is fixed in the current version.
