### ISSUE TITLE
"record" is a valid variable name in Java 16

### ISSUE THREAD

**Issue by koppor** [javaparser/javaparser#3366]
Following statement is a valid statement in Java:

```java
    Object record;
```

When parsing that, following error is output:

    org.opentest4j.AssertionFailedError: [(line 1,col 8) 'record' cannot be used as an identifier as it is a keyword.]

Expected output: no error.

This seems to be https://github.com/javaparser/javaparser/issues/3261, which should be resolved (https://github.com/javaparser/javaparser/issues/3261#issuecomment-841089780), but did not work here.

At https://github.com/javaparser/javaparser/pull/3362, I tried to craft a PR fixing that. However, the CI does not like it. (Locally, in IntelliJ, it runs)

Refs https://github.com/javaparser/javaparser/issues/2446 (requesting for record support), https://github.com/javaparser/javaparser/pull/3022 (implementing records), https://github.com/javaparser/javaparser/issues/3260#issuecomment-839869071 (proposing some fix on `record` handling)

**Comment by MysterAitch** [comment]
> At #3362, I tried to craft a PR fixing that. However, the CI does not like it. (Locally, in IntelliJ, it runs)

It's the Java 14 and Java 15 preview level tests that are not passing -- presumably, once those test cases are updated, the whole test suite will pass :+1:

**Comment by MysterAitch** [comment]
~I think you're right though -- `record` SOMETIMES can be used as a field's identifier which is a nuance the original implementation didn't take into account, my bad!~

edit -- I was wrong, see comments below

![image](https://user-images.githubusercontent.com/1537214/131904604-51921076-2df6-4467-b3d1-04e86d9fe965.png)

**Comment by koppor** [comment]
My IntelliJ says that instance fields are not allowed in records:

![grafik](https://user-images.githubusercontent.com/1366654/131913938-77bbdb26-7182-4ae2-8758-dbe81e955821.png)

I added tests at the PR.

**Comment by koppor** [comment]
Refs https://github.com/javaparser/javaparser/issues/3255

**Comment by MysterAitch** [comment]
> My IntelliJ says that instance fields are not allowed in records:
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/131913938-77bbdb26-7182-4ae2-8758-dbe81e955821.png)
> 
> I added tests at the PR.

Sorry, yes, `record` is permitted as an `Identifier` -- you correctly point out that the error being reported is about it being non-static. When the field is made static it compiles fine.

Thank you for your patience :+1: 

![image](https://user-images.githubusercontent.com/1537214/131980546-15ca41d9-1300-4d0d-a691-3ed40306203d.png)

Looking back at the JLS, `keyword` is only restricted in the context of type identifiers -- I could not find any restriction on `record` used within identifiers used elsewhere (e.g. method names, variable names). 

Here it specifies a `TypeIdentifier` as `Identifier but not var, yield, or record`
https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-TypeIdentifier

The variable declaration uses only `Identifier` (not `TypeIdentifier`).
https://docs.oracle.com/javase/specs/jls/se16/html/jls-8.html#jls-FieldDeclaration

For completeness, `Identifier` is defined as `IdentifierChars but not a Keyword or BooleanLiteral or NullLiteral`
https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-Identifier
