### ISSUE TITLE
Netlify something something build will fail after September 19

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#3374]
I've been getting these mails:

---
Final deprecation notice: Action required to prevent build failures after September 19

The Netlify build system maintains multiple build images, which set the environment in which your sites build. One or more of your sites is using the “Trusty” image, built on Ubuntu 14.04 (“Trusty Tahr”). The Trusty image moved into legacy support in 2019, after Ubuntu 14.04 reached end of life.

On September 19, 2021, we will end all support for the Netlify Trusty image. We have identified the following impacted sites belonging to your team, Federico Tomassetti's team:

javaparser

Select a site name above to access specific site settings in the Netlify UI where you can change the site’s build image. For more information about changes between images, how to run a test build, how to bulk upgrade multiple sites, and how to troubleshoot issues with upgrading, please visit the Trusty build image migration guide in the Netlify Support Forums.

If you have any questions, feel free to post a reply to the migration guide, where Netlify staff and community members are always happy to help!

**Comment by MysterAitch** [comment]
Do we know what Netlify is being used for?

**Comment by matozoid** [comment]
A quick search doesn't turn up anything. Maybe @ftomassetti knows?

I guess if nothing fails a week from now this issue can be safely closed.

**Comment by ftomassetti** [comment]
Hi @matozoid, I think I saw you yesterday at the Virtual Meetup :D Thank you for attending.
I think javaparser.org was published through Netlify at some point, but the last update I see there is from 2018
<img width="1486" alt="Screenshot 2021-09-17 at 14 54 47" src="https://user-images.githubusercontent.com/439078/133785842-65ebbf3a-70eb-4e7e-bfbd-802a8c4d14a6.png">

So either we moved out of Netlify or we have not been updating the website for a lot of time

**Comment by ftomassetti** [comment]
At least the number of stars is old :
<img width="1382" alt="Screenshot 2021-09-17 at 14 56 04" src="https://user-images.githubusercontent.com/439078/133786014-a8325665-4b14-4338-b047-a3d66b6fbe92.png">
D

**Comment by ftomassetti** [comment]
But I read that the new website is hosted on Github pages, so Netlify should not be relevant

**Comment by matozoid** [comment]
@ftomassetti - if you have an account, maybe you can remove uhh, whatever is there :-) And yeah, the meeting made me curious - for a while now my opinion is that we software developers are very stubborn and using very stupid tools (a text editor with a type writer font. Some are even defending vi! Come on!) so I'm very interested in tooling that really improves our work.
