### ISSUE TITLE
If we want to cite you?

### ISSUE THREAD

**Issue by mosh98** [javaparser/javaparser#3379]
Hi, writing a paper at the moment,
Wanted to know how we could cite you guys.

Is there a paper ya'll wrote or should i cite the book?

**Comment by MysterAitch** [comment]
Hi, 

There are a few options. 

There is an ebook available:
https://leanpub.com/javaparservisited


Alternatively, there are Zenodo DOIs available -- here's the DOI/link from the readme badge for the project itself, and DOIs for specific versions are available via there.

https://doi.org/10.5281/zenodo.2667378

> Cite all versions? You can cite all versions by using the DOI 10.5281/zenodo.2667378. This DOI represents all versions, and will always resolve to the latest one. Read more.


We're always keen to hear about how JavaParser is being used and to read publications where it has been used -- are you able to share any details? :+1:

**Comment by mosh98** [comment]
Thanks man!

Won't be able to share any details yet , but i will post in this issue thread once we publish it for sure! 

Have a nice day!
