### ISSUE TITLE
LexicalPreservingPrinter adds wrong indentation when adding new comments

### ISSUE THREAD

**Issue by ErtelJessica** [javaparser/javaparser#3387]
I'm using javaparser-symbol-solver-core 3.23.0
When adding a new comment to a method, the comment will be indented correctly, but the next node is not. This is due to `com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.Observer.fixIndentOfMovedNode(NodeText, int)` which always adds a Space to the next node of the new comment. But it should add the indentation prior to the comment (e.g. a tab) instead.

Failing Example:
```
String input = new StringJoiner("\n")
	.add("class A {")
	.add("")
	.add("\tpublic void setTheNumber(int number) {")
	.add("\t\tnumber = number;")
	.add("\t}")
	.add("")
	.add("}").toString();

CompilationUnit cu = StaticJavaParser.parse(input);
LexicalPreservingPrinter.setup(cu);

MethodDeclaration md = cu.findFirst(MethodDeclaration.class).get();
// create new comment
// due to https://github.com/javaparser/javaparser/issues/3191
Comment comment = new JavadocComment("new content");
md.setComment(comment);
System.out.println("cu");
System.out.println(cu);

System.out.println("lpp");
System.out.println(LexicalPreservingPrinter.print(cu));
```

The result will be

```
cu
class A {

    /**
     * new content
     */
    public void setTheNumber(int number) {
        number = number;
    }
}

lpp
class A {

	/**new content*/
 public void setTheNumber(int number) {
		number = number;
	}

}

```
So public void setTheNumber should not have the Space but a tab instead. And of course it would be nice if the JavaDoc comment would be formatted in three lines instead of one, but this could also be fixed by String manipulation if needed.

**Comment by jlerbsc** [comment]
Thank you for reporting this bug

**Comment by jlerbsc** [comment]
I'm not sure but it seems that the tab char '\t' is misinterpreted. If you replace tab character by space indentation then the result seems correct.

    String input = new StringJoiner("\n")
                .add("class A {")
                .add("")
                .add("    public void setTheNumber(int number) {")
                .add("        number = number;")
                .add("    }")
                .add("")
                .add("}").toString();


    class A {

        /**new content*/
        public void setTheNumber(int number) {
            number = number;
        }

    }

**Comment by ErtelJessica** [comment]
As far as I am able to understand your code, you are searching (in the method mentioned above, see https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinter.java#L305) for a "spaceCandidate". And for every such candidate you add `nodeText.addElement(index, new TokenTextElement(JavaToken.Kind.SPACE.getKind()));`. So I think in case of Space indentation you have 4 candidates and add four spaces. In case of \t you have only one candidate and add one space. 
But instead you schould add the type of spaceCandidate instead (e.g. 4 spaces or 1 \t).

**Comment by jlerbsc** [comment]
You are probably right!

You can also create the javadoc comment like this

    Javadoc javadoc = new Javadoc(JavadocDescription.parseText("new content"));
    md.setJavadocComment("\t", javadoc);

**Comment by ErtelJessica** [comment]
Thanks for the hint, but that does not solve the indentation problem, because `setJavadocComment(String indentation, Javadoc javadoc)` seems to be only responsible for the indentation of the comment itself. This does not change the space preceding the next line.
However creating the comment like this will cause the JavadocComment to be formatted as expected (e.g. in three lines instead of one line)!
