### ISSUE TITLE
Parsing error when having comment `/**/` in code.

### ISSUE THREAD

**Issue by allomy** [javaparser/javaparser#3400]
Try the following code for `Test1.java` and `Test2.java`, the `Test1.java` will give failure `com.github.javaparser.ParseProblemException: String index out of range: 3`, while the `Test2.java` parse successfully, there might be some issue with the regex of `/**/`.
```
try {
    parsed = JavaParser.parse(content);
} catch (ParseProblemException e) {
    System.err.println(e.toString());
}
```
```
// Test1.java
public class A {
	public void test() {
		/**/
	}
}
```
```
// Test2.java
public class A {
	public void test() {
	}
}
```

The javaparser version is showing below:
```
    <dependency>
      <groupId>com.github.javaparser</groupId>
      <artifactId>javaparser-core</artifactId>
      <version>3.23.1</version>
    </dependency>
```

**Comment by jlerbsc** [comment]
Curiously there is no static parse method in JavaParser!

This test case does not throw an exception

    void test3400() {
        String src = "// Test1.java\n" + 
                "public class A {\n" + 
                "    public void test() {\n" + 
                "        /**/\n" + 
                "    }\n" + 
                "}";
        CompilationUnit cu = StaticJavaParser.parse(src);
    }

**Comment by allomy** [comment]
@jlerbsc  Thank you for your quickly respond. A question that, is the StaticJavaParser work the same as JavaParser, that we could replace JavaParser as StaticJavaParser, is it right?

**Comment by jlerbsc** [comment]
Hmm no. StaticJavaParser is a wrapper around JavaParser. It seems to me that this use is not recommended by the JavaParser team. Personnaly i use it as an utility class to build unit test.
It's probably more appropriate to use this

    new JavaParser(configuration);

**Comment by allomy** [comment]
That makes sense, thank you, @jlerbsc .
