### ISSUE TITLE
LexicalPreservingPrinter fails to add imports above class comments

### ISSUE THREAD

**Issue by nimakarimipour** [javaparser/javaparser#3403]
If in a source file, the class itself is commented, ```LexicalPreservingPrinter``` fails to add import statements above the comment and imports are added after the class comment.

Please consider the input below where I want to add two method annotations on `run()` and `exec()`:

```java
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * THIS IS JAVADOC
 */
public class Test {

    public Object run(){
        //just to import random stuff, with less import statements, there is no issue and I cannot reproduce the bug
        ArrayList<Object> d0;
        List<Object> d1;
        HashMap<Object, Object> d2;
        Map<Object, Object> d3;
        LinkedList<Object> d4;
        Random d5;
        Arrays d6;
        return null;
    }

    public void exec(){
    }
}
```

Please find code below that adds two method annotations to the input above:

```java
private static void main(String[] args) throws Exception{
    String path = "PATH_TO/Test.java";
    CompilationUnit cu = LexicalPreservingPrinter.setup(StaticJavaParser.parse(new File(path)));
    TypeDeclaration<?> clazz = cu.getClassByName("Test").get();
    addAnnotation(cu, clazz, "exec", "Annotation", "custom.Annotation");
    addAnnotation(cu, clazz, "run", "Nullable", "javax.annotation.Nullable");
    System.out.println(LexicalPreservingPrinter.print(cu));
  }

private static void addAnnotation(CompilationUnit cu, TypeDeclaration<?> clazz, String method, String simpleName, String fullName){
    clazz.getMembers().forEach(
            bodyDeclaration ->
                    bodyDeclaration.ifCallableDeclaration(
                            callableDeclaration -> {
                              if (callableDeclaration.getName().asString().equals(method)) {
                                callableDeclaration.addMarkerAnnotation(simpleName);
                              }
                            }));
    cu.addImport(fullName);
  }
```
If we run the code above, we get the output below:

```java
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Random;
import custom.Annotation;
/**
 * THIS IS JAVADOC
 */
import javax.annotation.Nullable;

public class Test {
    @Nullable
    public Object run(){
        //just to import random stuff, with less import statements, there is no issue and I cannot reproduce the bug
        ArrayList<Object> d0;
        List<Object> d1;
        HashMap<Object, Object> d2;
        Map<Object, Object> d3;
        LinkedList<Object> d4;
        Random d5;
        Arrays d6;
        return null;
    }

    public void exec(){
    }
}
```

As you can see, `import javax.annotation.Nullable` statement is added after the class comment.

Please note that if we do any of the followings, the error will not reproduce:

1. Have less import statements in the source file.
2. Use `DefaultPrettyPrinter` instead of `LexicalPreservingPrinter`.
3. Remove class comments.

With best regards

**Comment by jlerbsc** [comment]
Hi @nimakarimipour did you try to insert your import with 

    cu.getImports().add() or cu.getImports().addLast()

**Comment by nimakarimipour** [comment]
> Hi @nimakarimipour did you try to insert your import with
> 
> ```
> cu.getImports().add() or cu.getImports().addLast()
> ```

Hi @jlerbsc , I used the following code as you suggested:

```java
ImportDeclaration importDeclaration = StaticJavaParser.parseImport("import " + fullName + ";");
cu.getImports().addLast(importDeclaration); // or just add()
```

And below is the output: (duplicate import statements and still below the comment)

```java
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Random;
import edu.ucr.cs.riple.injector.Initializer;
/**
 * THIS IS JAVADOC
 */
import javax.annotation.Nullable;
import javax.annotation.Nullable;

public class Test {

    Object f;

    @Nullable
    public Object run(){
        //dummy just to import random stuff
        ArrayList<Object> d0;
        List<Object> d1;
        HashMap<Object, Object> d2;
        Map<Object, Object> d3;
        LinkedList<Object> d4;
        Random d5;
        Arrays d6;
        return null;
    }

    @Initializer
    public void setF(Object f){
        this.f = f;
    }
}
```
I saw duplicate `import statements` with `cu.addImport()` as well when class has a comment on top and `LexicalPreservingPrinter` is used.

**Comment by jlerbsc** [comment]
Hi @nimakarimipour you are right! I don't know why but it's the expected behavior. A workaround is to insert the import declaration before others imports.

    cu.getImports().addFirst(importDeclaration);

Unfortunately LexicalPreservingPrinter has become very complex (there are a lot of cases to deal with) and insufficiently documented so if we change the current behavior (which is what we expect) we risk introducing new bugs.

**Comment by jlerbsc** [comment]
is this solution right for you?

**Comment by nimakarimipour** [comment]
> is this solution right for you?

Hi @jlerbsc 

Thank you for your solution, I could resolve the issue with the solution you mentioned and the class comments are in their right place.

With best regards.

**Comment by jlerbsc** [comment]
I am closing this problem for the moment but you are free to reopen it if you notice another problem.
