### ISSUE TITLE
LexicalPreservingPrinter.print, but indentation disappeared！！

### ISSUE THREAD

**Issue by saberya** [javaparser/javaparser#3404]
As follows, this is what a compileUnit content:
**CompileUnit cu:**

```
@Generated("jsonschema2pojo")
public class AaCO {
    
    public String title;
    
    public String originTotalPriceTitle;

    public String originTotalPriceStr;
    
    public List<PromotionTextsType> promotionTexts = new ArrayList<PromotionTextsType>();
    
    public String totalDiscountTitle;
    
    public String totalDiscountPriceStr;
    
    public String totalPriceTitle;

    public String totalPriceStr;

    @Generated("jsonschema2pojo")
    static class PromotionTextsType {
        
        public String name;
        
        public List<SubType> subList = new ArrayList<SubType>();
    }

    @Generated("jsonschema2pojo")
    static class SubType {

        public String desc;
    }
}
```
the two static classes is generated by "**typeDeclaration.addMember(innerDeclaration);**",
all in all, the result of cu.toString() is as above.

i just execute **LexicalPreservingPrinter.print(cu);**,
and then, the cu result is:
```
@Generated("jsonschema2pojo")
public class AaCO {
    
    public String title;
    
    public String originTotalPriceTitle;

    public String originTotalPriceStr;
    
    public List<PromotionTextsType> promotionTexts = new ArrayList<PromotionTextsType>();
    
    public String totalDiscountTitle;
    
    public String totalDiscountPriceStr;
    
    public String totalPriceTitle;

    public String totalPriceStr;
    @Generated("jsonschema2pojo")
**// the four blank spaces before "static" were deleted**
static class PromotionTextsType {
        
    public String name;
    
    public List<SubType> subList = new ArrayList<SubType>();
}

    @Generated("jsonschema2pojo")
// the four blank spaces before "static" were deleted
static class SubType {

    public String desc;
}
}
```
this two static classes indentation disappeared，i don't know what happened and i don't understand how LexicalPreservingPrinter save all information.
So, now i only cant user cu.toString() with risk of data distortion
Urgently, plz tell me how to resolve it

**Comment by saberya** [comment]
oh, bro, i think i find the reason:
At the beginning， 
```
com.github.javaparser.JavaParser javaParser =
            new com.github.javaparser.JavaParser(new ParserConfiguration().setLexicalPreservationEnabled(true));
```
this javaParse will lead to above problem, i don't know why  this  describe "**LexicalPreservingPrinter.print can be used to reproduce the original formatting of the file.**"  is wrong, or there sth i don't understand completely.

when i use 
```
com.github.javaparser.JavaParser javaParser =
            new com.github.javaparser.JavaParser();
```
the problem resovled, is this a bug for you?
what is real meaning of "the original formatting of the file" for LexicalPreservingPrinter?

**Comment by jlerbsc** [comment]
Hi @saberya LexicalPreservingPrinter must be initialized before it can be used.

**Comment by saberya** [comment]
@jlerbsc 
com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinterTest#testReplaceClassName
```
 @Test
    public void testReplaceClassName() {
        final JavaParser javaParser = new JavaParser(new ParserConfiguration().setLexicalPreservationEnabled(true));

        final String code = "class A {}";
        final CompilationUnit b = javaParser.parse(code).getResult().orElseThrow(AssertionError::new);
        LexicalPreservingPrinter.setup(b);

        assertEquals(1, b.findAll(ClassOrInterfaceDeclaration.class).size());
        b.findAll(ClassOrInterfaceDeclaration.class).forEach(coid -> coid.setName("B"));

        final String expected = "class B {}";

        final String actual = LexicalPreservingPrinter.print(b);
        assertEquals(expected, actual);
    }
```
the above is a junit test eg from project, i do sth like this. 
what the meaning of "initialize LexicalPreservingPrinter", i just call static method "LexicalPreservingPrinter.print()"?

**Comment by jlerbsc** [comment]
The setup method initializes the original formatting of the compilation unit. Is there an issue?

**Comment by saberya** [comment]
OK, bro, plz execute following junit test.
there is no interface to generate pojo with nested classes, so i add inner classes like this.
```
@Test
    void addingMember() throws IOException {
        String s1 = "\n" +
                "package com.test;\n" +
                "\n" +
                "import javax.annotation.Generated;\n" +
                "\n" +
                "@Generated(\"jsonschema2pojo\")\n" +
                "public class List {\n" +
                "\n" +
                "    /**\n" +
                "     * \n" +
                "     * (Required)\n" +
                "     * \n" +
                "     */\n" +
                "    public String index;\n" +
                "    /**\n" +
                "     * \n" +
                "     * (Required)\n" +
                "     * \n" +
                "     */\n" +
                "    public String text;\n" +
                "    /**\n" +
                "     * \n" +
                "     * (Required)\n" +
                "     * \n" +
                "     */\n" +
                "    public String title;\n" +
                "\n" +
                "}\n";
        String s2 = "\n" +
                "package com.test;\n" +
                "\n" +
                "import java.util.ArrayList;\n" +
                "import javax.annotation.Generated;\n" +
                "\n" +
                "@Generated(\"jsonschema2pojo\")\n" +
                "public class Fields {\n" +
                "\n" +
                "    public java.util.List<com.test.List> list = new ArrayList<com.test.List>();\n" +
                "    public String title;\n" +
                "\n" +
                "}\n";
        String rootCO = "\n" +
                "package com.test;\n" +
                "\n" +
                "import javax.annotation.Generated;\n" +
                "\n" +
                "@Generated(\"jsonschema2pojo\")\n" +
                "public class AaCO {\n" +
                "\n" +
                "    public Fields fields;\n" +
                "    public String id;\n" +
                "    public String market;\n" +
                "    public String tag;\n" +
                "    public String type;\n" +
                "\n" +
                "}\n";
        List<String> innerClassCode = new ArrayList<>();
        innerClassCode.add(s1);
        innerClassCode.add(s2);
        JavaParser javaParser = new JavaParser(new ParserConfiguration().setLexicalPreservationEnabled(true));
        CompilationUnit parser = LexicalPreservingPrinter.setup(javaParser.parse(rootCO).getResult().get());
        NodeList<TypeDeclaration<?>> types = parser.getTypes();
        for (String code : innerClassCode) {
            CompilationUnit innerParser = javaParser.parse(code).getResult().get();
            NodeList<TypeDeclaration<?>> innerTypes = innerParser.getTypes();
            for (TypeDeclaration innerDeclaration : innerTypes) {
                innerDeclaration.addModifier(STATIC);
                innerDeclaration.removeModifier(PUBLIC);
                types.get(0).addMember(innerDeclaration);
            }
        }
        String content = LexicalPreservingPrinter.print(parser);
        System.out.println(content);
    }
```

the indentation before "static" disappeared. Is there a bug ?
```
    public String totalPriceStr;
**// the four blank spaces before "static" were deleted**
static class PromotionTextsType {
        
    public String name;
    
    public List<SubType> subList = new ArrayList<SubType>();
}
```

```
    public String totalPriceStr;

    @Generated("jsonschema2pojo")
    static class PromotionTextsType {
        
        public String name;
        
        public List<SubType> subList = new ArrayList<SubType>();
    }
```

**Comment by apixandru** [comment]
I think that what @saberya is trying to point out is that when inserting one type into another type with lexical preservation, his expectation is that the entire new type would be indented. Currently, only the first line is idented to the last indentation detected in the file.

Doesn't seem to have anything to do with the static/public modifiers but general inserting multi-line elements into another type.

Also, the major issue here is the fact that both compilation units want to preserve the original indentation.

In his particular case, the intended behavior is obtained by parsing s1 and s2 without lexical preservation and then rootCo with lexical preservation. If that scenario happens then the indentation is what you would expect.

I guess the point is that when two files have lexical preservation and one is inserted into the other, it would make sense to indent all lines from the second file by the "current indentation" level of the first file while also preserving the second file's original indentation.

package com.test;

```
public class Parent {

    public Child child;

}

```

```
package com.test;

public class Child {

    public int id;

}
```

parentTypeDeclaration.addMember(childTypeDeclaration);

![image](https://user-images.githubusercontent.com/4395571/141658099-cca21ae8-b08c-41b9-8f3c-14a26fcc167f.png)

**Comment by saberya** [comment]
thanks, bro, @apixandru. i don't know the function details. Actually, this is a demand for nested classes.
A detail I need to point out that the first line of inner class is also not indented.
![image](https://user-images.githubusercontent.com/45654384/141664472-4f7fa6a3-36f3-4650-b82a-60b37e5f1215.png)

**Comment by jlerbsc** [comment]
This is because the child declaration is inserted as a single element. So a single ident is added before the child element.

It seems better to build a new Declaration like this

    ClassOrInterfaceDeclaration citd = new ClassOrInterfaceDeclaration(innerDeclaration.getModifiers(), innerDeclaration.asClassOrInterfaceDeclaration().isInterface(), innerDeclaration.getNameAsString());
    citd.addModifier(Modifier.Keyword.STATIC);
    citd.setMembers(innerDeclaration.getMembers());
    // and then add it as a new member 
    types.get(0).addMember(citd);

**Comment by jlerbsc** [comment]
Is this solution right for you?

**Comment by saberya** [comment]
It look likes that the result is right with the code with you provide.@jlerbsc
But i also don't understand even if i insert my inner class as single element, the result of "cu.toString()" is what i expect, however the result of "LexicalPreservingPrinter.print(cu)" lacks the indentation. 
I think there is some problem in the parsing of LexicalPreservingPrinter.

**Comment by jlerbsc** [comment]
It's just not the same algorithm. Syntactic preservation memorizes the syntax when calling the setup method and then tries to add, remove or keep the elements according to the actions that are performed. The algorithm is certainly not perfect, but there are a lot of different cases to deal with. It has become far too complex over the years.

**Comment by saberya** [comment]
ok, i get it.

**Comment by jlerbsc** [comment]
In this issue we expect the addition of an inner class to be indented.
The explanation provided by @apixandru is correct.
Below is a simplified test case that explains what must be done to obtain the expected behavior.

    @Test
    void addingMember() throws IOException {
        String s1 =
                "@Generated(\"jsonschema2pojo\")\n" +
                "public class List {\n" +
                "}\n";
        String rootCO =
                "public class AaCO {\n" +
                "\n" +
                "    public Fields fields;\n" +
                "\n" +
                "}\n";

        // Parser initialization without LPP
        JavaParser javaParser = new JavaParser(new ParserConfiguration());

        // Parse and modify the type to be inserted
        TypeDeclaration<?> typeS1 = javaParser.parse(s1).getResult().get().getType(0);
        typeS1.addModifier(Modifier.Keyword.STATIC);
        typeS1.removeModifier(Modifier.Keyword.PUBLIC);

        // Parse the root type
        CompilationUnit parser = LexicalPreservingPrinter.setup(javaParser.parse(rootCO).getResult().get());
        TypeDeclaration<?> actualType = parser.getTypes().get(0);

        // Add the inner type
        actualType.addMember(typeS1);

        String content = LexicalPreservingPrinter.print(parser);
        System.out.println(content);
    }
