### ISSUE TITLE
Do something with com.github.javaparser.Position

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#341]
It is not in use. @ftomassetti - did you have plans for it?

**Comment by ftomassetti** [comment]
I think it could be useful to start using it but we can readd it if needed. Nothing against dropping it.

**Comment by matozoid** [comment]
Where would you use it?

**Comment by ftomassetti** [comment]
In all places where we use a combination of line and column. It could also hold the source name (either a file name or a constant value like `<string>`).

**Comment by matozoid** [comment]
Hm, that would be major API breakage, right?

**Comment by matozoid** [comment]
I'll see what happens if I start using it.

**Comment by matozoid** [comment]
@ftomassetti as I'm going along, it seems that we need a "Range" class more than a "Position" class, since Positions always come in a begin-end pair. What do you think?

**Comment by ftomassetti** [comment]
I would think that a range could be composed by two positions :)
There is just to consider where to put the source (e.g., the filename) in
case we need it

On 12 July 2016 at 15:30, Danny van Bruggen notifications@github.com
wrote:

> @ftomassetti https://github.com/ftomassetti as I'm going along, it
> seems that we need a "Range" class more than a "Position" class, since
> Positions always come in a begin-end pair. What do you think?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/javaparser/javaparser/issues/341#issuecomment-232047450,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAazJglqXGcX0k6T2vlW8ygjTVuPitOzks5qU5bngaJpZM4JHh0H
> .

## 

Website at http://tomassetti.me
GitHub https://github.com/ftomassetti

**Comment by matozoid** [comment]
Of course, but do you think it would be a good idea to give Node a Range instead of two Positions?

Source could still go in Position. It would add a bit more memory usage, but I'm sure nobody will mind.

**Comment by matozoid** [comment]
In use on master.
