### ISSUE TITLE
align StaticJavaParser and SourceRoot parser config APIs

### ISSUE THREAD

**Issue by ericprud** [javaparser/javaparser#3415]
``` java
ParserConfiguration pc1 = StaticJavaParser.getConfiguration();
ParserConfiguration pc2 = new SourceRoot(...).getParserConfiguration();
```
Perhaps call them both `getParserConfiguration()` (would imply an update to this javaparser-visit book and git repo).

**Comment by MysterAitch** [comment]
Sounds like a good idea! 

I've marked it as an Easy first change -- anybody looking at this, I would request marking `getConfiguration` as deprecated rather than removing it.

**Comment by nelson-ng-96** [comment]
Hi, I would like to work on this issue for my university project. Is it possible for this issue to be assigned to me?

**Comment by jlerbsc** [comment]
This issue has been resolved.

**Comment by ericprud** [comment]
I lost my copy somewhere in the bowels of my file system, but should the authors of [JavaParser: Visited](https://leanpub.com/javaparservisited) be informed?

**Comment by jlerbsc** [comment]
> I lost my copy somewhere in the bowels of my file system, but should the authors of [JavaParser: Visited](https://leanpub.com/javaparservisited) be informed?

I'm not sure whether this book is regularly updated by its author(s), who are no longer contributing to the project.
