### ISSUE TITLE
how can I find out the scope of a variable?

### ISSUE THREAD

**Issue by dr3ws** [javaparser/javaparser#3423]
Here is an example of the code:

>         final int d = 9;
>         int a = 0, b = 1, c = 0;
> 
>         if (n < 4) {
>             int j = 0;
>             if (n < 2)
>                 int x = 0;
>             else
>                 int x = 1;
>         }

received output:
`[final int d = 9, int a = 0, b = 1, c = 0, int j = 0, int x = 1, int x = 0]`

how can you split variables to get something like this:
`final int d = 9, int a = 0, b = 1, c = 0` and `int j = 0, int x = 1, int x = 0`

my code:

>     public void visit(VariableDeclarationExpr variables, Void arg) {
>         variablesList.add(variables.toString());
>     }

does `variables` have any properties to solve this problem?

**Comment by MysterAitch** [comment]
The short version is that no, scope information is not encoded or directly accessible.

A naive approach is to repeatedly get the parent node until you reach either a `BlockStmt` (`{}`) or, like in your example, another node which implicitly represents a code block (implicitly added braces).

Variables declared within a for-header and parameters will also need to be handled differently too, given that they are declared outside of the block (the `{}`) to which these variables are scoped.

... And if that's not bad enough, scope gets even trickier still with Java 16 and the pattern matching variables.


So, not an ideal answer but hopefully this helps to clarify/explain a little further! :+1:

**Comment by dr3ws** [comment]
Okay, I get it. Thank you! 🙂
