### ISSUE TITLE
How can I get a relationship between a declared variable and an expression where this variable is used?

### ISSUE THREAD

**Issue by dr3ws** [javaparser/javaparser#3426]
There are the following sample code:

>     func(int n) {
>         int a = 0, b = 1;
>         a = b + n;
>         b = n;
>     }

How can I find out that the variable `n` is used in the expressionand `a = b + n` and  `b = n` , and the variable `b` is used in the expression `a = b + n` ?

Required to build a Data Dependency Graph (DDG).

**Comment by jlerbsc** [comment]
Hi @dr3ws currently there is no method that allows you to do this you must develop this research.

**Comment by dr3ws** [comment]
Okay, I got it! Thanks!🙂

**Comment by jlerbsc** [comment]
Hi @dr3ws Of course if you want to add this possibility to the JavaParser project you can submit your development. This issue seems to be related to this one #2257
