### ISSUE TITLE
JavaParserTypeSolver accepting something other than root src directory

### ISSUE THREAD

**Issue by roksui** [javaparser/javaparser#3439]
Hi team,

I am wondering if there is any way to let `JavaParserTypeSolver` to search through source code in format of InputStreams or byte array, insteand of giving it the root source directory? Because, I use this module at the backend of my program, and don't have access to the actual physical file path of the source code.

So, would there be any way to use `JavaParserTypeSolver` to go through string, byte array or any reader type objects to achieve the same result as feeding it the src directory?

**Comment by jlerbsc** [comment]
Hi @chop-sui This is probably because JavaParserTypeSolver needs to know all of your context in order to resolve symbols.

**Comment by roksui** [comment]
@jlerbsc Yes, I think so. I might have to manually go through all the imports in the src files and implement a similar functionality as what JavaParserTypeSolver does.

**Comment by jlerbsc** [comment]
Does this answer your question?

**Comment by roksui** [comment]
@jlerbsc yes thank you. Do you guys have any plan on letting JavaParserTypeSolver to search through source codes in the form of zip files as in ZipInputStream?

**Comment by jlerbsc** [comment]
This is not planned at the moment.
