### ISSUE TITLE
DumpVisitor upgrade

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#344]
- rename to something like "OutputVisitor"
- make formatting configurable, at least the indent ("\t", or "    ", or "  ", ...)
- deprecate DumpVisitor, remove in 3.0

**Comment by ftomassetti** [comment]
What about "PrettyPrintVisitor"?
So not keeping formatting because a feature, instead of a bug

**Comment by matozoid** [comment]
You should be in sales!

**Comment by ftomassetti** [comment]
Well, in the last year I had to sell my services so I learn a few things :D

**Comment by matozoid** [comment]
Refer to #122 for inspiration.
