### ISSUE TITLE
LexicalPreservingPrinter prints wrong output with line comments

### ISSUE THREAD

**Issue by xmcp** [javaparser/javaparser#3441]
Consider the following code:

```java
public class Foo {
    void bar() {
        stmt1(); // comment 1
        stmt2(); // comment 2
    }
}
```

If I use JavaParser to remove `stmt1();` and print the modified code, it turns out to be:

```java
public class Foo {
    void bar() {
 // comment 1        stmt2(); // comment 2
    }
}
```

You can see that a `\n` is missing after `// comment 1`, commenting out the next line, which is not what we want.

A code to reproduce this issue is:

```java
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.stmt.Statement;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class TestPrinter {
    public static void main(String[] args) {
        String src = "\n" +
            "public class Foo {\n" +
            "    void bar() {\n" +
            "        stmt1(); // comment 1\n" +
            "        stmt2(); // comment 2\n" +
            "    }\n" +
            "}\n";

        CompilationUnit cu = StaticJavaParser.parse(src);
        LexicalPreservingPrinter.setup(cu);

        BlockStmt method = cu.findFirst(BlockStmt.class).get();
        Statement stmt = method.getStatements().get(0); // stmt1()
        method.remove(stmt);

        System.out.println(LexicalPreservingPrinter.print(cu));
    }
}
```

I am using javaparser-core-3.23.1 on Java 1.8.0_271.

**Comment by jlerbsc** [comment]
Hi @xmcp maybe you also want to delete the comment?

     stmt.removeComment();
     method.remove(stmt);

This allows to have a correct result

    public class Foo {
      void bar() {
         stmt2(); // comment 2
      }
    }

**Comment by xmcp** [comment]
Thanks for this workaround.

Although this bug can be avoided by manually removing the comment before node removal, it is still very confusing that something in the previous statement will affect next statement so hope that it will be fixed in the next version.
