### ISSUE TITLE
LexicalPreservingPrinter does not preserve file format

### ISSUE THREAD

**Issue by JohnMcGuinness** [javaparser/javaparser#3447]
The following simple code:

```java
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.utils.CodeGenerationUtils;
import com.github.javaparser.utils.SourceRoot;

public class App {

	public static void main(String[] args) {
		new App().process();
	}

	private void process() {
		final ParserConfiguration config = new ParserConfiguration();
		config.setLexicalPreservationEnabled(true);
		final SourceRoot sourceRoot = new SourceRoot(CodeGenerationUtils.mavenModuleRoot(App.class).resolve("src/main/java"), config);
		sourceRoot.parse("", "Target.java");
		sourceRoot.saveAll();
	}
}
```

Does not preserve formatting of a simple Java file.

The following file before formatting:

```java
public class Target {

    public String foo(
        int arg1,
        int arg2
    ) {
        return String.valueOf(arg1 + arg2);
    }
}
```
Is formatted to this:

```java
public class Target {

    public String foo(int arg1, int arg2) {
        return String.valueOf(arg1 + arg2);
    }
}
```
The javadoc for ```LexicalPreservingPrinter``` says
> When this is enabled, LexicalPreservingPrinter.print can be used to reproduce the original formatting of the file.

Am I misunderstanding the purpose of ```LexicalPreservingPrinter```

**Comment by jlerbsc** [comment]
Hi @JohnMcGuinness In this case you have to setup the lexicalPreservingPrinter with the CompilationUnit like this.

> CompilationUnit cu = sourceRoot.parse("", "Target.java");
    LexicalPreservingPrinter.setup(cu);
    sourceRoot.saveAll();

**Comment by JohnMcGuinness** [comment]
It turns out I was missing just one thing. The processing method requires ```sourceRoot.setPrinter(LexicalPreservingPrinter::print);``` together with ```configuration.setLexicalPreservationEnabled(true);```. So the full method should be
```java
private void process() {
		final ParserConfiguration config = new ParserConfiguration();
		config.setLexicalPreservationEnabled(true);
		final SourceRoot sourceRoot = new SourceRoot(CodeGenerationUtils.mavenModuleRoot(App.class).resolve("src/main/java"), config);
		sourceRoot.setPrinter(LexicalPreservingPrinter::print);
		sourceRoot.parse("", "Target.java");
		sourceRoot.saveAll();
	}
```

**Comment by jlerbsc** [comment]
It is indeed a better solution
