### ISSUE TITLE
SwitchEntry.isEmpty() returns false if it only contains `break;`

### ISSUE THREAD

**Issue by sergekukharev** [javaparser/javaparser#3450]
A test to reproduce:
```java
    @Test
    void switchEntryShouldBeEmpty() {
        var code = "switch(5) { case 1: break; }";

        var switchStmt = StaticJavaParser.parseStatement(code);

        switchStmt.findFirst(SwitchEntry.class).ifPresent(entry -> assertTrue(entry.isEmpty()));
    }
```

From client perspective, `isEmpty()` should return `true` in case `SwitchEntry` only has break statement. Am I missing something? 

In case it is a real issue, it's because `SwitchEntry` doesn't have its own `isEmpty` and relies on default implementation provided by `NodeWithStatements`. The fix is relatively straightforward and I can prepare a PR.

**Comment by jlerbsc** [comment]
How do you differentiate an entry with a break statement from an entry without expression?

**Comment by sergekukharev** [comment]
A helper method like `hasBreakStatement()` just for the `SwitchEntry` class can help. I see your point, it's a tradeoff to make. 

To me, this behavior of `isEmpty()` was surprising [^1]. I think that users of the library should not need to look into method implementation to understand how it works. 

My use case for this behaviour - I want to write a tool that looks for **empty** code blocks and removes them. With current implementation I have to write something like this:
```java 
@Override
private SwitchEntry visit(SwitchEntry entry, Void arg) {
    if(entry.isEmpty() || (entry.getStatements().size == 1 && entry.getStatements().get(0) instanceof BreakStmt)) {
       return null;
    }
    
    return super(entry, arg);   
}
```

[^1]: https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by nimaje** [comment]
That isn't an empty code block and just removing `case c: break;` can change behavior, consider:
```java
switch (i) {
     case 1:
        break;
     default:
        throw IllegalArgumentException();
}
```
another case to consider is:
```java
switch (i) {
    case 2:
        doStuff();
     case 1:
        break;
     case 3:
        doOtherStuff();
}
```
where the `case 1:` part is unneeded, but you can't just throw away the `break;`

So I would say having `.isEmpty()` return `true` when there is a `break` would be more surprising.

**Comment by sergekukharev** [comment]
Yes, you are absolutely right. Didn't think about it this way.
