### ISSUE TITLE
The third-party jar package problem encountered by javaparser parsing

### ISSUE THREAD

**Issue by zhenghanshu27** [javaparser/javaparser#3452]
Now I use javaparser to parse my project and need to manually import third-party dependency packages. Now I want to do automated analysis, so how can I ignore the third-party dependency packages and directly parse my business code?

**Comment by jlerbsc** [comment]
Your question is very general, it is difficult to answer you in a few sentences. Maybe you can start by reading this book https://leanpub.com/javaparservisited

**Comment by zhizhixiongxuwei** [comment]
> Now I use javaparser to parse my project and need to manually import third-party dependency packages. Now I want to do automated analysis, so how can I ignore the third-party dependency packages and directly parse my business code?
Use SymbolStrategy

**Comment by jlerbsc** [comment]
What is your question?
