### ISSUE TITLE
Parsing problem for helping

### ISSUE THREAD

**Issue by YujiaoWu-111** [javaparser/javaparser#3455]
When I am parsing the following file：
```
public static boolean isTypeIncludedIn(TypeName value, Type... types) {
        for (Type item : types) {
            if (value.equals(typeName(item))) {
                return true;
            }
        }
        return false;
    }
```
it prompts:
Found "boolean", expected one of  ";" "@" "class" "enum" "interface" "module" "open" "record" (line 1,col 8).

**Comment by YujiaoWu-111** [comment]
Can I parse only a java method, not a class？

**Comment by jlerbsc** [comment]
Hi @YujiaoWu-111 you can use the method parseBodyDeclaration defined in the parser.

**Comment by YujiaoWu-111** [comment]
Thanks a lot!

> Hi @YujiaoWu-111 you can use the method parseBodyDeclaration defined in the parser.

**Comment by YujiaoWu-111** [comment]
Hi,I have another question. Sorry to bother you again, but this problem has been puzzling me for several days. The Original code is as follows:
```
ParserConfiguration parserConfiguration = new ParserConfiguration();
JavaParser parser = new JavaParser(parserConfiguration);
ParseResult<CompilationUnit> result = parser.parse(file);
for (TypeDeclaration<?> type : result.getTypes()) {
        // handle each type. all declaration in this type will be added by the scope manager along
        // the way
        getDeclarationHandler().handle(type);
      }
```
If I use the method **parseBodyDeclaration** , the type of return value is _ParseResult<BodyDeclaration<?>>_ 
`ParseResult<BodyDeclaration> result1=parser.parseBodyDeclaration(code);`
which is different from the method **parse**. 

If I want to use the information from **CompilationUnit**, for example **TypeDeclaration**, what should I do?
@jlerbsc

**Comment by jlerbsc** [comment]
Hi @YujiaoWu-111 your first question was about how to parse the content of a method... It's not the same as parsing the content of a file or a class. If you want to browse the AST of a class you absolutely have to parse the class (or the file). Your initial question lacked context for me to be able to answer it in a meaningful way.

**Comment by YujiaoWu-111** [comment]
Thanks for your reply. I'm using another tool which calls a method in JavaParser to parse a Java file. If a class is parsed, there is no problem, but if a method is parsed, it will prompt:
![image](https://user-images.githubusercontent.com/75311554/148046544-f259af61-a9db-44c7-ae6c-e1ddabc045fd.png)
But It is a bit difficult for me to describe the specific information of that tool, so I will not consider parsing a method for the time being. Thank you again.

**Comment by jlerbsc** [comment]
The most productive solution would be to question the support of the other tool you mentioned to find out what this other tool offers you.
