### ISSUE TITLE
Typos in latest release version? 2.24.0 vs 3.24.0

### ISSUE THREAD

**Issue by msridhar** [javaparser/javaparser#3466]
I think there may be a typo in some places for the just-released version of Javaparser.  I think it should be version 3.24.0 (to follow previous release 3.23.1), but I see 2.24.0 some places, e.g.:

https://github.com/javaparser/javaparser/releases/tag/javaparser-parent-2.24.0
https://github.com/javaparser/javaparser/commit/44efb34cfa8fbe988b4400313f416b764fe92608

Not sure if this was intentional or not.  FYI @MysterAitch

**Comment by MysterAitch** [comment]
Doh! You are entirely correct - my mistake :cry: 

Let's try that again...

**Comment by MysterAitch** [comment]
So... I can confirm that I definitely did make a typo in the release and the release labelled as 2.24.0 have been uploaded to maven central ([and cannot be removed/altered](https://central.sonatype.org/faq/can-i-change-a-component/)).

I do note that [the files for 3.24.0](https://repo.maven.apache.org/maven2/com/github/javaparser/javaparser-core/3.24.0/) have been uploaded to Maven Central in record time(!) and are already available for use though!

Thank you for noticing the error @msridhar and raising it as a concern so quickly :heart:

**Comment by MysterAitch** [comment]
_Sidenote: See these screenshots that show the updated commit happened at 19:53 (to be uploaded and promoted via OSSRH a few mins later), and the files were then publicly available for use via maven central at 19:59 -- normally it takes an hour or two, not a few minutes(!)_

![image](https://user-images.githubusercontent.com/1537214/148700495-6dc7f785-9a0c-41e4-8c27-c24248dec40e.png)

![image](https://user-images.githubusercontent.com/1537214/148699601-5e526399-d5c1-4c41-9a42-6ceb8103cd9d.png)
![image](https://user-images.githubusercontent.com/1537214/148699636-1ad1685f-a108-4718-91c4-9c636c39e29b.png)

**Comment by msridhar** [comment]
Thanks for the very quick fix!
