### ISSUE TITLE
new ArrayCreationExpr(Type elementType) creates element with invalid syntax

### ISSUE THREAD

**Issue by sergekukharev** [javaparser/javaparser#3467]
A test to reproduce:
```java
@Test
void invalidSyntaxCreatedWhenUsingConstructorWithOnlyTypeProvided() {
    var expr = new ArrayCreationExpr(PrimitiveType.byteType());

    assertEquals("new byte[]", expr.toString());
}
```

Additionally, this expression resolved type is wrong. It resolves to the `ResolvedPrimitiveType`, rather to `ResolvedArrayType`:
```java
    @Test
    void resolvesToTypeUsedInArrayNotArrayType() {
        var expr = new ArrayCreationExpr(PrimitiveType.byteType());
        insertIntoCompilationUnit(expr); // My custom method

        assertInstanceOf(ResolvedArrayType.class, expr.calculateResolvedType());
    }
```

The actual output of `expr.toString()` is `new byte {}` which is an invalid array definition. I think I can prepare a PR with a fix, but I need guidance as this is a BC-breaking change.

**Comment by jlerbsc** [comment]
Hi @sergekukharev probably an error in the constructor of the class ArrayCreationExpr 

> ArrayCreationExpr expr = new ArrayCreationExpr(PrimitiveType.byteType(), new NodeList<>(new ArrayCreationLevel()), new ArrayInitializerExpr());

new byte[] {}

**Comment by sergekukharev** [comment]
I'll try to create a PR for it.
