### ISSUE TITLE
Write some JavaDoc for each Node type

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#347]
Just a simple one-liner that says what syntax maps to this node type and a link to the [JLS](https://docs.oracle.com/javase/specs/jls/se8/html/index.html)

**Comment by gs0510** [comment]
Hi! I'd be able to do this. Can you please assign me to this issue. Thanks!

**Comment by matozoid** [comment]
@gs0510 that would be great! You've got an invite.

**Comment by gs0510** [comment]
@matozoid  I can see the javadoc for Node types [here](http://static.javadoc.io/com.github.javaparser/javaparser-core/3.0.0-alpha.2/com/github/javaparser/ast/nodeTypes/package-summary.html). How do I get edit access to this doc. Also, I see a class JavaDocComment and NodeWithJavaDoc, am I supposed to use this class for setting the comment for the JavaDoc? Thanks!

**Comment by matozoid** [comment]
@gs0510 - the task is to take all sub-classes of "Node" and document them. This is done by writing javadoc, which is Java's way of documenting source code. So we want to describe what syntax each node represents and where that is described in the [Java Language Specification](https://docs.oracle.com/javase/specs/jls/se8/html/index.html). This requires detailed knowledge of the Java programming language. Since "how do I write JavaDoc" is basic knowledge, I have to ask if you are aware of the size of this task?

**Comment by matozoid** [comment]
Hmmm, you seem to have some compiler writing experience. Have a go at it then:
https://docs.oracle.com/javase/specs/jls/se8/html/index.html
http://www.oracle.com/technetwork/articles/java/index-137868.html

**Comment by matozoid** [comment]
@gs0510 - how is it going?

**Comment by matozoid** [comment]
Assuming @gs0510 is not doing the job.
