### ISSUE TITLE
Get declaring class of a method in Javaparser

### ISSUE THREAD

**Issue by harshita19244** [javaparser/javaparser#3478]
For instance, I have the following comment obtained from the Glide project. I want to extract all the methods in a file which belong to the VolleyStreamFetcher class. I do not want methods of a public static class. Since there is no way to obtain declaring class of the method, is it possible to obtain such methods using Javaparser? Any help would be appreciated. 

package com.bumptech.glide.integration.volley;

import android.util.Log;
import androidx.annotation.NonNull;
import com.android.volley.NetworkResponse;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.Request.Priority;
import com.android.volley.Response.ErrorListener;
import com.android.volley.toolbox.HttpHeaderParser;
import com.bumptech.glide.load.DataSource;
import com.bumptech.glide.load.data.DataFetcher;
import com.bumptech.glide.load.data.DataFetcher.DataCallback;
import com.bumptech.glide.load.model.GlideUrl;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.Collections;
import java.util.Map;

public class VolleyStreamFetcher implements DataFetcher<InputStream> {
    private static final String TAG = "VolleyStreamFetcher";
    public static final VolleyRequestFactory DEFAULT_REQUEST_FACTORY = new VolleyRequestFactory() {
        public Request<byte[]> create(String url, DataCallback<? super InputStream> callback, Priority priority, Map<String, String> headers) {
            return new VolleyStreamFetcher.GlideRequest(url, callback, priority, headers);
        }
    };
    private final RequestQueue requestQueue;
    private final VolleyRequestFactory requestFactory;
    private final GlideUrl url;
    private volatile Request<byte[]> request;

    public VolleyStreamFetcher(RequestQueue requestQueue, GlideUrl url) {
        this(requestQueue, url, DEFAULT_REQUEST_FACTORY);
    }

    public VolleyStreamFetcher(RequestQueue requestQueue, GlideUrl url, VolleyRequestFactory requestFactory) {
        this.requestQueue = requestQueue;
        this.url = url;
        this.requestFactory = requestFactory;
    }

    public void loadData(@NonNull com.bumptech.glide.Priority priority, @NonNull DataCallback<? super InputStream> callback) {
        this.request = this.requestFactory.create(this.url.toStringUrl(), callback, glideToVolleyPriority(priority), this.url.getHeaders());
        this.requestQueue.add(this.request);
    }
    @NonNull
    public Class<InputStream> getDataClass() {
        return InputStream.class;
    }

    @NonNull
    public DataSource getDataSource() {
        return DataSource.REMOTE;
    }

    private static Priority glideToVolleyPriority(@NonNull com.bumptech.glide.Priority priority) {
        switch(priority) {
        case LOW:
            return Priority.LOW;
        case HIGH:
            return Priority.HIGH;
        case IMMEDIATE:
            return Priority.IMMEDIATE;
        default:
            return Priority.NORMAL;
        }
    }

    public static class GlideRequest extends Request<byte[]> {
        private final DataCallback<? super InputStream> callback;
        private final Priority priority;
        private final Map<String, String> headers;

        public GlideRequest(String url, DataCallback<? super InputStream> callback, Priority priority) {
            this(url, callback, priority, Collections.emptyMap());
        }

        public GlideRequest(String url, DataCallback<? super InputStream> callback, Priority priority, Map<String, String> headers) {
            super(0, url, (ErrorListener)null);
            this.callback = callback;
            this.priority = priority;
            this.headers = headers;
        }

        public Map<String, String> getHeaders() {
            return this.headers;
        }

        public Priority getPriority() {
            return this.priority;
        }

        protected VolleyError parseNetworkError(VolleyError volleyError) {
            if (Log.isLoggable("VolleyStreamFetcher", 3)) {
                Log.d("VolleyStreamFetcher", "Volley failed to retrieve response", volleyError);
            }

            if (!this.isCanceled()) {
                this.callback.onLoadFailed(volleyError);
            }

            return super.parseNetworkError(volleyError);
        }

        protected Response<byte[]> parseNetworkResponse(NetworkResponse response) {
            if (!this.isCanceled()) {
                this.callback.onDataReady(new ByteArrayInputStream(response.data));
            }

            return Response.success(response.data, HttpHeaderParser.parseCacheHeaders(response));
        }

        protected void deliverResponse(byte[] response) {
        }
    }
}

**Comment by jlerbsc** [comment]
Can you read the book https://leanpub.com/javaparservisited then you can use the findAll method on the CompilationUnit with an argument like MethodDeclaration class.

**Comment by harshita19244** [comment]
Thank you, will take a look
