### ISSUE TITLE
Some design mistakes

### ISSUE THREAD

**Issue by ZeroAicy** [javaparser/javaparser#3486]
1.
The parameter type of getFunctionalMethod method of FunctionalInterfaceLogic class is not necessarily ResolvedReferenceType, may also be other ResolvedType, such as ResolvedArrayType.

2.The parent node of lambdaexpr can be objectcreationexpr. Typeextractor class does not support
3.Methodreferenceexpr does not support class:: new calculation type

**Comment by ZeroAicy** [comment]
4.The repair method of typeextractor class should consider the case that the POS is greater than or equal to getnumberofparams when the method is a variable parameter

**Comment by ZeroAicy** [comment]
5.Typeextractor class does not consider lambdaexpr wrapped by enclosedexpr.
The parameter args of the solvearguments method of the javaparserface class is not considered to have enclosedexpr.

**Comment by matozoid** [comment]
Can you split this into five separate issues?

**Comment by jlerbsc** [comment]
Can you also give us for each case a unit test that illustrates the problem?

**Comment by matozoid** [comment]
I did the splitting, so I'll close this one. See you in the other issues!
