### ISSUE TITLE
SourceRoot.tryToParse() fails if the root path ends with a directory that is not a java identifier

### ISSUE THREAD

**Issue by stumpedatwork** [javaparser/javaparser#3489]
Hey, just a heads up

`new SourceRoot("tests/01").tryToParse()` causes `isSensibleDirectoryToEnter()` to skip the subtree and return zero `CompilationUnit`.

Thank you for being such awesome coders and people!

**Comment by jlerbsc** [comment]
What does "tests/01" represent? is this the name of a package?
