### ISSUE TITLE
Support Java 9

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#349]
Any changes to the syntax? I've spotted one: 
- [ ] _ is now a keyword.

**Comment by ftomassetti** [comment]
Was that a reserved word before? If not we could have to support different dialects

**Comment by matozoid** [comment]
It was just an identifier before. I can't think of a pretty way to support different dialects that would not cause a huge amount of work, you?

**Comment by matozoid** [comment]
- [ ] Make javaparser-core a Jigsaw module.

**Comment by matozoid** [comment]
- [ ] support module-info.java files. These contain a new mini-language.

**Comment by matozoid** [comment]
I'll split this into separate issues with their own tag.
