### ISSUE TITLE
Thread-Safety of LexicalPreservingPrinter

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3490]
I consider the use of LexicalPreservingPrinter. The javadoc states:

> Prepares the node so it can be used in the print methods. The correct order is:
> 
> Parse some code
> Call this setup method on the result
> Make changes to the AST as desired
Use one of the print methods on this class to print out the original source code with your changes added

Walking in the implementation, I understand some state is persisted into each considered node. If this class is indeed thread-safe, could this be stated explicitly in the documentation? (I initially supposed it was not the case, and some state was stored into a LexicalPreservingPrinter static field).

Thanks

**Comment by matozoid** [comment]
I would not assume that any part of JP is thread safe. There is mutable state all over the place, and nowhere has concurrency been taken into consideration.

**Comment by blacelle** [comment]
My usage of JP is quite concurrent (i.e. per CompilationUnit), but I certainly do not go through most of the code. I encountered an issue described in https://github.com/javaparser/javaparser/issues/3050 (workarounded with a slightly more specific API usage). Out of this, I did not observe any thread-safety issue.

While general thread-safety might be very difficult to achieve, I feel reasonnable to expect thread-safety as long as each CompilationUnit is processed in a mono-threaded way (i.e. multiple threads can process CompilationUnit in parallel, but a single CompilationUnit should be processed exclusively by a unique thread).

Without strong guarantee, does it sound a reasonnable usage?

**Comment by matozoid** [comment]
Making sure only a single thread accesses a compilation unit at any time should work fine. (I guess, as you found, that using a new JavaParser instance with a new instance of configuration works better than the StaticJavaParser :-) ) I haven't worked on JP for a while, so I can only make a blanket statement: the code that accesses the state of multiple compilation units at once is the symbol solver. If you use that one, best access all of the source code from a single thread at a time only.

**Comment by blacelle** [comment]
Thanks
