### ISSUE TITLE
Method has a multidimensional arrays argument in jar file. when call the method throw UnsolvedSymbolException

### ISSUE THREAD

**Issue by qingmuAdore** [javaparser/javaparser#3491]
jar file has a class。the code for example:
```
public class AlarmInfo{
    public void setStrExtParam(String[][] strExtParam) {
         //....
    }
}
```
My simple code:
```
public class App {
    public static void main(String[] args) {
        AlarmInfo alarmInfo = new AlarmInfo();
        String[][] strAppendInfo = new String[3][3];
        //...
        alarmInfo.setStrExtParam(strAppendInfo);
    }
}
```
the stmt: alarmInfo.setStrExtParam(strAppendInfo). When I can the MethodCallExpr.resolve() , throw exception:
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to alarmInfo.setStrExtParam(strAppendInfo)', cause='null'}

**Comment by jlerbsc** [comment]
Hi @qingmuAdore how did you initialize the symbol solver?

**Comment by qingmuAdore** [comment]
Hi @jlerbsc Thanks for reply. my symbolsolver like：

CombinedTypeSolver typeSolver = new CombinedTypeSolver();
typeSolver.add(new ReflectionTypeSolver(false));
typeSolver.add(new JarTypeSolver(#{myJarFile}));
typeSolver.add(new JavaParserTypeSolver(#{mySourcePath}));
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

I use visitor to parser。

MY CODE:
```
public static void parse(String sourcePath) {
    try {
        Files.walk(new File(sourcePath).toPath())
            .filter(Files::isRegularFile)
            .filter(
                p -> p.toFile().getName().endsWith(".java") && !p.toFile().getName().endsWith("package-info.java"))
            .forEach(path -> {
                try {
                    AstVisitor visitor = new AstVisitor();
                    AstTag tag = new AstTag();
                    visitor.visit(StaticJavaParser.parse(path), tag );
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```
```
public class AstVisitor extends VoidVisitorAdapter <AstTag>  {

    @Override
    public void visit(MethodCallExpr expr, AstTag arg) {
        super.visit(expr, arg);
       
       // UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to alarmInfo.setStrExtParam(strAppendInfo)', cause='null'} 
        ResolvedMethodDeclaration resolve = n.resolve(); 

        String callee = resolve.getQualifiedSignature();
        //...
    }
}
```

**Comment by jlerbsc** [comment]
What is the value of #{mySourcePath}

**Comment by jlerbsc** [comment]
This simplified test case works fine.

    @Test
    public void test3491() {
        String code = "public class AlarmInfo{\n"
                + "        public void setStrExtParam(String[][] strExtParam) {\n"
                + "             //....\n"
                + "        }\n"
                + "    }\n"
                + "public class App {\n"
                + "    public static void main(String[] args) {\n"
                + "        AlarmInfo alarmInfo = new AlarmInfo();\n"
                + "        String[][] strAppendInfo = new String[3][3];\n"
                + "        //...\n"
                + "        alarmInfo.setStrExtParam(strAppendInfo);\n"
                + "    }\n"
                + "}";
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(code);
        List<MethodCallExpr> exprs = cu.findAll(MethodCallExpr.class);
        exprs.forEach(expr -> System.out.println(expr.resolve().getQualifiedSignature()));
     }

**Comment by qingmuAdore** [comment]
@jlerbsc Yeah In this case, It work fine. But, there's a problem, when the class is in jar file.

**Comment by jlerbsc** [comment]
This bug is caused by a problem between JavaParser and Javassist.
In JP parameter type like String[][] is considered as a ResolvedArrayType{ResolvedArrayType{ReferenceType}}
In Javassist this type is considered as a ResolvedArrayType{ReferenceType}
I don't know how to resolve this case from the moment. @matozoid @MysterAitch some help would be appreciated.
