### ISSUE TITLE
Inaccuracy with isBlockComment()

### ISSUE THREAD

**Issue by shaifulcse** [javaparser/javaparser#3495]
It failed to recognise the following block comment. If I delete one of the stars from the first line, then it works successfully. 

```
/**
* When used with https://github.com/remy/polyfills/blob/master/EventSource.js , we
* resume after every message.
*/

```
I have used the following version:

        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
            <version>3.6.25</version>
        </dependency>

**Comment by jlerbsc** [comment]
Hi @shaifulcse The implementation conforms to the BlockComment javadoc.

> AST node that represent block comments.
Block comments can has multi lines and are delimited by "/\*" and "\*/".

**Comment by shaifulcse** [comment]
Thank you. My bad. I thought Javadoc comments are generally written above the class.
