### ISSUE TITLE
Constructor descriptor

### ISSUE THREAD

**Issue by kanghj** [javaparser/javaparser#3498]
Similar to https://github.com/javaparser/javaparser/issues/2059, is there a way to obtain the descriptor of the constructor?  

I noticed that com.github.javaparser.ast.body.ConstructorDeclaration lacks a `toDescriptor` method.

**Comment by jlerbsc** [comment]
Hi @kanghj You cannot obtain the descriptor of a constructor. It's not implemented. Probably because we cannot find an explicit  reference to that in the JLS.

**Comment by kanghj** [comment]
> we cannot find an explicit reference to that in the JLS

Ah, I see. Indeed, the JLS doesn't say anything about it. 
ASM seems to have an implementation of the constructor descriptor (https://github.com/consulo/objectweb-asm/blob/master/asm/src/main/java/org/objectweb/asm/Type.java), although I do not know what its implementation is based of.

Would it be appreciated if I made a pull request adding the `toDescriptor` method (similar to ASM's) for a constructor? I can try to write it over this weekend or the next.

**Comment by jlerbsc** [comment]
Ok. You can do it. Thanks.
