### ISSUE TITLE
GPG key for publishing changed

### ISSUE THREAD

**Issue by octylFractal** [javaparser/javaparser#3516]
Hi, I was updating Groovy to 3.0.10 and it pulled in the new 3.24.0 release of javaparser, which led me to discover that the key used to publish 3.24.0 (and 3.23.1) is different from the one used to publish 3.23.0. Can you explain this change?

The keys specifically are 431B8F80403A7DC1 for 3.23.0 and 249DEE8E2C07A0A2 for 3.23.1/3.24.0.

**Comment by matozoid** [comment]
@MysterAitch should know. He took over releasing, and was working on automating the release process.

**Comment by ice1000** [comment]
> @MysterAitch should know.

Is he still active?

**Comment by jlerbsc** [comment]
Are you talking about the key used to sign the library?

**Comment by octylFractal** [comment]
Yes, the one used in Maven Central for the `.asc` files.

**Comment by jlerbsc** [comment]
This makes sense for me because the library is built locally with a gpg key specific to the workstation the library is built on.

**Comment by ice1000** [comment]
That means it's the developers who changed a workstation to build the library? Not some hackers?

I think the OP intended to make sure if it's published by hackers or not ;)

**Comment by ice1000** [comment]
See, e.g. https://github.com/gradle/gradle/pull/20177#issuecomment-1068425300

**Comment by jlerbsc** [comment]
Recently I also had to configure gpg locally to build a new release. Currently the procedure used in the javaparser project is based on a local configuration. So no it's not a hacker who built this version of javaparser :-)

**Comment by MysterAitch** [comment]
It is slightly surprising, albeit reassuring(!), that the signatures are being checked by somebody - thank you @octylFractal  :smiley: 

I can confirm that the 3.23.1/3.24.0 releases (and the mistakenly numbered 2.24.0 release per changelog notes) were published by me with that GPG key. 

The change occurred when I moved from performing releases from within a VM I no longer have access to, to a different machine with a newly generated GPG key.

As @matozoid and @jlerbsc mention, the signing key may change again in the near future as we explore how the releases are produced, but we can take it as an action to consciously include a mention of this within the changelog or similar to provide some (re)assurance/traceability here :+1:

**Comment by octylFractal** [comment]
Okay, thank you!
