### ISSUE TITLE
Issue with JavaParserTypeSolver's SrcDir as argument

### ISSUE THREAD

**Issue by saketh2341** [javaparser/javaparser#3518]
I am using JavaParserTypeSolver and providing it String SrcDir as argument. When I am providing it the location of my project + "src/main/java" then it is working fine. Whereas when I am providing it only location of my project then I am receiving UnsolvedSymbolException.
		// In my case I am using JavaParserTypeSolver to parse different user repositories and there is no guarantee that everytime there will be a path like "location of project/src/main/java". Is there any alternate way of using JavaParserTypeSolver?

**Comment by jlerbsc** [comment]
This page describes another solution https://javaparser.org/setting-up-for-analysing-a-whole-project/
