### ISSUE TITLE
Release 3.24.1 not on Maven central

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#3520]

**Comment by jlerbsc** [comment]
Yes indeed it is an error you can use version 3.24.0

**Comment by daniellansun** [comment]
3.24.2 can not be found on Maven central either:
https://search.maven.org/search?q=g:com.github.javaparser%20AND%20a:javaparser-core

@jlerbsc Could you take a look? Thanks in advance!

**Comment by jlerbsc** [comment]
The version 3.24.1 has not been released on maven. 
For the version 3.24.2 you have to allow some time for the central maven site to be refreshed
