### ISSUE TITLE
Fields used within a method

### ISSUE THREAD

**Issue by minaschar** [javaparser/javaparser#3528]
Good Evening! I'm new to the library, but I'm very interested in learning more about it! My question is this... I would like to see which of the fields stated in the class, a method uses. I have found a way to get the fields of a class. But how could I get which of these fields the method uses? Is there any methodology we follow in such cases? Thank you very much!

**Comment by jlerbsc** [comment]
Hi @ics20072 You have to use JavaSymbolSolver to get the declaration of a field or a parameter. First You could read this book to learn how to use JavaParser
https://leanpub.com/javaparservisited

**Comment by minaschar** [comment]
Thank you very much for your answer!
