### ISSUE TITLE
Generate visitors from the AST classes

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#353]
Instead of manually patching the visitors every time we make some changes (and regularly forgetting to...) we should generate the visitors from code.

Work in progress over here, where I use @ftomassetti 's symbol solver to build the AST model, then use my own code generator to generate the visitors: https://github.com/matozoid/javaparser/tree/generate-visitors

**Comment by matozoid** [comment]
Will fix #220

**Comment by matozoid** [comment]
Might fix #236

**Comment by matozoid** [comment]
Will prevent #252 from happening again

**Comment by matozoid** [comment]
After some request for specific visitors, it seems like a good idea to make this a public tool.

A user might specify:
- the visitor's class name
- the visitor's argument that is passed into every method
- if it's a void visitor
- if it's not a void visitor, what the return type is
- what happens to the visitor before generating the methods (adding custom methods)
- what happens to the visitor after generating the methods (who knows?)

then a callback gets called for every node type, with
- the node class
- the names and type of the fields of this node
- the setters and getters for the fields of this node
- the visit method body, for the user to fill
- a map with information about all node types in case the user needs it

This will generate a CompilationUnit that can be written to disk and compiled.

**Comment by matozoid** [comment]
Also, since we're getting more and more repetitive code in the nodes, we could generate parts of those classes. Maybe with annotations, like:
@GenerateDefaultConstructor

@GenerateProperty(nullable, ...)

So the generator can read from the javaparser-core source directory, find all annotated methods, replace them and write them back.

**Comment by ftomassetti** [comment]
I am really looking forward to this one!

> After some request for specific visitors, it seems like a good idea to make this a public tool.

Were you thinking about having it as a class in JavaParser or as the third project under the JavaParser umbrella?

**Comment by matozoid** [comment]
Okay, @DeepSnowNeeL is actually working on this but I'll give you my personal thoughts: something that generates part of JavaParser seems good to have away from the source of JavaParser. I was thinking of a separate module so that at some time in the future a single build will build the generator, generate the visitors and other code, build the parser, and build the core.

**Comment by matozoid** [comment]
Here we go again: https://github.com/matozoid/javaparser/commits/issue_353_generate_visitors

**Comment by ftomassetti** [comment]
But if you use it JavaSymbolSolver does it mean you would java JavaParser depending on JavaSymbolSolver? Or would this be a separate module/project?

**Comment by matozoid** [comment]
This time I'm not using JSS.

**Comment by matozoid** [comment]
Look at JavaParserModel, NodeModel and FieldModel (which are far from complete, mind!)

**Comment by ftomassetti** [comment]
problem solved :D

**Comment by matozoid** [comment]
I'll close this since most of the base visitors are generated now, and add issues for specific visitors.
