### ISSUE TITLE
Unexpected behavior when parsing method parameters

### ISSUE THREAD

**Issue by taijidude** [javaparser/javaparser#3536]
Hello, new user here. I'm trying to write a unit test where i parse the following code: 

```java
 @Test
  public void genericMethodTest() {
    toParse = "class testc { public <T> void testm(Car test, Car test1) {} }";
    cu = StaticJavaParser.parse(toParse);
    converter = new FQNToImportConverter();
    converter.visit(cu, null);
    assertEquals("import Car;\n", converter.getImportStatements());
    String toCheck = cu.toString().replaceAll("\n", " ").replaceAll("\r", "").trim();
    assertEquals(toParse, toCheck);
  }
```

The class FQNToImportConverter  extends ModifierVisitor<Void>.  

```java
public class FQNToImportConverter extends ModifierVisitor<Void> {

  @Override
  public MethodDeclaration visit(MethodDeclaration it, Void p_arg) {
    super.visit(it, p_arg);
    NodeList<Parameter> l_parameters = it.getParameters();

    return it;
  }
}
```

When i debug into the method and lookup the contens of l_parameters i get: [Car Car, Car Car]

Is this a bug? Or am i using the wrong? 

Edit: I get the same behavior when trying to parse Constructor Parameters.

**Comment by jlerbsc** [comment]
Hi @taijidude with the current version i get 

> [Car test, Car test1]

Where is the issue?

**Comment by taijidude** [comment]
I looked it up and saw that my test project was using an older version. I will upgrade, try again and report back.

**Comment by taijidude** [comment]
Still have the same problem. Even with version 3.24.2.

**Comment by jlerbsc** [comment]
I'm using this test code without issue.

    @Test
      public void genericMethodTest() {
        String toParse = "class testc { public <T> void testm(Car test, Car test1) {} }";
        CompilationUnit cu = StaticJavaParser.parse(toParse);
        ModifierVisitor<Void> visitor = new ModifierVisitor<Void>() {
          @Override
          public MethodDeclaration visit(MethodDeclaration it, Void p_arg) {
            super.visit(it, p_arg);
            NodeList<Parameter> l_parameters = it.getParameters();
            return it;
          }
        };
        visitor.visit(cu, null);
    }

**Comment by taijidude** [comment]
ok, will setup a minimal project and try to replicate.

**Comment by taijidude** [comment]
Okay, got it work with your minimal example and also figured out how i shot myself in the foot. My Class which extended the visitor is longer and i didn't see a half implemented visit method for parameters which was messing every thing up. Thanks for your help and your time.
