### ISSUE TITLE
Annotation with only a string value

### ISSUE THREAD

**Issue by DanielVerloop** [javaparser/javaparser#3538]
Hey,

I am trying to generate a Java gherkin test file with the help of JavaParser.
Gherkin test functions are annotated as follows:
```
@Given("a bank account with initial balance of 100")
public void aBankAccountWithInitialBalanceOf(int arg0) { ... }
```
I am trying to add this kind of annotation to a method using the CompilationUnit.
However, I can't seem to find a type of annotation that is able to generate `@annotation("stringvalue")` type of annotation.

Does anyone know if this can be achieved?

**Comment by matozoid** [comment]
Here is some general advice:
- parse some code that has the syntax you want (StaticJavaParser.parse....)
- inspect the AST you got for that code: https://javaparser.org/inspecting-an-ast/
- find the node that represents the syntax, and "new" them in your code.

**Comment by jlerbsc** [comment]
Hi @DanielVerloop in addition to the comment of @matozoid you have 3 annotation classes

. SingleMemberAnnotationExpr An annotation that has a single value. For exemple  @Count(15)
. NormalAnnotationExpr An annotation that has zero or more key-value pairs. For exemple  @Mapping(a=5, d=10)
. MarkerAnnotationExpr An annotation that uses only the annotation type name. For exemple @Override

**Comment by DanielVerloop** [comment]
Thanks for the tips!

I don't know if I have discovered a bug, or the behaviour is intended.

If I try to use `.addSingleMemberAnnotation(name, cleanDescr);` it gives me a `com.github.javaparser.ParseProblemException: Encountered unexpected token: "a" <IDENTIFIER>` .
However whenever I try `.addSingleMemberAnnotation(name, "somedescription");` it parses without any problems.

Edit: it seems the a `StringLiteralExpression` type is expected, my bad!

**Comment by matozoid** [comment]
Looks like the user experience could be better here :-)
