### ISSUE TITLE
Is there is a way to find method calls inside a java file?

### ISSUE THREAD

**Issue by mahtagh** [javaparser/javaparser#3540]
Hi, 

I am looking for a way to see if a method is used in a java file or not. So Is there any way to find methods that are used in a java file?

Thank you,
Mahta

**Comment by mahtagh** [comment]
Also, it gets the type of each argument for each method

**Comment by jlerbsc** [comment]
Hi @mahtagh These questions are often asked, have you tried to read the various articles or the book on the use of JavaParser?

https://javaparser.org/getting-started.html

**Comment by mahtagh** [comment]
> Hi @mahtagh These questions are often asked, have you tried to read the various articles or the book on the use of JavaParser?
> 
> https://javaparser.org/getting-started.html

Thank you for your response.

**Comment by mahtagh** [comment]
> Hi @mahtagh These questions are often asked, have you tried to read the various articles or the book on the use of JavaParser?
> 
> https://javaparser.org/getting-started.html

Hi, Thank you for your response. Yes, I read the book and find a way to collect called methods inside a java code.
This is the code maybe it helps someone:

	private static class MethodCallVisitor extends VoidVisitorAdapter<ArrayList<String>> {
		@Override
		public void visit(MethodCallExpr n, ArrayList<String> arg) {
			// Found a method call
			
				System.out.println("no argument " + n.getScope() + " - " + n.getName());
				System.out.println(""+ n.getName());
				arg.add(n.getName().toString());
			
				String argu = "( ";
				for (int i = 0; i < n.getArguments().size(); i++) {
					System.out.println(" argument " + n.getScope() + " - " + n.getName() + " - "
							+ n.getArguments().get(i).getClass().getName() + " -- " + n.getArguments().get(i).toString());
				}
				
			super.visit(n, arg);

		}
	}

	public static class ClassNameCollector extends VoidVisitorAdapter<ArrayList<String>> {
		@Override
		public void visit(ClassOrInterfaceDeclaration n, ArrayList<String> collector) {
			super.visit(n, collector);

			for (MethodDeclaration method : n.getMethods()) {
				// Make the visitor go through everything inside the method.
				ArrayList<String> mds = new ArrayList<String>();
				method.accept(new MethodCallVisitor(), mds);
				collector.addAll(mds);
			}
			
		}
	}


- And in the main

CompilationUnit cu;
cu = StaticJavaParser.parse(new File(path));
ArrayList<String> className = new ArrayList<String>();
VoidVisitor<ArrayList<String>> classNameVisitor = new ClassNameCollector();
// Visit.
classNameVisitor.visit(cu, className);
