### ISSUE TITLE
Add breadth first travel to the TreeVisitor

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#355]
And add bdd tests for the class.

**Comment by zero33542** [comment]
Hello, I am now adding breadth first travel and I want to ask how do I add bdd tests?

**Comment by matozoid** [comment]
Thank you for helping!

The bdd tests are in the javaparser-testing module, they use http://jbehave.org/ . They are quite useful for testing parsing+dumping. If you don't think it is a good match, make a junit test.
