### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [javaparser/javaparser#3553]
Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `javaparser-core-serialization\pom.xml`, `org.glassfish:javax.json` scope should be `compile`  instead of `test`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by jlerbsc** [comment]
It seems to me that the actual scope is correct because test classes have runtime dependencies with javax.json.

**Comment by matozoid** [comment]
Yes, the "main" code only uses the JSON API, not the glassfish implementation, and it shouldn't.

**Comment by hazendaz** [comment]
@jlerbsc This ticket should be closed.  The suggestion was wrong.  Its correct as it is.  Tested and confirmed for grins if the implementation was needed, it is and only in test scope as currently defined.
