### ISSUE TITLE
LexicalPreservingPrinter doesn't preserve VariableDeclaration changes

### ISSUE THREAD

**Issue by peterphan** [javaparser/javaparser#3554]
When using the LexicalPreservingPrinter, it is still using the old VariableDeclaration ast nodes for printing. When running `toString()` on the compilation unit, I do see my changes made.
See https://github.com/peterphan/refactor-with-javaparser/tree/master for more details and how to repro

**Comment by jlerbsc** [comment]
Have you tried to create a new ClassOrInterfaceType instead of renaming the type?

**Comment by peterphan** [comment]
Is this something I'm supposed to do? Creating a new type is just more complicated since I have to get the parent node and update the type. Either way this is a bug right?

**Comment by jlerbsc** [comment]
This is not necessarily a bug it works according to the current implementation. Maybe the use of the ClassOrInterfaceType.setName(SimpleName) (vs ClassOrInterfaceType.setName(Sttring)) can solve your issue.

**Comment by peterphan** [comment]
setName(string) simply calls setName(new SimpleName(string)).

The JavaParser pdf manual also uses `setName` to make changes. I don't see how having semantic differences between `toString()` and `LexicalPreservingPrinter.print` can not be considered a bug

**Comment by jlerbsc** [comment]
You are right it was a guess setName(SimpleName) is not the solution to your issue.
Lexicalpreserving printer algorithms are a little (if not very) complicated. It is based on the observer pattern which propagates events to the children of the modified node, which is why I suggested that you create a new type rather than modify an attribute.

This unit test works fine

> @Test
    void test3554() {
        String code = "class A{ Baz baz;}";
        CompilationUnit cu = StaticJavaParser.parse(code);
        LexicalPreservingPrinter.setup(cu);
        ClassOrInterfaceType type = cu.findFirst(ClassOrInterfaceType.class).get();
        ClassOrInterfaceType nType = new ClassOrInterfaceType("Foo");
        NodeWithType<VariableDeclarator, ClassOrInterfaceType> node = (NodeWithType)type.getParentNode().get();
        node.setType(nType);
        System.out.println(LexicalPreservingPrinter.print(cu));
    }

**Comment by jlerbsc** [comment]
I am closing this issue because this is not a bug it works according to the current implementation. Perhaps the documentation could be improved on this particular point.
