### ISSUE TITLE
Unable to "resolve" a "record declaration"

### ISSUE THREAD

**Issue by corradomio** [javaparser/javaparser#3556]
Javaparser v3.24.2

In this code, I try to ""resolve"" a class and a "record".
On the "class" there are no problems.
On the "record" it is raised a "UnsupportedOperationException". 

But this is not reasonable: a "record declaration" is just a "class declaration" PLUS a "constructor" using ""a little strange"" syntax.

```
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.RecordDeclaration;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class IssueHLS9 {
    public static void main(String[] args) {
        String code =
            "package a.b.c.d;\n" +
                "\n" +
                "class AClass {}\n" +
                "record ARecord (int fi) { }\n" +
                "";

        TypeSolver typeSolver = new CombinedTypeSolver(
            new ReflectionTypeSolver()
        );
        StaticJavaParser.getConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_17);
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(code);

        (new VoidVisitorAdapter<Void>() {
            @Override
            public void visit(ClassOrInterfaceDeclaration n, Void arg) {
                ResolvedReferenceTypeDeclaration rrtd;
                try {
                    rrtd = n.resolve();
                }
                catch (Throwable t) {
                    t.printStackTrace();
                }
            }

            @Override
            public void visit(RecordDeclaration n, Void arg) {
                ResolvedReferenceTypeDeclaration rrtd;
                try {
                    rrtd = n.resolve();
                }
                catch (Throwable t) {
                    t.printStackTrace();
                }
            }

        }).visit(cu, null);
    }
}

```

The exception is rainsed in "javaSymbolSolver.java/method resolveDeclaration()/line 276.
This is correct, obviously, because in the list of supported declarations it is missing "RecordDeclaration"

**Comment by jlerbsc** [comment]
it's not as trivial as it seems because the compiler generates a constructor and getters... It is certainly necessary to provide the possibility of resolving these implicit methods or at least to ask the question of how the project must manage records .

**Comment by corradomio** [comment]
I know, 
However a ""temporary minimum support"" to avoid the exception can be a "temporary good idea"
;-)

**Comment by MysterAitch** [comment]
ref #2446

**Comment by MysterAitch** [comment]
> ```java
>         TypeSolver typeSolver = new CombinedTypeSolver(
>             new ReflectionTypeSolver()
>         );
> ```

@corradomio -- I fear that the reflection type solver is trickier than most to complete because methods such as `.isRecord()` do not exist, therefore it would require JavaParser to be built and developed using >= JDK16 (currently releases are built using JDK8).

Point taken re: providing minimal support as an interim solution, however.

**Comment by matozoid** [comment]
Would a workaround be to use jar solvers for the JDK 17 jars instead of the reflectiontypesolver?

(JDK 8 is still the most used, sadly: https://www.jetbrains.com/lp/devecosystem-2021/java/ )

**Comment by potjerodekool** [comment]
Multi release jars could be used to support features like records for newer Java versions. 
https://baeldung-cn.com/maven-multi-release-jars

**Comment by klauswuestefeld** [comment]
+1

**Comment by jlerbsc** [comment]
I'm closing this issue because the record resolution is under development and will be delivered in the next version.
