### ISSUE TITLE
How to retrieve the signature of a method declaration in the original JVM format?

### ISSUE THREAD

**Issue by XinyuanYe** [javaparser/javaparser#3559]
Hi,

Can we use Javaparser to retrieve the JVM signature of a method declaration?

Thank you!

**Comment by MysterAitch** [comment]
@XinyuanYe -- could you give a short example please?

**Comment by XinyuanYe** [comment]
> @XinyuanYe -- could you give a short example please?

@MysterAitch Thanks for the reply!

For example, if I have a method declaration like below

`long myMethod (int n, String s, int[] arr);`

How can I obtain its JVM method signature like: `myMethod(ILJAVA/LANG/STRING;[I)J`? 
Can Javaparser retrieve this kind of signature? 

Thank you for your help!

**Comment by matozoid** [comment]
(I don't think there is, and I think there is a reason for that - but I forgot. Might have to do with not knowing the fully qualified names of classes in javaparser-core)

**Comment by jlerbsc** [comment]
I think MethodDeclaration.toDescriptor() can do it partially.

**Comment by XinyuanYe** [comment]
I see. Cool, thanks for all the help!
