### ISSUE TITLE
Ensure JavaParser can parse all the OpenJDK sources

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#357]
Create a simple stand alone tool to download and parse the OpenJDK sources.

If incompatabilities are found, open new issues.

**Comment by ftomassetti** [comment]
I think we did something similar in the past. I am not 100% it was the OpenJDK project that we used.

**Comment by matozoid** [comment]
Yes, I closed the other one since I didn't think anybody was going to pick it up anymore. If we had a little tool, we could just run it every now and then.

**Comment by matozoid** [comment]
Hmmm, I'm doing this now and some errors are popping up. Will create issues.

**Comment by ftomassetti** [comment]
I think at a certain point I tried to parse some source files from the OpenJDK which actually contained errors (they were used in tests, I guess to check the compiler recognized the errors) so I had a moment of desperation before realizing that

**Comment by matozoid** [comment]
Tool is there, errors have been put in the issue tracker. Done.
