### ISSUE TITLE
Maybe  JavaParser can't parse the character " :: "

### ISSUE THREAD

**Issue by Ying091909** [javaparser/javaparser#3571]
- When I used the JavaParser to parse the code  which contains the ``` List<Integer>```, it had something wrong as follows

> Exception in thread "main" japa.parser.ParseException: Encountered ""<" "<"" at line 39,column 49. was expecting one of: \
"(" ... 

   Then I upgrade the JavaParser 1.0.1 to 1.0.11.   And it works well !

>         <dependency>
>             <groupId>com.google.code.javaparser</groupId>
>             <artifactId>javaparser</artifactId>
>             <version>1.0.11</version>
>         </dependency>

- Unfortunately,  the similar  problem arose when parsing another file.

> Exception in thread "main" japa.parser.ParseException: Encountered " ":" ": "" at line 64, column 19.
Was expecting one of:
    "instanceof" ...
    "(" ...
    ";" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    ">" ...
    "<" ...

I added the dependency as follows, but it doesn't works at this time.

```
       <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
            <version>3.24.2</version>
        </dependency>
```

- The code snippet to parse

>   @Override
>   public Predicate<Capabilities> isApplicable() {
>     return FIREFOX::is;
>   }

- My problem
Does the version cause this problem and how can I resolve it?  Look forward to your help

**Comment by jlerbsc** [comment]
It's a very old version of JavaParser. The project was moved to com.github.javaparser. You only need to declare this.

    <dependency>
        <groupId>com.github.javaparser</groupId>
        <artifactId>javaparser-symbol-solver-core</artifactId>
        <version>${javaparser.version}</version>
    </dependency>

**Comment by LYZ1125** [comment]
> It's a very old version of JavaParser. The project was moved to com.github.javaparser. You only need to declare this.
> 
> ```
> <dependency>
>     <groupId>com.github.javaparser</groupId>
>     <artifactId>javaparser-symbol-solver-core</artifactId>
>     <version>${javaparser.version}</version>
> </dependency>
> ```

I think she has tried adding the latest version.....

**Comment by Ying091909** [comment]
I forgot to delete the  dependency of ```1.0.11```. The problem has been solved now! Thank you very much!
