### ISSUE TITLE
Set/Change file name when saving modified java code via saveAll()

### ISSUE THREAD

**Issue by NicolasHa00** [javaparser/javaparser#3572]
Hello, 
I hope this is the right location to ask this question (or propose this functionality in the case it doesn't exist already). I am quite new to JavaParser. 
Is there a way to change the name of the file/files which was modified with JavaParser when using the method saveAll( ) ? The file was parsed with a compilation unit and then modified with a ModifierVisitor. The plan is to write it in the output folder with a different file name as there might be other files with the same name that might be overwritten. Thanks!

 `  sourceRoot.saveAll(
                    CodeGenerationUtils.mavenModuleRoot(ReplacementAO.class).resolve(Paths.get("output")));`

**Comment by matozoid** [comment]
Right now, no. As you can see, SourceRoot stores all parsed files in a "cache" of path->parseresult, and simply uses those paths to write them out again.

After SourceRoot was invented, `Storage` was added to `CompilationUnit` which also contains this path. It is currently read-only, but making this writable, and adapting SourceRoot to use this path instead would help you.

**Comment by NicolasHa00** [comment]
@matozoid Thank you, good to know! Shouldn't this method below (from the CompilationUnit class) be sufficient to edit the Path in the storage? 
` public CompilationUnit setStorage(Path path) {
        this.storage = new Storage(this, path);
        return this;
    }`
However, I'm not sure how to adapt the SourceRoot to use a modified path instead of the original one, or does this need to happen directly here on the JavaParser Github? 
Thanks!

**Comment by matozoid** [comment]
Yes, setStorage would solve the first part. The rest, well, if you want to give it a try, see here: https://github.com/javaparser/javaparser/wiki/Eclipse-Project-Setup-Guide
