### ISSUE TITLE
Can I use Javaparser to calculate the metrics of the code

### ISSUE THREAD

**Issue by Sichengluis** [javaparser/javaparser#3578]
I want to use JavaParser to calculate the metrics of the method code, and now I use some visitors to achieve it, such as the number of parameters of the method, the number of method calls, etc.

But I also want to calculate the cyclomatic complexity of the method code, could anyone give me some advice？

**Comment by jlerbsc** [comment]
Maybe a cfg (Control flow graph) can help you achieve this functionality but for the moment JP does not allow to obtain a cfg. You have to build it yourself.

**Comment by jlerbsc** [comment]
I am closing this issue because there is no more activity on it but you are free to reopen it if you have other information.
