### ISSUE TITLE
Variable Lineage from Java Symbol Resolver 

### ISSUE THREAD

**Issue by bhatnagar444** [javaparser/javaparser#3579]
**Problem :** So Oracle seems to be quite expensive to some of the companies so they convert their databases from oracle to Postgres.
Now after the database is converted, the queries written inside the code might be in oracle JDBC or oracle hibernate so there the need will come to convert the code queries also into respective database queries.
From oracle JDBC or oracle hibernate queries to Postgres JDBC or Postgres hibernate queries.

**Goal :** We need to make a tool/plugin/java application so that it takes the client's projects/java files as input and remediates the queries.

**My Efforts :** Have researched on some of the below mentioned tools/libraries for the same -
_AWS SCT (Schema Conversion Tool)_ - Which finds the lineage/assignments of the variable and converts static query but not dynamically made query.
_Spoon library -_ Which is helping me to get all the variables and its values defined in a java file (Maybe after that we can make a custom logic for the goal we want to achieve but that would be very difficult).
_Java eclipse AST (Abstract Syntax Tree)_ - Eclipse plugin which helps to get the tree type structure of the java file but not able to know how to proceed next.
Attaching a sample JDBC code will try to make you understand what is that task. This attached file contains 7-8 possible ways which I could think a developer can make a dynamic SQL query.

Also writing a piece of code consisting of dynamically made query and what needs to be achieved from the same.

```
package spoon;

import java.sql.*;

public class DynamicCodeForJDBC {
static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
static final String USER = "guest";
static final String PASS = "guest123";

static final String QUERY2 = "FROM Employees";
static final String QUERY3 = "id,first,last";
static final String QUERY1 = "SELECT";


public void execute() {
	StringBuffer sb = new StringBuffer();
	sb.append(QUERY1);
	sb.append(QUERY2);
	sb.append(QUERY3);
	String dynamic_query = sb.toString();
try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
	Statement stmt = conn.createStatement();
	ResultSet rs = stmt.executeQuery(dynamic_query);) {
	while (rs.next()) {
		System.out.print("ID: " + rs.getInt("id"));
		System.out.print(", Age: " + rs.getInt("age"));
		System.out.print(", First: " + rs.getString("first"));
		System.out.println(", Last: " + rs.getString("last"));
	}
} catch (SQLException e) {
	e.printStackTrace();
	}
}
}
```
Understanding of the above code and our goal - Now if we will run the above file then the value of "dynamic_query" will be "SELECT id,first,last FROM Employees" but running the above is not what we want instead we will feed/give the above .java extension (not .class) file as an input and we want the output as "SELECT id,first,last FROM Employees".

**Stepwise understanding**

1. Dynamic_query is passed inside executeQuery method.
2. Dynamic_query is formed by "sb".
3. sb is formed with the StringBuffer append method.
4. StringBuffer accepts QUERY1,QUERY2 and QUERY3.
So, in this way we need to find out the lineage of a variable and give "**SELECT id,first,last FROM Employees**" as the final output.

**NOTE :** _Every code and query is subjective to change as per different applications so we need to make a generic tool for the same._

**Comment by matozoid** [comment]
The most obvious place to look for these is runtime logging. I assume that is not what you want.

Your solution can be as complex or as simple as you want, depending on the amount of errors in the output you will accept.

If the pattern is always the same as what you have above (dynamic query in a stringbuffer, all parts get "append"ed, some parts are static final Strings) then you should be able to find this pattern by examining the AST, to find the variable definitions, to find where in the AST they are defined, and to find the constant values (or not, for those values not constant.)

Not seen in the example is truly dynamic SQL with "if" and "for". For this you will need a bit of data flow analysis. Some work is in progress, although you could make a hacky version yourself (if "append" is inside "if", then we have two queries: one with, one without the append.)

So, that's a general idea of where to go.

**Comment by jlerbsc** [comment]
What do you expect from us by posting this issue?

**Comment by jlerbsc** [comment]
I am closing this issue because the question that is being asked is not related to the use of Javaparser. If so, the question should be more specific.
