### ISSUE TITLE
Node naming

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#358]
After #189 and #252 , it seems we should refactor the naming of nodes.

Please discuss.

**Comment by mlangkabel** [comment]
Maybe we should use `NameExpr` when a node is ment that from the perspective of the parser can be substituted by some other Expr. Like for example when parsing the source of an assignment expr.
For other cases (like when parsing the name of a ClassOrInterfaceDecl) we could use a new type called `Name`.

A `Name` could extend the `Node` class so we can ask for its location. And a `NameExpr` could have a `Name` member.

As a result a visitor can implement different `visit` methods for `Name` and `NameExpr`.

**Comment by matozoid** [comment]
Would you say that we should move away from having simple strings for naming?

**Comment by mlangkabel** [comment]
That would be great! In my opinion the strongest argument for moving away from simple strings is that we could use a more specific data type to store location info in addition to the raw name string. This info is already available during the parsing step but hard to reconstruct afterwards (which would require another lexing step).

**Comment by matozoid** [comment]
Also see #101 and its associated gitter chat

**Comment by matozoid** [comment]
Also see #403 
More reading: https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html

**Comment by matozoid** [comment]
This is how I understand it now:
- A lot of the "String name" fields are identifiers. We can make those "Identifier identifier" with Identifier being a Node holding a String.
- A simple name is an identifier.
- A qualified name combines simple names separated by a ".". In JavaParser, a QualifiedNameExpr wraps a QualifiedNameExpr or a NameExpr for every "." in the name.
- A qualified name can often, but not always, be used where a simple name can be used. (Example: the name of a method cannot be qualified.) This means QualifiedNameExpr inheriting from NameExpr is not always appropriate. I'm not sure how important this is.
- A (qualified) name can be used in an expression. JavaParser simply turns every name into a NameExpr so every name is usable as an expression. It's possible to have a Name and a QualifiedName class next to the NameExpr and QualifiedNameExpr. Another way would be to have Name and QualifiedName, and a NameExpr that contains a (Qualified)Name. We can also keep the structure the same, strip NameExpr and QualifiedNameExpr of their "Expr" suffix and pretend they are sometimes expressions and sometimes not.
- There is a suggestion that NameExpr is used in places where an identifier should be used.

I feel confident about replacing names with identifiers, and replacing overuse of NameExpr with Identifier.

I'm not sure if the current NameExpr and QualifiedNameExpr classes should be changed.

**Comment by mlangkabel** [comment]
For my work on Coati I have compiled a list of classes containing a `NameExpr` that should rather be `Identifiers`:
- PackageDeclaration
- ImportDeclaration
- ClassOrInterfaceDeclaration
- EnumDeclaration
- EmptyTypeDeclaration
- AnnotationDeclaration
- ConstructorDeclaration
- MethodDeclaration

Do you think this list is complete? And what do we do about expressions that contain a `NameExpr` (e.g. `MethodCallExpr` or `ArrayAccessExpr`)?

I don't think that the NameExpr and QualifiedNameExpr classes need to be changed. But for consistency we could make the `NameExpr` a wrapper for an `Identifier` (with no additional information) and the `QualifiedNameExpr` a wrapper for an `Identifier` and a `NameExpr`.
This does not really make a difference for the JavaParser itself but it would allow users to write visitors for `Identifier`s that visits every name in the AST.

**Comment by matozoid** [comment]
I'll comb through the JLS :...(

**Comment by matozoid** [comment]
PackageDeclaration, 7.4.1: this needs a qualified name, so it is currently correct.
ImportDeclaration, 7.5: this needs a canonical name, which can contain a qualified name, so it's correct.

Before I go on, what is your criterium for saying that these should be identifiers?

**Comment by mlangkabel** [comment]
Ah, that's a good thing to ask! My criterium is the following: Only nodes that can be replaced by other `XyzExpr` classes should be stored as `NameExpr` (otherwise the name `NameExpr` can be quite misleading).

**Comment by matozoid** [comment]
Ah, but a NameExpr without the expression part is, if I read the JLS, not an Identifier. Check the first few paragraphs of this: https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html

**Comment by mlangkabel** [comment]
So calling it `Identifier` would be misleading, too. What do you think about calling the nodes that represent a name `Name` and `QualifiedName`?

**Comment by matozoid** [comment]
That's an improvement. But what do we do with the names that can be expressions? Wrap them in a (newly designed) NameExpr?

**Comment by mlangkabel** [comment]
That was my thought, too. So the NameExpr would wrap a Name/QualifiedName that stores the name string and a position value.

**Comment by matozoid** [comment]
So...

``` java
class Identifier extends Node { String name }
class Name extends Node { Identifier identifier }
class QualifiedName extends Name { Identifier identifier; Name name }
class NameExpr extends Expression { Name name }
```

?

**Comment by mlangkabel** [comment]
That seems to match the JLS well. Classes like `MethodDeclaration` could just keep an `Identifier` member. This would prevent anyone from using some qualified name there :)

**Comment by ptitjes** [comment]
@matozoid @mlangkabel FYI, I reversed the `Name`/`QualifiedName` relationship in JLaTo:

```
class Name extends Expr { String name; }
class QualifiedName extends Node { Option<QualifiedName> qualifier; Name name; }
```

Thus a Name can be used as an expression or as a normal node (like the name of a method):

```
class MethodDecl extends Decl { Name name; /* ... */ }
```

In this way, a qualified-name can never be substituted for a name, and a qualified-name can never be substituted for an expression too... (I had hard time to figure this out in order to avoid having a `NameExpr` node that just wraps a `Name`, as to keep the AST small.)

**Comment by ptitjes** [comment]
@mlangkabel When you speak about Coati, is that [this](https://www.coati.io/) ?

**Comment by mlangkabel** [comment]
@ptitjes yes, that is what I have been referring to :)
The implementation reversed for JLaTo is indeed quite compact, but in my opinion the one proposed by @matozoid is very straight forward and therefore easy to understand (and write visitor patterns for). 
I think of JavaParser as a project made for other projects to build upon so understandability should be an important trait.

**Comment by ftomassetti** [comment]
Agreed on understability vs cleverness

**Comment by matozoid** [comment]
@ptitjes yeah, I'm not too happy with NameExpr, but it seems to fit the pattern of something like ExpressionStmt. With the difference that the JLS never mentions a NameExpr of course.

**Comment by matozoid** [comment]
Now that I'm working on it, it seems from the grammar that `Identifier` should be `SimpleName`. So if we get rid of `Identifier` (which was causing a lot of get.get.get which @ptitjes was trying to avoid) we get...

``` java
abstract class Name extends Node { }
class SimpleName extends Name { String name }
class QualifiedName extends Name { String qualifier; Name name }
class NameExpr extends Expression { Name name }
```

Which also matches the text "There are two forms of names: simple names and qualified names."

I'm considering merging `Name` and `QualifiedName` into `Name`, with an `Optional<String>` qualifier more or less like @ptitjes is doing (or do we get an `Optional<Name> subName` ?) I'd rather not call it QualifiedName then, because it could be a single identifier.

**Comment by matozoid** [comment]
Okay, I'm confused by the current implementation which turns a.b.c into QN(c, QN(b, N(a))). This seems reversed to me, especially after all the ArrayType adventures.

**Comment by matozoid** [comment]
Okay, I think I'm going to work on comment support first, because our "interesting" comment attribution algorithm is taking advantage of all the new nodes by stuffing comments in the middle of qualified names...

**Comment by matozoid** [comment]
I ended up with almost the same thing as @ptitjes, and was doubting to go all the way but didn't :)

``` java
class SimpleName extends Node { String id }

class Name extends Node { Name qualifier (nullable); String id }

class NameExpr extends Expression { SimpleName name }
```

In words:
- SimpleName is just an identifier. It represents a name without dots.
- Name is an identifier with an optional qualifier, which is a Name again. It represents a name with dots.
- NameExpr is an adapter with which you can put a SimpleName in an expression.

There is still time to change things before 3.0 releases. Here are some possible questions:
- why is "Name" the qualifiable variant, why not have "Name" for simple name and "QualifiableName" for qualified name?
- is it worth more to protect names from ending up expressions, or to optimize a not very useful node away (NameExpr)
- should names have some kind of base class for some reason?
