### ISSUE TITLE
toString() with objects qualified names

### ISSUE THREAD

**Issue by jose** [javaparser/javaparser#3580]
Hi, all,

First, thanks for this awesome project.

Quick question, how do I print out the source code of a method with the qualifiled name of each object created within the method?
Lets suppose there is a class `org.Bar`

```java
package org;

public class Bar {
    public Bar() {
        //
    }

    public void xpto() {
        //
    }
}
```

and a class `org.Foo`

```java
package org;

public class Foo {
    /**
     * This is the method foo
     */
    public foo(int i) {
        Bar bar = new Bar();
        bar.xpto();
    }
}
```

and now suppose I've the following code

```java
MethodDeclaration methodDeclaration = ... // which points to the `foo(int i)` method declaration
System.out.println(methodDeclaration.toString());
```

which prints out

```java
/**
 * This is the method foo
 */
public foo(int i) {
    Bar bar = new Bar();
    bar.xpto();
}
```

but instead, I would like to print out the same source code but with the qualifiled name of each object, i.e.,

```java
/**
 * This is the method foo
 */
public foo(int i) {
    org.Bar bar = new org.Bar();
    bar.xpto();
}
```

is there any PrettyPrinter to achieve this?

--
Best,
Jose

**Comment by jlerbsc** [comment]
Hi @jose no there is currently no such feature.

**Comment by jose** [comment]
Ok.  @jlerbsc, are you aware of any other library/tool that might allow me to achieve that?

**Comment by jlerbsc** [comment]
What I mean is that you have to do the work yourself using the features offered by the project.

**Comment by GaoYizhuo2000** [comment]
Hi,
i'm Gao Yizhuo, a student from Australian National University and member of a 5-people IT group. We are very interested in this project and would like to make a contribution for this issue. We would appreciate it if i could be the assignee for this.
Best regards

**Comment by jose** [comment]
> We are very interested in this project and would like to make a contribution for this issue.

Thanks in advance.

**Comment by jlerbsc** [comment]
I'm closing this issue because the question has been answered and there's no need to work on JP..
