### ISSUE TITLE
Differentiate concatenating PLUS with PLUS within a calculation 

### ISSUE THREAD

**Issue by NicolasHa00** [javaparser/javaparser#3583]
Hello, 
with this ModifierVisitor, i want to replace every BinaryExpr.Operator.PLUS with another operator, like e.g. MINUS. But only the PLUS operators that are used for calculation `(a = b + c)` or `System.out.println(a+b);`. This is the code: 

            
                sourceRoot = new SourceRoot(
                        CodeGenerationUtils.mavenModuleRoot(ReplacementAOMath.class)
                                .resolve("src/main/resources"));

                CompilationUnit cuMutateAll = sourceRoot.parse("", filename);
                cuMutateAll.accept(new ModifierVisitor<Void>() {

                    @Override
                    public Visitable visit(BinaryExpr n, Void arg) {

                        if (n.getOperator() == arithmeticOperatorsFrom[i] && !n.getLeft().isStringLiteralExpr()
                                && !n.getRight().isStringLiteralExpr()) {
                            n.setOperator(arithmeticOperatorsTo[i]);
                            comment.setContent("Here, the arithmetic operator "
                                    + arithmeticOperatorsFrom[i].name()
                                    + " was mutated with the arithmetic operator " + arithmeticOperatorsTo[i].name()
                                    + ":");
                            n.setComment(comment);
                        }
                        return super.visit(n, arg);
                    }
                }, null);`

I also included `!n.getLeft().isStringLiteralExpr() && !n.getRight().isStringLiteralExpr()` to exclude the modification of concatenating PLUS operators next to strings, because the replacement of a + with a - would lead to a error in the modified code. 
However, when using this approach, this statement in the source code `(System.out.println("test" + j + i + inc + "test2")`; becomes modified to this statement: `System.out.println("test" + j - i - inc + "test2");`
This will lead to an error as the variables j, i and inc are no longer concatenated as they are supposed to. Is there any way to reliably exclude the modification such concatenating plus operators within my If-statement  with a method or something similar provided by the JavaParser? 

Thank you!

**Comment by jlerbsc** [comment]
Hi @NicolasHa00 maybe you can assume that if the first operand is a string then the expression is a concatenation (except for operations performed between parentheses where you could ask the question recursively).

**Comment by NicolasHa00** [comment]
Hi @jlerbsc, thanks for the quick answer! This seems like it could work, but I'm not sure how i would implement this check (not the recursive one, just the simple check if the first operand is a string). 
Could you give me a short advice/code example how i would get the first operand within a method call like System.out.println(), please? The starting point would be the Binary Expression n like in the example above.  
Thank you!

**Comment by jlerbsc** [comment]
Maybe that could be a starting point

    @Test
    void test3583() {
        String code = ""
                + "public class Foo {\n"
                + "    public void f(String a , int b) {\n"
                + "        System.out.println(a+b+1);\n"
                + "    }\n"
                + "}";

        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        StaticJavaParser.setConfiguration(configuration);
        
        CompilationUnit cu = StaticJavaParser.parse(code);

        BinaryExpr expr = cu.findFirst(BinaryExpr.class).get();
        System.out.println(isConcatenation(expr));
    }

    private boolean isConcatenation(BinaryExpr expr) {
        if (expr.getLeft() instanceof BinaryExpr) {
            return isConcatenation((BinaryExpr) expr.getLeft());
        }
        ResolvedType rt = expr.getLeft().calculateResolvedType();
        return "java.lang.String".equals(rt.describe());
    }

**Comment by jlerbsc** [comment]
or just

    @Test
    void test3583() {
      String code = ""
            + "public class Foo {\n"
            + "    public void f(String a , int b) {\n"
            + "        System.out.println(a+b+1);\n"
            + "    }\n"
            + "}";

    ParserConfiguration configuration = new ParserConfiguration()
            .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
    StaticJavaParser.setConfiguration(configuration);
    
    CompilationUnit cu = StaticJavaParser.parse(code);

    BinaryExpr expr = cu.findFirst(BinaryExpr.class).get();
    ResolvedType rt = expr.calculateResolvedType();
    System.out.println("java.lang.String".equals(rt.describe()));
    }

**Comment by NicolasHa00** [comment]
Thanks @jlerbsc ! Your example and especially the helper method worked fine and were exactly what I needed!
