### ISSUE TITLE
TypeSolver unable to resolve method calls that are defined and used within the same class file.

### ISSUE THREAD

**Issue by Navneetx777** [javaparser/javaparser#3584]
I am trying to resolve the class of method invocations within a workspace. I am iteratively changing the directory being fed to the JavaParserTypeSolver(). It is able to resolve classes for some methods but is failing and raising exception for what I've observed are methods whose definition lies within the class file it is being used in. Please let me know if there's something I am missing regarding the working of TypeSolver or any pointers regarding the issue.

**Comment by jlerbsc** [comment]
Hi @Navneetx777 can you provide us with a simple example of what you have developed?

**Comment by Navneetx777** [comment]
This is the code snippet where I am passing the directory to the typesolver:
`for(ICompilationUnit unit : units) {
                                
  File file = new File(workspacePath+pack.getPath()+"\\" + unit.getElementName());
  CombinedTypeSolver solver = new CombinedTypeSolver();
  solver.add(new ReflectionTypeSolver());
  solver.add(new JavaParserTypeSolver(projectPath + "/src"));
  TypeSolver typeSolver = solver;
  JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
  StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
  CompilationUnit cu = StaticJavaParser.parse(file);

}`

I have verified that the projectPath here is pointing correctly to the project's directory 

Here is a sample class it is having problem with 

`
**import statements**

public class RefrencesHandler extends AbstractHandler
		implements IJavaEditorTextHover, ITextHoverExtension, ITextHoverExtension2 {

	@Override
	public Object execute(ExecutionEvent event) throws ExecutionException {
		IWorkbenchWindow window = HandlerUtil.getActiveWorkbenchWindowChecked(event);
		IEditorPart editor = HandlerUtil.getActiveEditor(event);
		IEditorInput input = editor.getEditorInput();
		IFile file = (IFile) Platform.getAdapterManager().getAdapter(input, IFile.class);
		IWorkspace workspace = ResourcesPlugin.getWorkspace();
		IWorkspaceRoot root = workspace.getRoot();
		IProject[] plainProjects = root.getProjects();

		String currentFileFullpath = file.getFullPath().toString();
		String projectName = currentFileFullpath.substring(0, currentFileFullpath.indexOf("src")).replaceAll("/", "");
		String fullFileName = currentFileFullpath.split("java/")[0].replaceAll("/", ".").replaceAll(".java", "");
		IProject invokerFilePlainProject = root.getProject(projectName);
		IJavaProject invokerFileJavaProject = JavaCore.create(invokerFilePlainProject);
		Map<String, String> fieldNameAndTypeMap = new HashMap<>();
		createFieldNameAndTypeMap(fullFileName, invokerFileJavaProject, fieldNameAndTypeMap);
               String currentSelectedText = getCurrentSelection().getText();
		Set<String> serviceNameMethodNameSet = new HashSet<>();
                if (currentSelectedText != null) {
			String textArray[] = currentSelectedText.split(";");
			for (String text : textArray) {
				if (text.contains(".")) {
					setServiceMethodName(serviceNameMethodNameSet, text);
                                        .
                                        .
                               .}
                        }
                }
                return null;
            }
                private void setServiceMethodName(Set<String> serviceNameMethodNameSet, String text){...}
                private void createFieldNameAndTypeMap(String fullFileName, IJavaProject invokerFileJavaProject,
			Map<String, String> fieldNameAndTypeMap) {...}
                public ITextSelection getCurrentSelection() {...}
                
         }
`

In the above class its able to identify class for setServiceMethodName, ignoring createFieldNameAndTypeMap altogether and encountering an exception with getCurrentSelection :
`RefrencesHandler setServiceMethodName`

`UnsolvedSymbolException{context='getCurrentSelection().getText()', name='getCurrentSelection()', cause='UnsolvedSymbolException{context='null', name='ITextSelection', cause='null'}'}
`

**Comment by jlerbsc** [comment]
Where the ITextSelection interface is defined?

**Comment by Navneetx777** [comment]
HandlerUtil, ITextSelection etc. are all defined in the eclipse's own libraries for plugin development. The ITextSelection in particular is present in org.eclipse.jface.text._version__.jar.

**Comment by matozoid** [comment]
Quick idea: are you running from an Eclipse plugin, expecting something to be available through reflection, but maybe the osgi config is blocking the classloader from finding it?

**Comment by jlerbsc** [comment]
You probably have to declare the dependency org.eclipse.jface.text.version_.jar in the TypeSolver.

**Comment by jlerbsc** [comment]
I am closing this issue but you are free to reopen it if you have other information to submit to us.
