### ISSUE TITLE
foramt code has issue when method declaration has comment

### ISSUE THREAD

**Issue by zonggit** [javaparser/javaparser#3586]
there is a single line comment("**// this is a test**") in the method declaration
![图片](https://user-images.githubusercontent.com/19405663/169650751-329473d9-cc08-43b2-abd3-7d69487db89f.png)

`
public class TestClass {`
`    public void test(String p1, String p2) // this is a test`
`    {`
`        System.out.println("test");`
`    }`
`}
`

use below code to format:(the content of a is above code):
`CompilationUnit cu = StaticJavaParser.parse(a);`
`System.out.println(cu.toString());`

the output is:
![图片](https://user-images.githubusercontent.com/19405663/169650769-8a74ec59-313e-4916-a1d3-41c5f7a2468c.png)

the line of method declaration split to 4 lines and have 3 same comments

my questions is: how to fix this issue

**Comment by jlerbsc** [comment]
Hi @zonggit Thank you for reporting this bug that is related on how JP assign comment to node.

**Comment by Bash-09** [comment]
Hi, I'd love to have a try at fixing this issue if it isn't already.

Should I get it assigned to me or just begin working on a fork and submit it whenever?

**Comment by jlerbsc** [comment]
Hi @Bash-09 You can submit your suggestions for improvement at any time. Have you started working on this problem?

**Comment by Bash-09** [comment]
@jlerbsc 
> Hi @Bash-09 You can submit your suggestions for improvement at any time. Have you started working on this problem?

Thanks. I was just waiting on confirmation to double check, I am going ahead now.
