### ISSUE TITLE
Modifier is removed when removing an annotation.

### ISSUE THREAD

**Issue by nimakarimipour** [javaparser/javaparser#3588]
When using `LexicalPreservation` printer, it mistakenly removes the modifier when we are removing an annotation from a `Node` under the following circumstances:
1. Node is of type `FieldDeclaration`.
2. `FieldDeclaration` contains a modifier.
3. `FieldDeclaraion` contains an annotation.
4. Modifier is written on the left side of the annotation. (e.g. `public @Annot Object field;`).

I tested the above issue with all modifiers (e.g. `public`, `private`, `static` and ...) and all cases had the same issue.

Please find the code below where the error reported in this issue is reproduced:
```java
CompilationUnit tmp =
        StaticJavaParser.parse(
            "public class Foo{" + "\n" + "    protected @Nullable Object bar;" + "\n" + "}");
    LexicalPreservingPrinter.setup(tmp);
    Optional<ClassOrInterfaceDeclaration> optional = tmp.getClassByName("Foo");
    optional
        .get()
        .getMembers()
        .forEach(
            bodyDeclaration ->
                bodyDeclaration.ifFieldDeclaration(
                    fieldDeclaration -> {
                      NodeList<VariableDeclarator> vars =
                          fieldDeclaration.asFieldDeclaration().getVariables();
                      for (VariableDeclarator v : vars) {
                        if (v.getName().asString().equals("bar")) {
                          fieldDeclaration
                              .getAnnotations()
                              .removeIf(
                                  annotationExpr ->
                                      annotationExpr.getName().asString().equals("Nullable"));
                        }
                      }
                    }));
System.out.println(LexicalPreservingPrinter.print(tmp));
```

The output of the code above is:
```java
public class Foo{
    @Nullable Object bar;
}
```

The annotation is not removed and the modifier is deleted. Please let me know if you recommend another way of removing annotation from `Node`s or need more information.

Best,

Nima

**Comment by jlerbsc** [comment]
Thank you for reporting this bug. I will try to look at this issue over the next few days. Thank you for your patience.

**Comment by jlerbsc** [comment]
It looks more complex than I thought because annotations can be placed before or after the modifier. I think it's related to the concrete syntax model declaration but I'm not sure. Also when we declare concrete syntax model differently (with a mix) we generate other errors on the tests related to the Lexical Preserving Printer (the end of line characters are no longer in conformity with what should be). Maybe @MysterAitch or @matozoid can help us to resolve this issue.

**Comment by matozoid** [comment]
I'm not touching that thing ever again :-)

**Comment by msridhar** [comment]
@jlerbsc should this issue be marked as fixed now?  Thanks so much for digging in, we really appreciate it!

**Comment by jlerbsc** [comment]
Yes this issue is fixed.

**Comment by nimakarimipour** [comment]
Hi all, thank you very much for resolving this issue, Lexical Preserving Printer is crucial for our tool. Please let me know if there is anything I can do to help. Thanks again for your great tool.

**Comment by matozoid** [comment]
@nimakarimipour - there is tons of work to do, if you want to help, come to the gitter channel and chat :-)
