### ISSUE TITLE
How to find the declared Node of a variable in a statement

### ISSUE THREAD

**Issue by RickCompileError** [javaparser/javaparser#3591]
Hi,

I'm trying to find the `VariableDeclarator` from the `Expression`.

There is a simple code below :
```java
String str1 = "Hello";
System.out.println(str1);
```
The restriction is that I don't know the content of the code at the beginning, so I can only visit the AST and find the `Node : str1` at the second line to get the variable name `str1`.

Then how can I get the `Node : String str1 = "Hello";` at the first line by using the `Node : str1`?

I think it can use visit to solve again, but is there an easier way can get the same result?

Thanks,

**Comment by matozoid** [comment]
Maybe find the Statement you're in, then the enclosing BlockStmt, then where the Statement is in that BlockStmt, then trace back looking for a VariableDeclarationExpr inside an ExpressionStmt with the right Name. If not found, go up to the next BlockStmt, or go find fields declaring it?

The usual way for solving variables would be to walk the whole tree from start to end, collecting information and storing it in the nodes for easy access.

It sounds like you're writing some kind of symbol solver - are you aware that there is one included in JavaParser?

**Comment by RickCompileError** [comment]
Hi @matozoid ,

Thanks for your idea, I'll try it later.

Yes, I know. I also gave it a try but not spent too much time. I imitated with the example in the e-book, used `calculateResolvedType()` and got the `string` type indeed. But is there any function can call to get the `VariableDeclarationExpr`?

**Comment by jlerbsc** [comment]
Maybe you can resolve the NameExpr "str1" and if the result implements the interface AssociableToAST you can get the wrapped Node with the method toAst().

    @Test
    void test3591() {
        String code = ""
                + "public class Foo {\n"
                + "    public void f() {\n"
                + "      String str1 = \"Hello\";\n"
                + "      System.out.println(str1);\n"
                + "    }\n"
                + "}";

        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        StaticJavaParser.setConfiguration(configuration);
        
        CompilationUnit cu = StaticJavaParser.parse(code);
        
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        Expression expr = mce.getArguments().get(0);
        ResolvedValueDeclaration decl = ((NameExpr) expr).resolve();
        if (decl instanceof AssociableToAST) {
            System.out.println(((AssociableToAST)decl).toAst().get().toString());
        }
    }

**Comment by RickCompileError** [comment]
I see, thanks for your help
