### ISSUE TITLE
UnsolvedSymbolException is thrown at every occurance thus blocking shallower operations

### ISSUE THREAD

**Issue by yamanogluberk** [javaparser/javaparser#3602]
Lets move on from an example, when I try to resolve the type of a parameter of a method (List<HashMap<ExternalClass, Integer>> parameter1) I get an UnsolvedSymbolException because the SymbolSolver cant resolve ExternalClass, which is perfectly normal because it is not in the source code I fed to the SymbolSolver, but here is the thing I can't see the other parameter as well or even the type of the List, because there is an exception deepdown in the resolving operation and the whole operation is stopped. 

I am developing a project that analyzes Java source code and generates a tree that shows the relationships between classes, their methods, their fields, and even external classes etc. I make use of the UnsolvedSymbolException in simple cases to generate a node of my own. Here is how it works: I try to resolve some type used in code(lets say in an instance creation via constructor), if the SymbolSolver can resolve it, fine, I create a Node (of my own) for it with other information I have extracted using the JavaParser, if SymbolSolver can't resolve it, I extract the fully qualifed name using import statements and the name of the class that couldnt be resolved from the UnsolvedSymbolException, and again I create a Node(again of my own) and mark it as an ExternalClass(meaning it is a class not found in the project, like a library). Later occurances of this class (in UnsolvedSymbolExceptions) are redirected and referenced to the Node that I created for it. 

The problem is, this approach doesnt work for resolving cases with some depth in it as I described in the beginning. If the resolving failure occurs deep in the resolving tree, I cant access the shallower information. Like in the example List<HashMap<ExternalClass, Integer>> , I would like to be able to extract that the type parameter of the List is java.util.HashMap and when I try to resolve HashMap's type parameter then I get the exception for parameter 1, and get the resolve type for Integer as well. 

My suggestion is either trying to resolve inner symbols as their information is requested and throw the exception then, or implement a simple approach like mine(maybe optional feature) which is keeping record of unresolved types and returning them as unresolved types when requested and flagging them with a bool maybe(UnsupportedOperationException can be thrown when their unexisting info is requested, like trying to use a primiter with asReferenceType()) and thus not dropping whole resolve operation when there is an unresolved type deep in the operation.

WDYT about this, is there a solution to my problem that I am missing, or is my suggestion applicable?

**Comment by yamanogluberk** [comment]
@jlerbsc Hey, I see that you are mostly active around here, if you can take your time to inspect this issue and give your opinions on the topic, I would appreciate it. As I said, I am working on a project with a deadline and would like to know if there is a quick solution to my issue. Thanks btw for the project, great job!

**Comment by jlerbsc** [comment]
Hi @yamanogluberk Thanks for using javaparser on your project unfortunately I won't be of much help on your issue. Indeed the symbolsolver relies, from my understanding, on the fact of being able to deeply resolve all the types in order to be able to determine the declaration of the initial type or the invoked method. I have no idea how the symbolsolver would work if we changed this behavior. Only the founders of the project could shed some light on how to solve your issue. The easiest way to solve it is to declare all the dependencies of your project.

> "trying to resolve inner symbols as their information is requested "

In fact all symbols are needed when resolving a type or a method.

**Comment by yamanogluberk** [comment]
@jlerbsc Thanks anyways for taking the time to answer, I will try to find a way around

**Comment by jlerbsc** [comment]
I am closing this issue but you can reopen it if you have new questions on this subject.
