### ISSUE TITLE
How to swap two lines of code

### ISSUE THREAD

**Issue by RickCompileError** [javaparser/javaparser#3603]
I'm trying to swap two lines of code by using setRange() function on two Nodes

here is the simple code below
```java
Node n1, n2;
Range tmp = n1.getRange().get();
n1.setRange(n2.getRange().get());
n2.setRange(tmp);
```

The Range in Node was successfully swap but they didn't change the position when I using LexicalPreservingPrinter to look the result.

**Comment by jlerbsc** [comment]
Hi @RickCompileError LexicalPreservingrinter doesn't use range to print a node. Rrom my point of view you have to recreate the nodes with the existing ones.

**Comment by RickCompileError** [comment]
I see. Thanks for your help.
