### ISSUE TITLE
What's the right way to create a local variable?

### ISSUE THREAD

**Issue by fabiopereiragt** [javaparser/javaparser#3610]
I need to create a local variable in a method. So, I used this (example):

```
		cu.accept(new ModifierVisitor<Void>() {
			@Override
			public Visitable visit(VariableDeclarator n, Void arg) {
				if ((n.getType().asString().equals("File"))) {
					Statement staticStatement = StaticJavaParser.parseStatement("int x = 0");
					BlockStmt block = n.findAncestor(BlockStmt.class).get();
					List<Node> blocks = block.getChildNodes();
					int index = blocks.toString().indexOf(n.getParentNode().get().toString());
					n.findAncestor(BlockStmt.class).ifPresent(x -> {
						x.addStatement(index, staticStatement);
					});
				}
				return super.visit(n, arg);
			}
		}
```

It works, but I feel like it's a bad smell.
I saw that FieldDeclaration is in a Class context and could not be used in a method, is that right?

**Comment by jlerbsc** [comment]
Hi @fabiopereiragt your are right. FieldDeclaration is not the same as VariableDeclarator.
If you want to insert an element at a particular position you must actually implement the search for the insertion position.

**Comment by fabiopereiragt** [comment]
Hi @jlerbsc ! Thanks. So I understood about the position. But, what is the correct way to create a local variable? Adding an Statement in BlockStmt the way I did?

**Comment by jlerbsc** [comment]
The answer to your question probably depends on the context. In this case i think it's the right way.

**Comment by jlerbsc** [comment]
I am closing this issue as I believe the question posed has been answered. If you think this answer is not sufficient you can of course reopen this issue.
