### ISSUE TITLE
toDescriptor() for TypeDeclaration and ResolvedDeclaration

### ISSUE THREAD

**Issue by yufanyufan** [javaparser/javaparser#3615]
Currently, toDescriptor() exists for a few special classes: ast.type.Type and ast.body.MethodDeclaration

Can we add it to TypeDeclaration and ResolvedDeclaration?

**Comment by jlerbsc** [comment]
Descriptors are defined by the JLS ("A descriptor is a string representing the type of a field or method.").

https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.3
