### ISSUE TITLE
Replace arithmetic operation with method call

### ISSUE THREAD

**Issue by dsto97** [javaparser/javaparser#3616]
Hi all, I'm currently trying to learn how to use javaparser appropriately. After some easier things I wanted to try something more specific. 
`public static void main(String[] args) {
        int x = 5;
        int y = 3;
        int z = (x & y);
        System.out.println(z);
    }`
I try to replace the arithmetic operation 
`int z = (x & y)`
with my own method call to look like this
`int z = methodcall(x, y)`

That's my code so far which is actually runnable but the methodcall doesn't appear
`CombinedTypeSolver combined = new CombinedTypeSolver();
        combined.add(new ReflectionTypeSolver());

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combined);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(new FileInputStream(PATH));

        cu.accept(new ModifierVisitor<Void>(){
            @Override
            public Visitable visit(BinaryExpr n, Void arg){
                super.visit(n, arg);
                if(n.getOperator() == BinaryExpr.Operator.BINARY_AND){
                    Optional<Node> parent = n.getParentNode();
                    Expression left_op = n.getLeft();
                    Expression right_op = n.getRight();
                    Node methodcall = StaticJavaParser.parseExpression("arithmetics.and("+left_op+","+right_op+")");
                    parent.get().replace(methodcall);
                    return n;
                }
                return super.visit(n, arg);
            }
        }, null);

    }`

Do you have any hint how to achieve that?

**Comment by jlerbsc** [comment]
Hi @dsto97 you are using a ModifierVisitor that is usefull when nodes needs to be changed. Here  you are replacing a node by another. So you can use a VoidVisitor like this

    @Test
    void test3616() {
        String code = ""
                + "public class Foo {\n"
                + "    public static void main(String[] args) {\n"
                + "       int x = 5; int y = 3; int z = (x & y); System.out.println(z);\n"
                + "    }\n"
                + "}";

        CompilationUnit cu = StaticJavaParser.parse(code);

        VoidVisitor<Void> visitor = new VoidVisitorAdapter<Void>() {
            @Override
            public void visit(BinaryExpr n, Void arg){
                if(n.getOperator() == BinaryExpr.Operator.BINARY_AND){
                    Expression left_op = n.getLeft();
                    Expression right_op = n.getRight();
                    Node methodcall = StaticJavaParser.parseExpression("arithmetics.and("+left_op+","+right_op+")");
                    n.replace(methodcall);
                }
            }
        };
        cu.accept(visitor, null);
        System.out.println(cu.toString());
    }

**Comment by dsto97** [comment]
@jlerbsc thank you very much for your fast answer. That worked perfectly :D
