### ISSUE TITLE
getLocalDeclarationFromClassname with "java.util.NoSuchElementException" error

### ISSUE THREAD

**Issue by HJX-zhanS** [javaparser/javaparser#3620]
When I use the `getLocalDeclarationFromClassname` to get classes, the `java.util.NoSuchElementException` error occurs. The source code I parsed is:
[target_code.zip](https://github.com/javaparser/javaparser/files/8972775/target_code.zip)

Can you help me? Thanks!

**Comment by jlerbsc** [comment]
Hi @HJX-zhanS i can't reproduce your issue with this sample unit test.

    @Test
    public void issue3620() {
        considerCode(
                "class Foo {\n" +
                        "  class Baz {}\n" +
                        "}");
        List<ClassOrInterfaceDeclaration> classes = cu.getLocalDeclarationFromClassname("Baz");
        System.out.println(classes.get(0).getNameAsString());
    }

which returns 


    Baz

**Comment by HJX-zhanS** [comment]
> 

Hi@[jlerbsc](https://github.com/jlerbsc)，my problem occurs when I parse the code in "target.zip".
