### ISSUE TITLE
[Question] Resolve StringLiteral

### ISSUE THREAD

**Issue by fls-indinf** [javaparser/javaparser#3622]
Is there a way to get a concatenated String the compiler usually would inline?
```
public static final String SOME_TEXT = "Hello " + "World";
public static final String HELLO = "Hello";
public static final String WORLD = " World";
public static final String HELLO_WORLD = HELLO + WORLD;
```

**Comment by jlerbsc** [comment]
Hi @fls-indinf you have to do it yourself but JP provides the tools to do it.

**Comment by fls-indinf** [comment]
Hi,
Thank you. I guessed it, but I think a predefined filter would be nice to get the same results as e.g. the [bcel](https://github.com/apache/commons-bcel)-lib would with the ConstantString-Objects.

But nontheless, it's a powerful and flexible util doing a great job so far!
