### ISSUE TITLE
TypeExtractor doesn't handle EnclosedExpr well

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#3629]
Typeextractor class does not consider lambdaexpr wrapped by enclosedexpr.
The parameter args of the solvearguments method of the javaparserface class is not considered to have enclosedexpr.

(Taken from #3486 from @ZeroAicy )

**Comment by jlerbsc** [comment]
Seems to be related to https://github.com/javaparser/javaparser/issues/3859
and should be resolved now.
