### ISSUE TITLE
What is the difference between Java Parser's `BinaryExpr` and Infix Expression?

### ISSUE THREAD

**Issue by ThanoshanMV** [javaparser/javaparser#3630]
Hi Community,

I can notice that JP's [BinaryExpr](https://www.javadoc.io/static/com.github.javaparser/javaparser-core/3.24.0/com/github/javaparser/ast/expr/BinaryExpr.html) refers to an expression that has an expression on the left, an expression on the right and an operator on the middle.

Infix expression: the operator is written in-between the **two or more operands** [[Source](https://www.javatpoint.com/infix-to-postfix-java)].

I would like to know is there any difference between these two expressions?

I tried to parse a Java method using JavaParser for `BinaryExpr` and Eclipse JDT for `InfixExpression`.

JavaParser:
```
        com.github.javaparser.ast.CompilationUnit jpCompilationUnit = generateJavaParserCompilationUnit(testFunction);
        System.out.println("BinaryExpr Count " + jpCompilationUnit.findAll(BinaryExpr.class).size());
```

Eclipse JDT:
```     org.eclipse.jdt.core.dom.CompilationUnit jdtCompilationUnit = generateJdtCompilationUnit(testFunction);
        InfixExpressionVisitor infixExpressionVisitor = new InfixExpressionVisitor();
        jdtCompilationUnit.accept(infixExpressionVisitor);
        System.out.println("Infix Expression Count " + infixExpressionVisitor.getInfixExpressionCount());
```
Results:
```
BinaryExpr Count 6
Infix Expression Count 3
```

The Java function used for this experimentation;
```
public Program updateProgramPath (int id, String sourcePath) throws AdaptationException {
    Program program = null;
    Connection connection = null;
    Statement statement = null;
    ResultSet resultSet = null;
    try {
        String query = "UPDATE Programs SET " + "sourcePath = '" + sourcePath + "' " + "WHERE id = " + id;
        connection = DriverManager.getConnection (CONN_STR);
        statement = connection.createStatement ();
        statement.executeUpdate (query);
        query = "SELECT * from Programs WHERE id = " + id;
        resultSet = statement.executeQuery (query);
        if (! resultSet.next ()) {
            connection.rollback ();
            String msg = "Attempt to update program failed.";
            log.error (msg);
            throw new AdaptationException (msg);
        }
        program = getProgram (resultSet);
        connection.commit ();
    } catch (SQLException ex) {
        try {
            connection.rollback ();
        } catch (Exception e) {
        }
        String msg = "SQLException in updateProgramPath";
        log.error (msg, ex);
        throw new AdaptationException (msg, ex);
    } finally {
        try {
            resultSet.close ();
        } catch (Exception ex) {
        }
        try {
            statement.close ();
        } catch (Exception ex) {
        }
        try {
            connection.close ();
        } catch (Exception ex) {
        }
    }
    return program;
}
```

According to the definition and experimentation, I think may be `BinaryExpr` is a subset of Infix Expression.

Here is the [Eclipse JDT](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FInfixExpression.html) `InfixExpression` grammar: `Expression InfixOperator Expression { InfixOperator Expression }`

Please let me know what do you think about this issue. Thank you!

**Comment by jlerbsc** [comment]
Hi @ThanoshanMV  as you noticed there is no more notion of infix in JP than in JLS. Here are the binaryExpr detected in JP using your code. You will notice that there are 6 of them as well.

    "UPDATE Programs SET " + "sourcePath = '" + sourcePath + "' " + "WHERE id = " + id
    "UPDATE Programs SET " + "sourcePath = '" + sourcePath + "' " + "WHERE id = "
    "UPDATE Programs SET " + "sourcePath = '" + sourcePath + "' "
    "UPDATE Programs SET " + "sourcePath = '" + sourcePath
    "UPDATE Programs SET " + "sourcePath = '"
    "SELECT * from Programs WHERE id = " + id

**Comment by ThanoshanMV** [comment]
Thank you @jlerbsc. As you mentioned, I checked the [JLS](https://docs.oracle.com/javase/specs/jls/se18/html/jls-15.html#jls-15.2)  as well. There is no notion of infix.

**Comment by matozoid** [comment]
Note that every node type has some Javadoc explaining what it represents: https://javadoc.io/doc/com.github.javaparser/javaparser-core/latest/com/github/javaparser/ast/expr/BinaryExpr.html
