### ISSUE TITLE
Inner record within record is parsed as a MethodDeclaration

### ISSUE THREAD

**Issue by ktul** [javaparser/javaparser#3632]
Example:
```
record A() {
    record B() {
        record C() {
        }
    }
}
```
Here, `B` is wrongly parsed as a `MethodDeclaration` with `record` as the return type. Consequently, `C` is wrongly parsed as a local `RecordDeclaration` within a `LocalRecordDeclarationStmt`.

Interpreting `B` as a method is expected for Java 1.0 to 13, but then `A` and `C` would need to be parsed as methods as well, leading to syntax errors (method within method).

Setting the language level to 14 or 15 does not help. Neither does adding parameters to any of the records change the behaviour.

This does not happen when `B` is nested within a class, enum or interface.

**Comment by jlerbsc** [comment]
This is no longer an issue in the current version of JP.
