### ISSUE TITLE
Can I get the path from a solved type?

### ISSUE THREAD

**Issue by JavierYepez** [javaparser/javaparser#3633]
Hello, I'm trying to get the source file or `CompilationUnit` from a `com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl` instance. I didn't found any useful method in [here](https://www.javadoc.io/doc/com.github.javaparser/javaparser-symbol-solver-core/latest/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeImpl.html) to achieve it.

I'm getting the object by doing `node.resolve().getType()` on a `com.github.javaparser.ast.body.VariableDeclarator` node.

Thank you in advance

**Comment by jlerbsc** [comment]
Hi @JavierYepez  CompilationUnit is already available to nodes using findCompilationUnit(). It could provide a storage with getStorage() method. Your problem is to access the declaration Node from the node.resolve() return type which is a ResolvedValueDeclaration. If you are sure that the node is a field you can use asField() to get a ResolvedFieldDeclaration and then toAst() to get an Optional<FieldDeclaration>.

Then 


> fd.get().findCompilationUnit().get().getStorage().get().getPath()

**Comment by JavierYepez** [comment]
Thank you for your reply @jlerbsc !

I think your solution doesn't fit to my issue... Probably because of the lack of context. I didn't want to post source code because I'm running the library through Python. Anyway, here is a screenshot of the console showing what I can access:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/7388957/178974360-d3cb0ee5-9de5-493c-8e1b-83b6aff198ea.png">

I hope now it's more clear.

**Comment by jlerbsc** [comment]
Don't resolve the type. Below an example (you have to protect your code of course)

    @Test
    void test3633() {
        String code = ""
                + "class Foo {\n"
                + "    Vehicle3 x = new Vehicle3();; \n"
                + "}";

        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        StaticJavaParser.setConfiguration(configuration);

        CompilationUnit cu = StaticJavaParser.parse(code);

        List<VariableDeclarator> vds = cu.findAll(VariableDeclarator.class);
        Optional<FieldDeclaration> fd = vds.get(0).resolve().asField().toAst();
        System.out.println(fd.get().findCompilationUnit().get().getStorage().get().getPath().toString());
    }

**Comment by JavierYepez** [comment]
The solution doesn't work because it's not a `FieldDeclaration`. 

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/7388957/179184653-66bc6d45-7308-4fb7-a1d8-c1ae02431e4f.png">

Maybe I can get it from a resolved version of an `ObjectCreationExpr`?

    In[3]: node.getChildNodes()[2]
    Out[3]: <java object 'com.github.javaparser.ast.expr.ObjectCreationExpr'>

Please, note that I'm not interested in the CompilationUnit or path of the current file, which I could obtain like this:

    node.getChildNodes()[2].findCompilationUnit().get().getStorage().get().getPath().toString()

I want the CU of the file where 'Vehicle3' class is implemented.

Here is a sample of the source code that I want to parse:

    package virtualVehicle;
    
    import virtualVehicle.CACC.InInternalCommunication;
    
    public class Main {
	    
	    public static void main(String[] args) throws InterruptedException
	    {
		    run_vehicle3();
	    }
    
	    private static void run_vehicle3() {
		    Vehicle3 vehicle3 = new Vehicle3();
		    
		    vehicle3.cacc.inInComm.radar.speed = 56.0f;
		    vehicle3.cacc.inInComm.minDistance = 2.0f;
		    vehicle3.cacc.inExComm.maxDistance = 5.0f;
		    
		    vehicle3.decideToJoinPlatoon(30.0f, 8.05f);
			    
		    vehicle3.cacc.execute();
	    }
    }

My 'node' is referring to the first line in the `run_vehicle3()` method.

**Comment by jlerbsc** [comment]
You cannot get directly the CU of the referenced type (in your case Vehicle3 ) but you can resolve the method call expression (which give you a ResolvedConstructorDeclaration) then get the ast (Optional\<ConstructorDeclaration\>)  then possibly get the complilationUnit. In short

> mce.resolve().toAst().get().findCompilationUnit()

**Comment by JavierYepez** [comment]
Great! that solved my issue. Thank you
