### ISSUE TITLE
Release 3.24.3 not on Maven central

### ISSUE THREAD

**Issue by daniellansun** [javaparser/javaparser#3635]
Release 3.24.3 can not be found on Maven central, could you take a look? Thanks in advance.

https://search.maven.org/artifact/com.github.javaparser/javaparser-core

**Comment by jlerbsc** [comment]
Yes it is an error during deployment. The person who was in charge of it no longer seems available. So I'm sorry, but I'm experimenting right now.

**Comment by matozoid** [comment]
I tweeted about this, because it would be better if JP has more than one person responsible for it: https://twitter.com/matozoid/status/1547940727715295235

**Comment by jlerbsc** [comment]
Maybe it would be more logical for @MysterAitch to help deploy this version? Can you delete this tweet please?

**Comment by matozoid** [comment]
I think it would be good for JP if more people joined the community, but okay, it's deleted.

**Comment by jlerbsc** [comment]
I agree with you.
