### ISSUE TITLE
Add an inner class to source code 

### ISSUE THREAD

**Issue by zwangMcGill** [javaparser/javaparser#3638]
Hello,

How can I add an inner class to the source code? Is there any way to do so? Thank you!

**Comment by jlerbsc** [comment]
Hi @zwangMcGill you can add a new member (class declaration) in the class declaration. For exemple


    @Test
    public void issue3638() {
        considerCode(
                "class Outer {\n"
                + "}");
        // get the class declaration 'Outer'
        ClassOrInterfaceDeclaration cid = cu.findFirst(ClassOrInterfaceDeclaration.class).get();
        // create a new class declaration
        ClassOrInterfaceDeclaration inner = new ClassOrInterfaceDeclaration(new NodeList(), false, "Inner");
        // set the new class declaration into the members list
        cid.getMembers().add(inner);
        System.out.println(cu.toString());
    }

**Comment by jlerbsc** [comment]
I am closing this issue but you can reopen it if the answer does not suit you.
