### ISSUE TITLE
EqualsVisitor arbitrarily checks position

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#365]
Like this:
        if (!objEquals(n1.getBeginLine(), n2.getBeginLine())) {

It should not do so.

**Comment by matozoid** [comment]
Changing it breaks comment support :(

**Comment by ftomassetti** [comment]
I think we had a discussion on this, probably years ago. The point is "Equality" means different things in different context.
Two classes that look like this:
`class A {}`
are equal?
Does it depend on the package where they are? Does it depend on the number of spaces inside the brackets? A local or an inner classes with the same definition would be equal to the class A defined as a top level class?
Imho we would need different EqualsVisitor

**Comment by matozoid** [comment]
True, and I'm trying to generate visitors like these :) But I don't think a visitor should ignore 99% of node positions, and only check those for comments. This seems to have been hacked in for comment support, since that breaks when I remove the position checks. So now I'm going to see where it uses the EqualsVisitor, and if I can insert a custom visitor there.

**Comment by matozoid** [comment]
#728 and #729 have taken over from #280
