### ISSUE TITLE
unreproducible MAVEN_BUILD_TIMESTAMP

### ISSUE THREAD

**Issue by bmwiedemann** [javaparser/javaparser#3650]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
our `javaparser` 3.24.2 package varied from an embeded `MAVEN_BUILD_TIMESTAMP` value - probably
from https://github.com/javaparser/javaparser/blob/48dfd6d/javaparser-core/src/main/java-templates/com/github/javaparser/JavaParserBuild.java#L12
from https://github.com/javaparser/javaparser/blob/48dfd6d/javaparser-core/pom.xml#L29

There should be some way to create 2 bit-identical builds.

**Comment by jlerbsc** [comment]
I have no idea why this timestamp was added. Certainly to differentiate artifacts. It is better to base your comparison between the builds on other criteria.

**Comment by hazendaz** [comment]
fix is easy, add

```
        <!-- Reproducible Builds -->
        <project.build.outputTimestamp>1</project.build.outputTimestamp>
```

To the build.  It will auto update to timestamp of time of release.  The point to reproducible is that any tag can be rebuilt with same results.

In that java file, stop using ```build.timestamp``` as that is made up per this project.  Replace that with ```maven.build.timestamp```

And simply delete that from the pom.

I'll write up a PR for this.

**Comment by bmwiedemann** [comment]
For openSUSE, we have meanwhile solved it with
https://github.com/bmwiedemann/openSUSE/blob/0f56636e030af391df6d0d026e49fe546a715346/packages/j/javaparser/javaparser.spec#L97

Will still be good to have it more reproducible by default.

**Comment by jlerbsc** [comment]
There are apparently other ways to deal with this subject https://maven.apache.org/guides/mini/guide-reproducible-builds.html

**Comment by hazendaz** [comment]
@jlerbsc PR #3650 does address this here.
