### ISSUE TITLE
Calling JavaParserMethodDeclaration.declaringType() fails when declaring type is a record

### ISSUE THREAD

**Issue by Col-E** [javaparser/javaparser#3654]
Will be resolved upon completion of #3606

***

```java
public record Person (String name, String address) {
	boolean matchesName(Person other) {
		return name.equals(other.name);
	}
}
```
Resolving the method `matchesName` to a `JavaParserMethodDeclaration` value works correctly. However, attempting to then call `declaringType()` on that value fails.

```
java.lang.IllegalArgumentException: com.github.javaparser.ast.body.RecordDeclaration
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.toTypeDeclaration(JavaParserFactory.java:191)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.declaringType(JavaParserMethodDeclaration.java:74)
```

This is because in `JavaParserFactory.toTypeDeclaration(Node node, TypeSolver typeSolver)` there is no case for `RecordDeclaration`.

**Comment by jlerbsc** [comment]
I don't know if a record can be considered as a JavaParserClassDeclaration or if there are specifics. Seems to me that @MysterAitch has been working on integrating records into JP. Maybe he has a more precise idea on this point?

**Comment by jlerbsc** [comment]
This is no longer an issue in the current version of JP.
