### ISSUE TITLE
Replace variable declarations with an empty declaration and initialization

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#3659]
Hi, I need some little help, I'm trying to split variable declarations like:

```java
int x = 5;
ObjectOrClass newStuff = new ObjectOrClass();
```

into:

```java
int x;
x = 5
```
&
```java
ObjectOrClass newStuff;
newStuff = new ObjectOrClass();
```

How to do it the best way? I cannot use `ModifierVisitor` because from what I understand I can replace only this ONE particular node.

Thank you.

**Comment by PELock** [comment]
I came up with some household solution (I'm using visitors and prepending extra statement to the nearest block) but is there a way to return a list of statements in `ModifierVisitor`, that would be so much handy?

**Comment by jlerbsc** [comment]
The visitor does not work like this as the javadoc says "This visitor can be used to save time when some specific nodes needs to be changed. To do that just extend this class and override the methods from the nodes who needs to be changed , **returning the changed node**."

So a priori this is not how I will use this visitor but you can probably extend the ModifierVisitor which returns a Visitable object and do the work you want to do. NodeList is a visitable object.

**Comment by PELock** [comment]
I know they don't work that way, I'm really surprised it is so hard to replace one statement with multiple ones without doing some hacky code.

**Comment by jlerbsc** [comment]
JP is not a refactoring tool, in particular it allows you to manipulate the AST. Refactoring tasks are your responsibility.

**Comment by PELock** [comment]
This is some basic stuff, replacing one Node with a list of another and it's so damn impossible right now.

**Comment by PELock** [comment]
Hey @matozoid can you help me? Thank you.
