### ISSUE TITLE
Lexical preseving throws IllegalArgumentException on refactoring

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#3666]
The attached test case shows how the activation of lexical preseving looses output.
Version used: 3.24.4

Output:
lexicalPreserving=false: "literal".equals(var)
Exception in thread "main" java.lang.IllegalArgumentException: fromIndex(5) > toIndex(2)
	at java.util.SubList.<init>(AbstractList.java:624)
	at java.util.AbstractList.subList(AbstractList.java:484)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator$CalculatedSyntaxModel.sub(LexicalDifferenceCalculator.java:79)
	at com.github.javaparser.printer.lexicalpreservation.DifferenceElementCalculator.calculate(DifferenceElementCalculator.java:183)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatePropertyChange(LexicalDifferenceCalculator.java:180)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concretePropertyChange(LexicalPreservingPrinter.java:193)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.propertyChange(PropagatingAstObserver.java:62)
	at com.github.javaparser.ast.Node.lambda$notifyPropertyChange$5(Node.java:614)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.Node.notifyPropertyChange(Node.java:614)
	at com.github.javaparser.ast.expr.MethodCallExpr.setScope(MethodCallExpr.java:173)
	at eval.javaparser.ShowBugLexicalPreservingThrowsException.test(ShowBugLexicalPreservingThrowsException.java:36)
	at eval.javaparser.ShowBugLexicalPreservingThrowsException.run(ShowBugLexicalPreservingThrowsException.java:21)
	at eval.javaparser.ShowBugLexicalPreservingThrowsException.main(ShowBugLexicalPreservingThrowsException.java:16)

`
package eval.javaparser;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseProblemException;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.StringLiteralExpr;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class ShowBugLexicalPreservingThrowsException {

	String src = "var.equals(\"literal\")";

	public static void main(String[] args) {
		new ShowBugLexicalPreservingThrowsException().run();
	}

	void run() {
		test(false);
		test(true);
	}

	void test(boolean useLexicalPreserving) {
		Expression node = parse(src);

		if (useLexicalPreserving) {
			LexicalPreservingPrinter.setup(node);
		}

		MethodCallExpr mc = node.findFirst(MethodCallExpr.class).get();
		StringLiteralExpr stringLiteral = (StringLiteralExpr) mc.getArgument(0);

		Expression leftHandExpr = mc.getScope().get();
		mc.setArgument(0, leftHandExpr);
		mc.setScope(stringLiteral);

		String str;
		if (useLexicalPreserving) {
			str = LexicalPreservingPrinter.print(node);
		} else {
			str = node.toString();
		}
		System.out.println("lexicalPreserving=" + useLexicalPreserving + ": " + str);
	}

	Expression parse(String src) {
		JavaParser parser = new JavaParser();
		ParseResult<Expression> pr = parser.parseExpression(src);
		if (!pr.isSuccessful()) {
			throw new ParseProblemException(pr.getProblems());
		}
		return pr.getResult().get();
	}

}
`

**Comment by jlerbsc** [comment]
This bug seems a bit complex to me to deal with but a workaround consists in creating a new expression and possibly replacing the old expression with the new one.

Below is a simplified test case 

    @Test
    public void issue3666() {
        String src = "var.equals(\"literal\")";
        Expression node = StaticJavaParser.parseExpression(src);

        LexicalPreservingPrinter.setup(node);

        // here mc equals node there is no parent node
        MethodCallExpr mc = node.findFirst(MethodCallExpr.class).get();
        StringLiteralExpr stringLiteral = (StringLiteralExpr) mc.getArgument(0);
        Expression leftHandExpr = mc.getScope().get();
        
        // create a new expression
        MethodCallExpr mce = new MethodCallExpr(stringLiteral, mc.getNameAsString(), new NodeList(leftHandExpr)); 
        
        String str = LexicalPreservingPrinter.print(mce);
        System.out.println("lexicalPreserving="  + str);
    }

**Comment by magicwerk** [comment]
Great to get helpful feedback so fast! Unfortunately this seems not to be case nowadays for quite some projects, so thanks very much... Cheers

**Comment by jlerbsc** [comment]
Can this issue be closed?

**Comment by magicwerk** [comment]
IMHO this issue should be closed.  Obvioulsy it depends on your code whether lexical preservation works or not.
It's frustrating and time consuming to see it not work at all (see issue 3665) or encounter a meaningless exception as in this case.
Can you think of way of improving user experiencing? Or add a few sentences to the documentation how to use it?
Obvioulsy current usage is not reflected truely the documentation stating "You do not need to understand how it works internally unless of course, you are curious"...

**Comment by jlerbsc** [comment]
We do what we can in our free time to improve this tool. Thanks for understanding. 
What is important to note from my experience with lexical preservation is that "The event propagation is directed from the parent AST node to the child AST node".

**Comment by jlerbsc** [comment]
It seems that this issue is resolved in the current version.

Bellow the test case

    @Test
	public void issue3666() {
           String code="var.equals(\"literal\")";
	    Expression node = StaticJavaParser.parseExpression(code);

	    LexicalPreservingPrinter.setup(node);

	    // here mc equals node there is no parent node
	    MethodCallExpr mc = node.findFirst(MethodCallExpr.class).get();
	    StringLiteralExpr stringLiteral = (StringLiteralExpr) mc.getArgument(0);
	    Expression leftHandExpr = mc.getScope().get();
	    
	    // create a new expression
	    MethodCallExpr mce = new MethodCallExpr(stringLiteral, mc.getNameAsString(), new NodeList(leftHandExpr)); 
	    
	    assertEqualsStringIgnoringEol("\"literal\".equals(var)",  LexicalPreservingPrinter.print(mce));
	}
