### ISSUE TITLE
How to check if a class field is used inside a method

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#3669]
in this example 

```
class Demo{
int a;

void foo() {
    a = 5;
}
}


```
how do check if a has been used by the method foo?

**Comment by jlerbsc** [comment]
In this exemple you have to resolve the name expression ("a" in "a=5"). To do it you have to configure the symbol solver. For example:

    AssignExpr ae = ... // find the assign expression
    ae.getTarget().asNameExpr().resolve().isField(); // resolve the target of the assign expression and verify if it's a field

**Comment by jlerbsc** [comment]
I am closing this issue as we have answered the question.
