### ISSUE TITLE
Lexical preseving enters endless loop

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#3670]
The attached test case shows how the activation of lexical preseving creates an endless loop where the application hangs forever.
Version used: 3.24.4

Output:
old: public class Base {
}
new: public class Base {

    @MyAnnotation
    public static class Factory {
    }
}
old: public class Base {
}
--> APPLICATION NEVER FINISHES

`package eval.javaparser;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseProblemException;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ast.Modifier;
import com.github.javaparser.ast.Modifier.Keyword;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.expr.MarkerAnnotationExpr;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class ShowBugLexicalPreservingEndlessLoop {

	String src = "public class Base {}";

	public static void main(String[] args) {
		new ShowBugLexicalPreservingEndlessLoop().run();
	}

	void run() {
		test(false);
		test(true);
	}

	void test(boolean useLexicalPreserving) {
		ClassOrInterfaceDeclaration bd = parse(src);
		System.out.println("old: " + bd);

		if (useLexicalPreserving) {
			LexicalPreservingPrinter.setup(bd);
		}

		createFactory(bd);
		System.out.println("new: " + bd);
	}

	ClassOrInterfaceDeclaration parse(String src) {
		JavaParser parser = new JavaParser();
		ParseResult<BodyDeclaration<?>> pr = parser.parseBodyDeclaration(src);
		if (!pr.isSuccessful()) {
			throw new ParseProblemException(pr.getProblems());
		}
		return (ClassOrInterfaceDeclaration) pr.getResult().get();
	}

	ClassOrInterfaceDeclaration createFactory(ClassOrInterfaceDeclaration cls) {
		NodeList<Modifier> ms = Modifier.createModifierList(Keyword.PUBLIC, Keyword.STATIC);
		ClassOrInterfaceDeclaration factoryCls = new ClassOrInterfaceDeclaration(ms, false, "Factory");
		cls.getMembers().add(0, factoryCls);
		addAnnotation(factoryCls, "MyAnnotation");
		return factoryCls;
	}

	void addAnnotation(BodyDeclaration<?> node, String name) {
		MarkerAnnotationExpr annotation = new MarkerAnnotationExpr(name);
		node.addAnnotation(annotation);
	}
}
`

**Comment by jlerbsc** [comment]
There is certainly a bug in an obscure part of the code which calculates the difference between 2 syntactic elements. I suggest  the following workaround which consists in adding the new class (factory) after having completely initialized it.


     @Test
    public void issue3670() {
        considerCode("public class Base {}");

        LexicalPreservingPrinter.setup(cu);
        
        ClassOrInterfaceDeclaration cid = cu.findFirst(ClassOrInterfaceDeclaration.class).get();
        NodeList<Modifier> ms = Modifier.createModifierList(Keyword.PUBLIC, Keyword.STATIC);
        ClassOrInterfaceDeclaration factoryCls = new ClassOrInterfaceDeclaration(ms, false, "Factory");
        
        MarkerAnnotationExpr annotation = new MarkerAnnotationExpr("MyAnnotation");
        factoryCls.addAnnotation(annotation);
        
        cid.getMembers().add(0, factoryCls);
                
        System.out.println(LexicalPreservingPrinter.print(cu));
    }

**Comment by jlerbsc** [comment]
It looks like this issue is fixed in the current release.
