### ISSUE TITLE
How could I insert a statement before try statement in method?

### ISSUE THREAD

**Issue by masumcse1** [javaparser/javaparser#3676]
I have need bellow output . This line  "String result = null;" need to show before try statement . 
But it is showing inside of try statement . Here is my code : 

https://pastebin.mozilla.org/McXbnU7w

public Response saveProduct(ProductDto productDto) throws ServletException, IOException {
		      String result = null;
		try {
			createMyProduct.setProduct(productDto.getProduct());
			createMyProduct.execute(parameterMap);
			result = createMyProduct.getResult();
		
		} catch (BusinessException e) {
			return Response.status(Response.Status.BAD_REQUEST).entity(result).build();
		}
		

![image](https://user-images.githubusercontent.com/9381810/187091024-e36e80e5-0f89-4370-87de-8d26f2cd1b2d.png)

**Comment by jlerbsc** [comment]
I am closing this issue as there is no response to our request.
