### ISSUE TITLE
Function accepts a configuration but it does not do anything

### ISSUE THREAD

**Issue by ProfDoof** [javaparser/javaparser#3678]
Hi all, 

I'm knee-deep in y'all's codebase right now looking for example on how to override some of your printer functionalities because I'm trying to do some code canonicalization and I noticed that your default functions here accept a printer configuration but don't actually do anything with it. Just thought that was a bit odd and thought I would let y'all know.

https://github.com/javaparser/javaparser/blob/18893cba35bc281cbea04b5c5330722da0f9f3ba/javaparser-core/src/main/java/com/github/javaparser/printer/DefaultPrettyPrinter.java#L43-L54

**Comment by jlerbsc** [comment]
Hi @ProfDoof thank you for reporting this bug.
