### ISSUE TITLE
LineComment alwaysing trimming content

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#3681]
When creating a LineComment with a content starting with whitespace, that whitespace is thrown away.
This is done here: https://github.com/javaparser/javaparser/blob/a8eaeb3d00a86d4727cbd564d0e8d156815f52d4/javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java#L1772

I think it would be useful not to trim the content, so that the user get the possibility to control the exact content of comments. This is important when printing several line comments with content that should be aligned.

We cannot print this:

```
// a comment
//    something inlined
// b comment
```

Because this becomes:
```
// a comment
// something inlined
// b comment
```

I can provide a PR for this, if you agree with the idea

**Comment by jlerbsc** [comment]
Of course you are still one of the main contributors to this project. We are only trying to continue your work.
