### ISSUE TITLE
Method reference expression cannot be resolved 

### ISSUE THREAD

**Issue by kevin-rain** [javaparser/javaparser#3683]
public class MyService {

      public List<ResponseQueryOrderItem> queryList1(List<ResponseQueryOrderItem> list) {
         List<Long> collect = list.stream()
                .map(ResponseQueryOrderItem::getOrderId).collect(Collectors.toList());
         list(collect) ;
         return null;
     }

     public List<ResponseQueryOrderItem> queryList2(List<ResponseQueryOrderItem> list) {
         list(list.stream()
                .map(ResponseQueryOrderItem::getOrderId).collect(Collectors.toList())) ;
         return null;
     }

     private List<ResponseQueryOrderItem> list(List<Long> list){
         return new ArrayList<>();
     }
    } 

    public class ResponseQueryOrderItem {
      public long getOrderId() {
         return orderId;
      }
      private long orderId;
    }
queryList1 is success,but queryList2 is error

- UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to cpsskuOrdersImagesMapper.selectContractAndInvoiceByOrderId(list.stream().map(ResponseQueryOrderItem::getOrderId).collect(Collectors.toList()))', cause='null'}

version is 3.24.4

i think it's not perfect ,please how to resolve queryList2

**Comment by kevin-rain** [comment]
public class MethodVisitor extends VoidVisitorAdapter<Void> {
    @Override
    public void visit(MethodCallExpr n, Void arg) {
        ResolvedMethodDeclaration rmd = n.resolve();
        super.visit(n, arg);
    }
}

**Comment by kevin-rain** [comment]
can you help me,please ?

**Comment by jlerbsc** [comment]
It seems to be related to the method reference expression.

    public List<ResponseQueryOrderItem> queryList2(List<ResponseQueryOrderItem> list) {
    list(list.stream()
            //.map(ResponseQueryOrderItem::getOrderId).collect(Collectors.toList())) ;
            .map(resp -> resp.getOrderId()).collect(Collectors.toList())) ;
    return null;
}

**Comment by kevin-rain** [comment]
> It seems to be related to the method reference expression.
> 
> ```
> public List<ResponseQueryOrderItem> queryList2(List<ResponseQueryOrderItem> list) {
> list(list.stream()
>         //.map(ResponseQueryOrderItem::getOrderId).collect(Collectors.toList())) ;
>         .map(resp -> resp.getOrderId()).collect(Collectors.toList())) ;
> return null;
> ```
> 
> }

thankyou

**Comment by jlerbsc** [comment]
It seems that this issue is now resolved in the current version.
