### ISSUE TITLE
UnsolvedSymbolException  unable to find the value declaration corresponding to Arrays

### ISSUE THREAD

**Issue by Wouter1** [javaparser/javaparser#3689]
Trying to resolve the NameExp "Arrays" I get an unexpected error. 
Sorry for the large how-to-repro, to call resolve I have to set up , parse a java program and then dig into the parse to get access to the Arrays NameExp, and only then I can call resolve.. It would be great if there were a easier way to reproduce this. 

The static void main() program is just the same code as is in CODE, to show that the program that is in CODE actually works correctly.

How to reproduce:
```
package javaparser;

import java.util.Arrays;
import java.util.List;

import org.junit.Test;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.VariableDeclarationExpr;
import com.github.javaparser.ast.stmt.ExpressionStmt;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class ArraysResolveTest {

	public static void main(String[] args) {
		List<Integer> x = Arrays.asList(1, 2);
	}

	String CODE = "import java.util.Arrays;\n"
			+ "public class ArraysResolveTest {\n" + "\n"
			+ "	public static void main(String[] args) {\n"
			+ "				List<Integer> x = Arrays.asList(1, 2);\n"//
			+ "	}\n" + "}";

	@Test
	public void testResolve() {
		ParserConfiguration conf = new ParserConfiguration();
		CombinedTypeSolver typeSolver = new CombinedTypeSolver();
		typeSolver.add(new ReflectionTypeSolver(false));
		// FIXME add sources of jars source code etc
		// typeSolver.add(new JavaParserTypeSolver(new File(SOURCE_PATH)));
		// typeSolver.add(new JarTypeSolver(jarSourceFile));
		JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
		conf.setSymbolResolver(symbolSolver);
		JavaParser parser = new JavaParser(conf);

		CompilationUnit res = parser.parse(CODE).getResult().get();

		BodyDeclaration<?> mainmethod = res.getType(0).getMembers().get(0);
		ExpressionStmt statement = (ExpressionStmt) ((MethodDeclaration) mainmethod)
				.getBody().get().getStatements().get(0);
		VariableDeclarationExpr exp = (VariableDeclarationExpr) statement
				.getExpression();
		MethodCallExpr initvalue = (MethodCallExpr) exp.getVariable(0)
				.getInitializer().get();
		NameExpr scope = (NameExpr) initvalue.getScope().get();
		scope.resolve();
	}
}

```
with this pom
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>tudelft.utilities</groupId>
	<artifactId>j2p</artifactId>
	<version>1.0.0</version>

	<properties>
		<!-- Tell Maven we want to use Java 8 -->
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<!-- Tell Maven to treat all source files as UTF-8 -->
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>

		<dependency>
			<groupId>com.github.javaparser</groupId>
			<artifactId>javaparser-symbol-solver-core</artifactId>
			<version>3.24.2</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
</project>
```

Expected:
resolve() should give me a reference to the ```java.util.Arrays``` class as is imported in the CODE string. 

Error trace:
```
UnsolvedSymbolException{context='null', name='We are unable to find the value declaration corresponding to Arrays', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:187)
	at com.github.javaparser.ast.expr.NameExpr.resolve(NameExpr.java:164)
	at javaparser.ArraysResolveTest.testResolve(ArraysResolveTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by jlerbsc** [comment]
Hi @Wouter1 Your intention is apparently to find the type of the scope of the expression. However your code tries to find a declaration. In your case, just search for the scope type. I know the nuance is a bit confusing.

In this exemple note the usage of the method calculateResolvedType() on the scope expression.

     @Test
    void test3689() {
        String CODE = "import java.util.Arrays;\n"
                + "public class ArraysResolveTest {\n" + "\n"
                + " public static void main(String[] args) {\n"
                + "             List<Integer> x = Arrays.asList(1, 2);\n"//
                + " }\n" + "}";

        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        StaticJavaParser.setConfiguration(configuration);

        CompilationUnit cu = StaticJavaParser.parse(CODE);

        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);

        mces.forEach(mce -> {
            System.out.println(mce.toString());
            System.out.println(">>" + mce.resolve().toString()); // find the method declaration
            System.out.println(">>" + **mce.getScope().get().calculateResolvedType().describe()**); // find the type of the scope of the method call expression
        });
    }

**Comment by Wouter1** [comment]
@jlerbsc thanks for the quick response and help!

Yes I want to get the real type of the scope of "Arrays"..

With a little modification (removing a few "**" fro your code??) your code works here
```
	@Test
	public void test3689() {
		String CODE = "import java.util.Arrays;\n"
				+ "public class ArraysResolveTest {\n" + "\n"
				+ " public static void main(String[] args) {\n"
				+ "             List<Integer> x = Arrays.asList(1, 2);\n"//
				+ " }\n" + "}";

		ParserConfiguration configuration = new ParserConfiguration()
				.setSymbolResolver(new JavaSymbolSolver(
						new CombinedTypeSolver(new ReflectionTypeSolver())));
		StaticJavaParser.setConfiguration(configuration);

		CompilationUnit cu = StaticJavaParser.parse(CODE);

		List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);

		for (MethodCallExpr mce : mces) {
			System.out.println(mce.toString());
			System.out.println(">>" + mce.resolve().toString());
			// find the/ method declaration
			System.out.println(">>"
					+ mce.getScope().get().calculateResolvedType().describe());
			// find the type of the scope of the method call expression
		}
	}
```

not sure why you switched to the StaticJavaParser but I assume that's not needed. 

I was not aware of the "calculateResolvedType" method.  

Maybe you can also explain why resolve() did not work in this particular case? Should I always use "calculateResolvedType" instead of resolve?

**Comment by jlerbsc** [comment]
> With a little modification (removing a few "**" fro your code??) your code works here

This was to highlight a section of code

**Comment by jlerbsc** [comment]
> not sure why you switched to the StaticJavaParser but I assume that's not needed.

I'm using the class StaticJavaParser  to make test case creation easier.

**Comment by jlerbsc** [comment]
> Should I always use "calculateResolvedType" instead of resolve?

No it depends on what you want to do

> Maybe you can also explain why resolve() did not work in this particular case?

My understanding is that the resolve() method allows to get a declaration but in your case there is no declaration of the symbol 'Arrays' . Finally it is here that the nuance is a bit confusing because the Arrays class is declared in the import statements. But it seems to me that it is very specific to the case where we manipulate static data (method, class).

**Comment by Wouter1** [comment]
@jlerbsc  thanks for the clarifications!

So if I get you correct, it might still be a bug in resolve() but I can work around it in this case, using the calculateResolvedType ?

BTW it would be good if your explanation could be used to add some javadoc to resolve() and calculateResolvedType(),

**Comment by Wouter1** [comment]
@jlerbsc  it turned out that using calculateResolvedType does not alwasy cut it. Especially as I need to determine the type of the NameExpr (eg is it a name of a class or a variable)

I modified your test to show the problem and I dont see how calculateResolveType would help here.  You can see the problem in the "???" in the output text, I catch the exception to show the other cases work
```
@Test
	public void modifiedTest() {
		String CODE = "import java.util.Arrays;\n"
				+ "public class ArraysResolveTest {\n"
				+ "	public static void main(String[] args) {\n"
				+ "		Integer v = 3;\n"
				+ "		List<Integer> x = Arrays.asList(1, 2, v);\n"///
				+ "	}\n}";
		ParserConfiguration configuration = new ParserConfiguration()
				.setSymbolResolver(new JavaSymbolSolver(
						new CombinedTypeSolver(new ReflectionTypeSolver())));
		StaticJavaParser.setConfiguration(configuration);

		CompilationUnit cu = StaticJavaParser.parse(CODE);

		List<NameExpr> names = cu.findAll(NameExpr.class);

		for (NameExpr ne : names) {
			System.out.println(ne.toString());
			String type = "???";
			try {
				type = ne.resolve().toString();
			} catch (Exception e) {
			}
			System.out.println(">>" + type);
		}
	}

```

**Comment by jlerbsc** [comment]
I'm closing this issue as I think we've answered your question and JP is doing exactly what it needs to do. 

Briefly, the resolve() method makes it possible to obtain a ResolvedValueDeclaration which can be, for example, a field declaration or a variable declaration or even a declaration of an enumeration value... while the calculateResolvedType() method makes it possible to 'get the type of a node. 

In your case it seems that if the resolve() method does not allow you to obtain a declaration you had to adapt your processing either to know the type of the expression then to determine if it is a reference or not to take into account of the expression.
