### ISSUE TITLE
Remove "download as zip/tar.gz" from http://javaparser.org/

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#369]
I would say that using Maven or Gradle should be advertised.

**Comment by ftomassetti** [comment]
It is true that we should encourage people to use Maven or Gradle. However some users seem to want to do without such tools. I find that puzzling but from the questions we all receive it seems that someone just want to download jars manually

**Comment by matozoid** [comment]
I wouldn't be surprised if it is because there are two big buttons with download options right inside the page header at http://javaparser.org/ :-)

**Comment by UlhasDeshmukh** [comment]
Kindly review https://github.com/javaparser/javaparser/pull/480

**Comment by prayashm** [comment]
We can remove one download button, and change the other one to "Install using Maven"
and point it to either of these:
- [http://javaparser.org/#dependency-management](http://javaparser.org/#dependency-management)
- [https://github.com/javaparser/javaparser/wiki/Manual#maven](https://github.com/javaparser/javaparser/wiki/Manual#maven)

Should I do that?

**Comment by matozoid** [comment]
Please check the comments on #480 first.

**Comment by prayashm** [comment]
@matozoid Went over them.
The buttons at the top come with the automatic page generator, and can be edited by directly changing the `index.html` in `gh-pages` or using jekyll to generate the `index.html` from a local machine.

**Comment by matozoid** [comment]
How does using jekyll remove the buttons?

**Comment by matozoid** [comment]
Sounds like too much trouble right now - we'll look into redesigning the site some other time. Thanks everyone for helping!

**Comment by prayashm** [comment]
If we use jekyll ourselves, we can customize the theme to have buttons as we wish.
[Using a theme for Jekyll Site](https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/)

**Comment by matozoid** [comment]
If we do that, we probably want to redesign the whole thing, and that means a new discussion and a lot of effort. Now is not a good time for that - we're trying to get 3.0 released.

**Comment by matozoid** [comment]
@prayashm - we're nearing 3.0 Release Candidate, would you like to join in with #586 ?

**Comment by prayashm** [comment]
@matozoid sorry, into something else now.
