### ISSUE TITLE
Removing modifiers from method declaration results in loss of white space

### ISSUE THREAD

**Issue by steve-thousand** [javaparser/javaparser#3693]
When removing modifiers from a method declaration to make it package-private, I am seeing that all white space is being lost when printing with the LexicalPreservingPrinter. I was seeing this issue locally and noticed that [there is a test asserting this exact behavior.](https://github.com/javaparser/javaparser/commit/52bfa55b3f006b4132e839c961af954bd3553244#diff-469d6c7d73e2bc9738124f7fb71d294953092caa90ec171a317b48c004663e27R238)

```java
    @Test
    void removingModifiersWithExistingAnnotations() {
        considerCode(
                "class X {" + SYSTEM_EOL +
                        "  @Test" + SYSTEM_EOL +
                        "  public void testCase() {" + SYSTEM_EOL +
                        "  }" + SYSTEM_EOL +
                        "}" + SYSTEM_EOL
        );

        cu.getType(0).getMethods().get(0).setModifiers(new NodeList<>());

        String result = LexicalPreservingPrinter.print(cu.findCompilationUnit().get());
        assertEqualsStringIgnoringEol("class X {\n" +
                "  @Test\n" +
                "void testCase() {\n" +
                "  }\n" +
                "}\n", result);
    }
```

The fact that the test here asserts it makes me think that maybe this is expected behavior but it seems like odd expected behavior. I would expect that the white space preceeding the method declaration would be preserved. Is this a feature that is pending?

**Comment by steve-thousand** [comment]
Digging into the code, I see that the problem seems to occur inside of [this function](https://github.com/javaparser/javaparser/blame/master/javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Difference.java#L141), which attempts to remove preceeding whitespace. After removing the "public" modifier, if all previous tokens on that line are just whitespace it removes it all, seems it doesn't have any way of knowing that some of that whitespace is intentional indentation

**Comment by steve-thousand** [comment]
Looked around in the PRs and found that someone else already pointed out that this is a problem. I made a branch to see what would happen if the `considerEnforcingIndentation ` method was simplified to only remove one whitespace token and it fixes the modifier issue and no other tests break as a result. Does this mean that this is a good solution to the problem or are there other white space use-cases that aren't covered by tests?

https://github.com/javaparser/javaparser/pull/3694

**Comment by jlerbsc** [comment]
Thank you for reporting this bug.
I think the unit tests can be completed because it seems to me that they do not quite cover the case where there is an indentation.
