### ISSUE TITLE
Bug while parsing annotations with String literals containing ':'

### ISSUE THREAD

**Issue by JoaoRoxoNeves** [javaparser/javaparser#37]
I was trying to parse the following class:

```
public class Test {
    public static @interface SomeAnnotation {
        String value();
    }

    // Parser bug: the type of this field
    @SomeAnnotation("http://someURL.org/")
    protected Test test;
}
```

getType() on the FieldDeclaration of test returns a ReferenceType with:

```
//someURL.org/")
Test
```

It looks like the parser is treating the ':' character as some kind of separator, regardless of being inside a String literal...

(Tested on the latest version 1.0.12-SNAPSHOT as of this writing)

**Comment by ftomassetti** [comment]
I can replicate the problem but I guess you are wrong: it sees "//someURL.org/" as a comment

**Comment by ftomassetti** [comment]
Ok, I fixed this one, I will send a merge request

**Comment by ftomassetti** [comment]
Fixed by 392da9ccc2

**Comment by JoaoRoxoNeves** [comment]
It's working great. Thank you!

**Comment by ftomassetti** [comment]
Great, enjoy!
