### ISSUE TITLE
Use Java 8 in javaparser-core

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#370]
We've been keeping core at Java 6 for a while now, to keep backwards compatability with user projects that cannot upgrade to Java 7 or 8.

It seems there is no public support for Java 7 for a year now: http://www.oracle.com/technetwork/java/eol-135779.html

How about upgrading core to 8?

**Comment by ftomassetti** [comment]
I remember concerns about keeping Java 6 compatibility from @sebastiankirsch . I would like to hear from him if he still needs Java 6 compatibility

**Comment by sebastiankirsch** [comment]
If one can still parse Java6 code, I'm all for going to 8.
If not... well. I'm using JavaParser for finding dead code, mostly in legacy apps which may not yet be migrated to Java 7 or 8. That's all I can say really...

**Comment by DeepSnowNeeL** [comment]
I started to make builder methods like this one :

```
public CompilationUnit addImportWithoutDuplicates(String name) {
    if (getImports().stream().anyMatch(i -> i.getName().getName().equals(name)))
        return this;
    else
        return addImport(name, false, false);
}
```

Which benefits from java 1.8 & lambda, so if everybody agrees I would love to remove my actual 7-too-much-lines

```
 boolean alreadyImported = false;
        for (ImportDeclaration i : getImports()) {
            if (i.getName().getName().equals(name)) {
                alreadyImported = true;
                break;
            }
        }
```

**Comment by ftomassetti** [comment]
I am definitely in favor to move to Java 8

**Comment by matozoid** [comment]
Well, let's do it then.
