### ISSUE TITLE
How could I get the list of an AST's edges?

### ISSUE THREAD

**Issue by yilinfang** [javaparser/javaparser#3706]
In my task, I need to get all the edges in an AST(such as A -> B), how could I get all the edges from the CompilationUnit rather than travese the unit to get the edges?

**Comment by zhizhixiongxuwei** [comment]
AST结构应该没有边的概念

**Comment by jlerbsc** [comment]
There is no concept of graph in the JavaParser project. You have to build it yourself.

**Comment by jlerbsc** [comment]
@zhizhixiongxuwei Can you make comments in English so that everyone can benefit from your answer.

**Comment by jlerbsc** [comment]
@yilinfang I am closing this issue but you are free to reopen it if you have more specific questions to ask.
