### ISSUE TITLE
Cannot resolve var type.

### ISSUE THREAD

**Issue by pjcuser** [javaparser/javaparser#3707]
While parsing code such as the following:

```
for(var passport : p.getPassportList()) {
	var actualCash = passport.getFinalCash();
	...
   }
}
```

It hits an exception "java.lang.IllegalStateException: Cannot resolve `var` which has no initializer." while trying to calculate type of 'passport' as "n.getScope().get().calculateResolvedType().describe()".

Is var type resolution not supported or, is there a way to calculate or resolve it without causing exception?

**Comment by jlerbsc** [comment]
Hi @pjcuser can you give us a simple and full test case?

**Comment by jlerbsc** [comment]
This test is working properly

    void issue3707() {
        String CODE = 
                "public class A {\n" +
                "  void m() {\n" +
                "    var v = new Integer(0);\n" + 
                "  }\n" +
                "}";

        ParserConfiguration configuration = new ParserConfiguration()
                .setLanguageLevel(JAVA_10)
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        StaticJavaParser.setConfiguration(configuration);

        CompilationUnit cu = StaticJavaParser.parse(CODE);

        VariableDeclarationExpr vd = cu.findFirst(VariableDeclarationExpr.class).get();

        System.out.println(vd.calculateResolvedType().toString());
    }


with result


    ReferenceType{java.lang.Integer, typeParametersMap=TypeParametersMap{nameToValue={}}}

**Comment by pjcuser** [comment]
Yes, this simple test seems to work, but error occurs when I try to resolve the type of object `passport ` on which method `.getFinalCash()` is called. Can you test with similar scenario using `MethodCallExpr`?.

I'll create and post the sample code soon.
