### ISSUE TITLE
Line `Comment` not removed if in the middle of an `Expression`

### ISSUE THREAD

**Issue by dabico** [javaparser/javaparser#3718]
javaparser version: 3.24.4

---

I'm currently writing a Java source code processor. Implemented using JavaParser, it provides users with the ability to change exported code in various ways. One such change is the ability to remove different types of comments found within the source code. This is a very simple procedure, and it makes use of JavaParser as follows:

```java
public static String removeComments(String input) {
	Node node = StaticJavaParser.parse(input);
	List<Comment> comments = node.getAllContainedComments();
	node.getComment().ifPresent(comments::add);
	comments.forEach(Comment::remove);
	return node.toString();
}
```

Although this approach takes care of most cases of comments, I have noticed that if line comments are found within the middle of an expression, they are not removed. For instance, providing the following class as input:

```java
public class Markdown {
	static final Pattern inlineLink = Pattern.compile("(" + // Whole match = $1
		"\\[(.*?)\\]" + // Link text = $2
		"\\(" +
		"[ \\t]*" +
		"<?(.*?)>?" + // href = $3
		"[ \\t]*" +
		"(" +
		"(['\"])" + // Quote character = $5
		"(.*?)" + // Title = $6
		"\\5" +
		")?" +
		"\\)" +
		")", Pattern.DOTALL);
}
```

Will not result in any of the comments being removed.

**Comment by jlerbsc** [comment]
What comments are you talking about?

**Comment by jlerbsc** [comment]
It seems that in the current version 3.24.11-snapshot the comments are well removed and no longer appear.

This test case 

    @Test
	void issue3718() {
		considerCode(
				"class A {\n"
				+ "	Pattern inlineLink = Pattern.compile(\"(\" + // Whole match = $1\r\n"
				+ "		\"\\\\[(.*?)\\\\]\" + // Link text = $2\r\n"
				+ "		\"\\\\(\" +\r\n"
				+ "		\"[ \\\\t]*\" +\r\n"
				+ "		\"<?(.*?)>?\" + // href = $3\r\n"
				+ "		\"[ \\\\t]*\" +\r\n"
				+ "		\"(\" +\r\n"
				+ "		\"(['\\\"])\" + // Quote character = $5\r\n"
				+ "		\"(.*?)\" + // Title = $6\r\n"
				+ "		\"\\\\5\" +\r\n"
				+ "		\")?\" +\r\n"
				+ "		\"\\\\)\" +\r\n"
				+ "		\")\", Pattern.DOTALL);"
				+"}");
		List<Comment> comments = cu.getAllContainedComments();
		FieldDeclaration fd = cu.findFirst(FieldDeclaration.class).get();
		fd.getComment().ifPresent(comments::add);
		comments.forEach(Comment::remove);
		System.out.println(cu.toString());
	}

produces

    class A {

    Pattern inlineLink = Pattern.compile("(" + "\\[(.*?)\\]" + "\\(" + "[ \\t]*" + "<?(.*?)>?" + "[ \\t]*" + "(" + "(['\"])" + "(.*?)" + "\\5" + ")?" + "\\)" + ")", Pattern.DOTALL);
}

**Comment by jlerbsc** [comment]
I am closing this issue because it is not reproducible in the current version.
