### ISSUE TITLE
ParseProblemException

### ISSUE THREAD

**Issue by adrianopizzini** [javaparser/javaparser#3728]
Hi, I am using JavaParser 3.24.7 to parse a few opensource projects and I got an exception during the creation of the compilation unit for the file "src\core\lombok\javac\handlers\HandleVal.java" from lombok release 1.18.16

The error occurs in this part of code (second line of the block):
```
		if (localNode.shouldDeleteLombokAnnotations()) {
			JavacHandlerUtil.deleteImportFromCompilationUnit(localNode, val.class.getName());
			JavacHandlerUtil.deleteImportFromCompilationUnit(localNode, lombok.experimental.var.class.getName());
			JavacHandlerUtil.deleteImportFromCompilationUnit(localNode, var.class.getName());
		}
```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 107,col 64) "var" is not allowed here.

My code is very simple:
```
        File file = new File("D:\\Projects\\lombok-1.18.16\\src\\core\\lombok\\javac\\handlers\\HandleVal.java");
        SourceRoot sourceRoot = new SourceRoot(Path.of(file.getParent()));
        CompilationUnit comp = sourceRoot.parse("",file.getName());
```
[HandleVal.zip](https://github.com/javaparser/javaparser/files/9859202/HandleVal.zip)

**Comment by jlerbsc** [comment]
The 'var' keyword was introduced in java 10, so you need to configure the parser to support this version

**Comment by adrianopizzini** [comment]
Hi, thank you for the help...

I don´t think that is the problem because SourceRoot starts with LanguageLevel.JAVA_11. The problem still occurs even if I change the code to:
```
        SourceRoot sourceRoot = new SourceRoot(Path.of(file.getParent()));
        sourceRoot.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_17);
        CompilationUnit comp = sourceRoot.parse("",file.getName());
```

**Comment by jlerbsc** [comment]
I think it's a grammar error but I don't know JavaCC enough to modify the grammar. Maybe @MysterAitch  is somewhat available to support this issue. This error is produced by VarValidator.accept(..) and the statement below generates the error.

    JavacHandlerUtil.deleteImportFromCompilationUnit(localNode, var.class.getName());

**Comment by jlerbsc** [comment]
It seems that the VarType is assigned by a post processor which does not sufficiently check the context before positioning the type. So a PR is being developed.
