### ISSUE TITLE
Lexical preserving corrupts source when adding a modifier in first position

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#3761]
The attached test case shows how the activation of lexical preseving correpts source, i.e. it will not compile any more.
As you yesterday fixed #3750 (which is at least related from the effect on the source),
I checked it with the current version 3.24.9-SNAPSHOT, but it still fails.
Great to see you working on lexical preseving - I think it could be a very helpful feature, but it seems unfortunately not really production ready.

Output:
```
lexicalPreserving=false: class C {

    protected static String S = "s";
}

lexicalPreserving=true: class C { 
    staticprotected  String S = "s";
}
```

Source:
```
public class ShowBugLexicalCorruptsSource2 {

	static String src = "class C { \n"
			+ "    static String S = \"s\";\n"
			+ "}";

	public static void main(String[] args) {
		test(false);
		test(true);
	}

	static void test(boolean useLexicalPreserving) {
		TypeDeclaration<?> cu = StaticJavaParser.parseTypeDeclaration(src);

		if (useLexicalPreserving) {
			LexicalPreservingPrinter.setup(cu);
		}

		List<FieldDeclaration> fields = cu.findAll(FieldDeclaration.class);
		FieldDeclaration field = fields.get(0);

		List<Keyword> kws = field.getModifiers().stream().map(Modifier::getKeyword).collect(Collectors.toList());
		kws.add(0, Keyword.PROTECTED);
		field.setModifiers(kws.toArray(new Keyword[] {}));

		String str;
		if (useLexicalPreserving) {
			str = LexicalPreservingPrinter.print(cu);
		} else {
			str = cu.toString();
		}
		System.out.println("lexicalPreserving=" + useLexicalPreserving + ": " + str + "\n");
	}
}
```

**Comment by jlerbsc** [comment]
This is not quite the same case as the one you referenced (https://github.com/javaparser/javaparser/issues/3750). The lexical preservation function is very complex and has been at the center of issues for several years. We are gradually trying to offer a more reliable solution but it will take time. Thanks for understanding.
