### ISSUE TITLE
Support Jigsaw requires static 

### ISSUE THREAD

**Issue by saragluna** [javaparser/javaparser#3769]
We use `requires static xxx` in `module-info.java` in our project. When using javaparser, there's no method as `isStatic` for the ModuleRequiresDirective.  

https://github.com/javaparser/javaparser/blob/d3b54a0f7b44f07a9fee0b72e2a620b952557e00/javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleRequiresDirective.java#L118-L124

Do you think we can add a method called `isStatic` for `ModuleRequiresDirective`?

https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleDescriptor.Requires.Modifier.html
https://cr.openjdk.java.net/~mr/jigsaw/spec/api/java/lang/module/package-summary.html
https://www.oracle.com/corporate/features/understanding-java-9-modules.html
https://stackoverflow.com/questions/56170361/why-do-we-need-requires-static-in-java-9-module-system

**Comment by saragluna** [comment]
BTW, now it can be achieved by `hasModifier(Modifier.Keyword.STATIC)`.

**Comment by jlerbsc** [comment]
I am not very familiar with the modules but actually it seems to me quite legitimate to make this type of request. It will be included in the next version.
