### ISSUE TITLE
Split JavaConcepts test into smaller pieces

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#377]
JavaConcepts is probably an artifact from the old test setup, which was a few large classes that were parsed, and stuff was added to those classes when something had to be tested.

It should be easy, although tedious, to split it into a lot of small pieces in the dump tests.

**Comment by JulienVig** [comment]
Hi! I would like to help, is this issue still valid?

**Comment by matozoid** [comment]
Yes, you can give it a try! If you want to make good use of your time, make a PR with one or two tests so we (I ;-) ) can check if you're in the right direction.

**Comment by JimmyGan437** [comment]
Hi, is this issue still worked on? I'd like to help.

**Comment by jlerbsc** [comment]
I see no point in trying to refactor this test resource but if you want to propose an improvement you are free to do so, however it will require a lot of effort so as not to reduce the test opening. Otherwise I close this issue.

**Comment by jlerbsc** [comment]
Closed by https://github.com/javaparser/javaparser/pull/4167

Note that the implementation in the javaparser-core-testing-bdd project has been retained.
