### ISSUE TITLE
Lexical Preserving Fails To Remove Comment

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#3796]
The attached test case shows how the activation of lexical preseving fails to remove a comment.
Version used: 3.24.9

Output:

```
lexicalPreserving=false: public class MyClass {
}

lexicalPreserving=true: public class MyClass { 
	/** Comment */ 
	}
```

Source:
```
public class ShowBugLexicalPreservingFailsToRemoveComment {

	static String src = "public class MyClass { \n"
			+ "	/** Comment */ \n"
			+ "	@Rule String s0; \n"
			+ "} \n";

	public static void main(String[] args) {
		test(false);
		test(true);
	}

	static void test(boolean useLexicalPreserving) {
		BodyDeclaration<?> cu = StaticJavaParser.parseBodyDeclaration(src);

		if (useLexicalPreserving) {
			LexicalPreservingPrinter.setup(cu);
		}

		List<FieldDeclaration> fields = cu.findAll(FieldDeclaration.class);
		FieldDeclaration field = fields.get(0);

		field.remove();

		String str;
		if (useLexicalPreserving) {
			str = LexicalPreservingPrinter.print(cu);
		} else {
			str = cu.toString();
		}
		System.out.println("lexicalPreserving=" + useLexicalPreserving + ": " + str + "\n");
	}
}
```

**Comment by jlerbsc** [comment]
Hi @magicwerk i cannot reproduce your issue with the current snapshot release.

**Comment by magicwerk** [comment]
That's somehow strange, I just retested it again with 3.24.10-SNAPSHOT from master and got the same behavior...
Or what branch are you refering to?

C:\dev\Java\Sources\External\javaparser>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

C:\dev\Java\Sources\External\javaparser>git log -1
commit 41cf8cdacfdc8dcf2e317731344758772cdccd3b (HEAD -> master, origin/master, origin/HEAD)
Author: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Date:   Wed Dec 14 11:49:10 2022 +0000

    chore(deps): update dependency org.apache.maven.plugins:maven-checkstyle-plugin to v3.2.0

**Comment by jlerbsc** [comment]
It's my fault, I'm actually reproducing your issue.
