### ISSUE TITLE
Lexical Preserving: determine whether active / printing loses comments if not activated

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#3800]
I'm looking for a way to print out a CompilationUnit as good as possible, i.e. if lexical preserving has been setup for a node, the output should come from LexicalPreservingPrinter.print(), otherwise it should be formatted as done by cu.toString().

I was hoping that LexicalPreservingPrinter.print() would provide such fallback behavior, but this seems not the case. Even worse, it loses all comments (see test case below).

As workaround I was looking for a method like LexicalPreservingPrinter.isActive(Node), but was not able to find one. How can I detect whether lexical preserving  has been setup for a node? Or is there another approach how a good formatting could be realized for both cases?

The attached test case shows how the output a CompilationUnit is missing comments if printed out with LexicalPreservingPrinter.print() without having lexical preserving activated with LexicalPreservingPrinter.setup().

Version used: 3.24.9

Output:

```
Source:
public class MyClass { 
	/** Comment */ 
	@Rule String s0; 
} 


PrettyPrinter:
public class MyClass {

    /**
     * Comment
     */
    @Rule
    String s0;
}

LexicalPreservingPrinter:
public class MyClass {

    @Rule
String s0;
}

```

Source:
```
public class ShowBugLexicalPreservingPrintWithoutSetupLosesComments {

	static String src = "public class MyClass { \n"
			+ "	/** Comment */ \n"
			+ "	@Rule String s0; \n"
			+ "} \n";

	public static void main(String[] args) {
		BodyDeclaration<?> cu = StaticJavaParser.parseBodyDeclaration(src);
		System.out.println("Source:\n" + src + "\n");
		System.out.println("PrettyPrinter:\n" + cu + "\n");
		System.out.println("LexicalPreservingPrinter:\n" + LexicalPreservingPrinter.print(cu) + "\n");
	}
}

```

**Comment by jlerbsc** [comment]
Lexical preserving printer must be initialized before it is used.

**Comment by magicwerk** [comment]
Yes, obviously. But is there a way to find out whether it was initialized for a node, something like LexicalPreservingPrinter.isActive(Node)?

**Comment by jlerbsc** [comment]
No, this functionality does not exist but it would not be complex to develop. How would you like to use it to resolve this issue? Do you think it is essential for what you want to do?

**Comment by magicwerk** [comment]
I would not call it essential, but very helpful... If I cannot determine it from the node itself using a method like LexicalPreservingPrinter.isActive(Node), I have to store the information whether I activated LP for a node explicitly somewhere else.

**Comment by jlerbsc** [comment]
I will make a small adaptation for the next version which should be released at the end of the year.

**Comment by magicwerk** [comment]
great, thanks!

**Comment by jlerbsc** [comment]
> I would not call it essential, but very helpful... If I cannot determine it from the node itself using a method like LexicalPreservingPrinter.isActive(Node), I have to store the information whether I activated LP for a node explicitly somewhere else.

There is no need to store a state you can only do it like this

    cu.containsData(LexicalPreservingPrinter.NODE_TEXT_DATA)
