### ISSUE TITLE
Get method descriptor for ResolvedMethodDeclaration / MethodCallExpr

### ISSUE THREAD

**Issue by 0verhead** [javaparser/javaparser#3808]
## Description
While using javaparser I realized that it is cumbersome to get the corresponding method descriptor for a MethodCallExpr or for the ResolvedMethodDeclaration you get when resolving the MethodCallExpr.

Similar to #3559, #3615 and #2059, #3498, I would imagine that it would be useful to easily get the descriptor for a method call (or rather the respective method declaration).

Thus for a method call like `Math.pow(4.2, 3)` you would quickly get `(DD)D` (meaning (double, double) -> double).

### Problem
A MethodCallExpr resolves to a ResolvedMethodDeclaration, but that can actually be an instance of:
1. JavaParserMethodDeclaration
2. ReflectionMethodDeclaration
3. JavassistMethodDeclaration
4. maybe even more? The 3 above were the ones I encountered.

Of those 3, the JavaParserMethodDeclaration seemed to be the only one where it was somewhat straightforward get the descriptor.

### Possible Improvement?
In the end, I was able to get the descriptors for all the encountered cases. 
For ReflectionMethodDeclaration and JavassistMethodDeclaration, it was necessary to access the private fields `method` and `ctMethod`.
Now, I am wondering if it would be appreciated if I made a pull request adding a straightforward way to get the descriptor in all cases.

## More detailed use case example
Couple of months ago I had to match nodes in call tree xml files exported from JProfiler to methods and method calls in source code.  Each node basically looks like this (simplified):
```
<node leaf="true" class="java.lang.Math" methodName="pow" methodSignature="(DD)D" />
```

Take for example:
```
public void doMath() {
    DecimalFormat df = new DecimalFormat(".00");
    double dblResult = Math.pow(4.2, 3);
}
```
The corresponding (sub) tree in the xml file could look like this:
```
<node leaf="false" class="main.java.components.MyClass" methodName="doMath" methodSignature="()V">
    <node leaf="true" class="java.lang.Math" methodName="pow" methodSignature="(DD)D" />
</node>
```

So given the xml file (alongside other things to be done), I needed to get the full qualified path and the method descriptor (method signature) of the methods that were called  to reliably pair them to the right nodes.

In this simple example `Math.pow` and `<node leaf="true" class="java.lang.Math" methodName="pow" methodSignature="(DD)D" />`.
Of course this example could effortlessly be solved in a simpler way, but imagine for instance a scenario where a method is overloaded.

**Comment by jlerbsc** [comment]
Hi @vanHekthor Can you detail your PR by illustrating how tedious it is to get the corresponding method descriptor for a MethodCallExpr or for the ResolvedMethodDeclaration?

**Comment by 0verhead** [comment]
@jlerbsc To be more precise, figuring out the solution was tedious.  The actual solution itself does not have a shocking amount of lines. There may even be a simple, clean solution I am not seeing.

## Getting the method descriptors for each case:

A MethodCallExpr instance can be resolved as usual
```
ResolvedMethodDeclaration rmd = methodCall.resolve();
```

### Expectation
Now here, you would expect that a Resolved<ins>MethodDeclaration</ins> has something like a `toDescriptor()` as the class MethodDeclaration has such a method. It does not.

Depending on the actual instance of  `rmd` I had to write the following code lines to get the method descriptor.

### 1. rmd instanceof JavaParserMethodDeclaration
The simplest case:
```
JavaParserMethodDeclaration jpmd = (JavaParserMethodDeclaration) rmd;
MethodDeclaration methodDeclaration = jpmd.getWrappedNode();
String descriptor = methodDeclaration.toDescriptor();
```

### 2. rmd instanceof JavassistMethodDeclaration
The easiest way I found here was to get access to the private field `ctMethod` of JavassistMethodDeclaration.
```
try {
    Field privateField = JavassistMethodDeclaration.class.getDeclaredField("ctMethod");
    privateField.setAccessible(true);
    CtMethod javassistMethod = (CtMethod) privateField.get(rmd);

    String descriptor = javassistMethod.getMethodInfo().getDescriptor();
} catch (...) {
    ...
}
```

### 3. rmd instanceof ReflectionMethodDeclaration
Same idea as with JavassistMethodDeclaration and the ctMethod field: Get access to the private field `method` of ReflectionMethodDeclaration.
But unfortunately you can not get the method descriptor as conveniently from the Method class as from the CtMethod class.
Instead I used ASM's [Type.getMethodDescriptor](https://gitlab.ow2.org/asm/asm/-/blob/master/asm/src/main/java/org/objectweb/asm/Type.java#L580).
```
try {
    Field privateField = ReflectionMethodDeclaration.class.getDeclaredField("method");
    privateField.setAccessible(true);
    Method reflectionMethod = (Method) privateField.get(rmd);

    String descriptor = // do the same as ASM's Type.getMethodDescriptor
} catch (...) {
    ...
}
```

## What the PR would do
As mentioned in the beginning <ins>MethodDeclaration</ins> has a `toDescriptor` method.
I would like to match the functionality of Resolved<ins>MethodDeclaration</ins> to the (I think) reasonable expectation that you also get a `toDescriptor` method.

### Rough implementation plan

- Add `toDescriptor` to the interface ResolvedMethodDeclaration
- Add implementations for the classes implementing ResolvedMethodDeclaration, basically what I outlined above but without Java Reflection as the implementations obviously are inside the classes and have access to private fields
- Add a toDecriptor method for JavaParserEnumDeclaration.ValuesMethod and JavaParserEnumDeclaration.ValueOfMethod, which also implement ResolvedMethodDeclaration (haven't thought about it very much, but I suppose that it shouldn't be too hard)

**Comment by jlerbsc** [comment]
Hi @vanHekthor Seems reasonable to me. Maybe you can also take inspiration from what is done in the MethodDeclaration class.

**Comment by vanHekthor** [comment]
I did a PR, but I am not sure, if it was ok to include a javassist jar for the test. Got my inspiration from [here](https://github.com/javaparser/javaparser/issues/2205#issuecomment-871949162).

**Comment by 0verhead** [comment]
@jlerbsc  I did a PR, but I am not sure, if it was ok to include a javassist jar for the test. Got my inspiration from [here](https://github.com/javaparser/javaparser/issues/2205#issuecomment-871949162).

**Comment by jlerbsc** [comment]
Tests should be kept as simple as possible.

**Comment by 0verhead** [comment]
To my limited knowledge, there is no other way to check the descriptor of an instance of JavassistMethodDeclaration.
Excluding this case would also probably not be the right way.

Is there an idea that comes to your mind for this situation?

**Comment by jlerbsc** [comment]
There are already libraries in the resources that can be reused for specific test cases
