### ISSUE TITLE
Two qustion about using type & declaration. Resolve jars which wasn't imported .

### ISSUE THREAD

**Issue by LeoYelton** [javaparser/javaparser#3809]
I have two question below:
1. Why I can judge type isNested  in declaration but cannot judge it in ClassOrInterfaceType?
2. If I try to resolve some of java file , but their dependency jar is not registered in symbolresolver . How to resolve it without using jar? In details, can jp build a phantom class to resolve when no jar were import and use jar in self customized level when jars were import . maybe it is a complex requirement. 

Thanks.

**Comment by jlerbsc** [comment]
> 2\. If I try to resolve some of java file , but their dependency jar is not registered in symbolresolver . How to resolve it without using jar? 

You cannot resolve a declaration which is not registered in symbol solver.

**Comment by LeoYelton** [comment]
> > 2. If I try to resolve some of java file , but their dependency jar is not registered in symbolresolver . How to resolve it without using jar?
> 
> You cannot resolve a declaration which is not registered in symbol solver.

If some of jar were not registered.  Every place invoke 'resolve' method to resolve those not registered jar will cause exception and abort the code logic . So if I want to ignore some of type cannot resolve . I have to wrap every resolve method with try catch.

**Comment by jlerbsc** [comment]
> 1. Why I can judge type isNested  in declaration but cannot judge it in ClassOrInterfaceType?

This is probably historic because the javaparser-core module produces an AST from a java parser and the symbol solver module enriches the AST by providing expression resolution, for example...

**Comment by LeoYelton** [comment]
> > 1. Why I can judge type isNested  in declaration but cannot judge it in ClassOrInterfaceType?
> 
> This is probably historic because the javaparser-core module produces an AST from a java parser and the symbol solver module enriches the AST by providing expression resolution, for example...

Thanks , I read jp documentation and some issue before ,  so is there any way to transform ?

**Comment by Yelixing** [comment]
> > 1. Why I can judge type isNested  in declaration but cannot judge it in ClassOrInterfaceType?
> 
> This is probably historic because the javaparser-core module produces an AST from a java parser and the symbol solver module enriches the AST by providing expression resolution, for example...

I found one way just now, StaticJavaParser.getConfiguration().getSymbolResolver().get().calculateType('') .  😋 Thank for you reply. Hope can consider about the 'resolve method' suggestion.

**Comment by jlerbsc** [comment]
This is a very important refactoring job that will take a lot of time

**Comment by LeoYelton** [comment]
> This is a very important refactoring job that will take a lot of time

Thank for your reply. You're so kind.

**Comment by jlerbsc** [comment]
I'm closing this issue because I think I answered the question. If not, you can reopen it.
