### ISSUE TITLE
Change bitfields into EnumSets

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#381]
Modifiers are giving some bugreports thanks to their lack of typing. An EnumSet would force a contract that avoids these problems.

**Comment by DeepSnowNeeL** [comment]
It could be integrated to my work if you want & released with 3.0 since
it's breaking changes.

Le lun. 18 juil. 2016 12:00, Danny van Bruggen notifications@github.com a
écrit :

**Comment by matozoid** [comment]
I prefer keeping increments as small and focused as possible.
