### ISSUE TITLE
Inner class name resolusion error when annotation and block-comment are presented

### ISSUE THREAD

**Issue by CirQ** [javaparser/javaparser#3811]
Hi, there, I found an unexpected problem when I was parsing inner class with both annotations and block-comments, below is a running example. I've tested it on **3.24.2** and **3.24.8**, both versions end with wrong results.

Code:
```kotlin
fun main(){
    val program =
    """
        class Main {
        
            /* comment */ class Foo1 {}
            
            @Annotation class Foo2 {}
            
            /* comment */ @Annotation class Bar1 {}
            
            @Annotation /* comment */ class Bar2 {}
            
        }
    """.trimIndent()

    val cu = JavaParser().parse(program).result.get()
    cu.accept(object: VoidVisitorAdapter<Any?>(){
        override fun visit(n: ClassOrInterfaceDeclaration, a: Any?){
            println(n.name)
            println("----------------")
            super.visit(n, a)
        }
    }, null)
}
```

Output:
```
Main
----------------
Foo1
----------------
Foo2
----------------
Bar1
----------------
/* comment */
Bar2                 <--- wrong!
----------------
```

Anyone who knows the reason or how can I solve this issue? Thanks in advance!

**Comment by CirQ** [comment]
One more problem, for code (with line comment):

```java
class Main {
    @Annotation
    // comment
    class C {}
}
```

The result is:
```
// comment
C
```

**Comment by jlerbsc** [comment]
Have you try to use getNameAsString() method because getname method returns an AST node (SimpleName)?

**Comment by CirQ** [comment]
> Have you try to use getNameAsString() method because getname method returns an AST node (SimpleName)?

This one returns the correct result, thanks!

BTW, does it mean the results in the original issue are as expected? Why the AST name node contains the comments only when there are annotations before them?

**Comment by jlerbsc** [comment]
> BTW, does it mean the results in the original issue are as expected?

Yes it corresponds to how JP works.

https://tomassetti.me/java-comments-parsing/

**Comment by CirQ** [comment]
> > BTW, does it mean the results in the original issue are as expected?
> 
> Yes it corresponds to how JP works.
> 
> https://tomassetti.me/java-comments-parsing/

Thanks for your reply, that's great!
