### ISSUE TITLE
Add empty line after/before statement

### ISSUE THREAD

**Issue by marcluque** [javaparser/javaparser#3831]
I've been searching for a way to add empty lines such that printing code looks "prettier". I've stumbled upon this Stackoverflow post: https://stackoverflow.com/questions/70889680/javaparser-removes-empty-lines that describes how to print a parsed file in a fashion that maintains indentation, new lines, etc.
When trying the `LexicalPreservingPrinter` I got a few errors, e.g.:
`Exception in thread "main" java.lang.RuntimeException: Range not present on node package xyz;`
However, no errors when using `compilationUnit.toString` which uses `DefaultPrettyPrinter` I presume. From what I understood in some other issues with the `LexicalPreservingPrinter`, it's simply missing some maintenance. But, hence, unfortunately not available for printing, I assume.

Now I'm wondering, assuming it's somehow possible to add new lines to generated code, would it then be possible to print them using the `DefaultPrettyPrinter`?

To make this more concrete (assuming I can print new lines with `DefaultPrettyPrinter`), suppose I have the following:
```java
var someVar = new VariableDeclarationExpr(PrimitiveType.intType(), "someName");
var methodCallExprStmt = new ExpressionStmt(new MethodCallExpr(new NameExpr("this"), "init"));
var comment = methodCallExprStmt.setComment(new LineComment("Some comment"));
var block = new BlockStmt().addStatement(someVar).addStatement(methodCallExprStmt);
```
The output (invoking `block.toString()`) looks like this:
```
{
    int someName;
    // Some comment
    this.init();
}
```

This is what I would like it to look like:
```
{
    int someName;

    // Some comment
    this.init();
}
```
How would I go about adding the new line?

**Comment by jlerbsc** [comment]
Hi @marcluque LexicalPreservingPrinter is indeed maintained but it cannot be used for what you want to do.
I think the best way to do this would be to extend the DefaultPrettyPrinterVisitor and to setup a DefaultPrettyPrinter instance with your own VisitorFactory. I haven't tried this but it should look something like this

        CompilationUnit cu = parse(code);
        PrinterConfiguration configuration = new DefaultPrinterConfiguration();
        // TestVisitor is your own visitor
        Function<PrinterConfiguration, VoidVisitor<Void>> visitorFactory = (config) -> new TestVisitor(config);
        Printer printer = new DefaultPrettyPrinter(visitorFactory, configuration);
        return printer.print(cu.findFirst(ClassOrInterfaceDeclaration.class).get());

and your custom DefaultPrettyPrinterVisitor 

    public class TestVisitor extends DefaultPrettyPrinterVisitor {

        public TestVisitor(PrinterConfiguration configuration) {
            super(configuration);
        }
    
        @Override
        public void visit(final ClassOrInterfaceDeclaration n, final Void arg) {
            printer.print("test");
        }
    }

**Comment by marcluque** [comment]
Hi @jlerbsc, thank you for the quick response!

I see, thanks for the info about the `LexicalPreservingPrinter`. I just tried implementing your suggested solution. It seems that `SourcePrinter` only has package-private constructors, this is the compilation error:
```
error: no suitable constructor found for SourcePrinter(PrinterConfiguration)

constructor SourcePrinter.SourcePrinter(PrettyPrinterConfiguration) is not applicable
      (argument mismatch; PrinterConfiguration cannot be converted to PrettyPrinterConfiguration)
constructor SourcePrinter.SourcePrinter(PrinterConfiguration) is not applicable
      (SourcePrinter(PrinterConfiguration) is not public in SourcePrinter; cannot be accessed from outside package)
```

Am I missing something here? Or could I get a source printer instance from somewhere else?

**Comment by jlerbsc** [comment]
Yes you are right. Fortunately there is the possibility to instantiate the DefaultPrettyPrinterVisitor class without defining the SourcePrinter. I changed the example.

**Comment by jlerbsc** [comment]
To better integrate the printer you can add the printer in the CompilationUnit

    cu.printer(printer);
    // and then print your code like this
    System.out.println(cu.toString());

**Comment by marcluque** [comment]
Oh shoot, I must have overseen that! Thanks for the fix ^^

It works just as expected now, thank you very much for the quick and resourceful help!

This is how I adapted `visit(LineComment n, Void arg)` to achieve a new line before comments.
```diff
- if (!getOption(ConfigOption.PRINT_COMMENTS).isPresent()) {
-     return;
- }
- printer.print("// ").println(normalizeEolInTextBlock(n.getContent(), "").trim());
+ printer.println().print("// ").println(Utils.normalizeEolInTextBlock(n.getContent(), "").trim());
```

I hope this helps anyone stumbling across a similar issue.
