### ISSUE TITLE
No enum constant com.github.javaparser.ParserConfiguration.LanguageLevel.JAVA_18

### ISSUE THREAD

**Issue by k-wall** [javaparser/javaparser#3833]
Our project uses impsort-maven-plugin which uses javaparser.  We are considering moving to Java 18 but notice that javaparser doesn't yet support that language level.

Is there a plan to support Java 18 soon?

**Comment by jlerbsc** [comment]
Hi @k-wal For the moment, there are no plans to integrate support for Java 18 specificities.

**Comment by k-wall** [comment]
Thank you for the prompt response.

**Comment by jlerbsc** [comment]
It seems that java 18 does not bring major changes that have an impact on code parsing (except maybe Pattern Matching for switch). Do you agree with this observation?

**Comment by k-wall** [comment]
@jlerbsc yes. I agree.  Sorry for the late reply.

However as is now [superseded](https://jdk.java.net/18/), maybe this issue should be closed in favour of #3907

**Comment by jlerbsc** [comment]
No it's not useful, we'll go gradually ;-)

**Comment by jlerbsc** [comment]
Because pattern matching for switch is a Java 18 preview feature, it is not required to support this release.

**Comment by jlerbsc** [comment]
Here you will find a specific issue regarding support for pattern matching for switch which is a preview feature https://github.com/javaparser/javaparser/issues/4211
