### ISSUE TITLE
Changing ReturnStmt by IfStmt

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3850]
I'm trying to automatize change of code like:

```
return (a>b) ? 1 : 2;
```
into
```
if (a > b) {
  return 1
} else {
  return 2;
}
```

I tried the following:

		ConditionalExpr ternary = (ConditionalExpr) node;
		Node parent = ternary.getParentNode().get();

		Expression condition = ternary.getCondition();
		Expression thenExpr = ternary.getThenExpr();
		Expression elseExpr = ternary.getElseExpr();

		if (parent instanceof ReturnStmt) {
			Node newNode = new IfStmt(condition, new ReturnStmt(thenExpr), new ReturnStmt(elseExpr));
			return node.replace(newNode); // <-- this should be parent.replace(newNode)
		} else {
			return false;
		}

But it fails with:

```
java.lang.ClassCastException: class com.github.javaparser.ast.stmt.IfStmt cannot be cast to class com.github.javaparser.ast.expr.Expression (com.github.javaparser.ast.stmt.IfStmt and com.github.javaparser.ast.expr.Expression are in unnamed module of loader 'app')
	at com.github.javaparser.ast.stmt.ReturnStmt.replace(ReturnStmt.java:151)
	at com.github.javaparser.ast.Node.replace(Node.java:583)
	at eu.solven.cleanthat.language.java.refactorer.mutators.AvoidInlineConditionals.processNotRecursively(AvoidInlineConditionals.java:75)
```

Related code is:

```
    @Override
    @Generated("com.github.javaparser.generator.core.node.ReplaceMethodGenerator")
    public boolean replace(Node node, Node replacementNode) {
        if (node == null) {
            return false;
        }
        if (expression != null) {
            if (node == expression) {
                setExpression((Expression) replacementNode);  <--- My case breaks here.
                return true;
            }
        }
        return super.replace(node, replacementNode);
    }
```

Any hint for this useCase?

Thanks

**Comment by jlerbsc** [comment]
Hi @blacelle you are asking to replace an expression with a statement. You have to ask the parent node to replace one statement with another.

**Comment by blacelle** [comment]
Thanks for pinpointing my issue. The correct code is :

	ConditionalExpr ternary = (ConditionalExpr) node;
	Node parent = ternary.getParentNode().get();

	Expression condition = ternary.getCondition();
	Expression thenExpr = ternary.getThenExpr();
	Expression elseExpr = ternary.getElseExpr();

	if (parent instanceof ReturnStmt) {
		Node newNode = new IfStmt(condition, new ReturnStmt(thenExpr), new ReturnStmt(elseExpr));
		return parent.replace(newNode);
	} else {
		return false;
	}
