### ISSUE TITLE
Java 17 support roadmap

### ISSUE THREAD

**Issue by reuben-tonna-ixaris** [javaparser/javaparser#3857]
What is the plan to support java 17 features please.  

The attached sample application results in parsing errors caused by plugin impsort-maven-plugin which depends on the javaparser.  We suspect that the root cause of the problem might be the javaparser.  We tried the latest version of the parser available (3.24.10) but the issue persists.

[impsort-issues.zip](https://github.com/javaparser/javaparser/files/10443448/impsort-issues.zip)

**Comment by jlerbsc** [comment]
Hi @reuben-tonna-ixaris 
Although JP does not support all features of JDK17 (eg sealed classes) your code is parsed correctly by JP.

    @Test
	void issue3857() {
		String code = 
				"public class Application {\r\n"
				+ "\r\n"
				+ "    public void receive(final Exception exception) {\r\n"
				+ "        if (exception instanceof IllegalStateException illegalStateException) {\r\n"
				+ "            System.out.println(\"I'm an illegal state exception!\");\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "}";
		StaticJavaParser.getParserConfiguration().setLanguageLevel(LanguageLevel.JAVA_17);
		CompilationUnit cu = StaticJavaParser.parse(code);
		System.out.println(cu.toString());
	}

This unit test correctly displays the parsing result of the class.

    public class Application {

    public void receive(final Exception exception) {
        if (exception instanceof IllegalStateException illegalStateException) {
            System.out.println("I'm an illegal state exception!");
        }
    }
}

Besides, there is currently no road map on full support of Java 17.

**Comment by ctubbsii** [comment]
It looks like the original issue that triggered the creation of this issue was user error, resulting in the language level not being set correctly to `LanguageLevel.JAVA_17`. The issue reported here is not a bug with JP

**Comment by jlerbsc** [comment]
It's reassuring even if java 17 support is not complete.

**Comment by reuben-tonna-ixaris** [comment]
setting maven.compiler.release to 17 solves the issue as suggested.  Thanks

**Comment by jlerbsc** [comment]
Hi @reuben-tonna-ixaris Thanks for confirming.
