### ISSUE TITLE
`UnsupportedOperationException` when trying to resolve a type in an argument which is an EnclosedExpr

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser#3859]
# Problem

Given the following code

    import java.util.function.Consumer;
    
    class Demo {
        void foo(Consumer<String> arg) {}
        void print(Object arg) {}
        public void bar() {
            foo(s->print(s));
        }
        public void baz() {
            foo((s->print(s)));
        }
    }

Resolving the type of  the lambda expression used as an argument in `bar()` works fine. Also resolving the name used in the lambda expression  `bar()` works fine. 

However both operations fail with `java.lang.UnsupportedOperationException`s when attempted for the lambda expression defined `baz`.

Notice the only difference between both cases is the extra `(...)` around the lambda expression in `baz`.

# Analysis

The problems are caused by missing handling of EnclosedExpr in the code related to arguments in an MethodCallExpr.

**Comment by jlerbsc** [comment]
Hi @abego Thank you for this reporting but, on JDK8 & eclipse, both expressions generate compilation error in your example. An error-free compilation is a prerequisite to use Javaparser

> foo((s->{s;}));
> or foo(s->{s;});

Syntax error, insert "VariableDeclarators" to complete LocalVariableDeclaration

**Comment by jlerbsc** [comment]
I'm closing the issue because I think I answered the question. Of course if this is not the case you can reopen it.

**Comment by abego** [comment]
Hi @jlerbsc, you are right, the code originally given in the description does not compile. 
In my attempt to provide you with a "minimal reproducible example" I seem to have removed too much code ;-)

So instead of
```
...
foo((s->{s;}));
...
```
is should say
```
...
foo((s->print(s)));
...
```

I updated the sample code in the issue description and the unit test accordingly.

**Comment by abego** [comment]
@jlerbsc how can I reopen the issue? 
I don't see an "Reopen" button or so on this page.

![screenshot](https://user-images.githubusercontent.com/696535/213812539-0e967b0f-4a38-4a13-96d9-169d33953b43.png)

**Comment by jlerbsc** [comment]
Hi  @abego Thank you for your PR with which I agree in broad outline. I have a few comments on this one. In general, you could avoid mixing code that fixes the problem with code that is refactoring. Could you also avoid having commits that fix issues on other commits.

**Comment by jlerbsc** [comment]
I'm starting to have difficulty analyzing your PR could you redo one that also takes into account my various remarks. Thanks again for your time.

**Comment by abego** [comment]
@jlerbsc Thank you for taking the time to review and comment my PR. I will re-work it, taking your remarks into account. 

BTW: Could you please read my comment https://github.com/abego/javaparser/commit/4ef762593b41896b9519b6ef19a62c6077bb3818#r97696213 and suggest how to proceed with it.

**Comment by abego** [comment]
Hi @jlerbsc, what is the suggested approach regarding the next changes I am going to push? Should I create new Pull Requests? I.e. one for the "fix problem" changes and one for the refactorings?

**Comment by jlerbsc** [comment]
Yes indeed that would be better. Maybe do a first PR for the refactoring then another one that solves the problem based on this refactoring

**Comment by abego** [comment]
@jlerbsc I just pushed the "pure" fix of the issue in a new branch.

Following the "Red - Green - Refactor" Cycle I started with the failing test and the minimal changes to fix the issue. The refactorings will come in a next step, after you reviewed the first PR.

**Comment by abego** [comment]
Here already my
# Suggested Refactorings

## Improve TypeExtractor#visit(LambdaExpr, Boolean)

In TypeExtractor#visit(LambdaExpr, Boolean) the expression
```
demandParentNode(node, IS_NO_ENCLOSED_EXPR)
```
is repeated 3 times.

Suggestion: assign value to new variable "Node parent" and use 3 times.


## Improve TypeExtractor#getParamPos

In TypeExtractor#getParamPos the expression
```
demandParentNode(node, IS_NO_ENCLOSED_EXPR)
```
is repeated 2 times.

Suggestion: assign value to new variable "Node parent" and use 2 times.


## IS_NOT_ENCLOSED_EXPR

IS_NOT_ENCLOSED_EXPR is defined identically (and private) in TypeExtractor and LambdaExprContext.

Suggestion: move constant to a class accessible to both TypeExtractor and LambdaExprContext and make it public. (Optionally: change from constant to static method and move...)
Open question: where is a good place for the constant(/method)?


## Shared code in TypeExtractor#getParamPos and LambdaExprContext#pos

This code fragment from method TypeExtractor#getParamPos 
```
for (int i = 0; i < call.getArguments().size(); i++) {
    Expression expression = call.getArguments().get(i);
    while (expression instanceof EnclosedExpr) {
        expression = ((EnclosedExpr) expression).getInner();
    }
    if (expression == node) return i;
}
throw new IllegalStateException();
```
and this code fragment from method LambdaExprContext#pos
```
int i = 0;
for (Expression p : callExpr.getArguments()) {
    while (p instanceof EnclosedExpr) {
        p = ((EnclosedExpr) p).getInner();
    }
    if (p == param) {
        return i;
    }
    i++;
}
throw new IllegalArgumentException();
```
are semantically equivalent, just using different kind of for-statements.

Suggestion: extract to method, to be called from both locations. 
Open questions: How to name the method? Where to put the method? 


## Shared code to traverse the `inner` path of EnclosedExpr
In the CommonValidators constructor this ("old") code
```
while (target instanceof EnclosedExpr) {
    target = ((EnclosedExpr) target).getInner();
}
```
is semantically equal to code in TypeExtractor#getParamPos
```
while (expression instanceof EnclosedExpr) {
    expression = ((EnclosedExpr) expression).getInner();
}
```
which is semantically equal to code in JavaParserFacade#solveArguments
```
while (parameterValue instanceof EnclosedExpr) {
    parameterValue = ((EnclosedExpr) parameterValue).getInner();
}
```

Suggestion: extract to method, to be called from all locations. 
Open questions: How to name the method? Where to put the method?

**Comment by jlerbsc** [comment]
Hi @abego 
Thanks for making the effort to separate refactoring from bug fixing. There's refactoring that you don't have to separate from the other PR because it's obvious. I am thinking in particular of the following points "Improve TypeExtractor#visit(LambdaExpr, Boolean)" and "Improve TypeExtractor#getParamPos" .
Regarding "IS_NOT_ENCLOSED_EXPR", it is a predicate that applies to expressions so in my opinion the most appropriate class to carry this function is the Expression class.
In this case "Shared code in TypeExtractor#getParamPos and LambdaExprContext#pos" the method applies to an expression which contains arguments (for example MethodCallExpr, ObjectCreationExpr...) therefore it seems appropriate to carry this method by the interface NodeWithArguments. The only problem is that we risk introducing a dependency between an interface and a concrete class. One way to remedy this would be to add a getArgument() method in the NodeWithArguments interface which would accept a filter (of the Predicate type for example). The method could be called getPosition or getArgumentPosition...
I didn't have time to look precisely at this point "Shared code to traverse the inner path of EnclosedExpr". The job obliges.
Sorry for my English I am not a virtuoso of the language of Shakespeare. :(

**Comment by abego** [comment]
Hi @jlerbsc , thanks. The first items are clear and I agree. 

Just the "Shared code in TypeExtractor#getParamPos and LambdaExprContext#pos" suggestion I don't understand fully. I don't understand how to get from a new getArgument(Predicate<...>) method in NodeWithArguments to handling the "inner" path traversal necessary for getArgumentPosition(). Maybe just give the final solution and I will use it.

Alternatively I suggest to move the new "getArgumentPosition(...)" method into a new utility class `NodeWithArgumentsUtil` e.g. located next to the `NodeWithArguments` interface. This way we don't pollute the interface with implementation dependencies but still allow for simple reuse.
```
public class NodeWithArgumentsUtil() {
    private NodeWithArgumentsUtil() {}

    public static int getArgumentPosition(
            NodeWithArguments<?> nodeWithArguments, Node argument) {
        for (int i = 0; i < nodeWithArguments.getArguments().size(); i++) {
            Expression expression = nodeWithArguments.getArguments().get(i);
            while (expression.isEnclosedExpr()) {
                expression = expression.asEnclosedExpr().getInner();
            }
            if (expression == argument) return i;
        }
        throw new IllegalStateException();
    }
}
```

**Comment by jlerbsc** [comment]
Yes indeed a Predicate is not the right function but here is what I meant. These methods are implementeed in interface NodeWithArguments

    /*
     * Returns the position of an argument applying no filter.
     */
    default int getArgumentPosition(Expression argument) {
    	return getArgumentPosition(argument, expr -> expr);
    }
    
    /*
     * Returns the position of an argument applying a filter.
     */
    default int getArgumentPosition(Expression argument, Function<Expression, Expression> provider) {
    	if (argument == null) {
    		throw new IllegalStateException();
    	}
        for (int i = 0; i < getArguments().size(); i++) {
            Expression expression = getArguments().get(i);
            expression = provider.apply(expression);
            if (expression == argument) return i;
            break;
        }
        throw new IllegalStateException();
    }

Using it like this

    Function<Expression, Expression> excludeEnclosedExpr = expr -> {
		while (expr.isEnclosedExpr()) {
			expr = expr.asEnclosedExpr().getInner();
        }
		return expr;
	}; 
	
	@Test
	void testArgumentPosition() {
		considerCode(
				"class Foo {\n"
				+ " List<Integer> arr = new ArrayList<>();\n"
				+ "	public String getAttr(int i) {\n"
				+ "		return arr.get(((i)));\n"
				+ "	}\n"
				+ "}");
		MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
		Expression arg = mce.getArgument(0);
		Expression innerExpr = arg.asEnclosedExpr().getInner().asEnclosedExpr().getInner();
		assertEquals(0, mce.getArgumentPosition(innerExpr, excludeEnclosedExpr)); // with a filter on EnclosedExpr
		assertEquals(0, mce.getArgumentPosition(arg)); // with no filter
	}

**Comment by abego** [comment]
Hi @jlerbsc, thanks, this makes much more sense. 

I will provide a new PR to cover the refactorings once the "fix" PR (https://github.com/javaparser/javaparser/pull/3873) is merged.

One question:
- Please have a look at your implementation of `getArgumentPosition(Expression, Function<Expression, Expression>)`. In the loop I see a `break;`. I guess this is not correct as it will not allow us to find arguments at positions > 0.
