### ISSUE TITLE
Resolving types in maven dependencies

### ISSUE THREAD

**Issue by fedeb95** [javaparser/javaparser#3863]
Hi, I'm not sure if this is already implemented in JavaParser, but what I'd like to do is, when parsing the source code of a given maven project, resolve symbols also in the dependencies of said maven project (of course if sources are available), including transitive dependencies. Is there a symbol solver that does this already?

The way I'm creating it now is the following:
```
TypeSolver reflection = new ReflectionTypeSolver();
            TypeSolver pathSolver = new JavaParserTypeSolver(path + "/src/main/java/");
            TypeSolver typeSolver = new CombinedTypeSolver(reflection, pathSolver);
            JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
            StaticJavaParser.getParserConfiguration()
                    .setSymbolResolver(symbolSolver)
                    .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_8)
                    .setAttributeComments(false);
```
I'm doing it for multiple project paths so this is why you see a `path` variable. This correctly resolves symbols found in standard Java classes and in my project, but not in maven dependencies of the project.

If not already available, how should I proceed in implementing it, either contributing to JavaParser or with custom code, if you have any pointers on where to start?

**Comment by jlerbsc** [comment]
Hi @fedeb95 I think what you are looking for is the JarTypeSolver.

**Comment by jlerbsc** [comment]
> resolve symbols also in the dependencies of said maven project (of course if sources are available)

Source files are not required.

**Comment by jlerbsc** [comment]
I'm closing the issue because I think I answered the question. Of course if this is not the case you can reopen it.

**Comment by fedeb95** [comment]
Hi, yes that's what I needed for resolving types it seems. Do I need to create an instance of JarTypeSolver for each jar ? They can be a lot, it would be cool if a type solver that takes a path, say, to the local maven repository and solves for everything. I don't know if this is outside the scope of the library though. It should be easy to create custom logic given that JarTypeSolver exists.

**Comment by jlerbsc** [comment]
Yes you need to create an instance of JarTypeSolver for each jar.
