### ISSUE TITLE
Fully qualified type use is misread as field access

### ISSUE THREAD

**Issue by raphw** [javaparser/javaparser#3870]
When registering a visitor for the following code:

```java
public class Sample {
    String m(int x) {
        return x + pkg.Other.X;
    }
}
```
two `FieldAccessExpr` are passed to a visitor on the method body: One for `pkg.Other.X` and one for `pkg.Other`. The latter is obviously just an import, not a field access. 

Would it be possible to detect this when parsing?

**Comment by jlerbsc** [comment]
Hi @raphw It's not possible to detect this when parsing but you can certainly do that by querying the AST. It's hard to be more specific because you haven't said what you want to do.

**Comment by raphw** [comment]
I see, I fully understand that but was confused by the issued event.

Is there a convenient way to filter such false-positives if the reminder of the source is available?

**Comment by jlerbsc** [comment]
What are you trying to do?

**Comment by raphw** [comment]
I am trying to discover the declaring types of all fields that are read within a method of a source file.

**Comment by jlerbsc** [comment]
Depending on your context you may need to resolve the expression to get the declaration. Give us a more concrete example of what you are trying to do.

**Comment by jlerbsc** [comment]
For exemple from a method call expression you can get the package name of the class which declares the method

> mce.resolve().getPackageName()

**Comment by jlerbsc** [comment]
Is this exemple what you want to do?

    @Test
	void test() {
		String code =
				"class Foo {\n"
				+ "		String attr;\n"
				+ "		String m() {\n"
				+ "			return attr;\n"
				+ "		}\n"
				+ "	}";
		CompilationUnit cu = JavaParserAdapter.of(createParserWithResolver(defaultTypeSolver())).parse(code);
		VoidVisitor<Void> visitor = new VoidVisitorAdapter<Void>() {
			@Override
		    public void visit(final NameExpr n, final Void arg) {
		        System.out.println(n.calculateResolvedType().describe());
		    }
		};
		cu.accept(visitor, null);
	}

**Comment by jlerbsc** [comment]
Is this code snippet useful to you?

**Comment by raphw** [comment]
Thanks, I only had time to look into it again today. I did not find the methods you suggest. For `defaultTypeSolver`, I set:

```
new JavaParserTypeSolver("./src/main/java")
```

but I could not make sense of `createParserWithResolver`. How would you create the `JavaParser` that is needed as an argument here?

---

So what I got is the following:

```java
package a;
public class A {
    String m() {
        return b.B.X;
    }
}

package b;
public class B {
    public static final String F = "foo";
}
```

With the following parser code:

```java
public class ParserSample {
    public static void main(String[] args) throws Exception {
        TypeSolver solver = new JavaParserTypeSolver("./src/main/java");
        ParserConfiguration configuration = new ParserConfiguration();
        configuration.setSymbolResolver(new JavaSymbolSolver(solver));
        JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser(configuration));
        CompilationUnit unit = parser.parse(new File("./src/main/java/a/A.java"));
        unit.getTypes().forEach(type -> {
            type.getMethods().forEach(m -> {
                m.getBody().ifPresent(b -> b.accept(new VoidVisitorAdapter<>() {
                    @Override
                    public void visit(FieldAccessExpr n, Object arg) {
                        super.visit(n, arg);
                    }
                }, null));
            });
        });
    }
}
```

What I would have hoped for was a way to only receive `FieldAccessExpr` for actual field accesses, not for the package expression. This is what I hoped the `TypeSolver` could do for me somehow.

**Comment by jlerbsc** [comment]
This unit test class implements AbstractSymbolResolutionTest which has this method.

    protected JavaParser createParserWithResolver(TypeSolver typeSolver) {
        return new JavaParser(new ParserConfiguration().setSymbolResolver(symbolResolver(typeSolver)));
    }

    protected SymbolResolver symbolResolver(TypeSolver typeSolver) {
    	return new JavaSymbolSolver(typeSolver);
    }

    protected TypeSolver defaultTypeSolver() {
    	return new ReflectionTypeSolver();
    }

**Comment by raphw** [comment]
Alright. So I infer that there is no good way of filtering the second hit on a `FieldAccessExpr` but to try to resolve the `scope` of it? In this case, I would simply assume that a failed resolution would point to a package and move on.

**Comment by amihaiemil** [comment]
@raphw I found this Issue while searching for something similar. I think you have to try and resolve the scope yourself. 

As far as I can see, JavaParser does not model the different types of ``*name`` from Java's grammar (``typeName``, ``packageName``, ``packageOrTypeName``, ``expressionName``, ``methodName``, ``ambiguousName``). All of them go in JavaParser as ``Name``.

I was searching for an appropriate ``expressionName`` AST Node in JavaParser and all I can find is ``FieldAccessorExpr``, which seems the only practical scenario for ``expressionName``, if it has a scope. If it doesn't have a scope, then ``NameExpr`` (which encapsulates a simple name, without scope) is to be used.

I also noticed, in a lot of places where ``typeName`` is used, JavaParser uses ``Type`` (most likely ``ClassOrInterfaceType``).

They did model the ``PackageDeclaration`` and ``ImportDeclaration`` (as nodes, not as expressions) so I think the logic with the renaming names is: ``typeName`` is ``Type``/``ClassOrInterfaceType`` and ``expressionName`` is either ``NameExpr`` (no scope) or ``FieldAccessorExpr`` (when it has scope). 

So I would go with resolving FieldAccessorExpr and if I get yet another FieldAccessorExpr (the scope) which does not resolve, then it must be a package declaration. 

Hope this helps? :D

**Comment by jlerbsc** [comment]
> Alright. So I infer that there is no good way of filtering the second hit on a `FieldAccessExpr` but to try to resolve the `scope` of it? In this case, I would simply assume that a failed resolution would point to a package and move on.

Hi @raphw , the method resolve on an expression returns you a declaration which can be the declaration of a field, of a class... If you only want to process declarations relating to a field you must filter your result according to the declaration which is returned.

**Comment by jlerbsc** [comment]
I'm closing this issue because I think we tried to answer your questions. If this is not the case, you can of course reopen it or open a new issue on a new subject.
