### ISSUE TITLE
CompileUnit.toString() outputs 

### ISSUE THREAD

**Issue by peacepassion** [javaparser/javaparser#389]
First, this library provides great ability for parsing Java source code. Thanks for your work.  

I am using JavaParser to improve the quality of my library [ButterCookie](https://github.com/peacepassion/ButterCookie/tree/encoding_err) for extending Butterknife.  And strange things about character encoding happened.   

I leverage JavaParser to extract annotation out Java source file and output to the build directory. And when the source code contains Chinese string and OS is Windows 7, the output content of Chinese string become mess. However, everything is normal on Mac.  

The whole library link is https://github.com/peacepassion/ButterCookie/tree/encoding_err.  

The code used for extracting annotation is below:  

``` groovy
  void deleteAnnotationsFromSource(LibraryVariant variant) {
    String sourcePath = getCopiedSource(variant)
    List<File> files = getAllSourceFiles(sourcePath)
    DeleteAnnotationVisitor visitor = new DeleteAnnotationVisitor()
    files.each { File file ->
      CompilationUnit cu = JavaParser.parse(file, "UTF-8")
      List<TypeDeclaration> types = cu.getTypes()
      types.each { TypeDeclaration type -> deleteAnnotationFromClass(visitor, type)
      }

      file.text = cu.toString()
    }
  }

  void deleteAnnotationFromClass(DeleteAnnotationVisitor visitor, TypeDeclaration type) {
    List<BodyDeclaration> members = type.getMembers()
    members.each { BodyDeclaration member ->
      if (member instanceof MethodDeclaration) {
        visitor.visit((MethodDeclaration) member, null)
      } else if (member instanceof FieldDeclaration) {
        visitor.visit((FieldDeclaration) member, null)
      } else if (member instanceof TypeDeclaration) {
        deleteAnnotationFromClass(visitor, (TypeDeclaration) member)
      }
    }
  }

  public static class DeleteAnnotationVisitor extends ModifierVisitorAdapter {
    @Override
    Node visit(MethodDeclaration n, Object arg) {
      return n.setAnnotations(filterAnnotations(n.getAnnotations()))
    }

    @Override
    Node visit(FieldDeclaration n, Object arg) {
      return n.setAnnotations(filterAnnotations(n.getAnnotations()))
    }

    List<AnnotationExpr> filterAnnotations(List<AnnotationExpr> annotations) {
      if (annotations == null || annotations.size() == 0) {
        return annotations
      }
      annotations.each { AnnotationExpr annotation ->
        if (ARRAY.contains(annotation.name.toString())) {
          annotations.remove(annotation)
        }
      }
      return annotations
    }
  }
```

Reproduce env:  
Windows 7  

Reproduce step:  
1. command line run: ./gradlew clean assDeb  
2. check output file: ./library/build/source/release/me/ele/buttercookie/LibraryActivity.java  

Please help check this issue. Thanks in advance.  This is very important for the use of this library in China.

**Comment by matozoid** [comment]
Okay, before we try to solve old bugs: JavaParser 2.5.0 is out since yesterday, could you see if that fixes it?

**Comment by matozoid** [comment]
I installed Android Studio on Windows 7, checked out that branch, ran the command line thing, opened the file, and I see some code and a few Chinese characters. I'm not sure what I'm supposed to see?

**Comment by peacepassion** [comment]
The output file is ./library/build/source/release/me/ele/buttercookie/LibraryActivity.java. And the right content should be like following, especially the green Chinese string.  
![image](https://cloud.githubusercontent.com/assets/5254121/16970864/ab8d6d5e-4e51-11e6-9834-37c0b5e729cc.png)
The above output is content output on Mac.  

And the result on Win 7 looks as following.  
![image](https://cloud.githubusercontent.com/assets/5254121/16979089/d2946d18-4e91-11e6-9f99-266d0c0f0110.png)

**Comment by peacepassion** [comment]
I will try JavaParser2.5.0 asap.

**Comment by peacepassion** [comment]
I tried JP2.5.0, and I failed to build because of #391 . So I tried 2.3.0, and the result is the same.

**Comment by matozoid** [comment]
I tried building again and again, and keep getting the correct Chinese text. There has to be a piece of code that forgets to explicitly set the encoding and falls back to system encoding, which is not utf-8 on Windows. Since I can't reproduce, I can't help looking for it :(
