### ISSUE TITLE
How can I figure if the visit() is called for the last method?

### ISSUE THREAD

**Issue by TheLittleNaruto** [javaparser/javaparser#3897]
I have implemented a MethodVisitor by extending VoidVisitorAdapter like this:

```
public class MethodParser extends VoidVisitorAdapter<Void> {

    int count = 0;
    private final OnCompleteListener mListener;

    public MethodParser(OnCompleteListener listener) {
        this.mListener = listener;
    }

    @Override
    public void visit(MethodDeclaration n, Void arg) {
       System.out.println(n.getName().asString());
       count++;
       if(count == lastVisted) // Here lastVisited would be last method; currently there is no way to figure that out.
             mListener.onCompleted();
    }

}
```
However there is no way to figure out if the function visit() is executed for the last method(Node). Is there any token parameter which would return the last call of the visit method?

**Comment by jlerbsc** [comment]
Hi @TheLittleNaruto you have to call the super.visit(..) method for the AST to be completely visited.

**Comment by TheLittleNaruto** [comment]
> Hi @TheLittleNaruto you have to call the super.visit(..) method for the AST to be completely visited.

Ok thanks! BTW it's visiting all the methods with current implementation too. But as I said, there is no way I could find to figure if the visit() function is called for last method of the supplied Java file. @jlerbsc I want to notify the caller of MethodVisitor once all the methods are visited.

**Comment by jlerbsc** [comment]
Yes indeed you are right because you are only interested in method declarations. For your question it's a bit complicated to know what you want to do because you are comparing a number with a node which is never initialized. Maybe if you tell us what you want to do we can help you more.

**Comment by TheLittleNaruto** [comment]
> Yes indeed you are right because you are only interested in method declarations. For your question it's a bit complicated to know what you want to do because you are comparing a number with a node which is never initialized. Maybe if you tell us what you want to do we can help you more.

That "lastVisited" variable I would expect to get from MethodDeclaration object itself. I mean there has to be a token sort of thing which would tell wheather current visit() is last iteration over methods. You may ignore that "lastVisited" thing, I have added that just to explain what I want.

**Comment by jlerbsc** [comment]
There is no mechanism of this type in JP, it is up to you to implement it. For example, you can create a list of method declarations and loop through that list instead of using a visitor. You can also count method declarations and use that counter as an argument in your visitor.
For example

    node.findAll(MethodDeclaration.class); give you a list of MethodDeclaration in a node.

**Comment by TheLittleNaruto** [comment]
> There is no mechanism of this type in JP, it is up to you to implement it. For example, you can create a list of method declarations and loop through that list instead of using a visitor. You can also count method declarations and use that counter as an argument in your visitor. For example
> 
> ```
> node.findAll(MethodDeclaration.class); give you a list of MethodDeclaration in a node.
> ```

Thank you! This helped :)
