### ISSUE TITLE
Add OSGi metadata to javaparser-core

### ISSUE THREAD

**Issue by rombert** [javaparser/javaparser#390]
It would be great if you could add OSGi metadata to javaparser-core to make it simpler to reuse the code in OSGi environments.

A good start would be exporting everything except `com.github.javaparser.ast.internal` with version 0.0.0 - assuming you don't want to do fine-grained OSGi versioning for now.

**Comment by matozoid** [comment]
Would you be willing to submit a PR for this? I don't think any of the committers can do this without reading up on OSGi.

**Comment by rombert** [comment]
Let's see :-)

Submitted #394
