### ISSUE TITLE
Hi, find a resolve method bug when using symbol resolver

### ISSUE THREAD

**Issue by LeoYelton** [javaparser/javaparser#3900]
When giving a method of same name always get wrong method. I failed to submit the example before and forgot which file cause this problem. You can make an example such as 
```
class Main{
   public HaveSeveralSameNameMethodsClass cls = getInstance(); 
   public void method1(){
       String result =  cls.invokeB("3");//resolve this statement or expression
    }
}

```
```
class  HaveSeveralSameNameMethodsClass {
   public void invokeB(String param){  // case1
   }
   public String invokeB(T param){   // case2
       return ...;
    }
}
```

when calculate the real method by java parser , it always get the top method of same name . In this case , it will get case1 sometimes. And in fact it should match case2.

**Comment by jlerbsc** [comment]
This example does not compile. Can you submit a test case that reproduces your error?

**Comment by LeoYelton** [comment]
> This example does not compile. Can you submit a test case that reproduces your error?

I'm sorry about that. I'm so busy recently .  Upside code is a pseudo code I just write , represent the meaning.  I forgot where file is. If I find the detail code. I will give you one more reply.
The symbolResolver I use is 
3.24.0 also.

**Comment by jlerbsc** [comment]
I close this issue because without a reproducible test case we are not able to investigate the cause of the problem. But you can reopen it as soon as you can offer us a test case.
