### ISSUE TITLE
Unable to resolve method call argument declaration

### ISSUE THREAD

**Issue by sgIOlas** [javaparser/javaparser#3905]
Hi everyone, I am trying to use JavaParser for the following tasks:
1. Find all method calls and their arguments. This was pretty straightforward and doable using the CompilationUnit and MethodCallExpr.
2. Resolve where those arguments were declared. That is, line and initial value of the variable used as argument. This on the other hand has been pretty confusing since I don't know what to do once I have the argument nodes.

The only updated reference I could find regarding the symbol resolver was this [one](https://github.com/javaparser/javasymbolsolver-maven-sample/blob/master/src/main/java/com/yourorganization/maven_sample/MyAnalysis.java) but it did not help that much. I would appreciate if anyone could lend a hand, thanks in advance.

**Comment by jlerbsc** [comment]
>  initial value of the variable used as argument
Are you talking about data-flow analysis (https://en.wikipedia.org/wiki/Data-flow_analysis)?
In JP you can resolve a method invocation to find its declaration, you can find out the type of an argument. But you can't get flow graph control or data flow?

**Comment by sgIOlas** [comment]
> > initial value of the variable used as argument
> > Are you talking about data-flow analysis (https://en.wikipedia.org/wiki/Data-flow_analysis)?
> > In JP you can resolve a method invocation to find its declaration, you can find out the type of an argument. But you can't get flow graph control or data flow?

As you pointed out, I would need DFA functionality but I guess I did not fully understood the capabilities of JavaSymbolSover. It seems that for this use case I would be better off using something like CodeQL, Is that right?

**Comment by jlerbsc** [comment]
I don't know codeQL but the choice basically depends on what you want to achieve. If you want to transform your code you will definitely need a tool like Javaparser.

> codeQL: "Discover vulnerabilities across a codebase with CodeQL, our industry-leading semantic code analysis engine. CodeQL lets you query code as though it were data. Write a query to find all variants of a vulnerability, eradicating it forever."

**Comment by sgIOlas** [comment]
> I don't know codeQL but the choice basically depends on what you want to achieve. If you want to transform your code you will definitely need a tool like Javaparser.
> 
> > codeQL: "Discover vulnerabilities across a codebase with CodeQL, our industry-leading semantic code analysis engine. CodeQL lets you query code as though it were data. Write a query to find all variants of a vulnerability, eradicating it forever."

There is no need for me to transform the code. Judging by the examples available [here](https://codeql.github.com/docs/codeql-language-guides/analyzing-data-flow-in-java/#), CodeQL seems to be a perfect fit.

I will close the issue now, thank you for the help @jlerbsc!
