### ISSUE TITLE
Supporting Java 19 and more

### ISSUE THREAD

**Issue by jtama** [javaparser/javaparser#3907]
Hi,
Is there a plan to support higher versions than 19-Preview language compatibility ?

Many thanks.

**Comment by jlerbsc** [comment]
Hi @jtama For the moment the support of Java 19 is not planned. Javaparser would have to support Java 18 first.

**Comment by jtama** [comment]
Ok, I guess I will have to wait then 😉

**Comment by hejcz** [comment]
@jlerbsc are you waiting for the next LTS or is there some other blocker?

**Comment by jlerbsc** [comment]
Time and issues ;-)

**Comment by rpost** [comment]
Let me just place statement that I would really appreciate if javaparser could parse java 21. :)

**Comment by FeldrinH** [comment]
JavaParser now supports Java 18 and at least in GitHub issues I could not find reference to any specific Java 19 features that are unsupported. There are two other issues with the label "Java 19 Support", but they are both about preview features. What, if anything, is the blocker for declaring JavaParser Java 19 support complete?

**Comment by FeldrinH** [comment]
In fact, correct me if I'm wrong but Java 19 and 20 added no stable language features, so if JavaParser supports Java 18 then it should support Java 19 and 20 (non-preview) with no changes.

**Comment by jlerbsc** [comment]
I'm not sure that that Pattern Matching for switch (Third Preview) and Record Patterns are supported. I need to do some further tests .

https://openjdk.org/jeps/427
https://openjdk.org/jeps/405

**Comment by FeldrinH** [comment]
But talking about stable non-preview Java specifically, is there anything unsupported from Java 19 and 20?

**Comment by jlerbsc** [comment]
The next version will certainly support all the features that are not previewed in Java 21.

**Comment by jlerbsc** [comment]
All the features of Java 21 that were not preview have been implemented in version 3.26.0.
