### ISSUE TITLE
ResolvedType::isAssignableBy(ResolvedType) is wrong for arrays of boxed types

### ISSUE THREAD

**Issue by CptGit** [javaparser/javaparser#3919]
Test Case:

```java
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.VariableDeclarator;
import com.github.javaparser.resolution.types.ResolvedType;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;                                                            

public class IsAssignableByBoxedTypeArray {

    public static void main(String[] args) {
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(
                "class D {\n" +
                "   int[] x;\n" +
                "   Integer[] y;\n" +
                "}\n");
        ResolvedType intArrType = cu.findFirst(VariableDeclarator.class, f -> f.getNameAsString().equals("x")).get().resolve().getType();
        ResolvedType boxedIntArrType = cu.findFirst(VariableDeclarator.class, f -> f.getNameAsString().equals("y")).get().resolve().getType();
        if (intArrType.isAssignableBy(boxedIntArrType)) {
            throw new RuntimeException("int[] cannot be assigned by Integer[].");
        }
        if (boxedIntArrType.isAssignableBy(intArrType)) {
            throw new RuntimeException("Integer[] cannot be assigned by int[].");
        }
    }
}
```

Output:
```
Exception in thread "main" java.lang.RuntimeException: int[] cannot be assigned by Integer[].
        at IsAssignableByBoxedTypeArray.main(IsAssignableByBoxedTypeArray.java:25)
```

JavaParser version: 3.25.0
Java version: 11.0.18

**Comment by jlerbsc** [comment]
What do you think the outcome should be?
Indeed an array of primitive type is not assignable by an array of boxed type nor the reverse so int[] cannot be assigned by Integer[] and Integer[] cannot be assigned by int[].

But actually there are some problems in our approach because an array can be assigned only to a variable of a compatible array type, or to a variable of type Object, Cloneable or java.io.Serializable.

So thank you for alerting us to this issue.

**Comment by CptGit** [comment]
Hi, thanks for making the fix. I took a look at #3920 and I noticed some issue. I think "an array of Object is assignable by any array of primitive type" is not true, as things like Object[] a = new int[]{1, 2}; does not compile. I left a review in #3920.

**Comment by jlerbsc** [comment]
Yes you are right. This is a wrong comment. What i meant is an array can be assigned only to a variable of a compatible array type, or to a variable of type Object, Cloneable or java.io.Serializable.

**Comment by CptGit** [comment]
I see. Then it should be necessary to remove the check [`!isJavaLangObject(baseType)`](https://github.com/jlerbsc/javaparser/blob/26da2026648c9bb6345526a81ccae79387028df3/javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedArrayType.java#L99)?

**Comment by jlerbsc** [comment]
You are right again ;-)

**Comment by jlerbsc** [comment]
I think the solution wanted to be compatible with the expression String.format("%d", new int[] {1}); which does not raise a compilation error.

This is correct

    m(new int[] {});
    void m(Object... integers) {}

But there is a compilation error with

    m(new int[] {});
    void m(Integer... integers) {}

**Comment by CptGit** [comment]
If my understanding is correct, `integers` is actually an int[][], rather than int[] as one could think of. In other words, the entire int array is converted into an object.

> ```
> m(new int[] {});
> void m(Object... integers) {}
> ```

**Comment by jlerbsc** [comment]
What part of the JLS makes you think that?

**Comment by CptGit** [comment]
> What part of the JLS makes you think that?

I did not search for a specific JLS, but I think this is the only possible way to explain why it compiles as int[] cannot be converted to Object[].

Actually, I just ran the code snippet; if you print `integers.length` then it is not 0 but 1.

**Comment by jlerbsc** [comment]
I will consider that it is a particularity of the variable arity method.
