### ISSUE TITLE
Upgrading from 3.15.12 release

### ISSUE THREAD

**Issue by datavisortedyu** [javaparser/javaparser#3923]
We're currently using 3.15.12 of javaparser-symbol-solver-core and are planning to upgrade.

What's the recommendation for latest (stable) release that would have (almost) no incompatibilities with 3.15.12 release ?

Thanks

**Comment by jlerbsc** [comment]
All releases are stable but the one for which there will certainly be no incompatibility is version 3.24.9.
Version 3.24.10 should have been version 3.25.0.

**Comment by datavisortedyu** [comment]
3.15.12 to 3.24.9 is a big leap.
What are some of the major features / bug fixes involved ?

Thanks

**Comment by jlerbsc** [comment]
You can see this yourself in detail using the advanced github syntax in the PR tab; For example

    is:pr is:closed milestone:"3.15.13"
