### ISSUE TITLE
From `ResolvedType` to `Type`

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3929]
I want to manipulate code to transform something like :

		public void pre(List<Runnable> runnables) {
			runnables.forEach(r -> r.run());
		}

to

		public void post(List<Runnable> runnables) {
			runnables.forEach(Runnable::run);
		}

Walking the Node, I detect a `LambdaExpr`, and filter the relevant ones (with an `Expression` of type `MethodCallExpr`):

Then I resolve the scope of the `MethodCallExpr`, which gives me a `ResolvedType` (matching `Runnable` in my example). More precisely:

```
LambdaConstraintType{bound=ReferenceType{java.lang.Runnable, typeParametersMap=TypeParametersMap{nameToValue={}}}}
```

Finally, I'd like to replace the `MethodCallExpr` by a `MethodReferenceExpr`: 

```
new MethodReferenceExpr(theClassType, new NodeList<>(), methodCallExpr.getNameAsString());
```

However, I do not get how to build a proper `Type` (here `theClassType` variable) from the `ResolvedType`.

Any hint how to achieve this?

---

(I have related difficulties with `ResolvedType.isAssignableBy(ResolvedType)` where I'd like to craft a `ResolvedType` from the String `java.lang.RuntimeException`).

**Comment by jlerbsc** [comment]
For the second question, if you have a type declaration you can create a ResolvedReferenceType via ReferenceTypeImpl.create(<TypeDeclaration>)

**Comment by jlerbsc** [comment]
For the first question, the first argument of MethodReferenceExpr constructor is an expression so i think your can use simply a NameExpr which refer to the name of the class/interface (in this case "Runnable" ). I'm not sure of myself... You have to try.

**Comment by jlerbsc** [comment]
If this answer helped you please close this issue.

**Comment by blacelle** [comment]
> For the second question, if you have a type declaration you can create a ResolvedReferenceType via ReferenceTypeImpl.create()

```
    @Override
    protected ResolvedReferenceType create(ResolvedReferenceTypeDeclaration typeDeclaration) {
        return new ReferenceTypeImpl(typeDeclaration);
    }

    public ReferenceTypeImpl(ResolvedReferenceTypeDeclaration typeDeclaration) {
        super(typeDeclaration);
    }
```

How can I get a `ResolvedReferenceTypeDeclaration` from the string `java.lang.RuntimeException` ?

For now, I go into something like:

			List<ResolvedReferenceType> ancestors = referenceType.getAllClassesAncestors();

			if (referenceType.getQualifiedName().equals(RuntimeException.class.getName())) {
				return true;
			} else if (ancestors.size() >= INDEXOF_RUNTIMEEXCEPTION
					&& ancestors.get(ancestors.size() - INDEXOF_RUNTIMEEXCEPTION)
							.getQualifiedName()
							.equals(RuntimeException.class.getName())) {
				return true;
			} else {
				return false;
			}

while I'd like to go into something like:

    optResolved.get().isAssignableBy(typeRepresentingRuntimeException);

---

For the other case, a NameExpr does the job. I get later a more subtile issue as, for the same source, JP parses it as a TypeExpr(...) wrapping each package element. Then, it later breaks `Node` equality but I'll live with it.

**Comment by jlerbsc** [comment]
> JP parses it as a TypeExpr(...) wrapping each package element.

This is a limit on what the parser can do.

**Comment by jlerbsc** [comment]
> How can I get a `ResolvedReferenceTypeDeclaration` from the string `java.lang.RuntimeException` ?

You must resolve this type with a TypeSolver.

If you want to get a more precise answer you have to give more information. The code snippet does not make it easy to understand what you want to do.

**Comment by blacelle** [comment]
Excellent. Thanks @jlerbsc .

I got through with:

			ReflectionTypeSolver typeSolver = new ReflectionTypeSolver();
			SymbolReference<ResolvedReferenceTypeDeclaration> refType =
					typeSolver.tryToSolveType(RuntimeException.class.getName());

			ReferenceTypeImpl referenceTypeImpl = new ReferenceTypeImpl(refType.getCorrespondingDeclaration());

			referenceTypeImpl.isAssignableBy(xxx) {

**Comment by blacelle** [comment]
This was solved in a case where a `Type` was not necessary, and a `NameExpr` was sufficient (given an input `ResolvedType`).

https://github.com/javaparser/javaparser/issues/3932 hints how to effectively craft a `Type` from a `ResolvedType`
