### ISSUE TITLE
Release 2.5.1

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#393]
Alas, a bugfix release :(

**Comment by ftomassetti** [comment]
This was quick! Thanks for the new release!

**Comment by matozoid** [comment]
Have to do the release tonight, or do you happen to have access to a well configured machine?

And shouldn't you be on holiday???

**Comment by ftomassetti** [comment]
I am on holidays, so I do not write code, I just live through the people
writing it :)

**Comment by matozoid** [comment]
Released, on jcenter now. Maven central is still processing.
