### ISSUE TITLE
LexicalPreservingPrinter generates invalid code after swapping an ExpressionStmt in a LambdaExpr

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3930]
I want to manipulate :

public class TestFileSystemCodeProvider {

    @Test
    public void testInMemoryFileSystem() throws IOException {
        Stream.of("").listFilesForContent(file -> { System.out.println(s);});
    }
}

to remove the unnecessary curly brackets in the lambda. 

I consider the following code:

```
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.LambdaExpr;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.stmt.ExpressionStmt;
import com.github.javaparser.ast.stmt.Statement;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class LexicalPreservingSimplifyLambda {
	static final String testCase = "package eu.solven.cleanthat.code_provider.inmemory;\n" + "\n"
			+ "import java.util.stream.Stream;\n"
			+ "\n"
			+ "public class TestFileSystemCodeProvider {\n"
			+ "	@Test\n"
			+ "	public void testInMemoryFileSystem() throws IOException {\n"
			+ "\n"
			+ "		Stream.of(\"\").listFilesForContent(file -> {\n"
			+ "			System.out.println(s);\n"
			+ "		});\n"
			+ "	}\n"
			+ "}\n"
			+ "";

	public static void main(String[] args) {
		CompilationUnit unit = StaticJavaParser.parse(testCase);

		unit = LexicalPreservingPrinter.setup(unit);

		unit.walk(node -> {
			if (node instanceof LambdaExpr) {
				LambdaExpr lambdaExpr = (LambdaExpr) node;

				Statement body = lambdaExpr.getBody();

				if (!(body instanceof BlockStmt)) {
					return;
				}

				BlockStmt lambdaBLockStmt = (BlockStmt) body;

				if (lambdaBLockStmt.getStatements().size() == 1) {
					ExpressionStmt exprStmt = (ExpressionStmt) lambdaBLockStmt.getStatement(0);

					lambdaExpr.setBody(new ExpressionStmt(exprStmt.getExpression()));
				}
			}
		});

		System.out.println("OK");
		System.out.println(unit.toString());

		System.out.println("KO");
		System.out.println(LexicalPreservingPrinter.print(unit));
	}
}
```

The output is:

```
OK
package eu.solven.cleanthat.code_provider.inmemory;

import java.util.stream.Stream;

public class TestFileSystemCodeProvider {

    @Test
    public void testInMemoryFileSystem() throws IOException {
        Stream.of("").listFilesForContent(file -> System.out.println(s));
    }
}
```
whie is totally fine, except it does not rely on LexicalPreservingPrinter.

The following relies on `LexicalPreservingPrinter` but there is a lurking `;` which is invalid:
```
KO
package eu.solven.cleanthat.code_provider.inmemory;

import java.util.stream.Stream;

public class TestFileSystemCodeProvider {
	@Test
	public void testInMemoryFileSystem() throws IOException {

		Stream.of("").listFilesForContent(file -> System.out.println(s););  // <---- One of the `;` is invalid
	}
}
```

**Comment by jlerbsc** [comment]
The only way I see is to create a new Lambda expression. For example

    Optional<Node> parentNode = lambdaExpr.getParentNode();
	parentNode.ifPresent(n -> {
		ExpressionStmt exprStmt = (ExpressionStmt) lambdaBLockStmt.getStatement(0);
		LambdaExpr newLambdaExpr = new LambdaExpr();
		newLambdaExpr.setBody(new ExpressionStmt(exprStmt.getExpression()));
		n.replace(lambdaExpr, newLambdaExpr);
	});

**Comment by blacelle** [comment]
Thanks @jlerbsc . Any additional details on the cause of this issue ? (I'm just trying to get the kind of issues I can expect from `LexicalPreservingPrinter `)

Also, what is the impact of not using `LexicalPreservingPrinter` ? I lose custom formatting (i.e. various whitespaces characters). But could there be additional impact ? (losing some comments ? Some other syntax may be fundamentally different ?) 

I read in the Javadoc:

> A Lexical Preserving Printer is used to capture all the lexical information while parsing

However, `LexicalPreservingPrinter ` come into play **after** having parsed the source code: how can it help capturing more information while parsing?

**Comment by jlerbsc** [comment]
> how can it help capturing more information while parsing?

What information are you referring to?

**Comment by jlerbsc** [comment]
> what is the impact of not using `LexicalPreservingPrinter` ?

You lose the custom formatting. You can see this when you use the pretty printer instead of the LPP.

**Comment by jlerbsc** [comment]
> Any additional details on the cause of this issue ?

I think it comes from the fact that you are reusing an ExpressionStmt which was embedded in a block and therefore terminated (from a lexical point of view) with a semicolon. The lexical information which was initialized during the initialization of the node by the LPP carried this characteristic.

**Comment by blacelle** [comment]
> What information are you referring to?

`LexicalPreservingPrinter` javadoc refers to this information. I don't what is this information specifically to `LexicalPreservingPrinter` (which is my question).

> You lose the custom formatting. You can see this when you use the pretty printer instead of the LPP.

Hence, I should expect only whitespaces characters changes with or without LPP, correct? (Given various issues/difficulties with LPP, I may prefer PrettyPrinter (as long as the only changes are whitespaces characters/style differences))

**Comment by jlerbsc** [comment]
LPP captures all the information necessary to reproduce the source code in its original format, including AST modifications. This includes spaces, tabs, comments, line breaks...

**Comment by blacelle** [comment]
> A Lexical Preserving Printer is used to capture all the lexical information while parsing

Cependant LPP n'intervient qu'après le parsing: est-ce que LPP impacting le parsing ou non ? (La javadoc suggère que oui, mais le code suggère que non). 

		CompilationUnit unit = StaticJavaParser.parse(testCase); <-- Parsing
		unit = LexicalPreservingPrinter.setup(unit);  <-- LPP wiring

Peut-etre que le code est parsé lazily, ce qui expliquerait que LPP garde des informations supplémentaire au parsing, bien qu'il soit utilisé après l'appel à `.parse` ?

Je rencontre différentes difficultés avec LPP (c'est la vie, j'espère que mes reports sont satisfaisants). Je me demande donc si je pourrai m'en passé : si LPP capture `tout`, qu'implique sa non-utilisation ? (Perte des commentaires ? Perte de l'indentation ? Impact sur le code sans impact sémantique ? (e.g. ordre des modifiers))

**Comment by jlerbsc** [comment]
LPP has no impact on parsing (AST).
It only captures the code representation in the form of tokens.
This capture is carried out from a lexicon which is a model of the way in which the code is presented.
If you don't want to use LPP or the pretty printer, you have to format the code yourself.

**Comment by blacelle** [comment]
(Here is my debug analysis. As a new-comer, there may be trivial/falsy statements. I end with a fix suggestion (which looks bad to me, but does the job (in my case) and possibly/probably breaks other things : @jlerbsc you know better))

ExpressionStatements have a trailing `;`:

com.github.javaparser.printer.DefaultPrettyPrinterVisitor.visit(ExpressionStmt, Void)

    @Override
    public void visit(final ExpressionStmt n, final Void arg) {
        printOrphanCommentsBeforeThisChildNode(n);
        printComment(n.getComment(), arg);
        n.getExpression().accept(this, arg);
        printer.print(";");
    }

However LambdaExpr may print the inner Expression of an ExpressionStmt (hence skipping the trailing `;`:
com.github.javaparser.printer.DefaultPrettyPrinterVisitor.visit(LambdaExpr, Void)

        final Statement body = n.getBody();
        if (body instanceof ExpressionStmt) {
            // Print the expression directly
            ((ExpressionStmt) body).getExpression().accept(this, arg);
        } else {
            body.accept(this, arg);
        }

When computing the difference of Csm model:

```concreteSyntaxModelByClass.put(LambdaExpr.class, 
sequence(
   comment(), 
   conditional(
      ObservableProperty.ENCLOSING_PARAMETERS, 
      FLAG, 
      token(GeneratedJavaParserConstants.LPAREN)), 
   list(
      ObservableProperty.PARAMETERS, 
      sequence(comma(), space())
   ), 
   conditional(
      ObservableProperty.ENCLOSING_PARAMETERS, 
      FLAG, 
      token(GeneratedJavaParserConstants.RPAREN)), 
      space(), 
      token(GeneratedJavaParserConstants.ARROW), 
      space(), 
      conditional(
         ObservableProperty.EXPRESSION_BODY, 
         IS_PRESENT, 
         child(ObservableProperty.EXPRESSION_BODY), 
         child(ObservableProperty.BODY)
      )
   )
);
```
-> We can have both a body or an expressionBody: OK.

---

At runtime, PropertyChange is BODY (old is a BlockStatement, new is an ExpressionStatement).

Here, `satisfied` is computed as false (seemingly based on the oldValue), so we manipulate the thing as a body
```
        } else if (csm instanceof CsmConditional) {
            CsmConditional csmConditional = (CsmConditional) csm;
            boolean satisfied = change.evaluate(csmConditional, node);
            if (satisfied) {
                calculatedSyntaxModelForNode(csmConditional.getThenElement(), node, elements, change);
            } else {
                calculatedSyntaxModelForNode(csmConditional.getElseElement(), node, elements, change);
            }
```

Right after, in `calculatedSyntaxModelForNode`, we register the ExpressionStatement as `child`:

        } else if (csm instanceof CsmSingleReference) {
            CsmSingleReference csmSingleReference = (CsmSingleReference) csm;
            Node child;
            if (change instanceof PropertyChange && ((PropertyChange) change).getProperty() == csmSingleReference.getProperty()) {
                child = (Node) ((PropertyChange) change).getNewValue();
            } else {
                child = csmSingleReference.getProperty().getValueAsSingleReference(node);
            }
            if (child != null) {
                elements.add(new CsmChild(child));
            }

I feel it is around there, but it is unclear to me how to do that properly: we would need to register not the child as ExpressiontStatement, but the expression wrapped in the   `ExpressiontStatement`.

Here is a (not-exciting) proposal:

```
        } else if (csm instanceof CsmSingleReference) {
            CsmSingleReference csmSingleReference = (CsmSingleReference) csm;
            Node child;
            if (change instanceof PropertyChange && ((PropertyChange) change).getProperty() == csmSingleReference.getProperty()) {
                child = (Node) ((PropertyChange) change).getNewValue();
            	if (node instanceof LambdaExpr && child instanceof ExpressionStmt) {   // <-- Kind of replicate `DefaultPrettyPrinterVisitor.visit(LambdaExpr,`
            		child = ((ExpressionStmt) child).getExpression();
            	}
            } else {
                child = csmSingleReference.getProperty().getValueAsSingleReference(node);
            }
            if (child != null) {
                elements.add(new CsmChild(child));
            }
        } else ...
```

**Comment by jlerbsc** [comment]
What you have to do is to replace, in the parent node, the original lambda expression from another. Below is a snippet of the code.

    Optional<Node> parentNode = lambdaExpr.getParentNode();
    parentNode.ifPresent(n -> {
	    ExpressionStmt exprStmt = (ExpressionStmt) lambdaBLockStmt.getStatement(0);
	    LambdaExpr newLambdaExpr = new LambdaExpr();
	    newLambdaExpr.setParameters(lambdaExpr.getParameters());
	    newLambdaExpr.setBody(new ExpressionStmt(exprStmt.getExpression()));
	    n.replace(lambdaExpr, newLambdaExpr);
    });

Your suggestion is too specific.

**Comment by blacelle** [comment]
I get the workaround, but I'm not keen to add too many of such workaround in multiple places in my projects. Instead of adding a utility method in my project to workaround this JP issue, I thought preferable to fix it once and for all in JP.

Is my bug too specific, or the fix too specific ? The suggested fix is simply the equivalent of `PrettyPrinter` edge-case in the context of `LexicalDifferenceCalculator`. I would be happy to wotk in a more generic fix, if you can give me some insights how to improve the fix.

**Comment by blacelle** [comment]
Also, this kind of workaround (swapping the parent node) regularly generates side-issues. e.g., in another case (https://github.com/javaparser/javaparser/issues/3898), I forgot to transfer modifiers. Then I forgot to transfer annotations. I suppose I'm still missing transferring other things. Swapping the parent is an excellent **workaround**.

**Comment by jlerbsc** [comment]
It's not a workaround it's the way you should do it. When using LPP it is better to create a new object than to try to reuse an existing object.

> Indeed the problem you encounter is related to the way the lexical preserving printer assigns the tokens to the nodes and in addition to the presence of phantom nodes (virtual nodes).
First, the lexical preserving printer tries to assign java tokens to AST nodes according to the position of the nodes. It traverses all the nodes from the root of the AST as well as all the children in a resursive way with the exception of the nodes which have no position and the 'virtual/phantom' nodes. During this processing, the java tokens are assigned to the node closest to the token and whose position includes that of the token. Unfortunately, this logic does not work in the case of a variable declaration because the tokens describing the type of the variable are positioned before the actual declaration of the variable in the AST. In fact they are assigned to the expression in which the variable is declared. I am describing all this because when you modify a type, the modification is propagated to the direct parent but not to the grand parent or the great grand parent... So the modification does not reach the node which carries the tokens corresponding to the type of the variable and the modification is not taken into account by the lexical preserving printer.
In conclusion, it is extremely complicated to modify this mechanism and I strongly advise you to create a new declaration to replace the previous one.

**Comment by jlerbsc** [comment]
I will see if it is not possible to clone the object without cloning the data used by LPP. If possible, it will no longer be necessary to create a new object, but simply clone the object you want to modify.

**Comment by blacelle** [comment]
The issue would happen even with a fresh expression. No ?

**Comment by jlerbsc** [comment]
it seems to me not

    @Test
	void issue3930() {
		considerCode(
				"public class Foo {\n"
				+ "	 public void m(){\n"
				+ "		java.util.stream.Stream.of(\"\").listFilesForContent(file -> {\n"
				+ "			System.out.println(s);\n"
				+ "		});\n"
				+ "	 }\n"
				+ "}");

		String expected =
					"public class Foo {\n"
					+ "	 public void m(){\n"
					+ "		java.util.stream.Stream.of(\"\").listFilesForContent(file -> System.out.println(s));\n"
					+ "	 }\n"
					+ "}";

		cu.walk(node -> {
			if (node instanceof LambdaExpr) {
				LambdaExpr lambdaExpr = (LambdaExpr) node;

				Statement body = lambdaExpr.getBody();

				if (!(body instanceof BlockStmt)) {
					return;
				}

				BlockStmt lambdaBLockStmt = (BlockStmt) body;

				Optional<Node> parentNode = lambdaExpr.getParentNode();
				parentNode.ifPresent(n -> {
					ExpressionStmt exprStmt = (ExpressionStmt) lambdaBLockStmt.getStatement(0);
					LambdaExpr newLambdaExpr = new LambdaExpr();
					newLambdaExpr.setParameters(lambdaExpr.getParameters());
					newLambdaExpr.setBody(new ExpressionStmt(exprStmt.getExpression()));
					n.replace(lambdaExpr, newLambdaExpr);
				});
			}
		});

		String actual = LexicalPreservingPrinter.print(cu);
		System.out.println(actual);
		assertEqualsStringIgnoringEol(expected, actual);
	}

**Comment by blacelle** [comment]
@jlerbsc Sorry, I was not specific enough. I meant: the issue still happens even if I inject a fresh expression in the LambdaExpr, isn't it ?

I agree the issue does not happen when swapping the `LambdaExpr`. My analysis of the issue indicates the issue if when swapping a Statement in a LambdaExpr by any ExpressionStatement. Re-reading this issue, I understand you believe the issue is rooted in re-using an Expression from the initial Statement:

> I think it comes from the fact that you are reusing an ExpressionStmt which was embedded in a block and therefore terminated (from a lexical point of view) with a semicolon. The lexical information which was initialized during the initialization of the node by the LPP carried this characteristic.

But, I believe the issue happens for any Statement -> StatementExpression swap.

Here is a simpler test, just replacing the Statement by some simple StatementExpression:

```
package com.github.javaparser.printer.lexicalpreservation;

import static com.github.javaparser.utils.TestUtils.assertEqualsStringIgnoringEol;

import org.junit.jupiter.api.Test;

import com.github.javaparser.ast.expr.LambdaExpr;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.stmt.ExpressionStmt;

public class Issue3937Test extends AbstractLexicalPreservingTest {
	static final String given = "package custom.project;\n" + "\n"
			+ "import java.util.stream.Stream;\n"
			+ "\n"
			+ "class TestFileSystemCodeProvider {\n"
			+ "	void testInMemoryFileSystem() {\n"
			+ "\n"
			+ "		Stream.of(\"\").listFilesForContent(file -> {\n"
			+ "			System.out.println(s);\n"
			+ "		});\n"
			+ "	}\n"
			+ "}\n"
			+ "";

	@Test
	void test() {
		considerCode(given);

		LexicalPreservingPrinter.setup(cu);

		LambdaExpr lambdaExpr = cu.findFirst(LambdaExpr.class).get();
		lambdaExpr.setBody(new ExpressionStmt(new MethodCallExpr(new NameExpr("SomeClass"), "someMethod")));

		String actual = LexicalPreservingPrinter.print(cu);
		String expected = "package custom.project;\r\n"
				+ "\r\n"
				+ "import java.util.stream.Stream;\r\n"
				+ "\r\n"
				+ "class TestFileSystemCodeProvider {\r\n"
				+ "	void testInMemoryFileSystem() {\r\n"
				+ "\r\n"
				+ "		Stream.of(\"\").listFilesForContent(file -> SomeClass.someMethod());\r\n"
				+ "	}\r\n"
				+ "}\r\n"
				+ "";
		assertEqualsStringIgnoringEol(expected, actual);
	}
}
```
It fails just the same, with an unexpected `;` (and the PR fixes the issue just the same)

Hence, I still do not get what is too specific: my issue, or the fix ?

---

Even if the issue is not related to re-using the Expression, I do not get the following item:

> It's not a workaround it's the way you should do it. When using LPP it is better to create a new object than to try to reuse an existing object.

How do I know I can re-use or not a `Node` ? If I can not re-use the Expression, then I should create a new one. Should I create a new LambdaExpr, or can I re-use the existing ? In your your example, you create a new Lambda. Should I apply the same logic to the LambdaExpr parent ? I would end re-creating the CompilationUnit if I follow this pattern to any Node.
