### ISSUE TITLE
Is it possible to re-inject the type solver into the newly added nodes so that these new symbols are resolved correctly?

### ISSUE THREAD

**Issue by adrts-iscte** [javaparser/javaparser#3931]
Is more a question than an issue. Sorry, if I'm in the wrong place.

For example:

Considering the following class
````
class Bill {

    private double value;

    void methodToBeRenamed(double param1) {}

    void methodBodyChanged() {
        System.out.println(value);
    }
}
````

And I had a new method call to the `methodBodyChanged()` method, but replacing the whole method body/statements even if they are similar:

````
class Bill {

    private double value;

    void methodToBeRenamed(double param1) {}

    void methodBodyChanged() {
        System.out.println(value);
        methodToBeRenamed(value);
    }
}
````

The first/original class got parsed using the followed code (using Kotlin):
````
val solver = CombinedTypeSolver()
solver.add(ReflectionTypeSolver(false))
if (File(path).isFile) {
            val javaParser = JavaParser(ParserConfiguration().setSymbolResolver(JavaSymbolSolver(solver)))
            val parseResult = javaParser.parse(File(path))
}
````
        
Is it possible that the statement `System.out.println(value);` is resolved correctly again as it got substituted by another similar statement?

**Comment by jlerbsc** [comment]
There is no reason for this expression not to be resolved.

**Comment by adrts-iscte** [comment]
I think I have solved the problem! Thank you so much for your attention!
