### ISSUE TITLE
ResolvedReferenceType to ReferenceType

### ISSUE THREAD

**Issue by stschott** [javaparser/javaparser#3932]
I want to obtain the thrown exceptions from a super constructor and add them to a generated constructor in the child class.
When obtaining the exceptions from the super class they are of type ResolvedReferenceType.
To add them to the generated ConstructorDeclaration, a simple ReferenceType is required.

So how can I convert a ResolvedReferenceType to a ReferenceType?

**Comment by jlerbsc** [comment]
Hi @stschott you cannot generate directly a referenceType from a ResolvedReferenceType but you can create ClassOrInterfaceType with a qualified name/id.
