### ISSUE TITLE
how to wrap a long string

### ISSUE THREAD

**Issue by yisiliang** [javaparser/javaparser#3934]
I have a very long SQL string，when I use it as the method argument，the line of code will be very long。How to wrap it。

**Comment by jlerbsc** [comment]
What do you think? Create a variable containing the character string.

**Comment by yisiliang** [comment]
> What do you think? Create a variable containing the character string.

if the sql srring is very long，the generated code will be very long too。


````
System.out.println("very long very long very long very long very long");
````
I want it to be below:
```

System.out.println("very long very long very long "
+ "very long very long");

```

**Comment by jlerbsc** [comment]
In this case the argument of the method call expression must be a BinaryExpr with StringLiteralExpr.

**Comment by yisiliang** [comment]
> In this case the argument of the method call expression must be a BinaryExpr with StringLiteralExpr.

Ok,I got it. Thank you!
