### ISSUE TITLE
MANIFEST.MF points to non-existent URL

### ISSUE THREAD

**Issue by cowwoc** [javaparser/javaparser#3947]
The MANIFEST.MF file of javaparser-core contains:

  `Bundle-DocURL: https://github.com/javaparser/javaparser-core`

which is a broken link. Other tools (e.g. maven-license-plugin) use this property to generate hyperlinks and then *those* links are broken as well.

To fix this, you will need to add an `organization` section in your `pom.xml`. Example:

```
<organization>
  <name>Neva Development</name>
  <url>http://www.neva.zone</url>
</organization>
```

See https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html and https://github.com/neva-dev/felix-search-webconsole-plugin/blob/main/pom.xml for more information

**Comment by jlerbsc** [comment]
How do you do when there is no organization for example on an Open Source project?

**Comment by cowwoc** [comment]
Looking at https://github.com/bndtools/bnd/tree/master/maven-plugins/bnd-maven-plugin#default-bundle-headers I'm guessing you will need to update https://github.com/javaparser/javaparser/blob/6f7bf20d1e44841fd5ff70dae8c4993e10136fe6/javaparser-core/pom.xml#L52 with the following configuration:

```
<plugin>
  <groupId>biz.aQute.bnd</groupId>
  <artifactId>bnd-maven-plugin</artifactId>
  <configuration>
    <bnd><![CDATA[
      Bundle-DocURL: whatever value you want
    ]]></bnd>
  </configuration>
```

**Comment by jlerbsc** [comment]
It seems to me that JP is already configured for this case

https://github.com/bndtools/bnd/tree/master/maven-plugins/bnd-maven-plugin#group-2-scenarios-based-on-the-bnd-process-goal

**Comment by cowwoc** [comment]
How so? https://github.com/javaparser/javaparser/blob/6f7bf20d1e44841fd5ff70dae8c4993e10136fe6/javaparser-core/pom.xml#L52 invokes `bnd-process` and you never set the value of `Bundle-DocURL` or whatever it is derived from.

**Comment by jlerbsc** [comment]
"The common case where very little configuration is required; inputs and outputs are based on defaults. Bnd performs its analysis and enhances the jar with OSGi metadata obtained through introspection of classes, resources, dependencies"

**Comment by cowwoc** [comment]
Okay... But the value in the manifest file is incorrect..
 So clearly you'll need to explicitly override the default value.

**Comment by jlerbsc** [comment]
I think the modification that is currently being pushed should fix this problem. Thank you for understanding.

**Comment by cowwoc** [comment]
I'll give the next version a try.  Thank you.

**Comment by jlerbsc** [comment]
Thank you. The next version is scheduled for April 1st.
