### ISSUE TITLE
LexicalPreservingPrinter Ignores Changes to LambdaExpr Body

### ISSUE THREAD

**Issue by andrecsilva** [javaparser/javaparser#3949]
Using JavaParser 3.25.1

Consider the following code and its output below:
```java
  void main() {
    var original =
        "class A {\n"
            + "\n"
            + "  void foo() {\n"
            + "    Consumer<Integer> lambda = a -> System.out.println(a);\n"
            + "  }\n"
            + "}";
    var cu = StaticJavaParser.parse(original);
    var estmt = cu.findAll(ExpressionStmt.class).get(1);
    var lexpr = cu.findAll(LambdaExpr.class).get(0);
    LexicalPreservingPrinter.setup(cu);

    var block = new BlockStmt();
    var bstmt = new BreakStmt();
    block.addStatement(estmt);
    block.addStatement(bstmt);
    lexpr.setBody(block);

    System.out.println(cu);
    System.out.println(LexicalPreservingPrinter.print(cu));
  }
```
Output:
```
    class A {

        void foo() {
            Consumer<Integer> lambda = a -> {
                System.out.println(a);
                break;
            };
        }
    }

    class A {

      void foo() {
        Consumer<Integer> lambda = a -> System.out.println(a);
      }
    }
```
As we can see, the output of the `LexicalPreservingPrinter` ignores the changes made to the tree. The print before it shows that the changes are there.

**Comment by jlerbsc** [comment]
Thanks for reporting this bug.

**Comment by jlerbsc** [comment]
This is a very interesting and important bug that has never been identified. It's surprising but the LPP does not discover the changes that have been made. This is mainly due to the definition of the syntax of a lambda expression in LPP and and how conditional elements are handled. I don't have a solution yet but I'm thinking about it. For the moment, a workaround would certainly consist in creating a new lambda expression.

**Comment by jlerbsc** [comment]
I found a solution for this issue and i'll push a PR tomorrow.

For your test case to work you must also create a new ExpressionStmt with the expression contained by estmt because ExpressionStmt is already initialized by LPP and does not contain the semicolumn. I don't know if it's a bug or not.
