### ISSUE TITLE
Ability to automatically add import for a static method call 

### ISSUE THREAD

**Issue by ankitezee** [javaparser/javaparser#3956]
I want to generate code for a static method call and automatically add its import.

e.g. SpringApplication.run(Application.class, args)

Through documentation, I have been able to figure out one way to do it

`new ExpressionStmt(
              new MethodCallExpr(
                           "SpringApplication.run", 
                           new ClassExpr(new ClassOrInterfaceType("Application")), 
                           new NameExpr("args")))`

But this requires to manually add the import for SpringApplication as well.

Wondering if there is a way to pass the actual SpringApplication.class so it can automatically add the import as well (like how it does for Annotations)

Couldnt find the answer in documentation or SO (hence posting here)

**Comment by jlerbsc** [comment]
Hi @ankitezee  I'm sorry but you have to create the import declarations yourself.

**Comment by chunkomac** [comment]
Thanks @jlerbsc for quick response. Maybe take this as a feature request for later :)

Will manually add imports for now.

**Comment by jlerbsc** [comment]
Thanks for your suggestion but we are not going to implement this type of functionality because the objective of this Javaparser project is more to provide a tool to perform operations on the code but not to provide these operations. In short it is not a refactoring solution.

**Comment by jlerbsc** [comment]
If we answered your question, I'll let you close this issue.
