### ISSUE TITLE
How do you determine whether a parameter is generic?

### ISSUE THREAD

**Issue by jayrrrrr** [javaparser/javaparser#3967]
Example
```
public class Main {
    public static void main(String[] args) {
        String code = "public void foo(List<String> list, T obj) {}";
        JavaParser parser = new JavaParser();
        ParseResult<MethodDeclaration> parseResult = parser.parseMethodDeclaration(code);


        MethodDeclaration method = parseResult.getResult().get();

        NodeList<Parameter> parameters = method.getParameters();
        for (Parameter parameter : parameters) {
            if (parameter.getType().isTypeParameter()) {
                System.out.println(parameter.getNameAsString() + " is a generic type");
            } else {
                System.out.println(parameter.getNameAsString() + " is not a generic type");
            }
        }

    }
}

```
output
```
list is not a generic type
obj is not a generic type
```
it's don't work.
for why?

**Comment by jlerbsc** [comment]
You must use the symbol solver to access the type declaration. Below is an example. this is not trivial for the type parameter ;-)

    @Test
    void test0() {

		String code = "class A {\n"
				+ "		public <T> void foo(java.util.List<String> list, T obj) {\n"
				+ "		}\n"
				+ "	}";
		JavaParserAdapter parser = JavaParserAdapter.of(createParserWithResolver(defaultTypeSolver()));
        CompilationUnit cu = parser.parse(code);


        MethodDeclaration method = cu.findFirst(MethodDeclaration.class).get();

        NodeList<Parameter> parameters = method.getParameters();
        for (Parameter parameter : parameters) {
        	ResolvedType rt = parameter.getType().resolve();
        	if (rt.isReferenceType()) {
        		System.out.println(rt.describe()+ " is generic "+ rt.asReferenceType().getTypeDeclaration().get().isGeneric());
        	}
        	if (rt.isTypeVariable()) {
        		System.out.println(rt.describe()+ " is generic "+ rt.asTypeVariable().asTypeParameter().getContainer().isGeneric());
        	}
        }
    }

displays

    java.util.List<java.lang.String> is generic true
    T is generic true

**Comment by jlerbsc** [comment]
Does this response answer your questions?

**Comment by jayrrrrr** [comment]
Do you mean that I need to customize a parser to parse this code .use JavaParserAdapter?

**Comment by jlerbsc** [comment]
You can use the JavaParserAdapter class which facilitates code parsing but it is not necessary. On the other hand you must initialize the symbol solver.

**Comment by jayrrrrr** [comment]
Can you give me an example? Thanks!

**Comment by jlerbsc** [comment]
You will find examples on these links
https://github.com/javaparser/javasymbolsolver
https://tomassetti.me/resolve-method-calls-using-java-symbol-solver/

**Comment by jayrrrrr** [comment]
Thanks!
