### ISSUE TITLE
Is it possible to get the return type contained in a MethodCallExpr using JavaParser ?

### ISSUE THREAD

**Issue by alwaysaditi** [javaparser/javaparser#3974]
So I have this piece of code , that I was successfully able to parse and identify as a MethodCallExpr

`if(myList.isEmpty()==true)`

Note: I am aware that we rarely use the `==true` notation with booleans , but here I was trying to build an optimizer that would 
catch such statement and point out that it would be wise not to do so.

 I just wanted to know if it would be possible to get the type returned by this expression as a boolean variable ? For example could I get the return type of the following expression as an Integer ?. Here myList() is an ArrayList.

`if(myList.size()>1)`

Note : for calling functions that did not require an object to be invoked , I was easily able to calculate the returned value by the function, for example 

```
  public void input_avoidBooleanIfComparison(){
        boolean a = false;
        int b = 24;
        List<Integer> myList = new ArrayList<Integer>();
        myList.add(2);
        if(myList.isEmpty()==true)// analyze return types
   
        {

        }
        if(myList.size()==1)
        {

        }
        if(yesMethod()==true) System.out.println("True");
    
        boolean c = true;

        if((((yesMethod()==true)&&(c==false)))||(c==true)) System.out.println("True");
      
    }
```

In the line  `  if((((yesMethod()==true)&&(c==false)))||(c==true)) System.out.println("True"); ` I was able to successfully get the resolved type of the LHS of the Expression , i.e `yesMethod()` as true using `calculateResolvedType()`.   However , when I tried to use the same function for calculating the resolved type of , `myList.isEmpty()`, it generated an `UnsolvedSymbolException`.

The type of both `yesMethod()` and `myList.isEmpty()` seems to be` MethodCallExpr`, so it is quite confusing why it is easy to resolve one but not the other 

Could you please guide me , or provide me with any helpful links to documentation that would help me achieve specifically this, when calling methods with the help of an object ? I am sorry if this sounds very trivial as I am currently very new to JavaParser and JavaSymbolSolver

**Comment by alwaysaditi** [comment]
Note : this is the code  that I  wrote to calculate the resolved types 
```

public void avoidBooleanIfComparison() throws UnsolvedSymbolException {
        flag = 3;
        System.out.println("This method is used for detecting unnecessary boolean comparison");
        // check the datatype of the variable in the Expression (condition inside if) and then check
        // if its being compared to true or false
        IfStmtVisitor v_obj = new IfStmtVisitor();
        List<Expression> collector = new ArrayList<>();
        v_obj.visit(obj.compilationUnit, collector);
//variableType v1 = new variableType();
        for (int i = 0; i < collector.size(); i++) {
//            System.out.println(collector.get(i));

            // here u can get stuff on both sides of the and or OR
            List<BinaryExpr> myList = new ArrayList<BinaryExpr>();
            BinaryExprExtract b_obj = new BinaryExprExtract();
            try
            {
                b_obj.visit((BinaryExpr) collector.get(i), myList);
            }
            catch (ClassCastException e)
            {
Node e1 = collector.get(i).getChildNodes().get(0);
                while ( e1.getChildNodes().get(0) instanceof EnclosedExpr)
                {
                    //System.out.println(e1);
                 e1 = e1.getChildNodes().get(0);
                }
                    b_obj.visit((BinaryExpr) e1.getChildNodes().get(0),myList);
            }

            for (int k = 0; k < myList.size(); k++) {
                helperForOptimizationMethod(myList.get(k));
                // System.out.println("printing from mlist= " + myList.get(k));
            }


        }
    }
    public void helperForOptimizationMethod(BinaryExpr n) throws UnsolvedSymbolException {
        Expression leftVariable = n.getLeft();
        // System.out.println(leftVariable.calculateResolvedType().describe());
       // SymbolReference<ResolvedReferenceTypeDeclaration> res = tryToSolveType(name);
        String leftvarType = "";
        try
        {
            //System.out.println("class= "+n.getLeft().getClass()+" statement left= "+n.getLeft());
            leftvarType = leftVariable.calculateResolvedType().describe().toString();
        }
        catch(UnsolvedSymbolException e)
        {
            System.out.println("sTACK TraCE");
getMethodReturnType g_m = new getMethodReturnType();
String arg = "";
g_m.visit((MethodCallExpr) leftVariable,arg);
//System.out.println(arg);
           // e.printStackTrace();

        }


        String operator = n.getOperator().toString();
        Expression rightVariable = n.getRight();
        // System.out.println(rightVariable.calculateResolvedType().describe());
        String rightvarType = "";
    // rightvarType = rightVariable.calculateResolvedType().describe().toString();

        try
        {
            rightvarType = rightVariable.calculateResolvedType().describe().toString();
        }
        catch(UnsolvedSymbolException e)
        {
            System.out.println("sTACK TraCE");
          e.printStackTrace();
        }

// now u have to check if operator = "==" and left variable is boolean and right variable is 0
        try
        {
            if (operator == "EQUALS") {
// JUST NEED TO FIND THE CLASS OF THE LEFT VARIABLE
                if ((leftvarType == "boolean") && (rightvarType == "boolean"))// OR DIFFERENT REGEX THAT PEOPLE USE TO CHECK STRING SIZE=0
                {
                   
                    System.out.println("\nAvoid using equality with boolean expressions ");
                    System.out.println(n.getBegin());
                    System.out.println(n);
                    //condition satisfied
                }

            }

        }

        catch (IllegalStateException e)
        {

        }


        //Other methods of optimisation
        //pass condition of ifStatement to expression statement
    }
```
Thanks a lot for any help !!

**Comment by jlerbsc** [comment]
Your question is not very clear and your example is too complex. Can you clarify your question and provide a much simpler code example.

**Comment by alwaysaditi** [comment]
Sure . What I mean to ask is this : Suppose I have the following snippet of code

```
class Main {
  public static void main(String[] args) {
    System.out.println("Hello world!");
    if(yes(1)==true)
    {
      System.out.println("yep");
      //do something
    }
  List<Integer> myList = new ArrayList();
    if(myList.size()>1)
    {
      // do something
    }
    if(myList.isEmpty()==true)
    {
      //do something else 
    }
      
  }

  static boolean yes(int choice)
  {
    if(choice==1)
    {
      return true;
    }
    return false;
  }
}
```

I intend to find out the values returned by the statement `myList.isEmpty()` in the if statement. I could evaluate the value of the  variable returned by `yes()` which is a `boolean` , using `calculateResolvedType()` method in javaparser. When i tried to evaluate the value returned by `myList.isEmpty()`,  it throws an `UnsolvedSymbolException`, though the types of both `myList.isEmpty()` and `yes()` are `MethodCallExpr`. Could you please help me how to get the value returned by a `MethodCallExpr`, when the method is called from a **non static context** ?

Thanks for the help !

**Comment by jlerbsc** [comment]
It is certainly due to a bad configuration of the symbol solver. If you consider the following test case the results are correct.

    @Test
	void m() {
		ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(
                "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class Main {\n"
                + "	public static void main(String[] args) {\n"
                + "		System.out.println(\"Hello world!\");\n"
                + "		if (yes(1) == true) {\n"
                + "			System.out.println(\"yep\");\n"
                + "			// do something\n"
                + "		}\n"
                + "		List<Integer> myList = new ArrayList();\n"
                + "		if (myList.size() > 1) {\n"
                + "			// do something\n"
                + "		}\n"
                + "		if (myList.isEmpty() == true) {\n"
                + "			// do something else\n"
                + "		}\n"
                + "\n"
                + "	}\n"
                + "\n"
                + "	static boolean yes(int choice) {\n"
                + "		if (choice == 1) {\n"
                + "			return true;\n"
                + "		}\n"
                + "		return false;\n"
                + "	}\n"
                + "}"
        );

        for (MethodCallExpr mce : cu.findAll(MethodCallExpr.class)) {
            	System.out.println("Trying to calculate type from "+ mce.toString());
                String type = mce.calculateResolvedType().describe();
                System.out.println("Type is "+ type);
        }
	}


    Trying to calculate type from System.out.println("Hello world!")
    Type is void
    Trying to calculate type from yes(1)
    Type is boolean
    Trying to calculate type from System.out.println("yep")
    Type is void
    Trying to calculate type from myList.size()
    Type is int
    Trying to calculate type from myList.isEmpty()
    Type is boolean

**Comment by alwaysaditi** [comment]
Thanks a lot for the prompt replies!! I did try using this piece of code however , I still seem to be getting the same `UnsolvedSymbolException ` error. I aim to first isolate all BinaryExpr and then , if the left of it is a MethodCallExpr, then I aim to check the right . And if both are booleans, then I have to print, "Avoid Comparisons when LHS is Boolean".  Kindly let me know if I have made any mistake in replicating the code ?

 ```
 public void avoidBooleanIfComparison()
    {
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        for(BinaryExpr bex : obj.compilationUnit.findAll(BinaryExpr.class))
        {
            System.out.println("Binary expression= "+bex.toString()+" left= "+bex.getLeft());
            if(bex.getLeft() instanceof MethodCallExpr) {
               Expression mce = bex.getLeft();
                System.out.println("Trying to calculate type from "+ mce.toString());
                String type = mce.calculateResolvedType().describe(); // here is where the error occurs
                System.out.println("Type is "+ type);
                if(type=="boolean"&&((bex.getRight().toString().equals("true"))||(bex.getRight().toString().equals("false"))))
                {
                    System.out.println("avoid Comparsion if LHS is boolean");
                }
            }
        }

    }
```

**Comment by alwaysaditi** [comment]
I also tried creating a different CompilationUnit object, since the previous one might have had configurations that were needed by other parts of the project. Not sure if that would make any difference anyway, since the [ParserConfiguration docs](https://www.javadoc.io/doc/com.github.javaparser/javaparser-core/3.4.3/com/github/javaparser/ParserConfiguration.html)
says that Parser Configuration can be changed for the same compilation unit. However I seem to be getting the same `UnsolvedSymbolException`


```
public void avoidBooleanIfComparison() throws IOException
    {
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        FileInputStream in = new FileInputStream("src/main/resources/OptimiserInput.java");

        CompilationUnit cu;
        try {
            // parse the file
            cu = StaticJavaParser.parse((in));
        } finally {
            in.close();
        }
        for(BinaryExpr bex : cu.findAll(BinaryExpr.class))
        {
            System.out.println("Binary expression= "+bex.toString()+" left= "+bex.getLeft());
            if(bex.getLeft() instanceof MethodCallExpr) {
               Expression mce = bex.getLeft();
                System.out.println("Trying to calculate type from "+ mce.toString());
                String type = mce.calculateResolvedType().describe();
                System.out.println("Type is "+ type);
                if(type.equals("boolean")&&((bex.getRight().toString().equals("true"))||(bex.getRight().toString().equals("false"))))
                {
                    System.out.println("avoid evaluating boolean in IfComparsion");
                }
            }
        }

    }
```

**Comment by jlerbsc** [comment]
If you get the error UnsolvedSymbolException it is probably due to the configuration of the symbol solver.
Here is an example on how to configure the symbol solver.
https://stackoverflow.com/questions/73349014/how-to-resolve-a-maven-project

**Comment by alwaysaditi** [comment]
Thank you for your reply. I still don't seem to understand what the issue is , though. I couldn't find the resolved type of MethodCallExpr. I could , however, think of a workaround this problem. I was assuming (already working with) error-free code for my project and hence statements like `myList.isEmpty()>1` would be rejected by the compiler anyway. So the problem just boils down to checking if the left hand side is an Instance of `MethodCallExpr` and the RHS is true or false.

This is how I did it.

 ```
public void avoidBooleanIfComparison() throws IOException
    {



        for(BinaryExpr bex : obj.compilationUnit.findAll(BinaryExpr.class))
        {
            System.out.println("Binary expression= "+bex.toString()+" left= "+bex.getLeft());

            if(bex.getLeft() instanceof MethodCallExpr) {

                if(((bex.getRight().toString().equals("true"))||(bex.getRight().toString().equals("false"))))
                {
                    System.out.println("avoid evaluating boolean in IfComparsion");
                }
            }
else {
               if(bex.getLeft().calculateResolvedType().describe().equals("boolean")&&(((bex.getRight().toString().equals("true"))||(bex.getRight().toString().equals("false")))))
               {
                   System.out.println("avoid evaluating boolean in IfComparsion");
               }
            }





        }

    }
```

I would , however like to know any mistake I was making , so it could help me (or others) in the future. However , as far as I am concerned , this issue can now be dropped. Thanks a lot @jlerbsc for your help!
