### ISSUE TITLE
why BinaryExpr and ArrayInitializerExpr not implement NodeWithArguments

### ISSUE THREAD

**Issue by XenoAmess** [javaparser/javaparser#3982]
Is there any reason not doing so?
Or should I give a pr for this?

**Comment by jlerbsc** [comment]
Can you give us an example where it would be necessary?

**Comment by XenoAmess** [comment]
> Can you give us an example where it would be necessary?

@jlerbsc It is not necessary but I do think they be NodeWithArguments, if I read the doc and name from NodeWithArguments correctly.

**Comment by XenoAmess** [comment]
I kind of want this because I'm writing some code handling maven plugin, who detect some string expressions, and change them automatically.
So I dfs the node's children, and find the String expression, and find its parent, and get all arguments from the parent, and handle every arguments(if who be string expression), and set the result back to the parent.

So If they be not implement NodeWithArguments, I need to manually handle it from the 2 classes. it looks, just, duplicated.

**Comment by jlerbsc** [comment]
There is no concept of arguments in a BinaryExpr.
The array initializer grammar also does not specify the concept of arguments (https://docs.oracle.com/javase/specs/jls/se8/html/jls-10.html#jls-10.6). So you have to handle it yourself.

**Comment by XenoAmess** [comment]
> There is no concept of arguments in a BinaryExpr. The array initializer grammar also does not specify the concept of arguments (https://docs.oracle.com/javase/specs/jls/se8/html/jls-10.html#jls-10.6). So you have to handle it yourself.

got it.
