### ISSUE TITLE
why FieldDeclaration in an interface calling isStatic() return false?

### ISSUE THREAD

**Issue by XenoAmess** [javaparser/javaparser#3983]

**Comment by jlerbsc** [comment]
Can you provide us with a unit test that demonstrates your problem?

**Comment by XenoAmess** [comment]
> Can you provide us with a unit test that demonstrates your problem?

@jlerbsc sure, here.
https://github.com/javaparser/javaparser/pull/3984

**Comment by jlerbsc** [comment]
This is right. Thank you for reporting this bug which refers to "Every field declaration in the body of an interface is implicitly public, static, and final."
https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html
