### ISSUE TITLE
Update node removal example for 2.5.0

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#399]
DSNL, could you change the manual? I think you made stuff in "Remove / Delete Node from AST" superfluous.
https://github.com/javaparser/javaparser/wiki/Manual

**Comment by DeepSnowNeeL** [comment]
So I change the visitor way of doing it to something like cu..getClassByName("D").getMethodByName("foo").setBody(null) ?

We could use a bit more exemples to create classes from scratch using the new methods

**Comment by matozoid** [comment]
No, because 3.0 won't be out for a while. Right now this sample is wrong and needs fixing. The source code is in package "com.github.javaparser.junit.removenode"

**Comment by matozoid** [comment]
My mistake, this is a non-issue.
