### ISSUE TITLE
UnsolvedSymbolException for annotation from another java file.

### ISSUE THREAD

**Issue by fredsuvn** [javaparser/javaparser#3993]
There are two java files:
1: SomeAnnotation.java -- annotation
2: SomeClass.java -- a class of which methods annotated by SomeAnnotation.

Here I try to resolve the annotation:
sourceRoot.parse("", new SourceRoot.Callback() {
                @Override
                public Result process(Path localPath, Path absolutePath, ParseResult<CompilationUnit> result) {
                    if (!result.isSuccessful()) {
                        return Result.DONT_SAVE;
                    }
                    CompilationUnit cu = result.getResult().get();
                    List<MethodDeclaration> methods = cu.findAll(MethodDeclaration.class, it -> it.isStatic() && it.isPublic());
                    for (MethodDeclaration method : methods) {
                        for (AnnotationExpr annotation : method.getAnnotations()) {
                            //here the error thrown: UnsolvedSymbolException{context='null', name='We are unable to find the annotation declaration corresponding to @SomeAnnotation("zz")', cause='null'}
                            System.out.println(annotation.resolve());
                        }
                    }
                    return Result.SAVE;
                }
            });

It seems the parser cannot find declaration of SomeAnnotation.class, but sourceRoot has been included all packages.

**Comment by fredsuvn** [comment]
```
sourceRoot.parse("", new SourceRoot.Callback() {
                @Override
                public Result process(Path localPath, Path absolutePath, ParseResult<CompilationUnit> result) {
                    if (!result.isSuccessful()) {
                        return Result.DONT_SAVE;
                    }
                    System.out.println(absolutePath);
                    CompilationUnit cu = result.getResult().get();
                    List<MethodDeclaration> methods = cu.findAll(MethodDeclaration.class, it -> it.isStatic() && it.isPublic());
                    for (MethodDeclaration method : methods) {
                        for (AnnotationExpr annotation : method.getAnnotations()) {
                            //here the error thrown: UnsolvedSymbolException{context='null', name='We are unable to find the annotation declaration
                            System.out.println(annotation.resolve());
                        }
                    }
                    return Result.SAVE;
                }
            });
```

**Comment by jlerbsc** [comment]
Hi @fredsuvn How did you configure the symbol solver?

**Comment by fredsuvn** [comment]
> 

wow, it's OK after setting the symbol solver, THX:)
