### ISSUE TITLE
Add support for Java 6 syntax

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#4]

**Comment by isbadawi** [comment]
I don't think any new syntax was introduced in Java 6 ([release notes](http://www.oracle.com/technetwork/java/javase/features-141434.html), [incompatibilities](http://www.oracle.com/technetwork/java/javase/compatibility-137541.html#source)), so I guess you could go ahead and close this?

**Comment by matozoid** [comment]
Sure.
