### ISSUE TITLE
Parsing then visiting transform to an empty method body from 3.25.3

### ISSUE THREAD

**Issue by olamy** [javaparser/javaparser#4018]
From version 3.25.3 (til 3.25.2 it's fine) 
Before parsing and manipulating sources the method is:
```
    public void setThrottledRequests(int value)
    {
        int permits = _passes == null ? 0 : _passes.availablePermits();
        _passes = new Semaphore((value - _throttledRequests + permits), true);
        _throttledRequests = value;
    }
```
After parsing and doing some manipulation the body is now:
```
    public void setThrottledRequests(int value)
    {

    }
```
This can be reproduce with the following steps:
```
git clone https://github.com/jetty-project/jetty-modify-sources-maven-plugin
cd jetty-modify-sources-maven-plugin
mvn clean test -Djavaparser.version=3.25.3
```
I did the `git bisect` game and found this commit as culprit 25b12b3edff2661c29cde8c80cc66abc6348c93b

**Comment by jlerbsc** [comment]
Probably related to https://github.com/javaparser/javaparser/issues/4016

**Comment by jlerbsc** [comment]
Can you retest your code with the snapshot version because we have just fixed a problem similar to yours.

**Comment by jlerbsc** [comment]
In the current snapshot the issue seems to be resolved.

    @Test
    void issue4018() {
        CompilationUnit cu = StaticJavaParser.parse("class A {\n"
        		+ "public void setThrottledRequests(int value) {\n"
        		+ "        int permits = _passes == null ? 0 : _passes.availablePermits();\n"
        		+ "        _passes = new Semaphore((value - _throttledRequests + permits), true);\n"
        		+ "        _throttledRequests = value;\n"
        		+ "    }\n"
        		+ "}");

        System.out.println(cu.toString());
    }


returns 

    class A {

    public void setThrottledRequests(int value) {
        int permits = _passes == null ? 0 : _passes.availablePermits();
        _passes = new Semaphore((value - _throttledRequests + permits), true);
        _throttledRequests = value;
    }
}

**Comment by olamy** [comment]
@jlerbsc thanks a lot for the fix. Sorry to not have time to test that :(
