### ISSUE TITLE
Can it Construct an AST and also display it?

### ISSUE THREAD

**Issue by EbenezerJesuraj** [javaparser/javaparser#4019]
Hi, I am using this java-parser to parse my java class code files. I was also wondering if this java-parser can also construct an AST for a given java-code since it contains ast related files in the src directory, if yes(can create an ast) how?

**Comment by jlerbsc** [comment]
Can you be more specific about what you want to do?

**Comment by EbenezerJesuraj** [comment]
I am developing a java rest service (preferable in spring) which 
 
 a) can parse a java class code (passed as string), 
 b) allows us to understand the list of methods in the class and also,
 c) replace the method source code from a string (containing the method code) upon demand.
 
 for b) part of the problem statement, i can see some code related to ast in this project but i am unclear as to how to use it properly (some help needed in this area)
 
 **Sample java code:** 
 package com.springbootastparser;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringbootastparserApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringbootastparserApplication.class, args);
	}

}

**AST Representation:**

COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
|--PACKAGE_DEF -> package [1:0]
|   |--ANNOTATIONS -> ANNOTATIONS [1:20]
|   |--DOT -> . [1:20]
|   |   |--DOT -> . [1:11]
|   |   |   |--IDENT -> com [1:8]
|   |   |   `--IDENT -> beezlabs [1:12]
|   |   `--IDENT -> springbootastparser [1:21]
|   `--SEMI -> ; [1:40]
|--IMPORT -> import [3:0]
|   |--DOT -> . [3:31]
|   |   |--DOT -> . [3:26]
|   |   |   |--DOT -> . [3:10]
|   |   |   |   |--IDENT -> org [3:7]
|   |   |   |   `--IDENT -> springframework [3:11]
|   |   |   `--IDENT -> boot [3:27]
|   |   `--IDENT -> SpringApplication [3:32]
|   `--SEMI -> ; [3:49]
|--IMPORT -> import [4:0]
|   |--DOT -> . [4:45]
|   |   |--DOT -> . [4:31]
|   |   |   |--DOT -> . [4:26]
|   |   |   |   |--DOT -> . [4:10]
|   |   |   |   |   |--IDENT -> org [4:7]
|   |   |   |   |   `--IDENT -> springframework [4:11]
|   |   |   |   `--IDENT -> boot [4:27]
|   |   |   `--IDENT -> autoconfigure [4:32]
|   |   `--IDENT -> SpringBootApplication [4:46]
|   `--SEMI -> ; [4:67]
`--CLASS_DEF -> CLASS_DEF [6:0]
    |--MODIFIERS -> MODIFIERS [6:0]
    |   |--ANNOTATION -> ANNOTATION [6:0]
    |   |   |--AT -> @ [6:0]
    |   |   `--IDENT -> SpringBootApplication [6:1]
    |   `--LITERAL_PUBLIC -> public [7:0]
    |--LITERAL_CLASS -> class [7:7]
    |--IDENT -> SpringbootastparserApplication [7:13]
    `--OBJBLOCK -> OBJBLOCK [7:44]
        |--LCURLY -> { [7:44]
        |--METHOD_DEF -> METHOD_DEF [9:1]
        |   |--MODIFIERS -> MODIFIERS [9:1]
        |   |   |--LITERAL_PUBLIC -> public [9:1]
        |   |   `--LITERAL_STATIC -> static [9:8]
        |   |--TYPE -> TYPE [9:15]
        |   |   `--LITERAL_VOID -> void [9:15]
        |   |--IDENT -> main [9:20]
        |   |--LPAREN -> ( [9:24]
        |   |--PARAMETERS -> PARAMETERS [9:25]
        |   |   `--PARAMETER_DEF -> PARAMETER_DEF [9:25]
        |   |       |--MODIFIERS -> MODIFIERS [9:25]
        |   |       |--TYPE -> TYPE [9:25]
        |   |       |   |--IDENT -> String [9:25]
        |   |       |   `--ARRAY_DECLARATOR -> [ [9:31]
        |   |       |       `--RBRACK -> ] [9:32]
        |   |       `--IDENT -> args [9:34]
        |   |--RPAREN -> ) [9:38]
        |   `--SLIST -> { [9:40]
        |       |--EXPR -> EXPR [10:23]
        |       |   `--METHOD_CALL -> ( [10:23]
        |       |       |--DOT -> . [10:19]
        |       |       |   |--IDENT -> SpringApplication [10:2]
        |       |       |   `--IDENT -> run [10:20]
        |       |       |--ELIST -> ELIST [10:54]
        |       |       |   |--EXPR -> EXPR [10:54]
        |       |       |   |   `--DOT -> . [10:54]
        |       |       |   |       |--IDENT -> SpringbootastparserApplication [10:24]
        |       |       |   |       `--LITERAL_CLASS -> class [10:55]
        |       |       |   |--COMMA -> , [10:60]
        |       |       |   `--EXPR -> EXPR [10:62]
        |       |       |       `--IDENT -> args [10:62]
        |       |       `--RPAREN -> ) [10:66]
        |       |--SEMI -> ; [10:67]
        |       `--RCURLY -> } [11:1]
        `--RCURLY -> } [13:0]
        
   Currently i have a different programs performing my requirement, i was hoping whether javaparser has the functionality to perform the same, as it would reduce a lot of time and effort..
   
   If Yes, can it also replace a specific method at AST level (since it's a form of binary tree representation, we can have faster operations) and regenerate the java class code back from the binary tree (AST)..
   
  Why this question?
  
  I am unclear of what operations this javaparser can perform.. since the github docs contain how to setup and compile and i believe there is a lot of documentation missing in how to use the various features of the javaparser..

**Comment by jlerbsc** [comment]
> I am unclear of what operations this javaparser can perform.. since the github docs contain how to setup and compile and i believe there is a lot of documentation missing in how to use the various features of the javaparser..

Have you take a look to https://leanpub.com/javaparservisited
https://tomassetti.me/wp-content/uploads/2017/12/JavaParser-JUG-Milano.pdf (slide 38)
https://github.com/javaparser/javaparser/wiki

**Comment by jlerbsc** [comment]
> COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
> |--PACKAGE_DEF -> package [1:0]
> | |--ANNOTATIONS -> ANNOTATIONS [1:20]
> | |--DOT -> . [1:20]
> | | |--DOT -> . [1:11]
> | | | |--IDENT -> com [1:8]

This is not an AST representation but more a list of tokens and position. Yes with a little work you can certainly get the same representation.

**Comment by jlerbsc** [comment]
> If Yes, can it also replace a specific method at AST level (since it's a form of binary tree representation, we can have faster operations) and regenerate the java class code back from the binary tree (AST)..

Yes you can modify an AST with Javaparser. You have many examples in unit tests for example.

**Comment by EbenezerJesuraj** [comment]
Hi, In your JavaParser website (javaparser.org), in the parse demo you have provided an example, 

"class A { }" well that was not working for me, what was working for me was simply class A { } without the double quotes as it was giving a parse error.. Is it a mistake in your website or was i using your parser in a wrong way.. By the way the links to the documentation was of great help as one couldn't find it in the README Section

**Comment by jlerbsc** [comment]
This code is correct

> StaticJavaParser.parse("class A{}");

**Comment by EbenezerJesuraj** [comment]
Attaching Screen-shots for reference 

1) First image with quotes

2) Second image without quotes

![JavaParser-ParseError](https://user-images.githubusercontent.com/33781574/236794955-9d6ac3d2-7226-48e6-878c-138cbe467522.png)

![JavaParser-Working Version](https://user-images.githubusercontent.com/33781574/236794970-4eca6438-313a-4631-affb-6d658fff07c7.png)

**Comment by jlerbsc** [comment]
This issue is related to your web site.

**Comment by EbenezerJesuraj** [comment]
Thanks for your help on the documentation area, Now I am  able to Parse java code, construct an AST and also replace method source code..

**Comment by jlerbsc** [comment]
Very well. If we answered your questions maybe you can close this issue?
