### ISSUE TITLE
Update/remove Java version in description

### ISSUE THREAD

**Issue by espertus** [javaparser/javaparser#4025]
The description for this repository is::
> Java 1-15 Parser and Abstract Syntax Tree for Java, including preview features to Java 13

This is out-of-date (and hard to keep up-to-date). Consider updating it to Java 17 or removing the version numbers.

![image](https://github.com/javaparser/javaparser/assets/661056/c78f4664-15fc-41ce-adce-9d137ef0ddf3)

**Comment by jlerbsc** [comment]
Thanks for your attention. It's corrected.
