### ISSUE TITLE
NameExpr for ClassOrInterfaceType

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javaparser#403]
I'd like to request storing the name of a `ClassOrInterfaceType` as `NameExpr` instead of using a simple String. This would allow us to query the name's location (which is not always consistent with the type node's location -> e.g. when the type has type arguments).

**Comment by matozoid** [comment]
This is actually already stored as a NameExpr, it just has strings in the API for ease of use. getNameExpr and setNameExpr will get it.

Is that helpful?

**Comment by mlangkabel** [comment]
Thanks for getting back to me. I just re-checked the implementation and I really cannot find where those methods are implemented. The constructor of the `ClassOrInterfaceType` only requires a String and no NameExpr as argument. Maybe I missed something. I hope I don't make a fool of my here ;)

**Comment by matozoid** [comment]
No, I'm the fool. I have no idea where I was looking but today I see the same as you :-) Will fix.
