### ISSUE TITLE
Resolving references between two separately parsed CompilationUnits

### ISSUE THREAD

**Issue by adrts-iscte** [javaparser/javaparser#4032]
Sorry for not being an issue, but a question about Symbol Solver usage.

Considering two CompilationUnit:
First:
```
class First {
   void method(int i) {
   }
}
```

Second:

```
class Second{
}
```

After changing the `method` parameter of the  `First` CompilationUnit to `Second i`:
```
class First {
   void method(Second i) {
   }
}
```

The question is: 
How can the ClassOrInterfaceType node `Second`, from `method` parameter, be solved to the class `Second`, if there is no connection between both CompilationUnit. 

PS: Please note that the whole process described above is done only in memory, without writing out both CompilationUnit to files.

**Comment by jlerbsc** [comment]
Excellent question. I think I would clone the first one and modify the clone rather than modifying directly to the class to be modified. Another way to do this would be to go through several phases: an analysis phase followed by a modification phase.

**Comment by adrts-iscte** [comment]
I don't know if I understood it correctly.

So, if I call `JavaParserFacade.get(which solver?).convertToUsage(*the ClassOrInterfaceType referring to the parameter SecondBill*)` it would refer to `Second` class? Even if both CompilationUnit don't know about each other?

**Comment by jlerbsc** [comment]
It is the domain of the symbol solver to ensure this knowledge. When you configure the parser you can declare how type resolution should be performed. For example, if you have the source code for the 2 classes, you can indicate to the symbol solver the root directory where the 2 classes are located. It will be able to know that the parameter of method method in class First is of type Second.

The documentation in the wiki (https://github.com/javaparser/javaparser/wiki) will certainly give you a better understanding of how to do this. You can also check out this book https://leanpub.com/user_dashboard/library

**Comment by adrts-iscte** [comment]
Thank you for your quick answers!

And is there any way to add the content of a CompilationUnit to the symbol solver's knowledge without writing out this CompilationUnit to a folder and indicate this root directory?

**Comment by jlerbsc** [comment]
I think you need to create classes dynamically. I have never had the opportunity to implement this type of solution but it is possible that the ReflectionTypeSolver can solve this type of problem. Maybe you could try and give some feedback to the community.

**Comment by adrts-iscte** [comment]
What do you mean by creating the classes dynamically? And how can we connect that to the SymbolSoler?

**Comment by jlerbsc** [comment]
You can do it for example with the MemoryTypeSolver

		MemoryTypeSolver mts = new MemoryTypeSolver();
		TypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), mts);
		StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));

		CompilationUnit cu = StaticJavaParser.parse("class First {}");
		cu.getClassByName("First").get().addMethod("method");

		CompilationUnit cu2 = StaticJavaParser.parse("class Second {}");
		ClassOrInterfaceDeclaration coid = cu2.findFirst(ClassOrInterfaceDeclaration.class).get();
		mts.addDeclaration("Second", coid.resolve()); <-- this is important for the Symbol solver

		MethodDeclaration md = cu.findFirst(MethodDeclaration.class).get();
		md.addParameter("Second", "i");

		ResolvedMethodDeclaration rmd = md.resolve();
		System.out.println(rmd.getQualifiedSignature());

**Comment by adrts-iscte** [comment]
Thank you for answering me so frequently!

I have tested your code (as you might have tested it before sending it to me) and it works fine!

However, I tested this one (sorry for being in Kotlin):
```val mts = MemoryTypeSolver()
    val typeSolver = CombinedTypeSolver(ReflectionTypeSolver(), mts)
    StaticJavaParser.getParserConfiguration().setSymbolResolver(JavaSymbolSolver(typeSolver))

    val cu = StaticJavaParser.parse(File("src/main/kotlin/tests/issueGitTest/First.java"))
    val cu2 = StaticJavaParser.parse(File("src/main/kotlin/tests/issueGitTest/Second.java"))

    val coid = cu2.findFirst(ClassOrInterfaceDeclaration::class.java).get()
    mts.addDeclaration("Second", coid.resolve()); // <-- this is important for the Symbol solver

    val md = cu.findFirst(MethodDeclaration::class.java).get()
    md.addParameter("Second", "i")

    val rmd = md.resolve()
    println(rmd.qualifiedSignature)
```

The only difference is how we obtain both CompilationUnit, but it still does not solve `Second` ClassOrInterfaceType:

```
Exception in thread "main" UnsolvedSymbolException{context='null', name='Second', cause='null'}
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:642)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:638)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:69)
	at com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:60)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:70)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:81)
```

**Comment by jlerbsc** [comment]
Assuming tests is your package, you need to add a JavaParserTypeSolver to CombinedTypeSolver. This must point to the src/main/kotlin directory

**Comment by adrts-iscte** [comment]
In the example I posted above, both CompilationUnit are in the same folder. However, how should I configure the JavaParserTypeSolver if both CompilationUnit are in two different projects, so they dont share the same source root. Should I add two JavaParserTypeSolver to the CombinedTypeSolver, one for each folder where the CompilationUnit are in?

**Comment by jlerbsc** [comment]
Yes that should work.

**Comment by adrts-iscte** [comment]
Thank you! I think this part is okay!

However, there is one thing that still confuses me.
I have these two files: 
```
package tests.classOrInterfaceTypeWrongReference;

/**
 * @author Meaglin
 */
public class BlockBreakEvent {
}
```
```
package tests.classOrInterfaceTypeWrongReference;

/**
 * Handles all events thrown in relation to Blocks
 *
 * @author durron597
 */
public class BlockListener {

    /**
     * Called when a block is destroyed by a player.
     *
     * @param event Relevant event details
     */
    public void onBlockBreak(BlockBreakEvent event) {
    }
}
```

When I resolve the `BlockBreakEvent` parameter of the `onBlockBreak` method, it resolves to the `BlockBreakEvent` class declaration, but when I debug the two CompilationUnit references are different.

![image](https://github.com/javaparser/javaparser/assets/58140205/6bc65f83-6a39-41d2-8c6a-3ac0a6ae1a55)

**Comment by jlerbsc** [comment]
Can you share the code you use these 2 classes?

**Comment by adrts-iscte** [comment]
The code used to obtain the print above is (in Kotlin):
```
val jpts = JavaParserTypeSolver("src/main/kotlin/")
    val typeSolver = CombinedTypeSolver(ReflectionTypeSolver(false), jpts)

    val cu = StaticJavaParser.parse(File("src/main/kotlin/tests/classOrInterfaceTypeWrongReference/BlockListener.java"))
    val cu2 = StaticJavaParser.parse(File("src/main/kotlin/tests/classOrInterfaceTypeWrongReference/BlockBreakEvent.java"))

    val onBlockBreak = cu.types[0].methods.find { it.nameAsString == "onBlockBreak" }
    onBlockBreak?.let {
        val resolved = JavaParserFacade.get(typeSolver).convertToUsage(onBlockBreak.findFirst(ClassOrInterfaceType::class.java).get())
        println((resolved.asReferenceType().typeDeclaration.get() as JavaParserClassDeclaration).wrappedNode.uuid)
    }
```

The two files are in this folder:

![image](https://github.com/javaparser/javaparser/assets/58140205/c1a12395-eda3-45b5-8ee6-b11e1987aa70)

**Comment by jlerbsc** [comment]
Does the wrapped node (ClassOrInterfaceDeclaration) have the same reference as the one contained in cu2?

**Comment by adrts-iscte** [comment]
It does not.
![image](https://github.com/javaparser/javaparser/assets/58140205/ea9648d3-5ef0-4e72-bf5d-761b77dc6a74)

**Comment by jlerbsc** [comment]
It is true that it seems curious but I will not have time to look more closely.

**Comment by adrts-iscte** [comment]
Ever? Or some day you will look closer? Thank you so much!

**Comment by jlerbsc** [comment]
When the symbol solver tries to solve a type it parses the corresponding source file. At this point, the solver type only knows the name of the class. It therefore generates a new CompilationUnit. This is the reason why the references are different.

**Comment by adrts-iscte** [comment]
So...is there a workaround to solve a type to the parsed CompilationUnit via SourceRoot or StaticJavaParser and avoid the parse of the TypeSolver?

**Comment by jlerbsc** [comment]
No what is the problem?

**Comment by adrts-iscte** [comment]
I would like to parse some files, modify them, solve the references (including ClassOrInterfaceType) and use information extracted from that modifications.

More specifically I want to add a UUID to the comments of code elements (classes, methods, fields, etc) to identify them. For example:

```
package tests.classOrInterfaceTypeWrongReference;
 /** * @author Meaglin 
* 3acc5937-7460-41cc-a22a-010b47a707c7
*/ 
public class BlockBreakEvent { }
```

When I solve a ClassOrInterfaceType to the ClassOrInterfaceDeclaration `BlockBreakEvent`, I want to compare the stored UUID to another UUIDs from other versions (left-base-right) of a three way merge scenario.

**Comment by adrts-iscte** [comment]
Everything is okay now! 
Thanks for the follow-up!

**Comment by jlerbsc** [comment]
Can you share more details on the resolution of the problem so that the community can benefit from your experience?

**Comment by adrts-iscte** [comment]
I changed my approach.

**Before:**

1. Parse
2. Add UUIDs
3. Solve all references

**Now**

1. Parse
2. Add UUIDs
3. Write out files again
4. Parse
5. Solve all references

This solves the problem and is fully compatible with the work I'm developing.
