### ISSUE TITLE
ParseProblemException Switch expressions are not supported

### ISSUE THREAD

**Issue by dimanyfantakis** [javaparser/javaparser#4038]
A ParseProblemException is thrown, with the message "Switch expressions are not supported", when calling StaticJavaParser.parse() with a file that contains the following method:
```
private List<String> identifyEdgeType(Relationship relationship){
    return switch (relationship.getRelationshipType()) {
        case DEPENDENCY -> Arrays.asList("dashed", "none", "plain");
        case AGGREGATION -> Arrays.asList("line", "white_diamond", "none");
        case ASSOCIATION -> Arrays.asList("line", "none", "standard");
        case EXTENSION -> Arrays.asList("line", "none", "white_delta");
        default -> Arrays.asList("dashed", "none", "white_delta");
    };
}
```
I found the following closed issues #1845 #2025 . I believe these issues solved the switch expression introduced in JDK12. In my understanding the above syntax was introduced in JDK13, [JEP354](https://openjdk.org/jeps/354).

**Comment by jlerbsc** [comment]
Can you provide us with a simplified test case that reproduces your issue?

**Comment by dimanyfantakis** [comment]
Yes, of course.
Can you please link me an example of how a simplified test case should look like?
Thanks for the quick response.

**Comment by jlerbsc** [comment]
Something like this for example

    @Test
    void issue4038() {
		String code =
		  "class A {\n"
		  + "..."
		  + "}";

		JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser());

		parser.getParserConfiguration().setLanguageLevel(LanguageLevel.JAVA_8); <-- What version of java are you using?

		CompilationUnit cu = parser.parse(code);

		//System.out.println(cu.toString());

	}

**Comment by dimanyfantakis** [comment]
Your example gave me an idea.
I swapped the StaticJavaParser with the JavaParserAdapter, as shown in the example, and set the language level.
For Java versions of 14 and above the exception isn't being thrown. It is only being thrown for versions 13 and below.
I guess that means that the StaticJavaParser uses an older language level. I couldn't find anything related to that in the 
_JavaParser: Visited_ book.
Thank you for your help.

**Comment by jlerbsc** [comment]
By default, StaticJavaParser uses Java 11 as the language level. You can configure the StaticJavaParser to use another language level like this:

    StaticJavaParser.getParserConfiguration().setLanguageLevel(LanguageLevel.JAVA_13);

Is this issue resolved?

**Comment by dimanyfantakis** [comment]
Yes, thanks for the assistance!

**Comment by hezhou66** [comment]
@Test
void issue4038() {
JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser());
        parser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_21);
               // .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
        //File file = new File("/Users/hezhou/IdeaProjects/Test/src/main/java/org/example/shiro/JavaParserTest.java");
        String code = "class Inner{\n" +
                "\n" +
                "        public static final String S = \"s\";\n" +
                "\n" +
                "        public void switchTest(String s){\n" +
                "            switch (s) {\n" +
                "                case Inner.S:\n" +
                "                    System.out.println(\"s\");\n" +
                "                    break;\n" +
                "                default:\n" +
                "                    System.out.println(\"default\");\n" +
                "                    break;\n" +
                "            }\n" +
                "        }\n" +
                "    }";
        CompilationUnit cu = parser.parse(code);
}

@jlerbsc   case with constant reference throw error

com.github.javaparser.ParseProblemException: (line 7,col 28) Parse error. Found ":", expected one of  "enum" "exports" "module" "open" "opens" "permits" "provides" "record" "requires" "sealed" "strictfp" "to" "transitive" "uses" "when" "with" "yield" <IDENTIFIER>
