### ISSUE TITLE
Can "sealed", "permits" keyworlds still be used as variable names (or method names) in Java 17?

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#4041]
As https://github.com/ctubbsii suggests "sealed", "permits" keyworlds are only keywords in a particular context.

https://openjdk.org/jeps/397
Specify the notion of a contextual keyword, superseding the prior notions of restricted identifier and restricted keyword in the JLS. Introduce the character sequences sealed, non-sealed, and permits as contextual keywords.

https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-Identifier

This refers to the discussion on the impact of this PR https://github.com/javaparser/javaparser/pull/4039

**Comment by pankajharness** [comment]
Hi @jlerbsc can I work on this issue?

**Comment by pankaj819kumar** [comment]
I am working on this issue.

**Comment by jlerbsc** [comment]
If you want to maximise the chances of your PR being accepted, please share your thoughts so that we can discuss them before submitting it.

**Comment by msridhar** [comment]
Hi there, we've run into this issue now on multiple projects.  Our workaround for the moment is to set the language level to 11, but of course that won't work for code that uses Java 17 constructs and (legally) uses `sealed` or `permits` as a variable name.

@jlerbsc I'm wondering if it makes sense to temporarily disable the check that is prohibiting use of `sealed` and `permits` as variable names at language level 17?  This check is presumably also catching invalid uses of `sealed` and `permits` (like as class names?), but overall my feeling is that in those cases, probably parsing would fail for some other reason?  In my opinion, it might be better to temporarily be more lenient, until the proper checking for contextual keywords can be implemented.

**Comment by jlerbsc** [comment]
> I'm wondering if it makes sense to temporarily disable the check that is prohibiting use of `sealed` and `permits`

Unfortunately this is not a solution and it would inconvenience other users. I think it's a bug.
