### ISSUE TITLE
Symbol Solver mixes name with type

### ISSUE THREAD

**Issue by magicwerk** [javaparser/javaparser#4047]
The attached test case shows how the symbol solver mixes name with type.
Instead of resolving "java.lang.Long.intValue()" (which is done correctly for a name like 'val'), the solver gets confused by the name "Integer". If analyzing with the debugger, it seems that the solver tries randomly to find a type with the name found in the local package, java.lang, etc., even if the name has been declared as local variable.
Version used: 3.25.3

Output:
```
java.lang.Integer.intValue
```

Source:
```
public class ShowBugSymbolResolverMixNameWithType {

	String src = "public class MyClass { \r\n"
			+ "  static void f() { \r\n"
			+ "    Long Integer = null; \r\n"
			+ "    Integer.intValue(); \r\n"
			+ "  } \r\n"
			+ "} \r\n";

	public static void main(String[] args) {
		new ShowBugSymbolResolverMixNameWithType().run();
	}

	void run() {
		CompilationUnit cu = parse(src);
		cu.findAll(MethodCallExpr.class).forEach(n -> {
			ResolvedMethodDeclaration r = n.resolve();
			System.out.println(r.getQualifiedName());
		});
	}

	CompilationUnit parse(String src) {
		JavaParser parser = getParser();
		ParseResult<CompilationUnit> pr = parser.parse(src);
		return pr.getResult().get();
	}

	JavaParser getParser() {
		CombinedTypeSolver typeSolver = new CombinedTypeSolver();
		typeSolver.add(new ReflectionTypeSolver());
		ParserConfiguration cfg = new ParserConfiguration();
		cfg.setSymbolResolver(new JavaSymbolSolver(typeSolver));
		return new JavaParser(cfg);
	}
}
```

**Comment by hardik6955** [comment]
solve r means

**Comment by julian5392** [comment]
It also seems like can't resolve the method from user-written and third-party libraries.

**Comment by jlerbsc** [comment]
> It also seems like can't resolve the method from user-written and third-party libraries.

The CombinedTypeSolver  must be configure with a JavaparserTypeSolver (for java source files) and JarTypeSolver (for external libraries).
