### ISSUE TITLE
switch case block without brace when parent node is SwitchEntry

### ISSUE THREAD

**Issue by shijinkui** [javaparser/javaparser#4048]
when print the final code, the switch have brace like below:

```
            switch (x) {
                case 1: {
                    System.out.println(11);
                }
                break;
                case 2: {
                    System.out.println(22);
                }
                break;
            }
```

should be:
```
            switch (x) {
                case 1:
                    System.out.println(11);
                    break;
                case 2:
                    System.out.println(22);
                    break;
            }
```

**Comment by jlerbsc** [comment]
Hi,
Can you provide us with more information on the issue you are experiencing as well as unit tests that illustrate the problem and demonstrate that your solution fixes these issues?

**Comment by shijinkui** [comment]
> r
hi, 
In the Java code best practice, the case block with braces' readability is worse. Case with same indent is better read when the code more than ten lines. So, most of java code style rule disable case block braces. thx

**Comment by shijinkui** [comment]
![image](https://github.com/javaparser/javaparser/assets/648508/b49fc049-47c9-4a7d-91d5-fd543e5c2ebe)

**Comment by jlerbsc** [comment]
Can you provide us with a test case that reproduces the problem? How do you produce the  'final code'? Thanks.

**Comment by jlerbsc** [comment]
Can you show us that JP produces this code otherwise I will close this issue.

**Comment by jlerbsc** [comment]
Since we couldn't get a simple test case to reproduce this error, I'm closing the issue.
