### ISSUE TITLE
Switched upperBounds and lowerBounds on ResolvedTypeParameterDeclaration

### ISSUE THREAD

**Issue by Elewyth** [javaparser/javaparser#4051]
Hi

The class `ResolvedTypeParameterDeclaration` has the following methods:

- `hasUpperBound()`
- `hasLowerBound()`
- `getUpperBound()`
- `getLowerBound()`

The implementation of these methods check for the presence of an `extends` or `super` clause, respectively. However, I think these have been switched: `hasUpperBound()` checks for the presence of `super`, and `hasLowerBound()` returns `true`, if there is an `extends`.

As a reference, e.g. [this tutorial](https://docs.oracle.com/javase/tutorial/java/generics/upperBounded.html) calls the usage of `extends` an upper bound, while `ResolvedTypeParameterDeclaration` calls it a lower bound.

Edit: it seems the same is the case in `ResolvedWildcard` for the methods `isUpperBounded()` and `isLowerBounded()`.

Version: `3.25.3`

**Comment by jlerbsc** [comment]
@ftomassetti Do you agree with this observation? It seems to me that it is correct but I am surprised that there are not more issues on this subject.

**Comment by ftomassetti** [comment]
I agree: `extends` -> upper, `super` -> lower

https://docs.oracle.com/javase/tutorial/java/generics/upperBounded.html
