### ISSUE TITLE
[BUG] isDeclaredInInterface() returns true for fields inside Enums inside Interface

### ISSUE THREAD

**Issue by Elewyth** [javaparser/javaparser#4056]
Hi,

The method `#isPublic()` of `FieldDeclaration` checks either for the presence of a `public` modifer, or whether the field is part of an interface (`isDeclaredInInterface()`). The reasoning is that fields inside interfaces are always implicitly `public static final`. Unfortunately, this check is no implemented properly: it searches for the nearest `ClassOrInterfaceDeclaration` in the parent-hierarchy of the node, and returns `true`, if that node is an interface.

In the case where the field is part of an Enum (which is not a `ClassOrInterfaceDeclaration`, but rather a separate `EnumDeclaration`), the Enum is skipped and instead the enclosing interface is found.

Test Case:
```java
import com.github.javaparser.StaticJavaParser;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.hasSize;
import static org.junit.jupiter.api.Assertions.assertFalse;

class JavaParserIsPublicTest {

  @Test
  void testEnumWithPrivateFieldInsideInterface() {
    var source = """
        interface Outer {
          enum Numbers {
            ONE(1),
            TWO(2),
            THREE(3);

            Numbers(int i) {
              this.i = i;
            }

            private final int i;
          }
        }""";
    var cu = StaticJavaParser.parse(source);
    var types = cu.getTypes();
    assertThat(types, hasSize(1)); // OK

    var interfaceMembers = types.get(0).asClassOrInterfaceDeclaration().getMembers();
    assertThat(interfaceMembers, hasSize(1)); // OK

    var enumType = interfaceMembers.get(0).asEnumDeclaration();
    var enumFields = enumType.getFields();
    assertThat(enumFields, hasSize(1)); // OK

    var i = enumFields.get(0);
    assertFalse(i.isPublic()); // FAILS
  }
}
```

It seems this also applies to `isStatic()` and `isFinal()`, as they also use `isDeclaredInInterface`.

Suggested fix: extend `isDeclaredInInterface` to properly also check whether the field is declared in an `EnumDeclaration`, instead of only checking `ClassOrInterfaceDeclaration`.

Tested Version: `3.25.3`

A real-life occurrence of such a code sample (private field inside Enum inside Interface) can be found e.g. in `java.lang.System.Logger.Level#severity` of the JDK (17 Eclipse Adoptium).

**Comment by jlerbsc** [comment]
Why do you have 2 commits with the same fix?

**Comment by Elewyth** [comment]
> Why do you have 2 commits with the same fix?

I missed deleting a comment in the first commit and amended the correction into it (and force pushed the change). This now shows up as two separate commits in the issue history, but only the first one is relevant (the one linked in the PR).

i.e. https://github.com/Elewyth/javaparser/commit/3e192b41989243d3d8654b48306120a0010f45e8

**Comment by jlerbsc** [comment]
Can you make the commits more readable?

**Comment by Elewyth** [comment]
> Can you make the commits more readable?

Certainly, can you tell me what you don't find readable enough?

**Comment by jlerbsc** [comment]
Multiple commits for a single change.

**Comment by Elewyth** [comment]
Do you want me to squash the commits on the PR?

If you mean the seemingly same commits shown on this issue - I'm not sure what I can do. The "duplicated" commit (c666dca) doesn't exist on my fork or on the PR. I don't know how to remove it from this issue's history. If you check the PR you will only find the commit 3e192b4, which is the correct commit.
