### ISSUE TITLE
Getting the raw type from a Type

### ISSUE THREAD

**Issue by cowwoc** [javaparser/javaparser#4059]
When I retrieve the return type of a method, I get back a generic type. Does the API provide any way to convert this to the raw form, or am I supposed to manually strip `<...>` out of the returned string?

**Comment by cowwoc** [comment]
Nevermind. The following worked for me:

```
private String getRawTypeAsString(Type type)
{
	if (type.isClassOrInterfaceType())
		return type.asClassOrInterfaceType().getNameAsString();
	return type.toString();
}
```

**Comment by jlerbsc** [comment]
If you have resolved the return type of the method you can use the following methods

     @Test
    // The erasure of a parameterized type
    void erasure_rawtype() {
        List<ResolvedType> types = declaredTypes(
                "class A<String> {}");
        ResolvedType rt = types.get(0);
        String expected = "A";
        ResolvedType erasedType = rt.erasure();
        assertTrue(rt.asReferenceType().isRawType());
        assertEquals(expected, erasedType.describe());
    }

The detail is implemented in the ReferenceTypeTest class
