### ISSUE TITLE
Use of Diamond Operator bugged?

### ISSUE THREAD

**Issue by ninehusky** [javaparser/javaparser#4069]
Hey! 👋

I'm using JavaParser to analyze the use of missing generics. That is, I'd like to distinguish `Stack<Integer> s = new Stack<>();` from `Stack<Integer> s = new Stack();`.

I've explored using the `isUsingDiamondOperator` method on the `ObjectCreationExpr` class, but things seem to be off. I've tried writing a minimal example to demonstrate this: with the given code, is this the expected output? If not, happy to try my hand at a fix!

The code:
```
public class Main {
    public static void main(String[] args) {
        String code = "import java.util.Stack;\n\n" +
                "public class Main {\n" +
                "    public static void main(String[] args) {\n" +
                "        Stack<Integer> s1 = new Stack();\n" +
                "        Stack<Integer> s2 = new Stack<>();\n" +
                "    }\n" +
                "}";

        CompilationUnit cu = StaticJavaParser.parse(code);
        cu.accept(new ObjectCreationVisitor(), null);
    }

    private static class ObjectCreationVisitor extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(ObjectCreationExpr objectCreationExpr, Void arg) {
            super.visit(objectCreationExpr, arg);
            String javaCode = objectCreationExpr.toString();

            System.out.println(javaCode + " - Using diamond operator: " + objectCreationExpr.isUsingDiamondOperator());
        }
    }
}
```

The output:
```
new Stack() - Using diamond operator: false
new Stack<>() - Using diamond operator: false
```

Thanks in advance for the help!

**Comment by jlerbsc** [comment]
Hi @ninehusky you can resolve your issue with this code because v must be used on a Type.

    objectCreationExpr.getType().isUsingDiamondOperator()

**Comment by ninehusky** [comment]
Thank you! This was exactly what I needed.
