### ISSUE TITLE
JavaParser crashes due to unique char literal

### ISSUE THREAD

**Issue by ritvikraj1998** [javaparser/javaparser#4070]
'√' char literal causes java parser to crash. I tried to parse code of this [file](https://github.com/HouariZegai/Calculator/blob/master/src/main/java/com/houarizegai/calculator/ui/CalculatorUI.java).
Java parser crashed due to presence of the above literal in line 463. Replacing this with something else fixes the issue.

**Comment by jlerbsc** [comment]
I cannot reproduce your issue with this test case! What is your error message?

    @Test
    void issue4070() {
		String code = "char selectedOperator = '√'";
		JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser());
		VariableDeclarationExpr vde = parser.parseVariableDeclarationExpr(code);
		System.out.println(vde.toString());
	}

**Comment by jlerbsc** [comment]
Have you solved this issue?

**Comment by Lym666XD** [comment]
Guys may I take this testing issue?

**Comment by jlerbsc** [comment]
Of course, but this issue is not reproducible. I think I'll close it.

**Comment by Lym666XD** [comment]
thx by the way lol

**Comment by jlerbsc** [comment]
I am closing this issue because it is not reproducible and we have not had any additional information for several months.
