### ISSUE TITLE
Get a Node from SymbolSolver

### ISSUE THREAD

**Issue by KRK224** [javaparser/javaparser#4076]
Hi, I'm new user of javaParser.

I'm using SymbolSolver and find the resolvedType from it, but it seems ResolvedType has only the node's  metaData.
Is there any way to get (or access) a Node from ResolvedType? I want to set DataKey to Method Declaration Node which is resolved from the MethodCallExpr.

Here is my code,
```java
...
            CompilationUnit cu = optionalCompilationUnit.get();

            System.out.println("cu:::" + cu.getStorage().get().getFileName());
            // AtomicInteger ordinal = new AtomicInteger(0);

            cu.findAll(MethodCallExpr.class).forEach(node -> {

              System.out.println("********");
              System.out.println(" * Method Call::: " + node);

              printMethodReference(node);

              System.out.println("********\n");
...
```
```java
public static boolean printMethodReference(MethodCallExpr node) throws UnsolvedSymbolException {
    try {
      // node.resolve();
      System.out.println("packageName::: " + node.resolve().getPackageName());
      System.out.println("className:::" + node.resolve().getClassName());
      System.out.println("className.methodDeclaration::: " +
          node.resolve().getQualifiedSignature());
      return true;

    } catch (UnsolvedSymbolException e) {
      System.out.println("=================");
      System.out.printf("!!!!!!!! Got an Error to find reference for \'%s\' \n", node.getName());
      System.out.println(e.getMessage());
      System.out.println("=================");
      return false;
    }

  }
```
I can find the resolved type and its metadata as below, but I want to access the Node which is resolved from methodCallExpr.

```console
...
********
 * Method Call::: randomNumberGenerator.generate()
packageName::: application.generator
className:::RandomNumberGenerator
className.methodDeclaration::: application.generator.RandomNumberGenerator.generate()
********

********
 * Method Call::: fixedNumberGenerator.generate()
packageName::: application.generator
className:::FixedNumberGenerator
className.methodDeclaration::: application.generator.FixedNumberGenerator.generate()
********
...
```

**Comment by jlerbsc** [comment]
Hi @KRK224 You can get the node of all classes that implement AssociableToAST interface. In fact the AST is only really available for the classes for which you have the source code (for which the parser can generate the AST).

In your case resolving a MethodCallExpr node returns a ResolvedMethodDeclaration instance which implements the AssociableToAST interface. You can therefore call the toAst(<Type of node>) method to obtain the declaration of the method (MethodDeclaration).

An example is better than a long speech

    @Test
	void issue4076() {
		String testCase =
				"public class A {\n"
				+ "    public static void main(String[] args) {\n"
				+ "        A a = new A();\n"
				+ "        a.show();\n"
				+ "    }\n"
				+ "    public void show() {\n"
				+ "    }\n"
				+ "}";
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser(config));

        CompilationUnit cu = parser.parse(testCase);
        List<MethodCallExpr> methods = cu.findAll(MethodCallExpr.class);
        for (MethodCallExpr mce : methods) {
        	Optional<MethodDeclaration>  md = mce.resolve().toAst(MethodDeclaration.class);
                System.out.println(mce.toString()+" -> "+ md.toString());
        }
	}

**Comment by KRK224** [comment]
I really appreciate your support! Thank you:) @jlerbsc

**Comment by KRK224** [comment]
Hi, @jlerbsc 

I've found out that return data from toAst() is different from original cu's node.

what I try to do is as below:

1. Parsing all CompilationUnit with SymbolSolver
2. find all MethodCallExprs in each of CU and resolve its MethodDeclaration.
3. register information of MethodCallExpr to resolved MethodDeclaration's DataKey by toAst() method.
4. after Step 3, check all the MethodDeclaration in every CU that it has DataKey.

The problem is the MethodDeclaration derived from toAst is different from node in original cu in step 4.
it happened when MethodDeclaration is not in the same cu with MethodCallExpr.

<Step 3 Logic>

```java
  public static boolean printMethodReference(MethodCallExpr node)
      throws UnsolvedSymbolException {
    try {

      System.out.println("packageName::: " + node.resolve().getPackageName());
      System.out.println("className:::" + node.resolve().getClassName());
      System.out.println("className.getQualifiedSignature()::: " + node.resolve().getQualifiedSignature());

      // resolve to AST
      Optional<MethodDeclaration> md = node.resolve().toAst(MethodDeclaration.class);

      if (md.isPresent()) {
        MethodDeclaration refDeclaration = md.get();
        System.out.println(refDeclaration.getSignature());
        System.out.println(refDeclaration.getMetaModel().getTypeName());

        if (refDeclaration.getSignature().toString().equals("getCode()")) {
          Optional<Node> parentNodeOptional = null;
          Node parentNode = refDeclaration;

          // search the cu of resolved MethodDeclaration.
          do {
            parentNodeOptional = parentNode.getParentNode();
            parentNode = parentNodeOptional.get();

          } while (parentNode.getParentNode().isPresent());

          System.out.println(parentNode.getMetaModel().getTypeName()); // CompilationUnit
          tempGameStatusNodeFromToAst = parentNode; // saving in NodeType variable
          System.out.println(parentNode);

        }
        if (!md.get().containsData(childList)) {
          List<String> meNameList = new ArrayList<String>();
          System.out.println("DataKey is absent!");
          meNameList.add(node.toString());
          md.get().setData(childList, meNameList);
          System.out.println("check DataKey:::: " + md.get().getData(childList));
        } else {
          System.out.println("DataKey is present:::" + md.get().getDataKeys());
          List<String> tempMeNameList = md.get().getData(childList);
          tempMeNameList.add(node.toString());
          md.get().setData(childList, tempMeNameList);
          System.out.println("check DataKey:::: " + md.get().getData(childList));
        }

      }
      return true;

    } catch (UnsolvedSymbolException e) {
      System.out.println("=================");
      System.out.printf("!!!!!!!! Got an Error to find reference for \'%s\' \n", node.getName());
      System.out.println(e.getMessage());
      System.out.println("=================");
      return false;
    }

  }
```

I saved the CompilationUnit from MethodDeclaration's getParentNode() during Step 3 and compare it with original cu in Step 4 as below.

![image](https://github.com/javaparser/javaparser/assets/23701537/cb9c212e-83a6-45be-be7f-3eeffab8a94e)


they are different CompilationUnit but same contents.

```console
cu:::GameStatus.java
# original CU
package application.constant;

public enum GameStatus {

    PREPARING(0), PLAYING(1), END(2);

    private final int gameStatus;

    GameStatus(int gameStatus) {
        this.gameStatus = gameStatus;
    }

    public Integer getCode() {
        return gameStatus;
    }
}
# derived from toAst()
package application.constant;

public enum GameStatus {

    PREPARING(0), PLAYING(1), END(2);

    private final int gameStatus;

    GameStatus(int gameStatus) {
        this.gameStatus = gameStatus;
    }

    public Integer getCode() {
        return gameStatus;
    }
}
```

could you explain why this happened and how to use same CU and Node in Step 3 and Step4?

you can find all source code in [here](https://github.com/KRK224/javaparser-symbolsolver-test/tree/issue)

**Comment by jlerbsc** [comment]
Type resolution effectively creates new objects different from those produced by the parser which makes sense because they are 2 different features. For example, you could perfectly resolve a method of a class that has not been parsed. Furthermore you are using an internal property of "data" nodes with a key value that is not suitable for this operation. You have to change your way.

**Comment by KRK224** [comment]
Thank you for your explanation @jlerbsc! :)

The code is for the test that we could store dto object which has MethodCallExpr's information to MethodDeclaration Node.

Parsed MethodDeclaration Node is also going to be transformed into dto object and get relation with MethodCallExpr dto. that's why we are trying to save DataKey value(it will be dto object of MethodCallExpr) to MethodDeclaration Node.

According to your explanation, The object created by type resolution is different with parsed node and we can't map to another. so we will change our strategy to link MethodCallExpr to MethodDeclaration.

Thank you so much for answering me quickly!
