### ISSUE TITLE
Minor java.jj grammar issue

### ISSUE THREAD

**Issue by reportmill** [javaparser/javaparser#4079]
In the java.jj grammar file, the definition for StatementExpression (line 4408) starts out:

( LOOKAHEAD(2) PreIncrementExpression | PreDecrementExpression | PrimaryExpression ...

What is the point of the LOOKAHEAD(2) ? Seems like it only applies to the PreIncrementExpression, and if the first token is "++", it should evaluate that rule.

I've been trying to understand grammars, and since this is such a great one, I'm wondering if I'm missing something. :-)

**Comment by jlerbsc** [comment]
I'm not sure but the lookahead doesn't seem essential here.

**Comment by reportmill** [comment]
Thanks! I was just trying to decide if I was missing something.
