### ISSUE TITLE
Parameter type solved failed

### ISSUE THREAD

**Issue by julian5392** [javaparser/javaparser#4095]
Thank you for checking it out of your busy schedule. When I solve the constructor, the interface Node defined in org.w3c.dom cannot be solved. I'm not sure if there's a problem with my typesolvers setup.Org.w3c.dom exists in JDK11 and how to introduce it into typesolves.It seems that there may also be a problem with javaparser solving that the parameter is an interface type.

This is a error report:
`BitsPerComponentBox.BitsPerComponentBox(byte[])
Exception in thread "main" UnsolvedSymbolException{context='null', name='Node', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:509)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:567)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:563)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:78)
	at com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:61)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:71)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:82)
	at testcode.Main.main(Main.java:59)`
This is a reproducible testcase：
```
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.util.List;

public class Main {
    public static void main(String[] args) {
        String sourcecode ="import javax.imageio.metadata.IIOInvalidTreeException;\n" +
                "\n" +
                "import org.w3c.dom.Node;\n" +
                "import org.w3c.dom.NodeList;\n" +
                "public class BitsPerComponentBox extends Box {\n" +
                "    /** Counstructs a <code>BitsPerComponentBox</code> from the provided\n" +
                "     *  byte array containing the bit depths of each color component.\n" +
                "     */\n" +
                "    public BitsPerComponentBox(byte[] bitDepth) {\n" +
                "        super(8 + bitDepth.length,  0x62706363, null);\n" +
                "        data = bitDepth;\n" +
                "    }\n" +
                "\n" +
                "    /** Constructs a <code>BitsPerComponentBox</code> based on the provide\n" +
                "     *  <code>org.w3c.dom.Node</code>.\n" +
                "     */\n" +
                "    public BitsPerComponentBox(Node node) throws IIOInvalidTreeException {\n" +
                "        super(node);\n" +
                "        NodeList children = node.getChildNodes();\n" +
                "\n" +
                "        for (int i = 0; i < children.getLength(); i++) {\n" +
                "            Node child = children.item(i);\n" +
                "            String name = child.getNodeName();\n" +
                "\n" +

                "        }\n" +
                "    }\n" +
                "\n" +
                "    /** Returns the bit depths for all the image components. */\n" +
                "    public byte[] getBitDepth() {\n" +
                "        return data;\n" +
                "    }\n" +
                "}";
        CombinedTypeSolver myTypeSolver = new CombinedTypeSolver();
        myTypeSolver.add(new ReflectionTypeSolver());
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(myTypeSolver);

        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(sourcecode);
        List<ConstructorDeclaration> constructors = cu.findAll(ConstructorDeclaration.class);
        for (ConstructorDeclaration constructor : constructors) {
            String constructorName = constructor.resolve().getQualifiedSignature();
            System.out.println(constructorName);

        }
    }
}
```

**Comment by jlerbsc** [comment]
Are you running the code with a java 11?

**Comment by julian5392** [comment]
yes

**Comment by jlerbsc** [comment]
Could this be caused by a module declaration?

**Comment by julian5392** [comment]
Sorry, I dont know what you mean.

**Comment by jlerbsc** [comment]
You need to fix your config because actually the jreOnly flag in ReflectionTypeSolver is true, which means it will only resolve types from java or javax packages

> new ReflectionTypeSolver(false)

**Comment by julian5392** [comment]
Thank you, does setting to false have any side effects? And in another situation, method parameter type is self-written interface. The parameters of this method will fail to solve in the complete source code, but when I locate the method that failed to solve and extract a small use case for analysis, it can solve successfully.

**Comment by jlerbsc** [comment]
> does setting to false have any side effects?

No there is no side effect. In this case reflection is not limited to the packages java ant javax.

**Comment by jlerbsc** [comment]
> The parameters of this method will fail to solve in the complete source code, but when I locate the method that failed to solve and extract a small use case for analysis, it can solve successfully.

Without reproducible test cases it is difficult to find the cause of this issue.

**Comment by jlerbsc** [comment]
Can we close this issue or do you have more information to provide?

**Comment by julian5392** [comment]
Sorry, I can't provide a simplified testcase. But here are still problems parsing the whole testcase, maybe a bit big, , I can provide the corresponding program.

**Comment by julian5392** [comment]
[ParaSolveFailed.zip](https://github.com/javaparser/javaparser/files/12066738/ParaSolveFailed.zip)

**Comment by jlerbsc** [comment]
What class are you having a problem with?

**Comment by julian5392** [comment]
The problem occurred in this file, parameter solving for its constructor failed.
src/main/java/org/zeroturnaround/zip/transform/ZipEntrySourceZipEntryTransformer.java
```
  public ZipEntrySourceZipEntryTransformer(ZipEntrySource source) {
    this.source = source;
  }
```
ZipEntrySource is declared in src/main/java/org/zeroturnaround/zip/ZipEntrySource.java
The error report:
```
Exception in thread "main" UnsolvedSymbolException{context='null', name='ZipEntrySource', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:509)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:567)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:563)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:78)
	at com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:61)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:71)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:82)
	at javaparsetest.Main.getConstructorDeclaration(Main.java:71)
	at javaparsetest.Main.main(Main.java:30)
```

**Comment by jlerbsc** [comment]
Even if this is not the source of your problem, the main class can be improved because it is not necessary to configure the parser for each file. On the other hand, it seems that the JavaParserTypeSolver is not correctly instantiated because it must reference the directory where the source code is located. In your case, the source files can be found in particular under src\main\code\src\test\java...

**Comment by julian5392** [comment]
Thank you, this works. So in JavaParserTypeSolver("path"), must the path be a folder before the package folder?

**Comment by jlerbsc** [comment]
Absolutely.

**Comment by jlerbsc** [comment]
I think we have answered all the questions so now this issue can be closed.
