### ISSUE TITLE
Detecting depth of nested if and if-else statements using java-parser

### ISSUE THREAD

**Issue by alwaysaditi** [javaparser/javaparser#4098]
Hey , I have been using javaparser for some time , and tried to write code that can count the number of if and else-if statements within nested if statements. The depth of the else-if statements is based on the condition , hence I used a hashmap to store the first time an ifcondition is encountered on a variable, so that if it is encountered again , it would mean that it is an else statement. As I am quite new to contributing to java-parser, I just wanted to know whether I could open this as a pull request to be integrated into javaparser ?

Here is an example

```
class Main {
  public static void main(String[] args) {
    System.out.println("Hello world!");
    int a =1;
    int b=2;
    int c =3;
int d=4;
    if(a==1)
    {
      if(b==1)
      {
        
      }
      else if(b==2)
      {
         if(c==1)
        {
          
        }
        else if(c==2)
        {
          
        }

        else if(c==3)
        {
          if(d==1)
          {
            
          }

          else if(d==2)
          {
            
          }

          else if(d==3)
          {
            
          }

          else if(d==4)
          {
            System.out.println("a=1,b=2,c=3,d=4");
          }
        }
      }

      else if(b==3)
      {
       
      }

      else if(b==4)
      {
        
      }
    }
  }
}`
```

Here the conditions on the variables , b ,c and d are nested if statements and basically I wrote to count the  number of else if statements in nested if statements. As we can see the number of if and if-else statements conditioned on variable b is 4 , those on variable c is 3 and those on variable d is 4.

Here is the output of the code
<img width="517" alt="image" src="https://github.com/javaparser/javaparser/assets/68003668/9074de89-0f64-4c9b-bd65-f072d573767e">

Do let me know if it would be worth incorporating this into javaparser. Thank you! 

edit : I didn't open a pull request yet since I don't think there was any potential issue that could be fixed by this, was just an improvement I thought would be interesting

**Comment by jlerbsc** [comment]
Thank you for your suggestion but it's not a feature that we will try to integrate in JP because JP does not aim to provide this kind of metric.

**Comment by alwaysaditi** [comment]
No worries, thanks for reviewing ! I’ll try to see if there’s any more issues that I can work on in JP

**Comment by jlerbsc** [comment]
I'm closing this issue because we answered the question.
