### ISSUE TITLE
Unsupported types when getting default values from reflectively resolved annotations

### ISSUE THREAD

**Issue by freya022** [javaparser/javaparser#4099]
## Problem
The symbol solver is unable to get default value of reflectively resolved annotations of types such as `Class` or any array type

<details>
<summary>Test code</summary>

```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.expr.AnnotationExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR})
@Retention(RetentionPolicy.SOURCE)
@interface TargetType {
    Class<?>[] packagesOf();

    Class<?>[] classes() default {};
}

// Please note that this test was made outside a package
// To run this test you need to qualify the package name on the `@TargetType`
public class JavaParserBugTest { 
    private static final String TEST_CODE = "public class TargetTypeTest {\n" +
                                            "    @TargetType(packagesOf = {Expression.class, NodeList.class})\n" +
                                            "    public TargetTypeTest(List<Expression> expressions) {\n" +
                                            "        System.out.println(expressions.stream().collect(NodeList.toNodeList()));\n" +
                                            "    }\n" +
                                            "}\n";

    public static void main(String[] args) throws Exception {
        final ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));

        final JavaParser parser = new JavaParser(parserConfiguration);
        final ParseResult<CompilationUnit> parse = parser.parse(TEST_CODE);

        final CompilationUnit cu = parse.getResult().get();
        final ClassOrInterfaceDeclaration classDeclaration = cu.getClassByName("TargetTypeTest").get();
        final ConstructorDeclaration constructorDeclaration = classDeclaration.getConstructors().get(0);
        final AnnotationExpr annotationExpr = constructorDeclaration.getAnnotationByClass(TargetType.class).get();

        System.out.println(annotationExpr.resolve().getAnnotationMembers().stream()
                .filter(a -> "classes".equals(a.getName()))
                .findAny()
                .orElseThrow(() -> new AssertionError("No annotation value with name 'classes'"))
                .getDefaultValue());
    }
}
```
</details>

<details>
<summary>Exception</summary>
Exception in thread "main" java.lang.UnsupportedOperationException: Obtaining the type of the annotation member classes is not supported yet.
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionAnnotationMemberDeclaration.getDefaultValue(ReflectionAnnotationMemberDeclaration.java:65)
</details>

## Workaround
You can add your own expression converters:

<details>
<summary>Workaround</summary>

```java
static {
    try {
        final Field converterMapField = ReflectionAnnotationMemberDeclaration.class.getDeclaredField("valueAsExressionConverter");
        converterMapField.setAccessible(true);
        @SuppressWarnings("unchecked")
        final Map<Class<?>, Function<Object, ? extends Expression>> map = (Map<Class<?>, Function<Object, ? extends Expression>>) converterMapField.get(null);

        final JavaParser javaParser = new JavaParser();
        map.put(Class.class, o -> javaParser.parseExpression(((Class<?>) o).getName() + ".class").getResult().get());
        map.put(Class[].class, o -> {
            final Class<?>[] classes = (Class<?>[]) o;
            final NodeList<Expression> classExpressions = Arrays.stream(classes)
                    .map(a -> (Expression) map.get(Class.class).apply(a))
                    .collect(NodeList.toNodeList());
            return new ArrayInitializerExpr(classExpressions);
        });
    } catch (Exception e) {
        throw new RuntimeException(e);
    }
}
```
</details>

**Comment by jlerbsc** [comment]
From your test case I get this which looks correct to me. What are you getting?

> {}

**Comment by freya022** [comment]
```
Exception in thread "main" java.lang.UnsupportedOperationException: Obtaining the type of the annotation member classes is not supported yet.
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionAnnotationMemberDeclaration.getDefaultValue(ReflectionAnnotationMemberDeclaration.java:65)
```

`Method#getDefaultValue` returns a 0-length `Class` array, which it then tries to convert

I should be able to write a PR to support classes and 1D arrays, as well as handle null default values.

(I have updated the code and exception on the issue post)

**Comment by jlerbsc** [comment]
What version of JP are you using?

**Comment by freya022** [comment]
> What version of JP are you using?

`com.github.javaparser:javaparser-symbol-solver-core:3.25.4`

**Comment by jlerbsc** [comment]
I cannot reproduce your issue with this test case.

Please check your configuration or test case because the ReflectionAnnotationMemberDeclaration.getDefaultValue method is implemented since version 3.19.0 (https://github.com/javaparser/javaparser/pull/3055)


    @Test
	void test4099() {
		String TEST_CODE =
				"import java.lang.annotation.ElementType;\n"
				+ "import java.lang.annotation.Retention;\n"
				+ "import java.lang.annotation.RetentionPolicy;\n"
				+ "import java.lang.annotation.Target;"
				+ "@Target({ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR})\n"
				+ "@Retention(RetentionPolicy.SOURCE)\n"
				+ "@interface TargetType {\n"
				+ "  Class<?>[] packagesOf();\n"
				+ "\n"
				+ "  Class<?>[] classes() default {String.class};\n"
				+ "}"
				+"public class TargetTypeTest {\n" +
                "    @TargetType(packagesOf = {Expression.class, NodeList.class})\n" +
                "    public TargetTypeTest(List<Expression> expressions) {\n" +
                "        System.out.println(expressions.stream().collect(NodeList.toNodeList()));\n" +
                "    }\n" +
                "}\n";

		final ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));

        final JavaParser parser = new JavaParser(parserConfiguration);
        final ParseResult<CompilationUnit> parse = parser.parse(TEST_CODE);

        final CompilationUnit cu = parse.getResult().get();
        final ClassOrInterfaceDeclaration classDeclaration = cu.getClassByName("TargetTypeTest").get();
        final ConstructorDeclaration constructorDeclaration = classDeclaration.getConstructors().get(0);
        final AnnotationExpr annotationExpr = constructorDeclaration.getAnnotationByName("TargetType").get();

        System.out.println(annotationExpr.resolve().getAnnotationMembers().stream()
                .filter(a -> "classes".equals(a.getName()))
                .findAny()
                .orElseThrow(() -> new AssertionError("No annotation value with name 'classes'"))
                .getDefaultValue());
    }

**Comment by freya022** [comment]
The reason it works for you is because the symbol solver is using the JavaParser implementation to get the default value, instead of the reflection-based one. 

To replicate the issue,  you need the reflection-based implementation (`ReflectionAnnotationMemberDeclaration`) to be used. Your test code made the symbol solver use [`JavaParserAnnotationMemberDeclaration`](https://github.com/javaparser/javaparser/blob/dfea1a6aa2de2efa11f07943b5f635317570cf45/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnnotationMemberDeclaration.java#L53-L56).

Putting the `TargetType` annotation declaration in the test project instead of the string of code, will make the symbol solver use reflection. (notice how in my test case, the annotation is in compiled code, but the usage of it is in a string)

The code that reflectively reads the annotation default value, [here](https://github.com/javaparser/javaparser/blob/dfea1a6aa2de2efa11f07943b5f635317570cf45/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionAnnotationMemberDeclaration.java#L43-L51) and [here](https://github.com/javaparser/javaparser/blob/dfea1a6aa2de2efa11f07943b5f635317570cf45/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionAnnotationMemberDeclaration.java#L61-L67) do not support `Class`, array types, (nested) annotations and enum types.

**Comment by jlerbsc** [comment]
Maybe you can contribute to the project and propose a PR containing unit tests?

**Comment by freya022** [comment]
> Maybe you can contribute to the project and propose a PR containing unit tests?

I'll make sure to include those with the enhancement PR
