### ISSUE TITLE
CommentsParser encoding problem

### ISSUE THREAD

**Issue by soulcarta** [javaparser/javaparser#41]
I was trying to parse java sources that was written by other encoding(Not UTF-8)
but unexpected error occured.

Because CommentsParser.parse() using fixed encoding value(UTF-8) like below.
and JavaParser is using this method.

<pre>
public CommentsCollection parse(final String source) throws IOException, UnsupportedEncodingException {
        InputStream in = new ByteArrayInputStream(source.getBytes());
        return parse(in,"UTF-8");
}
</pre>

**Comment by SmiddyPence** [comment]
This shouldn't be too hard correct providing the encoding can be the same as the optional parameter in the JavaParser.parse method.

Can you provide and example class, so I can verify?

**Comment by ftomassetti** [comment]
I changed the CommentsParser in this way:

``` java
    public CommentsCollection parse(final String source) throws IOException, UnsupportedEncodingException {
        InputStream in = new ByteArrayInputStream(source.getBytes(Charset.defaultCharset()));
        return parse(in, Charset.defaultCharset().name());
    }

    public CommentsCollection parse(final InputStream in, final String charsetName) throws IOException, UnsupportedEncodingException {
        boolean lastWasASlashR = false;
        BufferedReader br = new BufferedReader(new InputStreamReader(in, charsetName));
        ....
```

Hopefully it should fix this issue (as part of the merge request #50 ). It would be nice to have someone trying.

**Comment by ftomassetti** [comment]
Is this one solved? Any reason to keep this one open?

**Comment by sebastiankirsch** [comment]
Seems like you fixed it. Maybe you can add a test case, but the code looks good to me.

**Comment by ptitjes** [comment]
Who wants to volunteer for the test case ?? I don't :P

**Comment by ftomassetti** [comment]
I can do that and we should add more tests in general. Working on it.

**Comment by ptitjes** [comment]
Nice!

**Comment by ftomassetti** [comment]
The test is now submitted in #129. Should we close this issue?
