### ISSUE TITLE
UnsolvedSymbolException when resolving parameter types

### ISSUE THREAD

**Issue by Onizuka1229** [javaparser/javaparser#4100]
Hello,

I'm using JavaParser to parse some Java code and extract the types of method parameters. I've set up a CombinedTypeSolver with a ReflectionTypeSolver and a JavaParserTypeSolver, and I've configured JavaParser to use this type solver.

However, when I try to resolve the types of the parameters, I get an UnsolvedSymbolException. The exception message is "Unsolved symbol"

Here is the code I'm using:

```java: 
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        combinedTypeSolver.add(new JavaParserTypeSolver(folder));
        for (Path jarPath : antProperties.getLibs()) {
            combinedTypeSolver.add(new JarTypeSolver(jarPath));
        }
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
....
for (MethodDeclaration method : klass.getMethods()) {
   method.getParameters().forEach(p -> {
                    if(p.getType().isClassOrInterfaceType()){
                        ReolvedType  type = p.getType().resolve();    // raise an exception
                });
}
```

```
com.github.javaparser.resolution.UnsolvedSymbolException: Unsolved symbol : AutoProcMidData
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:347) ~[javaparser-core-3.25.4.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:607) ~[javaparser-symbol-solver-core-3.25.4.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:618) ~[javaparser-symbol-solver-core-3.25.4.jar:na]
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:284) ~[javaparser-symbol-solver-core-3.25.4.jar:na]
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:325) ~[javaparser-core-3.25.4.jar:na]
	at pactera.tf.ejb2boot.utils.JavaSourceUtils.lambda$generateInterface$11(JavaSourceUtils.java:161) ~[classes/:na]
```
I am quite certain that AutoProcMidData.java is within the scope of JavaParserTypeSolver.
I've checked that my source code is correct and can be compiled, and I've made sure that all the necessary libraries are in my classpath. I'm not sure what else could be causing this issue.

Any help would be greatly appreciated. Thank you!

**Comment by jlerbsc** [comment]
Where is the AutoProcMidData class defined (in source code or in library)? Can you extract a simple test case? What directory does the 'folder' variable point to?

**Comment by jlerbsc** [comment]
Do you have any other information to provide or should we consider this issue resolved?

**Comment by Onizuka1229** [comment]
> Do you have any other information to provide or should we consider this issue resolved?

Yes, I realized this issue arose when I added the method to a new class and then iterated through its parameters for parsing. It might be due to my incorrect usage, so it should be considered resolved. Thanks for your time.
