### ISSUE TITLE
Unsolved symbol in zip file

### ISSUE THREAD

**Issue by AKuser** [javaparser/javaparser#4101]
I have two java files, Bar.java and Const.java, and now they're in a zip file with the following structure:
```
/source/java/com/test/part1/part11/Const.java
/source/java/com/test/part2/Bar.java   
```
Bar.java
```
package com.test.part2;
import com.test.part1.part11.Const;
public class Bar {
    private String select1WithOrderBy = "select 1 from tab " + Const.ORDER_BY;
}
```
Const.java
```
package com.test.part1.part11;
public class Const {
    public static final String ORDER_BY = "order by id desc";
}
```
Now I tried to resolve the symbolic dependency of Const.ORDER_BY, but I got an error.The code is like this.
```
ParserConfiguration parserConfiguration = new ParserConfiguration();
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), new JavaParserTypeSolver("/source/java"));
parserConfiguration.setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
StaticJavaParser.setConfiguration(parserConfiguration);
JavaParserFacade javaParserFacade = JavaParserFacade.get(combinedTypeSolver);
CompilationUnit compUnit = StaticJavaParser.parse("/source/java/com/test/part2/Bar.java");
javaParserFacade 
...
SymbolReference reference = javaParserFacade.solve(orderBy);
```
the orderBy is a FieldAccessExpr object.
the error is
`Unsolved symbol in Const.ORDER_BY : Const`
the cause is 
`UnsolvedSymbolException{context='Const', name='Solving Const', cause='null'}`

It's ok for when parsing these two files directly from the windows disk, but when the two files are put into a zip file, this error occurs. Is there any difference in symbol parsing in the zip file? 
Any help would be greatly appreciated. Thank you!

**Comment by jlerbsc** [comment]
To my knowledge you must unzip the files or package them in a jar format.

**Comment by AKuser** [comment]
> To my knowledge you must unzip the files or package them in a jar format.

Thanks. Is there a plan to support this?

**Comment by jlerbsc** [comment]
No. You can propose a PR if you wish.

**Comment by AKuser** [comment]
> No. You can propose a PR if you wish.

ok.Thanks.
