### ISSUE TITLE
Move to jakarta.json

### ISSUE THREAD

**Issue by bowbahdoe** [javaparser/javaparser#4111]
For a few annoying reasons, https://mvnrepository.com/artifact/jakarta.json is the replacement for javax.json.

https://blog.ltgt.net/javax-jakarta-mess-and-gradle-solution/
https://blog.ltgt.net/javax-jakarta-mess-even-worse/

I honestly don't know the right move, but making this issue to track.

**Comment by hazendaz** [comment]
pull request opened #4225 to resolve this issue.

**Comment by hazendaz** [comment]
At this point, there should be no left over javax. usage - its still javax namespace though.
