### ISSUE TITLE
Misleading parse exception when using default access for member of class

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javaparser#413]
When using the default access specifier for a member of a class the javaparser generates `An interface cannot have default members` as error message. But itsn't it the other way round? My Eclipse tells me `Default methods are allowed only in interfaces`.

**Comment by DeepSnowNeeL** [comment]
Can you provide an exemple class it fails to parse ? 
Thanks

**Comment by mlangkabel** [comment]
Sure:

```
public class Test {
    default void foo() {    
    }
}
```

**Comment by matozoid** [comment]
I fixed that error message while working on something else. It should be okay on master.
