### ISSUE TITLE
Extract all the full qualified names of outer classes used in a java file.

### ISSUE THREAD

**Issue by chaicho** [javaparser/javaparser#4132]
I have set up a combined type resolver that  takes all the dependency classpath of a java file. Now i want to extract all the full qualified names of outer classes used in a java file. Instead of traversing all the nodes and handle them one by one, is there any other apis that can be used to do it?

**Comment by jlerbsc** [comment]
> Instead of traversing all the nodes and handle them one by one

You don't need to iterate through all the nodes just traversing the ClassOrInterfaceType nodes should be enough

**Comment by chaicho** [comment]
Thanks for your help.I tried to use ClassOrInterfaceType and it indeed works for most of the case. What's more, i also want to extract the annotation classes so i alse use AnnotationExpr.
Here comes another problem, when it comes to a java file like this. The "File" class cannot be parsed.
```
import java.io.File;
public class testClass {
  public void test(){
     String sep = File.seperator; 
  }
}
```
I tried to use the FieldAccessExpr to find the corresponding node. And it seems that javaparser treats the "File" as a nameExpression and i cannot get "java.io.File" from it. Is there any way to get this done?

**Comment by jlerbsc** [comment]
Maybe you could give us a simple test case that reproduces your problem.

**Comment by jlerbsc** [comment]
I don't see any problem.

    @Test
	void issue4132() {
		String code =
				"import java.io.File;\n"
				+ "public class testClass {\n"
				+ "  public void test(){\n"
				+ "     String sep = File.separator; \n"
				+ "  }\n"
				+ "}";
        // Setup symbol solver
        StaticJavaParser.getConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(
                        new CombinedTypeSolver(new ReflectionTypeSolver())));
       

        StaticJavaParser.parse(code).accept(new VoidVisitorAdapter<String>() {
            @Override
            public void visit(FieldAccessExpr fae, String arg) {
                try {
                	System.out.println(fae.getNameAsString());
                    System.out.println(fae.resolve().getType().describe());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }, null);
    }

**Comment by jlerbsc** [comment]
I'm closing this exit because there has been no interaction since the last discussion.
