### ISSUE TITLE
How to find all implementations of an interface?

### ISSUE THREAD

**Issue by mikenlanggio** [javaparser/javaparser#4142]
I have a `ClassOrInterfaceDeclaration` (A) that is an interface.
How can I find all classes that implement (A)?
Moreover, is there any way to find implementation of a method (in an interface).
Thank you

**Comment by jlerbsc** [comment]
Using a visitor you can do something like that

    String code = "class Foo implements java.util.List {}";
    JavaParserAdapter parser = JavaParserAdapter.of(createParserWithResolver(defaultTypeSolver()));
    CompilationUnit cu = parser.parse(code);

    String type = "java.util.List"; <-- The interface you are looking for
    VoidVisitor<String> visitor = new VoidVisitorAdapter<String>() {
        @Override
        public void visit(final ClassOrInterfaceDeclaration n, final String arg) {
            if (n.getImplementedTypes().stream().anyMatch(implementedType -> implementedType.getNameWithScope().equals(arg))) {
                System.out.println(n.getFullyQualifiedName().get() + " implements " + arg);
            }
        }
    };
    cu.accept(visitor, type);



You can find the implementation of a method with similar code.

**Comment by mikenlanggio** [comment]
Thanks, I'm using spring boot in a large project, is there a better way to find them?  (like the solve() function to find the definition)

**Comment by jlerbsc** [comment]
You can look at the use of ProjectRoot or SourceRoot classes.
Below is an example of the code

        String type = "java.util.List"; <-- The interface you are looking for

        VoidVisitor<String> visitor = new VoidVisitorAdapter<String>() {
            @Override
            public void visit(final ClassOrInterfaceDeclaration n, final String arg) {
                if (n.getImplementedTypes().stream().anyMatch(implementedType -> implementedType.getNameWithScope().equals(arg))) {
                    System.out.println(n.getFullyQualifiedName().get() + " implements " + arg);
                }
            }
        };

       ProjectRoot projectRoot = new ProjectRoot(projectRootPath); // with a default configuration

        SourceRoot sourceRoot = projectRoot.getSourceRoot(projectRootPath.resolve("src/main/java")).get(); // imagine a maven project
        for (ParseResult<CompilationUnit> parseResult : sourceRoot.tryToParse()) {
            parseResult.ifSuccessful(cu-> {
                cu.accept(visitor, type);
            });
        }

**Comment by jlerbsc** [comment]
I'm closing this issue because there are no more interactions. I imagine that the answers provided enough information to answer the first questions. If this is not the case you can reopen this issue.
