### ISSUE TITLE
How to find current ClassOrInterfaceDeclaration based on MethodCallExpr?

### ISSUE THREAD

**Issue by mikenlanggio** [javaparser/javaparser#4143]
I have a simple example like this:
```
class A{
    public void func(){
        ...
    }
}

class B extends A{

}

class C{
    B b;
    constructor(){
        b = new B();
    }
    public void run(){
        b.func();
    }
}
```

I use `JavaParser` to try to get `B` class instead of `A` class by `b.func()` like this:
```
MethodCallExpr methodCall = getMethodCall(); //Get b.func();
ResolvedMethodDeclaration rmd = expr.resolve();

MethodDeclaration mdec = (JavaParserMethodDeclaration) rmd.getWrappedNode(); //Its return something like A.func(), not B.func()
ClassOrInterfaceDeclaration clazz = getParentNodeUntilType(mdec, ClassOrInterfaceDeclaration.class); // Try to get parentNode until that isClassOrInterfaceDeclaration

//I expect to get `B`, but it returns `A`

```
I want to get `B` instead of `A`.
How can I reach it? Thank you

**Comment by jlerbsc** [comment]
The func() method is defined in class A and is not overridden by class B. When you resolve the method call, JP finds that the method is declared in A. This is a logical result and you get the same result in any IDE.

**Comment by jlerbsc** [comment]
I'm closing this issue because there are no more interactions. I imagine that the answers provided enough information to answer the first questions. If this is not the case you can reopen this issue.
