### ISSUE TITLE
Add orphan comments to BlockStmt, the comment positions are incorrect when printed using LexicalPreservingPrinter

### ISSUE THREAD

**Issue by luopstro** [javaparser/javaparser#4144]
I want to add orphan comments to a BlockStmt, but after adding them, when I print the code using LexicalPreservingPrinter, I find that the added orphan comments are not inside the BlockStmt, but before the BlockStmt.
For example, I want to add an orphan comment to the function in the following code: TODO: Do something

```java
class Test {
    void function() {
        String val = "Test";
        System.out.println(val);
    }
}
```

I want to get the  code like this:

```java
class Test {
    void function() {
        String val = "Test";
        System.out.println(val);
        // TODO: Do something.
    }
}
```
But the code printed with LexicalPreservingPrinter is:

```java
class Test {
    void function() //TODO: Do something.
{
        String val = "Test";
        System.out.println(val);
    }
}
```

**Comment by luops2017** [comment]
```java
class Test {
    void function() {
        String val = "Test";
        System.out.println(val);
        // TODO: Do something.
    }
}
```
But the code printed with LexicalPreservingPrinter is:

**Comment by luops2017** [comment]
```java
class Test {
    void function() //TODO: Do something.
{
        String val = "Test";
        System.out.println(val);
    }
}
```

**Comment by jlerbsc** [comment]
This is how JP handles comment attribution. You can read this post if you want to know precisely the rules for attribution of comments  https://tomassetti.me/java-comments-parsing/
But your example highlights a problem at the LPP level. The brace is in the wrong place.

If you want to add a comment after the last statement of the block I think you need to do this. 

    Statement stmt = new EmptyStmt();
    block.getStatements().addLast(stmt);
    stmt.addOrphanComment(new LineComment("TODO: Do something"));

returns 

    void function() {
        String val = "Test";
        System.out.println(val);
        // TODO: Do something
        ;
    }

**Comment by jlerbsc** [comment]
It seems to me that there is no other way to achieve what you want to do. Furthermore, JP's lexical preservation states that an empty statement must be accompanied by a semicolon. This semicolon does not cause compilation problems. Based on this observation, I do not consider that there is a problem in LPP.
I am closing this issue considering that it is resolved but you are free to reopen it if this answer does not suit you.
