### ISSUE TITLE
Java 21 (Preview) Language Support

### ISSUE THREAD

**Issue by binis2** [javaparser/javaparser#4158]
Hello, 

I just want to ask if there are any plans to implement parsing of the new Java 21 + Preview language features? If so where can I track progress of it and potentially help with it?

**Comment by jlerbsc** [comment]
Hi, JP does not fully support java 18. Logic would dictate that we proceed step by step. Of course your help in supporting the different versions of Java would be welcome.

**Comment by jlerbsc** [comment]
I am closing this issue because we have created different issues to gradually manage support for different versions of Java.
