### ISSUE TITLE
ObjectCreationExpr typeArgument parsing problem

### ISSUE THREAD

**Issue by Kimmmey** [javaparser/javaparser#4162]
Parsing an ObjectCreationExpr stores the type including the type arguments as type and nothing as typeArguments.

See following test:
``` Java
package javaparser;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class ObjectCreationExprParserTest {

    public static final String EXAMPLE = """
            class A {
                void dummy() {
                    ArrayList<String> list = new ArrayList<String>();
                }
            }
            """;

    @Test
    void parseObjectCreationTest() {
        TypeSolver solver = new ReflectionTypeSolver();
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setSymbolResolver(new JavaSymbolSolver(solver));
        JavaParser parser = new JavaParser(parserConfiguration);
        ParseResult<CompilationUnit> cu = parser.parse(EXAMPLE);
        cu.ifSuccessful(c -> c.accept(new VoidVisitorAdapter<Void>() {
            @Override
            public void visit(ObjectCreationExpr n, Void arg) {
                super.visit(n, null);
                System.err.println(n.getTypeAsString());
                assertEquals("ArrayList", n.getTypeAsString()); // is ArrayList<String>

                System.err.println(n.getTypeArguments());
                assertTrue(n.getTypeArguments().isPresent()); // is false
                assertEquals(1, n.getTypeArguments().get().size()); // is Optional.empty
                assertEquals("String", n.getTypeArguments().get().get(0));
            }
        }, null));
    }
}
```

JavaParser version: 3.25.5

**Comment by Erio-Harrison** [comment]
Hi, I wish solve this problem. Could you assign it to me?

**Comment by jlerbsc** [comment]
There is no issue here. The expression has a type which is an ArrayList<String>.

**Comment by Kimmmey** [comment]
Ok, then I'm probably just misinterpreting the following lines of the javadoc:

> In new HashMap.Entry<String, Long>(15) {public String getKey() {return null;}}; HashMap.Entry is the type, String and Long are type arguments, 15 is an argument, and everything in { } is the anonymous class body.

[https://javadoc.io/static/com.github.javaparser/javaparser-core/3.25.5/com/github/javaparser/ast/expr/ObjectCreationExpr.html](https://javadoc.io/static/com.github.javaparser/javaparser-core/3.25.5/com/github/javaparser/ast/expr/ObjectCreationExpr.html)

@jlerbsc Could you please confirm this.

Best regards
Kim

**Comment by jlerbsc** [comment]
That seems correct to me.
new HashMap.Entry<String, Long>() is an expression. This expression has a type and the type has type arguments.
I recognize that the wording may be misleading.

**Comment by Kimmmey** [comment]
This means that the typeArguments of ObjectCreationExpr are never filled? Or is there a case where the typeArguments of an ObjectCreationExpr are filled or not empty?

Because otherwise I would wonder why ObjectCreationExpr implements NodeWithTypeArguments in the first place?

**Comment by jlerbsc** [comment]
As mentioned in the JLS https://docs.oracle.com/javase/specs/jls/se15/html/jls-15.html
(15.9. Class Instance Creation Expressions)

> UnqualifiedClassInstanceCreationExpression:
new [TypeArguments] ClassOrInterfaceTypeToInstantiate ([ArgumentList]) [ClassBody]

Donc on peut écrire ceci:

> class Foo<T>{}
Foo\<String\> x = new \<String\> Foo();

Here the getTypeArguments() method returns String.

**Comment by Kimmmey** [comment]
Thank you for pointing it out. This solved my question and I know what the TypeArguments are for. I didn't know this alternative. 

I will close here.
