### ISSUE TITLE
Calling MethodDeclaration.getDeclarationAsString leads to MethodDelaration.getComment returning no comment

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#4163]
I am using JavaParser v.3.25.5 to get comments associated to methods.
However, the use of the method `getDeclarationAsString` remove all the comments.

Here is the code I am using:

        VoidVisitorAdapter<Object> visitor = new VoidVisitorAdapter<Object>() {
            @Override
            public void visit(MethodDeclaration n, Object arg) {
                System.out.println(n.getDeclarationAsString(true, true, true));
                System.out.println(n.getSignature());
                System.out.println(n.getComment());
            }
        };
        File f = new File("./android-30/javax/obex/ClientOperation.java");
        StaticJavaParser.getParserConfiguration().setAttributeComments(true);
        visitor.visit(StaticJavaParser.parse(f), null);

I have the following output:

    public void setGetFinalFlag(boolean flag)
    setGetFinalFlag(boolean)
    Optional[]

If I comment the call to `getDeclarationAsString`, then I get the comment of the method.

    setGetFinalFlag(boolean)
    Optional[/**
     * Allows to set flag which will force GET to be always sent as single packet request with
     * final flag set. This is to improve compatibility with some profiles, i.e. PBAP which
     * require requests to be sent this way.
     */
    ]

**Comment by jlerbsc** [comment]
The getDeclarationAsString method does what it's supposed to do.

"A simple representation of the element declaration. It should fit one string."

"The declaration returned has this schema:
[accessSpecifier] [static] [abstract] [final] [native]
[synchronized] returnType methodName ([paramType [paramName]])
[throws exceptionsList]"

This method does not print comments.

If you absolutely need comments in your representation you can concatenate them with the string representing the method signature.

**Comment by ghost** [comment]
I am sorry, my question was maybe unclear.

I am calling the `MethodDeclaration.getComment` method to get the comment.
But I do not know why, if I call the `Method.getDeclarationAsString` method, then the `MethodDeclaration.getComment` will return `Optional.empty` even if there is a comment associated to the method.

**Comment by jlerbsc** [comment]
OK. You are right.

getDeclarationAsString modifies the printer configuration to prevent certain comments from being printed. I don't know why this was done but it doesn't seem to be right. On the other hand, the syntax below is a workaround.

    n.getComment().get().asString()

Logically you should be able to configure the printer like this because PRINT_COMMENTS is not a default option in pretty printer configuration.

    // add configuration option to the default 
    PrinterConfiguration config = new DefaultPrinterConfiguration()
                .addOption(new DefaultConfigurationOption(ConfigOption.PRINT_COMMENTS));
    // create a printer with the new configuration
    Printer printer = new DefaultPrettyPrinter(config);
    CompilationUnit cu = StaticJavaParser.parse(code);
    // set the printer on the compilation unit for future uses
    cu.printer(printer);

in your case it is not necessary to configure the parser.

    StaticJavaParser.getParserConfiguration().setAttributeComments(true);
