### ISSUE TITLE
Use of patterns with instanceof is not supported

### ISSUE THREAD

**Issue by perNyfelt** [javaparser/javaparser#4169]
When running Gradle 8.4 -> GroovyDoc 4.0.15 which uses javaparser-core 3.25.5 i get the following error:

[ant:groovydoc] Attempting to ignore error parsing Java source file: se/alipsa/groovy/matrix/util/DataType.java
[ant:groovydoc] Consider reporting the error to the Groovy project: https://issues.apache.org/jira/browse/GROOVY
[ant:groovydoc] ... or directly to the JavaParser project: https://github.com/javaparser/javaparser/issues
[ant:groovydoc] Error: (line 55,col 9) Use of patterns with instanceof is not supported.

The offending code is:

  public static String sqlType(Object value, int... varcharSize) {
    if (value instanceof BigDecimal bd) {
      return "DECIMAL(" + bd.precision() + "," + bd.scale() + ")";
    }
    return value == null ? null : sqlType(value.getClass(), varcharSize);
  }

**Comment by jlerbsc** [comment]
Are you sure you have configured the java version in the parser configuration?

**Comment by jlerbsc** [comment]
It seems that using the intanceof pattern is supported (in JP) starting with Java 16. https://openjdk.org/jeps/394

- delivered in JDK 14 as a preview feature (https://openjdk.java.net/jeps/12)  https://openjdk.org/jeps/305
- delivered in JDK 15 https://openjdk.java.net/projects/jdk/15) for a second round of preview feature https://openjdk.org/jeps/375

**Comment by jlerbsc** [comment]
@Test
    void issue4169() {

		String code =
	            "class A {\n"
	            + "public static String sqlType(Object value, int... varcharSize) {\n"
	            + "  if (value instanceof BigDecimal bd) {\n"
	            + "    return \"DECIMAL(\" + bd.precision() + \",\" + bd.scale() + \")\";\n"
	            + "  }\n"
	            + "  return value == null ? null : sqlType(value.getClass(), varcharSize);\n"
	            + "}"
	            + "}";
		ParserConfiguration config = new ParserConfiguration();
		config.setLanguageLevel(LanguageLevel.JAVA_16);
        JavaParser parser = new JavaParser(config);
        CompilationUnit cu = JavaParserAdapter.of(parser).parse(code);
        System.out.println(cu.toString());
    }

**Comment by perNyfelt** [comment]
OK thank you. This must be some issue in the groovydoc plugin then. I will open a case with the groovydoc project instead. Thank for the prompt reply!
