### ISSUE TITLE
UnsolvedSymbolException{context='null', name='Str', cause='null'} with MethodCallExpr

### ISSUE THREAD

**Issue by Neo0214** [javaparser/javaparser#4173]
Here is my example
Str.java:public class Str{ public out(){System.out.print("a");}}
Main.java: main(){ Str str=new Str; str.out()}
When I use following code:
`String calledClass=methodCallExpr.getScope().get().calculateResolvedType().asReferenceType().getQualifiedName();`
I get exception like this :
UnsolvedSymbolException{context='null', name='Str', cause='null'} 
Also, I've set symbol solver before getting CompilationUnit:
`        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(project_root_path));

        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();
        combinedSolver.add(reflectionTypeSolver);
        combinedSolver.add(javaParserTypeSolver);
        ParserConfiguration parserConfiguration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(combinedSolver));
        StaticJavaParser.setConfiguration(parserConfiguration);

        for (String file : files) {
            CompilationUnit cu=parseJavaFile(new File(file));
            cus.add(cu);
        }`
I don't know how to solve it, if anyone could help, thank you very much.

**Comment by jlerbsc** [comment]
This is a TypeSolver configuration issue. project_root_path must point to the root source folder.

**Comment by jlerbsc** [comment]
Did this answer help you resolve your issue? If so, please close this issue.

**Comment by Neo0214** [comment]
Thank you. It helped me solve the issue.
