### ISSUE TITLE
Node not removed from AssignExpr value

### ISSUE THREAD

**Issue by mdproctor** [javaparser/javaparser#4191]
I have a Node set as a value in AssignExpr, I add that Node to an MethodCallExpr argument and while it's removed from the AssignExpr children list, it is not removed from the value field.

**Comment by jlerbsc** [comment]
Can you provide a simple unit test that reproduces the issue?

**Comment by jlerbsc** [comment]
If you don't submit a simple test case to us that reproduces this issue, I'm going to close this issue because we can't work on it effectively.

**Comment by jlerbsc** [comment]
Since we are unable to obtain a simple test case I am closing the issue but you can reopen it if you have additional information to bring to our attention.
