### ISSUE TITLE
How to recursively read all methods invoked from a method call?

### ISSUE THREAD

**Issue by mikenlanggio** [javaparser/javaparser#4197]
I'm encountering a rather peculiar issue. I'm receiving the error message `Symbol resolution not configured: to configure, consider setting a SymbolResolver in the ParserConfiguration` when attempting to call a method from a library that has a parameter variable declared using the "var" keyword.

I'm trying to scan a Spring Boot application, and below is a reproduction of my issue:

**ControllerA.java:**

```java
public class ControllerA {
    // Autowired...

    public void methodA() {
        StringUtils.isEmpty("ok"); // <--- This works;
        String myVariable = "ok";
        StringUtils.isEmpty(myVariable); // <--- This works;
        var myVariable1 = "ok";
        StringUtils.isEmpty(myVariable1); // <--- This results in an error: Symbol resolution not configured: to configure, consider setting a SymbolResolver in the ParserConfiguration;
    }
}
```

When I attempt to recursively read all the methods from `methodA`, it looks something like this:

```java
public class MiniScan {
    public void traversalMethodCallingTree(MethodCallExpr methodCall) {
        MethodUsage methodUsage = JavaParserFacade.get(combinedSolver).solveMethodAsUsage(methodCall); // Error occurs here at StringUtils.isEmpty(myVariable1);
        MethodDeclaration methodDeclaration = getMethodDeclarationFromMethodUsage(methodUsage);
        var methodCalls = methodDeclaration.findAll(MethodCallExpr.class);

        for (var item : methodCalls) {
            var callingTree = traversalMethodCallingTree(item);
        }
    }

    public void run() {
        var methodA = getMethodAFromControllerA();
        traversalMethodCallingTree(methodA);
    }
}
```

These code snippets illustrate the issue I'm encountering.

**Comment by jlerbsc** [comment]
How did you setup the type solver? This exception is thrown when no type solver is configured in the parser.

**Comment by mikenlanggio** [comment]
Thank you for your reply. After testing, I feel like `JavaParserFacade.get(typeSolver)` doesn't really work as expected.

**A.java:**

```java
class A {
    public void foo(Object param) {
        var a = 1;
        System.out.println(a);
    }
}
```

**ResolveMethodCalls:**

```java
TypeSolver typeSolver = new ReflectionTypeSolver(false);
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
boolean isEnableSymbolResolverFromStaticJavaParser = false;
if (isEnableSymbolResolverFromStaticJavaParser) {
    StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
}

CompilationUnit cu = StaticJavaParser.parse(new File(FILE_PATH));
var methodDeclare = cu.findAll(MethodDeclaration.class).get(0);

methodDeclare.findAll(MethodCallExpr.class).forEach(mce -> {
    var testResolve = JavaParserFacade.get(typeSolver).solveMethodAsUsage(mce);
});
```

When `isEnableSymbolResolverFromStaticJavaParser` is set to `false`, it doesn't work at all (throws an exception). If I set it to `true`, it works.

I thought if I use `JavaParserFacade.get(typeSolver)` it doesn't depend on whatever I set to `StaticJavaParser`?

**Comment by jlerbsc** [comment]
You no longer have to use the JavaParserFacade class directly because all the mechanics for obtaining a declaration from an AST node are integrated. There may be documentation here and there that mentions this way of doing things but it is no longer useful except perhaps in marginal cases.
In your case just do it.

    TypeSolver typeSolver = new ReflectionTypeSolver(false);
    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
    StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);

    CompilationUnit cu = StaticJavaParser.parse(new File(FILE_PATH));
    var methodDeclare = cu.findAll(MethodDeclaration.class).get(0);

    methodDeclare.findAll(MethodCallExpr.class).forEach(mce -> {
        var testResolve = mce.resolve();
    });

**Comment by mikenlanggio** [comment]
I know it, but I still have to use `JavaParserFacade` because `.resolve()` is not always works.
For example:
`A.foo` call `B.baz` call `C.bar`.
I want to find a tree calling like A.foo -> B.baz -> C.bar
I find `B.baz` by using `resolve` (in A.foo), after that, I want to go to `C.bar` but it doesn't work anymore because `B.bar` isn't auto apply `setSymbolResolver`.

**Comment by jlerbsc** [comment]
Do you mean that A.foo , B.baz , C.bar are different classes? You have probably to setup a JavaParserTypeSolver which should point to the directory that contains your source code.

**Comment by mikenlanggio** [comment]
Thank you for your reply.

`mce.resolve()` returns the type `ReflectionMethodDeclaration`. How can I continue to find `MethodCallExpr` inside it? For example:

**A.java:**
```java
class A {
    public void foo(Object param) {
        new B().bar();
    }
}
```

**B.java:**
```java
class B {
    public void bar() {
        new C().baz();
    }
}
```

**main.java:**
```java
public static void main(String[] args) throws Exception {
    TypeSolver typeSolver = new ReflectionTypeSolver(false);
    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
    StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);

    CompilationUnit cu = StaticJavaParser.parse(new File("A.java"));
    var methodDeclare = cu.findAll(MethodDeclaration.class).get(0);

    methodDeclare.findAll(MethodCallExpr.class).forEach(mce -> {
        var resolveB = (ReflectionMethodDeclaration) mce.resolve(); // B.baz

        // I want to continue finding C.baz against `resolveB`
    });
}
```

**Comment by jlerbsc** [comment]
JP doesn't have this type of feature. What you can do is build the AST for each of the classes in your application, iterate through the AST and build the dependency/call graph.

**Comment by mikenlanggio** [comment]
I can achieve my goal by using `JavaParserFacade.get(typeSolver)`, but it doesn't work correctly.

**Comment by jlerbsc** [comment]
JP simply doesn't provide this type of functionality. There is no proven issue in your examples but simply incorrect use of the API.

**Comment by jlerbsc** [comment]
I am closing this issue because there is no error demonstrated and the requested functionality is not implemented in JP.
