### ISSUE TITLE
Bug while parsing comments

### ISSUE THREAD

**Issue by soulcarta** [javaparser/javaparser#42]
Here is example code

``` java
public class ClassWithBlockComments {

    /* comment to a method */
    void foo(){};

    /*// comment put randomly in class: <==This is a Problem

    another orphan.
    It spans over more lines */

}
```

Of course it's not normal coding style.
But Unfortunately this kind of source exist.

Here is where the problem occurred.(CommentParser:line 82)
In that case, the value of "currentContent" is empty. 
So "currentContent.toString().length()-1" make StringIndexOutOfBoundException

``` java
case IN_BLOCK_COMMENT:
    if (prevChar=='*' && c=='/'){
        // delete last character
        String content = currentContent.deleteCharAt(currentContent.toString().length()-1).toString();
        ...
```

**Comment by ftomassetti** [comment]
This one seems fixed, we should close this issue.

**Comment by ftomassetti** [comment]
Fixed by 16b88ae

**Comment by soulcarta** [comment]
@ftomassetti I checked that the modified. Work correctly.
Thank you.

**Comment by soulcarta** [comment]
Yes. I checked that the modified. Work correctly.
Thank you.
