### ISSUE TITLE
How to obtain all dependencies of a Java file

### ISSUE THREAD

**Issue by heyuxiang1996** [javaparser/javaparser#4201]
I have a task to find all class dependencies starting with the com.xxx.sdk package name in a Java file. I have the path to this Java file and the path to the aar file of com.xxx.sdk. How can I output all dependent classes starting with the com.xxx.sdk package name?
```
@Test
    public void tempTest() throws IOException {
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new AarTypeSolver(new File("E:\\Resources\\Gradle\\repository\\caches\\modules-2\\files-2.1\\com.xxx.api\\sdk\\33.1.8.019\\489e00aebacf85c023c413efbd45f1784ab31af6\\sdk-33.1.8.019.aar"))); // dependent third-party aar file path, with package name starting with com.xxxx.sdk
        combinedTypeSolver.add(new JavaParserTypeSolver(new File("E:\\Project\\xxxProject")));  //project root path
        combinedTypeSolver.add(new ReflectionTypeSolver());
        JavaParser javaParser = new JavaParser(new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver)));
        CompilationUnit compilationUnit = javaParser.parse(new File("xxxx.java")).getResult().get();  //java file path
        //How to obtain all dependencies on com.xxxx.sdk for this compileUnit and output the dependency class name?
    }
```

**Comment by heyuxiang1996** [comment]
If you only use ImportDeclaration to obtain dependencies, there should be some omissions. Is there a more accurate way to obtain all dependencies?

**Comment by jlerbsc** [comment]
Javaparser does not directly provide a way to obtain these dependencies. If import declarations are not enough you can also try to resolve method calls and object instantiations.

**Comment by heyuxiang1996** [comment]
> Javaparser does not directly provide a way to obtain these dependencies. If import declarations are not enough you can also try to resolve method calls and object instantiations.

Thank you. I will try to solve this problem by using JavaParser to parse expressions. If JavaParse can provide an official interface for resolving dependencies between classes, it will be beneficial for architecture protection checks
