### ISSUE TITLE
MethodDeclaration.replace() method wipes out parent node of the replacement.

### ISSUE THREAD

**Issue by fabgo** [javaparser/javaparser#4210]
The MethodDeclaration.replace() method wipes out the parent node of the replacement.

To get the below code to work, I explicitly had to stash and set the parent node of the replaced method declaration.

My expectation would be that the replace() method would transfer the parent node to the replacement.

In other words, parent->child is set, but child->parent is not, which leads to an inconsistent tree.

```
        ParseResult<MethodDeclaration> parseResult = javaParser.parseMethodDeclaration(sourceCode);

        if (parseResult.isSuccessful()) {
            MethodDeclaration newMethodDeclaration = parseResult.getResult().get();
            LexicalPreservingPrinter.setup(newMethodDeclaration);

            // Get the parent node of the original method declaration
            Node parentNode = methodDeclaration.getParentNode().get();

            methodDeclaration.replace(newMethodDeclaration);

            // BUG: After replacing the method declaration, the parent node is wiped out, and needs to be explicitly set back
            methodDeclaration.setParentNode(parentNode);

            List<MethodCallExpr> methodCallExprs = methodDeclaration.findAll(MethodCallExpr.class);
            for (MethodCallExpr methodCallExpr : methodCallExprs) {
                try {
                    methodCallExpr.resolve();
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        } 
```

Note that even if I explicitly set the parent in the new method declaration before calling replace(), it is explicitly wiped out. In other words, the following code does not work:

```
Node parentNode = methodDeclaration.getParentNode().get();

newMethodDeclaration.setParentNode(parentNode);

methodDeclaration.replace(newMethodDeclaration);

// methodDeclaration.getParentNode() returns an empty optional
```

**Comment by jlerbsc** [comment]
I cannot reproduce your problem. Can you provide the code corresponding to the initial source code (sourceCode) and the new method declaration (newMethodDeclaration).

**Comment by jlerbsc** [comment]
Here is the test case I used to try to reproduce your issue.

    @Test
	void issue4210() {
		String code =
				"public class Foo {\n"
				+ "  public void m() {}\n"
				+ "}";

		MethodDeclaration newMethodDeclaration = StaticJavaParser.parseMethodDeclaration("void y() {}");
		
        StaticJavaParser.parse(code).accept(new VoidVisitorAdapter<String>() {
            @Override
            public void visit(MethodDeclaration methodDeclaration, String arg) {
                try {
                	methodDeclaration.replace(newMethodDeclaration);
                	System.out.println(newMethodDeclaration.findCompilationUnit().get().toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }, null);
    }

This code displays

    public class Foo {

        void y() {
        }
    }

**Comment by fabgo** [comment]
I think my understanding was incorrect. replace() does not actually replace the method declaration. It replaces the child of the parent. The method declaration itself is unchanged, except the parent is set to null.

**Comment by jlerbsc** [comment]
"The method declaration itself is unchanged, except the parent is set to null." that's correct. You are working on the AST (a tree). The node is dereferenced.
