### ISSUE TITLE
Changing A Comment Into An Annotation?

### ISSUE THREAD

**Issue by avansaun** [javaparser/javaparser#423]
The project I'm currently working on requires me to find comments in a file which contain annotation tags and change them so that they are no longer commented. For example, changing something like `//AnAnnotation` to `@AnAnnotation`. I am trying to use a method that extends ModifierVisitorAdapter, but am having trouble finding a way to switch from Comment to Annotation. Is there any way to accomplish this?

**Comment by nerzid** [comment]
I think you miss a point about how to comment out annotations. If a annotation is commented it would look like this `//@Annotation...` so basically it is just a comment. The solution to your answer is you can get that comment's content that contains annotation, than use that content to create an annotation just like the content. Also don't forget to delete comment with annotation as well.

**Comment by avansaun** [comment]
Thanks for the fast reply! To be more specific, I'm trying to take a commented out Jira test case number and change it from `//ABC-1234` into an `@Jira ABC-1234` tag. So If I was to use the MethodChangerVisitor class from the "Changing methods from a class with a visitor" example in the manual page, how could I take a comment that is passed into the visitor method and then pass it back to the CompilationUnit as an Annotation? 

The way I'm approaching this is like so:

```
public class TagUpdater {
       public static void main(String[] args) {
                 //get FileInputStream and parse file with CompilationUnit cu
                cu.accept(new CommentToAnnotation(), null);
                System.out.println(cu.toString());
        }

       public static class CommentToAnnotation extends MethodVisitorAdapter {
                @Override
                public Node visit(Comment n, Object arg) {
                        //grab comment content and create annotation
                        return super.visit(n, arg)
                }
        } 
}

```

So where I am stuck is how to pass an annotation back to the cu instead of a comment. Or is there a better way to do all of this? Sorry if I'm not explaining this clearly.

**Comment by nerzid** [comment]
## Test.java

```

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseException;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.comments.Comment;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Arrays;

public class Test {

    public static void main(String[] args) {

        // Project's File
        File f = new File("/home/nerzid/Desktop/test.java");

        try {
            CompilationUnit cu = JavaParser.parse(f, StandardCharsets.UTF_8);

            new MethodChangerVisitor().visit(cu, null);

            Files.write(f.toPath(), Arrays.asList(cu.toString()), StandardCharsets.UTF_8);
        } catch (ParseException | IOException ex) {

        }

    }

    private static class MethodChangerVisitor extends VoidVisitorAdapter {

        @Override
        public void visit(MethodDeclaration n, Object arg) {

            Comment comment = n.getComment();

            if (comment != null) {
                n.addAnnotation(comment.getContent());
                n.setComment(null);
            }
        }
    }
}

```

## Test.txt Before

```
import java.util.Scanner;

public class test
{
    private int count;
    public static String warning = "WARNING";

    public static void main(String[] args)
    {

        Scanner input = new Scanner(System.in);
        String kelime = input.nextLine();
        System.out.println("Kelime: " + kelime);

    }

    //example
    public void hello()
    {
        System.out.println("Selamssöçİşü");    
    }
}
```

## Test.txt After

```
import java.util.Scanner;

public class test {

    private int count;

    public static String warning = "WARNING";

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        String kelime = input.nextLine();
        System.out.println("Kelime: " + kelime);
    }

    @example()
    public void hello() {
        System.out.println("Selamssöçİşü");
    }
}
```

Note that, this code is not clean and very like to be buggy, but I think you can handle that :bowtie: 
I've used javaparser-core-3.0.0.-SNAPSHOT.jar for this test.

**Comment by DeepSnowNeeL** [comment]
You might want to use addMarkerAnnotation to avoid the () after the annotation name

**Comment by avansaun** [comment]
Thank you both so much, I think this is right along the lines of what I'm looking for. Does the  javaparser-core-3.0.0.-SNAPSHOT include the addAnnotation() (or addMarkerAnnotation()) method? I'm currently using javaparser-core-2.5.1 and it doesn't recognize that method. If so, where can I download the 3.0.0-SNAPSHOT jar file? I can't seem to locate it one the site here.

**Comment by nerzid** [comment]
Yeup, it does. I think you can't download it directly. You need to build it via maven.

**Comment by avansaun** [comment]
Hmm okay, I tried that but couldn't find 3.0.0 in the Maven repository. Any idea why that wouldn't show up?

https://mvnrepository.com/artifact/com.github.javaparser/javaparser-core

**Comment by nerzid** [comment]
I think you haven't used maven before :smile:  
Firstly, download and install apache maven from [HERE](https://maven.apache.org/download.cgi)
Make sure that you have a environment variable called JAVA_HOME with value of your jdk's path, like this 
![Java_Home](https://cloud.githubusercontent.com/assets/11797282/17867241/55a7acbc-68b2-11e6-9d0f-77287a671805.png)

than open up CMD, and write this codes respectively

`git clone https://github.com/javaparser/javaparser`
`cd javaparser`
`mvn clean install`

You'll see **javaparser-core-3.0.0.-SNAPSHOT.jar** in the directory **javaparser/javaparser-core/target**

**Comment by avansaun** [comment]
Thank you! Yeah I haven't used Maven much before. So I now have the 3.0.0 version in my Maven dependency, and everything looks normal except the n.addAnnotation(<String>) method is still not recognized. Do I need to refresh something to get everything to update? Thanks again for all the help.

**Comment by avansaun** [comment]
I ended up just using Java's Scanner to do the parsing of the comments for my project, so I'll close this issue. I'm sure that nerzid's solution would work correctly though, and assuming that it was simply a problem with my local setup. Thank you both for the help, and hopefully this will help others if they have a similar problem.
