### ISSUE TITLE
Reference of Field

### ISSUE THREAD

**Issue by Laughh** [javaparser/javaparser#4233]
Hi! I'm using JavaParser to do something, and I'm confused that is there any way to get references of each `VariableDeclarator` in `FieldDeclaration`?

**Comment by jlerbsc** [comment]
Hi It seems to me that the getVariables method does exactly what you are looking for.

**Comment by Laughh** [comment]
> Hi It seems to me that the getVariables method does exactly what you are looking for.

I'm sorry that my description may be incorrect.

```
package pkg;

import java.io.IOException;
import java.util.*;
import java.lang.*;

public class A{

    private List<Integer> list = new ArrayList<>(), list2;
    public static void main(String... args) {
        int x = 0;
        A a = new A();
        a.test();
    }

    public List<Integer> getList(){
        return list;
    }

    public void addVal(int x){
        list.add(x);
    }
}
```
I hope to find each usage of `list` and `list2`, for `list`, the result should contain `return list` and `list.add(x)`.

**Comment by jlerbsc** [comment]
This feature is not implemented in JP. You can search for a declaration from an expression but the reverse does not exist.

**Comment by Laughh** [comment]
> This feature is not implemented in JP. You can search for a declaration from an expression but the reverse does not exist.

Thank you!
