### ISSUE TITLE
Reformat all source code according to the formatting rules.

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#424]
MAKE SURE nobody is working on anything, or merging will be hell!

**Comment by rosrossito** [comment]
Matozoid, hello,
may I join this project?
Can you assign this task to me? I would like to try to make it.

**Comment by matozoid** [comment]
Sure, this weekend I'll pull all the pull requests, so then would be a good time to do this.

**Comment by matozoid** [comment]
@DeepSnowNeeL can you finalize #435 before Sunday?

**Comment by DeepSnowNeeL** [comment]
Well you can include it like this, I'll continue to propose PR every time I use javaparser and find a way to do better with code building :)
Could you check that the eclipse formatting is updated and does the right thing ? I think I always break formatting... :(

Thanks !

**Comment by matozoid** [comment]
@DeepSnowNeeL - good point. I personally only format the lines I touch, which is a pain.
@rosrossito - could you first investigate the current formatters and see if you can get them to format stuff identically?

**Comment by rosrossito** [comment]
Ok. I will try.

2016-09-01 13:49 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by rosrossito** [comment]
Danny,

could you clarify the task more precisely?

I mean in what modules current formatters are located?

Do you have already this formatting rules?

2016-09-01 15:24 GMT+03:00 Ruslan Omelchenko <
ruslan.omelchenko.irtcits@gmail.com>:

**Comment by matozoid** [comment]
Check https://github.com/javaparser/javaparser/wiki/Coding-Guidelines

**Comment by matozoid** [comment]
I think Intellij should have the option to "import *" turned off.

**Comment by rosrossito** [comment]
I followed the instruction given in guiedlines, but I am not shure that I
made it properly.
Also cloned project was built with error.
May be you can give me some hint concerning that.
Nevertheless I pulled request.

2016-09-11 1:10 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
There was a comment that maybe the files in dev-files shouldn't be in git, but in the wiki, next to the instructions for formatter settings. What do you think?

**Comment by DeepSnowNeeL** [comment]
I think this is handy and does not impact the final jar so I would keep it
like this

**Comment by matozoid** [comment]
In that case we could also add scripts to put those files in the correct place.

**Comment by matozoid** [comment]
So the tasks are:
- inspect the files in dev-files to see if we can get the formatters for intellij and eclipse to match
- maybe create a little script that copies those files to the IDE's config directory
- review https://github.com/javaparser/javaparser/wiki/Coding-Guidelines
- format all source code

**Comment by rosrossito** [comment]
I started to inspect if we can get the same fomatters.

I can say that:

1) "indent with 4 spaces" is the same,

2) "Copyright" for new files is also Ok. I added some description for Idea
on wiki. You can look on
https://github.com/rosrossito/javaparser/wiki/Coding-Guidelines

3) "wrap lines at 120 characters":

There was a problem in Idea. To avoid it is necessary to put "yes" on "Wrap
when typing reaches right margin"

4) "wrapped arguments are aligned to opening parenthesis":

Eclipse is ok. There is a problem in Idea. Unfortunately I don't know how
to fix it.

It is possible in settings of Idea to suppress introducing braces
automatically only for some statements such as for…, if… etc, but not for
all methods.

2016-10-03 20:08 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
2) That's cool, can you apply it to https://github.com/javaparser/javaparser/wiki/Coding-Guidelines too?

4) what is the problem exactly?

The main thing we want to avoid is that we get ping-pong formatting: someone with Idea reformats something from an Eclipse user which causes unnecessary changes and merge problems, and then another Eclipse user comes by and reformats the same thing again, and again we have unnecessary changes. I assume introduction of braces does not cause ping-ponging?

**Comment by rosrossito** [comment]
1. Shure. Done.
2. The  problem is that Idea do not delete spaces after left parenthesis
   before methods’ arguments.
   
   I just followed instructions in guidelines. But may be it is not so
   critical and we can skip this requirement.
3. And the last: "type and method annotations go on a separate line"

I didn't understand, it means annotations @ or body of method (line after
method name).

2016-10-04 17:45 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
Thanks!

4: so we're talking about this situation?

``` java
abcabcabc(
            int x,    <--- this?
            int y);
```

5: means we have

``` java
@Abc
public void aaa() {
}
```

instead of

``` java
@Abc public void aaa() {
}
```

I just stumbled upon this stuff: http://editorconfig.org/ - that seems much easier to maintain than those configuration files we have now. What do you think about it?

**Comment by ftomassetti** [comment]
Does it support IntelliJ IDEA?

**Comment by matozoid** [comment]
The other way around: IDEA support editorconfig.

Eclipse needs a plugin.

**Comment by rosrossito** [comment]
1. I talk about this situation:
   abcabcab (  int x,  <-- spaces after  left paranthesis
   int y)

Eclipse fix this:
abcabcab (int x,
int y)

2016-10-07 20:49 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by rosrossito** [comment]
1. Strange, but neither Idea nor Eclipse can not fix this problem, despite
   options are set correctly:
   a) for Eclipse Java->CodeStyle->Formatter->Edit->Annotations->Insert new
   line after annotations on methods and Insert new line after annotations on
   type (yes)
   b) for Idea File->Settings->Java->Wrapping and Braces->Method
   annotations->Wrap always

2016-10-09 12:36 GMT+03:00 Ruslan Omelchenko <
ruslan.omelchenko.irtcits@gmail.com>:

**Comment by matozoid** [comment]
4) don't worry about it, it's not like eclipse formats it this way, the idea formats it another way, and they keep correcting each other.

5) don't forget it's also about types (classes & interfaces.) How do you mean "can't fix?" They won't do the formatting right?

**Comment by rosrossito** [comment]
1. Yes.
   If you have
   @abc public void aaa ()
   {
   }

They do not do
@abc
public void aaa()
{
}

2016-10-09 17:58 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
I just formatted something like that in Intellij Idea, and it does move the annotation to a separate line when formatting.

**Comment by rosrossito** [comment]
I don't know why my Idea do not do that.
May be I do something wrong...
So, nevertheless it works.

2016-10-11 0:23 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
Have you checked that editorconfig site? Does that work better than what we have now?

**Comment by rosrossito** [comment]
Yes, I read it.
I suppose that EditorConfig does not support "annotations on separate line"
and "arguments are aligned to opening parenthesis".
At least I did not see anything about annotations in properties and
"spaces_around_brackets" is not intended to be implemented by EditorConfig (
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties).

2016-10-13 17:44 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
So it's not so great? Let's forget about that then.

**Comment by rosrossito** [comment]
So, what is the next step?

2016-10-16 22:49 GMT+03:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
Wait for a moment when nobody is working on anything.

**Comment by matozoid** [comment]
I suggest doing this right after RC1 releases. Can you join https://gitter.im/javaparser/javaparser ?
