### ISSUE TITLE
isAssignableBy for gradle or maven class

### ISSUE THREAD

**Issue by Laughh** [javaparser/javaparser#4248]
Hi! I wanna to figure out that if I use some classes that are imported from gradle or maven, the function `isAssignableBy` will throw an `UnsolvedSymbolException`？

```
class B extends com.github.javaparser.ast.Node {

}

class C extends B{

    public void funC(){

    }
}
```

In above code, the JavaParser can not judge that variable declared with type B can be assigned by C object, right?

**Comment by jlerbsc** [comment]
> the function `isAssignableBy` will throw an `UnsolvedSymbolException`？

To resolve external dependencies (e.g. libraries) you must configure symbol resolution. The same goes for dependencies with JDK classes.

**Comment by Laughh** [comment]
> > the function `isAssignableBy` will throw an `UnsolvedSymbolException`？
> 
> To resolve external dependencies (e.g. libraries) you must configure symbol resolution. The same goes for dependencies with JDK classes.

If I don't add path for external dependencies, the function `isAssignableBy ` will throw an `UnsolvedSymbolException` in class `ReferenceTypeImpl`.

**Comment by jlerbsc** [comment]
That's right, that's how javaparser works. You ask him to compare different references but he doesn't know them all so he tells you he can't solve the problem.

**Comment by jlerbsc** [comment]
I'm closing this issue because we've answered it. You are free to reopen it if you would like more information.
