### ISSUE TITLE
javaparser-core now depends on Guava

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#4249]
With the recent release including commit c6a0e51, javaparser-core now has a dependency on guava and all of its dependencies.

We are using javaparser-core just for its parsing capabilities and have no use for the symbol solver and related functionality. It would be ideal if javaparser-core could remain a single jar with no dependencies (or minimal dependencies).

**Comment by jlerbsc** [comment]
That's right, there is a dependency with the guava cache which has been integrated into the latest version of Javaparser. This is for the moment a preview feature which is not definitive but which would certainly optimize the performance linked to the resolution of symbols. Unfortunately even if you don't use symbol resolution, this dependency will be necessary in future versions if this functionality is maintained.

**Comment by ghost** [comment]
Yes, that's what I'm getting at. One of our main motivations for selecting javaparser-core was that it had no dependencies for our use case (naive parsing of single Java files only). 

If javaparser-core now has similar dependencies as the symbol resolver, it will no longer be usable for us.

**Comment by jlerbsc** [comment]
The intention is not to integrate the dependencies of the symbol solver into Javaparser core but simply an API. This transition has been in progress for several months and you haven't noticed it. What you have highlighted is just the integration of an additional library. It is not even clear that this implementation will be sustainable if it does not provide the expected performance gains.
If this development does not suit you, I am sorry and you have every right to look at other projects which seem more successful to you.

**Comment by jlerbsc** [comment]
I think I found a compromise to avoid introducing this dependency into javaparser-core while still retaining the cache functionality. The modification will certainly be implemented in the next version which should be published at the end of the year.
