### ISSUE TITLE
Get node by offset in file

### ISSUE THREAD

**Issue by Laughh** [javaparser/javaparser#4254]
Hi! Is there any API to get the node in AST by given offset in the original file? BTW, I want to know that if each node generated by JDT Can be converted to a corresponding node in JavaParser ?

**Comment by jlerbsc** [comment]
There is no this type of functionality at the moment but you have all the APIs to do it.

**Comment by Laughh** [comment]
Thank you! And I have another question that if a Node do not have an empty `Range`, is it unique?

**Comment by jlerbsc** [comment]
> if a Node do not have an empty `Range`, is it unique?

The range is represented by 2 positions: the start row and column and the end row and column. So yes it seems difficult to me that 2 nodes have the same range that would mean that they are superimposed..

**Comment by jlerbsc** [comment]
I worked on a visitor that would allow you to locate a node using range. If you wait a little, this work will be committed soon.
