### ISSUE TITLE
Parse a new block of code and add it to an existant Compilation Unit

### ISSUE THREAD

**Issue by uhfonso** [javaparser/javaparser#4260]
Hello, I would like to know if it is possible to parse a generic block of code (For example a String with "if(x<y){x++}") and then add this new parsed block to an already existent parsed file. 
I know it's possible to this manually, but I would have to identify which statement I would want to create and then add the content to it, and I want to make this as generic as possible. 
Will be thankful with any help, thank you!

**Comment by jlerbsc** [comment]
Hi, You can parse a string and then analyze the AST. In your example the main node is in IF statement.

**Comment by jlerbsc** [comment]
Does this answer agree with you?

**Comment by jlerbsc** [comment]
I'm closing this exit because there's no answer.
