### ISSUE TITLE
ResolvedReferenceType returns incorrect typeParametersMap

### ISSUE THREAD

**Issue by Elewyth** [javaparser/javaparser#4269]
Test Case:
```java
class JavaParserTest {

  @Test
  void typeParametersMap() {
    var typeSolver = new ReflectionTypeSolver();
    var collection = new ReflectionInterfaceDeclaration(Collection.class, typeSolver);
    var iterable = collection.getInterfacesExtended().getFirst();
    assertEquals("java.lang.Iterable", iterable.getQualifiedName());
    var param = iterable.typeParametersMap().getValueBySignature("java.lang.Iterable.T").orElseThrow();
    assertEquals("E", param.describe()); // fails: returns "T" instead
  }

  @Test
  void getTypeParametersMap() {
    var typeSolver = new ReflectionTypeSolver();
    var collection = new ReflectionInterfaceDeclaration(Collection.class, typeSolver);
    var iterable = collection.getInterfacesExtended().getFirst();
    assertEquals("java.lang.Iterable", iterable.getQualifiedName());
    var param = iterable.getTypeParametersMap().getFirst().b;
    assertEquals("E", param.describe()); // fails: returns "T" instead
  }
}
```

For Context:
```java
// Iterable is declared as
public interface Iterable<T> { }
// Collection is declared as
public interface Collection<E> extends Iterable<E> { }
```

javaparser version: 3.25.7
Java version: 21

It seems that both  `typeParametersMap()` and `getTypeParametersMap()` do not properly include the information that `Collection` passes `E` as a type argument to `Iterable`. Instead, the both return a reference to `T` (the type parameter of `Iterable`) as the value for `T`. This is, of course, impossible, since there is no `T` on `Collection`.

Is this a bug, or am I misunderstanding how these methods are supposed to work? On another note, what is the difference between these two methods? They seem to return different values in certain circumstances.

EDIT:
I figured out using `getAncestors()` instead of `getInterfacesExtended()` works correctly. However, it is still confusing/unclear why `getAncestors()` works and `getInterfacesExtended()` does not. Maybe this just needs some clearer documentation.

**Comment by jlerbsc** [comment]
> It seems that both typeParametersMap() and getTypeParametersMap() do not properly include the information that Collection passes E as a type argument to Iterable. Instead, the both return a reference to T (the type parameter of Iterable) as the value for T. This is, of course, impossible, since there is no T on Collection.

All this seems logical to me because the code refers to a declaration and the declaration of the Iterable interface does indeed include a parameter type T.

**Comment by jlerbsc** [comment]
> On another note, what is the difference between these two methods?

These 2 structures are different views on the same information.

**Comment by jlerbsc** [comment]
> I figured out using `getAncestors()` instead of `getInterfacesExtended()` works correctly. However, it is still confusing/unclear why `getAncestors()` works and `getInterfacesExtended()` does not.

getAncestors() method  returns the list of ancestors as a list of resolved reference types.

Below is an extract from the javadoc of the method

    * Note that an ancestor can be parametrized types with values specified. For example:
     * <p>
     * class A implements Comparable&lt;String&gt; {}
     * <p>
     * In this case the ancestor is Comparable&lt;String&gt;

**Comment by jlerbsc** [comment]
> Maybe this just needs some clearer documentation.

I readily admit that the documentation could have been more precise/clear, the project designers should certainly have spent more time on it.

**Comment by Elewyth** [comment]
Thank you for your response. Yes, the documentation for `getAncestors()` does clearly state that it includes parameterized references. I guess I just didn't see that method existed before, and was working with `getInterfacesExtended()`. Using `getAncestors()` everything works as expected!
