### ISSUE TITLE
Reduce constructor count

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#427]
Check all classes, see if they have convenience constructors and turn them into static create methods.

**Comment by matozoid** [comment]
Here's the approach I have in my mind:
- make one constructor that has parameters for every field (more or less like Scala.) Throw away the other constructors.
- make that constructor very tight in what it accepts: throw exceptions for arguments being null where it is not allowed. (Note: double check that setters don't allow you to sneak in nulls.)
- make static methods to create new instances. (The thrown away constructors should give some inspiration here)
- make one static method without parameters that creates a new instance set to reasonable defaults.

Naming. Not sure yet:
- maybe call all of them "create(...)" and expect them to be used like "NameExpr.create(...)"
- maybe call all of them "createBlah(...)" where Blah is the object being created, possibly with some specific text for this way of creation appended. These can be statically imported and used like "createNameExpr(...)"
- maybe call all of them "blah(...)" which is the same as the previous option, but more DSL'ish: "nameExpr("hello")"

@DeepSnowNeeL - you're already creating lots of functionality like this, what do you think?

**Comment by DeepSnowNeeL** [comment]
Really not a big fan of static methods to construct objects.
I would prefer having everything constructed from parent methods and keep a
big ctor for the parser

I need to dig deeper on statement/expr builder methods to make something
handy

**Comment by matozoid** [comment]
I see what you mean - build the AST from the root, not from the leaves. Let's keep the amount small then. Not sure how we would deal with nodes that can be in many other nodes then (NameExpr for example.)

We agree on the big constructor. There is also a default, no-parameters constructor in every node. Would you like to leave that there?

**Comment by DeepSnowNeeL** [comment]
Yeah the no-arg constructor is really usefull to build nodes with just the
params I have

**Comment by matozoid** [comment]
I went through all the constructors recently and forwarded them all to a "main" constructor. It's probably fine like this. Actually, I'll investigate the static methods that came from ASTHelper to see if they fit in nicely with what we have now, and after that I'll close this.
