### ISSUE TITLE
Symbol resolution issue with MethodDeclaration in JavaParser

### ISSUE THREAD

**Issue by zgorzk** [javaparser/javaparser#4286]
I am attempting to retrieve recursively all methods invoked within a given method. To accomplish this, I employ a visitor that, for each MethodCallExpr encountered, locates the corresponding MethodDeclaration and proceeds to process it. However, after the initial successful resolution, subsequent attempts fail as if no solvers are defined.

By example for classes:

```
public class A {
    public void methodWithForEachInA() {
        B b = new B();
        new ArrayList<>().forEach(el -> b.methodWithForEachInB());
    }
}

public class B {
    public void methodWithForEachInB() {
        C c = new C();
        new ArrayList<>().forEach(el -> c.methodWithForEachInC());
    }
}

public class C {
    public void methodWithForEachInC() {
        new ArrayList<>().forEach(System.out::println);
    }
}
```

I would expect that Visitor below:
```
public class TestVisitor extends VoidVisitorAdapter<Void> {

    @Override
    public void visit(MethodDeclaration node, Void arg) {
        System.out.println(node.toString());
        super.visit(node, arg);
    }
    @Override
    public void visit(MethodCallExpr node, Void arg) {
        try {
            var symbol = node.resolve();
            if (symbol instanceof JavaParserMethodDeclaration methodDeclaration) {
                visit(methodDeclaration.getWrappedNode(), arg);
//                methodDeclaration.getWrappedNode().accept(new TestVisitor(), arg);  also not working
            } else {
                super.visit(node, arg);
            }
        } catch (RuntimeException e) {
            var solver = node.getSymbolResolver();
            e.printStackTrace();
        }
    }
}
```

will print:

> public void methodWithForEachInA() {
>     B b = new B();
>     new ArrayList<>().forEach(el -> b.methodWithForEachInB());
> }
> public void methodWithForEachInB() {
>     C c = new C();
>     new ArrayList<>().forEach(el -> c.methodWithForEachInC());
> }
> public void methodWithForEachInC() {
>     new ArrayList<>().forEach(System.out::println);
> }

But it only prints (below) and then fail to resolve "forEach" in method methodWithForEachInB with "Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration". But i can see in variable **solver** that solvers are defined.

> public void methodWithForEachInA() {
>     B b = new B();
>     new ArrayList<>().forEach(el -> b.methodWithForEachInB());
> }
> public void methodWithForEachInB() {
>     C c = new C();
>     new ArrayList<>().forEach(el -> c.methodWithForEachInC());
> }

I have my solver configured like below and they work fine but not for MethodDeclaration (and its children) resolved by "node.resolve()".
```
    public static void main(String[] args) throws IOException {
        String SRC_PATH = "src/main/java";
        String FILE_PATH = "src/main/java/test/A.java";

        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new JavaParserTypeSolver(new File(SRC_PATH)));
        typeSolver.add(new ReflectionTypeSolver(false));

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
        ParserConfiguration pc = new ParserConfiguration().setSymbolResolver(symbolSolver);
        StaticJavaParser.setConfiguration(pc);

        TestVisitor testVisitor = new TestVisitor();

        CompilationUnit c = StaticJavaParser.parse(new File(FILE_PATH));
        c.accept(testVisitor,null);
    }
```
### Environment
- javaparser-symbol-solver-core: 3.25.7
- Java 20

Is there sth i'm doing wrong that my solvers are not detected, or is it a bug?

**Comment by jlerbsc** [comment]
The ArrayList import is certainly missing for your code to work correctly.

**Comment by zgorzk** [comment]
Sure I omitted imports but code is running as i described. Here repo with this example:
https://github.com/zgorzk/javaparserIssue4286

**Comment by jlerbsc** [comment]
Here's the result I get with your test case on the latest version of JP and integrating the ArrayList import. It seems to me that it corresponds to what you're expecting.

> public void methodWithForEachInA() {
    B b = new B();
    new ArrayList<>().forEach(el -> b.methodWithForEachInB());
}
public void methodWithForEachInB() {
    C c = new C();
    new ArrayList<>().forEach(el -> c.methodWithForEachInC());
}
public void methodWithForEachInC() {
    new ArrayList<>().forEach(System.out::println);
}
public void methodWithForEachInB() {
    C c = new C();
    new ArrayList<>().forEach(el -> c.methodWithForEachInC());
}
public void methodWithForEachInC() {
    new ArrayList<>().forEach(System.out::println);
}
public void methodWithForEachInC() {
    new ArrayList<>().forEach(System.out::println);
}

**Comment by zgorzk** [comment]
I know where is my problem. 
What i believe u did is make code from all 3 classes (A,B,C) into one String and parse it like 

> CompilationUnit c = StaticJavaParser.parse(CODE_STRING)

 instead of parsing the way i try to:

> CompilationUnit c = StaticJavaParser.parse(new File(FILE_PATH))

When it's in one compilation unit then all MethodCallExpr can be resolved. But when i parse one file "A.java" i have a compilation unit with

> MethodDeclaration methodWithForEachInA()
> MethodCallExpr methodWithForEachInB() - which solver can resolve into MethodDeclaration methodWithForEachInB()
> 

But now when i try to resolve any MethodCallExpr from MethodDeclaration methodWithForEachInB() it fails with:
> java.lang.IllegalStateException: Symbol resolution not configured: to configure consider setting a SymbolResolver in 
> the ParserConfiguration
> 	at com.github.javaparser.ast.Node.lambda$getSymbolResolver$9(Node.java:805)
> 	at java.base/java.util.Optional.map(Optional.java:260)
> 	at com.github.javaparser.ast.Node.getSymbolResolver(Node.java:801)
> 	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:319)
> 	at TestVisitor.visit(TestVisitor.java:16)

It looks like like i cannot resolve recursively MethodCallExpr because it works only first time and i need to find some other way to do it. 
Does it sound right?

**Comment by zgorzk** [comment]
It seems like my approach with (below) should also be working and error "Symbol resolution not configured..." should not occur. 
> CompilationUnit c = StaticJavaParser.parse(new File(FILE_PATH))

**Comment by jlerbsc** [comment]
In your case, you'll certainly get a different result if you use the SourceRoot class to parse all the files in a single pass. 

It seems to me that the symbol solver is linked to the root of the AST (CompilationUnit) when the file is parsed.

**Comment by zgorzk** [comment]
So i did some experiments and with code below for each compilation unit from parsed file solver was defined:
```
        SourceRoot sourceRoot = new SourceRoot(Paths.get(SRC_PATH_TEST));
        sourceRoot.getParserConfiguration().setSymbolResolver(symbolSolver);
        sourceRoot.tryToParse();
        List<CompilationUnit> cus = sourceRoot.getCompilationUnits();
        cus.forEach(c -> {
            var solver = c.getSymbolResolver();
            c.accept(testVisitor,null);
        });
```

But when in Visitor I resolve MethodCallExpr to MethodDeclaration end then i try to process it the solvers are no longer available. Previously i wrote that they are, but that was my mistake, sorry.
```
    @Override
    public void visit(MethodCallExpr node, Void arg) {
        try {
            var solver = node.getSymbolResolver()  // should be here, then i would see it causes exception having breakpoint on next line
            var symbol = node.resolve();
            if (symbol instanceof JavaParserMethodDeclaration methodDeclaration) {
                visit(methodDeclaration.getWrappedNode(), arg);
            } else {
                super.visit(node, arg);
            }
        } catch (RuntimeException e) {
            var solver = node.getSymbolResolver(); // this was wrong
            e.printStackTrace();
        }
    }
```

Resolved MethodDeclaration is a part of new CompilationUnit(not a part of above list cus) and it does not have solvers defined. 
Is there a way to resolve MethodCallExpr to MethodDeclaration and keep solvers or define them for a node returned by node.resolve()?

**Comment by zgorzk** [comment]
if there is no gracious way to achieve it then I guess I can just pass my cus list to Visitor and when i resolve MethodCallExpr to MethodDeclaration find corresponding node in one of cus elements (where solvers are defined)

**Comment by jlerbsc** [comment]
The JavaParserTypeSolver class instantiates a parser with a default configuration that does not contain the symbolSolver declaration. To do what you want to do, you need to proceed differently, for example by constructing a call graph by browsing the method calls in each class declaration.

However, in your case, a workaround would be to use this code snippet.

        CombinedTypeSolver typeSolver = new CombinedTypeSolver();

        ParserConfiguration parserConfiguration = new ParserConfiguration()
				.setSymbolResolver(new JavaSymbolSolver(typeSolver));

        typeSolver.add(new JavaParserTypeSolver(new File(SRC_PATH), parserConfiguration));
        typeSolver.add(new ReflectionTypeSolver(false));

        StaticJavaParser.setConfiguration(parserConfiguration);

In addition, instead of using StaticJavaParser, I advise you to use the following adapter

    JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser(parserConfiguration));

**Comment by zgorzk** [comment]
Ok I get It. Thanks!

**Comment by zgorzk** [comment]
So it is not a bug and I should close the issue, right? Asking cause i see that label Bug report was added and removed?

**Comment by jlerbsc** [comment]
At first I thought it was a bug, but on closer analysis I realised it was the expected behaviour. The JavaParserTypeSolver is a special solver in that it internally uses a parser initialised with default values because it is independent of the initialisation made by the user. The API can be used to provide a configuration. It's a solution that doesn't seem very intuitive to me, but it exists and you can use it.

**Comment by zgorzk** [comment]
Yeah it works for me. Thank u for your help!

**Comment by bs76** [comment]
Came here as I faced similar problem. While in visitor I tried to resolve symbols -- usually those were final public static in parent classes. Resolving would fail in ~ 30% of cases with missing resolver. Turns out I had to explicitly set java language level in ParserConfiguration and *then* all started to resolve correctly.

**Comment by jlerbsc** [comment]
> Came here as I faced similar problem. While in visitor I tried to resolve symbols -- usually those were final public static in parent classes. Resolving would fail in ~ 30% of cases with missing resolver. Turns out I had to explicitly set java language level in ParserConfiguration and _then_ all started to resolve correctly.

Can you open up a new avenue for your problem and provide us with a simple test case that reproduces your case.
