### ISSUE TITLE
How to resolve ImportDeclaration

### ISSUE THREAD

**Issue by Laughh** [javaparser/javaparser#4292]
Hi, I'm using JP, I wanna know that is there any way to resolve ImportDeclation?

**Comment by jlerbsc** [comment]
No, that's not possible at the moment. Can you describe your requirements?

**Comment by Laughh** [comment]
For an import statement, if the imported class or method is in the source file, find the corresponding ClassOrInterfaceDeclaration, EnumDeclaration or MethodDeclaration.

**Comment by Laughh** [comment]
Whether the method `tryToSolveType` can help me?

**Comment by jlerbsc** [comment]
> For an import statement, if the imported class or method is in the source file, find the corresponding ClassOrInterfaceDeclaration, EnumDeclaration or MethodDeclaration.

This doesn't correspond to the description of a use case, which means we can't provide you with a relevant answer. It seems that you're not interested in local classes or classes declared in the same package, for example.

The tryToSolveType method tries to resolve a type by its name, so if you have the name of a type you can obtain the corresponding declaration.

**Comment by Laughh** [comment]
Got it! Thanks a lot!
