### ISSUE TITLE
The Annotation inner TypeReference are not visited in Adapter

### ISSUE THREAD

**Issue by chmuche** [javaparser/javaparser#430]
Java8 introduce a new ElementType in the Annotation Target (`ElementType.TYPE_PARAMETER`)
[JSL 9.6.4.1. @Target  ](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.4.1)

In VoidAdapter<A> the method :

```
@Override public void visit(final ReferenceType n, final A arg) {
        visitComment(n.getComment(), arg);
        n.getType().accept(this, arg);
    }
```

Don't visit the annotations

A little workaround is to override this method like this :

```
@Override
    public void visit(final ReferenceType n, final A arg) {
        for (AnnotationExpr annotation : n.getAnnotations()) {
            annotation.accept(this, arg);
        }
        super.visit(n, arg);
    }
```

this Issue is in tree Adapter Void, Generic, Modifier but not in DumpVisitor

**Comment by chmuche** [comment]
After more research I think ReferenceType#getArraysAnnotations() is not used in the same Adapter.

**Comment by matozoid** [comment]
I'm still working on this, annotations turn out to be a more complex topic than I thought.
