### ISSUE TITLE
Regression in 3.25.9: `Cannot be 'abstract' and also 'private'.` for a `private` method in an interface

### ISSUE THREAD

**Issue by famod** [javaparser/javaparser#4331]
Following (stupid) interface:
```java
public interface Foo {

    default String bar() {
        return "bar" + baz();
    }

    private String baz() {
        return "baz";
    }
}
```
yields parsing error `Cannot be 'abstract' and also 'private'.` for the `baz()` method with 3.25.9, but not with 3.25.8 or earlier.

Parser creation:
```java
    private static JavaParser buildParser() {
        final var config = new ParserConfiguration();
        config.setLanguageLevel(LanguageLevel.JAVA_17);
        return new JavaParser(config);
    }
```

Maybe caused by https://github.com/javaparser/javaparser/pull/4317/files#diff-ed6e5bb8f3aae72a41d0bea075cc5d3c1c663b1e8aef01100bc22e30ccb24086 :question:

**Comment by jlerbsc** [comment]
Thank you for declaring this regression.

**Comment by famod** [comment]
Thanks @jlerbsc for releasing 3.25.10 with the fix!
