### ISSUE TITLE
Processing nested classes and their methods

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#4334]
Hi, I'm trying to shuffle the methods in each class in the compilation unit, I do it like this

```java
        compilationUnit.accept(new VoidVisitorAdapter<Void>()
        {
            // iterate class by class
            @Override
            public void visit(ClassOrInterfaceDeclaration nodeClass, Void param)
            {
                // enlist all methods in a class or interface
                List<MethodDeclaration> methodDeclarationList = new ArrayList<>();

                System.out.println("CLASS = " + nodeClass.getNameAsString());

                nodeClass.accept(new VoidVisitorAdapter<>()
                {
                    @Override
                    public void visit(MethodDeclaration node, List<MethodDeclaration> param)
                    {
                        System.out.println(node.getNameAsString());
                        param.add(node.clone());
                    }

                }, methodDeclarationList);

                // random order
                Collections.shuffle(methodDeclarationList);

                // reset index
                index = 0;

                // insert shuffled methods one by one
                nodeClass.accept(new VoidVisitorAdapter<>()
                {
                    @Override
                    public void visit(MethodDeclaration node, List<MethodDeclaration> param)
                    {
                        node.replace(param.get(index));

                        index++;
                    }

                }, methodDeclarationList);

                super.visit(nodeClass, param);
            }

         }, null);
```

But the problem is, the `public void visit(MethodDeclaration node, List<MethodDeclaration> param)` method visitor, visits nested class methods. 

How can I visit class by class and method by method in those classes when they are nested?

```java
@Extension
public class Sample {

    public boolean ONE) {
        return 1;
    }

    public boolean TWO) {
        return 2;
    }

    private static class NestedClass extends Thread {
        @Override
        public void run() {
        }
    }
}
```
So by using my code, it lists `ONE` `TWO` and `run` methods as child of `Sample()` class.

Why does it pick `run()` as the child of the outer `Sample` class, shouldn't it avoid doing?

It's the child of `NestedClass` shouldn't it be picked by the visitor of that ClassOrInterface visitor only?

I was convinced only the direct children of that class will be visited...

When I open the debugger and look at the `childNodes`, I cannot see `run` method in `SampleClass` children list, I can only find it in `NestedClass` children list (on 2nd level of compilation unit tree). 

How to make the visitors act accordingly and visit only the direct children of the class method list?

Thank you :)

**Comment by PELock** [comment]
Is checking

`if (node.getParentNode().isPresent() && node.getParentNode().get() == nodeClass)`

in MethodVisitor a good way to do it?

**Comment by jlerbsc** [comment]
This is a design problem arising from the fact that you have nested 2 visitors and your code snippet has compilation errors.

The visitor you are using browses all the members of the class declaration or the included class is one of the members of the class. The solution would be to modify the visitor's behaviour so that it is only interested in method declarations or create your own visitor.

May be something like that

    List<MethodDeclaration> methodDeclarationList = new ArrayList<>();

		 cu.accept(new VoidVisitorAdapter<List<MethodDeclaration>>()
	        {
	            // iterate class by class
	            @Override
	            public void visit(ClassOrInterfaceDeclaration nodeClass, List<MethodDeclaration> param)
				{
					System.out.println("CLASS = " + nodeClass.getNameAsString());

					List<MethodDeclaration> methodDeclarations = nodeClass.findAll(MethodDeclaration.class);
					methodDeclarations.forEach(md -> visit(md.asMethodDeclaration(), param));

					// random order
					Collections.shuffle(methodDeclarationList);
					// reset index
					Count index = new Count();

					// insert shuffled methods one by one
					methodDeclarations.forEach(md -> {
						md.replace(param.get(index.compteur));
						index.incr();
					});

					param.clear();

					nodeClass.getMembers().stream()
					.filter(member -> member.isClassOrInterfaceDeclaration())
					.forEach(member -> visit(member.asClassOrInterfaceDeclaration(), param));

				}

	            @Override
                public void visit(MethodDeclaration node, List<MethodDeclaration> param)
                {
                    System.out.println(node.getNameAsString());
                    param.add(node.clone());
                }

	         }, methodDeclarationList);

**Comment by PELock** [comment]
I cannot nest 2 visitors? Is that a problem too?

**Comment by jlerbsc** [comment]
The visitor you are using browses all the members of the class declaration...

You should look at the source of the VoidVisitorAdapter class and you'll immediately understand why.

**Comment by PELock** [comment]
Is there a way from the visitor perspective to make it visit only the direct children, not the nested items?

**Comment by PELock** [comment]
Your code is invalid, still it treats the `public void run()` method as a member of outer class.

**Comment by jlerbsc** [comment]
You probably need to develop your own visitor. In this case, the class included is a member of the "mother" class. You can try what you suggested, i.e. excluding the method if the class doesn't match.

**Comment by jlerbsc** [comment]
> Your code is invalid, still it treats the `public void run()` method as a member of outer class.

It was an example of what you can do.

**Comment by PELock** [comment]
Jup, checking for direct ownership

```java
if (node.getParentNode().isPresent() && node.getParentNode().get() == nodeClass)
```

does the job. It would be cool if this sort of vistor be available by default.

Thank you for your help :)
