### ISSUE TITLE
Find the first ancestor of a type?

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#4335]
I'm trying to find the first instance of `ClassOrInterfaceDeclaration` for the nested Java class methods, right now I use

```java
 Optional<ClassOrInterfaceDeclaration> topNode = nestedMethodNode.findAncestor(ClassOrInterfaceDeclaration.class);
```
But it works only for the nearest ancestor.

What is the proper way of finding the top most class declaration of the nested method (multilevel)?

**Comment by jlerbsc** [comment]
You can call findAncestor recursively until you no longer find the declaration you're looking for.

**Comment by jlerbsc** [comment]
I am closing this issue because we have given an answer and there is no further interaction on this subject.
