### ISSUE TITLE
Arrays as Variables

### ISSUE THREAD

**Issue by HadeellAbunassar** [javaparser/javaparser#4338]
Im trying  to extract Java source code's UML features. Regarding the array type, it functions properly when it is a method signature or return type, but it won't be detected when it is a variable.

the part of the code related to my problem:

    @Override
    public void visit(FieldDeclaration n, Void arg) {
        super.visit(n, arg);
        String modifiers = modifiersToString(n.getModifiers());
        Type type = n.getElementType();
        System.out.println("Processing type: " + n.getElementType().getClass().getSimpleName() + " - " + n.getElementType());
        String typeName = typeToString(type);
        memberInfo.append("Field: ")
                .append(modifiers.isEmpty() ? "" : modifiers + " ")
                .append(typeName + " ")
                .append(n.getVariables().get(0).getName())
                .append("\n");
     }

    @Override
    public void visit(MethodDeclaration n, Void arg) {
        super.visit(n, arg);
        String modifiers = modifiersToString(n.getModifiers());
        System.out.println("Processing type: " + n.getType().getClass().getSimpleName() + " - " + n.getType());
        String returnType = typeToString(n.getType());
        memberInfo.append("Method: ")
                .append(modifiers.isEmpty() ? "" : modifiers + " ")
                .append(returnType + " ")
                .append(n.getName())
                .append(parametersToString(n.getParameters()))
                .append("\n");
    }

     private String typeToString(Type type) {
        StringBuilder typeStr = new StringBuilder();
        while (type instanceof ArrayType) {
            ArrayType arrayType = (ArrayType) type;
            type = arrayType.getComponentType();
            typeStr.append("[]");
        }
        return type.toString() + typeStr;
    }  

When Im trying to run this code:

    public class UML {
    public int[] checkInt;
    public Item[] checkItem;
    public String[] checkString;

    public double[] checkDouble;

    public Item[] getCheckItem() {
        return checkItem;
    }

    public double[] getCheckDouble() {
        return checkDouble;
    }

    public String[] check(int[] checkInt,double[] checkDouble){
        return "";
    }
    } 

I get this output : 
Processing type: PrimitiveType - int
Processing type: ClassOrInterfaceType - Item
Processing type: ClassOrInterfaceType - String
Processing type: PrimitiveType - double
Processing type: ArrayType - Item[]
Processing type: ArrayType - double[]
Processing type: ArrayType - String[]
public class UML

Field: public int checkInt
Field: public Item checkItem
Field: public String checkString
Field: public double checkDouble
Method: public Item[] getCheckItem()
Method: public double[] getCheckDouble()
Method: public String[] check(int[] checkInt, double[] checkDouble)

**Comment by jlerbsc** [comment]
To obtain the type of a field declaration, use the n.getCommonType() method, as the getElementType() method, in the case of an array, provides the type of the elements in the array.
