### ISSUE TITLE
Split GenericVisitor and VoidVisitor to multiple J8 @FunctionalInterface

### ISSUE THREAD

**Issue by chmuche** [javaparser/javaparser#434]
I think that will be great if the two big interfaces will be split in a lot of little Functional interface, is that way we can use lambda expression and not always use Generic or Void Visitor.

it's just an idea like that

**Comment by matozoid** [comment]
Doesn't it get clumsy to override a lot of visit methods then?

**Comment by chmuche** [comment]
I don't know yet,  but I agree the visitor design pattern of the GOF is define with one big interface.  But I think ,  maybe with functionnal interface we can do this differently.
 Like I said is just an idea. 

Because a VoidVisitor's method is just a BiConsumer with a particular type. So I think is maybe possible.

**Comment by matozoid** [comment]
You can always try it out and show it in a PR :)

**Comment by matozoid** [comment]
@chmuche have you tried to see if this is feasible?

**Comment by matozoid** [comment]
Moving this out of 3.0.0 since @chmuche is not availble for a few months.

**Comment by matozoid** [comment]
This would be more or less implemented by #804. If not, please reopen.
