### ISSUE TITLE
somtimes AssignExpr.target is wrong

### ISSUE THREAD

**Issue by HaHarden** [javaparser/javaparser#4340]
if my code is that:
```java
class Test {
  private MyObject field;
  private void fun() {
    field = new MyObject();  // the AssignExpr.target is NameExpr,but it should be FieldAccessExpr
    this.filed = new MyObject();  // the AssignExpr.target is FieldAccessExpr,it's right.
  }
}
```
the forth line is wrong!

**Comment by jlerbsc** [comment]
Not at all, 'field' is indeed a NameExpr.

**Comment by HaHarden** [comment]
when I get the AssignExpr of the forth line,how do I determine whether AssignExpr.target is a local variable or a field access?

**Comment by jlerbsc** [comment]
To get the declaration you have to resolve the expression corresponding to the target.

**Comment by jlerbsc** [comment]
I'm closing this issue because we've answered the question and there are no further questions.
