### ISSUE TITLE
Regression from #602

### ISSUE THREAD

**Issue by laurentschoelens** [javaparser/javaparser#4355]
@matozoid and @ftomassetti

I'm trying to move from javaparser 2.x to 3.x and got issues with parsing `Long.MIN_VALUE`.

- With latest 2.x, `-9223372036854775808L` is parsed to the special `com.github.javaparser.ast.expr.LongLiteralMinValueExpr` which got the good final result.

- With 3.x, `-9223372036854775808L` is parsed to `com.github.javaparser.ast.expr.UnaryExpr` with `com.github.javaparser.ast.expr.LongLiteralExpr`. But parsing `9223372036854775808L` as Long will throw `NumberFormatException` since the value is higher than `Long.MAX_VALUE`.

Could you tell me how can I fix this regarding 3.x model or if I'm doing something wrong ?

For me, it's regression from #602 in 3.x RC

**Comment by jlerbsc** [comment]
There is no parsing error with this snippet.

    CompilationUnit cu = StaticJavaParser.parse(
				 "class Foo {\n"
				 + "	Long l = 9223372036854775808L;\n"
				 + "}");
     System.out.println(cu.toString());

But the compiler generates this error "The literal 9223372036854775808L of type long is out of range" for this field declaration.

Even if JP tolerates a few approximations in the code that is parsed, the prerequisite is still to provide it with code that compiles without error.

**Comment by laurentschoelens** [comment]
Thanks for the reply but my concern is about `-9223372036854775808L` with minus sign first.

`-9223372036854775808L == Long.MIN_VALUE`

**Comment by jlerbsc** [comment]
I'm not sure I understand your problem but there is no parsing error with

    CompilationUnit cu = StaticJavaParser.parse(
			 "class Foo {\n"
			 + "	Long l = -9223372036854775808L;\n"
			 + "}");

**Comment by jlerbsc** [comment]
For the information of others, see the discussions on this subject  https://github.com/javaparser/javaparser/pull/605

**Comment by laurentschoelens** [comment]
I'll try to look how to adapt my code to make it work again. Keep you updated

**Comment by laurentschoelens** [comment]
In fact, I've found that my initial code wasn't parsing properly negative numbers (the only one which was working was the Long's and Integer's MIN_VALUE). Closing the issue. Thanks for the project and sorry about this falsy-issue
