### ISSUE TITLE
Jar file location for JarTypeSolver

### ISSUE THREAD

**Issue by dexieBirb** [javaparser/javaparser#4374]
Hello, I'm creating an executable jar that uses javaparser.
For my CombinedTypeSolvers, I need to use JarTypeSolver however the jar location is within the executable jar. Now I'm getting a FileNotFoundException.

I just want to confirm if JarTypeSolver can locate jar files inside the project jar?

![image](https://github.com/javaparser/javaparser/assets/149030519/41a51016-a2e0-4254-a53f-de4acb4e4c90)

**Comment by jlerbsc** [comment]
Hi, I'm not sure you can do this with Javaparser, which uses javassist internally to load classes defined in a library. May be you could try this method https://stackoverflow.com/questions/37260774/load-library-jars-with-javassist

The general use case is a project using Javaparser which is analysing another project which may contain source files and/or libraries.

**Comment by jlerbsc** [comment]
Have you made any progress?

**Comment by dexieBirb** [comment]
Hi @jlerbsc ,

Sorry for the late response.

Yes, I was able to progress. This worked for me.

![image](https://github.com/javaparser/javaparser/assets/149030519/8e7e0f0c-8ded-480b-805a-d515c415aab2)

I can get all the classes I need. 
![image](https://github.com/javaparser/javaparser/assets/149030519/9f50ff95-09f0-42e4-807d-73dd94b816b5)

Thanks! :)

**Comment by jlerbsc** [comment]
In general, the person who opened the issue closes it when the subject is closed.

**Comment by dexieBirb** [comment]
Ok thanks again @jlerbsc!
