### ISSUE TITLE
【Question】Can a API be provided with a very concise judgment of whether the current variable is a local variable or a ginseng or field?

### ISSUE THREAD

**Issue by RTxin** [javaparser/javaparser#4378]
1. Can a API be provided with a very concise judgment of whether the current variable is a local variable or a ginseng or field?
2. I want to find out who used a 'variable' or 'method' and how to operate it

**Comment by jlerbsc** [comment]
> 1. Can a API be provided with a very concise judgment of whether the current variable is a local variable or a ginseng or field?

You can use symbol resolution to obtain a declaration, but I'm not sure that this meets your needs.

**Comment by jlerbsc** [comment]
> 2\. I want to find out who used a 'variable' or 'method' and how to operate it

Javaparser does not currently provide this information.
