### ISSUE TITLE
【Question】Should the results of `Expression#RESOLVE` cache?

### ISSUE THREAD

**Issue by RTxin** [javaparser/javaparser#4379]
1. If I write multiple rule detectors that use 'resolve' or `calculateResolvedType`, since the current `resolve` is re-executed each time, I consider JP can exchanging some space for time to reduce the time cost of resolve。

**Comment by jlerbsc** [comment]
Javaparser already has a cache to prevent certain costly operations from being re-executed. You can also add caching to your own code if you wish, but if you propose a modification to JP you will have to demonstrate that your solution has real added value.

To answer your question more precisely, it is indeed possible that caching the result of this method could be valuable. I also occasionally work on this subject but for the moment I haven't validated the solution I've implemented.
