### ISSUE TITLE
How to add statements to java methods

### ISSUE THREAD

**Issue by sbhat-hortonworks** [javaparser/javaparser#438]
I want to write a custom profiler for a huge codebase and want to know if I can use JavaParser to add startProfiler() endProfiler() between lines of code. I have seen many examples to read code, change method name etc. If it is possible to add code in methods, can someone provide me an example?

Like eg : if my code is : 
public void startMethod () { 
      hello();
}

It should now be : 
public void startMethod () { 
   startProfiler(); 
   hello(); 
   endProfiler();
}

I will also need to make sure that the startProfiler()/endProfiler() should be added between loop/conditional statements

Eg : For input : 
public void startMethod () { 
   for(int i = 0 ; i < 4; i++) {
      hello(); 
}
}

Output should be :
public void startMethod () { 
   for(int i = 0 ; i < 4; i++) {
      startProfiler(); 
      hello(); 
      endProfiler();
}
}
and NOT : 
public void startMethod () { 
    startProfiler();
    for(int i = 0 ; i < 4; i++) {
      endProfiler();
      startProfiler(); 
      hello(); 
      endProfiler();
  }
}

**Comment by chmuche** [comment]
You want to add `startProfiler();` and `endProfiler();` before and after each method's call ? 
Or only before and after a specific method _hello_ in your sample.

**Comment by sbhat-hortonworks** [comment]
Before and after each line of code in the method. Except if it is loop/conditional statement (and the line is not a comment/empty line)

**Comment by DeepSnowNeeL** [comment]
Here is an example :

``` java
CompilationUnit parse = JavaParser.parse(Paths.get("input.java").toFile());
        ModifierVisitorAdapter<?> modifier = new ModifierVisitorAdapter<Object>() {
            @Override
            public Node visit(MethodDeclaration n, Object arg) {
                super.visit(n, arg);
                //TODO handle other types of loops (do while, while, foreach)
                if (n.getBody().getStmts().stream().anyMatch(stmt -> stmt.getClass().equals(ForStmt.class))) {
                    n.getBody().getStmts().stream().filter(stmt -> stmt.getClass().equals(ForStmt.class)).map(stmt -> (ForStmt) stmt).forEach(forStmt -> {
                        if (forStmt.getBody() == null)
                            return;
                        if (forStmt.getBody().getClass().equals(BlockStmt.class))
                            appendProfilerMethods((BlockStmt) forStmt.getBody());
                        else {
                            Statement temp = forStmt.getBody();
                            BlockStmt createBlockStatementAsBody = forStmt.createBlockStatementAsBody();
                            createBlockStatementAsBody.getStmts().add(temp);
                            temp.setParentNode(createBlockStatementAsBody);
                            appendProfilerMethods(createBlockStatementAsBody);
                        }
                    });
                } else
                    appendProfilerMethods(n.getBody());

                return n;

            }

            private void appendProfilerMethods(BlockStmt body) {
                MethodCallExpr methodCallStartProfiler = new MethodCallExpr(null, "startProfiler");
                ExpressionStmt expr1 = new ExpressionStmt(methodCallStartProfiler);
                methodCallStartProfiler.setParentNode(expr1);
                body.getStmts().add(0, expr1);
                expr1.setParentNode(body);

                MethodCallExpr methodCallEndProfiler = new MethodCallExpr(null, "endProfiler");
                ExpressionStmt expr2 = new ExpressionStmt(methodCallEndProfiler);
                methodCallEndProfiler.setParentNode(expr2);
                body.getStmts().add(expr2);
                expr2.setParentNode(body);
            }
        };
        parse.accept(modifier, null);
           System.out.print(parse.toString());
```

Input:

``` java
package mypackage;

public class MyClass {
    public void startMethod() {
        hello();
    }

    public void startMethod() {
        for (int i = 0; i < 4; i++) {
            hello();
        }
    }
}
```

Ouputs:

``` java
package mypackage;

public class MyClass {

    public void startMethod() {
        startProfiler();
        hello();
        endProfiler();
    }

    public void startMethod() {
        for (int i = 0; i < 4; i++) {
            startProfiler();
            hello();
            endProfiler();
        }
    }
}
```

**Comment by sbhat-hortonworks** [comment]
Are there missing methods in the example? I see createBlockStatementAsBody() and setParentNode() is not part of the API

**Comment by DeepSnowNeeL** [comment]
I'm using the 3.0 alpha with probably my pending PR in it, but it does what it says :p

**Comment by sbhat-hortonworks** [comment]
Okk.. :D I am too new and embarrassed that I don’t know what these methods should do.

**Comment by sbhat-hortonworks** [comment]
I did generate a simple code by checking examples :

import java.io.File;

import java.io.IOException;

import japa.parser.ASTHelper;

import japa.parser.JavaParser;

import japa.parser.ParseException;

import japa.parser.ast.CompilationUnit;

import japa.parser.ast.Node;

import japa.parser.ast.expr.MethodCallExpr;

import japa.parser.ast.expr.NameExpr;

import japa.parser.ast.stmt.BlockStmt;

import japa.parser.ast.stmt.ExpressionStmt;

import japa.parser.ast.stmt.Statement;

import japa.parser.ast.visitor.ModifierVisitorAdapter;

public class ModifierVisitorAdapterDemo {

public static void main(String[] args) throws IOException, ParseException {

String filename = "CodeChange.java";

File sourceFile = new File(filename);

CompilationUnit cu = JavaParser.parse(sourceFile);

cu.accept(new ModifierVisitor(filename), null);

// instead of printing it to stdout you can write it to a file

System.out.println("// enriched source");

System.out.println(cu.toString());

// to save it into the original file

// this will overwrite the input file

// Files.write(sourceFile.toPath(),

// cu.toString().getBytes(Charset.defaultCharset()),

// StandardOpenOption.TRUNCATE_EXISTING

// );

}

private static class ModifierVisitor extends ModifierVisitorAdapter {

private String filename;

public ModifierVisitor(String filename) {

this.filename = filename;

}

@Override

public Node visit(ExpressionStmt node, Object arg) {

BlockStmt block = new BlockStmt();

ASTHelper.addStmt(block, makeCoverageTrackingCall("startProfiler"));

ASTHelper.addStmt(block, node);

ASTHelper.addStmt(block, makeCoverageTrackingCall("endProfiler"));

return block;

}

private Statement makeCoverageTrackingCall(String method) {

NameExpr coverageTracker = ASTHelper.createNameExpr("profiling");

MethodCallExpr call = new MethodCallExpr(coverageTracker, method);

return new ExpressionStmt(call);

}

}

}

But this is giving me the output with extra braces :

// enriched source

import java.io.BufferedReader;

import java.io.FileReader;

import java.io.IOException;

public class CodeChange {

```
public static void main(String[] args) throws IOException {

    {

        startProfiler();

        BufferedReader br = new BufferedReader(new FileReader(""));

        endProfiler();

    }

    {

        startProfiler();

        String currentLine = null;

        endProfiler();

    }

    while ((currentLine = br.readLine()) != null) {

        {

            startProfiler();

            System.out.println(currentLine);

            endProfiler();

        }

    }

}
```

}

For the input :

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class CodeChange {

public static void main(String [] args) throws IOException {
BufferedReader br = new BufferedReader(new FileReader(""));
String currentLine = null;
while ((currentLine = br.readLine()) != null) {
System.out.println(currentLine);
}
}
}
