### ISSUE TITLE
Different nodes have same hashcode

### ISSUE THREAD

**Issue by Laughh** [javaparser/javaparser#4390]
Hello! I'm using JP, and in the following code, I found that variables have the same hashCode in different scopes
```
public void hash(){
    {
        // 1
        Object cnt = new Object();
        cnt.equals(null);
    }
    {
        // 2
        Object cnt = new Object();
        cnt.equals(null);
    }

}
```

Here is the output. The ranges are different, but the hash code is Identical value. And is there any way to distinguish the two VariableDeclarators by hash code?
```
cnt = new Object()
Optional[(line 56,col 20)-(line 56,col 37)]
-628174007
--------------------
cnt = new Object()
Optional[(line 61,col 20)-(line 61,col 37)]
-628174007
--------------------
```

**Comment by jlerbsc** [comment]
Hi, The hashcode calculation for a variable declaration is based on the name, type, comments and initialisation expression attributes.

**Comment by Laughh** [comment]
But why the range are not considered？

**Comment by jlerbsc** [comment]
I don't know exactly. It's a functional equality which is obtained by an in-depth check of all the attributes which describe a node.

**Comment by jlerbsc** [comment]
I'm closing this exit because we've given an answer.
