### ISSUE TITLE
Meaning of LanguageLevel

### ISSUE THREAD

**Issue by BaumiCoder** [javaparser/javaparser#4392]
I have some Questions about the `LanguageLevel` of the parser.
1. What is difference between `CURRENT` and `BLEEDING_EDGE`? The [descriptions in the Javadoc](https://www.javadoc.io/static/com.github.javaparser/javaparser-core/3.25.10/com/github/javaparser/ParserConfiguration.LanguageLevel.html#CURRENT) are slightly different, but I cannot capture what is the different between "latest Java version" and "newest Java features". (Lately only `BLEEDING_EDGE` [was updated](https://github.com/javaparser/javaparser/commit/c8b5c77775f059e55e7531f34f522ed36fa976f7) by @johannescoetzee to 21, but `CURRENT` is still 16.)
2. The [RAW](https://www.javadoc.io/static/com.github.javaparser/javaparser-core/3.25.10/com/github/javaparser/ParserConfiguration.LanguageLevel.html#RAW) option disable post processing and validation. I understand that validation means that the code is checked to be valid for the specific Java version (e.g., Text Block Literals are not supported by Java versions lower than 15). If I want to parse all Java versions, I do not care about such validation, but what does the "post processing" do?
3. The supported Java versions are also mentioned in the README (1.0 to 18) and in the "About" section of the GitHub Repository (1 to 17). Should these versions only correspond to latest release or the status of the main branch? The range from the README actual correspond to the latest release (3.25.10).

**Comment by jlerbsc** [comment]
Thank you for reporting these inconsistencies.

CURRENT is the latest Java version that is available. It should be set at Java 18. This is a mistake.
BLEEDING_EDGE means the newest Java features supported. It is currently set to Java 21 because there are Java 21 features under development.

The about section has not evolved. I have just corrected this part.

The post processors are not clearly documented, but overall they include actions carried out after validation, such as assigning comments or initialising the solver symbol...

**Comment by BaumiCoder** [comment]
Thank you @jlerbsc for you fast answer.

1. :heavy_check_mark:  Okay, that means that the version from `BLEEDING_EDGE` has not been fully implemented in javaparser yet. 
2. I am only interested in the ranges of classes, methods, variables, Javadoc and of the `SimpleName` in the child notes of a class (i.e. the name of the class). Is the post processing helpful for this (e.g., "assigning comments" for Javadoc)?
3. :heavy_check_mark: The versions there is bounded by the `CURRENT` version, because the others are still under development, isn't it?

**Comment by jlerbsc** [comment]
> 2\. Is the post processing helpful for this

In theory, no, it's not useful.
