### ISSUE TITLE
Fail to use symbol resolver

### ISSUE THREAD

**Issue by matthieu-vergne** [javaparser/javaparser#4394]
Hi,

I try to figure out to which declaration refers a particular name, like in this code:
```java
void myMethod(String a) {
  a = "abc";
}
```
The `a` on line 2 refers to the parameter declared on line 1.

In a refactoring context, where we want to rename a particular name, we need to find the declaration for it and change all the names related to it, but only them. For example in this code:
```java
class MyClass {
	interface MyInt {
		String myMethod(String myParam);
	}

	MyInt myMethod(MyInt myParam) {
		myParam = new MyInt() {
			@Override
			public String myMethod(String myParam) {
				return myParam;
			}
		};
		return myParam;
	}
}
```
when renaming `myParam` on line 7, I should change also its declaration on line 6 and when it is returned on line 13. I should not change it on lines 9-10, because this is a different parameter (with the same name) hiding the one I am currently renaming. If I rename the parameter on lines 9-10, it should not change lines 6, 7, 13 (different parameter), but I should also not change line 3, because the parameter in the interface can have a different name than the corresponding implementations.

I am looking at the symbol resolver right now, but I fail to find a way to obtain what I want. Currently using the type resolvers, but I am unable to make it work properly:
> UnsolvedSymbolException{context='myParam', name='Solving myParam', cause='null'}

Moreover, type resolution is a first step, but at the end I need to resolve the declaration itself, since I may have hiding with the same types too. Do we have something like that in JavaParser?

**Comment by jlerbsc** [comment]
Hi, Javaparser allows you to find the declaration corresponding to a variable, for example, but does not allow you to retrieve all the uses of this variable.

**Comment by matthieu-vergne** [comment]
Finding the declaration is fine to me, I can do the rest. Just need to know how to do it.

**Comment by matthieu-vergne** [comment]
Just to be precise, I am not asking about some general aspect. I already know that the parser provides, generally speaking, the relevant information to figure out whether a given name refers to a given declaration. You can pass through a Parameter in the AST, then find an AssignExp that uses the same name, so based on the context you can figure out it relates to that parameter (or not if another parameter/variable/field has been declared since then).

My question is really concrete: is there already something implemented that allows me to tell something like this AssignExp assigns something to a "myParam", which is resolved to this parameter/field/variable/etc. without having to browse the whole AST myself. I would expect something like that implemented in the symbol resolving part.

**Comment by jlerbsc** [comment]
The variable declaration is a node that can be resolved by the resolve() method, which returns an instance of ResolvedValueDeclaration, for which there are many implementations.

**Comment by matthieu-vergne** [comment]
Based on what you said and experimenting a lot, I was able to make a simple code work on my input:
```java
class MyClass {
	interface MyInt {
		String myMethod(String myParam);
	}

	MyInt myMethod(MyInt myParam) {
		myParam = new MyInt() {
			@Override
			public String myMethod(String myParam) {
				return myParam;
			}
		};
		return myParam;
	}
}
```

In this simple code, I go straight to the point (with streams on the compilation unit) after parsing the input:
- I retrieve the `Parameter` at line 6 as a reference (what I expect at the end),
- I retrieve the `SimpleName` at line 7 that states "myParam",
- I take its parent `NameExpr` that I `resolve()` into a `ResolvedValueDeclaration`
- I check `isParameter()` before to translate it with `asParameter().toAst(Parameter.class)`
- I get a `Parameter` that I compare to my reference, and it is the expected one

So it works, and it roughly reproduce what I do in my actual code.

Now in my actual code, which is more complex but where I parse the same input, I do virtually the same thing (at some point get a `SimpleName`, then its parent `NameExpr` and resolve) but it fails to resolve it:
```
UnsolvedSymbolException{context='null', name='We are unable to find the value declaration corresponding to myParam', cause='null'}
	at com.github.javaparser.symbolsolver.core@3.25.10/com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:198)
	at com.github.javaparser.core@3.25.10/com.github.javaparser.ast.expr.NameExpr.resolve(NameExpr.java:166)
	at [my own code where I call nameExpr.resolve()]
```
What could cause such an exception?

**Comment by matthieu-vergne** [comment]
I got it: I change the identifier of the declaration before to look for the `SimpleName` related to it, and it seems it makes their resolve impossible. If I change first the `SimpleName` occurrences then I can resolve the declaration, and then I rename the declaration at the end.

**Comment by jlerbsc** [comment]
> What could cause such an exception?

I think it's the same bug as this one https://github.com/javaparser/javaparser/issues/3674.
If you share a code snippet we can confirm that it's the same bug.

**Comment by matthieu-vergne** [comment]
If you want to investigate you can clone my project and checkout this commit:
https://github.com/matthieu-vergne/STANOS/tree/121e3e54a45b3c1a0224572e6d56516df41b856c

Run the RefactorerTest unit tests:
https://github.com/matthieu-vergne/STANOS/blob/121e3e54a45b3c1a0224572e6d56516df41b856c/stanos-core/src/test/java/fr/vergne/stanos/core/refactorer/RefactorerTest.java
They should all be green.

Go to the Refactorer class at line 236:
https://github.com/matthieu-vergne/STANOS/blob/121e3e54a45b3c1a0224572e6d56516df41b856c/stanos-core/src/main/java/fr/vergne/stanos/core/refactorer/Refactorer.java#L236
Move this line after line 216 to rename the declaration before the other occurrences of the name.

Then you should have several tests failing with this exception:
```
UnsolvedSymbolException{context='null', name='We are unable to find the value declaration corresponding to myParam', cause='null'}
	at com.github.javaparser.symbolsolver.core@3.25.10/com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:198)
	at com.github.javaparser.core@3.25.10/com.github.javaparser.ast.expr.NameExpr.resolve(NameExpr.java:166)
	at [my own code where I call nameExpr.resolve()]
```
