### ISSUE TITLE
MethodCallExpr inside lambda in assignment expression cannot be resolved

### ISSUE THREAD

**Issue by YXL-123** [javaparser/javaparser#4399]
```
    public static void main(String[] args) throws IOException {
        String code = """
                import java.util.ArrayList;
                import java.util.List;
                public class Lambda {
                    interface MyInterface {
                        void doSomething(int a);
                    }
                      
                    void test(){
                        MyInterface myInterface;
                        ArrayList<Integer> list = new ArrayList<>();
                        list.forEach(val -> System.out.println(val));
                        myInterface = arg -> System.out.println(arg);
                    }
                }
                """;
        JavaParser javaParser = new JavaParser();
        TypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver());
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
        javaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
        javaParser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_17);
        ParseResult<CompilationUnit> result = javaParser.parse(code);
        ModifierVisitor<Void> visit = new ModifierVisitor<>(){
            public Visitable visit(MethodCallExpr n, Void arg) {
                ResolvedMethodDeclaration resolve = n.resolve();
                System.out.println(resolve.getQualifiedSignature());
                return super.visit(n, arg);
            }
        };
        visit.visit(result.getResult().get(), null);
        System.out.println(result.getResult().get());
    }
```
Hi, I'm trying to get the QualifiedSignature of MethodCallExpr but I'm getting a parsing error when MethodCallEcpr is in the lambda expression. In the above example, the lambda in the foreach does not give an error, but when it is used as the value of the assignment statement, the following error occurs. Is my usage wrong? Thank you.

> Exception in thread "main" java.lang.UnsupportedOperationException: Unknown node type: AssignExpr
> 	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.LambdaExprContext.solveSymbolAsValue(LambdaExprContext.java:198)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:63)
> 	at com.github.javaparser.resolution.model.Value.from(Value.java:45)
> 	at com.github.javaparser.resolution.Context.solveSymbolAsValueInParentContext(Context.java:199)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:145)
> 	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:76)
> 	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:82)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:334)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64)
> 	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:81)

**Comment by jlerbsc** [comment]
This case is not currently covered. Thank you for reporting this bug.

**Comment by YXL-123** [comment]
OK, thank you for your reply

**Comment by YXL-123** [comment]
OK, thank you for your reply.

**Comment by jlerbsc** [comment]
This is not trivial, because to resolve the println(..) method Javaparser has to resolve the type of the parameter, which is undefined at this stage. I don't see any precision on this point in the JLS. If you can clarify what needs to be done, I can try to resolve this bug quickly.

                public class Lambda {
                    interface MyInterface {
                        void doSomething(int a);
                    }

                    void test(){
                        MyInterface myInterface;
                        myInterface = arg -> System.out.println(arg);
                    }
                }

Decompiling the class doesn't provide any information either.

    Compiled from "Lambda.java"
    public class Lambda {
      public Lambda();
        Code:
           0: aload_0
           1: invokespecial #1                  // Method java/lang/Object."<init>":()V
           4: return

      void test();
        Code:
           0: invokedynamic #2,  0              // InvokeDynamic #0:doSomething:()LLambda$MyInterface;
           5: astore_1
           6: return
    }

**Comment by YXL-123** [comment]
Thanks, we try to distinguish function overloading by getting the QualifiedSignature of MethodCallExpr and get its method descriptor.

**Comment by YXL-123** [comment]
Hello, I have encountered a new problem about the MethodCallExpr node. For example, in the following example, how should I distinguish whether the scope is a class or a variable? In addition, the full class name form of Class will be parsed as FieldAccessExpr.
```
public class MethodCall {
    static class A{
        void a(){}
        static void b(){}
    }

    A a = new A();
    static void b(){}

    void call(){
        a.a();
        MethodCall.b();
        org.demo.expr.MethodCall.b();

        this.a.a();
        MethodCall.A.b();
    }
}
```

**Comment by jlerbsc** [comment]
Please don't mix issues.

**Comment by YXL-123** [comment]
Sorry, I'll create a new issue.
