### ISSUE TITLE
JavaParser finds "." in place of first element after a yeild statement.

### ISSUE THREAD

**Issue by Decencies** [javaparser/javaparser#4400]
> parse error: (line 98,col 31) Parse error. Found ".", expected one of  "," ";" "=" "@" "["

Line 98:
`                        yield rIHCHOIOCIOICHHRHHIOHIHIC.OOICCOCOCRHCOCIORIHHIHHHH("user", "publicServerGame", var4_6, var2_3);`

Column 31 (whitespace ommited):
`yield rIHCHOIOCIOICHHRHHIOHIHIC.OOICCOCOCRHCOCIORIHHIHHHH("user", "publicServerGame", var4_6, var2_3);`
`      ^`

Evidently there is no "." written at column 31

**Comment by Decencies** [comment]
Code formatting doesn't do it justice, here's a picture with an I-beam indicating the exact place:
![image](https://github.com/javaparser/javaparser/assets/66835910/864d2ac2-3c3f-45b3-bbb8-b1720a46cc59)

**Comment by jlerbsc** [comment]
Can you provide us with a unit test?

**Comment by Decencies** [comment]
> Can you provide us with a unit test?

Would the code being parsed suffice? I don't really know how to setup a unit test for this

**Comment by Decencies** [comment]
> > Can you provide us with a unit test?
> 
> Would the code being parsed suffice? I don't really know how to setup a unit test for this

https://pastebin.com/TjCbBvWS

**Comment by Decencies** [comment]
The program is using the latest version of JavaParser available on maven-central (3.25.10)

**Comment by jlerbsc** [comment]
Thank you. Can you show us how you configure the parser.

**Comment by Decencies** [comment]
> Thank you. Can you show us how you configure the parser.

https://github.com/sfPlayer1/Matcher/blob/2cb3bbd8a4652c33ce907c1bb1d5356835ec11d5/src/main/java/matcher/srcprocess/SrcDecorator.java#L72

**Comment by jlerbsc** [comment]
I get no exceptions when I parse your class with this code snippet.

    JavaParser javaParser = new JavaParser();
    javaParser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.RAW);
    ParseResult<CompilationUnit> result = javaParser.parse(code);

**Comment by Decencies** [comment]
Very weird, it seems to work standalone for me too....

**Comment by Decencies** [comment]
> Very weird, it seems to work standalone for me too....

nevermind, result.isSuccessful() is not true

**Comment by Decencies** [comment]
> > Very weird, it seems to work standalone for me too....
> 
> nevermind, result.isSuccessful() is not true

```java
JavaParser javaParser = new JavaParser();
javaParser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.RAW);
ParseResult<CompilationUnit> result = javaParser.parse(code);

if (!result.isSuccessful()) {
	for (Problem problem : result.getProblems()) {
		System.out.println(problem.getMessage());
	}
}
```

```
Parse error. Found ".", expected one of  "," ";" "=" "@" "["
Parse error. Found ".", expected one of  "," ";" "=" "@" "["
Parse error. Found ".", expected one of  "," ";" "=" "@" "["
Parse error. Found ".", expected one of  "," ";" "=" "@" "["
```

**Comment by jlerbsc** [comment]
Your test case can be reduced to the following.

There seem to be 2 problems:
The label parsing which does not tolerate the '.' character;
The parsing of the expression which does not tolerate a negative integer;

	@Test
	void issue4400() {
		String code =
				"enum LEVEL {\r\n"
				+ "		LOW, MEDIUM, HIGH;\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	public class Foo {\r\n"
				+ "		public static int match(LEVEL level) {\n"
				+ "	          return switch (level) {\n"
				+ "			default -> throw new UnsupportedOperationException();\n"
				+ "			case LEVEL.LOW -> -1;\n"
				+ "		  };\n"
				+ "		}\n"
				+ "	}";
		JavaParser javaParser = new JavaParser();
		javaParser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.RAW);
		ParseResult<CompilationUnit> result = javaParser.parse(code);

		if (!result.isSuccessful()) {
			for (Problem problem : result.getProblems()) {
				System.out.println(problem.getMessage());
			}
		}

	}

**Comment by jlerbsc** [comment]
This problem seems to have been solved in the current version javaparser-parent-3.26.0-snapshot

**Comment by jlerbsc** [comment]
I'm closing this issue as it seems to have been resolved.
