### ISSUE TITLE
Missing tokens in parent nodes

### ISSUE THREAD

**Issue by matthieu-vergne** [javaparser/javaparser#4403]
I am currently playing with the tokens associated to the nodes. To do so I am implementing something to display the tokens associated to each node of the tree, aligned on their tokens. Something that looks like this:
```
CompilationUnit
[...token...][...token...][...token...][...token...][...token...][...token...][EOF]
ClassOrInterfaceDeclaration                                                        
[...token...][...token...][...token...][...token...][...token...][...token...]     
             SimpleName                FieldDeclaration                            
             [...token...]             [...token...][...token...][...token...]     
                                                    VariableDeclarator             
                                                    [...token...]                   
```

When parsing the following code:
```java
class MyClass{String myField;}
```
It builds a CompilationUnit
that contains a ClassOrInterfaceDeclaration
that contains a SimpleName(MyClass) + FieldDeclaration(String myField)
FieldDeclaration contains a VariableDeclarator
that contains a ClassOrInterfaceType(String) + SimpleName(myField)

This is what we see by following the child nodes at each level.

In terms of tokens, it seems that a parent node contains the tokens of its child nodes. For example, ClassOrInterfaceDeclaration contains all these tokens:
```
[col 1-5:class][col 6: ][col 7-13:MyClass][col 14:{][col 15-20:String][col 21: ][col 22-28:myField][col 29:;][col 30:}]
```
And here is the only token of its SimpleName
```
[col 7-13:MyClass]
```
and the tokens of its FieldDeclaration:
```
[col 15-20:String][col 21: ][col 22-28:myField][col 29:;]
```
We can see the tokens of the two children are all in the tokens of the parent ClassOrInterfaceDeclaration.

However, it seems to not apply everywhere, especially for the VariableDeclarator, which only has this token:
```
[col 22-28:myField]
```
but it contains both a ClassOrInterfaceType with this token:
```
[col 15-20:String]
```
and a SimpleName with this token:
```
[col 22-28:myField]
```

We can see the ClassOrInterfaceType token is missing from its parent VariableDeclarator tokens.

It gives me a representation that is not a tree anymore, with "orphan" tokens like the ClassOrInterfaceType here:
![image](https://github.com/javaparser/javaparser/assets/1774210/bbedbc81-0403-4dde-8adf-013523cda1d1)

It looks like a discrepancy to me, since I would expect a parent to have all the tokens of its children, otherwise the tokens representation is not a tree anymore, and updating the token of a child does not necessarily mean updating a token of its parent. Is it a bug or is it intended?

**Comment by jlerbsc** [comment]
This is how the LexicalPreservingPrinter works, as described here https://tomassetti.me/lexical-preservation-javaparser/

**Comment by matthieu-vergne** [comment]
Thank you for the link, but I don't get the point. Maybe I was not clear.

I am not using the LPP here. I am implementing my own stuff to look at the tokens hierarchy.
By displaying it I observed that some parent nodes don't have the tokens of their children.
And it is about a freshly parsed CompilationUnit, without changes.

**Comment by jlerbsc** [comment]
The range of tokens are defined by the parser. To my knowledge, nowhere does it say that this is a hierarchy.

**Comment by matthieu-vergne** [comment]
By investigating further, it looks like it is a specificity of VariableDeclarator, because of the way combined declarations are handled. As per the Javadoc:
https://github.com/javaparser/javaparser/blob/f7428faf4bacc648dd65cd6ca6c21f87ca2a67ab/javaparser-core/src/main/java/com/github/javaparser/ast/body/VariableDeclarator.java#L55-L56

So a code `int x = 14, y = 3;` leads to 2 VariableDeclarators:
- `int x = 14` 
- `int y = 3`

And clearly composing them does not lead to the parent code, which factors the type `int`. So although it might be true in general by construction (and surely true for at least one ancestor), it is not a guarantee that the immediate parent contains the child tokens.
