### ISSUE TITLE
Tests systematically failing on Windows

### ISSUE THREAD

**Issue by matthieu-vergne** [javaparser/javaparser#4410]
To test the project, the readme states to execute the mvn install command with the wrapper:
https://github.com/javaparser/javaparser/blob/master/readme.md?plain=1#L100-L105

On my machine, it fails constantly:
![image](https://github.com/javaparser/javaparser/assets/1774210/7b179c31-dfb1-49fc-b728-90282dad3b11)

My machine: Windows 11 23H2 (build 22631.3447)

I wonder whether it is because there is a space in my user name, and thus in the path used. When I move the project in a path where there is no space, it still fails the same, but the test section still seems to depend on a path related to my user name, even if my project is not there anymore:
![image](https://github.com/javaparser/javaparser/assets/1774210/2608294d-025f-4fed-8f24-61287e6b113a)

**Comment by jlerbsc** [comment]
> but the test section still seems to depend on a path related to my user name

This is not the case.

**Comment by jlerbsc** [comment]
What is your java version?

**Comment by matthieu-vergne** [comment]
```
$ java --version
openjdk 17.0.9 2023-10-17 LTS
OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.46+19-CA (build 17.0.9+8-LTS, mixed mode, sharing)
```

**Comment by matthieu-vergne** [comment]
> > but the test section still seems to depend on a path related to my user name
> 
> This is not the case.

Well, it is, since it uses the .m2 repository which, in my case, is there.
I provided the PR to fix it, since it was indeed a problem of space in the path.
![image](https://github.com/javaparser/javaparser/assets/1774210/aa9b304f-4729-4ce8-bed5-d2bb6ed50389)
