### ISSUE TITLE
bad code formatter

### ISSUE THREAD

**Issue by HanzoDev1375** [javaparser/javaparser#4451]
hello im using java paser for format code java my java code

```java
public class JavaCodeFormat {
    /** lib implementation 'com.github.javaparser:javaparser-core:3.25.10' */
    public static String format(String code) {
      try {
        CompilationUnit cu = StaticJavaParser.parse(code);

        DefaultPrinterConfiguration configuration = new DefaultPrinterConfiguration();
        DefaultPrettyPrinter printer = new DefaultPrettyPrinter(configuration);

        String formattedCode = printer.print(cu);
        System.out.println(formattedCode);
        return formattedCode;
      } catch (Throwable t) {
        System.err.println("An error occurred during code formatting: " + t.getMessage());
        return code; // Return the original code if an error occurs
      }
    }

```
and format code by java paser

```java
String[] a = {"a","b","c"};

```

format code by google code formater

```java
String[] a = {
     "a",
     "b",
     "c"
};

```

**Comment by jlerbsc** [comment]
What's the problem?

**Comment by HanzoDev1375** [comment]
> What's the problem?

Hello, the codes are not Formating well according to Google

**Comment by jlerbsc** [comment]
It's normal, there's no relationship between the 2.

**Comment by HanzoDev1375** [comment]
Look, let me tell you like this, it does not comply with the new Java rules, for example, there is a code in the Google rules
 @Test
 public void myapp(){

 ///Todo 
 }

 But your library sorter works like this 
 @Test public void myapp(){

 ///Todo 
 }
 And this is not very interesting for the user. I can't use Google Code Formatter because it is extremely unstable for Android

**Comment by jlerbsc** [comment]
The pretty printer doesn't work like the google formatter. I don't understand your problem.

**Comment by HanzoDev1375** [comment]
I need it to work like google printer, this type of printer is code for 10 years ago

**Comment by jlerbsc** [comment]
You can develop your own printer using the pretty printer model. There is no need to propose a PR as this printer will not be integrated into Javaparser.

**Comment by jlerbsc** [comment]
I'm closing this exit because we've answered the question you asked.
