### ISSUE TITLE
How to distinguish whether the Scope of MethodCallExpr is a class or a variable or field?

### ISSUE THREAD

**Issue by YXL-123** [javaparser/javaparser#4456]
Hello, I have a question about the MethodCallExpr node. For example, in the following example, how should I distinguish whether the scope is a class or a variable or field? In addition, the full class name form of Class will be parsed as FieldAccessExpr.
```
public class MethodCall {
    static class A{
        void a(){}
        static void b(){}
    }

    A a = new A();
    static void b(){}

    void call(){
        a.a();
        MethodCall.b();
        org.demo.expr.MethodCall.b();

        this.a.a();
        MethodCall.A.b();
    }
}
```

**Comment by YXL-123** [comment]
This is its AST
![methodCall_ast](https://github.com/javaparser/javaparser/assets/72548567/02bd63f6-81dc-48c7-aad9-910b1314fefa)

**Comment by zhipingwu** [comment]
From my understanding, Javaparser is still single file language parser, the statement 

org.demo.expr.MethodCall.b();

in a single file, will be hard for Javaparser to recognize whether there is really a Class or Object named org, and a field demo, then a field expr, then a field MethoCall exist as the scope or not.

So, it depends on why you want to distinguish whether the scope is a class or a variable or field, can you name a few situations in front of you?

**Comment by jlerbsc** [comment]
> In addition, the full class name form of Class will be parsed as FieldAccessExpr.

This is a limitation of the parser, which in this case cannot distinguish the true nature of the code (access expression to a field or the qualified name of a class, etc.). The solver symbol fills this gap.

**Comment by jlerbsc** [comment]
> how should I distinguish whether the scope is a class or a variable or field?

You need to resolve the expression of the method scope, but there are limitations, for example if the expression represents a class.

Below is a simplistic  example


    Expression scope = methodCallExpr.getScope().get();
    System.out.println(scope.asNameExpr().resolve().isField());
    System.out.println(scope.asNameExpr().resolve().isParameter());
    System.out.println(scope.asNameExpr().resolve().isVariable());

but it won't work for these 2 expressions

    MethodCall.b();
    org.demo.expr.MethodCall.b();

**Comment by jlerbsc** [comment]
Does this answer your questions?
