### ISSUE TITLE
Fix comment parsing

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#45]
Make comment parsing work 100%, and write decent tests for it.

**Comment by ftomassetti** [comment]
I think that we could close this issue when we merge #50 and close #49.

While more tests are always welcome we have now some documentation in place (and more to come as part of #49), with 35 tests related to comments out of 60 total tests.

**Comment by SmiddyPence** [comment]
#50 and #49 are closed now. 

Others can create a new ticket for specific errors when found.
