### ISSUE TITLE
`com.github.javaparser.ast.Node#setParentNode` maybe lost parentNode，There may be forced modifications to the original AST Node

### ISSUE THREAD

**Issue by RTxin** [javaparser/javaparser#4507]
in my case, variable `first` is not empty, But when I call `getNameAsExpression`, the value of the variable `second` becomes null.

When I hit the breakpoint for tuning I found that，`getNameAsExpression`---->`new NameExpr(var)`---->`setParentNode`.

Inside the `setParentNode` method, `parentNode = newParentNode;` is used directly.

But the old `parentNode.getParentNode()` is not null, and `newParentNode.getParentNode()` is null.

I think `newParentNode` and `oldParentNode` should be added with some kind of link to ensure that new nodes returned by similar APIs do not affect the original AST Node。

**So far I've only found two methods that have been problematic for me to use：**
**1.     `com.github.javaparser.ast.nodeTypes.NodeWithSimpleName#getNameAsExpression`**
**2.     `com.github.javaparser.ast.body.CallableDeclaration#getSignature`**
**3.   ` com.github.javaparser.ast.NodeList#add(N)`** (`List<VariableDeclarator> staticList = new NodeList<>()` I found this problem when I mistakenly thought that a NodeList could be used as a normal list like an ArrayList.)

# There should be more methods that may have this problem and may require changes to the logic of `setParentNode`.

# Case
```java
    @Test
    public void issue4493() throws IOException {
        String classA_V1 = "public class ClassA{\n" +
                "    private String log =  \"sad\";\n" +
                "}";
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_18);
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver(false));
        parserConfiguration.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        parserConfiguration.setAttributeComments(true);

        final JavaParser javaParser = new JavaParser(parserConfiguration);

        final ParseResult<CompilationUnit> pc = javaParser.parse(classA_V1);
        if (pc.isSuccessful()) {
            pc.getResult().ifPresent(cu -> cu.accept(new VoidVisitorAdapter<Void>() {
                @Override
                public void visit(FieldDeclaration n, Void arg) {
                    Optional<CompilationUnit> first = n.getVariables().get(0).getName().findCompilationUnit();
                    System.out.println("first compilationUnit is " + first );
                    n.getVariables().get(0).getNameAsExpression();
                    Optional<CompilationUnit> second= n.getVariables().get(0).getName().findCompilationUnit();
                    System.out.println("second compilationUnit is " + second);
                }
            }, null));
        }
    }
```

**Comment by jlerbsc** [comment]
The getNameAsExpression method should not initialise the parent node.

**Comment by RTxin** [comment]
> The getNameAsExpression method should not initialise the parent node.

In addition, I found these three places that may have similar problems and need your help to look into them as well：

1. com.github.javaparser.ast.nodeTypes.NodeWithTypeArguments#setTypeArguments(com.github.javaparser.ast.NodeList<com.github.javaparser.ast.type.Type>)       【This method internally uses `setAsParentNodeOf`  ，This method is called by `com.github.javaparser.ast.body.CallableDeclaration#getSignature`】
2. com.github.javaparser.ast.NodeList#add(N) 【List<VariableDeclarator> staticList = new NodeList<>() I found this problem when I mistakenly thought that a NodeList could be used as a normal list like an ArrayList.】

**Maybe need to find out more ways to have this problem, or just make changes to the internal logic of setParent?**

**Comment by jlerbsc** [comment]
The logic in the setParentNode method is designed to attach new nodes to the AST. Old nodes are detached from the AST. This logic is correct and there is no reason to challenge it.

**Comment by RTxin** [comment]
> The logic in the setParentNode method is designed to attach new nodes to the AST. Old nodes are detached from the AST. This logic is correct and there is no reason to challenge it.

I understand what you mean and agree you.
Surely, the logic of `setParentNode` is fine from a macro point of view, So if new Api methods are to be developed in the future, it may be necessary to consider whether the `setParentNode` method is included and whether it is really needed.

Thanks for the reply🌹❤, I don't have any more questions, I'll reOpen this issue for feedback if I have similar questions in the future!😁

**Comment by jlerbsc** [comment]
I don't think there's much we can do except perhaps document the method better.

To get the right result, we'd have to clone the variable declaration like this

    n.getVariables().get(0).clone().getNameAsExpression();

**Comment by RTxin** [comment]
> I don't think there's much we can do except perhaps document the method better.
> 
> To get the right result, we'd have to clone the variable declaration like this
> 
> ```
> n.getVariables().get(0).clone().getNameAsExpression();
> ```

hi @jlerbsc ,
     I recently encountered a new scenario where I wanted to call NameExpr's resolve method. The regular NameExpr is OK, but invoke  `n.clone().getNameAsExpression().resolve()`      or        ` n.getNameAsExpression().resolve();` The error message `'The node is not inserted in a CompilationUnit'` is displayed.
      How can I use it？

**Comment by jlerbsc** [comment]
Can you provide us with a usable unit test that shows what you want to do and how you're going to do it?

**Comment by RTxin** [comment]
> Can you provide us with a usable unit test that shows what you want to do and how you're going to do it?

In general, I often need to parse these variable names and reverse to find the declaration, or get other more detailed information such as type, visibility, etc
```java
    @Test
    public void issue4493() throws IOException {
        String classA_V1 =
                "public class Sample {\n" +
                        "    public static String[] strings1 = {\"first\", \"second\"}; // Sink\n" +
                        "}";
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_18);
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver(false));
        parserConfiguration.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        parserConfiguration.setAttributeComments(true);

        final JavaParser javaParser = new JavaParser(parserConfiguration);

        final ParseResult<CompilationUnit> pc = javaParser.parse(classA_V1);
        if (pc.isSuccessful()) {
            pc.getResult().ifPresent(cu -> cu.accept(new VoidVisitorAdapter<Void>() {
                @Override
                public void visit(final FieldAccessExpr n, Void arg) {
                    try {
                        // get the name of the field
                        NameExpr expression = n.clone().getNameAsExpression();
                        extracted(expression);
                    } catch (Exception exception) {
                        exception.printStackTrace();
                    }
                }

                @Override
                public void visit(FieldDeclaration n, Void arg) {
                    super.visit(n, arg);
                    try {
                        for (VariableDeclarator variable : n.getVariables()) {
                            NameExpr expression = variable.clone().getNameAsExpression();
                            extracted(expression);
                        }
                    } catch (Exception exception) {
                        exception.printStackTrace();
                    }
                }

                private void extracted(NameExpr expression) {
                    ResolvedValueDeclaration declaration = expression.resolve();
                    // jump to AST Node , do other operations
                    declaration.toAst()
//                                .filter(........)
//                                .map(...............)
                            .orElse(null);
                    isSubtypeOf(declaration.getType(), "java.util.Date");
                }

                private void isSubtypeOf(ResolvedType type, String needClassName) {
                    // Detects whether the current class or its parent class has a specified class name
                    //......
                }
            }, null));
        }
    }
```

**Comment by jlerbsc** [comment]
Firstly, when you clone a node from the AST, the clone isn't part of the AST and it doesn't have the property that allows you to use the symbol solver (which is logical).

Now if I only consider the visit(FieldDeclaration n, Void arg) method of the visitor, why do you create a new expression (NameExpr) to obtain the type of the variable. You can simply resolve the variable to get the type (variable.resolve().getType()).
