### ISSUE TITLE
FindAll does not retrieve all the MethodCallExpr within a Statement

### ISSUE THREAD

**Issue by darthdaver** [javaparser/javaparser#4508]
I have a TryStmt as the following:

```java
try {
    System.clearProperty(SLSTR_L1B_PIXEL_GEOCODING_INVERSE);
    System.clearProperty(SYSPROP_SNAP_PIXEL_CODING_FRACTION_ACCURACY);
    final String[] keys = AbstractProductFactory.getForwardAndInverseKeys_pixelCoding(SLSTR_L1B_PIXEL_GEOCODING_INVERSE);
    assertEquals(PixelForward.KEY, keys[0]);
    assertEquals(PixelQuadTreeInverse.KEY, keys[1]);
} finally {
    if (inverseKey != null) {
        System.setProperty(SLSTR_L1B_PIXEL_GEOCODING_INVERSE, inverseKey);
    }
    if (fractionalAccuracy != null) {
        System.setProperty(SYSPROP_SNAP_PIXEL_CODING_FRACTION_ACCURACY, fractionalAccuracy);
    }
}
```

and I need to retrieve all the MethodCallExpr within the TryStmt. According to the documentation, 

```
public <T extends Node> List<T> findAll(Class<T> nodeType)
Walks the AST with pre-order traversal, returning all nodes of type "nodeType".
```

However, no MethodCallExpr are retrieved (see image attached).

<img width="921" alt="image" src="https://github.com/user-attachments/assets/31289c5e-6c49-4c78-a9b2-eedace28af64">

Instead, if I navigate the AST of the TryStmt until a given statement, it works:

<img width="922" alt="image" src="https://github.com/user-attachments/assets/c7b75f8c-11e8-491b-9f01-e70125e74013">

**Comment by jlerbsc** [comment]
I cannot reproduce your issue with this unit test.

    void issue4508() {
        String code = "try {\r\n"
        		+ "    System.clearProperty(SLSTR_L1B_PIXEL_GEOCODING_INVERSE);\r\n"
        		+ "    System.clearProperty(SYSPROP_SNAP_PIXEL_CODING_FRACTION_ACCURACY);\r\n"
        		+ "    final String[] keys = AbstractProductFactory.getForwardAndInverseKeys_pixelCoding(SLSTR_L1B_PIXEL_GEOCODING_INVERSE);\r\n"
        		+ "    assertEquals(PixelForward.KEY, keys[0]);\r\n"
        		+ "    assertEquals(PixelQuadTreeInverse.KEY, keys[1]);\r\n"
        		+ "} finally {\r\n"
        		+ "    if (inverseKey != null) {\r\n"
        		+ "        System.setProperty(SLSTR_L1B_PIXEL_GEOCODING_INVERSE, inverseKey);\r\n"
        		+ "    }\r\n"
        		+ "    if (fractionalAccuracy != null) {\r\n"
        		+ "        System.setProperty(SYSPROP_SNAP_PIXEL_CODING_FRACTION_ACCURACY, fractionalAccuracy);\r\n"
        		+ "    }\r\n"
        		+ "}";

        final Statement stmt = StaticJavaParser.parseStatement(code);
        stmt.findAll(MethodCallExpr.class).forEach(st -> System.out.println(st.toString()));
    }

**Comment by jlerbsc** [comment]
This issue is closed because there is no longer any exchange and the issue cannot be reproduced.
