### ISSUE TITLE
Inspect current Windows compile problem

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#454]
It compiles fine on Windows, but not on our appveyor build tool.

**Comment by matozoid** [comment]
It's something with M2_HOME, @ftomassetti - do you feel like looking at it?

**Comment by ftomassetti** [comment]
There are 2 ways to fix this:
- fix the M2_HOME path
- stop installing our own Maven version

I went for option 1. There is one test failing but it seems legit

**Comment by matozoid** [comment]
Thanks!
