### ISSUE TITLE
ParseProblemException Switch expressions with constants throw error

### ISSUE THREAD

**Issue by hezhou66** [javaparser/javaparser#4552]
com.github.javaparser.ParseProblemException: (line 7,col 28) Parse error. Found ":", expected one of "enum" "exports" "module" "open" "opens" "permits" "provides" "record" "requires" "sealed" "strictfp" "to" "transitive" "uses" "when" "with" "yield"

**Comment by hezhou66** [comment]
@Test
issueTest() {
        JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser());
        parser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_21);
        String code = "class Inner{\n" +
                "\n" +
                " public static final String S = \"s\";\n" +
                "\n" +
                " public void switchTest(String s){\n" +
                " switch (s) {\n" +
                " case Inner.S:\n" +
                " System.out.println(\"s\");\n" +
                " break;\n" +
                " default:\n" +
                " System.out.println(\"default\");\n" +
                " break;\n" +
                " }\n" +
                " }\n" +
                " }";
        CompilationUnit cu = parser.parse(code);
    }

**Comment by jlerbsc** [comment]
@johannescoetzee do you have time to look into this problem?

**Comment by johannescoetzee** [comment]
This looks like a duplicate of https://github.com/javaparser/javaparser/issues/4455 which was fixed in https://github.com/javaparser/javaparser/pull/4458. I couldn't reproduce the error with the latest javaparser version 3.26.2 (technically with the current master branch, but they're equivalent at the moment). I modified the given testcase slightly to have it compile and to add some more thorough testing and this passes for me

```
    @Test
    void issue4552Test() {
        JavaParserAdapter parser = JavaParserAdapter.of(new JavaParser());
        parser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_21);
        String code = "class Inner{\n" +
                "    public static final String S = \"s\";\n" +
                "    public void switchTest(String s){\n" +
                "        switch (s) {\n" +
                "            case Inner.S:\n" +
                "                System.out.println(\"s\");\n" +
                "                break;\n" +
                "            default:\n" +
                "                System.out.println(\"default\");\n" +
                "                break;\n" +
                "        }\n" +
                "    }\n" +
                "}";
        CompilationUnit cu = parser.parse(code);
        SwitchStmt switchStmt = cu.findAll(SwitchStmt.class).get(0);

        assertEquals(2, switchStmt.getEntries().size());

        SwitchEntry entry = switchStmt.getEntry(0);
        assertEquals(1, entry.getLabels().size());

        Expression label = entry.getLabels().get(0);
        assertInstanceOf(FieldAccessExpr.class, label);

        FieldAccessExpr fieldAccess = label.asFieldAccessExpr();

        assertInstanceOf(NameExpr.class, fieldAccess.getScope());
        assertEquals("Inner", fieldAccess.getScope().asNameExpr().getNameAsString());

        assertEquals("S", fieldAccess.getNameAsString());
    }
```

@hezhou66 could you please test this again with javaparser version 3.26.2 and let me know whether this still fails for you?

**Comment by hezhou66** [comment]
@johannescoetzee   Thks，it runs fine with 3.26.2
