### ISSUE TITLE
After toAst()，error: Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration

### ISSUE THREAD

**Issue by newCheng** [javaparser/javaparser#4553]
Hi

I want to obtain the type of a member variable in a Java class and get the corresponding ClassOrInterfaceDeclaration object for that type, so I can analyze the member variables within it.But After I transform the resolvedReferenceTypeDeclaration to a Ast,and try to call resolve() method, an error happen.

`ClassOrInterfaceDeclaration classOrInterfaceDeclaration = Navigator.demandNodeOfGivenClass(cu, ClassOrInterfaceDeclaration.class);
        for (FieldDeclaration field : classOrInterfaceDeclaration.getFields()) {
            ResolvedReferenceType referenceType = field.getVariables().get(0).getType().resolve().asReferenceType();
            ResolvedReferenceTypeDeclaration resolvedReferenceTypeDeclaration = typeSolver.solveType(referenceType.getQualifiedName());
            Node node = resolvedReferenceTypeDeclaration.toAst().get();
            for (FieldDeclaration fieldDeclaration : node.findAll(FieldDeclaration.class)) {
                fieldDeclaration.getVariable(0).getType().resolve().asReferenceType().getQualifiedName();
            }
        }`

Exception in thread "main" java.lang.IllegalStateException: Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration
	at com.github.javaparser.ast.Node.lambda$getSymbolResolver$9(Node.java:826)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.github.javaparser.ast.Node.getSymbolResolver(Node.java:822)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:336)

**Comment by newCheng** [comment]
ClassOrInterfaceDeclaration classOrInterfaceDeclaration = Navigator.demandNodeOfGivenClass(cu, ClassOrInterfaceDeclaration.class);
        for (FieldDeclaration field : classOrInterfaceDeclaration.getFields()) {
            ResolvedReferenceType referenceType = field.getVariables().get(0).getType().resolve().asReferenceType();
            ResolvedReferenceTypeDeclaration resolvedReferenceTypeDeclaration = typeSolver.solveType(referenceType.getQualifiedName());
            Node node = resolvedReferenceTypeDeclaration.toAst().get();
            for (FieldDeclaration fieldDeclaration : node.findAll(FieldDeclaration.class)) {
                fieldDeclaration.getVariable(0).getType().resolve().asReferenceType().getQualifiedName();
            }
        }

**Comment by jlerbsc** [comment]
Can you provide us with a complete test case? Thank you.

**Comment by newCheng** [comment]
User.java:
```
package experiment.pojo;
public class User {
    private MobilePhone phone;
}
```
MobilePhone.java:
```
package experiment.pojo;
public class MobilePhone {

    private String area;

    private String number;

}
```
my java parser code:
```
public class Test1 {

    public static void main(String[] args) throws FileNotFoundException {
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("src/main/java"));
        TypeSolver typeSolver = new CombinedTypeSolver(
                javaParserTypeSolver,
                new ReflectionTypeSolver()
        );
        StaticJavaParser.getParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(new File("src/main/java/experiment/pojo/User.java"));
        ClassOrInterfaceDeclaration classOrInterfaceDeclaration = Navigator.demandNodeOfGivenClass(cu, ClassOrInterfaceDeclaration.class);
        for (FieldDeclaration field : classOrInterfaceDeclaration.getFields()) {
            ResolvedReferenceType referenceType = field.getVariables().get(0).getType().resolve().asReferenceType();
            ResolvedReferenceTypeDeclaration resolvedReferenceTypeDeclaration = typeSolver.solveType(referenceType.getQualifiedName());

            Node node = resolvedReferenceTypeDeclaration.toAst().get();
            for (FieldDeclaration fieldDeclaration : node.findAll(FieldDeclaration.class)) {
                System.out.println(fieldDeclaration.getVariable(0).getType().resolve().asReferenceType().getQualifiedName());
            }
        }
    }
}
```

error:
Exception in thread "main" java.lang.IllegalStateException: Symbol resolution not configured: to configure consider setting a SymbolResolver in the ParserConfiguration
	at com.github.javaparser.ast.Node.lambda$getSymbolResolver$9(Node.java:826)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.github.javaparser.ast.Node.getSymbolResolver(Node.java:822)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:336)

**Comment by jlerbsc** [comment]
Why don't you make use of the facilities offered to you by JP?

    for (FieldDeclaration field : classOrInterfaceDeclaration.getFields()) {
            ResolvedReferenceType referenceType = field.getVariables().get(0).getType().resolve().asReferenceType();
            ResolvedReferenceTypeDeclaration resolvedReferenceTypeDeclaration = **referenceType.getTypeDeclaration(**).get();

            for (ResolvedFieldDeclaration fieldDeclaration : resolvedReferenceTypeDeclaration.**getAllFields()**) {
                System.out.println(fieldDeclaration.getName());
            }
        }

**Comment by newCheng** [comment]
I want to get full name of field type.
I couldn't find the corresponding method call for ResolvedFieldDeclaration and  ResolvedReferenceTypeDeclaration.

**Comment by jlerbsc** [comment]
I think what you're looking for is fieldDeclaration.getType().describe()

**Comment by jlerbsc** [comment]
If we answered your question, you could close this exit.
