### ISSUE TITLE
How to get the parameter's  full class name?

### ISSUE THREAD

**Issue by shizhenchao** [javaparser/javaparser#4566]
-- class A:
```java
package com.demo;

public class A {
    public void b(B b) {

    }
}
```

--class B:
```java
package com.demo;

public class B {
}
```

---- main
```java
package com.demo;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.Parameter;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;

import java.io.File;
import java.io.FileNotFoundException;

import static com.github.javaparser.ParseStart.COMPILATION_UNIT;
import static com.github.javaparser.Providers.provider;

public class M1 {
    public static void main(String[] args) throws FileNotFoundException {
        new JavaParser().parse(COMPILATION_UNIT, provider(new File("src/main/java/com/demo/A.java"))).ifSuccessful(cu ->
                cu.accept(new VoidVisitorAdapter<Void>() {
                    @Override
                    public void visit(MethodDeclaration method, Void arg) {
                        for (Parameter parameter : method.getParameters()) {
                            System.out.println(parameter.getTypeAsString()); // B
                        }
                    }
                }, null)
        );


    }
}
```

The output is 'B', I want to get 'com.demo.B'

**Comment by jlerbsc** [comment]
To find out the type of parameter you need to use the symbol solver.

**Comment by shizhenchao** [comment]
How to use? think you

**Comment by jlerbsc** [comment]
There are many examples in the test cases and on the project https://github.com/javaparser/javasymbolsolver-maven-sample

**Comment by shizhenchao** [comment]
thank you very much!



---- Replied Message ----
| From | jean pierre ***@***.***> |
| Date | 09/28/2024 23:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [javaparser/javaparser] How to get the parameter's full class name? (Issue #4566) |

There are many examples in the test cases and on the project https://github.com/javaparser/javasymbolsolver-maven-sample

**Comment by shizhenchao** [comment]
only one case in this reposotory



---- Replied Message ----
| From | jean pierre ***@***.***> |
| Date | 09/28/2024 23:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [javaparser/javaparser] How to get the parameter's full class name? (Issue #4566) |

There are many examples in the test cases and on the project https://github.com/javaparser/javasymbolsolver-maven-sample

**Comment by jlerbsc** [comment]
> only one case in this reposotory
Yes, but that's enough to understand how to use the symbol solver and there are the unit tests for the symbol solver project to complete your understanding.

**Comment by shizhenchao** [comment]
I have successfully resolved the problem. Your assistance is greatly appreciated. The issue can now be closed.





---- Replied Message ----
| From | jean pierre ***@***.***> |
| Date | 09/29/2024 20:26 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [javaparser/javaparser] How to get the parameter's full class name? (Issue #4566) |

only one case in this reposotory
Yes, but that's enough to understand how to use the symbol solver and there are the unit tests for the symbol solver project to complete your understanding.

**Comment by jlerbsc** [comment]
For other people reading this issue, you could describe the solution to your problem in detail, or even add an extract of the code.
You can also close this issue if you have no more questions.

**Comment by GaoYizhuo2000** [comment]
Hi,
i'm Gao Yizhuo, a student from Australian National University and member of a 5-people IT group. We are very interested in this project and would like to make a contribution for this issue. We would appreciate it if i could be the assignee for this.
Best regards

**Comment by jlerbsc** [comment]
> Hi, i'm Gao Yizhuo, a student from Australian National University and member of a 5-people IT group. We are very interested in this project and would like to make a contribution for this issue. We would appreciate it if i could be the assignee for this. Best regards

Hi @GaoYizhuo2000 It's simply a question of how to use JP.
