### ISSUE TITLE
ArrayCreationExpr.arrayCount always stays 0

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#457]
Since we already have a list with all initializers, we can just as well delete this field.

See #237

**Comment by ptitjes** [comment]
You can have both dimension-expressions and dimensions in a ArrayCreationExpr (see JLS8 section 15.10.1).
For instance, `new int[10][10][][]` is a valid array creation expression.

**Comment by matozoid** [comment]
Yes, new int[10][10][][] would have arrayCount=2. I misunderstood this functionality.
