### ISSUE TITLE
MethodCallExpr: Class declared fields not finding requested field

### ISSUE THREAD

**Issue by Bl3nd** [javaparser/javaparser#4575]
Example: 

`class Constants { public static final String nl; }`

MethodCallExpr:
`someMethod(Constants.nl);`

This ends up calling the `ReflectionClassAdapter.hasField(String)` method, which the `.getDeclaredFields` assumes that static final fields are capitalized so it checks if `NL.equals(nl)`. Which from the example above, it is actually lowercase.

**Comment by jlerbsc** [comment]
Can you provide us a full unit test.

**Comment by Bl3nd** [comment]
Sorry for no response, I was trying to figure out a way that I could post a unit test, but I just fixed the issue. I changed `ReflectionTypeSolver(false)` to `ReflectionTypeSolver(true)`.
