### ISSUE TITLE
AST differencing

### ISSUE THREAD

**Issue by PlayeerOne** [javaparser/javaparser#4598]
Hi, I was wondering if there is a way to perform AST differencing using the JavaParser generated ASTs.

**Comment by jlerbsc** [comment]
Hi @PlayeerOne  Can you elaborate?

**Comment by PlayeerOne** [comment]
> Hi @PlayeerOne Can you elaborate?

Given two pieces of code where one is the result of the second subject to some changes. I would like to extract the tree difference between their ASTs, the changes that were applied on the first piece of code. Another feature I would be interested in, is mapping lines of code with the corresponding subtree, I am not sure if this is a feature that javaparser offers. Thank you for your time !

**Comment by jlerbsc** [comment]
No, JP doesn't have this type of feature, but you can try to come up with a solution!

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by PlayeerOne** [comment]
> No, JP doesn't have this type of feature, but you can try to come up with a solution!

I guess I have no choice but to do that

**Comment by jlerbsc** [comment]
I'm closing this issue because JP doesn't provide this type of feature and there are no plans to add it. You can add your comments if you want the community to benefit from your thoughts on this subject.
