### ISSUE TITLE
Variable declaration annotation ends up on wrong node

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#460]
In the case of a VariableDeclarationExpr, the first annotation ends up on the expr, not on the inner type:
`VariableDeclarationExpr(@C, type=ArrayType(@B, ArrayType(@A, PrimitiveType(no annotations, int))))`
should be
`VariableDeclarationExpr(no annotations, type=ArrayType(@B, ArrayType(@A, PrimitiveType(@C, int))))`

**Comment by ptitjes** [comment]
Well, this behaviour conforms to the standard. See in JLS8 section 14.4, the production `LocalVariableDeclaration` uses an `UnannType`.

**Comment by matozoid** [comment]
Thanks!
