### ISSUE TITLE
Fail on generic array creation

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#461]
JavaParser parses this:

new ArrayList<String>[2];

but it is not valid Java. [See here](http://stackoverflow.com/questions/7131652/generic-array-creation-error)

**Comment by matozoid** [comment]
Another one:

Object x=new <Object> @A ArrayList[2];

is also not valid Java, but JavaParser says it's okay.

Not sure why `[ typeArgs = TypeArguments() annotations = Annotations() ]` is in AllocationExpression

**Comment by ptitjes** [comment]
The JLS section 15.10.1 defines the grammar this way and says in the second paragraph after the grammar:

> It is a compile-time error if the ClassOrInterfaceType does not denote a reifiable
> type (§4.7). Otherwise, the ClassOrInterfaceType may name any named reference
> type, even an abstract class type (§8.1.1.1) or an interface type.

Thus `new @A List<?> @B []{}` is a valid expression.

**Comment by matozoid** [comment]
I love problems that are not problems after all.
