### ISSUE TITLE
Cannot support to calculateResolvedType the class `com.github.javaparser.ast.expr.MarkerAnnotationExpr`

### ISSUE THREAD

**Issue by RTxin** [javaparser/javaparser#4620]
### Case
```java
  @Nullable
  public Boolean foo() {
    return null; // Compliant
  }
```
### Uses
```java
n.getAnnotations().get(0).calculateResolvedType()
```
### Stack
```
java.lang.UnsupportedOperationException: com.github.javaparser.ast.expr.MarkerAnnotationExpr
com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:304)
com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:36)
com.github.javaparser.ast.expr.MarkerAnnotationExpr.accept(MarkerAnnotationExpr.java:69)
com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:533)
com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:394)
com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:359)
com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:443)
com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:578)
```

**Comment by jlerbsc** [comment]
Can you provide us a unit test.

**Comment by RTxin** [comment]
> Can you provide us a unit test.

    @Test
    public void issue4493() throws IOException {
        String classA_V1 =
                "import javax.annotation.Nullable;\n" +
                "// NullMarked at the package level\n" +
                "class BooleanMethodReturnCheckJSpecifySampleA {\n" +
                "\t@Nullable\n" +
                "\tpublic Boolean bar() {\n" +
                "\t\treturn null; // Compliant\n" +
                "\t}\n" +
                "\n" +
                "}";
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_18);
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver(false));
        parserConfiguration.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        parserConfiguration.setAttributeComments(true);

        final JavaParser javaParser = new JavaParser(parserConfiguration);

        final ParseResult<CompilationUnit> pc = javaParser.parse(classA_V1);
        if (pc.isSuccessful()) {
            pc.getResult().ifPresent(cu -> cu.accept(new VoidVisitorAdapter<Void>() {
                @Override
                public void visit(final MarkerAnnotationExpr n, Void arg) {
                    try {
                        n.calculateResolvedType();
                    } catch (Exception exception) {
                        exception.printStackTrace();
                    }
                }
            }, null));
        }
    }

**Comment by jlerbsc** [comment]
Thank you for the unit test. What exactly do you want to do? If you want to obtain the declaration of the annotation, you need to use the resolve() method. But you can't get the type of an annotation because an annotation is not considered to be a type.

**Comment by RTxin** [comment]
> Thank you for the unit test. What exactly do you want to do? If you want to obtain the declaration of the annotation, you need to use the resolve() method. But you can't get the type of an annotation because an annotation is not considered to be a type.

thanks for your answer!
