### ISSUE TITLE
Add getElementType to ArrayType

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#465]
This should find the type that is wrapped inside the ArrayType(s).

a= ArrayType(ArrayType(int))
a.getElementType() => int

**Comment by ptitjes** [comment]
The term used in the JLS is "component". So maybe "getComponentType()" ?
Or use "getComponentType()" to retrieve the immediate component type ?

**Comment by matozoid** [comment]
I was following the naming in 10.1. To be honest, I don't really see the difference with "component" so I may be confused.

**Comment by matozoid** [comment]
I've read it again: https://docs.oracle.com/javase/specs/jls/se7/html/jls-10.html

int[][] a;

The element type is int.
The component type depends: for a[] it is int[]. For a[][] it is int.

The component type is already available as getType()
The element type getter is what we want to add here.
