### ISSUE TITLE
Add getArrayDepth to ArrayType

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#466]
This should count the depth of ArrayType nesting.

a= ArrayType(ArrayType(int))
a.getArrayDepth() => 2
a.getType().getArrayDepth() => 1

**Comment by matozoid** [comment]
If anybody knows a better term than "depth"...?

**Comment by ptitjes** [comment]
Well, it seems to me that the exact term is "dimensions". Or you could also say "dimension count" if "dimensions" retrieves the dimension object.

However, I am not sure having such a method is useful ! You have to think about the bigger picture where you have type-checking, etc... and thus utilities to manipulate types, build default initializers...

**Comment by matozoid** [comment]
Well, it depends on what that bigger picture is. There are some big products like [Coati](https://www.coati.io/) using JavaParser, and I would expect they have a bunch of tools built around it, but I also see people building quick & dirty things. I don't see why we wouldn't spend an hour building this to save one or two users some frustration?

**Comment by matozoid** [comment]
This is very indirectly implemented by ArrayType.unwrapArrayTypes, since that returns a list of ArrayBracketPairs that you can as for its size.
