### ISSUE TITLE
Make an "architectural style guide"

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#478]
There are many patterns use throughout JavaParser, like how we use lists, how we do builder methods, how we see (im)mutability, etc.

**Comment by ftomassetti** [comment]
In general it would be nice to have a _contributing.md_ also

**Comment by matozoid** [comment]
Would it make sense to quickly take a contributing.md from another project?

**Comment by ftomassetti** [comment]
imho yes, that would make sense. Then we could do some simplifications

**Comment by matozoid** [comment]
I've looked at [an example](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) and it's HUGE. It made me wonder: what _are_ our guidelines? We don't have the amount of contributions that I'm annoyed with what people do here.)

Maybe...
- mention that we're volunteers and sometimes nobody is around to respond for weeks or months.
- that a PR is a more efficient way of getting things in JP than opening an issue
- maybe an overview of the labels on issues and PR's, although I'm really keeping those mostly for my own reference ;)
- that we like to see some kind of unit or bdd test for new functionality (although I myself sometimes violate this)
- a pointer to the style guide (or put the whole style guide in it)
- a pointer to the architecture guide we're supposed to be creating with this issue :)

**Comment by matozoid** [comment]
- a link that lists all the issues labeled "easy"

**Comment by matozoid** [comment]
- if people could please mention in the issue that they started work on it.

**Comment by ftomassetti** [comment]
I would keep much shorter than the one from Atom: because we are too lazy to write such a long document and because everyone is too lazy to read it :)

**Comment by rosrossito** [comment]
What is useful there for me as for newcomer for the first glance is that "contribution" is divided by parts and "Your First Code Contribution" even has levels. I think it significantly simplifies search appropriate task, you do not need to surf through all issues.

**Comment by matozoid** [comment]
Do you mean that there should be more sections in contributing.md? Or do you want a more extensive tagging of issues?

**Comment by rosrossito** [comment]
Ideally both: as description these sections in contributing.md as appropriate labels of issues.

**Comment by matozoid** [comment]
We now have issues tagged as "easy" that are meant to be picked up by people who want to try making a contribution, it is the first line in contributing.md. How would you like to see this improved?

**Comment by rosrossito** [comment]
Sure, "easy" tag helps. But I think it would be better to have here 2 sections: code contribution and other tasks, which not require contribution new code (like "reformat source code according to formatting rules"). But it's only my opinion, may be it is not so necessary. 
Also may be it would be useful to add link for contriduting.md on home page https://github.com/javaparser/javaparser/wiki.

**Comment by matozoid** [comment]
Yeah, I think that could be the tags "easy" and "general request" together. Maybe there should be an explanation of the issue labels somewhere?

Contributing.md itself could be organized a little better, but it's a start. Open issues if you think of more improvements.

Would you like to do that last one?

**Comment by rosrossito** [comment]
You mean to add label "general request" for some issues?
I can try.

2016-10-30 20:09 GMT+02:00 Danny van Bruggen notifications@github.com:

**Comment by matozoid** [comment]
No, the labels are okay, I'm saying that that combination seems to be what you want.

**Comment by rosrossito** [comment]
Yeah, that is what I said.

2016-11-05 14:46 GMT+02:00 Danny van Bruggen notifications@github.com:
