### ISSUE TITLE
Visitors visit ImportDeclaration.name even when it is empty

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#488]
ImportDeclaration.getName may throw an exception when the import declaration is empty. At least the Void and GenericVisitorAdapter don't take this into account and always visit it. This may lead to unexpected exceptions.

Some solutions I can think of:
1. fix the visitors
2. let an empty import declaration return null (or Optional.empty()) as the name
3. let an empty import declaration return "" as the name

I think 2 is the most "JavaParser-like" of the three.

**Comment by matozoid** [comment]
Actually, it feels like something is fundamentally strange here. ImportDeclaration really behaves like two classes: EmptyImportDeclaration with no state, and a normal ImportDeclaration. Keeping it as it is now means you can switch from empty to non-empty, which is nice. Giving it a pretty class hierarchy (BaseImportDeclaration, ImportDeclaration, EmptyImportDeclaration, or so) seems like a lot of overhead for something that is probably a typo (an empty import declaration.) Maybe we can reuse EmptyStmt in some way?

My worry: users may be rather surprised that an empty import is something they have to deal with explicitly. Receiving complaints that their product throws exceptions when somebody accidentally types a ; too much is probably not the way they want to find out.

@ftomassetti - you wrote it, what do you think?

**Comment by ftomassetti** [comment]
I think the EmptyImportDeclaration is something unfortunate that we probably need to have. However introducing it would require introducing the BaseImportDeclaration. I guess my thinking at the time was making the simplest thing. Right now going for the class hierarchy seems to me the best option.

**Comment by ftomassetti** [comment]
BTW the idea was to call `isEmptyImportDeclaration` before using `getName`, like when using an `Optional` you call `isPresent` before calling `get`.

**Comment by matozoid** [comment]
Alright, let's do the base class suggestion then.

**Comment by matozoid** [comment]
After reading through the JLS (7.5) I see no mention of allowing stray semicolons here, so it seems that parsers allow it for convenience.

I also saw this:

```
ImportDeclaration:
    SingleTypeImportDeclaration
    TypeImportOnDemandDeclaration
    SingleStaticImportDeclaration
    StaticImportOnDemandDeclaration
```

... so if we're going full out with the class hierarchy, why not create a class for each of these, and of course EmptyImportDeclaration?

Will do this unless someone stops me :)
