### ISSUE TITLE
Document how comments attribution work

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#49]
...and also how we would like it to work.

**Comment by ftomassetti** [comment]
Initial documentation available here:
https://github.com/matozoid/javaparser/wiki/CommentsParsing

It would be nice to refer to the Javadoc documentation of the classes involved with comments handling. Does github help with producing Javadoc documentation?

**Comment by ftomassetti** [comment]
I could add some tests to verify the parser works as written in the documentation.

Could someone take a look at the page and tell me if it makes sense?

**Comment by SmiddyPence** [comment]
Made a couple of typo corrections.  Also added a couple more scenarios we have seen around "atypical" comment usage.  

Test would be very useful, especially given that a lot is open to interpretation unlike the base grammar.  As someone coming in cold its very hard to know if it is that way by intention or that particular case was just not considered.

**Comment by ftomassetti** [comment]
Thank you!
Hey, the first atypical example is awful, we should fix that!

In the next days I will write those tests.

**Comment by SmiddyPence** [comment]
I was thinking about it more and it is actually very difficult to do, because it is open to all kinds of interpretation.

``` java
// b is cool.
int b; 
```

That makes sense that it is attributed to the field b to both a human and parser.  However:

``` java
// Here be dragons
int b = 0;
int c = b;
// Here finisheth the dragons 
return c;
```

Here the comments have been use to describe a number of statements, which is obvious to a human; but not a parser.  

I wonder if it is trying to do too much? Perhaps a more broader brush could be easier to implement and still be useful to people? 

As before classes and methods could commentable, with a single comment by proximity.  Then other comments are just the "contained by" a method or a class and the api practitioner can use line number etc to work out what they are relevant for.

Or perhaps different modes different modes of parsing, one like now where is tries to go to the finest level of detail; where it is bias on developer interpretation - or the more broader approach is just a different implementation of the comment parser.

**Comment by ftomassetti** [comment]
I agree there will be cases in which we cannot obtain the ideal results, we can just relay on good practices and conventions. In the case of "Here be dragons" I would expect a blank line between the comment and variable, we could use it to understand the comment is not directly related to the variable (we do not that at the moment).

I think we have different users interested in different things:
1) Many could simply not care about comments, that is why comments parsing should be optional or there should be the possibility to disable it (I do not remember what is the case, I will check)
2) Others could want could want to know which comments are present in a file, without knowing how they are attributed
3) Others could want some comments attribution (something like, the comments attributed to class and methods and anything else)
4) Finally, some could be interested in comments attribution at the finer levels

We do provide a method to collect all the comments which are contained in a node and its children (Node.getAllContainedComments). Calling this method on CompilationUnit gives all the comments in the source file (case 2 covered).

For case 3 the user could call for each method getComment (to get the comment attributed to the method) and getAllContainedComments (to get all the comments inside the method, without looking at the way we attributed them to the various statements).

For case 4 the user could use the more granular getComment and getOrphanComments.

I think we need some refinements to the comments attribution algorithm and definitely we need more documentation (imho we need also Javadoc, see issue #51). We should ensure that comments attribution works well when reasonable conventions are adopted, and make clear that it really depends on those conventions, and every violations lead to possible problems to comments attribution. 

So said we could have different strategies for comments attribution (or a configurable one), with variants which try to attribute comments more aggressively and others which go just for safe bets, leaving all the other comments as orphan (i.e., not attributed to any element). I think in this way we could cover most of the possible usages of JavaParser. From that we can correct listening to other users needs?

Hopefully I could work on this stuff in the week-end if you think it makes sense, I would build upon the pending merge request. I would do another merge request or update the existing one and leave it pending for a week or so to give the possibility to you matozoid or whoever want to comment on it. Do you think it could work?

**Comment by SmiddyPence** [comment]
Ok, sounds sensible.  

The tests/docs are the important part to me, as it's key the interpretation of the attribution rules.

**Comment by ftomassetti** [comment]
Ok, I would describe the different levels at which comments can be used (as in my previous comment) but I would do that after we have Javadoc (#51), so I can refer to them.

**Comment by ftomassetti** [comment]
Done, see https://github.com/matozoid/javaparser/wiki/Comments:-which-support-do-we-have-in-JavaParser%3F

Native speakers such as @SmiddyPence willing to correct my grammar mistakes are welcome :D

**Comment by SmiddyPence** [comment]
Done, made a few minor changes.

**Comment by ftomassetti** [comment]
Thanks, I appreciate that

On Mon, Aug 25, 2014 at 10:35 AM, Nicholas Smith notifications@github.com
wrote:

> Done, made a few minor changes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matozoid/javaparser/issues/49#issuecomment-53245015.

## 

Website at http://www.federico-tomassetti.it
Indirizzo PEC federico.tomassetti@ording.eu
