### ISSUE TITLE
Is there is a way to obtain method calls inside a method?

### ISSUE THREAD

**Issue by moar82** [javaparser/javaparser#490]
Let's suppose I have the following method, and I want to detect all callings to method ToString().
Here inside assertEquals method called, there is one call to ToString.  Is there is a way to obtain all method calls to ToString() method?

`
public void testTagDefinitions() {
    Facade facade = Model.getFacade();//
    Object td = Model.getExtensionMechanismsFactory().buildTagDefinition("testTD", stereotype, null, "String");
      assertEquals("1..3", facade.toString(facade.getMultiplicity(td)));
}
`

**Comment by matozoid** [comment]
Yes there is. What version of JavaParser are you using?

**Comment by moar82** [comment]
Hi,
the version is javaparser-core-3.0.1-alpha.3-SNAPSHOT

and according to git, the tag is:
javaparser-parent-3.0.0-alpha.3-4-g5894380

**Comment by matozoid** [comment]
I took out the "//" because it made the sample invalid.

``` java
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import org.junit.Test;

public class ObtainMethodCalssInsideMethod {
    @Test
    public void test() {
        CompilationUnit cu = JavaParser.parse("class X{ public void testTagDefinitions() { Facade facade = Model.getFacade(); Object td = Model.getExtensionMechanismsFactory().buildTagDefinition(\"testTD\", stereotype, null, \"String\"); assertEquals(\"1..3\", facade.toString(facade.getMultiplicity(td))); }}");

        ClassOrInterfaceDeclaration classX = cu.getClassByName("X");

        for (MethodDeclaration method : classX.getMethods()) {
            // Make the visitor go through everything inside the method.
            method.accept(new MethodCallVisitor(), null);
        }
    }
}

class MethodCallVisitor extends VoidVisitorAdapter<Void> {
    @Override
    public void visit(MethodCallExpr n, Void arg) {
        // Found a method call
        System.out.println(n.getScope() + " - " + n.getName());
        // Don't forget to call super, it may find more method calls inside the arguments of this method call, for example.
        super.visit(n, arg);
    }
}
```

**Comment by moar82** [comment]
Hi Danny,
I run the code, but I noticed that it does not give me the the type of the
arguments (e.g., n.getTypeArguments()=null)
In my case I would like to know which type of parameters is called
assertEquals?

Do you have any idea.

Thank you,

Kind regards,

Rodrigo.

**Comment by matozoid** [comment]
The arguments to the methods are in getArgs(). Note that JavaParser is only a parser. It takes the source code and makes a nice tree. It does not in which package "Facade" is, or that "facade" is of type "Facade", or that toString is a method on class Object. It sees only strings. If you're looking for that information, you need an additional library like java-symbol-solver.

**Comment by matozoid** [comment]
If any more help is needed you can reopen this issue or start a new one.
