### ISSUE TITLE
Redo NodeList

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#504]
Something like `getParentNode`.

If the parent is a Node it would return the result of getParent, otherwise it would return getParent.getParentNode().

**Comment by matozoid** [comment]
Hmmm... I can see the use, but we need another name since a NodeList is... a Node :)

**Comment by DeepSnowNeeL** [comment]
getEnclosingNode ?

**Comment by matozoid** [comment]
Well, "Node" is the problem word.

`getNonListParentNode` is ugly :)

**Comment by matozoid** [comment]
If you think the introduction of NodeList was a mistake, that would be good feedback too 😊

**Comment by DeepSnowNeeL** [comment]
Well if it interefere with getParent it will be annoying, i'll migrate soon
my code to the last alpha and let you know if it's really a pain to upgrade
and what feel annoying :)

**Comment by ftomassetti** [comment]
I think that NodeList is useful but maybe it could not be a node.

Unfortunately I did not follow all the discussions (shame on me) but for me NodeList is not a Node, it is a container of nodes.

We could take EMF as an example (EMF: the meta-modelling framework used in several products including [Xtext](http://xtext.org)): a node is always contained in a containment reference (which could be a List or thing with just one element). The containmente reference would be ~ our NodeList.

Maybe we could have:

```
interface NodeContainer { 
   NodeContainer getContainer();
   Node getContainingNode(); // as getContainer but skips NodeLists
}

// alternatively only some nodes could be NodesContainer and we could exclude 
// the nodes which cannot have children
class Node implements NodeContainer {}

class NodeList implements NodeContainer {}
```

Would this make sense? We would have still NodeList as part of the hierarchy (necessary to make easy insertions and deletions) but for certain usages we could easily skip it.

**Comment by matozoid** [comment]
_crunch_ _crunch_ that seems to make sense. So NodeList is no longer a parent to its children. NodeList will simply set the parent to its own parent. Uhuh, this could work. Also: I don't have to undo a few days of work, so that makes me happy ;)

**Comment by matozoid** [comment]
And: it immediately solves the problem of having two lists with more or less the same content in NodeList.

**Comment by ftomassetti** [comment]
Do you want me to send a PR for this or do you prefer to do it yourself?

**Comment by DeepSnowNeeL** [comment]
Take a look at w3c dom elements & nodes on the standard java libs to see
how they did it, it uses a NodeList when you do getChildNodes() (btw, it
doesn't implements iterable and is awful to use :p)

**Comment by matozoid** [comment]
A PR would be nice!

**Comment by ftomassetti** [comment]
Also, when asking the children, I do not want to get as children the NodeLists, I want the real nodes

**Comment by matozoid** [comment]
Okay, but this is not because "that's how it used to be" but for some reason?

There's a method for this that I kept for backwards compatability. Check it out.

**Comment by matozoid** [comment]
@ftomassetti - would you like to pick this up? You seem to have a clear image of what to do.

**Comment by ftomassetti** [comment]
I gave it a try but this is more complicated than I thought

**Comment by matozoid** [comment]
Here's what's in my mind:
- NodeList should not be a Node (it will never end up in in a list of childrenNodes)
- NodeList should have a parent (this is a common interface with Node, maybe that NodeContainer you mentioned)
- NodeList will set the parent of all of its children to its own parent (so it is never the parent of the children it contains)

So basically, make a specialized List that sets the parent of all the children it contains.

How does that match with what you're doing?

**Comment by matozoid** [comment]
Working on this...
