### ISSUE TITLE
Generating Javadoc documentation

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#51]
We could generate the Javadoc documentation and provide it as github pages.

I think it is technically possible but it would require maven skills far superior to mine. Volunteers are really welcome :D

**Comment by SmiddyPence** [comment]
I have seen a maven site plugin that works well to for that, but I haven't seen one that does JavaDoc.

I'll have a look, but worse case.  Generating the JavaDoc and pushing to a branch isn't to laborious

**Comment by ftomassetti** [comment]
I generated them manually, they are now available at http://matozoid.github.io/javaparser/javadoc-current/
so later we could store the javadoc of release version in other directories.
