### ISSUE TITLE
Synchronization to javaparser.org

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#510]
Figure out how we (should) synchronize to javaparser.org. If we already do, it isn't working. If we don't, we should build it.

**Comment by DeepSnowNeeL** [comment]
There is a few way I can think of :
- Travis (but can we hide the ftp password from the config file in any way ?)
- A personnal jenkins who watch the git repo & auto upload when it detects changes. 
- A simple git hook to do the job ?
- Use github pages and redirect javaparser.org to github pages ?

Suggest other solutions so we can choose one :)

**Comment by matozoid** [comment]
@SmiddyPence - from the git log I gather that you've kept the site up to date. Did you automate it, or is it all hand made?

**Comment by matozoid** [comment]
I was informed that there is a button in our github settings that we can hit to update javaparser.org.
