### ISSUE TITLE
List JavaSymbolSolver in the Readme as a related project

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#512]
We have other projects listed. Now that JavaSymbolSolver is part of the same organization it could make sense to list it also.

**Comment by matozoid** [comment]
Oh, I thought this was a PR! :)

**Comment by ptitjes** [comment]
Ohh! JavaSymbolSolver is now part of the JavaParser organization !!??

**Comment by matozoid** [comment]
Yes, there is a lot of activity on symbol solver lately, and I'd say it is quickly going from @ftomassetti's toy project to a high quality project!

**Comment by ftomassetti** [comment]
to do that I am going to need a _LOT_ of help. The people from Coati started using and it motivated me to do some improvements (basically hacking support for Java 8 type inference).
The code quality is poor in some places and I hope to improve it over time with all the help I can get
