### ISSUE TITLE
Create handy setters for optionals

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#515]
instead of using `ObjectCreationExpr setAnonymousClassBody(final Optional<NodeList<BodyDeclaration<?>>> anonymousClassBody)`

I would rather use a setter which uses : Optional.ofNullable(arg) because most of the case I use set to set an actual value, and null would be handled and produce an empty optional.

This is to do for every Optional field with a setter method

**Comment by ptitjes** [comment]
Just a note to point out that `Optional` is supposed to be used for method return value only.

From the Javadoc of Optional:
« This is a value-based class; use of identity-sensitive operations (including reference equality (==), identity hash code, or synchronization) on instances of Optional may have unpredictable results and should be avoided. »

Indeed, there was lengthy discussions about the real value of `Optional` compared to some alternatives like Scala's `Option`.
http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html
https://dzone.com/articles/optional-java-8-cheat-sheet

`Optional` is not supposed to be taken as argument but was meant, says the documentation, as a container for optional return values. Indeed, that is the reason an `Option` exists in [JLaTo](http://jlato.org)

**Comment by DeepSnowNeeL** [comment]
To my understanding that means that we shouldn't have fields with Optional
but just use it in the getter to wrap the null value..
Argh can you feel the refactor coming... :P

**Comment by ptitjes** [comment]
Yep, you read that well... `Optional` is supposed to be used in return statements to do some `Optional.whateverOrNull(xxx)`...

As for the refactoring, you can use [JLaTo](http://jlato.org/)! That would be a couple of `cu.forAll(...)` :)
Feedback welcome!

**Comment by matozoid** [comment]
If we go that way, we need to answer these questions:
- what will a setter look like? No Optional?
- if so, do we want a getter to return an optional when a setter doesn't set an optional? This is not consistent.
- how will we indicate which values can be set to null if there is no optional there?

**Comment by DeepSnowNeeL** [comment]
- what will a setter look like? No Optional?

To me, yes and we handle internal nulls but expose optionals on getters
- if so, do we want a getter to return an optional when a setter doesn't set an optional? This is not consistent.

Looks like it's Optional intended use 
- how will we indicate which values can be set to null if there is no optional there?

We protect them with Objects.requireNonNull or equivalent for those who is forbidden to be null (+javadoc)

Others are just ok with set(null) since get() will return the correct optional

**Comment by matozoid** [comment]
After reading around a little...
http://stackoverflow.com/questions/26327957/should-java-8-getters-return-optional-type/26328555#26328555
It looks to me like the creators think of Optional as a funny little plaything that could help in some situations. For JavaParser that would mean unbalancing getters and setters, which I find ugly and confusing. That would make me want to abandon them and use @NotNull annotations instead.
On the other hand, the suggested usage is just that, and we can ignore it. The problem with the annotations is that there are many different versions of them, and the JSR to standardize them has been abandoned.

Who has more thoughts on this?

@DeepSnowNeeL - your last point: asserts work on runtime, Optional moves checking to compile time, just like annotations.

**Comment by matozoid** [comment]
Additionally this: http://blog.joda.org/2014/11/optional-in-java-se-8.html which says "Please focus on using it as a return type (from methods that perform some useful piece of functionality) Please don't use it as the field of a Java-Bean."

Maybe in the future Optional will be suitable for this, but not now. I'll make an issue to roll back the Optional change.

**Comment by matozoid** [comment]
This looks like the discussion to end all discussions, for those interested: http://blog.codefx.org/java/dev/design-optional/
