### ISSUE TITLE
Update wiki documentation for 3.0

### ISSUE THREAD

**Issue by ducmle** [javaparser/javaparser#518]
Hi, 

I've just downloaded the latest version from the site, compiled it using mavern (as instructed) and successfully run the first 2 examples on the manual page (i.e. CuPrinter andMethodPrinter).

However, the third example (MethodChanger) failed to compile because no ASTHelper is found.
I checked in the source code tree and also could not find it.

What do i get this file?

Thanks very much

**Comment by ftomassetti** [comment]
The changelog for version 3.0.0-alpha.1 says:

> 409 remove ASTHelper (methods are now on specific Node subclasses)

I guess we should update the manual.

**Comment by ducmle** [comment]
Hi, 

After some trial-and-error, I've just managed to fix the two method-changer examples in your manual. See the attached files (the old codes are commented out).

Hope this helps other beginners!
[method-changer-examples.zip](https://github.com/javaparser/javaparser/files/552639/method-changer-examples.zip)

**Comment by ducmle** [comment]
...And here is the updated ClassCreator example.
(I'm not sure if the last part that adds the method call "System.out.println" is written using the correct style, although the output looks correct - please confirm!)

[ClassCreator.java.txt](https://github.com/javaparser/javaparser/files/552660/ClassCreator.java.txt)

Output: 

package java.parser.test;

public class GeneratedClass {

```
public static void main(String... args) {
    System.out.println("Hello World!");
}
```

}

**Comment by matozoid** [comment]
Thanks for the report! The documentation is for 2.5.1, which is the official release. The alpha's are just snapshots for those interested. When we're done with 3.0, we will update the documentation (but thanks for the reminder, we need an issue for that.)

The wiki samples are part of the test suite, you can find them here: https://github.com/javaparser/javaparser/tree/master/javaparser-testing/src/test/java/com/github/javaparser/junit/wiki_samples
