### ISSUE TITLE
AssignExpr target could be any expr?

### ISSUE THREAD

**Issue by danwyryunq** [javaparser/javaparser#519]
More or less, the subject is the question, but shouldn't the target property in AssignExpr be of type NameExpr instead of just Expression? As far as I know, it couldn't be anything else.

**Comment by matozoid** [comment]
That's a duplicate of our oldest open issue :) #109

**Comment by matozoid** [comment]
@danwyryunq if you think this answer is sufficient, can you close this issue?

**Comment by danwyryunq** [comment]
yes, sorry, and thanks
