### ISSUE TITLE
Make shortcuts for list.get(i)

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#524]
So many `getTypes().get(0)` in the tests. Why not have helper methods for every list: `getType(int i) { return getTypes().get(i); }`

(this needs the equivalent setType(i, ...) too)

**Comment by qnnguyen** [comment]
Is this something I can work on?

Was thinking I'd add a shortcut to all the interfaces with a NodeList-returning getter.

**Comment by DeepSnowNeeL** [comment]
Please implement the list interface, I hated so much working with w3c.nodelist because it isn't standard (https://docs.oracle.com/javase/7/docs/api/org/w3c/dom/NodeList.html)
I would rather use getTypes().get(0) cause I know how it works so don't forget to say it in the javadoc that this is only a helper to getTypes().get(0) and that it can throws IOOB exceptions

**Comment by matozoid** [comment]
@DeepSnowNeeL agreed, but that's another issue. I'll create it: #550
@qnnguyen that's great, but you'll probably miss a few lists that are not in interfaces, so be careful.

**Comment by matozoid** [comment]
We still need the setters.

**Comment by matozoid** [comment]
@tiaped - you could pick this one up?

**Comment by tiaped** [comment]
Yes I can.
I will probably start next week.

**Comment by matozoid** [comment]
Cool, no hurry.

**Comment by tiaped** [comment]
Hi, I started today in fact.
I think of starting from #558.
Everywhere where a T getXXX(int i) was added, I'll add a void setXXX(int i, T element).
If it seems right, would you like also a void addXXX(T element)?

**Comment by matozoid** [comment]
Not sure, because if we continue adding methods we might as well copy the whole List interface for every list. You choose if you want set(i, element) or not. I don't think it's a very common thing to do after all.

addXXX: there are already quite a few of these methods. Good plan!

**Comment by matozoid** [comment]
Forgot to mention: all of our setters return "this"

**Comment by tiaped** [comment]
Hi, sorry if I missed something.
As the issue is still open, I might have forgot to do something?

Pierre

**Comment by matozoid** [comment]
I think I forgot to close it - can you check if it is mentioned in the changelog? https://github.com/javaparser/javaparser/pull/732

**Comment by tiaped** [comment]
I believe it is : 
 matozoid referenced this pull request 8 minutes ago
Closed
Make shortcuts for list.get(i) #524

**Comment by matozoid** [comment]
I mean https://github.com/matozoid/javaparser/blob/62f16963a46c3eaa3557589019e189395e191ae9/changelog.md

I see it is in RC.4, I'll label it.
