### ISSUE TITLE
A couple of issues about manual statement insertion into method body

### ISSUE THREAD

**Issue by ducmle** [javaparser/javaparser#534]
Hi, 

When manually setting a method's body using this API method BlockStmt.addStatement(String) then the generated code of the method has two issues: 
(1) an extra semi-colon (;) is added as the last character of the last statement in the input, which causes compilation error in some cases
(2) if the input contains multiple code statements separated by the next-line char ('\n'), then only the first line is properly aligned, other lines are generated without identation.

Note for issue (1) that removing the semi-colon at the end of the input statement is not an option because the the code may come from another source that contains an arbitrary number of lines.

My JavaParser version: 3.0.1-alpha.6.

Below is an example code and the generated output. The comments in the code help explain the problems.

```
public class ManualMethodBody {
  public static void main(String[] args) {
    CompilationUnit codeUnit = JavaParser.parse("class Test {}");
    
    ClassOrInterfaceDeclaration testCls = codeUnit.getClassByName("Test");
    
    MethodDeclaration method = testCls.addMethod("greeting", Modifier.PUBLIC);
    BlockStmt body = method.createBody();
    // an extra ';' is added to end of first and third statement, but not to the second
    // '\n' char causes the third statement to be misaligned!
    body.addStatement("System.out.println(\"hello\");");
    body.addStatement("System.out.print(\"world\");\n System.out.println(\"...\");");

    System.out.println(testCls);
  }
}
```

Output:

```
class Test {

    public void greeting() {
        System.out.println("hello");;
        System.out.print("world");
 System.out.println("...");;
    }
}
```

Thanks for your help.

**Comment by matozoid** [comment]
Thanks for the clear report!

addStatement is supposed to add only a single statement, and as you found out it does not want a semicolon. Here's a an approach that will avoid that: we parse the statements before adding them.

``` java
public class ManualMethodBody {
    public static void main(String[] args) {
        CompilationUnit codeUnit = JavaParser.parse("class Test {}");

        ClassOrInterfaceDeclaration testCls = codeUnit.getClassByName("Test");

        MethodDeclaration method = testCls.addMethod("greeting", Modifier.PUBLIC);
        BlockStmt body = method.createBody();

        // a ; is expected by the parser at the end of a statement. 
        Statement statement = JavaParser.parseStatement("System.out.println(\"hello\");");
        body.addStatement(statement);

        // parse several statements and add them in a loop - just need to put { and } around them.
        BlockStmt blockStmt = JavaParser.parseBlock("{System.out.print(\"world\");\n System.out.println(\"...\");}");

        blockStmt.getStmts().forEach(body::addStatement);

        System.out.println(testCls);
    }
}
```

I'll add a new issue that makes adding all statements from a BlockStmt easier.

If this answer is sufficient, could you close this issue?

**Comment by DeepSnowNeeL** [comment]
Now that I see that, I think addStatement(String) should probably use parseStatement inside instead of NameExpr

**Comment by ducmle** [comment]
Yes it worked. Thank you very much. 

And i agree that if you could add this as a method in BlockStmt class then it would be great. 
If you do then in my opinion you should still keep the method addStatement(String) as it is and instead introduce a new method like addStatement(BlockStmt).

Thanks.
