### ISSUE TITLE
Make adding all statements from a BlockStmt to a NodeWithStatements easier.

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#535]
Put a method on NodeWithStatements that takes all statements from a NodeWithStatements or a NodeList<Statement> and adds them to another NodeWithStatements. This can call addStatement internally.

Use case: #534

**Comment by DeepSnowNeeL** [comment]
Will do it in my PR

**Comment by matozoid** [comment]
@DeepSnowNeeL I guess this should have been closed?

**Comment by DeepSnowNeeL** [comment]
Oh yeah that was done ages ago :P

**Comment by matozoid** [comment]
Then it is probably in 3.0.0 :)
