### ISSUE TITLE
Request for features

### ISSUE THREAD

**Issue by ducmle** [javaparser/javaparser#537]
Hi, 

In the process of using JavaParser for a couple of recent projects, i've encountered a number of recurring code patterns that i thought would be nice to have incorporated into the existing API. 

I briefly describe these patterns below. A code example is given for one of the patterns. 

1/ Node.toStrucString(): String
to print out the tree structure of the AST's subtree rooted at a given node
- this method is useful to learn the tree structure of a node to see what it has and determine how to best process it

2/ Node.getTopLevelChildrenNodes(Class<N> type): List<N extends Node>
(a variant of getChildrenNodes) to return the immediate (top-level) children nodes of a given node that are of a particular type
- this method is useful to carry out a recursive processing of a node in stages (first perform on the top-level children, then on those of these children, and so on)
- idea: one can achieve the above by using getNodesByType() and then filter out only the Nodes that satisify Node.getParentNode().getParentNode() = currentNode

3/ MethodDeclaration.getIdentifierNodesInBody(IdentifierType type): List<Node>
to return the Nodes that represent identifiers in the body statements of a method that are of a certain type; where identifier type (enum) = {Variable, MethodCall, [...]}.
e.g. 
given method declaration md = 
  void test() {
    int x=0;
    int y = ++x;
    Toolkit.test2(x,y);
     System.out.println("done");
  }

then:
md.getIdentifierNodesInBody(IdentifierType.Variable) = [ Node("x"), Node("y") ]
md.getIdentifierNodesInBody(IdentifierType.MethodCall) = [ Node("test2"), Node("println") ]

- this method is useful for method's code analysis and rewriting

Thanks.

**Comment by matozoid** [comment]
Thank you for the suggestions!

**Comment by ftomassetti** [comment]
It could make sense to split this in 3 issues

**Comment by ftomassetti** [comment]
Thank you @ducmle it is always nice to get feedback!

**Comment by matozoid** [comment]
I split this up into separate issues. Please check.

**Comment by ducmle** [comment]
Thank you for a prompt response. I have just checked and contributed a comment to #538.

**Comment by matozoid** [comment]
Since this was split up I'll close this one.
