### ISSUE TITLE
Lazy initialized lists should be used everywhere

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#54]
We did that for comments in issue #3 but it applies everywhere.

I could do that in this way, if you agree:

``` java
    public List<Parameter> getParameters() {
        if (null == parameters) {
            parameters = new ArrayList<Parameter>();
        }
        return parameters;
    }
```

Thoughts?

**Comment by sebastiankirsch** [comment]
Why not adapt all the setters/constructors and set either the specified non-null value or `Collections.emptyList()`? This simplifies the getter code and is probably faster & more memory-efficient then anything else.

The only downside is that the lists cannot be modified, but, alas, one needs to set your own list in such cases.

**Comment by ftomassetti** [comment]
It makes sense: after all you are not supposed to edit the list (as you said).

I can do this change over the week-end if everyone agrees.

**Comment by ftomassetti** [comment]
Just to be sure, before doing the same change on a ton of classes, would that work for you?

``` java
private List<AnnotationExpr> annotations = Collections.emptyList();

public List<AnnotationExpr> getAnnotations() {
    return annotations;
}

public void setAnnotations(List<AnnotationExpr> annotations) {
    if (null == annotations) {
        throw new NullPointerException();
    }
    this.annotations = annotations;
    setAsParentNodeOf(this.annotations);
}
```

**Comment by sebastiankirsch** [comment]
Looking at the ASTParser line 3353 I'd assume that you cannot throw a NPE,
but should fall back to the empty list as well. Which is much more
user-friendly as well. Apart from that, looks great!

Federico Tomassetti notifications@github.com schrieb am Wed Feb 18 2015
at 4:40:21 PM:

**Comment by ftomassetti** [comment]
Ok, let's do that for the sake of compatibility, maybe I would add a note to specify that in the future that could be changed

**Comment by ptitjes** [comment]
It seems to me this deals with the same problems that PR #106 tries to fix. Do you @javaparser/owners think that we must take a definitive decision about this for 2.1 ?

**Comment by ftomassetti** [comment]
Given this is swamped for the moment I will prepare another pull requests with the bug fixes present in this pull request. They should be less controversial

**Comment by ftomassetti** [comment]
I think we have done this in the end, closing

**Comment by JinyongPark** [comment]
without Maven, how i use your source? i use eclipse with Dynamic Web Project

**Comment by ftomassetti** [comment]
please @JinyongPark do not ask questions unrelated this issue here. If you have questions open a new issue. Thank you!
