### ISSUE TITLE
Feature to return nodes that represent identifiers...

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#540]
(Taken from #537)

`MethodDeclaration.getIdentifierNodesInBody(IdentifierType type): List<Node>`
to return the Nodes that represent identifiers in the body statements of a method that are of a certain type; where identifier type (enum) = {Variable, MethodCall, [...]}.
e.g. 
given method declaration md = 
  void test() {
    int x=0;
    int y = ++x;
    Toolkit.test2(x,y);
     System.out.println("done");
  }

then:
md.getIdentifierNodesInBody(IdentifierType.Variable) = [ Node("x"), Node("y") ]
md.getIdentifierNodesInBody(IdentifierType.MethodCall) = [ Node("test2"), Node("println") ]

- this method is useful for method's code analysis and rewriting

**Comment by DeepSnowNeeL** [comment]
To me this is easy to do with a visitor and don't really need its own
feature

Le lun. 7 nov. 2016 à 11:40, Danny van Bruggen notifications@github.com a
écrit :

**Comment by ducmle** [comment]
i was thinking may be it would improve productivity if this was defined as a single method, instead of having to write the same visitor each time. 

May be if it is not suitable to go into MethodDeclaration, you could put it in some TookKit class?

**Comment by ducmle** [comment]
sorry i meant Toolkit class.

**Comment by matozoid** [comment]
I was thinking it might be interesting to have a contrib module separate from the core module...

**Comment by matozoid** [comment]
I think this has become really simple because we have `Name` and `SimpleName` now, and a `GenericListVisitorAdapter` which can collect results while visiting. Maybe this could be part of the documentation.

**Comment by matozoid** [comment]
Agreeing with @DeepSnowNeeL that this is really basic visitor usage.
