### ISSUE TITLE
PrettyPrinter: optional spaces around operators

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#545]
1 + 1
vs
1+1

**Comment by matozoid** [comment]
If I look at Intellij's formatter, the complete list is...
- =, +=, ...
- &&, ||
- ==, !=, <, >, <=, >=
- &, ^, |
- +, -, *, /, %
- <<, >>, >>>
- ->

**Comment by matozoid** [comment]
@DeepSnowNeeL @ftomassetti I'm wondering how detailed I should make these settings. Just one "spaces around operators" boolean, or booleans for "space before" and "space after" for each kind of operator, or somewhere between?

I haven't seen any requests for this feature, so I'm thinking of the simplest setting...

**Comment by ftomassetti** [comment]
Mmm I should always go for spacing around operators, but no spaces could be potentially something used.

**Comment by Mathiponds** [comment]
Is this issue still available ?

**Comment by matozoid** [comment]
Yes it is, consider yourself assigned :-)

**Comment by hmellin97** [comment]
@matozoid is it the class PrettyPrintVisitor.java that dictates how PrettyPrint should print different things?

**Comment by matozoid** [comment]
Here's a little article about printing: https://javaparser.org/making-strings-in-javaparser/

`PrettyPrinter` is a friendly frontend for pretty printing, that uses...
`PrettyPrintVisitor` for the actual printing, and
'PrettyPrinterConfiguration' for configuring the visitor.

`toString` simply uses the visitor.

You can look at the unit tests to see how it fits together, and you can experiment with it like a user to get an idea.
