### ISSUE TITLE
Rename UserData back to Data

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#551]
Since we have plans to use this field from within the project, it's no longer "user only."

**Comment by fofiedelly** [comment]
@matozoid  cannot find any occurence of UserData in this project! 
As the issue already been closed ? 
I'm a newbie in the Opensource world!

**Comment by ftomassetti** [comment]
See class `Node`, methods `getUserData` and `setUserData`

**Comment by fofiedelly** [comment]
Am i suppose tho change all occurences of "UserData" to "Data" ? is it case sensitive ? 
Since i can see var names like userData in those methods!

**Comment by matozoid** [comment]
It is all case sensitive, but it's just like general Java coding. Do you know the Java coding guidelines?
