### ISSUE TITLE
Support module-info.java files.

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#554]
These files contain a new mini-language.

**Comment by gunnarmorling** [comment]
Has work on this began already?

**Comment by matozoid** [comment]
We're waiting for the specification to stabilize - has that happened?

**Comment by gunnarmorling** [comment]
It's not finalized yet (in Early Draft state currently).

But I think module-info.java syntax is fairly stable by now. Smaller
adjustments may be done down the road, but I wouldn't expect any
fundamental changes at this point.

**Comment by matozoid** [comment]
Let's see... This seems to contain the specs: http://openjdk.java.net/projects/jigsaw/spec/

So alright, work can be started here. It would be very nice to have Java 9 support finished before it's out.

**Comment by gunnarmorling** [comment]
Cool. The grammar for module descriptors is here:
http://cr.openjdk.java.net/~mr/jigsaw/spec/lang-vm.html#jigsaw-1.1

**Comment by matozoid** [comment]
Here's a little braindump:
- module info is a little language that has overlap with Java, but adds a lot of keywords. Therefore we cannot make it part of the main grammar - we don't want normal Java files to fail because of reserved words that are intended for module info. So we'll need a second grammar.
- the second grammar will reuse a lot of stuff from the main grammar (imports, type names, annotations...) so we'll have to find a reuse mechanism. JavaCC does not seem to have one.
- for the main JavaParser interface we'll define an additional `parseModuleInfo` method next to the usual `parse` method, with the same amount of variants, and an instance parser method variant. So no funky "what are we parsing here?" logic.
- The grammar for module info starts with `CompilationUnit`, so we can simply add a new `ModuleInfo` field to `CompilationUnit`. I'm a little sad that two different parse rules will be able to produce a `CompilationUnit` now, this might cause confusion.
- `SourceRoot` has the option to parse a directory full of files. We'll add an overridable heuristic to it that checks the file name by default. `module-info.java` will trigger the module info parser. It should be overridable since the JLS is not exact: "A compilation unit (JLS 7.3) may contain a module declaration, in which case the filename of the compilation unit is *typically* module-info.java."

**Comment by gunnarmorling** [comment]
I don't know JavaCC, but instead of having a separate grammar, couldn't you have two alternative definitions for `CompilationUnit`: `TypeDeclaration` | `ModuleDeclaration`? Like it's done for `TypeDeclaration` itself which can be a class/interface | enum | annotation type.

Then you can re-use definitions for imports, identifiers etc. Of course the productions for `requires`, `uses` etc. would only be used within `ModuleDeclaration`, so their terminal symbols wouldn't conflict with regular type declarations.

**Comment by ftomassetti** [comment]
I think lexical rules would be different and there is no way to restrict them. I think first tokens are recognized using global rules and only then parsing begins, so that would not work because we would have different keywords

**Comment by gunnarmorling** [comment]
Ah, yes, I see what you mean. It might be possible to not consider "requires" et al. as actual reserved keywords but handle them as "soft keywords" within the productions under `ModuleDeclaration` during parsing. I have no idea though whether and how that's doable with JavaCC.

**Comment by matozoid** [comment]
Well, I looked at that. It is possible to define a separate set of tokens that you can switch to. The examples always show Javadoc - token `/**` switches to the javadoc token set, and `*/` switches back to the normal set. Two problems: I can't switch to module info tokens until I match token `open` or `module` - so those still become reserved in normal Java. Switching back would be done on `}`. On the other hand, I could just start the parser in the module info token state, but here is problem 2: I don't know if a token can be in two states at once - which I need because module-info reuses a bunch of normal Java tokens. I can't redefine them. Anyway, it feels like I'm forcing things here.

So now @gunnarmorling made me think I could do something dirty: instead of defining keywords I can match identifiers. I can check if they are the correct keywords in the Java code embedded in the grammar.

There are also hints that reuse can be done using JJTree, but I have no idea why something that generates AST's would help me do reuse.

**Comment by gunnarmorling** [comment]
>  instead of defining keywords I can match identifiers. I can check if they are the correct keywords in the Java code embedded in the grammar.

Yes, that's what I had in mind. I think we do something similar in our parser for HQL (Antlr-based, though).

**Comment by matozoid** [comment]
Okay, that idea is turning into a giant hack. I'll do a naive implementation and people can improve later on if they want :)

**Comment by matozoid** [comment]
@gunnarmorling I'd like your feedback on #800 please
