### ISSUE TITLE
Observing nodes

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#559]
If we want to promote JavaParser as a tool to change code I think it would be useful to have the possibility to react to changes. To do that we could use the observer pattern. In this way I could register to get notifications for all changes and possibly react by doing something (update some caches, try to compile the new code, dump code on the disk, verify some property is respected, etc.)

Thoughts?

**Comment by matozoid** [comment]
I've been thinking how to generate Problems from the grammar, from the code while parsing, and on demand after a user made changes. Would this help with that?

**Comment by ftomassetti** [comment]
I am not familiar with the Problems thing but the "after a user made changes" sounds something we could use: we could add observers to nodes and on any change we could mark nodes as "dirty" and then regenerate problems when needed (for example the first time someone ask them)

**Comment by matozoid** [comment]
--> https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/Problem.java
A problem is essentially a single piece of feedback to the user of JavaParser. From "could not open file" to "annotations are not supported at this source level" to "opening bracket at position 10,10 was not closed"

A TryStmt can be invalid, you can set every optional part to null and it doesn't compile anymore. I don't want to throw an exception immediately when that happens, but I would like to be able to give that feedback somehow.

Sounds useful, but let's move this particular Problem problem into the future :)

**Comment by matozoid** [comment]
Callbacks are all the hype nowadays. Is there some library we should look at for inspiration?

**Comment by DeepSnowNeeL** [comment]
Just make sure it's functional interfaces so it can be converted to lambdas
:)

**Comment by matozoid** [comment]
I played with it a little, and here is my feedback:

``` java
package com.github.javaparser;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.observing.NodeObserver;
import com.github.javaparser.ast.type.ClassOrInterfaceType;

import static com.github.javaparser.ast.NodeList.nodeList;

public class A {
    public static void main(String[] args) {
        CompilationUnit compilationUnit = JavaParser.parse("class X {}");

        ClassOrInterfaceDeclaration x = compilationUnit.getClassByName("X");
        /* Is this the best scope for a callback? It seems to be attached to exactly one node, 
         and it will receive only events generated by this node. 
         Don't we want some kind of event propagation (like bubbling to parent) through the AST?
         */
        x.register(new NodeObserver() {
            @Override
            // Generics don't make much sense since all property types from x can come through here.
            public <P> void propertyChange(Node observedNode, String propertyName, P oldValue, P newValue) {
                System.out.println(propertyName + " " + oldValue.toString() + " -> " + newValue);
            }
        });
        // Doesn't work because of the generics
//        x.register((o, p, old, nw) -> {} );

        // Doesn't trigger. So much work to do :) :)
        x.addExtends(Object.class);

        // Triggers the callback
        x.setExtends(nodeList(new ClassOrInterfaceType()));


        System.out.println(compilationUnit);
    }
}
```

**Comment by ftomassetti** [comment]
About propagating to the parent I have 3 issues with that:
- the first one is that observer do not consume the events, otherwise I could not have more than one observer per node, so it is not clear when I should propagate to the parent
- (weak) the second issue is performances: I am afraid that propagating for many levels could be an issue
- setters are called in the constructor: this does not cause observers to be called because they cannot be already registered at that time. However if the node propagate to its parent (if the parent is already set) then the observers on the parent could be called for invokations of setters during the initialization

Maybe we can just register observers for all nodes we are interested into, possibly... for all the nodes. This can be done rather easily recursively, and we could add the same observer to the new nodes when new nodes are created. Note that the observer can be used for multiple nodes because it received the observer node as the first parameter, so it can distinguish them.

The generic on propertyChange is probably useless, I wanted just to use it to guarantee that the old and the new value have the same type.

If Generics get in the way of using lambdas... we should probably remove them!

**Comment by matozoid** [comment]
I see a problem with not doing event propagation and registering for all nodes as a solution: when you start adding new nodes, you will have to register your stuff there too. That's easy to forget. How would you deal with this? Maybe have a list of "global" (ThreadLocal?) observers somewhere that always get called? That would also trigger the setters-in-the-constructor thing, although I don't see what's wrong with that.

Yes, I'm not happy with Object old, Object new, but it seems unavoidable here, unless you want to specify callbacks on property level.

**Comment by DeepSnowNeeL** [comment]
I tend to prefer custom observer interfaces to the java poorly designed
default.
I can't get the real use case where you would use such observers tho.

**Comment by ftomassetti** [comment]
> I see a problem with not doing event propagation and registering for all nodes as a solution: when you start adding new nodes, you will have to register your stuff there too. That's easy to forget. 

I would define one observer that initially I put on all nodes, than this observer would attach itself to other nodes when it is notified of new nodes being added to the tree.

> How would you deal with this? Maybe have a list of "global" (ThreadLocal?) observers somewhere that always get called? That would also trigger the setters-in-the-constructor thing, although I don't see what's wrong with that.

Yes, we could have some global list of observers. Maybe we could put those observers on the root of the AST and enable some flag somewhere to consider these global observers.

**Comment by matozoid** [comment]
That first point makes a lot of sense and solves the problem. It's up to you if you want to add global observers or not :)

**Comment by ftomassetti** [comment]
The only issue I have now is that I can find all the nodes in a trees but I cannot get all NodeLists, so I cannot add an observer to them :( Maybe I should use a visitor

**Comment by ftomassetti** [comment]
Ok, I added a method that give the list of NodeLists owned by a method and completed the PR

**Comment by matozoid** [comment]
I was gone for a few hours - I kind of reversed my opinion, in that I don't think this solution is very obvious. I still think we should have event bubbling, but maybe another time, with a configuration option like "no events / local events / bubbly events"

**Comment by ftomassetti** [comment]
Consider one of the test:

``` java
        // PropagatingAstObserver automatically add itself to all new nodes added to the subtree  
        AstObserver observer = new PropagatingAstObserver() {
            @Override
            public void concretePropertyChange(Node observedNode, String propertyName, Object oldValue, Object newValue) {
                changes.add(String.format("%s.%s changed from %s to %s", observedNode.getClass().getSimpleName(), propertyName, oldValue, newValue));
            }
        };
        // we register it for all nodes
        cu.registerForSubtree(observer);

        // now we create a new node, of course we get the notification
        FieldDeclaration fieldDeclaration = cu.getClassByName("A").addField("String", "foo");
        // assert on the notifications...

        // now we change the field we just added: he got the observer automatically, so we get more notification
        cu.getClassByName("A").getFieldByName("foo").getVariables().get(0).setId(new VariableDeclaratorId("Bar"));
       // assert on the notifications...  
```

I think this is reasonably easy to use **IF** the user is aware of the existence of these classes and methods

**Comment by matozoid** [comment]
Alright, I'm convinced and I think I'll stay convinced this time :)

**Comment by ftomassetti** [comment]
Well, we can always improve this one later, also considering feedback from users and the kind of unexpected stuff they try to do with this feature :)

**Comment by DeepSnowNeeL** [comment]
Why not using an enum to define the behavior ? (Instead of PropagatingAstObserver type) It might expose better which
options are available :)

**Comment by ftomassetti** [comment]
Now node has an additional register method which take an observer and a mode, where mode is one of these:

```
    /**
     * Different registration mode for observers on nodes.
     */
    public enum ObserverRegistrationMode {

        /**
         * Notify exclusively for changes happening on this node alone.
         */
        JUST_THIS_NODE,

        /**
         * Notify for changes happening on this node and all its descendants existing at the moment in
         * which the observer was registered. Nodes attached later will not be observed.
         */
        THIS_NODE_AND_EXISTING_DESCENDANTS,

        /**
         * Notify for changes happening on this node and all its descendants. The descendants existing at the moment in
         * which the observer was registered will be observed immediately. As new nodes are attached later they are
         * automatically registered to be observed.
         */
        SELF_PROPAGATING
    }
```

In NodeTest I added three tests to show how the same changes are notified differently using the different values. This method is intended to make life easier for the user and it is a facade on the existing facilities. In practice:
- with `JUST_THIS_NODE` we call _node.register(observer)_, 
- with `THIS_NODE_AND_EXISTING_DESCENDANTS` we call _node.registerSubTree(observer)_ 
- and with `SELF_PROPAGATING` we call _node.registerSubTree(PropagatingAstObserver.transformInPropagatingObserver(observer))_
