### ISSUE TITLE
I do not know how to visit import declarations

### ISSUE THREAD

**Issue by sdrgroup** [javaparser/javaparser#561]
I think parsing the package that imported in a class is very important. But when I extend my own class from VoidVisitorAdapter, I find that there is a error that if I use @Override. I think  javaparser can not support parsing import. Is it possible that add the function that can get the list of import?

**Comment by matozoid** [comment]
Thanks for the report! Can you...
- show a few lines of code about what you are trying to do?
- tell us the version of JavaParser that you are using?

**Comment by sdrgroup** [comment]
I try to get the import information in the java file, but it doesn't support ImportDeclaration in VoidVisitorAdapter. And there are not some other methods can get the import information. I think parsing import in a file is important, but JavaParser should support it now.
The following is the code ,but you know, it cannot work.
The javaparser's version is 3.0.0-alpha.8.
OS is Ubuntu 16.04

public class MethodVisitor extends VoidVisitorAdapter {
    @Override
    public void visit(ImportDeclaration im, Object arg) {
        String importInFile = im.toString();
        logger.info("the import is:"+importInFile);
        super.visit(im, arg);
    }
}

**Comment by ftomassetti** [comment]
Well, this is very surprising. To my knowledge JavaParser support all different forms of imports.

Could you please indicate the source code of one file containing imports which are not recognized?

**Comment by ftomassetti** [comment]
You may want to do this:

```
public class MyAdapter extends VoidVisitorAdapter {

    @Override
    public void visit(EmptyImportDeclaration n, Object arg) {
        super.visit(n, arg);
    }

    @Override
    public void visit(SingleStaticImportDeclaration n, Object arg) {
        super.visit(n, arg);
    }

    @Override
    public void visit(SingleTypeImportDeclaration n, Object arg) {
        super.visit(n, arg);
    }

    @Override
    public void visit(StaticImportOnDemandDeclaration n, Object arg) {
        super.visit(n, arg);
    }

    @Override
    public void visit(TypeImportOnDemandDeclaration n, Object arg) {
        super.visit(n, arg);
    }
}
```

There are different kinds of imports and the visitor permits to handle them separately.

This should solve your issue. I am going to close this ticket. Please feel free to reopen it if you are facing other problems processing imports.

**Comment by matozoid** [comment]
@sdrgroup - maybe you have some input for issue #660 ?
