### ISSUE TITLE
Node.remove should invoke the setter

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#565]
`Node.remove` directly set the field of the parent while it should call the setter. The setter would notify the observers, otherwise we have changes which cannot be observed.

**Comment by DeepSnowNeeL** [comment]
on it

**Comment by DeepSnowNeeL** [comment]
Well actually it uses `setParentNode(null);` so I don't really get it (but I still edited a few things so i'll pr anyway)

**Comment by ftomassetti** [comment]
I am also working on this one :D
I should have claimed it

**Comment by ftomassetti** [comment]
Related issue: in NodeList.remove we set the parent of the node to null even if the node is not part of the NodeList

**Comment by ftomassetti** [comment]
Given you call it first the issue is yours, I will help review it and call it first next time, sorry for the confusion

**Comment by DeepSnowNeeL** [comment]
Np check #566 and  tell me if I need  to change anything for the Node class ? Since it calls setParentNode(null) it should be okay ? or is there somthing else i'm missing ?

**Comment by ftomassetti** [comment]
Solve through #566 and #567
