### ISSUE TITLE
Provide a common interface for all classes with modifiers

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#57]
Different classes (TypeDeclaration, MethodDeclaration, FieldDeclaration, others?) have a method getModifers, we could declare a common interface, so that certain operation could be performed on all of this classes.

**Comment by sebastiankirsch** [comment]
The hardest part is probably the name of the interface. Although we already have a `DocumentableNode`, I find `ModifiableNode` a bit misleading, as it suggests the node can be modified (which is the case with any node). How about `NodeWithModifier`?

**Comment by ftomassetti** [comment]
I would suggest `NodeWithModifiers` (we can have more than one)

**Comment by ftomassetti** [comment]
If we are going to support Java 8, we could do something like this:

```
/**
 * A Node with Modifiers.
 */
public interface NodeWithModifiers {
    int getModifiers();

    // repeat for isPrivate, isPublic, isStatic, etc.
    default boolean isStatic() {
        return ModifierSet.isStatic(getModifiers());
    }
}
```

**Comment by ptitjes** [comment]
And why not replace the integer with an EnumSet ? Those are really lightweight.

We could easily implement a `int getModifiers();` for backward compatibility.

**Comment by ftomassetti** [comment]
done as suggested by @ptitjes 

Note that we should refactor also a bunch of constructors: for now I have left all the old methods (deprecating some of them)

**Comment by matozoid** [comment]
Is this connected to a pull request or so?

**Comment by matozoid** [comment]
Let's see if #363 moves us in a nice direction for replacing bitfields.
