### ISSUE TITLE
Need Help With Visitor

### ISSUE THREAD

**Issue by azscottd** [javaparser/javaparser#573]
I've reviewed the examples but am unclear how to achieve the following:

How would one implement a visitor to identify all occurrences of instantiation of object type "Bar" with a parameter of object type "Foo"?

i.e.

Foo o = new Foo();
Bar b = new Bar(o);

I'd like to identify the source file and line number.

Thank you.

**Comment by ftomassetti** [comment]
Short answer: using JavaParser you can easily find all the object instantiation but using JavaParser alone you can not find the type of values. You can use [JavaSymbolSolver](https://github.com/javaparser/javasymbolsolver) (a project from the same team of JavaParser) to get the type of `o` and so achieve your goal.

Regarding JavaParser: can you create a visitor to get all the `ObjectCreationExprs`?

Regarding JavaSymbolSolver: if you have a problem using it to get the type of the value please [open a ticket there](https://github.com/javaparser/javasymbolsolver/issues/new).

**Comment by matozoid** [comment]
No response, closing.
