### ISSUE TITLE
Javadoc comments ignored/dropped

### ISSUE THREAD

**Issue by BCooper63** [javaparser/javaparser#576]
I've found two cases where the Javadoc node is dropped, ignored or lost.

1) When there is a blank line between the Javadoc block and the class/enum declaration.
2) When an enum constant declaration if followed by a line common.

The attached files demonstrate these issues. MissingJavadoc.java(.txt) parses the file InputEnum.java(.txt). It then uses a visitor class to visit the Enum declaration and the two enum constant declarations.

It should be the case that the EnumDeclaration visit and both EnumConstantDeclaration visits all have a JavadocComment with the relative Javadoc.

[InputEnum.java.txt](https://github.com/javaparser/javaparser/files/601047/InputEnum.java.txt)
[MissingJavadoc.java.txt](https://github.com/javaparser/javaparser/files/601049/MissingJavadoc.java.txt)

**Comment by matozoid** [comment]
Thanks! Improved Javadoc support is on the planning after we release 3.0.

**Comment by ryan-devrel** [comment]
Any update on this?  There's another case I've encountered similar to this:

```java
/**
 *   Valid JavaDoc comment.
 */
// TODO: Fix this method
public String myMethod() {
  ...
}
```

The line comment prevents the JavaDoc comment from being associated with the method. It'd be nice if the JavaDoc was accessible from a MethodDeclaration visitor.

**Comment by matozoid** [comment]
Have you tried playing with the `doNotAssignCommentsPrecedingEmptyLines` setting in `ParserConfiguration`?

**Comment by jlerbsc** [comment]
In the ast there can only be one comment for a node so in this exemple the javadoc comment cannot be setted into the node because at this stage a line comment is already attached to the node (in this case EnumConstantDeclaration). The javadoc comment is considered as an orphan node and is attached to the orphan comments of the parent node. See CommentsInserter.insertComments(..). 

    public enum InputEnum { 
           /** 
            * First Enum Constant Declaration
            */ 
            EnumOne; // With a comment following the declaration
     }

**Comment by jlerbsc** [comment]
Finally, it seems that this is the desired behavior

https://tomassetti.me/java-comments-parsing/
and
https://leanpub.com/javaparservisited

**Comment by matozoid** [comment]
Comment behaviour is extensively documented in the book, by the way.

**Comment by jlerbsc** [comment]
I added the link to the book .
