### ISSUE TITLE
Provide a common interface for all classes with names

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#58]
Similarly to #57 I think it could be useful to have a common interface for all things that have the method getName (there are a few).

**Comment by sebastiankirsch** [comment]
Is `NameableNode` fine for everyone?

**Comment by ftomassetti** [comment]
Mmm, those names typically have to have a name, _Nameable_ to me sounds like something that could have a name. I do not have strong suggestions on this one, maybe `NamedNode` or `NodeWithName` (similarly to the current suggestion for #57 )?

**Comment by sebastiankirsch** [comment]
`ǸamedNode` sounds good to me.
