### ISSUE TITLE
Imports should have a qualified name method

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#584]
I am porting JavaSymbolSolver to alpha.10 and I have issues with imports. I miss a method that give me the qualified name. Also, it seems that name ClassOrInterfaceType has a simple name + a scope which should be another ClassOrInterfaceType. However this is often not the case: the scope is just a package. Am I missing something? Today I am pretty tired so I could be missing something obvious here

**Comment by matozoid** [comment]
COIT having a scope like that is an interesting things that I found a release or two ago. I think it is meant for inner classes: X.Y is COIT Y with scope COIT X. This messes up with something like com.github.X.Y, where github and com are also seen as COITs. I know of no good way to fix this. Heuristics could be a good hack: does a component of the name start with a lower case letter? It's probably a part of a qualified name. Upper case? It's probably a context COIT.

For imports: I claim there is no such thing as "the qualified name". The QN of the package we're importing? Of the class? Of the member? Of the class whose member we're importing? The idea with the refactoring is to treat all four kinds of imports seperately, because they do not do the same thing. Each variant will give you more specific information than the old ImportDeclaration did.

If that's still not what you want, please describe so we can figure out what to do.

**Comment by ftomassetti** [comment]
Heuristics are good in my opinion but not in the core module.

I am just suggesting than maybe the imports without the asterisk could get a method that give me the full name.

**Comment by matozoid** [comment]
Check out ImportDeclarationTest.java, is that what you need?

**Comment by ftomassetti** [comment]
Looking at these tests:

```
    @Test
    public void singleTypeImportDeclaration() {
        ImportDeclaration importDeclaration = JavaParser.parseImport("import a.b.c.X;");
        SingleTypeImportDeclaration i = (SingleTypeImportDeclaration) importDeclaration;
        assertEquals("a.b.c.X", i.getType().toString());
    }

    @Test
    public void typeImportOnDemandDeclaration() {
        ImportDeclaration importDeclaration = JavaParser.parseImport("import a.b.c.D.*;");
        TypeImportOnDemandDeclaration i = (TypeImportOnDemandDeclaration) importDeclaration;
        assertEquals("a.b.c.D", i.getName().toString());
        assertEquals("D", i.getName().getId());
    }

    @Test
    public void singleStaticImportDeclaration() {
        ImportDeclaration importDeclaration = JavaParser.parseImport("import static a.b.c.X.def;");
        SingleStaticImportDeclaration i = (SingleStaticImportDeclaration) importDeclaration;
        assertEquals("a.b.c.X", i.getType().toString());
        assertEquals("def", i.getStaticMember());
    }

    @Test
    public void staticImportOnDemandDeclaration() {
        ImportDeclaration importDeclaration = JavaParser.parseImport("import static a.b.c.X.*;");
        StaticImportOnDemandDeclaration i = (StaticImportOnDemandDeclaration) importDeclaration;
        assertEquals("X", i.getType().getNameAsString());
		assertEquals("c", i.getType().getScope().get().getNameAsString());
		assertEquals("b", i.getType().getScope().get().getScope().get().getNameAsString());
		assertEquals("a", i.getType().getScope().get().getScope().get().getScope().get().getNameAsString());
    }
```

In the first three cases I can get what I need calling toString. I would suggest having some other method returning that value because later toString could be changed to include spaces or comments for example, while we want a method giving the complete name now and in the future and with a more meaningful name.

The fourth case seem not covered (at least in the test)

**Comment by matozoid** [comment]
If you mean the fourth test doesn't show a name, that's the same pattern: getType().toString()

I agree that toString is not the greatest idea here. getName().getString() can be changed to getNameAsString(), would you like a getTypeAsString() ? Would you like these ...AsString() methods to output only the identifiers and the dots?

**Comment by ftomassetti** [comment]
Yes, I would be very happy if I could be guaranteed that they return only the identifiers and the dots. Ideally I would call it `getFullName, getCompleteName, getQualifiedName, getComposedName` or something similar, but I am not feeling very strongly towards any of them, I would like just not having to call toString to get meaningful information

**Comment by matozoid** [comment]
Oh, if you like another name than "...AsString", I'm going to show you this method you created a year ago:

```java
public interface NodeWithDeclaration {
    String getDeclarationAsString();
}
```
;)

**Comment by ftomassetti** [comment]
I meant another name than `toString`. Now that I see this method I found a sign of great programming wisdom to name them `xxxAsString`. I vote to append `asString` to all of our methods :D

**Comment by matozoid** [comment]
Well, that's settled then :)

**Comment by matozoid** [comment]
I've accidentally merged this into alpha 11... There are some asString() methods now, but I think the approach is wrong. This should be done with visitors I think. Anyway, the direct need has been addressed.
