### ISSUE TITLE
Tidying up tests

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#59]
This issue came up from a comment in https://github.com/matozoid/javaparser/pull/50.
I copy the description from there.

The two files "TestCommentsParser" and "TestCommentsParsing" seem just to be two buckets with slightly different names.

Some tests use Hamcrest matchers other don't.

What I assume is legacy test code, that uses main rather than JUnit.

**Comment by SmiddyPence** [comment]
In progress.

**Comment by ftomassetti** [comment]
With the last pull request I merged I committed by mistake some additional tests on comments (working and passing). I realize they could be a problem because they could touch classes you were working on. I am sorry about that, please let me know if I need to remove them and feel free to override/remove them if they cause any troubles. My bad.

**Comment by SmiddyPence** [comment]
Ok, so this is just an example of using BDD for a couple of scenarios.

Anyway I was breaking the tests into more manageable files.  Moving source into separate files rather than inline code, converting to Hamcrest etc.

I notice that a lot of tests are basically the same, but it is the content of the class under test that really vary.  So I think more of a BDD or specification approach might work better.

E.g. In one file we might define a story or spec (imagine syntax highlighting) for a Class under test or family of classes

``` cucumber
Scenario: A Class With Line Comments is processed by the Comments Parser

Given the class:
package japa.parser.comments;

public class ClassWithLineComments {

    public void aMethod(){
        // first comment
        int a=0; // second comment
        // third comment
        // fourth comment
    }
}
When the class is parsed by the comment parser
Then the total number of line comments is 4
Then line comment 1 is " first comment"
Then line comment 2 is " second comment"
Then line comment 3 is " third comment"
Then line comment 4 is " fourth comment"
Then the line comments have the following positions:
|beginLine|beginColumn|endLine|endColumn|
|6|9|6|25|
|7|18|7|35|
|8|9|8|25|
|9|9|9|26|
```

The we define the repeatable steps.

``` java
public class CommentParsingSteps {

    private CommentsCollection commentsCollection;
    private String sourceUnderTest;


    @Given("the class:$classSrc")
    public void givenTheClass(String classSrc) {
        this.sourceUnderTest = classSrc.trim();
    }

    @When("the class is parsed by the comment parser")
    public void whenTheClassIsParsedByTheCommentParser() throws IOException {
        commentsCollection = new CommentsParser().parse(sourceUnderTest);
    }

    @Then("the total number of line comments is $expectedCount")
    public void thenTheTotalNumberOfLineCommentsIsCount(int $expectedCount) {
        assertThat(commentsCollection.size(), is($expectedCount));
    }

    @Then("line comment $position is \"$expectedContent\"")
    public void thenLineCommentAtPositionHasExpectedContent(int position, String expectedContent) {
        LineComment lineCommentUnderTest = commentsCollection.getLineComments().get(position-1);

        assertThat(lineCommentUnderTest.getContent(), is(expectedContent));
    }

    @Then("block comment $position is \"$expectedContent\"")
    public void thenBlockCommentAtPositionHasExpectedContent(int position, String expectedContent) {
        BlockComment lineCommentUnderTest = commentsCollection.getBlockComments().get(position - 1);

        assertThat(lineCommentUnderTest.getContent(), equalToIgnoringWhiteSpace(expectedContent));
    }

    @Then("the line comments have the following positions: $table")
    public void thenTheLineCommentsHaveTheFollowingPositions(ExamplesTable examplesTable) {
        int index = 0;
        for(Parameters exampleRow : examplesTable.getRowsAsParameters()){
            Comment expectedLineComment = toLineComment(exampleRow, new LineComment());
            Comment lineCommentUnderTest = commentsCollection.getLineComments().get(index);

            assertThat(lineCommentUnderTest.getBeginLine(), is(expectedLineComment.getBeginLine()));
            assertThat(lineCommentUnderTest.getBeginColumn(), is(expectedLineComment.getBeginColumn()));
            assertThat(lineCommentUnderTest.getEndLine(), is(expectedLineComment.getEndLine()));
            assertThat(lineCommentUnderTest.getEndColumn(), is(expectedLineComment.getEndColumn()));
            index ++;
        }
    }

    @Then("the block comments have the following positions: $table")
    public void thenTheBlockCommentsHaveTheFollowingPositions(ExamplesTable examplesTable) {
        int index = 0;
        for(Parameters exampleRow : examplesTable.getRowsAsParameters()){
            Comment expectedLineComment = toLineComment(exampleRow, new BlockComment());
            Comment lineCommentUnderTest = commentsCollection.getBlockComments().get(index);

            assertThat(lineCommentUnderTest.getBeginLine(), is(expectedLineComment.getBeginLine()));
            assertThat(lineCommentUnderTest.getBeginColumn(), is(expectedLineComment.getBeginColumn()));
            assertThat(lineCommentUnderTest.getEndLine(), is(expectedLineComment.getEndLine()));
            assertThat(lineCommentUnderTest.getEndColumn(), is(expectedLineComment.getEndColumn()));
            index ++;
        }
    }

    private Comment toLineComment(Parameters row, Comment comment) {
        comment.setBeginLine(Integer.parseInt(row.values().get("beginLine")));
        comment.setBeginColumn(Integer.parseInt(row.values().get("beginColumn")));
        comment.setEndLine(Integer.parseInt(row.values().get("endLine")));
        comment.setEndColumn(Integer.parseInt(row.values().get("endColumn")));
        return comment;
    }

}
```

Other than a bit of jBehave plumbing that I have put in that is basically it.

I like this:

a) Because the src code under test is neatly tied into the test cases and easy to see what is expected, rather than in separate files or as unreadable inline strings.

b) As long as we word the steps the same way we can just reuse the same test code over and over.

c) The Specification approach can tie neatly into a wiki for users to understand how the library should work rather than fairly unreadable "unit" tests

What do you think, perhaps overkill?  Clone my repo if you want a quick play.

**Comment by ftomassetti** [comment]
In my opinion this is great because it makes things nicer and give me the possibility of learn JBehave by looking at what you are doing :D 

I think when we have enough examples other contributors who are not familiar with JBehave can just copy & modify those tests without having too much problems.

It would be nice to hear what @matozoid think about that.

My only concern is that we probably want to have all the tests using one paradigm, I wonder how much effort could take to port all the existing tests (60 something) to JBehave. What do you think?

**Comment by ftomassetti** [comment]
I forgot one thing: Great work!

**Comment by SmiddyPence** [comment]
It'll take a little while, but not too long.  It's fairly enjoyable as it generally something that works well. 

I've had a fair amount of joy with JBehave I think main problem with it comes with the "scalability" of it, if you have dozens of new scenarios coming in every sprint/phase it gets out of hand quickly - just in maintenance terms. For a project like this, where the product is fairly static it should be good.  It is a trait of this breed of integration testing in general I have heard the same complains about Spock as well, not specific to JBehave.

**Comment by matozoid** [comment]
I just hope we don't scare potential committers away by requiring them to learn this - but that's the case with any technology. We could also go all out and switch to a more scripty language to get rid of the verbosity. It's hard to make the tests worse than they are now :)

One thing I would certainly do is get rid of the horrible, awful Hamcrest matchers in favour of AssertJ. Its code generation feature should do wonders for the readability of the asserts. --> http://joel-costigliola.github.io/assertj/assertj-assertions-generator.html

**Comment by ftomassetti** [comment]
Maybe we can put some extra comments or add links to appropriate documentation for JBehave to reduce the risk of scaring committers. Or maybe some committers will simply not provide tests, I have not being involved in the project for long time so I do not know how frequently committers do their homework providing appropriate tests.

**Comment by SmiddyPence** [comment]
Ok what I will do is convert the comment parsing tests, and you guys can have a look at how it will work.  Then make a decision on whether to use it and convert all the remaining tests.

I guess my opinion on it is that as far as a learning curve goes it is probably easier to pick up JBehave then working on the parser itself.  So I don't think potential committers would lack capability.

**Comment by matozoid** [comment]
Full steam ahead then!

**Comment by SmiddyPence** [comment]
Handled in #68
