### ISSUE TITLE
Create validation framework

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#594]
The idea:
```java
Validator v = new Java14Validator();
List<Problem> problems = v.validate(compilationUnit);
```
Problems could be "annotations are not supported in Java 1.4" or "try has no catch or finally" and so on.

It would be nice of a validator was simply a collection of validationRules that are applied to the supplied compilationUnit. A validationRule would probably contain some kind of visitor.

Why? There can be many problems with an AST, and currently there is no consistent way to report those. With this framework, every non-parse error (there is no AST to validate until we're done parsing) can be detected on demand by the user.

This splits JavaParser errors in these categories:
- environmental errors (file not found...)
- parse errors
- semantic errors (found by validators)
- user errors (triggered by asserts: using empty names, using null where not allowed, ...)

**Comment by ftomassetti** [comment]
Should this be a separate project under the JavaParser umbrella?
This could benefit from typechecks I think

**Comment by matozoid** [comment]
What do you mean with type checks? In what way?

Separate project: I feel that reporting problems for a certain Java version is core business. But only the validators for Java versions.

**Comment by ftomassetti** [comment]
Type checks: checks for example if you try to assign an int to a String field

**Comment by matozoid** [comment]
Oh alright, that goes into another module or project.

**Comment by matozoid** [comment]
@ftomassetti - how would you put type checking in here? That seems JSS territory?

**Comment by ftomassetti** [comment]
Yes, it should be based on JSS. We could implement another Validator to.

Some things we could verify:
* verify assignments involve compatible types
* all references are resolved
* a class do not extend itself
* in catch clauses Exceptions are used and not other types

So we are getting closer and closer to get our own compiler...

**Comment by matozoid** [comment]
Okay, shall we open an issue on JSS for this?
