### ISSUE TITLE
Battle test remove

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#597]
We could take several Java files, build the AST and try to remove all nodes (starting from the leaves). This would permit to battle-test the remove method.

**Comment by matozoid** [comment]
Do you want this in 3.0, or shall I remove the label?

**Comment by ftomassetti** [comment]
I guess we can remove it: if we do it later and we find bugs it would not change the API anyway so I think it is not strictly necessary to have it as part of 3.0.0

**Comment by matozoid** [comment]
The introspecting emove was replaced by generated code.

**Comment by ftomassetti** [comment]
Cool, I guess we can close this one then

**Comment by matozoid** [comment]
Oh, yeah, I forgot to do so :)
