### ISSUE TITLE
Generate remove methods for nodes

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#598]
Instead of having a fancy introspection remove() method, generate a remove method per node type by using the metamodel that is being considered here: #353

**Comment by ftomassetti** [comment]
This would be a good idea!
Should we assign it to milestone 4? Create a label for metamodel stuff?

**Comment by matozoid** [comment]
My planning goes no further than 3.0 ;) We've got so many ideas now that we could plan 3.1, 3.2, 3.3 instead of a big jump to 4.0. But planning what is going to be in 3.1 is impossible because us volunteers do whatever we like anyway ;)

A label? I'm using one for Java 9 so I know when we can claim Java 9 support. How would it help with metamodeling?

**Comment by matozoid** [comment]
@ftomassetti @DeepSnowNeeL can you write a sample remove() method for one type of node, non-trivial? So that it is clear what to generate?

**Comment by ftomassetti** [comment]
The way remove works is basically call some setter in the parent with a null value. Note that the method to call depends on the parent: the same Node could be potentially used in different roles. This is what would make difficult this method I think

**Comment by matozoid** [comment]
Would it help to call `parent.remove(this)` so that the logic can be moved to the node that knows what children it has?

**Comment by ftomassetti** [comment]
Yes, using `parent.remove(this)` would help
