### ISSUE TITLE
Restrict reparenting of nodes

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#603]
We have the odd case where we can get a node from one AST, and set it in another AST. This will try to remove it from the first AST. This could make its state invalid, like removing the "then" clause from an IfStmt.

Suggestion: once a node's parent is set, it cannot be changed anymore. Setting a node while its parent is set is a runtime error.

New way to use a node from one AST in another is to clone() the node and set the clone in the other AST.

**Comment by ftomassetti** [comment]
Remove a node can fail. If the node cannot be removed that it cannot be added elsewhere.

Maybe we could:
1) let people remove a Node and permit only to add nodes which are unparented. 
2) Otherwise we could throw an exception when trying to add a node which has a parent, without even trying to remove the node first
2) We just try to remove nodes which have a parent before adding them, if this fails then we throw an exception

**Comment by matozoid** [comment]
Okay, could you explain a bit more? Is 1, 2, 3 a sequence?

**Comment by ftomassetti** [comment]
They were three alternatives but I now realized I should correct them.

**Option 1**: if someone try to add a Node which has a parent we throw `IllegalArgumentException`
**Option 2**: when adding a Node we try to remove the node from the AST. If we cannot we throw `IllegalArgumentException`

In case we go for Option 1 we could still allow to remove a Node manually. So a user could decide to remove the Node and later add it. If he has removed the Node successfully that Node can be added successfully. Alternatively we could say that a Node that was in the AST is "tainted" and it cannot be added anymore to the AST.

I would go for **Option 2**

**Comment by matozoid** [comment]
I see what you mean. How different is the current situation from option 2?

**Comment by matozoid** [comment]
This is fixed in 3.1.0. Setting a required property to null is not allowed. Setting it to another node will reparent everything. If an attempt to reparent a required node is made: assert.
