### ISSUE TITLE
Document the build process

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#61]
We should write a few lines on how to build the project and how to include it as a dependency.

We should either doing that in the README.md or add a reference there.

**Comment by matozoid** [comment]
Building from scratch works fine for me without the javacc step, even with an empty local repo. Not sure what's wrong here?

**Comment by ptitjes** [comment]
@matozoid I believe that since https://github.com/javaparser/javaparser/commit/cd1296db6541d76624a38675c54c163fd3e46bed, the build process is correctly documented.

Can we close this issue ?

**Comment by ptitjes** [comment]
From gitter discussion:
  @matozoid: I think we had a discussion a long time ago with the same conclusion: close it
