### ISSUE TITLE
Package-private constructors always have an unknown begin position

### ISSUE THREAD

**Issue by avik-das** [javaparser/javaparser#611]
It seems `ConstructorDeclaration`s don't have valid begin positions. They're always `0-0`. See this minimal test case, which I ran with `3.0.0-RC.1`:

```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;

public class PositionBug {
    public static void main(String[] args) {
        String src =
            "package test;\n" +
            "\n" +
            "public class Test {\n" +
            "    Test() {\n" +
            "        // minimal\n" +
            "    }\n" +
            "}";

        CompilationUnit unit = JavaParser.parse(src);
        System.out.println(
                unit
                    .getTypes().get(0)
                    .getMembers().get(0)
                    .getRange()
        );
    }
}
```

The output is:

```
Optional[(line 0,col 0)-(line 6,col 5)]
```

You can change the constructor to a method, and the begin position will be correctly populated. Adding more constructors doesn't change anything; all the `ConstructorDeclaration`s have an unknown begin position.

**Comment by avik-das** [comment]
Turns out the issue is actually with package-private ~methods and~ constructors, ones without a visibility modifier. If you add `public` to the constructor above, it works. ~If you create a method that's package-private, it doesn't work.~

**Comment by ftomassetti** [comment]
We have actually received a patch for this exact issue a few hours ago. I think that your problem should be already solved in the master branch. Unfortunately we merged the patch after releasing the first RC so it will be available in RC2

**Comment by avik-das** [comment]
@ftomassetti: Perfect, thanks for the heads up. I looked through that patch just now so I can hopefully contribute for these types of cases in the future, but for this one, I'll wait. I'll close this so it doesn't clutter up your bug list, and re-open if it doesn't get fixed in the next RC.

**Comment by ftomassetti** [comment]
perfect, thanks! And thank you also for reporting the issue!

**Comment by matozoid** [comment]
@avik-das you can expect RC2 coming weekend :)

**Comment by avik-das** [comment]
@matozoid: Fantastic! I'll keep an eye out. Thanks.

**Comment by avik-das** [comment]
@ftomassetti @matozoid: I wanted to confirm that upgrading to RC2 worked for me. Thanks.

**Comment by ftomassetti** [comment]
@avik-das thanks to you for reporting this issue and help us verifying it !
