### ISSUE TITLE
Parser-generated Problems don't have a correct begin position

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#613]
The begin position is set to the start of the last token in the rule that creates the problem. It should be the start of the FIRST token.

**Comment by jlerbsc** [comment]
What is the desired behavior?

    public void test613() {
        String source = "public default class A{}";
        CompilationUnit cu = StaticJavaParser.parse(source);
    }

This test case reports 

    com.github.javaparser.ParseProblemException: (line 1,col 1) 'default' is not allowed here.

this report should it be rather ?

    com.github.javaparser.ParseProblemException: (line 1,col 8) 'default' is not allowed here.

**Comment by matozoid** [comment]
Oof, this is an old one! I think the one you have there is a validator-generated problem? What about `public invalid class A{}`?

**Comment by jlerbsc** [comment]
public invalid class A{}

    (line 1,col 1) Parse error. Found  "invalid" <IDENTIFIER>, expected one of  ";" "@" "class" "enum" "interface" "module" "open" "record"

**Comment by matozoid** [comment]
Looks good enough to me! Close?
