### ISSUE TITLE
Add method to print Constructor and Method prototypes

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#62]
It can be useful for different users (for example I am building a Java linter and I could use it).
All sort of reporting and analysis on Java code could take advantage of that method.
What do you think?

**Comment by SmiddyPence** [comment]
Prototype is a bit ambiguous for Java...

Are we talking about signature, but with parameters names and return etc?  Signature would be a decent fair expectations for the API.  Maybe "declaration" would be less controversial term than prototype?

Ex Sig: `anotherMethodToChange(int)` 

Ex Dec: `public void anotherMethodToChange(int value)` 

formally : [accessSpecifier] [static] [abstract] [final] [native]
    [synchronized] returnType methodName ([paramlist])
    [throws exceptionsList]

**Comment by ftomassetti** [comment]
Yes, that is what I meant. It is important to use the right terminology, thank you.

I will call it declaration and include your specification (the one following "formally") in the JavaDoc.

**Comment by SmiddyPence** [comment]
I just cargo cult-ed spec off of Oracle ;-)
