### ISSUE TITLE
Helper for fieldDeclaration.getVariable(0).getType()

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#621]
Previously we could do getElementType() directly on a FieldDeclaration,
Now that's been reworked, it would be great to have a helper to directly get the type of the first variable declared by this field.

`getFirstVariableType()` can be cool
Maybe we could have `getFirstVariableIdentifierAsString()` too ?

Thanks

**Comment by matozoid** [comment]
Oh, I thought you wanted something that behaved like the old getElementType() - which would be getVariable(0).getType().getElementType(). Is getVariable(0).getType() so hard to use?

**Comment by DeepSnowNeeL** [comment]
Well, no it isn't that hard.

But considering java coding standards, i'm certain that 90% of fields are simple ClassOrInterfaceDeclaration followed by only 1 variable identifier so I think it will be usefull :)

**Comment by matozoid** [comment]
Well, I'm worried that users will use these methods because they are easy, and introduce bugs because their code fails in the less common situation of multiple variables :(

**Comment by DeepSnowNeeL** [comment]
Yep.. well as you wish :P

**Comment by matozoid** [comment]
That was not meant to be a final decision :) Putting back getElementType() as a shortcut is fine. What about... `getCommonType()` which checks that all variables have exactly the same type, then return the type node from the first variable?

**Comment by DeepSnowNeeL** [comment]
Returning an Optional if it doesn't ? 
I don't really see a benefit from getCommonType() it does slightly the same thing (at least in my case) and has the same drawbacks. 

I think if we create the getFirst... it's already in the dev head than it can contain more than one element

getCommonType could be added to, but not useful in my case

**Comment by DeepSnowNeeL** [comment]
oops

**Comment by matozoid** [comment]
I was thinking of asserting if it doesn't match - so that the user will be notified that he failed to check for multiple variables :) Is that more useful?

**Comment by matozoid** [comment]
Anyway, what it would add over "first" is that it will behave like the old getType(). It returns the type that is common to all variables. First means: ignore the other variables, who cares.

**Comment by DeepSnowNeeL** [comment]
Allright let's go for `getCommonType` then

**Comment by matozoid** [comment]
Are you sure? ;)
