### ISSUE TITLE
Pretty printing variables with array types

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#632]
Currently this `byte[] rawData` is pretty printed as `byte rawData[]`.
I would suggest we pretty print it as `byte[] rawData`. We could check the common type between all the fields and print it in front of the variables, while putting extra brackets behind the variables.

For example:
`int a[], b[][]` -> `int[] a, b[]`
`int[] a[]` -> `int[][] a`
`int[] a, b[]` -> `int[] a, b[]`

What do you think?

**Comment by ftomassetti** [comment]
If you agree I can send a PR

**Comment by matozoid** [comment]
Please do send a PR, I know I've taken the lazy solution here :)

**Comment by ftomassetti** [comment]
I can easily find the common type between different fields but to preserve annotations correctly probably we should remember where the brackets were...

**Comment by matozoid** [comment]
Well, that certainly makes it more complex, but if you do it right you should be able to add brackets to the type on the left as long as all variables have the same annotations on those brackets...

Or you say "if there are annotations on the brackets I'll just stick all brackets behind the identifiers, as it is now. It's not like I've ever seen an annotated array bracket.
