### ISSUE TITLE
Make TAB character size used by JavaCC configurable

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#639]
It is set to 8, and all positions are calculated using this number. This may very well be wrong for some cases. I think it is mostly 4 nowadays, but should be configurable.

**Comment by matozoid** [comment]
This was found after reading @larsac07's thesis: http://bora.uib.no/bitstream/handle/1956/12756/144804725.pdf

@larsac07 - if you have more suggestions, please add :)

**Comment by larsac07** [comment]
Yay! Someone read my thesis!

**Comment by matozoid** [comment]
@larsac07 turns out you weren't the only one bothered by the TAB thing, by the way - in the new version it was changed to 1 already :)
