### ISSUE TITLE
In getDeclarationAsString parameter names should be optional

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#64]
We should give the possibility to include or exclude them (as with do for modifiers and throws declarations).

So the user could choose if get something like:

```
void foo(int a, long b)
```

or

```
void foo(int, long)
```

**Comment by chundongwang** [comment]
Just found a deep-inside bug of my project caused by this and I prefer to at least have a parameter of showing variable name or not. :)

**Comment by sebastiankirsch** [comment]
Fixed by #92?

**Comment by ptitjes** [comment]
I guess we can close this one as well...

**Comment by ftomassetti** [comment]
I think #92 fixed this and we can close it. Let's reopen it if we are all wrong about that :)
