### ISSUE TITLE
Add missing optionals to builder methods

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#650]
In CompilationUnit I found a few that happily return null. Better check all the nodes.

**Comment by matozoid** [comment]
@DeepSnowNeeL can we call upon thee again?

**Comment by DeepSnowNeeL** [comment]
quite busy right now, I'll take a look when I have time and report the one i've found so you can fix them

**Comment by matozoid** [comment]
Well, I can do the looking too, since they are well documented :)
