### ISSUE TITLE
Calculating code coverage

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#66]
Given we are getting better tests, it could be nice to calculate also code coverage.
I am not familiar with anything for Java. 
Do you know something we could use?

**Comment by matozoid** [comment]
EMMA and Cobertura are common options - which does not mean they are the best, of course.

**Comment by ftomassetti** [comment]
Ok, I will take a look at both and start playing with the easiest one :)

**Comment by ftomassetti** [comment]
Note to myself: take a look at https://github.com/trautonen/coveralls-maven-plugin

**Comment by deepsidhu1313** [comment]
Julio Gessar also suggested me to use Cobertura with my project. However the version i checked was not properly built or had outdated scripts. So i reverted back to stable working version. But i didn't get much time to implement it in my project.

**Comment by SmiddyPence** [comment]
I'll take a look and either way look to close this out.

**Comment by ftomassetti** [comment]
Thanks! I tried to use coveralls but I did not manage to get a report

**Comment by ptitjes** [comment]
I used JaCoCo for the code coverage of JLaTo (Cobertura does not support Java 1.8) and the coveralls-maven-plugin to extract data from the collected data.

I always build JLaTo for OpenJDK 6, OpenJDK 7, Oracle JDK 7 and Oracle JDK 8 on Travis and the coveralls plugin aggregates the data, some seconds after Coveralls gets notified and generate a report.

You can take a look at JLaTo's [POM](https://github.com/ptitjes/jlato/blob/master/pom.xml) and [Travis build file](https://github.com/ptitjes/jlato/blob/master/.travis.yml). Also look at the README.md file for the badges.

**Comment by SmiddyPence** [comment]
Ta.  Yea you'll need some shenanigans to handle it being multi module.

Coming out at 60%, kind of understandable I think

https://coveralls.io/github/SmiddyPence/javaparser

**Comment by ftomassetti** [comment]
stupid question: is there a way to store a report online, so that it can be used to find out which areas need more testing?
For example I used to run JaCoCo on Jenkind (private instance) and there we could save files so we saved the HTML reports and serve them. I am not sure if we can do something similar using Travis or some specific service.

**Comment by SmiddyPence** [comment]
Well that is the Coveralls part.  JaCoCo creates and tradition ugly html.  Following the link you should see the stats per class.

**Comment by SmiddyPence** [comment]
Closing, currently 60% - badged in ReadMe.md
