### ISSUE TITLE
Make helper methods to access literal values

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#663]
All literal integers, doubles, etc, are stored as strings. Add methods to get and set these as their native type.

**Comment by ftomassetti** [comment]
+1

**Comment by arturbosch** [comment]
I want to take care of this issue :)

**Comment by ftomassetti** [comment]
Go for it!

**Comment by matozoid** [comment]
Wheeee!

**Comment by matozoid** [comment]
Some background:
- it's probably only the nodes extending `LiteralStringValueExpr`
- I think the most consistent would be to add a constructor that sets the value as the correct type by using:... a setter that does the same. And add a getter with a different return type. Since we can't overload on return type, we can use the `asString()` pattern we're using elsewhere, so that would be `asChar`
- probably prefer `long` over `Long` since the first is more often used, and a null value is invalid here anyway.
- I think the JDK already has all the methods that deliver conversion functionality. Just be sure the converter matches with what you can have in the source code.

I hope I haven't insulted your intelligence with this :)

**Comment by arturbosch** [comment]
so basically adding a new Constructor for each LiteralExpr and an asXXX() method?
We also don't want any conversion checks, so the user needs to handle it by himself, am I right?

**Comment by arturbosch** [comment]
For example there are two constructors one with a string, one with a string and a range like `public LongLiteralExpr(final Range range, final String value)`, should we create two new constructors, one with range, one without?

**Comment by matozoid** [comment]
Here are the patterns:
- there is always a default constructor that sets all values to something valid
- there is always a constructor that starts with `Range` - that's used by the parser and is seen as private.
- there is always a constructor with the same parameters as the one that starts with `Range`, but without `Range`. It's called the all parameters constructor. (Does not actually always have all the parameters ;) )
- there are a bunch of extra constructors that are considered useful to users.
- all constructors forward to the `Range` constructor with `this(....)`
- the `Range` constructor initializes the object by calling setters only. (The setters contain all kinds of extra code that keeps the AST consistent)

So I would say we need one or more (probably one, these are not complex objects) constructor in the "extra" category - your commit does that just fine. (I was thinking of forwarding to the setter, but that would break the above rules)

Then we need a getter *and* a setter. JavaParser loves mutability, unfashionable as it is nowadays. Your `asChar` is a fine getter.

Test things by parsing actual code:

```java
Expression expression = JavaParser.parseExpression("'\\n'");
System.out.println(expression);
```
The value of this `CharLiteralExpr` is two characters, so your conversion fails both ways here. We have an awkward utility function `StringLiteralExpr.escape` that does something related, but really we have a problem there by not being able to specify in the constructor if the string we're passing is escaped or not.

**Comment by arturbosch** [comment]
This issue is trickier than I thought :)

`JavaParser.parseExpression("25L")` is saved as 25L, so `Long.parseLong(value)` will throw an exception. Would testing for a `L` at the end of the string be enough?

I think that parsing `JavaParser.parseExpression("\\n")` should not be allowed as java does not allow this sequence as a char value. `\\\n` is not parsable which is right, why we support parsing `\\n`?

**Comment by matozoid** [comment]
I forward you to the JLS :) https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.10 - it has to be able to parse everything. Also check the `decode` methods that or `Integer` etc.

The JLS should supply a nice test set with all kinds of odd formats.

About parsing \\\n: if you look at this in Java source code, you will first see the character "backslash", then the character "n". So that's what I'm passing to the parser. "\\\n" is "the Java escape sequence for an end of line". "\n" is simply the end of line character. The first (including quotes) looks like this in source code:
```java
'\n'
```
the second like this:
```java
'
'
```
which is clearly invalid.

Your example with three backslashes is
```java
'\
'
```

**Comment by arturbosch** [comment]
So basically your saying we need to support conversions for binary, octal, hex etc formats too :D ?
And `underscores`? Will they still valid in Java9?

We do not have Float-, Byte- and ShortLiterals, you they should also be handled by Integer- and DoubleLiterals?

If you are looking at `\\n` in Java source code, you see see an CompileError. In JavaParser `"'\\n'"` is correct syntax in my editor not :O (or we have a misscommunication here :D)

**Comment by matozoid** [comment]
Yes, I think most of those are covered in the standard `decode` methods though!

Hadn't thought about that, but yes: float is handled by `DoubleLiteralExpr` etc, if you want me to check the grammar for what goes into what, just shout.

`\\n` is actually valid Java: it's an escaped backslash and an `n`. I'll take a look at what you're doing and see if I can break it :)
