### ISSUE TITLE
Generate getNodeLists() methods

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#666]
The metamodel will have information on all fields, so that can be used to correcly generate these methods.

**Comment by matozoid** [comment]
@ftomassetti - the interesting thing is that this information is available from the metamodel directly - we could remove these methods alltogether!

**Comment by ftomassetti** [comment]
That is a very good news, also because we are missing some node lists here and there, as I noticed working on the Concrete Syntax Model
