### ISSUE TITLE
Setup continuos integration

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#67]
Maybe we could have continuos integration using travis, to ensure all tests keep passing. 

I can take care of that if it is ok for you.

**Comment by matozoid** [comment]
There's one running at https://drone.io/github.com/matozoid/javaparser - but do set up what you like :)

**Comment by ftomassetti** [comment]
Cool!

It would be nice to have some widget telling if the tests are not passing and need to be fixed. Just because it makes the project looks so professional :D
