### ISSUE TITLE
ParseProblemExceptions when Parsing Multithreaded

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javaparser#671]
When concurrently parsing multiple files the JavaParser occasionally thows `ParseProblemException`s with the message: "Encountered unexpected token."

I think this has something to do with the `defaultInstance` member of the `JavaParser` class. After reverting the line 

`ParseResult<T> result = defaultInstance.parse(context, provider);`

in the `JavaParser.simplifiedParse(...)` to 

`ParseResult<T> result = new JavaParser(new ParserConfiguration()).parse(context, provider);`

everything works out fine again.

**Comment by matozoid** [comment]
*scratches head*
Not sure if I should call this a bug or a feature... :)

Let's call it a bug. The static parse method are supposed to be quick & easy. Concurrency problems aren't easy. We should roll this back.
