### ISSUE TITLE
It should not be possible to add a Field to an AnnotationDeclaration

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#676]
The methods `addField` should be overridden in `AnnotationDeclaration` to return `UnsupportedOperationException`

**Comment by matozoid** [comment]
Alternatively we can add those methods to a new NodeWithFields, and put that on EnumDeclaration and ClassOrInterfaceDeclaration only. You would need to cast when you only have a TypeDeclaration then, and my question is "does that happen a lot?"

**Comment by ftomassetti** [comment]
I am not sure. As a user I tend to prefer getting an UnsupportedOperationException if I am doing something stupid instead of having to cast, but it is just a personal taste, I would be happy we any of those two alternatives

**Comment by matozoid** [comment]
I agree with not liking casting. Still, if we rarely use the "TypeDeclaration" type, then I prefer static type checking (not having the methods) over dynamic (throwing exceptions.)
