### ISSUE TITLE
The range of the ArrayType is wrong

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#678]
Example:
```
String code = "public @interface ClassPreamble { String[] author(); }";
...parsing...
AnnotationDeclaration ad = cu.getAnnotationDeclarationByName("ClassPreamble").get();
AnnotationMemberDeclaration md = (AnnotationMemberDeclaration)ad.getMember(0);
Type type = md.getType();
```

The range of `type` is line 1, col 41-42 while it should be col 35-42.

**Comment by ftomassetti** [comment]
I suggest we fix it in ArrayType.wrapInArrayTypes:

```
    @SafeVarargs
    public static Type wrapInArrayTypes(Type type, List<ArrayBracketPair>... arrayBracketPairLists) {
        for (int i = arrayBracketPairLists.length - 1; i >= 0; i--) {
            final List<ArrayBracketPair> arrayBracketPairList = arrayBracketPairLists[i];
            if (arrayBracketPairList != null) {
                for (int j = arrayBracketPairList.size() - 1; j >= 0; j--) {
                    ArrayBracketPair pair = arrayBracketPairList.get(j);
                    Range range = null;
                    if (type.getRange().isPresent() && pair.getRange().isPresent()) {
                        range = new Range(type.getBegin().get(), pair.getRange().get().end);
                    }
                    type = new ArrayType(range, type, pair.getAnnotations());
                }
            }
        }
        return type;
    }
```

If this works for you I will send a PR

**Comment by ftomassetti** [comment]
I have created in a branch a test and a fix for this. It is branch issue678 on my fork, built on top of issue677

**Comment by matozoid** [comment]
I just came back from holiday and can't think straight yet. What does it do? Include the type in the range?

**Comment by ftomassetti** [comment]
Yes, basically it does that. I think that the range of the ArrayType should be either invalid or as long as the type, while for `int[]` I get a range of 2 characters

**Comment by matozoid** [comment]
Okay, but what about `int a[]` ?

**Comment by ftomassetti** [comment]
right, well, I think there are two cases: the case in which we return a type as it exists on the file and a case in which we calculate a type and return it.

`int[] a` -> type existing on file
`int a[]` -> type calculated

in the first case the range is obvious and it can be properly calculated, in the second case instead the range is not obvious because the type was calculated combining two different pieces. In such case we could return a no-range maybe, to indicate that this element is somehow _virtual_ or _calculated_, not something really present on the file itself in this form

**Comment by matozoid** [comment]
Hmmm, that's rather non-obvious behaviour. Can you tell me more about your use case, so we can figure out what's best?

**Comment by ftomassetti** [comment]
my use case is about lexical preservation: I need the correct range to figure out which tokens belong to a certain node

**Comment by matozoid** [comment]
I've tought about it for a while and I can see your approach now. Please PR :)

**Comment by ftomassetti** [comment]
Related to this: also the range of the ArrayCreationLevel inside an ArrayCreationExpr seems wrong

**Comment by matozoid** [comment]
Okay, I didn't respond to the last remark because it just seems so backwards to me to set the range of an array creation level to anything but the area marked by [ and ]... If you want to know which tokens belong to it: the first one is [ and the last one is ], right?

**Comment by ftomassetti** [comment]
I agree, the ArrayCreationLevel should point to the area between '[' and ']' but it seems to not doing that at this moment. I added a few tests on that in #706

**Comment by matozoid** [comment]
Oh right, I thought you wanted it to cover the whole ArrayCreationExpr too :) Cool!

**Comment by matozoid** [comment]
@ftomassetti didn't this go in 3.0.1?

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by ftomassetti** [comment]
oh, I was pinged a few times on this one...

**Comment by ftomassetti** [comment]
We have two PRs merged, I would close this one
