### ISSUE TITLE
Node.remove seems not to work with comments

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#682]
Probably because the comment could be a child of the parent of the commented node.

Note that it does not explode, it just returns false because it cannot remove the comment. So it is not 100% a bug, more a missing feature.

**Comment by ftomassetti** [comment]
A partial solution could be to override remove in Comment:

```
    @Override
    public boolean remove() {
        if (this.commentedNode != null) {
            this.commentedNode.setComment(null);
            return true;
        } else {
            throw new UnsupportedOperationException();
        }
    }
```

So that at least the comments associated to a node can be removed.

**Comment by matozoid** [comment]
Let's get #598 off the ground :) Before that, hacks are okay. PR?
