### ISSUE TITLE
Parent of previous value is not removed in all setters

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#692]
When we use setters we do not remove the parent for the existing value. Consider this test:

```
    @Test
    public void whenSettingANewNameTheOldNameHasNoParent() {
        ClassOrInterfaceDeclaration decl = new ClassOrInterfaceDeclaration(EnumSet.noneOf(Modifier.class), false, "A");
        SimpleName originalName = decl.getName();
        assertTrue(decl == originalName.getParentNode().get());
        decl.setName("AnotherName");
        assertEquals(false, originalName.getParentNode().isPresent());
    }
```

I would expect the `originalName` to have no parent after we replace it. Unfortunately this is not the case. It means we should fix all setters...

**Comment by matozoid** [comment]
I have seen the same thing, mainly because childNodes would have nodes that were overwritten by a setter previously (and should have been gone.)

**Comment by matozoid** [comment]
Leaving this for past 3.0.0, since it is a lot of work, and is marginal enough not to get noticed until now.

**Comment by matozoid** [comment]
This was done while generating the setters.
