### ISSUE TITLE
getScope of MethodCallExpr should return Optional<Expression>

### ISSUE THREAD

**Issue by arturbosch** [javaparser/javaparser#695]
Like FieldAccessExpr.getScope() returns an Optional, I think MethodCallExpr should also return one.

Is there a specific reason for this difference? 

If not I can provide a PullRequest. Already tested in the source code and only four Visitors needed to be adjusted.

**Comment by matozoid** [comment]
The reason is that we forgot. Please open a PR, tomorrow we'll release version 3.0.0 so this is just on time :)
