### ISSUE TITLE
Explicitly set plugin versions in pom

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#698]
Set them all to the newest versions.

**Comment by jeandersonbc** [comment]
Is this still open? I noticed that the root pom.xml file already has a `properties` node with the plugin versions from modules:

```{xml}
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>

        <!-- Maven Plugins -->
        <javacc-maven-plugin.version>2.6</javacc-maven-plugin.version>
        <maven-clean-plugin.version>3.0.0</maven-clean-plugin.version>
        <maven-compiler-plugin.version>3.5.1</maven-compiler-plugin.version>
        <maven-install-plugin.version>2.5.2</maven-install-plugin.version>
        <maven-jar-plugin.version>3.0.2</maven-jar-plugin.version>
        <maven-release-plugin.version>2.5.3</maven-release-plugin.version>
        <maven-resources-plugin.version>3.0.1</maven-resources-plugin.version>
        <maven-jacoco-plugin.version>0.7.7.201606060606</maven-jacoco-plugin.version>
        <maven-coveralls-plugin.version>4.2.0</maven-coveralls-plugin.version>
        <bnd-maven-plugin.version>3.2.0</bnd-maven-plugin.version>
</properties>
```

As far as I understood, these flags are shared across the `core` and `testing` modules although there is a duplicated property (`java.version` is redefined in core's pom.xml file).

**Comment by matozoid** [comment]
Okay, I don't see any plugin warnings coming by when compiling or releasing anymore, so I guess this is done.

java.version is probably duplicated because we used to compile core with a different Java version than the rest. Better leave that until we decide to remove that completely.
