### ISSUE TITLE
Build issue with Maven 

### ISSUE THREAD

**Issue by nguyenthanhvuh** [javaparser/javaparser#704]
Hi, I am trying to build javaparser (the latest version 3) from src on a Debian 8 system with Oracle jdk8 but keep getting some error about 

`[ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:3.2.0:bnd-process (default) on project javaparser-core: Execution default of goal biz.aQute.bnd:bnd-maven-plugin:3.2.0:bnd-process failed: A required class was missing while executing biz.aQute.bnd:bnd-maven-plugin:3.2.0:bnd-process: org/slf4j/LoggerFactory`

Attached is the full log when running `mvn clean install -X`

[error.txt](https://github.com/javaparser/javaparser/files/697604/error.txt)

**Comment by nguyenthanhvuh** [comment]
Could it be because the Debian's slf4j library 1.7.7-1 is too old  ?

**Comment by matozoid** [comment]
Try upgrading your maven.

**Comment by nguyenthanhvuh** [comment]
Thanks.  Upgrading to latest version of Maven 3.3.9 works.   Note that the default maven version of Debian 8 works with JavaParser 2.5, but no longer works with JavaParser 3.0.
