### ISSUE TITLE
Maven Modules

### ISSUE THREAD

**Issue by SmiddyPence** [javaparser/javaparser#71]
I propose splitting the project into three modules:

**core** - Main module with all the libraries code
**grammar** - Contains grammar and generated sources
**acceptance-tests** - All the JBehave bases testing

Rational - Not plainly obvious what code is generated and that you have to run javacc:javacc initially from the command line.  The IDE can get pissy while referencing src files from the target directory.

Any other suggestions logical divisions, names there of...

**Comment by SmiddyPence** [comment]
Ok so should have realised, that there would be a cyclic dependency between core and grammar.  So grammar is generating the src files directly to core atm.

Thoughts?

https://github.com/SmiddyPence/javaparser/tree/Milestone2

**Comment by arouel** [comment]
It should basically work in same way as an ANTLR grammar generates sources before the compilation starts. So it should require only the right phase in the lifecycle to ensure everything works well.

The separation into **grammar** and **core** sounds not like a good idea to me. The grammar could be hidden for users and therefore I do not see any value in a separate module for it. It should be completely encapsulated and isolated to the outer world.

**Comment by SmiddyPence** [comment]
The problem is not really a lifecycle issue.  It is that the generated code references non generated code and vice versa.  So ultimately you have to end up with the compilation happening in one module, where all the src resides.  Rather than having one module depend on the other.

I'm not clear on your second concern, you seem to imply hiding is bad; but then claim it should be encapsulated?  

From an end user point of view, there is no difference they add a jar and use it as normal, nothing changes.  The separating is mainly for maintenance to help people understand that some code is generated.  It will also make the generated sources first class citizens; making debugging and working with the IDE easier; rather than having to attach src files from the target directory.

**Comment by arouel** [comment]
If they depend on each other it does not make sense to separate it into two JARs. In case we want to provide also OSGi meta data you get trouble because of that circular reference. I do not see any maintenance improvements by separating it. That an end user understand how it works together is questionable and can easily be solved with documentation on class-level. And that it brings easier working with in an IDE can be solved by packaging everything useful into the corresponding `*-sources.jar`.

**Comment by SmiddyPence** [comment]
To a certain extent I agree while there are circular dependencies, it doesn't make sense to have only a grammar file in a module. However it does not always have to be this way, hopefully we can refactor this, as it is somewhat of a smells.  That is exactly my point to have a *-sources.jar", but it would be built from a separate module using vanilla maven rather than the assembly plugin or some such.

Perhaps you can have a crack at it then, I think the following problems need solving as they are current problems, rather than conjecture.

A)  Checking out the code then executing "mvn clean install" does not currently work.  You have to manually invoke the javacc goal.  This is currently confusing for users who in the past have even raised issues for the project being broken.  

B) When importing the project into the IDE there should be no compilation errors.  Again this is a current problem that faces users, it looks like the project doesn't build properly until they invest time into why it isn't working.

**Comment by matozoid** [comment]
I was worried, so I tried A, but the maven build seems to work perfectly. The build server hasn't failed either, so that's probably a local issue.

For B I tried Intellij IDEA. Import the project by opening the pom, open the Maven Projects tab, find and run the javacc:javacc goal, and everything is fine. I guess you might want javacc:javacc to run automatically, but that probably requires a plugin.

**Comment by SmiddyPence** [comment]
My mistake then I though A).  Guess I should have read #60 more carefully.

**Comment by SmiddyPence** [comment]
Ok so I have reverted more to the status quo as people seem to be happier with that.  Although I have kept the separate testing module.
**javaparser** - Parent
**japa** - All Library Code
**japa-test** - Acceptance Test Code

Just on the names @matozoid have you considered a domain other than the verbose and fairly ugly.  com.google.code.javaparser?  We could perhaps tweak the artifact & groups to be something more pleasant.  I guess this to do with not wanting to appear to "rip-off" the original author(s) works.

**Comment by arouel** [comment]
I suggest the artifact names:
**javaparser-parent** - Parent
**javaparser** (or **javaparser-core**) - All Library Code
**javaparser-testing** - Acceptance Test Code

In case we want to change the artifact and group name we should keep in mind that each one who is doing releases at Maven Central (as I did in the past) needs to request permission for the new coordinates at https://issues.sonatype.org/browse/ossrh.

What about creating a "javaparser" organization at Github and using this as package name (`com.github.javaparser`)?

**Comment by matozoid** [comment]
There was some discussion when we were doing the first release after moving the code from google code. I think the logic was: I don't want my nick (matozoid) on it, and I don't want people to spend time figuring out which group ID is the newest, so let's keep it at what it is. 

About splitting into modules: can't really judge, since I haven't done much developing on it. Feels like overkill though.

Feel free to ignore my opinion. My only role is keeping the project open and alive :)

**Comment by SmiddyPence** [comment]
Well that is one benefit of creating the org.  You can then transfer the ownership there and your name isn't directly associated to it.

People knowing the correct co-ordinates is problem - true, but there are two sides to that coin.  Some people might be looking for newer versions or documentation on a now dead project on google code.

**Comment by SmiddyPence** [comment]
I'm planning on creating a Milestone2 branch here and pushing my changes over for Java 8.  I plan on up versioning the pom to 2.0.0-SNAPSHOT.  I'm thinking that major versions numbers could be tied to Java versions. Or would people prefer 1.1.0...

Objections, suggestions?

**Comment by sebastiankirsch** [comment]
I'm sorry for commenting so late, but: what it is the reason for this "modularization"? I don't see why seperating the tests from the code is a good thing... shouldn't `mvn verify` on the "core module" tell me if everything is just fine? So why put the tests someplace else?
As mentioned in #73, I'd appreciate different modules for different functionality; like parsing and manipulating the AST for example.

And, @SmiddyPence, you were saying something about Java8 - so are you working on this issue or on #27?

**Comment by sebastiankirsch** [comment]
And concerning the version number: If you "break" the API, I'd prefer 2.0.0. If I can simply replace 1.0.11 with the new version without modifying the code, I'd go with 1.1.0.
See http://semver.org

**Comment by SmiddyPence** [comment]
Thanks for the versioning metaphor it sounds entirely sensible.

The reason for the split is that we are now running JBehave based testing.  These are considered by all extent to be integration tests. It my experience these are usually best separated into their own module. [Maven Docs](http://docs.codehaus.org/display/MAVENUSER/Maven+and+Integration+Testing), 

It is also the default assumption by the JBehave library that integration tests are run from a separate module.  

> because typically these have a cross-modular and cross-cutting concerns. 

The convention is also to include them in an `src` folder rather than a `test` folder, I like to think this promotes tests as first class code citizens (rather than maligned test code)

Your not the only one to think this is over the top, but I think it is generally easier to start tidy than change when you have more mass.

Also yes I am working on this and #27 hoping to make that the next milestone release.

**Comment by sebastiankirsch** [comment]
Well, that article is from 2008 or something. Integration tests should by run using failsafe nowadays (as listed in the article itself), eliminating much of the hassle that motivated the article. I'd agree that having an own "integration test module" for many modules that need to be tested in an integrated way makes sense, though. I also agree to put them in `src` if there's a specific test-module.

I don't have any experience with JBehave however, thus I don't know anything about JBehave's assumptions and general appliance.

> when you have more mass

Looking forward to that - and having Java8 support! ;)

**Comment by SmiddyPence** [comment]
Admittedly I have not used failsafe, but my understanding of is it really facilitates the running of integration tests along side unit tests; and managing the life cycle separately?   Admittedly not "best practice" but we are using integration tests in place of unit tests, so really they should run by default in the way unit test would.  

A few of us made the decision to favor one style of testing.  I can't speak for others, but personally I agreed to this as I think it is a bit much to ask open source commiters to do both and I think there is generally more value in integration testing. 

Also failsafe seems to facilitate pre and post phases that are needed more when you need to instantiate an environment and maintain a consistent state.  As this is library and inherently stateless, I for once I will cry overkill!

Would be a good conversation to have over a beer, I'm generally interested in hearing peoples experiences.  On a thread like this it can come across as argumentative, which is not my intention.

**Comment by sebastiankirsch** [comment]
> Would be a good conversation to have over a beer, I'm generally interested in hearing peoples experiences. On a thread like this it can come across as argumentative, which is not my intention.

Agreed. I was just giving my opinion, and this thread at least helped me understand your intentions better. It was not my intention to object on what you commiters agreed upon. After all, this seems to be more about personal flavors of doing things...

So I'm happily awaiting your changes ;)

**Comment by SmiddyPence** [comment]
The opinions are needed and appreciated.

How would you feel about @before suggestion of

> What about creating a "javaparser" organization at Github and using this as package name (com.github.javaparser)?

I think the `import japa.parser` is a bit poor and also the fact co-ordinates are still `com.google.code` is confusing.  Although this would be a breaking `2.0.0` change ;-) I think the version 8 support is as big a carrot as we can get for that.  Although I know @matozoid is less keen.

**Comment by matozoid** [comment]
Here you go -> https://github.com/matozoid/javaparser/issues/74

**Comment by SmiddyPence** [comment]
Done
