### ISSUE TITLE
Specific visitors for Expression and Statement classes

### ISSUE THREAD

**Issue by danwyryunq** [javaparser/javaparser#711]
This is more of a feature request than an issue. 
Separate and specific visitors for Expressions, and Statements might be usefull, to create cleaner code for those Visitors that only need to work on these particular sets of classes. 
Could be accomplished by just adding the necessary abstract  accept() methods to the Expression and Statement classes, (and it's implementations in the subclasses) without the need to create any new Visitable interfaces, and creating the corresponding  ExpressionVisitor. and StatementVisitor interfaces, of course.

**Comment by ftomassetti** [comment]
I wonder if in this case you could just use the Visitor Adapter and override all the methods related to the type of elements you are interested into (statements, expressions, other). Would that be enough or would this solution have advantages over using the adapters?

**Comment by danwyryunq** [comment]
I'm not sure I completely understand what the purpose of the Visitor Adapters are, but I guess that would be a decent solution to get shorter and cleaner Visitors as I mentioned. 
On the other hand, the advantages I see in the specific visitors are just purpose clarity, and the nicity of the IDE integration suggesting missing method implementations when implementing the classes that extend them. 
Anyway, it's just a suggestion, but the solution you suggest is perfectly useful.

**Comment by matozoid** [comment]
What we could make is a few visitors that implement everything empty (like the adapters) except for statement types for example. That would force extending visitors to implement all the statement visit methods. It's such a specific use case that I would like to keep this out of the core though.

**Comment by danwyryunq** [comment]
I like matozoid's much better.
I'm closing the issue, as there's no need to further discussion I think. 
Thanks for the ideas.
