### ISSUE TITLE
WildCardType should have the property SUPER_TYPES, not super

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#714]
This is wrong:
```
    public WildcardType setSuperTypes(final ReferenceType sup) {
        notifyPropertyChange(ObservableProperty.SUPER, this.superTypes, sup);
        this.superTypes = sup;
        setAsParentNodeOf(this.superTypes);
        return this;
    }
```

we should also add SUPER_TYPES in ObservableProperty

**Comment by matozoid** [comment]
Why is this labeled metamodel, by the way?

**Comment by ftomassetti** [comment]
Because it is about defining the structure of the data: things like ObservableProperty could be the representation of the metamodel at runtime. We could have a metamodel defined outside the core: we would use it to generate classes, including things like ObservableProperty, which permits to access some of the information of the metamodel when using JavaParser.

**Comment by matozoid** [comment]
Oh, true! Thanks :)

**Comment by matozoid** [comment]
This was done while generating all the observable code.
