### ISSUE TITLE
Introduce the ObservableProperty MaximumCommonType as a derived property

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#715]
I would add a flag `derived` to the ObservableProperty. It would `false` for all the existing properties.
I would then add a property named `MAXIMUM_COMMON_TYPE` with this flag set to true.

Would that makes sense @matozoid ?

**Comment by ftomassetti** [comment]
Potentially also `isUsingDiamondOperator` could be defined as a derived attribute

**Comment by ftomassetti** [comment]
Also `isGeneric`

**Comment by matozoid** [comment]
If this is of use to you, then go ahead. You're mr. Observable.

**Comment by ftomassetti** [comment]
Eh eh, nice. I wanted just to let you know, because it is related to what we discussed about the metamodel (having the concept of "derived property")

**Comment by matozoid** [comment]
Yep, it's on my nice-to-have list :)

**Comment by matozoid** [comment]
@ftomassetti we have several derived properties now. Are we done here? (I don't see `isGeneric` yet though)

**Comment by ftomassetti** [comment]
I think we can close this one
