### ISSUE TITLE
NodeWithJavadoc.getJavadoc and getJavadocComment return null

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#719]
This should be Optional.empty()

**Comment by arturbosch** [comment]
What about `Node.getComment()`? There will be many breaking changes, for which release are you planning this?

**Comment by matozoid** [comment]
3.1.0 I guess. Nothing big enough to warrant a 4 release, and these are not breaking features, they are breaking bugs. They need fixing.

**Comment by arturbosch** [comment]
Node.getComment returning null is OK? I would like to work on that issue

**Comment by matozoid** [comment]
That's fixed in my PR, but as that one is huge, it would make sense if someone made a small focused PR of it.

**Comment by matozoid** [comment]
Okay, now this one is fixed too - better leave it to me :)

**Comment by matozoid** [comment]
#658
