### ISSUE TITLE
Release Stable jar files time to time

### ISSUE THREAD

**Issue by deepsidhu1313** [javaparser/javaparser#72]
It will be great if you can upload stable jars of this project to be used as libraries. :) Thanks

**Comment by SmiddyPence** [comment]
The library is available through Maven Central.  You can download the jar or select a dependency management tool to use from here:

http://mvnrepository.com/artifact/com.google.code.javaparser/javaparser/1.0.11

**Comment by SmiddyPence** [comment]
I think this is covered and there was no follow up from the originator.
