### ISSUE TITLE
Method hasJavaDocComment should not be on Node

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#720]
Most nodes cannot have Javadoc. This should be on NodeWithJavadoc.

**Comment by ftomassetti** [comment]
I am not sure this is true: most nodes _should not_ have a Javadoc, but nothing prevents me to add it. For example what if the user write this:

```java
void foo() {
    /** javadoc */
    int a;
}
```

Here the variable has an associated comment, which happens to be a Javadoc comment

**Comment by matozoid** [comment]
Everything has been set up so only the nodes that can have Javadoc according to specs get those methods. Only this method is lost in Node. So either we change the whole approach - and I don't see why we should make it easy to put Javadoc on nodes where it is meaningless - or we move this method.

**Comment by ftomassetti** [comment]
My goal would not be users add Javadoc where it is not supposed to go, but I think we should parse existing code also if it is stupid. Considering someone is so idiotic to write the example I added before, how would that be parsed?

**Comment by arturbosch** [comment]
But would it change anything in the parsing mechanism?

 If I look at the method `public boolean hasJavaDocComment() {
        return hasComment() && getComment() instanceof JavadocComment;
    }` 
as an user I can still write javadoc over local variables for instance and get them with the `getComment()` method. I just have to do the `comment instanceOf JavadocComment` manually or do I miss the point?

So +1 for moving.

**Comment by ftomassetti** [comment]
If we are just making less easy to play with Javadoc comments where they are not supposed to be, but we permit to people to handle this corner case that I am perfectly fine with it

**Comment by matozoid** [comment]
@ftomassetti this is the case. Thanks for the discussion!

**Comment by ftomassetti** [comment]
Thank you, and sorry for the misunderstanding!

**Comment by matozoid** [comment]
Confused this one with all the other comment issues. Not done yet!

**Comment by matozoid** [comment]
Sorry for the mess.
