### ISSUE TITLE
How to use addStatement

### ISSUE THREAD

**Issue by mohsen-khaxar** [javaparser/javaparser#721]
Hi,
I want to use the method BlockStmt.addStatement but I receive this error message : "The method addStatement(Statement) is ambiguous for the type BlockStmt".
I use javaparser 3.0.0.
How can I solve it?

Many Thanks,

**Comment by matozoid** [comment]
Okay, what type are you passing to it? Do you have a few lines of code that demonstrate this?

**Comment by mohsen-khaxar** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5359609/22198475/e87a4964-e16b-11e6-99dd-44045642a71a.png)

I wanted to check JavaParser and for this, I passed null to the method.

**Comment by arturbosch** [comment]
Well if you pass null to the addStatement methods, of course three methods could be right:
`default N addStatement(Statement statement)`, `default N addStatement(Expression expr)` and ` default N addStatement(String statement)`. Every object can be null in Java, so the compiler is confused and asks for help :)

Try passing something like `addStatement(new NameExpr());`

**Comment by matozoid** [comment]
@mohsen-khaxar - if this is answer enough, please close the issue.

**Comment by mohsen-khaxar** [comment]
Thank you for your help.
You are right.
