### ISSUE TITLE
Version 3 requires Java 8 to compile because it uses the java.util.Optional class. Is it possible to change that to be used with Java 7?

### ISSUE THREAD

**Issue by JaviRpo** [javaparser/javaparser#722]
Version 3 requires Java 8 to compile because it uses the java.util.Optional class. Is it possible to change that to be used with Java 7?

**Comment by ftomassetti** [comment]
Unfortunately I think this would not be possible. Removing all usages of Java 8 would be a major change and Java 7 has been in end of life for almost 2 years now

**Comment by matozoid** [comment]
It's a conscious decision to go with Java 8 for version 3. We'll probably move to Java 9 in a year or two.

*thinks* it should be a neat side project to write a program using JavaParser that transforms the JavaParser code, removing Optionals... But that would have to be contributed by a user.

**Comment by matozoid** [comment]
Is this question answered?

**Comment by matozoid** [comment]
No response

**Comment by klaushauschild1984** [comment]
It would be nice to have the information about the major java version for every language feature. With that in hand you can "go" through all the projects sources, detect language features that have to be down graded and transform them into something compatible for your need.

**Comment by matozoid** [comment]
That actually sounds like a hilarious project - in a good way :) A Java source level downgrader! I'll make a new cool project idea for it.

**Comment by matozoid** [comment]
#870
