### ISSUE TITLE
com.github.javaparser.ast.imports classes missing from ver 3.0.0 onwards

### ISSUE THREAD

**Issue by tamtam22** [javaparser/javaparser#724]
Hi,

There are missing classes from version **3.0.0** onwards in **com.github.javaparser.ast.imports**

In 3.0.0 RC3, 
http://static.javadoc.io/com.github.javaparser/javaparser-core/3.0.0-RC.3/com/github/javaparser/ast/imports/package-use.html

SingleStaticImportDeclaration
SingleTypeImportDeclaration
StaticImportOnDemandDeclaration
TypeImportOnDemandDeclaration
BadImportDeclaration

The methods above are still present in 3.0.0 RC3 and not marked as deprecated.

However. these methods are no longer in the library/project since version 3.0.0 is released.

**Comment by matozoid** [comment]
Correct, they were removed after their introduction in one of the betas led to 100% negative response from several users. They cannot be reintroduced without thoroughly breaking the API.

If you tell us what functionality you are missing in ImportDeclaration, we can consider ways to introduce it.

**Comment by matozoid** [comment]
No follow up, closing.
