### ISSUE TITLE
Cleaning up

### ISSUE THREAD

**Issue by sebastiankirsch** [javaparser/javaparser#73]
When running [deadode4j version 2.0.0](https://github.com/ImmobilienScout24/deadcode4j), I stumbled over these classes that probably should be removed:
- `japa.parser.Position`
- `japa.parser.ast.TreeVisitor`

They were both introduced in late 2013, but are no longer used.

Also, I'd suggest moving class `japa.parser.ASTHelper` to the test source, as it is only used in that context. Then one could remove lots of methods which are not used.

Now I'll happily create a patch for this, I just wanted to ask what the policy is regarding downgrade compatibility - as there could be some people out there using those classes. So you might want to deprecate those classes now and remove them with the 2.0.0 release. Please indicate what your intentions are.

**Comment by ftomassetti** [comment]
Imho, ASTHelper could be useful not just internally but also for our users and probably the same could be true about the TreeVisitor. If Position is no longer used we can probably drop it, I do not know who could use it and for what reason...

As I said, just my opinion

**Comment by sebastiankirsch** [comment]
I thought javaparser's main purpose lies in parsing java files - therefore I don't see why anyone merely using the library would want to create AST nodes.

When looking at the TreeVisitor, I would assume that the other visitors in place are much more powerful and thus preferable from a library user's perspective. Also, this class was introduced in order to perform tests, thus my assumption it could be removed.
Although it is trivial to reproduce it's behavior, I won't deny that there could be someone being happy about the class' existence ;) But then, it should probably be moved to the `visitor` package.

Obivously, this is just my opinion...

**Comment by ftomassetti** [comment]
I agree that the main goal is to parse files but I think that in the long run we want also JavaParser to be useful for refactoring code (see for example #22), that is why it is useful to have methods to create nodes, move nodes, edit nodes.

I agree that TreeVisitor is trivial and probably no one is using it, I wanted just to say that I perceive JavaParser as a tool to parse and to manipulate ASTs, so the manipulate-part could be used by final users.

In general it would be nice to know better how JavaParser is used

**Comment by sebastiankirsch** [comment]
Ah, I wasn't aware of the direction JavaParser is headed, so I understand better now ;)

**Comment by SmiddyPence** [comment]
I think the direction it is heading is an interesting question.

Personally the value proposition this library had for me was that the was a "**Lightweight** Parser".  There is an eclipse.org library that offers an ASTParser, but that was massively bloated with things I didn't need.

I think if the product is aiming for "Lightweight" as it's proposition; additional functionality should be additive via additional libraries with people choosing what they want.  This kind of ties in to my motion of splitting the maven project into several modules, but that was not well received.

**Comment by sebastiankirsch** [comment]
As for me, I value the lightweight parsing aspect over anything else, too.

I'd embrace splitting up into modules based on "end-user functionality", e.g. a core for pure parsing and an additional module for manipulating the source code.

**Comment by ftomassetti** [comment]
I also agree that simplicity is a big plus (as @SmiddyPence said, JavaParser is way easier to use than ASTParser). I just thing that right now the other functionality (Something else or just ASTHelper?) are so limited that it does not yet make sense to split the project in different modules but I totally agree that if/when more functionalities are developed we should do that.

**Comment by ptitjes** [comment]
My 2 cents... (even if I did not contribute for a long long time)

I always used JavaParser for massive (pattern-matching based) refactoring and indeed ASTHelper is essential. Else you have to know all the details of the AST api. You have visitors then you must have a factory.

Please let ASTHelper in the API !

**Comment by ptitjes** [comment]
BTW, I now use Position in my grammar-work pull request (https://github.com/javaparser/javaparser/pull/108)

**Comment by sebastiankirsch** [comment]
That leaves the `TreeVisitor`, a construct similar to the one @ptitjes suggested in #91 - however, this isn't eligible for testing if every node has parent set, as nodes set themselves as children if the parent is set (the `TreeVisitor` traverses the children).
It would fit the needs of the PositionTestVisitor though, so I think this one can be closed.

**Comment by ptitjes** [comment]
@sebastiankirsch So we do keep TreeVisitor for now and close the ticket ?

**Comment by ptitjes** [comment]
@javaparser/owners What's the status for this ?

**Comment by ftomassetti** [comment]
Maybe we can add a separate module with these utilities class. The test module should have access to that module to use ASTHelper.

**Comment by ptitjes** [comment]
Let's not make a new module for one class. I think we can close that ticket. We will make a new run of deadcode4j before releasing 3.0.

**Comment by matozoid** [comment]
Please open a new ticket if anything specific needs to be done.
