### ISSUE TITLE
Generate PrettyPrintVisitor

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#731]
@ftomassetti - this one is for you :)

**Comment by ftomassetti** [comment]
Right after #705 

However I am not sure we will need to generate the PrettyPrintVisitor because we could instead interpret the concrete syntax model. The advantage of the PrettyPrintVisitor is that you can override a couple of methods if you want.

**Comment by matozoid** [comment]
For me, the advantage of generating the visitors is that there is no human in there accidentally introducing bugs. Now, the PPV is pretty well-tested because everyone uses it, so maybe that's not necessary.

How do we use the CSM instead of generating the PPV? What does that mean?

**Comment by ftomassetti** [comment]
On this machine it would take a bit to find the code but basically we have the CSM that for each node say something like: 

`CSM(ImportDeclaration) = sequence(keyword("package"), space(), property("name"), semicolon())`

Then there a class that could be called CsmPrettyPrinter with a method `prettyPrint(Node)` which take the node, look at the type and find the corresponding CSM and then interpret it. For example if it sees that the top level element is a sequence it will produce the string for the elements of the sequence and concatenate them. When it find something like `keyword("package")` it just produces a string. When it finds `property("name")` it will get the property name of the current node (more or less `ObservableProperty.NAME.getValueFor(node)`) and print it.

The same CSM will be then interpreted differently for lexical preservation: we will basically ignore things like "space" or "newline" and put there instead the actual tokens (space, tabs, comments). That is more or less the plan.

So by checking that interpreting the CSM we get the same thing we used to get from the PrettyPrintVisitor we are pretty sure the CSM is correct, then for lexical preservation we just need to interpret it differently, but at that point we just need to test the lexical-preserving interpretation of the CSM, not the whole CSM

**Comment by matozoid** [comment]
Am I right that we're talking about two different things? I'm on a quest to generate as much code as possible. You are on a quest for lexical preservation. For me it makes sense to generate the PPV, you are only using the PPV as a test case. Something like that?

**Comment by ftomassetti** [comment]
Ok, I started looking into this one

**Comment by matozoid** [comment]
We should have a brainstorm about how to do pretty printing and comment manipulation now we have the CST and lexical preservation.

**Comment by ftomassetti** [comment]
For now I am using the CST metamodel to generate the PrettyPrintVisitor

**Comment by ftomassetti** [comment]
I am facing a significant issues with the VariableDeclarator because of the array levels and the associated annotations.

**Comment by matozoid** [comment]
I am not surprised. :-D

**Comment by ftomassetti** [comment]
Do you think are we going to remove the PrettyPrintVisitor? In that case should we drop this task?

**Comment by matozoid** [comment]
Well, I have this idea because you suggested we could use the CST for pretty printing :-) And that cursor API can be used for reformatting, for example.

**Comment by ftomassetti** [comment]
Ok, then I will leave it for now and we could close the ticket as we delete the PrettyPrintVisitor. If we instead end up keeping it we will finish this work.

**Comment by matozoid** [comment]
Okay, do follow up on the array bracket trouble in the AST/CST
