### ISSUE TITLE
MethodDeclaration and ConstructorDeclaration share many fields -> new SuperType?

### ISSUE THREAD

**Issue by arturbosch** [javaparser/javaparser#738]
This two behave quite similar in java and also share a lot of fields in javaparser. I often want treat both the same in my smell detection code but then need to work with a BodyDeclaration and make casts. NodeWithDeclaration etc do not help that much here. That's quite a pain.

How about we introduce a super type for both of these. This is what both share:
```java
    private EnumSet<Modifier> modifiers;

    private NodeList<TypeParameter> typeParameters;

    private SimpleName name;

    private NodeList<Parameter> parameters;

    private NodeList<ReferenceType> thrownExceptions;

    private BlockStmt body;
```

Spoon (other java AST tool) has a CtExecutable node which do exactly the same as I propose. 
What do you think? I can also work on this issue..

**Comment by matozoid** [comment]
+1. Let's make sure we have a good name for it though, what do you suggest?

**Comment by arturbosch** [comment]
How about CallableDeclaration?

**Comment by matozoid** [comment]
Okay, if that goes in before the weekend I can still regenerate the metamodel for it.
