### ISSUE TITLE
How could I addStatement(0, "string") ?

### ISSUE THREAD

**Issue by yanOnGithub** [javaparser/javaparser#739]
In the manual, under "Creating a CompilationUnit from scratch", the sample code shows that I could add a statement by constructing the parse tree node by node. I find that inefficient. The addStatement(String) method does not take an index either. I am working around it by creating a NameExpr.

```java
    private static class MethodChangerVisitor extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(MethodDeclaration method, Void arg) {
            NameExpr expr = new NameExpr("logger.debug(1)");
            method.getBody().get().addStatement(0, expr);
            
        }
    }

```

**Comment by matozoid** [comment]
What I do in the generators is constructing a bit of code as a string, like your "logger.debug(1);" then using the parseStatement method on JavaParser.

[here for example](https://github.com/javaparser/javaparser/blob/master/javaparser-core-generators/src/main/java/com/github/javaparser/generator/core/visitor/HashCodeVisitorGenerator.java)

(in other methods I use addStatement(String), but that uses parseStatement internally)

You'll find more parse... methods in JavaParser for other situations.

Is this what you are looking for?

**Comment by yanOnGithub** [comment]
yes it worked thx
```java
addStatement(0, JavaParser.parseStatement("logger.debug(1);"));
````

**Comment by matozoid** [comment]
Tip: add `import static com.github.javaparser.JavaParser.*;` and you can leave the `JavaParser.` part off :)
