### ISSUE TITLE
Change package and maven group id

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#74]
These two are left over from the project's life on Google Code.

Suggestions for improvements below:

**Comment by matozoid** [comment]
Created a "javaparser" organization, maybe we should make it the official location of the project.

**Comment by SmiddyPence** [comment]
Personally I think it is a good idea for an org in the long run.

Changing co-ordinates is not ideal, but I think makes more sense than maintaining the old ones now the project has moved hosting.

We can perhaps have a fuller gh-pages site with not just the JavaDoc, but information about the project past a present. As well as how to use etc.

**Comment by sebastiankirsch** [comment]
+1

**Comment by arouel** [comment]
+1

**Comment by SmiddyPence** [comment]
So this branch: https://github.com/SmiddyPence/javaparser/tree/Milestone2

Has **Java 8**, **Maven Modules** and **Updated package name & Maven Co-ordinates**.

Do people want to review it there first or shall I create a Milestone2 branch here and push it over?

**Comment by SmiddyPence** [comment]
Hi @matozoid

Can you transfer the repo to the organization?  

I can then update the `issueManagement` etc sections of the pom with the correct urls. Before the SonaType release.

**Comment by matozoid** [comment]
Repository has been transfered!

**Comment by SmiddyPence** [comment]
Cool I have raised the ticket.

Do you own the existing drone.io build?  Will need to move the repo url there as well... If you don't I can just add it to my drone account; no worries.

**Comment by matozoid** [comment]
Better get that drone.io build off my account, so I can leave things to active users and committers like you! I'll delete mine. A good time to see if there's a nicer build site out there too.

**Comment by sebastiankirsch** [comment]
I'd recommend [Travis CI](https://travis-ci.org).

**Comment by ftomassetti** [comment]
+1 for Travis: I am using  it for different projects and I am happy with it (I have nothing against drone.io anyway)

**Comment by SmiddyPence** [comment]
I left it as drone.io for the time being, just because it took about ~30 seconds.  If someone wants to set up Travis feel free, I didn't feel the need just to execute "mvn clean install".  Perhaps when #66 comes about the extra control will be useful.

In any case closing this now as the modules are in place.
