### ISSUE TITLE
How could I insert a statement before all return stmts in methods?

### ISSUE THREAD

**Issue by yanOnGithub** [javaparser/javaparser#740]
```java
    private static class ReturnChangerVisitor extends ModifierVisitor<Void> {
        @Override
        public Node visit(ReturnStmt returnStmt, Void args) {
        	// TODO: insert a println before the return stmt
        	return returnStmt;
        }
    }
```

What the return statement is a thenStatement w/o braces?

```java
if(1==1) return 1;
```

Should I write a method that goes thru the whole parse recursively?
```java
private void changeReturnStmts(Node node) {
    // TODO: recursion
}
```

**Comment by matozoid** [comment]
Do you want
`if(1==1) { println(); return 1; }`
or
`println(); if(1==1) return 1;`
?

**Comment by yanOnGithub** [comment]
```java
if(1==1) { println(); return 1; }
```

Another thing I am gonna do is to force all if-then-else to have braces, and then log which branch is taken. So I will have to add the braces to if-then w/o braces anyway.

**Comment by matozoid** [comment]
If I run this code:
```java
Statement statement = JavaParser.parseStatement("if(a) x();");
Statement statement2 = JavaParser.parseStatement("if(a) {x();}");

// This visitor is on master, not yet released
TreeStructureVisitor treeStructureVisitor = new TreeStructureVisitor();

statement.accept(treeStructureVisitor, 0);
statement2.accept(treeStructureVisitor, 0);
```

I get
```
IfStmt
	NameExpr
		SimpleName
			identifier: a
	ExpressionStmt
		MethodCallExpr
			SimpleName
				identifier: x
```
and
```
IfStmt
	NameExpr
		SimpleName
			identifier: a
	BlockStmt
		ExpressionStmt
			MethodCallExpr
				SimpleName
					identifier: x
```
... so it looks like you'll have to wrap that `ExpressionStmt` in a `BlockStmt` if you visit an `IfStmt` with a `then` or `else` that is an `ExpressionStmt`.

Of course, you can ask the same question for something like `while(true) return 5;` or anything that takes a block statement.

**Comment by yanOnGithub** [comment]
Simple depth-first recursion worked but I haven't got TreeVisitor working.

```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at com.github.javaparser.ast.visitor.TreeVisitor.visitDepthFirst(TreeVisitor.java:41)
	at com.github.javaparser.ast.visitor.TreeVisitor.visitDepthFirst(TreeVisitor.java:42)
	at com.github.javaparser.ast.visitor.TreeVisitor.visitDepthFirst(TreeVisitor.java:42)
	at com.github.javaparser.ast.visitor.TreeVisitor.visitDepthFirst(TreeVisitor.java:42)

```
```java
	private static class ReturnStmtAddLogVistor extends TreeVisitor {
		public void process(Node node) {	
			if(! (node instanceof ReturnStmt)) {
				return;
			}
			
			ReturnStmt returnStmt = (ReturnStmt) node;
			BlockStmt parentBlock = (BlockStmt) node.getParentNode().get();
			MethodDeclaration method = node.getAncestorOfType(MethodDeclaration.class).get();
			int childIndex = parentBlock.getChildNodes().indexOf(node);
			if(method.getType() instanceof VoidType) {
				parentBlock.addStatement(childIndex, JavaParser.parseStatement("logger.debug(\"methodReturnValue:void\");"));
			}
			else {
				parentBlock.addStatement(childIndex, JavaParser.parseStatement(method.getType().toString() + " methodReturnValue = " + returnStmt.getExpression().get() + ";"));
				returnStmt.setExpression(JavaParser.parseExpression("methodReturnValue"));
			}
		}
	}
```

**Comment by yanOnGithub** [comment]
ModifierVisitor seems to hang in an infinite loop if I am inserting **before** the return stmt.

```java
	private static class ReturnStmtChangerVisitor extends ModifierVisitor<Void> {
		@Override
		public Node visit(ReturnStmt returnStmt, Void arg) {
```

**Comment by matozoid** [comment]
Too bad about TreeVisitor, I guess it gets a conflict when we're changing the tree it is visiting. Needs improvement.

**Comment by matozoid** [comment]
Your ModifierVisitor code is cut short, I can't see what you're doing there.

**Comment by yanOnGithub** [comment]
```java
	private static class ReturnStmtChangerVisitor extends ModifierVisitor<Void> {
		@Override
		public Node visit(ReturnStmt returnStmt, Void arg) {
			BlockStmt parentBlock = (BlockStmt) returnStmt.getParentNode().get();
			int indexInParent = parentBlock.getChildNodes().indexOf(returnStmt);
			MethodDeclaration method = returnStmt.getAncestorOfType(MethodDeclaration.class).get();
			if(method.getType() instanceof VoidType) {
				parentBlock.addStatement(indexInParent, JavaParser.parseStatement("logger.debug(\"methodReturnValue:void\");"));
			}
			else {
				parentBlock.addStatement(indexInParent, JavaParser.parseStatement(method.getType().toString() + " methodReturnValue = " + returnStmt.getExpression().get() + ";"));
				returnStmt.setExpression(JavaParser.parseExpression("methodReturnValue"));
			}
			return returnStmt;
		}
	}
```

**Comment by yanOnGithub** [comment]
In addition to visitBreadthFirst and visitDepthFirst, do you think right-to-left sibling iteration, i.e. for n-1 downto 0, will avoid the infinite loop? How about pre-order and post-order?

**Comment by matozoid** [comment]
I debugged your modifiervisitor code (you can do so too ;) ) Every time you say "addStatement" you are inserting a new value in the NodeList that the visitor is currently visiting. It will never get to the end if you keep adding things :) I'm not sure what the best fix would be. The idea is to say "have I already inserted logging here? Then don't do it again."

**Comment by matozoid** [comment]
Yes, iterating backwards would help, but it is quite a hack.

Feel free to open issues for adding other ways of traversal.

**Comment by yanOnGithub** [comment]
Did you use iterator or index? Insertion should change the indices after the insertion point but not the iterators.

**Comment by matozoid** [comment]
I'm thinking you could reverse the approach: instead of finding `ReturnStmt` and going up, you could find `Statement` and use `getNodesByType(ReturnStmt.class)` - that should prevent messing up the visitor state. I'll go think if I can find a decent way to fix visiting NodeList.

**Comment by matozoid** [comment]
Up for the next release: #745

You can override the visit(NodeList n, A arg) in your modifiervisitor if you want it right now.

**Comment by yanOnGithub** [comment]
Let's close this for now. Who knows which behavior is the best in future? Anyway there is always the good old DIY recursion.
