### ISSUE TITLE
From the source code, how could I find the corresponding node in the parse tree?

### ISSUE THREAD

**Issue by yanOnGithub** [javaparser/javaparser#747]
Just the grammar, please. In #744 , I was banging my head at FieldDeclaration instead of BodyDeclaration and members. I would like to learn the names of the nodes in the parse tree.

http://stackoverflow.com/questions/38811186/javaparser-where-is-the-java-grammar-definition/38812859

**Comment by matozoid** [comment]
I'm afraid that the answer there is correct: the jj file is the grammar, and you'll have to learn to read it. It is not that hard when you finally get it :)

For example:
```
EnumConstantDeclaration EnumConstantDeclaration():
{
	NodeList<AnnotationExpr> annotations = new NodeList<AnnotationExpr>();
	AnnotationExpr ann;
	SimpleName name;
	NodeList<Expression> args = emptyList();
	NodeList<BodyDeclaration<?>> classBody = emptyList();
	Position begin = INVALID;
}
{
  {  }
  ( ann = Annotation() { annotations = add(annotations, ann); begin = begin.orIfInvalid(ann.getBegin().get()); } )*
  name = SimpleName() { begin = begin.orIfInvalid(tokenBegin()); } 
  [ args = Arguments() ] [ classBody = ClassOrInterfaceBody(false) ]
  { 
      return new EnumConstantDeclaration(range(begin, tokenEnd()), annotations, name, args, classBody);  
  }
}
```

is

```
EnumConstantDeclaration ::=  ( Annotation )*  SimpleName  [ Arguments ] [ ClassOrInterfaceBody ]
```

**Comment by yanOnGithub** [comment]
https://java.net/downloads/javacc/contrib/grammars/java-1.7.jj

The jdk1.7 one contains less embedded code.

**Comment by matozoid** [comment]
Yes, that is because we extended it a lot for JavaParser. If you want our Java 8 grammar without code, you will have to filter the jj file. Maybe simply removing everything between { and } will make it more readable.

**Comment by yanOnGithub** [comment]
iirc there is a javacc grammar for javacc, that could be used to remove the embedded code in the jdk1.8 grammar.

**Comment by matozoid** [comment]
Cool, good luck!

**Comment by matozoid** [comment]
Yesterday I was thinking that the question behind this question seems to be: do you have documentation? If you say you want to learn the names of the nodes, do you want a document that describes the structure of each of them? Can the TreeStructureVisitor on master help? Does the Javadoc on the nodes help? Maybe @ftomassetti can generate pseudo-BNF from his concrete syntax model? Would you like to see this in the book, on the wiki, on javaparser.org, or in a blog post?

**Comment by yanOnGithub** [comment]
The TreeStructureVisitor that you have shown in #740 shows only identifiers. It would be nice to add the parens and braces. It should be enough for small parse trees.

I am looking for something that I can associate parts of the source code with the node names within the parse tree.

Imagine a parse tree visualization that looks like explorer folders, that I can click on "private static Logger logger = XXX;" to learn the node name to be BodyDeclaration instead of FieldDeclaration. Having the BNF still requires brain-parsing. Tree structure is not obvious from the javadoc.

Take a look at Antlr TestRig on google images.

**Comment by DeepSnowNeeL** [comment]
I had a hard time too when I started using javaparser learning all the
nodes names.

Something like the antlr TestRig is definitely something which would be
nice to have !

I imagine a static utility method "Util.show(Node)" which would popup a
swing tree defining the structure and for each node, when I click it, there
is the associated ouput on a textfield on the right.


Le jeu. 2 févr. 2017 à 10:47, yanOnGithub <notifications@github.com> a
écrit :

**Comment by matozoid** [comment]
I use the Java debugger for that :D But that's not very professional, so let's see...

You want to input some code like `int a;`, you probably want to pick a rule like `VariableDeclarationExpr`, you want to see the hierarchy of AST nodes generated, their properties, and you want to have the syntax bits like `(` `)` `,` `[` intersected?

The syntax bits will require the CSM that @ftomassetti is making.
Graphical output sounds nice-to-have.
An interactive application sounds nice-to-have.

( @SmiddyPence was looking for something like this for the book.)

**Comment by yanOnGithub** [comment]
http://stackoverflow.com/questions/23446263/parse-tree-representation-using-javacc

Xml parse tree output should help, too. Folding is readily available.

**Comment by yanOnGithub** [comment]
![image](https://cloud.githubusercontent.com/assets/25423046/22548430/45ea4ba4-e981-11e6-96be-2668b5702c60.png)

Notepad++ can fold indented text already. Try pasting the output of TreeStructureVisitor and view the source code as python. We may not need another tree explorer swing GUI to get folding. You have already shown the non-terminals and identifiers. Add parens/braces/binary operators may or may not help. I have yet to experiment.

Note that Antlr TestRig out of the box may not be the best tool to go from parts of the source code to the node name in the parse tree. You could go from the tree nodes to the source but not the other way around. Antlr TestRig with "Ctrl+F" for searching by "original source code" or "pretty-printed source code" should work. In windows explorer top right search box, you could type a filename and get a list of search results. Double-clicking one of them leads to the folder. "Ctrl+F" comes in various flavors in various tools.

**Comment by yanOnGithub** [comment]
DIY recursion + Node.toString().matches(regex) would work, too.

**Comment by matozoid** [comment]
The TreeStructureVisitor:
- is easy to change by overriding the methods that do the output.
- is a first attempt at writing something like this, so this is good input.

I was considering output in [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) format for example. Maybe XML or yaml or JSON. All of these could probably be implemented simply by overriding those methods. It would certainly be the easiest approach to what you're asking. I'll make some issues.

**Comment by yanOnGithub** [comment]
graphviz DOT format does not support folding.

**Comment by matozoid** [comment]
But it does generate awesome diagrams!

**Comment by IrfanKhanKakar** [comment]
Hi, i have a File which contain Java projects,
know i want parser this file and generate UML Class diagram.

but when i writ  : 	CompilationUnit compilationUnit = JavaParser.parse(file);

its give me an Error, due to CompilationUnit not import in java package,

i try a lot to load http://javaparser.org    library in my eclipse, but its not working.  

kindly anyone help me........................

**Comment by SmiddyPence** [comment]
Hi,

This is now a closed issue if you have questions I recommend using the public chat [channel](https://gitter.im/javaparser/javaparser?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

There is also usage documentation on the [Wiki](https://github.com/javaparser/javaparser/wiki) and in the [Book](https://leanpub.com/javaparservisited)

In the case you describe it sounds like your problem is not to do with the library, but how you are including the library on the project's classpath in eclipse. Perhaps try checking the [starter project](https://github.com/javaparser/javaparser-maven-sample).
