### ISSUE TITLE
Add pre-in-post-order visiting to TreeVisitor

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#751]
As described here: https://en.wikipedia.org/wiki/Tree_traversal#Generic_tree
Currently we only seem to have in-order.

As suggested in #740

**Comment by matozoid** [comment]
The most interesting thing is figuring out what the nicest API is, and how to keep things backwards compatible.

**Comment by yanOnGithub** [comment]
btw i have yet to figure out a use case for this.

**Comment by matozoid** [comment]
That's okay, it just seems to be a sensible thing to have :)

**Comment by ryan-beckett** [comment]
Hi @matozoid, my name is Ryan and I would like to contribute to this project. Nice to meet you! This is the first issue I'd like to try and implement, and I have some questions. Firstly, the JUnit test "TreeVisitorTest.depthFirt()" appears to test for pre-order visiting, not in-order. Can you confirm this? Second, you spoke of "figuring out what the nicest API is" and "keep things backwards compatible". Can you clarify upon these issues? What's wrong with adding "visitInOrder(), visitPreOrder(), etc." to the class? Thanks.

**Comment by ryan-beckett** [comment]
So, how would you even define what the in-order traversal would be on a non-binary tree (See [ref](http://stackoverflow.com/questions/3429006/can-a-non-binary-tree-be-tranversed-in-order))? That further  backs my aforementioned confusion about @matozoid saying we have in-order. I don't see an issue with just having preOrder(), postOrder(), and breathFirst().

**Comment by matozoid** [comment]
Hi! Thanks for your offer :)

- for what it should do, I'd like to refer to @yanOnGithub . I can say that I hadn't considered any of this before, and put this issue here so we could think about it when we got to it. Which is now, I guess.
- from your ref I understand the in-order is defined as however we want to define it. So if you think there's a good way to define it, go ahead, otherwise don't.
- for backwards compatability: before we get to version 4.0.0, we should not break the API when we introduce new features. So the current API should stay, but we can deprecate things that we would like to get rid of. For example: there is a "process(Node)" method - maybe you want to change the name.
- API idea: we might want to split up into a BreadthFirstVisitor and DepthFirstVisitor so that the methods to implement match the algorithm it uses.
- API idea: maybe replace process(Node) by functional stuff (but only if it improves things)

Do you have any other suggestions?

**Comment by ryan-beckett** [comment]
1.  I think giving API clients the choice of pre/post/breadth-first order is enough to satisfy the majority of their needs (i.e. Pretty Printing, Symbol tables). Unless you can think of a use case where visiting the first one... two... or however many children, processing the node, and then visiting the rest of the children is needed, I don't see the need to define and implement an in-order traversal.

2. Thanks. This makes things clearer.  The comments for visitDepthFirst() should at least denote it's doing a pre-order traversal. I think adding more visitor classes just bloats things, but perhaps you foresee a good reason to. And if so, I'm all ears. I don't have much experience applying patterns. Alternatively, we could deprecate visitDepthFirst(), and add visitPreOrder() and visitPostOrder(). I like the latter option frankly.

3. I have no ideas for the functional stuff.

**Comment by matozoid** [comment]
1. I have no idea about use cases - although I was thinking of reworking the `TreeStructureVisitor` #753 to use the TreeVisitor since it treats all nodes the same. As I said: maybe @yanOnGithub has more ideas.
2. Do you think there's a chance that people will want to use several at the same time? If not, then please do as you prefer. If I sounded confused in my previous answer, that is because I was :)
3. Passing a `Consumer<Node>` to the visit method would allow you to pass a lambda to it, like `visitXxx(root, n -> println(n));` - the only negative is a slight performance hit, I think.

**Comment by matozoid** [comment]
Hi @ryan-beckett - how is it going?

**Comment by ryan-beckett** [comment]
Hi @matozoid, sorry, I've been really busy this week. I'm going submit a pull request to be reviewed, and we'll take it from there.

**Comment by ftomassetti** [comment]
hi @ryan-beckett , while working on a long running PR I had to add a new method to traverse trees. You can find in #786. Do you have comments on that? Is that conflicting with what you are working on? Can we go ahead and merge it?

**Comment by matozoid** [comment]
Oops, forgot to close this one!
