### ISSUE TITLE
Investigate code from @ducmle for TreeStructureVisitor

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#754]
Last post in #538 with the zip file.

**Comment by matozoid** [comment]
Hey @ducmle - I'll take a look at this.

**Comment by matozoid** [comment]
Well, I tried to define "compound" as "a node that has at least one field that is a node," and that didn't work, because every node can have a comment, which is a node, so every node is compound.

**Comment by ducmle** [comment]
Hi @matozoid, Thanks for your interest.

How about excluding the comment because technically comment should be removed in the syntactic grammar (according to JLS 1.8)?

In the code, I also use toStringWithoutComments to print the node content.

**Comment by matozoid** [comment]
Hmmmm, I think the whole TreeStructureVisitor needs a good rethinking... Keep an eye on #753 too, by the way.

Note that toStringWithoutComments in gone in 3.0.0, it has been replaced by toString(PrettyPrinterConfiguration) or PrettyPrinter.print(node), and setting the configuration to not print comments.

**Comment by matozoid** [comment]
This is being worked on.
