### ISSUE TITLE
Please omits empty parenthesis of no arg annotation when output AST source code texts

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#756]
@NotNull vs. @NotNull() :)

**Comment by DeepSnowNeeL** [comment]
That's the difference between MarkerAnnotationExpr and the 2 other annotation
nodes. (You might be using SingleMemberAnnotationExpr)

But I'm ok with you, we should have only one type of annotation node

**Comment by matozoid** [comment]
We can do two things:
- print `SingleMemberAnnotationExpr` with no content as `@NotNull` - but what would be the point of `MarkerAnnotationExpr` then?
- collapse all the annotation types into one. That will have to wait until 4.0.0 though, and we're not even thinking about starting work on 4.0.0 yet :)

**Comment by ghost** [comment]
That's help, thank you.

**Comment by matozoid** [comment]
I'll close this then, and open an issue for collapsing the annotation types.
