### ISSUE TITLE
Improve sorting algorithms

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#76]
A rather horrible sort was found here: https://github.com/matozoid/javaparser/pull/75

Fix it by using built in JDK sorting algorithms, and search around for more of these bubble sorts.

**Comment by ftomassetti** [comment]
Maybe PositionUtils.sortByBeginPosition could be a good candidate (also, the name of the variable arrayNodos is misspelled)

**Comment by ftomassetti** [comment]
Created a pull request for this one (pull request #94 ). Do we have more of those?

**Comment by ptitjes** [comment]
Can we close this ?

**Comment by matozoid** [comment]
Sí

**Comment by ftomassetti** [comment]
@matozoid ar you learning Italian?

**Comment by matozoid** [comment]
No, aprendo español. ¡Tengo amigos en España!

**Comment by ftomassetti** [comment]
oh well, close enough :D
