### ISSUE TITLE
Add annotation to methods and classes that were generated

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#770]
... to indicate that they were.

Java has a `@Generated` annotation which requires the generator class as a parameter. This is messy, but I think it's the best option: no additional dependencies, no custom annotation, and it is a sensible thing to mention what generated the code.

```java
@Generated("com.github.javaparser.generator.core.node.GetNodeListsGenerator")
@Override
public List<NodeList<?>> getNodeLists() {
    return Arrays.asList(getMembers(), getAnnotations());
}
```

It might be possible to automate this in the `VisitorGenerator` class, not sure about the `NodeGenerator`

**Comment by arturbosch** [comment]
+1, they would also indicate not to try to refactor generated code
