### ISSUE TITLE
Documentation should specify that JavaParser.parse() closes the InputStream passed. 

### ISSUE THREAD

**Issue by Parth** [javaparser/javaparser#774]
+ From the book:
>For convenience, although we’re creating an instance of a FileInputStream we do not need to concern ourselves with closing the resource, the parse method will take care of this.

+ [And from the source](https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/JavaParser.java#L112).

Parsing an InputStream might not be the only thing an InputStream will be used for. And this assumes it is. A user, for example, might call parse, then upon success, save the file somewhere else. We should either not close the InputStream that the user passes, or we should say that the parse() will in the documentation ([No mention of close() in the docs](http://static.javadoc.io/com.github.javaparser/javaparser-core/3.1.0-beta.1/com/github/javaparser/JavaParser.html)). 

Would be happy to contribute fix, if deemed needed.

**Comment by matozoid** [comment]
Thanks, please do open a PR :)

**Comment by matozoid** [comment]
Hi @Parth-Mehrotra - are you still working on this issue?

**Comment by Parth** [comment]
Hi, I'll take a look this weekend, and update this issue.

**Comment by matozoid** [comment]
Hey @Parth-Mehrotra - are you still on this?
