### ISSUE TITLE
Go through the changes in the JLS for Java 9 once it is released

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#788]
... and make issues for relevant changes.

**Comment by matozoid** [comment]
For now I can only find the JLS diff for project Jigsaw.

**Comment by matozoid** [comment]
I'm pretty sure we're complete, unless they make a last minute change to Jigsaw.

**Comment by DeepSnowNeeL** [comment]
like not going for modules or delay it :P since IBM & red hat are not happy
with it :p

Le ven. 12 mai 2017 à 21:58, Danny van Bruggen <notifications@github.com> a
écrit :

**Comment by matozoid** [comment]
Uhuh, that will certainly be in the news :-)

**Comment by phax** [comment]
A public draft is available: http://cr.openjdk.java.net/~iris/se/9/java-se-9-pr-spec-01/java-se-9-annex-3.html

**Comment by matozoid** [comment]
Let's have another look then

**Comment by matozoid** [comment]
Thanks you @phax - your link was very useful for adding a new feature that nobody seems to have noticed!
