### ISSUE TITLE
Add a lambda visitor syntax

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#804]
Add a method with approximate syntax `apply(Class<T extends Node>, Function<T, ?> f)` to `Node` which visits the whole tree and calls the function for all nodes matching the class.

This could be implemented with a more generic  `apply(Function<T, ?> f)`.

Maybe find the correct name for this method, and if there is an existing approach in the functional programming world.

**Comment by ftomassetti** [comment]
+1 for this feature

It should be easy but it would require some understanding of how generics work

**Comment by matozoid** [comment]
I just ran into the `Files.list` `walk` and `find` methods - we could follow that pattern.

**Comment by matozoid** [comment]
https://www.npmjs.com/package/1tree has some as well:
walk, walkUp, find, contains, and maybe findAll, closest, ancestors...
