### ISSUE TITLE
com.github.javaparser.ast.expr.LambdaExpr does not set itself as parent of its child nodes

### ISSUE THREAD

**Issue by sebastiankirsch** [javaparser/javaparser#82]
I will come up with a pull request for that shortly...

**Comment by sebastiankirsch** [comment]
I didn't come up with a test for this, as I'm not sure if this warrants a jbehave test and I'm not sure what the situation is with unit tests... Any input on this?

**Comment by SmiddyPence** [comment]
I would just add another `then` to the existing Lambda tests.  Then have a `assertThat(lambdaExpr, is(blockStmt.getParentNode()))`

I have just free-handed this, so it might not be perfect... 

https://gist.github.com/SmiddyPence/f8922ab21c233e686c1b

Or I can add it afterwards if you prefer.

**Comment by sebastiankirsch** [comment]
Thanks for the hint, I added the assertions.
