### ISSUE TITLE
Add modifier does not notify about the change

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#822]
In NodeWithModifiers:

```
    default N addModifier(Modifier... modifiers) {
        getModifiers().addAll(Arrays.stream(modifiers)
                .collect(Collectors.toCollection(() -> EnumSet.noneOf(Modifier.class))));
        return (N) this;
    }
```

This does not cause a notification. We could refactor it to invoke setModifiers, which does. The problem is we cannot call notifyChange directly from here I think.

**Comment by matozoid** [comment]
The problem remains though - people can still do `getModifiers().add(...)`. We solved this for `List` by making `NodeList`... We can do the same here.
