### ISSUE TITLE
Make Modifier a Node

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#834]
`Modifier` misses `Range` information.

Since this means it cannot be an enum anymore, stop using `EnumSet`. Consider if it is worth the effort to make a `NodeSet` or that we can get away with using `NodeList`.

(Interesting: what if we can change the backing list for NodeList, and get other features like sorting, or forcing uniqueness?)

**Comment by matozoid** [comment]
Considering #912, maybe simply mix up annotations and modifiers in the same list.

**Comment by ftomassetti** [comment]
Yes, things seem to push in this direction
