### ISSUE TITLE
com.github.javaparser.ast.body.Parameter.getType() can be null since 2.0.0

### ISSUE THREAD

**Issue by sebastiankirsch** [javaparser/javaparser#84]
I assume a parameter's type being `null` only occurs for lambda expressions, thus why it didn't pop up until now.

This causes `NullPointerException`s at least for
- `com.github.javaparser.ast.visitor.GenericVisitorAdapter`
- `com.github.javaparser.ast.visitor.ModifierVisitorAdapter`
- `com.github.javaparser.ast.visitor.VoidVisitorAdapter`

The other adapters seem to be unaffected, one of them was explicitly adapted to it. I'd appreciate a double-check of this.

Before introducing a mere `if (parameter.getType() != null)` everywhere, I wanted to discuss how this should be approached. Does it make sense to introduce a new class representing lambda parameters? Although lambda parameters can have a type too, it seems that it's the only instance a paramater can have no type. Or am I missing something?

**Comment by ftomassetti** [comment]
imho would be better to avoid using null. Solutions that come to mind:
1) As Sebastian suggested we could create a class that represent a Lambda parameter
2) use an Optional (but it could require add Guava, which is probably overkill, or create our own Optional class, which is probably a bad idea). 
3) maybe we can create a class to represent the lack of type something like:

```
class Untyped extends Type {
```

**Comment by ptitjes** [comment]
As suggested by @ftomassetti, I think we need to introduce a Type object which denotes the fact that a type is not explicitly specified.

I would rather call it NonSpecifiedType or UnknownType than UndefinedType or Untyped which would not have the same meaning.

From a technical point of view it is just a null object.

**Comment by ptitjes** [comment]
Pull request: https://github.com/javaparser/javaparser/pull/116
