### ISSUE TITLE
Save filepath/filename in CompilationUnit

### ISSUE THREAD

**Issue by shibumi** [javaparser/javaparser#842]
It would be nice if JavaParser.parse(Filename) could return the filepath/filename in the returned Object.

**Comment by matozoid** [comment]
On one hand: this would mean refactoring `SourceRoot`, on the other hand: this would enable more validations (class matches filename, package declaration wrong, etc.)

**Comment by shibumi** [comment]
At the moment we have an "information leak". When i for example iterate over a big java project and produce CompilationUnits for every file and sort these units into a bigger modell, I would like to have the filepath/filename for every CompilationUnit. I am sure that also other projects would profit from this changes.

**Comment by matozoid** [comment]
Yes, it's probably a good thing and this will be built. In the end it is a design decision, but since our approach is "the Abstract Syntax Christmas Tree" full of decorations, this can go in too.

**Comment by shibumi** [comment]
@matozoid cool awesome!
