### ISSUE TITLE
Casting a lambda expression causes a parsing failure

### ISSUE THREAD

**Issue by sebastiankirsch** [javaparser/javaparser#85]
I failed to parse some Java 8 files with lambda expressions; my stack trace was something like this

```
java.lang.NullPointerException
    at com.github.javaparser.ast.Node.setAsParentNodeOf(Node.java:331)
    at com.github.javaparser.ast.expr.MethodCallExpr.setArgs(MethodCallExpr.java:96)
    at com.github.javaparser.ast.expr.MethodCallExpr.<init>(MethodCallExpr.java:63)
    at com.github.javaparser.ASTParser.PrimarySuffixWithoutSuper(ASTParser.java:3180)
```

Obviously, the provided arguments was a list containing a `null` value. I boiled it down to a simple statement that cannot be parsed:

```
Stream<CharSequence> stream = Stream.generate((Supplier<CharSequence>) () -> "Fail");
```

Removing the cast makes the problem go away.

As this is certainly to be fixed within the `java_1_8.jj` file, I won't come up with a fix (this stuff is just beyond me). I can however set up a branch with a test case or something.

**Comment by SmiddyPence** [comment]
Ouch, I hadn't even considered that.  Not sure I'm entirely comfortable with it either!

**Comment by sebastiankirsch** [comment]
So, I added the branch [issue-85](https://github.com/javaparser/javaparser/tree/issue-85) and there, adapted the old java_1_7.jj file such that it is easier to spot which changes have been made.

**Comment by sebastiankirsch** [comment]
Based on that, look at [line 1966](https://github.com/javaparser/javaparser/blob/7a693327ae45239d14107bed68ec4498edea87ad/javaparser-core/src/main/javacc/java_1_8.jj#L1966): there, the existing expression `ret` is set to `null`.
Removing this else-branch makes the parser succeed. However, the `EnclosedExpr` has no inner expression set; thus the parsed compilation unit looks like this

```
Stream.generate((Supplier<CharSequence>) ());
```

Better, but not done. I'll dig a bit more into that, but I really don't understand much of this javacc stuff. Maybe @rpau can help... you are the original author of the 1.8 additions, aren't you?

**Comment by sebastiankirsch** [comment]
In [line 2812](https://github.com/javaparser/javaparser/blob/7a693327ae45239d14107bed68ec4498edea87ad/javaparser-core/src/main/javacc/java_1_8.jj#L2812), the expression is set to `null` as well... changing this has no effect on my test case, however.

**Comment by sebastiankirsch** [comment]
Well, if I change the `CastExpression()` definition in [line 2267](https://github.com/javaparser/javaparser/blob/7a693327ae45239d14107bed68ec4498edea87ad/javaparser-core/src/main/javacc/java_1_8.jj#L2267) such that it allows an `Expression()` instead of an `UnaryExpressionNotPlusMinus()` (I assume line 2265 is not correct as well), the test case works just fine. However, javacc issues a bunch of warnings now. To me, this indicates the lamdba stuff should have been added to the `UnaryExpressionNotPlusMinus()` instead of the `Expression()` definition. This would, as far as I can tell, also make the lambda additions in lines 2781-2814 unnecessary.

I'll go further down this road, but again: I have no idea what I'm doing here...

**Comment by SmiddyPence** [comment]
I think it takes someone to go down the rabbit hole.  I follow what your saying, but I'm not sure what the correct course is.  It may even be another option not stated.

On the background I merged the grammar from @rpau 's repository.  It wasn't a complete copy as there were some deviations already between the two projects.

https://github.com/rpau/javalang/blob/master/src/main/javacc/java_1_8.jj

**Comment by sebastiankirsch** [comment]
So I had a look at the [PMD grammar file](http://sourceforge.net/p/pmd/code/ci/master/tree/pmd-java/etc/grammar/Java.jjt) - and they have a very familiar AST defined there (which may or may not be surprising; I can't tell). The biggest difference there is that they defined the Lambda stuff in the `PrimaryPrefix` section, which I was pondering about after my last comment as well.  
I'm starting to comprehend this syntax slowly, but I'm not sure if I can adapt it.

**Comment by rpau** [comment]
@sebastiankirsch I can take a look with my tests and I will tell if I can help you as soon as possible ;)

**Comment by rpau** [comment]
@sebastiankirsch I have solved this bug on my grammar. Check the last commit (e622a591a247c9c32d457dffbe11c99bc22e373e)

**Comment by sebastiankirsch** [comment]
Thanks, I will have a look at it!

Note to self: [this is the relevant commit](https://github.com/rpau/javalang/commit/e622a591a247c9c32d457dffbe11c99bc22e373e)

**Comment by sebastiankirsch** [comment]
So I applied the changes and it works. However, I really think someone that is more into this javacc grammar should take the [PMD](http://sourceforge.net/p/pmd/code/ci/master/tree/pmd-java/etc/grammar/Java.jjt) stuff as a basis and adapt it; our lambda handling just feels awkward in comparison.

However, in order to fix this, I'll open up a pull request with the "working" adaptation.
