### ISSUE TITLE
Removing MethodCallExpr from the parent node

### ISSUE THREAD

**Issue by fruffy** [javaparser/javaparser#858]
Hello, 
I have a question about the remove method.
I would like to remove method calls which are encapsulated in various types of parent nodes. ( ReturnStmt, ExpressionStmt, BinaryExpr...). However, the method always defaults to Node.remove() and returns false in all these cases. 
What would be the best way to remove a method call here? Unfortunately, I could not get it to work with a ModifierVisitor.
The end goal is to use the javasymbolsolver to replace method calls with the respective cfg of their declarations.

Best,
FRuffy

Example:
```
private int buildCFG(int numbers) {
		while ( numbers < 3 ) {
			int j = 3;
			numbers++;
		}
		System.out.print("exit");
		return numbers;
}
```
should turn into
```
private int buildCFG(int numbers) {
		while ( numbers < 3 ) {
			int j = 3;
			numbers++;
		}
		return numbers;
}
```
for now.

**Comment by matozoid** [comment]
Ah, I tried it out and see your problem. `Node.remove()` turns "please remove X" into "parent of X, please remove X" - because the parent is the one that contains the node. The nasty thing is that `MethodCallExpr` for example is wrapped in an `ExpressionStatement` so that it can be used as a statement inside the method body. `ExpressionStatement` ignores the remove request, because the contained `MethodCallExpr` is not optional. You would have to remove the `ExpressionStatement` instead. Remove does not do this for you.

The good news is: `ModifierVisitor` *does* do this for you.

```java
public class RemoveExpression {
    public static void main(String[] args) {
        CompilationUnit cu = JavaParser.parse("class X{private int buildCFG(int numbers) {\n" +
                "\t\twhile ( numbers < 3 ) {\n" +
                "\t\t\tint j = 3;\n" +
                "\t\t\tnumbers++;\n" +
                "\t\t}\n" +
                "\t\tSystem.out.print(\"exit\");\n" +
                "\t\treturn numbers;\n" +
                "}}");

        cu.accept(new ModifierVisitor<Void>() {
            @Override
            public Visitable visit(MethodCallExpr n, Void arg) {
                if (n.getName().getIdentifier().equals("print")) {
                    return null;
                }
                return super.visit(n, arg);
            }
        }, null);

        System.out.println(cu);
    }
}
```

**Comment by matozoid** [comment]
If you really want to, I think you can emulate this behaviour by calling `remove` on X, then parent of X, then parent of parent of X, etc. until one of them returns `true` - meaning it was removed.

**Comment by fruffy** [comment]
Thank you, that worked! I used the while(!remove()) loop to remove the call in question.

I have another question mildly related to this one.
As far as I understand. Node.setAsParentNodeOf(Node) does not really register a node in the AST.
So if I added a node to my method block above, it would not be handled by the visitor, or at least the print visitor. Only if I use operations such as addStatement etc.., I am able to add new fields which are also printed. 
Why is that? Or what is the functionality of setAsParentNodeOf/setParentNode?

I am wondering because I am currently running into a problem where I would like to add a Statement to a parent node. But since the type of getParentNode() is generic I have to cast to many Statement and Expression types before being able to properly add a node.

**Comment by matozoid** [comment]
Just use the correct setter or adder, they will do parent management for you. These methods will be made protected when we move to Java 9.

I'm not sure what you're doing in your last paragraph. A piece of code would help.

**Comment by fruffy** [comment]
> These methods will be made protected when we move to Java 9.

Ah that is good to know, I was not sure if they were actually intended to be used.
So basically, what I have is this method declaration. I would like to statically resolve all method calls in it using the Java standard library which I have parsed using the Symbolsolver.


```
private int buildCFG(List<Method> methList) {
	int j = 3;
	for (int i = 0, k = 2; i < methList.size(); i++) {
		j = 123;
		j++;
	}
	System.out.print("exit");
	return j;
}
```

(For now) I would like to resolve it to:

```
private int buildCFG(List<Method> methList) {
	int j = 3;
	for (int i = 0, k = 2; i < methList.size(); i++) {
		j = 123;
		j++;
	}
	if (s == null) {
	    s = "null";
	}
	write(s);
	return j;
}
```
which is the body of the print statement. 
However, if I used
```
BlockStmt newBody = declarationBody.get().clone();
	for (Node n : newBody.getChildNodes()) {
		methodCallParent.setAsParentNodeOf(n);
}
```
The resulting output of toString() or a TreeVisitor is missing the added nodes entirely.
```
private int buildCFG(List<Method> methList) {
	int j = 3;
	for (int i = 0, k = 2; i < methList.size(); i++) {
		j = 123;
		j++;
	}
	return j;
}
```

What I have to do right now is check the type of the parent node, cast it, and then use the addStatement methods to get it to work.
Since I will have to account for every possible parent type or combination for a method call this quickly turns into madness.


```
BlockStmt newBody = declarationBody.get().clone();
if (methodCallParent instanceof BlockStmt) {								
	for (Node n : newBody.getChildNodes()) {
		int childIndex = methodCallParent.getChildNodes().indexOf(methodCallExpr);
		if (n instanceof Statement) {
			((BlockStmt) methodCallParent).addStatement(childIndex, (Statement) n);
			childIndex++;
		} else if (n instanceof Expression) {
			((BlockStmt) methodCallParent).addStatement(childIndex, (Expression) n);
			childIndex++;
		}
	}
} else {
	methodCallParent.setAsParentNodeOf(newBody);
}
```

I assuming we cannot use setParent as it would violate the syntax constraints of Java.  I am new to all of this and tried it out because I only needed the tree structure of the AST and not a syntactically correct output.
I am thinking about a proper implementation currently, but it seems quite complicated and would involve preliminary transformation of the code into a normalised version. For example: 
`if (methodCall())`
would turn into
`boolean check0 = methodCall(); if(check0)`
which is easier to resolve.

**Comment by matozoid** [comment]
Okay, let's see...
- working with directly setting parents will only affect the `childNodes` list, no other fields. This will do nothing but make the AST inconsistent.
- if you're saying "I want to replace every method call expression with X" then that sounds like you need the ModifierVisitor to me, with one overridden visit method for `MethodCallExpr` that finds the replacement for its parameter and returns that replacement.
- if you want to get access to `addStatement` on a `Node`, check if it is an instance of `NodeWithStatements`. Check out all the other `NodeWith...` interfaces, we're using them as a kind of cheapo multiple inheritance.

I think I'm not answering the whole question, so feel free to ask more.

**Comment by fruffy** [comment]
Great, thank you! It was mostly confusion about the purpose of `setAsParentNodeOf()` but since it is intended to be protected I won't use it.
I am already using a `ModifierVisitor` but wasn't aware of the `NodeWith...` classifications.
The answer was mostly about what I am intending to use the Javaparser for and to see what the API could do. I will probably run into further issues down the road so I thought it would be good to provide  some context.

**Comment by matozoid** [comment]
Cool, see you soon then :-)
