### ISSUE TITLE
Add method removeForced()

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#859]
In #858 there is a little trick to make sure `remove()` really removes the node by walking up the hierarchy.

Add it to `Node`.

(Naming: if it starts with "remove" it will show up next to the normal `remove` method in tools. `forced` could be a parameter of remove instead of its own method, but that would mean that everyone has to think about this option every time the method is used. In theory it would be better to reverse the naming and let `remove()` always succeed, and a method like `removeFromParent()` could fail, but that will break the API.)

**Comment by matozoid** [comment]
@FRuffy if you're interested you can pick this up :)

**Comment by fruffy** [comment]
Yeah sure I can take a look!
Edit: I have not forgotten this feature, I just have not been able to work on the project recently. Will do a pull request soon.
