### ISSUE TITLE
VoltProcTools uses java-symbol-solver 0.3.1 and javaparser 2.3.0

### ISSUE THREAD

**Issue by raffishquartan** [javaparser/javaparser#860]
https://github.com/cfogelberg/vpt

**Comment by ftomassetti** [comment]
Thank you for sharing! It helps a lot to know about these projects to learn how we can help.

**Comment by raffishquartan** [comment]
javaparser is a great tool. There was a bit of a learning curve with the API but I think that's pretty unavoidable with something like this. I haven't used java-symbol-solver much yet but will be using it more soon. Thanks for all your work and all the work of the other contributors too!

**Comment by matozoid** [comment]
I put it on this page :) https://github.com/javaparser/javaparser/wiki/Projects-using-JavaParser

If you have suggestions for making things easier, do share.

**Comment by matozoid** [comment]
I'll close this since it's no question or issue.
