### ISSUE TITLE
Is this tool can use in java 7 ?

### ISSUE THREAD

**Issue by coderlindacheng** [javaparser/javaparser#868]
hello,

my question is just as the title.

thanks.

**Comment by matozoid** [comment]
This is a Java 8 library. Version 2.5.1 is Java 6 compatible, but it is no longer supported.

Java 7 has been end-of-life for two years and is now a security risk. http://www.oracle.com/technetwork/java/eol-135779.html#Java7-end-public-updates

**Comment by coderlindacheng** [comment]
thanks your replies

but my project is depended on java 7,i can't change the production situation.but i want to make some sugars into my project(aka i want to generate some code automatically).

so,what you means is , this tool just satisfy in java 6 and java 8,not in java 7 ? is that right.

**Comment by coderlindacheng** [comment]
by the way, i found this project because project lombok.
i want to custom it,but i found is to difficult.
so ,i just want to find some tool to help me writing a project to do so

**Comment by matozoid** [comment]
This tool will *parse* all Java version up to 8 (and a little of 9.)
To *use* this tool you will need at least JDK version 8.

I understand that many companies use outdated Java version, I see this often in my job. I think that is irresponsible, and maybe you can use JavaParser as a reason to move to Java 8.

To make JP run with an older JDK would take a lot of work. Also see #722

You can search for other tools that parse Java and see what their requirements are, I know there are several.

**Comment by matozoid** [comment]
I guess this is answered?

**Comment by coderlindacheng** [comment]
yes,thanks lot
