### ISSUE TITLE
Dummy implementation of setJavaDoc and getJavaDoc: should we change it?

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#87]
There are a lot of comments like:
 "//To change body of implemented methods use File | Settings | File Templates." 

(see for example AnnotationDeclaration)

**Comment by ftomassetti** [comment]
Looking better at it the problem seems that we have a lot of classes with these methods:

```
    @Override
    public void setJavaDoc(JavadocComment javadocComment) {
        //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public JavadocComment getJavaDoc() {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }
```

Maybe we should implement it correctly in Node, so we do not have to repeat it over and over. Probably the implementation in Node should throw an exception (I think we can add a Javadoc to a limited number of nodes, while most cannot be documented) and a few nodes should just save the value and return it.
Thoughts?

**Comment by SmiddyPence** [comment]
Interesting question.  

I would suggest that Node is too loose, I'd guess that the majority of subtypes are not actually DocumentableNodes.

What about a "delegate" although I have always liked the term "mixin" it's just not Java! 

http://stackoverflow.com/questions/263121/java-traits-or-mixins-pattern

**Comment by ftomassetti** [comment]
Yes, it makes sense: the implementation in Node would throw an exception and all the classes implementing DocumentableNode would use the delegate to just save the value. If you agree I can go on and implement it in the week-end (or earlier maybe)

**Comment by SmiddyPence** [comment]
Sounds good to me, unless there are other suggestions.

**Comment by sebastiankirsch** [comment]
I didn't get the exception throwing in Node... why is that necessary?

Also, not sure about introducing a delegate for one plain field without any logic attached to it. Is it worth the effort? Wouldn't object, however.

**Comment by SmiddyPence** [comment]
I think the premise is that it is cleaner than all the null checking in all ~10 document-able types.

**Comment by sebastiankirsch** [comment]
Alright then, at least a bit of logic ;)

**Comment by SmiddyPence** [comment]
Agree as a pattern it tends to be for more elaborate logic.

**Comment by ftomassetti** [comment]
Well, I would argue that is good to report some error to the user trying to assign a Javadoc to a node that cannot be documented. I think it is very bad to have silent failures

**Comment by sebastiankirsch** [comment]
In general, I agree.  
But I thought that only those classes that really support it do implement the DocumentableNode interface and thus should integrate the delegate? So, there would be no need for an exception to be thrown...

I feel like I'm missing something... :O

**Comment by ftomassetti** [comment]
Oh, you are probably right, I saw some implementations returning null and I thought it was a method declared in Node but it seems not the case, sorry for the confusion. Then no need for exceptions :)

**Comment by ftomassetti** [comment]
pull request #93 prepared
