### ISSUE TITLE
Parse error for non-fully-qualified types in JavaParser 2.4.0

### ISSUE THREAD

**Issue by huangwaylon** [javaparser/javaparser#871]
I am using version 2.4.0 of JavaParser (due to a need to maintain Java 7 compatibility, I cannot upgrade to the latest version of JavaParser).

I am interested in simplifying type names.
For instance, the line:
`org.apache.commons.lang3.math.Fraction fraction0 = org.apache.commons.lang3.math.Fraction.ONE_QUARTER;`

should be simplified to the line:
`Fraction fraction0 = Fraction.ONE_QUARTER;`

after we add the import statement:
`import org.apache.commons.lang3.math.Fraction;`

I am able to add the import statement successfully. The approach that I have taken to simplifying type names has been to step through each statement in a method. I have iterated through the entire method and obtained all the names of the reference types using a visitor. I also maintain a map from fully-qualified type name to simple type name, using some simple string processing. 

I then take the statement, convert it to a string, and do a text substitution. To add the converted statement back into the compilation unit, I need to call:
`Statement newStatement = JavaParser.parseStatement(stmt);`
However, this always throws a `ParseException` for statements without the fully-qualified type name.

How can I resolve this issue? Version 3.0.0-alpha4 and above works fine, the parseStatement method's implementation has changed. Is there a better approach to this problem?

Thank you very much.

**Comment by matozoid** [comment]
Okay, indeed 2.4.0 has many bugs that have been solved. There is no support on that version. On the other hand: if someone wants to release a 2.4.1 we will help do the release.

Two things:
- how about switching to 2.5.1? Does that solve it?
- you say parseStatement fails on a certain kind of string. Do you have an example string?

**Comment by huangwaylon** [comment]
Hi, thanks for the comment!

The String that parseStatement fails on is:
`Fraction fraction0 = Fraction.ONE_QUARTER;`
since that statement doesn't contain the fully qualified type name for Fraction.

However, I was able to figure this out. Instead of parsing statement by statement, I parse the entire compilation unit instead - this doesn't throw a `ParseException`. So I write the compilation unit to a string, do some string replacements, create an `InputStream` to hold the string. Finally, I call `JavaParser.parse(inputStream);` and this successfully parses the compilation unit!

**Comment by matozoid** [comment]
Okay, I don't see why `parseStatement` doesn't do the trick, but I guess it's one of the many bugs that were solved. I still recommend upgrading at least to 2.5.1!

Good luck :)
