### ISSUE TITLE
Let setters do nothing when set value == current value

### ISSUE THREAD

**Issue by user1derek** [javaparser/javaparser#878]
Greetings. 

I am using an extended ModifierVisitor to change (add/change and remove code) an AST. I also wanted to use the AstObserver (with propagation) to monitor the changes I make to the AST.

My approach is to only override the ModifierVisitor methods that I'm interested in (eg. BlockStmt). However, the ModifierVisitor methods I don't override reconstruct each Node to essentially create an identical Node. As an example here is a code snippet:

public Visitable visit(final BinaryExpr n, final A arg) {
        Expression left = (Expression) n.getLeft().accept(this, arg); 
        Expression right = (Expression) n.getRight().accept(this, arg); 
        Comment comment = n.getComment().map(s -> (Comment) s.accept(this, arg)).orElse(null);
        if (left == null)
            return right;
        if (right == null)
            return left;
        n.setLeft(left);
        n.setRight(right);
        n.setComment(comment);
        return n;
    }

The problem is this reconstruction triggers change events to the AstObserver even though no changes have actually occurred.

I'm just wondering if perhaps I'm misusing either ModifierVisitor/AstObserver or if anyone has recommendations on a better approach.

Thanks!

**Comment by matozoid** [comment]
Well, looks like `ModifierVisitor` lives up to its name ;-) I can imagine adding checks so the visitor only calls the setter if a value is actually changed - that would be a nice addition.

... that would mean changing the generator for this visitor, it's going to be interesting to see how we deal with `NodeList`s then.

**Comment by matozoid** [comment]
@ftomassetti - is there a reason that we get change events for things that haven't changed?

**Comment by user1derek** [comment]
Thanks for your quick response and help. Yes it sure does live up to its name. ;)

For my case I could check for equality between the old and new value in the `propertyChange` method of my `AstObserverAdapter` class. For example, the BinaryExpr code I showed above does trigger a `propertyChange` even if the Binary Expression hasn't changed. But the old value and the new value are, not surprisingly, the same Object. It's doable but a little more work to check for equality with collections.

If this were the case it might even be possible to get away with doing the check in the `notifyPropertyChange` method of `Node` in the core code. But I don't want to assume that it shouldn't trigger the `propertyChange` call when the oldValue and newValue are the same...maybe there are use cases where this is valuable. 

I'm not sure what trickiness there could be in the other methods of `AstObserverAdapter` or if they're ever even triggered by the ModifierVisitor methods that aren't overridden.

My actual approach was to change from a ModifierVisitor to a VoidVisitorAdapter. I wasn't using the "return null to remove a node" feature of ModifierVisitor anyway and just need the superclass to help navigate through the AST.

**Comment by matozoid** [comment]
I called for @ftomassetti because he is the one who built the observer functionality, and he's using it for the lexical preservation code. Honestly, I have no idea why anybody would ever want to know that a field is set to the value it already had :) But good that you've already fixed your problem!

**Comment by ftomassetti** [comment]
All calls to setters cause notifications, the notified object can decide if to ignore the change or not. Deciding if some change is irrelevant should be probably done case by case: in some cases the fact the old value and the new one are equals (but not the same object!) could be a reason to ignore the change, while in others we may want to get identity.

**Comment by matozoid** [comment]
Uhuh, but in case the new object == the old one? It's a meaningless operation to the AST, and the `ModifierVisitor` only does these `set`s because it is lazy.

**Comment by ftomassetti** [comment]
Well, for identity equality we could solve this in 3 ways:
* avoding calling setters if the value remain the same
* having a check in all setters and return if the value is the same as the old value
* having the check in the Lexical Preservation observer

**Comment by matozoid** [comment]
Check 2 would be easy to generate code for.

**Comment by ftomassetti** [comment]
Should we go for check 2 then?

**Comment by matozoid** [comment]
It seems to me to fix all all future problems of this kind. Let's do it!

**Comment by ftomassetti** [comment]
PR sent

**Comment by ftomassetti** [comment]
@user1derek when you have time it would be great if you let us know if the last patch on master fix your issue

**Comment by user1derek** [comment]
I downloaded and built the 3.1.5 SNAPSHOT. Only the comment property is now firing a `propertyChange ` for files that have no changes. Since almost every (all?) node can have a comment there are lots of changes like the following:

property=comment
oldValue = null
newValue = null

I also put a bunch of the JavaParser source files through my test and noticed many `parentChange `events for nodes "range", "kind" and "text" are received.

**Comment by matozoid** [comment]
Of course, one or two setters are not generated because they contain all kinds of custom code, and `setComment()` is one of them. @ftomassetti would you like to manually add a check to it?
