### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by JKazma** [javaparser/javaparser#881]
I think I found a memory leak using the JavaParserFacade. Here's the code I used.

https://gist.github.com/JKazma/bc31d700beaf55935fd8a66467892ec4

Using the JVM Debugger Memory View plugin with intelliJ, I noticed that alot of objects were being created and never collected by the garbage collector. This does not happen if I comment out the 57th line in the code above. Below you can find a few screenshots of the Debugger output during runtime.

Also, the directory I'm using contains around 5000 java files.

Am I doing something wrong or is this indeed a memory issue?

![image](https://cloud.githubusercontent.com/assets/8633374/24520602/05713ab8-1557-11e7-9c5f-406a4666a7ab.png)

![image](https://cloud.githubusercontent.com/assets/8633374/24520626/17990090-1557-11e7-8542-27a530f56416.png)

![image](https://cloud.githubusercontent.com/assets/8633374/24520641/26ba7810-1557-11e7-82a0-3617c9992391.png)

**Comment by JKazma** [comment]
Posted in https://github.com/javaparser/javasymbolsolver/issues/189 instead.

**Comment by matozoid** [comment]
Okay :)
