### ISSUE TITLE
CallableDeclaration: Add method to retrieve signature

### ISSUE THREAD

**Issue by fruffy** [javaparser/javaparser#882]
In Java a signature is defined as 
> the method name and the number and type of its parameters. Return types and thrown exceptions are not considered to be a part of the method signature.  

However, this feature is not present in CallableDeclaration.
getDeclarationAsString() always includes the return type.
I ran into trouble here when comparing the MethodDeclaration of JavaParser vs the MethodDeclaration of Java-Symbol-Solver, which both have a different naming behaviour.

So I added a method to all CallableDeclaration types which is very similar to getDeclarationAsString()
```
    @Override
    public String getSignature() {
        StringBuilder sb = new StringBuilder();
        sb.append(getName());
        sb.append("(");
        boolean firstParam = true;
        for (Parameter param : getParameters()) {
            if (firstParam) {
                firstParam = false;
            } else {
                sb.append(", ");
            }
            sb.append(param.getType().toString(prettyPrinterNoCommentsConfiguration));
            if (param.isVarArgs()) {
                sb.append("...");
            }
        }
        sb.append(")");
        return sb.toString();
}
```
Is it sensible to add this method or should getDeclarationAsString() just be amended with a fourth parameter?

**Comment by matozoid** [comment]
Thanks for the feedback!

Lots of remarks here:
- `getDeclarationAsString()` is something I've been tolerating in the codebase for a while, but I'm not happy with it
- It would be nice to have `getSignature()` return a new `Signature` type. Functionally meaningful information shouldn't be passed around in a string.
- instead of `toString`, use `asString`. `toString` does pretty printing, `asString` tries to give the most useful representation of the node.
- printing a list like that can be done easily with `SeparatedItemStringBuilder`
- what is the actual problem we're solving between JP and JSS? I haven't used JSS lot - do you have an idea @ftomassetti ?

**Comment by matozoid** [comment]
@FRuffy - could you take a look at the PR and check if it is correct and sufficient for your needs?

**Comment by fruffy** [comment]
Yes, it works great. thanks a lot! There is one thing, I had to add a temporary toString() method to make it comparable with the javasymbolsolver `getSignature()` call. I am going to make a suggestion to implement the `Signature` type in javasymbolsolver too.
```
@Override
public String toString() {
	StringBuilder parameterBuilder = new StringBuilder();
	parameterBuilder.append(name + "(");
    for (int i = 0; i < parameterTypes.size(); i++) {
        if (i != 0) {
        	parameterBuilder.append(", ");
        }
        parameterBuilder.append(parameterTypes.get(i).toString());
    }
	parameterBuilder.append(")");
   return parameterBuilder.toString();
}
```

**Comment by matozoid** [comment]
@ftomassetti - pay attention to this issue pleaaaase :)

**Comment by ftomassetti** [comment]
Mmm, maybe returning a Signature object would be the best solution. That Signature object could have 2 methods, one to produce a string with return type and one without. It would also make declarationAsString redundant

**Comment by matozoid** [comment]
@ftomassetti - what about interoperability with JSS? Do we want to have a single `Signature` class for both?

**Comment by matozoid** [comment]
And can I deprecate all `declarationAsString` methods? Please? They are a maintenance nightmare...

**Comment by ftomassetti** [comment]
yes. Depending on how we design the Signature object we could reuse it. The fact is the fact is that in JavaParser we have "shallow types" while in JSS we have "resolved types", so I am not sure we can reuse it, maybe making it generic...

**Comment by matozoid** [comment]
I'm actually not sure what @FRuffy is doing, what he's trying to compare, why we need to compare signature in the parser and the solver. @FRuffy ?

**Comment by matozoid** [comment]
And @ftomassetti - are you sure you want the return type optionally in the signature? It is not officially part of it. Why would we want that?

**Comment by ftomassetti** [comment]
I think in some cases people want it, in others they don't

**Comment by matozoid** [comment]
I'm running into all kinds of trouble because of generics. These should be stripped out of the signature.

**Comment by matozoid** [comment]
Well, there's new stuff in the PR.
