### ISSUE TITLE
Add VarType

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#883]
Just for fun: implement the proposed `var` keyword and put it in the tree as a special type.

**Comment by matozoid** [comment]
Hmmm, that would mean breaking software that happens to use this as a class name. Better leave it alone until it is official.

**Comment by matozoid** [comment]
Implementing this would mean implementing some kind of post-processing phase, just like we have the validation phase now.

Why? Because from Java 10 (or so) a variable declaration with a type named `var` will become special: it's not just a `ClassOrInterfaceType` but a new type, `VarType` or `InferredType` or so. Since we have only one parser, and that parser should parse every Java version, we should turn `var` from `ClassOrInterfaceType` into `VarType` after parsing.

**Comment by DeepSnowNeeL** [comment]
Can't we detect "var" as a token and create a VarType directly on regular
parse phase ? I guess var is a reserved keyword with java 10 ?
And I guess VarType should be a direct subclass of Type ?

**Comment by matozoid** [comment]
Yes we can, but then the grammar would be incompatible with java 1-9! They have no concept of `VarType`.

About var: it's seen as a special type name, not a keyword. So if we find a type called `var` in a variable declaration starting from Java 10 (or whenever it will be implemented) it means "infer the actual type here."

Yes, VarType extends Type. There are already a few other funny types there.

**Comment by matozoid** [comment]
https://bugs.openjdk.java.net/browse/JDK-8151454
