### ISSUE TITLE
Question about Exception throwing for the visit methods?

### ISSUE THREAD

**Issue by danwyryunq** [javaparser/javaparser#886]
Hi guys, I'd like to know if there is any particular reason why visitor methods are not provided a throws Exception  signature as it a possibility that any user that implement them would eventually run across an Exception throwing situation, being forced to either throw only RuntimeExceptions or add the corresponding ' 'throws' to every visit and accept methods as well.   
Am I missing something here?

**Comment by matozoid** [comment]
This decision has been made before any of the current team was working on it, so here is my best guess: adding "throws Exception" to every visit method would force everyone using a visitor to catch Exception when using it. I have not seen any visitors that want to throw an exception yet, so I would say that was a good decision.

In my opinion, with the decision to make lambda's really awkward to use with checked exceptions, they feel secretly deprecated to me, even though I kind of liked them. The replacement should be something like Scala's `Try` class, which we do not have in Java yet. You would specify the result type of the visitor as a `Try<YourDesiredResult>`.

Anyway, that's all my opinion.

**Comment by ftomassetti** [comment]
Agreed. It seems to me that many are just abandoning checked exceptions and few languages after Java have used them. While there are drawbacks either way I think it is more practical to not have them in the interface

**Comment by danwyryunq** [comment]
I also thought about something like that, more like a Failable result type. 
Great guys, that's good to me.
i'm closing this right away.
