### ISSUE TITLE
Is there a way to list superclasses of all the classes in a file/folder?

### ISSUE THREAD

**Issue by niharikaepuri** [javaparser/javaparser#888]
public static void main(String[] args) throws Exception
{
inner = new DefaultMutableTreeNode("InnerClasses");
tree1 = new JTree(inner);
File projectDir = new File("/home/iiitb/Desktop/projects/pl/tree/GUI/one2");

files_list = listClasses(projectDir);
CompilationUnit cu;
for(int i =0; i< files_list.size(); i++)
	{
		try (FileInputStream in = new FileInputStream(files_list.get(i))) 
		{
			cu = JavaParser.parse(in);

		List<TypeDeclaration> types = cu.getTypes();

			ArrayList<String> parents = new ArrayList<>();		
			for (TypeDeclaration typeDeclaration : types) 
			{

 				printTypes(typeDeclaration, parents);
			
 			}
		}
	}

}

private static void printTypes(BodyDeclaration item, List parents)
{
if (item instanceof TypeDeclaration)
{
TypeDeclaration type = (TypeDeclaration) item;
System.out.println(type.getMembers());
s.add(getClassName(type.getName(), parents));

	// Class c = 	getClass(type.getName)
	// c.getSuperClass();		
	// type.getName().getSuperClass();

  		List<BodyDeclaration> members = type.getMembers();
  		List<String> cloneOfParents = new ArrayList<>(parents);
  		cloneOfParents.add(type.getName());
 		for (BodyDeclaration bodyDeclaration : members) 
		{
    		printTypes(bodyDeclaration, cloneOfParents);
  			}
		}

}

private static String getClassName(String name, List parents) {
StringBuilder builder = new StringBuilder();
for (String string : parents) {
builder.append(string);
builder.append(".");
}
return builder.append(name).toString();

}

**Comment by ftomassetti** [comment]
You asked this question already on the JSS project (https://github.com/javaparser/javaparser/issues/888). Closing this duplicate issue.
