### ISSUE TITLE
Make bnd maven plugin fail on warnings

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#897]
Too many times have we forgotten to add a new package to `bnd.bnd`. See if we can configure the plugin to fail the build instead of just warning.

**Comment by matozoid** [comment]
So many snippets of documentation for that plugin, but no clear overview :-(

**Comment by MysterAitch** [comment]
Can this be closed given bnd is now generated? Or is there more to this issue?

**Comment by matozoid** [comment]
That's probably all of it. Thanks for checking.
