### ISSUE TITLE
Import statement of inner class contains dollar($) sign.

### ISSUE THREAD

**Issue by sckimos** [javaparser/javaparser#905]
Hi.

When importing inner class with CompliationUnit.addImport(Class) method, 
class name contains a dollar($) sign.

````java
import JavaParserTest$TestInnerClass;
````

But I think it should be a dot(.)

````java
import JavaParserTest.TestInnerClass;
````

I tested with javaparser-core-3.2.0 , and here is my test code.

````java
import org.junit.Test;

import com.github.javaparser.ast.CompilationUnit;

public class JavaParserTest {

    public static class TestInnerClass {
    }

    @Test
    public void addImport() throws Exception {
        CompilationUnit cu = new CompilationUnit();
        cu.addImport(TestInnerClass.class);
        System.out.println(cu.toString());
    }
}
````

Thank you.

**Comment by matozoid** [comment]
Yes, this is quite obviously wrong.

We'll have to walk through all the builder methods that accept a `Class` and see how to fix this nicely.

**Comment by DeepSnowNeeL** [comment]
If $ is illegal in package name we can be done with a replace.
My bad btw, Assign me on this

**Comment by matozoid** [comment]
Cool, can you check if there are other types of classes that might fail? (I was thinking of anonymous classes for example)
