### ISSUE TITLE
Javadoc block tag parsing issues

### ISSUE THREAD

**Issue by sischnei** [javaparser/javaparser#907]
Hi guys,

I'm having issues with parsing of Javadoc block tags. Given the following javadoc:

    /*
    * Add a field to this and automatically add the import of the type if needed
    *
    * @param typeClass the type of the field
    * continued in a second line
    * @param name the name of the field
    */

I would expect two block tags for the two params, however with version 3.2.3-SNAPSHOT I get three block tags, where the "continued in a second line" is parsed as `JavadocBlockTag{type=UNKNOWN, content='JavadocDescription{elements=[JavadocSnippet{text='in a second line'}]}', name=Optional.empty}`.

I have extended the unit tests to showcase the problem: https://github.com/sischnei/javaparser/commit/6c450c880c6dca8f24c43c91ab680fc08a04ce25

I also attempted to solve the issue and contribute a fix, but I'm worried that the problem is a little bit more complicated. I was thinking about adding all lines that do not confirm with `JavadocParser::isABlockLine` to the last block, however the `JavadocParser::isABlockLine` only checks if the line starts with an '@' symbol. So with my solution, a second line starting with eg. a "@see" would not be correctly associated with the last "@param" block. 

I hope you understand what I mean. Basically I'd suggest extending also `JavadocParser::isABlockLine` to only consider real blocks (like "@param", "@return",...). What do you think? Should I go on and create a pull request?

**Comment by sischnei** [comment]
Actually I just realise that I have been mixing up block comments and online comments (which start with '{@'), so actually it should be enough to just group block tags over multiple lines and keep everything else the same. I'll try to come up with a PR for it!

**Comment by matozoid** [comment]
Cool, thanks!

**Comment by sischnei** [comment]
Ok, so I hope that my PR can be merged (I don't know why AppVeyor build fails). 
One thing I'm not sure about yet is tab handling, eg. given the javadoc

    /*
    * Add a field to this and automatically add the import of the type if needed
    *
    * @param typeClass the type of the field
    *     continued in a second line
    * @param name the name of the field
    */

It would currently result in a snippet that also contains the tab. I don't seem to be able to replicate that here in github since it always discards my additional spaces....
Should `cleanLines` take care of \t tabs as well?

**Comment by matozoid** [comment]
@ftomassetti - for that last remark above: do you try to keep original formatting or do you reformat everything while parsing?

**Comment by ftomassetti** [comment]
I would say that keeping the original formatting would be optimal

**Comment by sischnei** [comment]
Ok, well right now it should keep everything, except of course the newline. But if required, I can adapt it so that it keeps also the newline but still parses it into one block tag...

**Comment by matozoid** [comment]
@ftomassetti - what do you do when parsing the first part of the javadoc? Keep or remove EOLs?

**Comment by ftomassetti** [comment]
What I do is not necessarily what is right to do :)
I would say we can throw away all the EOLs that we can reconstruct later
