### ISSUE TITLE
Add NodeWithCondition interface

### ISSUE THREAD

**Issue by arturbosch** [javaparser/javaparser#937]
When analyzing conditional statements, I miss such an interface for easier unification of the task.
Instead of many `instanceOf's`, one would be sufficient. What do you think? I can provide a PR ^^

**Comment by matozoid** [comment]
Sounds good, which nodes would that be?

**Comment by arturbosch** [comment]
IfStmt, DoStmt, WhileStmt are the obvious ones, ForStmt has a compare expression which should also be a condition. That's it?

**Comment by DeepSnowNeeL** [comment]
You should make a Node.isConditional() or maybe better
Statement.isConditional()

Le lun. 22 mai 2017 à 18:25, Artur Bosch <notifications@github.com> a
écrit :

**Comment by arturbosch** [comment]
Well than I still have to cast it to a specific Node to retrieve the condition.

```groovy
def method(Statement stmt) {
    if(stmt instanceOf WhileStmt) {
        (stmt as WhileStmt).condition
        ... etc
    }
}
```

**Comment by matozoid** [comment]
@arturbosch I've quickly added it so it can go in tonight's release.

@DeepSnowNeeL that's not a pattern we normally follow. Would you like a complete set like `isStatement` `isExpression` etc etc?

**Comment by matozoid** [comment]
I think we should have a fancy Java 8 `ifConditional(Consumer<NodeWithConditional>)` then. Open another issue if one of you wants that, because it will involve code generation magic :)
