### ISSUE TITLE
cannot get extended type with the form,AAA.BBB

### ISSUE THREAD

**Issue by junzii** [javaparser/javaparser#940]
the parsing code is like this:
class A extends BB.CC{
}
I try to get parent class with ClassOrInterfaceDeclaration.getExtendedTypes(), but only CC can be got. Actually, it should be BB.CC

**Comment by matozoid** [comment]
"BB" is in field `scope`. Fully qualified name = scope.scope.scope.name + "." + scope.scope.name + "." + scope.name + "." + name (and so on.)

Does this solve your problem?

**Comment by matozoid** [comment]
No answer, closing.
