### ISSUE TITLE
Integrate java-symbol-solver

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#943]
Somewhere in the future :-)

**Comment by ftomassetti** [comment]
I think we have been doing some progress on this with #1169 and #1178 . In some way #1154 was the first step for this one.

**Comment by matozoid** [comment]
How far along are we now?

**Comment by ftomassetti** [comment]
Well I think that with the new API it will be more intuitive to answer questions directly from AST nodes. We need to had more methods on the AST nodes but all of those will be simple calls to the SymbolResolver. Now that the infrastructure is in place I would say the hard stuff is done. I would refine, polish, document these parts and then see what people think.

**Comment by matozoid** [comment]
@ftomassetti I thought of a thing: in core we have many places where we seem to offer some kind of functionality that work on types, but it really just works on strings. A bad one is `Signature` for example. It would be nice if we could say "for all these types in the signature I would like to get the fully qualified name. If we can't get it, just leave it as it is". I'm not sure how this would look. Maybe an if-symbol-solver-configured statement, maybe a `Optional<String> getFqn(String type)` method... What do you think?

**Comment by ftomassetti** [comment]
I would call this done, at least on the JP side. We could want to add some more tests on the JSS side but here everything looks good. Thanks to everyone!
