### ISSUE TITLE
Cannot import the javaparser class after adding the dependency of pom.xml

### ISSUE THREAD

**Issue by xryanyjy** [javaparser/javaparser#944]
After adding dependency of the pom.xml file, the javaparser-core-3.2.5 jar package has appeared in external library, however, I still can't import javaparser class. I have tried other javaparser by adding dependency like japa.parser.* and it can be imported successfully. I don't know why and hope to ask for some help, big thanks!

**Comment by xryanyjy** [comment]
By the way, big sorry for such easy and maybe stupid question.

**Comment by matozoid** [comment]
japa.parser looks like a very old package name?

Anyway, here is a small, complete project: https://github.com/matozoid/java-logic-positivizer

**Comment by xryanyjy** [comment]
Big thanks for the quick reply! japa.parser is probably an old package and I just want to try it to find what's the problem of my configuration because I'm new to java orz.

By cloning your small project, I found I have the same problem that the javaparser package classes cannot be imported.  After adding dependency of the pom.xml, the javaparser-core jar package appeared in the external library but there seems no useful classes in it. I wonder whether this is where the problem. 

The "Maven:com.github.javaparser:javaparser-core:3.2.5" library contains following files: "javaparser-core-3.2.5.jar"---"META-INF"---"maven.com.github.javaparser.javaparser.core"---"pom.properties"&"pom.xml"; "MANIFEST.MF", containing no classes needed to be imported.

Sorry for bothering you again. At your convenience, hoping for your reply.

**Comment by matozoid** [comment]
Okay, it is really a problem of setup on your side. It would be easiest if you let someone at your place take a look.

One thing I can do: can you show me your complete pom? I think you're specifying "pom" in the dependency or so.

**Comment by xryanyjy** [comment]
Big thanks for your kind help! It seems I can't upload the picture in my comment, thus I pasted what I write here.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.uoe.degree.proj</groupId>
    <artifactId>gencorpus</artifactId>
    <version>0.0.1</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-core</artifactId>
            <version>3.2.5</version>
        </dependency>

    </dependencies>

</project>

At your convenience, could you please help me to see where does my configuration wrong.

**Comment by matozoid** [comment]
Okay, that's exactly the same as the sample indeed :) When you do a `mvn clean install` from the command line this should give no trouble. Beyond that, it's a tool problem and I will have to send you off to the people making those tools.

**Comment by xryanyjy** [comment]
Thank you for your reply! What is the exact meaning of tool problem? I found other jar packages like eclipse jdt can be used after adding the dependencies. Will it be solved if I re-install the maven tool? It seems that other people can successfully use the javaparser.

**Comment by matozoid** [comment]
If the sample project doesn't work, some tool (maven, eclipse, intellij, java, linux, windows, etc...) on your side is malfunctioning. That means that this is no longer a question about JavaParser. Please ask people near you, or maybe ask on StackOverflow or so?
