### ISSUE TITLE
I want to add a new statement or expression to the body at any given position in the Body list of statements

### ISSUE THREAD

**Issue by sourabhsparkala** [javaparser/javaparser#945]
Is this possible in javaparser-core?

**Comment by matozoid** [comment]
Yes it is.
Please give more context (some code for example) for a better answer.

**Comment by sourabhsparkala** [comment]
before://
method(){
   int a;
   int b;
}

after://
method(){
   int a;
   int b;
  SOP(a/10);
}

the print statement should be possible if there is a integer variable 'a' already declared. So in this case, I am using the visit(VariableDeclarator,null) to check the presence of the variable with name = 'a'. But I do not know how to add the next SOP statement to CompilationUnit from the visit() function.

Your help would be appreciated.

**Comment by sourabhsparkala** [comment]
@Override
    public Node visit(VariableDeclarator declarator, Void args) {
        if (declarator.getNameAsString().equals("a") && declarator.getInitializer().isPresent()) {
            Expression expression = declarator.getInitializer().get();
            if (expression instanceof IntegerLiteralExpr) {
                          //The statement to add the new SOP statement here? How to get the MethodDeclaration of the same variable compilationUnit.
         `}
        }
        return declarator;
    }

**Comment by matozoid** [comment]
```java
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.VariableDeclarator;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.IntegerLiteralExpr;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.visitor.GenericVisitorAdapter;

import static com.github.javaparser.JavaParser.parseClassBodyDeclaration;

public class Issue945 {
    public static void main(String[] args) {
        GenericVisitorAdapter<Node, Void> visitor = new GenericVisitorAdapter<Node, Void>() {
            @Override
            public Node visit(VariableDeclarator declarator, Void args) {
                if (declarator.getNameAsString().equals("a") && declarator.getInitializer().isPresent()) {
                    Expression expression = declarator.getInitializer().get();
                    if (expression instanceof IntegerLiteralExpr) {
                        declarator
                                .getAncestorOfType(BlockStmt.class)
                                .ifPresent(block -> block.addStatement("System.out.println(" + declarator.getNameAsString() + ");"));
                    }
                }
                return declarator;
            }
        };

        BodyDeclaration method = parseClassBodyDeclaration("void method(){ int a=0; int b=2; }");

        method.accept(visitor, null);

        System.out.println(method);
    }
}
```

In short: for all variable declarations called `a` with an initializer that are at some point contained in `BlockStmt` (which may misfire, when they are in a `for(int a=2;...;....){}` for example) I add a new statement to the end of that `BlockStmt`.

Figuring out how to deal with for-statements and other anomalies is left as an exercise for the student ;-)

**Comment by sourabhsparkala** [comment]
Thank you for the solution. This helped a lot

**Comment by matozoid** [comment]
Good luck!
