### ISSUE TITLE
How can I access the body of an if-else block?

### ISSUE THREAD

**Issue by abhay-iy97** [javaparser/javaparser#946]
I'm trying to calculate the cyclomatic complexity of a program and am trying to count the number of if-else clauses within the code. Problem I'm facing is how do I access a given "if" block and look within it for more such if-else clauses? 
I use the getElseStmt() with recursion to obtain the outer if-else if clauses but how can I obtain access to their blocks?
For Example: 
`if(condition)
{ if(condition 2) else}
else
{if (condition 3) else}`
So I want the answer to be 6 but my code will give me 2. How can I access the inner "if"/"else"? Is there any method to access the body of the block and test it as per my requirements? 
The getThenStmt() gives the body with the braces from which I can't seem to extract the "if" clauses? How do I go about this?

**Comment by matozoid** [comment]
Your approach is valid, but it looks like you are writing all AST traversal logic yourself - but that has already been written for you.

If you just want to count the if statements, you can use a visitor that visits only `IfStmt`, or you can look at the size of a call to `compilationUnit.getChildNodesByType(IfStmt.class)`.

**Comment by abhay-iy97** [comment]
`public void visit(IfStmt n, Void arg) 
	    	    {
	    	    	System.out.println("Found an if statement @ " + n.getBegin());
	    	    }`
This visitor function only gives the outermost "if" statement as output and ignores the inner block's "if"
I need to count the "if" , "else if" and "else" statements. How can that be achieved by means of a visitor?


I applied the second part of your answer in my code and it _works_. Although it only helps me count the if and else-if but not the "else" statements. If there's an else clause, it is ignored. How can I ensure that the else gets counted as well? 
 Like for the example I mentioned in the original question, 
The size of the call returns only 3 since it encounters only 3 if statements but ignores the "else" whereas I want the answer to be 6
I can make this possible by making all the else statements "else-if" but I can't always do that. 
So how do I go about this? Is there any function that can help or will I have to write specific code to obtain this kind of an output?
just an Example to make it clearer: 
`if(condition) `
`{ if(condition 2)//else}` 
`else if(condition 3) `
    ` {if (condition 4) 
         //
      else} `
`else`
     ` {if(condition 5) 
     //
     } `
In this case, I'd want the answer to be 8 but the size of the call will return 5. 
Thanks for answering :) @matozoid .

**Comment by matozoid** [comment]
The visitor has its travel logic inside the visit methods. If you override one and don't call super, it will not go inside the node, so that's what's missing there :-)

Second part: else is not a node, it is a property of `IfStmt`. So you can go over the list of `IfStmt` and count simple if-statements as 1, and `IfStmt`s that have an else as 2. (If I understand your goal correctly.)

This would be a nice sample for my [blog](https://matozoid.github.io/), hmmm...

**Comment by abhay-iy97** [comment]
Ah.
Yes, I included the super.visit call and it does work now. The line numbers(for every `if` clause) do appear a bit skewed up due to the recursion. So I guess I'll go with the getChildNodesByType method.

With reference to the second part, 
How do I check for an else? For instance, there could be programs wherein the `if` and `else-if` satisfy all conditions and therefore there is no need to add an `else` clause. But in the case where an `else` clause is present, how may I look for it?
**Example:**
Count returned in this case would be 2 (whereas I need it to be 3)
```
if(n<0) 
//
else if(n>0)
 //
else
 //
```

**OR**
(Count returned as 2 which is correct)
```
if(n<=0) 
//
else if(n>0) 
//
``` 
I hope this does not come across as gibberish.  
I tried the getElseStmt() but it just returns the same output and skips over the else clauses. 
You mentioned going over a list and checking if the` IfStmt`contains an else clause. I think that's where my problem lies. If you could guide me on how to do this, I think I'd be able to solve this issue.

**Comment by abhay-iy97** [comment]
This is the piece of code I've been playing around with and it works except for the `else `clause dilemma. What more  additions should I make such that it identifies `else` as well?  
```
public void visit(IfStmt n, Void arg) 
            {
            System.out.println("Found an if statement @ " + n.getBegin());
            }
 void process(Node node)
            {
                count=0;
                for (Node child : node.getChildNodesByType(IfStmt.class))
                {
                    count++;
                   visit((IfStmt)child,null);   
                }
            }
```

**Comment by matozoid** [comment]
```java
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.stmt.IfStmt;

import static com.github.javaparser.JavaParser.parseClassBodyDeclaration;

public class Issue946 {
    public static void main(String[] args) {
        BodyDeclaration method1 = parseClassBodyDeclaration("void x(int n) {if (n < 0) ; else if (n > 0) ; else ; }");
        BodyDeclaration method2 = parseClassBodyDeclaration("void y(int n) { if (n <= 0) ; else if (n > 0) ; }");

        System.out.println(process(method1));
        System.out.println(process(method2));
    }

    void x(int n) {if (n < 0) ; else if (n > 0) ; else ; }

    void y(int n) { if (n <= 0) ; else if (n > 0) ; }

    static int process(Node node) {
        int complexity = 0;
        for (IfStmt ifStmt : node.getChildNodesByType(IfStmt.class)) {
            // We found an "if" - cool, add one.
            complexity++;
            if (ifStmt.getElseStmt().isPresent()) {
                // This "if" has an "else"
                if (ifStmt.getElseStmt().get() instanceof IfStmt) {
                    // it's an "else-if". We already count that by counting the "if" above.
                } else {
                    // it's an "else-something". Add it.
                    complexity++;
                }
            }
        }
        return complexity;
    }
}
```

If you want to do it with a visitor, the logic should be about the same.

**Comment by abhay-iy97** [comment]
Right I've tried your code.
This is the case I'm testing just to check the functionality. The correct count of if-else clauses is returned (YAY :-)) but the line numbers are a bit messed up. Please correct me if I'm wrong but is it because `else` isn't a node itself therefore we just iterate the `count` in the case the `else` clause is present in the code and we aren't actually moving to the else node(since it does not exist). Therefore we remain on the previous node itself and that's why the line numbers are being printed again? 

Only query remaining: Why is line 47 being printed twice? That line contains the else if clause
Since nodes are hierarchical so the node being considered is as mentioned below?
```
else if (condition)//
else 
```
```
line 36	if(n>0)
line 37		{
line 38			if(n%2==0)
line 39			{
line 40				System.out.println("Even positive");
line 41			}	
line 42			else
line 43			{
line 44				System.out.println("Odd positive");
line 45			}
line 46		}
line 47		else if(n<0)
line 48		{
line 49			if(n%2==0)
line 50			{
line 51				System.out.println("Even negative");
line 52			}	
line 53			else 
line 54			{
line 55				System.out.println("Odd negative");
line 56			}
line 57		}
line 58		else
line 59		{
line 60			if(n==0)
line 61				System.out.println("ok");
line 62		}
```

**OUTPUT:**
```
Found an if statement @ Optional[(line 36,col 3)]
Found an if statement @ Optional[(line 38,col 4)]
Found an if statement @ Optional[(line 38,col 4)]
Found an if statement @ Optional[(line 47,col 8)]
Found an if statement @ Optional[(line 47,col 8)]
Found an if statement @ Optional[(line 49,col 4)]
Found an if statement @ Optional[(line 49,col 4)]
Found an if statement @ Optional[(line 60,col 4)]
```
I slightly modified your code to call visit() whenever the` count `variable is incremented.
```
for (IfStmt child : node.getChildNodesByType(IfStmt.class))
	    	        {
	    	        	count++;
	    	          
	    	           visit(child,null);
	    	               if (child.getElseStmt().isPresent()) 
	    	               {
	    	                   if (child.getElseStmt().get() instanceof IfStmt) {
	    	                       // it's an "else-if". We already count that by counting the "if" above.
	    	                   } else {
	    	                       count++;
	    	                       visit(child,null);
	    	                   }
	    	               }
	    	         }
```

Is there any way in which I could print the line number where `else` is actually present?
Thanks for all the help @matozoid

**Comment by matozoid** [comment]
Ummm, do you have a chunk of code that I can try instead of snippets? That would save me a lot of time.

I don't really get what you're trying to say about the line numbers, but I noticed one thing: the `else` *is* a node, so you can ask it for its position.

Oh, and you're making a mistake with visitor usage: never directly call `visit` - always call `accept` on a node.

Don't forget we have a book which explains all of this quite extensively: https://leanpub.com/javaparservisited

**Comment by arturbosch** [comment]
Hey take a look at this class: [CyclomaticComplexityVisitor.groovy](https://github.com/arturbosch/SmartSmells/blob/master/src/main/groovy/io/gitlab/arturbosch/smartsmells/common/visitor/CyclomaticComplexityVisitor.groovy).

**Comment by abhay-iy97** [comment]
If `else` is a node then how can I obtain it's line number? Also you mentioned above in the comments that `else` is not a node? I don't follow. Please explain. @matozoid 
This is the code I'm using now.
```java
public class X
{
	    public static void main(String[] args) throws Exception 
	    {
	      //Calls process etc.
	    }
	    
	    public static void process(Node node)
	    {
	    	int count=0;
	        for (IfStmt child : node.getChildNodesByType(IfStmt.class))
	        {
	        	count++;
	          
	           child.accept(new MethodVisitor(),null); 		
	               if (child.getElseStmt().isPresent()) 
	               {
	                   if (child.getElseStmt().get() instanceof IfStmt) {
	                   } else {
	                       count++;
	                      child.accept(new MethodVisitor(), null);
	                   }
	               }
	         }
	    }

	    private static class MethodVisitor extends VoidVisitorAdapter<Void>
	    {
	    		@Override
	    	        public void visit(IfStmt n, Void arg) 
	    	        {
	    	    	     System.out.println("Found an if statement @ " + n.getBegin());	
	    	        }
	    }
}
```

By line numbers I mean, I want to print the line number wherever an` if `,` else-if` or an `else` clause is present. So in the example  presented above with the line numbers **I wanted the output to be** : 

```
Line 36      // ( If is present)             <-Obtained in the output
Line 38      // ( If is present)             <-Obtained in the output
Line 42      // ( else is present)           <-Did not get this output
Line 47      // ( else-If is present)        <-Obtained in the output
Line 49      // ( If is present)             <-Obtained in the output
Line 53      // ( else is present)           <-Did not get this output
Line 58      // ( else is present)           <-Did not get this output
Line 60      // ( If is present)             <-Obtained in the output
```

But I got another output which I've mentioned above. There were line numbers which repeated and I don't really know why. So how do I get the correct output of line numbers?

**Comment by matozoid** [comment]
Okay, I see where I was confusing. I meant to say: there is no node class called `ElseStmt`, *but* below the `IfStmt` node, there is a `Statement` node which is in the property `elseStmt`. The important thing: there is not `visit(ElseStmt)` method in the visitors, because there is no such type - you'll have to visit `IfStmt` and get `elseStmt`.

I'll go look at your code now.

**Comment by matozoid** [comment]
Ha, you're doing something pretty complex, and I don't think it's necessary: mixing `getChildNodesByType` and a visitor. Instead of trying to fix this, can you tell me what my approach above is missing, or what's missing from @arturbosch's implementation?

**Comment by abhay-iy97** [comment]
I'm attempting to print the line number at which the `if` `else-if `and `else `nodes are found.
This printing takes place in the visit function. That's pretty much why I'm calling `visit` at least in this case.
Both your codes gives me the count of the nodes which is fine but I'm also trying to add this line printing feature. So would this be the right way to go about it? 
It does seem to work but partially as explained in the outputs above.

**Comment by matozoid** [comment]
```java
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.stmt.IfStmt;
import com.github.javaparser.ast.stmt.Statement;

import static com.github.javaparser.JavaParser.parseClassBodyDeclaration;

public class Issue946 {
    public static void main(String[] args) {
        BodyDeclaration method1 = parseClassBodyDeclaration("void x(int n) \n{if (n < 0) ; \nelse if (n > 0) ; \nelse ; }");
        BodyDeclaration method2 = parseClassBodyDeclaration("void y(int n) { if (n <= 0) ; else if (n > 0) ; }");

        System.out.println(process(method1));
        System.out.println(process(method2));
    }

    void x(int n) {if (n < 0) ; else if (n > 0) ; else ; }

    void y(int n) { if (n <= 0) ; else if (n > 0) ; }

    static int process(Node node) {
        int complexity = 0;
        for (IfStmt ifStmt : node.getChildNodesByType(IfStmt.class)) {
            // We found an "if" - cool, add one.
            complexity++;
            printLine(ifStmt);
            if (ifStmt.getElseStmt().isPresent()) {
                // This "if" has an "else"
                Statement elseStmt = ifStmt.getElseStmt().get();
                if (elseStmt instanceof IfStmt) {
                    // it's an "else-if". We already count that by counting the "if" above.
                } else {
                    // it's an "else-something". Add it.
                    complexity++;
                    printLine(elseStmt);
                }
            }
        }
        return complexity;
    }

    private static void printLine(Node node) {
        node.getRange().ifPresent(r -> System.out.println("line:"+r.begin.line));
    }
}
```

Now it prints the line numbers where it finds complexity. (They should be sorted, but if they aren't it shouldn't be very hard to put them in a list and sort them.)

**Comment by matozoid** [comment]
In @arturbosch's file you could do the same: print the line in `countMcc()`

**Comment by abhay-iy97** [comment]
Yes, this is very close to the output I need. I will have to sort it. Thanks
Can you please explain the `printLine` function?
What exactly does the getRange().ifPresent() function do?

And why can't I use the visitor itself to print the line? Where is my code going wrong?

**Comment by matozoid** [comment]
For your code I would say: for a simpel case like this, use a visitor OR `getChildNodesByType` - I don't want to spend my holiday debugging that :-)

A node can or can not have a range, that's why it's `Optional`. It's a Java 8 feature --> http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html

**Comment by matozoid** [comment]
If this question is answered, please close it.

**Comment by abhay-iy97** [comment]
Thank you for all the help :)
