### ISSUE TITLE
CommentParser:  invalid comment within String found

### ISSUE THREAD

**Issue by quarkie** [javaparser/javaparser#95]
The commentParser does recognize the following as a comment and  fails  which is not correct:
String failStr= ("/*/data");

**Comment by ftomassetti** [comment]
Are you suggesting that "/*/" should be recognized as a valid comment?

According to http://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.7

I think it is not: the asterisk part of the start of the comment cannot be "reused" as part of the end of the comment. Am I wrong in interpreting your problem? Am I wrong in my interpretation of the language specs?

**Comment by SmiddyPence** [comment]
Opposite way round.  (unverified yet)

It is not a valid comment; but the parser recognizes it as one.

**Comment by ftomassetti** [comment]
My bad, I did not read correctly, ok, that is bad :)
Probably we should start by writing a failing test and then look in the comment parser.

**Comment by SmiddyPence** [comment]
I'll write the test, you can fix it. Call it virtual pairing :wink:

**Comment by ftomassetti** [comment]
Love that!

**Comment by quarkie** [comment]
Yes it should not be recognized as a comment ^^ 
very fast reaction time  here  ;-)

**Comment by ftomassetti** [comment]
We try to be fast, I think we always had the experience of reporting an issue and get an answer a long after it stopped to be useful :)
It is bad because users stop reporting problems, while we really need that: I would have never ran in this issue myself

**Comment by quarkie** [comment]
i just saw that the version I am using is the old one from googlecode .-(. in the current trunk(github) the error might be fixed, as stringsare recognized.  sorry  for making you work on things that might be fixed :-(

**Comment by ftomassetti** [comment]
No problem, it could be worthy to add that test anyway, please keep reporting issues, in the worst case we will just realize how awesome the project already is :D

**Comment by ptitjes** [comment]
@SmiddyPence @ftomassetti Did one of you finally write a test ?

**Comment by ftomassetti** [comment]
Just sent a pull request with the test (see #130). Should we close this issue?
