### ISSUE TITLE
How to get  the line number from ClassTree or MethodTree

### ISSUE THREAD

**Issue by adudurant** [javaparser/javaparser#956]
I use the Javaparser to analyze some java code.But how to  get the line number from ClassTree or MethodTree?  In fact ,I know that  the node or the statement have the API to get the line number.However,how to get from the Tree?

**Comment by matozoid** [comment]
I'm not sure what you mean with ClassTree or MethodTree - is it the output of `compilationUnit.getMethods()` or so? A little code example would help.

In general: every type of node has fields `range` and `tokenRange`. `range` points to `line,col` coordinates in the file. `tokenRange` points to the tokens for this node, and these tokens include their `line,col` coordinates too.

**Comment by adudurant** [comment]
@matozoid 
	static class VariableScanner extends TreeScanner<List<String>, List<String>>
	{
		@Override
		public List<String> visitVariable(VariableTree node,List<String> p)
		{
			System.out.println("variable "+node.toString());
			p.add(node.toString());
			return p;
		}
	
	}

How to get the var line number？

**Comment by adudurant** [comment]
@matozoid  or how to get the Variable line number?

**Comment by adudurant** [comment]
@matozoid   I  couldn't solve this problem， for  too few document to refer to。

**Comment by adudurant** [comment]
The code as  follow

public class JDKParser {
	private ParserFactory factory;
	private static int counter = 0; 
	public JDKParser() {
		factory = getParserFactory();
	}
	public List<String> parseMethodDefs(String file) throws IOException {
		JCCompilationUnit unit = parse(file);
		MethodScanner scanner = new MethodScanner();
		return scanner.visitCompilationUnit(unit, new ArrayList<String>());
	}
	public List<String> parseClassDefs(String file) throws IOException {
		JCCompilationUnit unit = parse(file);
		ClassScanner scanner = new ClassScanner();
		return scanner.visitCompilationUnit(unit, new ArrayList<String>());
	}
	public List<String> parseVariableDefs(String file) throws IOException {
		JCCompilationUnit unit = parse(file);
		VariableScanner scanner = new VariableScanner();
		return scanner.visitCompilationUnit(unit, new ArrayList<String>());
	}
	JCCompilationUnit parse(String file) throws IOException {
		Parser parser = factory.newParser(readFile(file), true, false, true);
		return parser.parseCompilationUnit();
	}
	private ParserFactory getParserFactory() {
		Context context = new Context();
		JavacFileManager.preRegister(context);
		ParserFactory factory = ParserFactory.instance(context);
		return factory;
	}
	CharSequence readFile(String file) throws IOException {
		FileInputStream fin = new FileInputStream(file);
		FileChannel ch = fin.getChannel();
		ByteBuffer buffer = ch.map(MapMode.READ_ONLY, 0, ch.size());
		return Charset.defaultCharset().decode(buffer);
	}
	static class MethodScanner extends TreeScanner<List<String>, List<String>> {

		@Override
		public List<String> visitMethod(MethodTree node, List<String> p) {
			p.add(node.getName().toString());
			return p;
		}

	}
	static class ClassScanner extends TreeScanner<List<String>, List<String>>
	{
		@Override
		public List<String> visitClass(ClassTree node,List<String> p)
		{
			return p;      
		}
	}
	static class VariableScanner extends TreeScanner<List<String>, List<String>>
	{
		@Override
		public List<String> visitVariable(VariableTree node,List<String> p)
		{
			System.out.println("variable "+node.toString());
			p.add(node.toString());
			return p;
		}
	}
	public static void main(String[] args) throws IOException {
		JDKParser parser = new JDKParser();

		for (String cl : parser.parseClassDefs("F:\\Multi.java")) {
			System.out.println(cl);
		}

	}
}

**Comment by matozoid** [comment]
Okay, your code is from another project. `TreeScanner` and `MethodScanner` are from the JDK Compiler Tree API.

This project, JavaParser, is a completely independent implementation of a parser for Java. You will need to ask your question elsewhere, sorry!

**Comment by matozoid** [comment]
(or, of course, you switch to this project. We have some documentation and helpful people ;-) )

**Comment by adudurant** [comment]
Well ，anyone could help？

**Comment by matozoid** [comment]
What is your project? I could explain if JavaParser is a good for for it.

**Comment by adudurant** [comment]
You are so kind.Well,I want to get code about  the class the var  the method and so on from a java file.What 'more ,the file is from a project and I don't want to compile it. The JDKParser would help,could you show me some code meet my need so that I could begin?

**Comment by matozoid** [comment]
This is within the scope of this library.
Here is our front page, it is recommended to read the book: http://javaparser.org/ (you can pay $0 if you like)
Here is a starter project: https://github.com/matozoid/java-logic-positivizer . You want to remove the modifier visitor and put a `VoidVisitorAdapter<Void>` there. Then you can add visit methods like the code you sent.

**Comment by matozoid** [comment]
No response, closing.
