### ISSUE TITLE
JavaParser.parseStatement() the second if block is completely ignored

### ISSUE THREAD

**Issue by sourabhsparkala** [javaparser/javaparser#957]
If I have a string given below to be parsed as Statement
String s="if (false)
        {
            i = 0;
        }
        else
        {
            data = 4;
        }
        if (true)
        {
            System.out.println(i);
        }";

JavaParser.parseStatement(s) ignores the 2nd 'if' block i.e 
if (true)
        {
            System.out.println(i);
        }

**Comment by arturbosch** [comment]
Maybe because that are two statements and the parseStatement just expects one?

**Comment by matozoid** [comment]
Correct, please open an issue to make parsing fail if the stream isn't completely consumed or so.

**Comment by sourabhsparkala** [comment]
Thank you for the repsonse

After the fix would JavapParser.parseStatements() be able to consume the entire stream?

**Comment by matozoid** [comment]
No, it would fail because it is supposed to parse only one statement. You can use parseBlock to parse multiple statements. Just surround your piece of code with { and }

**Comment by matozoid** [comment]
I assume this is answered. If not, please reopen or create a new issue.
