### ISSUE TITLE
Version constant

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#959]
Many users have issues with JSS because they use the wrong version of JP. Maybe we could have a check if we had a constant in JP telling us which version of JP we are using. On the JSS side we could use a static initializer to throw an exception if needed.

What do you guys think?

**Comment by matozoid** [comment]
Do you know of any maven tools to do this easily?

**Comment by matozoid** [comment]
Personally I think it's a beginner's mistake that shouldn't be fixed with more complexity on our side - I have no idea why suddenly this minor change triggered three issues though :-/

**Comment by ftomassetti** [comment]
Beginner mistakes have a cost on our time :)
It is also something surprising for more people that they do not need to use JavaParser when using JavaSymbolSolver.
Maybe it could be solved at the maven/gradle level checking if a dependency appear twice, it could be worth looking into that.
