### ISSUE TITLE
GenericVisitorAdapter: print tree?

### ISSUE THREAD

**Issue by jjYBdx4IL** [javaparser/javaparser#960]
Hi!

Is there an easy way (some already existing dump utility for debugging etc.) to "visually" print/log the AST? Ie. use traversal depth as indentation size or something similar and print out all nodes?

TY!

**Comment by matozoid** [comment]
See #753 - @ryan-beckett is working on it. In the mean time I use the debugger from my IDE ;)

**Comment by jjYBdx4IL** [comment]
My problem with GenericVisitorAdapter is that, like in that other issue stated somewhere similarly, that I'd have to override a lot of methods, and on top of that, I wouldn't be sure that an update wouldn't introduce a new method/type that I'd miss then. So, a practical solution would be to simply add a single visit method like visit(Node, Object payload) and call it from any of the visit methods, or vice versa, call the specific visit methods from the visit(Node...) method by reflection.

**Comment by matozoid** [comment]
I'll move what we have into the next release.

**Comment by matozoid** [comment]
See #964

**Comment by matozoid** [comment]
You can find `XmlPrinter` and `JsonPrinter` in version 3.2.8

**Comment by jjYBdx4IL** [comment]
TY!
