### ISSUE TITLE
Eclipse Project Setup Guide in Wiki

### ISSUE THREAD

**Issue by ryan-beckett** [javaparser/javaparser#961]
Would you guys like to add this Eclipse project setup [guide](https://gist.github.com/ryan-beckett/bfe820707f55ddee4f84c7bd26a4ec19) as a Wiki page? It's in markdown and ready to be copied and pasted into a new page. I can do it myself, but I figured I'd ask first.

**Comment by matozoid** [comment]
Wow, that's elaborate! It's only missing a note to set the correct formatting as seen here: https://github.com/javaparser/javaparser/wiki/Coding-Guidelines

Do add it to the wiki, I guess "contributer help" is the header to file it under.

**Comment by ryan-beckett** [comment]
Done.

**Comment by matozoid** [comment]
Thanks!
