### ISSUE TITLE
inner classes don't show

### ISSUE THREAD

**Issue by UMLBuilder** [javaparser/javaparser#962]
How do i identify inner classes since they do not show a complete name as class$innerclass. And how do i prevent inner classes methods from showing up on the outter class again.

**Comment by UMLBuilder** [comment]
for example, when running the code below, in this same file

import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.visitor.VoidVisitor;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;


public class UMLReverser {
	
	private static final String FILE_PATH = "....omitted ....";
	
    private static List<CNode>  UMLTree;
    private static CompilationUnit cu;

	private static class MethodNameListing extends VoidVisitorAdapter<List<String>> {
		
		 @Override
		public void visit(MethodDeclaration md, List<String> methodList) {
		  super.visit(md, methodList);
		  System.out.println("Method Name added: " + md.getName());
		}
	}
	
	private static class ClassNameListing extends VoidVisitorAdapter<List<CNode>> {
		
		 @Override
		public void visit(ClassOrInterfaceDeclaration cl, List<CNode> umlT) {
		  //super.visit(cl, umlT);
		  CNode newNode= new CNode();
		  umlT.add(newNode);
		  newNode.classname=cl.getName().toString();
		  System.out.println("Class Name added: " + cl.getName());
		  
		  newNode.methods = new ArrayList<String>();
		  VoidVisitor<List<String>> MethodNameListing = new MethodNameListing();
		  MethodNameListing.visit(cu, newNode.methods);
		}
	}


	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
		
		cu = JavaParser.parse(new FileInputStream(FILE_PATH));
		UMLTree = new ArrayList<CNode>();
		
		VoidVisitor<List<CNode>> ClassNameListing = new ClassNameListing();
		ClassNameListing.visit(cu, UMLTree);
		
		System.out.print("we got to the end");

	}	
}

the return is simply:

Class Name added: UMLReverser
Method Name added: visit
Method Name added: visit
Method Name added: main
we got to the end

instead of what I would like to see:

Class Name added: UMLReverser
Class Name added: UMLReverser$MethodNameListing
Method Name added: visit
Class Name added: UMLReverser$ClassNameListing
Method Name added: visit

Method Name added: main
we got to the end

**Comment by matozoid** [comment]
Using this terminology: https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html
- `class$innerClass` is a notation that is used after the parsing step. While parsing, we only take the text from the source file and put it into a tree. The name of a class is literally what is in the source file.
- there is a helper method that tells you if a class is nested: `isNested()` - this may be what you want ("to identify inner classes"). It simply checks if the class is defined directly inside another class. If you really need INNER classes, you can check that `isStatic()` is false.
- I don't understand your second question. Can you be a bit more specific? Maybe you're visiting methods and you can't distinguish between the ones in the nested class and the outer class?

**Comment by UMLBuilder** [comment]
IsNested() will solve part of my problem, how can I get to the parent class so that I can construct the naming chain class$innerclass? I saw a getparent() which returns an Optional<node>, but could not figure out how to grab the data out of this Node.

Also,

I want to list the methods of the nested classes on its class (that I was able to do), but when I list the methods of the outer class, all these methods show up again. How can I eliminate that? I tried to remove the method declaration node (of the inner class) after I iterate through it, but it did not work.

BTW, my project is to design the UML from the code base in Java. I will let you post it after it’s done (if you are interested, of course). I’m starting with the class diagrams first, of course.

**Comment by matozoid** [comment]
- to do something with the parent node, you will have to cast it. Beware of unexpected situations like...
```java
public enum Abc {
  A;
  class X {}
}
```
My approach is to use an IDE with a debugger, and examine the AST for a piece of code in the variable window.
I think `getAncestorOfType(TypeDeclaration.class)` should get you started.

- I meant `isNestedType()` by the way, sorry!

- are you using a visitor to list the methods? If so, consider visiting `TypeDeclaration` instead of `MethodDeclaration` and calling `getMethods()` on it.

**Comment by UMLBuilder** [comment]
I tried to cast it the parent node to ClassOrInterfaceDeclaration, but it failed, even though I know that was the correct type of node (I saw on the debugger).

**Comment by UMLBuilder** [comment]
TypeDeclaration is not visitable.

**Comment by matozoid** [comment]
- are you sure you aren't casting `Optional` to a node? Here's a guide if needed: http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html

- Of course, TypeDeclaration is abstract. Sorry! But, same story but with its children: EnumDeclaration, AnnotationDeclaration and ClassOrInterfaceDeclaration.

**Comment by UMLBuilder** [comment]
I figured I had to invoke get() again to get to a Node per se, and I can retrieve the name by asking it to ToString(), but it still would not let me cast it.

In the case of the methods, I still need to visit each method in the context of the class to verify method invocation in other classes. But I need to avoid repeating nested/Inner class methods. Any ideas?

**Comment by UMLBuilder** [comment]
Got it all done by inspecting the parent node, first child….

**Comment by matozoid** [comment]
You mean the issue is fixed? If not, it would be good to look at some code because I keep having to guess what you're doing.

**Comment by UMLBuilder** [comment]
The issue is fixed, I’m able to identify the inner class all the way to the package, and create the proper $ full name. I’m also able to use the parent node to verify if the method is on the current method or left over from an inner class (same thing can be done with variables and constructors).

In my personal opinion, the visitor should have alternative parameters to shun off nested/inner class, especially if they are private. Having to dig into the AST kinda defeats the purpose of the visitor.

I’m building code that reads a project and generates the UML for it 9post development documentation, if you will). CNode is a simple data structure. The UMLTree is not being constructed yet, for now I’m just printing the results. I Plan to use PlantUML to display it. Code  embedded below:

* @author Renato
*
*/
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.Parameter;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.visitor.VoidVisitor;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;


public class UMLReverser {

                private static final String FILE_PATH = "… redacted …";

    private static List<CNode>  UMLTree;
    private static CompilationUnit cu;
    private static String contextClass;


    private static class MethodNameListing extends VoidVisitorAdapter<List<String>> {

                                @Override
                                public void visit(MethodDeclaration  md, List<String> methodList) {
                                  super.visit(md, methodList);
                                  NodeList<Parameter> args;
                                  List<Node> parent = md.getParentNode().get().getChildNodes();
                                  if (parent.size()>0) // verify parent of method for inner class
                                  {
                                                  Node myParent = parent.get(0);
                                                  if (!(myParent.toString().equals(contextClass)))
                                                                  return;
                                  }

                                   System.out.println("Method Name added: " + md.getName().toString());
                                   args=md.getParameters();
                                   for (int count=0; count<args.size(); ++count) System.out.println("----> argument: " + args.get(count).toString());

                }

    private static class ConstructorNameListing extends VoidVisitorAdapter<List<String>> {

                                @Override
                                public void visit(ConstructorDeclaration  cd, List<String> methodList) {
                                  super.visit(cd, methodList);
                                  methodList.add(cd.getName().toString());
                                  NodeList<Parameter> args;
                                  List<Node> parent = cd.getParentNode().get().getChildNodes();
                                  if (parent.size()>0) // verify parent of constructor for inner class
                                  {
                                                  Node myParent = parent.get(0);
                                                  if (!(myParent.toString().equals(contextClass)))
                                                                  return;
                                  }

                                   System.out.println("Constructor Name added: " + cd.getName().toString());
                                   args=cd.getParameters();
                                   for (int count=0; count<args.size(); ++count) System.out.println("----> argument: " + args.get(count).toString());

                                }
                }

                private static class ClassNameListing extends VoidVisitorAdapter<List<CNode>> {

                                @Override
                                public void visit(ClassOrInterfaceDeclaration cl, List<CNode> umlT) {
                                  super.visit(cl, umlT);
                                  Stack<String> innernodeChain = new Stack<String>();
                                  innernodeChain.push(cl.getName().toString());
                                  CNode newNode= new CNode();
                                  System.out.println("\n\n");
                                  Node parent =cl.getParentNode().get();
                                  List<Node> parentsChildren = parent.getChildNodes();
                                  while ((parentsChildren.size()>0) && (!parentsChildren.get(0).toString().startsWith("package ")))// dig until package
                                  {
                                                  Node myParent = parentsChildren.get(0);
                                                  innernodeChain.push(myParent.toString());
                                                  // go up one level
                                                  parent = parent.getParentNode().get();
                                                  parentsChildren = parent.getChildNodes();
                                  }

                                  String fullname="";
                                  int innerDepth = innernodeChain.size();
                                  for (int count=0; count<innerDepth; ++count)
                                  {
                                                  String currentName= innernodeChain.pop();
                                                  fullname += currentName;
                                                  if (count<innerDepth-1) fullname += "$";
                                  }
                                  umlT.add(newNode);
                                  newNode.classname=fullname;
                                  contextClass= cl.getName().toString();
                                  System.out.println("Class Name added: " + fullname);

                                  newNode.methods = new ArrayList<String>();

                                  VoidVisitor<List<String>> constructors = new ConstructorNameListing();
                                  constructors.visit(cl, newNode.methods);
                                  VoidVisitor<List<String>> MethodNameListing = new MethodNameListing();
                                  MethodNameListing.visit(cl, newNode.methods);
                                }

                }


                /**
                * @param args
                */
                public static void main(String[] args) throws Exception {

                                cu = JavaParser.parse(new FileInputStream(FILE_PATH));
                                UMLTree = new ArrayList<CNode>();

                                VoidVisitor<List<CNode>> ClassNameListing = new ClassNameListing();
                                ClassNameListing.visit(cu, UMLTree);

                                System.out.print("we got to the end");

                }

}

**Comment by UMLBuilder** [comment]
Do you want me to update the thread and explain how I did it?

**Comment by matozoid** [comment]
No, it's fine, I just wanted to know if the question is answered so we can close this one. Let us know when you have some diagrams to see - we can give you a shout out on Twitter and so on :-)

**Comment by matozoid** [comment]
About additional visitor parameters (I assume methods, not parameters) - the current ones use the visitor pattern exactly as you would expect. But I too have wondered if I could make a few new ones that also visitor the `NodeWith...` interfaces for example. That would mean the same node gets visited multiple times. I'll make an issue.

**Comment by UMLBuilder** [comment]
Yes, I meant cover methods with additional parameters. But, you are right, other solutions can cover the capability without breaking the pattern.

**Comment by matozoid** [comment]
Here, take a look at this, I think it does more or less what you want:

```java
package com.github.javaparser;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.utils.CodeGenerationUtils;
import com.github.javaparser.utils.SourceRoot;

import static com.github.javaparser.utils.SourceRoot.Callback.Result.DONT_SAVE;

public class UMLReverser {
    /**
     * @param args
     */
    public static void main(String[] args) throws Exception {
        SourceRoot sourceRoot = new SourceRoot(CodeGenerationUtils.mavenModuleRoot(UMLReverser.class).resolve("src/main/java"));

        sourceRoot.parse("", new JavaParser(), (localPath, absolutePath, result) -> {
            if (result.isSuccessful()) {
                CompilationUnit compilationUnit = result.getResult().get();
                compilationUnit.accept(new VoidVisitorAdapter<Void>() {
                    @Override
                    public void visit(ClassOrInterfaceDeclaration n, Void arg) {
                        System.out.println(dollaryName(n));
                        n.getMethods().forEach(m -> System.out.println("\t" + m.getNameAsString()));

                        super.visit(n, arg);
                    }
                }, null);
            }
            return DONT_SAVE;
        });

    }

    private static String dollaryName(TypeDeclaration<?> n) {
        if (n.isNestedType()) {
            return dollaryName((TypeDeclaration<?>) n.getParentNode().get()) + "$" + n.getNameAsString();
        }
        return n.getNameAsString();
    }

    // Test classes
    static class Z {
        void z() {};
        class Q {
            void q() {};
        }
        
        void b() {
            class B {
            }
        }
    }

    class X {
        class Y {
            void y() {};
        }
        void x() {};
    }
}

class Xx {
    void xx() {};
}
```

**Comment by UMLBuilder** [comment]
Thanks. There was more then the code I sent, I actually analyze the code within the method to figure out how certain classes are used, and that’s why I had the method separated on code. But, your contribution is greatly appreciated.

**Comment by matozoid** [comment]
Cool! See you in another issue :-)
