### ISSUE TITLE
Linthub: do we think is it useful

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#97]
Hi, I recently installed Linthub and I just realized I activated also for this project by mistake. First of all I am sorry about that.

This service install an hook on pull request which run a linter on the code and suggest style improvements or possible issues. I realized I had probably enabled it fo this project when looking at a current pull request (https://linthub.io/javaparser/javaparser/04a81d470473b81309a98a5afba120f320dad7d7)

Do you want me to disable it? Do you think it can be useful?

**Comment by SmiddyPence** [comment]
I think a linter it is a good example (certainly starting point) for using the parser to refactor code i.e. #22 

It would be nice to "eat our own dog food" in that respect rather than using another tool.  Although good for a compare and contrast.  Create similar tests from what that tools spits out then use them here.

**Comment by matozoid** [comment]
It mostly seems to suggest that someone should run a source code formatter :D

**Comment by sebastiankirsch** [comment]
In theory, I like the idea. However, before turning this on we should either "fix" the whole code base or make sure it only reports issues for touched lines. I don't see this helping if it reports a bunch of errors for code a patch didn't touch...

**Comment by ftomassetti** [comment]
I should have disabled it now (sorry again).
However it could be a good point to have some common style guidelines (and a tool to check them: we do not want to do that manually). However it is not a priority probably.
I would close this issue for now but feel free to reopen it if necessary.
