### ISSUE TITLE
parsing classes in the same directory

### ISSUE THREAD

**Issue by 4ndygu** [javaparser/javaparser#971]
Say that I'm running javaparser over some class A, but class A is using some object instance of class B in the same directory and package, so it doesn't really need an import statement. If, say, I'm looking for all Assignment Expressions and their types, how would I be able to take this into account with JavaParserTypeSolver? 

pointing a JavaParserTypeSolver to the root directory works for imported resources, but not for this specific case. Maybe im missing something?

**Comment by matozoid** [comment]
Sorry for the extra effort, but your issue will be handled better if you put it on JavaSymbolSolver's issue list: https://github.com/javaparser/javasymbolsolver/issues

**Comment by 4ndygu** [comment]
thanks!
