### ISSUE TITLE
Invalid POM for 3.2.8

### ISSUE THREAD

**Issue by bartoszmajsak** [javaparser/javaparser#976]
While building the project against version `3.2.8` I'm getting following error:

```
[WARNING] The POM for com.github.javaparser:javaparser-core:jar:3.2.8 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

Debug logging doesn't really say much more than that or I am not able to see the correct information in all this noise :) 

#### My environment

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/bin/mvn
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_121/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.11.5-100.fc24.x86_64", arch: "amd64", family: "unix"
```

**Comment by matozoid** [comment]
Good thing we don't have any transitive dependencies :-) I'll take a look.

**Comment by bartoszmajsak** [comment]
Yeah otherwise it would fail ;)

**Comment by matozoid** [comment]
Fixed in next release!

**Comment by matozoid** [comment]
Oh, it was a property definition under the same name as the placeholder inside it. So a recursive one. I think I got that suggestion from Google somewhere, so that suggestion was wrong :-)
