### ISSUE TITLE
Find Unused codes or DeadCodes using JavaParser or JavaSymbolSolver

### ISSUE THREAD

**Issue by sourabhsparkala** [javaparser/javaparser#977]
Find unnecessary (dead) public java code. For example public classes, methods or fields which have no references. 

I want to know if it is possible to use JavaParser or JavaSymbolSolver static analysis to find these dead codes in the source code. Could I get a starting point or an example snippet to understand, how to accomplish this?

Regards

**Comment by matozoid** [comment]
@ftomassetti - your turn again

**Comment by arturbosch** [comment]
Here you [go](https://github.com/arturbosch/SmartSmells/blob/master/src/main/groovy/io/gitlab/arturbosch/smartsmells/smells/deadcode/DeadCodeVisitor.groovy)

I have a visitor which finds unused code declared as private (private members, parameters and locale variables). It is not really good code to look at as I was new to groovy and javaparser back then but it does it's job good enought. With SymbolSolver you surely will be able to also detect Unused public members :)

**Comment by sourabhsparkala** [comment]
Thank you so much. This really helped a lot....

Regards
Sourabh
