### ISSUE TITLE
Do we need a mailing-list for users and developers?

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#98]
Hi,
do you think would help to have a mailing list where users could ask for help or let us know about their usages of javaparser?
It could be also useful to discuss about the project (think about discussions about using a style checker, or maybe planning for future directions of the project).
What do you think?
I would suggest to open a google group and refer it in the README.
Opinions?

**Comment by SmiddyPence** [comment]
I think we need something like that for the more conversational type discussions, rather than raising issue.

Don't have a recommendation however.  Although having something at google again, might confuse the co-ordinates somewhat.

**Comment by sebastiankirsch** [comment]
Sounds good to me.

**Comment by ftomassetti** [comment]
Ok, let's see if we can find alternatives. Looking for google groups alternatives I found gitter (https://gitter.im/) which integrates with GitHub and it is used by different projects. However it feels more like a chat and it requires a GitHub account. We could also create a mailing-list or use something like discourse (https://github.com/discourse/discourse/blob/master/docs/INSTALL.md) but we would need to install it.
Other ideas?

**Comment by sebastiankirsch** [comment]
Hm, there are surprisingly few (useful) alternatives out there; never tried
them out tbh. yahoo groups maybe? Although it seems that even for public
groups, messages cannot be seen without logging in - which is quite a
bummer for users...

Federico Tomassetti notifications@github.com schrieb am Mon Feb 16 2015
at 10:58:57 PM:

**Comment by ftomassetti** [comment]
Yes, it was very surprising also for me that there are few alternatives! I would suggest to avoid yahoo groups, users have to create a Yahoo account (I do not know how popular it is where you are, but in the countries where I lived was very rarely used in the last years). Also to read the messages on the web interface you have to login, it could make the content non indexable I think (I could be wrong)

**Comment by matozoid** [comment]
Consider Google+ or... Facebook... - mailing lists are so last century :)

**Comment by matozoid** [comment]
... maybe IRC or another chat tool (Slack seems to come up all the time)

**Comment by SmiddyPence** [comment]
Feel similarly about avoiding additional signups.  Can try gitter in the first instance seems low effort.

**Comment by ftomassetti** [comment]
slack seems cool, I am just now sure how people can join the channel: I tried creating the team "javaparser" but I had two possibilities: 1) specify a domain (so users with a mail from that domain could login) 2) invite manually people. I could not find an option for leaving the channel open

**Comment by sebastiankirsch** [comment]
Gitter seems fine, but the free version only keeps a history of 2 weeks. I
guess that's a no-go...

Federico Tomassetti notifications@github.com schrieb am Tue Feb 17 2015
at 11:35:35 AM:

**Comment by SmiddyPence** [comment]
Let's just try it, will spare the watchers some emails.

Quite a lot of fixes are done under two weeks once someone puts their mind it it.

**Comment by matozoid** [comment]
Gitter seems to work fine, shall we close this issue?

**Comment by ftomassetti** [comment]
I agree we could close it (given I opened it I will close it now). 
We can still reopen it if we change our minds or someone does not agree with Gitter :)

We should just consider (as Sebastian says) that this is great for discussion but it is not storing history for longs, so maybe we should recap decisions taken in Gitter back in the issues.
