### ISSUE TITLE
Save the AST ? 

### ISSUE THREAD

**Issue by lodart** [javaparser/javaparser#983]
Hi ! 
Is it possible to save the AST (couldn't do it with Serialization) to use it later ?
Here's what I have to do : I parse some source code, I gather all Callable Declarations, and I compute all the calls between them (mainly with JSS). Then I analyse stuff. 
But I'd like to avoid all the first part each time I run an analysis.

Thank you !

**Comment by matozoid** [comment]
Why can't you do it with serialization? Because we didn't put `Serializable` on everything?

I guess the most straightforward way would be to use one of the popular XML, JSON, YAML, etc mappers.

But it seems you want to save more than just the AST?

**Comment by lodart** [comment]
Yes, basically, I wan't to save a list of "WrappedNodes" (that contain a JP Node + some infos, like it's "parents" and "children"). I couldn't serialize those as I got NotSerializableException, and I don't wan't them to be transient as I could need them later.
I'll have a look on those mappers, thank you !

**Comment by matozoid** [comment]
Something like Jackson has a pretty simple API, good luck!
