### ISSUE TITLE
Possible bug in Statement.remove where syntatically identical statements appear?

### ISSUE THREAD

**Issue by drdrwhite** [javaparser/javaparser#984]
If I call .remove() on a statement in a block, and there is another syntactically identical statement in the same block, then I get an exception when pretty printing the compilation unit.

Minimal example below.

I note discrepancies between the updated childNodes and statement arrays of the parent block statement object after the remove.

I'm using JavaParser-core 3.2.8 from Maven.

It may be that I haven't understood the semantics of .remove(). Apologies if so. I'm new to JavaParser. Thanks for creating such a fantastic library.

```

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;

class Minimal {

    private static String test = "public class Example {\n" +
            "  public static void example() {\n" +
            "    boolean swapped;\n" +
            "    swapped=false;\n" +
            "    swapped=false;\n" +
            "  }\n" +
            "}\n";

    public static void main(String args[]) throws Exception {
        CompilationUnit unit = JavaParser.parse(test);
        // remove the second swapped=false
        Node target = unit.getChildNodes().get(0).getChildNodes().get(1).getChildNodes().get(2).getChildNodes().get(2);
        target.remove();
        System.out.println(unit.toString()); // throws exception
    }

}
```

**Comment by codykenb** [comment]
[EqualsVisitor.nodeEquals() line: 100](https://github.com/javaparser/javaparser/blob/javaparser-parent-3.2.8/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/EqualsVisitor.java#L100) checks if the nodes are equal, they are not, but the function continues to check all children recursively and eventually returns true.

If the nodes are not the same, should nodeEquals() return false immediately?

Could line 100-102:
```
        if (n == n2) {
            return true;
        }
```
be replaced with:
```
        if (n != n2) {
            return false;
        }
```
?

If the root node's are the same, continue checking equality on down the tree. 
If the root nodes are not the same, no point descending, just return false.

**Comment by matozoid** [comment]
Ouch, that's a nasty mix of using `==` and `equals`. Debugging...

**Comment by matozoid** [comment]
@drdrwhite - thanks for the excellent sample code! It has now become a unit test :-) See #986

**Comment by matozoid** [comment]
@codykenb - that would be true if the `EqualsVisitor` compared on object identity - but then you could simply do `a==b` on any two nodes and get your answer. `EqualsVisitor` gives you a comparison on content, not identity. `a==4` and `a==4` are equal according to this visitor, even if they come from completely different source files.

**Comment by matozoid** [comment]
Oh, and thanks for the compliment, @drdrwhite :)

**Comment by drdrwhite** [comment]
Thanks very much for addressing this so quickly @matozoid 

When is this likely to be released to Maven? I ask as this was discovered by the [Gin Project](https://github.com/drdrwhite/gin) and we have a PR blocked on it.

...btw, the Gin project is a research project that in essence searches code spaces for optimisations... these methods tend to generate pretty funky code, so we will be giving JavaParser a thorough test!

**Comment by ftomassetti** [comment]
I think it is already in version 3.2.9 which was released yesterday

**Comment by matozoid** [comment]
Looking forward to hopefully not too many bug reports, @drdrwhite ;-)
