### ISSUE TITLE
Organize a miniconference

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#985]
As suggested in #968, it would be nice to have (virtual) meetings to coordinate things a bit more.

**Comment by ftomassetti** [comment]
Ideally I would like to hear from users. The problem is that is hard to reach them.

Then I would like to hear what we think are our priorities: what we think is needed, what we are excited about, what we think we can build in the next six months or so, etc.

**Comment by matozoid** [comment]
How about we do this next February at... FOSDEM or so? @ftomassetti

**Comment by ftomassetti** [comment]
It would work for me. What did you have in mind? Who should we invite?

**Comment by matozoid** [comment]
Pick a date and place and advertise on Twitter and the site a bit? Do a retrospective kind of event with whoever shows up?

**Comment by ftomassetti** [comment]
We could write on twitter something like "@matozoid & @ftomasse will be both in Bruxelles for the FOSDEM. Someone wants to meet and talk about #javaparser?"

Aside from this we could put a banner on the website

**Comment by matozoid** [comment]
For example, do you think we should offer something like some hacking or a presentation?

**Comment by matozoid** [comment]
@ftomassetti I wouldn't know who to invite except mr. RedHat.

**Comment by ftomassetti** [comment]
Me neither, I think we can try to see on twitter if someone wants to join us

**Comment by matozoid** [comment]
@ftomassetti you can write a Twitter message, you're the famous one ;-)

**Comment by matozoid** [comment]
So did we have a mini conference? :-D

**Comment by ftomassetti** [comment]
Yes, a short one :D

**Comment by matozoid** [comment]
So we can open a new issue if we want another :-)
