### ISSUE TITLE
How to get parameter String's package name "java.lang"?

### ISSUE THREAD

**Issue by anql** [javaparser/javaparser#987]
Sample Java Code:
``` Java
public class Main {

    public void print(String msg) {
        //...
    }
}

```

I can get String class 's SimpleName from 'com.github.javaparser.ast.body.Parameter'.
But how to get String's package name "java.lang"?

**Comment by matozoid** [comment]
Please take a look at the Java symbol solver project.

**Comment by anql** [comment]
Thank you!
