### ISSUE TITLE
The parent of the javaparser-core-generators is not updated

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javaparser#992]
It is 3.2.9-SNAPSHOT. Idealy we should change it automatically

**Comment by matozoid** [comment]
Hmmm, what I can do is make them part of the build again, but take out the part where they are run during the build. Then we do the running from the scripts, or with a special profile or so.

**Comment by matozoid** [comment]
Let's not tag stuff "easy" that we don't want new people to do :-D

**Comment by ftomassetti** [comment]
Right, I will use the tag easy more carefully
